srcFile = "HyProBox.cpp";
ipaths = {'-I/Applications/MATLAB_R2018b.app/extern/include',...
    '-I/Users/marta/hypro/build/resources/antlr_build/include/antlr4-runtime',...
    '-I/Users/marta/hypro/build/resources/antlr_build/include/antlr4-runtime/misc',...
    '-I/Users/marta/hypro/build/resources/antlr_build/include/antlr4-runtime/atn',...
    '-I/Users/marta/hypro/build/resources/antlr_build/include/antlr4-runtime/dfa',...
    '-I/Users/marta/hypro/build/resources/antlr_build/include/antlr4-runtime/tree',...
    '-I/Users/marta/hypro/build/resources/antlr_build/include/antlr4-runtime/support',...
    '-I/Users/marta/hypro/src','-I/usr/local/opt/llvm/include','-I/Users/marta/carl/src',...
    '-I/usr/local/include','-I/Users/marta/carl/resources/include',...
    '-I/usr/local/opt/llvm/include/c++/v1/ -DGTEST_USE_OWN_TR1_TUPLE=1 -std=c++17 -stdlib=libc++',...
    '-L/usr/local/opt/llvm/lib','-L/Users/marta/hypro/build','-lhypro',...
    'LDFLAGS=$LDFLAGS -Wl -rpath /Users/marta/hypro/build';};
    
mex -setup c++;
mex('-v',ipaths{:},'CC=/usr/local/opt/llvm/bin/clang','CXX=/usr/local/opt/llvm/bin/clang++','COMPFLAGS=$COMPFLAGS -std=c++17', 'CXXFLAGS=\$CXXFLAGS -std=c++17',srcFile)