#pragma once

#include "../../util/type_handling/better_enums/enum_default_ctor.h"

namespace hypro {

BETTER_ENUM( TRACING_STRATEGY, int, DEFAULT,
			 SINGLESTEP, BINARYSEARCH, REMEMBERING_SEARCH, UNSAT_CORE, FULL_REUSED_PREDICATE, REUSED_PREDICATE_WITH_LP
);

BETTER_ENUM( PREDICATE_TRACING_ORIGIN, int, DEFAULT,
	FIRST, LAST, MIDDLE, ALL
);

BETTER_ENUM( COUNTEREXAMPLE_STRATEGY, int, DEFAULT,
			 Z3_BASIC, RANDOM, Z3_SMALL_REPRESENTATION, REMEMBERING_COUNTEREXAMPLES
);

BETTER_ENUM( REFINEMENT_TYPE, int, DEFAULT,
			 AVOIDANT, FULL, EXACT_SOURCES, REMEMBERING_SOURCES, PATH_WISE_ORIGINS
);

}  // namespace hypro
