HyPro: /home/travis/build/hypro/hypro/src/hypro/util/adaptions_eigen/adaptions_eigen.h File Reference
adaptions_eigen.h File Reference
#include "../../config.h"
#include "../../types.h"
#include "transformation.h"
#include <carl/numbers/numbers.h>
#include <eigen3/Eigen/Dense>
#include <eigen3/Eigen/Eigenvalues>
#include <functional>
#include <iosfwd>
#include <limits>
#include <eigen3/unsupported/Eigen/src/MatrixFunctions/MatrixExponential.h>
Classes
struct std::hash< hypro::vector_t< Number > >
struct std::hash< hypro::matrix_t< Number > >
Namespaces
Eigen
hypro
General context interface to set up a reachability worker.
Functions
template<typename Number >
bool Eigen::operator< (const hypro::vector_t< Number > &lhs, const hypro::vector_t< Number > &rhs)
template<typename Number >
bool Eigen::operator<= (const hypro::vector_t< Number > &lhs, const hypro::vector_t< Number > &rhs)
template<typename Number >
bool Eigen::operator> (const hypro::vector_t< Number > &lhs, const hypro::vector_t< Number > &rhs)
template<typename Number >
bool Eigen::operator>= (const hypro::vector_t< Number > &lhs, const hypro::vector_t< Number > &rhs)
template<typename Number >
std::size_t Eigen::VectorHashValue (const hypro::vector_t< Number > &pVector)
template<typename Number >
std::size_t Eigen::MatrixHashValue (const hypro::matrix_t< Number > &pMatrix)
template<typename Number >
bool Eigen::operator== (const hypro::vector_t< Number > &lhs, const hypro::vector_t< Number > &rhs)
template<typename Number >
bool Eigen::operator!= (const hypro::vector_t< Number > &lhs, const hypro::vector_t< Number > &rhs)
template<typename Number >
bool Eigen::operator== (const hypro::matrix_t< Number > &lhs, const hypro::matrix_t< Number > &rhs)
template<typename Number >
bool Eigen::operator!= (const hypro::matrix_t< Number > &lhs, const hypro::matrix_t< Number > &rhs)
template<typename Number >
std::ostream & Eigen::operator<< (std::ostream &_out, const hypro::vector_t< Number > &in)
template<typename Number >
std::ostream & Eigen::operator<< (std::ostream &_out, const hypro::matrix_t< Number > &in)
template<typename Number >
Number Eigen::norm (const hypro::vector_t< Number > &in, bool roundUp=true)
template<>
double Eigen::norm (const hypro::vector_t< double > &in, bool roundUp)
template<typename Number >
Number Eigen::inftyNorm (const hypro::matrix_t< Number > &in)
template<typename Number >
hypro::matrix_t< Number > Eigen::abs (const hypro::matrix_t< Number > &in)
template<typename From , typename To >
matrix_t< To > hypro::convert (const matrix_t< From > &_mat)
template<typename From , typename To >
Eigen::DiagonalMatrix< To, Eigen::Dynamic > hypro::convert (const Eigen::DiagonalMatrix< From, Eigen::Dynamic > &_mat)
template<typename Number >
vector_t< Number > hypro::normalize (const vector_t< Number > &in)
template<typename Number >
vector_t< Number > hypro::project (const vector_t< Number > &in, const std::vector< std::size_t > &dimensions)
template<typename Number >
vector_t< Number > hypro::scalarProjection (const vector_t< Number > &source, const vector_t< Number > &target)
template<typename Number >
int hypro::effectiveDimension (const std::vector< vector_t< Number >> &vertices)
template<typename Number >
std::pair< bool, Number > hypro::linearDependent (const vector_t< Number > &lhs, const vector_t< Number > &rhs)
template<typename Number , carl::DisableIf< std::is_same< Number, double >> = carl::dummy>
vector_t< Number > hypro::reduceNumberRepresentation (const vector_t< Number > &in)
template<typename Number >
std::string hypro::createCode (const matrix_t< Number > &in, unsigned index=0)
template<typename Number >
matrix_t< Number > hypro::matrixExponential (const matrix_t< Number > &inMatrix)
Computes the matrix exponential via conversion to double and then using eigen::exp.
template<typename Number >
std::string hypro::createCode (const vector_t< Number > &in, unsigned index=0)
template<typename Number >
bool hypro::satisfiesIneqation (const vector_t< Number > &constraint, Number constant, const vector_t< Number > &point)
mpq_class std::abs (const mpq_class &x)
mpq_class std::sqrt (const mpq_class &x)
mpq_class std::max (const mpq_class &x, const mpq_class &y)
Function Documentation
mpq_class std::abs (const mpq_class & x) inline
Definition at line 424 of file adaptions_eigen.h.
mpq_class std::max (const mpq_class & x, const mpq_class & y) inline
Definition at line 430 of file adaptions_eigen.h.
References std::max().
Referenced by std::max().
mpq_class std::sqrt (const mpq_class & x) inline
Definition at line 427 of file adaptions_eigen.h.
References std::sqrt().
Referenced by std::sqrt().