HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/globalFunctions/checkIntervals.m File Reference
checkIntervals.m File Reference
Functions
if ismatrix (intervals)%Check if number of columns is two[rows
error ("checkIntervals: Lower bound is larger than upper bound.")
error ("chekIntervals: Argument is not a n x 2 matrix.")
error ("checkIntervals: Argument is not a n x 2 matrix.")
Variables
function out
if cols = size(intervals)
Function Documentation
error ("checkIntervals: Lower bound is larger than upper bound.")
error ("chekIntervals: Argument is not a n x 2 matrix.")
error ("checkIntervals: Argument is not a n x 2 matrix.")
if ismatrix (intervals)
Variable Documentation
if cols = size(intervals)
Definition at line 5 of file checkIntervals.m.
Referenced by hypro::reachability::computeFirstSegment(), ObjectHandle::convert2Matlab(), ObjectHandle::mIntervals2Hypro(), ObjectHandle::mLocCondMap2Hypro(), ObjectHandle::mMatrix2Hypro(), ObjectHandle::mPoint2Hypro(), ObjectHandle::mPointsVector2Hypro(), ObjectHandle::mVectorOfVectors2Hypro(), MReach::setSettings(), hypro::glpk_context::updateConstraints(), and vector2Matlab().
end else out
Initial value:
= checkIntervals(intervals)
    out = 1
Definition at line 1 of file checkIntervals.m.