HyPro: hypro::ExactQuickhull::FacetSpace< Number, Euclidian > Class Template Reference
hypro::ExactQuickhull::FacetSpace< Number, Euclidian > Class Template Reference
Public Member Functions
FacetSpace (pointVector_t &points, dimension_t dimension)
Facet & insertNew ()
void insertTrivialFacet (Number const scalar)
void insertReduced (Facet const &other, dimension_t newDimension, dimension_t reducedDimension)
size_t insertConePart (facet_ind_t other_i, point_ind_t visiblePoint, size_t replaceAt)
void computeNormal (Facet &facet)
void validateFacet (Facet &facet, point_t const &containedPoint, Facet const &adjacentFacet)
void validateVertexContainment (Facet &facet)
bool tryAddToOutsideSet (Facet &facet, point_ind_t point_i)
void establishNeighborhood (facet_ind_t facet_i, facet_ind_t other_i)
template<typename UnaryPredicate >
facet_ind_t findFacet (UnaryPredicate predicate)
void removeCoplanarFacets ()
void compressVector ()
void endModificationPhase ()
void deleteFacet (facet_ind_t facet_i)
std::string printAll ()
std::string printFacet (Facet const &facet)
void containsVertices (Facet &facet)
void containsVertices (Facet &facet, Facet &currentFacet, bitset_t &visited)
void containsAllPoints (Facet &facet, bool inverted=false)
template<typename UnaryPredicate >
ExactQuickhull< Number, Euclidian >::facet_ind_t findFacet (UnaryPredicate predicate)
Public Attributes
size_t firstInserted
size_t firstDeleted = 0
std::vector< facet_ind_t > deletedPositions {}
facetVector_t facets {}
Detailed Description
template<typename Number, bool Euclidian>
class hypro::ExactQuickhull::FacetSpace< Number, Euclidian >
Definition at line 10 of file FacetSpace.h.
Constructor & Destructor Documentation
template<typename Number , bool Euclidian> hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::FacetSpace (pointVector_t & points, dimension_t dimension) inline explicit
Definition at line 21 of file FacetSpace.h.
Member Function Documentation
template<typename Number , bool Euclidian> void hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::compressVector ()
Definition at line 206 of file FacetSpace.tpp.
template<typename Number , bool Euclidian> void hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::computeNormal (Facet & facet)
Definition at line 86 of file FacetSpace.tpp.
References hypro::ExactQuickhull::Facet< Number, Euclidian >::mNormal, hypro::ExactQuickhull::Facet< Number, Euclidian >::mOffset, and hypro::ExactQuickhull::Facet< Number, Euclidian >::mVertices.
template<typename Number , bool Euclidian> void hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::containsAllPoints (Facet & facet, bool inverted = false)
Definition at line 284 of file FacetSpace.tpp.
References hypro::ExactQuickhull::Facet< Number, Euclidian >::invert(), hypro::ExactQuickhull::Facet< Number, Euclidian >::mOutsideSet, and hypro::ExactQuickhull::Facet< Number, Euclidian >::visible().
template<typename Number , bool Euclidian> void hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::containsVertices (Facet & facet)
Definition at line 260 of file FacetSpace.tpp.
template<typename Number , bool Euclidian> void hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::containsVertices (Facet & facet, Facet & currentFacet, bitset_t & visited)
Definition at line 266 of file FacetSpace.tpp.
References hypro::ExactQuickhull::Facet< Number, Euclidian >::mNeighbors, hypro::ExactQuickhull::Facet< Number, Euclidian >::mVertices, and hypro::ExactQuickhull::Facet< Number, Euclidian >::visible().
template<typename Number , bool Euclidian> void hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::deleteFacet (facet_ind_t facet_i)
Definition at line 228 of file FacetSpace.tpp.
template<typename Number , bool Euclidian> void hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::endModificationPhase ()
Definition at line 222 of file FacetSpace.tpp.
template<typename Number , bool Euclidian> void hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::establishNeighborhood (facet_ind_t facet_i, facet_ind_t other_i)
Definition at line 148 of file FacetSpace.tpp.
References hypro::ExactQuickhull::Facet< Number, Euclidian >::mNeighbors, and hypro::ExactQuickhull::Facet< Number, Euclidian >::mVertices.
template<typename Number , bool Euclidian> template<typename UnaryPredicate > facet_ind_t hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::findFacet (UnaryPredicate predicate)
template<typename Number , bool Euclidian> template<typename UnaryPredicate > ExactQuickhull<Number, Euclidian>::facet_ind_t hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::findFacet (UnaryPredicate predicate)
Definition at line 192 of file FacetSpace.tpp.
template<typename Number , bool Euclidian> size_t hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::insertConePart (facet_ind_t other_i, point_ind_t visiblePoint, size_t replaceAt)
Inserts a new facet that is defined by an existing one, except that the visiblePoint replaces the point at the specified index.
Parameters
other The existing facet to construct a new one from.
visiblePoint The point to insert.
insertAt The index to insert the visiblePoint at.
containedPoint A point to use for orientation.
Returns
The index where the visiblePoint was inserted.
Definition at line 76 of file FacetSpace.tpp.
template<typename Number , bool Euclidian> ExactQuickhull< Number, Euclidian >::Facet & hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::insertNew ()
Definition at line 11 of file FacetSpace.tpp.
template<typename Number , bool Euclidian> void hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::insertReduced (Facet const & other, dimension_t newDimension, dimension_t reducedDimension)
Inserts a new facet in the given dimension, from a lower dimensional facet, by setting 'reducedDimension' to 0.
Parameters
other The facet to construct the new one from.
newDimension The dimension of the new facet.
reducedDimension The dimension to set to 0 in the new facet.
Definition at line 31 of file FacetSpace.tpp.
References hypro::ExactQuickhull::Facet< Number, Euclidian >::mNormal, hypro::ExactQuickhull::Facet< Number, Euclidian >::mOffset, and hypro::ExactQuickhull::Facet< Number, Euclidian >::mVertices.
template<typename Number , bool Euclidian> void hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::insertTrivialFacet (Number const scalar)
Inserts a one dimensional facet that represents an interval bound at the given scalar.
Parameters
scalar The interval bound.
Definition at line 23 of file FacetSpace.tpp.
template<typename Number , bool Euclidian> std::string hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::printAll ()
Definition at line 234 of file FacetSpace.tpp.
template<typename Number , bool Euclidian> std::string hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::printFacet (Facet const & facet)
Definition at line 243 of file FacetSpace.tpp.
References hypro::ExactQuickhull::Facet< Number, Euclidian >::mNormal, and hypro::ExactQuickhull::Facet< Number, Euclidian >::mOffset.
template<typename Number , bool Euclidian> void hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::removeCoplanarFacets ()
Definition at line 197 of file FacetSpace.tpp.
References hypro::ExactQuickhull::Facet< Number, Euclidian >::mNormal, and hypro::ExactQuickhull::Facet< Number, Euclidian >::mOffset.
template<typename Number , bool Euclidian> bool hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::tryAddToOutsideSet (Facet & facet, point_ind_t point_i)
Definition at line 132 of file FacetSpace.tpp.
References hypro::ExactQuickhull::Facet< Number, Euclidian >::distance(), hypro::ExactQuickhull::Facet< Number, Euclidian >::furthestPoint, hypro::ExactQuickhull::Facet< Number, Euclidian >::furthestPointDistance, and hypro::ExactQuickhull::Facet< Number, Euclidian >::mOutsideSet.
template<typename Number , bool Euclidian> void hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::validateFacet (Facet & facet, point_t const & containedPoint, Facet const & adjacentFacet)
Definition at line 124 of file FacetSpace.tpp.
References hypro::ExactQuickhull::Facet< Number, Euclidian >::setOrientation().
template<typename Number , bool Euclidian> void hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::validateVertexContainment (Facet & facet)
Member Data Documentation
template<typename Number , bool Euclidian> std::vector<facet_ind_t> hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::deletedPositions {}
Definition at line 17 of file FacetSpace.h.
template<typename Number , bool Euclidian> facetVector_t hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::facets {}
Definition at line 19 of file FacetSpace.h.
template<typename Number , bool Euclidian> size_t hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::firstDeleted = 0
Definition at line 16 of file FacetSpace.h.
template<typename Number , bool Euclidian> size_t hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::firstInserted
Definition at line 15 of file FacetSpace.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/quickhull/quickhull_exact/FacetSpace.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/quickhull/quickhull_exact/FacetSpace.tpp