HyPro: hypro::SupportFunctionContent< Number, Setting > Class Template Reference
hypro::SupportFunctionContent< Number, Setting > Class Template Reference
Class for support function content.
Public Member Functions
virtual ~SupportFunctionContent ()
std::shared_ptr< SupportFunctionContent< Number, Setting > > & operator= (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &_orig)
EvaluationResult< Number > evaluate (const vector_t< Number > &_direction, bool useExact) const
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &_directions, bool useExact) const
std::size_t dimension () const
SF_TYPE type () const
unsigned depth () const
unsigned operationCount () const
std::shared_ptr< SupportFunctionContent< Number, Setting > > getThis () const
unsigned multiplicationsPerEvaluation () const
void forceLinTransReduction ()
Point< Number > supremumPoint () const
std::vector< std::size_t > collectProjections () const
std::vector< std::size_t > collectProjectionsIterative () const
sumContent< Number, Setting > * summands () const
scaleContent< Number, Setting > * scaleParameters () const
trafoContent< Number, Setting > * linearTrafoParameters () const
unionContent< Number, Setting > * unionParameters () const
intersectionContent< Number, Setting > * intersectionParameters () const
projectionContent< Number, Setting > * projectionParameters () const
PolytopeSupportFunction< Number, Setting > * polytope () const
BoxSupportFunction< Number, Setting > * box () const
BallSupportFunction< Number > * ball () const
EllipsoidSupportFunction< Number > * ellipsoid () const
std::shared_ptr< SupportFunctionContent< Number, Setting > > project (const std::vector< std::size_t > &dimensions) const
std::shared_ptr< SupportFunctionContent< Number, Setting > > affineTransformation (const matrix_t< Number > &A, const vector_t< Number > &b) const
std::shared_ptr< SupportFunctionContent< Number, Setting > > minkowskiSum (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &_rhs) const
std::shared_ptr< SupportFunctionContent< Number, Setting > > intersect (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &_rhs) const
bool contains (const Point< Number > &_point) const
bool contains (const vector_t< Number > &_point) const
std::shared_ptr< SupportFunctionContent< Number, Setting > > unite (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &_rhs) const
std::shared_ptr< SupportFunctionContent< Number, Setting > > scale (const Number &_factor=1) const
void reduceRepresentation ()
bool empty () const
void cleanUp () const
void print () const
bool checkTreeValidity () const
std::size_t getDotRepresentation (std::size_t startIndex, std::string &nodes, std::string &transitions) const
Static Public Member Functions
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE _type, matrix_t< Number > _shapeMatrix)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE _type, Number _radius, unsigned dimension)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE _type, const matrix_t< Number > &_directions, const vector_t< Number > &_distances, bool overrideReduction=false)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE _type, const std::vector< carl::Interval< Number >> &inbox)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE _type, const std::vector< Halfspace< Number >> &_planes)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE _type, const std::vector< Point< Number >> &_points)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE type, const std::shared_ptr< SupportFunctionContent< Number, Setting >> &lhs, const std::shared_ptr< SupportFunctionContent< Number, Setting >> &rhs)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE type, const std::vector< std::shared_ptr< SupportFunctionContent< Number, Setting >>> &rhs)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &orig, const matrix_t< Number > &constraints, const vector_t< Number > &constants)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &orig, Number factor)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &orig, const std::vector< std::size_t > &dimensions)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &orig)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > unite (const std::vector< std::shared_ptr< SupportFunctionContent< Number, Setting >>> &_rhs)
Friends
template<typename N , typename C , typename S >
class SupportFunctionT
std::ostream & operator<< (std::ostream &lhs, const std::shared_ptr< SupportFunctionContent< Number, Setting >> &rhs)
Detailed Description
template<typename Number, typename Setting>
class hypro::SupportFunctionContent< Number, Setting >
Class for support function content.
Template Parameters
Number The used number type.
Definition at line 35 of file PolytopeSupportFunction.h.
Constructor & Destructor Documentation
template<typename Number , typename Setting > hypro::SupportFunctionContent< Number, Setting >::~SupportFunctionContent () virtual
Definition at line 395 of file SupportFunctionContent.tpp.
References hypro::BOX, hypro::ELLIPSOID, hypro::SupportFunctionContent< Number, Setting >::ellipsoid(), hypro::INFTY_BALL, hypro::INTERSECT, hypro::SupportFunctionContent< Number, Setting >::linearTrafoParameters(), hypro::LINTRAFO, hypro::NONE, hypro::POLY, hypro::PROJECTION, hypro::SCALE, hypro::SUM, hypro::TWO_BALL, and hypro::UNITE.
Member Function Documentation
template<typename Number , typename Setting > std::shared_ptr< SupportFunctionContent< Number, Setting > > hypro::SupportFunctionContent< Number, Setting >::affineTransformation (const matrix_t< Number > & A, const vector_t< Number > & b) const
Definition at line 1462 of file SupportFunctionContent.tpp.
References hypro::SupportFunctionContent< Number, Setting >::create(), and hypro::SupportFunctionContent< Number, Setting >::getThis().
template<typename Number , typename Setting > BallSupportFunction< Number > * hypro::SupportFunctionContent< Number, Setting >::ball () const
Definition at line 1451 of file SupportFunctionContent.tpp.
References hypro::INFTY_BALL, and hypro::TWO_BALL.
Referenced by hypro::SupportFunctionContent< Number, Setting >::contains(), hypro::SupportFunctionContent< Number, Setting >::empty(), hypro::SupportFunctionContent< Number, Setting >::multiEvaluate(), and hypro::SupportFunctionContent< Number, Setting >::supremumPoint().
template<typename Number , typename Setting > BoxSupportFunction< Number, Setting > * hypro::SupportFunctionContent< Number, Setting >::box () const
Definition at line 1439 of file SupportFunctionContent.tpp.
References hypro::BOX.
Referenced by hypro::SupportFunctionContent< Number, Setting >::contains(), hypro::SupportFunctionContent< Number, Setting >::empty(), hypro::SupportFunctionContent< Number, Setting >::multiEvaluate(), and hypro::SupportFunctionContent< Number, Setting >::supremumPoint().
template<typename Number, typename Setting> bool hypro::SupportFunctionContent< Number, Setting >::checkTreeValidity () const inline
Definition at line 385 of file SupportFunctionContent.h.
References hypro::BOX, hypro::ELLIPSOID, hypro::INFTY_BALL, hypro::INTERSECT, hypro::LINTRAFO, hypro::NONE, hypro::POLY, hypro::PROJECTION, hypro::SCALE, hypro::SUM, hypro::TWO_BALL, hypro::UNITE, and hypro::ZONOTOPE.
Referenced by hypro::SupportFunctionContent< Number, Setting >::empty(), hypro::SupportFunctionContent< Number, Setting >::forceLinTransReduction(), hypro::SupportFunctionContent< Number, Setting >::multiEvaluate(), hypro::SupportFunctionContent< Number, Setting >::operator=(), and hypro::SupportFunctionContent< Number, Setting >::supremumPoint().
template<typename Number , typename Setting > void hypro::SupportFunctionContent< Number, Setting >::cleanUp () const
Definition at line 1657 of file SupportFunctionContent.tpp.
References hypro::BOX, hypro::ELLIPSOID, hypro::SupportFunctionContent< Number, Setting >::getThis(), hypro::INFTY_BALL, hypro::INTERSECT, hypro::LINTRAFO, hypro::NONE, hypro::POLY, hypro::PROJECTION, hypro::SCALE, hypro::SUM, hypro::TWO_BALL, hypro::UNITE, and hypro::ZONOTOPE.
template<typename Number , typename Setting > std::vector< std::size_t > hypro::SupportFunctionContent< Number, Setting >::collectProjections () const
Definition at line 1214 of file SupportFunctionContent.tpp.
References hypro::BOX, hypro::ELLIPSOID, hypro::SupportFunctionContent< Number, Setting >::getThis(), hypro::INFTY_BALL, hypro::INTERSECT, hypro::LINTRAFO, hypro::NONE, hypro::POLY, hypro::PROJECTION, hypro::SCALE, hypro::SUM, hypro::swap(), hypro::TWO_BALL, hypro::UNITE, and hypro::ZONOTOPE.
template<typename Number, typename Setting> std::vector<std::size_t> hypro::SupportFunctionContent< Number, Setting >::collectProjectionsIterative () const
template<typename Number , typename Setting > bool hypro::SupportFunctionContent< Number, Setting >::contains (const Point< Number > & _point) const
Definition at line 1480 of file SupportFunctionContent.tpp.
References hypro::NONE, and hypro::Point< Number >::rawCoordinates().
template<typename Number , typename Setting > bool hypro::SupportFunctionContent< Number, Setting >::contains (const vector_t< Number > & _point) const
Definition at line 1486 of file SupportFunctionContent.tpp.
References hypro::SupportFunctionContent< Number, Setting >::ball(), hypro::BOX, hypro::SupportFunctionContent< Number, Setting >::box(), defaultTemplateDirectionCount, hypro::SupportFunctionContent< Number, Setting >::dimension(), hypro::ELLIPSOID, hypro::SupportFunctionContent< Number, Setting >::ellipsoid(), hypro::INFTY_BALL, hypro::INTERSECT, hypro::SupportFunctionContent< Number, Setting >::intersectionParameters(), hypro::SupportFunctionContent< Number, Setting >::linearTrafoParameters(), hypro::LINTRAFO, hypro::NONE, hypro::POLY, hypro::SupportFunctionContent< Number, Setting >::polytope(), hypro::PROJECTION, hypro::SupportFunctionContent< Number, Setting >::projectionParameters(), hypro::SCALE, hypro::SupportFunctionContent< Number, Setting >::scaleParameters(), hypro::SUM, hypro::SupportFunctionContent< Number, Setting >::summands(), hypro::EvaluationResult< Number >::supportValue, hypro::TWO_BALL, hypro::SupportFunctionContent< Number, Setting >::unionParameters(), and hypro::UNITE.
template<typename Number, typename Setting> static std::shared_ptr<SupportFunctionContent<Number, Setting> > hypro::SupportFunctionContent< Number, Setting >::create (SF_TYPE _type, matrix_t< Number > _shapeMatrix) inline static
Definition at line 227 of file SupportFunctionContent.h.
Referenced by hypro::SupportFunctionContent< Number, Setting >::affineTransformation(), hypro::SupportFunctionContent< Number, Setting >::intersect(), hypro::SupportFunctionContent< Number, Setting >::minkowskiSum(), hypro::SupportFunctionContent< Number, Setting >::project(), hypro::SupportFunctionContent< Number, Setting >::scale(), and hypro::SupportFunctionContent< Number, Setting >::unite().
template<typename Number, typename Setting> static std::shared_ptr<SupportFunctionContent<Number, Setting> > hypro::SupportFunctionContent< Number, Setting >::create (SF_TYPE _type, Number _radius, unsigned dimension) inline static
Definition at line 234 of file SupportFunctionContent.h.
template<typename Number, typename Setting> static std::shared_ptr<SupportFunctionContent<Number, Setting> > hypro::SupportFunctionContent< Number, Setting >::create (SF_TYPE _type, const matrix_t< Number > & _directions, const vector_t< Number > & _distances, bool overrideReduction = false) inline static
Definition at line 241 of file SupportFunctionContent.h.
template<typename Number, typename Setting> static std::shared_ptr<SupportFunctionContent<Number, Setting> > hypro::SupportFunctionContent< Number, Setting >::create (SF_TYPE _type, const std::vector< carl::Interval< Number >> & inbox) inline static
Definition at line 249 of file SupportFunctionContent.h.
template<typename Number, typename Setting> static std::shared_ptr<SupportFunctionContent<Number, Setting> > hypro::SupportFunctionContent< Number, Setting >::create (SF_TYPE _type, const std::vector< Halfspace< Number >> & _planes) inline static
Definition at line 257 of file SupportFunctionContent.h.
template<typename Number, typename Setting> static std::shared_ptr<SupportFunctionContent<Number, Setting> > hypro::SupportFunctionContent< Number, Setting >::create (SF_TYPE _type, const std::vector< Point< Number >> & _points) inline static
Definition at line 265 of file SupportFunctionContent.h.
template<typename Number, typename Setting> static std::shared_ptr<SupportFunctionContent<Number, Setting> > hypro::SupportFunctionContent< Number, Setting >::create (SF_TYPE type, const std::shared_ptr< SupportFunctionContent< Number, Setting >> & lhs, const std::shared_ptr< SupportFunctionContent< Number, Setting >> & rhs) inline static
Definition at line 272 of file SupportFunctionContent.h.
References hypro::sumContent< Number, Setting >::lhs, and hypro::sumContent< Number, Setting >::rhs.
template<typename Number, typename Setting> static std::shared_ptr<SupportFunctionContent<Number, Setting> > hypro::SupportFunctionContent< Number, Setting >::create (SF_TYPE type, const std::vector< std::shared_ptr< SupportFunctionContent< Number, Setting >>> & rhs) inline static
Definition at line 279 of file SupportFunctionContent.h.
References hypro::sumContent< Number, Setting >::rhs.
template<typename Number, typename Setting> static std::shared_ptr<SupportFunctionContent<Number, Setting> > hypro::SupportFunctionContent< Number, Setting >::create (const std::shared_ptr< SupportFunctionContent< Number, Setting >> & orig, const matrix_t< Number > & constraints, const vector_t< Number > & constants) inline static
Definition at line 286 of file SupportFunctionContent.h.
References hypro::LINTRAFO.
template<typename Number, typename Setting> static std::shared_ptr<SupportFunctionContent<Number, Setting> > hypro::SupportFunctionContent< Number, Setting >::create (const std::shared_ptr< SupportFunctionContent< Number, Setting >> & orig, Number factor) inline static
Definition at line 295 of file SupportFunctionContent.h.
References hypro::SCALE.
template<typename Number, typename Setting> static std::shared_ptr<SupportFunctionContent<Number, Setting> > hypro::SupportFunctionContent< Number, Setting >::create (const std::shared_ptr< SupportFunctionContent< Number, Setting >> & orig, const std::vector< std::size_t > & dimensions) inline static
Definition at line 302 of file SupportFunctionContent.h.
References hypro::PROJECTION.
template<typename Number, typename Setting> static std::shared_ptr<SupportFunctionContent<Number, Setting> > hypro::SupportFunctionContent< Number, Setting >::create (const std::shared_ptr< SupportFunctionContent< Number, Setting >> & orig) inline static
Definition at line 309 of file SupportFunctionContent.h.
template<typename Number , typename Setting > unsigned hypro::SupportFunctionContent< Number, Setting >::depth () const
Definition at line 892 of file SupportFunctionContent.tpp.
References hypro::NONE.
template<typename Number , typename Setting > std::size_t hypro::SupportFunctionContent< Number, Setting >::dimension () const
Definition at line 881 of file SupportFunctionContent.tpp.
References hypro::NONE.
Referenced by hypro::SupportFunctionContent< Number, Setting >::contains(), and hypro::SupportFunctionContent< Number, Setting >::empty().
template<typename Number , typename Setting > EllipsoidSupportFunction< Number > * hypro::SupportFunctionContent< Number, Setting >::ellipsoid () const
Definition at line 1445 of file SupportFunctionContent.tpp.
References hypro::ELLIPSOID.
Referenced by hypro::SupportFunctionContent< Number, Setting >::contains(), hypro::SupportFunctionContent< Number, Setting >::empty(), hypro::SupportFunctionContent< Number, Setting >::multiEvaluate(), and hypro::SupportFunctionContent< Number, Setting >::~SupportFunctionContent().
template<typename Number , typename Setting > bool hypro::SupportFunctionContent< Number, Setting >::empty () const
Definition at line 1587 of file SupportFunctionContent.tpp.
References hypro::SupportFunctionContent< Number, Setting >::ball(), hypro::BOX, hypro::SupportFunctionContent< Number, Setting >::box(), hypro::SupportFunctionContent< Number, Setting >::checkTreeValidity(), defaultTemplateDirectionCount, hypro::SupportFunctionContent< Number, Setting >::dimension(), hypro::ELLIPSOID, hypro::SupportFunctionContent< Number, Setting >::ellipsoid(), hypro::INFTY, hypro::INFTY_BALL, hypro::INTERSECT, hypro::SupportFunctionContent< Number, Setting >::intersectionParameters(), hypro::SupportFunctionContent< Number, Setting >::linearTrafoParameters(), hypro::LINTRAFO, hypro::NONE, hypro::POLY, hypro::SupportFunctionContent< Number, Setting >::polytope(), hypro::PROJECTION, hypro::SupportFunctionContent< Number, Setting >::projectionParameters(), hypro::SCALE, hypro::SupportFunctionContent< Number, Setting >::scaleParameters(), hypro::SUM, hypro::SupportFunctionContent< Number, Setting >::summands(), hypro::TWO_BALL, hypro::SupportFunctionContent< Number, Setting >::unionParameters(), and hypro::UNITE.
template<typename Number , typename Setting > EvaluationResult< Number > hypro::SupportFunctionContent< Number, Setting >::evaluate (const vector_t< Number > & _direction, bool useExact) const
Definition at line 493 of file SupportFunctionContent.tpp.
References hypro::SupportFunctionContent< Number, Setting >::multiEvaluate().
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::specificEvaluation().
template<typename Number , typename Setting > void hypro::SupportFunctionContent< Number, Setting >::forceLinTransReduction ()
Definition at line 1055 of file SupportFunctionContent.tpp.
References hypro::SupportFunctionContent< Number, Setting >::checkTreeValidity(), hypro::INTERSECT, hypro::SupportFunctionContent< Number, Setting >::intersectionParameters(), hypro::SupportFunctionContent< Number, Setting >::linearTrafoParameters(), hypro::LINTRAFO, hypro::NONE, hypro::PROJECTION, hypro::SupportFunctionContent< Number, Setting >::projectionParameters(), hypro::SCALE, hypro::SupportFunctionContent< Number, Setting >::scaleParameters(), hypro::SUM, hypro::SupportFunctionContent< Number, Setting >::summands(), hypro::SupportFunctionContent< Number, Setting >::unionParameters(), and hypro::UNITE.
template<typename Number, typename Setting> std::size_t hypro::SupportFunctionContent< Number, Setting >::getDotRepresentation (std::size_t startIndex, std::string & nodes, std::string & transitions) const inline
Definition at line 538 of file SupportFunctionContent.h.
References hypro::BOX, hypro::ELLIPSOID, hypro::PolytopeSupportFunction< Number, Setting >::getDotRepresentation(), hypro::INFTY_BALL, hypro::INTERSECT, hypro::unionContent< Number, Setting >::items, hypro::sumContent< Number, Setting >::lhs, hypro::intersectionContent< Number, Setting >::lhs, hypro::LINTRAFO, hypro::NONE, hypro::trafoContent< Number, Setting >::origin, hypro::scaleContent< Number, Setting >::origin, hypro::projectionContent< Number, Setting >::origin, hypro::sumContent< Number, Setting >::originCount(), hypro::trafoContent< Number, Setting >::originCount(), hypro::scaleContent< Number, Setting >::originCount(), hypro::unionContent< Number, Setting >::originCount(), hypro::intersectionContent< Number, Setting >::originCount(), hypro::projectionContent< Number, Setting >::originCount(), hypro::trafoContent< Number, Setting >::parameters, hypro::POLY, hypro::PROJECTION, hypro::sumContent< Number, Setting >::rhs, hypro::intersectionContent< Number, Setting >::rhs, hypro::SCALE, hypro::SUM, hypro::TWO_BALL, hypro::UNITE, and hypro::ZONOTOPE.
template<typename Number, typename Setting> std::shared_ptr<SupportFunctionContent<Number, Setting> > hypro::SupportFunctionContent< Number, Setting >::getThis () const inline
Definition at line 327 of file SupportFunctionContent.h.
References hypro::contains(), hypro::project(), and hypro::unite().
Referenced by hypro::SupportFunctionContent< Number, Setting >::affineTransformation(), hypro::SupportFunctionContent< Number, Setting >::cleanUp(), hypro::SupportFunctionContent< Number, Setting >::collectProjections(), hypro::SupportFunctionContent< Number, Setting >::intersect(), hypro::SupportFunctionContent< Number, Setting >::minkowskiSum(), hypro::SupportFunctionContent< Number, Setting >::multiEvaluate(), hypro::SupportFunctionContent< Number, Setting >::multiplicationsPerEvaluation(), hypro::SupportFunctionContent< Number, Setting >::project(), hypro::SupportFunctionContent< Number, Setting >::scale(), and hypro::SupportFunctionContent< Number, Setting >::unite().
template<typename Number , typename Setting > std::shared_ptr< SupportFunctionContent< Number, Setting > > hypro::SupportFunctionContent< Number, Setting >::intersect (const std::shared_ptr< SupportFunctionContent< Number, Setting >> & _rhs) const
Definition at line 1474 of file SupportFunctionContent.tpp.
References hypro::SupportFunctionContent< Number, Setting >::create(), hypro::SupportFunctionContent< Number, Setting >::getThis(), and hypro::INTERSECT.
template<typename Number , typename Setting > intersectionContent< Number, Setting > * hypro::SupportFunctionContent< Number, Setting >::intersectionParameters () const
Definition at line 1420 of file SupportFunctionContent.tpp.
References hypro::INTERSECT.
Referenced by hypro::SupportFunctionContent< Number, Setting >::contains(), hypro::SupportFunctionContent< Number, Setting >::empty(), hypro::SupportFunctionContent< Number, Setting >::forceLinTransReduction(), hypro::SupportFunctionContent< Number, Setting >::print(), and hypro::SupportFunctionContent< Number, Setting >::supremumPoint().
template<typename Number , typename Setting > trafoContent< Number, Setting > * hypro::SupportFunctionContent< Number, Setting >::linearTrafoParameters () const
Definition at line 1402 of file SupportFunctionContent.tpp.
References hypro::LINTRAFO.
Referenced by hypro::SupportFunctionContent< Number, Setting >::contains(), hypro::SupportFunctionContent< Number, Setting >::empty(), hypro::SupportFunctionContent< Number, Setting >::forceLinTransReduction(), hypro::SupportFunctionContent< Number, Setting >::print(), hypro::SupportFunctionContent< Number, Setting >::supremumPoint(), and hypro::SupportFunctionContent< Number, Setting >::~SupportFunctionContent().
template<typename Number , typename Setting > std::shared_ptr< SupportFunctionContent< Number, Setting > > hypro::SupportFunctionContent< Number, Setting >::minkowskiSum (const std::shared_ptr< SupportFunctionContent< Number, Setting >> & _rhs) const
Definition at line 1468 of file SupportFunctionContent.tpp.
References hypro::SupportFunctionContent< Number, Setting >::create(), hypro::SupportFunctionContent< Number, Setting >::getThis(), and hypro::SUM.
template<typename Number , typename Setting > std::vector< EvaluationResult< Number > > hypro::SupportFunctionContent< Number, Setting >::multiEvaluate (const matrix_t< Number > & _directions, bool useExact) const
Definition at line 503 of file SupportFunctionContent.tpp.
References hypro::SupportFunctionContent< Number, Setting >::ball(), hypro::BOX, hypro::SupportFunctionContent< Number, Setting >::box(), hypro::SupportFunctionContent< Number, Setting >::checkTreeValidity(), hypro::ELLIPSOID, hypro::SupportFunctionContent< Number, Setting >::ellipsoid(), hypro::EvaluationResult< Number >::errorCode, hypro::FEAS, hypro::SupportFunctionContent< Number, Setting >::getThis(), hypro::INFEAS, hypro::INFTY, hypro::INFTY_BALL, hypro::INTERSECT, hypro::LINTRAFO, hypro::NONE, hypro::EvaluationResult< Number >::optimumValue, hypro::POLY, hypro::SupportFunctionContent< Number, Setting >::polytope(), hypro::PROJECTION, hypro::SCALE, hypro::SUM, hypro::EvaluationResult< Number >::supportValue, hypro::TWO_BALL, and hypro::UNITE.
Referenced by hypro::SupportFunctionContent< Number, Setting >::evaluate().
template<typename Number , typename Setting > unsigned hypro::SupportFunctionContent< Number, Setting >::multiplicationsPerEvaluation () const
Returns an approximation of the number of mv multiplications neccessary for an evaluation of the SF
Definition at line 904 of file SupportFunctionContent.tpp.
References hypro::BOX, hypro::ELLIPSOID, hypro::SupportFunctionContent< Number, Setting >::getThis(), hypro::INFTY_BALL, hypro::INTERSECT, hypro::LINTRAFO, hypro::NONE, hypro::POLY, hypro::SupportFunctionContent< Number, Setting >::polytope(), hypro::PROJECTION, hypro::SCALE, hypro::SUM, hypro::TWO_BALL, hypro::UNITE, and hypro::ZONOTOPE.
template<typename Number , typename Setting > unsigned hypro::SupportFunctionContent< Number, Setting >::operationCount () const
Definition at line 898 of file SupportFunctionContent.tpp.
References hypro::NONE.
template<typename Number , typename Setting > std::shared_ptr< SupportFunctionContent< Number, Setting > > & hypro::SupportFunctionContent< Number, Setting >::operator= (const std::shared_ptr< SupportFunctionContent< Number, Setting >> & _orig)
Definition at line 440 of file SupportFunctionContent.tpp.
References hypro::BOX, hypro::SupportFunctionContent< Number, Setting >::checkTreeValidity(), hypro::ELLIPSOID, hypro::INFTY_BALL, hypro::INTERSECT, hypro::LINTRAFO, hypro::NONE, hypro::POLY, hypro::PROJECTION, hypro::SCALE, hypro::SUM, hypro::TWO_BALL, and hypro::UNITE.
template<typename Number , typename Setting > PolytopeSupportFunction< Number, Setting > * hypro::SupportFunctionContent< Number, Setting >::polytope () const
Definition at line 1433 of file SupportFunctionContent.tpp.
References hypro::POLY.
Referenced by hypro::SupportFunctionContent< Number, Setting >::contains(), hypro::SupportFunctionContent< Number, Setting >::empty(), hypro::SupportFunctionContent< Number, Setting >::multiEvaluate(), hypro::SupportFunctionContent< Number, Setting >::multiplicationsPerEvaluation(), hypro::SupportFunctionContent< Number, Setting >::print(), and hypro::SupportFunctionContent< Number, Setting >::supremumPoint().
template<typename Number , typename Setting > void hypro::SupportFunctionContent< Number, Setting >::print () const
Definition at line 1732 of file SupportFunctionContent.tpp.
References hypro::BOX, hypro::ELLIPSOID, hypro::INFTY_BALL, hypro::INTERSECT, hypro::SupportFunctionContent< Number, Setting >::intersectionParameters(), hypro::SupportFunctionContent< Number, Setting >::linearTrafoParameters(), hypro::LINTRAFO, hypro::POLY, hypro::SupportFunctionContent< Number, Setting >::polytope(), hypro::PROJECTION, hypro::SupportFunctionContent< Number, Setting >::projectionParameters(), hypro::SCALE, hypro::SUM, hypro::SupportFunctionContent< Number, Setting >::summands(), hypro::TWO_BALL, and hypro::UNITE.
template<typename Number , typename Setting > std::shared_ptr< SupportFunctionContent< Number, Setting > > hypro::SupportFunctionContent< Number, Setting >::project (const std::vector< std::size_t > & dimensions) const
Definition at line 1457 of file SupportFunctionContent.tpp.
References hypro::SupportFunctionContent< Number, Setting >::create(), and hypro::SupportFunctionContent< Number, Setting >::getThis().
template<typename Number , typename Setting > projectionContent< Number, Setting > * hypro::SupportFunctionContent< Number, Setting >::projectionParameters () const
Definition at line 1427 of file SupportFunctionContent.tpp.
References hypro::PROJECTION.
Referenced by hypro::SupportFunctionContent< Number, Setting >::contains(), hypro::SupportFunctionContent< Number, Setting >::empty(), hypro::SupportFunctionContent< Number, Setting >::forceLinTransReduction(), hypro::SupportFunctionContent< Number, Setting >::print(), and hypro::SupportFunctionContent< Number, Setting >::supremumPoint().
template<typename Number , typename Setting > void hypro::SupportFunctionContent< Number, Setting >::reduceRepresentation ()
Definition at line 1583 of file SupportFunctionContent.tpp.
template<typename Number , typename Setting > std::shared_ptr< SupportFunctionContent< Number, Setting > > hypro::SupportFunctionContent< Number, Setting >::scale (const Number & _factor = 1) const
Definition at line 1578 of file SupportFunctionContent.tpp.
References hypro::SupportFunctionContent< Number, Setting >::create(), and hypro::SupportFunctionContent< Number, Setting >::getThis().
template<typename Number , typename Setting > scaleContent< Number, Setting > * hypro::SupportFunctionContent< Number, Setting >::scaleParameters () const
Definition at line 1408 of file SupportFunctionContent.tpp.
References hypro::SCALE.
Referenced by hypro::SupportFunctionContent< Number, Setting >::contains(), hypro::SupportFunctionContent< Number, Setting >::empty(), hypro::SupportFunctionContent< Number, Setting >::forceLinTransReduction(), and hypro::SupportFunctionContent< Number, Setting >::supremumPoint().
template<typename Number , typename Setting > sumContent< Number, Setting > * hypro::SupportFunctionContent< Number, Setting >::summands () const
Definition at line 1396 of file SupportFunctionContent.tpp.
References hypro::SUM.
Referenced by hypro::SupportFunctionContent< Number, Setting >::contains(), hypro::SupportFunctionContent< Number, Setting >::empty(), hypro::SupportFunctionContent< Number, Setting >::forceLinTransReduction(), hypro::SupportFunctionContent< Number, Setting >::print(), and hypro::SupportFunctionContent< Number, Setting >::supremumPoint().
template<typename Number , typename Setting > Point< Number > hypro::SupportFunctionContent< Number, Setting >::supremumPoint () const
Definition at line 1122 of file SupportFunctionContent.tpp.
References hypro::Point< Number >::affineTransformation(), hypro::Point< Number >::at(), hypro::SupportFunctionContent< Number, Setting >::ball(), hypro::BOX, hypro::SupportFunctionContent< Number, Setting >::box(), hypro::SupportFunctionContent< Number, Setting >::checkTreeValidity(), hypro::Point< Number >::dimension(), hypro::INFTY_BALL, hypro::Point< Number >::inftyNorm(), hypro::INTERSECT, hypro::SupportFunctionContent< Number, Setting >::intersectionParameters(), hypro::SupportFunctionContent< Number, Setting >::linearTrafoParameters(), hypro::LINTRAFO, hypro::NONE, hypro::POLY, hypro::SupportFunctionContent< Number, Setting >::polytope(), hypro::PROJECTION, hypro::SupportFunctionContent< Number, Setting >::projectionParameters(), hypro::SCALE, hypro::SupportFunctionContent< Number, Setting >::scaleParameters(), hypro::SUM, hypro::SupportFunctionContent< Number, Setting >::summands(), hypro::TWO_BALL, hypro::SupportFunctionContent< Number, Setting >::unionParameters(), hypro::UNITE, and hypro::Point< Number >::Zero().
template<typename Number , typename Setting > SF_TYPE hypro::SupportFunctionContent< Number, Setting >::type () const
Definition at line 887 of file SupportFunctionContent.tpp.
template<typename Number , typename Setting > unionContent< Number, Setting > * hypro::SupportFunctionContent< Number, Setting >::unionParameters () const
Definition at line 1414 of file SupportFunctionContent.tpp.
References hypro::UNITE.
Referenced by hypro::SupportFunctionContent< Number, Setting >::contains(), hypro::SupportFunctionContent< Number, Setting >::empty(), hypro::SupportFunctionContent< Number, Setting >::forceLinTransReduction(), and hypro::SupportFunctionContent< Number, Setting >::supremumPoint().
template<typename Number , typename Setting > std::shared_ptr< SupportFunctionContent< Number, Setting > > hypro::SupportFunctionContent< Number, Setting >::unite (const std::shared_ptr< SupportFunctionContent< Number, Setting >> & _rhs) const
Definition at line 1567 of file SupportFunctionContent.tpp.
References hypro::SupportFunctionContent< Number, Setting >::create(), hypro::SupportFunctionContent< Number, Setting >::getThis(), and hypro::UNITE.
Referenced by hypro::unite().
template<typename Number , typename Setting > std::shared_ptr< SupportFunctionContent< Number, Setting > > hypro::SupportFunctionContent< Number, Setting >::unite (const std::vector< std::shared_ptr< SupportFunctionContent< Number, Setting >>> & _rhs) static
Definition at line 1573 of file SupportFunctionContent.tpp.
References hypro::SupportFunctionContent< Number, Setting >::create(), and hypro::UNITE.
Friends And Related Function Documentation
template<typename Number, typename Setting> std::ostream& operator<< (std::ostream & lhs, const std::shared_ptr< SupportFunctionContent< Number, Setting >> & rhs) friend
Definition at line 370 of file SupportFunctionContent.h.
template<typename Number, typename Setting> template<typename N , typename C , typename S > friend class SupportFunctionT friend
Definition at line 186 of file SupportFunctionContent.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunction/PolytopeSupportFunction.h
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunction/SupportFunctionContent.h
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunction/SupportFunctionContent.tpp