HyPro: hypro::TemplatePolyhedronContext< State > Class Template Reference
hypro::TemplatePolyhedronContext< State > Class Template Reference
Public Member Functions
TemplatePolyhedronContext ()=delete
TemplatePolyhedronContext (const std::shared_ptr< Task< State >> &t, const Strategy< State > &strat, WorkQueue< std::shared_ptr< Task< State >>> *localQueue, WorkQueue< std::shared_ptr< Task< State >>> *localCEXQueue, Flowpipe< State > &localSegments, ReachabilitySettings &settings)
~TemplatePolyhedronContext ()
void execBeforeFirstSegment () override
void firstSegment () override
void applyContinuousEvolution () override
void execBeforeProcessDiscreteBehavior () override
vector_t< Number > gradientOfLinearFct (const vector_t< Number > &linearFct)
std::pair< vector_t< typename State::NumberType >, typename State::NumberType > lieDerivative (const vector_t< Number > &dir)
std::pair< vector_t< typename State::NumberType >, typename State::NumberType > lieDerivativeExtended (const vector_t< Number > &dir)
vector_t< Number > locationInvariantStrengthening (const TemplatePolyhedron< Number > &invTPpoly, const vector_t< Number > &initialOffsets)
template<typename Setting >
TemplatePolyhedronT< typename State::NumberType, hypro::Converter< Number >, Setting > createTemplateContent (const TemplatePolyhedronT< Number, hypro::Converter< Number >, Setting > &tpoly)
bool isPositiveInvariant (const TemplatePolyhedron< Number > &tpoly, const vector_t< Number > &invVector)
bool isRelaxedInvariant (const TemplatePolyhedron< Number > &tpoly, const vector_t< Number > &invVector)
template<typename Setting >
TemplatePolyhedronT< typename State::NumberType, hypro::Converter< typename State::NumberType >, Setting > createTemplateContent (const TemplatePolyhedronT< Number, hypro::Converter< Number >, Setting > &tpoly)
Public Member Functions inherited from hypro::LTIContext< State >
LTIContext ()=delete
~LTIContext ()
LTIContext (const TaskType &t, const Strategy< State > &strat, WorkQueue< TaskType > *localQueue, WorkQueue< TaskType > *localCEXQueue, Flowpipe< State > &localSegments, ReachabilitySettings &settings)
virtual void execOnStart () override
virtual void execAfterFirstSegment () override
virtual void checkInvariant () override
virtual void intersectBadStates () override
virtual void execBeforeLoop () override
virtual bool doneCondition () override
virtual void checkTransition () override
virtual void execOnLoopItExit () override
virtual void processDiscreteBehavior () override
virtual void execOnEnd () override
void initalizeFirstSegmentHandlers ()
void initializeInvariantHandlers ()
void initializeBadStateHandlers ()
void initializeGuardHandlers ()
void applyBacktracking ()
bool omitTransition (Transition< Number > *transition)
bool omitInvariant ()
bool omitBadStateCheck ()
Public Member Functions inherited from hypro::IContext
virtual void execBeforeCheckInvariant ()
virtual void execAfterCheckInvariant ()
virtual void execBeforeIntersectBadStates ()
virtual void execAfterIntersectBadStates ()
virtual void execOnLoopItEnter ()
virtual void execBeforeCheckTransition ()
virtual void execAfterCheckTransition ()
virtual void execBeforeContinuousEvolution ()
virtual void execAfterContinuousEvolution ()
virtual void execAfterLoop ()
virtual void execAfterProcessDiscreteBehavior ()
Additional Inherited Members
Protected Attributes inherited from hypro::LTIContext< State >
std::shared_ptr< Task< State > > mTask
Strategy< State > mStrategy
WorkQueue< TaskType > * mLocalQueue
WorkQueue< TaskType > * mLocalCEXQueue
Flowpipe< State > & mLocalSegments
ReachabilitySettings mSettings
EventTimingContainer< Number > mLocalTimings
HierarchicalIntervalVector< CONTAINMENT, tNumber > mTransitionTimings
std::vector< std::tuple< Transition< Number > *, State > > mDiscreteSuccessorBuffer
std::map< Transition< Number > *, State > mPotentialZenoTransitions
std::vector< Transition< Number > * > mDisabledTransitions
tNumber mCurrentLocalTime
carl::Interval< tNumber > mCurrentGlobalTimeInterval
carl::Interval< tNumber > mCurrentTimeInterval
State mComputationState
std::vector< IFirstSegmentHandler< State > * > mFirstSegmentHandlers
std::vector< IInvariantHandler * > mInvariantHandlers
std::vector< IBadStateHandler * > mBadStateHandlers
std::vector< ITimeEvolutionHandler * > mContinuousEvolutionHandlers
std::map< Transition< Number > *, std::vector< IGuardHandler< State > * > > mTransitionHandlerMap
Detailed Description
template<typename State>
class hypro::TemplatePolyhedronContext< State >
Definition at line 34 of file TemplatePolyhedronContext.h.
Constructor & Destructor Documentation
template<typename State> hypro::TemplatePolyhedronContext< State >::TemplatePolyhedronContext () delete
template<typename State> hypro::TemplatePolyhedronContext< State >::TemplatePolyhedronContext (const std::shared_ptr< Task< State >> & t, const Strategy< State > & strat, WorkQueue< std::shared_ptr< Task< State >>> * localQueue, WorkQueue< std::shared_ptr< Task< State >>> * localCEXQueue, Flowpipe< State > & localSegments, ReachabilitySettings & settings) inline
Definition at line 60 of file TemplatePolyhedronContext.h.
template<typename State> hypro::TemplatePolyhedronContext< State >::~TemplatePolyhedronContext () inline
Definition at line 72 of file TemplatePolyhedronContext.h.
References hypro::TemplatePolyhedronContext< State >::applyContinuousEvolution(), hypro::TemplatePolyhedronContext< State >::createTemplateContent(), hypro::TemplatePolyhedronContext< State >::execBeforeFirstSegment(), hypro::TemplatePolyhedronContext< State >::execBeforeProcessDiscreteBehavior(), hypro::TemplatePolyhedronContext< State >::firstSegment(), hypro::TemplatePolyhedronContext< State >::gradientOfLinearFct(), hypro::TemplatePolyhedronContext< State >::isPositiveInvariant(), hypro::TemplatePolyhedronContext< State >::isRelaxedInvariant(), hypro::TemplatePolyhedronContext< State >::lieDerivative(), hypro::TemplatePolyhedronContext< State >::lieDerivativeExtended(), and hypro::TemplatePolyhedronContext< State >::locationInvariantStrengthening().
Member Function Documentation
template<typename State > void hypro::TemplatePolyhedronContext< State >::applyContinuousEvolution () override virtual
Reimplemented from hypro::LTIContext< State >.
Definition at line 518 of file TemplatePolyhedronContext.tpp.
Referenced by hypro::TemplatePolyhedronContext< State >::~TemplatePolyhedronContext().
template<typename State> template<typename Setting > TemplatePolyhedronT<typename State::NumberType, hypro::Converter<Number>, Setting> hypro::TemplatePolyhedronContext< State >::createTemplateContent (const TemplatePolyhedronT< Number, hypro::Converter< Number >, Setting > & tpoly)
Referenced by hypro::TemplatePolyhedronContext< State >::~TemplatePolyhedronContext().
template<typename State> template<typename Setting > TemplatePolyhedronT<typename State::NumberType, hypro::Converter<typename State::NumberType>, Setting> hypro::TemplatePolyhedronContext< State >::createTemplateContent (const TemplatePolyhedronT< Number, hypro::Converter< Number >, Setting > & tpoly)
Definition at line 305 of file TemplatePolyhedronContext.tpp.
References hypro::SettingsProvider< State >::getHybridAutomaton().
template<typename State > void hypro::TemplatePolyhedronContext< State >::execBeforeFirstSegment () override virtual
Reimplemented from hypro::LTIContext< State >.
Definition at line 463 of file TemplatePolyhedronContext.tpp.
References hypro::LTIContext< State >::execBeforeFirstSegment().
Referenced by hypro::TemplatePolyhedronContext< State >::~TemplatePolyhedronContext().
template<typename State > void hypro::TemplatePolyhedronContext< State >::execBeforeProcessDiscreteBehavior () override virtual
Reimplemented from hypro::IContext.
Definition at line 548 of file TemplatePolyhedronContext.tpp.
References hypro::IContext::execBeforeProcessDiscreteBehavior().
Referenced by hypro::TemplatePolyhedronContext< State >::~TemplatePolyhedronContext().
template<typename State > void hypro::TemplatePolyhedronContext< State >::firstSegment () override virtual
Reimplemented from hypro::LTIContext< State >.
Definition at line 495 of file TemplatePolyhedronContext.tpp.
References hypro::SettingsProvider< State >::getTimeStepSize().
Referenced by hypro::TemplatePolyhedronContext< State >::~TemplatePolyhedronContext().
template<typename State > vector_t< typename State::NumberType > hypro::TemplatePolyhedronContext< State >::gradientOfLinearFct (const vector_t< Number > & linearFct)
Definition at line 6 of file TemplatePolyhedronContext.tpp.
Referenced by hypro::TemplatePolyhedronContext< State >::~TemplatePolyhedronContext().
template<typename State > bool hypro::TemplatePolyhedronContext< State >::isPositiveInvariant (const TemplatePolyhedron< Number > & tpoly, const vector_t< Number > & invVector)
Definition at line 369 of file TemplatePolyhedronContext.tpp.
Referenced by hypro::TemplatePolyhedronContext< State >::~TemplatePolyhedronContext().
template<typename State > bool hypro::TemplatePolyhedronContext< State >::isRelaxedInvariant (const TemplatePolyhedron< Number > & tpoly, const vector_t< Number > & invVector)
Definition at line 416 of file TemplatePolyhedronContext.tpp.
Referenced by hypro::TemplatePolyhedronContext< State >::~TemplatePolyhedronContext().
template<typename State > std::pair< vector_t< typename State::NumberType >, typename State::NumberType > hypro::TemplatePolyhedronContext< State >::lieDerivative (const vector_t< Number > & dir)
Definition at line 14 of file TemplatePolyhedronContext.tpp.
Referenced by hypro::TemplatePolyhedronContext< State >::~TemplatePolyhedronContext().
template<typename State > std::pair< vector_t< typename State::NumberType >, typename State::NumberType > hypro::TemplatePolyhedronContext< State >::lieDerivativeExtended (const vector_t< Number > & dir)
Definition at line 35 of file TemplatePolyhedronContext.tpp.
Referenced by hypro::TemplatePolyhedronContext< State >::~TemplatePolyhedronContext().
template<typename State > vector_t< typename State::NumberType > hypro::TemplatePolyhedronContext< State >::locationInvariantStrengthening (const TemplatePolyhedron< Number > & invTPpoly, const vector_t< Number > & initialOffsets)
Definition at line 55 of file TemplatePolyhedronContext.tpp.
References hypro::FEAS, and hypro::INFEAS.
Referenced by hypro::TemplatePolyhedronContext< State >::~TemplatePolyhedronContext().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/contexts/TemplatePolyhedronContext.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/contexts/TemplatePolyhedronContext.tpp