HyPro: hypro::ReachTree< State > Class Template Reference
hypro::ReachTree< State > Class Template Reference
#include <ReachTree.h>
Public Member Functions
ReachTree (ReachTreeNode< State > *_root)
~ReachTree ()
ReachTreeNode< State > * getRoot () const
std::size_t getDepth () const
std::size_t getNumberNodes () const
double getAvgBranching () const
std::vector< std::size_t > getLevelCnt () const
std::string getDotRepresentation () const
TreeStatistic getTreeStats () const
Private Attributes
ReachTreeNode< State > * mRoot
Detailed Description
template<typename State>
class hypro::ReachTree< State >
Definition at line 16 of file ReachTree.h.
Constructor & Destructor Documentation
template<typename State> hypro::ReachTree< State >::ReachTree (ReachTreeNode< State > * _root)
template<typename State> hypro::ReachTree< State >::~ReachTree () inline
Definition at line 23 of file ReachTree.h.
References hypro::ReachTree< State >::getAvgBranching(), hypro::ReachTree< State >::getDepth(), hypro::ReachTree< State >::getDotRepresentation(), hypro::ReachTree< State >::getLevelCnt(), hypro::ReachTree< State >::getNumberNodes(), hypro::ReachTree< State >::getRoot(), hypro::ReachTree< State >::getTreeStats(), hypro::ReachTree< State >::mRoot, and string().
Member Function Documentation
template<typename State> double hypro::ReachTree< State >::getAvgBranching () const
Referenced by hypro::ReachTree< State >::~ReachTree().
template<typename State> std::size_t hypro::ReachTree< State >::getDepth () const
Referenced by hypro::ReachTree< State >::~ReachTree().
template<typename State> std::string hypro::ReachTree< State >::getDotRepresentation () const
Referenced by hypro::ReachTree< State >::~ReachTree().
template<typename State> std::vector<std::size_t> hypro::ReachTree< State >::getLevelCnt () const
Referenced by hypro::ReachTree< State >::~ReachTree().
template<typename State> std::size_t hypro::ReachTree< State >::getNumberNodes () const
Referenced by hypro::ReachTree< State >::~ReachTree().
template<typename State> ReachTreeNode<State>* hypro::ReachTree< State >::getRoot () const
Referenced by main(), and hypro::ReachTree< State >::~ReachTree().
template<typename State> TreeStatistic hypro::ReachTree< State >::getTreeStats () const
Referenced by hypro::ReachTree< State >::~ReachTree().
Member Data Documentation
template<typename State> ReachTreeNode<State>* hypro::ReachTree< State >::mRoot private
Definition at line 18 of file ReachTree.h.
Referenced by hypro::ReachTree< State >::~ReachTree().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/ReachTree.h