HyPro: hypro::TimedContext< State > Class Template Reference
hypro::TimedContext< State > Class Template Reference
#include <TimedContext.h>
Public Member Functions
TimedContext ()=default
~TimedContext ()
TimedContext (const std::shared_ptr< Task< State >> &t, const Strategy< State > &strat, WorkQueue< std::shared_ptr< Task< State >>> *localQueue, WorkQueue< std::shared_ptr< Task< State >>> *localCEXQueue, Flowpipe< State > &localSegments, ReachabilitySettings &settings)
virtual void execOnLoopItExit () override
virtual bool doneCondition () override
virtual void applyContinuousEvolution () override
virtual void checkInvariant () override
virtual void checkTransition () override
carl::Interval< tNumber > computeShortestElapsedTimeIntervalForSubspace (State &in, size_t index)
Compute the minimum elapsed time interval in a subspace.
carl::Interval< tNumber > handshakeTimestamps (State &preOp, State &postOp)
Performs a handshake over all timed subspaces. This is especially important checking for guard/invariant/badstate intersection. This check ensures that the satisfaction conditions occur on an intersecting timestamp over all subspaces.
Public Member Functions inherited from hypro::LTIContext< State >
LTIContext ()=delete
~LTIContext ()
LTIContext (const TaskType &t, const Strategy< State > &strat, WorkQueue< TaskType > *localQueue, WorkQueue< TaskType > *localCEXQueue, Flowpipe< State > &localSegments, ReachabilitySettings &settings)
virtual void execOnStart () override
virtual void execBeforeFirstSegment () override
virtual void firstSegment () override
virtual void execAfterFirstSegment () override
virtual void intersectBadStates () override
virtual void execBeforeLoop () override
virtual void processDiscreteBehavior () override
virtual void execOnEnd () override
void initalizeFirstSegmentHandlers ()
void initializeInvariantHandlers ()
void initializeBadStateHandlers ()
void initializeGuardHandlers ()
void applyBacktracking ()
bool omitTransition (Transition< Number > *transition)
bool omitInvariant ()
bool omitBadStateCheck ()
Public Member Functions inherited from hypro::IContext
virtual void execBeforeCheckInvariant ()
virtual void execAfterCheckInvariant ()
virtual void execBeforeIntersectBadStates ()
virtual void execAfterIntersectBadStates ()
virtual void execOnLoopItEnter ()
virtual void execBeforeCheckTransition ()
virtual void execAfterCheckTransition ()
virtual void execBeforeContinuousEvolution ()
virtual void execAfterContinuousEvolution ()
virtual void execAfterLoop ()
virtual void execBeforeProcessDiscreteBehavior ()
virtual void execAfterProcessDiscreteBehavior ()
Private Types
using Number = typename State::NumberType
Private Attributes
bool mElapsed
State mPreOpState
Additional Inherited Members
Protected Attributes inherited from hypro::LTIContext< State >
std::shared_ptr< Task< State > > mTask
Strategy< State > mStrategy
WorkQueue< TaskType > * mLocalQueue
WorkQueue< TaskType > * mLocalCEXQueue
Flowpipe< State > & mLocalSegments
ReachabilitySettings mSettings
EventTimingContainer< Number > mLocalTimings
HierarchicalIntervalVector< CONTAINMENT, tNumber > mTransitionTimings
std::vector< std::tuple< Transition< Number > *, State > > mDiscreteSuccessorBuffer
std::map< Transition< Number > *, State > mPotentialZenoTransitions
std::vector< Transition< Number > * > mDisabledTransitions
tNumber mCurrentLocalTime
carl::Interval< tNumber > mCurrentGlobalTimeInterval
carl::Interval< tNumber > mCurrentTimeInterval
State mComputationState
std::vector< IFirstSegmentHandler< State > * > mFirstSegmentHandlers
std::vector< IInvariantHandler * > mInvariantHandlers
std::vector< IBadStateHandler * > mBadStateHandlers
std::vector< ITimeEvolutionHandler * > mContinuousEvolutionHandlers
std::map< Transition< Number > *, std::vector< IGuardHandler< State > * > > mTransitionHandlerMap
Detailed Description
template<typename State>
class hypro::TimedContext< State >
Definition at line 20 of file TimedContext.h.
Member Typedef Documentation
template<typename State > using hypro::TimedContext< State >::Number = typename State::NumberType private
Definition at line 21 of file TimedContext.h.
Constructor & Destructor Documentation
template<typename State > hypro::TimedContext< State >::TimedContext () default
template<typename State > hypro::TimedContext< State >::~TimedContext () inline
Definition at line 28 of file TimedContext.h.
template<typename State > hypro::TimedContext< State >::TimedContext (const std::shared_ptr< Task< State >> & t, const Strategy< State > & strat, WorkQueue< std::shared_ptr< Task< State >>> * localQueue, WorkQueue< std::shared_ptr< Task< State >>> * localCEXQueue, Flowpipe< State > & localSegments, ReachabilitySettings & settings) inline
Definition at line 29 of file TimedContext.h.
References hypro::TimedContext< State >::applyContinuousEvolution(), hypro::TimedContext< State >::checkInvariant(), hypro::TimedContext< State >::checkTransition(), hypro::TimedContext< State >::computeShortestElapsedTimeIntervalForSubspace(), hypro::TimedContext< State >::doneCondition(), hypro::TimedContext< State >::execOnLoopItExit(), hypro::TimedContext< State >::handshakeTimestamps(), and index.
Member Function Documentation
template<typename State > virtual void hypro::TimedContext< State >::applyContinuousEvolution () override virtual
Reimplemented from hypro::LTIContext< State >.
Referenced by hypro::TimedContext< State >::TimedContext().
template<typename State > virtual void hypro::TimedContext< State >::checkInvariant () override virtual
Reimplemented from hypro::LTIContext< State >.
Referenced by hypro::TimedContext< State >::TimedContext().
template<typename State > virtual void hypro::TimedContext< State >::checkTransition () override virtual
Reimplemented from hypro::LTIContext< State >.
Referenced by hypro::TimedContext< State >::TimedContext().
template<typename State > carl::Interval<tNumber> hypro::TimedContext< State >::computeShortestElapsedTimeIntervalForSubspace (State & in, size_t index)
Compute the minimum elapsed time interval in a subspace.
Parameters
in the current state
index subspace index
Returns
time interval in that state
Referenced by hypro::TimedContext< State >::TimedContext().
template<typename State > virtual bool hypro::TimedContext< State >::doneCondition () override virtual
Reimplemented from hypro::LTIContext< State >.
Referenced by hypro::TimedContext< State >::TimedContext().
template<typename State > virtual void hypro::TimedContext< State >::execOnLoopItExit () override virtual
Reimplemented from hypro::LTIContext< State >.
Referenced by hypro::TimedContext< State >::TimedContext().
template<typename State > carl::Interval<tNumber> hypro::TimedContext< State >::handshakeTimestamps (State & preOp, State & postOp)
Performs a handshake over all timed subspaces. This is especially important checking for guard/invariant/badstate intersection. This check ensures that the satisfaction conditions occur on an intersecting timestamp over all subspaces.
If the timestamps intersect, the subspaces are cut to this intersecting timeframe. If the timestamps do not intersect, that means that the spaces may all validate their condition, but they don't validate it during the same time frame. We return an empty timestamp here.
Do not forget to set the returned timestamp on the corresponding state.
Parameters
state before operation
state after operation
Returns
timestamp after operation
Referenced by hypro::TimedContext< State >::TimedContext().
Member Data Documentation
template<typename State > bool hypro::TimedContext< State >::mElapsed private
Definition at line 24 of file TimedContext.h.
template<typename State > State hypro::TimedContext< State >::mPreOpState private
Definition at line 25 of file TimedContext.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/contexts/TimedContext.h