HyPro: hypro::Transition< Number > Class Template Reference
hypro::Transition< Number > Class Template Reference
Class for transition.
#include <Location.h>
Public Member Functions
Transition ()=default
Default constructor.
Transition (const Transition< Number > &orig)=default
Copy constructor.
Transition (Transition< Number > &&orig)=default
Move constructor.
Transition & operator= (const Transition< Number > &orig)=default
Copy assignment operator.
Transition & operator= (Transition< Number > &&orig)=default
Move assignment operator.
~Transition ()
Destroys the object.
Transition (Location< Number > *source, Location< Number > *target)
Constructor from source and target location.
Transition (Location< Number > *source, Location< Number > *target, const Condition< Number > &guard, const Reset< Number > &reset)
Full constructor for basic transition.
Location< Number > * getSource () const
Location< Number > * getTarget () const
const Condition< Number > & getGuard () const
const Reset< Number > & getReset () const
Aggregation getAggregation () const
std::size_t getClusterBound () const
Number getTriggerTime () const
bool isUrgent () const
bool isTimeTriggered () const
bool hasIdentityReset () const
const std::vector< Label > & getLabels () const
std::size_t hash () const
void setSource (Location< Number > *source)
void setTarget (Location< Number > *target)
void setSource (std::unique_ptr< Location< Number >> &source)
void setTarget (std::unique_ptr< Location< Number >> &target)
void setGuard (const Condition< Number > &guard)
void setReset (const Reset< Number > &val)
void setAggregation (Aggregation agg)
void setClusterBound (std::size_t cluster)
void setUrgent (bool urgent=true)
void setTriggerTime (Number t)
void setLabels (const std::vector< Label > &labels)
void addLabel (const Label &lab)
std::string getDotRepresentation (const std::vector< std::string > &vars) const
bool isComposedOf (const Transition< Number > &rhs, const std::vector< std::string > &rhsVars, const std::vector< std::string > &thisVars) const
Determines if this composed of rhs and a potential rest.
void decompose (const Decomposition &decomposition)
Private Attributes
Location< Number > * mSource = nullptr
Location< Number > * mTarget = nullptr
Pointer to the source location.
Condition< Number > mGuard
Pointer to the target location.
Reset< Number > mReset
Guard condition enabling the transition if satisfied.
Aggregation mAggregationSetting = Aggregation::none
Reset function.
std::size_t mClustering = 0
Aggregation settings.
bool mUrgent = false
Clustering: maximal number of discrete successors.
Number mTriggerTime = Number(-1)
Flag if transition is urgent.
std::vector< Label > mLabels = std::vector<Label>()
Trigger-time: if positive acts as an additional guard.
std::size_t mHash = 0
Friends
std::ostream & operator<< (std::ostream &ostr, const Transition< Number > &t)
Outstream operator.
bool operator== (const Transition< Number > &lhs, const Transition< Number > &rhs)
Equality comparison operator.
bool operator!= (const Transition< Number > &lhs, const Transition< Number > &rhs)
Inequality comparison operator.
bool operator== (const std::set< std::unique_ptr< Transition< Number >>> &lhs, const std::set< std::unique_ptr< Transition< Number >>> &rhs)
Equality operator for sets of unique pointers to transitions.
Detailed Description
template<typename Number>
class hypro::Transition< Number >
Class for transition.
Template Parameters
Number The used number type.
Definition at line 23 of file Location.h.
Constructor & Destructor Documentation
template<typename Number> hypro::Transition< Number >::Transition () default
Default constructor.
template<typename Number> hypro::Transition< Number >::Transition (const Transition< Number > & orig) default
Copy constructor.
Parameters
[in] orig The original.
template<typename Number> hypro::Transition< Number >::Transition (Transition< Number > && orig) default
Move constructor.
Parameters
[in] orig The original.
template<typename Number> hypro::Transition< Number >::~Transition () inline
Destroys the object.
Definition at line 82 of file Transition.h.
template<typename Number> hypro::Transition< Number >::Transition (Location< Number > * source, Location< Number > * target) inline
Constructor from source and target location.
Parameters
source The source
target The target
Definition at line 89 of file Transition.h.
template<typename Number> hypro::Transition< Number >::Transition (Location< Number > * source, Location< Number > * target, const Condition< Number > & guard, const Reset< Number > & reset) inline
Full constructor for basic transition.
Parameters
source The source.
target The target.
[in] guard The guard.
[in] reset The reset.
Definition at line 105 of file Transition.h.
Member Function Documentation
template<typename Number> void hypro::Transition< Number >::addLabel (const Label & lab) inline
Definition at line 180 of file Transition.h.
template<typename Number> void hypro::Transition< Number >::decompose (const Decomposition & decomposition) inline
decomposes guard and reset of this transition.
Definition at line 202 of file Transition.h.
template<typename Number> Aggregation hypro::Transition< Number >::getAggregation () const inline
Definition at line 124 of file Transition.h.
Referenced by hypro::updateTiming().
template<typename Number> std::size_t hypro::Transition< Number >::getClusterBound () const inline
Definition at line 125 of file Transition.h.
template<typename Number> std::string hypro::Transition< Number >::getDotRepresentation (const std::vector< std::string > & vars) const
Referenced by hypro::Transition< N >::addLabel().
template<typename Number> const Condition<Number>& hypro::Transition< Number >::getGuard () const inline
Definition at line 122 of file Transition.h.
Referenced by std::hash< hypro::Transition< Number > >::operator()().
template<typename Number> const std::vector<Label>& hypro::Transition< Number >::getLabels () const inline
Definition at line 130 of file Transition.h.
template<typename Number> const Reset<Number>& hypro::Transition< Number >::getReset () const inline
Definition at line 123 of file Transition.h.
Referenced by std::hash< hypro::Transition< Number > >::operator()().
template<typename Number> Location<Number>* hypro::Transition< Number >::getSource () const inline
Definition at line 114 of file Transition.h.
Referenced by std::hash< hypro::Transition< Number > >::operator()().
template<typename Number> Location<Number>* hypro::Transition< Number >::getTarget () const inline
Definition at line 118 of file Transition.h.
Referenced by std::hash< hypro::Transition< Number > >::operator()(), and hypro::updateTiming().
template<typename Number> Number hypro::Transition< Number >::getTriggerTime () const inline
Definition at line 126 of file Transition.h.
template<typename Number> std::size_t hypro::Transition< Number >::hash () const
Referenced by hypro::Transition< N >::getLabels().
template<typename Number> bool hypro::Transition< Number >::hasIdentityReset () const inline
Definition at line 129 of file Transition.h.
template<typename Number> bool hypro::Transition< Number >::isComposedOf (const Transition< Number > & rhs, const std::vector< std::string > & rhsVars, const std::vector< std::string > & thisVars) const
Determines if this composed of rhs and a potential rest.
Checks whether this transition can be the result of a parallel composition where rhs was part of one composite.
Parameters
[in] rhs The right hand side
[in] rhsVars The right hand side variables
[in] thisVars The variables of this
Returns
True if composed of, False otherwise.
Referenced by hypro::Transition< N >::addLabel().
template<typename Number> bool hypro::Transition< Number >::isTimeTriggered () const inline
Definition at line 128 of file Transition.h.
template<typename Number> bool hypro::Transition< Number >::isUrgent () const inline
Definition at line 127 of file Transition.h.
template<typename Number> Transition& hypro::Transition< Number >::operator= (const Transition< Number > & orig) default
Copy assignment operator.
Parameters
[in] orig The original.
Returns
A copy of the passed transition.
template<typename Number> Transition& hypro::Transition< Number >::operator= (Transition< Number > && orig) default
Move assignment operator.
Parameters
[in] orig The original.
Returns
Result.
template<typename Number> void hypro::Transition< Number >::setAggregation (Aggregation agg) inline
Definition at line 157 of file Transition.h.
template<typename Number> void hypro::Transition< Number >::setClusterBound (std::size_t cluster) inline
Definition at line 164 of file Transition.h.
template<typename Number> void hypro::Transition< Number >::setGuard (const Condition< Number > & guard) inline
Definition at line 149 of file Transition.h.
template<typename Number> void hypro::Transition< Number >::setLabels (const std::vector< Label > & labels) inline
Definition at line 176 of file Transition.h.
template<typename Number> void hypro::Transition< Number >::setReset (const Reset< Number > & val) inline
Definition at line 153 of file Transition.h.
template<typename Number> void hypro::Transition< Number >::setSource (Location< Number > * source) inline
Definition at line 133 of file Transition.h.
template<typename Number> void hypro::Transition< Number >::setSource (std::unique_ptr< Location< Number >> & source) inline
Definition at line 141 of file Transition.h.
template<typename Number> void hypro::Transition< Number >::setTarget (Location< Number > * target) inline
Definition at line 137 of file Transition.h.
template<typename Number> void hypro::Transition< Number >::setTarget (std::unique_ptr< Location< Number >> & target) inline
Definition at line 145 of file Transition.h.
template<typename Number> void hypro::Transition< Number >::setTriggerTime (Number t) inline
Definition at line 172 of file Transition.h.
template<typename Number> void hypro::Transition< Number >::setUrgent (bool urgent = true) inline
Definition at line 168 of file Transition.h.
Friends And Related Function Documentation
template<typename Number> bool operator!= (const Transition< Number > & lhs, const Transition< Number > & rhs) friend
Inequality comparison operator.
Parameters
[in] lhs The left hand side
[in] rhs The right hand side Qreturn True if both transitions are unequal, false otherwise
Definition at line 260 of file Transition.h.
template<typename Number> std::ostream& operator<< (std::ostream & ostr, const Transition< Number > & t) friend
Outstream operator.
Parameters
ostr The outstream.
[in] t The transition.
Returns
Reference to the outstream.
Definition at line 214 of file Transition.h.
template<typename Number> bool operator== (const Transition< Number > & lhs, const Transition< Number > & rhs) friend
Equality comparison operator.
Parameters
[in] lhs The left hand side.
[in] rhs The right hand side.
Returns
True if both transitions are equal, false otherwise.
Definition at line 237 of file Transition.h.
template<typename Number> bool operator== (const std::set< std::unique_ptr< Transition< Number >>> & lhs, const std::set< std::unique_ptr< Transition< Number >>> & rhs) friend
Equality operator for sets of unique pointers to transitions.
First tests whether the size of the sets are equal. Then compares the transitions the unique pointers point to for equality.
Parameters
[in] lhs left hand side; first set to compare
[in] rhs right hand sid; second set to compare
Definition at line 270 of file Transition.h.
Member Data Documentation
template<typename Number> Aggregation hypro::Transition< Number >::mAggregationSetting = Aggregation::none private
Reset function.
Definition at line 40 of file Transition.h.
Referenced by hypro::Transition< N >::getAggregation().
template<typename Number> std::size_t hypro::Transition< Number >::mClustering = 0 private
Aggregation settings.
Definition at line 41 of file Transition.h.
Referenced by hypro::Transition< N >::getClusterBound().
template<typename Number> Condition<Number> hypro::Transition< Number >::mGuard private
Pointer to the target location.
Definition at line 38 of file Transition.h.
Referenced by hypro::Transition< N >::getGuard().
template<typename Number> std::size_t hypro::Transition< Number >::mHash = 0 mutable private
Definition at line 45 of file Transition.h.
template<typename Number> std::vector<Label> hypro::Transition< Number >::mLabels = std::vector<Label>() private
Trigger-time: if positive acts as an additional guard.
Definition at line 44 of file Transition.h.
Referenced by hypro::Transition< N >::getLabels().
template<typename Number> Reset<Number> hypro::Transition< Number >::mReset private
Guard condition enabling the transition if satisfied.
Definition at line 39 of file Transition.h.
Referenced by hypro::Transition< N >::getReset().
template<typename Number> Location<Number>* hypro::Transition< Number >::mSource = nullptr private
Definition at line 36 of file Transition.h.
Referenced by hypro::Transition< N >::getSource().
template<typename Number> Location<Number>* hypro::Transition< Number >::mTarget = nullptr private
Pointer to the source location.
Definition at line 37 of file Transition.h.
Referenced by hypro::Transition< N >::getTarget().
template<typename Number> Number hypro::Transition< Number >::mTriggerTime = Number(-1) private
Flag if transition is urgent.
Definition at line 43 of file Transition.h.
Referenced by hypro::Transition< N >::getTriggerTime().
template<typename Number> bool hypro::Transition< Number >::mUrgent = false private
Clustering: maximal number of discrete successors.
Definition at line 42 of file Transition.h.
Referenced by hypro::Transition< N >::isUrgent().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/Location.h
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/Transition.h