HyPro: hypro::affineFlow< Number > Class Template Reference
hypro::affineFlow< Number > Class Template Reference
Public Member Functions
affineFlow ()=default
affineFlow (const affineFlow< Number > &in)=default
affineFlow (const matrix_t< Number > &A, const vector_t< Number > &b)
virtual ~affineFlow ()
std::size_t dimension () const
void setTranslation (const vector_t< Number > &newB)
const vector_t< Number > & getTranslation () const
bool hasTranslation () const
bool isTimed () const
bool isDiscrete () const
Public Member Functions inherited from hypro::linearFlow< Number >
linearFlow ()=default
linearFlow (const linearFlow &in)=default
linearFlow (const matrix_t< Number > A)
virtual ~linearFlow ()
std::size_t dimension () const
std::size_t size () const
void setFlowMatrix (const matrix_t< Number > &newA)
void addRow (const vector_t< Number > &row)
const matrix_t< Number > & getFlowMatrix () const
matrix_t< Number > & rGetFlowMatrix ()
bool isIdentity () const
bool hasNoFlow () const
bool isTimed () const
bool isDiscrete () const
Static Public Member Functions
static DynamicType type ()
Static Public Member Functions inherited from hypro::linearFlow< Number >
static DynamicType type ()
Protected Attributes
vector_t< Number > mTranslation
TRIBOOL mIsNoTranslation = TRIBOOL::NSET
Protected Attributes inherited from hypro::linearFlow< Number >
matrix_t< Number > mFlowMatrix = matrix_t<Number>(0, 0)
TRIBOOL mIsIdentity = TRIBOOL::NSET
TRIBOOL mNoFlow = TRIBOOL::NSET
Friends
bool operator== (const affineFlow< Number > &lhs, const affineFlow< Number > &rhs)
bool operator!= (const affineFlow< Number > &lhs, const affineFlow< Number > &rhs)
std::ostream & operator<< (std::ostream &out, const affineFlow< Number > &in)
Detailed Description
template<typename Number>
class hypro::affineFlow< Number >
Definition at line 10 of file affine.h.
Constructor & Destructor Documentation
template<typename Number> hypro::affineFlow< Number >::affineFlow () default
template<typename Number> hypro::affineFlow< Number >::affineFlow (const affineFlow< Number > & in) default
template<typename Number> hypro::affineFlow< Number >::affineFlow (const matrix_t< Number > & A, const vector_t< Number > & b) inline
Definition at line 19 of file affine.h.
template<typename Number> virtual hypro::affineFlow< Number >::~affineFlow () inline virtual
Definition at line 23 of file affine.h.
Member Function Documentation
template<typename Number> std::size_t hypro::affineFlow< Number >::dimension () const inline
Definition at line 26 of file affine.h.
References hypro::linearFlow< Number >::dimension().
template<typename Number> const vector_t<Number>& hypro::affineFlow< Number >::getTranslation () const inline
Definition at line 32 of file affine.h.
References hypro::affineFlow< Number >::mTranslation.
Referenced by std::hash< hypro::affineFlow< Number > >::operator()().
template<typename Number> bool hypro::affineFlow< Number >::hasTranslation () const inline
Definition at line 34 of file affine.h.
References hypro::FALSE, hypro::NSET, and hypro::TRUE.
Referenced by hypro::affineFlow< Number >::isDiscrete().
template<typename Number> bool hypro::affineFlow< Number >::isDiscrete () const inline
Definition at line 55 of file affine.h.
References hypro::linearFlow< Number >::hasNoFlow(), and hypro::affineFlow< Number >::hasTranslation().
template<typename Number> bool hypro::affineFlow< Number >::isTimed () const inline
Definition at line 46 of file affine.h.
References hypro::linearFlow< Number >::hasNoFlow().
template<typename Number> void hypro::affineFlow< Number >::setTranslation (const vector_t< Number > & newB) inline
Definition at line 28 of file affine.h.
References hypro::NSET.
template<typename Number> static DynamicType hypro::affineFlow< Number >::type () inline static
Definition at line 25 of file affine.h.
References hypro::affine.
Friends And Related Function Documentation
template<typename Number> bool operator!= (const affineFlow< Number > & lhs, const affineFlow< Number > & rhs) friend
Definition at line 63 of file affine.h.
template<typename Number> std::ostream& operator<< (std::ostream & out, const affineFlow< Number > & in) friend
Definition at line 67 of file affine.h.
template<typename Number> bool operator== (const affineFlow< Number > & lhs, const affineFlow< Number > & rhs) friend
Definition at line 59 of file affine.h.
Member Data Documentation
template<typename Number> TRIBOOL hypro::affineFlow< Number >::mIsNoTranslation = TRIBOOL::NSET mutable protected
Definition at line 14 of file affine.h.
template<typename Number> vector_t<Number> hypro::affineFlow< Number >::mTranslation protected
Definition at line 13 of file affine.h.
Referenced by hypro::affineFlow< Number >::getTranslation().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/flow/affine.h