HyPro: hypro::SingularAnalyzer< Representation > Class Template Reference
hypro::SingularAnalyzer< Representation > Class Template Reference
Class which implements a forward reachability analysis method for singular automata.
Public Types
using SingularResult = AnalysisResult< VerificationSuccess, Failure< Representation >>
Public Member Functions
SingularAnalyzer ()=delete
Default constructor (deleted).
SingularAnalyzer (HybridAutomaton< Number > const &ha, FixedAnalysisParameters const &fixedParameters, std::vector< ReachTreeNode< Representation >> &roots)
Construct a new Singular Analyzer object.
SingularResult run ()
Main method for reachability analysis. Calls the method forwardRun.
SingularResult forwardRun ()
Execute forward reachability result.
Protected Attributes
HybridAutomaton< Number > const * mHybridAutomaton
Automaton which is analyzed.
FixedAnalysisParameters mAnalysisSettings
Settings used for analysis.
std::vector< ReachTreeNode< Representation > > & mReachTree
Forest of ReachTrees computed.
std::deque< ReachTreeNode< Representation > * > mWorkQueue
Queue holds all nodes that require processing.
Detailed Description
template<typename Representation>
class hypro::SingularAnalyzer< Representation >
Class which implements a forward reachability analysis method for singular automata.
Requires the usage of a suitable state set representation, e.g., carlPolytope.
Template Parameters
Representation The used state set representation.
Definition at line 22 of file SingularAnalyzer.h.
Constructor & Destructor Documentation
template<typename Representation> hypro::SingularAnalyzer< Representation >::SingularAnalyzer (HybridAutomaton< Number > const & ha, FixedAnalysisParameters const & fixedParameters, std::vector< ReachTreeNode< Representation >> & roots) inline
Construct a new Singular Analyzer object.
Parameters
ha The hybrid (singular) automaton
fixedParameters A parameter configuration (parameter timeStep is not used)
roots The root nodes of the search tree containing the initial states of ha
Definition at line 40 of file SingularAnalyzer.h.
Member Function Documentation
template<typename Representation > SingularAnalyzer< Representation >::SingularResult hypro::SingularAnalyzer< Representation >::forwardRun ()
Execute forward reachability result.
Returns
SAFE if no bad state intersection is found and UNKNOWN otherwise.
Definition at line 11 of file SingularAnalyzer.tpp.
References hypro::ReachTreeNode< State >::addChild(), hypro::TreeNode< Data >::getDepth(), and hypro::ReachTreeNode< State >::getFlowpipe().
template<typename Representation > SingularAnalyzer< Representation >::SingularResult hypro::SingularAnalyzer< Representation >::run ()
Main method for reachability analysis. Calls the method forwardRun.
Returns
SAFE if no bad state intersection is found and UNKNOWN otherwise.
Definition at line 6 of file SingularAnalyzer.tpp.
Referenced by hypro::reachability::ReachSingular< Representation >::computeForwardReachability().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/analyzer/SingularAnalyzer.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/analyzer/SingularAnalyzer.tpp