HyPro: hypro::ContinuousSystem< Number > Class Template Reference
hypro::ContinuousSystem< Number > Class Template Reference
Public Member Functions
ContinuousSystem ()
ContinuousSystem (const PolynomialODE< Number > &ode_input, const Flowpipe< Number > &initialSet_input)
ContinuousSystem (const ContinuousSystem< Number > &system)
~ContinuousSystem ()
int reach_picard (std::list< Flowpipe< Number >> &result, const carl::Variable &t, const double time, const double stepsize, const exponent order, const Range< Number > &estimation) const
ContinuousSystem< Number > & operator= (const ContinuousSystem< Number > &system)
void output (std::ostream &os, const exponent order)
Protected Attributes
PolynomialODE< Number > ode
Flowpipe< Number > initialSet
Detailed Description
template<typename Number>
class hypro::ContinuousSystem< Number >
Definition at line 44 of file continuous.h.
Constructor & Destructor Documentation
template<typename Number > hypro::ContinuousSystem< Number >::ContinuousSystem ()
Definition at line 266 of file continuous.tpp.
template<typename Number > hypro::ContinuousSystem< Number >::ContinuousSystem (const PolynomialODE< Number > & ode_input, const Flowpipe< Number > & initialSet_input)
Definition at line 270 of file continuous.tpp.
template<typename Number > hypro::ContinuousSystem< Number >::ContinuousSystem (const ContinuousSystem< Number > & system)
Definition at line 277 of file continuous.tpp.
References hypro::ContinuousSystem< Number >::initialSet, and hypro::ContinuousSystem< Number >::ode.
template<typename Number > hypro::ContinuousSystem< Number >::~ContinuousSystem ()
Definition at line 283 of file continuous.tpp.
Member Function Documentation
template<typename Number > ContinuousSystem< Number > & hypro::ContinuousSystem< Number >::operator= (const ContinuousSystem< Number > & system)
Definition at line 318 of file continuous.tpp.
References hypro::ContinuousSystem< Number >::initialSet, and hypro::ContinuousSystem< Number >::ode.
template<typename Number > void hypro::ContinuousSystem< Number >::output (std::ostream & os, const exponent order)
Definition at line 328 of file continuous.tpp.
References hypro::ContinuousSystem< Number >::output().
Referenced by hypro::ContinuousSystem< Number >::output().
template<typename Number > int hypro::ContinuousSystem< Number >::reach_picard (std::list< Flowpipe< Number >> & result, const carl::Variable & t, const double time, const double stepsize, const exponent order, const Range< Number > & estimation) const
Definition at line 287 of file continuous.tpp.
References hypro::Flowpipe< State >::next_picard().
Member Data Documentation
template<typename Number> Flowpipe<Number> hypro::ContinuousSystem< Number >::initialSet protected
Definition at line 47 of file continuous.h.
Referenced by hypro::ContinuousSystem< Number >::ContinuousSystem(), and hypro::ContinuousSystem< Number >::operator=().
template<typename Number> PolynomialODE<Number> hypro::ContinuousSystem< Number >::ode protected
Definition at line 46 of file continuous.h.
Referenced by hypro::ContinuousSystem< Number >::ContinuousSystem(), and hypro::ContinuousSystem< Number >::operator=().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/TaylorModel/continuous.h
/home/travis/build/hypro/hypro/src/hypro/representations/TaylorModel/continuous.tpp