HyPro: hypro::Fan< Number > Class Template Reference
hypro::Fan< Number > Class Template Reference
Class for a polytopal fan.
#include <Fan.h>
Public Types
using cones = std::vector< const Cone< Number > * >
Public Member Functions
Fan ()
~Fan ()
Fan (const Fan &_orig)
const cones & get () const
const Cone< Number > * get (unsigned _index) const
unsigned dimension () const
unsigned size () const
void add (const Cone< Number > *_cone)
const Cone< Number > * containingCone (const Point< Number > &_vector) const
Fan< Number > operator= (const Fan< Number > &_rhs)
Private Attributes
cones mCones
unsigned mDimension
Detailed Description
template<typename Number>
class hypro::Fan< Number >
Class for a polytopal fan.
Template Parameters
Number The used number type.
Definition at line 18 of file Fan.h.
Member Typedef Documentation
template<typename Number> using hypro::Fan< Number >::cones = std::vector<const Cone<Number>*>
Definition at line 20 of file Fan.h.
Constructor & Destructor Documentation
template<typename Number> hypro::Fan< Number >::Fan () inline
Definition at line 27 of file Fan.h.
template<typename Number> hypro::Fan< Number >::~Fan () inline
Definition at line 31 of file Fan.h.
template<typename Number> hypro::Fan< Number >::Fan (const Fan< Number > & _orig) inline
Definition at line 33 of file Fan.h.
Member Function Documentation
template<typename Number> void hypro::Fan< Number >::add (const Cone< Number > * _cone) inline
Definition at line 52 of file Fan.h.
References hypro::Cone< Number >::dimension(), and hypro::Fan< Number >::mDimension.
template<typename Number> const Cone<Number>* hypro::Fan< Number >::containingCone (const Point< Number > & _vector) const inline
Definition at line 57 of file Fan.h.
References constraints(), i, hypro::Fan< Number >::mDimension, and hypro::Cone< Number >::size().
template<typename Number> unsigned hypro::Fan< Number >::dimension () const inline
Definition at line 48 of file Fan.h.
References hypro::Fan< Number >::mDimension.
Referenced by hypro::Fan< Number >::operator=().
template<typename Number> const cones& hypro::Fan< Number >::get () const inline
Definition at line 41 of file Fan.h.
References hypro::Fan< Number >::mCones.
Referenced by hypro::Fan< Number >::operator=().
template<typename Number> const Cone<Number>* hypro::Fan< Number >::get (unsigned _index) const inline
Definition at line 43 of file Fan.h.
References assert().
template<typename Number> Fan<Number> hypro::Fan< Number >::operator= (const Fan< Number > & _rhs) inline
Definition at line 84 of file Fan.h.
References hypro::Fan< Number >::dimension(), and hypro::Fan< Number >::get().
template<typename Number> unsigned hypro::Fan< Number >::size () const inline
Definition at line 50 of file Fan.h.
Member Data Documentation
template<typename Number> cones hypro::Fan< Number >::mCones private
Definition at line 23 of file Fan.h.
Referenced by hypro::Fan< Number >::get().
template<typename Number> unsigned hypro::Fan< Number >::mDimension private
Definition at line 24 of file Fan.h.
Referenced by hypro::Fan< Number >::add(), hypro::Fan< Number >::containingCone(), and hypro::Fan< Number >::dimension().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/Polytopes/Fan.h