HyPro: hypro::Flowpipe< State > Class Template Reference
hypro::Flowpipe< State > Class Template Reference
Container for a flowpipe, i.e. an ordered sequence of state sets (flowpipe segments).
Public Member Functions
Flowpipe ()
~Flowpipe ()
void setStates (const States &states)
void setStates (States &&states)
void addState (const State &state)
void addState (State &&state)
const States & getStates () const
States & rGetStates ()
Range< States > selectTimestamps (const carl::Interval< tNumber > &span)
template<typename Number >
Range< States > selectSatisfyingStates (const Condition< Number > &cond)
std::vector< PlotData< State > > getPlotData (std::size_t refinementLevel=0, std::size_t threadId=0) const
States::iterator begin ()
States::iterator end ()
States::const_iterator begin () const
States::const_iterator end () const
std::size_t size () const
Flowpipe ()
Flowpipe (const TaylorModelVec< Number > &tmv_input, const Domain< Number > &domain_input)
Flowpipe (const Flowpipe< Number > &flowpipe)
~Flowpipe ()
void clear ()
void enclosure (Range< Number > &range)
void enclosure (Range< Number > &range, const exponent order)
void composition (TaylorModelVec< Number > &result, Domain< Number > &fp_domain, const exponent order)
template<class Setting >
int next_picard (Flowpipe< Number > &result, const PolynomialODE< Number > &ode, const carl::Variable &t, const double stepsize, const exponent order, const Range< Number > &estimation)
Flowpipe< Number > & operator= (const Flowpipe< Number > &flowpipe)
void output (std::ostream &os, const exponent order)
Protected Attributes
TaylorModelVec< Number > tmvPre
TaylorModelVec< Number > tmv
Domain< Number > domain
Detailed Description
template<typename State>
class hypro::Flowpipe< State >
Container for a flowpipe, i.e. an ordered sequence of state sets (flowpipe segments).
Template Parameters
State Used state type.
Definition at line 18 of file Flowpipe.h.
Constructor & Destructor Documentation
template<typename Number > hypro::Flowpipe< Number >::Flowpipe ()
Definition at line 5 of file Flowpipe.tpp.
template<typename Number > hypro::Flowpipe< Number >::~Flowpipe ()
Definition at line 9 of file Flowpipe.tpp.
template<typename State> hypro::Flowpipe< State >::Flowpipe ()
template<typename Number > hypro::Flowpipe< Number >::Flowpipe (const TaylorModelVec< Number > & tmv_input, const Domain< Number > & domain_input)
Definition at line 17 of file continuous.tpp.
template<typename Number > hypro::Flowpipe< Number >::Flowpipe (const Flowpipe< Number > & flowpipe)
Definition at line 23 of file continuous.tpp.
References hypro::Flowpipe< State >::domain, hypro::Flowpipe< State >::tmv, and hypro::Flowpipe< State >::tmvPre.
template<typename State> hypro::Flowpipe< State >::~Flowpipe ()
Member Function Documentation
template<typename State> void hypro::Flowpipe< State >::addState (const State & state) inline
Definition at line 30 of file Flowpipe.h.
template<typename State> void hypro::Flowpipe< State >::addState (State && state) inline
Definition at line 31 of file Flowpipe.h.
template<typename State> States::iterator hypro::Flowpipe< State >::begin () inline
Definition at line 46 of file Flowpipe.h.
template<typename State> States::const_iterator hypro::Flowpipe< State >::begin () const inline
Definition at line 48 of file Flowpipe.h.
template<typename Number > void hypro::Flowpipe< Number >::clear ()
Definition at line 34 of file continuous.tpp.
References hypro::Flowpipe< State >::clear().
Referenced by hypro::Flowpipe< State >::clear().
template<typename Number > void hypro::Flowpipe< Number >::composition (TaylorModelVec< Number > & result, Domain< Number > & fp_domain, const exponent order)
Definition at line 70 of file continuous.tpp.
References hypro::TaylorModelVec< Number >::substitute().
template<typename Number > void hypro::Flowpipe< Number >::enclosure (Range< Number > & range)
Definition at line 40 of file continuous.tpp.
References hypro::Flowpipe< State >::enclosure(), hypro::TaylorModelVec< Number >::enclosure(), and hypro::TaylorModelVec< Number >::substitute().
Referenced by hypro::Flowpipe< State >::enclosure().
template<typename Number > void hypro::Flowpipe< Number >::enclosure (Range< Number > & range, const exponent order)
Definition at line 60 of file continuous.tpp.
References hypro::Flowpipe< State >::enclosure(), hypro::TaylorModelVec< Number >::enclosure(), and hypro::TaylorModelVec< Number >::substitute().
template<typename State> States::iterator hypro::Flowpipe< State >::end () inline
Definition at line 47 of file Flowpipe.h.
template<typename State> States::const_iterator hypro::Flowpipe< State >::end () const inline
Definition at line 49 of file Flowpipe.h.
template<typename State > std::vector< PlotData< State > > hypro::Flowpipe< State >::getPlotData (std::size_t refinementLevel = 0, std::size_t threadId = 0) const
Definition at line 13 of file Flowpipe.tpp.
Referenced by hypro::Flowpipe< Number >::selectSatisfyingStates().
template<typename State> const States& hypro::Flowpipe< State >::getStates () const inline
Definition at line 33 of file Flowpipe.h.
template<typename Number > template<class Setting > int hypro::Flowpipe< Number >::next_picard (Flowpipe< Number > & result, const PolynomialODE< Number > & ode, const carl::Variable & t, const double stepsize, const exponent order, const Range< Number > & estimation)
Definition at line 82 of file continuous.tpp.
References hypro::Domain< Number >::assign(), hypro::TaylorModelVec< Number >::assign(), hypro::Flowpipe< State >::domain, hypro::TaylorModelVec< Number >::enclosure(), hypro::Range< Number >::find_assignment(), hypro::Range< Number >::get_assignments(), hypro::TaylorModelVec< Number >::Picard(), hypro::TaylorModelVec< Number >::Picard_assign(), hypro::TaylorModelVec< Number >::rmConstantTerm(), hypro::TaylorModelVec< Number >::substitute(), hypro::TaylorModelVec< Number >::tms, hypro::Flowpipe< State >::tmv, and hypro::Flowpipe< State >::tmvPre.
Referenced by hypro::ContinuousSystem< Number >::reach_picard().
template<typename Number > Flowpipe< Number > & hypro::Flowpipe< Number >::operator= (const Flowpipe< Number > & flowpipe)
Definition at line 240 of file continuous.tpp.
References hypro::Flowpipe< State >::domain, hypro::Flowpipe< State >::tmv, and hypro::Flowpipe< State >::tmvPre.
template<typename Number > void hypro::Flowpipe< Number >::output (std::ostream & os, const exponent order)
Definition at line 251 of file continuous.tpp.
template<typename State> States& hypro::Flowpipe< State >::rGetStates () inline
Definition at line 34 of file Flowpipe.h.
template<typename State> template<typename Number > Range<States> hypro::Flowpipe< State >::selectSatisfyingStates (const Condition< Number > & cond) inline
Definition at line 40 of file Flowpipe.h.
template<typename State> Range<States> hypro::Flowpipe< State >::selectTimestamps (const carl::Interval< tNumber > & span) inline
Definition at line 35 of file Flowpipe.h.
template<typename State> void hypro::Flowpipe< State >::setStates (const States & states) inline
Definition at line 28 of file Flowpipe.h.
template<typename State> void hypro::Flowpipe< State >::setStates (States && states) inline
Definition at line 29 of file Flowpipe.h.
template<typename State> std::size_t hypro::Flowpipe< State >::size () const inline
Definition at line 51 of file Flowpipe.h.
Member Data Documentation
template<typename State> Domain<Number> hypro::Flowpipe< State >::domain protected
Definition at line 20 of file continuous.h.
Referenced by hypro::Flowpipe< State >::Flowpipe(), hypro::Flowpipe< State >::next_picard(), and hypro::Flowpipe< State >::operator=().
template<typename State> TaylorModelVec<Number> hypro::Flowpipe< State >::tmv protected
Definition at line 19 of file continuous.h.
Referenced by hypro::Flowpipe< State >::Flowpipe(), hypro::Flowpipe< State >::next_picard(), and hypro::Flowpipe< State >::operator=().
template<typename State> TaylorModelVec<Number> hypro::Flowpipe< State >::tmvPre protected
Definition at line 18 of file continuous.h.
Referenced by hypro::Flowpipe< State >::Flowpipe(), hypro::Flowpipe< State >::next_picard(), and hypro::Flowpipe< State >::operator=().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/Flowpipe.h
/home/travis/build/hypro/hypro/src/hypro/representations/TaylorModel/continuous.h
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/Flowpipe.tpp
/home/travis/build/hypro/hypro/src/hypro/representations/TaylorModel/continuous.tpp