HyPro: hypro::PrincipalComponentAnalysis< Number > Class Template Reference
hypro::PrincipalComponentAnalysis< Number > Class Template Reference
Public Member Functions
PrincipalComponentAnalysis ()=default
PrincipalComponentAnalysis (const std::vector< Point< Number >> &samples)
PrincipalComponentAnalysis (const PrincipalComponentAnalysis< Number > &orig)=default
const Point< Number > & mean () const
const std::vector< Point< Number > > & samples () const
const std::vector< Halfspace< Number > > box () const
void setSamples (const std::vector< Point< Number >> &samples)
void computeMean () const
void computeOrientedBox () const
Detailed Description
template<typename Number>
class hypro::PrincipalComponentAnalysis< Number >
Definition at line 18 of file pca.h.
Constructor & Destructor Documentation
template<typename Number> hypro::PrincipalComponentAnalysis< Number >::PrincipalComponentAnalysis () default
Referenced by hypro::PrincipalComponentAnalysis< Number >::PrincipalComponentAnalysis().
template<typename Number> hypro::PrincipalComponentAnalysis< Number >::PrincipalComponentAnalysis (const std::vector< Point< Number >> & samples) inline
Definition at line 28 of file pca.h.
References hypro::PrincipalComponentAnalysis< Number >::mean(), and hypro::PrincipalComponentAnalysis< Number >::PrincipalComponentAnalysis().
template<typename Number> hypro::PrincipalComponentAnalysis< Number >::PrincipalComponentAnalysis (const PrincipalComponentAnalysis< Number > & orig) default
Member Function Documentation
template<typename Number > const std::vector< Halfspace< Number > > hypro::PrincipalComponentAnalysis< Number >::box () const
Definition at line 15 of file pca.tpp.
Referenced by hypro::PrincipalComponentAnalysis< Number >::samples(), hypro::Converter< Number >::toHPolytope(), and hypro::Converter< Number >::toZonotope().
template<typename Number > void hypro::PrincipalComponentAnalysis< Number >::computeMean () const
Definition at line 32 of file pca.tpp.
Referenced by hypro::PrincipalComponentAnalysis< Number >::samples().
template<typename Number > void hypro::PrincipalComponentAnalysis< Number >::computeOrientedBox () const
Definition at line 46 of file pca.tpp.
Referenced by hypro::PrincipalComponentAnalysis< Number >::samples().
template<typename Number> const Point<Number>& hypro::PrincipalComponentAnalysis< Number >::mean () const
Referenced by hypro::PrincipalComponentAnalysis< Number >::PrincipalComponentAnalysis().
template<typename Number> const std::vector<Point<Number> >& hypro::PrincipalComponentAnalysis< Number >::samples () const inline
Definition at line 38 of file pca.h.
References hypro::PrincipalComponentAnalysis< Number >::box(), hypro::PrincipalComponentAnalysis< Number >::computeMean(), hypro::PrincipalComponentAnalysis< Number >::computeOrientedBox(), and hypro::PrincipalComponentAnalysis< Number >::setSamples().
template<typename Number > void hypro::PrincipalComponentAnalysis< Number >::setSamples (const std::vector< Point< Number >> & samples)
Definition at line 24 of file pca.tpp.
Referenced by hypro::PrincipalComponentAnalysis< Number >::samples().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/util/pca.h
/home/travis/build/hypro/hypro/src/hypro/util/pca.tpp