HyPro: ObjectHandle Class Reference
ObjectHandle Class Reference
#include <ObjectHandle.h>
Public Types
using flowpipe = std::vector< hypro::State_t< double >>
Static Public Member Functions
template<typename T >
static void pair2Matlab (const std::pair< T, T > &, mxArray *, const int, const int)
template<typename T >
static std::vector< T > objArray2Hypro (const mxArray *, const int)
template<typename T >
static void objArray2Matlab (const std::vector< T > &, mxArray *, const int)
template<typename T >
static void vector2Matlab (const std::vector< T > &, mxArray *)
template<typename T >
static void vector2Matlab (const std::vector< T > &, mxArray *, mxArray *)
static void flowpipes2Matlab (const std::vector< std::pair< unsigned, flowpipe >> &, mxArray *, const int)
static void convert2Matlab (const carl::Interval< double > &, mxArray *, const int, const int, const int=0)
static void convert2Matlab (const hypro::matrix_t< double > &, mxArray *, const int, const int, const int=0)
static void convert2Matlab (const hypro::vector_t< double > &, mxArray *, const int, const int, const int=0)
static void convert2Matlab (const hypro::Point< double > &, mxArray *, const int, const int, const int=0)
static void convert2Matlab (const hypro::EvaluationResult< double > &, mxArray *, const int, const int, const int=0)
static void convert2Matlab (const hypro::Halfspace< double > &, mxArray *, mxArray *, const int, const int, const int=0)
static void convert2Matlab (const hypro::CONTAINMENT &, std::string &)
static void convert2Matlab (const hypro::SOLUTION &, std::string &)
static void convert2Matlab (const hypro::representation_name &, std::string &)
static void convert2Matlab (const std::vector< std::string > &, mxArray *, const mwSize *)
static void convert2Matlab (const std::map< const hypro::Location< double > *, hypro::Condition< double >> &, mxArray *)
static void convert2Matlab (const std::vector< hypro::Point< double >> &, mxArray *)
static hypro::SOLUTION mSolution2Hypro (char *)
static hypro::representation_name mRepresentationName2Hypro (int type)
static carl::Interval< double > mInterval2Hypro (const mxArray *)
static carl::Interval< hypro::tNumber > mMPQInterval2Hypro (const mxArray *)
static hypro::matrix_t< double > mMatrix2Hypro (const mxArray *, const int, const int)
static hypro::vector_t< double > mVector2Hypro (const mxArray *, const int)
static hypro::Point< double > mPoint2Hypro (const mxArray *, const int)
static hypro::Halfspace< double > mHalfspace2Hypro (const mxArray *, const int, double)
static std::map< hypro::Location< double >, hypro::Condition< double > > mlocationConditionMap2Hypro (mxArray *, const int)
static std::vector< std::size_t > mSizeVector2Hypro (const mxArray *, const int)
static std::vector< carl::Interval< double > > mIntervals2Hypro (const mxArray *, const int=1, const int=2)
static std::vector< carl::Interval< double > > mPoints2Hypro (const mxArray *)
static std::pair< hypro::Point< double >, hypro::Point< double > > mPointPair2Hypro (const mxArray *)
static std::vector< hypro::Point< double > > mPointsVector2Hypro (const mxArray *, const int, const int)
static std::vector< hypro::Halfspace< double > > mHalfspaces2Hypro (mxArray *, mxArray *, const int, const int, const int)
static std::vector< carl::Term< double > > mMultivariatePoly2Hypro (const mxArray *)
static std::vector< std::vector< std::size_t > > mVectorOfVectors2Hypro (const mxArray *, const int, const int)
static std::vector< std::string > mStringVector2Hypro (const mxArray *)
static std::map< const hypro::Location< double > *, hypro::Condition< double > > mLocCondMap2Hypro (const mxArray *)
static std::vector< std::unique_ptr< hypro::Location< double > > > mLocsVector2Hypro (const mxArray *)
Detailed Description
Definition at line 28 of file ObjectHandle.h.
Member Typedef Documentation
using ObjectHandle::flowpipe = std::vector<hypro::State_t<double>>
Definition at line 30 of file ObjectHandle.h.
Member Function Documentation
void ObjectHandle::convert2Matlab (const carl::Interval< double > & inter, mxArray * m_out, const int rows, const int cols, const int index = 0) static
Definition at line 231 of file ObjectHandle.h.
References index, and out.
Referenced by pair2Matlab(), and vector2Matlab().
void ObjectHandle::convert2Matlab (const hypro::matrix_t< double > & matrix, mxArray * m_out, const int rows, const int cols, const int index = 0) static
Definition at line 244 of file ObjectHandle.h.
References cols, i, and out.
void ObjectHandle::convert2Matlab (const hypro::vector_t< double > & vec, mxArray * m_out, const int rows, const int cols, const int index = 0) static
Definition at line 276 of file ObjectHandle.h.
References i, out, and vec.
void ObjectHandle::convert2Matlab (const hypro::Point< double > & p, mxArray * m_out, const int rows, const int cols, const int index = 0) static
Definition at line 291 of file ObjectHandle.h.
References i, and out.
static void ObjectHandle::convert2Matlab (const hypro::EvaluationResult< double > & , mxArray * , const int , const int , const int = 0) static
void ObjectHandle::convert2Matlab (const hypro::Halfspace< double > & h, mxArray * m_normal_out, mxArray * m_offset_out, const int rows, const int cols, const int index = 0) static
Definition at line 306 of file ObjectHandle.h.
References cols, i, index, hypro::Halfspace< Number >::normal(), and hypro::Halfspace< Number >::offset().
void ObjectHandle::convert2Matlab (const hypro::CONTAINMENT & cont, std::string & out) static
Definition at line 325 of file ObjectHandle.h.
References hypro::BOT, hypro::FULL, hypro::NO, hypro::PARTIAL, and hypro::YES.
void ObjectHandle::convert2Matlab (const hypro::SOLUTION & sol, std::string & out) static
Definition at line 344 of file ObjectHandle.h.
References hypro::FEAS, hypro::INFEAS, hypro::INFTY, and hypro::UNKNOWN.
void ObjectHandle::convert2Matlab (const hypro::representation_name & name, std::string & out) static
Definition at line 361 of file ObjectHandle.h.
References box.
void ObjectHandle::convert2Matlab (const std::vector< std::string > & strings, mxArray * str_arr, const mwSize * dims) static
Definition at line 403 of file ObjectHandle.h.
References i.
void ObjectHandle::convert2Matlab (const std::map< const hypro::Location< double > *, hypro::Condition< double >> & locConmap, mxArray * m_array) static
Definition at line 213 of file ObjectHandle.h.
References cond, i, and loc.
void ObjectHandle::convert2Matlab (const std::vector< hypro::Point< double >> & points, mxArray * m_out) static
Definition at line 170 of file ObjectHandle.h.
References cols, dims, i, out, and points.
void ObjectHandle::flowpipes2Matlab (const std::vector< std::pair< unsigned, flowpipe >> & flowpipes, mxArray * m_out, const int rows) static
Definition at line 190 of file ObjectHandle.h.
References convertPtr2Mat(), dims, flowpipes, and i.
Referenced by MReach::computeForwardReachability().
hypro::Halfspace< double > ObjectHandle::mHalfspace2Hypro (const mxArray * m_normal, const int len, double offset) static
Definition at line 542 of file ObjectHandle.h.
References mVector2Hypro().
std::vector< hypro::Halfspace< double > > ObjectHandle::mHalfspaces2Hypro (mxArray * m_matrix, mxArray * m_offsets, const int rows, const int cols, const int len) static
Definition at line 606 of file ObjectHandle.h.
References i, mat, mMatrix2Hypro(), mVector2Hypro(), and vec.
carl::Interval< double > ObjectHandle::mInterval2Hypro (const mxArray * m_interval) static
Definition at line 447 of file ObjectHandle.h.
References interval.
std::vector< carl::Interval< double > > ObjectHandle::mIntervals2Hypro (const mxArray * m_intervals, const int rows = 1, const int cols = 2) static
Definition at line 430 of file ObjectHandle.h.
References cols, i, and intervals.
static std::map<hypro::Location<double>, hypro::Condition<double> > ObjectHandle::mlocationConditionMap2Hypro (mxArray * , const int) static
std::map< const hypro::Location< double > *, hypro::Condition< double > > ObjectHandle::mLocCondMap2Hypro (const mxArray * structArray) static
Definition at line 662 of file ObjectHandle.h.
References cols, cond, dims, hypro::Location< Number >::getName(), i, loc, name, and string().
std::vector< std::unique_ptr< hypro::Location< double > > > ObjectHandle::mLocsVector2Hypro (const mxArray * locsVector) static
Definition at line 682 of file ObjectHandle.h.
References l, loc, and locs.
hypro::matrix_t< double > ObjectHandle::mMatrix2Hypro (const mxArray * m_matrix, const int rows, const int cols) static
Definition at line 259 of file ObjectHandle.h.
References cols, i, and matrix.
Referenced by mHalfspaces2Hypro().
static carl::Interval<hypro::tNumber> ObjectHandle::mMPQInterval2Hypro (const mxArray *) static
static std::vector<carl::Term<double> > ObjectHandle::mMultivariatePoly2Hypro (const mxArray *) static
hypro::Point< double > ObjectHandle::mPoint2Hypro (const mxArray * m_vec, const int cols) static
Definition at line 484 of file ObjectHandle.h.
References cols, i, point, temp, and vec.
std::pair< hypro::Point< double >, hypro::Point< double > > ObjectHandle::mPointPair2Hypro (const mxArray * m_mat) static
Definition at line 498 of file ObjectHandle.h.
References dims, i, and mat.
std::vector< carl::Interval< double > > ObjectHandle::mPoints2Hypro (const mxArray * m_points) static
Definition at line 457 of file ObjectHandle.h.
References points.
std::vector< hypro::Point< double > > ObjectHandle::mPointsVector2Hypro (const mxArray * m_vec, const int rows, const int cols) static
Definition at line 522 of file ObjectHandle.h.
References cols, i, and points.
hypro::representation_name ObjectHandle::mRepresentationName2Hypro (int type) static
Definition at line 568 of file ObjectHandle.h.
References box.
std::vector< std::size_t > ObjectHandle::mSizeVector2Hypro (const mxArray * m_sizes, const int v_len) static
Definition at line 416 of file ObjectHandle.h.
References i, and vec.
hypro::SOLUTION ObjectHandle::mSolution2Hypro (char * mSol) static
Definition at line 552 of file ObjectHandle.h.
References hypro::FEAS, hypro::INFEAS, hypro::INFTY, and hypro::UNKNOWN.
std::vector< std::string > ObjectHandle::mStringVector2Hypro (const mxArray * strings) static
Definition at line 643 of file ObjectHandle.h.
References i, string(), and vec.
hypro::vector_t< double > ObjectHandle::mVector2Hypro (const mxArray * m_vector, const int v_len) static
Definition at line 470 of file ObjectHandle.h.
References i, and vector.
Referenced by mHalfspace2Hypro(), and mHalfspaces2Hypro().
std::vector< std::vector< size_t > > ObjectHandle::mVectorOfVectors2Hypro (const mxArray * m_matrix, const int rows, const int cols) static
Definition at line 625 of file ObjectHandle.h.
References cols, i, matrix, temp, and vector.
Referenced by MReach::setSettings().
template<typename T > std::vector< T > ObjectHandle::objArray2Hypro (const mxArray * array_ptr, const int len) static
Definition at line 140 of file ObjectHandle.h.
References i, and vec.
template<typename T > static void ObjectHandle::objArray2Matlab (const std::vector< T > & , mxArray * , const int) static
template<typename T > static void ObjectHandle::pair2Matlab (const std::pair< T, T > & , mxArray * , const int , const int) static
template<typename T > static void ObjectHandle::vector2Matlab (const std::vector< T > & , mxArray *) static
template<typename T > static void ObjectHandle::vector2Matlab (const std::vector< T > & , mxArray * , mxArray *) static
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/util/matlab/handles/ObjectHandle.h