HyPro: hypro::Ridge< Number > Class Template Reference
hypro::Ridge< Number > Class Template Reference
#include <Ridge.h>
Public Types
using vertexSet = std::vector< Point< Number >>
Public Member Functions
Ridge ()
Ridge (const Ridge< Number > &f)
Ridge (std::shared_ptr< Facet< Number >> facet1, std::shared_ptr< Facet< Number >> facet2)
~Ridge ()
vertexSet & rVertices ()
vertexSet vertices () const
std::vector< std::shared_ptr< Facet< Number > > > & rNeighbors ()
std::vector< std::shared_ptr< Facet< Number > > > neighbors () const
Halfspace< Number > halfspace () const
Private Attributes
vertexSet mVertices
std::vector< std::shared_ptr< Facet< Number > > > mNeighbors
Halfspace< Number > mHalfspace
Detailed Description
template<class Number>
class hypro::Ridge< Number >
Definition at line 17 of file Ridge.h.
Member Typedef Documentation
template<class Number> using hypro::Ridge< Number >::vertexSet = std::vector<Point<Number>>
Typedefs
Definition at line 22 of file Ridge.h.
Constructor & Destructor Documentation
template<class Number> hypro::Ridge< Number >::Ridge () inline
Constructors & Destructor
Definition at line 36 of file Ridge.h.
template<class Number> hypro::Ridge< Number >::Ridge (const Ridge< Number > & f) inline
Definition at line 38 of file Ridge.h.
References hypro::Ridge< Number >::halfspace(), hypro::Ridge< Number >::neighbors(), and hypro::Ridge< Number >::vertices().
template<class Number> hypro::Ridge< Number >::Ridge (std::shared_ptr< Facet< Number >> facet1, std::shared_ptr< Facet< Number >> facet2) inline
Definition at line 44 of file Ridge.h.
References i.
template<class Number> hypro::Ridge< Number >::~Ridge () inline
Definition at line 65 of file Ridge.h.
Member Function Documentation
template<class Number> Halfspace<Number> hypro::Ridge< Number >::halfspace () const inline
Definition at line 79 of file Ridge.h.
References hypro::Ridge< Number >::mHalfspace.
Referenced by hypro::Ridge< Number >::Ridge().
template<class Number> std::vector<std::shared_ptr<Facet<Number> > > hypro::Ridge< Number >::neighbors () const inline
Definition at line 77 of file Ridge.h.
References hypro::Ridge< Number >::mNeighbors.
Referenced by hypro::Ridge< Number >::Ridge().
template<class Number> std::vector<std::shared_ptr<Facet<Number> > >& hypro::Ridge< Number >::rNeighbors () inline
Definition at line 75 of file Ridge.h.
References hypro::Ridge< Number >::mNeighbors.
template<class Number> vertexSet& hypro::Ridge< Number >::rVertices () inline
Getters and Setters
Definition at line 71 of file Ridge.h.
References hypro::Ridge< Number >::mVertices.
template<class Number> vertexSet hypro::Ridge< Number >::vertices () const inline
Definition at line 73 of file Ridge.h.
References hypro::Ridge< Number >::mVertices.
Referenced by std::hash< hypro::Ridge< Number > >::operator()(), and hypro::Ridge< Number >::Ridge().
Member Data Documentation
template<class Number> Halfspace<Number> hypro::Ridge< Number >::mHalfspace private
Definition at line 30 of file Ridge.h.
Referenced by hypro::Ridge< Number >::halfspace().
template<class Number> std::vector<std::shared_ptr<Facet<Number> > > hypro::Ridge< Number >::mNeighbors private
Definition at line 29 of file Ridge.h.
Referenced by hypro::Ridge< Number >::neighbors(), and hypro::Ridge< Number >::rNeighbors().
template<class Number> vertexSet hypro::Ridge< Number >::mVertices private
Members
Definition at line 28 of file Ridge.h.
Referenced by hypro::Ridge< Number >::rVertices(), and hypro::Ridge< Number >::vertices().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/Ridge.h