HyPro: hypro::EventTimingContainer< Number > Class Template Reference
hypro::EventTimingContainer< Number > Class Template Reference
Public Member Functions
EventTimingContainer ()
EventTimingContainer (tNumber timeHorizon)
EventTimingContainer (const EventTimingContainer &orig)
EventTimingContainer (EventTimingContainer &&orig)=default
~EventTimingContainer ()=default
EventTimingContainer & operator= (const EventTimingContainer &orig)
EventTimingContainer & operator= (EventTimingContainer &&orig)
std::mutex & getMutex () const
bool isInitialized () const
void initialize (tNumber timeHorizon)
void merge (const EventTimingContainer &snapshot)
void setTransitionTimings (const std::map< Transition< Number > *, HierarchicalIntervalVector< CONTAINMENT, tNumber >> &timings)
void setTransitionTimings (Transition< Number > *t, const HierarchicalIntervalVector< CONTAINMENT, tNumber > &timings)
void setInvariantTimings (const HierarchicalIntervalVector< CONTAINMENT, tNumber > &timings)
void setBadStateTimings (const HierarchicalIntervalVector< CONTAINMENT, tNumber > &timings)
const std::map< Transition< Number > *, HierarchicalIntervalVector< CONTAINMENT, tNumber > > & getTransitionTimings () const
std::map< Transition< Number > *, HierarchicalIntervalVector< CONTAINMENT, tNumber > > & rGetTransitionTimings ()
const HierarchicalIntervalVector< CONTAINMENT, tNumber > & getTransitionTimings (Transition< Number > *transition) const
const HierarchicalIntervalVector< CONTAINMENT, tNumber > & getInvariantTimings () const
HierarchicalIntervalVector< CONTAINMENT, tNumber > & rGetInvariantTimings ()
const HierarchicalIntervalVector< CONTAINMENT, tNumber > & getBadStateTimings () const
bool hasTransitionEvent (Transition< Number > *transition) const
bool hasTransitionEvent (const carl::Interval< tNumber > &timeInterval, Transition< Number > *transition) const
bool hasTransitionInformation (const carl::Interval< tNumber > &timeInterval, Transition< Number > *transition) const
bool hasTransition (Transition< Number > *t) const
bool hasInvariantEvent (CONTAINMENT type) const
bool satisfiedInvariant (const carl::Interval< tNumber > &timeInterval) const
bool hasInvariantEvent (const carl::Interval< tNumber > &timeInterval, CONTAINMENT type) const
bool hasBadStateEvent () const
bool hasBadStateEvent (const carl::Interval< tNumber > &timeInterval, CONTAINMENT type) const
bool hasPositiveBadStateEvent (const carl::Interval< tNumber > &timeInterval) const
void insertTransition (Transition< Number > *transition, const carl::Interval< tNumber > &timeInterval, CONTAINMENT type)
void insertInvariant (const carl::Interval< tNumber > &timeInterval, CONTAINMENT type)
void insertBadState (const carl::Interval< tNumber > &timeInterval, CONTAINMENT type)
std::size_t getDotRepresentation (std::size_t startIndex, std::string &nodes, std::string &transitions, std::vector< unsigned > &levels) const
Friends
std::ostream & operator<< (std::ostream &out, const EventTimingContainer &in)
bool operator== (const EventTimingContainer &lhs, const EventTimingContainer &rhs)
bool operator!= (const EventTimingContainer &lhs, const EventTimingContainer &rhs)
Detailed Description
template<typename Number>
class hypro::EventTimingContainer< Number >
Definition at line 12 of file EventTimingContainer.h.
Constructor & Destructor Documentation
template<typename Number> hypro::EventTimingContainer< Number >::EventTimingContainer () inline
Definition at line 22 of file EventTimingContainer.h.
Referenced by hypro::EventTimingContainer< N >::EventTimingContainer().
template<typename Number> hypro::EventTimingContainer< Number >::EventTimingContainer (tNumber timeHorizon) inline explicit
Definition at line 29 of file EventTimingContainer.h.
template<typename Number> hypro::EventTimingContainer< Number >::EventTimingContainer (const EventTimingContainer< Number > & orig)
template<typename Number> hypro::EventTimingContainer< Number >::EventTimingContainer (EventTimingContainer< Number > && orig) default
template<typename Number> hypro::EventTimingContainer< Number >::~EventTimingContainer () default
Referenced by hypro::EventTimingContainer< N >::EventTimingContainer().
Member Function Documentation
template<typename Number > const HierarchicalIntervalVector< CONTAINMENT, tNumber > & hypro::EventTimingContainer< Number >::getBadStateTimings () const
Definition at line 179 of file EventTimingContainer.tpp.
Referenced by hypro::EventTimingContainer< Number >::merge(), and hypro::EventTimingContainer< N >::rGetInvariantTimings().
template<typename Number > std::size_t hypro::EventTimingContainer< Number >::getDotRepresentation (std::size_t startIndex, std::string & nodes, std::string & transitions, std::vector< unsigned > & levels) const
Definition at line 184 of file EventTimingContainer.tpp.
template<typename Number > const HierarchicalIntervalVector< CONTAINMENT, tNumber > & hypro::EventTimingContainer< Number >::getInvariantTimings () const
Definition at line 154 of file EventTimingContainer.tpp.
Referenced by hypro::EventTimingContainer< Number >::merge(), and hypro::EventTimingContainer< N >::setBadStateTimings().
template<typename Number> std::mutex& hypro::EventTimingContainer< Number >::getMutex () const inline
Definition at line 45 of file EventTimingContainer.h.
template<typename Number > const std::map< Transition< Number > *, HierarchicalIntervalVector< CONTAINMENT, tNumber > > & hypro::EventTimingContainer< Number >::getTransitionTimings () const
Definition at line 139 of file EventTimingContainer.tpp.
Referenced by hypro::EventTimingContainer< Number >::merge(), and hypro::EventTimingContainer< N >::setBadStateTimings().
template<typename Number> const HierarchicalIntervalVector< CONTAINMENT, tNumber > & hypro::EventTimingContainer< Number >::getTransitionTimings (Transition< Number > * transition) const
Definition at line 149 of file EventTimingContainer.tpp.
template<typename Number > bool hypro::EventTimingContainer< Number >::hasBadStateEvent () const
Definition at line 101 of file EventTimingContainer.tpp.
Referenced by hypro::EventTimingContainer< N >::hasTransition().
template<typename Number > bool hypro::EventTimingContainer< Number >::hasBadStateEvent (const carl::Interval< tNumber > & timeInterval, CONTAINMENT type) const
Definition at line 106 of file EventTimingContainer.tpp.
template<typename Number > bool hypro::EventTimingContainer< Number >::hasInvariantEvent (CONTAINMENT type) const
Definition at line 84 of file EventTimingContainer.tpp.
Referenced by hypro::EventTimingContainer< N >::hasTransition().
template<typename Number > bool hypro::EventTimingContainer< Number >::hasInvariantEvent (const carl::Interval< tNumber > & timeInterval, CONTAINMENT type) const
Definition at line 96 of file EventTimingContainer.tpp.
template<typename Number > bool hypro::EventTimingContainer< Number >::hasPositiveBadStateEvent (const carl::Interval< tNumber > & timeInterval) const
Definition at line 111 of file EventTimingContainer.tpp.
Referenced by hypro::EventTimingContainer< N >::hasTransition().
template<typename Number> bool hypro::EventTimingContainer< Number >::hasTransition (Transition< Number > * t) const inline
Definition at line 67 of file EventTimingContainer.h.
template<typename Number> bool hypro::EventTimingContainer< Number >::hasTransitionEvent (Transition< Number > * transition) const
Definition at line 58 of file EventTimingContainer.tpp.
Referenced by hypro::EventTimingContainer< N >::rGetInvariantTimings().
template<typename Number> bool hypro::EventTimingContainer< Number >::hasTransitionEvent (const carl::Interval< tNumber > & timeInterval, Transition< Number > * transition) const
Definition at line 66 of file EventTimingContainer.tpp.
template<typename Number> bool hypro::EventTimingContainer< Number >::hasTransitionInformation (const carl::Interval< tNumber > & timeInterval, Transition< Number > * transition) const
Definition at line 76 of file EventTimingContainer.tpp.
Referenced by hypro::EventTimingContainer< N >::rGetInvariantTimings().
template<typename Number > void hypro::EventTimingContainer< Number >::initialize (tNumber timeHorizon)
Definition at line 33 of file EventTimingContainer.tpp.
Referenced by hypro::EventTimingContainer< N >::getMutex().
template<typename Number > void hypro::EventTimingContainer< Number >::insertBadState (const carl::Interval< tNumber > & timeInterval, CONTAINMENT type)
Definition at line 169 of file EventTimingContainer.tpp.
Referenced by hypro::EventTimingContainer< N >::hasTransition().
template<typename Number > void hypro::EventTimingContainer< Number >::insertInvariant (const carl::Interval< tNumber > & timeInterval, CONTAINMENT type)
Definition at line 159 of file EventTimingContainer.tpp.
Referenced by hypro::EventTimingContainer< N >::hasTransition().
template<typename Number> void hypro::EventTimingContainer< Number >::insertTransition (Transition< Number > * transition, const carl::Interval< tNumber > & timeInterval, CONTAINMENT type)
Definition at line 123 of file EventTimingContainer.tpp.
Referenced by hypro::EventTimingContainer< N >::hasTransition().
template<typename Number > bool hypro::EventTimingContainer< Number >::isInitialized () const
Definition at line 28 of file EventTimingContainer.tpp.
Referenced by hypro::EventTimingContainer< N >::getMutex().
template<typename Number> void hypro::EventTimingContainer< Number >::merge (const EventTimingContainer< Number > & snapshot)
Definition at line 39 of file EventTimingContainer.tpp.
References hypro::EventTimingContainer< Number >::getBadStateTimings(), hypro::EventTimingContainer< Number >::getInvariantTimings(), hypro::EventTimingContainer< Number >::getTransitionTimings(), and hypro::HierarchicalIntervalVector< T, Number >::merge().
Referenced by hypro::EventTimingContainer< N >::getMutex().
template<typename Number> EventTimingContainer& hypro::EventTimingContainer< Number >::operator= (const EventTimingContainer< Number > & orig)
Referenced by hypro::EventTimingContainer< N >::EventTimingContainer().
template<typename Number> EventTimingContainer& hypro::EventTimingContainer< Number >::operator= (EventTimingContainer< Number > && orig)
template<typename Number> HierarchicalIntervalVector<CONTAINMENT, tNumber>& hypro::EventTimingContainer< Number >::rGetInvariantTimings () inline
Definition at line 60 of file EventTimingContainer.h.
template<typename Number > std::map< Transition< Number > *, HierarchicalIntervalVector< CONTAINMENT, tNumber > > & hypro::EventTimingContainer< Number >::rGetTransitionTimings ()
Definition at line 144 of file EventTimingContainer.tpp.
Referenced by hypro::EventTimingContainer< N >::setBadStateTimings().
template<typename Number > bool hypro::EventTimingContainer< Number >::satisfiedInvariant (const carl::Interval< tNumber > & timeInterval) const
Definition at line 89 of file EventTimingContainer.tpp.
Referenced by hypro::EventTimingContainer< N >::hasTransition().
template<typename Number> void hypro::EventTimingContainer< Number >::setBadStateTimings (const HierarchicalIntervalVector< CONTAINMENT, tNumber > & timings) inline
Definition at line 54 of file EventTimingContainer.h.
template<typename Number> void hypro::EventTimingContainer< Number >::setInvariantTimings (const HierarchicalIntervalVector< CONTAINMENT, tNumber > & timings) inline
Definition at line 53 of file EventTimingContainer.h.
template<typename Number> void hypro::EventTimingContainer< Number >::setTransitionTimings (const std::map< Transition< Number > *, HierarchicalIntervalVector< CONTAINMENT, tNumber >> & timings) inline
Definition at line 51 of file EventTimingContainer.h.
template<typename Number> void hypro::EventTimingContainer< Number >::setTransitionTimings (Transition< Number > * t, const HierarchicalIntervalVector< CONTAINMENT, tNumber > & timings) inline
Definition at line 52 of file EventTimingContainer.h.
Friends And Related Function Documentation
template<typename Number> bool operator!= (const EventTimingContainer< Number > & lhs, const EventTimingContainer< Number > & rhs) friend
Definition at line 95 of file EventTimingContainer.h.
template<typename Number> std::ostream& operator<< (std::ostream & out, const EventTimingContainer< Number > & in) friend
Definition at line 81 of file EventTimingContainer.h.
template<typename Number> bool operator== (const EventTimingContainer< Number > & lhs, const EventTimingContainer< Number > & rhs) friend
Definition at line 91 of file EventTimingContainer.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/timing/EventTimingContainer.h
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/timing/EventTimingContainer.tpp