HyPro: hypro::VPolytopeT< Number, Converter, S > Class Template Reference
hypro::VPolytopeT< Number, Converter, S > Class Template Reference
State set representations
The class implementing the vertex representation of a convex polytope.
Public Types
using pointVector = std::vector< Point< Number >>
typedef S Settings
typedef Number NumberType
Public Member Functions
VPolytopeT ()
Default constructor.
VPolytopeT (const Point< Number > &point)
Constructor from a single point.
VPolytopeT (const pointVector &points)
Constructor from a vector of points.
VPolytopeT (const std::vector< vector_t< Number >> &rawPoints)
Constructor from a vector of coordinates.
VPolytopeT (const matrix_t< Number > &_constraints, const vector_t< Number > _constants)
Constructor from a constraint system represented by a matrix and a vector.
VPolytopeT (const VPolytopeT &orig)=default
Copy constructor.
VPolytopeT (VPolytopeT &&_orig)=default
Move constructor.
~VPolytopeT ()
Destroys the object.
matrix_t< Number > matrix () const
vector_t< Number > vector () const
VPolytopeT project (const std::vector< std::size_t > &dimensions) const
VPolytopeT assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const
VPolytopeT linearTransformation (const matrix_t< Number > &A) const
VPolytopeT affineTransformation (const matrix_t< Number > &A, const vector_t< Number > &b) const
VPolytopeT minkowskiSum (const VPolytopeT &rhs) const
VPolytopeT intersect (const VPolytopeT &rhs) const
Intersects the polytope with a second polytope.
VPolytopeT intersectHalfspace (const Halfspace< Number > &rhs) const
VPolytopeT intersectHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const
std::pair< CONTAINMENT, VPolytopeT > satisfiesHalfspace (const Halfspace< Number > &rhs) const
std::pair< CONTAINMENT, VPolytopeT > satisfiesHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const
bool contains (const Point< Number > &point) const
bool contains (const vector_t< Number > &vec) const
Checks if a point represented by its coordinates is contained in the polytope.
bool contains (const VPolytopeT &_other) const
Checks if the other polytope is fully contained in this polytope.
VPolytopeT unite (const VPolytopeT &rhs) const
void reduceRepresentation ()
Reduces the box - only in case rational types are used, the number representation is optimized.
void clear ()
Clears the polytope.
EvaluationResult< Number > evaluate (const vector_t< Number > &direction) const
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &directions, bool useExact=true) const
bool empty () const
Checks if the polytope represents the empty set.
std::size_t dimension () const
Returns the space dimension.
std::size_t size () const
Returns the number of vertices.
bool reduced () const
Returns whether the polytope has been reduced (i.e. the set of vertices is minimal).
Number supremum () const
Returns the supremum of the set according to the infty norm.
const Cone< Number > & cone () const
Returns the cone of this.
void setCone (const Cone< Number > &_cone)
Explicitly sets the cone.
void setNeighbors (const Point< Number > &_point, const std::set< Point< Number >> &_neighbors)
void unsafeSetNeighbors (const std::vector< std::set< unsigned >> &_neighbors)
std::vector< Point< Number > > neighbors (const Point< Number > &_point) const
pointVector::iterator insert (const Point< Number > &i)
Point< Number > & emplace_back (Point< Number > &&i)
pointVector::iterator insert (const vector_t< Number > &_coord)
pointVector::iterator insert (const typename pointVector::const_iterator begin, const typename pointVector::const_iterator end)
std::vector< Point< Number > > vertices (const matrix_t< Number > &=matrix_t< Number >::Zero(0, 0)) const
bool hasVertex (const Point< Number > &vertex) const
bool hasVertex (const vector_t< Number > &vertex) const
pointVector::iterator begin ()
pointVector::const_iterator begin () const
pointVector::iterator end ()
pointVector::const_iterator end () const
void removeRedundancy ()
template<typename N = Number, carl::DisableIf< carl::is_float< N >> = carl::dummy>
void reduceNumberRepresentation (std::size_t limit=fReach_DENOMINATOR) const
template<typename N = Number, carl::EnableIf< carl::is_float< N >> = carl::dummy>
void reduceNumberRepresentation (unsigned=fReach_DENOMINATOR) const
void updateNeighbors ()
VPolytopeT< Number, Converter, S > & operator= (const VPolytopeT< Number, Converter, S > &rhs)=default
VPolytopeT< Number, Converter, S > & operator= (VPolytopeT< Number, Converter, S > &&rhs)=default
bool operator== (const VPolytopeT< Number, Converter, S > &rhs) const
Static Public Member Functions
static VPolytopeT unite (const std::vector< VPolytopeT > &rhs)
Computes the convex hull of this and a set of polytopes.
static VPolytopeT Empty ()
Constructs the empty polytope.
static representation_name type ()
Returns the type.
Detailed Description
template<typename Number, typename Converter, typename S>
class hypro::VPolytopeT< Number, Converter, S >
The class implementing the vertex representation of a convex polytope.
Template Parameters
Number The used number type.
Converter The used converter. @{
Definition at line 34 of file VPolytope.h.
Member Typedef Documentation
template<typename Number, typename Converter, typename S> typedef Number hypro::VPolytopeT< Number, Converter, S >::NumberType
Definition at line 38 of file VPolytope.h.
template<typename Number, typename Converter, typename S> using hypro::VPolytopeT< Number, Converter, S >::pointVector = std::vector<Point<Number>>
Definition at line 36 of file VPolytope.h.
template<typename Number, typename Converter, typename S> typedef S hypro::VPolytopeT< Number, Converter, S >::Settings
Definition at line 37 of file VPolytope.h.
Constructor & Destructor Documentation
template<typename Number , typename Converter , typename S > hypro::VPolytopeT< Number, Converter, S >::VPolytopeT ()
Default constructor.
Definition at line 13 of file VPolytope.tpp.
References hypro::EMPTY.
Referenced by hypro::VPolytopeT< Number, Converter, S >::Empty().
template<typename Number , typename Converter , typename S > hypro::VPolytopeT< Number, Converter, S >::VPolytopeT (const Point< Number > & point)
Constructor from a single point.
Parameters
[in] point The point.
Definition at line 21 of file VPolytope.tpp.
template<typename Number , typename Converter , typename S > hypro::VPolytopeT< Number, Converter, S >::VPolytopeT (const pointVector & points)
Constructor from a vector of points.
Parameters
[in] points The points.
Definition at line 29 of file VPolytope.tpp.
References hypro::VPolytopeT< Number, Converter, S >::reduceNumberRepresentation().
template<typename Number , typename Converter , typename S > hypro::VPolytopeT< Number, Converter, S >::VPolytopeT (const std::vector< vector_t< Number >> & rawPoints)
Constructor from a vector of coordinates.
Parameters
[in] rawPoints The raw coordinates.
Definition at line 42 of file VPolytope.tpp.
References hypro::VPolytopeT< Number, Converter, S >::reduceNumberRepresentation().
template<typename Number , typename Converter , typename S > hypro::VPolytopeT< Number, Converter, S >::VPolytopeT (const matrix_t< Number > & _constraints, const vector_t< Number > _constants)
Constructor from a constraint system represented by a matrix and a vector.
Parameters
[in] _constraints The constraints.
[in] _constants The constants.
Definition at line 56 of file VPolytope.tpp.
References default_double_comparison_ulps, and hypro::VPolytopeT< Number, Converter, S >::dimension().
template<typename Number, typename Converter, typename S> hypro::VPolytopeT< Number, Converter, S >::VPolytopeT (const VPolytopeT< Number, Converter, S > & orig) default
Copy constructor.
Parameters
[in] orig The original.
template<typename Number, typename Converter, typename S> hypro::VPolytopeT< Number, Converter, S >::VPolytopeT (VPolytopeT< Number, Converter, S > && _orig) default
Move constructor.
Parameters
[in] <unnamed> The original.
template<typename Number, typename Converter, typename S> hypro::VPolytopeT< Number, Converter, S >::~VPolytopeT () inline
Destroys the object.
Definition at line 93 of file VPolytope.h.
Member Function Documentation
template<typename Number , typename Converter , typename S > VPolytopeT< Number, Converter, S > hypro::VPolytopeT< Number, Converter, S >::affineTransformation (const matrix_t< Number > & A, const vector_t< Number > & b) const
Definition at line 175 of file VPolytope.tpp.
References hypro::VPolytopeT< Number, Converter, S >::begin(), hypro::VPolytopeT< Number, Converter, S >::emplace_back(), hypro::VPolytopeT< Number, Converter, S >::end(), hypro::VPolytopeT< Number, Converter, S >::setCone(), and hypro::VPolytopeT< Number, Converter, S >::unsafeSetNeighbors().
Referenced by hypro::VPolytopeT< Number, Converter, S >::assignIntervals().
template<typename Number, typename Converter, typename S> VPolytopeT hypro::VPolytopeT< Number, Converter, S >::assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const inline
Definition at line 110 of file VPolytope.h.
References hypro::VPolytopeT< Number, Converter, S >::affineTransformation(), hypro::VPolytopeT< Number, Converter, S >::contains(), hypro::VPolytopeT< Number, Converter, S >::intersect(), hypro::VPolytopeT< Number, Converter, S >::intersectHalfspace(), hypro::VPolytopeT< Number, Converter, S >::intersectHalfspaces(), hypro::VPolytopeT< Number, Converter, S >::linearTransformation(), hypro::VPolytopeT< Number, Converter, S >::minkowskiSum(), hypro::VPolytopeT< Number, Converter, S >::satisfiesHalfspace(), hypro::VPolytopeT< Number, Converter, S >::satisfiesHalfspaces(), and hypro::VPolytopeT< Number, Converter, S >::unite().
template<typename Number, typename Converter, typename S> pointVector::iterator hypro::VPolytopeT< Number, Converter, S >::begin () inline
Definition at line 299 of file VPolytope.h.
Referenced by hypro::VPolytopeT< Number, Converter, S >::affineTransformation(), hypro::VPolytopeT< Number, Converter, S >::contains(), hypro::VPolytopeT< Number, Converter, S >::insert(), hypro::VPolytopeT< Number, Converter, S >::linearTransformation(), and hypro::VPolytopeT< Number, Converter, S >::unite().
template<typename Number, typename Converter, typename S> pointVector::const_iterator hypro::VPolytopeT< Number, Converter, S >::begin () const inline
Definition at line 300 of file VPolytope.h.
template<typename Number , typename Converter , typename S > void hypro::VPolytopeT< Number, Converter, S >::clear ()
Clears the polytope.
Definition at line 529 of file VPolytope.tpp.
References hypro::EMPTY, and hypro::GeometricObjectBase::mEmptyState.
Referenced by hypro::VPolytopeT< Number, Converter, S >::reduceRepresentation().
template<typename Number, typename Converter, typename S> const Cone<Number>& hypro::VPolytopeT< Number, Converter, S >::cone () const inline
Returns the cone of this.
Returns
The cone.
Definition at line 219 of file VPolytope.h.
Referenced by hypro::VPolytopeT< Number, Converter, S >::minkowskiSum().
template<typename Number , typename Converter , typename S > bool hypro::VPolytopeT< Number, Converter, S >::contains (const Point< Number > & point) const
Definition at line 323 of file VPolytope.tpp.
References hypro::Point< Number >::rawCoordinates().
Referenced by hypro::VPolytopeT< Number, Converter, S >::assignIntervals(), hypro::VPolytopeT< Number, Converter, S >::contains(), and hypro::VPolytopeT< Number, Converter, S >::intersect().
template<typename Number , typename Converter , typename S > bool hypro::VPolytopeT< Number, Converter, S >::contains (const vector_t< Number > & vec) const
Checks if a point represented by its coordinates is contained in the polytope.
Parameters
[in] vec The point vector.
Returns
True, if the point lies inside the polytope.
Definition at line 328 of file VPolytope.tpp.
References hypro::Optimizer< Number >::addConstraint(), hypro::VPolytopeT< Number, Converter, S >::begin(), hypro::Optimizer< Number >::checkConsistency(), hypro::VPolytopeT< Number, Converter, S >::contains(), hypro::VPolytopeT< Number, Converter, S >::dimension(), hypro::effectiveDimension(), hypro::VPolytopeT< Number, Converter, S >::empty(), hypro::VPolytopeT< Number, Converter, S >::end(), hypro::VPolytopeT< Number, Converter, S >::insert(), hypro::VPolytopeT< Number, Converter, S >::size(), hypro::Converter< Number >::toHPolytope(), hypro::VPolytopeT< Number, Converter, S >::unite(), and hypro::VPolytopeT< Number, Converter, S >::vertices().
template<typename Number, typename Converter, typename S> bool hypro::VPolytopeT< Number, Converter, S >::contains (const VPolytopeT< Number, Converter, S > & _other) const
Checks if the other polytope is fully contained in this polytope.
Parameters
[in] _other The other polytope.
Returns
True, if the other polytope is contained.
template<typename Number, typename Converter, typename S> std::size_t hypro::VPolytopeT< Number, Converter, S >::dimension () const inline
Returns the space dimension.
Returns
The space dimension.
Definition at line 186 of file VPolytope.h.
Referenced by hypro::VPolytopeT< Number, Converter, S >::contains(), hypro::VPolytopeT< Number, Converter, S >::emplace_back(), hypro::VPolytopeT< Number, Converter, S >::insert(), hypro::VPolytopeT< Number, Converter, S >::operator==(), hypro::VPolytopeT< Number, Converter, S >::reduceNumberRepresentation(), hypro::VPolytopeT< Number, Converter, S >::removeRedundancy(), hypro::Converter< Number >::toVPolytope(), and hypro::VPolytopeT< Number, Converter, S >::VPolytopeT().
template<typename Number, typename Converter, typename S> Point<Number>& hypro::VPolytopeT< Number, Converter, S >::emplace_back (Point< Number > && i) inline
Definition at line 265 of file VPolytope.h.
References hypro::VPolytopeT< Number, Converter, S >::dimension().
Referenced by hypro::VPolytopeT< Number, Converter, S >::affineTransformation(), and hypro::VPolytopeT< Number, Converter, S >::linearTransformation().
template<typename Number, typename Converter, typename S> bool hypro::VPolytopeT< Number, Converter, S >::empty () const inline
Checks if the polytope represents the empty set.
Returns
True if there are no vertices.
Definition at line 174 of file VPolytope.h.
Referenced by hypro::VPolytopeT< Number, Converter, S >::contains(), hypro::VPolytopeT< Number, Converter, S >::minkowskiSum(), hypro::VPolytopeT< Number, Converter, S >::satisfiesHalfspaces(), hypro::Converter< Number >::toBox(), and hypro::VPolytopeT< Number, Converter, S >::unite().
template<typename Number, typename Converter, typename S> static VPolytopeT hypro::VPolytopeT< Number, Converter, S >::Empty () inline static
Constructs the empty polytope.
Returns
The polytope.
Definition at line 180 of file VPolytope.h.
References hypro::VPolytopeT< Number, Converter, S >::VPolytopeT().
Referenced by hypro::VPolytopeT< Number, Converter, S >::minkowskiSum(), hypro::VPolytopeT< Number, Converter, S >::project(), and hypro::VPolytopeT< Number, Converter, S >::unite().
template<typename Number, typename Converter, typename S> pointVector::iterator hypro::VPolytopeT< Number, Converter, S >::end () inline
Definition at line 301 of file VPolytope.h.
Referenced by hypro::VPolytopeT< Number, Converter, S >::affineTransformation(), hypro::VPolytopeT< Number, Converter, S >::contains(), hypro::VPolytopeT< Number, Converter, S >::insert(), hypro::VPolytopeT< Number, Converter, S >::linearTransformation(), and hypro::VPolytopeT< Number, Converter, S >::unite().
template<typename Number, typename Converter, typename S> pointVector::const_iterator hypro::VPolytopeT< Number, Converter, S >::end () const inline
Definition at line 302 of file VPolytope.h.
References hypro::VPolytopeT< Number, Converter, S >::removeRedundancy().
template<typename Number , typename Converter , typename S > EvaluationResult< Number > hypro::VPolytopeT< Number, Converter, S >::evaluate (const vector_t< Number > & direction) const
Definition at line 535 of file VPolytope.tpp.
References hypro::EvaluationResult< Number >::errorCode, hypro::FEAS, hypro::EvaluationResult< Number >::optimumValue, and hypro::EvaluationResult< Number >::supportValue.
Referenced by hypro::VPolytopeT< Number, Converter, S >::multiEvaluate(), and hypro::VPolytopeT< Number, Converter, S >::reduceRepresentation().
template<typename Number, typename Converter, typename S> bool hypro::VPolytopeT< Number, Converter, S >::hasVertex (const Point< Number > & vertex) const inline
Definition at line 290 of file VPolytope.h.
Referenced by hypro::VPolytopeT< Number, Converter, S >::operator==().
template<typename Number, typename Converter, typename S> bool hypro::VPolytopeT< Number, Converter, S >::hasVertex (const vector_t< Number > & vertex) const inline
Definition at line 297 of file VPolytope.h.
template<typename Number, typename Converter, typename S> pointVector::iterator hypro::VPolytopeT< Number, Converter, S >::insert (const Point< Number > & i) inline
Definition at line 257 of file VPolytope.h.
References hypro::Point< Number >::dimension(), and hypro::VPolytopeT< Number, Converter, S >::dimension().
Referenced by hypro::VPolytopeT< Number, Converter, S >::contains(), hypro::VPolytopeT< Number, Converter, S >::minkowskiSum(), and hypro::VPolytopeT< Number, Converter, S >::unite().
template<typename Number, typename Converter, typename S> pointVector::iterator hypro::VPolytopeT< Number, Converter, S >::insert (const vector_t< Number > & _coord) inline
Definition at line 273 of file VPolytope.h.
References hypro::VPolytopeT< Number, Converter, S >::dimension().
template<typename Number, typename Converter, typename S> pointVector::iterator hypro::VPolytopeT< Number, Converter, S >::insert (const typename pointVector::const_iterator begin, const typename pointVector::const_iterator end) inline
Definition at line 280 of file VPolytope.h.
References hypro::VPolytopeT< Number, Converter, S >::begin(), hypro::VPolytopeT< Number, Converter, S >::dimension(), and hypro::VPolytopeT< Number, Converter, S >::end().
template<typename Number, typename Converter, typename S> VPolytopeT< Number, Converter, S > hypro::VPolytopeT< Number, Converter, S >::intersect (const VPolytopeT< Number, Converter, S > & rhs) const
Intersects the polytope with a second polytope.
Parameters
[in] rhs The right hand side.
Returns
The resulting object.
Definition at line 207 of file VPolytope.tpp.
References hypro::VPolytopeT< Number, Converter, S >::contains(), and hypro::VPolytopeT< Number, Converter, S >::size().
Referenced by hypro::VPolytopeT< Number, Converter, S >::assignIntervals().
template<typename Number , typename Converter , typename S > VPolytopeT< Number, Converter, S > hypro::VPolytopeT< Number, Converter, S >::intersectHalfspace (const Halfspace< Number > & rhs) const
Definition at line 237 of file VPolytope.tpp.
References hypro::Converter< Number >::toHPolytope(), and hypro::Converter< Number >::toVPolytope().
Referenced by hypro::VPolytopeT< Number, Converter, S >::assignIntervals().
template<typename Number , typename Converter , typename S > VPolytopeT< Number, Converter, S > hypro::VPolytopeT< Number, Converter, S >::intersectHalfspaces (const matrix_t< Number > & _mat, const vector_t< Number > & _vec) const
Definition at line 246 of file VPolytope.tpp.
References hypro::Converter< Number >::toHPolytope(), and hypro::Converter< Number >::toVPolytope().
Referenced by hypro::VPolytopeT< Number, Converter, S >::assignIntervals().
template<typename Number , typename Converter , typename S > VPolytopeT< Number, Converter, S > hypro::VPolytopeT< Number, Converter, S >::linearTransformation (const matrix_t< Number > & A) const
Definition at line 160 of file VPolytope.tpp.
References hypro::VPolytopeT< Number, Converter, S >::begin(), hypro::VPolytopeT< Number, Converter, S >::emplace_back(), hypro::VPolytopeT< Number, Converter, S >::end(), hypro::VPolytopeT< Number, Converter, S >::setCone(), and hypro::VPolytopeT< Number, Converter, S >::unsafeSetNeighbors().
Referenced by hypro::VPolytopeT< Number, Converter, S >::assignIntervals().
template<typename Number, typename Converter, typename S> matrix_t<Number> hypro::VPolytopeT< Number, Converter, S >::matrix () const inline
Definition at line 100 of file VPolytope.h.
template<typename Number, typename Converter, typename S> VPolytopeT< Number, Converter, S > hypro::VPolytopeT< Number, Converter, S >::minkowskiSum (const VPolytopeT< Number, Converter, S > & rhs) const
Definition at line 191 of file VPolytope.tpp.
References hypro::VPolytopeT< Number, Converter, S >::cone(), hypro::VPolytopeT< Number, Converter, S >::empty(), hypro::VPolytopeT< Number, Converter, S >::Empty(), hypro::VPolytopeT< Number, Converter, S >::insert(), and hypro::VPolytopeT< Number, Converter, S >::setCone().
Referenced by hypro::VPolytopeT< Number, Converter, S >::assignIntervals().
template<typename Number , typename Converter , typename S > std::vector< EvaluationResult< Number > > hypro::VPolytopeT< Number, Converter, S >::multiEvaluate (const matrix_t< Number > & directions, bool useExact = true) const
Definition at line 556 of file VPolytope.tpp.
References hypro::VPolytopeT< Number, Converter, S >::evaluate().
Referenced by hypro::VPolytopeT< Number, Converter, S >::reduceRepresentation().
template<typename Number, typename Converter, typename S> std::vector<Point<Number> > hypro::VPolytopeT< Number, Converter, S >::neighbors (const Point< Number > & _point) const inline
Definition at line 246 of file VPolytope.h.
template<typename Number, typename Converter, typename S> VPolytopeT<Number, Converter, S>& hypro::VPolytopeT< Number, Converter, S >::operator= (const VPolytopeT< Number, Converter, S > & rhs) default
Referenced by hypro::VPolytopeT< Number, Converter, S >::reduceNumberRepresentation().
template<typename Number, typename Converter, typename S> VPolytopeT<Number, Converter, S>& hypro::VPolytopeT< Number, Converter, S >::operator= (VPolytopeT< Number, Converter, S > && rhs) default
template<typename Number , typename Converter , typename S > bool hypro::VPolytopeT< Number, Converter, S >::operator== (const VPolytopeT< Number, Converter, S > & rhs) const
Definition at line 688 of file VPolytope.tpp.
References hypro::VPolytopeT< Number, Converter, S >::dimension(), hypro::VPolytopeT< Number, Converter, S >::hasVertex(), and hypro::VPolytopeT< Number, Converter, S >::vertices().
Referenced by hypro::VPolytopeT< Number, Converter, S >::reduceNumberRepresentation().
template<typename Number , typename Converter , typename S > VPolytopeT< Number, Converter, S > hypro::VPolytopeT< Number, Converter, S >::project (const std::vector< std::size_t > & dimensions) const
Definition at line 146 of file VPolytope.tpp.
References hypro::VPolytopeT< Number, Converter, S >::Empty().
Referenced by hypro::VPolytopeT< Number, Converter, S >::vector().
template<typename Number, typename Converter, typename S> bool hypro::VPolytopeT< Number, Converter, S >::reduced () const inline
Returns whether the polytope has been reduced (i.e. the set of vertices is minimal).
Returns
True, if the set of vertices is minimal.
Definition at line 207 of file VPolytope.h.
References hypro::VPolytopeT< Number, Converter, S >::supremum().
template<typename Number, typename Converter, typename S> template<typename N = Number, carl::DisableIf< carl::is_float< N >> = carl::dummy> void hypro::VPolytopeT< Number, Converter, S >::reduceNumberRepresentation (std::size_t limit = fReach_DENOMINATOR) const inline
Definition at line 307 of file VPolytope.h.
References hypro::VPolytopeT< Number, Converter, S >::dimension().
Referenced by hypro::VPolytopeT< Number, Converter, S >::reduceRepresentation(), and hypro::VPolytopeT< Number, Converter, S >::VPolytopeT().
template<typename Number, typename Converter, typename S> template<typename N = Number, carl::EnableIf< carl::is_float< N >> = carl::dummy> void hypro::VPolytopeT< Number, Converter, S >::reduceNumberRepresentation (unsigned = fReach_DENOMINATOR) const inline
Definition at line 352 of file VPolytope.h.
References default_double_comparison_ulps, hypro::VPolytopeT< Number, Converter, S >::operator=(), hypro::VPolytopeT< Number, Converter, S >::operator==(), and hypro::VPolytopeT< Number, Converter, S >::updateNeighbors().
template<typename Number, typename Converter, typename S> void hypro::VPolytopeT< Number, Converter, S >::reduceRepresentation () inline
Reduces the box - only in case rational types are used, the number representation is optimized.
Definition at line 157 of file VPolytope.h.
References hypro::VPolytopeT< Number, Converter, S >::clear(), hypro::VPolytopeT< Number, Converter, S >::evaluate(), hypro::VPolytopeT< Number, Converter, S >::multiEvaluate(), hypro::VPolytopeT< Number, Converter, S >::reduceNumberRepresentation(), and hypro::VPolytopeT< Number, Converter, S >::removeRedundancy().
template<typename Number , typename Converter , typename S > void hypro::VPolytopeT< Number, Converter, S >::removeRedundancy ()
Definition at line 578 of file VPolytope.tpp.
References hypro::VPolytopeT< Number, Converter, S >::dimension(), and hypro::VPolytopeT< Number, Converter, S >::updateNeighbors().
Referenced by hypro::VPolytopeT< Number, Converter, S >::end(), and hypro::VPolytopeT< Number, Converter, S >::reduceRepresentation().
template<typename Number , typename Converter , typename S > std::pair< CONTAINMENT, VPolytopeT< Number, Converter, S > > hypro::VPolytopeT< Number, Converter, S >::satisfiesHalfspace (const Halfspace< Number > & rhs) const
Definition at line 255 of file VPolytope.tpp.
References hypro::FULL, hypro::NO, hypro::numberOfPointsInHalfspace(), hypro::Converter< Number >::toHPolytope(), and hypro::Converter< Number >::toVPolytope().
Referenced by hypro::VPolytopeT< Number, Converter, S >::assignIntervals().
template<typename Number , typename Converter , typename S > std::pair< CONTAINMENT, VPolytopeT< Number, Converter, S > > hypro::VPolytopeT< Number, Converter, S >::satisfiesHalfspaces (const matrix_t< Number > & _mat, const vector_t< Number > & _vec) const
Definition at line 282 of file VPolytope.tpp.
References hypro::VPolytopeT< Number, Converter, S >::empty(), hypro::FULL, hypro::NO, hypro::numberOfPointsInHalfspace(), hypro::removeRows(), hypro::Converter< Number >::toHPolytope(), and hypro::Converter< Number >::toVPolytope().
Referenced by hypro::VPolytopeT< Number, Converter, S >::assignIntervals().
template<typename Number, typename Converter, typename S> void hypro::VPolytopeT< Number, Converter, S >::setCone (const Cone< Number > & _cone) inline
Explicitly sets the cone.
Parameters
[in] _cone The cone.
Definition at line 225 of file VPolytope.h.
Referenced by hypro::VPolytopeT< Number, Converter, S >::affineTransformation(), hypro::VPolytopeT< Number, Converter, S >::linearTransformation(), and hypro::VPolytopeT< Number, Converter, S >::minkowskiSum().
template<typename Number, typename Converter, typename S> void hypro::VPolytopeT< Number, Converter, S >::setNeighbors (const Point< Number > & _point, const std::set< Point< Number >> & _neighbors) inline
Definition at line 227 of file VPolytope.h.
template<typename Number, typename Converter, typename S> std::size_t hypro::VPolytopeT< Number, Converter, S >::size () const inline
Returns the number of vertices.
Returns
The number of vertices.
Definition at line 195 of file VPolytope.h.
Referenced by hypro::VPolytopeT< Number, Converter, S >::contains(), hypro::VPolytopeT< Number, Converter, S >::intersect(), and hypro::VPolytopeT< Number, Converter, S >::unite().
template<typename Number , typename Converter , typename S > Number hypro::VPolytopeT< Number, Converter, S >::supremum () const
Returns the supremum of the set according to the infty norm.
Returns
The supremum.
Definition at line 568 of file VPolytope.tpp.
References hypro::Point< Number >::inftyNorm().
Referenced by hypro::VPolytopeT< Number, Converter, S >::reduced().
template<typename Number, typename Converter, typename S> static representation_name hypro::VPolytopeT< Number, Converter, S >::type () inline static
Returns the type.
Returns
The type.
Definition at line 201 of file VPolytope.h.
template<typename Number, typename Converter, typename S> VPolytopeT hypro::VPolytopeT< Number, Converter, S >::unite (const VPolytopeT< Number, Converter, S > & rhs) const
Referenced by hypro::VPolytopeT< Number, Converter, S >::assignIntervals(), and hypro::VPolytopeT< Number, Converter, S >::contains().
template<typename Number , typename Converter , typename S > VPolytopeT< Number, Converter, S > hypro::VPolytopeT< Number, Converter, S >::unite (const std::vector< VPolytopeT< Number, Converter, S > > & rhs) static
Computes the convex hull of this and a set of polytopes.
Parameters
[in] rhs The set of polytopes.
Returns
The resulting object.
Definition at line 432 of file VPolytope.tpp.
References hypro::VPolytopeT< Number, Converter, S >::begin(), hypro::effectiveDimension(), hypro::VPolytopeT< Number, Converter, S >::empty(), hypro::VPolytopeT< Number, Converter, S >::Empty(), hypro::VPolytopeT< Number, Converter, S >::end(), hypro::VPolytopeT< Number, Converter, S >::insert(), hypro::VPolytopeT< Number, Converter, S >::size(), and hypro::VPolytopeT< Number, Converter, S >::vertices().
template<typename Number, typename Converter, typename S> void hypro::VPolytopeT< Number, Converter, S >::unsafeSetNeighbors (const std::vector< std::set< unsigned >> & _neighbors) inline
Definition at line 244 of file VPolytope.h.
Referenced by hypro::VPolytopeT< Number, Converter, S >::affineTransformation(), and hypro::VPolytopeT< Number, Converter, S >::linearTransformation().
template<typename Number , typename Converter , typename S > void hypro::VPolytopeT< Number, Converter, S >::updateNeighbors ()
Definition at line 650 of file VPolytope.tpp.
Referenced by hypro::VPolytopeT< Number, Converter, S >::reduceNumberRepresentation(), and hypro::VPolytopeT< Number, Converter, S >::removeRedundancy().
template<typename Number, typename Converter, typename S> vector_t<Number> hypro::VPolytopeT< Number, Converter, S >::vector () const inline
Definition at line 104 of file VPolytope.h.
References hypro::VPolytopeT< Number, Converter, S >::project().
Referenced by hypro::operator<<().
template<typename Number, typename Converter, typename S> std::vector<Point<Number> > hypro::VPolytopeT< Number, Converter, S >::vertices (const matrix_t< Number > & = matrix_t<Number>::Zero(0, 0)) const inline
Definition at line 288 of file VPolytope.h.
Referenced by hypro::VPolytopeT< Number, Converter, S >::contains(), hypro::convert(), hypro::VPolytopeT< Number, Converter, S >::operator==(), hypro::Converter< Number >::toBox(), hypro::Converter< Number >::toHPolytope(), hypro::Converter< Number >::toZonotope(), and hypro::VPolytopeT< Number, Converter, S >::unite().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/Polytopes/VPolytope/VPolytope.h
/home/travis/build/hypro/hypro/src/hypro/representations/Polytopes/VPolytope/VPolytope.tpp