HyPro: hypro::EllipsoidT< Number, Converter > Class Template Reference
hypro::EllipsoidT< Number, Converter > Class Template Reference
Class for ellipsoids.
Public Member Functions
EllipsoidT (Number _radius, std::size_t _dimension)
EllipsoidT (matrix_t< Number > _shapeMatrix)
EllipsoidT (const EllipsoidT &_orig)
matrix_t< Number > matrix () const
std::size_t dimension () const
Returns the current dimension of the ellipsoid.
bool empty () const
Checks, if the ellipsoid is empty.
EllipsoidT< Number, Converter > & operator= (const EllipsoidT< Number, Converter > &rhs)=default
Assignment operator.
void print () const
EllipsoidT linearTransformation (const matrix_t< Number > &_A) const
EllipsoidT affineTransformation (const matrix_t< Number > &_A, const vector_t< Number > &_b) const
EllipsoidT minkowskiSum (const EllipsoidT &_rhs, bool _approx=true) const
vector_t< Number > evaluate (vector_t< Number > const l) const
matrix_t< Number > approxEllipsoidTMatrix (const matrix_t< Number > _matrix) const
Friends
bool operator== (const EllipsoidT< Number, Converter > &b1, const EllipsoidT< Number, Converter > &b2)
bool operator!= (const EllipsoidT< Number, Converter > &b1, const EllipsoidT< Number, Converter > &b2)
std::ostream & operator<< (std::ostream &ostr, const EllipsoidT< Number, Converter > &)
Detailed Description
template<typename Number, typename Converter>
class hypro::EllipsoidT< Number, Converter >
Class for ellipsoids.
Template Parameters
Number The used number type.
Definition at line 21 of file Ellipsoid.h.
Member Function Documentation
template<typename Number , typename Converter > EllipsoidT< Number, Converter > hypro::EllipsoidT< Number, Converter >::affineTransformation (const matrix_t< Number > & _A, const vector_t< Number > & _b) const
Parameters
A a linear transformation matrix
b shiftvector. ignored here and just included to fit the lin. trans of other representations
Returns
ellipsoid obtained by applying the linear transformation
Definition at line 71 of file Ellipsoid.tpp.
template<typename Number , typename Converter > matrix_t< Number > hypro::EllipsoidT< Number, Converter >::approxEllipsoidTMatrix (const matrix_t< Number > _matrix) const
Parameters
_matrix a shapematrix of an ellipsoid
Returns
matrix overapproximating the ellipsoid defined by _matrix
Definition at line 100 of file Ellipsoid.tpp.
References hypro::fReach_DENOMINATOR.
Referenced by hypro::EllipsoidT< Number, Converter >::minkowskiSum().
template<typename Number , typename Converter > std::size_t hypro::EllipsoidT< Number, Converter >::dimension () const
Returns the current dimension of the ellipsoid.
Returns
Definition at line 50 of file Ellipsoid.tpp.
template<typename Number , typename Converter > bool hypro::EllipsoidT< Number, Converter >::empty () const
Checks, if the ellipsoid is empty.
Returns
True, if the ellipsoid is empty.
Definition at line 55 of file Ellipsoid.tpp.
template<typename Number , typename Converter > vector_t< Number > hypro::EllipsoidT< Number, Converter >::evaluate (vector_t< Number > const l) const
Parameters
l direction in which to evaluate
Returns
vector to outmost point in direction l
Definition at line 135 of file Ellipsoid.tpp.
template<typename Number , typename Converter > EllipsoidT< Number, Converter > hypro::EllipsoidT< Number, Converter >::linearTransformation (const matrix_t< Number > & _A) const
Parameters
A a linear transformation matrix
b shiftvector. ignored here and just included to fit the lin. trans of other representations
Returns
ellipsoid obtained by applying the linear transformation
Definition at line 66 of file Ellipsoid.tpp.
template<typename Number , typename Converter > matrix_t< Number > hypro::EllipsoidT< Number, Converter >::matrix () const
Returns the shape matrix of the object.
Returns
Definition at line 45 of file Ellipsoid.tpp.
Referenced by hypro::EllipsoidT< Number, Converter >::minkowskiSum().
template<typename Number, typename Converter> EllipsoidT< Number, Converter > hypro::EllipsoidT< Number, Converter >::minkowskiSum (const EllipsoidT< Number, Converter > & _rhs, bool _approx = true) const
Parameters
rhs second ellipsoid used for the minkowskiSum,
l direction of tight approximation
Returns
ellipsoid overapproximating the mink sum of two ellipsoids
Definition at line 77 of file Ellipsoid.tpp.
References hypro::EllipsoidT< Number, Converter >::approxEllipsoidTMatrix(), and hypro::EllipsoidT< Number, Converter >::matrix().
template<typename Number, typename Converter> EllipsoidT<Number, Converter>& hypro::EllipsoidT< Number, Converter >::operator= (const EllipsoidT< Number, Converter > & rhs) default
Assignment operator.
Parameters
rhs An EllipsoidT.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/Ellipsoids/Ellipsoid.h
/home/travis/build/hypro/hypro/src/hypro/representations/Ellipsoids/Ellipsoid.tpp