HyPro: hypro::HybridSystemParser Class Reference
hypro::HybridSystemParser Class Reference
#include <HybridSystemParser.h>
Classes
class ActualParmsContext
class AddExpressionContext
class AdressableContext
class AdressableIdContext
class AdressablePairContext
class AdressableProjContext
class AdressablesContext
class AlgVarsDefsContext
class AndExpressionContext
class AutDeclContext
class AutomatonBodyContext
class CompareExpressionContext
class ConstantDefsContext
class ContDeclContext
class ContDeclsContext
class ControllabilityContext
class CoreEdgeContext
class DeclContext
class DictPairsContext
class DiscDeclContext
class DiscDeclsContext
class EdgeEventContext
class EdgeEventsContext
class EnumDefsContext
class EquationContext
class EquationDerivateContext
class EquationNonDerivateContext
class EquationsContext
class EventsContext
class EventTypeContext
class ExpressionContext
class ExpressionFactorContext
class ExpressionsContext
class ExprFactContext
class ExprFactNameContext
class ExprFactNumberContext
class ExprFactRealNumberContext
class FieldContext
class FieldsContext
class FormalDeclarationContext
class FormalDeclsContext
class FormalParmsContext
class FuncBodyContext
class FuncExpressionContext
class FuncParamDeclsContext
class FuncParamsContext
class FuncStatementContext
class FuncStatementsContext
class FuncVarDeclContext
class FuncVarDeclsContext
class GroupBodyContext
class GroupDeclContext
class IdentifierContext
class ImportsContext
struct Initializer
class InvariantContext
class InvariantDeclsContext
class InvariantsContext
class InvDisablesContext
class InvDisablesSetContext
class InvExprContext
class InvNeedsContext
class InvNeedsSetContext
class IoDeclsContext
class LocationContext
class LocationElementContext
class LocationElementsContext
class LocationsContext
class LocContext
class LocElemContext
class LocElemEdgeToContext
class LocElemEqsContext
class LocElemInitialFlagContext
class LocElemInitialFlagExprContext
class LocElemInvContext
class LocElemLoopContext
class LocElemMarkedContext
class LocElemMarkedExprContext
class LocElemUrgentContext
class LocIdContext
class LocIdElemContext
class MulExpressionContext
class NameContext
class NamesContext
class NameSetContext
class NonEmptySetExpressionContext
class OptAutDeclsContext
class OptControllabilityContext
class OptDerivateContext
class OptEdgeGuardContext
class OptEdgeUpdateContext
class OptEdgeUrgentContext
class OptElifExprsContext
class OptElifFuncStatsContext
class OptElifUpdatesContext
class OptElseFuncStatContext
class OptElseUpdateContext
class OptExpressionContext
class OptGroupDeclsContext
class OptIoDeclsContext
class OptPrintFileContext
class OptPrintForsContext
class OptPrintWhenContext
class OptSupKindContext
class OptSvgCopyPostContext
class OptSvgCopyPreContext
class OptSvgFileContext
class OptSvgInEventElifsContext
class OrExpressionContext
class PrintContext
class PrintFileContext
class PrintForContext
class PrintForsContext
class PrintTxtContext
class ProjectionContext
class ProjectionsContext
class SpecificationContext
class StdLibFunctionContext
class StringTokenContext
class SupKindContext
class SvgAttrContext
class SvgCopyContext
class SvgFileContext
class SvgInContext
class SvgInEventContext
class SvgInEventElifsContext
class SvgMoveContext
class SvgOutContext
class SwitchBodyContext
class SwitchCasesContext
class TypeContext
class TypeDefsContext
class TypesContext
class UnaryExprContext
class UnaryExpressionContext
class UnaryExprFuncContext
class UnaryExprMinusContext
class UnaryExprPlusContext
class UpdateContext
class UpdateIfContext
class UpdateNonIfContext
class UpdatesContext
Public Types
enum {
T__0 = 1, T__1 = 2, T__2 = 3, T__3 = 4,
T__4 = 5, T__5 = 6, T__6 = 7, T__7 = 8,
T__8 = 9, T__9 = 10, T__10 = 11, T__11 = 12,
T__12 = 13, T__13 = 14, T__14 = 15, T__15 = 16,
T__16 = 17, T__17 = 18, T__18 = 19, T__19 = 20,
T__20 = 21, T__21 = 22, T__22 = 23, T__23 = 24,
T__24 = 25, T__25 = 26, T__26 = 27, T__27 = 28,
T__28 = 29, T__29 = 30, T__30 = 31, T__31 = 32,
T__32 = 33, T__33 = 34, T__34 = 35, T__35 = 36,
T__36 = 37, T__37 = 38, T__38 = 39, T__39 = 40,
T__40 = 41, T__41 = 42, T__42 = 43, T__43 = 44,
T__44 = 45, T__45 = 46, T__46 = 47, T__47 = 48,
T__48 = 49, T__49 = 50, T__50 = 51, T__51 = 52,
T__52 = 53, T__53 = 54, T__54 = 55, T__55 = 56,
T__56 = 57, T__57 = 58, T__58 = 59, T__59 = 60,
T__60 = 61, T__61 = 62, T__62 = 63, T__63 = 64,
T__64 = 65, T__65 = 66, T__66 = 67, T__67 = 68,
T__68 = 69, T__69 = 70, T__70 = 71, T__71 = 72,
T__72 = 73, T__73 = 74, T__74 = 75, T__75 = 76,
T__76 = 77, T__77 = 78, T__78 = 79, T__79 = 80,
T__80 = 81, T__81 = 82, T__82 = 83, T__83 = 84,
T__84 = 85, T__85 = 86, T__86 = 87, T__87 = 88,
T__88 = 89, T__89 = 90, T__90 = 91, T__91 = 92,
T__92 = 93, T__93 = 94, T__94 = 95, T__95 = 96,
T__96 = 97, T__97 = 98, T__98 = 99, T__99 = 100,
T__100 = 101, T__101 = 102, T__102 = 103, T__103 = 104,
T__104 = 105, T__105 = 106, T__106 = 107, T__107 = 108,
T__108 = 109, T__109 = 110, T__110 = 111, T__111 = 112,
T__112 = 113, T__113 = 114, T__114 = 115, T__115 = 116,
T__116 = 117, T__117 = 118, T__118 = 119, T__119 = 120,
T__120 = 121, T__121 = 122, T__122 = 123, T__123 = 124,
T__124 = 125, T__125 = 126, T__126 = 127, T__127 = 128,
T__128 = 129, T__129 = 130, T__130 = 131, T__131 = 132,
T__132 = 133, T__133 = 134, T__134 = 135, T__135 = 136,
MULOP = 137, ADDOP = 138, COMPOP = 139, NUMBER = 140,
REALNUMBER = 141, STRING = 142, IDENTIFIER = 143, RELATIVENAME = 144,
ABSOLUTENAME = 145, ROOTNAME = 146, WS = 147
}
enum {
RuleSpecification = 0, RuleGroupBody = 1, RuleAutomatonBody = 2, RuleOptGroupDecls = 3,
RuleGroupDecl = 4, RuleOptAutDecls = 5, RuleAutDecl = 6, RuleDecl = 7,
RuleImports = 8, RuleTypeDefs = 9, RuleEnumDefs = 10, RuleConstantDefs = 11,
RuleAlgVarsDefs = 12, RuleFuncParams = 13, RuleFuncParamDecls = 14, RuleFuncBody = 15,
RuleFuncVarDecls = 16, RuleFuncVarDecl = 17, RuleFuncStatements = 18, RuleFuncStatement = 19,
RuleOptElifFuncStats = 20, RuleOptElseFuncStat = 21, RuleEvents = 22, RuleActualParms = 23,
RuleFormalParms = 24, RuleFormalDecls = 25, RuleFormalDeclaration = 26, RuleDiscDecls = 27,
RuleDiscDecl = 28, RuleContDecls = 29, RuleContDecl = 30, RuleOptDerivate = 31,
RuleOptControllability = 32, RuleControllability = 33, RuleEventType = 34, RuleExpressions = 35,
RuleOptExpression = 36, RuleExpression = 37, RuleEquations = 38, RuleEquation = 39,
RuleOrExpression = 40, RuleAndExpression = 41, RuleCompareExpression = 42, RuleAddExpression = 43,
RuleMulExpression = 44, RuleUnaryExpression = 45, RuleFuncExpression = 46, RuleExpressionFactor = 47,
RuleNonEmptySetExpression = 48, RuleDictPairs = 49, RuleOptElifExprs = 50, RuleSwitchBody = 51,
RuleSwitchCases = 52, RuleTypes = 53, RuleType = 54, RuleFields = 55,
RuleField = 56, RuleNameSet = 57, RuleNames = 58, RuleName = 59,
RuleOptSupKind = 60, RuleSupKind = 61, RuleIdentifier = 62, RuleStringToken = 63,
RuleStdLibFunction = 64, RuleLocations = 65, RuleLocation = 66, RuleLocationElements = 67,
RuleLocationElement = 68, RuleCoreEdge = 69, RuleOptEdgeGuard = 70, RuleOptEdgeUrgent = 71,
RuleOptEdgeUpdate = 72, RuleEdgeEvents = 73, RuleEdgeEvent = 74, RuleInvariantDecls = 75,
RuleInvariants = 76, RuleInvariant = 77, RuleUpdates = 78, RuleUpdate = 79,
RuleOptElifUpdates = 80, RuleOptElseUpdate = 81, RuleAdressables = 82, RuleAdressable = 83,
RuleProjections = 84, RuleProjection = 85, RuleOptIoDecls = 86, RuleIoDecls = 87,
RuleSvgFile = 88, RuleOptSvgFile = 89, RuleSvgCopy = 90, RuleOptSvgCopyPre = 91,
RuleOptSvgCopyPost = 92, RuleSvgMove = 93, RuleSvgOut = 94, RuleSvgAttr = 95,
RuleSvgIn = 96, RuleSvgInEvent = 97, RuleOptSvgInEventElifs = 98, RuleSvgInEventElifs = 99,
RulePrintFile = 100, RulePrint = 101, RulePrintTxt = 102, RuleOptPrintFors = 103,
RulePrintFors = 104, RulePrintFor = 105, RuleOptPrintWhen = 106, RuleOptPrintFile = 107
}
Public Member Functions
HybridSystemParser (antlr4::TokenStream *input)
~HybridSystemParser ()
virtual std::string getGrammarFileName () const override
virtual const antlr4::atn::ATN & getATN () const override
virtual const std::vector< std::string > & getTokenNames () const override
virtual const std::vector< std::string > & getRuleNames () const override
virtual antlr4::dfa::Vocabulary & getVocabulary () const override
SpecificationContext * specification ()
GroupBodyContext * groupBody ()
AutomatonBodyContext * automatonBody ()
OptGroupDeclsContext * optGroupDecls ()
GroupDeclContext * groupDecl ()
OptAutDeclsContext * optAutDecls ()
AutDeclContext * autDecl ()
DeclContext * decl ()
ImportsContext * imports ()
TypeDefsContext * typeDefs ()
EnumDefsContext * enumDefs ()
ConstantDefsContext * constantDefs ()
AlgVarsDefsContext * algVarsDefs ()
FuncParamsContext * funcParams ()
FuncParamDeclsContext * funcParamDecls ()
FuncBodyContext * funcBody ()
FuncVarDeclsContext * funcVarDecls ()
FuncVarDeclContext * funcVarDecl ()
FuncStatementsContext * funcStatements ()
FuncStatementContext * funcStatement ()
OptElifFuncStatsContext * optElifFuncStats ()
OptElseFuncStatContext * optElseFuncStat ()
EventsContext * events ()
ActualParmsContext * actualParms ()
FormalParmsContext * formalParms ()
FormalDeclsContext * formalDecls ()
FormalDeclarationContext * formalDeclaration ()
DiscDeclsContext * discDecls ()
DiscDeclContext * discDecl ()
ContDeclsContext * contDecls ()
ContDeclContext * contDecl ()
OptDerivateContext * optDerivate ()
OptControllabilityContext * optControllability ()
ControllabilityContext * controllability ()
EventTypeContext * eventType ()
ExpressionsContext * expressions ()
OptExpressionContext * optExpression ()
ExpressionContext * expression ()
EquationsContext * equations ()
EquationContext * equation ()
OrExpressionContext * orExpression ()
AndExpressionContext * andExpression ()
CompareExpressionContext * compareExpression ()
AddExpressionContext * addExpression ()
MulExpressionContext * mulExpression ()
UnaryExpressionContext * unaryExpression ()
FuncExpressionContext * funcExpression ()
ExpressionFactorContext * expressionFactor ()
NonEmptySetExpressionContext * nonEmptySetExpression ()
DictPairsContext * dictPairs ()
OptElifExprsContext * optElifExprs ()
SwitchBodyContext * switchBody ()
SwitchCasesContext * switchCases ()
TypesContext * types ()
TypeContext * type ()
FieldsContext * fields ()
FieldContext * field ()
NameSetContext * nameSet ()
NamesContext * names ()
NameContext * name ()
OptSupKindContext * optSupKind ()
SupKindContext * supKind ()
IdentifierContext * identifier ()
StringTokenContext * stringToken ()
StdLibFunctionContext * stdLibFunction ()
LocationsContext * locations ()
LocationContext * location ()
LocationElementsContext * locationElements ()
LocationElementContext * locationElement ()
CoreEdgeContext * coreEdge ()
OptEdgeGuardContext * optEdgeGuard ()
OptEdgeUrgentContext * optEdgeUrgent ()
OptEdgeUpdateContext * optEdgeUpdate ()
EdgeEventsContext * edgeEvents ()
EdgeEventContext * edgeEvent ()
InvariantDeclsContext * invariantDecls ()
InvariantsContext * invariants ()
InvariantContext * invariant ()
UpdatesContext * updates ()
UpdateContext * update ()
OptElifUpdatesContext * optElifUpdates ()
OptElseUpdateContext * optElseUpdate ()
AdressablesContext * adressables ()
AdressableContext * adressable ()
ProjectionsContext * projections ()
ProjectionContext * projection ()
OptIoDeclsContext * optIoDecls ()
IoDeclsContext * ioDecls ()
SvgFileContext * svgFile ()
OptSvgFileContext * optSvgFile ()
SvgCopyContext * svgCopy ()
OptSvgCopyPreContext * optSvgCopyPre ()
OptSvgCopyPostContext * optSvgCopyPost ()
SvgMoveContext * svgMove ()
SvgOutContext * svgOut ()
SvgAttrContext * svgAttr ()
SvgInContext * svgIn ()
SvgInEventContext * svgInEvent ()
OptSvgInEventElifsContext * optSvgInEventElifs ()
SvgInEventElifsContext * svgInEventElifs ()
PrintFileContext * printFile ()
PrintContext * print ()
PrintTxtContext * printTxt ()
OptPrintForsContext * optPrintFors ()
PrintForsContext * printFors ()
PrintForContext * printFor ()
OptPrintWhenContext * optPrintWhen ()
OptPrintFileContext * optPrintFile ()
Static Private Attributes
static std::vector< antlr4::dfa::DFA > _decisionToDFA
static antlr4::atn::PredictionContextCache _sharedContextCache
static std::vector< std::string > _ruleNames
static std::vector< std::string > _tokenNames
static std::vector< std::string > _literalNames
static std::vector< std::string > _symbolicNames
static antlr4::dfa::Vocabulary _vocabulary
static antlr4::atn::ATN _atn
static std::vector< uint16_t > _serializedATN
static Initializer _init
Detailed Description
Definition at line 13 of file HybridSystemParser.h.
Member Enumeration Documentation
anonymous enum
Enumerator
T__0
T__1
T__2
T__3
T__4
T__5
T__6
T__7
T__8
T__9
T__10
T__11
T__12
T__13
T__14
T__15
T__16
T__17
T__18
T__19
T__20
T__21
T__22
T__23
T__24
T__25
T__26
T__27
T__28
T__29
T__30
T__31
T__32
T__33
T__34
T__35
T__36
T__37
T__38
T__39
T__40
T__41
T__42
T__43
T__44
T__45
T__46
T__47
T__48
T__49
T__50
T__51
T__52
T__53
T__54
T__55
T__56
T__57
T__58
T__59
T__60
T__61
T__62
T__63
T__64
T__65
T__66
T__67
T__68
T__69
T__70
T__71
T__72
T__73
T__74
T__75
T__76
T__77
T__78
T__79
T__80
T__81
T__82
T__83
T__84
T__85
T__86
T__87
T__88
T__89
T__90
T__91
T__92
T__93
T__94
T__95
T__96
T__97
T__98
T__99
T__100
T__101
T__102
T__103
T__104
T__105
T__106
T__107
T__108
T__109
T__110
T__111
T__112
T__113
T__114
T__115
T__116
T__117
T__118
T__119
T__120
T__121
T__122
T__123
T__124
T__125
T__126
T__127
T__128
T__129
T__130
T__131
T__132
T__133
T__134
T__135
MULOP
ADDOP
COMPOP
NUMBER
REALNUMBER
STRING
IDENTIFIER
RELATIVENAME
ABSOLUTENAME
ROOTNAME
WS
Definition at line 15 of file HybridSystemParser.h.
anonymous enum
Enumerator
RuleSpecification
RuleGroupBody
RuleAutomatonBody
RuleOptGroupDecls
RuleGroupDecl
RuleOptAutDecls
RuleAutDecl
RuleDecl
RuleImports
RuleTypeDefs
RuleEnumDefs
RuleConstantDefs
RuleAlgVarsDefs
RuleFuncParams
RuleFuncParamDecls
RuleFuncBody
RuleFuncVarDecls
RuleFuncVarDecl
RuleFuncStatements
RuleFuncStatement
RuleOptElifFuncStats
RuleOptElseFuncStat
RuleEvents
RuleActualParms
RuleFormalParms
RuleFormalDecls
RuleFormalDeclaration
RuleDiscDecls
RuleDiscDecl
RuleContDecls
RuleContDecl
RuleOptDerivate
RuleOptControllability
RuleControllability
RuleEventType
RuleExpressions
RuleOptExpression
RuleExpression
RuleEquations
RuleEquation
RuleOrExpression
RuleAndExpression
RuleCompareExpression
RuleAddExpression
RuleMulExpression
RuleUnaryExpression
RuleFuncExpression
RuleExpressionFactor
RuleNonEmptySetExpression
RuleDictPairs
RuleOptElifExprs
RuleSwitchBody
RuleSwitchCases
RuleTypes
RuleType
RuleFields
RuleField
RuleNameSet
RuleNames
RuleName
RuleOptSupKind
RuleSupKind
RuleIdentifier
RuleStringToken
RuleStdLibFunction
RuleLocations
RuleLocation
RuleLocationElements
RuleLocationElement
RuleCoreEdge
RuleOptEdgeGuard
RuleOptEdgeUrgent
RuleOptEdgeUpdate
RuleEdgeEvents
RuleEdgeEvent
RuleInvariantDecls
RuleInvariants
RuleInvariant
RuleUpdates
RuleUpdate
RuleOptElifUpdates
RuleOptElseUpdate
RuleAdressables
RuleAdressable
RuleProjections
RuleProjection
RuleOptIoDecls
RuleIoDecls
RuleSvgFile
RuleOptSvgFile
RuleSvgCopy
RuleOptSvgCopyPre
RuleOptSvgCopyPost
RuleSvgMove
RuleSvgOut
RuleSvgAttr
RuleSvgIn
RuleSvgInEvent
RuleOptSvgInEventElifs
RuleSvgInEventElifs
RulePrintFile
RulePrint
RulePrintTxt
RuleOptPrintFors
RulePrintFors
RulePrintFor
RuleOptPrintWhen
RuleOptPrintFile
Definition at line 44 of file HybridSystemParser.h.
Constructor & Destructor Documentation
HybridSystemParser::HybridSystemParser (antlr4::TokenStream * input)
Definition at line 14 of file HybridSystemParser.cpp.
References _atn, _decisionToDFA, and _sharedContextCache.
HybridSystemParser::~HybridSystemParser ()
Definition at line 18 of file HybridSystemParser.cpp.
Member Function Documentation
HybridSystemParser::ActualParmsContext * HybridSystemParser::actualParms ()
Definition at line 2202 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::ActualParmsContext::expressions(), RuleActualParms, T__26, and T__27.
HybridSystemParser::AddExpressionContext * HybridSystemParser::addExpression ()
Definition at line 3663 of file HybridSystemParser.cpp.
References ADDOP, hypro::HybridSystemParser::AddExpressionContext::mulExpression(), and RuleAddExpression.
HybridSystemParser::AdressableContext * HybridSystemParser::adressable ()
Definition at line 7395 of file HybridSystemParser.cpp.
References identifier(), projections(), RuleAdressable, T__22, T__26, and T__27.
Referenced by update().
HybridSystemParser::AdressablesContext * HybridSystemParser::adressables ()
Definition at line 7295 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::AdressablesContext::adressable(), RuleAdressables, and T__22.
HybridSystemParser::AlgVarsDefsContext * HybridSystemParser::algVarsDefs ()
Definition at line 1320 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::AlgVarsDefsContext::expression(), hypro::HybridSystemParser::AlgVarsDefsContext::identifier(), RuleAlgVarsDefs, T__22, and T__23.
HybridSystemParser::AndExpressionContext * HybridSystemParser::andExpression ()
Definition at line 3525 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::AndExpressionContext::compareExpression(), RuleAndExpression, and T__47.
HybridSystemParser::AutDeclContext * HybridSystemParser::autDecl ()
Definition at line 643 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::AutDeclContext::decl(), hypro::HybridSystemParser::AutDeclContext::discDecls(), hypro::HybridSystemParser::AutDeclContext::events(), RuleAutDecl, T__1, T__10, T__11, T__9, and hypro::HybridSystemParser::AutDeclContext::type().
HybridSystemParser::AutomatonBodyContext * HybridSystemParser::automatonBody ()
Definition at line 153 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::AutomatonBodyContext::locations(), hypro::HybridSystemParser::AutomatonBodyContext::optAutDecls(), hypro::HybridSystemParser::AutomatonBodyContext::optIoDecls(), and RuleAutomatonBody.
HybridSystemParser::CompareExpressionContext * HybridSystemParser::compareExpression ()
Definition at line 3594 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::CompareExpressionContext::addExpression(), COMPOP, and RuleCompareExpression.
HybridSystemParser::ConstantDefsContext * HybridSystemParser::constantDefs ()
Definition at line 1243 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::ConstantDefsContext::expression(), hypro::HybridSystemParser::ConstantDefsContext::identifier(), RuleConstantDefs, T__22, and T__23.
HybridSystemParser::ContDeclContext * HybridSystemParser::contDecl ()
Definition at line 2758 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::ContDeclContext::expression(), hypro::HybridSystemParser::ContDeclContext::identifier(), hypro::HybridSystemParser::ContDeclContext::optDerivate(), RuleContDecl, and T__23.
HybridSystemParser::ContDeclsContext * HybridSystemParser::contDecls ()
Definition at line 2693 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::ContDeclsContext::contDecl(), RuleContDecls, and T__22.
HybridSystemParser::ControllabilityContext * HybridSystemParser::controllability ()
Definition at line 2927 of file HybridSystemParser.cpp.
References RuleControllability, T__40, and T__41.
HybridSystemParser::CoreEdgeContext * HybridSystemParser::coreEdge ()
Definition at line 6270 of file HybridSystemParser.cpp.
References ABSOLUTENAME, hypro::HybridSystemParser::CoreEdgeContext::edgeEvents(), hypro::HybridSystemParser::CoreEdgeContext::expressions(), IDENTIFIER, hypro::HybridSystemParser::CoreEdgeContext::optEdgeGuard(), hypro::HybridSystemParser::CoreEdgeContext::optEdgeUpdate(), hypro::HybridSystemParser::CoreEdgeContext::optEdgeUrgent(), RELATIVENAME, ROOTNAME, RuleCoreEdge, T__111, T__112, T__113, T__114, and hypro::HybridSystemParser::CoreEdgeContext::updates().
Referenced by locationElement().
HybridSystemParser::DeclContext * HybridSystemParser::decl ()
Definition at line 800 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::DeclContext::algVarsDefs(), hypro::HybridSystemParser::DeclContext::constantDefs(), hypro::HybridSystemParser::DeclContext::contDecls(), hypro::HybridSystemParser::DeclContext::controllability(), hypro::HybridSystemParser::DeclContext::enumDefs(), hypro::HybridSystemParser::DeclContext::equations(), hypro::HybridSystemParser::DeclContext::eventType(), hypro::HybridSystemParser::DeclContext::expressions(), hypro::HybridSystemParser::DeclContext::identifier(), hypro::HybridSystemParser::DeclContext::invariantDecls(), hypro::HybridSystemParser::DeclContext::ioDecls(), hypro::HybridSystemParser::DeclContext::optControllability(), RuleDecl, T__1, T__12, T__13, T__14, T__15, T__16, T__17, T__18, T__19, T__20, T__21, hypro::HybridSystemParser::DeclContext::type(), and hypro::HybridSystemParser::DeclContext::typeDefs().
HybridSystemParser::DictPairsContext * HybridSystemParser::dictPairs ()
Definition at line 4533 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::DictPairsContext::expression(), RuleDictPairs, T__22, and T__4.
Referenced by expressionFactor().
HybridSystemParser::DiscDeclContext * HybridSystemParser::discDecl ()
Definition at line 2600 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::DiscDeclContext::expression(), hypro::HybridSystemParser::DiscDeclContext::expressions(), hypro::HybridSystemParser::DiscDeclContext::identifier(), RuleDiscDecl, T__23, T__24, T__25, T__37, and T__38.
HybridSystemParser::DiscDeclsContext * HybridSystemParser::discDecls ()
Definition at line 2535 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::DiscDeclsContext::discDecl(), RuleDiscDecls, and T__22.
HybridSystemParser::EdgeEventContext * HybridSystemParser::edgeEvent ()
Definition at line 6583 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::EdgeEventContext::expression(), hypro::HybridSystemParser::EdgeEventContext::name(), RuleEdgeEvent, T__114, T__115, and T__60.
HybridSystemParser::EdgeEventsContext * HybridSystemParser::edgeEvents ()
Definition at line 6522 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::EdgeEventsContext::edgeEvent(), RuleEdgeEvents, and T__22.
HybridSystemParser::EnumDefsContext * HybridSystemParser::enumDefs ()
Definition at line 1158 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::EnumDefsContext::identifier(), RuleEnumDefs, T__22, T__23, T__24, and T__25.
HybridSystemParser::EquationContext * HybridSystemParser::equation ()
Definition at line 3389 of file HybridSystemParser.cpp.
References expression(), identifier(), RuleEquation, T__23, and T__45.
HybridSystemParser::EquationsContext * HybridSystemParser::equations ()
Definition at line 3303 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::EquationsContext::equation(), RuleEquations, and T__22.
Referenced by locationElement().
HybridSystemParser::EventsContext * HybridSystemParser::events ()
Definition at line 2145 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::EventsContext::name(), RuleEvents, and T__22.
HybridSystemParser::EventTypeContext * HybridSystemParser::eventType ()
Definition at line 2981 of file HybridSystemParser.cpp.
References ABSOLUTENAME, IDENTIFIER, RELATIVENAME, ROOTNAME, RuleEventType, T__3, T__42, T__63, T__64, T__66, T__67, T__68, T__69, T__70, T__71, T__72, and hypro::HybridSystemParser::EventTypeContext::type().
HybridSystemParser::ExpressionContext * HybridSystemParser::expression ()
Definition at line 3225 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::ExpressionContext::orExpression(), RuleExpression, T__43, and T__44.
Referenced by equation(), expressionFactor(), invariant(), and update().
HybridSystemParser::ExpressionFactorContext * HybridSystemParser::expressionFactor ()
Definition at line 4222 of file HybridSystemParser.cpp.
References dictPairs(), expression(), expressions(), name(), nonEmptySetExpression(), NUMBER, optElifExprs(), REALNUMBER, RuleExpressionFactor, stringToken(), switchBody(), T__22, T__24, T__25, T__26, T__27, T__29, T__35, T__4, T__45, T__52, T__53, T__54, T__55, T__56, T__57, T__58, T__59, T__60, T__61, T__7, and type().
HybridSystemParser::ExpressionsContext * HybridSystemParser::expressions ()
Definition at line 3059 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::ExpressionsContext::expression(), RuleExpressions, and T__22.
Referenced by expressionFactor(), locationElement(), and update().
HybridSystemParser::FieldContext * HybridSystemParser::field ()
Definition at line 5212 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::FieldContext::identifier(), RuleField, and hypro::HybridSystemParser::FieldContext::type().
HybridSystemParser::FieldsContext * HybridSystemParser::fields ()
Definition at line 5151 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::FieldsContext::field(), RuleFields, and T__22.
HybridSystemParser::FormalDeclarationContext * HybridSystemParser::formalDeclaration ()
Definition at line 2413 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::FormalDeclarationContext::controllability(), hypro::HybridSystemParser::FormalDeclarationContext::eventType(), hypro::HybridSystemParser::FormalDeclarationContext::identifier(), hypro::HybridSystemParser::FormalDeclarationContext::name(), hypro::HybridSystemParser::FormalDeclarationContext::optControllability(), RuleFormalDeclaration, T__14, T__16, T__36, and hypro::HybridSystemParser::FormalDeclarationContext::type().
HybridSystemParser::FormalDeclsContext * HybridSystemParser::formalDecls ()
Definition at line 2336 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::FormalDeclsContext::formalDeclaration(), RuleFormalDecls, and T__1.
HybridSystemParser::FormalParmsContext * HybridSystemParser::formalParms ()
Definition at line 2267 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::FormalParmsContext::formalDecls(), RuleFormalParms, T__26, and T__27.
HybridSystemParser::FuncBodyContext * HybridSystemParser::funcBody ()
Definition at line 1559 of file HybridSystemParser.cpp.
References ABSOLUTENAME, hypro::HybridSystemParser::FuncBodyContext::funcStatements(), hypro::HybridSystemParser::FuncBodyContext::funcVarDecls(), IDENTIFIER, RELATIVENAME, ROOTNAME, RuleFuncBody, STRING, hypro::HybridSystemParser::FuncBodyContext::stringToken(), T__1, T__26, T__29, T__3, T__30, T__31, T__32, T__33, T__63, T__64, T__66, T__67, T__68, T__69, T__7, T__70, T__71, and T__72.
HybridSystemParser::FuncExpressionContext * HybridSystemParser::funcExpression ()
Definition at line 4002 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::FuncExpressionContext::expressionFactor(), hypro::HybridSystemParser::FuncExpressionContext::expressions(), hypro::HybridSystemParser::FuncExpressionContext::optExpression(), RuleFuncExpression, hypro::HybridSystemParser::FuncExpressionContext::stdLibFunction(), T__26, T__27, T__4, T__52, and T__53.
Referenced by unaryExpression().
HybridSystemParser::FuncParamDeclsContext * HybridSystemParser::funcParamDecls ()
Definition at line 1490 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::FuncParamDeclsContext::identifier(), RuleFuncParamDecls, T__1, and hypro::HybridSystemParser::FuncParamDeclsContext::type().
HybridSystemParser::FuncParamsContext * HybridSystemParser::funcParams ()
Definition at line 1413 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::FuncParamsContext::funcParamDecls(), RuleFuncParams, T__26, and T__27.
HybridSystemParser::FuncStatementContext * HybridSystemParser::funcStatement ()
Definition at line 1900 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::FuncStatementContext::adressables(), hypro::HybridSystemParser::FuncStatementContext::expressions(), hypro::HybridSystemParser::FuncStatementContext::funcStatements(), IDENTIFIER, hypro::HybridSystemParser::FuncStatementContext::optElifFuncStats(), hypro::HybridSystemParser::FuncStatementContext::optElseFuncStat(), RuleFuncStatement, T__1, T__26, T__28, T__29, T__30, T__31, T__32, T__33, T__4, and T__7.
HybridSystemParser::FuncStatementsContext * HybridSystemParser::funcStatements ()
Definition at line 1825 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::FuncStatementsContext::funcStatement(), IDENTIFIER, RuleFuncStatements, T__26, T__29, T__30, T__31, T__32, and T__33.
HybridSystemParser::FuncVarDeclContext * HybridSystemParser::funcVarDecl ()
Definition at line 1728 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::FuncVarDeclContext::expression(), hypro::HybridSystemParser::FuncVarDeclContext::identifier(), RuleFuncVarDecl, T__22, and T__23.
HybridSystemParser::FuncVarDeclsContext * HybridSystemParser::funcVarDecls ()
Definition at line 1657 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::FuncVarDeclsContext::funcVarDecl(), RuleFuncVarDecls, T__1, and hypro::HybridSystemParser::FuncVarDeclsContext::type().
virtual const antlr4::atn::ATN& hypro::HybridSystemParser::getATN () const inline override virtual
Definition at line 80 of file HybridSystemParser.h.
References _atn.
std::string HybridSystemParser::getGrammarFileName () const override virtual
Definition at line 22 of file HybridSystemParser.cpp.
const std::vector< std::string > & HybridSystemParser::getRuleNames () const override virtual
Definition at line 26 of file HybridSystemParser.cpp.
References _ruleNames.
Referenced by getTokenNames().
virtual const std::vector<std::string>& hypro::HybridSystemParser::getTokenNames () const inline override virtual
Definition at line 81 of file HybridSystemParser.h.
References _tokenNames, getRuleNames(), and getVocabulary().
dfa::Vocabulary & HybridSystemParser::getVocabulary () const override virtual
Definition at line 30 of file HybridSystemParser.cpp.
References _vocabulary.
Referenced by getTokenNames().
HybridSystemParser::GroupBodyContext * HybridSystemParser::groupBody ()
Definition at line 101 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::GroupBodyContext::optGroupDecls(), and RuleGroupBody.
HybridSystemParser::GroupDeclContext * HybridSystemParser::groupDecl ()
Definition at line 342 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::GroupDeclContext::actualParms(), hypro::HybridSystemParser::GroupDeclContext::automatonBody(), hypro::HybridSystemParser::GroupDeclContext::decl(), hypro::HybridSystemParser::GroupDeclContext::formalParms(), hypro::HybridSystemParser::GroupDeclContext::funcBody(), hypro::HybridSystemParser::GroupDeclContext::funcParams(), hypro::HybridSystemParser::GroupDeclContext::groupBody(), IDENTIFIER, hypro::HybridSystemParser::GroupDeclContext::identifier(), hypro::HybridSystemParser::GroupDeclContext::imports(), hypro::HybridSystemParser::GroupDeclContext::name(), hypro::HybridSystemParser::GroupDeclContext::optSupKind(), RELATIVENAME, RuleGroupDecl, hypro::HybridSystemParser::GroupDeclContext::supKind(), T__0, T__1, T__2, T__3, T__4, T__5, T__6, T__7, T__8, and hypro::HybridSystemParser::GroupDeclContext::types().
HybridSystemParser::IdentifierContext * HybridSystemParser::identifier ()
Definition at line 5559 of file HybridSystemParser.cpp.
References IDENTIFIER, and RuleIdentifier.
Referenced by adressable(), equation(), location(), and locationElement().
HybridSystemParser::ImportsContext * HybridSystemParser::imports ()
Definition at line 1020 of file HybridSystemParser.cpp.
References RuleImports, hypro::HybridSystemParser::ImportsContext::stringToken(), and T__22.
HybridSystemParser::InvariantContext * HybridSystemParser::invariant ()
Definition at line 6888 of file HybridSystemParser.cpp.
References expression(), name(), nameSet(), nonEmptySetExpression(), RuleInvariant, T__117, and T__118.
HybridSystemParser::InvariantDeclsContext * HybridSystemParser::invariantDecls ()
Definition at line 6679 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::InvariantDeclsContext::invariants(), hypro::HybridSystemParser::InvariantDeclsContext::optSupKind(), RuleInvariantDecls, hypro::HybridSystemParser::InvariantDeclsContext::supKind(), T__1, and T__116.
Referenced by locationElement().
HybridSystemParser::InvariantsContext * HybridSystemParser::invariants ()
Definition at line 6752 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::InvariantsContext::invariant(), RuleInvariants, and T__22.
HybridSystemParser::IoDeclsContext * HybridSystemParser::ioDecls ()
Definition at line 7667 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::IoDeclsContext::print(), hypro::HybridSystemParser::IoDeclsContext::printFile(), RuleIoDecls, hypro::HybridSystemParser::IoDeclsContext::svgCopy(), hypro::HybridSystemParser::IoDeclsContext::svgFile(), hypro::HybridSystemParser::IoDeclsContext::svgIn(), hypro::HybridSystemParser::IoDeclsContext::svgMove(), hypro::HybridSystemParser::IoDeclsContext::svgOut(), T__119, T__121, T__125, T__127, T__131, T__132, and T__133.
HybridSystemParser::LocationContext * HybridSystemParser::location ()
Definition at line 5833 of file HybridSystemParser.cpp.
References identifier(), locationElements(), RuleLocation, T__1, T__36, and T__4.
HybridSystemParser::LocationElementContext * HybridSystemParser::locationElement ()
Definition at line 6103 of file HybridSystemParser.cpp.
References coreEdge(), equations(), expressions(), identifier(), invariantDecls(), RuleLocationElement, T__1, T__108, T__109, T__110, T__19, T__20, and T__21.
HybridSystemParser::LocationElementsContext * HybridSystemParser::locationElements ()
Definition at line 5930 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::LocationElementsContext::locationElement(), RuleLocationElements, T__108, T__109, T__116, T__19, T__20, T__21, T__73, T__74, and T__75.
Referenced by location().
HybridSystemParser::LocationsContext * HybridSystemParser::locations ()
Definition at line 5731 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::LocationsContext::location(), RuleLocations, and T__36.
HybridSystemParser::MulExpressionContext * HybridSystemParser::mulExpression ()
Definition at line 3732 of file HybridSystemParser.cpp.
References MULOP, RuleMulExpression, and hypro::HybridSystemParser::MulExpressionContext::unaryExpression().
HybridSystemParser::NameContext * HybridSystemParser::name ()
Definition at line 5379 of file HybridSystemParser.cpp.
References ABSOLUTENAME, IDENTIFIER, hypro::HybridSystemParser::NameContext::identifier(), RELATIVENAME, ROOTNAME, and RuleName.
Referenced by expressionFactor(), hypro::HybridSystemParser::Initializer::Initializer(), and invariant().
HybridSystemParser::NamesContext * HybridSystemParser::names ()
Definition at line 5310 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::NamesContext::name(), RuleNames, and T__22.
HybridSystemParser::NameSetContext * HybridSystemParser::nameSet ()
Definition at line 5258 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::NameSetContext::names(), RuleNameSet, T__24, and T__25.
Referenced by invariant().
HybridSystemParser::NonEmptySetExpressionContext * HybridSystemParser::nonEmptySetExpression ()
Definition at line 4481 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::NonEmptySetExpressionContext::expressions(), RuleNonEmptySetExpression, T__24, and T__25.
Referenced by expressionFactor(), and invariant().
HybridSystemParser::OptAutDeclsContext * HybridSystemParser::optAutDecls ()
Definition at line 552 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::OptAutDeclsContext::autDecl(), RuleOptAutDecls, T__10, T__11, T__116, T__119, T__12, T__121, T__125, T__127, T__13, T__131, T__132, T__133, T__14, T__15, T__16, T__17, T__18, T__19, T__20, T__21, T__40, T__41, T__73, T__74, T__75, and T__9.
HybridSystemParser::OptControllabilityContext * HybridSystemParser::optControllability ()
Definition at line 2878 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::OptControllabilityContext::controllability(), RuleOptControllability, T__40, and T__41.
HybridSystemParser::OptDerivateContext * HybridSystemParser::optDerivate ()
Definition at line 2825 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::OptDerivateContext::expression(), RuleOptDerivate, and T__39.
HybridSystemParser::OptEdgeGuardContext * HybridSystemParser::optEdgeGuard ()
Definition at line 6365 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::OptEdgeGuardContext::expressions(), RuleOptEdgeGuard, and T__111.
HybridSystemParser::OptEdgeUpdateContext * HybridSystemParser::optEdgeUpdate ()
Definition at line 6465 of file HybridSystemParser.cpp.
References RuleOptEdgeUpdate, T__113, and hypro::HybridSystemParser::OptEdgeUpdateContext::updates().
HybridSystemParser::OptEdgeUrgentContext * HybridSystemParser::optEdgeUrgent ()
Definition at line 6414 of file HybridSystemParser.cpp.
References RuleOptEdgeUrgent, and T__112.
HybridSystemParser::OptElifExprsContext * HybridSystemParser::optElifExprs ()
Definition at line 4594 of file HybridSystemParser.cpp.
References ABSOLUTENAME, hypro::HybridSystemParser::OptElifExprsContext::expression(), IDENTIFIER, NUMBER, REALNUMBER, RELATIVENAME, ROOTNAME, RuleOptElifExprs, STRING, T__100, T__101, T__102, T__103, T__104, T__105, T__106, T__107, T__24, T__26, T__29, T__34, T__4, T__48, T__49, T__50, T__51, T__52, T__54, T__55, T__56, T__57, T__59, T__60, T__61, T__76, T__77, T__78, T__79, T__80, T__81, T__82, T__83, T__84, T__85, T__86, T__87, T__88, T__89, T__90, T__91, T__92, T__93, T__94, T__95, T__96, T__97, T__98, and T__99.
Referenced by expressionFactor().
HybridSystemParser::OptElifFuncStatsContext * HybridSystemParser::optElifFuncStats ()
Definition at line 2036 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::OptElifFuncStatsContext::expression(), hypro::HybridSystemParser::OptElifFuncStatsContext::funcStatements(), RuleOptElifFuncStats, T__34, and T__4.
HybridSystemParser::OptElifUpdatesContext * HybridSystemParser::optElifUpdates ()
Definition at line 7179 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::OptElifUpdatesContext::expressions(), RuleOptElifUpdates, T__34, T__4, and hypro::HybridSystemParser::OptElifUpdatesContext::updates().
Referenced by update().
HybridSystemParser::OptElseFuncStatContext * HybridSystemParser::optElseFuncStat ()
Definition at line 2095 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::OptElseFuncStatContext::funcStatements(), RuleOptElseFuncStat, and T__35.
HybridSystemParser::OptElseUpdateContext * HybridSystemParser::optElseUpdate ()
Definition at line 7238 of file HybridSystemParser.cpp.
References RuleOptElseUpdate, T__35, and hypro::HybridSystemParser::OptElseUpdateContext::update().
Referenced by update().
HybridSystemParser::OptExpressionContext * HybridSystemParser::optExpression ()
Definition at line 3116 of file HybridSystemParser.cpp.
References ABSOLUTENAME, hypro::HybridSystemParser::OptExpressionContext::expression(), IDENTIFIER, NUMBER, REALNUMBER, RELATIVENAME, ROOTNAME, RuleOptExpression, STRING, T__100, T__101, T__102, T__103, T__104, T__105, T__106, T__107, T__24, T__26, T__29, T__48, T__49, T__50, T__51, T__52, T__54, T__55, T__56, T__57, T__59, T__60, T__61, T__76, T__77, T__78, T__79, T__80, T__81, T__82, T__83, T__84, T__85, T__86, T__87, T__88, T__89, T__90, T__91, T__92, T__93, T__94, T__95, T__96, T__97, T__98, and T__99.
HybridSystemParser::OptGroupDeclsContext * HybridSystemParser::optGroupDecls ()
Definition at line 205 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::OptGroupDeclsContext::groupDecl(), IDENTIFIER, RuleOptGroupDecls, T__0, T__116, T__119, T__12, T__121, T__125, T__127, T__13, T__131, T__132, T__133, T__14, T__15, T__16, T__17, T__18, T__19, T__2, T__20, T__21, T__3, T__40, T__41, T__5, T__73, T__74, T__75, and T__8.
HybridSystemParser::OptIoDeclsContext * HybridSystemParser::optIoDecls ()
Definition at line 7583 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::OptIoDeclsContext::ioDecls(), RuleOptIoDecls, T__119, T__121, T__125, T__127, T__131, T__132, and T__133.
HybridSystemParser::OptPrintFileContext * HybridSystemParser::optPrintFile ()
Definition at line 9055 of file HybridSystemParser.cpp.
References _atn, _decisionToDFA, _literalNames, _ruleNames, _serializedATN, _sharedContextCache, _symbolicNames, _tokenNames, _vocabulary, RuleOptPrintFile, hypro::HybridSystemParser::OptPrintFileContext::stringToken(), and T__120.
HybridSystemParser::OptPrintForsContext * HybridSystemParser::optPrintFors ()
Definition at line 8763 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::OptPrintForsContext::printFors(), RuleOptPrintFors, and T__134.
HybridSystemParser::OptPrintWhenContext * HybridSystemParser::optPrintWhen ()
Definition at line 8966 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::OptPrintWhenContext::expression(), RuleOptPrintWhen, T__111, T__123, and T__124.
HybridSystemParser::OptSupKindContext * HybridSystemParser::optSupKind ()
Definition at line 5454 of file HybridSystemParser.cpp.
References RuleOptSupKind, hypro::HybridSystemParser::OptSupKindContext::supKind(), T__73, T__74, and T__75.
HybridSystemParser::OptSvgCopyPostContext * HybridSystemParser::optSvgCopyPost ()
Definition at line 7985 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::OptSvgCopyPostContext::expression(), RuleOptSvgCopyPost, and T__124.
HybridSystemParser::OptSvgCopyPreContext * HybridSystemParser::optSvgCopyPre ()
Definition at line 7932 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::OptSvgCopyPreContext::expression(), RuleOptSvgCopyPre, and T__123.
HybridSystemParser::OptSvgFileContext * HybridSystemParser::optSvgFile ()
Definition at line 7811 of file HybridSystemParser.cpp.
References RuleOptSvgFile, hypro::HybridSystemParser::OptSvgFileContext::stringToken(), and T__120.
HybridSystemParser::OptSvgInEventElifsContext * HybridSystemParser::optSvgInEventElifs ()
Definition at line 8440 of file HybridSystemParser.cpp.
References RuleOptSvgInEventElifs, hypro::HybridSystemParser::OptSvgInEventElifsContext::svgInEventElifs(), and T__34.
HybridSystemParser::OrExpressionContext * HybridSystemParser::orExpression ()
Definition at line 3464 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::OrExpressionContext::andExpression(), RuleOrExpression, and T__46.
HybridSystemParser::PrintContext * HybridSystemParser::print ()
Definition at line 8622 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::PrintContext::optPrintFile(), hypro::HybridSystemParser::PrintContext::optPrintFors(), hypro::HybridSystemParser::PrintContext::optPrintWhen(), hypro::HybridSystemParser::PrintContext::printTxt(), RulePrint, T__1, and T__133.
HybridSystemParser::PrintFileContext * HybridSystemParser::printFile ()
Definition at line 8562 of file HybridSystemParser.cpp.
References RulePrintFile, hypro::HybridSystemParser::PrintFileContext::stringToken(), T__1, and T__132.
HybridSystemParser::PrintForContext * HybridSystemParser::printFor ()
Definition at line 8877 of file HybridSystemParser.cpp.
References ABSOLUTENAME, IDENTIFIER, hypro::HybridSystemParser::PrintForContext::name(), RELATIVENAME, ROOTNAME, RulePrintFor, T__135, T__14, T__20, and T__56.
HybridSystemParser::PrintForsContext * HybridSystemParser::printFors ()
Definition at line 8820 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::PrintForsContext::printFor(), RulePrintFors, and T__22.
HybridSystemParser::PrintTxtContext * HybridSystemParser::printTxt ()
Definition at line 8680 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::PrintTxtContext::expression(), RulePrintTxt, T__123, and T__124.
HybridSystemParser::ProjectionContext * HybridSystemParser::projection ()
Definition at line 7531 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::ProjectionContext::expression(), RuleProjection, T__52, and T__53.
HybridSystemParser::ProjectionsContext * HybridSystemParser::projections ()
Definition at line 7478 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::ProjectionsContext::projection(), RuleProjections, and T__52.
Referenced by adressable().
HybridSystemParser::SpecificationContext * HybridSystemParser::specification ()
Definition at line 57 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::SpecificationContext::groupBody(), and RuleSpecification.
HybridSystemParser::StdLibFunctionContext * HybridSystemParser::stdLibFunction ()
Definition at line 5643 of file HybridSystemParser.cpp.
References RuleStdLibFunction, T__100, T__101, T__102, T__103, T__104, T__105, T__106, T__107, T__76, T__77, T__78, T__79, T__80, T__81, T__82, T__83, T__84, T__85, T__86, T__87, T__88, T__89, T__90, T__91, T__92, T__93, T__94, T__95, T__96, T__97, T__98, and T__99.
HybridSystemParser::StringTokenContext * HybridSystemParser::stringToken ()
Definition at line 5603 of file HybridSystemParser.cpp.
References RuleStringToken, and STRING.
Referenced by expressionFactor().
HybridSystemParser::SupKindContext * HybridSystemParser::supKind ()
Definition at line 5504 of file HybridSystemParser.cpp.
References RuleSupKind, T__73, T__74, and T__75.
HybridSystemParser::SvgAttrContext * HybridSystemParser::svgAttr ()
Definition at line 8207 of file HybridSystemParser.cpp.
References RuleSvgAttr, hypro::HybridSystemParser::SvgAttrContext::stringToken(), T__129, and T__130.
HybridSystemParser::SvgCopyContext * HybridSystemParser::svgCopy ()
Definition at line 7876 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::SvgCopyContext::expression(), hypro::HybridSystemParser::SvgCopyContext::optSvgCopyPost(), hypro::HybridSystemParser::SvgCopyContext::optSvgCopyPre(), hypro::HybridSystemParser::SvgCopyContext::optSvgFile(), RuleSvgCopy, T__1, T__121, and T__122.
HybridSystemParser::SvgFileContext * HybridSystemParser::svgFile ()
Definition at line 7763 of file HybridSystemParser.cpp.
References RuleSvgFile, hypro::HybridSystemParser::SvgFileContext::stringToken(), T__1, and T__119.
HybridSystemParser::SvgInContext * HybridSystemParser::svgIn ()
Definition at line 8278 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::SvgInContext::expression(), hypro::HybridSystemParser::SvgInContext::optSvgFile(), RuleSvgIn, hypro::HybridSystemParser::SvgInContext::svgInEvent(), T__1, T__122, T__131, and T__14.
HybridSystemParser::SvgInEventContext * HybridSystemParser::svgInEvent ()
Definition at line 8350 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::SvgInEventContext::expression(), hypro::HybridSystemParser::SvgInEventContext::name(), hypro::HybridSystemParser::SvgInEventContext::optSvgInEventElifs(), RuleSvgInEvent, hypro::HybridSystemParser::SvgInEventContext::svgInEventElifs(), T__29, T__35, T__4, and T__7.
HybridSystemParser::SvgInEventElifsContext * HybridSystemParser::svgInEventElifs ()
Definition at line 8503 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::SvgInEventElifsContext::expression(), hypro::HybridSystemParser::SvgInEventElifsContext::name(), RuleSvgInEventElifs, T__34, and T__4.
HybridSystemParser::SvgMoveContext * HybridSystemParser::svgMove ()
Definition at line 8046 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::SvgMoveContext::expression(), RuleSvgMove, hypro::HybridSystemParser::SvgMoveContext::svgFile(), T__1, T__122, T__125, T__126, T__22, T__4, and T__7.
HybridSystemParser::SvgOutContext * HybridSystemParser::svgOut ()
Definition at line 8149 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::SvgOutContext::expression(), hypro::HybridSystemParser::SvgOutContext::optSvgFile(), RuleSvgOut, hypro::HybridSystemParser::SvgOutContext::svgAttr(), T__1, T__122, T__127, and T__128.
HybridSystemParser::SwitchBodyContext * HybridSystemParser::switchBody ()
Definition at line 4711 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::SwitchBodyContext::expression(), RuleSwitchBody, hypro::HybridSystemParser::SwitchBodyContext::switchCases(), and T__35.
Referenced by expressionFactor().
HybridSystemParser::SwitchCasesContext * HybridSystemParser::switchCases ()
Definition at line 4787 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::SwitchCasesContext::expression(), RuleSwitchCases, T__4, and T__62.
HybridSystemParser::TypeContext * HybridSystemParser::type ()
Definition at line 4931 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::TypeContext::expression(), hypro::HybridSystemParser::TypeContext::fields(), hypro::HybridSystemParser::TypeContext::name(), RuleType, T__26, T__27, T__3, T__4, T__52, T__53, T__63, T__64, T__65, T__66, T__67, T__68, T__69, T__70, T__71, T__72, hypro::HybridSystemParser::TypeContext::type(), and hypro::HybridSystemParser::TypeContext::types().
Referenced by expressionFactor().
HybridSystemParser::TypeDefsContext * HybridSystemParser::typeDefs ()
Definition at line 1089 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::TypeDefsContext::identifier(), RuleTypeDefs, T__22, T__23, and hypro::HybridSystemParser::TypeDefsContext::type().
HybridSystemParser::TypesContext * HybridSystemParser::types ()
Definition at line 4850 of file HybridSystemParser.cpp.
References RuleTypes, T__22, and hypro::HybridSystemParser::TypesContext::type().
HybridSystemParser::UnaryExpressionContext * HybridSystemParser::unaryExpression ()
Definition at line 3838 of file HybridSystemParser.cpp.
References ABSOLUTENAME, funcExpression(), IDENTIFIER, NUMBER, REALNUMBER, RELATIVENAME, ROOTNAME, RuleUnaryExpression, STRING, T__100, T__101, T__102, T__103, T__104, T__105, T__106, T__107, T__24, T__26, T__29, T__48, T__49, T__50, T__51, T__52, T__54, T__55, T__56, T__57, T__59, T__60, T__61, T__76, T__77, T__78, T__79, T__80, T__81, T__82, T__83, T__84, T__85, T__86, T__87, T__88, T__89, T__90, T__91, T__92, T__93, T__94, T__95, T__96, T__97, T__98, and T__99.
HybridSystemParser::UpdateContext * HybridSystemParser::update ()
Definition at line 7087 of file HybridSystemParser.cpp.
References adressable(), expression(), expressions(), IDENTIFIER, optElifUpdates(), optElseUpdate(), RuleUpdate, T__26, T__28, T__29, T__4, T__7, and updates().
HybridSystemParser::UpdatesContext * HybridSystemParser::updates ()
Definition at line 6993 of file HybridSystemParser.cpp.
References RuleUpdates, T__22, and hypro::HybridSystemParser::UpdatesContext::update().
Referenced by update().
Member Data Documentation
atn::ATN HybridSystemParser::_atn static private
Definition at line 1966 of file HybridSystemParser.h.
Referenced by getATN(), HybridSystemParser(), hypro::HybridSystemParser::Initializer::Initializer(), and optPrintFile().
std::vector< dfa::DFA > HybridSystemParser::_decisionToDFA static private
Definition at line 1958 of file HybridSystemParser.h.
Referenced by HybridSystemParser(), hypro::HybridSystemParser::Initializer::Initializer(), and optPrintFile().
HybridSystemParser::Initializer HybridSystemParser::_init static private
Definition at line 1973 of file HybridSystemParser.h.
Referenced by hypro::HybridSystemParser::Initializer::Initializer().
std::vector< std::string > HybridSystemParser::_literalNames static private
Initial value:
= {
  "", "'import'", "';'", "'namespace'", "'func'", "':'", "'group'", "'def'",
  "'end'", "'automaton'", "'alphabet'", "'monitor'", "'disc'", "'type'",
  "'enum'", "'event'", "'const'", "'alg'", "'input'", "'cont'", "'equation'",
  "'initial'", "'marked'", "','", "'='", "'{'", "'}'", "'('", "')'", "':='",
  "'if'", "'while'", "'break'", "'continue'", "'return'", "'elif'", "'else'",
  "'location'", "'in'", "'any'", "'der'", "'controllable'", "'uncontrollable'",
  "'void'", "'=>'", "'<=>'", "'''", "'or'", "'and'", "'-'", "'+'", "'not'",
  "'sample'", "'['", "']'", "'true'", "'false'", "'time'", "'<'", "'>'",
  "'switch'", "'?'", "'self'", "'case'", "'bool'", "'int'", "'..'", "'real'",
  "'string'", "'list'", "'set'", "'dict'", "'tuple'", "'dist'", "'plant'",
  "'requirement'", "'supervisor'", "'acosh'", "'acos'", "'asinh'", "'asin'",
  "'atanh'", "'cosh'", "'cos'", "'sinh'", "'sin'", "'tanh'", "'tan'", "'abs'",
  "'cbrt'", "'ceil'", "'del'", "'empty'", "'exp'", "'floor'", "'fmt'", "'ln'",
  "'log'", "'max'", "'min'", "'pop'", "'pow'", "'round'", "'scale'", "'sign'",
  "'size'", "'sqrt'", "'bernoulli'", "'beta'", "'urgent'", "'edge'", "'goto'",
  "'when'", "'now'", "'do'", "'tau'", "'!'", "'invariant'", "'needs'", "'disables'",
  "'svgFile'", "'file'", "'svgCopy'", "'id'", "'pre'", "'post'", "'svgmove'",
  "'to'", "'svgout'", "'value'", "'attr'", "'text'", "'svgin'", "'printFile'",
  "'print'", "'for'", "'final'"
}
Definition at line 1963 of file HybridSystemParser.h.
Referenced by optPrintFile().
std::vector< std::string > HybridSystemParser::_ruleNames static private
Initial value:
= {
  "specification", "groupBody", "automatonBody", "optGroupDecls", "groupDecl",
  "optAutDecls", "autDecl", "decl", "imports", "typeDefs", "enumDefs", "constantDefs",
  "algVarsDefs", "funcParams", "funcParamDecls", "funcBody", "funcVarDecls",
  "funcVarDecl", "funcStatements", "funcStatement", "optElifFuncStats",
  "optElseFuncStat", "events", "actualParms", "formalParms", "formalDecls",
  "formalDeclaration", "discDecls", "discDecl", "contDecls", "contDecl",
  "optDerivate", "optControllability", "controllability", "eventType", "expressions",
  "optExpression", "expression", "equations", "equation", "orExpression",
  "andExpression", "compareExpression", "addExpression", "mulExpression",
  "unaryExpression", "funcExpression", "expressionFactor", "nonEmptySetExpression",
  "dictPairs", "optElifExprs", "switchBody", "switchCases", "types", "type",
  "fields", "field", "nameSet", "names", "name", "optSupKind", "supKind",
  "identifier", "stringToken", "stdLibFunction", "locations", "location",
  "locationElements", "locationElement", "coreEdge", "optEdgeGuard", "optEdgeUrgent",
  "optEdgeUpdate", "edgeEvents", "edgeEvent", "invariantDecls", "invariants",
  "invariant", "updates", "update", "optElifUpdates", "optElseUpdate", "adressables",
  "adressable", "projections", "projection", "optIoDecls", "ioDecls", "svgFile",
  "optSvgFile", "svgCopy", "optSvgCopyPre", "optSvgCopyPost", "svgMove",
  "svgOut", "svgAttr", "svgIn", "svgInEvent", "optSvgInEventElifs", "svgInEventElifs",
  "printFile", "print", "printTxt", "optPrintFors", "printFors", "printFor",
  "optPrintWhen", "optPrintFile"
}
Definition at line 1960 of file HybridSystemParser.h.
Referenced by getRuleNames(), and optPrintFile().
std::vector< uint16_t > HybridSystemParser::_serializedATN static private
Definition at line 1967 of file HybridSystemParser.h.
Referenced by hypro::HybridSystemParser::Initializer::Initializer(), and optPrintFile().
atn::PredictionContextCache HybridSystemParser::_sharedContextCache static private
Definition at line 1959 of file HybridSystemParser.h.
Referenced by HybridSystemParser(), and optPrintFile().
std::vector< std::string > HybridSystemParser::_symbolicNames static private
Initial value:
= {
  "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
  "", "", "", "", "", "", "", "", "", "", "", "MULOP", "ADDOP", "COMPOP",
  "NUMBER", "REALNUMBER", "STRING", "IDENTIFIER", "RELATIVENAME", "ABSOLUTENAME",
  "ROOTNAME", "WS"
}
Definition at line 1964 of file HybridSystemParser.h.
Referenced by hypro::HybridSystemParser::Initializer::Initializer(), and optPrintFile().
std::vector< std::string > HybridSystemParser::_tokenNames static private
Definition at line 1961 of file HybridSystemParser.h.
Referenced by getTokenNames(), hypro::HybridSystemParser::Initializer::Initializer(), and optPrintFile().
dfa::Vocabulary HybridSystemParser::_vocabulary static private
Definition at line 1965 of file HybridSystemParser.h.
Referenced by getVocabulary(), hypro::HybridSystemParser::Initializer::Initializer(), and optPrintFile().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-cif/HybridSystemParser.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-cif/HybridSystemParser.cpp