HyPro: hypro::Domain< Number > Class Template Reference
hypro::Domain< Number > Class Template Reference
Public Member Functions
Domain ()
Domain (const Domain< Number > &domain)
~Domain ()
void assign (const carl::Variable &v, const carl::Interval< Number > &I)
bool find_assignment (carl::Interval< Number > &I, const carl::Variable &v) const
void clear ()
std::map< carl::Variable, carl::Interval< Number > > & get_assignments ()
Domain< Number > & operator= (const Domain< Number > &domain)
Protected Types
using assignment_type = std::pair< const carl::Variable, carl::Interval< Number >>
Protected Attributes
std::map< carl::Variable, carl::Interval< Number > > assignments
Friends
template<typename N >
std::ostream & operator<< (std::ostream &os, const Domain< N > &domain)
Detailed Description
template<typename Number>
class hypro::Domain< Number >
Definition at line 21 of file TaylorModel.h.
Member Typedef Documentation
template<typename Number> using hypro::Domain< Number >::assignment_type = std::pair<const carl::Variable, carl::Interval<Number>> protected
Definition at line 24 of file TaylorModel.h.
Constructor & Destructor Documentation
template<typename Number > hypro::Domain< Number >::Domain ()
Definition at line 762 of file TaylorModel.tpp.
template<typename Number > hypro::Domain< Number >::Domain (const Domain< Number > & domain)
Definition at line 771 of file TaylorModel.tpp.
References hypro::Domain< Number >::assignments.
template<typename Number > hypro::Domain< Number >::~Domain ()
Definition at line 766 of file TaylorModel.tpp.
Member Function Documentation
template<typename Number > void hypro::Domain< Number >::assign (const carl::Variable & v, const carl::Interval< Number > & I)
Definition at line 776 of file TaylorModel.tpp.
Referenced by hypro::Flowpipe< State >::next_picard().
template<typename Number > void hypro::Domain< Number >::clear ()
Definition at line 807 of file TaylorModel.tpp.
template<typename Number > bool hypro::Domain< Number >::find_assignment (carl::Interval< Number > & I, const carl::Variable & v) const
Definition at line 790 of file TaylorModel.tpp.
template<typename Number > std::map< carl::Variable, carl::Interval< Number > > & hypro::Domain< Number >::get_assignments ()
Definition at line 802 of file TaylorModel.tpp.
Referenced by hypro::TaylorModel< Number >::cutoff(), hypro::TaylorModel< Number >::cutoff_nr(), hypro::TaylorModel< Number >::enclosure(), hypro::TaylorModel< Number >::normalize(), hypro::TaylorModel< Number >::poly_enclosure(), and hypro::TaylorModel< Number >::truncation().
template<typename Number > Domain< Number > & hypro::Domain< Number >::operator= (const Domain< Number > & domain)
Definition at line 812 of file TaylorModel.tpp.
References hypro::Domain< Number >::assignments.
Friends And Related Function Documentation
template<typename Number> template<typename N > std::ostream& operator<< (std::ostream & os, const Domain< N > & domain) friend
Definition at line 820 of file TaylorModel.tpp.
Member Data Documentation
template<typename Number> std::map<carl::Variable, carl::Interval<Number> > hypro::Domain< Number >::assignments protected
Definition at line 23 of file TaylorModel.h.
Referenced by hypro::Domain< Number >::Domain(), and hypro::Domain< Number >::operator=().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/TaylorModel/TaylorModel.h
/home/travis/build/hypro/hypro/src/hypro/representations/TaylorModel/TaylorModel.tpp