HyPro: hypro::IntersectHalfspaceOp< Number, Converter, Setting > Class Template Reference
hypro::IntersectHalfspaceOp< Number, Converter, Setting > Class Template Reference
#include <IntersectHalfspaceOp.h>
Public Member Functions
IntersectHalfspaceOp ()=delete
IntersectHalfspaceOp (const SupportFunctionNewT< Number, Converter, Setting > &origin, const Halfspace< Number > &h)
IntersectHalfspaceOp (const IntersectHalfspaceData< Number > &d)
~IntersectHalfspaceOp ()
SFNEW_TYPE getType () const
unsigned getOriginCount () const
std::size_t getDimension () const
Halfspace< Number > getHalfspace () const
RGNData * getData () const
void setDimension (const std::size_t d)
matrix_t< Number > transform (const matrix_t< Number > &param) const
std::vector< EvaluationResult< Number > > compute (const matrix_t< Number > &, bool) const
std::vector< EvaluationResult< Number > > aggregate (std::vector< std::vector< EvaluationResult< Number >>> &resultStackBack, const matrix_t< Number > &directions) const
EvaluationResult< Number > resolveEvaluationResults (const EvaluationResult< Number > &other, const vector_t< Number > &dir) const
EvaluationResult< Number > leGuernic (const vector_t< Number > &direction) const
EvaluationResult< Number > leGuernicFast (const vector_t< Number > &direction) const
bool empty (const std::vector< bool > &childrenEmpty) const
Point< Number > supremumPoint (std::vector< Point< Number >> &points) const
vector_t< Number > reverseOp (const vector_t< Number > &point) const
bool contains (const std::vector< bool > &v, const vector_t< Number > &point) const
Public Member Functions inherited from hypro::RootGrowNode< Number, Converter, Setting >
RootGrowNode ()
virtual ~RootGrowNode ()
virtual PointerVec getChildren () const
virtual PointerVec & rGetChildren ()
virtual SETSTATE isEmpty () const
virtual LeafData getLeafData () const
void addToChildren (const std::shared_ptr< RootGrowNode > &rhs)
void clearChildren ()
virtual void print (std::ostream &ostr) const
virtual bool empty () const
virtual Point< Number > supremumPoint () const
virtual bool contains (const vector_t< Number > &) const
virtual std::vector< std::size_t > intersectDims (const std::vector< std::vector< std::size_t >> &dims) const
Private Types
using PointerVec = typename RootGrowNode< Number, Converter, Setting >::PointerVec
Private Attributes
SFNEW_TYPE type = SFNEW_TYPE::INTERSECTHSPACEOP
unsigned originCount
PointerVec mChildren
std::size_t mDimension
Halfspace< Number > hspace
Additional Inherited Members
Public Types inherited from hypro::RootGrowNode< Number, Converter, Setting >
using PointerVec = std::vector< std::shared_ptr< RootGrowNode< Number, Converter, Setting >>>
Protected Attributes inherited from hypro::RootGrowNode< Number, Converter, Setting >
SFNEW_TYPE mType = NODE
unsigned originCount = 0
PointerVec mChildren = PointerVec()
std::size_t mDimension = 0
SETSTATE mEmptyState = SETSTATE::UNKNOWN
Detailed Description
template<typename Number, typename Converter, typename Setting>
class hypro::IntersectHalfspaceOp< Number, Converter, Setting >
Definition at line 34 of file IntersectHalfspaceOp.h.
Member Typedef Documentation
template<typename Number , typename Converter , typename Setting > using hypro::IntersectHalfspaceOp< Number, Converter, Setting >::PointerVec = typename RootGrowNode<Number, Converter, Setting>::PointerVec private
Definition at line 38 of file IntersectHalfspaceOp.h.
Constructor & Destructor Documentation
template<typename Number , typename Converter , typename Setting > hypro::IntersectHalfspaceOp< Number, Converter, Setting >::IntersectHalfspaceOp () delete
template<typename Number , typename Converter , typename Setting > hypro::IntersectHalfspaceOp< Number, Converter, Setting >::IntersectHalfspaceOp (const SupportFunctionNewT< Number, Converter, Setting > & origin, const Halfspace< Number > & h) inline
Definition at line 56 of file IntersectHalfspaceOp.h.
References hypro::SupportFunctionNewT< Number, Converter, Setting >::addOperation().
template<typename Number , typename Converter , typename Setting > hypro::IntersectHalfspaceOp< Number, Converter, Setting >::IntersectHalfspaceOp (const IntersectHalfspaceData< Number > & d) inline
Definition at line 64 of file IntersectHalfspaceOp.h.
References d, and hypro::IntersectHalfspaceData< Number >::hspace.
template<typename Number , typename Converter , typename Setting > hypro::IntersectHalfspaceOp< Number, Converter, Setting >::~IntersectHalfspaceOp () inline
Definition at line 70 of file IntersectHalfspaceOp.h.
Member Function Documentation
template<typename Number , typename Converter , typename Setting > std::vector<EvaluationResult<Number> > hypro::IntersectHalfspaceOp< Number, Converter, Setting >::aggregate (std::vector< std::vector< EvaluationResult< Number >>> & resultStackBack, const matrix_t< Number > & directions) const inline virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 95 of file IntersectHalfspaceOp.h.
References assert(), i, and hypro::Halfspace< Number >::normal().
template<typename Number , typename Converter , typename Setting > std::vector<EvaluationResult<Number> > hypro::IntersectHalfspaceOp< Number, Converter, Setting >::compute (const matrix_t< Number > & , bool) const inline virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 89 of file IntersectHalfspaceOp.h.
References assert().
template<typename Number , typename Converter , typename Setting > bool hypro::IntersectHalfspaceOp< Number, Converter, Setting >::contains (const std::vector< bool > & v, const vector_t< Number > & point) const inline virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 327 of file IntersectHalfspaceOp.h.
References assert(), and hypro::Halfspace< Number >::contains().
template<typename Number , typename Converter , typename Setting > bool hypro::IntersectHalfspaceOp< Number, Converter, Setting >::empty (const std::vector< bool > & childrenEmpty) const inline virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 286 of file IntersectHalfspaceOp.h.
References assert(), hypro::EMPTY, hypro::SupportFunctionNewT< Number, Converter, Setting >::evaluate(), hypro::NONEMPTY, hypro::Halfspace< Number >::normal(), hypro::Halfspace< Number >::offset(), and hypro::UNKNOWN.
template<typename Number , typename Converter , typename Setting > RGNData* hypro::IntersectHalfspaceOp< Number, Converter, Setting >::getData () const inline virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 78 of file IntersectHalfspaceOp.h.
References hypro::IntersectHalfspaceData< Number >::hspace.
template<typename Number , typename Converter , typename Setting > std::size_t hypro::IntersectHalfspaceOp< Number, Converter, Setting >::getDimension () const inline virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 76 of file IntersectHalfspaceOp.h.
template<typename Number , typename Converter , typename Setting > Halfspace<Number> hypro::IntersectHalfspaceOp< Number, Converter, Setting >::getHalfspace () const inline
Definition at line 77 of file IntersectHalfspaceOp.h.
References hypro::IntersectHalfspaceData< Number >::hspace.
template<typename Number , typename Converter , typename Setting > unsigned hypro::IntersectHalfspaceOp< Number, Converter, Setting >::getOriginCount () const inline virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 75 of file IntersectHalfspaceOp.h.
template<typename Number , typename Converter , typename Setting > SFNEW_TYPE hypro::IntersectHalfspaceOp< Number, Converter, Setting >::getType () const inline virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 74 of file IntersectHalfspaceOp.h.
References type.
template<typename Number , typename Converter , typename Setting > EvaluationResult<Number> hypro::IntersectHalfspaceOp< Number, Converter, Setting >::leGuernic (const vector_t< Number > & direction) const inline
Definition at line 131 of file IntersectHalfspaceOp.h.
References assert(), hypro::SupportFunctionNewT< Number, Converter, Setting >::evaluate(), hypro::FEAS, hypro::Halfspace< Number >::normal(), hypro::Halfspace< Number >::offset(), PI_UP, hypro::EvaluationResult< Number >::supportValue, and upper.
template<typename Number , typename Converter , typename Setting > EvaluationResult<Number> hypro::IntersectHalfspaceOp< Number, Converter, Setting >::leGuernicFast (const vector_t< Number > & direction) const inline
Definition at line 207 of file IntersectHalfspaceOp.h.
References assert(), hypro::SupportFunctionNewT< Number, Converter, Setting >::evaluate(), hypro::FEAS, i, log, hypro::Halfspace< Number >::normal(), hypro::Halfspace< Number >::offset(), PI_UP, hypro::EvaluationResult< Number >::supportValue, and upper.
template<typename Number , typename Converter , typename Setting > EvaluationResult<Number> hypro::IntersectHalfspaceOp< Number, Converter, Setting >::resolveEvaluationResults (const EvaluationResult< Number > & other, const vector_t< Number > & dir) const inline
Definition at line 112 of file IntersectHalfspaceOp.h.
References hypro::EvaluationResult< Number >::errorCode, hypro::Halfspace< Number >::evaluate(), hypro::FEAS, hypro::INFTY, hypro::EvaluationResult< Number >::optimumValue, and hypro::EvaluationResult< Number >::supportValue.
template<typename Number , typename Converter , typename Setting > vector_t<Number> hypro::IntersectHalfspaceOp< Number, Converter, Setting >::reverseOp (const vector_t< Number > & point) const inline virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 323 of file IntersectHalfspaceOp.h.
References point.
template<typename Number , typename Converter , typename Setting > void hypro::IntersectHalfspaceOp< Number, Converter, Setting >::setDimension (const std::size_t d) inline virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 79 of file IntersectHalfspaceOp.h.
References d.
template<typename Number , typename Converter , typename Setting > Point<Number> hypro::IntersectHalfspaceOp< Number, Converter, Setting >::supremumPoint (std::vector< Point< Number >> & points) const inline virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 308 of file IntersectHalfspaceOp.h.
References assert(), hypro::Halfspace< Number >::contains(), hypro::SupportFunctionNewT< Number, Converter, Setting >::evaluate(), hypro::FEAS, hypro::Halfspace< Number >::normal(), points, and hypro::Point< Number >::Zero().
template<typename Number , typename Converter , typename Setting > matrix_t<Number> hypro::IntersectHalfspaceOp< Number, Converter, Setting >::transform (const matrix_t< Number > & param) const inline virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 84 of file IntersectHalfspaceOp.h.
Member Data Documentation
template<typename Number , typename Converter , typename Setting > Halfspace<Number> hypro::IntersectHalfspaceOp< Number, Converter, Setting >::hspace private
Definition at line 49 of file IntersectHalfspaceOp.h.
template<typename Number , typename Converter , typename Setting > PointerVec hypro::IntersectHalfspaceOp< Number, Converter, Setting >::mChildren private
Definition at line 44 of file IntersectHalfspaceOp.h.
template<typename Number , typename Converter , typename Setting > std::size_t hypro::IntersectHalfspaceOp< Number, Converter, Setting >::mDimension private
Definition at line 45 of file IntersectHalfspaceOp.h.
template<typename Number , typename Converter , typename Setting > unsigned hypro::IntersectHalfspaceOp< Number, Converter, Setting >::originCount private
Definition at line 43 of file IntersectHalfspaceOp.h.
template<typename Number , typename Converter , typename Setting > SFNEW_TYPE hypro::IntersectHalfspaceOp< Number, Converter, Setting >::type = SFNEW_TYPE::INTERSECTHSPACEOP private
Definition at line 42 of file IntersectHalfspaceOp.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunctionNew/IntersectHalfspaceOp.h