HyPro: hypro::LTIContext< State > Class Template Reference
hypro::LTIContext< State > Class Template Reference
Public Member Functions
LTIContext ()=delete
~LTIContext ()
LTIContext (const TaskType &t, const Strategy< State > &strat, WorkQueue< TaskType > *localQueue, WorkQueue< TaskType > *localCEXQueue, Flowpipe< State > &localSegments, ReachabilitySettings &settings)
virtual void execOnStart () override
virtual void execBeforeFirstSegment () override
virtual void firstSegment () override
virtual void execAfterFirstSegment () override
virtual void checkInvariant () override
virtual void intersectBadStates () override
virtual void execBeforeLoop () override
virtual bool doneCondition () override
virtual void checkTransition () override
virtual void applyContinuousEvolution () override
virtual void execOnLoopItExit () override
virtual void processDiscreteBehavior () override
virtual void execOnEnd () override
void initalizeFirstSegmentHandlers ()
void initializeInvariantHandlers ()
void initializeBadStateHandlers ()
void initializeGuardHandlers ()
void applyBacktracking ()
bool omitTransition (Transition< Number > *transition)
bool omitInvariant ()
bool omitBadStateCheck ()
Public Member Functions inherited from hypro::IContext
virtual void execBeforeCheckInvariant ()
virtual void execAfterCheckInvariant ()
virtual void execBeforeIntersectBadStates ()
virtual void execAfterIntersectBadStates ()
virtual void execOnLoopItEnter ()
virtual void execBeforeCheckTransition ()
virtual void execAfterCheckTransition ()
virtual void execBeforeContinuousEvolution ()
virtual void execAfterContinuousEvolution ()
virtual void execAfterLoop ()
virtual void execBeforeProcessDiscreteBehavior ()
virtual void execAfterProcessDiscreteBehavior ()
Protected Attributes
std::shared_ptr< Task< State > > mTask
Strategy< State > mStrategy
WorkQueue< TaskType > * mLocalQueue
WorkQueue< TaskType > * mLocalCEXQueue
Flowpipe< State > & mLocalSegments
ReachabilitySettings mSettings
EventTimingContainer< Number > mLocalTimings
HierarchicalIntervalVector< CONTAINMENT, tNumber > mTransitionTimings
std::vector< std::tuple< Transition< Number > *, State > > mDiscreteSuccessorBuffer
std::map< Transition< Number > *, State > mPotentialZenoTransitions
std::vector< Transition< Number > * > mDisabledTransitions
tNumber mCurrentLocalTime
carl::Interval< tNumber > mCurrentGlobalTimeInterval
carl::Interval< tNumber > mCurrentTimeInterval
State mComputationState
std::vector< IFirstSegmentHandler< State > * > mFirstSegmentHandlers
std::vector< IInvariantHandler * > mInvariantHandlers
std::vector< IBadStateHandler * > mBadStateHandlers
std::vector< ITimeEvolutionHandler * > mContinuousEvolutionHandlers
std::map< Transition< Number > *, std::vector< IGuardHandler< State > * > > mTransitionHandlerMap
Detailed Description
template<typename State>
class hypro::LTIContext< State >
Definition at line 25 of file LTIContext.h.
Constructor & Destructor Documentation
template<typename State> hypro::LTIContext< State >::LTIContext () delete
Referenced by hypro::LTIContext< State >::~LTIContext().
template<typename State> hypro::LTIContext< State >::~LTIContext () inline
Definition at line 63 of file LTIContext.h.
References hypro::LTIContext< State >::applyBacktracking(), hypro::LTIContext< State >::applyContinuousEvolution(), hypro::LTIContext< State >::checkInvariant(), hypro::LTIContext< State >::checkTransition(), hypro::LTIContext< State >::doneCondition(), hypro::LTIContext< State >::execAfterFirstSegment(), hypro::LTIContext< State >::execBeforeFirstSegment(), hypro::LTIContext< State >::execBeforeLoop(), hypro::LTIContext< State >::execOnEnd(), hypro::LTIContext< State >::execOnLoopItExit(), hypro::LTIContext< State >::execOnStart(), hypro::LTIContext< State >::firstSegment(), hypro::LTIContext< State >::initalizeFirstSegmentHandlers(), hypro::LTIContext< State >::initializeBadStateHandlers(), hypro::LTIContext< State >::initializeGuardHandlers(), hypro::LTIContext< State >::initializeInvariantHandlers(), hypro::LTIContext< State >::intersectBadStates(), hypro::LTIContext< State >::LTIContext(), hypro::LTIContext< State >::omitBadStateCheck(), hypro::LTIContext< State >::omitInvariant(), hypro::LTIContext< State >::omitTransition(), and hypro::LTIContext< State >::processDiscreteBehavior().
template<typename State > hypro::LTIContext< State >::LTIContext (const TaskType & t, const Strategy< State > & strat, WorkQueue< TaskType > * localQueue, WorkQueue< TaskType > * localCEXQueue, Flowpipe< State > & localSegments, ReachabilitySettings & settings)
Definition at line 5 of file LTIContext.tpp.
References hypro::BOT, hypro::FULL, hypro::HierarchicalIntervalVector< T, Number >::initialize(), hypro::LTIContext< State >::mComputationState, hypro::LTIContext< State >::mTask, hypro::LTIContext< State >::mTransitionTimings, hypro::NO, and hypro::YES.
Member Function Documentation
template<typename State > void hypro::LTIContext< State >::applyBacktracking ()
Definition at line 125 of file LTIContext.tpp.
References hypro::TreeNode< ReachTreeNode< State > >::getDepth(), hypro::SettingsProvider< State >::getGlobalTimeHorizon(), hypro::ReachTreeNode< State >::getMutex(), hypro::TreeNode< ReachTreeNode< State > >::getParent(), hypro::ReachTreeNode< State >::getRefinements(), hypro::ReachTreeNode< State >::getStateAtLevel(), hypro::RefinementSetting< State >::initialSet, hypro::LTIContext< State >::mLocalCEXQueue, hypro::LTIContext< State >::mStrategy, hypro::LTIContext< State >::mTask, hypro::ReachTreeNode< State >::setNewRefinement(), and hypro::ReachTreeNode< State >::setTimestamp().
Referenced by hypro::LTIContext< State >::intersectBadStates(), and hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::applyContinuousEvolution () override virtual
Implements hypro::IContext.
Reimplemented in hypro::TemplatePolyhedronContext< State >, and hypro::TimedContext< State >.
Definition at line 724 of file LTIContext.tpp.
References hypro::LTIContext< State >::mComputationState, hypro::LTIContext< State >::mContinuousEvolutionHandlers, hypro::LTIContext< State >::mStrategy, and hypro::LTIContext< State >::mTask.
Referenced by hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::checkInvariant () override virtual
Implements hypro::IContext.
Reimplemented in hypro::TimedContext< State >.
Definition at line 413 of file LTIContext.tpp.
References hypro::FULL, hypro::LTIContext< State >::mComputationState, hypro::LTIContext< State >::mInvariantHandlers, hypro::LTIContext< State >::mLocalSegments, hypro::LTIContext< State >::mLocalTimings, hypro::LTIContext< State >::mSettings, hypro::LTIContext< State >::mTask, hypro::NO, hypro::LTIContext< State >::omitInvariant(), hypro::PARTIAL, and hypro::ReachabilitySettings::useInvariantTimingInformation.
Referenced by hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::checkTransition () override virtual
Implements hypro::IContext.
Reimplemented in hypro::TimedContext< State >.
Definition at line 592 of file LTIContext.tpp.
References hypro::ReachabilitySettings::jumpDepth, hypro::LTIContext< State >::mComputationState, hypro::LTIContext< State >::mDisabledTransitions, hypro::LTIContext< State >::mDiscreteSuccessorBuffer, hypro::LTIContext< State >::mLocalTimings, hypro::LTIContext< State >::mSettings, hypro::LTIContext< State >::mTask, hypro::LTIContext< State >::mTransitionHandlerMap, hypro::NO, hypro::LTIContext< State >::omitTransition(), hypro::ReachabilitySettings::useGuardTimingInformation, and hypro::YES.
Referenced by hypro::LTIContext< State >::~LTIContext().
template<typename State > bool hypro::LTIContext< State >::doneCondition () override virtual
Implements hypro::IContext.
Reimplemented in hypro::TimedContext< State >.
Definition at line 586 of file LTIContext.tpp.
References hypro::LTIContext< State >::mContinuousEvolutionHandlers, hypro::LTIContext< State >::mCurrentLocalTime, hypro::LTIContext< State >::mSettings, and hypro::ReachabilitySettings::timeBound.
Referenced by hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::execAfterFirstSegment () override virtual
Reimplemented from hypro::IContext.
Definition at line 394 of file LTIContext.tpp.
References hypro::LTIContext< State >::mComputationState, hypro::LTIContext< State >::mCurrentGlobalTimeInterval, hypro::LTIContext< State >::mCurrentLocalTime, hypro::LTIContext< State >::mCurrentTimeInterval, hypro::LTIContext< State >::mStrategy, and hypro::LTIContext< State >::mTask.
Referenced by hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::execBeforeFirstSegment () override virtual
Reimplemented from hypro::IContext.
Reimplemented in hypro::TemplatePolyhedronContext< State >.
Definition at line 282 of file LTIContext.tpp.
References hypro::Path< Number, tNumber >::addTimeStep(), hypro::Path< Number, tNumber >::addTransition(), hypro::HandlerFactory< State >::buildGuardHandler(), hypro::IGuardHandler< State >::handlerName(), hypro::Path< Number, tNumber >::hasChatteringZeno(), hypro::ReachabilitySettings::jumpDepth, hypro::LTIContext< State >::mComputationState, hypro::LTIContext< State >::mDiscreteSuccessorBuffer, hypro::LTIContext< State >::mLocalTimings, hypro::LTIContext< State >::mPotentialZenoTransitions, hypro::LTIContext< State >::mSettings, hypro::LTIContext< State >::mTask, and hypro::EventTimingProvider< Number >::updateTimings().
Referenced by hypro::TemplatePolyhedronContext< State >::execBeforeFirstSegment(), and hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::execBeforeLoop () override virtual
Reimplemented from hypro::IContext.
Definition at line 531 of file LTIContext.tpp.
References hypro::HandlerFactory< State >::buildContinuousEvolutionHandler(), hypro::HandlerFactory< State >::buildGuardHandler(), hypro::ITimeEvolutionHandler::handlerName(), hypro::LTIContext< State >::initializeGuardHandlers(), hypro::LTIContext< State >::mComputationState, hypro::LTIContext< State >::mContinuousEvolutionHandlers, hypro::LTIContext< State >::mDisabledTransitions, hypro::LTIContext< State >::mFirstSegmentHandlers, hypro::LTIContext< State >::mPotentialZenoTransitions, hypro::LTIContext< State >::mSettings, hypro::LTIContext< State >::mStrategy, hypro::LTIContext< State >::mTask, and hypro::ReachabilitySettings::timeBound.
Referenced by hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::execOnEnd () override virtual
Reimplemented from hypro::IContext.
Definition at line 859 of file LTIContext.tpp.
References hypro::RefinementSetting< State >::fullyComputed, hypro::LTIContext< State >::mLocalTimings, hypro::LTIContext< State >::mSettings, hypro::LTIContext< State >::mTask, hypro::EventTimingProvider< Number >::rGetNode(), hypro::ReachabilitySettings::useBadStateTimingInformation, hypro::ReachabilitySettings::useGuardTimingInformation, and hypro::ReachabilitySettings::useInvariantTimingInformation.
Referenced by hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::execOnLoopItExit () override virtual
Reimplemented from hypro::IContext.
Reimplemented in hypro::TimedContext< State >.
Definition at line 746 of file LTIContext.tpp.
References hypro::LTIContext< State >::mCurrentGlobalTimeInterval, hypro::LTIContext< State >::mCurrentLocalTime, hypro::LTIContext< State >::mCurrentTimeInterval, hypro::LTIContext< State >::mStrategy, and hypro::LTIContext< State >::mTask.
Referenced by hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::execOnStart () override virtual
Reimplemented from hypro::IContext.
Definition at line 216 of file LTIContext.tpp.
References hypro::EventTimingProvider< Number >::getTimings(), hypro::LTIContext< State >::initalizeFirstSegmentHandlers(), hypro::LTIContext< State >::mLocalQueue, hypro::LTIContext< State >::mLocalTimings, hypro::LTIContext< State >::mSettings, hypro::LTIContext< State >::mStrategy, hypro::LTIContext< State >::mTask, hypro::EventTimingProvider< Number >::rGetNode(), hypro::ReachabilitySettings::useBadStateTimingInformation, hypro::ReachabilitySettings::useGuardTimingInformation, and hypro::ReachabilitySettings::useInvariantTimingInformation.
Referenced by hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::firstSegment () override virtual
Implements hypro::IContext.
Reimplemented in hypro::TemplatePolyhedronContext< State >.
Definition at line 380 of file LTIContext.tpp.
References hypro::LTIContext< State >::initializeBadStateHandlers(), hypro::LTIContext< State >::initializeInvariantHandlers(), hypro::LTIContext< State >::mComputationState, and hypro::LTIContext< State >::mFirstSegmentHandlers.
Referenced by hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::initalizeFirstSegmentHandlers ()
Definition at line 23 of file LTIContext.tpp.
References hypro::LTIContext< State >::mComputationState, hypro::LTIContext< State >::mFirstSegmentHandlers, hypro::LTIContext< State >::mStrategy, and hypro::LTIContext< State >::mTask.
Referenced by hypro::LTIContext< State >::execOnStart(), and hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::initializeBadStateHandlers ()
Definition at line 60 of file LTIContext.tpp.
References hypro::affine, hypro::HandlerFactory< State >::buildBadStateHandler(), hypro::getFlowType(), hypro::IBadStateHandler::handlerName(), hypro::isDiscrete(), hypro::LTIContext< State >::mBadStateHandlers, hypro::LTIContext< State >::mComputationState, hypro::LTIContext< State >::mFirstSegmentHandlers, and hypro::rectangular.
Referenced by hypro::LTIContext< State >::firstSegment(), and hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::initializeGuardHandlers ()
Definition at line 86 of file LTIContext.tpp.
References hypro::affine, hypro::HandlerFactory< State >::buildGuardHandler(), hypro::getFlowType(), hypro::IGuardHandler< State >::handlerName(), hypro::isDiscrete(), hypro::LTIContext< State >::mComputationState, hypro::LTIContext< State >::mFirstSegmentHandlers, hypro::LTIContext< State >::mTask, hypro::LTIContext< State >::mTransitionHandlerMap, and hypro::rectangular.
Referenced by hypro::LTIContext< State >::execBeforeLoop(), and hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::initializeInvariantHandlers ()
Definition at line 33 of file LTIContext.tpp.
References hypro::affine, hypro::HandlerFactory< State >::buildInvariantHandler(), hypro::getFlowType(), hypro::IInvariantHandler::handlerName(), hypro::isDiscrete(), hypro::LTIContext< State >::mComputationState, hypro::LTIContext< State >::mFirstSegmentHandlers, hypro::LTIContext< State >::mInvariantHandlers, and hypro::rectangular.
Referenced by hypro::LTIContext< State >::firstSegment(), and hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::intersectBadStates () override virtual
Implements hypro::IContext.
Definition at line 473 of file LTIContext.tpp.
References hypro::LTIContext< State >::applyBacktracking(), hypro::LTIContext< State >::mBadStateHandlers, hypro::LTIContext< State >::mComputationState, hypro::LTIContext< State >::mLocalTimings, hypro::LTIContext< State >::mSettings, hypro::LTIContext< State >::mTask, hypro::NO, hypro::LTIContext< State >::omitBadStateCheck(), hypro::EventTimingProvider< Number >::updateTimings(), hypro::ReachabilitySettings::useBadStateTimingInformation, hypro::ReachabilitySettings::useGuardTimingInformation, hypro::ReachabilitySettings::useInvariantTimingInformation, and hypro::YES.
Referenced by hypro::LTIContext< State >::~LTIContext().
template<typename State > bool hypro::LTIContext< State >::omitBadStateCheck ()
Definition at line 838 of file LTIContext.tpp.
References hypro::LTIContext< State >::mComputationState, hypro::LTIContext< State >::mLocalTimings, hypro::LTIContext< State >::mSettings, hypro::NO, and hypro::ReachabilitySettings::useBadStateTimingInformation.
Referenced by hypro::LTIContext< State >::intersectBadStates(), and hypro::LTIContext< State >::~LTIContext().
template<typename State > bool hypro::LTIContext< State >::omitInvariant ()
Definition at line 817 of file LTIContext.tpp.
References hypro::FULL, hypro::LTIContext< State >::mComputationState, hypro::LTIContext< State >::mLocalTimings, hypro::LTIContext< State >::mSettings, and hypro::ReachabilitySettings::useInvariantTimingInformation.
Referenced by hypro::LTIContext< State >::checkInvariant(), and hypro::LTIContext< State >::~LTIContext().
template<typename State > bool hypro::LTIContext< State >::omitTransition (Transition< Number > * transition)
Definition at line 763 of file LTIContext.tpp.
References hypro::Transition< Number >::getSource(), hypro::Transition< Number >::getTarget(), hypro::LTIContext< State >::mComputationState, hypro::LTIContext< State >::mLocalTimings, hypro::LTIContext< State >::mSettings, hypro::LTIContext< State >::mTask, and hypro::ReachabilitySettings::useGuardTimingInformation.
Referenced by hypro::TimedContext< State >::checkTransition(), hypro::LTIContext< State >::checkTransition(), and hypro::LTIContext< State >::~LTIContext().
template<typename State > void hypro::LTIContext< State >::processDiscreteBehavior () override virtual
Implements hypro::IContext.
Definition at line 753 of file LTIContext.tpp.
References hypro::HandlerFactory< State >::buildDiscreteSuccessorHandler(), hypro::IJumpHandler::handle(), hypro::IJumpHandler::handlerName(), hypro::LTIContext< State >::mDiscreteSuccessorBuffer, hypro::LTIContext< State >::mLocalCEXQueue, hypro::LTIContext< State >::mLocalQueue, hypro::LTIContext< State >::mLocalTimings, hypro::LTIContext< State >::mStrategy, and hypro::LTIContext< State >::mTask.
Referenced by hypro::LTIContext< State >::~LTIContext().
Member Data Documentation
template<typename State> std::vector<IBadStateHandler*> hypro::LTIContext< State >::mBadStateHandlers protected
Definition at line 56 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::initializeBadStateHandlers(), and hypro::LTIContext< State >::intersectBadStates().
template<typename State> State hypro::LTIContext< State >::mComputationState protected
Definition at line 50 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::applyContinuousEvolution(), hypro::LTIContext< State >::checkInvariant(), hypro::LTIContext< State >::checkTransition(), hypro::LTIContext< State >::execAfterFirstSegment(), hypro::LTIContext< State >::execBeforeFirstSegment(), hypro::LTIContext< State >::execBeforeLoop(), hypro::LTIContext< State >::firstSegment(), hypro::LTIContext< State >::initalizeFirstSegmentHandlers(), hypro::LTIContext< State >::initializeBadStateHandlers(), hypro::LTIContext< State >::initializeGuardHandlers(), hypro::LTIContext< State >::initializeInvariantHandlers(), hypro::LTIContext< State >::intersectBadStates(), hypro::LTIContext< State >::LTIContext(), hypro::LTIContext< State >::omitBadStateCheck(), hypro::LTIContext< State >::omitInvariant(), and hypro::LTIContext< State >::omitTransition().
template<typename State> std::vector<ITimeEvolutionHandler*> hypro::LTIContext< State >::mContinuousEvolutionHandlers protected
Definition at line 57 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::applyContinuousEvolution(), hypro::LTIContext< State >::doneCondition(), and hypro::LTIContext< State >::execBeforeLoop().
template<typename State> carl::Interval<tNumber> hypro::LTIContext< State >::mCurrentGlobalTimeInterval protected
Definition at line 46 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::execAfterFirstSegment(), and hypro::LTIContext< State >::execOnLoopItExit().
template<typename State> tNumber hypro::LTIContext< State >::mCurrentLocalTime protected
Definition at line 45 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::doneCondition(), hypro::LTIContext< State >::execAfterFirstSegment(), and hypro::LTIContext< State >::execOnLoopItExit().
template<typename State> carl::Interval<tNumber> hypro::LTIContext< State >::mCurrentTimeInterval protected
Definition at line 47 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::execAfterFirstSegment(), and hypro::LTIContext< State >::execOnLoopItExit().
template<typename State> std::vector<Transition<Number>*> hypro::LTIContext< State >::mDisabledTransitions protected
Definition at line 43 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::checkTransition(), and hypro::LTIContext< State >::execBeforeLoop().
template<typename State> std::vector<std::tuple<Transition<Number>*, State> > hypro::LTIContext< State >::mDiscreteSuccessorBuffer protected
Definition at line 40 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::checkTransition(), hypro::LTIContext< State >::execBeforeFirstSegment(), and hypro::LTIContext< State >::processDiscreteBehavior().
template<typename State> std::vector<IFirstSegmentHandler<State>*> hypro::LTIContext< State >::mFirstSegmentHandlers protected
Definition at line 54 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::execBeforeLoop(), hypro::LTIContext< State >::firstSegment(), hypro::LTIContext< State >::initalizeFirstSegmentHandlers(), hypro::LTIContext< State >::initializeBadStateHandlers(), hypro::LTIContext< State >::initializeGuardHandlers(), and hypro::LTIContext< State >::initializeInvariantHandlers().
template<typename State> std::vector<IInvariantHandler*> hypro::LTIContext< State >::mInvariantHandlers protected
Definition at line 55 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::checkInvariant(), and hypro::LTIContext< State >::initializeInvariantHandlers().
template<typename State> WorkQueue<TaskType>* hypro::LTIContext< State >::mLocalCEXQueue protected
Definition at line 33 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::applyBacktracking(), and hypro::LTIContext< State >::processDiscreteBehavior().
template<typename State> WorkQueue<TaskType>* hypro::LTIContext< State >::mLocalQueue protected
Definition at line 32 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::execOnStart(), and hypro::LTIContext< State >::processDiscreteBehavior().
template<typename State> Flowpipe<State>& hypro::LTIContext< State >::mLocalSegments protected
Definition at line 34 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::checkInvariant().
template<typename State> EventTimingContainer<Number> hypro::LTIContext< State >::mLocalTimings protected
Definition at line 37 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::checkInvariant(), hypro::LTIContext< State >::checkTransition(), hypro::LTIContext< State >::execBeforeFirstSegment(), hypro::LTIContext< State >::execOnEnd(), hypro::LTIContext< State >::execOnStart(), hypro::LTIContext< State >::intersectBadStates(), hypro::LTIContext< State >::omitBadStateCheck(), hypro::LTIContext< State >::omitInvariant(), hypro::LTIContext< State >::omitTransition(), and hypro::LTIContext< State >::processDiscreteBehavior().
template<typename State> std::map<Transition<Number>*, State> hypro::LTIContext< State >::mPotentialZenoTransitions protected
Definition at line 42 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::execBeforeFirstSegment(), and hypro::LTIContext< State >::execBeforeLoop().
template<typename State> ReachabilitySettings hypro::LTIContext< State >::mSettings protected
Definition at line 35 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::checkInvariant(), hypro::LTIContext< State >::checkTransition(), hypro::LTIContext< State >::doneCondition(), hypro::LTIContext< State >::execBeforeFirstSegment(), hypro::LTIContext< State >::execBeforeLoop(), hypro::LTIContext< State >::execOnEnd(), hypro::LTIContext< State >::execOnStart(), hypro::LTIContext< State >::intersectBadStates(), hypro::LTIContext< State >::omitBadStateCheck(), hypro::LTIContext< State >::omitInvariant(), and hypro::LTIContext< State >::omitTransition().
template<typename State> Strategy<State> hypro::LTIContext< State >::mStrategy protected
Definition at line 31 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::applyBacktracking(), hypro::LTIContext< State >::applyContinuousEvolution(), hypro::LTIContext< State >::execAfterFirstSegment(), hypro::LTIContext< State >::execBeforeLoop(), hypro::LTIContext< State >::execOnLoopItExit(), hypro::LTIContext< State >::execOnStart(), hypro::LTIContext< State >::initalizeFirstSegmentHandlers(), and hypro::LTIContext< State >::processDiscreteBehavior().
template<typename State> std::shared_ptr<Task<State> > hypro::LTIContext< State >::mTask protected
Definition at line 30 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::applyBacktracking(), hypro::LTIContext< State >::applyContinuousEvolution(), hypro::LTIContext< State >::checkInvariant(), hypro::LTIContext< State >::checkTransition(), hypro::LTIContext< State >::execAfterFirstSegment(), hypro::LTIContext< State >::execBeforeFirstSegment(), hypro::LTIContext< State >::execBeforeLoop(), hypro::LTIContext< State >::execOnEnd(), hypro::LTIContext< State >::execOnLoopItExit(), hypro::LTIContext< State >::execOnStart(), hypro::LTIContext< State >::initalizeFirstSegmentHandlers(), hypro::LTIContext< State >::initializeGuardHandlers(), hypro::LTIContext< State >::intersectBadStates(), hypro::LTIContext< State >::LTIContext(), hypro::LTIContext< State >::omitTransition(), and hypro::LTIContext< State >::processDiscreteBehavior().
template<typename State> std::map<Transition<Number>*, std::vector<IGuardHandler<State>*> > hypro::LTIContext< State >::mTransitionHandlerMap protected
Definition at line 59 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::checkTransition(), and hypro::LTIContext< State >::initializeGuardHandlers().
template<typename State> HierarchicalIntervalVector<CONTAINMENT, tNumber> hypro::LTIContext< State >::mTransitionTimings protected
Definition at line 38 of file LTIContext.h.
Referenced by hypro::LTIContext< State >::LTIContext().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/contexts/LTIContext.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/contexts/LTIContext.tpp