HyPro: hypro::TPolyFirstSegmentHandler< State > Class Template Reference
hypro::TPolyFirstSegmentHandler< State > Class Template Reference
Public Member Functions
TPolyFirstSegmentHandler ()=delete
TPolyFirstSegmentHandler (State *state, size_t index, tNumber timeStep)
~TPolyFirstSegmentHandler ()
void handle ()
const char * handlerName ()
void setInvariant (const vector_t< Number > &inv)
const matrix_t< typename State::NumberType > & getTrafo () const
const vector_t< typename State::NumberType > & getTranslation () const
const flowVariant< typename State::NumberType > & getTransformation () const
std::optional< vector_t< Number > > getRelaxedInvariant () const
Public Member Functions inherited from hypro::IFirstSegmentHandler< State >
virtual ~IFirstSegmentHandler ()
Detailed Description
template<typename State>
class hypro::TPolyFirstSegmentHandler< State >
Definition at line 16 of file TPolyFirstSegmentHandler.h.
Constructor & Destructor Documentation
template<typename State> hypro::TPolyFirstSegmentHandler< State >::TPolyFirstSegmentHandler () delete
template<typename State> hypro::TPolyFirstSegmentHandler< State >::TPolyFirstSegmentHandler (State * state, size_t index, tNumber timeStep) inline
Definition at line 36 of file TPolyFirstSegmentHandler.h.
template<typename State> hypro::TPolyFirstSegmentHandler< State >::~TPolyFirstSegmentHandler () inline
Definition at line 43 of file TPolyFirstSegmentHandler.h.
References hypro::TPolyFirstSegmentHandler< State >::handle().
Member Function Documentation
template<typename State> std::optional<vector_t<Number> > hypro::TPolyFirstSegmentHandler< State >::getRelaxedInvariant () const inline
Definition at line 56 of file TPolyFirstSegmentHandler.h.
References hypro::interval.
template<typename State> const matrix_t<typename State::NumberType>& hypro::TPolyFirstSegmentHandler< State >::getTrafo () const inline
Definition at line 52 of file TPolyFirstSegmentHandler.h.
template<typename State> const flowVariant<typename State::NumberType>& hypro::TPolyFirstSegmentHandler< State >::getTransformation () const inline virtual
Implements hypro::IFirstSegmentHandler< State >.
Definition at line 54 of file TPolyFirstSegmentHandler.h.
template<typename State> const vector_t<typename State::NumberType>& hypro::TPolyFirstSegmentHandler< State >::getTranslation () const inline
Definition at line 53 of file TPolyFirstSegmentHandler.h.
template<typename State > void hypro::TPolyFirstSegmentHandler< State >::handle () virtual
Implements hypro::IFirstSegmentHandler< State >.
Definition at line 57 of file TPolyFirstSegmentHandler.tpp.
References hypro::EvaluationResult< Number >::errorCode, hypro::FEAS, hypro::INFTY, and hypro::EvaluationResult< Number >::supportValue.
Referenced by hypro::TPolyFirstSegmentHandler< State >::~TPolyFirstSegmentHandler().
template<typename State> const char* hypro::TPolyFirstSegmentHandler< State >::handlerName () inline virtual
Implements hypro::IFirstSegmentHandler< State >.
Definition at line 48 of file TPolyFirstSegmentHandler.h.
References hypro::TPolyFirstSegmentHandler< State >::setInvariant().
template<typename State > void hypro::TPolyFirstSegmentHandler< State >::setInvariant (const vector_t< Number > & inv)
Definition at line 8 of file TPolyFirstSegmentHandler.tpp.
References hypro::interval.
Referenced by hypro::TPolyFirstSegmentHandler< State >::handlerName().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/firstSegmentHandlers/TPolyFirstSegmentHandler.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/firstSegmentHandlers/TPolyFirstSegmentHandler.tpp