HyPro: hypro::ReachTreeNode< State > Class Template Reference
hypro::ReachTreeNode< State > Class Template Reference
#include <ReachTreeNode.h>
Public Types
using Node_t = typename TreeNode< ReachTreeNode< State >>::Node_t
using const_Node_t = typename TreeNode< ReachTreeNode< State >>::const_Node_t
using NodeList_t = typename TreeNode< ReachTreeNode< State >>::NodeList_t
Public Types inherited from hypro::TreeNode< ReachTreeNode< State > >
using Node_t = ReachTreeNode< State > *
pointer to parent node, nullptr if root.
using const_Node_t = const ReachTreeNode< State > *
using NodeList_t = std::vector< ReachTreeNode< State > * >
Public Member Functions
ReachTreeNode (const ReachTreeNode< State > &orig)
~ReachTreeNode ()
ReachTreeNode ()
ReachTreeNode (const State &state, unsigned level=0)
ReachTreeNode (const State &state, unsigned level, ReachTreeNode< State > *parent)
std::mutex & getMutex () const
const Path< Number, tNumber > & getPath () const
const State::repVariant & getSetAtLevel (unsigned level) const
const State & getStateAtLevel (unsigned level) const
const State & getState () const
const carl::Interval< tNumber > & getTimestamp (unsigned level) const
Gets the timestamp of entry (i.e. global timestamp) for a certain level.
const std::vector< RefinementSetting< State > > & getRefinements () const
std::vector< RefinementSetting< State > > & rGetRefinements ()
unsigned getLatestBTLevel () const
unsigned getLatestFullyComputedLevel () const
void getLevelCnt (std::vector< std::size_t > &levels) const
std::vector< ReachTreeNode< State > * > getChildrenForTransition (Transition< Number > *transition) const
bool isFullyComputedOnSomeLevel () const
void updateContent (ReachTreeNode< State > *updatedNode)
void addRefinement (const RefinementSetting< State > &ref)
void setNewRefinement (unsigned level, const RefinementSetting< State > &ref)
void clearRefinements ()
void convertRefinement (unsigned fromLevel, unsigned toLevel)
void setTimestamp (unsigned level, const carl::Interval< tNumber > &timeInterval)
void addTransitionToPath (Transition< Number > *trans, const carl::Interval< tNumber > &enabledTime)
void addTimeStepToPath (const carl::Interval< tNumber > &timeStep)
void refineIntervals ()
bool hasFixedPoint (const State &s, typename ReachTreeNode< State >::Node_t skip) const
void setParent (ReachTreeNode< State > *parent)
std::size_t getDotRepresentation (std::size_t startIndex, std::string &nodes, std::string &transitions, std::vector< unsigned > &levels) const
Public Member Functions inherited from hypro::TreeNode< ReachTreeNode< State > >
TreeNode ()
TreeNode (unsigned _depth, const std::vector< ReachTreeNode< State > * > &_children, ReachTreeNode< State > *_parent)
~TreeNode ()
int getDepth () const
std::size_t getSubtreeDepth () const
std::size_t getSubtreeSize () const
double getAvgSubtreeBranching () const
const std::vector< ReachTreeNode< State > * > & getChildren () const
ReachTreeNode< State > * getParent () const
void setDepth (int _depth)
void addChild (ReachTreeNode< State > *child)
void setParent (ReachTreeNode< State > *parent)
Protected Attributes
Path< Number, tNumber > mPath
std::vector< RefinementSetting< State > > mRefinements
path cache.
std::mutex mutex
ordered list of applied refinements.
Protected Attributes inherited from hypro::TreeNode< ReachTreeNode< State > >
int mDepth
std::vector< ReachTreeNode< State > * > mChildren
depth cache
ReachTreeNode< State > * mParent
children list
Private Types
using Number = typename State::NumberType
Friends
template<typename S >
std::ostream & operator<< (std::ostream &out, const ReachTreeNode< S > &reachTreeNode)
template<typename S >
bool operator< (const ReachTreeNode< S > &lhs, const ReachTreeNode< S > &rhs)
template<typename S >
bool operator== (const ReachTreeNode< S > &lhs, const ReachTreeNode< S > &rhs)
Detailed Description
template<typename State>
class hypro::ReachTreeNode< State >
Definition at line 111 of file ReachTreeNode.h.
Member Typedef Documentation
template<typename State> using hypro::ReachTreeNode< State >::const_Node_t = typename TreeNode<ReachTreeNode<State>>::const_Node_t
Definition at line 122 of file ReachTreeNode.h.
template<typename State> using hypro::ReachTreeNode< State >::Node_t = typename TreeNode<ReachTreeNode<State>>::Node_t
Definition at line 121 of file ReachTreeNode.h.
template<typename State> using hypro::ReachTreeNode< State >::NodeList_t = typename TreeNode<ReachTreeNode<State>>::NodeList_t
Definition at line 123 of file ReachTreeNode.h.
template<typename State> using hypro::ReachTreeNode< State >::Number = typename State::NumberType private
Definition at line 112 of file ReachTreeNode.h.
Constructor & Destructor Documentation
template<typename State> hypro::ReachTreeNode< State >::ReachTreeNode (const ReachTreeNode< State > & orig) inline
Definition at line 126 of file ReachTreeNode.h.
template<typename State> hypro::ReachTreeNode< State >::~ReachTreeNode () inline
Definition at line 135 of file ReachTreeNode.h.
template<typename State> hypro::ReachTreeNode< State >::ReachTreeNode () inline
Definition at line 137 of file ReachTreeNode.h.
template<typename State> hypro::ReachTreeNode< State >::ReachTreeNode (const State & state, unsigned level = 0) inline
Definition at line 145 of file ReachTreeNode.h.
References assert(), and state.
template<typename State> hypro::ReachTreeNode< State >::ReachTreeNode (const State & state, unsigned level, ReachTreeNode< State > * parent) inline
Definition at line 166 of file ReachTreeNode.h.
References assert(), state, and tmp.
Member Function Documentation
template<typename State> void hypro::ReachTreeNode< State >::addRefinement (const RefinementSetting< State > & ref)
template<typename State> void hypro::ReachTreeNode< State >::addTimeStepToPath (const carl::Interval< tNumber > & timeStep) inline
Definition at line 238 of file ReachTreeNode.h.
References hypro::Path< Number, tNumber >::addTimeStep(), hypro::RefinementSetting< State >::operator==, rhs, s, string(), and transitions.
template<typename State> void hypro::ReachTreeNode< State >::addTransitionToPath (Transition< Number > * trans, const carl::Interval< tNumber > & enabledTime) inline
Definition at line 237 of file ReachTreeNode.h.
References hypro::Path< Number, tNumber >::addTransition().
template<typename State> void hypro::ReachTreeNode< State >::clearRefinements () inline
Definition at line 227 of file ReachTreeNode.h.
template<typename State> void hypro::ReachTreeNode< State >::convertRefinement (unsigned fromLevel, unsigned toLevel)
template<typename State> std::vector<ReachTreeNode<State>*> hypro::ReachTreeNode< State >::getChildrenForTransition (Transition< Number > * transition) const
Referenced by hypro::isTreeExtension().
template<typename State> std::size_t hypro::ReachTreeNode< State >::getDotRepresentation (std::size_t startIndex, std::string & nodes, std::string & transitions, std::vector< unsigned > & levels) const
template<typename State> unsigned hypro::ReachTreeNode< State >::getLatestBTLevel () const
template<typename State> unsigned hypro::ReachTreeNode< State >::getLatestFullyComputedLevel () const
template<typename State> void hypro::ReachTreeNode< State >::getLevelCnt (std::vector< std::size_t > & levels) const
template<typename State> std::mutex& hypro::ReachTreeNode< State >::getMutex () const inline
Definition at line 185 of file ReachTreeNode.h.
template<typename State> const Path<Number, tNumber>& hypro::ReachTreeNode< State >::getPath () const inline
Definition at line 187 of file ReachTreeNode.h.
template<typename State> const std::vector<RefinementSetting<State> >& hypro::ReachTreeNode< State >::getRefinements () const inline
Definition at line 204 of file ReachTreeNode.h.
Referenced by hypro::nodeUpdater< State >::createAndRaiseRefinementTask(), and hypro::nodeUpdater< State >::createAndRaiseTask().
template<typename State> const State::repVariant& hypro::ReachTreeNode< State >::getSetAtLevel (unsigned level) const
template<typename State> const State& hypro::ReachTreeNode< State >::getState () const inline
Definition at line 193 of file ReachTreeNode.h.
Referenced by hypro::Task< State >::getInitialStateSet().
template<typename State> const State& hypro::ReachTreeNode< State >::getStateAtLevel (unsigned level) const
template<typename State> const carl::Interval<tNumber>& hypro::ReachTreeNode< State >::getTimestamp (unsigned level) const
Gets the timestamp of entry (i.e. global timestamp) for a certain level.
Parameters
[in] level The level.
Returns
The timestamp.
template<typename State> bool hypro::ReachTreeNode< State >::hasFixedPoint (const State & s, typename ReachTreeNode< State >::Node_t skip) const
template<typename State> bool hypro::ReachTreeNode< State >::isFullyComputedOnSomeLevel () const
template<typename State> void hypro::ReachTreeNode< State >::refineIntervals ()
template<typename State> std::vector<RefinementSetting<State> >& hypro::ReachTreeNode< State >::rGetRefinements () inline
Definition at line 206 of file ReachTreeNode.h.
Referenced by hypro::nodeUpdater< State >::createAndRaiseRefinementTask(), and hypro::nodeUpdater< State >::createAndRaiseTask().
template<typename State> void hypro::ReachTreeNode< State >::setNewRefinement (unsigned level, const RefinementSetting< State > & ref)
Referenced by hypro::nodeUpdater< State >::createAndRaiseRefinementTask(), and hypro::nodeUpdater< State >::createAndRaiseTask().
template<typename State> void hypro::ReachTreeNode< State >::setParent (ReachTreeNode< State > * parent)
template<typename State> void hypro::ReachTreeNode< State >::setTimestamp (unsigned level, const carl::Interval< tNumber > & timeInterval)
Referenced by main().
template<typename State> void hypro::ReachTreeNode< State >::updateContent (ReachTreeNode< State > * updatedNode)
Referenced by hypro::nodeUpdater< State >::createAndRaiseRefinementTask().
Friends And Related Function Documentation
template<typename State> template<typename S > bool operator< (const ReachTreeNode< S > & lhs, const ReachTreeNode< S > & rhs) friend
template<typename State> template<typename S > std::ostream& operator<< (std::ostream & out, const ReachTreeNode< S > & reachTreeNode) friend
template<typename State> template<typename S > bool operator== (const ReachTreeNode< S > & lhs, const ReachTreeNode< S > & rhs) friend
Member Data Documentation
template<typename State> Path<Number, tNumber> hypro::ReachTreeNode< State >::mPath protected
Definition at line 115 of file ReachTreeNode.h.
template<typename State> std::vector<RefinementSetting<State> > hypro::ReachTreeNode< State >::mRefinements protected
path cache.
Definition at line 116 of file ReachTreeNode.h.
template<typename State> std::mutex hypro::ReachTreeNode< State >::mutex mutable protected
ordered list of applied refinements.
Definition at line 118 of file ReachTreeNode.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/ReachTreeNode.h