HyPro: hypro::timedGuardHandler< State > Class Template Reference
hypro::timedGuardHandler< State > Class Template Reference
#include <forwardDeclarations.h>
Public Member Functions
timedGuardHandler ()=delete
timedGuardHandler (std::shared_ptr< State > state, size_t index, Transition< Number > *transition)
void handle ()
const char * handlerName ()
virtual double getSortIndex () override
virtual void setSortIndex (double sortIndex) override
Public Member Functions inherited from hypro::ltiGuardHandler< State >
bool operator() (const State &stateSet)
const TransitionStatesMap & getGuardSatisfyingStateSets () const
Private Types
using Number = typename State::NumberType
Additional Inherited Members
Public Types inherited from hypro::ltiGuardHandler< State >
using TransitionStatesMap = std::map< Transition< Number > *, std::vector< State >>
Protected Attributes inherited from hypro::ltiGuardHandler< State >
TransitionStatesMap mGuardSatisfyingStates
Detailed Description
template<typename State>
class hypro::timedGuardHandler< State >
Definition at line 42 of file forwardDeclarations.h.
Member Typedef Documentation
template<typename State > using hypro::timedGuardHandler< State >::Number = typename State::NumberType private
Definition at line 8 of file timedGuardHandler.h.
Constructor & Destructor Documentation
template<typename State > hypro::timedGuardHandler< State >::timedGuardHandler () delete
template<typename State > hypro::timedGuardHandler< State >::timedGuardHandler (std::shared_ptr< State > state, size_t index, Transition< Number > * transition) inline
Definition at line 12 of file timedGuardHandler.h.
References hypro::Decomposition::at(), hypro::SettingsProvider< State >::getSubspaceDecomposition(), and hypro::timedGuardHandler< State >::handle().
Member Function Documentation
template<typename State > virtual double hypro::timedGuardHandler< State >::getSortIndex () inline override virtual
Definition at line 25 of file timedGuardHandler.h.
template<typename State > void hypro::timedGuardHandler< State >::handle ()
Referenced by hypro::timedGuardHandler< State >::timedGuardHandler().
template<typename State > const char* hypro::timedGuardHandler< State >::handlerName () inline
Definition at line 23 of file timedGuardHandler.h.
template<typename State > virtual void hypro::timedGuardHandler< State >::setSortIndex (double sortIndex) inline override virtual
Definition at line 26 of file timedGuardHandler.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/forwardDeclarations.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/guardHandlers/timedGuardHandler.h