HyPro: hypro::SettingsProvider< State > Class Template Reference
hypro::SettingsProvider< State > Class Template Reference
#include <SettingsProvider.h>
Public Member Functions
const HybridAutomaton< Number > & getHybridAutomaton ()
ReachabilitySettings & getReachabilitySettings ()
unsigned getWorkerThreadCount () const
void setWorkerThreadCount (std::size_t c)
void setSkipPlot (bool skip)
bool skipPlot () const
bool useGlobalQueuesOnly () const
bool useFixedPointTest () const
double getQueueBalancingRatio () const
bool useLocalTiming () const
bool useAnyTimingInformation () const
bool useDecider ()
void setUseDecider (bool useDecider)
bool decomposeAutomaton ()
void setDecomposeAutomaton (bool decompose)
std::size_t getNumberVariables () const
tNumber getGlobalTimeHorizon () const
void setHybridAutomaton (HybridAutomaton< Number > &&ha)
void setReachabilitySettings (const ReachabilitySettings &rs)
template<typename N = Number, typename T = tNumber, carl::DisableIf< std::is_same< N, T >> = carl::dummy>
void setReachabilitySettings (const ReachabilitySettings &rs)
template<typename Representation >
void addStrategyElement (tNumber timeStep, AGG_SETTING agg, int clustering)
void setStrategy (const Strategy< State > &strat)
const Strategy< State > & getStrategy () const
tNumber getLocalTimeHorizon () const
tNumber getTimeStepSize (std::size_t i=0) const
const LockedFileWriter & getDotFileWriter () const
bool isFullTimed ()
void setFullTimed (bool timed)
bool useContextSwitch ()
const Decomposition & getSubspaceDecomposition () const
void setSubspaceDecomposition (const Decomposition &decomp)
const std::map< const Location< Number > *, std::shared_ptr< std::vector< SUBSPACETYPE > > > & getLocationSubspaceTypeMap () const
void computeLocationSubspaceTypeMapping (const HybridAutomaton< Number > &ha)
std::map< const Location< Number > *, LOCATIONTYPE > getLocationTypeMap ()
void computeLocationTypeMapping (const HybridAutomaton< Number > &ha)
Private Types
using Number = typename State::NumberType
Private Member Functions
SettingsProvider ()
Private Attributes
HybridAutomaton< Number > mHybridAutomaton
ReachabilitySettings mReachabilitySettings
Strategy< State > mStrategy
bool mGlobalQueuesOnly = false
bool mSkipPlot = false
bool mUseLocalTiming = false
bool mUseFixedPointTest = true
bool mDoDecomposition = false
bool mUseDecider = false
int mThreadcount = 1
double mBalancingRatio = 1.0
LockedFileWriter treeDotFileWriter
Decomposition mSubspaceDecomposition
bool fullTimed = false
bool contextSwitch = false
std::map< const Location< Number > *, std::shared_ptr< std::vector< SUBSPACETYPE > > > mLocationSubspaceTypeMap
std::map< const Location< Number > *, LOCATIONTYPE > mLocationTypeMap
Detailed Description
template<typename State>
class hypro::SettingsProvider< State >
SettingsProvider is a Singleton class providing meta information about the reachability analysis process.
Definition at line 20 of file SettingsProvider.h.
Member Typedef Documentation
template<typename State> using hypro::SettingsProvider< State >::Number = typename State::NumberType private
Definition at line 21 of file SettingsProvider.h.
Constructor & Destructor Documentation
template<typename State> hypro::SettingsProvider< State >::SettingsProvider () inline private
Definition at line 23 of file SettingsProvider.h.
References c, hypro::SettingsProvider< State >::getHybridAutomaton(), hypro::SettingsProvider< State >::getReachabilitySettings(), hypro::SettingsProvider< State >::getWorkerThreadCount(), and hypro::SettingsProvider< State >::setWorkerThreadCount().
Member Function Documentation
template<typename State> template<typename Representation > void hypro::SettingsProvider< State >::addStrategyElement (tNumber timeStep, AGG_SETTING agg, int clustering)
Referenced by main(), and hypro::SettingsProvider< State >::setReachabilitySettings().
template<typename State> void hypro::SettingsProvider< State >::computeLocationSubspaceTypeMapping (const HybridAutomaton< Number > & ha)
Referenced by hypro::SettingsProvider< State >::getLocationSubspaceTypeMap().
template<typename State> void hypro::SettingsProvider< State >::computeLocationTypeMapping (const HybridAutomaton< Number > & ha)
Referenced by hypro::SettingsProvider< State >::getLocationTypeMap().
template<typename State> bool hypro::SettingsProvider< State >::decomposeAutomaton ()
Referenced by hypro::SettingsProvider< State >::setUseDecider().
template<typename State> const LockedFileWriter& hypro::SettingsProvider< State >::getDotFileWriter () const inline
Definition at line 77 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::treeDotFileWriter.
template<typename State> tNumber hypro::SettingsProvider< State >::getGlobalTimeHorizon () const inline
Definition at line 45 of file SettingsProvider.h.
References hypro::ReachabilitySettings::jumpDepth, hypro::SettingsProvider< State >::mReachabilitySettings, hypro::SettingsProvider< State >::setHybridAutomaton(), hypro::SettingsProvider< State >::setReachabilitySettings(), and hypro::ReachabilitySettings::timeBound.
template<typename State> const HybridAutomaton<Number>& hypro::SettingsProvider< State >::getHybridAutomaton ()
Referenced by main(), and hypro::SettingsProvider< State >::SettingsProvider().
template<typename State> tNumber hypro::SettingsProvider< State >::getLocalTimeHorizon () const inline
Definition at line 74 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::mReachabilitySettings, and hypro::ReachabilitySettings::timeBound.
template<typename State> const std::map<const Location<Number>*, std::shared_ptr<std::vector<SUBSPACETYPE> > >& hypro::SettingsProvider< State >::getLocationSubspaceTypeMap () const inline
Definition at line 88 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::computeLocationSubspaceTypeMapping(), and hypro::SettingsProvider< State >::mLocationSubspaceTypeMap.
template<typename State> std::map<const Location<Number>*, LOCATIONTYPE> hypro::SettingsProvider< State >::getLocationTypeMap () inline
Definition at line 91 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::computeLocationTypeMapping(), and hypro::SettingsProvider< State >::mLocationTypeMap.
template<typename State> std::size_t hypro::SettingsProvider< State >::getNumberVariables () const inline
Definition at line 44 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::mHybridAutomaton.
template<typename State> double hypro::SettingsProvider< State >::getQueueBalancingRatio () const
Referenced by hypro::SettingsProvider< State >::useFixedPointTest().
template<typename State> ReachabilitySettings& hypro::SettingsProvider< State >::getReachabilitySettings ()
Referenced by hypro::SettingsProvider< State >::SettingsProvider().
template<typename State> const Strategy<State>& hypro::SettingsProvider< State >::getStrategy () const inline
Definition at line 72 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::mStrategy.
Referenced by hypro::nodeUpdater< State >::createAndRaiseRefinementTask(), hypro::nodeUpdater< State >::createAndRaiseTask(), hypro::insertAndCreateTask(), and main().
template<typename State> const Decomposition& hypro::SettingsProvider< State >::getSubspaceDecomposition () const inline
Definition at line 85 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::mSubspaceDecomposition.
Referenced by hypro::rectangularGuardHandler< State >::rectangularGuardHandler(), and hypro::timedGuardHandler< State >::timedGuardHandler().
template<typename State> tNumber hypro::SettingsProvider< State >::getTimeStepSize (std::size_t i = 0) const inline
Definition at line 75 of file SettingsProvider.h.
References i, and hypro::SettingsProvider< State >::mStrategy.
template<typename State> unsigned hypro::SettingsProvider< State >::getWorkerThreadCount () const
Referenced by hypro::SettingsProvider< State >::SettingsProvider().
template<typename State> bool hypro::SettingsProvider< State >::isFullTimed () inline
Definition at line 79 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::fullTimed.
template<typename State> void hypro::SettingsProvider< State >::setDecomposeAutomaton (bool decompose) inline
Definition at line 43 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::mDoDecomposition.
template<typename State> void hypro::SettingsProvider< State >::setFullTimed (bool timed) inline
Definition at line 80 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::fullTimed, and hypro::timed.
template<typename State> void hypro::SettingsProvider< State >::setHybridAutomaton (HybridAutomaton< Number > && ha)
Referenced by hypro::SettingsProvider< State >::getGlobalTimeHorizon(), and main().
template<typename State> void hypro::SettingsProvider< State >::setReachabilitySettings (const ReachabilitySettings & rs)
Referenced by hypro::SettingsProvider< State >::getGlobalTimeHorizon(), and main().
template<typename State> template<typename N = Number, typename T = tNumber, carl::DisableIf< std::is_same< N, T >> = carl::dummy> void hypro::SettingsProvider< State >::setReachabilitySettings (const ReachabilitySettings & rs) inline
Definition at line 53 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::addStrategyElement(), hypro::clustering, hypro::ReachabilitySettings::clustering, hypro::ReachabilitySettings::fileName, hypro::ReachabilitySettings::jumpDepth, hypro::SettingsProvider< State >::mReachabilitySettings, hypro::ReachabilitySettings::plotDimensions, hypro::ReachabilitySettings::pplDenomimator, hypro::ReachabilitySettings::timeBound, hypro::ReachabilitySettings::timeStep, timeStep, hypro::ReachabilitySettings::uniformBloating, hypro::ReachabilitySettings::useBadStateTimingInformation, hypro::ReachabilitySettings::useGuardTimingInformation, and hypro::ReachabilitySettings::useInvariantTimingInformation.
template<typename State> void hypro::SettingsProvider< State >::setSkipPlot (bool skip) inline
Definition at line 33 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::mSkipPlot, hypro::SettingsProvider< State >::skipPlot(), and hypro::SettingsProvider< State >::useGlobalQueuesOnly().
template<typename State> void hypro::SettingsProvider< State >::setStrategy (const Strategy< State > & strat) inline
Definition at line 71 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::mStrategy.
template<typename State> void hypro::SettingsProvider< State >::setSubspaceDecomposition (const Decomposition & decomp) inline
Definition at line 86 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::mSubspaceDecomposition.
template<typename State> void hypro::SettingsProvider< State >::setUseDecider (bool useDecider) inline
Definition at line 41 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::decomposeAutomaton(), hypro::SettingsProvider< State >::mUseDecider, and hypro::SettingsProvider< State >::useDecider().
template<typename State> void hypro::SettingsProvider< State >::setWorkerThreadCount (std::size_t c)
Referenced by hypro::SettingsProvider< State >::SettingsProvider().
template<typename State> bool hypro::SettingsProvider< State >::skipPlot () const
Referenced by hypro::SettingsProvider< State >::setSkipPlot().
template<typename State> bool hypro::SettingsProvider< State >::useAnyTimingInformation () const inline
Definition at line 39 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::mReachabilitySettings, hypro::ReachabilitySettings::useBadStateTimingInformation, hypro::SettingsProvider< State >::useDecider(), hypro::ReachabilitySettings::useGuardTimingInformation, and hypro::ReachabilitySettings::useInvariantTimingInformation.
template<typename State> bool hypro::SettingsProvider< State >::useContextSwitch () inline
Definition at line 83 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::contextSwitch.
template<typename State> bool hypro::SettingsProvider< State >::useDecider ()
Referenced by hypro::SettingsProvider< State >::setUseDecider(), and hypro::SettingsProvider< State >::useAnyTimingInformation().
template<typename State> bool hypro::SettingsProvider< State >::useFixedPointTest () const inline
Definition at line 36 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::getQueueBalancingRatio(), and hypro::SettingsProvider< State >::mUseFixedPointTest.
template<typename State> bool hypro::SettingsProvider< State >::useGlobalQueuesOnly () const
Referenced by hypro::SettingsProvider< State >::setSkipPlot().
template<typename State> bool hypro::SettingsProvider< State >::useLocalTiming () const inline
Definition at line 38 of file SettingsProvider.h.
References hypro::SettingsProvider< State >::mUseLocalTiming.
Referenced by hypro::nodeUpdater< State >::createAndRaiseTask().
Member Data Documentation
template<typename State> bool hypro::SettingsProvider< State >::contextSwitch = false private
Definition at line 112 of file SettingsProvider.h.
Referenced by hypro::SettingsProvider< State >::useContextSwitch().
template<typename State> bool hypro::SettingsProvider< State >::fullTimed = false private
Definition at line 109 of file SettingsProvider.h.
Referenced by hypro::SettingsProvider< State >::isFullTimed(), and hypro::SettingsProvider< State >::setFullTimed().
template<typename State> double hypro::SettingsProvider< State >::mBalancingRatio = 1.0 private
Definition at line 105 of file SettingsProvider.h.
template<typename State> bool hypro::SettingsProvider< State >::mDoDecomposition = false private
Definition at line 102 of file SettingsProvider.h.
Referenced by hypro::SettingsProvider< State >::setDecomposeAutomaton().
template<typename State> bool hypro::SettingsProvider< State >::mGlobalQueuesOnly = false private
Definition at line 98 of file SettingsProvider.h.
template<typename State> HybridAutomaton<Number> hypro::SettingsProvider< State >::mHybridAutomaton private
Definition at line 95 of file SettingsProvider.h.
Referenced by hypro::SettingsProvider< State >::getNumberVariables().
template<typename State> std::map<const Location<Number>*, std::shared_ptr<std::vector<SUBSPACETYPE> > > hypro::SettingsProvider< State >::mLocationSubspaceTypeMap private
Definition at line 115 of file SettingsProvider.h.
Referenced by hypro::SettingsProvider< State >::getLocationSubspaceTypeMap().
template<typename State> std::map<const Location<Number>*, LOCATIONTYPE> hypro::SettingsProvider< State >::mLocationTypeMap private
Definition at line 116 of file SettingsProvider.h.
Referenced by hypro::SettingsProvider< State >::getLocationTypeMap().
template<typename State> ReachabilitySettings hypro::SettingsProvider< State >::mReachabilitySettings private
Definition at line 96 of file SettingsProvider.h.
Referenced by hypro::SettingsProvider< State >::getGlobalTimeHorizon(), hypro::SettingsProvider< State >::getLocalTimeHorizon(), hypro::SettingsProvider< State >::setReachabilitySettings(), and hypro::SettingsProvider< State >::useAnyTimingInformation().
template<typename State> bool hypro::SettingsProvider< State >::mSkipPlot = false private
Definition at line 99 of file SettingsProvider.h.
Referenced by hypro::SettingsProvider< State >::setSkipPlot().
template<typename State> Strategy<State> hypro::SettingsProvider< State >::mStrategy private
Definition at line 97 of file SettingsProvider.h.
Referenced by hypro::SettingsProvider< State >::getStrategy(), hypro::SettingsProvider< State >::getTimeStepSize(), and hypro::SettingsProvider< State >::setStrategy().
template<typename State> Decomposition hypro::SettingsProvider< State >::mSubspaceDecomposition private
Definition at line 107 of file SettingsProvider.h.
Referenced by hypro::SettingsProvider< State >::getSubspaceDecomposition(), and hypro::SettingsProvider< State >::setSubspaceDecomposition().
template<typename State> int hypro::SettingsProvider< State >::mThreadcount = 1 private
Definition at line 104 of file SettingsProvider.h.
template<typename State> bool hypro::SettingsProvider< State >::mUseDecider = false private
Definition at line 103 of file SettingsProvider.h.
Referenced by hypro::SettingsProvider< State >::setUseDecider().
template<typename State> bool hypro::SettingsProvider< State >::mUseFixedPointTest = true private
Definition at line 101 of file SettingsProvider.h.
Referenced by hypro::SettingsProvider< State >::useFixedPointTest().
template<typename State> bool hypro::SettingsProvider< State >::mUseLocalTiming = false private
Definition at line 100 of file SettingsProvider.h.
Referenced by hypro::SettingsProvider< State >::useLocalTiming().
template<typename State> LockedFileWriter hypro::SettingsProvider< State >::treeDotFileWriter private
Definition at line 106 of file SettingsProvider.h.
Referenced by hypro::SettingsProvider< State >::getDotFileWriter().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/SettingsProvider.h