HyPro: hypro::BoxSupportFunction< Number, Setting > Class Template Reference
hypro::BoxSupportFunction< Number, Setting > Class Template Reference
Public Member Functions
BoxSupportFunction (const std::vector< carl::Interval< Number >> &intervals)
BoxSupportFunction (const std::vector< Point< Number >> &_points)
BoxSupportFunction (const BoxSupportFunction< Number, Setting > &_origin)
~BoxSupportFunction ()
BoxSupportFunction< Number, Setting > & operator= (const BoxSupportFunction< Number, Setting > &_orig)
std::size_t dimension () const
SF_TYPE type () const
matrix_t< Number > constraints () const
vector_t< Number > constants () const
std::vector< Point< Number > > vertices () const
Point< Number > supremumPoint () const
EvaluationResult< Number > evaluate (const vector_t< Number > &l, bool useExact) const
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &_A, bool useExact, bool setTemplate=false) const
Evaluates the support function in the directions given in the passed matrix.
bool contains (const Point< Number > &_point) const
Check if point is contained in the support function.
bool contains (const vector_t< Number > &_point) const
Check if point is contained in the support function.
bool empty () const
const std::vector< carl::Interval< Number > > & getIntervals () const
std::string getDotRepresentation () const
Friends
std::ostream & operator<< (std::ostream &lhs, const BoxSupportFunction< Number, Setting > &rhs)
Detailed Description
template<typename Number, typename Setting>
class hypro::BoxSupportFunction< Number, Setting >
Definition at line 24 of file BoxSupportFunction.h.
Constructor & Destructor Documentation
template<typename Number , typename Setting > hypro::BoxSupportFunction< Number, Setting >::BoxSupportFunction (const std::vector< carl::Interval< Number >> & intervals)
Definition at line 12 of file BoxSupportFunction.tpp.
template<typename Number , typename Setting > hypro::BoxSupportFunction< Number, Setting >::BoxSupportFunction (const std::vector< Point< Number >> & _points)
Definition at line 18 of file BoxSupportFunction.tpp.
template<typename Number , typename Setting > hypro::BoxSupportFunction< Number, Setting >::BoxSupportFunction (const BoxSupportFunction< Number, Setting > & _origin)
Definition at line 34 of file BoxSupportFunction.tpp.
template<typename Number , typename Setting > hypro::BoxSupportFunction< Number, Setting >::~BoxSupportFunction ()
Definition at line 40 of file BoxSupportFunction.tpp.
Member Function Documentation
template<typename Number , typename Setting > vector_t< Number > hypro::BoxSupportFunction< Number, Setting >::constants () const
Definition at line 73 of file BoxSupportFunction.tpp.
template<typename Number , typename Setting > matrix_t< Number > hypro::BoxSupportFunction< Number, Setting >::constraints () const
Definition at line 61 of file BoxSupportFunction.tpp.
template<typename Number , typename Setting > bool hypro::BoxSupportFunction< Number, Setting >::contains (const Point< Number > & _point) const
Check if point is contained in the support function.
To check if the given point is contained in the support function we evaluate it in all its directions (uses multiEvaluate).
Parameters
_point The point to check.
Returns
True, if the point is inside the support function.
Definition at line 170 of file BoxSupportFunction.tpp.
References hypro::BoxSupportFunction< Number, Setting >::dimension(), and hypro::Point< Number >::dimension().
Referenced by hypro::BoxSupportFunction< Number, Setting >::contains().
template<typename Number , typename Setting > bool hypro::BoxSupportFunction< Number, Setting >::contains (const vector_t< Number > & _point) const
Check if point is contained in the support function.
To check if the given point is contained in the support function we evaluate it in all its directions (uses multiEvaluate).
Parameters
_point The point to check.
Returns
True, if the point is inside the support function.
Definition at line 181 of file BoxSupportFunction.tpp.
References hypro::BoxSupportFunction< Number, Setting >::contains(), and hypro::BoxSupportFunction< Number, Setting >::dimension().
template<typename Number , typename Setting > std::size_t hypro::BoxSupportFunction< Number, Setting >::dimension () const
Returns the dimension of the object.
Returns
Definition at line 51 of file BoxSupportFunction.tpp.
Referenced by hypro::BoxSupportFunction< Number, Setting >::contains(), hypro::BoxSupportFunction< Number, Setting >::empty(), hypro::BoxSupportFunction< Number, Setting >::evaluate(), hypro::BoxSupportFunction< Number, Setting >::multiEvaluate(), and hypro::BoxSupportFunction< Number, Setting >::vertices().
template<typename Number , typename Setting > bool hypro::BoxSupportFunction< Number, Setting >::empty () const
Definition at line 192 of file BoxSupportFunction.tpp.
References hypro::BoxSupportFunction< Number, Setting >::dimension().
Referenced by hypro::BoxSupportFunction< Number, Setting >::evaluate(), and hypro::BoxSupportFunction< Number, Setting >::supremumPoint().
template<typename Number , typename Setting > EvaluationResult< Number > hypro::BoxSupportFunction< Number, Setting >::evaluate (const vector_t< Number > & l, bool useExact) const
Evaluates the support function in the given direction.
Parameters
l
Returns
Definition at line 128 of file BoxSupportFunction.tpp.
References hypro::BoxSupportFunction< Number, Setting >::dimension(), hypro::BoxSupportFunction< Number, Setting >::empty(), hypro::FEAS, and hypro::INFTY.
Referenced by hypro::BoxSupportFunction< Number, Setting >::multiEvaluate().
template<typename Number , typename Setting > std::string hypro::BoxSupportFunction< Number, Setting >::getDotRepresentation () const
Definition at line 205 of file BoxSupportFunction.tpp.
Referenced by hypro::BoxSupportFunction< Number, Setting >::getIntervals().
template<typename Number, typename Setting> const std::vector<carl::Interval<Number> >& hypro::BoxSupportFunction< Number, Setting >::getIntervals () const inline
Definition at line 89 of file BoxSupportFunction.h.
References hypro::BoxSupportFunction< Number, Setting >::getDotRepresentation().
template<typename Number , typename Setting > std::vector< EvaluationResult< Number > > hypro::BoxSupportFunction< Number, Setting >::multiEvaluate (const matrix_t< Number > & _A, bool useExact, bool setTemplate = false) const
Evaluates the support function in the directions given in the passed matrix.
Uses the standard evaluate method for multiple directions.
Parameters
_A Matrix holding the directions in which to evaluate.
Returns
Vector of support values.
Definition at line 158 of file BoxSupportFunction.tpp.
References hypro::BoxSupportFunction< Number, Setting >::dimension(), and hypro::BoxSupportFunction< Number, Setting >::evaluate().
template<typename Number , typename Setting > BoxSupportFunction< Number, Setting > & hypro::BoxSupportFunction< Number, Setting >::operator= (const BoxSupportFunction< Number, Setting > & _orig)
Definition at line 45 of file BoxSupportFunction.tpp.
template<typename Number , typename Setting > Point< Number > hypro::BoxSupportFunction< Number, Setting >::supremumPoint () const
Definition at line 118 of file BoxSupportFunction.tpp.
References hypro::BoxSupportFunction< Number, Setting >::empty().
template<typename Number , typename Setting > SF_TYPE hypro::BoxSupportFunction< Number, Setting >::type () const
Definition at line 56 of file BoxSupportFunction.tpp.
References hypro::BOX.
template<typename Number , typename Setting > std::vector< Point< Number > > hypro::BoxSupportFunction< Number, Setting >::vertices () const
Definition at line 85 of file BoxSupportFunction.tpp.
References hypro::BoxSupportFunction< Number, Setting >::dimension().
Friends And Related Function Documentation
template<typename Number, typename Setting> std::ostream& operator<< (std::ostream & lhs, const BoxSupportFunction< Number, Setting > & rhs) friend
Definition at line 93 of file BoxSupportFunction.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunction/BoxSupportFunction.h
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunction/BoxSupportFunction.tpp