HyPro: hypro::TaylorModelVec< Number > Class Template Reference
hypro::TaylorModelVec< Number > Class Template Reference
Public Types
using assignment_type = std::pair< const carl::Variable, TaylorModel< Number >>
Public Member Functions
TaylorModelVec ()
TaylorModelVec (const std::map< carl::Variable, TaylorModel< Number >> &assignments)
TaylorModelVec (Range< Number > &range)
TaylorModelVec (const TaylorModelVec &tmv)
~TaylorModelVec ()
void assign (const carl::Variable &v, const TaylorModel< Number > &tm)
bool find_assignment (TaylorModel< Number > &tm, const carl::Variable &v) const
bool isEmpty () const
void clear ()
void rmConstantTerm (Range< Number > &constant)
void cutoff (const carl::Interval< Number > &threshold, Domain< Number > &domain)
void cutoff_nr (const carl::Interval< Number > &threshold, Domain< Number > &domain)
void truncation (const exponent order, Domain< Number > &domain)
void truncation_nr (const exponent order)
void enclosure (Range< Number > &range, Domain< Number > &domain) const
TaylorModelVec< Number > & operator= (const TaylorModelVec< Number > &tmv)
TaylorModelVec< Number > & operator+= (const TaylorModelVec< Number > &tmv)
TaylorModelVec< Number > & operator-= (const TaylorModelVec< Number > &tmv)
const TaylorModelVec< Number > operator+ (const TaylorModelVec< Number > &tmv) const
const TaylorModelVec< Number > operator- (const TaylorModelVec< Number > &tmv) const
TaylorModelVec< Number > substitute (const std::map< carl::Variable, TaylorModel< Number >> &substitutions, Domain< Number > &domain, const exponent order) const
TaylorModelVec< Number > substitute (const TaylorModelVec< Number > &substitutions, Domain< Number > &domain, const exponent order) const
TaylorModelVec< Number > derivative (carl::Variable::Arg v, unsigned nth=1) const
void derivative_assign (carl::Variable::Arg v, unsigned nth=1)
TaylorModelVec< Number > LieDerivative (const PolynomialODE< Number > &ode) const
void LieDerivative_assign (const PolynomialODE< Number > &ode)
TaylorModelVec< Number > integration (carl::Variable::Arg v, const carl::Interval< Number > &range_of_v)
void integration_assign (carl::Variable::Arg v, const carl::Interval< Number > &range_of_v)
TaylorModelVec< Number > Picard (const TaylorModelVec< Number > &x0, const PolynomialODE< Number > &ode, Domain< Number > &domain, carl::Variable::Arg t, const carl::Interval< Number > &range_of_t, const exponent order) const
void Picard_assign (const TaylorModelVec< Number > &x0, const PolynomialODE< Number > &ode, Domain< Number > &domain, carl::Variable::Arg t, const carl::Interval< Number > &range_of_t, const exponent order)
Public Attributes
std::map< carl::Variable, TaylorModel< Number > > tms
Friends
class TaylorModel< Number >
class Flowpipe< Number >
template<typename N >
std::ostream & operator<< (std::ostream &os, const TaylorModelVec< N > &tmv)
Detailed Description
template<typename Number>
class hypro::TaylorModelVec< Number >
Definition at line 44 of file TaylorModel.h.
Member Typedef Documentation
template<typename Number> using hypro::TaylorModelVec< Number >::assignment_type = std::pair<const carl::Variable, TaylorModel<Number>>
Definition at line 195 of file TaylorModel.h.
Constructor & Destructor Documentation
template<typename Number > hypro::TaylorModelVec< Number >::TaylorModelVec ()
Definition at line 959 of file TaylorModel.tpp.
template<typename Number > hypro::TaylorModelVec< Number >::TaylorModelVec (const std::map< carl::Variable, TaylorModel< Number >> & assignments)
Definition at line 963 of file TaylorModel.tpp.
template<typename Number > hypro::TaylorModelVec< Number >::TaylorModelVec (Range< Number > & range)
Definition at line 968 of file TaylorModel.tpp.
References hypro::Range< Number >::get_assignments().
template<typename Number > hypro::TaylorModelVec< Number >::TaylorModelVec (const TaylorModelVec< Number > & tmv)
Definition at line 981 of file TaylorModel.tpp.
References hypro::TaylorModelVec< Number >::tms.
template<typename Number > hypro::TaylorModelVec< Number >::~TaylorModelVec ()
Definition at line 986 of file TaylorModel.tpp.
Member Function Documentation
template<typename Number > void hypro::TaylorModelVec< Number >::assign (const carl::Variable & v, const TaylorModel< Number > & tm)
Definition at line 990 of file TaylorModel.tpp.
Referenced by hypro::TaylorModelVec< Number >::derivative(), hypro::TaylorModelVec< Number >::integration(), hypro::TaylorModelVec< Number >::LieDerivative(), hypro::Flowpipe< State >::next_picard(), hypro::TaylorModelVec< Number >::Picard(), hypro::TaylorModelVec< Number >::Picard_assign(), and hypro::TaylorModelVec< Number >::substitute().
template<typename Number > void hypro::TaylorModelVec< Number >::clear ()
Definition at line 1024 of file TaylorModel.tpp.
template<typename Number > void hypro::TaylorModelVec< Number >::cutoff (const carl::Interval< Number > & threshold, Domain< Number > & domain)
Definition at line 1042 of file TaylorModel.tpp.
template<typename Number > void hypro::TaylorModelVec< Number >::cutoff_nr (const carl::Interval< Number > & threshold, Domain< Number > & domain)
Definition at line 1049 of file TaylorModel.tpp.
template<typename Number > TaylorModelVec< Number > hypro::TaylorModelVec< Number >::derivative (carl::Variable::Arg v, unsigned nth = 1) const
Definition at line 1223 of file TaylorModel.tpp.
References hypro::TaylorModelVec< Number >::assign(), and hypro::TaylorModel< Number >::derivative().
template<typename Number > void hypro::TaylorModelVec< Number >::derivative_assign (carl::Variable::Arg v, unsigned nth = 1)
Definition at line 1238 of file TaylorModel.tpp.
template<typename Number > void hypro::TaylorModelVec< Number >::enclosure (Range< Number > & range, Domain< Number > & domain) const
Definition at line 1070 of file TaylorModel.tpp.
References hypro::Range< Number >::assign(), and hypro::Range< Number >::clear().
Referenced by hypro::Flowpipe< State >::enclosure(), and hypro::Flowpipe< State >::next_picard().
template<typename Number > bool hypro::TaylorModelVec< Number >::find_assignment (TaylorModel< Number > & tm, const carl::Variable & v) const
Definition at line 1003 of file TaylorModel.tpp.
template<typename Number > TaylorModelVec< Number > hypro::TaylorModelVec< Number >::integration (carl::Variable::Arg v, const carl::Interval< Number > & range_of_v)
Definition at line 1267 of file TaylorModel.tpp.
References hypro::TaylorModelVec< Number >::assign(), and hypro::TaylorModel< Number >::integration().
template<typename Number > void hypro::TaylorModelVec< Number >::integration_assign (carl::Variable::Arg v, const carl::Interval< Number > & range_of_v)
Definition at line 1282 of file TaylorModel.tpp.
Referenced by hypro::TaylorModelVec< Number >::Picard(), and hypro::TaylorModelVec< Number >::Picard_assign().
template<typename Number > bool hypro::TaylorModelVec< Number >::isEmpty () const
Definition at line 1015 of file TaylorModel.tpp.
template<typename Number > TaylorModelVec< Number > hypro::TaylorModelVec< Number >::LieDerivative (const PolynomialODE< Number > & ode) const
Definition at line 1245 of file TaylorModel.tpp.
References hypro::TaylorModelVec< Number >::assign(), and hypro::TaylorModel< Number >::LieDerivative().
template<typename Number > void hypro::TaylorModelVec< Number >::LieDerivative_assign (const PolynomialODE< Number > & ode)
Definition at line 1260 of file TaylorModel.tpp.
template<typename Number > const TaylorModelVec< Number > hypro::TaylorModelVec< Number >::operator+ (const TaylorModelVec< Number > & tmv) const
Definition at line 1143 of file TaylorModel.tpp.
References hypro::TaylorModelVec< Number >::tms.
template<typename Number > TaylorModelVec< Number > & hypro::TaylorModelVec< Number >::operator+= (const TaylorModelVec< Number > & tmv)
Definition at line 1091 of file TaylorModel.tpp.
References hypro::TaylorModelVec< Number >::tms.
template<typename Number > const TaylorModelVec< Number > hypro::TaylorModelVec< Number >::operator- (const TaylorModelVec< Number > & tmv) const
Definition at line 1167 of file TaylorModel.tpp.
References hypro::TaylorModelVec< Number >::tms.
template<typename Number > TaylorModelVec< Number > & hypro::TaylorModelVec< Number >::operator-= (const TaylorModelVec< Number > & tmv)
Definition at line 1117 of file TaylorModel.tpp.
References hypro::TaylorModelVec< Number >::tms.
template<typename Number > TaylorModelVec< Number > & hypro::TaylorModelVec< Number >::operator= (const TaylorModelVec< Number > & tmv)
Definition at line 1082 of file TaylorModel.tpp.
References hypro::TaylorModelVec< Number >::tms.
template<typename Number > TaylorModelVec< Number > hypro::TaylorModelVec< Number >::Picard (const TaylorModelVec< Number > & x0, const PolynomialODE< Number > & ode, Domain< Number > & domain, carl::Variable::Arg t, const carl::Interval< Number > & range_of_t, const exponent order) const
Definition at line 1289 of file TaylorModel.tpp.
References hypro::TaylorModelVec< Number >::assign(), hypro::PolynomialODE< Number >::assignments, hypro::TaylorModelVec< Number >::integration_assign(), hypro::TaylorModel< Number >::substitute(), and hypro::TaylorModelVec< Number >::truncation().
Referenced by hypro::Flowpipe< State >::next_picard().
template<typename Number > void hypro::TaylorModelVec< Number >::Picard_assign (const TaylorModelVec< Number > & x0, const PolynomialODE< Number > & ode, Domain< Number > & domain, carl::Variable::Arg t, const carl::Interval< Number > & range_of_t, const exponent order)
Definition at line 1312 of file TaylorModel.tpp.
References hypro::TaylorModelVec< Number >::assign(), hypro::PolynomialODE< Number >::assignments, hypro::TaylorModelVec< Number >::integration_assign(), hypro::TaylorModel< Number >::substitute(), and hypro::TaylorModelVec< Number >::truncation().
Referenced by hypro::Flowpipe< State >::next_picard().
template<typename Number > void hypro::TaylorModelVec< Number >::rmConstantTerm (Range< Number > & constant)
Definition at line 1029 of file TaylorModel.tpp.
References hypro::Range< Number >::assign(), and hypro::Range< Number >::clear().
Referenced by hypro::Flowpipe< State >::next_picard().
template<typename Number > TaylorModelVec< Number > hypro::TaylorModelVec< Number >::substitute (const std::map< carl::Variable, TaylorModel< Number >> & substitutions, Domain< Number > & domain, const exponent order) const
Definition at line 1191 of file TaylorModel.tpp.
References hypro::TaylorModelVec< Number >::assign(), and hypro::TaylorModel< Number >::substitute().
Referenced by hypro::Flowpipe< State >::composition(), hypro::Flowpipe< State >::enclosure(), and hypro::Flowpipe< State >::next_picard().
template<typename Number > TaylorModelVec< Number > hypro::TaylorModelVec< Number >::substitute (const TaylorModelVec< Number > & substitutions, Domain< Number > & domain, const exponent order) const
Definition at line 1207 of file TaylorModel.tpp.
References hypro::TaylorModelVec< Number >::assign(), and hypro::TaylorModel< Number >::substitute().
template<typename Number > void hypro::TaylorModelVec< Number >::truncation (const exponent order, Domain< Number > & domain)
Definition at line 1056 of file TaylorModel.tpp.
Referenced by hypro::TaylorModelVec< Number >::Picard(), and hypro::TaylorModelVec< Number >::Picard_assign().
template<typename Number > void hypro::TaylorModelVec< Number >::truncation_nr (const exponent order)
Definition at line 1063 of file TaylorModel.tpp.
Friends And Related Function Documentation
template<typename Number> friend class Flowpipe< Number > friend
Definition at line 251 of file TaylorModel.h.
template<typename Number> template<typename N > std::ostream& operator<< (std::ostream & os, const TaylorModelVec< N > & tmv) friend
Definition at line 1334 of file TaylorModel.tpp.
template<typename Number> friend class TaylorModel< Number > friend
Definition at line 250 of file TaylorModel.h.
Member Data Documentation
template<typename Number> std::map<carl::Variable, TaylorModel<Number> > hypro::TaylorModelVec< Number >::tms
Definition at line 194 of file TaylorModel.h.
Referenced by hypro::Flowpipe< State >::next_picard(), hypro::TaylorModelVec< Number >::operator+(), hypro::TaylorModelVec< Number >::operator+=(), hypro::TaylorModelVec< Number >::operator-(), hypro::TaylorModelVec< Number >::operator-=(), hypro::TaylorModelVec< Number >::operator=(), hypro::TaylorModel< Number >::substitute(), and hypro::TaylorModelVec< Number >::TaylorModelVec().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/TaylorModel/TaylorModel.h
/home/travis/build/hypro/hypro/src/hypro/representations/TaylorModel/TaylorModel.tpp