HyPro: hypro::Range< Number > Struct Template Reference
hypro::Range< Number > Struct Template Reference
Public Member Functions
Range ()
Range (const Range< Number > &range)
~Range ()
void assign (const carl::Variable &v, const carl::Interval< Number > &I)
bool find_assignment (carl::Interval< Number > &I, const carl::Variable &v) const
void clear ()
std::map< carl::Variable, carl::Interval< Number > > & get_assignments ()
Range< Number > & operator= (const Range< Number > &range)
Range (typename T::const_iterator b, typename T::const_iterator e)
bool isEmpty () const
operator T () const
Public Attributes
T::const_iterator begin = nullptr
T::const_iterator end = nullptr
Protected Types
using assignment_type = std::pair< const carl::Variable, carl::Interval< Number >>
Protected Attributes
std::map< carl::Variable, carl::Interval< Number > > assignments
Friends
template<typename N >
std::ostream & operator<< (std::ostream &os, const Range< N > &range)
Detailed Description
template<typename Number>
struct hypro::Range< Number >
Definition at line 163 of file TaylorModel.h.
Member Typedef Documentation
template<typename Number> using hypro::Range< Number >::assignment_type = std::pair<const carl::Variable, carl::Interval<Number>> protected
Definition at line 166 of file TaylorModel.h.
Constructor & Destructor Documentation
template<typename Number > hypro::Range< Number >::Range ()
Definition at line 892 of file TaylorModel.tpp.
template<typename Number > hypro::Range< Number >::Range (const Range< Number > & range)
Definition at line 901 of file TaylorModel.tpp.
References hypro::Range< Number >::assignments.
template<typename Number > hypro::Range< Number >::~Range ()
Definition at line 896 of file TaylorModel.tpp.
template<typename Number> hypro::Range< Number >::Range (typename T::const_iterator b, typename T::const_iterator e) inline
Definition at line 9 of file Range.h.
Member Function Documentation
template<typename Number > void hypro::Range< Number >::assign (const carl::Variable & v, const carl::Interval< Number > & I)
Definition at line 906 of file TaylorModel.tpp.
Referenced by hypro::TaylorModelVec< Number >::enclosure(), and hypro::TaylorModelVec< Number >::rmConstantTerm().
template<typename Number > void hypro::Range< Number >::clear ()
Definition at line 937 of file TaylorModel.tpp.
Referenced by hypro::TaylorModelVec< Number >::enclosure(), and hypro::TaylorModelVec< Number >::rmConstantTerm().
template<typename Number > bool hypro::Range< Number >::find_assignment (carl::Interval< Number > & I, const carl::Variable & v) const
Definition at line 920 of file TaylorModel.tpp.
Referenced by hypro::Flowpipe< State >::next_picard(), and hypro::output_2D_interval_gnuplot().
template<typename Number > std::map< carl::Variable, carl::Interval< Number > > & hypro::Range< Number >::get_assignments ()
Definition at line 932 of file TaylorModel.tpp.
Referenced by hypro::Flowpipe< State >::next_picard(), and hypro::TaylorModelVec< Number >::TaylorModelVec().
template<typename Number> bool hypro::Range< Number >::isEmpty () const inline
Definition at line 13 of file Range.h.
References hypro::Range< Number >::end.
template<typename Number> hypro::Range< Number >::operator T () const inline explicit
Definition at line 17 of file Range.h.
template<typename Number > Range< Number > & hypro::Range< Number >::operator= (const Range< Number > & range)
Definition at line 942 of file TaylorModel.tpp.
References hypro::Range< Number >::assignments.
Friends And Related Function Documentation
template<typename Number> template<typename N > std::ostream& operator<< (std::ostream & os, const Range< N > & range) friend
Definition at line 950 of file TaylorModel.tpp.
Member Data Documentation
template<typename Number> std::map<carl::Variable, carl::Interval<Number> > hypro::Range< Number >::assignments protected
Definition at line 165 of file TaylorModel.h.
Referenced by hypro::Range< Number >::operator=(), and hypro::Range< Number >::Range().
template<typename Number> T::const_iterator hypro::Range< Number >::begin = nullptr
Definition at line 6 of file Range.h.
template<typename Number> T::const_iterator hypro::Range< Number >::end = nullptr
Definition at line 7 of file Range.h.
Referenced by hypro::Range< Number >::isEmpty().
The documentation for this struct was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/TaylorModel/TaylorModel.h
/home/travis/build/hypro/hypro/src/hypro/util/Range.h
/home/travis/build/hypro/hypro/src/hypro/representations/TaylorModel/TaylorModel.tpp