HyPro: hypro::HybridSystemParser::FuncExpressionContext Class Reference
hypro::HybridSystemParser::FuncExpressionContext Class Reference
#include <HybridSystemParser.h>
Public Member Functions
FuncExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
ExpressionFactorContext * expressionFactor ()
StdLibFunctionContext * stdLibFunction ()
std::vector< ExpressionsContext * > expressions ()
ExpressionsContext * expressions (size_t i)
std::vector< OptExpressionContext * > optExpression ()
OptExpressionContext * optExpression (size_t i)
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Detailed Description
Definition at line 893 of file HybridSystemParser.h.
Constructor & Destructor Documentation
HybridSystemParser::FuncExpressionContext::FuncExpressionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 3962 of file HybridSystemParser.cpp.
Member Function Documentation
antlrcpp::Any HybridSystemParser::FuncExpressionContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
Definition at line 3995 of file HybridSystemParser.cpp.
HybridSystemParser::ExpressionFactorContext * HybridSystemParser::FuncExpressionContext::expressionFactor ()
Definition at line 3966 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::funcExpression().
std::vector< HybridSystemParser::ExpressionsContext * > HybridSystemParser::FuncExpressionContext::expressions ()
Definition at line 3974 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::funcExpression().
HybridSystemParser::ExpressionsContext * HybridSystemParser::FuncExpressionContext::expressions (size_t i)
Definition at line 3978 of file HybridSystemParser.cpp.
References i.
size_t HybridSystemParser::FuncExpressionContext::getRuleIndex () const override virtual
Definition at line 3991 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::RuleFuncExpression.
std::vector< HybridSystemParser::OptExpressionContext * > HybridSystemParser::FuncExpressionContext::optExpression ()
Definition at line 3982 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::funcExpression().
HybridSystemParser::OptExpressionContext * HybridSystemParser::FuncExpressionContext::optExpression (size_t i)
Definition at line 3986 of file HybridSystemParser.cpp.
References i.
HybridSystemParser::StdLibFunctionContext * HybridSystemParser::FuncExpressionContext::stdLibFunction ()
Definition at line 3970 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::funcExpression().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-cif/HybridSystemParser.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-cif/HybridSystemParser.cpp