HyPro: hypro::HybridSystemParser::GroupDeclContext Class Reference
hypro::HybridSystemParser::GroupDeclContext Class Reference
Public Member Functions
GroupDeclContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
DeclContext * decl ()
ImportsContext * imports ()
antlr4::tree::TerminalNode * IDENTIFIER ()
antlr4::tree::TerminalNode * RELATIVENAME ()
TypesContext * types ()
IdentifierContext * identifier ()
FuncParamsContext * funcParams ()
FuncBodyContext * funcBody ()
NameContext * name ()
ActualParmsContext * actualParms ()
FormalParmsContext * formalParms ()
GroupBodyContext * groupBody ()
OptSupKindContext * optSupKind ()
AutomatonBodyContext * automatonBody ()
SupKindContext * supKind ()
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Detailed Description
Definition at line 246 of file HybridSystemParser.h.
Constructor & Destructor Documentation
HybridSystemParser::GroupDeclContext::GroupDeclContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 266 of file HybridSystemParser.cpp.
Member Function Documentation
antlrcpp::Any HybridSystemParser::GroupDeclContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
Definition at line 335 of file HybridSystemParser.cpp.
HybridSystemParser::ActualParmsContext * HybridSystemParser::GroupDeclContext::actualParms ()
Definition at line 306 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::groupDecl().
HybridSystemParser::AutomatonBodyContext * HybridSystemParser::GroupDeclContext::automatonBody ()
Definition at line 322 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::groupDecl().
HybridSystemParser::DeclContext * HybridSystemParser::GroupDeclContext::decl ()
Definition at line 270 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::groupDecl().
HybridSystemParser::FormalParmsContext * HybridSystemParser::GroupDeclContext::formalParms ()
Definition at line 310 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::groupDecl().
HybridSystemParser::FuncBodyContext * HybridSystemParser::GroupDeclContext::funcBody ()
Definition at line 298 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::groupDecl().
HybridSystemParser::FuncParamsContext * HybridSystemParser::GroupDeclContext::funcParams ()
Definition at line 294 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::groupDecl().
size_t HybridSystemParser::GroupDeclContext::getRuleIndex () const override virtual
Definition at line 331 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::RuleGroupDecl.
HybridSystemParser::GroupBodyContext * HybridSystemParser::GroupDeclContext::groupBody ()
Definition at line 314 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::groupDecl().
tree::TerminalNode * HybridSystemParser::GroupDeclContext::IDENTIFIER ()
Definition at line 278 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::IDENTIFIER.
HybridSystemParser::IdentifierContext * HybridSystemParser::GroupDeclContext::identifier ()
Definition at line 290 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::groupDecl().
HybridSystemParser::ImportsContext * HybridSystemParser::GroupDeclContext::imports ()
Definition at line 274 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::groupDecl().
HybridSystemParser::NameContext * HybridSystemParser::GroupDeclContext::name ()
Definition at line 302 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::groupDecl().
HybridSystemParser::OptSupKindContext * HybridSystemParser::GroupDeclContext::optSupKind ()
Definition at line 318 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::groupDecl().
tree::TerminalNode * HybridSystemParser::GroupDeclContext::RELATIVENAME ()
Definition at line 282 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::RELATIVENAME.
HybridSystemParser::SupKindContext * HybridSystemParser::GroupDeclContext::supKind ()
Definition at line 326 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::groupDecl().
HybridSystemParser::TypesContext * HybridSystemParser::GroupDeclContext::types ()
Definition at line 286 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::groupDecl().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-cif/HybridSystemParser.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-cif/HybridSystemParser.cpp