HyPro: hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD > Class Template Reference
hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD > Class Template Reference
Specialization of orthogonal polyhedra by the neighborhood representation.
#include <Neighborhood.h>
Public Member Functions
OrthogonalPolyhedron ()
OrthogonalPolyhedron (const Vertex< Number > &_vertex)
OrthogonalPolyhedron (const VertexContainer< Number > &vertices)
OrthogonalPolyhedron (const std::set< Vertex< Number >> &points)
OrthogonalPolyhedron (const std::vector< Vertex< Number >> &points)
OrthogonalPolyhedron (const OrthogonalPolyhedron< Number, Type > &copy)
OrthogonalPolyhedron (const OrthogonalPolyhedron< Number, Type > &&move)
std::vector< carl::Variable > variables () const
std::vector< Vertex< Number > > vertices () const
Box< Number > boundaryBox () const
void addVertex (const Vertex< Number > &_vertex)
void addVertices (const std::vector< Vertex< Number >> &_vertices)
bool empty () const
unsigned size () const
bool isVertex (const Point< Number > &_point) const
bool isOnIEdge (const Point< Number > &_point, unsigned i) const
bool isInternal (const Point< Number > &_point) const
bool isExternal (const Point< Number > &_point) const
std::vector< Point< Number > > iNeighborhood (const Point< Number > &_point, unsigned i) const
std::vector< Point< Number > > iNegNeighborhood (const Point< Number > &_point, unsigned i) const
std::vector< Point< Number > > neighborhood (const Point< Number > &_point) const
std::vector< Point< Number > > iSlice (unsigned i, Number pos) const
OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > iProjection (unsigned i) const
unsigned int dimension () const
OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > linearTransformation (const matrix_t< Number > &A, const vector_t< Number > &b) const
OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > minkowskiSum (const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > &rhs) const
OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > intersect (const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > &rhs) const
OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > hull () const
bool contains (const Point< Number > &point) const
bool contains (const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > &_other) const
OrthogonalPolyhedron< Number, Type > unite (const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > &rhs) const
std::vector< std::vector< Point< Number > > > preparePlot (unsigned _xDim=0, unsigned _yDim=1) const
OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > & operator= (const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > &_in)=default
OrthogonalPolyhedron< Number, TyORTHO_TYPE::NEIGHBORHOODpe > & operator= (OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > &&)=default
Private Attributes
Grid< Number > mGrid
Friends
bool operator== (const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > &op1, const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > &op2)
bool operator!= (const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > &op1, const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > &op2)
std::ostream & operator<< (std::ostream &ostr, const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > &p)
Detailed Description
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD>
class hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >
Specialization of orthogonal polyhedra by the neighborhood representation.
Template Parameters
Number The used number type.
<unnamed> The specialized representation type.
Definition at line 17 of file Neighborhood.h.
Constructor & Destructor Documentation
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::OrthogonalPolyhedron ()
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::OrthogonalPolyhedron (const Vertex< Number > & _vertex)
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::OrthogonalPolyhedron (const VertexContainer< Number > & vertices)
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::OrthogonalPolyhedron (const std::set< Vertex< Number >> & points)
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::OrthogonalPolyhedron (const std::vector< Vertex< Number >> & points)
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::OrthogonalPolyhedron (const OrthogonalPolyhedron< Number, Type > & copy)
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::OrthogonalPolyhedron (const OrthogonalPolyhedron< Number, Type > && move)
Member Function Documentation
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > void hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::addVertex (const Vertex< Number > & _vertex)
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > void hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::addVertices (const std::vector< Vertex< Number >> & _vertices)
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > Box<Number> hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::boundaryBox () const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > bool hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::contains (const Point< Number > & point) const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > bool hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::contains (const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > & _other) const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > unsigned int hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::dimension () const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > bool hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::empty () const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > OrthogonalPolyhedron<Number, ORTHO_TYPE::NEIGHBORHOOD> hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::hull () const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > std::vector<Point<Number> > hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::iNegNeighborhood (const Point< Number > & _point, unsigned i) const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > std::vector<Point<Number> > hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::iNeighborhood (const Point< Number > & _point, unsigned i) const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > OrthogonalPolyhedron<Number, ORTHO_TYPE::NEIGHBORHOOD> hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::intersect (const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > & rhs) const
Referenced by main().
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > OrthogonalPolyhedron<Number, ORTHO_TYPE::NEIGHBORHOOD> hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::iProjection (unsigned i) const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > bool hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::isExternal (const Point< Number > & _point) const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > bool hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::isInternal (const Point< Number > & _point) const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > std::vector<Point<Number> > hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::iSlice (unsigned i, Number pos) const
Referenced by main().
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > bool hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::isOnIEdge (const Point< Number > & _point, unsigned i) const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > bool hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::isVertex (const Point< Number > & _point) const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > OrthogonalPolyhedron<Number, ORTHO_TYPE::NEIGHBORHOOD> hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::linearTransformation (const matrix_t< Number > & A, const vector_t< Number > & b) const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > OrthogonalPolyhedron<Number, ORTHO_TYPE::NEIGHBORHOOD> hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::minkowskiSum (const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > & rhs) const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > std::vector<Point<Number> > hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::neighborhood (const Point< Number > & _point) const
Referenced by main().
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > OrthogonalPolyhedron<Number, ORTHO_TYPE::NEIGHBORHOOD>& hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::operator= (const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > & _in) default
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > OrthogonalPolyhedron<Number, TyORTHO_TYPE::NEIGHBORHOODpe>& hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::operator= (OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > &&) default
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > std::vector<std::vector<Point<Number> > > hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::preparePlot (unsigned _xDim = 0, unsigned _yDim = 1) const
Referenced by main().
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > unsigned hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::size () const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > OrthogonalPolyhedron<Number, Type> hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::unite (const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > & rhs) const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > std::vector<carl::Variable> hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::variables () const
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > std::vector<Vertex<Number> > hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::vertices () const
Referenced by main().
Friends And Related Function Documentation
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > bool operator!= (const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > & op1, const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > & op2) friend
Definition at line 92 of file Neighborhood.h.
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > std::ostream& operator<< (std::ostream & ostr, const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > & p) friend
Definition at line 97 of file Neighborhood.h.
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > bool operator== (const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > & op1, const OrthogonalPolyhedron< Number, ORTHO_TYPE::NEIGHBORHOOD > & op2) friend
Definition at line 87 of file Neighborhood.h.
Member Data Documentation
template<typename Number, ORTHO_TYPE::NEIGHBORHOOD > Grid<Number> hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >::mGrid private
Definition at line 19 of file Neighborhood.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/OrthogonalPolyhedron/representations/Neighborhood.h