HyPro: hypro::UnionOp< Number, Converter, Setting > Class Template Reference
hypro::UnionOp< Number, Converter, Setting > Class Template Reference
#include <UnionOp.h>
Public Member Functions
UnionOp ()=delete
UnionOp (const SupportFunctionNewT< Number, Converter, Setting > &lhs, const SupportFunctionNewT< Number, Converter, Setting > &rhs)
UnionOp (const SupportFunctionNewT< Number, Converter, Setting > &lhs, const std::vector< SupportFunctionNewT< Number, Converter, Setting >> &rhs)
UnionOp (const RGNData &)
~UnionOp ()
SFNEW_TYPE getType () const override
unsigned getOriginCount () const override
std::size_t getDimension () const override
RGNData * getData () const override
void setDimension (const std::size_t d) override
matrix_t< Number > transform (const matrix_t< Number > &param) const override
std::vector< EvaluationResult< Number > > compute (const matrix_t< Number > &, bool) const override
std::vector< EvaluationResult< Number > > aggregate (std::vector< std::vector< EvaluationResult< Number >>> &resultStackBack, const matrix_t< Number > &) const override
bool empty (const std::vector< bool > &childrenEmpty) const override
Point< Number > supremumPoint (std::vector< Point< Number >> &points) const override
bool contains (const std::vector< bool > &v, const vector_t< Number > &) const override
std::vector< std::size_t > intersectDims (const std::vector< std::vector< std::size_t >> &dims) const override
Public Member Functions inherited from hypro::RootGrowNode< Number, Converter, Setting >
RootGrowNode ()
virtual ~RootGrowNode ()
virtual PointerVec getChildren () const
virtual PointerVec & rGetChildren ()
virtual SETSTATE isEmpty () const
virtual LeafData getLeafData () const
void addToChildren (const std::shared_ptr< RootGrowNode > &rhs)
void clearChildren ()
virtual void print (std::ostream &ostr) const
virtual bool empty () const
virtual Point< Number > supremumPoint () const
virtual vector_t< Number > reverseOp (const vector_t< Number > &point) const
virtual bool contains (const vector_t< Number > &) const
Private Attributes
SFNEW_TYPE type = SFNEW_TYPE::UNIONOP
unsigned originCount = 2
std::size_t mDimension
std::vector< std::shared_ptr< RootGrowNode< Number, Converter, Setting > > > mChildren
Additional Inherited Members
Public Types inherited from hypro::RootGrowNode< Number, Converter, Setting >
using PointerVec = std::vector< std::shared_ptr< RootGrowNode< Number, Converter, Setting >>>
Protected Attributes inherited from hypro::RootGrowNode< Number, Converter, Setting >
SFNEW_TYPE mType = NODE
unsigned originCount = 0
PointerVec mChildren = PointerVec()
std::size_t mDimension = 0
SETSTATE mEmptyState = SETSTATE::UNKNOWN
Detailed Description
template<typename Number, typename Converter, typename Setting>
class hypro::UnionOp< Number, Converter, Setting >
Definition at line 25 of file UnionOp.h.
Constructor & Destructor Documentation
template<typename Number , typename Converter , typename Setting > hypro::UnionOp< Number, Converter, Setting >::UnionOp () delete
template<typename Number , typename Converter , typename Setting > hypro::UnionOp< Number, Converter, Setting >::UnionOp (const SupportFunctionNewT< Number, Converter, Setting > & lhs, const SupportFunctionNewT< Number, Converter, Setting > & rhs) inline
Definition at line 41 of file UnionOp.h.
References hypro::SupportFunctionNewT< Number, Converter, Setting >::addOperation(), assert(), hypro::SupportFunctionNewT< Number, Converter, Setting >::dimension(), hypro::EMPTY, hypro::SupportFunctionNewT< Number, Converter, Setting >::empty(), and vector.
template<typename Number , typename Converter , typename Setting > hypro::UnionOp< Number, Converter, Setting >::UnionOp (const SupportFunctionNewT< Number, Converter, Setting > & lhs, const std::vector< SupportFunctionNewT< Number, Converter, Setting >> & rhs) inline
Definition at line 51 of file UnionOp.h.
References hypro::SupportFunctionNewT< Number, Converter, Setting >::addOperation(), assert(), hypro::SupportFunctionNewT< Number, Converter, Setting >::dimension(), hypro::SupportFunctionNewT< Number, Converter, Setting >::empty(), and rhs.
template<typename Number , typename Converter , typename Setting > hypro::UnionOp< Number, Converter, Setting >::UnionOp (const RGNData &) inline
Definition at line 62 of file UnionOp.h.
template<typename Number , typename Converter , typename Setting > hypro::UnionOp< Number, Converter, Setting >::~UnionOp () inline
Definition at line 64 of file UnionOp.h.
Member Function Documentation
template<typename Number , typename Converter , typename Setting > std::vector<EvaluationResult<Number> > hypro::UnionOp< Number, Converter, Setting >::aggregate (std::vector< std::vector< EvaluationResult< Number >>> & resultStackBack, const matrix_t< Number > &) const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 89 of file UnionOp.h.
References assert(), hypro::FEAS, hypro::INFEAS, and hypro::INFTY.
template<typename Number , typename Converter , typename Setting > std::vector<EvaluationResult<Number> > hypro::UnionOp< Number, Converter, Setting >::compute (const matrix_t< Number > & , bool) const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 82 of file UnionOp.h.
References assert().
template<typename Number , typename Converter , typename Setting > bool hypro::UnionOp< Number, Converter, Setting >::contains (const std::vector< bool > & v, const vector_t< Number > &) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 132 of file UnionOp.h.
template<typename Number , typename Converter , typename Setting > bool hypro::UnionOp< Number, Converter, Setting >::empty (const std::vector< bool > & childrenEmpty) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 113 of file UnionOp.h.
template<typename Number , typename Converter , typename Setting > RGNData* hypro::UnionOp< Number, Converter, Setting >::getData () const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 71 of file UnionOp.h.
template<typename Number , typename Converter , typename Setting > std::size_t hypro::UnionOp< Number, Converter, Setting >::getDimension () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 70 of file UnionOp.h.
References hypro::UnionOp< Number, Converter, Setting >::mDimension.
template<typename Number , typename Converter , typename Setting > unsigned hypro::UnionOp< Number, Converter, Setting >::getOriginCount () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 69 of file UnionOp.h.
References hypro::UnionOp< Number, Converter, Setting >::originCount.
template<typename Number , typename Converter , typename Setting > SFNEW_TYPE hypro::UnionOp< Number, Converter, Setting >::getType () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 68 of file UnionOp.h.
References hypro::UnionOp< Number, Converter, Setting >::type.
template<typename Number , typename Converter , typename Setting > std::vector<std::size_t> hypro::UnionOp< Number, Converter, Setting >::intersectDims (const std::vector< std::vector< std::size_t >> & dims) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 140 of file UnionOp.h.
References dims.
template<typename Number , typename Converter , typename Setting > void hypro::UnionOp< Number, Converter, Setting >::setDimension (const std::size_t d) inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 72 of file UnionOp.h.
References d.
template<typename Number , typename Converter , typename Setting > Point<Number> hypro::UnionOp< Number, Converter, Setting >::supremumPoint (std::vector< Point< Number >> & points) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 121 of file UnionOp.h.
References assert(), hypro::Point< Number >::inftyNorm(), and points.
template<typename Number , typename Converter , typename Setting > matrix_t<Number> hypro::UnionOp< Number, Converter, Setting >::transform (const matrix_t< Number > & param) const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 77 of file UnionOp.h.
Member Data Documentation
template<typename Number , typename Converter , typename Setting > std::vector<std::shared_ptr<RootGrowNode<Number, Converter, Setting> > > hypro::UnionOp< Number, Converter, Setting >::mChildren private
Definition at line 32 of file UnionOp.h.
template<typename Number , typename Converter , typename Setting > std::size_t hypro::UnionOp< Number, Converter, Setting >::mDimension private
Definition at line 31 of file UnionOp.h.
Referenced by hypro::UnionOp< Number, Converter, Setting >::getDimension().
template<typename Number , typename Converter , typename Setting > unsigned hypro::UnionOp< Number, Converter, Setting >::originCount = 2 private
Definition at line 30 of file UnionOp.h.
Referenced by hypro::UnionOp< Number, Converter, Setting >::getOriginCount().
template<typename Number , typename Converter , typename Setting > SFNEW_TYPE hypro::UnionOp< Number, Converter, Setting >::type = SFNEW_TYPE::UNIONOP private
Definition at line 29 of file UnionOp.h.
Referenced by hypro::UnionOp< Number, Converter, Setting >::getType().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunctionNew/UnionOp.h