HyPro: hypro::VertexEnumeration< Number > Class Template Reference
hypro::VertexEnumeration< Number > Class Template Reference
Public Member Functions
VertexEnumeration ()=default
VertexEnumeration (const VertexEnumeration< Number > &_orig)=default
VertexEnumeration (const std::vector< Halfspace< Number >> &hsv)
VertexEnumeration (const matrix_t< Number > &constraints, const vector_t< Number > &constants)
~VertexEnumeration ()=default
const std::vector< Halfspace< Number > > & getHsv () const
const std::vector< Dictionary< Number > > & getDictionaries () const
const std::vector< Point< Number > > & getPositivePoints () const
void printPositivePoints () const
const std::vector< Point< Number > > & getPoints () const
void printPoints () const
const std::vector< vector_t< Number > > & getLinealtySpace () const
void printLinealtySpace () const
const std::vector< vector_t< Number > > & getPositiveCones () const
void printPositiveCones () const
const std::vector< vector_t< Number > > & getCones () const
void printCones () const
void increment (Eigen::Index &i, Eigen::Index &j, std::size_t maxJ)
void enumerateVertices ()
does everything with the halfspaces in mHsv
void enumerateVerticesNaive ()
create vertices by permutating all d-combinations of half-spaces.
void enumerateVertices (Dictionary< Number > &dictionary)
find all the vertices obtained from a given dictionary acording to Fukuda's algorithm.
void enumerateVerticesEachDictionary ()
enumerate all the vertices of the dictionaries in mDictionaries.
void enumerateDictionaries ()
Finds all the optimal dictionaries from the first one in mDictionaries.
Dictionary< Number > findFirstVertex ()
Finds a fist vertex, detects the linealty spaces and adds the corresponding constrains.
int linearIndependance (std::map< int, vector_t< Number >> collection, vector_t< Number > &candidateRef) const
If the candidate is independent from the collection, returns the smallest non nul coordinate, -1 otherwise.
std::vector< std::size_t > findIndepHs () const
Point< Number > findIntersection (const std::vector< std::size_t > &selectionRef) const
bool findPositiveConstrains ()
Transform Ax<=b into A'y<=b' & y>=0.
void toGeneralCoordinates ()
Converts the positive cones and points into the original system of coordinates.
void findLinealtySpace ()
void addLinealtyConstrains ()
Adds to halfspace set two halfspaces for each linealty direction to block it.
Detailed Description
template<typename Number>
class hypro::VertexEnumeration< Number >
Definition at line 11 of file vertexEnumeration.h.
Constructor & Destructor Documentation
template<typename Number> hypro::VertexEnumeration< Number >::VertexEnumeration () default
template<typename Number> hypro::VertexEnumeration< Number >::VertexEnumeration (const VertexEnumeration< Number > & _orig) default
template<typename Number > hypro::VertexEnumeration< Number >::VertexEnumeration (const std::vector< Halfspace< Number >> & hsv)
Definition at line 16 of file vertexEnumeration.tpp.
template<typename Number > hypro::VertexEnumeration< Number >::VertexEnumeration (const matrix_t< Number > & constraints, const vector_t< Number > & constants)
Definition at line 20 of file vertexEnumeration.tpp.
template<typename Number> hypro::VertexEnumeration< Number >::~VertexEnumeration () default
Member Function Documentation
template<typename Number > void hypro::VertexEnumeration< Number >::addLinealtyConstrains ()
Adds to halfspace set two halfspaces for each linealty direction to block it.
Definition at line 644 of file vertexEnumeration.tpp.
Referenced by hypro::VertexEnumeration< Number >::findFirstVertex().
template<typename Number > void hypro::VertexEnumeration< Number >::enumerateDictionaries ()
Finds all the optimal dictionaries from the first one in mDictionaries.
Definition at line 263 of file vertexEnumeration.tpp.
References hypro::Dictionary< Number >::basis(), hypro::Dictionary< Number >::cobasis(), hypro::Dictionary< Number >::findZeros(), hypro::Dictionary< Number >::get(), hypro::VertexEnumeration< Number >::increment(), hypro::Dictionary< Number >::isDualFeasible(), hypro::Dictionary< Number >::isOptimal(), hypro::Dictionary< Number >::pivot(), hypro::Dictionary< Number >::reverseDual(), hypro::Dictionary< Number >::selectDualBlandPivot(), hypro::Dictionary< Number >::setOnes(), and hypro::Dictionary< Number >::setValue().
Referenced by hypro::VertexEnumeration< Number >::enumerateVertices().
template<typename Number > void hypro::VertexEnumeration< Number >::enumerateVertices ()
does everything with the halfspaces in mHsv
Definition at line 98 of file vertexEnumeration.tpp.
References hypro::VertexEnumeration< Number >::enumerateDictionaries(), hypro::VertexEnumeration< Number >::enumerateVerticesEachDictionary(), hypro::VertexEnumeration< Number >::findPositiveConstrains(), and hypro::VertexEnumeration< Number >::toGeneralCoordinates().
Referenced by hypro::ConvexHull< Number >::convexHullVertices(), hypro::VertexEnumeration< Number >::enumerateVerticesEachDictionary(), and main().
template<typename Number > void hypro::VertexEnumeration< Number >::enumerateVertices (Dictionary< Number > & dictionary)
find all the vertices obtained from a given dictionary acording to Fukuda's algorithm.
Definition at line 187 of file vertexEnumeration.tpp.
References hypro::Dictionary< Number >::basis(), hypro::Dictionary< Number >::cobasis(), hypro::Dictionary< Number >::findCones(), hypro::VertexEnumeration< Number >::increment(), hypro::Dictionary< Number >::isLexMin(), hypro::Dictionary< Number >::isOptimal(), hypro::Dictionary< Number >::isPrimalFeasible(), hypro::Dictionary< Number >::pivot(), hypro::Dictionary< Number >::printDictionary(), hypro::Dictionary< Number >::reverse(), hypro::Dictionary< Number >::selectBlandPivot(), and hypro::Dictionary< Number >::toPoint().
template<typename Number > void hypro::VertexEnumeration< Number >::enumerateVerticesEachDictionary ()
enumerate all the vertices of the dictionaries in mDictionaries.
Definition at line 253 of file vertexEnumeration.tpp.
References hypro::VertexEnumeration< Number >::enumerateVertices().
Referenced by hypro::VertexEnumeration< Number >::enumerateVertices().
template<typename Number > void hypro::VertexEnumeration< Number >::enumerateVerticesNaive ()
create vertices by permutating all d-combinations of half-spaces.
Definition at line 133 of file vertexEnumeration.tpp.
References default_double_comparison_ulps.
template<typename Number > Dictionary< Number > hypro::VertexEnumeration< Number >::findFirstVertex ()
Finds a fist vertex, detects the linealty spaces and adds the corresponding constrains.
Definition at line 322 of file vertexEnumeration.tpp.
References hypro::ConstrainSet< Number >::add(), hypro::VertexEnumeration< Number >::addLinealtyConstrains(), hypro::Dictionary< Number >::constrainSet(), hypro::Dictionary< Number >::fixOutOfBounds(), hypro::Dictionary< Number >::nonSlackToBase(), hypro::Dictionary< Number >::pushToBounds(), and hypro::Dictionary< Number >::toCobase().
Referenced by hypro::VertexEnumeration< Number >::findPositiveConstrains().
template<typename Number > std::vector< std::size_t > hypro::VertexEnumeration< Number >::findIndepHs () const
Returns
A set of the index of d independent hyperplanes of mHsv.
Definition at line 443 of file vertexEnumeration.tpp.
References hypro::VertexEnumeration< Number >::linearIndependance().
template<typename Number > Point< Number > hypro::VertexEnumeration< Number >::findIntersection (const std::vector< std::size_t > & selectionRef) const
Returns
the intersection of the hyperplanes in selectionRef.
Definition at line 464 of file vertexEnumeration.tpp.
template<typename Number > void hypro::VertexEnumeration< Number >::findLinealtySpace ()
Definition at line 591 of file vertexEnumeration.tpp.
template<typename Number > bool hypro::VertexEnumeration< Number >::findPositiveConstrains ()
Transform Ax<=b into A'y<=b' & y>=0.
Definition at line 478 of file vertexEnumeration.tpp.
References hypro::Dictionary< Number >::basis(), hypro::Dictionary< Number >::cobasis(), hypro::Dictionary< Number >::constrainSet(), hypro::VertexEnumeration< Number >::findFirstVertex(), and hypro::Dictionary< Number >::isOptimal().
Referenced by hypro::VertexEnumeration< Number >::enumerateVertices().
template<typename Number > const std::vector< vector_t< Number > > & hypro::VertexEnumeration< Number >::getCones () const
Definition at line 86 of file vertexEnumeration.tpp.
template<typename Number > const std::vector< Dictionary< Number > > & hypro::VertexEnumeration< Number >::getDictionaries () const
Definition at line 33 of file vertexEnumeration.tpp.
template<typename Number > const std::vector< Halfspace< Number > > & hypro::VertexEnumeration< Number >::getHsv () const
Definition at line 28 of file vertexEnumeration.tpp.
template<typename Number > const std::vector< vector_t< Number > > & hypro::VertexEnumeration< Number >::getLinealtySpace () const
Definition at line 62 of file vertexEnumeration.tpp.
Referenced by hypro::ConvexHull< Number >::convexHullVertices().
template<typename Number > const std::vector< Point< Number > > & hypro::VertexEnumeration< Number >::getPoints () const
Definition at line 50 of file vertexEnumeration.tpp.
Referenced by hypro::ConvexHull< Number >::convexHullVertices(), and main().
template<typename Number > const std::vector< vector_t< Number > > & hypro::VertexEnumeration< Number >::getPositiveCones () const
Definition at line 74 of file vertexEnumeration.tpp.
template<typename Number > const std::vector< Point< Number > > & hypro::VertexEnumeration< Number >::getPositivePoints () const
Definition at line 38 of file vertexEnumeration.tpp.
template<typename Number > void hypro::VertexEnumeration< Number >::increment (Eigen::Index & i, Eigen::Index & j, std::size_t maxJ)
Definition at line 6 of file vertexEnumeration.tpp.
Referenced by hypro::VertexEnumeration< Number >::enumerateDictionaries(), and hypro::VertexEnumeration< Number >::enumerateVertices().
template<typename Number > int hypro::VertexEnumeration< Number >::linearIndependance (std::map< int, vector_t< Number >> collection, vector_t< Number > & candidateRef) const
If the candidate is independent from the collection, returns the smallest non nul coordinate, -1 otherwise.
Definition at line 424 of file vertexEnumeration.tpp.
Referenced by hypro::VertexEnumeration< Number >::findIndepHs().
template<typename Number > void hypro::VertexEnumeration< Number >::printCones () const
Definition at line 91 of file vertexEnumeration.tpp.
template<typename Number > void hypro::VertexEnumeration< Number >::printLinealtySpace () const
Definition at line 67 of file vertexEnumeration.tpp.
template<typename Number > void hypro::VertexEnumeration< Number >::printPoints () const
Definition at line 55 of file vertexEnumeration.tpp.
template<typename Number > void hypro::VertexEnumeration< Number >::printPositiveCones () const
Definition at line 79 of file vertexEnumeration.tpp.
template<typename Number > void hypro::VertexEnumeration< Number >::printPositivePoints () const
Definition at line 43 of file vertexEnumeration.tpp.
template<typename Number > void hypro::VertexEnumeration< Number >::toGeneralCoordinates ()
Converts the positive cones and points into the original system of coordinates.
Definition at line 579 of file vertexEnumeration.tpp.
Referenced by hypro::VertexEnumeration< Number >::enumerateVertices().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/convexHull/vertexEnumeration.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/convexHull/vertexEnumeration.tpp