HyPro: MReach Class Reference
MReach Class Reference
#include <MReach.h>
Public Types
using Reacher = hypro::reachability::Reach< double, hypro::reachability::ReachSettings, hypro::State_t< double >>
using flowpipe = std::vector< hypro::State_t< double >>
Static Public Member Functions
static void del_reach (int lhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
static void new_reach (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
static void computeForwardReachability (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
static void setSettings (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
static void setRepresentationType (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
static void settings (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
static void process (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
static void reachedBadStates (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
Detailed Description
Definition at line 14 of file MReach.h.
Member Typedef Documentation
using MReach::flowpipe = std::vector<hypro::State_t<double>>
Definition at line 17 of file MReach.h.
using MReach::Reacher = hypro::reachability::Reach<double, hypro::reachability::ReachSettings, hypro::State_t<double>>
Definition at line 16 of file MReach.h.
Member Function Documentation
void MReach::computeForwardReachability (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[]) static
Definition at line 19 of file MReach.cpp.
References dims, flowpipes, ObjectHandle::flowpipes2Matlab(), mexErrMsgTxt(), and reacher.
Referenced by process().
void MReach::del_reach (int lhs, mxArray * plhs[], int nrhs, const mxArray * prhs[]) static
Definition at line 3 of file MReach.cpp.
References mexErrMsgTxt().
Referenced by process().
void MReach::new_reach (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[]) static
Definition at line 9 of file MReach.cpp.
References mexErrMsgTxt(), and reacher.
Referenced by process().
void MReach::process (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[]) static
Definition at line 201 of file MReach.cpp.
References computeForwardReachability(), del_reach(), mexErrMsgTxt(), new_reach(), reachedBadStates(), setRepresentationType(), setSettings(), and settings().
Referenced by mexFunction().
void MReach::reachedBadStates (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[]) static
Definition at line 191 of file MReach.cpp.
References mexErrMsgTxt(), reacher, and safe.
Referenced by process().
void MReach::setRepresentationType (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[]) static
Definition at line 39 of file MReach.cpp.
References box, mexErrMsgTxt(), reacher, and type.
Referenced by process().
void MReach::setSettings (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[]) static
Definition at line 74 of file MReach.cpp.
References hypro::clustering, hypro::ReachabilitySettings::clustering, cols, dims, file(), hypro::ReachabilitySettings::fileName, fname, hypro::ReachabilitySettings::jumpDepth, jumpDepth, mexErrMsgTxt(), ObjectHandle::mVectorOfVectors2Hypro(), hypro::ReachabilitySettings::plotDimensions, hypro::ReachabilitySettings::pplDenomimator, reacher, settings(), string(), timeBound, hypro::ReachabilitySettings::timeBound, hypro::ReachabilitySettings::timeStep, timeStep, tmp, uniformBloating, and hypro::ReachabilitySettings::uniformBloating.
Referenced by process().
void MReach::settings (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[]) static
Definition at line 133 of file MReach.cpp.
References dim, i, hypro::ReachabilitySettings::jumpDepth, mexErrMsgTxt(), reacher, size, and string().
Referenced by process(), and setSettings().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/util/matlab/reachability/@MHyProReach/MReach.h
/home/travis/build/hypro/hypro/src/hypro/util/matlab/reachability/@MHyProReach/MReach.cpp