HyPro: hypro::HyproSettingVisitor< Number > Class Template Reference
hypro::HyproSettingVisitor< Number > Class Template Reference
Public Member Functions
HyproSettingVisitor (std::vector< std::string > &varVec)
~HyproSettingVisitor ()
antlrcpp::Any visitSetting (HybridAutomatonParser::SettingContext *ctx) override
Friends
class HyproHAVisitor< Number >
Detailed Description
template<typename Number>
class hypro::HyproSettingVisitor< Number >
Definition at line 36 of file HyproFormulaVisitor.h.
Constructor & Destructor Documentation
template<typename Number > hypro::HyproSettingVisitor< Number >::HyproSettingVisitor (std::vector< std::string > & varVec)
Definition at line 8 of file HyproSettingVisitor.tpp.
template<typename Number > hypro::HyproSettingVisitor< Number >::~HyproSettingVisitor ()
Definition at line 13 of file HyproSettingVisitor.tpp.
Member Function Documentation
template<typename Number > antlrcpp::Any hypro::HyproSettingVisitor< Number >::visitSetting (HybridAutomatonParser::SettingContext * ctx) override virtual
Reimplemented from hypro::HybridAutomatonBaseVisitor.
Definition at line 18 of file HyproSettingVisitor.tpp.
References hypro::ReachabilitySettings::fileName, hypro::HybridAutomatonParser::SettingContext::filename(), hypro::HybridAutomatonParser::SettingContext::fixedsteps(), hypro::ReachabilitySettings::jumpDepth, hypro::HybridAutomatonParser::SettingContext::maxjumps(), hypro::HybridAutomatonParser::FixedstepsContext::NUMBER(), hypro::HybridAutomatonParser::TimeContext::NUMBER(), hypro::HybridAutomatonParser::MaxjumpsContext::NUMBER(), hypro::ReachabilitySettings::plotDimensions, hypro::HybridAutomatonParser::SettingContext::plotsetting(), hypro::HybridAutomatonParser::SettingContext::time(), hypro::ReachabilitySettings::timeBound, hypro::ReachabilitySettings::timeStep, hypro::HybridAutomatonParser::PlotsettingContext::VARIABLE(), and hypro::HybridAutomatonParser::FilenameContext::VARIABLE().
Friends And Related Function Documentation
template<typename Number> friend class HyproHAVisitor< Number > friend
Definition at line 31 of file HyproSettingVisitor.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HyproFormulaVisitor.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HyproSettingVisitor.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HyproSettingVisitor.tpp