HyPro: hypro::NodeManager< State > Class Template Reference
hypro::NodeManager< State > Class Template Reference
#include <NodeManager.h>
Public Member Functions
ReachTreeNode< State >::NodeList_t setInitialStates (const std::vector< State > &_init_states)
ReachTreeNode< State >::Node_t getNode (const std::vector< unsigned > &_id)
bool fixedPointReached (const State &s)
void printTree ()
const ReachTree< State > & getTree () const
Static Public Member Functions
static void printTree (typename ReachTreeNode< State >::Node_t _node)
Private Types
using Number = typename State::NumberType
Private Member Functions
NodeManager ()
~NodeManager ()
Private Attributes
ReachTreeNode< State >::NodeList_t mInitialStates
ReachTree< State > mTree
Detailed Description
template<typename State>
class hypro::NodeManager< State >
Definition at line 25 of file NodeManager.h.
Member Typedef Documentation
template<typename State > using hypro::NodeManager< State >::Number = typename State::NumberType private
Definition at line 26 of file NodeManager.h.
Constructor & Destructor Documentation
template<typename State > hypro::NodeManager< State >::NodeManager () private
template<typename State > hypro::NodeManager< State >::~NodeManager () inline private
Definition at line 35 of file NodeManager.h.
References hypro::NodeManager< State >::fixedPointReached(), hypro::NodeManager< State >::getNode(), hypro::NodeManager< State >::printTree(), s, and hypro::NodeManager< State >::setInitialStates().
Member Function Documentation
template<typename State > bool hypro::NodeManager< State >::fixedPointReached (const State & s)
Referenced by hypro::NodeManager< State >::~NodeManager().
template<typename State > ReachTreeNode<State>::Node_t hypro::NodeManager< State >::getNode (const std::vector< unsigned > & _id)
Referenced by hypro::NodeManager< State >::~NodeManager().
template<typename State > const ReachTree<State>& hypro::NodeManager< State >::getTree () const inline
Definition at line 45 of file NodeManager.h.
References hypro::NodeManager< State >::mTree, and hypro::NodeManager< State >::printTree().
template<typename State > void hypro::NodeManager< State >::printTree ()
Referenced by hypro::NodeManager< State >::getTree(), and hypro::NodeManager< State >::~NodeManager().
template<typename State > static void hypro::NodeManager< State >::printTree (typename ReachTreeNode< State >::Node_t _node) static
template<typename State > ReachTreeNode<State>::NodeList_t hypro::NodeManager< State >::setInitialStates (const std::vector< State > & _init_states)
Referenced by hypro::NodeManager< State >::~NodeManager().
Member Data Documentation
template<typename State > ReachTreeNode<State>::NodeList_t hypro::NodeManager< State >::mInitialStates private
Definition at line 30 of file NodeManager.h.
template<typename State > ReachTree<State> hypro::NodeManager< State >::mTree private
Definition at line 31 of file NodeManager.h.
Referenced by hypro::NodeManager< State >::getTree().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/NodeManager.h