HyPro: hypro::Cone< Number > Class Template Reference
hypro::Cone< Number > Class Template Reference
Public Types
using planeVector = std::vector< std::shared_ptr< Halfspace< Number >>>
Public Member Functions
Cone ()
Cone (const Cone &_orig)
Cone (const planeVector &_planes)
~Cone ()
const Cone< Number >::planeVector & planes () const
vectorSet< Number > vectors () const
unsigned dimension () const
unsigned size () const
void add (std::shared_ptr< Halfspace< Number >> _plane)
void add (vector_t< Number > _vector)
Cone< Number > linearTransformation (const matrix_t< Number > A) const
Cone< Number > affineTransformation (const matrix_t< Number > A, const vector_t< Number > &b) const
Cone< Number > minkowskiSum (const Cone &_rhs) const
Point< Number > getUnitAverageVector () const
bool contains (const vector_t< Number > &_vector) const
bool contains (const vector_t< Number > &_vector, planeVector &_insidePlanes, std::set< std::shared_ptr< Halfspace< Number >>> &_outsidePlanes) const
bool contains (const Point< Number > *_vector) const
Cone< Number > operator= (const Cone< Number > &_rhs)
Detailed Description
template<typename Number>
class hypro::Cone< Number >
Definition at line 22 of file Cone.h.
Member Typedef Documentation
template<typename Number> using hypro::Cone< Number >::planeVector = std::vector<std::shared_ptr<Halfspace<Number>>>
Definition at line 24 of file Cone.h.
Constructor & Destructor Documentation
template<typename Number > hypro::Cone< Number >::Cone ()
Definition at line 8 of file Cone.tpp.
template<typename Number > hypro::Cone< Number >::Cone (const Cone< Number > & _orig)
Definition at line 13 of file Cone.tpp.
template<typename Number > hypro::Cone< Number >::Cone (const planeVector & _planes)
Definition at line 18 of file Cone.tpp.
template<typename Number > hypro::Cone< Number >::~Cone ()
Definition at line 23 of file Cone.tpp.
Member Function Documentation
template<typename Number > void hypro::Cone< Number >::add (std::shared_ptr< Halfspace< Number >> _plane)
Definition at line 100 of file Cone.tpp.
Referenced by hypro::Cone< Number >::affineTransformation(), hypro::Cone< Number >::linearTransformation(), and hypro::Cone< Number >::minkowskiSum().
template<typename Number > void hypro::Cone< Number >::add (vector_t< Number > _vector)
Definition at line 106 of file Cone.tpp.
References hypro::Cone< Number >::contains(), and hypro::Cone< Number >::vectors().
template<typename Number > Cone< Number > hypro::Cone< Number >::affineTransformation (const matrix_t< Number > A, const vector_t< Number > & b) const
Definition at line 182 of file Cone.tpp.
References hypro::Cone< Number >::add().
template<typename Number > bool hypro::Cone< Number >::contains (const vector_t< Number > & _vector) const
Definition at line 212 of file Cone.tpp.
Referenced by hypro::Cone< Number >::add(), hypro::Cone< Number >::contains(), and hypro::Cone< Number >::vectors().
template<typename Number > bool hypro::Cone< Number >::contains (const vector_t< Number > & _vector, planeVector & _insidePlanes, std::set< std::shared_ptr< Halfspace< Number >>> & _outsidePlanes) const
Definition at line 220 of file Cone.tpp.
References hypro::Cone< Number >::contains().
template<typename Number > bool hypro::Cone< Number >::contains (const Point< Number > * _vector) const
Definition at line 235 of file Cone.tpp.
References hypro::Cone< Number >::contains(), and hypro::Point< Number >::rawCoordinates().
template<typename Number > unsigned hypro::Cone< Number >::dimension () const
Definition at line 88 of file Cone.tpp.
Referenced by hypro::Fan< Number >::add().
template<typename Number > Point< Number > hypro::Cone< Number >::getUnitAverageVector () const
Definition at line 201 of file Cone.tpp.
template<typename Number > Cone< Number > hypro::Cone< Number >::linearTransformation (const matrix_t< Number > A) const
Definition at line 172 of file Cone.tpp.
References hypro::Cone< Number >::add().
template<typename Number > Cone< Number > hypro::Cone< Number >::minkowskiSum (const Cone< Number > & _rhs) const
Definition at line 192 of file Cone.tpp.
References hypro::Cone< Number >::add(), and hypro::Cone< Number >::vectors().
template<typename Number > Cone< Number > hypro::Cone< Number >::operator= (const Cone< Number > & _rhs)
Definition at line 240 of file Cone.tpp.
References hypro::Cone< Number >::planes().
template<typename Number > const Cone< Number >::planeVector & hypro::Cone< Number >::planes () const
Definition at line 27 of file Cone.tpp.
Referenced by hypro::Cone< Number >::operator=().
template<typename Number > unsigned hypro::Cone< Number >::size () const
Definition at line 95 of file Cone.tpp.
Referenced by hypro::Fan< Number >::containingCone().
template<typename Number > vectorSet< Number > hypro::Cone< Number >::vectors () const
Definition at line 32 of file Cone.tpp.
References hypro::Cone< Number >::contains().
Referenced by hypro::Cone< Number >::add(), and hypro::Cone< Number >::minkowskiSum().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/Polytopes/Cone.h
/home/travis/build/hypro/hypro/src/hypro/representations/Polytopes/Cone.tpp