HyPro: hypro::TPolyTimeEvolutionHandler< State > Class Template Reference
hypro::TPolyTimeEvolutionHandler< State > Class Template Reference
Public Member Functions
TPolyTimeEvolutionHandler ()=delete
TPolyTimeEvolutionHandler (State *state, size_t index, tNumber timeStep, matrix_t< Number > trafo, vector_t< Number > translation)
~TPolyTimeEvolutionHandler ()
void handle ()
const char * handlerName ()
bool getMarkedForDelete ()
void setMarkedForDelete (bool)
void setInvariant (const vector_t< Number > &inv)
std::optional< vector_t< Number > > getRelaxedInvariant () const
const matrix_t< typename State::NumberType > & getTrafo () const
const vector_t< typename State::NumberType > & getTranslation () const
Public Member Functions inherited from hypro::ITimeEvolutionHandler
virtual ~ITimeEvolutionHandler ()
Protected Attributes
State * mState
size_t mIndex
tNumber mTimeStep
matrix_t< Number > mTrafo
vector_t< Number > mTranslation
std::optional< vector_t< Number > > mStrengthenedInvariant
Detailed Description
template<typename State>
class hypro::TPolyTimeEvolutionHandler< State >
Definition at line 56 of file forwardDeclarations.h.
Constructor & Destructor Documentation
template<typename State> hypro::TPolyTimeEvolutionHandler< State >::TPolyTimeEvolutionHandler () delete
template<typename State> hypro::TPolyTimeEvolutionHandler< State >::TPolyTimeEvolutionHandler (State * state, size_t index, tNumber timeStep, matrix_t< Number > trafo, vector_t< Number > translation) inline
Definition at line 33 of file TPolyTimeEvolutionHandler.h.
template<typename State> hypro::TPolyTimeEvolutionHandler< State >::~TPolyTimeEvolutionHandler () inline
Definition at line 41 of file TPolyTimeEvolutionHandler.h.
References hypro::TPolyTimeEvolutionHandler< State >::handle().
Member Function Documentation
template<typename State> bool hypro::TPolyTimeEvolutionHandler< State >::getMarkedForDelete () inline virtual
Implements hypro::ITimeEvolutionHandler.
Definition at line 46 of file TPolyTimeEvolutionHandler.h.
template<typename State> std::optional<vector_t<Number> > hypro::TPolyTimeEvolutionHandler< State >::getRelaxedInvariant () const inline
Definition at line 49 of file TPolyTimeEvolutionHandler.h.
References hypro::TPolyTimeEvolutionHandler< State >::mStrengthenedInvariant.
template<typename State> const matrix_t<typename State::NumberType>& hypro::TPolyTimeEvolutionHandler< State >::getTrafo () const inline
Definition at line 50 of file TPolyTimeEvolutionHandler.h.
References hypro::TPolyTimeEvolutionHandler< State >::mTrafo.
template<typename State> const vector_t<typename State::NumberType>& hypro::TPolyTimeEvolutionHandler< State >::getTranslation () const inline
Definition at line 51 of file TPolyTimeEvolutionHandler.h.
References hypro::TPolyTimeEvolutionHandler< State >::mTranslation.
template<typename State > void hypro::TPolyTimeEvolutionHandler< State >::handle () virtual
Implements hypro::ITimeEvolutionHandler.
Definition at line 26 of file TPolyTimeEvolutionHandler.tpp.
References hypro::EvaluationResult< Number >::errorCode, hypro::FEAS, hypro::INFTY, and hypro::EvaluationResult< Number >::supportValue.
Referenced by hypro::TPolyTimeEvolutionHandler< State >::~TPolyTimeEvolutionHandler().
template<typename State> const char* hypro::TPolyTimeEvolutionHandler< State >::handlerName () inline virtual
Implements hypro::ITimeEvolutionHandler.
Definition at line 45 of file TPolyTimeEvolutionHandler.h.
template<typename State > void hypro::TPolyTimeEvolutionHandler< State >::setInvariant (const vector_t< Number > & inv)
Definition at line 6 of file TPolyTimeEvolutionHandler.tpp.
Referenced by hypro::TPolyTimeEvolutionHandler< State >::setMarkedForDelete().
template<typename State> void hypro::TPolyTimeEvolutionHandler< State >::setMarkedForDelete (bool) inline virtual
Implements hypro::ITimeEvolutionHandler.
Definition at line 47 of file TPolyTimeEvolutionHandler.h.
References hypro::TPolyTimeEvolutionHandler< State >::setInvariant().
Member Data Documentation
template<typename State> size_t hypro::TPolyTimeEvolutionHandler< State >::mIndex protected
Definition at line 22 of file TPolyTimeEvolutionHandler.h.
template<typename State> State* hypro::TPolyTimeEvolutionHandler< State >::mState protected
Definition at line 21 of file TPolyTimeEvolutionHandler.h.
template<typename State> std::optional<vector_t<Number> > hypro::TPolyTimeEvolutionHandler< State >::mStrengthenedInvariant protected
Definition at line 28 of file TPolyTimeEvolutionHandler.h.
Referenced by hypro::TPolyTimeEvolutionHandler< State >::getRelaxedInvariant().
template<typename State> tNumber hypro::TPolyTimeEvolutionHandler< State >::mTimeStep protected
Definition at line 23 of file TPolyTimeEvolutionHandler.h.
template<typename State> matrix_t<Number> hypro::TPolyTimeEvolutionHandler< State >::mTrafo protected
Definition at line 24 of file TPolyTimeEvolutionHandler.h.
Referenced by hypro::TPolyTimeEvolutionHandler< State >::getTrafo().
template<typename State> vector_t<Number> hypro::TPolyTimeEvolutionHandler< State >::mTranslation protected
Definition at line 25 of file TPolyTimeEvolutionHandler.h.
Referenced by hypro::TPolyTimeEvolutionHandler< State >::getTranslation().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/forwardDeclarations.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/timeEvolutionHandlers/TPolyTimeEvolutionHandler.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/timeEvolutionHandlers/TPolyTimeEvolutionHandler.tpp