HyPro: hypro::z3Context Class Reference
hypro::z3Context Class Reference
#include <z3Context.h>
Public Member Functions
z3Context ()
~z3Context ()
z3::expr real_val (mpq_class val)
Detailed Description
Definition at line 9 of file z3Context.h.
Constructor & Destructor Documentation
hypro::z3Context::z3Context () inline
Definition at line 11 of file z3Context.h.
hypro::z3Context::~z3Context () inline
Definition at line 12 of file z3Context.h.
References real_val().
Member Function Documentation
z3::expr hypro::z3Context::real_val (mpq_class val)
Definition at line 5 of file z3Context.cpp.
References assert(), and string().
Referenced by hypro::addPreSolution(), and ~z3Context().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/util/linearOptimization/z3/z3Context.h
/home/travis/build/hypro/hypro/src/hypro/util/linearOptimization/z3/z3Context.cpp