HyPro: hypro::HybridSystemParser::DiscDeclContext Class Reference
hypro::HybridSystemParser::DiscDeclContext Class Reference
#include <HybridSystemParser.h>
Public Member Functions
DiscDeclContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
IdentifierContext * identifier ()
ExpressionContext * expression ()
ExpressionsContext * expressions ()
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Detailed Description
Definition at line 603 of file HybridSystemParser.h.
Constructor & Destructor Documentation
HybridSystemParser::DiscDeclContext::DiscDeclContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 2572 of file HybridSystemParser.cpp.
Member Function Documentation
antlrcpp::Any HybridSystemParser::DiscDeclContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
Definition at line 2593 of file HybridSystemParser.cpp.
HybridSystemParser::ExpressionContext * HybridSystemParser::DiscDeclContext::expression ()
Definition at line 2580 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::discDecl().
HybridSystemParser::ExpressionsContext * HybridSystemParser::DiscDeclContext::expressions ()
Definition at line 2584 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::discDecl().
size_t HybridSystemParser::DiscDeclContext::getRuleIndex () const override virtual
Definition at line 2589 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::RuleDiscDecl.
HybridSystemParser::IdentifierContext * HybridSystemParser::DiscDeclContext::identifier ()
Definition at line 2576 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::discDecl().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-cif/HybridSystemParser.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-cif/HybridSystemParser.cpp