HyPro: hypro::reachability::Reach< Number, ReacherSettings, State > Class Template Reference
hypro::reachability::Reach< Number, ReacherSettings, State > Class Template Reference
Class implementing a basic reachbility analysis algorithm for linear hybrid automata.
#include <Reach.h>
Public Types
using TaskType = std::pair< unsigned, State >
using TaskTypePtr = std::unique_ptr< TaskType >
using flowpipe_t = std::vector< State >
Public Member Functions
Reach (const HybridAutomaton< Number > &_automaton, const ReachabilitySettings &_settings=ReachabilitySettings())
Constructor for a basic reachability analysis algorithm for linear hybrid automata.
std::vector< std::pair< unsigned, flowpipe_t > > computeForwardReachability ()
Computes the forward reachability of the given automaton.
void setInitialStates (std::vector< State > &&initialStates)
WorkQueue< TaskTypePtr > & rGetQueue ()
flowpipe_t computeForwardTimeClosure (const State &_state)
Computes the forward time closure (FTC) of the given valuation in the respective location.
bool reachedBadStates () const
Returns whether the bad states were reachable so far.
void processDiscreteBehaviour (const std::vector< std::tuple< Transition< Number > *, State >> &_newInitialSets)
Computes one time step and one discrete step, i.e. increases the depth of the search by one.
bool intersectGuard (Transition< Number > *_trans, const State &_segment, State &result) const
Checks, whether the passed transition is enabled by the passed valuation. Sets the result to be the intersection of the guard and the valuation.
bool checkTransitions (const State &_state, const carl::Interval< tNumber > &currentTime, std::vector< std::tuple< Transition< Number > *, State >> &nextInitialSets) const
const ReachabilitySettings & settings () const
void setSettings (const ReachabilitySettings &settings)
representation_name getRepresentationType () const
void setRepresentationType (const representation_name &type)
Private Member Functions
matrix_t< Number > computeTrafoMatrix (const Location< Number > *_loc) const
bool intersectBadStates (const State &_state) const
Private Attributes
HybridAutomaton< Number > mAutomaton
ReachabilitySettings mSettings
std::size_t mCurrentLevel = 0
Number mBloatingFactor = 0
std::map< unsigned, std::vector< flowpipe_t > > mReachableStates
WorkQueue< TaskTypePtr > mWorkingQueue
Plotter< Number > & plotter = Plotter<Number>::getInstance()
representation_name mType
bool mInitialStatesSet = false
bool mIntersectedBadStates
Detailed Description
template<typename Number, typename ReacherSettings, typename State>
class hypro::reachability::Reach< Number, ReacherSettings, State >
Class implementing a basic reachbility analysis algorithm for linear hybrid automata.
Template Parameters
Number The used number type.
Representation The used state set representation type.
Definition at line 59 of file Reach.h.
Member Typedef Documentation
template<typename Number, typename ReacherSettings, typename State> using hypro::reachability::Reach< Number, ReacherSettings, State >::flowpipe_t = std::vector<State>
Definition at line 63 of file Reach.h.
template<typename Number, typename ReacherSettings, typename State> using hypro::reachability::Reach< Number, ReacherSettings, State >::TaskType = std::pair<unsigned, State>
Definition at line 61 of file Reach.h.
template<typename Number, typename ReacherSettings, typename State> using hypro::reachability::Reach< Number, ReacherSettings, State >::TaskTypePtr = std::unique_ptr<TaskType>
Definition at line 62 of file Reach.h.
Constructor & Destructor Documentation
template<typename Number, typename ReacherSettings, typename State> hypro::reachability::Reach< Number, ReacherSettings, State >::Reach (const HybridAutomaton< Number > & _automaton, const ReachabilitySettings & _settings = ReachabilitySettings())
Constructor for a basic reachability analysis algorithm for linear hybrid automata.
Parameters
_automaton The analyzed automaton.
_settings The reachability analysis settings.
Member Function Documentation
template<typename Number, typename ReacherSettings, typename State> bool hypro::reachability::Reach< Number, ReacherSettings, State >::checkTransitions (const State & _state, const carl::Interval< tNumber > & currentTime, std::vector< std::tuple< Transition< Number > *, State >> & nextInitialSets) const
template<typename Number, typename ReacherSettings, typename State> std::vector<std::pair<unsigned, flowpipe_t> > hypro::reachability::Reach< Number, ReacherSettings, State >::computeForwardReachability ()
Computes the forward reachability of the given automaton.
Returns
The flowpipe as a result of this computation.
Referenced by main().
template<typename Number, typename ReacherSettings, typename State> flowpipe_t hypro::reachability::Reach< Number, ReacherSettings, State >::computeForwardTimeClosure (const State & _state)
Computes the forward time closure (FTC) of the given valuation in the respective location.
[long description]
Parameters
_loc The location in which the FTC is to be computed.
_val The valuation which is initial in the respective location.
Returns
The id of the computed flowpipe.
template<typename Number, typename ReacherSettings, typename State> matrix_t<Number> hypro::reachability::Reach< Number, ReacherSettings, State >::computeTrafoMatrix (const Location< Number > * _loc) const private
template<typename Number, typename ReacherSettings, typename State> representation_name hypro::reachability::Reach< Number, ReacherSettings, State >::getRepresentationType () const inline
Definition at line 141 of file Reach.h.
template<typename Number, typename ReacherSettings, typename State> bool hypro::reachability::Reach< Number, ReacherSettings, State >::intersectBadStates (const State & _state) const private
template<typename Number, typename ReacherSettings, typename State> bool hypro::reachability::Reach< Number, ReacherSettings, State >::intersectGuard (Transition< Number > * _trans, const State & _segment, State & result) const
Checks, whether the passed transition is enabled by the passed valuation. Sets the result to be the intersection of the guard and the valuation.
[long description]
Parameters
_trans The transition, which is to be enabled.
_val The valuation possibly enabling the passed transition.
result At the end of the method this holds the result of the intersection of the guard and the valuation.
Returns
True, if the transition is enabled, false otherwise.
template<typename Number, typename ReacherSettings, typename State> void hypro::reachability::Reach< Number, ReacherSettings, State >::processDiscreteBehaviour (const std::vector< std::tuple< Transition< Number > *, State >> & _newInitialSets)
Computes one time step and one discrete step, i.e. increases the depth of the search by one.
[long description]
Parameters
_init The initial valuations.
Returns
The resulting flowpipes.
template<typename Number, typename ReacherSettings, typename State> bool hypro::reachability::Reach< Number, ReacherSettings, State >::reachedBadStates () const inline
Returns whether the bad states were reachable so far.
[long description]
Returns
true, if the bad states were reachable.
Definition at line 114 of file Reach.h.
template<typename Number, typename ReacherSettings, typename State> WorkQueue<TaskTypePtr>& hypro::reachability::Reach< Number, ReacherSettings, State >::rGetQueue () inline
Definition at line 96 of file Reach.h.
template<typename Number, typename ReacherSettings, typename State> void hypro::reachability::Reach< Number, ReacherSettings, State >::setInitialStates (std::vector< State > && initialStates)
template<typename Number, typename ReacherSettings, typename State> void hypro::reachability::Reach< Number, ReacherSettings, State >::setRepresentationType (const representation_name & type) inline
Definition at line 142 of file Reach.h.
References hypro::reachability::computeTrafoMatrix().
Referenced by main().
template<typename Number, typename ReacherSettings, typename State> void hypro::reachability::Reach< Number, ReacherSettings, State >::setSettings (const ReachabilitySettings & settings) inline
Definition at line 139 of file Reach.h.
Referenced by main().
template<typename Number, typename ReacherSettings, typename State> const ReachabilitySettings& hypro::reachability::Reach< Number, ReacherSettings, State >::settings () const inline
Definition at line 138 of file Reach.h.
Referenced by main().
Member Data Documentation
template<typename Number, typename ReacherSettings, typename State> HybridAutomaton<Number> hypro::reachability::Reach< Number, ReacherSettings, State >::mAutomaton private
Definition at line 66 of file Reach.h.
template<typename Number, typename ReacherSettings, typename State> Number hypro::reachability::Reach< Number, ReacherSettings, State >::mBloatingFactor = 0 private
Definition at line 69 of file Reach.h.
template<typename Number, typename ReacherSettings, typename State> std::size_t hypro::reachability::Reach< Number, ReacherSettings, State >::mCurrentLevel = 0 private
Definition at line 68 of file Reach.h.
template<typename Number, typename ReacherSettings, typename State> bool hypro::reachability::Reach< Number, ReacherSettings, State >::mInitialStatesSet = false private
Definition at line 74 of file Reach.h.
template<typename Number, typename ReacherSettings, typename State> bool hypro::reachability::Reach< Number, ReacherSettings, State >::mIntersectedBadStates mutable private
Definition at line 76 of file Reach.h.
template<typename Number, typename ReacherSettings, typename State> std::map<unsigned, std::vector<flowpipe_t> > hypro::reachability::Reach< Number, ReacherSettings, State >::mReachableStates private
Definition at line 70 of file Reach.h.
template<typename Number, typename ReacherSettings, typename State> ReachabilitySettings hypro::reachability::Reach< Number, ReacherSettings, State >::mSettings private
Definition at line 67 of file Reach.h.
template<typename Number, typename ReacherSettings, typename State> representation_name hypro::reachability::Reach< Number, ReacherSettings, State >::mType private
Definition at line 73 of file Reach.h.
template<typename Number, typename ReacherSettings, typename State> WorkQueue<TaskTypePtr> hypro::reachability::Reach< Number, ReacherSettings, State >::mWorkingQueue private
Definition at line 71 of file Reach.h.
template<typename Number, typename ReacherSettings, typename State> Plotter<Number>& hypro::reachability::Reach< Number, ReacherSettings, State >::plotter = Plotter<Number>::getInstance() private
Definition at line 72 of file Reach.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/Reach.h