HyPro: hypro::SupportFunctionT< Number, Converter, Setting > Class Template Reference
hypro::SupportFunctionT< Number, Converter, Setting > Class Template Reference
State set representations
Class wrapping the support function content.
Public Types
typedef Setting Settings
typedef Number NumberType
Public Member Functions
SupportFunctionT ()
SupportFunctionT (const SupportFunctionT &_orig)
SupportFunctionT (SF_TYPE _type, Number _radius, unsigned dimension)
SupportFunctionT (const std::vector< Point< Number >> &_vertices)
SupportFunctionT (const matrix_t< Number > &_directions, const vector_t< Number > &_distances, bool overrideReduction=false)
SupportFunctionT (const std::vector< Halfspace< Number >> &_planes)
SupportFunctionT (SupportFunctionT &&other)
SupportFunctionT (const matrix_t< Number > &_shapeMatrix)
SupportFunctionT (const std::vector< carl::Interval< Number >> &inBox)
virtual ~SupportFunctionT ()
SupportFunctionT< Number, Converter, Setting > & operator= (SupportFunctionT< Number, Converter, Setting > _orig)
EvaluationResult< Number > evaluate (const vector_t< Number > &_direction, bool useExact=true) const
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &_directions, bool useExact=true) const
std::size_t dimension () const
std::size_t size () const
SF_TYPE sfType () const
unsigned depth () const
unsigned operationCount () const
sumContent< Number, Setting > * summands () const
scaleContent< Number, Setting > * scaleParameters () const
trafoContent< Number, Setting > * linearTrafoParameters () const
unionContent< Number, Setting > * unionParameters () const
intersectionContent< Number, Setting > * intersectionParameters () const
PolytopeSupportFunction< Number, Setting > * polytope () const
BallSupportFunction< Number > * ball () const
BoxSupportFunction< Number, Setting > * box () const
EllipsoidSupportFunction< Number > * ellipsoid () const
matrix_t< Number > matrix () const
vector_t< Number > vector () const
void removeRedundancy ()
void reduceNumberRepresentation ()
std::vector< Point< Number > > vertices (const matrix_t< Number > &=matrix_t< Number >::Zero(0, 0)) const
std::vector< Point< Number > > vertices (const std::vector< vector_t< Number >> &additionalDirections) const
Number supremum () const
SupportFunctionT project (const std::vector< std::size_t > &dimensions) const
SupportFunctionT assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const
SupportFunctionT linearTransformation (const matrix_t< Number > &A) const
SupportFunctionT affineTransformation (const matrix_t< Number > &A, const vector_t< Number > &b) const
SupportFunctionT minkowskiSum (const SupportFunctionT &_rhs) const
SupportFunctionT intersect (const SupportFunctionT &_rhs) const
SupportFunctionT intersectHalfspace (const Halfspace< Number > &hs) const
SupportFunctionT intersectHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const
bool contains (const Point< Number > &_point) const
bool contains (const vector_t< Number > &_point) const
bool contains (const SupportFunctionT &rhs) const
bool contains (const SupportFunctionT &rhs, std::size_t directions) const
SupportFunctionT unite (const SupportFunctionT &_rhs) const
SupportFunctionT scale (const Number &_factor=1) const
std::pair< CONTAINMENT, SupportFunctionT > satisfiesHalfspace (const Halfspace< Number > &rhs) const
std::pair< CONTAINMENT, SupportFunctionT > satisfiesHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const
void reduceRepresentation ()
Reduces the support function. This is Settings-dependent and can result in a templated evaluation.
bool empty () const
void print () const
void swap (SupportFunctionT &first, SupportFunctionT &second)
void forceLinTransReduction ()
unsigned multiplicationsPerEvaluation () const
void cleanUp () const
Cleans up optimizer context data when joining threads in a multithreaded environment. Used to avoid memory leaks when threads which created the support function are joined.
std::string getDotRepresentation () const
std::vector< std::size_t > collectProjections () const
const SupportFunctionT & evaluateTemplate (std::size_t directionCount=defaultTemplateDirectionCount, bool force=false) const
Static Public Member Functions
static representation_name type ()
static SupportFunctionT unite (const std::vector< SupportFunctionT > &_rhs)
Static Public Attributes
static constexpr auto type_enum = representation_name::support_function
Friends
std::ostream & operator<< (std::ostream &lhs, const SupportFunctionT< Number, Converter, Setting > &rhs)
bool operator== (const SupportFunctionT< Number, Converter, Setting > &lhs, const SupportFunctionT< Number, Converter, Setting > &rhs)
Detailed Description
template<typename Number, typename Converter, typename Setting>
class hypro::SupportFunctionT< Number, Converter, Setting >
Class wrapping the support function content.
Template Parameters
Number The used number type.
Converter The used converter. @{
Definition at line 38 of file PolytopeSupportFunction.h.
Member Typedef Documentation
template<typename Number, typename Converter, typename Setting> typedef Number hypro::SupportFunctionT< Number, Converter, Setting >::NumberType
Definition at line 26 of file SupportFunction.h.
template<typename Number, typename Converter, typename Setting> typedef Setting hypro::SupportFunctionT< Number, Converter, Setting >::Settings
Definition at line 25 of file SupportFunction.h.
Constructor & Destructor Documentation
template<typename Number , typename Converter , typename Setting > hypro::SupportFunctionT< Number, Converter, Setting >::SupportFunctionT ()
Definition at line 24 of file SupportFunction.tpp.
References hypro::GeometricObjectBase::GeometricObjectBase(), and hypro::SupportFunctionT< Number, Converter, Setting >::swap().
template<typename Number, typename Converter, typename Setting> hypro::SupportFunctionT< Number, Converter, Setting >::SupportFunctionT (const SupportFunctionT< Number, Converter, Setting > & _orig)
template<typename Number , typename Converter , typename Setting > hypro::SupportFunctionT< Number, Converter, Setting >::SupportFunctionT (SF_TYPE _type, Number _radius, unsigned dimension)
Definition at line 44 of file SupportFunction.tpp.
template<typename Number , typename Converter , typename Setting > hypro::SupportFunctionT< Number, Converter, Setting >::SupportFunctionT (const std::vector< Point< Number >> & _vertices)
Definition at line 50 of file SupportFunction.tpp.
template<typename Number , typename Converter , typename Setting > hypro::SupportFunctionT< Number, Converter, Setting >::SupportFunctionT (const matrix_t< Number > & _directions, const vector_t< Number > & _distances, bool overrideReduction = false)
Definition at line 56 of file SupportFunction.tpp.
template<typename Number , typename Converter , typename Setting > hypro::SupportFunctionT< Number, Converter, Setting >::SupportFunctionT (const std::vector< Halfspace< Number >> & _planes)
Definition at line 62 of file SupportFunction.tpp.
template<typename Number, typename Converter, typename Setting> hypro::SupportFunctionT< Number, Converter, Setting >::SupportFunctionT (SupportFunctionT< Number, Converter, Setting > && other)
template<typename Number , typename Converter , typename Setting > hypro::SupportFunctionT< Number, Converter, Setting >::SupportFunctionT (const matrix_t< Number > & _shapeMatrix)
Definition at line 68 of file SupportFunction.tpp.
template<typename Number , typename Converter , typename Setting > hypro::SupportFunctionT< Number, Converter, Setting >::SupportFunctionT (const std::vector< carl::Interval< Number >> & inBox)
Definition at line 74 of file SupportFunction.tpp.
template<typename Number , typename Converter , typename Setting > hypro::SupportFunctionT< Number, Converter, Setting >::~SupportFunctionT () virtual
Definition at line 81 of file SupportFunction.tpp.
Member Function Documentation
template<typename Number , typename Converter , typename Setting > SupportFunctionT< Number, Converter, Setting > hypro::SupportFunctionT< Number, Converter, Setting >::affineTransformation (const matrix_t< Number > & A, const vector_t< Number > & b) const
Definition at line 365 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals().
template<typename Number, typename Converter, typename Setting> SupportFunctionT hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const inline
Definition at line 83 of file SupportFunction.h.
References hypro::SupportFunctionT< Number, Converter, Setting >::affineTransformation(), hypro::SupportFunctionT< Number, Converter, Setting >::cleanUp(), hypro::SupportFunctionT< Number, Converter, Setting >::contains(), hypro::SupportFunctionT< Number, Converter, Setting >::empty(), hypro::SupportFunctionT< Number, Converter, Setting >::forceLinTransReduction(), hypro::SupportFunctionT< Number, Converter, Setting >::getDotRepresentation(), hypro::SupportFunctionT< Number, Converter, Setting >::intersect(), hypro::SupportFunctionT< Number, Converter, Setting >::intersectHalfspace(), hypro::SupportFunctionT< Number, Converter, Setting >::intersectHalfspaces(), hypro::SupportFunctionT< Number, Converter, Setting >::linearTransformation(), hypro::SupportFunctionT< Number, Converter, Setting >::minkowskiSum(), hypro::SupportFunctionT< Number, Converter, Setting >::multiplicationsPerEvaluation(), hypro::SupportFunctionT< Number, Converter, Setting >::print(), hypro::SupportFunctionT< Number, Converter, Setting >::reduceRepresentation(), hypro::SupportFunctionT< Number, Converter, Setting >::satisfiesHalfspace(), hypro::SupportFunctionT< Number, Converter, Setting >::satisfiesHalfspaces(), hypro::SupportFunctionT< Number, Converter, Setting >::scale(), hypro::SupportFunctionT< Number, Converter, Setting >::swap(), and hypro::SupportFunctionT< Number, Converter, Setting >::unite().
template<typename Number , typename Converter , typename Setting > BallSupportFunction< Number > * hypro::SupportFunctionT< Number, Converter, Setting >::ball () const
Definition at line 189 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > BoxSupportFunction< Number, Setting > * hypro::SupportFunctionT< Number, Converter, Setting >::box () const
Definition at line 194 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > void hypro::SupportFunctionT< Number, Converter, Setting >::cleanUp () const
Cleans up optimizer context data when joining threads in a multithreaded environment. Used to avoid memory leaks when threads which created the support function are joined.
Definition at line 139 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , typename Setting > std::vector< std::size_t > hypro::SupportFunctionT< Number, Converter, Setting >::collectProjections () const
Definition at line 658 of file SupportFunction.tpp.
template<typename Number , typename Converter , typename Setting > bool hypro::SupportFunctionT< Number, Converter, Setting >::contains (const Point< Number > & _point) const
Definition at line 401 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals(), hypro::computeBoundaryPointsExpensive(), hypro::computeBoundaryPointsExpensiveRecursive(), and hypro::SupportFunctionT< Number, Converter, Setting >::contains().
template<typename Number , typename Converter , typename Setting > bool hypro::SupportFunctionT< Number, Converter, Setting >::contains (const vector_t< Number > & _point) const
Definition at line 406 of file SupportFunction.tpp.
References hypro::SupportFunctionT< Number, Converter, Setting >::contains(), hypro::SupportFunctionT< Number, Converter, Setting >::dimension(), hypro::SupportFunctionT< Number, Converter, Setting >::evaluate(), and hypro::SupportFunctionT< Number, Converter, Setting >::unite().
template<typename Number, typename Converter, typename Setting> bool hypro::SupportFunctionT< Number, Converter, Setting >::contains (const SupportFunctionT< Number, Converter, Setting > & rhs) const
template<typename Number, typename Converter, typename Setting> bool hypro::SupportFunctionT< Number, Converter, Setting >::contains (const SupportFunctionT< Number, Converter, Setting > & rhs, std::size_t directions) const
template<typename Number , typename Converter , typename Setting > unsigned hypro::SupportFunctionT< Number, Converter, Setting >::depth () const
Definition at line 129 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > std::size_t hypro::SupportFunctionT< Number, Converter, Setting >::dimension () const
Definition at line 119 of file SupportFunction.tpp.
Referenced by hypro::computeBoundaryPointsExpensive(), hypro::computeBoundaryPointsExpensiveRecursive(), hypro::SupportFunctionT< Number, Converter, Setting >::contains(), hypro::SupportFunctionT< Number, Converter, Setting >::evaluateTemplate(), and hypro::SupportFunctionT< Number, Converter, Setting >::project().
template<typename Number , typename Converter , typename Setting > EllipsoidSupportFunction< Number > * hypro::SupportFunctionT< Number, Converter, Setting >::ellipsoid () const
Definition at line 199 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > bool hypro::SupportFunctionT< Number, Converter, Setting >::empty () const
Definition at line 634 of file SupportFunction.tpp.
References hypro::EMPTY, hypro::GeometricObjectBase::mEmptyState, hypro::NONEMPTY, hypro::UNIVERSAL, and hypro::UNKNOWN.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , typename Setting > EvaluationResult< Number > hypro::SupportFunctionT< Number, Converter, Setting >::evaluate (const vector_t< Number > & _direction, bool useExact = true) const
Definition at line 98 of file SupportFunction.tpp.
References hypro::EvaluationResult< Number >::supportValue.
Referenced by hypro::computeBoundaryPointsExpensive(), hypro::computeBoundaryPointsExpensiveRecursive(), and hypro::SupportFunctionT< Number, Converter, Setting >::contains().
template<typename Number , typename Converter , typename Setting > const SupportFunctionT< Number, Converter, Setting > & hypro::SupportFunctionT< Number, Converter, Setting >::evaluateTemplate (std::size_t directionCount = defaultTemplateDirectionCount, bool force = false) const
Definition at line 664 of file SupportFunction.tpp.
References hypro::SupportFunctionT< Number, Converter, Setting >::dimension(), hypro::INFTY, and hypro::SupportFunctionT< Number, Converter, Setting >::multiEvaluate().
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::matrix(), hypro::SupportFunctionT< Number, Converter, Setting >::reduceRepresentation(), and hypro::SupportFunctionT< Number, Converter, Setting >::vector().
template<typename Number , typename Converter , typename Setting > void hypro::SupportFunctionT< Number, Converter, Setting >::forceLinTransReduction ()
forces the topmost chain of linear transformations to be reduced to a single lin.trans
Returns
reduced SF
Definition at line 653 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , typename Setting > std::string hypro::SupportFunctionT< Number, Converter, Setting >::getDotRepresentation () const
Definition at line 144 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals().
template<typename Number, typename Converter, typename Setting> SupportFunctionT< Number, Converter, Setting > hypro::SupportFunctionT< Number, Converter, Setting >::intersect (const SupportFunctionT< Number, Converter, Setting > & _rhs) const
Definition at line 377 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals(), hypro::computeBoundaryPointsExpensive(), and hypro::computeBoundaryPointsExpensiveRecursive().
template<typename Number , typename Converter , typename Setting > SupportFunctionT< Number, Converter, Setting > hypro::SupportFunctionT< Number, Converter, Setting >::intersectHalfspace (const Halfspace< Number > & hs) const
Definition at line 383 of file SupportFunction.tpp.
References hypro::Halfspace< Number >::normal(), and hypro::Halfspace< Number >::offset().
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals(), and hypro::SupportFunctionT< Number, Converter, Setting >::satisfiesHalfspace().
template<typename Number , typename Converter , typename Setting > SupportFunctionT< Number, Converter, Setting > hypro::SupportFunctionT< Number, Converter, Setting >::intersectHalfspaces (const matrix_t< Number > & _mat, const vector_t< Number > & _vec) const
Definition at line 395 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals(), and hypro::SupportFunctionT< Number, Converter, Setting >::satisfiesHalfspaces().
template<typename Number , typename Converter , typename Setting > intersectionContent< Number, Setting > * hypro::SupportFunctionT< Number, Converter, Setting >::intersectionParameters () const
Definition at line 179 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > trafoContent< Number, Setting > * hypro::SupportFunctionT< Number, Converter, Setting >::linearTrafoParameters () const
Definition at line 164 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > SupportFunctionT< Number, Converter, Setting > hypro::SupportFunctionT< Number, Converter, Setting >::linearTransformation (const matrix_t< Number > & A) const
Definition at line 359 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , typename Setting > matrix_t< Number > hypro::SupportFunctionT< Number, Converter, Setting >::matrix () const
Definition at line 204 of file SupportFunction.tpp.
References hypro::SupportFunctionT< Number, Converter, Setting >::evaluateTemplate().
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::type().
template<typename Number, typename Converter, typename Setting> SupportFunctionT< Number, Converter, Setting > hypro::SupportFunctionT< Number, Converter, Setting >::minkowskiSum (const SupportFunctionT< Number, Converter, Setting > & _rhs) const
Definition at line 371 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , typename Setting > std::vector< EvaluationResult< Number > > hypro::SupportFunctionT< Number, Converter, Setting >::multiEvaluate (const matrix_t< Number > & _directions, bool useExact = true) const
Definition at line 107 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::evaluateTemplate().
template<typename Number , typename Converter , typename Setting > unsigned hypro::SupportFunctionT< Number, Converter, Setting >::multiplicationsPerEvaluation () const
Returns
number of mv multiplications needed for a single evaluation on the SF
Definition at line 134 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , typename Setting > unsigned hypro::SupportFunctionT< Number, Converter, Setting >::operationCount () const
Definition at line 154 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > SupportFunctionT< Number, Converter, Setting > & hypro::SupportFunctionT< Number, Converter, Setting >::operator= (SupportFunctionT< Number, Converter, Setting > _orig)
Definition at line 87 of file SupportFunction.tpp.
References hypro::SupportFunctionT< Number, Converter, Setting >::swap().
template<typename Number , typename Converter , typename Setting > PolytopeSupportFunction< Number, Setting > * hypro::SupportFunctionT< Number, Converter, Setting >::polytope () const
Definition at line 184 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > void hypro::SupportFunctionT< Number, Converter, Setting >::print () const
Definition at line 643 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals(), hypro::computeBoundaryPointsExpensive(), and hypro::computeBoundaryPointsExpensiveRecursive().
template<typename Number , typename Converter , typename Setting > SupportFunctionT< Number, Converter, Setting > hypro::SupportFunctionT< Number, Converter, Setting >::project (const std::vector< std::size_t > & dimensions) const
Definition at line 335 of file SupportFunction.tpp.
References hypro::SupportFunctionT< Number, Converter, Setting >::dimension().
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::reduceNumberRepresentation().
template<typename Number, typename Converter, typename Setting> void hypro::SupportFunctionT< Number, Converter, Setting >::reduceNumberRepresentation () inline
Definition at line 78 of file SupportFunction.h.
References hypro::SupportFunctionT< Number, Converter, Setting >::project(), hypro::SupportFunctionT< Number, Converter, Setting >::supremum(), and hypro::SupportFunctionT< Number, Converter, Setting >::vertices().
template<typename Number , typename Converter , typename Setting > void hypro::SupportFunctionT< Number, Converter, Setting >::reduceRepresentation ()
Reduces the support function. This is Settings-dependent and can result in a templated evaluation.
Definition at line 621 of file SupportFunction.tpp.
References hypro::BOX, hypro::SupportFunctionT< Number, Converter, Setting >::evaluateTemplate(), and hypro::POLY.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , typename Setting > void hypro::SupportFunctionT< Number, Converter, Setting >::removeRedundancy ()
Definition at line 220 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > std::pair< CONTAINMENT, SupportFunctionT< Number, Converter, Setting > > hypro::SupportFunctionT< Number, Converter, Setting >::satisfiesHalfspace (const Halfspace< Number > & rhs) const
Definition at line 452 of file SupportFunction.tpp.
References hypro::EvaluationResult< Number >::errorCode, hypro::FULL, hypro::INFEAS, hypro::SupportFunctionT< Number, Converter, Setting >::intersectHalfspace(), hypro::NO, hypro::Halfspace< Number >::normal(), hypro::Halfspace< Number >::offset(), hypro::PARTIAL, hypro::EvaluationResult< Number >::supportValue, and hypro::Converter< Number >::toHPolytope().
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , typename Setting > std::pair< CONTAINMENT, SupportFunctionT< Number, Converter, Setting > > hypro::SupportFunctionT< Number, Converter, Setting >::satisfiesHalfspaces (const matrix_t< Number > & _mat, const vector_t< Number > & _vec) const
Definition at line 490 of file SupportFunction.tpp.
References hypro::appendRow(), hypro::EvaluationResult< Number >::errorCode, hypro::FULL, hypro::INFEAS, hypro::SupportFunctionT< Number, Converter, Setting >::intersectHalfspaces(), hypro::NO, hypro::PARTIAL, hypro::intersectionContent< Number, Setting >::rhs, and hypro::EvaluationResult< Number >::supportValue.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , typename Setting > SupportFunctionT< Number, Converter, Setting > hypro::SupportFunctionT< Number, Converter, Setting >::scale (const Number & _factor = 1) const
Definition at line 447 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , typename Setting > scaleContent< Number, Setting > * hypro::SupportFunctionT< Number, Converter, Setting >::scaleParameters () const
Definition at line 169 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > SF_TYPE hypro::SupportFunctionT< Number, Converter, Setting >::sfType () const
Definition at line 124 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::type().
template<typename Number, typename Converter, typename Setting> std::size_t hypro::SupportFunctionT< Number, Converter, Setting >::size () const inline
Definition at line 57 of file SupportFunction.h.
template<typename Number , typename Converter , typename Setting > sumContent< Number, Setting > * hypro::SupportFunctionT< Number, Converter, Setting >::summands () const
Definition at line 159 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > Number hypro::SupportFunctionT< Number, Converter, Setting >::supremum () const
Definition at line 329 of file SupportFunction.tpp.
References hypro::Point< Number >::inftyNorm().
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::reduceNumberRepresentation().
template<typename Number, typename Converter, typename Setting> void hypro::SupportFunctionT< Number, Converter, Setting >::swap (SupportFunctionT< Number, Converter, Setting > & first, SupportFunctionT< Number, Converter, Setting > & second)
Definition at line 648 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals(), hypro::SupportFunctionT< Number, Converter, Setting >::operator=(), and hypro::SupportFunctionT< Number, Converter, Setting >::SupportFunctionT().
template<typename Number, typename Converter, typename Setting> static representation_name hypro::SupportFunctionT< Number, Converter, Setting >::type () inline static
Definition at line 58 of file SupportFunction.h.
References hypro::SupportFunctionT< Number, Converter, Setting >::ball(), hypro::SupportFunctionT< Number, Converter, Setting >::box(), hypro::SupportFunctionT< Number, Converter, Setting >::depth(), hypro::SupportFunctionT< Number, Converter, Setting >::ellipsoid(), hypro::SupportFunctionT< Number, Converter, Setting >::intersectionParameters(), hypro::SupportFunctionT< Number, Converter, Setting >::linearTrafoParameters(), hypro::SupportFunctionT< Number, Converter, Setting >::matrix(), hypro::SupportFunctionT< Number, Converter, Setting >::operationCount(), hypro::SupportFunctionT< Number, Converter, Setting >::polytope(), hypro::SupportFunctionT< Number, Converter, Setting >::removeRedundancy(), hypro::SupportFunctionT< Number, Converter, Setting >::scaleParameters(), hypro::SupportFunctionT< Number, Converter, Setting >::sfType(), hypro::SupportFunctionT< Number, Converter, Setting >::summands(), hypro::SupportFunctionT< Number, Converter, Setting >::unionParameters(), and hypro::SupportFunctionT< Number, Converter, Setting >::vector().
template<typename Number , typename Converter , typename Setting > unionContent< Number, Setting > * hypro::SupportFunctionT< Number, Converter, Setting >::unionParameters () const
Definition at line 174 of file SupportFunction.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::type().
template<typename Number, typename Converter, typename Setting> SupportFunctionT hypro::SupportFunctionT< Number, Converter, Setting >::unite (const SupportFunctionT< Number, Converter, Setting > & _rhs) const
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals(), and hypro::SupportFunctionT< Number, Converter, Setting >::contains().
template<typename Number, typename Converter, typename Setting> static SupportFunctionT hypro::SupportFunctionT< Number, Converter, Setting >::unite (const std::vector< SupportFunctionT< Number, Converter, Setting > > & _rhs) static
template<typename Number , typename Converter , typename Setting > vector_t< Number > hypro::SupportFunctionT< Number, Converter, Setting >::vector () const
Definition at line 212 of file SupportFunction.tpp.
References hypro::SupportFunctionT< Number, Converter, Setting >::evaluateTemplate().
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > std::vector< Point< Number > > hypro::SupportFunctionT< Number, Converter, Setting >::vertices (const matrix_t< Number > & additionalDirections = matrix_t<Number>::Zero(0, 0)) const
Definition at line 225 of file SupportFunction.tpp.
References hypro::Converter< Number >::toHPolytope().
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::reduceNumberRepresentation().
template<typename Number , typename Converter , typename Setting > std::vector< Point< Number > > hypro::SupportFunctionT< Number, Converter, Setting >::vertices (const std::vector< vector_t< Number >> & additionalDirections) const
Definition at line 323 of file SupportFunction.tpp.
References hypro::Converter< Number >::toHPolytope().
Friends And Related Function Documentation
template<typename Number, typename Converter, typename Setting> std::ostream& operator<< (std::ostream & lhs, const SupportFunctionT< Number, Converter, Setting > & rhs) friend
Definition at line 130 of file SupportFunction.h.
template<typename Number, typename Converter, typename Setting> bool operator== (const SupportFunctionT< Number, Converter, Setting > & lhs, const SupportFunctionT< Number, Converter, Setting > & rhs) friend
Definition at line 137 of file SupportFunction.h.
Member Data Documentation
template<typename Number, typename Converter, typename Setting> constexpr auto hypro::SupportFunctionT< Number, Converter, Setting >::type_enum = representation_name::support_function static
Definition at line 27 of file SupportFunction.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunction/PolytopeSupportFunction.h
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunction/SupportFunction.h
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunction/SupportFunction.tpp