HyPro: hypro::HPolytopeT< Number, Converter, Setting > Class Template Reference
hypro::HPolytopeT< Number, Converter, Setting > Class Template Reference
State set representations
Class for a H-polytope.
Public Types
enum REDUCTION_STRATEGY {
DROP = 0, DROP_SMOOTH, UNITE, UNITE_SMOOTH,
UNITE_CUT, UNITE_NORM, DIRECTED_SMALL, DIRECTED_BIG,
DIRECTED_TEMPLATE
}
using HalfspaceVector = std::vector< Halfspace< Number >>
typedef Setting Settings
typedef Number NumberType
Public Member Functions
HPolytopeT ()
Constructor for the universal H-polytope.
HPolytopeT (const HPolytopeT &orig)
Copy constructor.
HPolytopeT (const HalfspaceVector &planes)
Constructor from a vector of halfspaces.
HPolytopeT (const matrix_t< Number > &A, const vector_t< Number > &b)
Constructor from a matrix and a vector.
HPolytopeT (const matrix_t< Number > &A)
Constructor from a matrix.
HPolytopeT (const std::vector< Point< Number >> &points)
Constructor from a vector of points.
template<typename SettingRhs , carl::DisableIf< std::is_same< Setting, SettingRhs >> = carl::dummy>
HPolytopeT (const HPolytopeT< Number, Converter, SettingRhs > &orig)
~HPolytopeT ()
Destructor.
double sizeOfHPolytopeT () const
Approximates the storage usage of the current polytope.
bool empty () const
Determines, if the polytope is empty.
std::size_t dimension () const
Getter for the dimension of the polytope.
std::size_t size () const
Getter for the number of constraints.
void unreduce () const
Resets the information if the current polytope contains redundant constraints.
void setReduced () const
Manually sets the polytope to behave as if it did not contain redundant constraints.
bool isNonRedundant () const
Returns, whether the current polytope contains redundant constraints.
matrix_t< Number > matrix () const
Getter for the matrix representation of the constraints.
vector_t< Number > vector () const
Getter for the vector of offsets of the bounding hyperplanes.
std::pair< matrix_t< Number >, vector_t< Number > > inequalities () const
Getter for the full description of the polytope as a pair of a matrix and a vector.
std::vector< Point< Number > > vertices (const matrix_t< Number > &=matrix_t< Number >::Zero(0, 0)) const
Getter for the vertices of the current polytope.
Number supremum () const
Getter for a number representing the supremum according to the infinity norm of the polytope.
void insert (const Halfspace< Number > &plane)
Inserts an additional bounding halfspace into the polytope.
void insert (const typename HalfspaceVector::iterator begin, const typename HalfspaceVector::iterator end)
Inserts a range of halfspaces into the current polytope.
void erase (const unsigned index)
Removes the constraint at position index.
const HalfspaceVector & constraints () const
bool hasConstraint (const Halfspace< Number > &hplane) const
const HPolytopeT & removeRedundancy ()
HPolytopeT heuristic () const
HPolytopeT reduce (unsigned facet=1, unsigned facet2=0, REDUCTION_STRATEGY strat=REDUCTION_STRATEGY::DROP) const
HPolytopeT reduce_directed (std::vector< vector_t< Number >> directions, REDUCTION_STRATEGY strat=REDUCTION_STRATEGY::DIRECTED_SMALL) const
void reduceAssign (unsigned _steps=1, REDUCTION_STRATEGY strat=REDUCTION_STRATEGY::DROP)
bool isBounded (std::vector< vector_t< Number >>) const
bool isExtremePoint (const vector_t< Number > &point) const
bool isExtremePoint (const Point< Number > &point) const
EvaluationResult< Number > evaluate (const vector_t< Number > &_direction) const
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &_direction) const
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &_directions, bool useExact) const
std::vector< Point< Number > > vertexEnumeration () const
std::pair< CONTAINMENT, HPolytopeT > satisfiesHalfspace (const Halfspace< Number > &rhs) const
std::pair< CONTAINMENT, HPolytopeT > satisfiesHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const
HPolytopeT project (const std::vector< std::size_t > &dimensions) const
HPolytopeT assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const
HPolytopeT linearTransformation (const matrix_t< Number > &A) const
HPolytopeT affineTransformation (const matrix_t< Number > &A, const vector_t< Number > &b) const
HPolytopeT minkowskiSum (const HPolytopeT &rhs) const
HPolytopeT intersect (const HPolytopeT &rhs) const
HPolytopeT intersectHalfspace (const Halfspace< Number > &rhs) const
HPolytopeT intersectHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const
bool contains (const Point< Number > &point) const
bool contains (const vector_t< Number > &vec) const
bool contains (const HPolytopeT &rhs) const
HPolytopeT unite (const HPolytopeT &rhs) const
void reduceRepresentation ()
void clear ()
void print () const
HPolytopeT & operator= (const HPolytopeT< Number, Converter, Setting > &rhs)
bool operator== (const HPolytopeT< Number, Converter, Setting > &rhs) const
template<typename N = Number, carl::DisableIf< std::is_same< N, double >> = carl::dummy>
void reduceNumberRepresentation (const std::vector< Point< Number >> &_vertices=std::vector< Point< Number >>(), unsigned limit=fReach_DENOMINATOR) const
template<typename N = Number, carl::EnableIf< std::is_same< N, double >> = carl::dummy>
void reduceNumberRepresentation (const std::vector< Point< double >> &=std::vector< Point< double >>(), unsigned=fReach_DENOMINATOR) const
std::optional< Optimizer< Number > > & getOptimizer () const
void setOptimizer (const matrix_t< Number > &mat=matrix_t< Number >::Zero(1, 1), const vector_t< Number > &vec=vector_t< Number >::Zero(1)) const
void setUpdated (const bool &b)
bool getUpdated () const
Static Public Member Functions
static HPolytopeT< Number, Converter, Setting > Empty ()
Static method for construction of an empty H-polytope.
static representation_name type ()
static HPolytopeT unite (const std::vector< HPolytopeT > &rhs)
Static Public Attributes
static constexpr auto type_enum = representation_name::polytope_h
Friends
std::ostream & operator<< (std::ostream &lhs, const HPolytopeT< Number, Converter, Setting > &rhs)
void swap (HPolytopeT &a, HPolytopeT &b)
Detailed Description
template<typename Number, typename Converter, class Setting>
class hypro::HPolytopeT< Number, Converter, Setting >
Class for a H-polytope.
Template Parameters
Number The used number type.
Converter The used converter. @{
Definition at line 36 of file HPolytope.h.
Member Typedef Documentation
template<typename Number, typename Converter, class Setting> using hypro::HPolytopeT< Number, Converter, Setting >::HalfspaceVector = std::vector<Halfspace<Number>>
Definition at line 50 of file HPolytope.h.
template<typename Number, typename Converter, class Setting> typedef Number hypro::HPolytopeT< Number, Converter, Setting >::NumberType
Definition at line 53 of file HPolytope.h.
template<typename Number, typename Converter, class Setting> typedef Setting hypro::HPolytopeT< Number, Converter, Setting >::Settings
Definition at line 52 of file HPolytope.h.
Member Enumeration Documentation
template<typename Number, typename Converter, class Setting> enum hypro::HPolytopeT::REDUCTION_STRATEGY
Enumerator
DROP
DROP_SMOOTH
UNITE
UNITE_SMOOTH
UNITE_CUT
UNITE_NORM
DIRECTED_SMALL
DIRECTED_BIG
DIRECTED_TEMPLATE
Definition at line 38 of file HPolytope.h.
Constructor & Destructor Documentation
template<typename Number , typename Converter , class Setting > hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT ()
Constructor for the universal H-polytope.
Definition at line 5 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::setOptimizer().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::unite().
template<typename Number , typename Converter , class Setting > hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT (const HPolytopeT< Number, Converter, Setting > & orig)
Copy constructor.
Parameters
orig Original H-polytope.
Definition at line 16 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::getOptimizer(), hypro::HPolytopeT< Number, Converter, Setting >::matrix(), hypro::HPolytopeT< Number, Converter, Setting >::setOptimizer(), and hypro::HPolytopeT< Number, Converter, Setting >::vector().
template<typename Number , typename Converter , class Setting > hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT (const HalfspaceVector & planes)
Constructor from a vector of halfspaces.
The resulting object is the intersection of the given halfspaces, i.e. the conjunction of the linear constraints representing the halfspaces.
Parameters
planes A vector of halfspaces.
Definition at line 27 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::empty(), hypro::HPolytopeT< Number, Converter, Setting >::matrix(), hypro::HPolytopeT< Number, Converter, Setting >::reduceNumberRepresentation(), hypro::HPolytopeT< Number, Converter, Setting >::setOptimizer(), and hypro::HPolytopeT< Number, Converter, Setting >::vector().
template<typename Number, typename Converter , class Setting > hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT (const matrix_t< Number > & A, const vector_t< Number > & b)
Constructor from a matrix and a vector.
Each row in the matrix is considered to represent a constraint, i.e. a normal to a bounding hyperplane. Each corresponding entry in the passed vector is the offset of that plane, i.e. the constant part of the linear constraint.
Parameters
A A matrix.
b A vector.
Definition at line 52 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::empty(), hypro::HPolytopeT< Number, Converter, Setting >::reduceNumberRepresentation(), and hypro::HPolytopeT< Number, Converter, Setting >::setOptimizer().
template<typename Number, typename Converter , class Setting > hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT (const matrix_t< Number > & A)
Constructor from a matrix.
Each row in the matrix is considered to represent a constraint, i.e. a normal to a bounding hyperplane. The offset of each plane is considered to be 0, i.e. if the number of affinely independent constraints is larger or equal to d+1, the resulting polytope represents the origin point.
Parameters
A A matrix.
Definition at line 73 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::setOptimizer().
template<typename Number, typename Converter , class Setting > hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT (const std::vector< Point< Number >> & points)
Constructor from a vector of points.
Converts a vertex-representation into a hyperplanar representation, i.e. solving the plane enumeration problem.
Parameters
points A vector of points.
Definition at line 86 of file HPolytope.tpp.
References hypro::Point< Number >::at(), hypro::Point< Number >::coeffWiseMax(), hypro::Point< Number >::coeffWiseMin(), hypro::Halfspace< Number >::computePlaneNormal(), hypro::Halfspace< Number >::computePlaneOffset(), hypro::HPolytopeT< Number, Converter, Setting >::dimension(), hypro::Point< Number >::dimension(), hypro::effectiveDimension(), hypro::EMPTY, hypro::HPolytopeT< Number, Converter, Setting >::insert(), hypro::HPolytopeT< Number, Converter, Setting >::matrix(), hypro::GeometricObjectBase::mEmptyState, hypro::NONEMPTY, hypro::HPolytopeT< Number, Converter, Setting >::setOptimizer(), and hypro::HPolytopeT< Number, Converter, Setting >::vector().
template<typename Number, typename Converter, class Setting > template<typename SettingRhs , carl::DisableIf< std::is_same< Setting, SettingRhs >> > hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT (const HPolytopeT< Number, Converter, SettingRhs > & orig)
Definition at line 288 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::getOptimizer(), hypro::HPolytopeT< Number, Converter, Setting >::matrix(), hypro::HPolytopeT< Number, Converter, Setting >::setOptimizer(), and hypro::HPolytopeT< Number, Converter, Setting >::vector().
template<typename Number , typename Converter , class Setting > hypro::HPolytopeT< Number, Converter, Setting >::~HPolytopeT ()
Destructor.
Definition at line 298 of file HPolytope.tpp.
Member Function Documentation
template<typename Number, typename Converter , class Setting > HPolytopeT< Number, Converter, Setting > hypro::HPolytopeT< Number, Converter, Setting >::affineTransformation (const matrix_t< Number > & A, const vector_t< Number > & b) const
Definition at line 854 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::empty(), hypro::HPolytopeT< Number, Converter, Setting >::inequalities(), hypro::HPolytopeT< Number, Converter, Setting >::size(), hypro::Converter< Number >::toHPolytope(), and hypro::Converter< Number >::toVPolytope().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::assignIntervals().
template<typename Number, typename Converter, class Setting> HPolytopeT hypro::HPolytopeT< Number, Converter, Setting >::assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const inline
Definition at line 259 of file HPolytope.h.
References hypro::HPolytopeT< Number, Converter, Setting >::affineTransformation(), hypro::HPolytopeT< Number, Converter, Setting >::contains(), hypro::HPolytopeT< Number, Converter, Setting >::intersect(), hypro::HPolytopeT< Number, Converter, Setting >::intersectHalfspace(), hypro::HPolytopeT< Number, Converter, Setting >::intersectHalfspaces(), hypro::HPolytopeT< Number, Converter, Setting >::linearTransformation(), hypro::HPolytopeT< Number, Converter, Setting >::minkowskiSum(), and hypro::HPolytopeT< Number, Converter, Setting >::unite().
template<typename Number , typename Converter , class Setting > void hypro::HPolytopeT< Number, Converter, Setting >::clear ()
Definition at line 1109 of file HPolytope.tpp.
References hypro::GeometricObjectBase::mEmptyState, and hypro::UNIVERSAL.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , class Setting > const HPolytopeT< Number, Converter, Setting >::HalfspaceVector & hypro::HPolytopeT< Number, Converter, Setting >::constraints () const
Definition at line 630 of file HPolytope.tpp.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::contains(), hypro::HPolytopeT< Number, Converter, Setting >::intersect(), hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), hypro::HPolytopeT< Number, Converter, Setting >::minkowskiSum(), hypro::HPolytopeT< Number, Converter, Setting >::operator=(), hypro::HPolytopeT< Number, Converter, Setting >::operator==(), hypro::HPolytopeT< Number, Converter, Setting >::reduce(), and hypro::HPolytopeT< Number, Converter, Setting >::reduce_directed().
template<typename Number, typename Converter , class Setting > bool hypro::HPolytopeT< Number, Converter, Setting >::contains (const Point< Number > & point) const
Definition at line 970 of file HPolytope.tpp.
References hypro::Point< Number >::rawCoordinates().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::assignIntervals(), hypro::HPolytopeT< Number, Converter, Setting >::contains(), hypro::HPolytopeT< Number, Converter, Setting >::reduce_directed(), and hypro::HPolytopeT< Number, Converter, Setting >::reduceNumberRepresentation().
template<typename Number, typename Converter , class Setting > bool hypro::HPolytopeT< Number, Converter, Setting >::contains (const vector_t< Number > & vec) const
Definition at line 978 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::constraints(), hypro::HPolytopeT< Number, Converter, Setting >::contains(), hypro::HPolytopeT< Number, Converter, Setting >::empty(), hypro::EvaluationResult< Number >::errorCode, hypro::HPolytopeT< Number, Converter, Setting >::evaluate(), hypro::FEAS, hypro::INFEAS, hypro::INFTY, and hypro::EvaluationResult< Number >::supportValue.
template<typename Number, typename Converter, class Setting> bool hypro::HPolytopeT< Number, Converter, Setting >::contains (const HPolytopeT< Number, Converter, Setting > & rhs) const
template<typename Number , typename Converter , class Setting > std::size_t hypro::HPolytopeT< Number, Converter, Setting >::dimension () const
Getter for the dimension of the polytope.
Note that this only returns the space dimension and not the effective dimension of the polytope.
Returns
The space dimension.
Definition at line 352 of file HPolytope.tpp.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT(), hypro::HPolytopeT< Number, Converter, Setting >::inequalities(), hypro::HPolytopeT< Number, Converter, Setting >::matrix(), hypro::HPolytopeT< Number, Converter, Setting >::multiEvaluate(), hypro::HPolytopeT< Number, Converter, Setting >::operator=(), hypro::HPolytopeT< Number, Converter, Setting >::operator==(), hypro::HPolytopeT< Number, Converter, Setting >::project(), hypro::HPolytopeT< Number, Converter, Setting >::sizeOfHPolytopeT(), hypro::HPolytopeT< Number, Converter, Setting >::unite(), and hypro::HPolytopeT< Number, Converter, Setting >::vertices().
template<typename Number , typename Converter , class Setting > bool hypro::HPolytopeT< Number, Converter, Setting >::empty () const
Determines, if the polytope is empty.
Checks for satisfiability of the given constraints.
Returns
True if the polytope is empty, false otherwise.
Definition at line 306 of file HPolytope.tpp.
References hypro::Optimizer< Number >::checkConsistency(), hypro::EMPTY, hypro::HPolytopeT< Number, Converter, Setting >::matrix(), hypro::GeometricObjectBase::mEmptyState, hypro::NONEMPTY, hypro::Optimizer< Number >::setMatrix(), hypro::HPolytopeT< Number, Converter, Setting >::setOptimizer(), hypro::Optimizer< Number >::setVector(), hypro::UNIVERSAL, and hypro::HPolytopeT< Number, Converter, Setting >::vector().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::affineTransformation(), hypro::HPolytopeT< Number, Converter, Setting >::contains(), hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT(), hypro::HPolytopeT< Number, Converter, Setting >::intersect(), hypro::HPolytopeT< Number, Converter, Setting >::linearTransformation(), hypro::HPolytopeT< Number, Converter, Setting >::reduceNumberRepresentation(), hypro::HPolytopeT< Number, Converter, Setting >::satisfiesHalfspace(), hypro::HPolytopeT< Number, Converter, Setting >::satisfiesHalfspaces(), hypro::HPolytopeT< Number, Converter, Setting >::sizeOfHPolytopeT(), hypro::HPolytopeT< Number, Converter, Setting >::supremum(), hypro::HPolytopeT< Number, Converter, Setting >::unite(), and hypro::HPolytopeT< Number, Converter, Setting >::vertices().
template<typename Number , typename Converter , class Setting > HPolytopeT< Number, Converter, Setting > hypro::HPolytopeT< Number, Converter, Setting >::Empty () static
Static method for construction of an empty H-polytope.
An empty H-polytope is constructed by creating two hyperplanes which falsify each other.
Returns
An empty polytope.
Definition at line 344 of file HPolytope.tpp.
References hypro::EMPTY, and hypro::GeometricObjectBase::setEmptyState().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::intersect(), hypro::HPolytopeT< Number, Converter, Setting >::linearTransformation(), hypro::HPolytopeT< Number, Converter, Setting >::minkowskiSum(), hypro::HPolytopeT< Number, Converter, Setting >::project(), and hypro::HPolytopeT< Number, Converter, Setting >::sizeOfHPolytopeT().
template<typename Number , typename Converter , class Setting > void hypro::HPolytopeT< Number, Converter, Setting >::erase (const unsigned index)
Removes the constraint at position index.
Parameters
index An index.
Definition at line 620 of file HPolytope.tpp.
References hypro::EMPTY, hypro::GeometricObjectBase::mEmptyState, hypro::GeometricObjectBase::setEmptyState(), and hypro::UNKNOWN.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), hypro::HPolytopeT< Number, Converter, Setting >::reduce(), and hypro::HPolytopeT< Number, Converter, Setting >::reduce_directed().
template<typename Number, typename Converter , class Setting > EvaluationResult< Number > hypro::HPolytopeT< Number, Converter, Setting >::evaluate (const vector_t< Number > & _direction) const
Definition at line 702 of file HPolytope.tpp.
References hypro::Optimizer< Number >::evaluate(), hypro::HPolytopeT< Number, Converter, Setting >::matrix(), hypro::Optimizer< Number >::setMatrix(), hypro::HPolytopeT< Number, Converter, Setting >::setOptimizer(), hypro::Optimizer< Number >::setVector(), and hypro::HPolytopeT< Number, Converter, Setting >::vector().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::contains(), hypro::HPolytopeT< Number, Converter, Setting >::intersectHalfspace(), hypro::HPolytopeT< Number, Converter, Setting >::isBounded(), hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), hypro::HPolytopeT< Number, Converter, Setting >::minkowskiSum(), hypro::HPolytopeT< Number, Converter, Setting >::multiEvaluate(), and hypro::HPolytopeT< Number, Converter, Setting >::unite().
template<typename Number, typename Converter, class Setting> std::optional<Optimizer<Number> >& hypro::HPolytopeT< Number, Converter, Setting >::getOptimizer () const inline
Definition at line 443 of file HPolytope.h.
References hypro::HPolytopeT< Number, Converter, Setting >::setOptimizer().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT(), and hypro::HPolytopeT< Number, Converter, Setting >::operator=().
template<typename Number, typename Converter, class Setting> bool hypro::HPolytopeT< Number, Converter, Setting >::getUpdated () const inline
Definition at line 446 of file HPolytope.h.
template<typename Number, typename Converter , class Setting > bool hypro::HPolytopeT< Number, Converter, Setting >::hasConstraint (const Halfspace< Number > & hplane) const
Definition at line 635 of file HPolytope.tpp.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), hypro::HPolytopeT< Number, Converter, Setting >::satisfiesHalfspace(), and hypro::HPolytopeT< Number, Converter, Setting >::satisfiesHalfspaces().
template<typename Number , typename Converter , class Setting > HPolytopeT< Number, Converter, Setting > hypro::HPolytopeT< Number, Converter, Setting >::heuristic () const
Definition at line 243 of file reduction.tpp.
References hypro::Permutator::end(), and hypro::UNITE.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant().
template<typename Number , typename Converter , class Setting > std::pair< matrix_t< Number >, vector_t< Number > > hypro::HPolytopeT< Number, Converter, Setting >::inequalities () const
Getter for the full description of the polytope as a pair of a matrix and a vector.
Returns
A pair of a matrix and a vector.
Definition at line 384 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::dimension().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::affineTransformation(), hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), and hypro::HPolytopeT< Number, Converter, Setting >::linearTransformation().
template<typename Number, typename Converter , class Setting > void hypro::HPolytopeT< Number, Converter, Setting >::insert (const Halfspace< Number > & plane)
Inserts an additional bounding halfspace into the polytope.
Parameters
plane The plane to add.
Definition at line 586 of file HPolytope.tpp.
References hypro::Halfspace< Number >::dimension(), hypro::GeometricObjectBase::mEmptyState, hypro::NONEMPTY, and hypro::UNKNOWN.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT(), hypro::HPolytopeT< Number, Converter, Setting >::insert(), hypro::HPolytopeT< Number, Converter, Setting >::intersect(), hypro::HPolytopeT< Number, Converter, Setting >::intersectHalfspace(), hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), hypro::HPolytopeT< Number, Converter, Setting >::minkowskiSum(), hypro::HPolytopeT< Number, Converter, Setting >::reduce(), and hypro::HPolytopeT< Number, Converter, Setting >::reduce_directed().
template<typename Number, typename Converter , class Setting > void hypro::HPolytopeT< Number, Converter, Setting >::insert (const typename HalfspaceVector::iterator begin, const typename HalfspaceVector::iterator end)
Inserts a range of halfspaces into the current polytope.
Parameters
iterator Iterator pointing to the start of the range.
iterator Iterator pointing to the end of the range.
Definition at line 611 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::insert().
template<typename Number , typename Converter , class Setting > HPolytopeT< Number, Converter, Setting > hypro::HPolytopeT< Number, Converter, Setting >::intersect (const HPolytopeT< Number, Converter, Setting > & rhs) const
Definition at line 924 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::constraints(), hypro::HPolytopeT< Number, Converter, Setting >::empty(), hypro::HPolytopeT< Number, Converter, Setting >::Empty(), and hypro::HPolytopeT< Number, Converter, Setting >::insert().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::assignIntervals().
template<typename Number, typename Converter , class Setting > HPolytopeT< Number, Converter, Setting > hypro::HPolytopeT< Number, Converter, Setting >::intersectHalfspace (const Halfspace< Number > & rhs) const
Definition at line 942 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::evaluate(), hypro::HPolytopeT< Number, Converter, Setting >::insert(), hypro::Halfspace< Number >::normal(), and hypro::Halfspace< Number >::offset().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::assignIntervals(), and hypro::HPolytopeT< Number, Converter, Setting >::satisfiesHalfspace().
template<typename Number, typename Converter , class Setting > HPolytopeT< Number, Converter, Setting > hypro::HPolytopeT< Number, Converter, Setting >::intersectHalfspaces (const matrix_t< Number > & _mat, const vector_t< Number > & _vec) const
Definition at line 955 of file HPolytope.tpp.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::assignIntervals(), and hypro::HPolytopeT< Number, Converter, Setting >::satisfiesHalfspaces().
template<typename Number, typename Converter , class Setting > bool hypro::HPolytopeT< Number, Converter, Setting >::isBounded (std::vector< vector_t< Number >> evaluations) const
Definition at line 225 of file reduction.tpp.
References hypro::EvaluationResult< Number >::errorCode, hypro::HPolytopeT< Number, Converter, Setting >::evaluate(), and hypro::INFTY.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), hypro::HPolytopeT< Number, Converter, Setting >::reduce(), and hypro::HPolytopeT< Number, Converter, Setting >::reduce_directed().
template<typename Number, typename Converter , class Setting > bool hypro::HPolytopeT< Number, Converter, Setting >::isExtremePoint (const vector_t< Number > & point) const
Definition at line 683 of file HPolytope.tpp.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isExtremePoint(), and hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant().
template<typename Number, typename Converter , class Setting > bool hypro::HPolytopeT< Number, Converter, Setting >::isExtremePoint (const Point< Number > & point) const
Definition at line 697 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::isExtremePoint(), and hypro::Point< Number >::rawCoordinates().
template<typename Number, typename Converter, class Setting> bool hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant () const inline
Returns, whether the current polytope contains redundant constraints.
Only reads the stored flag without.
Returns
True, if there are no redundant constraints, false otherwise.
Definition at line 181 of file HPolytope.h.
References hypro::HPolytopeT< Number, Converter, Setting >::constraints(), hypro::HPolytopeT< Number, Converter, Setting >::erase(), hypro::HPolytopeT< Number, Converter, Setting >::evaluate(), hypro::HPolytopeT< Number, Converter, Setting >::hasConstraint(), hypro::HPolytopeT< Number, Converter, Setting >::heuristic(), hypro::HPolytopeT< Number, Converter, Setting >::inequalities(), hypro::HPolytopeT< Number, Converter, Setting >::insert(), hypro::HPolytopeT< Number, Converter, Setting >::isBounded(), hypro::HPolytopeT< Number, Converter, Setting >::isExtremePoint(), hypro::HPolytopeT< Number, Converter, Setting >::matrix(), hypro::HPolytopeT< Number, Converter, Setting >::multiEvaluate(), hypro::HPolytopeT< Number, Converter, Setting >::project(), hypro::HPolytopeT< Number, Converter, Setting >::reduce(), hypro::HPolytopeT< Number, Converter, Setting >::reduce_directed(), hypro::HPolytopeT< Number, Converter, Setting >::reduceAssign(), hypro::HPolytopeT< Number, Converter, Setting >::removeRedundancy(), hypro::HPolytopeT< Number, Converter, Setting >::satisfiesHalfspace(), hypro::HPolytopeT< Number, Converter, Setting >::satisfiesHalfspaces(), hypro::HPolytopeT< Number, Converter, Setting >::supremum(), hypro::HPolytopeT< Number, Converter, Setting >::vector(), hypro::HPolytopeT< Number, Converter, Setting >::vertexEnumeration(), and hypro::HPolytopeT< Number, Converter, Setting >::vertices().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::operator=().
template<typename Number, typename Converter , class Setting > HPolytopeT< Number, Converter, Setting > hypro::HPolytopeT< Number, Converter, Setting >::linearTransformation (const matrix_t< Number > & A) const
Definition at line 826 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::empty(), hypro::HPolytopeT< Number, Converter, Setting >::Empty(), hypro::HPolytopeT< Number, Converter, Setting >::inequalities(), hypro::HPolytopeT< Number, Converter, Setting >::size(), hypro::Converter< Number >::toHPolytope(), and hypro::Converter< Number >::toVPolytope().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::assignIntervals(), and hypro::HPolytopeT< Number, Converter, Setting >::project().
template<typename Number , typename Converter , class Setting > matrix_t< Number > hypro::HPolytopeT< Number, Converter, Setting >::matrix () const
Getter for the matrix representation of the constraints.
Returns
A matrix.
Definition at line 363 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::dimension().
Referenced by hypro::convert(), hypro::HPolytopeT< Number, Converter, Setting >::empty(), hypro::HPolytopeT< Number, Converter, Setting >::evaluate(), hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT(), hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), hypro::HPolytopeT< Number, Converter, Setting >::multiEvaluate(), hypro::HPolytopeT< Number, Converter, Setting >::operator=(), hypro::HPolytopeT< Number, Converter, Setting >::removeRedundancy(), and hypro::Converter< Number >::toPolytope().
template<typename Number , typename Converter , class Setting > HPolytopeT< Number, Converter, Setting > hypro::HPolytopeT< Number, Converter, Setting >::minkowskiSum (const HPolytopeT< Number, Converter, Setting > & rhs) const
Definition at line 888 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::constraints(), hypro::HPolytopeT< Number, Converter, Setting >::Empty(), hypro::EvaluationResult< Number >::errorCode, hypro::HPolytopeT< Number, Converter, Setting >::evaluate(), hypro::INFEAS, hypro::INFTY, hypro::HPolytopeT< Number, Converter, Setting >::insert(), and hypro::EvaluationResult< Number >::supportValue.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::assignIntervals().
template<typename Number, typename Converter , class Setting > std::vector< EvaluationResult< Number > > hypro::HPolytopeT< Number, Converter, Setting >::multiEvaluate (const matrix_t< Number > & _direction) const
Definition at line 749 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::evaluate().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant().
template<typename Number, typename Converter , class Setting > std::vector< EvaluationResult< Number > > hypro::HPolytopeT< Number, Converter, Setting >::multiEvaluate (const matrix_t< Number > & _directions, bool useExact) const
Definition at line 723 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::dimension(), hypro::Optimizer< Number >::evaluate(), hypro::HPolytopeT< Number, Converter, Setting >::matrix(), hypro::Optimizer< Number >::setMatrix(), hypro::HPolytopeT< Number, Converter, Setting >::setOptimizer(), hypro::Optimizer< Number >::setVector(), and hypro::HPolytopeT< Number, Converter, Setting >::vector().
template<typename Number, typename Converter, class Setting> HPolytopeT& hypro::HPolytopeT< Number, Converter, Setting >::operator= (const HPolytopeT< Number, Converter, Setting > & rhs) inline
Definition at line 285 of file HPolytope.h.
References hypro::HPolytopeT< Number, Converter, Setting >::constraints(), hypro::HPolytopeT< Number, Converter, Setting >::dimension(), hypro::GeometricObjectBase::getEmptyState(), hypro::HPolytopeT< Number, Converter, Setting >::getOptimizer(), hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), hypro::HPolytopeT< Number, Converter, Setting >::matrix(), hypro::GeometricObjectBase::mEmptyState, hypro::GeometricObjectBase::operator=(), hypro::HPolytopeT< Number, Converter, Setting >::setOptimizer(), and hypro::HPolytopeT< Number, Converter, Setting >::vector().
template<typename Number, typename Converter, class Setting> bool hypro::HPolytopeT< Number, Converter, Setting >::operator== (const HPolytopeT< Number, Converter, Setting > & rhs) const inline
Definition at line 312 of file HPolytope.h.
References hypro::HPolytopeT< Number, Converter, Setting >::constraints(), and hypro::HPolytopeT< Number, Converter, Setting >::dimension().
template<typename Number , typename Converter , class Setting > void hypro::HPolytopeT< Number, Converter, Setting >::print () const
Definition at line 1121 of file HPolytope.tpp.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , class Setting > HPolytopeT< Number, Converter, Setting > hypro::HPolytopeT< Number, Converter, Setting >::project (const std::vector< std::size_t > & dimensions) const
Definition at line 805 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::dimension(), hypro::HPolytopeT< Number, Converter, Setting >::Empty(), and hypro::HPolytopeT< Number, Converter, Setting >::linearTransformation().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant().
template<typename Number , typename Converter , class Setting > HPolytopeT< Number, Converter, Setting > hypro::HPolytopeT< Number, Converter, Setting >::reduce (unsigned facet = 1, unsigned facet2 = 0, REDUCTION_STRATEGY strat = REDUCTION_STRATEGY::DROP) const
Definition at line 460 of file reduction.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::constraints(), hypro::HPolytopeT< Number, Converter, Setting >::erase(), hypro::HPolytopeT< Number, Converter, Setting >::insert(), hypro::HPolytopeT< Number, Converter, Setting >::isBounded(), hypro::Point< Number >::rawCoordinates(), hypro::UNITE, and hypro::HPolytopeT< Number, Converter, Setting >::vertices().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant().
template<typename Number, typename Converter , class Setting > HPolytopeT< Number, Converter, Setting > hypro::HPolytopeT< Number, Converter, Setting >::reduce_directed (std::vector< vector_t< Number >> directions, REDUCTION_STRATEGY strat = REDUCTION_STRATEGY::DIRECTED_SMALL) const
Definition at line 714 of file reduction.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::constraints(), hypro::HPolytopeT< Number, Converter, Setting >::contains(), hypro::HPolytopeT< Number, Converter, Setting >::erase(), hypro::HPolytopeT< Number, Converter, Setting >::insert(), hypro::HPolytopeT< Number, Converter, Setting >::isBounded(), hypro::Point< Number >::rawCoordinates(), hypro::HPolytopeT< Number, Converter, Setting >::size(), and hypro::HPolytopeT< Number, Converter, Setting >::vertices().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant().
template<typename Number, typename Converter, class Setting> void hypro::HPolytopeT< Number, Converter, Setting >::reduceAssign (unsigned _steps = 1, REDUCTION_STRATEGY strat = REDUCTION_STRATEGY::DROP)
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant().
template<typename Number, typename Converter, class Setting> template<typename N = Number, carl::DisableIf< std::is_same< N, double >> = carl::dummy> void hypro::HPolytopeT< Number, Converter, Setting >::reduceNumberRepresentation (const std::vector< Point< Number >> & _vertices = std::vector<Point<Number>>(), unsigned limit = fReach_DENOMINATOR) const inline
Definition at line 330 of file HPolytope.h.
References hypro::HPolytopeT< Number, Converter, Setting >::contains(), hypro::HPolytopeT< Number, Converter, Setting >::empty(), and hypro::HPolytopeT< Number, Converter, Setting >::vertices().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT(), and hypro::HPolytopeT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number, typename Converter, class Setting> template<typename N = Number, carl::EnableIf< std::is_same< N, double >> = carl::dummy> void hypro::HPolytopeT< Number, Converter, Setting >::reduceNumberRepresentation (const std::vector< Point< double >> & = std::vector<Point<double>>(), unsigned = fReach_DENOMINATOR) const inline
Definition at line 405 of file HPolytope.h.
template<typename Number, typename Converter, class Setting> void hypro::HPolytopeT< Number, Converter, Setting >::reduceRepresentation () inline
Definition at line 274 of file HPolytope.h.
References hypro::HPolytopeT< Number, Converter, Setting >::clear(), hypro::HPolytopeT< Number, Converter, Setting >::print(), hypro::HPolytopeT< Number, Converter, Setting >::reduceNumberRepresentation(), and hypro::HPolytopeT< Number, Converter, Setting >::removeRedundancy().
template<typename Number , typename Converter , class Setting > const HPolytopeT< Number, Converter, Setting > & hypro::HPolytopeT< Number, Converter, Setting >::removeRedundancy ()
Definition at line 643 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::matrix(), hypro::Optimizer< Number >::redundantConstraints(), hypro::Optimizer< Number >::setMatrix(), hypro::HPolytopeT< Number, Converter, Setting >::setOptimizer(), hypro::Optimizer< Number >::setVector(), and hypro::HPolytopeT< Number, Converter, Setting >::vector().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), and hypro::HPolytopeT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number, typename Converter , class Setting > std::pair< CONTAINMENT, HPolytopeT< Number, Converter, Setting > > hypro::HPolytopeT< Number, Converter, Setting >::satisfiesHalfspace (const Halfspace< Number > & rhs) const
Definition at line 762 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::empty(), hypro::FULL, hypro::HPolytopeT< Number, Converter, Setting >::hasConstraint(), hypro::HPolytopeT< Number, Converter, Setting >::intersectHalfspace(), hypro::NO, hypro::Halfspace< Number >::normal(), hypro::Halfspace< Number >::offset(), and hypro::PARTIAL.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant().
template<typename Number, typename Converter , class Setting > std::pair< CONTAINMENT, HPolytopeT< Number, Converter, Setting > > hypro::HPolytopeT< Number, Converter, Setting >::satisfiesHalfspaces (const matrix_t< Number > & _mat, const vector_t< Number > & _vec) const
Definition at line 780 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::empty(), hypro::FULL, hypro::HPolytopeT< Number, Converter, Setting >::hasConstraint(), hypro::HPolytopeT< Number, Converter, Setting >::intersectHalfspaces(), hypro::NO, and hypro::PARTIAL.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant().
template<typename Number, typename Converter , class Setting > void hypro::HPolytopeT< Number, Converter, Setting >::setOptimizer (const matrix_t< Number > & mat = matrix_t<Number>::Zero(1, 1), const vector_t< Number > & vec = vector_t<Number>::Zero(1)) const
Definition at line 1174 of file HPolytope.tpp.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::empty(), hypro::HPolytopeT< Number, Converter, Setting >::evaluate(), hypro::HPolytopeT< Number, Converter, Setting >::getOptimizer(), hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT(), hypro::HPolytopeT< Number, Converter, Setting >::multiEvaluate(), hypro::HPolytopeT< Number, Converter, Setting >::operator=(), and hypro::HPolytopeT< Number, Converter, Setting >::removeRedundancy().
template<typename Number, typename Converter, class Setting> void hypro::HPolytopeT< Number, Converter, Setting >::setReduced () const inline
Manually sets the polytope to behave as if it did not contain redundant constraints.
This function can avoid an expensive redundancy removal call in case the user already knows that this property holds.
Definition at line 174 of file HPolytope.h.
template<typename Number, typename Converter, class Setting> void hypro::HPolytopeT< Number, Converter, Setting >::setUpdated (const bool & b) inline
Definition at line 445 of file HPolytope.h.
template<typename Number , typename Converter , class Setting > std::size_t hypro::HPolytopeT< Number, Converter, Setting >::size () const
Getter for the number of constraints.
Returns
The number of constraints.
Definition at line 358 of file HPolytope.tpp.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::affineTransformation(), hypro::HPolytopeT< Number, Converter, Setting >::linearTransformation(), hypro::HPolytopeT< Number, Converter, Setting >::reduce_directed(), and hypro::HPolytopeT< Number, Converter, Setting >::sizeOfHPolytopeT().
template<typename Number, typename Converter, class Setting> double hypro::HPolytopeT< Number, Converter, Setting >::sizeOfHPolytopeT () const inline
Approximates the storage usage of the current polytope.
[long description]
Returns
The size.
Definition at line 131 of file HPolytope.h.
References hypro::HPolytopeT< Number, Converter, Setting >::dimension(), hypro::HPolytopeT< Number, Converter, Setting >::empty(), hypro::HPolytopeT< Number, Converter, Setting >::Empty(), and hypro::HPolytopeT< Number, Converter, Setting >::size().
template<typename Number , typename Converter , class Setting > Number hypro::HPolytopeT< Number, Converter, Setting >::supremum () const
Getter for a number representing the supremum according to the infinity norm of the polytope.
Returns
A number.
Definition at line 519 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::empty(), hypro::Point< Number >::inftyNorm(), and hypro::HPolytopeT< Number, Converter, Setting >::vertices().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant().
template<typename Number, typename Converter, class Setting> static representation_name hypro::HPolytopeT< Number, Converter, Setting >::type () inline static
Definition at line 162 of file HPolytope.h.
template<typename Number , typename Converter , class Setting > HPolytopeT< Number, Converter, Setting > hypro::HPolytopeT< Number, Converter, Setting >::unite (const HPolytopeT< Number, Converter, Setting > & rhs) const
Definition at line 1012 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::dimension(), hypro::HPolytopeT< Number, Converter, Setting >::empty(), hypro::EvaluationResult< Number >::errorCode, hypro::HPolytopeT< Number, Converter, Setting >::evaluate(), hypro::FEAS, hypro::INFEAS, hypro::EvaluationResult< Number >::supportValue, and hypro::HPolytopeT< Number, Converter, Setting >::vertices().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , class Setting > HPolytopeT< Number, Converter, Setting > hypro::HPolytopeT< Number, Converter, Setting >::unite (const std::vector< HPolytopeT< Number, Converter, Setting > > & rhs) static
Definition at line 1098 of file HPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT(), and hypro::HPolytopeT< Number, Converter, Setting >::vertices().
template<typename Number, typename Converter, class Setting> void hypro::HPolytopeT< Number, Converter, Setting >::unreduce () const inline
Resets the information if the current polytope contains redundant constraints.
This function may be used to allow a manual call to the redundancy removal method.
Definition at line 168 of file HPolytope.h.
template<typename Number , typename Converter , class Setting > vector_t< Number > hypro::HPolytopeT< Number, Converter, Setting >::vector () const
Getter for the vector of offsets of the bounding hyperplanes.
Returns
A vector.
Definition at line 375 of file HPolytope.tpp.
Referenced by hypro::convert(), hypro::HPolytopeT< Number, Converter, Setting >::empty(), hypro::HPolytopeT< Number, Converter, Setting >::evaluate(), hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT(), hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), hypro::HPolytopeT< Number, Converter, Setting >::multiEvaluate(), hypro::HPolytopeT< Number, Converter, Setting >::operator=(), hypro::HPolytopeT< Number, Converter, Setting >::removeRedundancy(), and hypro::Converter< Number >::toPolytope().
template<typename Number, typename Converter, class Setting> std::vector<Point<Number> > hypro::HPolytopeT< Number, Converter, Setting >::vertexEnumeration () const
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant().
template<typename Number, typename Converter , class Setting > std::vector< Point< Number > > hypro::HPolytopeT< Number, Converter, Setting >::vertices (const matrix_t< Number > & = matrix_t<Number>::Zero(0, 0)) const
Getter for the vertices of the current polytope.
Solves the vertex enumeration problem, i.e. converts the hyperplanar description into a vertex description.
Returns
A vector of points.
Definition at line 395 of file HPolytope.tpp.
References default_double_comparison_ulps, hypro::HPolytopeT< Number, Converter, Setting >::dimension(), and hypro::HPolytopeT< Number, Converter, Setting >::empty().
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), hypro::HPolytopeT< Number, Converter, Setting >::reduce(), hypro::HPolytopeT< Number, Converter, Setting >::reduce_directed(), hypro::HPolytopeT< Number, Converter, Setting >::reduceNumberRepresentation(), hypro::HPolytopeT< Number, Converter, Setting >::supremum(), and hypro::HPolytopeT< Number, Converter, Setting >::unite().
Friends And Related Function Documentation
template<typename Number, typename Converter, class Setting> std::ostream& operator<< (std::ostream & lhs, const HPolytopeT< Number, Converter, Setting > & rhs) friend
Definition at line 301 of file HPolytope.h.
template<typename Number, typename Converter, class Setting> void swap (HPolytopeT< Number, Converter, Setting > & a, HPolytopeT< Number, Converter, Setting > & b) friend
Definition at line 320 of file HPolytope.h.
Member Data Documentation
template<typename Number, typename Converter, class Setting> constexpr auto hypro::HPolytopeT< Number, Converter, Setting >::type_enum = representation_name::polytope_h static
Definition at line 54 of file HPolytope.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/Polytopes/HPolytope/HPolytope.h
/home/travis/build/hypro/hypro/src/hypro/representations/Polytopes/HPolytope/HPolytope.tpp
/home/travis/build/hypro/hypro/src/hypro/representations/Polytopes/HPolytope/reduction.tpp