HyPro: hypro::Spinlock Class Reference
hypro::Spinlock Class Reference
#include <Spinlock.h>
Public Member Functions
Spinlock ()
void lock ()
void unlock ()
Private Attributes
std::atomic_flag state_ = ATOMIC_FLAG_INIT
Detailed Description
Definition at line 7 of file Spinlock.h.
Constructor & Destructor Documentation
hypro::Spinlock::Spinlock () inline
Definition at line 9 of file Spinlock.h.
References lock(), and unlock().
Member Function Documentation
void hypro::Spinlock::lock ()
lock Spinlock
Definition at line 4 of file Spinlock.cpp.
References state_.
Referenced by Spinlock().
void hypro::Spinlock::unlock ()
unlock Spinlock
Definition at line 10 of file Spinlock.cpp.
References state_.
Referenced by Spinlock().
Member Data Documentation
std::atomic_flag hypro::Spinlock::state_ = ATOMIC_FLAG_INIT private
Definition at line 21 of file Spinlock.h.
Referenced by lock(), and unlock().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/util/multithreading/Spinlock.h
/home/travis/build/hypro/hypro/src/hypro/util/multithreading/Spinlock.cpp