HyPro: hypro::DecisionEntity< Number > Class Template Reference
hypro::DecisionEntity< Number > Class Template Reference
Public Member Functions
representation_name getRepresentationForAutomaton (const HybridAutomaton< Number > &ha)
representation_name getRepresentationForLocation (const Location< Number > &loc)
representation_name getRepresentationForSubspace (const Location< Number > &loc, size_t index)
Decomposition getSubspaceDecomposition (const HybridAutomaton< Number > &automaton)
bool checkDecomposed (const HybridAutomaton< Number > &automaton)
std::pair< HybridAutomaton< Number >, Decomposition > decomposeAutomaton (const HybridAutomaton< Number > &automaton)
void addEdgesForLinTrafo (matrix_t< Number > linTrafo, boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS > &graph)
void addEdgesForAffineTrafo (matrix_t< Number > affineTrafo, boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS > &graph)
void addEdgesForCondition (Condition< Number > condition, boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS > &graph)
void addEdgesForRectTrafo (const std::vector< carl::Interval< Number >> &intervals, boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS > &graph)
void addEdgesForRectMap (const std::map< carl::Variable, carl::Interval< Number >> &map, boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS > &graph)
void printDecomposition (const Decomposition &decomposition)
bool isTimedAutomaton (const HybridAutomaton< Number > &ha)
bool isRectangularAutomaton (const HybridAutomaton< Number > &ha)
bool isTimedLocation (const Location< Number > &loc)
bool isRectangularLocation (const Location< Number > &loc)
bool isTimedSubspace (const Location< Number > &loc, size_t index)
bool isRectangularSubspace (const Location< Number > &loc, size_t index)
bool isDiscreteSubspace (const Location< Number > &loc, size_t index)
Detailed Description
template<typename Number>
class hypro::DecisionEntity< Number >
DecisionEntity is a Singleton class providing decision procedures for choosing a suitable represenation
Definition at line 21 of file DecisionEntity.h.
Member Function Documentation
template<typename Number > void hypro::DecisionEntity< Number >::addEdgesForAffineTrafo (matrix_t< Number > affineTrafo, boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS > & graph)
Definition at line 260 of file DecisionEntity.tpp.
template<typename Number > void hypro::DecisionEntity< Number >::addEdgesForCondition (Condition< Number > condition, boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS > & graph)
Definition at line 309 of file DecisionEntity.tpp.
template<typename Number > void hypro::DecisionEntity< Number >::addEdgesForLinTrafo (matrix_t< Number > linTrafo, boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS > & graph)
Definition at line 275 of file DecisionEntity.tpp.
template<typename Number > void hypro::DecisionEntity< Number >::addEdgesForRectMap (const std::map< carl::Variable, carl::Interval< Number >> & map, boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS > & graph)
Definition at line 297 of file DecisionEntity.tpp.
template<typename Number > void hypro::DecisionEntity< Number >::addEdgesForRectTrafo (const std::vector< carl::Interval< Number >> & intervals, boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS > & graph)
Definition at line 286 of file DecisionEntity.tpp.
template<typename Number > bool hypro::DecisionEntity< Number >::checkDecomposed (const HybridAutomaton< Number > & automaton)
Definition at line 249 of file DecisionEntity.tpp.
References hypro::HybridAutomaton< Number >::getInitialStates().
template<typename Number > std::pair< HybridAutomaton< Number >, Decomposition > hypro::DecisionEntity< Number >::decomposeAutomaton (const HybridAutomaton< Number > & automaton)
Definition at line 398 of file DecisionEntity.tpp.
References hypro::HybridAutomaton< Number >::decompose(), and hypro::Decomposition::size().
template<typename Number > representation_name hypro::DecisionEntity< Number >::getRepresentationForAutomaton (const HybridAutomaton< Number > & ha)
Definition at line 16 of file DecisionEntity.tpp.
References hypro::isTimed().
template<typename Number > representation_name hypro::DecisionEntity< Number >::getRepresentationForLocation (const Location< Number > & loc)
Definition at line 28 of file DecisionEntity.tpp.
References hypro::isTimed().
template<typename Number > representation_name hypro::DecisionEntity< Number >::getRepresentationForSubspace (const Location< Number > & loc, size_t index)
Definition at line 4 of file DecisionEntity.tpp.
References hypro::isTimed().
template<typename Number > Decomposition hypro::DecisionEntity< Number >::getSubspaceDecomposition (const HybridAutomaton< Number > & automaton)
decomposed the given space into a set of set of variables. Each of the variable sets indicate dependent variables
Definition at line 347 of file DecisionEntity.tpp.
References hypro::HybridAutomaton< Number >::dimension(), hypro::HybridAutomaton< Number >::getGlobalBadStates(), hypro::HybridAutomaton< Number >::getLocalBadStates(), hypro::HybridAutomaton< Number >::getLocations(), hypro::HybridAutomaton< Number >::getTransitions(), and hypro::Decomposition::mDecomposition.
template<typename Number > bool hypro::DecisionEntity< Number >::isDiscreteSubspace (const Location< Number > & loc, size_t index)
Definition at line 40 of file DecisionEntity.tpp.
References hypro::Location< Number >::getLinearFlow(), and hypro::Location< Number >::getRectangularFlow().
template<typename Number > bool hypro::DecisionEntity< Number >::isRectangularAutomaton (const HybridAutomaton< Number > & ha)
Definition at line 239 of file DecisionEntity.tpp.
References hypro::HybridAutomaton< Number >::getLocations().
template<typename Number > bool hypro::DecisionEntity< Number >::isRectangularLocation (const Location< Number > & loc)
Definition at line 217 of file DecisionEntity.tpp.
References hypro::Location< Number >::getName(), and hypro::Location< Number >::getNumberFlow().
template<typename Number > bool hypro::DecisionEntity< Number >::isRectangularSubspace (const Location< Number > & loc, size_t index)
Definition at line 110 of file DecisionEntity.tpp.
References hypro::Location< Number >::getInvariant(), hypro::Location< Number >::getLinearFlow(), hypro::Location< Number >::getName(), hypro::Location< Number >::getRectangularFlow(), and hypro::Location< Number >::getTransitions().
template<typename Number > bool hypro::DecisionEntity< Number >::isTimedAutomaton (const HybridAutomaton< Number > & ha)
Definition at line 229 of file DecisionEntity.tpp.
References hypro::HybridAutomaton< Number >::getLocations().
template<typename Number > bool hypro::DecisionEntity< Number >::isTimedLocation (const Location< Number > & loc)
Definition at line 156 of file DecisionEntity.tpp.
References hypro::Location< Number >::getInvariant(), hypro::Location< Number >::getLinearFlow(), hypro::Location< Number >::getName(), hypro::Location< Number >::getNumberFlow(), and hypro::Location< Number >::getTransitions().
template<typename Number > bool hypro::DecisionEntity< Number >::isTimedSubspace (const Location< Number > & loc, size_t index)
Definition at line 45 of file DecisionEntity.tpp.
References hypro::Location< Number >::getInvariant(), hypro::Location< Number >::getLinearFlow(), hypro::Location< Number >::getName(), hypro::Location< Number >::getTransitions(), and hypro::isTimed().
Referenced by hypro::SettingsProvider< State >::computeLocationSubspaceTypeMapping().
template<typename Number > void hypro::DecisionEntity< Number >::printDecomposition (const Decomposition & decomposition)
Definition at line 333 of file DecisionEntity.tpp.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/decomposition/DecisionEntity.h
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/decomposition/DecisionEntity.tpp