HyPro: hypro::HybridSystemParser::DeclContext Class Reference
hypro::HybridSystemParser::DeclContext Class Reference
#include <HybridSystemParser.h>
Public Member Functions
DeclContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
TypeDefsContext * typeDefs ()
EnumDefsContext * enumDefs ()
OptControllabilityContext * optControllability ()
IdentifierContext * identifier ()
EventTypeContext * eventType ()
ControllabilityContext * controllability ()
TypeContext * type ()
ConstantDefsContext * constantDefs ()
AlgVarsDefsContext * algVarsDefs ()
ContDeclsContext * contDecls ()
EquationsContext * equations ()
ExpressionsContext * expressions ()
InvariantDeclsContext * invariantDecls ()
IoDeclsContext * ioDecls ()
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Detailed Description
Definition at line 300 of file HybridSystemParser.h.
Constructor & Destructor Documentation
HybridSystemParser::DeclContext::DeclContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 728 of file HybridSystemParser.cpp.
Member Function Documentation
antlrcpp::Any HybridSystemParser::DeclContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
Definition at line 793 of file HybridSystemParser.cpp.
HybridSystemParser::AlgVarsDefsContext * HybridSystemParser::DeclContext::algVarsDefs ()
Definition at line 764 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::decl().
HybridSystemParser::ConstantDefsContext * HybridSystemParser::DeclContext::constantDefs ()
Definition at line 760 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::decl().
HybridSystemParser::ContDeclsContext * HybridSystemParser::DeclContext::contDecls ()
Definition at line 768 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::decl().
HybridSystemParser::ControllabilityContext * HybridSystemParser::DeclContext::controllability ()
Definition at line 752 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::decl().
HybridSystemParser::EnumDefsContext * HybridSystemParser::DeclContext::enumDefs ()
Definition at line 736 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::decl().
HybridSystemParser::EquationsContext * HybridSystemParser::DeclContext::equations ()
Definition at line 772 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::decl().
HybridSystemParser::EventTypeContext * HybridSystemParser::DeclContext::eventType ()
Definition at line 748 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::decl().
HybridSystemParser::ExpressionsContext * HybridSystemParser::DeclContext::expressions ()
Definition at line 776 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::decl().
size_t HybridSystemParser::DeclContext::getRuleIndex () const override virtual
Definition at line 789 of file HybridSystemParser.cpp.
References hypro::HybridSystemParser::RuleDecl.
HybridSystemParser::IdentifierContext * HybridSystemParser::DeclContext::identifier ()
Definition at line 744 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::decl().
HybridSystemParser::InvariantDeclsContext * HybridSystemParser::DeclContext::invariantDecls ()
Definition at line 780 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::decl().
HybridSystemParser::IoDeclsContext * HybridSystemParser::DeclContext::ioDecls ()
Definition at line 784 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::decl().
HybridSystemParser::OptControllabilityContext * HybridSystemParser::DeclContext::optControllability ()
Definition at line 740 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::decl().
HybridSystemParser::TypeContext * HybridSystemParser::DeclContext::type ()
Definition at line 756 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::decl().
HybridSystemParser::TypeDefsContext * HybridSystemParser::DeclContext::typeDefs ()
Definition at line 732 of file HybridSystemParser.cpp.
Referenced by hypro::HybridSystemParser::decl().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-cif/HybridSystemParser.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-cif/HybridSystemParser.cpp