HyPro: hypro::Transformation< Number > Class Template Reference
hypro::Transformation< Number > Class Template Reference
Class for transformation of Hybrid Automata for Eigenvalue Decomposition(EVD) forward reachability analysis.
Public Types
using locationVector = std::vector< Location< Number > * >
using transitionVector = std::vector< Transition< Number > * >
using locationStateMap = typename HybridAutomaton< Number >::locationStateMap
using locationConditionMap = std::map< Location< Number > *, Condition< Number >, locPtrComp< Number >>
using conditionVector = std::vector< Condition< Number >>
using setVector = std::vector< std::pair< matrix_t< Number >, vector_t< Number >>>
Vector of conditions.
using locationPtrMap = std::map< const Location< Number > *, Location< Number > *, locPtrComp< Number >>
using locationComputationSTMap = std::map< Location< Number > *, STallValues< Number >, locPtrComp< Number >>
Public Member Functions
Transformation ()=delete
Default constructor.
Transformation (const HybridAutomaton< Number > &_hybrid)
Constructor from hybrid automata to adjust automaton and transformation All static properties relating to the Hybrid Automaton are stored in this class.
Transformation (const Transformation< Number > &_trafo)
Copy constructor.
void output_HybridAutomaton ()
void addGlobalBadStates (const HybridAutomaton< Number > &_hybrid, const bool transform)
HybridAutomaton< Number > & getTransformedHybridAutomaton ()
const locationComputationSTMap & getLocationComputationSTMap ()
Detailed Description
template<typename Number>
class hypro::Transformation< Number >
Class for transformation of Hybrid Automata for Eigenvalue Decomposition(EVD) forward reachability analysis.
Template Parameters
Number The used number type.
Definition at line 61 of file Transformation.h.
Member Typedef Documentation
template<typename Number> using hypro::Transformation< Number >::conditionVector = std::vector<Condition<Number>>
Definition at line 67 of file Transformation.h.
template<typename Number> using hypro::Transformation< Number >::locationComputationSTMap = std::map<Location<Number>*, STallValues<Number>, locPtrComp<Number>>
Definition at line 72 of file Transformation.h.
template<typename Number> using hypro::Transformation< Number >::locationConditionMap = std::map<Location<Number>*, Condition<Number>, locPtrComp<Number>>
Definition at line 66 of file Transformation.h.
template<typename Number> using hypro::Transformation< Number >::locationPtrMap = std::map<const Location<Number>*, Location<Number>*, locPtrComp<Number>>
Definition at line 70 of file Transformation.h.
template<typename Number> using hypro::Transformation< Number >::locationStateMap = typename HybridAutomaton<Number>::locationStateMap
Definition at line 65 of file Transformation.h.
template<typename Number> using hypro::Transformation< Number >::locationVector = std::vector<Location<Number>*>
Definition at line 63 of file Transformation.h.
template<typename Number> using hypro::Transformation< Number >::setVector = std::vector<std::pair<matrix_t<Number>, vector_t<Number>>>
Vector of conditions.
Definition at line 68 of file Transformation.h.
template<typename Number> using hypro::Transformation< Number >::transitionVector = std::vector<Transition<Number>*>
Definition at line 64 of file Transformation.h.
Constructor & Destructor Documentation
template<typename Number> hypro::Transformation< Number >::Transformation () delete
Default constructor.
template<typename Number > hypro::Transformation< Number >::Transformation (const HybridAutomaton< Number > & _hybrid)
Constructor from hybrid automata to adjust automaton and transformation All static properties relating to the Hybrid Automaton are stored in this class.
Parameters
[in] _hybrid The original hybrid automaton.
Definition at line 10 of file Transformation.tpp.
References hypro::Location< Number >::addTransition(), hypro::CONSTANT, hypro::CONVERGENT, hypro::detail::declare_structures(), hypro::DIVERGENT, hypro::HybridAutomaton< Number >::getInitialStates(), hypro::HybridAutomaton< Number >::getLocalBadStates(), hypro::HybridAutomaton< Number >::getLocations(), hypro::Reset< Number >::getMatrix(), hypro::HybridAutomaton< Number >::getTransitions(), hypro::Reset< Number >::getVector(), hypro::INITIALIZED, hypro::LINEAR, hypro::STallValues< Number >::mSTflowpipeSegment, hypro::STallValues< Number >::mSTindependentFunct, hypro::HybridAutomaton< Number >::setLocations(), hypro::Reset< Number >::setMatrix(), hypro::Reset< Number >::setVector(), and hypro::Reset< Number >::size().
template<typename Number> hypro::Transformation< Number >::Transformation (const Transformation< Number > & _trafo)
Copy constructor.
Parameters
[in] _hybrid The original transformation for an hybrid automaton.
Member Function Documentation
template<typename Number > void hypro::Transformation< Number >::addGlobalBadStates (const HybridAutomaton< Number > & _hybrid, const bool transform)
Definition at line 228 of file Transformation.tpp.
References hypro::CONSTANT, hypro::CONVERGENT, hypro::DIVERGENT, hypro::HybridAutomaton< Number >::getGlobalBadStates(), hypro::HybridAutomaton< Number >::getLocations(), hypro::INITIALIZED, hypro::LINEAR, hypro::linear, hypro::STallValues< Number >::mSTflowpipeSegment, and hypro::STallValues< Number >::mSTindependentFunct.
template<typename Number> const locationComputationSTMap& hypro::Transformation< Number >::getLocationComputationSTMap () inline
Definition at line 139 of file Transformation.h.
template<typename Number> HybridAutomaton<Number>& hypro::Transformation< Number >::getTransformedHybridAutomaton () inline
Definition at line 137 of file Transformation.h.
template<typename Number > void hypro::Transformation< Number >::output_HybridAutomaton ()
Definition at line 496 of file Transformation.tpp.
Referenced by main().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/eigendecomposition/Transformation.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/eigendecomposition/Transformation.tpp