HyPro: hypro::RootGrowNode< Number, Converter, Setting > Class Template Reference
hypro::RootGrowNode< Number, Converter, Setting > Class Template Reference abstract
#include <IntersectHalfspaceOp.h>
Public Types
using PointerVec = std::vector< std::shared_ptr< RootGrowNode< Number, Converter, Setting >>>
Public Member Functions
RootGrowNode ()
virtual ~RootGrowNode ()
virtual SFNEW_TYPE getType () const
virtual unsigned getOriginCount () const
virtual PointerVec getChildren () const
virtual PointerVec & rGetChildren ()
virtual std::size_t getDimension () const
virtual SETSTATE isEmpty () const
virtual RGNData * getData () const =0
virtual LeafData getLeafData () const
virtual void setDimension (const std::size_t d)
void addToChildren (const std::shared_ptr< RootGrowNode > &rhs)
void clearChildren ()
virtual void print (std::ostream &ostr) const
virtual matrix_t< Number > transform (const matrix_t< Number > &param) const =0
virtual std::vector< EvaluationResult< Number > > compute (const matrix_t< Number > &param, bool useExact) const =0
virtual std::vector< EvaluationResult< Number > > aggregate (std::vector< std::vector< EvaluationResult< Number >>> &resultStackBack, const matrix_t< Number > &currentParam) const =0
virtual bool empty () const
virtual bool empty (const std::vector< bool > &) const
virtual Point< Number > supremumPoint () const
virtual Point< Number > supremumPoint (std::vector< Point< Number >> &) const
virtual vector_t< Number > reverseOp (const vector_t< Number > &point) const
virtual bool contains (const vector_t< Number > &) const
virtual bool contains (const std::vector< bool > &, const vector_t< Number > &) const
virtual std::vector< std::size_t > intersectDims (const std::vector< std::vector< std::size_t >> &dims) const
Protected Attributes
SFNEW_TYPE mType = NODE
unsigned originCount = 0
PointerVec mChildren = PointerVec()
std::size_t mDimension = 0
SETSTATE mEmptyState = SETSTATE::UNKNOWN
Friends
std::ostream & operator<< (std::ostream &ostr, const RootGrowNode &r)
Detailed Description
template<typename Number, typename Converter, typename Setting>
class hypro::RootGrowNode< Number, Converter, Setting >
Definition at line 23 of file IntersectHalfspaceOp.h.
Member Typedef Documentation
template<typename Number, typename Converter, typename Setting> using hypro::RootGrowNode< Number, Converter, Setting >::PointerVec = std::vector<std::shared_ptr<RootGrowNode<Number, Converter, Setting>>>
Definition at line 67 of file RootGrowNode.h.
Constructor & Destructor Documentation
template<typename Number, typename Converter, typename Setting> hypro::RootGrowNode< Number, Converter, Setting >::RootGrowNode () inline
Definition at line 81 of file RootGrowNode.h.
template<typename Number, typename Converter, typename Setting> virtual hypro::RootGrowNode< Number, Converter, Setting >::~RootGrowNode () inline virtual
Definition at line 82 of file RootGrowNode.h.
Member Function Documentation
template<typename Number, typename Converter, typename Setting> void hypro::RootGrowNode< Number, Converter, Setting >::addToChildren (const std::shared_ptr< RootGrowNode< Number, Converter, Setting > > & rhs) inline
Definition at line 106 of file RootGrowNode.h.
template<typename Number, typename Converter, typename Setting> virtual std::vector<EvaluationResult<Number> > hypro::RootGrowNode< Number, Converter, Setting >::aggregate (std::vector< std::vector< EvaluationResult< Number >>> & resultStackBack, const matrix_t< Number > & currentParam) const pure virtual
Implemented in hypro::TrafoOp< Number, Converter, Setting >, hypro::Leaf< Number, Converter, Setting, Representation >, hypro::ProjectOp< Number, Converter, Setting >, hypro::IntersectHalfspaceOp< Number, Converter, Setting >, hypro::IntersectOp< Number, Converter, Setting >, hypro::ScaleOp< Number, Converter, Setting >, hypro::UnionOp< Number, Converter, Setting >, and hypro::SumOp< Number, Converter, Setting >.
template<typename Number, typename Converter, typename Setting> void hypro::RootGrowNode< Number, Converter, Setting >::clearChildren () inline
Definition at line 107 of file RootGrowNode.h.
template<typename Number, typename Converter, typename Setting> virtual std::vector<EvaluationResult<Number> > hypro::RootGrowNode< Number, Converter, Setting >::compute (const matrix_t< Number > & param, bool useExact) const pure virtual
Implemented in hypro::TrafoOp< Number, Converter, Setting >, hypro::Leaf< Number, Converter, Setting, Representation >, hypro::ProjectOp< Number, Converter, Setting >, hypro::IntersectHalfspaceOp< Number, Converter, Setting >, hypro::IntersectOp< Number, Converter, Setting >, hypro::ScaleOp< Number, Converter, Setting >, hypro::SumOp< Number, Converter, Setting >, and hypro::UnionOp< Number, Converter, Setting >.
template<typename Number, typename Converter, typename Setting> virtual bool hypro::RootGrowNode< Number, Converter, Setting >::contains (const vector_t< Number > &) const inline virtual
Reimplemented in hypro::Leaf< Number, Converter, Setting, Representation >.
Definition at line 175 of file RootGrowNode.h.
References assert().
template<typename Number, typename Converter, typename Setting> virtual bool hypro::RootGrowNode< Number, Converter, Setting >::contains (const std::vector< bool > & , const vector_t< Number > &) const inline virtual
Reimplemented in hypro::IntersectHalfspaceOp< Number, Converter, Setting >, hypro::TrafoOp< Number, Converter, Setting >, hypro::IntersectOp< Number, Converter, Setting >, hypro::SumOp< Number, Converter, Setting >, hypro::ScaleOp< Number, Converter, Setting >, hypro::ProjectOp< Number, Converter, Setting >, and hypro::UnionOp< Number, Converter, Setting >.
Definition at line 179 of file RootGrowNode.h.
References assert().
template<typename Number, typename Converter, typename Setting> virtual bool hypro::RootGrowNode< Number, Converter, Setting >::empty () const inline virtual
Reimplemented in hypro::Leaf< Number, Converter, Setting, Representation >.
Definition at line 157 of file RootGrowNode.h.
References assert().
Referenced by hypro::Leaf< Number, Converter, Setting, Representation >::empty().
template<typename Number, typename Converter, typename Setting> virtual bool hypro::RootGrowNode< Number, Converter, Setting >::empty (const std::vector< bool > &) const inline virtual
Reimplemented in hypro::IntersectHalfspaceOp< Number, Converter, Setting >, hypro::TrafoOp< Number, Converter, Setting >, hypro::IntersectOp< Number, Converter, Setting >, hypro::SumOp< Number, Converter, Setting >, hypro::UnionOp< Number, Converter, Setting >, hypro::ScaleOp< Number, Converter, Setting >, and hypro::ProjectOp< Number, Converter, Setting >.
Definition at line 161 of file RootGrowNode.h.
References assert().
template<typename Number, typename Converter, typename Setting> virtual PointerVec hypro::RootGrowNode< Number, Converter, Setting >::getChildren () const inline virtual
Definition at line 88 of file RootGrowNode.h.
Referenced by hypro::IntersectOp< Number, Converter, Setting >::empty().
template<typename Number, typename Converter, typename Setting> virtual RGNData* hypro::RootGrowNode< Number, Converter, Setting >::getData () const pure virtual
Implemented in hypro::TrafoOp< Number, Converter, Setting >, hypro::Leaf< Number, Converter, Setting, Representation >, hypro::IntersectHalfspaceOp< Number, Converter, Setting >, hypro::IntersectOp< Number, Converter, Setting >, hypro::ScaleOp< Number, Converter, Setting >, hypro::ProjectOp< Number, Converter, Setting >, hypro::SumOp< Number, Converter, Setting >, and hypro::UnionOp< Number, Converter, Setting >.
Referenced by hypro::convertSettings().
template<typename Number, typename Converter, typename Setting> virtual std::size_t hypro::RootGrowNode< Number, Converter, Setting >::getDimension () const inline virtual
Reimplemented in hypro::TrafoOp< Number, Converter, Setting >, hypro::Leaf< Number, Converter, Setting, Representation >, hypro::IntersectOp< Number, Converter, Setting >, hypro::IntersectHalfspaceOp< Number, Converter, Setting >, hypro::ScaleOp< Number, Converter, Setting >, hypro::ProjectOp< Number, Converter, Setting >, hypro::SumOp< Number, Converter, Setting >, and hypro::UnionOp< Number, Converter, Setting >.
Definition at line 90 of file RootGrowNode.h.
template<typename Number, typename Converter, typename Setting> virtual LeafData hypro::RootGrowNode< Number, Converter, Setting >::getLeafData () const inline virtual
Reimplemented in hypro::Leaf< Number, Converter, Setting, Representation >.
Definition at line 100 of file RootGrowNode.h.
Referenced by hypro::convertSettings().
template<typename Number, typename Converter, typename Setting> virtual unsigned hypro::RootGrowNode< Number, Converter, Setting >::getOriginCount () const inline virtual
Reimplemented in hypro::TrafoOp< Number, Converter, Setting >, hypro::Leaf< Number, Converter, Setting, Representation >, hypro::IntersectOp< Number, Converter, Setting >, hypro::IntersectHalfspaceOp< Number, Converter, Setting >, hypro::ScaleOp< Number, Converter, Setting >, hypro::ProjectOp< Number, Converter, Setting >, hypro::SumOp< Number, Converter, Setting >, and hypro::UnionOp< Number, Converter, Setting >.
Definition at line 87 of file RootGrowNode.h.
template<typename Number, typename Converter, typename Setting> virtual SFNEW_TYPE hypro::RootGrowNode< Number, Converter, Setting >::getType () const inline virtual
Reimplemented in hypro::TrafoOp< Number, Converter, Setting >, hypro::Leaf< Number, Converter, Setting, Representation >, hypro::IntersectOp< Number, Converter, Setting >, hypro::IntersectHalfspaceOp< Number, Converter, Setting >, hypro::ScaleOp< Number, Converter, Setting >, hypro::ProjectOp< Number, Converter, Setting >, hypro::SumOp< Number, Converter, Setting >, and hypro::UnionOp< Number, Converter, Setting >.
Definition at line 86 of file RootGrowNode.h.
Referenced by hypro::convertSettings().
template<typename Number, typename Converter, typename Setting> virtual std::vector<std::size_t> hypro::RootGrowNode< Number, Converter, Setting >::intersectDims (const std::vector< std::vector< std::size_t >> & dims) const inline virtual
Reimplemented in hypro::IntersectOp< Number, Converter, Setting >, hypro::SumOp< Number, Converter, Setting >, hypro::ProjectOp< Number, Converter, Setting >, and hypro::UnionOp< Number, Converter, Setting >.
Definition at line 184 of file RootGrowNode.h.
References dims.
template<typename Number, typename Converter, typename Setting> virtual SETSTATE hypro::RootGrowNode< Number, Converter, Setting >::isEmpty () const inline virtual
Definition at line 91 of file RootGrowNode.h.
template<typename Number, typename Converter, typename Setting> virtual void hypro::RootGrowNode< Number, Converter, Setting >::print (std::ostream & ostr) const inline virtual
Reimplemented in hypro::Leaf< Number, Converter, Setting, Representation >.
Definition at line 111 of file RootGrowNode.h.
References c, and hypro::detail::getType().
template<typename Number, typename Converter, typename Setting> virtual vector_t<Number> hypro::RootGrowNode< Number, Converter, Setting >::reverseOp (const vector_t< Number > & point) const inline virtual
Reimplemented in hypro::IntersectHalfspaceOp< Number, Converter, Setting >, hypro::TrafoOp< Number, Converter, Setting >, hypro::ScaleOp< Number, Converter, Setting >, and hypro::ProjectOp< Number, Converter, Setting >.
Definition at line 174 of file RootGrowNode.h.
References point.
template<typename Number, typename Converter, typename Setting> virtual PointerVec& hypro::RootGrowNode< Number, Converter, Setting >::rGetChildren () inline virtual
Definition at line 89 of file RootGrowNode.h.
template<typename Number, typename Converter, typename Setting> virtual void hypro::RootGrowNode< Number, Converter, Setting >::setDimension (const std::size_t d) inline virtual
Reimplemented in hypro::TrafoOp< Number, Converter, Setting >, hypro::Leaf< Number, Converter, Setting, Representation >, hypro::IntersectHalfspaceOp< Number, Converter, Setting >, hypro::IntersectOp< Number, Converter, Setting >, hypro::ScaleOp< Number, Converter, Setting >, hypro::ProjectOp< Number, Converter, Setting >, hypro::SumOp< Number, Converter, Setting >, and hypro::UnionOp< Number, Converter, Setting >.
Definition at line 102 of file RootGrowNode.h.
References d.
template<typename Number, typename Converter, typename Setting> virtual Point<Number> hypro::RootGrowNode< Number, Converter, Setting >::supremumPoint () const inline virtual
Reimplemented in hypro::Leaf< Number, Converter, Setting, Representation >.
Definition at line 165 of file RootGrowNode.h.
References assert().
template<typename Number, typename Converter, typename Setting> virtual Point<Number> hypro::RootGrowNode< Number, Converter, Setting >::supremumPoint (std::vector< Point< Number >> &) const inline virtual
Reimplemented in hypro::IntersectHalfspaceOp< Number, Converter, Setting >, hypro::IntersectOp< Number, Converter, Setting >, hypro::TrafoOp< Number, Converter, Setting >, hypro::SumOp< Number, Converter, Setting >, hypro::UnionOp< Number, Converter, Setting >, hypro::ScaleOp< Number, Converter, Setting >, and hypro::ProjectOp< Number, Converter, Setting >.
Definition at line 169 of file RootGrowNode.h.
References assert().
template<typename Number, typename Converter, typename Setting> virtual matrix_t<Number> hypro::RootGrowNode< Number, Converter, Setting >::transform (const matrix_t< Number > & param) const pure virtual
Implemented in hypro::TrafoOp< Number, Converter, Setting >, hypro::Leaf< Number, Converter, Setting, Representation >, hypro::IntersectHalfspaceOp< Number, Converter, Setting >, hypro::IntersectOp< Number, Converter, Setting >, hypro::ScaleOp< Number, Converter, Setting >, hypro::ProjectOp< Number, Converter, Setting >, hypro::SumOp< Number, Converter, Setting >, and hypro::UnionOp< Number, Converter, Setting >.
Friends And Related Function Documentation
template<typename Number, typename Converter, typename Setting> std::ostream& operator<< (std::ostream & ostr, const RootGrowNode< Number, Converter, Setting > & r) friend
Definition at line 123 of file RootGrowNode.h.
Member Data Documentation
template<typename Number, typename Converter, typename Setting> PointerVec hypro::RootGrowNode< Number, Converter, Setting >::mChildren = PointerVec() protected
Definition at line 74 of file RootGrowNode.h.
template<typename Number, typename Converter, typename Setting> std::size_t hypro::RootGrowNode< Number, Converter, Setting >::mDimension = 0 protected
Definition at line 75 of file RootGrowNode.h.
template<typename Number, typename Converter, typename Setting> SETSTATE hypro::RootGrowNode< Number, Converter, Setting >::mEmptyState = SETSTATE::UNKNOWN mutable protected
Definition at line 76 of file RootGrowNode.h.
template<typename Number, typename Converter, typename Setting> SFNEW_TYPE hypro::RootGrowNode< Number, Converter, Setting >::mType = NODE protected
Definition at line 72 of file RootGrowNode.h.
template<typename Number, typename Converter, typename Setting> unsigned hypro::RootGrowNode< Number, Converter, Setting >::originCount = 0 protected
Definition at line 73 of file RootGrowNode.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunctionNew/IntersectHalfspaceOp.h
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunctionNew/RootGrowNode.h