HyPro: hypro::ConstraintSetT< Number, S > Class Template Reference
hypro::ConstraintSetT< Number, S > Class Template Reference
State set representations
A class representing a plain constraint set. This class is intended to serve as a container.
#include <ConstraintSet.h>
Public Types
typedef S Settings
typedef Number NumberType
Public Member Functions
ConstraintSetT ()
Creates an empty constraintSet.
ConstraintSetT (const ConstraintSetT &orig)=default
Copy constructor.
ConstraintSetT (ConstraintSetT &&orig)=default
Move constructor.
ConstraintSetT (const matrix_t< Number > &_constraints, const vector_t< Number > &_constants)
Constructor from a matrix and a vector.
ConstraintSetT (const matrix_t< Number > &_constraints)
Constructor from a matrix and a vector.
~ConstraintSetT ()
Destructor.
const matrix_t< Number > & matrix () const
const vector_t< Number > & vector () const
matrix_t< Number > & rMatrix ()
vector_t< Number > & rVector ()
void setMatrix (const matrix_t< Number > &in)
void setVector (const vector_t< Number > &in)
bool isAxisAligned () const
bool empty () const
Determines if the current constraintSet is empty.
void addConstraint (const vector_t< Number > &normal, Number offset)
std::vector< Point< Number > > vertices (const matrix_t< Number > &=matrix_t< Number >::Zero(0, 0)) const
Getter for a vertex-representation of the current constraintSet.
ConstraintSetT< Number, S > & operator= (const ConstraintSetT< Number, S > &rhs)=default
Assignment operator.
ConstraintSetT< Number, S > & operator= (ConstraintSetT< Number, S > &&rhs)=default
Move assignment operator.
std::size_t dimension () const
Getter for the space dimension.
void removeRedundancy ()
Removes redundancy (part of the general interface. Does nothing for constraintSets.)
std::size_t size () const
Storage size determination.
const ConstraintSetT & reduceNumberRepresentation (unsigned)
Function to reduce the number representation (over-approximate).
std::pair< CONTAINMENT, ConstraintSetT > satisfiesHalfspace (const Halfspace< Number > &) const
std::pair< CONTAINMENT, ConstraintSetT > satisfiesHalfspaces (const matrix_t< Number > &, const vector_t< Number > &) const
ConstraintSetT project (const std::vector< std::size_t > &) const
ConstraintSetT assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const
ConstraintSetT linearTransformation (const matrix_t< Number > &) const
ConstraintSetT affineTransformation (const matrix_t< Number > &, const vector_t< Number > &) const
ConstraintSetT minkowskiSum (const ConstraintSetT &) const
ConstraintSetT intersect (const ConstraintSetT &) const
Computes the intersection of two constraintSets.
ConstraintSetT intersectHalfspace (const Halfspace< Number > &) const
ConstraintSetT intersectHalfspaces (const matrix_t< Number > &, const vector_t< Number > &) const
bool contains (const Point< Number > &) const
bool contains (const ConstraintSetT &) const
Containment check for a constraintSet.
ConstraintSetT unite (const ConstraintSetT &) const
Computes the union of two constraintSets.
void reduceRepresentation ()
Does nothing as a ConstraintSet is only a container.
void clear ()
Makes this constraintSet the empty constraintSet.
Static Public Member Functions
static representation_name type ()
static ConstraintSetT unite (const std::vector< ConstraintSetT > &)
Computes the union of the current constraintSet with a set of constraintSets.
Private Attributes
matrix_t< Number > mConstraints
vector_t< Number > mConstants
TRIBOOL mIsBox = TRIBOOL::NSET
Friends
bool operator== (const ConstraintSetT< Number, S > &b1, const ConstraintSetT< Number, S > &b2)
Checks if two constraintSets are equal.
bool operator!= (const ConstraintSetT< Number, S > &b1, const ConstraintSetT< Number, S > &b2)
Determines inequality of two constraintSets.
std::ostream & operator<< (std::ostream &ostr, const ConstraintSetT< Number, S > &b)
Outstream operator.
Detailed Description
template<typename Number, typename S = ConstraintSetSettings>
class hypro::ConstraintSetT< Number, S >
A class representing a plain constraint set. This class is intended to serve as a container.
A constraint set in this case is a datastructure similar to a H-Polytope but without any functionality. The idea is just to have a container for data received from the parser or as an intermediate type.
Template Parameters
Number The used number type.
Converter The used converter. @{
Definition at line 26 of file ConstraintSet.h.
Member Typedef Documentation
template<typename Number, typename S = ConstraintSetSettings> typedef Number hypro::ConstraintSetT< Number, S >::NumberType
Definition at line 33 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> typedef S hypro::ConstraintSetT< Number, S >::Settings
Definition at line 32 of file ConstraintSet.h.
Constructor & Destructor Documentation
template<typename Number, typename S = ConstraintSetSettings> hypro::ConstraintSetT< Number, S >::ConstraintSetT () inline
Creates an empty constraintSet.
The empty constraintSet is represented by a zero-dimensional point pair.
Definition at line 49 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> hypro::ConstraintSetT< Number, S >::ConstraintSetT (const ConstraintSetT< Number, S > & orig) default
Copy constructor.
Parameters
[in] orig The original.
template<typename Number, typename S = ConstraintSetSettings> hypro::ConstraintSetT< Number, S >::ConstraintSetT (ConstraintSetT< Number, S > && orig) default
Move constructor.
Parameters
[in] orig The original.
template<typename Number, typename S = ConstraintSetSettings> hypro::ConstraintSetT< Number, S >::ConstraintSetT (const matrix_t< Number > & _constraints, const vector_t< Number > & _constants) inline
Constructor from a matrix and a vector.
Constructs a constraintSet assuming each row of the matrix is the normal to a hyperplane and its corresponding entry in the given vector is the offset.
Parameters
_constraints A matrix representing the constraint normals.
_constants A vector representing the offsets of the corresponting hyperplane.
Definition at line 72 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> hypro::ConstraintSetT< Number, S >::ConstraintSetT (const matrix_t< Number > & _constraints) inline explicit
Constructor from a matrix and a vector.
Constructs a constraintSet assuming each row of the matrix is the normal to a hyperplane and its corresponding entry in the given vector is the offset.
Parameters
_constraints A matrix representing the constraint normals.
_constants A vector representing the offsets of the corresponting hyperplane.
Definition at line 83 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> hypro::ConstraintSetT< Number, S >::~ConstraintSetT () inline
Destructor.
Definition at line 90 of file ConstraintSet.h.
Member Function Documentation
template<typename Number, typename S = ConstraintSetSettings> void hypro::ConstraintSetT< Number, S >::addConstraint (const vector_t< Number > & normal, Number offset) inline
Definition at line 121 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> ConstraintSetT hypro::ConstraintSetT< Number, S >::affineTransformation (const matrix_t< Number > & , const vector_t< Number > &) const inline
Definition at line 226 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> ConstraintSetT hypro::ConstraintSetT< Number, S >::assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const inline
Definition at line 223 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> void hypro::ConstraintSetT< Number, S >::clear () inline
Makes this constraintSet the empty constraintSet.
Definition at line 273 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> bool hypro::ConstraintSetT< Number, S >::contains (const Point< Number > &) const inline
Definition at line 238 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> bool hypro::ConstraintSetT< Number, S >::contains (const ConstraintSetT< Number, S > &) const inline
Containment check for a constraintSet.
Parameters
[in] constraintSet The constraintSet.
Returns
True, if the given constraintSet is contained in the current constraintSet, false otherwise.
Definition at line 245 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> std::size_t hypro::ConstraintSetT< Number, S >::dimension () const inline
Getter for the space dimension.
Returns
The dimension of the space.
Definition at line 194 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> bool hypro::ConstraintSetT< Number, S >::empty () const inline
Determines if the current constraintSet is empty.
The method invokes the linear optimizer to check for the existence of a solution.
Returns
True, if the represented set is empty, False otherwise.
Definition at line 117 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> ConstraintSetT hypro::ConstraintSetT< Number, S >::intersect (const ConstraintSetT< Number, S > &) const inline
Computes the intersection of two constraintSets.
Parameters
[in] rhs The right hand side constraintSet.
Returns
The resulting constraintSet.
Definition at line 234 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> ConstraintSetT hypro::ConstraintSetT< Number, S >::intersectHalfspace (const Halfspace< Number > &) const inline
Definition at line 236 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> ConstraintSetT hypro::ConstraintSetT< Number, S >::intersectHalfspaces (const matrix_t< Number > & , const vector_t< Number > &) const inline
Definition at line 237 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> bool hypro::ConstraintSetT< Number, S >::isAxisAligned () const inline
Definition at line 105 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> ConstraintSetT hypro::ConstraintSetT< Number, S >::linearTransformation (const matrix_t< Number > &) const inline
Definition at line 225 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> const matrix_t<Number>& hypro::ConstraintSetT< Number, S >::matrix () const inline
Definition at line 96 of file ConstraintSet.h.
Referenced by hypro::convert(), hypro::AffineTransformation< N >::isIdentity(), std::hash< hypro::AffineTransformation< Number > >::operator()(), and hypro::toFlowstarFormat().
template<typename Number, typename S = ConstraintSetSettings> ConstraintSetT hypro::ConstraintSetT< Number, S >::minkowskiSum (const ConstraintSetT< Number, S > &) const inline
Definition at line 227 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> ConstraintSetT<Number, S>& hypro::ConstraintSetT< Number, S >::operator= (const ConstraintSetT< Number, S > & rhs) default
Assignment operator.
Parameters
rhs A constraintSet.
template<typename Number, typename S = ConstraintSetSettings> ConstraintSetT<Number, S>& hypro::ConstraintSetT< Number, S >::operator= (ConstraintSetT< Number, S > && rhs) default
Move assignment operator.
Parameters
rhs A constraintSet.
template<typename Number, typename S = ConstraintSetSettings> ConstraintSetT hypro::ConstraintSetT< Number, S >::project (const std::vector< std::size_t > &) const inline
Definition at line 222 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> const ConstraintSetT& hypro::ConstraintSetT< Number, S >::reduceNumberRepresentation (unsigned) inline
Function to reduce the number representation (over-approximate).
The function tries to reduce the size of each interval boundary in case it is larger than some specified limit. This is done by outward rounding.
Parameters
[in] limit The limit
Definition at line 217 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> void hypro::ConstraintSetT< Number, S >::reduceRepresentation () inline
Does nothing as a ConstraintSet is only a container.
Definition at line 267 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> void hypro::ConstraintSetT< Number, S >::removeRedundancy () inline
Removes redundancy (part of the general interface. Does nothing for constraintSets.)
Definition at line 199 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> matrix_t<Number>& hypro::ConstraintSetT< Number, S >::rMatrix () inline
Definition at line 99 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> vector_t<Number>& hypro::ConstraintSetT< Number, S >::rVector () inline
Definition at line 100 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> std::pair<CONTAINMENT, ConstraintSetT> hypro::ConstraintSetT< Number, S >::satisfiesHalfspace (const Halfspace< Number > &) const inline
Definition at line 219 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> std::pair<CONTAINMENT, ConstraintSetT> hypro::ConstraintSetT< Number, S >::satisfiesHalfspaces (const matrix_t< Number > & , const vector_t< Number > &) const inline
Definition at line 220 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> void hypro::ConstraintSetT< Number, S >::setMatrix (const matrix_t< Number > & in) inline
Definition at line 102 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> void hypro::ConstraintSetT< Number, S >::setVector (const vector_t< Number > & in) inline
Definition at line 103 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> std::size_t hypro::ConstraintSetT< Number, S >::size () const inline
Storage size determination.
Returns
Size of the required memory.
Definition at line 206 of file ConstraintSet.h.
Referenced by hypro::AffineTransformation< N >::size().
template<typename Number, typename S = ConstraintSetSettings> static representation_name hypro::ConstraintSetT< Number, S >::type () inline static
Definition at line 208 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> ConstraintSetT hypro::ConstraintSetT< Number, S >::unite (const ConstraintSetT< Number, S > &) const inline
Computes the union of two constraintSets.
Parameters
[in] rhs The right hand side constraintSet.
Returns
The resulting constraintSet.
Definition at line 255 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> static ConstraintSetT hypro::ConstraintSetT< Number, S >::unite (const std::vector< ConstraintSetT< Number, S > > &) inline static
Computes the union of the current constraintSet with a set of constraintSets.
Parameters
[in] constraintSets The constraintSets.
Returns
The resulting constraintSet.
Definition at line 262 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> const vector_t<Number>& hypro::ConstraintSetT< Number, S >::vector () const inline
Definition at line 97 of file ConstraintSet.h.
Referenced by hypro::convert(), hypro::AffineTransformation< N >::isIdentity(), std::hash< hypro::AffineTransformation< Number > >::operator()(), and hypro::toFlowstarFormat().
template<typename Number, typename S = ConstraintSetSettings> std::vector<Point<Number> > hypro::ConstraintSetT< Number, S >::vertices (const matrix_t< Number > & = matrix_t<Number>::Zero(0, 0)) const inline
Getter for a vertex-representation of the current constraintSet.
Not implemented.
Returns
An empty vector of points.
Definition at line 141 of file ConstraintSet.h.
Friends And Related Function Documentation
template<typename Number, typename S = ConstraintSetSettings> bool operator!= (const ConstraintSetT< Number, S > & b1, const ConstraintSetT< Number, S > & b2) friend
Determines inequality of two constraintSets.
Parameters
b1 A constraintSet.
b2 A constraintSet.
Returns
False, if both constraintSets are equal.
Definition at line 162 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> std::ostream& operator<< (std::ostream & ostr, const ConstraintSetT< Number, S > & b) friend
Outstream operator.
Parameters
ostr Outstream.
b A constraintSet.
Definition at line 181 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> bool operator== (const ConstraintSetT< Number, S > & b1, const ConstraintSetT< Number, S > & b2) friend
Checks if two constraintSets are equal.
Parameters
b1 Contains the first constraintSet.
b2 Contains the second constraintSet.
Returns
True, if they are equal.
Definition at line 149 of file ConstraintSet.h.
Member Data Documentation
template<typename Number, typename S = ConstraintSetSettings> vector_t<Number> hypro::ConstraintSetT< Number, S >::mConstants private
Vector describing the constant parts for the respective constraints.
Definition at line 37 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> matrix_t<Number> hypro::ConstraintSetT< Number, S >::mConstraints private
Matrix describing the linear constraints.
Definition at line 36 of file ConstraintSet.h.
template<typename Number, typename S = ConstraintSetSettings> TRIBOOL hypro::ConstraintSetT< Number, S >::mIsBox = TRIBOOL::NSET mutable private
Definition at line 38 of file ConstraintSet.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/ConstraintSet/ConstraintSet.h