HyPro: hypro::Condition< Number > Class Template Reference
hypro::Condition< Number > Class Template Reference
#include <Condition.h>
Public Member Functions
Condition ()=default
cache for the hash value
Condition (const matrix_t< Number > &mat, const vector_t< Number > &vec)
Condition (const ConstraintSetT< Number > &constraints)
Condition (const std::vector< std::variant< ConstraintSetT< Number >>> &sets)
Condition (const Condition &orig)=default
Condition (Condition &&orig)=default
Condition & operator= (const Condition &orig)=default
Condition & operator= (Condition &&orig)=default
~Condition ()
std::size_t size () const
bool empty () const
const matrix_t< Number > & getMatrix (std::size_t I=0) const
const vector_t< Number > & getVector (std::size_t I=0) const
bool isAxisAligned () const
bool isAxisAligned (std::size_t i) const
void setMatrix (const matrix_t< Number > &m, std::size_t I=0)
void setVector (const vector_t< Number > &v, std::size_t I=0)
const std::vector< ConstraintSetT< Number > > & constraints () const
std::size_t hash () const
std::string getDotRepresentation (const std::vector< std::string > &vars) const
void decompose (const Decomposition &decomposition)
Private Member Functions
void checkAxisAligned (std::size_t i) const
Private Attributes
std::vector< ConstraintSetT< Number > > mConstraints
std::vector< TRIBOOL > mConditionIsBox
holds the constraints specifying the condition
std::size_t mHash = 0
cache to check whether constraints are axis-aligned
Friends
bool operator== (const Condition &lhs, const Condition &rhs)
bool operator!= (const Condition &lhs, const Condition &rhs)
std::ostream & operator<< (std::ostream &out, const Condition &in)
Detailed Description
template<typename Number>
class hypro::Condition< Number >
Definition at line 13 of file Condition.h.
Constructor & Destructor Documentation
template<typename Number> hypro::Condition< Number >::Condition () default
cache for the hash value
Referenced by hypro::Condition< N >::Condition().
template<typename Number> hypro::Condition< Number >::Condition (const matrix_t< Number > & mat, const vector_t< Number > & vec) inline
Definition at line 20 of file Condition.h.
template<typename Number> hypro::Condition< Number >::Condition (const ConstraintSetT< Number > & constraints) inline explicit
Definition at line 24 of file Condition.h.
template<typename Number> hypro::Condition< Number >::Condition (const std::vector< std::variant< ConstraintSetT< Number >>> & sets) explicit
template<typename Number> hypro::Condition< Number >::Condition (const Condition< Number > & orig) default
template<typename Number> hypro::Condition< Number >::Condition (Condition< Number > && orig) default
template<typename Number> hypro::Condition< Number >::~Condition () inline
Definition at line 33 of file Condition.h.
Member Function Documentation
template<typename Number> void hypro::Condition< Number >::checkAxisAligned (std::size_t i) const private
template<typename Number> const std::vector<ConstraintSetT<Number> >& hypro::Condition< Number >::constraints () const inline
Definition at line 54 of file Condition.h.
Referenced by std::hash< hypro::Condition< Number > >::operator()().
template<typename Number> void hypro::Condition< Number >::decompose (const Decomposition & decomposition)
decomposes constraint set of this condition
Referenced by hypro::Condition< N >::constraints(), and hypro::Transition< N >::decompose().
template<typename Number> bool hypro::Condition< Number >::empty () const inline
Definition at line 37 of file Condition.h.
template<typename Number> std::string hypro::Condition< Number >::getDotRepresentation (const std::vector< std::string > & vars) const
Referenced by hypro::Condition< N >::constraints().
template<typename Number> const matrix_t<Number>& hypro::Condition< Number >::getMatrix (std::size_t I = 0) const inline
Definition at line 39 of file Condition.h.
Referenced by hypro::Flowpipe< hypro::State >::selectSatisfyingStates(), and hypro::toFlowstarFormat().
template<typename Number> const vector_t<Number>& hypro::Condition< Number >::getVector (std::size_t I = 0) const inline
Definition at line 43 of file Condition.h.
Referenced by hypro::Flowpipe< hypro::State >::selectSatisfyingStates(), and hypro::toFlowstarFormat().
template<typename Number> std::size_t hypro::Condition< Number >::hash () const
Referenced by hypro::Condition< N >::constraints().
template<typename Number> bool hypro::Condition< Number >::isAxisAligned () const
Referenced by hypro::Condition< N >::getVector().
template<typename Number> bool hypro::Condition< Number >::isAxisAligned (std::size_t i) const
template<typename Number> Condition& hypro::Condition< Number >::operator= (const Condition< Number > & orig) default
Referenced by hypro::Condition< N >::Condition().
template<typename Number> Condition& hypro::Condition< Number >::operator= (Condition< Number > && orig) default
template<typename Number> void hypro::Condition< Number >::setMatrix (const matrix_t< Number > & m, std::size_t I = 0)
Referenced by hypro::Condition< N >::getVector(), and main().
template<typename Number> void hypro::Condition< Number >::setVector (const vector_t< Number > & v, std::size_t I = 0)
Referenced by hypro::Condition< N >::getVector(), and main().
template<typename Number> std::size_t hypro::Condition< Number >::size () const inline
Definition at line 36 of file Condition.h.
Referenced by hypro::toFlowstarFormat().
Friends And Related Function Documentation
template<typename Number> bool operator!= (const Condition< Number > & lhs, const Condition< Number > & rhs) friend
Definition at line 82 of file Condition.h.
template<typename Number> std::ostream& operator<< (std::ostream & out, const Condition< Number > & in) friend
Definition at line 87 of file Condition.h.
template<typename Number> bool operator== (const Condition< Number > & lhs, const Condition< Number > & rhs) friend
Definition at line 69 of file Condition.h.
Member Data Documentation
template<typename Number> std::vector<TRIBOOL> hypro::Condition< Number >::mConditionIsBox mutable private
holds the constraints specifying the condition
Definition at line 16 of file Condition.h.
Referenced by hypro::Condition< N >::Condition().
template<typename Number> std::vector<ConstraintSetT<Number> > hypro::Condition< Number >::mConstraints private
Definition at line 15 of file Condition.h.
Referenced by hypro::Condition< N >::constraints().
template<typename Number> std::size_t hypro::Condition< Number >::mHash = 0 mutable private
cache to check whether constraints are axis-aligned
Definition at line 17 of file Condition.h.
Referenced by hypro::Condition< N >::Condition().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/Condition.h