HyPro: hypro::EventTimingProvider< Number > Class Template Reference
hypro::EventTimingProvider< Number > Class Template Reference
Public Member Functions
void initialize (const HybridAutomaton< Number > &ha, tNumber globalTimeHorizon)
void initialize (const Location< Number > *loc, tNumber globalTimeHorizon)
void setName (const std::string &name)
const std::string & getName () const
EventTimingNode< Number > * getRoot ()
void clear ()
const EventTimingNode< Number > * getTimingNode (const Path< Number, tNumber > &path, std::size_t level=0) const
Find the best suitable node in the timing tree which matches the passed path.
EventTimingNode< Number > * rGetNode (const Path< Number, tNumber > &path, std::size_t level=0) const
Find the best suitable node in the timing tree which matches the passed path.
std::optional< EventTimingContainer< Number > > getTimings (const Path< Number, tNumber > &path) const
void updateTimings (const Path< Number, tNumber > &path, const EventTimingContainer< Number > &update)
EventTimingNode< Number >::Node_t addChildToNode (typename EventTimingNode< Number >::Node_t parent, tNumber timeHorizon)
std::string getDotRepresentation () const
Protected Member Functions
EventTimingProvider ()
Detailed Description
template<typename Number>
class hypro::EventTimingProvider< Number >
Definition at line 18 of file EventTimingProvider.h.
Constructor & Destructor Documentation
template<typename Number > hypro::EventTimingProvider< Number >::EventTimingProvider () protected
Definition at line 6 of file EventTimingProvider.tpp.
Member Function Documentation
template<typename Number > EventTimingNode< Number >::Node_t hypro::EventTimingProvider< Number >::addChildToNode (typename EventTimingNode< Number >::Node_t parent, tNumber timeHorizon)
Definition at line 257 of file EventTimingProvider.tpp.
References hypro::DAGNode< EventTimingNode< Number > >::addChild(), and hypro::DAGNode< EventTimingNode< Number > >::addParent().
Referenced by hypro::EventTimingProvider< Number >::clear(), and hypro::updateTiming().
template<typename Number > void hypro::EventTimingProvider< Number >::clear () inline
Definition at line 37 of file EventTimingProvider.h.
References hypro::EventTimingProvider< Number >::addChildToNode(), hypro::EventTimingProvider< Number >::getDotRepresentation(), hypro::EventTimingProvider< Number >::getTimingNode(), hypro::EventTimingProvider< Number >::getTimings(), hypro::EventTimingProvider< Number >::rGetNode(), and hypro::EventTimingProvider< Number >::updateTimings().
Referenced by hypro::EventTimingProvider< Number >::initialize().
template<typename Number > std::string hypro::EventTimingProvider< Number >::getDotRepresentation () const
Definition at line 271 of file EventTimingProvider.tpp.
References hypro::Path< Number, tNumber >::begin(), and hypro::Path< Number, tNumber >::end().
Referenced by hypro::EventTimingProvider< Number >::clear().
template<typename Number > const std::string& hypro::EventTimingProvider< Number >::getName () const inline
Definition at line 33 of file EventTimingProvider.h.
template<typename Number > EventTimingNode<Number>* hypro::EventTimingProvider< Number >::getRoot () inline
Definition at line 35 of file EventTimingProvider.h.
template<typename Number > const EventTimingNode< Number > * hypro::EventTimingProvider< Number >::getTimingNode (const Path< Number, tNumber > & path, std::size_t level = 0) const
Find the best suitable node in the timing tree which matches the passed path.
Definition at line 67 of file EventTimingProvider.tpp.
Referenced by hypro::EventTimingProvider< Number >::clear().
template<typename Number > std::optional< EventTimingContainer< Number > > hypro::EventTimingProvider< Number >::getTimings (const Path< Number, tNumber > & path) const
Definition at line 77 of file EventTimingProvider.tpp.
References hypro::Path< Number, tNumber >::begin(), hypro::Path< Number, tNumber >::end(), hypro::FULL, hypro::PARTIAL, hypro::HierarchicalIntervalVector< T, Number >::setTypeOrder(), hypro::unite(), and hypro::YES.
Referenced by hypro::EventTimingProvider< Number >::clear(), hypro::LTIContext< State >::execOnStart(), and hypro::RectangularContext< State >::execOnStart().
template<typename Number > void hypro::EventTimingProvider< Number >::initialize (const HybridAutomaton< Number > & ha, tNumber globalTimeHorizon)
Definition at line 15 of file EventTimingProvider.tpp.
References hypro::DAGNode< EventTimingNode< Number > >::addParent(), hypro::EventTimingProvider< Number >::clear(), hypro::HybridAutomaton< Number >::getInitialStates(), hypro::EventTimingNode< Number >::setEntryTimestamp(), and hypro::EventTimingNode< Number >::setLocation().
template<typename Number > void hypro::EventTimingProvider< Number >::initialize (const Location< Number > * loc, tNumber globalTimeHorizon)
Definition at line 49 of file EventTimingProvider.tpp.
References hypro::DAGNode< EventTimingNode< Number > >::addParent(), hypro::EventTimingProvider< Number >::clear(), hypro::EventTimingNode< Number >::setEntryTimestamp(), and hypro::EventTimingNode< Number >::setLocation().
template<typename Number > EventTimingNode< Number > * hypro::EventTimingProvider< Number >::rGetNode (const Path< Number, tNumber > & path, std::size_t level = 0) const
Find the best suitable node in the timing tree which matches the passed path.
Definition at line 72 of file EventTimingProvider.tpp.
Referenced by hypro::EventTimingProvider< Number >::clear(), hypro::LTIContext< State >::execOnEnd(), hypro::RectangularContext< State >::execOnEnd(), hypro::LTIContext< State >::execOnStart(), hypro::RectangularContext< State >::execOnStart(), and hypro::EventTimingProvider< Number >::updateTimings().
template<typename Number > void hypro::EventTimingProvider< Number >::setName (const std::string & name) inline
Definition at line 32 of file EventTimingProvider.h.
template<typename Number > void hypro::EventTimingProvider< Number >::updateTimings (const Path< Number, tNumber > & path, const EventTimingContainer< Number > & update)
Definition at line 246 of file EventTimingProvider.tpp.
References hypro::EventTimingProvider< Number >::rGetNode().
Referenced by hypro::EventTimingProvider< Number >::clear(), hypro::LTIContext< State >::execBeforeFirstSegment(), hypro::RectangularContext< State >::execBeforeFirstSegment(), hypro::RectangularContext< State >::intersectBadStates(), and hypro::LTIContext< State >::intersectBadStates().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/timing/EventTimingProvider.h
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/timing/EventTimingProvider.tpp