HyPro: hypro::TaylorModel< Number > Class Template Reference
hypro::TaylorModel< Number > Class Template Reference
Public Member Functions
TaylorModel ()
~TaylorModel ()
TaylorModel (const MultivariatePolynomial< carl::Interval< Number >> &p, const carl::Interval< Number > &r)
TaylorModel (const MultivariatePolynomial< carl::Interval< Number >> &p)
TaylorModel (const carl::Interval< Number > &I)
TaylorModel (const TaylorModel< Number > &tm)
TaylorModel (const std::initializer_list< Term< carl::Interval< Number >>> &terms)
TaylorModel (const std::initializer_list< Term< carl::Interval< Number >>> &terms, const carl::Interval< Number > &r)
TaylorModel (const Term< carl::Interval< Number >> &term)
TaylorModel (carl::Variable::Arg v)
bool isZero () const
bool isConstant () const
bool isLinear () const
carl::Interval< Number > rmConstantTerm ()
exponent tmOrder () const
TaylorModel< Number > pow (unsigned exp, Domain< Number > &domain, const exponent order) const
void checkConsistency () const
bool has (carl::Variable::Arg v) const
void cutoff (const carl::Interval< Number > &threshold, Domain< Number > &domain)
void cutoff_nr (const carl::Interval< Number > &threshold, Domain< Number > &domain)
void truncation (const exponent order, Domain< Number > &domain)
void truncation_nr (const exponent order)
void enclosure (carl::Interval< Number > &I, Domain< Number > &domain) const
void poly_enclosure (carl::Interval< Number > &I, Domain< Number > &domain) const
void normalize (Domain< Number > &domain)
TaylorModel< Number > & operator= (const TaylorModel< Number > &tm)
TaylorModel< Number > & operator+= (const TaylorModel< Number > &tm)
TaylorModel< Number > & operator-= (const TaylorModel< Number > &tm)
const TaylorModel< Number > operator+ (const TaylorModel< Number > &tm) const
const TaylorModel< Number > operator- (const TaylorModel< Number > &tm) const
TaylorModel< Number > multiply (const carl::Interval< Number > &I) const
TaylorModel< Number > multiply (const TaylorModel< Number > &tm, Domain< Number > &domain, const exponent order) const
TaylorModel< Number > multiply (const Term< carl::Interval< Number >> &term, Domain< Number > &domain, const exponent order) const
TaylorModel< Number > multiply (carl::Variable::Arg v, Domain< Number > &domain, const exponent order) const
void multiply_assign (const carl::Interval< Number > &I)
void multiply_assign (const TaylorModel< Number > &tm, Domain< Number > &domain, const exponent order)
void multiply_assign (const Term< carl::Interval< Number >> &term, Domain< Number > &domain, const exponent order)
void multiply_assign (carl::Variable::Arg v, Domain< Number > &domain, const exponent order)
TaylorModel< Number > div (const carl::Interval< Number > &I) const
void div_assign (const carl::Interval< Number > &I)
TaylorModel< Number > substitute (const std::map< carl::Variable, TaylorModel< Number >> &substitutions, Domain< Number > &domain, const exponent order) const
TaylorModel< Number > substitute (const TaylorModelVec< Number > &substitutions, Domain< Number > &domain, const exponent order) const
TaylorModel< Number > derivative (carl::Variable::Arg v, unsigned nth=1) const
void derivative_assign (carl::Variable::Arg v, unsigned nth=1)
TaylorModel< Number > LieDerivative (const PolynomialODE< Number > &ode) const
void LieDerivative_assign (const PolynomialODE< Number > &ode)
TaylorModel< Number > integration (carl::Variable::Arg v, const carl::Interval< Number > &range_of_v)
void integration_assign (carl::Variable::Arg v, const carl::Interval< Number > &range_of_v)
Protected Types
using TermsType = std::vector< Term< carl::Interval< Number >>>
using MonomialType = std::shared_ptr< const Monomial >
Friends
class Flowpipe< Number >
template<typename N >
std::ostream & operator<< (std::ostream &os, const TaylorModel< N > &tm)
Detailed Description
template<typename Number>
class hypro::TaylorModel< Number >
Definition at line 74 of file TaylorModel.h.
Member Typedef Documentation
template<typename Number> using hypro::TaylorModel< Number >::MonomialType = std::shared_ptr<const Monomial> protected
Definition at line 81 of file TaylorModel.h.
template<typename Number> using hypro::TaylorModel< Number >::TermsType = std::vector<Term<carl::Interval<Number>>> protected
Definition at line 80 of file TaylorModel.h.
Constructor & Destructor Documentation
template<typename Number > hypro::TaylorModel< Number >::TaylorModel ()
Definition at line 13 of file TaylorModel.tpp.
template<typename Number > hypro::TaylorModel< Number >::~TaylorModel ()
Definition at line 19 of file TaylorModel.tpp.
template<typename Number > hypro::TaylorModel< Number >::TaylorModel (const MultivariatePolynomial< carl::Interval< Number >> & p, const carl::Interval< Number > & r)
Definition at line 23 of file TaylorModel.tpp.
template<typename Number > hypro::TaylorModel< Number >::TaylorModel (const MultivariatePolynomial< carl::Interval< Number >> & p) explicit
Definition at line 29 of file TaylorModel.tpp.
template<typename Number > hypro::TaylorModel< Number >::TaylorModel (const carl::Interval< Number > & I) explicit
Definition at line 37 of file TaylorModel.tpp.
template<typename Number > hypro::TaylorModel< Number >::TaylorModel (const TaylorModel< Number > & tm) explicit
Definition at line 46 of file TaylorModel.tpp.
template<typename Number > hypro::TaylorModel< Number >::TaylorModel (const std::initializer_list< Term< carl::Interval< Number >>> & terms) explicit
Definition at line 52 of file TaylorModel.tpp.
template<typename Number > hypro::TaylorModel< Number >::TaylorModel (const std::initializer_list< Term< carl::Interval< Number >>> & terms, const carl::Interval< Number > & r)
Definition at line 61 of file TaylorModel.tpp.
template<typename Number > hypro::TaylorModel< Number >::TaylorModel (const Term< carl::Interval< Number >> & term) explicit
Definition at line 70 of file TaylorModel.tpp.
template<typename Number > hypro::TaylorModel< Number >::TaylorModel (carl::Variable::Arg v) explicit
Definition at line 79 of file TaylorModel.tpp.
Member Function Documentation
template<typename Number > void hypro::TaylorModel< Number >::checkConsistency () const
Definition at line 747 of file TaylorModel.tpp.
template<typename Number > void hypro::TaylorModel< Number >::cutoff (const carl::Interval< Number > & threshold, Domain< Number > & domain)
Definition at line 192 of file TaylorModel.tpp.
References hypro::Domain< Number >::get_assignments().
template<typename Number > void hypro::TaylorModel< Number >::cutoff_nr (const carl::Interval< Number > & threshold, Domain< Number > & domain)
Definition at line 213 of file TaylorModel.tpp.
References hypro::Domain< Number >::get_assignments().
template<typename Number > TaylorModel< Number > hypro::TaylorModel< Number >::derivative (carl::Variable::Arg v, unsigned nth = 1) const
Definition at line 652 of file TaylorModel.tpp.
Referenced by hypro::TaylorModelVec< Number >::derivative().
template<typename Number > void hypro::TaylorModel< Number >::derivative_assign (carl::Variable::Arg v, unsigned nth = 1)
Definition at line 664 of file TaylorModel.tpp.
template<typename Number > TaylorModel< Number > hypro::TaylorModel< Number >::div (const carl::Interval< Number > & I) const
Definition at line 508 of file TaylorModel.tpp.
template<typename Number > void hypro::TaylorModel< Number >::div_assign (const carl::Interval< Number > & I)
Definition at line 521 of file TaylorModel.tpp.
template<typename Number > void hypro::TaylorModel< Number >::enclosure (carl::Interval< Number > & I, Domain< Number > & domain) const
Definition at line 281 of file TaylorModel.tpp.
References hypro::Domain< Number >::get_assignments().
template<typename Number > bool hypro::TaylorModel< Number >::has (carl::Variable::Arg v) const
Definition at line 752 of file TaylorModel.tpp.
template<typename Number > TaylorModel< Number > hypro::TaylorModel< Number >::integration (carl::Variable::Arg v, const carl::Interval< Number > & range_of_v)
Definition at line 672 of file TaylorModel.tpp.
Referenced by hypro::TaylorModelVec< Number >::integration().
template<typename Number > void hypro::TaylorModel< Number >::integration_assign (carl::Variable::Arg v, const carl::Interval< Number > & range_of_v)
Definition at line 710 of file TaylorModel.tpp.
template<typename Number > bool hypro::TaylorModel< Number >::isConstant () const
Definition at line 135 of file TaylorModel.tpp.
Referenced by hypro::TaylorModel< Number >::substitute().
template<typename Number > bool hypro::TaylorModel< Number >::isLinear () const
Definition at line 140 of file TaylorModel.tpp.
template<typename Number > bool hypro::TaylorModel< Number >::isZero () const
Definition at line 129 of file TaylorModel.tpp.
template<typename Number > TaylorModel< Number > hypro::TaylorModel< Number >::LieDerivative (const PolynomialODE< Number > & ode) const
Definition at line 715 of file TaylorModel.tpp.
References hypro::PolynomialODE< Number >::find_assignment().
Referenced by hypro::TaylorModelVec< Number >::LieDerivative().
template<typename Number > void hypro::TaylorModel< Number >::LieDerivative_assign (const PolynomialODE< Number > & ode)
Definition at line 742 of file TaylorModel.tpp.
template<typename Number > TaylorModel< Number > hypro::TaylorModel< Number >::multiply (const carl::Interval< Number > & I) const
Definition at line 367 of file TaylorModel.tpp.
template<typename Number > TaylorModel< Number > hypro::TaylorModel< Number >::multiply (const TaylorModel< Number > & tm, Domain< Number > & domain, const exponent order) const
Definition at line 377 of file TaylorModel.tpp.
References hypro::TaylorModel< Number >::poly_enclosure(), and hypro::TaylorModel< Number >::truncation().
template<typename Number > TaylorModel< Number > hypro::TaylorModel< Number >::multiply (const Term< carl::Interval< Number >> & term, Domain< Number > & domain, const exponent order) const
Definition at line 398 of file TaylorModel.tpp.
References hypro::TaylorModel< Number >::poly_enclosure(), and hypro::TaylorModel< Number >::truncation().
template<typename Number > TaylorModel< Number > hypro::TaylorModel< Number >::multiply (carl::Variable::Arg v, Domain< Number > & domain, const exponent order) const
Definition at line 419 of file TaylorModel.tpp.
References hypro::TaylorModel< Number >::poly_enclosure(), and hypro::TaylorModel< Number >::truncation().
template<typename Number > void hypro::TaylorModel< Number >::multiply_assign (const carl::Interval< Number > & I)
Definition at line 440 of file TaylorModel.tpp.
Referenced by hypro::TaylorModel< Number >::pow(), and hypro::TaylorModel< Number >::substitute().
template<typename Number > void hypro::TaylorModel< Number >::multiply_assign (const TaylorModel< Number > & tm, Domain< Number > & domain, const exponent order)
Definition at line 446 of file TaylorModel.tpp.
References hypro::TaylorModel< Number >::poly_enclosure(), and hypro::TaylorModel< Number >::truncation().
template<typename Number > void hypro::TaylorModel< Number >::multiply_assign (const Term< carl::Interval< Number >> & term, Domain< Number > & domain, const exponent order)
Definition at line 467 of file TaylorModel.tpp.
References hypro::TaylorModel< Number >::poly_enclosure(), and hypro::TaylorModel< Number >::truncation().
template<typename Number > void hypro::TaylorModel< Number >::multiply_assign (carl::Variable::Arg v, Domain< Number > & domain, const exponent order)
Definition at line 488 of file TaylorModel.tpp.
References hypro::TaylorModel< Number >::poly_enclosure(), and hypro::TaylorModel< Number >::truncation().
template<typename Number > void hypro::TaylorModel< Number >::normalize (Domain< Number > & domain)
Definition at line 296 of file TaylorModel.tpp.
References hypro::Domain< Number >::get_assignments().
template<typename Number > const TaylorModel< Number > hypro::TaylorModel< Number >::operator+ (const TaylorModel< Number > & tm) const
Definition at line 351 of file TaylorModel.tpp.
template<typename Number > TaylorModel< Number > & hypro::TaylorModel< Number >::operator+= (const TaylorModel< Number > & tm)
Definition at line 335 of file TaylorModel.tpp.
template<typename Number > const TaylorModel< Number > hypro::TaylorModel< Number >::operator- (const TaylorModel< Number > & tm) const
Definition at line 359 of file TaylorModel.tpp.
template<typename Number > TaylorModel< Number > & hypro::TaylorModel< Number >::operator-= (const TaylorModel< Number > & tm)
Definition at line 343 of file TaylorModel.tpp.
template<typename Number > TaylorModel< Number > & hypro::TaylorModel< Number >::operator= (const TaylorModel< Number > & tm)
Definition at line 325 of file TaylorModel.tpp.
template<typename Number > void hypro::TaylorModel< Number >::poly_enclosure (carl::Interval< Number > & I, Domain< Number > & domain) const
Definition at line 289 of file TaylorModel.tpp.
References hypro::Domain< Number >::get_assignments().
Referenced by hypro::TaylorModel< Number >::multiply(), and hypro::TaylorModel< Number >::multiply_assign().
template<typename Number > TaylorModel< Number > hypro::TaylorModel< Number >::pow (unsigned exp, Domain< Number > & domain, const exponent order) const
Definition at line 166 of file TaylorModel.tpp.
References hypro::TaylorModel< Number >::multiply_assign().
Referenced by hypro::TaylorModel< Number >::substitute().
template<typename Number > carl::Interval< Number > hypro::TaylorModel< Number >::rmConstantTerm ()
Definition at line 145 of file TaylorModel.tpp.
template<typename Number > TaylorModel< Number > hypro::TaylorModel< Number >::substitute (const std::map< carl::Variable, TaylorModel< Number >> & substitutions, Domain< Number > & domain, const exponent order) const
Definition at line 530 of file TaylorModel.tpp.
References hypro::TaylorModel< Number >::isConstant(), hypro::TaylorModel< Number >::multiply_assign(), and hypro::TaylorModel< Number >::pow().
Referenced by hypro::TaylorModelVec< Number >::Picard(), hypro::TaylorModelVec< Number >::Picard_assign(), and hypro::TaylorModelVec< Number >::substitute().
template<typename Number > TaylorModel< Number > hypro::TaylorModel< Number >::substitute (const TaylorModelVec< Number > & substitutions, Domain< Number > & domain, const exponent order) const
Definition at line 646 of file TaylorModel.tpp.
References hypro::TaylorModelVec< Number >::tms.
template<typename Number > exponent hypro::TaylorModel< Number >::tmOrder () const
Definition at line 161 of file TaylorModel.tpp.
template<typename Number > void hypro::TaylorModel< Number >::truncation (const exponent order, Domain< Number > & domain)
Definition at line 233 of file TaylorModel.tpp.
References hypro::Domain< Number >::get_assignments().
Referenced by hypro::TaylorModel< Number >::multiply(), and hypro::TaylorModel< Number >::multiply_assign().
template<typename Number > void hypro::TaylorModel< Number >::truncation_nr (const exponent order)
Definition at line 264 of file TaylorModel.tpp.
Friends And Related Function Documentation
template<typename Number> friend class Flowpipe< Number > friend
Definition at line 159 of file TaylorModel.h.
template<typename Number> template<typename N > std::ostream& operator<< (std::ostream & os, const TaylorModel< N > & tm) friend
Definition at line 757 of file TaylorModel.tpp.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/TaylorModel/TaylorModel.h
/home/travis/build/hypro/hypro/src/hypro/representations/TaylorModel/TaylorModel.tpp