HyPro: hypro::Path< Number, tNumber > Class Template Reference
hypro::Path< Number, tNumber > Class Template Reference
Class to define a path in some hybrid automaton.
Public Types
using TIterator = typename std::deque< TPathElement< Number, tNumber >>::iterator
using TIterator_const = typename std::deque< TPathElement< Number, tNumber >>::const_iterator
Public Member Functions
Path ()
Path (std::initializer_list< TPathElement< Number, tNumber >> pathElems)
~Path ()
void add (const TPathElement< Number, tNumber > &elem)
void addTransition (Transition< Number > *t, const carl::Interval< tNumber > &enabledTime)
void addTimeStep (const carl::Interval< tNumber > &timeStep)
std::pair< Transition< Number > *, carl::Interval< tNumber > > getTransitionToJumpDepth (unsigned depth) const
Path & deleteAfterPos (std::size_t cutpos)
Path & deleteBeforePos (std::size_t cutpos)
Path & clear ()
bool sharesPrefix (const Path< Number, tNumber > &rhs) const
Path sharedPrefix (const Path< Number, tNumber > &rhs) const
Path removeSharedPrefix (const Path< Number, tNumber > &rhs) const
bool isEmpty () const
tNumber maximalTimeSpan (typename std::deque< TPathElement< Number, tNumber >>::const_iterator start, typename std::deque< TPathElement< Number, tNumber >>::const_iterator end) const
std::size_t getNumberDiscreteJumps () const
std::vector< Transition< Number > * > getTransitionSequence (typename std::deque< TPathElement< Number, tNumber >>::const_iterator start, typename std::deque< TPathElement< Number, tNumber >>::const_iterator end) const
std::vector< Transition< Number > * > getTransitionSequence () const
bool hasChatteringZeno () const
bool operator> (const Path< Number, tNumber > &r) const
bool operator> (unsigned r) const
TIterator begin ()
TIterator end ()
TIterator_const begin () const
TIterator_const end () const
const TPathElement< Number, tNumber > & back () const
const TPathElement< Number, tNumber > & front () const
std::size_t size () const
TPathElement< Number, tNumber > at (int index) const
void pop_front ()
void push_front (const TPathElement< Number, tNumber > &elem)
bool operator== (const Path< Number, tNumber > &rhs) const
bool operator!= (const Path< Number, tNumber > &rhs) const
Static Public Member Functions
static bool sharePrefix (const Path< Number, tNumber > &lhs, const Path< Number, tNumber > &rhs)
Friends
std::ostream & operator<< (std::ostream &_out, const Path< Number, tNumber > &path)
Detailed Description
template<typename Number, typename tNumber = Number>
class hypro::Path< Number, tNumber >
Class to define a path in some hybrid automaton.
Template Parameters
Number The used number type.
Definition at line 106 of file Path.h.
Member Typedef Documentation
template<typename Number, typename tNumber = Number> using hypro::Path< Number, tNumber >::TIterator = typename std::deque<TPathElement<Number, tNumber>>::iterator
Definition at line 148 of file Path.h.
template<typename Number, typename tNumber = Number> using hypro::Path< Number, tNumber >::TIterator_const = typename std::deque<TPathElement<Number, tNumber>>::const_iterator
Definition at line 149 of file Path.h.
Constructor & Destructor Documentation
template<typename Number, typename tNumber = Number> hypro::Path< Number, tNumber >::Path () inline
Definition at line 114 of file Path.h.
template<typename Number, typename tNumber> hypro::Path< Number, tNumber >::Path (std::initializer_list< TPathElement< Number, tNumber >> pathElems)
Definition at line 12 of file Path.tpp.
References hypro::detail::for_each().
template<typename Number, typename tNumber = Number> hypro::Path< Number, tNumber >::~Path () inline
Definition at line 116 of file Path.h.
Member Function Documentation
template<typename Number, typename tNumber> void hypro::Path< Number, tNumber >::add (const TPathElement< Number, tNumber > & elem)
Definition at line 18 of file Path.tpp.
Referenced by hypro::Path< Number, tNumber >::sharedPrefix().
template<typename Number , typename tNumber> void hypro::Path< Number, tNumber >::addTimeStep (const carl::Interval< tNumber > & timeStep)
Definition at line 29 of file Path.tpp.
Referenced by hypro::ReachTreeNode< State >::addTimeStepToPath(), hypro::LTIContext< State >::execBeforeFirstSegment(), and hypro::RectangularContext< State >::execBeforeFirstSegment().
template<typename Number, typename tNumber> void hypro::Path< Number, tNumber >::addTransition (Transition< Number > * t, const carl::Interval< tNumber > & enabledTime)
Definition at line 23 of file Path.tpp.
Referenced by hypro::ReachTreeNode< State >::addTransitionToPath(), hypro::LTIContext< State >::execBeforeFirstSegment(), and hypro::RectangularContext< State >::execBeforeFirstSegment().
template<typename Number , typename tNumber > TPathElement< Number, tNumber > hypro::Path< Number, tNumber >::at (int index) const
Definition at line 284 of file Path.tpp.
Referenced by hypro::Path< Number, tNumber >::operator==(), and hypro::Path< Number, tNumber >::sharedPrefix().
template<typename Number , typename tNumber > const TPathElement< Number, tNumber > & hypro::Path< Number, tNumber >::back () const
Definition at line 324 of file Path.tpp.
template<typename Number , typename tNumber > Path< Number, tNumber >::TIterator hypro::Path< Number, tNumber >::begin ()
Definition at line 304 of file Path.tpp.
Referenced by hypro::EventTimingProvider< Number >::getDotRepresentation(), and hypro::EventTimingProvider< Number >::getTimings().
template<typename Number , typename tNumber > Path< Number, tNumber >::TIterator_const hypro::Path< Number, tNumber >::begin () const
Definition at line 314 of file Path.tpp.
template<typename Number , typename tNumber > Path< Number, tNumber > & hypro::Path< Number, tNumber >::clear ()
Definition at line 90 of file Path.tpp.
Referenced by hypro::Path< Number, tNumber >::deleteBeforePos().
template<typename Number , typename tNumber > Path< Number, tNumber > & hypro::Path< Number, tNumber >::deleteAfterPos (std::size_t cutpos)
Definition at line 59 of file Path.tpp.
References hypro::Path< Number, tNumber >::size().
template<typename Number , typename tNumber > Path< Number, tNumber > & hypro::Path< Number, tNumber >::deleteBeforePos (std::size_t cutpos)
Definition at line 76 of file Path.tpp.
References hypro::Path< Number, tNumber >::clear(), and hypro::Path< Number, tNumber >::size().
template<typename Number , typename tNumber > Path< Number, tNumber >::TIterator hypro::Path< Number, tNumber >::end ()
Definition at line 309 of file Path.tpp.
Referenced by hypro::EventTimingProvider< Number >::getDotRepresentation(), hypro::EventTimingProvider< Number >::getTimings(), and hypro::Path< Number, tNumber >::getTransitionSequence().
template<typename Number , typename tNumber > Path< Number, tNumber >::TIterator_const hypro::Path< Number, tNumber >::end () const
Definition at line 319 of file Path.tpp.
template<typename Number , typename tNumber > const TPathElement< Number, tNumber > & hypro::Path< Number, tNumber >::front () const
Definition at line 330 of file Path.tpp.
template<typename Number , typename tNumber > std::size_t hypro::Path< Number, tNumber >::getNumberDiscreteJumps () const
Definition at line 170 of file Path.tpp.
template<typename Number, typename tNumber> std::vector< Transition< Number > * > hypro::Path< Number, tNumber >::getTransitionSequence (typename std::deque< TPathElement< Number, tNumber >>::const_iterator start, typename std::deque< TPathElement< Number, tNumber >>::const_iterator end) const
Definition at line 181 of file Path.tpp.
References hypro::Path< Number, tNumber >::end().
template<typename Number, typename tNumber = Number> std::vector<Transition<Number>*> hypro::Path< Number, tNumber >::getTransitionSequence () const inline
Definition at line 140 of file Path.h.
References hypro::Path< Number, tNumber >::getTransitionSequence(), and hypro::operator>().
Referenced by hypro::Path< Number, tNumber >::getTransitionSequence().
template<typename Number , typename tNumber > std::pair< Transition< Number > *, carl::Interval< tNumber > > hypro::Path< Number, tNumber >::getTransitionToJumpDepth (unsigned depth) const
Definition at line 35 of file Path.tpp.
template<typename Number , typename tNumber > bool hypro::Path< Number, tNumber >::hasChatteringZeno () const
Definition at line 198 of file Path.tpp.
References hypro::Path< Number, tNumber >::maximalTimeSpan().
Referenced by hypro::LTIContext< State >::execBeforeFirstSegment(), and hypro::RectangularContext< State >::execBeforeFirstSegment().
template<typename Number, typename tNumber = Number> bool hypro::Path< Number, tNumber >::isEmpty () const inline
Definition at line 135 of file Path.h.
template<typename Number, typename tNumber> tNumber hypro::Path< Number, tNumber >::maximalTimeSpan (typename std::deque< TPathElement< Number, tNumber >>::const_iterator start, typename std::deque< TPathElement< Number, tNumber >>::const_iterator end) const
Definition at line 136 of file Path.tpp.
Referenced by hypro::Path< Number, tNumber >::hasChatteringZeno().
template<typename Number, typename tNumber = Number> bool hypro::Path< Number, tNumber >::operator!= (const Path< Number, tNumber > & rhs) const inline
Definition at line 185 of file Path.h.
template<typename Number, typename tNumber = Number> bool hypro::Path< Number, tNumber >::operator== (const Path< Number, tNumber > & rhs) const inline
Definition at line 173 of file Path.h.
References hypro::Path< Number, tNumber >::at(), and hypro::Path< Number, tNumber >::size().
template<typename Number, typename tNumber> bool hypro::Path< Number, tNumber >::operator> (const Path< Number, tNumber > & r) const
Definition at line 269 of file Path.tpp.
template<typename Number, typename tNumber> bool hypro::Path< Number, tNumber >::operator> (unsigned r) const
Definition at line 274 of file Path.tpp.
template<typename Number , typename tNumber > void hypro::Path< Number, tNumber >::pop_front ()
Definition at line 289 of file Path.tpp.
Referenced by hypro::Path< Number, tNumber >::removeSharedPrefix().
template<typename Number, typename tNumber> void hypro::Path< Number, tNumber >::push_front (const TPathElement< Number, tNumber > & elem)
Definition at line 294 of file Path.tpp.
template<typename Number, typename tNumber> Path< Number, tNumber > hypro::Path< Number, tNumber >::removeSharedPrefix (const Path< Number, tNumber > & rhs) const
Definition at line 124 of file Path.tpp.
References hypro::Path< Number, tNumber >::pop_front(), hypro::Path< Number, tNumber >::sharedPrefix(), and hypro::Path< Number, tNumber >::size().
template<typename Number, typename tNumber> Path< Number, tNumber > hypro::Path< Number, tNumber >::sharedPrefix (const Path< Number, tNumber > & rhs) const
Definition at line 111 of file Path.tpp.
References hypro::Path< Number, tNumber >::add(), hypro::Path< Number, tNumber >::at(), and hypro::Path< Number, tNumber >::size().
Referenced by hypro::Path< Number, tNumber >::removeSharedPrefix().
template<typename Number, typename tNumber> bool hypro::Path< Number, tNumber >::sharePrefix (const Path< Number, tNumber > & lhs, const Path< Number, tNumber > & rhs) static
Definition at line 99 of file Path.tpp.
Referenced by hypro::Path< Number, tNumber >::sharesPrefix().
template<typename Number, typename tNumber> bool hypro::Path< Number, tNumber >::sharesPrefix (const Path< Number, tNumber > & rhs) const
Definition at line 299 of file Path.tpp.
References hypro::Path< Number, tNumber >::sharePrefix().
template<typename Number , typename tNumber > std::size_t hypro::Path< Number, tNumber >::size () const
Definition at line 279 of file Path.tpp.
Referenced by hypro::Path< Number, tNumber >::deleteAfterPos(), hypro::Path< Number, tNumber >::deleteBeforePos(), hypro::Path< Number, tNumber >::operator==(), hypro::Path< Number, tNumber >::removeSharedPrefix(), and hypro::Path< Number, tNumber >::sharedPrefix().
Friends And Related Function Documentation
template<typename Number, typename tNumber = Number> std::ostream& operator<< (std::ostream & _out, const Path< Number, tNumber > & path) friend
Definition at line 163 of file Path.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/Path.h
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/Path.tpp