HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/handles/ClassHandle.h File Reference
ClassHandle.h File Reference
Classes
class ClassHandle< T >
Functions
template<class T >
mxArray * convertPtr2Mat (T *ptr)
template<class T >
mxArray * convertSmartPtr2Mat (T *ptr)
template<class T >
ClassHandle< T > * convertMat2HandlePtr (const mxArray *in)
template<class T >
T * convertMat2Ptr (const mxArray *in)
template<class T >
void destroyObject (const mxArray *in)
template<class T >
void destroySmartObject (const mxArray *in)
Function Documentation
template<class T > ClassHandle<T>* convertMat2HandlePtr (const mxArray * in) inline
Definition at line 47 of file ClassHandle.h.
References ClassHandle< T >::isValid(), mexErrMsgTxt(), and ClassHandle< T >::ptr().
template<class T > T* convertMat2Ptr (const mxArray * in) inline
Definition at line 58 of file ClassHandle.h.
References ClassHandle< T >::ptr(), and temp.
template<class T > mxArray* convertPtr2Mat (T * ptr) inline
Definition at line 30 of file ClassHandle.h.
References out.
Referenced by ObjectHandle::flowpipes2Matlab().
template<class T > mxArray* convertSmartPtr2Mat (T * ptr) inline
Definition at line 39 of file ClassHandle.h.
References out.
template<class T > void destroyObject (const mxArray * in) inline
Definition at line 65 of file ClassHandle.h.
template<class T > void destroySmartObject (const mxArray * in) inline
Definition at line 71 of file ClassHandle.h.