HyPro: hypro::ContextBasedReachabilityWorker< State > Class Template Reference
hypro::ContextBasedReachabilityWorker< State > Class Template Reference
Public Member Functions
ContextBasedReachabilityWorker (const ReachabilitySettings &settings)
~ContextBasedReachabilityWorker ()
void processTask (const TaskType &t, const Strategy< State > &strat, WorkQueue< TaskType > *localQueue, WorkQueue< TaskType > *localCEXQueue, Flowpipe< State > &localSegments)
void computeForwardReachability (const TaskType &task, const Strategy< State > &strat, WorkQueue< TaskType > *localQueue, WorkQueue< TaskType > *localCEXQueue, Flowpipe< State > &localSegments)
bool isValidTask (const TaskType &task, WorkQueue< TaskType > *localCEXQueue)
Public Member Functions inherited from hypro::IWorker< std::shared_ptr< Task< State > >, State >
IWorker (const ReachabilitySettings &settings)
virtual ~IWorker ()
virtual void processTask (const std::shared_ptr< Task< State > > &w, const Strategy< State > &strategy, WorkQueue< TaskType > *localQueue, WorkQueue< TaskType > *localCEXQueue, Flowpipe< State > &localSegments)=0
bool detectedUnsafety () const
Additional Inherited Members
Public Types inherited from hypro::IWorker< std::shared_ptr< Task< State > >, State >
using Number = typename State::NumberType
using TaskType = std::shared_ptr< Task< State >>
Protected Attributes inherited from hypro::IWorker< std::shared_ptr< Task< State > >, State >
ReachabilitySettings mSettings
bool isUnsafe
Detailed Description
template<typename State>
class hypro::ContextBasedReachabilityWorker< State >
Definition at line 19 of file ContextBasedReachabilityWorker.h.
Constructor & Destructor Documentation
template<typename State> hypro::ContextBasedReachabilityWorker< State >::ContextBasedReachabilityWorker (const ReachabilitySettings & settings) inline
Definition at line 24 of file ContextBasedReachabilityWorker.h.
template<typename State> hypro::ContextBasedReachabilityWorker< State >::~ContextBasedReachabilityWorker () inline
Definition at line 28 of file ContextBasedReachabilityWorker.h.
References hypro::ContextBasedReachabilityWorker< State >::computeForwardReachability(), hypro::ContextBasedReachabilityWorker< State >::isValidTask(), and hypro::ContextBasedReachabilityWorker< State >::processTask().
Member Function Documentation
template<typename State > void hypro::ContextBasedReachabilityWorker< State >::computeForwardReachability (const TaskType & task, const Strategy< State > & strat, WorkQueue< TaskType > * localQueue, WorkQueue< TaskType > * localCEXQueue, Flowpipe< State > & localSegments)
Definition at line 17 of file ContextBasedReachabilityWorker.tpp.
References hypro::IContext::applyContinuousEvolution(), hypro::IContext::checkInvariant(), hypro::IContext::checkTransition(), hypro::ContextFactory< State >::createContext(), hypro::IContext::doneCondition(), hypro::IContext::execAfterCheckInvariant(), hypro::IContext::execAfterCheckTransition(), hypro::IContext::execAfterContinuousEvolution(), hypro::IContext::execAfterFirstSegment(), hypro::IContext::execAfterIntersectBadStates(), hypro::IContext::execAfterLoop(), hypro::IContext::execBeforeCheckInvariant(), hypro::IContext::execBeforeCheckTransition(), hypro::IContext::execBeforeContinuousEvolution(), hypro::IContext::execBeforeFirstSegment(), hypro::IContext::execBeforeIntersectBadStates(), hypro::IContext::execBeforeLoop(), hypro::IContext::execBeforeProcessDiscreteBehavior(), hypro::IContext::execOnEnd(), hypro::IContext::execOnLoopItEnter(), hypro::IContext::execOnLoopItExit(), hypro::IContext::execOnStart(), hypro::IContext::firstSegment(), hypro::IContext::intersectBadStates(), hypro::IContext::processDiscreteBehavior(), hypro::HardTerminateException::what(), and hypro::FinishWithDiscreteProcessingException::what().
Referenced by hypro::ContextBasedReachabilityWorker< State >::~ContextBasedReachabilityWorker().
template<typename State > bool hypro::ContextBasedReachabilityWorker< State >::isValidTask (const TaskType & task, WorkQueue< TaskType > * localCEXQueue)
Definition at line 145 of file ContextBasedReachabilityWorker.tpp.
References hypro::WorkQueueT< Workable, Setting >::enqueue(), hypro::WorkQueueT< Workable, Setting >::nonLockingEnqueue(), and hypro::WorkQueueT< Workable, Setting >::nonLockingSize().
Referenced by hypro::ContextBasedReachabilityWorker< State >::~ContextBasedReachabilityWorker().
template<typename State > void hypro::ContextBasedReachabilityWorker< State >::processTask (const TaskType & t, const Strategy< State > & strat, WorkQueue< TaskType > * localQueue, WorkQueue< TaskType > * localCEXQueue, Flowpipe< State > & localSegments)
Definition at line 6 of file ContextBasedReachabilityWorker.tpp.
Referenced by main(), and hypro::ContextBasedReachabilityWorker< State >::~ContextBasedReachabilityWorker().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/workers/ContextBasedReachabilityWorker.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/workers/ContextBasedReachabilityWorker.tpp