HyPro: hypro::EventTimingNode< Number > Class Template Reference
hypro::EventTimingNode< Number > Class Template Reference
Public Types
using Node_t = typename DAGNode< EventTimingNode< Number >>::Node_t
using const_Node_t = typename DAGNode< EventTimingNode< Number >>::const_Node_t
using NodeList_t = typename DAGNode< EventTimingNode< Number >>::NodeList_t
Public Types inherited from hypro::DAGNode< EventTimingNode< Number > >
using Node_t = EventTimingNode< Number > *
using const_Node_t = const EventTimingNode< Number > *
using NodeList_t = std::vector< EventTimingNode< Number > * >
Public Member Functions
EventTimingNode ()
EventTimingNode (const EventTimingContainer< Number > &in)
const EventTimingContainer< Number > & getTimings () const
EventTimingContainer< Number > & rGetTimings ()
const Location< Number > * getLocation () const
const Transition< Number > * getEntryTransition () const
const carl::Interval< tNumber > & getEntryTimestamp () const
TimingAggregate< Number > & rGetTimingAggregate ()
void setLevel (std::size_t l)
std::size_t getLevel () const
void setTimings (const EventTimingContainer< Number > &timings)
void setLocation (const Location< Number > *loc)
void setEntryTimestamp (const carl::Interval< tNumber > &t)
void extendEntryTimestamp (const carl::Interval< tNumber > &t)
void setEntryTransition (const Transition< Number > *trans)
std::size_t getDotRepresentation (int id, std::string &nodes, std::string &transitions) const
Public Member Functions inherited from hypro::DAGNode< EventTimingNode< Number > >
DAGNode ()
parents list, empty if root.
DAGNode (const typename DAGNode< EventTimingNode< Number > >::NodeList_t &_children, EventTimingNode< Number > *_parent)
~DAGNode ()
std::size_t getSubtreeSize () const
double getAvgSubtreeBranching () const
const DAGNode< EventTimingNode< Number > >::NodeList_t & getChildren () const
const DAGNode< EventTimingNode< Number > >::NodeList_t & getParents () const
void addChild (EventTimingNode< Number > *child)
void addParent (EventTimingNode< Number > *parent)
Protected Attributes
EventTimingContainer< Number > mTimings
const Location< Number > * mLocation = nullptr
const Transition< Number > * mEntryTransition = nullptr
carl::Interval< tNumber > mEntryTimestamp
TimingAggregate< Number > mTimingAggregate
std::size_t mLevel = 0
Protected Attributes inherited from hypro::DAGNode< EventTimingNode< Number > >
NodeList_t mChildren
NodeList_t mParents
children list
Friends
std::ostream & operator<< (std::ostream &out, const EventTimingNode< Number > &in)
Detailed Description
template<typename Number>
class hypro::EventTimingNode< Number >
Definition at line 12 of file EventTimingNode.h.
Member Typedef Documentation
template<typename Number> using hypro::EventTimingNode< Number >::const_Node_t = typename DAGNode<EventTimingNode<Number>>::const_Node_t
Definition at line 23 of file EventTimingNode.h.
template<typename Number> using hypro::EventTimingNode< Number >::Node_t = typename DAGNode<EventTimingNode<Number>>::Node_t
Definition at line 22 of file EventTimingNode.h.
template<typename Number> using hypro::EventTimingNode< Number >::NodeList_t = typename DAGNode<EventTimingNode<Number>>::NodeList_t
Definition at line 24 of file EventTimingNode.h.
Constructor & Destructor Documentation
template<typename Number> hypro::EventTimingNode< Number >::EventTimingNode () inline
Definition at line 26 of file EventTimingNode.h.
template<typename Number> hypro::EventTimingNode< Number >::EventTimingNode (const EventTimingContainer< Number > & in) inline
Definition at line 27 of file EventTimingNode.h.
Member Function Documentation
template<typename Number > void hypro::EventTimingNode< Number >::extendEntryTimestamp (const carl::Interval< tNumber > & t)
Definition at line 62 of file EventTimingNode.tpp.
Referenced by hypro::EventTimingNode< N >::EventTimingNode().
template<typename Number > std::size_t hypro::EventTimingNode< Number >::getDotRepresentation (int id, std::string & nodes, std::string & transitions) const
Definition at line 73 of file EventTimingNode.tpp.
template<typename Number > const carl::Interval< tNumber > & hypro::EventTimingNode< Number >::getEntryTimestamp () const
Definition at line 31 of file EventTimingNode.tpp.
Referenced by hypro::EventTimingNode< N >::EventTimingNode().
template<typename Number > const Transition< Number > * hypro::EventTimingNode< Number >::getEntryTransition () const
Definition at line 26 of file EventTimingNode.tpp.
Referenced by hypro::EventTimingNode< N >::EventTimingNode().
template<typename Number > std::size_t hypro::EventTimingNode< Number >::getLevel () const
Definition at line 46 of file EventTimingNode.tpp.
Referenced by hypro::EventTimingNode< N >::EventTimingNode().
template<typename Number > const Location< Number > * hypro::EventTimingNode< Number >::getLocation () const
Definition at line 21 of file EventTimingNode.tpp.
Referenced by hypro::EventTimingNode< N >::EventTimingNode().
template<typename Number > const EventTimingContainer< Number > & hypro::EventTimingNode< Number >::getTimings () const
Definition at line 11 of file EventTimingNode.tpp.
Referenced by hypro::EventTimingNode< N >::EventTimingNode().
template<typename Number > TimingAggregate< Number > & hypro::EventTimingNode< Number >::rGetTimingAggregate ()
Definition at line 36 of file EventTimingNode.tpp.
Referenced by hypro::EventTimingNode< N >::EventTimingNode().
template<typename Number > EventTimingContainer< Number > & hypro::EventTimingNode< Number >::rGetTimings ()
Definition at line 16 of file EventTimingNode.tpp.
Referenced by hypro::EventTimingNode< N >::EventTimingNode().
template<typename Number > void hypro::EventTimingNode< Number >::setEntryTimestamp (const carl::Interval< tNumber > & t)
Definition at line 56 of file EventTimingNode.tpp.
Referenced by hypro::EventTimingNode< N >::EventTimingNode(), and hypro::EventTimingProvider< Number >::initialize().
template<typename Number> void hypro::EventTimingNode< Number >::setEntryTransition (const Transition< Number > * trans)
Definition at line 68 of file EventTimingNode.tpp.
Referenced by hypro::EventTimingNode< N >::EventTimingNode().
template<typename Number > void hypro::EventTimingNode< Number >::setLevel (std::size_t l)
Definition at line 41 of file EventTimingNode.tpp.
Referenced by hypro::EventTimingNode< N >::EventTimingNode().
template<typename Number> void hypro::EventTimingNode< Number >::setLocation (const Location< Number > * loc)
Definition at line 51 of file EventTimingNode.tpp.
Referenced by hypro::EventTimingNode< N >::EventTimingNode(), and hypro::EventTimingProvider< Number >::initialize().
template<typename Number> void hypro::EventTimingNode< Number >::setTimings (const EventTimingContainer< Number > & timings)
Definition at line 5 of file EventTimingNode.tpp.
Referenced by hypro::EventTimingNode< N >::EventTimingNode().
Friends And Related Function Documentation
template<typename Number> std::ostream& operator<< (std::ostream & out, const EventTimingNode< Number > & in) friend
Definition at line 46 of file EventTimingNode.h.
Member Data Documentation
template<typename Number> carl::Interval<tNumber> hypro::EventTimingNode< Number >::mEntryTimestamp protected
Definition at line 17 of file EventTimingNode.h.
template<typename Number> const Transition<Number>* hypro::EventTimingNode< Number >::mEntryTransition = nullptr protected
Definition at line 16 of file EventTimingNode.h.
template<typename Number> std::size_t hypro::EventTimingNode< Number >::mLevel = 0 protected
Definition at line 19 of file EventTimingNode.h.
template<typename Number> const Location<Number>* hypro::EventTimingNode< Number >::mLocation = nullptr protected
Definition at line 15 of file EventTimingNode.h.
template<typename Number> TimingAggregate<Number> hypro::EventTimingNode< Number >::mTimingAggregate protected
Definition at line 18 of file EventTimingNode.h.
template<typename Number> EventTimingContainer<Number> hypro::EventTimingNode< Number >::mTimings protected
Definition at line 14 of file EventTimingNode.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/timing/EventTimingNode.h
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/timing/EventTimingNode.tpp