HyPro: hypro::HybridAutomatonParser::SettingContext Class Reference
hypro::HybridAutomatonParser::SettingContext Class Reference
#include <HybridAutomatonParser.h>
Public Member Functions
SettingContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
std::vector< FixedstepsContext * > fixedsteps ()
FixedstepsContext * fixedsteps (size_t i)
std::vector< TimeContext * > time ()
TimeContext * time (size_t i)
std::vector< RemainderContext * > remainder ()
RemainderContext * remainder (size_t i)
std::vector< IdentityContext * > identity ()
IdentityContext * identity (size_t i)
std::vector< QrprecondContext * > qrprecond ()
QrprecondContext * qrprecond (size_t i)
std::vector< PlotsettingContext * > plotsetting ()
PlotsettingContext * plotsetting (size_t i)
std::vector< FixedordersContext * > fixedorders ()
FixedordersContext * fixedorders (size_t i)
std::vector< AdaptiveordersContext * > adaptiveorders ()
AdaptiveordersContext * adaptiveorders (size_t i)
std::vector< CutoffContext * > cutoff ()
CutoffContext * cutoff (size_t i)
std::vector< PrecisionContext * > precision ()
PrecisionContext * precision (size_t i)
std::vector< FilenameContext * > filename ()
FilenameContext * filename (size_t i)
std::vector< MaxjumpsContext * > maxjumps ()
MaxjumpsContext * maxjumps (size_t i)
std::vector< PrintContext * > print ()
PrintContext * print (size_t i)
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Detailed Description
Definition at line 599 of file HybridAutomatonParser.h.
Constructor & Destructor Documentation
HybridAutomatonParser::SettingContext::SettingContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 2661 of file HybridAutomatonParser.cpp.
Member Function Documentation
antlrcpp::Any HybridAutomatonParser::SettingContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
Definition at line 2774 of file HybridAutomatonParser.cpp.
std::vector< HybridAutomatonParser::AdaptiveordersContext * > HybridAutomatonParser::SettingContext::adaptiveorders ()
Definition at line 2721 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::setting().
HybridAutomatonParser::AdaptiveordersContext * HybridAutomatonParser::SettingContext::adaptiveorders (size_t i)
Definition at line 2725 of file HybridAutomatonParser.cpp.
References i.
std::vector< HybridAutomatonParser::CutoffContext * > HybridAutomatonParser::SettingContext::cutoff ()
Definition at line 2729 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::setting().
HybridAutomatonParser::CutoffContext * HybridAutomatonParser::SettingContext::cutoff (size_t i)
Definition at line 2733 of file HybridAutomatonParser.cpp.
References i.
std::vector< HybridAutomatonParser::FilenameContext * > HybridAutomatonParser::SettingContext::filename ()
Definition at line 2745 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::setting().
HybridAutomatonParser::FilenameContext * HybridAutomatonParser::SettingContext::filename (size_t i)
Definition at line 2749 of file HybridAutomatonParser.cpp.
References i.
std::vector< HybridAutomatonParser::FixedordersContext * > HybridAutomatonParser::SettingContext::fixedorders ()
Definition at line 2713 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::setting().
HybridAutomatonParser::FixedordersContext * HybridAutomatonParser::SettingContext::fixedorders (size_t i)
Definition at line 2717 of file HybridAutomatonParser.cpp.
References i.
std::vector< HybridAutomatonParser::FixedstepsContext * > HybridAutomatonParser::SettingContext::fixedsteps ()
Definition at line 2665 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::setting().
HybridAutomatonParser::FixedstepsContext * HybridAutomatonParser::SettingContext::fixedsteps (size_t i)
Definition at line 2669 of file HybridAutomatonParser.cpp.
References i.
size_t HybridAutomatonParser::SettingContext::getRuleIndex () const override virtual
Definition at line 2770 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::RuleSetting.
std::vector< HybridAutomatonParser::IdentityContext * > HybridAutomatonParser::SettingContext::identity ()
Definition at line 2689 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::setting().
HybridAutomatonParser::IdentityContext * HybridAutomatonParser::SettingContext::identity (size_t i)
Definition at line 2693 of file HybridAutomatonParser.cpp.
References i.
std::vector< HybridAutomatonParser::MaxjumpsContext * > HybridAutomatonParser::SettingContext::maxjumps ()
Definition at line 2753 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::setting().
HybridAutomatonParser::MaxjumpsContext * HybridAutomatonParser::SettingContext::maxjumps (size_t i)
Definition at line 2757 of file HybridAutomatonParser.cpp.
References i.
std::vector< HybridAutomatonParser::PlotsettingContext * > HybridAutomatonParser::SettingContext::plotsetting ()
Definition at line 2705 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::setting().
HybridAutomatonParser::PlotsettingContext * HybridAutomatonParser::SettingContext::plotsetting (size_t i)
Definition at line 2709 of file HybridAutomatonParser.cpp.
References i.
std::vector< HybridAutomatonParser::PrecisionContext * > HybridAutomatonParser::SettingContext::precision ()
Definition at line 2737 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::setting().
HybridAutomatonParser::PrecisionContext * HybridAutomatonParser::SettingContext::precision (size_t i)
Definition at line 2741 of file HybridAutomatonParser.cpp.
References i.
std::vector< HybridAutomatonParser::PrintContext * > HybridAutomatonParser::SettingContext::print ()
Definition at line 2761 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::setting().
HybridAutomatonParser::PrintContext * HybridAutomatonParser::SettingContext::print (size_t i)
Definition at line 2765 of file HybridAutomatonParser.cpp.
References i.
std::vector< HybridAutomatonParser::QrprecondContext * > HybridAutomatonParser::SettingContext::qrprecond ()
Definition at line 2697 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::setting().
HybridAutomatonParser::QrprecondContext * HybridAutomatonParser::SettingContext::qrprecond (size_t i)
Definition at line 2701 of file HybridAutomatonParser.cpp.
References i.
std::vector< HybridAutomatonParser::RemainderContext * > HybridAutomatonParser::SettingContext::remainder ()
Definition at line 2681 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::setting().
HybridAutomatonParser::RemainderContext * HybridAutomatonParser::SettingContext::remainder (size_t i)
Definition at line 2685 of file HybridAutomatonParser.cpp.
References i.
std::vector< HybridAutomatonParser::TimeContext * > HybridAutomatonParser::SettingContext::time ()
Definition at line 2673 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::setting().
HybridAutomatonParser::TimeContext * HybridAutomatonParser::SettingContext::time (size_t i)
Definition at line 2677 of file HybridAutomatonParser.cpp.
References i.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HybridAutomatonParser.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HybridAutomatonParser.cpp