HyPro: hypro::Reset< Number > Class Template Reference
hypro::Reset< Number > Class Template Reference
Public Member Functions
Reset ()=default
Reset (const Reset &orig)
Reset (Reset &&orig)=default
Reset & operator= (const Reset< Number > &orig)=default
Reset & operator= (Reset< Number > &&orig)=default
Reset (const matrix_t< Number > &mat, const vector_t< Number > &vec)
Reset (const std::vector< carl::Interval< Number >> &intervals)
~Reset ()
bool empty () const
std::size_t size () const
const vector_t< Number > & getVector (std::size_t I=0) const
const matrix_t< Number > & getMatrix (std::size_t I=0) const
matrix_t< Number > & rGetMatrix (std::size_t I=0)
vector_t< Number > & rGetVector (std::size_t I=0)
const std::vector< carl::Interval< Number > > & getIntervals (std::size_t I=0) const
std::vector< carl::Interval< Number > > & rGetIntervals (std::size_t I=0)
const AffineTransformation< Number > & getAffineReset (std::size_t I=0) const
const std::vector< AffineTransformation< Number > > & getAffineResets () const
const IntervalAssignment< Number > & getIntervalReset (std::size_t I=0) const
const std::vector< IntervalAssignment< Number > > & getIntervalResets () const
void setVector (const vector_t< Number > &in, std::size_t I=0)
void setMatrix (const matrix_t< Number > &in, std::size_t I=0)
void setIntervals (const std::vector< carl::Interval< Number >> &intervals, std::size_t I=0)
bool isIdentity () const
std::size_t hash () const
void decompose (const Decomposition &decomposition)
Protected Attributes
std::vector< AffineTransformation< Number > > mAffineResets
std::vector< IntervalAssignment< Number > > mIntervalResets
std::size_t mHash = 0
bool mDecomposed = false
Friends
std::ostream & operator<< (std::ostream &ostr, const Reset< Number > &a) friend std
bool operator!= (const Reset< Number > &lhs, const Reset< Number > &rhs)
Detailed Description
template<typename Number>
class hypro::Reset< Number >
Examples:
example_bouncingBall.cpp.
Definition at line 35 of file Reset.h.
Constructor & Destructor Documentation
template<typename Number> hypro::Reset< Number >::Reset () default
template<typename Number> hypro::Reset< Number >::Reset (const Reset< Number > & orig) inline
Definition at line 44 of file Reset.h.
template<typename Number> hypro::Reset< Number >::Reset (Reset< Number > && orig) default
template<typename Number> hypro::Reset< Number >::Reset (const matrix_t< Number > & mat, const vector_t< Number > & vec)
Definition at line 6 of file Reset.tpp.
template<typename Number> hypro::Reset< Number >::Reset (const std::vector< carl::Interval< Number >> & intervals)
template<typename Number> hypro::Reset< Number >::~Reset () inline
Definition at line 53 of file Reset.h.
Member Function Documentation
template<typename Number > void hypro::Reset< Number >::decompose (const Decomposition & decomposition)
decomposes reset
Definition at line 207 of file Reset.tpp.
References hypro::selectCols(), and hypro::selectRows().
Referenced by hypro::Transition< N >::decompose().
template<typename Number> bool hypro::Reset< Number >::empty () const inline
Definition at line 55 of file Reset.h.
Referenced by hypro::applyReset().
template<typename Number> const AffineTransformation<Number>& hypro::Reset< Number >::getAffineReset (std::size_t I = 0) const inline
Definition at line 65 of file Reset.h.
Referenced by hypro::applyReset(), and std::hash< hypro::Reset< Number > >::operator()().
template<typename Number> const std::vector<AffineTransformation<Number> >& hypro::Reset< Number >::getAffineResets () const inline
Definition at line 66 of file Reset.h.
template<typename Number> const IntervalAssignment<Number>& hypro::Reset< Number >::getIntervalReset (std::size_t I = 0) const inline
Definition at line 67 of file Reset.h.
Referenced by hypro::applyReset(), and std::hash< hypro::Reset< Number > >::operator()().
template<typename Number> const std::vector<IntervalAssignment<Number> >& hypro::Reset< Number >::getIntervalResets () const inline
Definition at line 68 of file Reset.h.
template<typename Number > const std::vector< carl::Interval< Number > > & hypro::Reset< Number >::getIntervals (std::size_t I = 0) const
Definition at line 34 of file Reset.tpp.
template<typename Number > const matrix_t< Number > & hypro::Reset< Number >::getMatrix (std::size_t I = 0) const
Definition at line 19 of file Reset.tpp.
Referenced by hypro::combine(), and hypro::Transformation< Number >::Transformation().
template<typename Number > const vector_t< Number > & hypro::Reset< Number >::getVector (std::size_t I = 0) const
Definition at line 14 of file Reset.tpp.
Referenced by hypro::combine(), and hypro::Transformation< Number >::Transformation().
template<typename Number > std::size_t hypro::Reset< Number >::hash () const
Definition at line 92 of file Reset.tpp.
template<typename Number > bool hypro::Reset< Number >::isIdentity () const
Definition at line 81 of file Reset.tpp.
Referenced by hypro::Transition< N >::hasIdentityReset().
template<typename Number> Reset& hypro::Reset< Number >::operator= (const Reset< Number > & orig) default
template<typename Number> Reset& hypro::Reset< Number >::operator= (Reset< Number > && orig) default
template<typename Number > std::vector< carl::Interval< Number > > & hypro::Reset< Number >::rGetIntervals (std::size_t I = 0)
Definition at line 39 of file Reset.tpp.
template<typename Number > matrix_t< Number > & hypro::Reset< Number >::rGetMatrix (std::size_t I = 0)
Definition at line 24 of file Reset.tpp.
Referenced by hypro::operator||().
template<typename Number > vector_t< Number > & hypro::Reset< Number >::rGetVector (std::size_t I = 0)
Definition at line 29 of file Reset.tpp.
Referenced by hypro::operator||().
template<typename Number> void hypro::Reset< Number >::setIntervals (const std::vector< carl::Interval< Number >> & intervals, std::size_t I = 0)
Definition at line 69 of file Reset.tpp.
Referenced by hypro::HyproTransitionVisitor< Number >::visitJumps().
template<typename Number> void hypro::Reset< Number >::setMatrix (const matrix_t< Number > & in, std::size_t I = 0)
Definition at line 56 of file Reset.tpp.
Referenced by hypro::combine(), main(), hypro::Transformation< Number >::Transformation(), and hypro::HyproTransitionVisitor< Number >::visitJumps().
template<typename Number> void hypro::Reset< Number >::setVector (const vector_t< Number > & in, std::size_t I = 0)
Definition at line 44 of file Reset.tpp.
Referenced by hypro::combine(), main(), hypro::Transformation< Number >::Transformation(), and hypro::HyproTransitionVisitor< Number >::visitJumps().
template<typename Number> std::size_t hypro::Reset< Number >::size () const inline
Definition at line 56 of file Reset.h.
Referenced by hypro::applyReset(), hypro::combine(), std::hash< hypro::Reset< Number > >::operator()(), and hypro::Transformation< Number >::Transformation().
Friends And Related Function Documentation
template<typename Number> bool operator!= (const Reset< Number > & lhs, const Reset< Number > & rhs) friend
Definition at line 116 of file Reset.h.
template<typename Number> std::ostream& operator<< (std::ostream & ostr, const Reset< Number > & a) friend
Definition at line 83 of file Reset.h.
Member Data Documentation
template<typename Number> std::vector<AffineTransformation<Number> > hypro::Reset< Number >::mAffineResets protected
Definition at line 37 of file Reset.h.
template<typename Number> bool hypro::Reset< Number >::mDecomposed = false protected
Definition at line 40 of file Reset.h.
template<typename Number> std::size_t hypro::Reset< Number >::mHash = 0 mutable protected
Definition at line 39 of file Reset.h.
template<typename Number> std::vector<IntervalAssignment<Number> > hypro::Reset< Number >::mIntervalResets protected
Definition at line 38 of file Reset.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/Reset.h
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/Reset.tpp