HyPro: hypro::BoxT< double, Converter > Class Template Reference
hypro::BoxT< double, Converter > Class Template Reference
Class holding a specialization of the generic BoxT type with double numbers.
#include <Box_double.h>
Public Member Functions
BoxT ()
Creates an empty box.
BoxT (const BoxT &orig)=default
Copy constructor.
BoxT (BoxT &&orig)=default
Move constructor.
BoxT (const carl::Interval< double > &val)
Box constructor from one interval, results in a one-dimensional box.
BoxT (const std::pair< Point< double >, Point< double >> &limits)
Box constructor from a pair of points.
BoxT (const std::vector< carl::Interval< double >> &_intervals)
Constructor from a vector of intervals.
BoxT (const matrix_t< double > &_constraints, const vector_t< double > &_constants)
Constructor from a matrix and a vector.
BoxT (const std::set< Point< double >> &_points)
Constructor from a set of points.
BoxT (const std::vector< Point< double >> &_points)
A constructor from a vector of points.
~BoxT ()
Destructor.
std::vector< carl::Interval< double > > boundaries () const
Getter for interval representation of the current box.
const std::pair< Point< double >, Point< double > > & limits () const
Getter for the limiting points.
std::pair< Point< double >, Point< double > > & rLimits ()
Getter for a reference to the limit points.
matrix_t< double > matrix () const
vector_t< double > vector () const
std::vector< Halfspace< double > > constraints () const
Getter for the hyperplanar representation of the current box.
void insert (const carl::Interval< double > &val)
Extends the dimension of the current box by the given interval.
carl::Interval< double > interval (std::size_t d) const
Getter for an interval representation of one specific dimension.
carl::Interval< double > at (std::size_t _index) const
Getter for an interval representation of one specific dimension.
bool empty () const
Determines if the current box is empty.
bool isSymmetric () const
Determines if the current box is symmetric.
Point< double > max () const
Getter for the maximal point.
Point< double > min () const
Getter for the maximal point.
double supremum () const
Method returning the supremum point of the box, i.e. the maximal point.
std::vector< Point< double > > vertices (const Location< double > *=nullptr) const
Getter for a vertex-representation of the current box.
BoxT< double, Converter > & operator= (const BoxT< double, Converter > &rhs)=default
Assignment operator.
BoxT< double, Converter > & operator= (BoxT< double, Converter > &&rhs)=default
Move assignment operator.
BoxT< double, Converter > operator* (const double &factor) const
Scaling operator.
carl::Interval< double > operator[] (unsigned i) const
Access operator (const).
std::size_t dimension () const
Getter for the space dimension.
void removeRedundancy ()
Removes redundancy (part of the general interface. Does nothing for boxes.)
std::size_t size () const
Storage size determination.
const BoxT< double, Converter > & reduceNumberRepresentation (unsigned=fReach_DENOMINATOR)
Empty function for number size reduction, which is omitted when using native double numbers.
BoxT< double, Converter > makeSymmetric () const
Makes a symmetric box from the current box.
std::pair< bool, BoxT > satisfiesHalfspace (const Halfspace< double > &rhs) const
Checks, if the box lies inside the given halfspace.
std::pair< bool, BoxT > satisfiesHalfspaces (const matrix_t< double > &_mat, const vector_t< double > &_vec) const
Checks, if the box lies inside the given set of halfspaces.
BoxT< double, Converter > project (const std::vector< unsigned > &dimensions) const
Projects the box onto the given dimensions.
BoxT< double, Converter > linearTransformation (const matrix_t< double > &A) const
Applies a linear transformation to the box.
BoxT< double, Converter > affineTransformation (const matrix_t< double > &A, const vector_t< double > &b) const
Applies an affine transformation to the box.
BoxT< double, Converter > minkowskiSum (const BoxT< double, Converter > &rhs) const
Computes the Minkowski sum of two boxes.
BoxT< double, Converter > minkowskiDecomposition (const BoxT< double, Converter > &rhs) const
Computes the Minkowski decomposition of the current box by the given box.
BoxT< double, Converter > intersect (const BoxT< double, Converter > &rhs) const
Computes the intersection of two boxes.
BoxT< double, Converter > intersectHalfspace (const Halfspace< double > &hspace) const
Computes the intersection of the current box with a given halfspace.
BoxT< double, Converter > intersectHalfspaces (const matrix_t< double > &_mat, const vector_t< double > &_vec) const
Computes the intersection of the current box with a set of halfspaces.
bool contains (const Point< double > &point) const
Containment check for a point.
bool contains (const BoxT< double, Converter > &box) const
Containment check for a box.
BoxT< double, Converter > unite (const BoxT< double, Converter > &rhs) const
Computes the union of two boxes.
void clear ()
Makes this box the empty box.
void print () const
A deprecated print method. Use the outstream operator.
Public Member Functions inherited from hypro::GeometricObject< double, BoxT< double, Converter > >
virtual ~GeometricObject ()
Destroys the object.
Static Public Member Functions
static BoxT< double, Converter > Empty (std::size_t dimension=0)
Static method for the construction of an empty box of required dimension.
static representation_name type ()
static BoxT< double, Converter > unite (const std::vector< BoxT< double, Converter >> &boxes)
Computes the union of the current box with a set of boxes.
Protected Attributes
std::pair< Point< double >, Point< double > > mLimits
Friends
bool operator== (const BoxT< double, Converter > &b1, const BoxT< double, Converter > &b2)
Checks if two boxes are equal.
bool operator!= (const BoxT< double, Converter > &b1, const BoxT< double, Converter > &b2)
Determines inequality of two boxes.
std::ostream & operator<< (std::ostream &ostr, const BoxT< double, Converter > &)
Outstream operator.
Detailed Description
template<typename Converter>
class hypro::BoxT< double, Converter >
Class holding a specialization of the generic BoxT type with double numbers.
Template Parameters
Converter The used converter.
Definition at line 19 of file Box_double.h.
Constructor & Destructor Documentation
BoxT() [1/9]
template<typename Converter > hypro::BoxT< double, Converter >::BoxT () inline
Creates an empty box.
The empty box is represented by a zero-dimensional point pair.
Definition at line 37 of file Box_double.h.
References hypro::BoxT< Number, Converter >::BoxT(), hypro::BoxT< Number, Converter >::dimension(), and hypro::BoxT< Number, Converter >::empty().
BoxT() [2/9]
template<typename Converter > hypro::BoxT< double, Converter >::BoxT (const BoxT< double, Converter > & orig) default
Copy constructor.
Parameters
[in] orig The original.
BoxT() [3/9]
template<typename Converter > hypro::BoxT< double, Converter >::BoxT (BoxT< double, Converter > && orig) default
Move constructor.
Parameters
[in] orig The move-copyable original.
BoxT() [4/9]
template<typename Converter > hypro::BoxT< double, Converter >::BoxT (const carl::Interval< double > & val) inline explicit
Box constructor from one interval, results in a one-dimensional box.
Parameters
[in] val An interval.
Definition at line 55 of file Box_double.h.
BoxT() [5/9]
template<typename Converter > hypro::BoxT< double, Converter >::BoxT (const std::pair< Point< double >, Point< double >> & limits) inline explicit
Box constructor from a pair of points.
The given parameters are considered as the maximal and minimal point. The constructor does not check the order of points.
Parameters
limits Pair of points.
Definition at line 66 of file Box_double.h.
References hypro::BoxT< Number, Converter >::BoxT(), and hypro::BoxT< Number, Converter >::limits().
BoxT() [6/9]
template<typename Converter > hypro::BoxT< double, Converter >::BoxT (const std::vector< carl::Interval< double >> & _intervals) explicit
Constructor from a vector of intervals.
The vector is required to be sorted, i.e. the first interval maps to the first dimension etc..
Parameters
_intervals A vector of intervals.
BoxT() [7/9]
template<typename Converter > hypro::BoxT< double, Converter >::BoxT (const matrix_t< double > & _constraints, const vector_t< double > & _constants)
Constructor from a matrix and a vector.
Constructs a box assuming each row of the matrix is the normal to a hyperplane and its corresponding entry in the given vector is the offset.
Parameters
_constraints A matrix representing the constraint normals.
_constants A vector representing the offsets of the corresponting hyperplane.
BoxT() [8/9]
template<typename Converter > hypro::BoxT< double, Converter >::BoxT (const std::set< Point< double >> & _points) explicit
Constructor from a set of points.
The constructor does not rely on the operator < of the point class, thus each point is considered for the construction of the maximal and minimal point.
Parameters
_points A set of points.
BoxT() [9/9]
template<typename Converter > hypro::BoxT< double, Converter >::BoxT (const std::vector< Point< double >> & _points) explicit
A constructor from a vector of points.
Creates the maximal and minimal point by collecting all coordinates from all given points.
Parameters
_points A vector of points.
Member Function Documentation
affineTransformation()
template<typename Converter > BoxT<double,Converter> hypro::BoxT< double, Converter >::affineTransformation (const matrix_t< double > & A, const vector_t< double > & b) const virtual
Applies an affine transformation to the box.
The transformation is done on the two limit points directly. TODO: Add more extensive description here.
Parameters
[in] A A matrix for the affine transformation.
[in] b A vector for the offset.
Returns
The resulting box.
Implements hypro::GeometricObject< double, BoxT< double, Converter > >.
at()
template<typename Converter > carl::Interval<double> hypro::BoxT< double, Converter >::at (std::size_t _index) const inline
Getter for an interval representation of one specific dimension.
Converts the d-th entries in the maximal and minimal point to an interval.
Parameters
d The queried dimension.
Returns
An interval.
Definition at line 171 of file Box_double.h.
boundaries()
template<typename Converter > std::vector<carl::Interval<double> > hypro::BoxT< double, Converter >::boundaries () const
Getter for interval representation of the current box.
Converts the two-points representation of the current box into a sorted vector of intervals.
Returns
A vector of intervals.
constraints()
template<typename Converter > std::vector<Halfspace<double> > hypro::BoxT< double, Converter >::constraints () const
Getter for the hyperplanar representation of the current box.
Converts the two-points representation into a hyperplanar representation, i.e. a H-polytope.
Returns
A vector of hyperplanes.
contains() [1/2]
template<typename Converter > bool hypro::BoxT< double, Converter >::contains (const Point< double > & point) const virtual
Containment check for a point.
Parameters
[in] point The point.
Returns
True, if the point is contained inside the current box, false otherwise.
Implements hypro::GeometricObject< double, BoxT< double, Converter > >.
contains() [2/2]
template<typename Converter > bool hypro::BoxT< double, Converter >::contains (const BoxT< double, Converter > & box) const
Containment check for a box.
Parameters
[in] box The box.
Returns
True, if the given box is contained in the current box, false otherwise.
dimension()
template<typename Converter > std::size_t hypro::BoxT< double, Converter >::dimension () const inline virtual
Getter for the space dimension.
Returns
The dimension of the space.
Implements hypro::GeometricObject< double, BoxT< double, Converter > >.
Definition at line 322 of file Box_double.h.
Empty()
template<typename Converter > static BoxT<double,Converter> hypro::BoxT< double, Converter >::Empty (std::size_t dimension = 0) inline static
Static method for the construction of an empty box of required dimension.
Parameters
dimension Required dimension.
Returns
Empty box.
Definition at line 117 of file Box_double.h.
References hypro::BoxT< Number, Converter >::boundaries(), and hypro::BoxT< Number, Converter >::dimension().
empty()
template<typename Converter > bool hypro::BoxT< double, Converter >::empty () const inline virtual
Determines if the current box is empty.
The method checks the dimension of the limit points and afterwards each interval for emptiness.
Returns
True, if one interval is empty. False if the dimension is 0 or no interval is empty.
Implements hypro::GeometricObject< double, BoxT< double, Converter > >.
Definition at line 183 of file Box_double.h.
insert()
template<typename Converter > void hypro::BoxT< double, Converter >::insert (const carl::Interval< double > & val) inline
Extends the dimension of the current box by the given interval.
Effectively extends the dimension of the current box.
Parameters
val An interval.
Definition at line 155 of file Box_double.h.
References hypro::BoxT< Number, Converter >::interval().
intersect()
template<typename Converter > BoxT<double,Converter> hypro::BoxT< double, Converter >::intersect (const BoxT< double, Converter > & rhs) const
Computes the intersection of two boxes.
Parameters
[in] rhs The right hand side box.
Returns
The resulting box.
intersectHalfspace()
template<typename Converter > BoxT<double,Converter> hypro::BoxT< double, Converter >::intersectHalfspace (const Halfspace< double > & hspace) const virtual
Computes the intersection of the current box with a given halfspace.
Parameters
[in] hspace The halfspace.
Returns
The resulting box.
Implements hypro::GeometricObject< double, BoxT< double, Converter > >.
intersectHalfspaces()
template<typename Converter > BoxT<double,Converter> hypro::BoxT< double, Converter >::intersectHalfspaces (const matrix_t< double > & _mat, const vector_t< double > & _vec) const virtual
Computes the intersection of the current box with a set of halfspaces.
Parameters
[in] _mat The matrix representing the normal vectors.
[in] _vec The vector representing the offsets.
Returns
The resulting box.
Implements hypro::GeometricObject< double, BoxT< double, Converter > >.
interval()
template<typename Converter > carl::Interval<double> hypro::BoxT< double, Converter >::interval (std::size_t d) const
Getter for an interval representation of one specific dimension.
Converts the d-th entries in the maximal and minimal point to an interval.
Parameters
d The queried dimension.
Returns
An interval.
isSymmetric()
template<typename Converter > bool hypro::BoxT< double, Converter >::isSymmetric () const inline
Determines if the current box is symmetric.
A box is symmetric, if its centroid is the origin in the respective space, i.e. if the center of each interval in each dimension is zero.
Returns
True if symmetric, False otherwise.
Definition at line 202 of file Box_double.h.
limits()
template<typename Converter > const std::pair<Point<double>, Point<double> >& hypro::BoxT< double, Converter >::limits () const inline
Getter for the limiting points.
Returns
A pair of points.
Definition at line 132 of file Box_double.h.
References hypro::BoxT< Number, Converter >::mLimits.
linearTransformation()
template<typename Converter > BoxT<double,Converter> hypro::BoxT< double, Converter >::linearTransformation (const matrix_t< double > & A) const virtual
Applies a linear transformation to the box.
The transformation is done on the two limit points directly. TODO: Add more extensive description here.
Parameters
[in] A A matrix for the linear transformation.
Returns
The resulting box.
Implements hypro::GeometricObject< double, BoxT< double, Converter > >.
makeSymmetric()
template<typename Converter > BoxT<double,Converter> hypro::BoxT< double, Converter >::makeSymmetric () const
Makes a symmetric box from the current box.
The symmetry is obtained by dimension-wise extension of the boundaries. The resulting boundaries for each dimension are the maximal absolute values of the original boundaries mirrored positive and negative.
Returns
The resulting symmetric box.
max()
template<typename Converter > Point<double> hypro::BoxT< double, Converter >::max () const inline
Getter for the maximal point.
Returns
A point.
Definition at line 218 of file Box_double.h.
min()
template<typename Converter > Point<double> hypro::BoxT< double, Converter >::min () const inline
Getter for the maximal point.
Returns
A point.
Definition at line 226 of file Box_double.h.
References hypro::BoxT< Number, Converter >::supremum(), and hypro::BoxT< Number, Converter >::vertices().
Referenced by operator*().
minkowskiDecomposition()
template<typename Converter > BoxT<double,Converter> hypro::BoxT< double, Converter >::minkowskiDecomposition (const BoxT< double, Converter > & rhs) const
Computes the Minkowski decomposition of the current box by the given box.
Parameters
[in] rhs The right hand side box.
Returns
The resulting box.
minkowskiSum()
template<typename Converter > BoxT<double,Converter> hypro::BoxT< double, Converter >::minkowskiSum (const BoxT< double, Converter > & rhs) const virtual
Computes the Minkowski sum of two boxes.
Parameters
[in] rhs The right hand side box.
Returns
The resulting box.
Implements hypro::GeometricObject< double, BoxT< double, Converter > >.
operator*()
template<typename Converter > BoxT<double,Converter> hypro::BoxT< double, Converter >::operator* (const double & factor) const inline
Scaling operator.
Parameters
[in] factor The scaling factor.
Returns
The scaled box.
Definition at line 282 of file Box_double.h.
References hypro::BoxT< Number, Converter >::empty(), and min().
operator=() [1/2]
template<typename Converter > BoxT<double,Converter>& hypro::BoxT< double, Converter >::operator= (const BoxT< double, Converter > & rhs) default
Assignment operator.
Parameters
rhs A box.
operator=() [2/2]
template<typename Converter > BoxT<double,Converter>& hypro::BoxT< double, Converter >::operator= (BoxT< double, Converter > && rhs) default
Move assignment operator.
Parameters
rhs A box.
operator[]()
template<typename Converter > carl::Interval<double> hypro::BoxT< double, Converter >::operator[] (unsigned i) const inline
Access operator (const).
Parameters
i Dimension to access.
Returns
An interval.
Definition at line 312 of file Box_double.h.
project()
template<typename Converter > BoxT<double,Converter> hypro::BoxT< double, Converter >::project (const std::vector< unsigned > & dimensions) const virtual
Projects the box onto the given dimensions.
Parameters
[in] dimensions The dimensions.
Returns
The projected box.
Implements hypro::GeometricObject< double, BoxT< double, Converter > >.
reduceNumberRepresentation()
template<typename Converter > const BoxT<double,Converter>& hypro::BoxT< double, Converter >::reduceNumberRepresentation (unsigned = fReach_DENOMINATOR) inline
Empty function for number size reduction, which is omitted when using native double numbers.
Parameters
limit Parameter for a length estimation.
Definition at line 341 of file Box_double.h.
References hypro::BoxT< Number, Converter >::affineTransformation(), hypro::BoxT< Number, Converter >::clear(), hypro::BoxT< Number, Converter >::contains(), hypro::BoxT< Number, Converter >::intersect(), hypro::BoxT< Number, Converter >::intersectHalfspace(), hypro::BoxT< Number, Converter >::intersectHalfspaces(), hypro::BoxT< Number, Converter >::linearTransformation(), hypro::BoxT< Number, Converter >::makeSymmetric(), hypro::BoxT< Number, Converter >::minkowskiDecomposition(), hypro::BoxT< Number, Converter >::minkowskiSum(), hypro::BoxT< Number, Converter >::print(), hypro::BoxT< Number, Converter >::project(), hypro::BoxT< Number, Converter >::satisfiesHalfspace(), hypro::BoxT< Number, Converter >::satisfiesHalfspaces(), and hypro::BoxT< Number, Converter >::unite().
rLimits()
template<typename Converter > std::pair<Point<double>, Point<double> >& hypro::BoxT< double, Converter >::rLimits () inline
Getter for a reference to the limit points.
Returns
A reference to the limit point pair of the object.
Definition at line 138 of file Box_double.h.
References hypro::BoxT< Number, Converter >::constraints(), and hypro::BoxT< Number, Converter >::mLimits.
satisfiesHalfspace()
template<typename Converter > std::pair<bool, BoxT> hypro::BoxT< double, Converter >::satisfiesHalfspace (const Halfspace< double > & rhs) const virtual
Checks, if the box lies inside the given halfspace.
This function combines the intersection with a given halfspace along with the emptiness test on the result, which is often faster than the sequential execution of both commands.
Parameters
[in] rhs The halfspace.
Returns
A pair of a Boolean value and a box. The Boolean is true in case the resulting box is not empty and false otherwise.
Implements hypro::GeometricObject< double, BoxT< double, Converter > >.
satisfiesHalfspaces()
template<typename Converter > std::pair<bool, BoxT> hypro::BoxT< double, Converter >::satisfiesHalfspaces (const matrix_t< double > & _mat, const vector_t< double > & _vec) const virtual
Checks, if the box lies inside the given set of halfspaces.
This function combines the intersection with a given set of halfspaces along with the emptiness test on the result, which is often faster than the sequential execution of both commands.
Parameters
[in] _mat The normals of the halfspaces.
[in] _vec The offsets of the halfspaces.
Returns
A pair of a Boolean value and a box. The Boolean is true in case the resulting box is not empty and false otherwise.
Implements hypro::GeometricObject< double, BoxT< double, Converter > >.
size()
template<typename Converter > std::size_t hypro::BoxT< double, Converter >::size () const
Storage size determination.
Returns
Size of the required memory.
supremum()
template<typename Converter > double hypro::BoxT< double, Converter >::supremum () const
Method returning the supremum point of the box, i.e. the maximal point.
Returns
A point representing the supremum of the current box.
unite() [1/2]
template<typename Converter > BoxT<double,Converter> hypro::BoxT< double, Converter >::unite (const BoxT< double, Converter > & rhs) const virtual
Computes the union of two boxes.
Parameters
[in] rhs The right hand side box.
Returns
The resulting box.
Implements hypro::GeometricObject< double, BoxT< double, Converter > >.
unite() [2/2]
template<typename Converter > static BoxT<double,Converter> hypro::BoxT< double, Converter >::unite (const std::vector< BoxT< double, Converter >> & boxes) static
Computes the union of the current box with a set of boxes.
Parameters
[in] boxes The boxes.
Returns
The resulting box.
vertices()
template<typename Converter > std::vector<Point<double> > hypro::BoxT< double, Converter >::vertices (const Location< double > * = nullptr) const virtual
Getter for a vertex-representation of the current box.
Converts the current box from its two-point representation into a vertex representation, i.e. a V-polytope. The representation is generated by creating all possible combinations of upper and lower bounds of the box.
Returns
A vector of points.
Implements hypro::GeometricObject< double, BoxT< double, Converter > >.
Friends And Related Function Documentation
operator!=
template<typename Converter > bool operator!= (const BoxT< double, Converter > & b1, const BoxT< double, Converter > & b2) friend
Determines inequality of two boxes.
Parameters
b1 A box.
b2 A box.
Returns
False, if both boxes are equal.
Definition at line 263 of file Box_double.h.
operator<<
template<typename Converter > std::ostream& operator<< (std::ostream & ostr, const BoxT< double, Converter > &) friend
Outstream operator.
Parameters
ostr Outstream.
b A box.
Definition at line 302 of file Box_double.h.
operator==
template<typename Converter > bool operator== (const BoxT< double, Converter > & b1, const BoxT< double, Converter > & b2) friend
Checks if two boxes are equal.
Parameters
b1 Contains the first box.
b2 Contains the second box.
Returns
True, if they are equal.
Definition at line 250 of file Box_double.h.
Member Data Documentation
mLimits
template<typename Converter > std::pair<Point<double>, Point<double> > hypro::BoxT< double, Converter >::mLimits protected
Pair of points describing the minimal and the maximal point of the box.
Definition at line 26 of file Box_double.h.
The documentation for this class was generated from the following file:
/Users/travis/build/hypro/hypro/src/hypro/representations/Box/Box_double.h