HyPro: hypro::BallSupportFunction< Number > Class Template Reference
hypro::BallSupportFunction< Number > Class Template Reference
Public Member Functions
BallSupportFunction (const BallSupportFunction< Number > &_orig)
BallSupportFunction (Number _radius, SF_TYPE _type)
~BallSupportFunction ()
unsigned dimension () const
Number radius () const
SF_TYPE type () const
void setDimension (unsigned dim)
Point< Number > supremumPoint () const
EvaluationResult< Number > evaluate (const vector_t< Number > &l) const
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &_A) const
Evaluates the support function in the directions given in the passed matrix.
bool contains (const Point< Number > &_point) const
Check if point is contained in the support function.
bool contains (const vector_t< Number > &_point) const
Check if point is contained in the support function.
bool empty () const
Detailed Description
template<typename Number>
class hypro::BallSupportFunction< Number >
Definition at line 20 of file BallSupportFunction.h.
Constructor & Destructor Documentation
template<typename Number > hypro::BallSupportFunction< Number >::BallSupportFunction (const BallSupportFunction< Number > & _orig)
Definition at line 26 of file BallSupportFunction.tpp.
template<typename Number > hypro::BallSupportFunction< Number >::BallSupportFunction (Number _radius, SF_TYPE _type)
Definition at line 18 of file BallSupportFunction.tpp.
References hypro::INFTY_BALL, and hypro::TWO_BALL.
template<typename Number > hypro::BallSupportFunction< Number >::~BallSupportFunction ()
Definition at line 33 of file BallSupportFunction.tpp.
Member Function Documentation
template<typename Number > bool hypro::BallSupportFunction< Number >::contains (const Point< Number > & _point) const
Check if point is contained in the support function.
To check if the given point is contained in the support function we evaluate it in all its directions (uses multiEvaluate).
Parameters
_point The point to check.
Returns
True, if the point is inside the support function.
Definition at line 121 of file BallSupportFunction.tpp.
References hypro::Point< Number >::rawCoordinates().
Referenced by hypro::BallSupportFunction< Number >::setDimension().
template<typename Number > bool hypro::BallSupportFunction< Number >::contains (const vector_t< Number > & _point) const
Check if point is contained in the support function.
To check if the given point is contained in the support function we evaluate it in all its directions (uses multiEvaluate).
Parameters
_point The point to check.
Returns
True, if the point is inside the support function.
Definition at line 126 of file BallSupportFunction.tpp.
References hypro::INFTY_BALL, and hypro::TWO_BALL.
template<typename Number > unsigned hypro::BallSupportFunction< Number >::dimension () const
Returns the dimension of the object.
Returns
Definition at line 37 of file BallSupportFunction.tpp.
Referenced by hypro::BallSupportFunction< Number >::supremumPoint().
template<typename Number > bool hypro::BallSupportFunction< Number >::empty () const
Definition at line 143 of file BallSupportFunction.tpp.
Referenced by hypro::BallSupportFunction< Number >::setDimension().
template<typename Number > EvaluationResult< Number > hypro::BallSupportFunction< Number >::evaluate (const vector_t< Number > & l) const
Evaluates the support function in the given direction.
Parameters
l
Returns
Definition at line 59 of file BallSupportFunction.tpp.
References hypro::EvaluationResult< Number >::errorCode, hypro::FEAS, hypro::INFTY_BALL, hypro::normalize(), hypro::EvaluationResult< Number >::optimumValue, hypro::EvaluationResult< Number >::supportValue, and hypro::TWO_BALL.
Referenced by hypro::BallSupportFunction< Number >::setDimension().
template<typename Number > std::vector< EvaluationResult< Number > > hypro::BallSupportFunction< Number >::multiEvaluate (const matrix_t< Number > & _A) const
Evaluates the support function in the directions given in the passed matrix.
Uses the standard evaluate method for multiple directions.
Parameters
_A Matrix holding the directions in which to evaluate.
Returns
Vector of support values.
Definition at line 105 of file BallSupportFunction.tpp.
References hypro::EvaluationResult< Number >::errorCode, hypro::FEAS, hypro::INFEAS, hypro::normalize(), and hypro::EvaluationResult< Number >::supportValue.
Referenced by hypro::BallSupportFunction< Number >::setDimension().
template<typename Number > Number hypro::BallSupportFunction< Number >::radius () const
Definition at line 42 of file BallSupportFunction.tpp.
template<typename Number> void hypro::BallSupportFunction< Number >::setDimension (unsigned dim) inline
Definition at line 40 of file BallSupportFunction.h.
References hypro::BallSupportFunction< Number >::contains(), hypro::BallSupportFunction< Number >::empty(), hypro::BallSupportFunction< Number >::evaluate(), hypro::BallSupportFunction< Number >::multiEvaluate(), and hypro::BallSupportFunction< Number >::supremumPoint().
template<typename Number > Point< Number > hypro::BallSupportFunction< Number >::supremumPoint () const
Definition at line 52 of file BallSupportFunction.tpp.
References hypro::BallSupportFunction< Number >::dimension().
Referenced by hypro::BallSupportFunction< Number >::setDimension().
template<typename Number > SF_TYPE hypro::BallSupportFunction< Number >::type () const
Definition at line 47 of file BallSupportFunction.tpp.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunction/BallSupportFunction.h
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunction/BallSupportFunction.tpp