HyPro: hypro::LTIWorker< State > Class Template Reference
hypro::LTIWorker< State > Class Template Reference
#include <LTIWorker.h>
Public Member Functions
LTIWorker (const HybridAutomaton< Number > &ha, const Settings &settings)
REACHABILITY_RESULT computeForwardReachability (const ReachTreeNode< State > &task)
REACHABILITY_RESULT computeTimeSuccessors (const ReachTreeNode< State > &task)
void computeJumpSuccessors ()
const JumpSuccessors & getJumpSuccessorSets () const
const Flowpipe< State > & getFlowpipe () const
Protected Attributes
const HybridAutomaton< Number > & mHybridAutomaton
const Settings & mSettings
JumpSuccessors mJumpSuccessorSets
Flowpipe< State > mFlowpipe
Private Types
using Number = typename State::NumberType
using JumpSuccessors = typename ltiGuardHandler< State >::TransitionStatesMap
Private Member Functions
void postProcessJumpSuccessors (const JumpSuccessors &guardSatisfyingSets)
bool requireTimeSuccessorComputation (std::size_t segmentCount) const
Detailed Description
template<typename State>
class hypro::LTIWorker< State >
Definition at line 18 of file LTIWorker.h.
Member Typedef Documentation
template<typename State > using hypro::LTIWorker< State >::JumpSuccessors = typename ltiGuardHandler<State>::TransitionStatesMap private
Definition at line 21 of file LTIWorker.h.
template<typename State > using hypro::LTIWorker< State >::Number = typename State::NumberType private
Definition at line 20 of file LTIWorker.h.
Constructor & Destructor Documentation
template<typename State > hypro::LTIWorker< State >::LTIWorker (const HybridAutomaton< Number > & ha, const Settings & settings) inline
Definition at line 24 of file LTIWorker.h.
References hypro::LTIWorker< State >::computeForwardReachability(), hypro::LTIWorker< State >::computeJumpSuccessors(), and hypro::LTIWorker< State >::computeTimeSuccessors().
Member Function Documentation
template<typename State > REACHABILITY_RESULT hypro::LTIWorker< State >::computeForwardReachability (const ReachTreeNode< State > & task)
Referenced by hypro::LTIWorker< State >::LTIWorker().
template<typename State > void hypro::LTIWorker< State >::computeJumpSuccessors ()
Referenced by hypro::LTIWorker< State >::LTIWorker().
template<typename State > REACHABILITY_RESULT hypro::LTIWorker< State >::computeTimeSuccessors (const ReachTreeNode< State > & task)
Referenced by hypro::LTIWorker< State >::LTIWorker().
template<typename State > const Flowpipe<State>& hypro::LTIWorker< State >::getFlowpipe () const inline
Definition at line 34 of file LTIWorker.h.
References hypro::LTIWorker< State >::mFlowpipe, and hypro::LTIWorker< State >::postProcessJumpSuccessors().
template<typename State > const JumpSuccessors& hypro::LTIWorker< State >::getJumpSuccessorSets () const inline
Definition at line 33 of file LTIWorker.h.
References hypro::LTIWorker< State >::mJumpSuccessorSets.
template<typename State > void hypro::LTIWorker< State >::postProcessJumpSuccessors (const JumpSuccessors & guardSatisfyingSets) private
Referenced by hypro::LTIWorker< State >::getFlowpipe().
template<typename State > bool hypro::LTIWorker< State >::requireTimeSuccessorComputation (std::size_t segmentCount) const inline private
Definition at line 39 of file LTIWorker.h.
References hypro::Settings::localTimeHorizon, hypro::LTIWorker< State >::mSettings, and hypro::Settings::strategy.
Member Data Documentation
template<typename State > Flowpipe<State> hypro::LTIWorker< State >::mFlowpipe protected
Definition at line 45 of file LTIWorker.h.
Referenced by hypro::LTIWorker< State >::getFlowpipe().
template<typename State > const HybridAutomaton<Number>& hypro::LTIWorker< State >::mHybridAutomaton protected
Definition at line 42 of file LTIWorker.h.
template<typename State > JumpSuccessors hypro::LTIWorker< State >::mJumpSuccessorSets protected
Definition at line 44 of file LTIWorker.h.
Referenced by hypro::LTIWorker< State >::getJumpSuccessorSets().
template<typename State > const Settings& hypro::LTIWorker< State >::mSettings protected
Definition at line 43 of file LTIWorker.h.
Referenced by hypro::LTIWorker< State >::requireTimeSuccessorComputation().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/workers/LTIWorker.h