HyPro: hypro::TreeNode< Data > Class Template Reference
hypro::TreeNode< Data > Class Template Reference
Class for an n-ary tree.
#include <TreeNode.h>
Public Types
using Node_t = Data *
pointer to parent node, nullptr if root.
using const_Node_t = const Data *
using NodeList_t = std::vector< Data * >
Public Member Functions
TreeNode ()
TreeNode (unsigned _depth, const std::vector< Data * > &_children, Data *_parent)
~TreeNode ()
int getDepth () const
std::size_t getSubtreeDepth () const
std::size_t getSubtreeSize () const
double getAvgSubtreeBranching () const
const std::vector< Data * > & getChildren () const
Data * getParent () const
void setDepth (int _depth)
void addChild (Data *child)
void setParent (Data *parent)
Protected Attributes
int mDepth
std::vector< Data * > mChildren
depth cache
Data * mParent
children list
Friends
bool operator== (const TreeNode< Data > &lhs, const TreeNode< Data > &rhs)
Detailed Description
template<typename Data>
class hypro::TreeNode< Data >
Class for an n-ary tree.
Template Parameters
Data Data type stored in the tree nodes.
Definition at line 17 of file TreeNode.h.
Member Typedef Documentation
template<typename Data> using hypro::TreeNode< Data >::const_Node_t = const Data*
Definition at line 25 of file TreeNode.h.
template<typename Data> using hypro::TreeNode< Data >::Node_t = Data*
pointer to parent node, nullptr if root.
Definition at line 24 of file TreeNode.h.
template<typename Data> using hypro::TreeNode< Data >::NodeList_t = std::vector<Data*>
Definition at line 26 of file TreeNode.h.
Constructor & Destructor Documentation
template<typename Data> hypro::TreeNode< Data >::TreeNode () inline
Definition at line 28 of file TreeNode.h.
template<typename Data> hypro::TreeNode< Data >::TreeNode (unsigned _depth, const std::vector< Data * > & _children, Data * _parent) inline
Definition at line 33 of file TreeNode.h.
template<typename Data> hypro::TreeNode< Data >::~TreeNode () inline
Definition at line 52 of file TreeNode.h.
Member Function Documentation
template<typename Data> void hypro::TreeNode< Data >::addChild (Data * child) inline
Definition at line 136 of file TreeNode.h.
template<typename Data> double hypro::TreeNode< Data >::getAvgSubtreeBranching () const inline
Definition at line 95 of file TreeNode.h.
template<typename Data> const std::vector<Data*>& hypro::TreeNode< Data >::getChildren () const inline
Definition at line 111 of file TreeNode.h.
Referenced by hypro::TreeNode< ReachTreeNode< State > >::getAvgSubtreeBranching(), hypro::TreeNode< ReachTreeNode< State > >::getSubtreeDepth(), and hypro::TreeNode< ReachTreeNode< State > >::getSubtreeSize().
template<typename Data> int hypro::TreeNode< Data >::getDepth () const inline
Definition at line 58 of file TreeNode.h.
Referenced by hypro::TreeNode< ReachTreeNode< State > >::addChild().
template<typename Data> Data* hypro::TreeNode< Data >::getParent () const inline
Definition at line 115 of file TreeNode.h.
Referenced by hypro::TreeNode< ReachTreeNode< State > >::getDepth(), hypro::TreeNode< ReachTreeNode< State > >::setDepth(), and hypro::TreeNode< ReachTreeNode< State > >::TreeNode().
template<typename Data> std::size_t hypro::TreeNode< Data >::getSubtreeDepth () const inline
Definition at line 74 of file TreeNode.h.
template<typename Data> std::size_t hypro::TreeNode< Data >::getSubtreeSize () const inline
Definition at line 85 of file TreeNode.h.
template<typename Data> void hypro::TreeNode< Data >::setDepth (int _depth) inline
Definition at line 119 of file TreeNode.h.
template<typename Data> void hypro::TreeNode< Data >::setParent (Data * parent) inline
Definition at line 143 of file TreeNode.h.
Friends And Related Function Documentation
template<typename Data> bool operator== (const TreeNode< Data > & lhs, const TreeNode< Data > & rhs) friend
Definition at line 149 of file TreeNode.h.
Member Data Documentation
template<typename Data> std::vector<Data*> hypro::TreeNode< Data >::mChildren protected
depth cache
Definition at line 20 of file TreeNode.h.
Referenced by hypro::TreeNode< ReachTreeNode< State > >::getChildren().
template<typename Data> int hypro::TreeNode< Data >::mDepth protected
Definition at line 19 of file TreeNode.h.
Referenced by hypro::TreeNode< ReachTreeNode< State > >::getDepth().
template<typename Data> Data* hypro::TreeNode< Data >::mParent protected
children list
Definition at line 21 of file TreeNode.h.
Referenced by hypro::TreeNode< ReachTreeNode< State > >::getParent().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/TreeNode.h