HyPro: hypro::IContext Class Reference
hypro::IContext Class Reference abstract
#include <IContext.h>
Public Member Functions
virtual void execOnStart ()
virtual void execBeforeFirstSegment ()
virtual void firstSegment ()=0
virtual void execAfterFirstSegment ()
virtual void execBeforeCheckInvariant ()
virtual void checkInvariant ()=0
virtual void execAfterCheckInvariant ()
virtual void execBeforeIntersectBadStates ()
virtual void intersectBadStates ()=0
virtual void execAfterIntersectBadStates ()
virtual void execBeforeLoop ()
virtual bool doneCondition ()=0
virtual void execOnLoopItEnter ()
virtual void execBeforeCheckTransition ()
virtual void checkTransition ()=0
virtual void execAfterCheckTransition ()
virtual void execBeforeContinuousEvolution ()
virtual void applyContinuousEvolution ()=0
virtual void execAfterContinuousEvolution ()
virtual void execOnLoopItExit ()
virtual void execAfterLoop ()
virtual void execBeforeProcessDiscreteBehavior ()
virtual void processDiscreteBehavior ()=0
virtual void execAfterProcessDiscreteBehavior ()
virtual void execOnEnd ()
Detailed Description
Definition at line 10 of file IContext.h.
Member Function Documentation
virtual void hypro::IContext::applyContinuousEvolution () pure virtual
Implemented in hypro::LTIContext< State >, hypro::RectangularContext< State >, hypro::TemplatePolyhedronContext< State >, and hypro::TimedContext< State >.
Referenced by execBeforeContinuousEvolution().
virtual void hypro::IContext::checkInvariant () pure virtual
Implemented in hypro::LTIContext< State >, hypro::RectangularContext< State >, and hypro::TimedContext< State >.
Referenced by execBeforeCheckInvariant().
virtual void hypro::IContext::checkTransition () pure virtual
Implemented in hypro::LTIContext< State >, hypro::RectangularContext< State >, and hypro::TimedContext< State >.
Referenced by execBeforeCheckTransition().
virtual bool hypro::IContext::doneCondition () pure virtual
Implemented in hypro::LTIContext< State >, hypro::RectangularContext< State >, and hypro::TimedContext< State >.
Referenced by execBeforeLoop().
virtual void hypro::IContext::execAfterCheckInvariant () inline virtual
Definition at line 26 of file IContext.h.
virtual void hypro::IContext::execAfterCheckTransition () inline virtual
Definition at line 44 of file IContext.h.
virtual void hypro::IContext::execAfterContinuousEvolution () inline virtual
Definition at line 50 of file IContext.h.
virtual void hypro::IContext::execAfterFirstSegment () inline virtual
Reimplemented in hypro::LTIContext< State >, and hypro::RectangularContext< State >.
Definition at line 20 of file IContext.h.
virtual void hypro::IContext::execAfterIntersectBadStates () inline virtual
Definition at line 32 of file IContext.h.
virtual void hypro::IContext::execAfterLoop () inline virtual
Definition at line 54 of file IContext.h.
virtual void hypro::IContext::execAfterProcessDiscreteBehavior () inline virtual
Definition at line 60 of file IContext.h.
virtual void hypro::IContext::execBeforeCheckInvariant () inline virtual
Definition at line 22 of file IContext.h.
References checkInvariant().
virtual void hypro::IContext::execBeforeCheckTransition () inline virtual
Definition at line 40 of file IContext.h.
References checkTransition().
virtual void hypro::IContext::execBeforeContinuousEvolution () inline virtual
Definition at line 46 of file IContext.h.
References applyContinuousEvolution().
virtual void hypro::IContext::execBeforeFirstSegment () inline virtual
Reimplemented in hypro::TemplatePolyhedronContext< State >, hypro::LTIContext< State >, and hypro::RectangularContext< State >.
Definition at line 16 of file IContext.h.
References firstSegment().
virtual void hypro::IContext::execBeforeIntersectBadStates () inline virtual
Definition at line 28 of file IContext.h.
References intersectBadStates().
virtual void hypro::IContext::execBeforeLoop () inline virtual
Reimplemented in hypro::LTIContext< State >, and hypro::RectangularContext< State >.
Definition at line 34 of file IContext.h.
References doneCondition().
virtual void hypro::IContext::execBeforeProcessDiscreteBehavior () inline virtual
Reimplemented in hypro::TemplatePolyhedronContext< State >.
Definition at line 56 of file IContext.h.
References processDiscreteBehavior().
virtual void hypro::IContext::execOnEnd () inline virtual
Reimplemented in hypro::LTIContext< State >, and hypro::RectangularContext< State >.
Definition at line 62 of file IContext.h.
virtual void hypro::IContext::execOnLoopItEnter () inline virtual
Definition at line 38 of file IContext.h.
virtual void hypro::IContext::execOnLoopItExit () inline virtual
Reimplemented in hypro::LTIContext< State >, hypro::RectangularContext< State >, and hypro::TimedContext< State >.
Definition at line 52 of file IContext.h.
virtual void hypro::IContext::execOnStart () inline virtual
Reimplemented in hypro::LTIContext< State >, and hypro::RectangularContext< State >.
Definition at line 14 of file IContext.h.
virtual void hypro::IContext::firstSegment () pure virtual
Implemented in hypro::TemplatePolyhedronContext< State >, hypro::LTIContext< State >, and hypro::RectangularContext< State >.
Referenced by execBeforeFirstSegment().
virtual void hypro::IContext::intersectBadStates () pure virtual
Implemented in hypro::LTIContext< State >, and hypro::RectangularContext< State >.
Referenced by execBeforeIntersectBadStates().
virtual void hypro::IContext::processDiscreteBehavior () pure virtual
Implemented in hypro::LTIContext< State >, and hypro::RectangularContext< State >.
Referenced by execBeforeProcessDiscreteBehavior().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/contexts/IContext.h