HyPro: hypro::GeneralizedStarT< Number, Converter, Setting > Class Template Reference
hypro::GeneralizedStarT< Number, Converter, Setting > Class Template Reference
State set representations
The class which represents a GeneralizedStar.
Public Types
typedef Number NumberType
typedef Setting Settings
Public Member Functions
GeneralizedStarT ()
Creates an empty GeneralizedStar.
GeneralizedStarT (const GeneralizedStarT &orig)
Copy constructor.
template<typename SettingRhs , carl::DisableIf< std::is_same< Setting, SettingRhs >> = carl::dummy>
GeneralizedStarT (const GeneralizedStarT< Number, Converter, SettingRhs > &orig)
Settings conversion constructor.
GeneralizedStarT (GeneralizedStarT &&orig)
Move constructor.
~GeneralizedStarT ()
Destructor.
Setting getSettings () const
bool empty () const
Determines if the current GeneralizedStar is empty.
Number supremum () const
Method returning the supremum point of the GeneralizedStar, i.e. the maximal point.
std::vector< Point< Number > > vertices (const matrix_t< Number > &=matrix_t< Number >::Zero(0, 0)) const
Getter for a vertex-representation of the current GeneralizedStar.
EvaluationResult< Number > evaluate (const vector_t< Number > &_direction, bool) const
Evaluation function (convex linear optimization).
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &_directions, bool useExact=true) const
Multi-evaluation function (convex linear optimization).
GeneralizedStarT< Number, Converter, Setting > & operator= (const GeneralizedStarT< Number, Converter, Setting > &rhs)=default
Assignment operator.
GeneralizedStarT< Number, Converter, Setting > & operator= (GeneralizedStarT< Number, Converter, Setting > &&rhs)=default
Move assignment operator.
std::size_t dimension () const
Getter for the space dimension.
void removeRedundancy ()
Removes redundancy.
std::size_t size () const
Storage size determination.
const GeneralizedStarT & reduceNumberRepresentation ()
Function to reduce the number representation (over-approximate).
std::pair< CONTAINMENT, GeneralizedStarT > satisfiesHalfspace (const Halfspace< Number > &rhs) const
std::pair< CONTAINMENT, GeneralizedStarT > satisfiesHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const
GeneralizedStarT project (const std::vector< std::size_t > &dimensions) const
GeneralizedStarT assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const
GeneralizedStarT linearTransformation (const matrix_t< Number > &A) const
GeneralizedStarT affineTransformation (const matrix_t< Number > &A, const vector_t< Number > &b) const
GeneralizedStarT minkowskiSum (const GeneralizedStarT &rhs) const
GeneralizedStarT intersect (const GeneralizedStarT &rhs) const
Computes the intersection of two GeneralizedStares.
GeneralizedStarT intersectHalfspace (const Halfspace< Number > &hspace) const
GeneralizedStarT intersectHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const
bool contains (const Point< Number > &point) const
bool contains (const GeneralizedStarT &GeneralizedStar) const
Containment check for a GeneralizedStar.
GeneralizedStarT unite (const GeneralizedStarT &rhs) const
Computes the union of two GeneralizedStares.
void reduceRepresentation ()
Reduces the representation of the current GeneralizedStar.
void clear ()
Makes this GeneralizedStar equal to the empty GeneralizedStar.
Static Public Member Functions
static GeneralizedStarT Empty ()
Static method for the construction of an empty GeneralizedStar of required dimension.
static representation_name type ()
static GeneralizedStarT unite (const std::vector< GeneralizedStarT > &GeneralizedStares)
Computes the union of the current GeneralizedStar with a set of GeneralizedStares.
Friends
template<class SettingRhs >
bool operator== (const GeneralizedStarT< Number, Converter, Setting > &b1, const GeneralizedStarT< Number, Converter, SettingRhs > &b2)
Checks if two GeneralizedStars are equal.
bool operator!= (const GeneralizedStarT< Number, Converter, Setting > &b1, const GeneralizedStarT< Number, Converter, Setting > &b2)
Determines inequality of two GeneralizedStares.
std::ostream & operator<< (std::ostream &ostr, const GeneralizedStarT< Number, Converter, Setting > &b)
Outstream operator.
Detailed Description
template<typename Number, typename Converter, class Setting>
class hypro::GeneralizedStarT< Number, Converter, Setting >
The class which represents a GeneralizedStar.
Template Parameters
Number The used number type.
Converter The used converter.
Settings The used settings. @{
Definition at line 22 of file GeneralizedStar.h.
Constructor & Destructor Documentation
template<typename Number, typename Converter, class Setting> hypro::GeneralizedStarT< Number, Converter, Setting >::GeneralizedStarT (const GeneralizedStarT< Number, Converter, Setting > & orig)
Copy constructor.
Parameters
[in] orig The original.
template<typename Number, typename Converter, class Setting> template<typename SettingRhs , carl::DisableIf< std::is_same< Setting, SettingRhs >> = carl::dummy> hypro::GeneralizedStarT< Number, Converter, Setting >::GeneralizedStarT (const GeneralizedStarT< Number, Converter, SettingRhs > & orig) inline
Settings conversion constructor.
Parameters
[in] orig The original.
Definition at line 57 of file GeneralizedStar.h.
References hypro::GeneralizedStarT< Number, Converter, Setting >::GeneralizedStarT().
template<typename Number, typename Converter, class Setting> hypro::GeneralizedStarT< Number, Converter, Setting >::GeneralizedStarT (GeneralizedStarT< Number, Converter, Setting > && orig)
Move constructor.
Parameters
[in] orig The original.
Member Function Documentation
template<typename Number, typename Converter, class Setting> bool hypro::GeneralizedStarT< Number, Converter, Setting >::contains (const GeneralizedStarT< Number, Converter, Setting > & GeneralizedStar) const
Containment check for a GeneralizedStar.
Parameters
[in] GeneralizedStar The GeneralizedStar.
Returns
True, if the given GeneralizedStar is contained in the current GeneralizedStar, false otherwise.
template<typename Number, typename Converter, class Setting> std::size_t hypro::GeneralizedStarT< Number, Converter, Setting >::dimension () const
Getter for the space dimension.
Returns
The dimension of the space.
template<typename Number, typename Converter, class Setting> static GeneralizedStarT hypro::GeneralizedStarT< Number, Converter, Setting >::Empty () inline static
Static method for the construction of an empty GeneralizedStar of required dimension.
Parameters
dimension Required dimension.
Returns
Empty GeneralizedStar.
Definition at line 82 of file GeneralizedStar.h.
References hypro::GeneralizedStarT< Number, Converter, Setting >::empty(), hypro::GeneralizedStarT< Number, Converter, Setting >::evaluate(), hypro::GeneralizedStarT< Number, Converter, Setting >::GeneralizedStarT(), hypro::GeneralizedStarT< Number, Converter, Setting >::multiEvaluate(), hypro::GeneralizedStarT< Number, Converter, Setting >::supremum(), and hypro::GeneralizedStarT< Number, Converter, Setting >::vertices().
template<typename Number, typename Converter, class Setting> bool hypro::GeneralizedStarT< Number, Converter, Setting >::empty () const
Determines if the current GeneralizedStar is empty.
Returns
True, if GeneralizedStar is empty. False otherwise.
Referenced by hypro::GeneralizedStarT< Number, Converter, Setting >::Empty().
template<typename Number, typename Converter, class Setting> EvaluationResult<Number> hypro::GeneralizedStarT< Number, Converter, Setting >::evaluate (const vector_t< Number > & _direction, bool) const
Evaluation function (convex linear optimization).
Parameters
[in] _direction The direction/cost function.
Returns
Maximum towards _direction.
Referenced by hypro::GeneralizedStarT< Number, Converter, Setting >::Empty().
template<typename Number, typename Converter, class Setting> GeneralizedStarT hypro::GeneralizedStarT< Number, Converter, Setting >::intersect (const GeneralizedStarT< Number, Converter, Setting > & rhs) const
Computes the intersection of two GeneralizedStares.
Parameters
[in] rhs The right hand side GeneralizedStar.
Returns
The resulting GeneralizedStar.
template<typename Number, typename Converter, class Setting> std::vector<EvaluationResult<Number> > hypro::GeneralizedStarT< Number, Converter, Setting >::multiEvaluate (const matrix_t< Number > & _directions, bool useExact = true) const
Multi-evaluation function (convex linear optimization).
Parameters
[in] _directions The directions/cost functions.
Returns
A set of maxima towards the respective directions.
Referenced by hypro::GeneralizedStarT< Number, Converter, Setting >::Empty().
template<typename Number, typename Converter, class Setting> GeneralizedStarT<Number, Converter, Setting>& hypro::GeneralizedStarT< Number, Converter, Setting >::operator= (const GeneralizedStarT< Number, Converter, Setting > & rhs) default
Assignment operator.
Parameters
rhs A GeneralizedStar.
template<typename Number, typename Converter, class Setting> GeneralizedStarT<Number, Converter, Setting>& hypro::GeneralizedStarT< Number, Converter, Setting >::operator= (GeneralizedStarT< Number, Converter, Setting > && rhs) default
Move assignment operator.
Parameters
rhs A GeneralizedStar.
template<typename Number, typename Converter, class Setting> const GeneralizedStarT& hypro::GeneralizedStarT< Number, Converter, Setting >::reduceNumberRepresentation ()
Function to reduce the number representation (over-approximate).
Parameters
[in] limit The limit
template<typename Number, typename Converter, class Setting> std::size_t hypro::GeneralizedStarT< Number, Converter, Setting >::size () const
Storage size determination.
Returns
Size of the required memory.
template<typename Number, typename Converter, class Setting> Number hypro::GeneralizedStarT< Number, Converter, Setting >::supremum () const
Method returning the supremum point of the GeneralizedStar, i.e. the maximal point.
Returns
A point representing the supremum of the current GeneralizedStar.
Referenced by hypro::GeneralizedStarT< Number, Converter, Setting >::Empty().
template<typename Number, typename Converter, class Setting> GeneralizedStarT hypro::GeneralizedStarT< Number, Converter, Setting >::unite (const GeneralizedStarT< Number, Converter, Setting > & rhs) const
Computes the union of two GeneralizedStares.
Parameters
[in] rhs The right hand side GeneralizedStar.
Returns
The resulting GeneralizedStar.
template<typename Number, typename Converter, class Setting> static GeneralizedStarT hypro::GeneralizedStarT< Number, Converter, Setting >::unite (const std::vector< GeneralizedStarT< Number, Converter, Setting > > & GeneralizedStares) static
Computes the union of the current GeneralizedStar with a set of GeneralizedStares.
Parameters
[in] GeneralizedStares The GeneralizedStares.
Returns
The resulting GeneralizedStar.
template<typename Number, typename Converter, class Setting> std::vector<Point<Number> > hypro::GeneralizedStarT< Number, Converter, Setting >::vertices (const matrix_t< Number > & = matrix_t< Number >::Zero(0, 0)) const
Getter for a vertex-representation of the current GeneralizedStar.
Returns
A vector of points.
Referenced by hypro::GeneralizedStarT< Number, Converter, Setting >::Empty().
Friends And Related Function Documentation
template<typename Number, typename Converter, class Setting> bool operator!= (const GeneralizedStarT< Number, Converter, Setting > & b1, const GeneralizedStarT< Number, Converter, Setting > & b2) friend
Determines inequality of two GeneralizedStares.
Parameters
b1 A GeneralizedStar.
b2 A GeneralizedStar.
Returns
False, if both GeneralizedStares are equal.
Definition at line 135 of file GeneralizedStar.h.
template<typename Number, typename Converter, class Setting> std::ostream& operator<< (std::ostream & ostr, const GeneralizedStarT< Number, Converter, Setting > & b) friend
Outstream operator.
Parameters
ostr Outstream.
b A GeneralizedStar.
Definition at line 154 of file GeneralizedStar.h.
template<typename Number, typename Converter, class Setting> template<class SettingRhs > bool operator== (const GeneralizedStarT< Number, Converter, Setting > & b1, const GeneralizedStarT< Number, Converter, SettingRhs > & b2) friend
Checks if two GeneralizedStars are equal.
Parameters
b1 Contains the first GeneralizedStar.
b2 Contains the second GeneralizedStar.
Returns
True, if they are equal.
Definition at line 125 of file GeneralizedStar.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/GeneralizedStar/GeneralizedStar.h