HyPro: hypro::DifferenceBoundsT< Number, Converter, Setting > Class Template Reference
hypro::DifferenceBoundsT< Number, Converter, Setting > Class Template Reference
State set representations
Class wrapping the difference bounds content.
Classes
class DBMEntry
Public Types
enum BOUND_TYPE { SMALLER, SMALLER_EQ, INFTY }
typedef Setting Settings
typedef Number NumberType
Public Member Functions
DifferenceBoundsT ()
DifferenceBoundsT (const DifferenceBoundsT &orig)=default
DifferenceBoundsT (matrix_t< Number > matrix, vector_t< Number > vector)
matrix_t< Number > matrix () const
vector_t< Number > vector () const
matrix_t< DBMEntry > getDBM () const
void setDBM (matrix_t< DBMEntry > dbm)
Number getTimeHorizon () const
void setTimeHorizon (Number horizon)
carl::Interval< tNumber > getCoveredTimeInterval () const
std::size_t dimension () const
std::size_t size () const
bool empty () const
EvaluationResult< Number > evaluate (const vector_t< Number > &direction, bool useExact=true) const
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &directions, bool useExact=true) const
std::vector< Point< Number > > vertices (const matrix_t< Number > &=matrix_t< Number >::Zero(0, 0)) const
std::pair< CONTAINMENT, DifferenceBoundsT > satisfiesHalfspace (const Halfspace< Number > &rhs) const
std::pair< CONTAINMENT, DifferenceBoundsT > satisfiesHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const
DifferenceBoundsT project (const std::vector< std::size_t > &dimensions) const
DifferenceBoundsT assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const
DifferenceBoundsT linearTransformation (const matrix_t< Number > &A) const
DifferenceBoundsT affineTransformation (const matrix_t< Number > &A, const vector_t< Number > &b) const
DifferenceBoundsT minkowskiSum (const DifferenceBoundsT &_rhs) const
DifferenceBoundsT intersect (const DifferenceBoundsT &_rhs) const
DifferenceBoundsT intersectHalfspace (const Halfspace< Number > &hs) const
DifferenceBoundsT intersectHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const
bool contains (const Point< Number > &_point) const
DifferenceBoundsT unite (const DifferenceBoundsT &_rhs) const
void reduceRepresentation ()
const DifferenceBoundsT & removeRedundancy ()
DifferenceBoundsT elapse () const
DifferenceBoundsT rewind () const
DifferenceBoundsT free (int x) const
DifferenceBoundsT reset (int x, Number value) const
DifferenceBoundsT copy (int src, int dest) const
DifferenceBoundsT shift (int x, Number offset) const
DifferenceBoundsT shift (Number offset) const
bool contains (const DifferenceBoundsT &_rhs) const
DifferenceBoundsT intersectConstraint (const int x, const int y, const DBMEntry &bound) const
std::pair< CONTAINMENT, DifferenceBoundsT > intersectConstraints (const matrix_t< Number > constraints, const vector_t< Number > constants, const CONTAINMENT defaultOnEmptyConstraints) const
DifferenceBoundsT extraM (const vector_t< DBMEntry > &MBounds) const
DifferenceBoundsT extraMPlus (const vector_t< DBMEntry > &MBounds) const
DifferenceBoundsT extraLU (const vector_t< DBMEntry > &LBounds, const vector_t< DBMEntry > &UBounds) const
DifferenceBoundsT extraLUPlus (const vector_t< DBMEntry > &LBounds, const vector_t< DBMEntry > &UBounds) const
Static Public Member Functions
static representation_name type ()
Friends
std::ostream & operator<< (std::ostream &ostr, const DifferenceBoundsT< Number, Converter, Setting > &db)
std::ostream & operator<< (std::ostream &ostr, const BOUND_TYPE value)
bool operator== (const DifferenceBoundsT< Number, Converter, Setting > &lhs, const DifferenceBoundsT< Number, Converter, Setting > &rhs)
Detailed Description
template<typename Number, typename Converter, class Setting>
class hypro::DifferenceBoundsT< Number, Converter, Setting >
Class wrapping the difference bounds content.
Template Parameters
Number The used number type.
Converter The used converter.
@{
Definition at line 21 of file DifferenceBounds.h.
Member Typedef Documentation
template<typename Number, typename Converter, class Setting> typedef Number hypro::DifferenceBoundsT< Number, Converter, Setting >::NumberType
Definition at line 30 of file DifferenceBounds.h.
template<typename Number, typename Converter, class Setting> typedef Setting hypro::DifferenceBoundsT< Number, Converter, Setting >::Settings
Definition at line 29 of file DifferenceBounds.h.
Member Enumeration Documentation
template<typename Number, typename Converter, class Setting> enum hypro::DifferenceBoundsT::BOUND_TYPE
Enumerator
SMALLER
SMALLER_EQ
INFTY
Definition at line 23 of file DifferenceBounds.h.
Constructor & Destructor Documentation
template<typename Number , typename Converter , class Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::DifferenceBoundsT ()
Definition at line 6 of file DifferenceBounds.tpp.
template<typename Number, typename Converter, class Setting> hypro::DifferenceBoundsT< Number, Converter, Setting >::DifferenceBoundsT (const DifferenceBoundsT< Number, Converter, Setting > & orig) default
template<typename Number , typename Converter , class Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::DifferenceBoundsT (matrix_t< Number > matrix, vector_t< Number > vector)
Definition at line 13 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::getDBM(), and hypro::Converter< Number >::toDifferenceBounds().
Member Function Documentation
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::affineTransformation (const matrix_t< Number > & A, const vector_t< Number > & b) const
Definition at line 210 of file DifferenceBounds.tpp.
References hypro::Converter< Number >::toDifferenceBounds(), and hypro::Converter< Number >::toHPolytope().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::assignIntervals().
template<typename Number, typename Converter, class Setting> DifferenceBoundsT hypro::DifferenceBoundsT< Number, Converter, Setting >::assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const inline
Definition at line 170 of file DifferenceBounds.h.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::affineTransformation(), hypro::DifferenceBoundsT< Number, Converter, Setting >::contains(), hypro::DifferenceBoundsT< Number, Converter, Setting >::intersect(), hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectHalfspace(), hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectHalfspaces(), hypro::DifferenceBoundsT< Number, Converter, Setting >::linearTransformation(), hypro::DifferenceBoundsT< Number, Converter, Setting >::minkowskiSum(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::unite().
template<typename Number , typename Converter , class Setting > bool hypro::DifferenceBoundsT< Number, Converter, Setting >::contains (const Point< Number > & _point) const
Definition at line 249 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::DBMEntry(), hypro::Point< Number >::rawCoordinates(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::assignIntervals(), hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::shift().
template<typename Number, typename Converter, class Setting> bool hypro::DifferenceBoundsT< Number, Converter, Setting >::contains (const DifferenceBoundsT< Number, Converter, Setting > & _rhs) const
checks whether _rhs is contained in the left hand side
A DBM X contains a DBM Y if the lower bounds of Y are greater or equal than the lower bounds of X and the upper bounds of Y are smaller or equal than the upper bounds of X.
This is the case if for every entry i,j in Y d_ij is lower or equal than the corresponding d_ij in X
Parameters
_rhs
Returns
true is lhs contains rhs
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::copy (int src, int dest) const
Copies a the value of clock src to clock dest, i.e. resets the value of dest to the value of src.
Parameters
src index of src clock
dest index of dest clock
Returns
DBM with clock dest set to clock src
Definition at line 356 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::DBMEntry(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , class Setting > std::size_t hypro::DifferenceBoundsT< Number, Converter, Setting >::dimension () const
Definition at line 65 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::getDBM().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::vector().
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::elapse () const
Elapses time for all clocks, i.e. d_i0 (that is x_i-0<=d_i0) is set to infinity
Returns
a DBM where the smaller(_eq) constraints for each clock is moved to infinity.
Definition at line 294 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::DBMEntry(), hypro::INFTY, and hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , class Setting > bool hypro::DifferenceBoundsT< Number, Converter, Setting >::empty () const
Definition at line 77 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::DBMEntry().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , class Setting > EvaluationResult< Number > hypro::DifferenceBoundsT< Number, Converter, Setting >::evaluate (const vector_t< Number > & direction, bool useExact = true) const
Definition at line 121 of file DifferenceBounds.tpp.
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::extraLU (const vector_t< DBMEntry > & LBounds, const vector_t< DBMEntry > & UBounds) const
extrapolates the current DBM by using the ExtraLU Method. A description can be found in: Behrman, Bouyer "Lower and Upper Bounds in Zone Based Abstractions of Timed Automata"
Lower and upper bounds are defined as follows: The maximal lower bound denoted L(x) (resp. maximal upper bound U(x)) of clock x is the maximal constant k such that there exists a constraint x>k or x>=k (resp x<k or x<=k) in a guard of some transition or in an invariant of some location of the automaton. If such a constant does not exist we set L(x) (resp. U(x)) to -INFTY. (Here: DBMEntry with BOUNDTYPE::INFTY)
Parameters
LBounds List of DBMEntries describing the maximal lower Bound for each variable i.e. the largest constant the variable is compared against. Note that the BOUND_TYPE has no effect unless it is infinity which denotes that the variable is not compared against any constant (i.e. is interpreted as -INFTY) The Bound for the 0 clock is 0.
UBounds List of DBMEntries describing the maximal upper Bound for each variable i.e. the largest constant the variable is compared against. Note that the BOUND_TYPE has no effect unless it is infinity which denotes that the variable is not compared against any constant (i.e. is interpreted as -INFTY) The Bound for the 0 clock is 0.
Returns
The extrapolated DBM
Definition at line 598 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::DBMEntry(), hypro::INFTY, and hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::extraLUPlus (const vector_t< DBMEntry > & LBounds, const vector_t< DBMEntry > & UBounds) const
extrapolates the current DBM by using the ExtraLU+ Method. A description can be found in: Behrman, Bouyer "Lower and Upper Bounds in Zone Based Abstractions of Timed Automata"
see extraLU(LBounds,UBounds) for a definition of lower and upper bounds in this context.
Parameters
LBounds List of DBMEntries describing the maximal lower Bound for each variable i.e. the largest constant the variable is compared against. Note that the BOUND_TYPE has no effect unless it is infinity which denotes that the variable is not compared against any constant (i.e. is interpreted as -INFTY) The Bound for the 0 clock is 0.
UBounds List of DBMEntries describing the maximal upper Bound for each variable i.e. the largest constant the variable is compared against. Note that the BOUND_TYPE has no effect unless it is infinity which denotes that the variable is not compared against any constant (i.e. is interpreted as -INFTY) The Bound for the 0 clock is 0.
Returns
The extrapolated DBM
Definition at line 626 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::DBMEntry(), hypro::INFTY, and hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::extraM (const vector_t< DBMEntry > & MBounds) const
extrapolates the current DBM by using the ExtraM Method. A description can be found in: Behrman, Bouyer "Lower and Upper Bounds in Zone Based Abstractions of Timed Automata"
Parameters
MBounds List of DBMEntries describing the maximal Bounds for each variable i.e. the largest constant the variable is compared against. Note that the BOUND_TYPE has no effect unless it is infinity which denotes that the variable is not compared against any constant (i.e. is interpreted as -INFTY). The Bound for the 0 clock is 0.
Returns
The extrapolated DBM
Definition at line 534 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::DBMEntry(), hypro::INFTY, and hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::extraMPlus (const vector_t< DBMEntry > & MBounds) const
extrapolates the current DBM by using the ExtraM+ Method. A description can be found in: Behrman, Bouyer "Lower and Upper Bounds in Zone Based Abstractions of Timed Automata"
Parameters
MBounds List of DBMEntries describing the maximal Bounds for each variable i.e. the largest constant the variable is compared against. Note that the BOUND_TYPE has no effect unless it is infinity which denotes that the variable is not compared against any constant (i.e. is interpreted as -INFTY) The Bound for the 0 clock is 0.
Returns
The extrapolated DBM
Definition at line 562 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::DBMEntry(), hypro::INFTY, and hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::free (int x) const
Frees a clock x, i.e. removes all bounding constraints for that clock
Parameters
x index of the clock
Returns
DBM with clock x freed
Definition at line 322 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::DBMEntry(), hypro::INFTY, and hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , class Setting > carl::Interval< tNumber > hypro::DifferenceBoundsT< Number, Converter, Setting >::getCoveredTimeInterval () const
Definition at line 52 of file DifferenceBounds.tpp.
References hypro::Converter< Number >::toBox().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::vector().
template<typename Number , typename Converter , class Setting > matrix_t< typename DifferenceBoundsT< Number, Converter, Setting >::DBMEntry > hypro::DifferenceBoundsT< Number, Converter, Setting >::getDBM () const
Definition at line 33 of file DifferenceBounds.tpp.
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::DifferenceBoundsT(), hypro::DifferenceBoundsT< Number, Converter, Setting >::dimension(), hypro::DifferenceBoundsT< Number, Converter, Setting >::intersect(), hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectConstraints(), hypro::DifferenceBoundsT< Number, Converter, Setting >::shift(), hypro::DifferenceBoundsT< Number, Converter, Setting >::size(), hypro::DifferenceBoundsT< Number, Converter, Setting >::unite(), hypro::DifferenceBoundsT< Number, Converter, Setting >::vector(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::vertices().
template<typename Number , typename Converter , class Setting > Number hypro::DifferenceBoundsT< Number, Converter, Setting >::getTimeHorizon () const
Definition at line 42 of file DifferenceBounds.tpp.
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::vector(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::vertices().
template<typename Number, typename Converter, class Setting> DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::intersect (const DifferenceBoundsT< Number, Converter, Setting > & _rhs) const
Definition at line 223 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::getDBM(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectConstraint().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectConstraint (const int x, const int y, const DBMEntry & bound) const
intersects the DBM with the bound given by index x, y and bound value bound i.e. x-y <= bound
Parameters
x
y
bound
Returns
the intersection of the DBM with constraint x-y bound
Definition at line 456 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::DBMEntry(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::intersect(), hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectConstraints(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , class Setting > std::pair< CONTAINMENT, DifferenceBoundsT< Number, Converter, Setting > > hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectConstraints (const matrix_t< Number > constraints, const vector_t< Number > constants, const CONTAINMENT defaultOnEmptyConstraints) const
intersects the DBM with the bound given set of constraints i.e. x-y <= bound
Parameters
x
y
bound
Returns
the intersection of the DBM with constraint x-y bound
Definition at line 498 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::getDBM(), hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectConstraint(), hypro::NO, and hypro::PARTIAL.
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectHalfspace (const Halfspace< Number > & hs) const
Definition at line 237 of file DifferenceBounds.tpp.
References hypro::Converter< Number >::toDifferenceBounds(), and hypro::Converter< Number >::toHPolytope().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectHalfspaces (const matrix_t< Number > & _mat, const vector_t< Number > & _vec) const
Definition at line 243 of file DifferenceBounds.tpp.
References hypro::Converter< Number >::toDifferenceBounds(), and hypro::Converter< Number >::toHPolytope().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::linearTransformation (const matrix_t< Number > & A) const
Definition at line 204 of file DifferenceBounds.tpp.
References hypro::Converter< Number >::toDifferenceBounds(), and hypro::Converter< Number >::toHPolytope().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::assignIntervals().
template<typename Number, typename Converter, class Setting> matrix_t<Number> hypro::DifferenceBoundsT< Number, Converter, Setting >::matrix () const inline
Definition at line 140 of file DifferenceBounds.h.
template<typename Number, typename Converter, class Setting> DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::minkowskiSum (const DifferenceBoundsT< Number, Converter, Setting > & _rhs) const
Definition at line 216 of file DifferenceBounds.tpp.
References hypro::Converter< Number >::toDifferenceBounds(), and hypro::Converter< Number >::toHPolytope().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , class Setting > std::vector< EvaluationResult< Number > > hypro::DifferenceBoundsT< Number, Converter, Setting >::multiEvaluate (const matrix_t< Number > & directions, bool useExact = true) const
Definition at line 128 of file DifferenceBounds.tpp.
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::project (const std::vector< std::size_t > & dimensions) const
Definition at line 190 of file DifferenceBounds.tpp.
References hypro::Converter< Number >::toDifferenceBounds(), and hypro::Converter< Number >::toHPolytope().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> void hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation () inline
Definition at line 182 of file DifferenceBounds.h.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::contains(), hypro::DifferenceBoundsT< Number, Converter, Setting >::copy(), hypro::DifferenceBoundsT< Number, Converter, Setting >::elapse(), hypro::DifferenceBoundsT< Number, Converter, Setting >::extraLU(), hypro::DifferenceBoundsT< Number, Converter, Setting >::extraLUPlus(), hypro::DifferenceBoundsT< Number, Converter, Setting >::extraM(), hypro::DifferenceBoundsT< Number, Converter, Setting >::extraMPlus(), hypro::DifferenceBoundsT< Number, Converter, Setting >::free(), hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectConstraint(), hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectConstraints(), hypro::DifferenceBoundsT< Number, Converter, Setting >::removeRedundancy(), hypro::DifferenceBoundsT< Number, Converter, Setting >::reset(), hypro::DifferenceBoundsT< Number, Converter, Setting >::rewind(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::shift().
template<typename Number , typename Converter , class Setting > const DifferenceBoundsT< Number, Converter, Setting > & hypro::DifferenceBoundsT< Number, Converter, Setting >::removeRedundancy ()
Definition at line 664 of file DifferenceBounds.tpp.
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::reset (int x, Number value) const
Resets clock x to given Number value.
Parameters
x index of the clock
value reset value of the clock
Returns
DBM with clock x reset to value
Definition at line 339 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::DBMEntry(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::rewind () const
Computes the set of clock assignments that can reach the current DBMs Zone when time is elapsed. It is computed by setting all lower clock bound to 0.
I.e. d_0i (that is 0-x_i <= d_0i <=> x_i >= -d_01) is set to 0
Returns
a DBM where the greater_(eq) constraints for each clock is moved to 0.
Definition at line 305 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::DBMEntry(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , class Setting > std::pair< CONTAINMENT, DifferenceBoundsT< Number, Converter, Setting > > hypro::DifferenceBoundsT< Number, Converter, Setting >::satisfiesHalfspace (const Halfspace< Number > & rhs) const
Definition at line 176 of file DifferenceBounds.tpp.
References hypro::Converter< Number >::toDifferenceBounds(), and hypro::Converter< Number >::toHPolytope().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , class Setting > std::pair< CONTAINMENT, DifferenceBoundsT< Number, Converter, Setting > > hypro::DifferenceBoundsT< Number, Converter, Setting >::satisfiesHalfspaces (const matrix_t< Number > & _mat, const vector_t< Number > & _vec) const
Definition at line 183 of file DifferenceBounds.tpp.
References hypro::Converter< Number >::toDifferenceBounds(), and hypro::Converter< Number >::toHPolytope().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> void hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM (matrix_t< DBMEntry > dbm)
Definition at line 37 of file DifferenceBounds.tpp.
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::contains(), hypro::DifferenceBoundsT< Number, Converter, Setting >::copy(), hypro::DifferenceBoundsT< Number, Converter, Setting >::elapse(), hypro::DifferenceBoundsT< Number, Converter, Setting >::extraLU(), hypro::DifferenceBoundsT< Number, Converter, Setting >::extraLUPlus(), hypro::DifferenceBoundsT< Number, Converter, Setting >::extraM(), hypro::DifferenceBoundsT< Number, Converter, Setting >::extraMPlus(), hypro::DifferenceBoundsT< Number, Converter, Setting >::free(), hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectConstraint(), hypro::DifferenceBoundsT< Number, Converter, Setting >::reset(), hypro::DifferenceBoundsT< Number, Converter, Setting >::rewind(), hypro::DifferenceBoundsT< Number, Converter, Setting >::shift(), hypro::Converter< Number >::toDifferenceBounds(), hypro::DifferenceBoundsT< Number, Converter, Setting >::unite(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::vector().
template<typename Number , typename Converter , class Setting > void hypro::DifferenceBoundsT< Number, Converter, Setting >::setTimeHorizon (Number horizon)
Definition at line 47 of file DifferenceBounds.tpp.
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::vector().
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::shift (int x, Number offset) const
Shifts the valuation of clock x by the given offset
Parameters
x index of the clock
offset offset to be applied
Returns
DBM with clock x shifted by offset
Definition at line 377 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::DBMEntry(), hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::max(), hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::min(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , class Setting > DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::shift (Number offset) const
Shifts the valuation of all clocks by the given offset
Parameters
offset offset to be applied
Returns
DBM with clocks shifted by offset
Definition at line 400 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::contains(), hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::DBMEntry(), hypro::DifferenceBoundsT< Number, Converter, Setting >::getDBM(), hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::max(), hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::min(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM().
template<typename Number , typename Converter , class Setting > std::size_t hypro::DifferenceBoundsT< Number, Converter, Setting >::size () const
Definition at line 71 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::getDBM().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::vector().
template<typename Number, typename Converter, class Setting> static representation_name hypro::DifferenceBoundsT< Number, Converter, Setting >::type () inline static
Definition at line 160 of file DifferenceBounds.h.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::empty(), hypro::DifferenceBoundsT< Number, Converter, Setting >::evaluate(), hypro::DifferenceBoundsT< Number, Converter, Setting >::multiEvaluate(), hypro::DifferenceBoundsT< Number, Converter, Setting >::project(), hypro::DifferenceBoundsT< Number, Converter, Setting >::satisfiesHalfspace(), hypro::DifferenceBoundsT< Number, Converter, Setting >::satisfiesHalfspaces(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::vertices().
template<typename Number, typename Converter, class Setting> DifferenceBoundsT< Number, Converter, Setting > hypro::DifferenceBoundsT< Number, Converter, Setting >::unite (const DifferenceBoundsT< Number, Converter, Setting > & _rhs) const
Definition at line 276 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::getDBM(), hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::max(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::assignIntervals().
template<typename Number, typename Converter, class Setting> vector_t<Number> hypro::DifferenceBoundsT< Number, Converter, Setting >::vector () const inline
Definition at line 145 of file DifferenceBounds.h.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::dimension(), hypro::DifferenceBoundsT< Number, Converter, Setting >::getCoveredTimeInterval(), hypro::DifferenceBoundsT< Number, Converter, Setting >::getDBM(), hypro::DifferenceBoundsT< Number, Converter, Setting >::getTimeHorizon(), hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM(), hypro::DifferenceBoundsT< Number, Converter, Setting >::setTimeHorizon(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::size().
template<typename Number , typename Converter , class Setting > std::vector< Point< Number > > hypro::DifferenceBoundsT< Number, Converter, Setting >::vertices (const matrix_t< Number > & = matrix_t<Number>::Zero(0, 0)) const
Definition at line 134 of file DifferenceBounds.tpp.
References hypro::DifferenceBoundsT< Number, Converter, Setting >::getDBM(), hypro::DifferenceBoundsT< Number, Converter, Setting >::getTimeHorizon(), and hypro::Converter< Number >::toHPolytope().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::type().
Friends And Related Function Documentation
template<typename Number, typename Converter, class Setting> std::ostream& operator<< (std::ostream & ostr, const DifferenceBoundsT< Number, Converter, Setting > & db) friend
Definition at line 316 of file DifferenceBounds.h.
template<typename Number, typename Converter, class Setting> std::ostream& operator<< (std::ostream & ostr, const BOUND_TYPE value) friend
Definition at line 330 of file DifferenceBounds.h.
template<typename Number, typename Converter, class Setting> bool operator== (const DifferenceBoundsT< Number, Converter, Setting > & lhs, const DifferenceBoundsT< Number, Converter, Setting > & rhs) friend
Definition at line 348 of file DifferenceBounds.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/DifferenceBounds/DifferenceBounds.h
/home/travis/build/hypro/hypro/src/hypro/representations/DifferenceBounds/DifferenceBounds.tpp