HyPro: hypro::Vertex< Number > Class Template Reference
hypro::Vertex< Number > Class Template Reference
Forward declaration of class Vertex.
#include <Vertex.h>
Public Member Functions
Vertex (bool color=false)
Vertex (const Point< Number > &p, bool color=false)
Vertex (const vector_t< Number > &p, bool color=false)
Vertex (const Vertex< Number > &v)
Vertex (const Vertex< Number > &&v)
~Vertex ()
Destroy the Vertex object.
bool color () const
void setColor (bool c=true)
Point< Number > point () const
Point< Number > & rPoint ()
void setPoint (const Point< Number > &p)
void invertColor ()
void swap (Vertex< Number > &_rhs)
Number coordinate (const carl::Variable &_var) const
Number coordinate (std::size_t _dim) const
vector_t< Number > rawCoordinates () const
std::size_t dimension () const
std::vector< carl::Variable > variables () const
bool hasDimension (const carl::Variable &_i) const
bool hasDimensions (const std::vector< carl::Variable > &_variables) const
Vertex< Number > & operator= (const Vertex< Number > &_rhs)
Copy assignment operator.
Vertex< Number > & operator= (Vertex< Number > &&_rhs)
Number & operator[] (const carl::Variable &_i)
Number & operator[] (std::size_t pos)
Number at (const carl::Variable &_i) const
Number at (unsigned _i) const
Private Attributes
Point< Number > mPoint
bool mColor = false
Friends
bool operator== (const Vertex< Number > &_v1, const Vertex< Number > &_v2)
bool operator!= (const Vertex< Number > &_v1, const Vertex< Number > &_v2)
bool operator< (const Vertex< Number > &_v1, const Vertex< Number > &_v2)
bool operator> (const Vertex< Number > &_v1, const Vertex< Number > &_v2)
std::ostream & operator<< (std::ostream &ostr, const Vertex &v)
Detailed Description
template<class Number>
class hypro::Vertex< Number >
Forward declaration of class Vertex.
Template Parameters
Number
Definition at line 22 of file Vertex.h.
Constructor & Destructor Documentation
template<class Number> hypro::Vertex< Number >::Vertex (bool color = false) inline explicit
Parameters
dimension
color
Definition at line 48 of file Vertex.h.
template<class Number> hypro::Vertex< Number >::Vertex (const Point< Number > & p, bool color = false) inline
Parameters
p
color
Definition at line 57 of file Vertex.h.
template<class Number> hypro::Vertex< Number >::Vertex (const vector_t< Number > & p, bool color = false) inline
Definition at line 60 of file Vertex.h.
template<class Number> hypro::Vertex< Number >::Vertex (const Vertex< Number > & v) inline
Parameters
v
Definition at line 68 of file Vertex.h.
template<class Number> hypro::Vertex< Number >::Vertex (const Vertex< Number > && v) inline
Definition at line 72 of file Vertex.h.
template<class Number> hypro::Vertex< Number >::~Vertex () inline
Destroy the Vertex object.
Definition at line 79 of file Vertex.h.
Member Function Documentation
template<class Number> Number hypro::Vertex< Number >::at (const carl::Variable & _i) const inline
Definition at line 243 of file Vertex.h.
template<class Number> Number hypro::Vertex< Number >::at (unsigned _i) const inline
Definition at line 245 of file Vertex.h.
template<class Number> bool hypro::Vertex< Number >::color () const inline
Returns
the color of the vertex.
Definition at line 85 of file Vertex.h.
Referenced by hypro::VertexContainer< Number >::find(), and std::hash< hypro::Vertex< Number > >::operator()().
template<class Number> Number hypro::Vertex< Number >::coordinate (const carl::Variable & _var) const inline
See also
Point::coordinate
Definition at line 128 of file Vertex.h.
template<class Number> Number hypro::Vertex< Number >::coordinate (std::size_t _dim) const inline
Definition at line 130 of file Vertex.h.
template<class Number> std::size_t hypro::Vertex< Number >::dimension () const inline
See also
Point::dimension
Definition at line 137 of file Vertex.h.
template<class Number> bool hypro::Vertex< Number >::hasDimension (const carl::Variable & _i) const inline
See also
Point::hasDimension
Definition at line 147 of file Vertex.h.
template<class Number> bool hypro::Vertex< Number >::hasDimensions (const std::vector< carl::Variable > & _variables) const inline
See also
Point::hasDimensions
Definition at line 152 of file Vertex.h.
template<class Number> void hypro::Vertex< Number >::invertColor () inline
Inverts the color.
Definition at line 114 of file Vertex.h.
template<class Number> Vertex<Number>& hypro::Vertex< Number >::operator= (const Vertex< Number > & _rhs) inline
Copy assignment operator.
Parameters
_rhs righthand side
Definition at line 165 of file Vertex.h.
template<class Number> Vertex<Number>& hypro::Vertex< Number >::operator= (Vertex< Number > && _rhs) inline
Definition at line 172 of file Vertex.h.
template<class Number> Number& hypro::Vertex< Number >::operator[] (const carl::Variable & _i) inline
Parameters
i
Returns
Definition at line 240 of file Vertex.h.
template<class Number> Number& hypro::Vertex< Number >::operator[] (std::size_t pos) inline
Definition at line 241 of file Vertex.h.
template<class Number> Point<Number> hypro::Vertex< Number >::point () const inline
Returns
the point of the vertex
Definition at line 97 of file Vertex.h.
Referenced by std::hash< hypro::Vertex< Number > >::operator()().
template<class Number> vector_t<Number> hypro::Vertex< Number >::rawCoordinates () const inline
Definition at line 132 of file Vertex.h.
template<class Number> Point<Number>& hypro::Vertex< Number >::rPoint () inline
Returns
the point of the vertex
Definition at line 103 of file Vertex.h.
Referenced by hypro::VertexContainer< Number >::linearTransformation(), and hypro::VertexContainer< Number >::move().
template<class Number> void hypro::Vertex< Number >::setColor (bool c = true) inline
Parameters
c the new value for this vertex' color.
Definition at line 91 of file Vertex.h.
template<class Number> void hypro::Vertex< Number >::setPoint (const Point< Number > & p) inline
Parameters
p the new value for this vertex' point
Definition at line 109 of file Vertex.h.
template<class Number> void hypro::Vertex< Number >::swap (Vertex< Number > & _rhs) inline
Definition at line 116 of file Vertex.h.
Referenced by hypro::Vertex< std::size_t >::operator=().
template<class Number> std::vector<carl::Variable> hypro::Vertex< Number >::variables () const inline
See also
Point::variables
Definition at line 142 of file Vertex.h.
Friends And Related Function Documentation
template<class Number> bool operator!= (const Vertex< Number > & _v1, const Vertex< Number > & _v2) friend
Parameters
v1
v2
Returns
true, if they are not equal.
Definition at line 200 of file Vertex.h.
template<class Number> bool operator< (const Vertex< Number > & _v1, const Vertex< Number > & _v2) friend
Comparison operator for the map. Compares the points of both vertices. If both are equal, the color is compared while true is greater than false
Parameters
v1
v2
Returns
Definition at line 211 of file Vertex.h.
template<class Number> std::ostream& operator<< (std::ostream & ostr, const Vertex< Number > & v) friend
Definition at line 247 of file Vertex.h.
template<class Number> bool operator== (const Vertex< Number > & _v1, const Vertex< Number > & _v2) friend
Parameters
v1
v2
Returns
true, if they are equal.
Definition at line 184 of file Vertex.h.
template<class Number> bool operator> (const Vertex< Number > & _v1, const Vertex< Number > & _v2) friend
Comparison operator for the map. Compares the points of both vertices. If both are equal, the color is compared while true is greater than false return mPoint
Parameters
v1
v2
Returns
Definition at line 233 of file Vertex.h.
Member Data Documentation
template<class Number> bool hypro::Vertex< Number >::mColor = false private
Definition at line 40 of file Vertex.h.
Referenced by hypro::Vertex< std::size_t >::color(), hypro::Vertex< std::size_t >::invertColor(), and hypro::Vertex< std::size_t >::swap().
template<class Number> Point<Number> hypro::Vertex< Number >::mPoint private
Definition at line 39 of file Vertex.h.
Referenced by hypro::Vertex< std::size_t >::point(), hypro::Vertex< std::size_t >::rPoint(), and hypro::Vertex< std::size_t >::swap().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/Vertex.h