HyPro: hypro::HyproLocationVisitor< Number > Class Template Reference
hypro::HyproLocationVisitor< Number > Class Template Reference
Public Member Functions
HyproLocationVisitor (std::vector< std::string > &varVec)
~HyproLocationVisitor ()
antlrcpp::Any visitModes (HybridAutomatonParser::ModesContext *ctx) override
Public Member Functions inherited from hypro::HybridAutomatonBaseVisitor
virtual antlrcpp::Any visitStart (HybridAutomatonParser::StartContext *ctx) override
virtual antlrcpp::Any visitVardeclaration (HybridAutomatonParser::VardeclarationContext *ctx) override
virtual antlrcpp::Any visitConstantdeclaration (HybridAutomatonParser::ConstantdeclarationContext *ctx) override
virtual antlrcpp::Any visitReplacedexpr (HybridAutomatonParser::ReplacedexprContext *ctx) override
virtual antlrcpp::Any visitConstantexpr (HybridAutomatonParser::ConstantexprContext *ctx) override
virtual antlrcpp::Any visitConnector (HybridAutomatonParser::ConnectorContext *ctx) override
virtual antlrcpp::Any visitTerm (HybridAutomatonParser::TermContext *ctx) override
virtual antlrcpp::Any visitPolynom (HybridAutomatonParser::PolynomContext *ctx) override
virtual antlrcpp::Any visitExpression (HybridAutomatonParser::ExpressionContext *ctx) override
virtual antlrcpp::Any visitEquation (HybridAutomatonParser::EquationContext *ctx) override
virtual antlrcpp::Any visitConstraint (HybridAutomatonParser::ConstraintContext *ctx) override
virtual antlrcpp::Any visitInterval (HybridAutomatonParser::IntervalContext *ctx) override
virtual antlrcpp::Any visitIntervalexpr (HybridAutomatonParser::IntervalexprContext *ctx) override
virtual antlrcpp::Any visitConstrset (HybridAutomatonParser::ConstrsetContext *ctx) override
virtual antlrcpp::Any visitInit (HybridAutomatonParser::InitContext *ctx) override
virtual antlrcpp::Any visitInitstate (HybridAutomatonParser::InitstateContext *ctx) override
virtual antlrcpp::Any visitUnsafeset (HybridAutomatonParser::UnsafesetContext *ctx) override
virtual antlrcpp::Any visitLbadstate (HybridAutomatonParser::LbadstateContext *ctx) override
virtual antlrcpp::Any visitGbadstate (HybridAutomatonParser::GbadstateContext *ctx) override
virtual antlrcpp::Any visitJumps (HybridAutomatonParser::JumpsContext *ctx) override
virtual antlrcpp::Any visitTransition (HybridAutomatonParser::TransitionContext *ctx) override
virtual antlrcpp::Any visitFromto (HybridAutomatonParser::FromtoContext *ctx) override
virtual antlrcpp::Any visitUrgent (HybridAutomatonParser::UrgentContext *ctx) override
virtual antlrcpp::Any visitGuard (HybridAutomatonParser::GuardContext *ctx) override
virtual antlrcpp::Any visitLabels (HybridAutomatonParser::LabelsContext *ctx) override
virtual antlrcpp::Any visitAllocation (HybridAutomatonParser::AllocationContext *ctx) override
virtual antlrcpp::Any visitResetfct (HybridAutomatonParser::ResetfctContext *ctx) override
virtual antlrcpp::Any visitAggregation (HybridAutomatonParser::AggregationContext *ctx) override
virtual antlrcpp::Any visitSetting (HybridAutomatonParser::SettingContext *ctx) override
virtual antlrcpp::Any visitFixedsteps (HybridAutomatonParser::FixedstepsContext *ctx) override
virtual antlrcpp::Any visitTime (HybridAutomatonParser::TimeContext *ctx) override
virtual antlrcpp::Any visitPlotsetting (HybridAutomatonParser::PlotsettingContext *ctx) override
virtual antlrcpp::Any visitFilename (HybridAutomatonParser::FilenameContext *ctx) override
virtual antlrcpp::Any visitMaxjumps (HybridAutomatonParser::MaxjumpsContext *ctx) override
virtual antlrcpp::Any visitPrint (HybridAutomatonParser::PrintContext *ctx) override
virtual antlrcpp::Any visitRemainder (HybridAutomatonParser::RemainderContext *ctx) override
virtual antlrcpp::Any visitIdentity (HybridAutomatonParser::IdentityContext *ctx) override
virtual antlrcpp::Any visitQrprecond (HybridAutomatonParser::QrprecondContext *ctx) override
virtual antlrcpp::Any visitFixedorders (HybridAutomatonParser::FixedordersContext *ctx) override
virtual antlrcpp::Any visitAdaptiveorders (HybridAutomatonParser::AdaptiveordersContext *ctx) override
virtual antlrcpp::Any visitCutoff (HybridAutomatonParser::CutoffContext *ctx) override
virtual antlrcpp::Any visitPrecision (HybridAutomatonParser::PrecisionContext *ctx) override
Friends
class HyproHAVisitor< Number >
Detailed Description
template<typename Number>
class hypro::HyproLocationVisitor< Number >
Definition at line 27 of file HyproFormulaVisitor.h.
Constructor & Destructor Documentation
template<typename Number > hypro::HyproLocationVisitor< Number >::HyproLocationVisitor (std::vector< std::string > & varVec)
Definition at line 8 of file HyproLocationVisitor.tpp.
template<typename Number > hypro::HyproLocationVisitor< Number >::~HyproLocationVisitor ()
Definition at line 13 of file HyproLocationVisitor.tpp.
Member Function Documentation
template<typename Number > antlrcpp::Any hypro::HyproLocationVisitor< Number >::visitModes (HybridAutomatonParser::ModesContext * ctx) override virtual
Reimplemented from hypro::HybridAutomatonBaseVisitor.
Definition at line 18 of file HyproLocationVisitor.tpp.
References hypro::HybridAutomatonParser::LocationContext::activities(), hypro::HybridAutomatonParser::InvariantsContext::constrset(), hypro::HybridAutomatonParser::ActivitiesContext::equation(), hypro::HybridAutomatonParser::ActivitiesContext::intervalexpr(), hypro::HybridAutomatonParser::LocationContext::invariants(), hypro::HybridAutomatonParser::ModesContext::location(), hypro::rectangularFlow< Number >::setFlowIntervals(), hypro::linearFlow< Number >::setFlowMatrix(), hypro::Location< Number >::setName(), and hypro::HybridAutomatonParser::LocationContext::VARIABLE().
Friends And Related Function Documentation
template<typename Number> friend class HyproHAVisitor< Number > friend
Definition at line 31 of file HyproLocationVisitor.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HyproFormulaVisitor.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HyproLocationVisitor.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HyproLocationVisitor.tpp