HyPro: hypro::NeighborhoodContainer Class Reference
hypro::NeighborhoodContainer Class Reference
A neighborhood container which maps points to their set of neighbor points.
#include <NeighborhoodContainer.h>
Public Types
using neighborhood = std::vector< Point< int > >
Public Member Functions
NeighborhoodContainer ()
NeighborhoodContainer (const NeighborhoodContainer &copy)
NeighborhoodContainer & operator= (const NeighborhoodContainer &orig)=default
NeighborhoodContainer & operator= (NeighborhoodContainer &&orig)=default
~NeighborhoodContainer ()
void clear ()
bool empty () const
neighborhood getNeighborhood (const Point< int > &p, bool pointself=false)
neighborhood getNeighborhoodForDimension (const Point< int > &p, const carl::Variable &dimension, bool pointself=false)
Private Member Functions
bool hasNeighborhood (const Point< int > &p) const
void calculateNeighborhood (const Point< int > &p)
Private Attributes
std::map< Point< int >, neighborhood > mNeighborhoods
Detailed Description
A neighborhood container which maps points to their set of neighbor points.
Definition at line 18 of file NeighborhoodContainer.h.
Member Typedef Documentation
using hypro::NeighborhoodContainer::neighborhood = std::vector<Point<int> >
Definition at line 20 of file NeighborhoodContainer.h.
Constructor & Destructor Documentation
hypro::NeighborhoodContainer::NeighborhoodContainer () inline
Definition at line 26 of file NeighborhoodContainer.h.
hypro::NeighborhoodContainer::NeighborhoodContainer (const NeighborhoodContainer & copy) inline
Definition at line 28 of file NeighborhoodContainer.h.
References mNeighborhoods, and operator=().
hypro::NeighborhoodContainer::~NeighborhoodContainer () inline
Definition at line 35 of file NeighborhoodContainer.h.
Member Function Documentation
void hypro::NeighborhoodContainer::calculateNeighborhood (const Point< int > & p) private
Definition at line 51 of file NeighborhoodContainer.cpp.
References assert(), d, dim, hypro::Point< Number >::dimension(), i, mNeighborhoods, and hypro::Point< Number >::rawCoordinates().
Referenced by getNeighborhood(), getNeighborhoodForDimension(), and hasNeighborhood().
void hypro::NeighborhoodContainer::clear () inline
Definition at line 37 of file NeighborhoodContainer.h.
bool hypro::NeighborhoodContainer::empty () const inline
Definition at line 39 of file NeighborhoodContainer.h.
References dimension(), getNeighborhood(), and getNeighborhoodForDimension().
NeighborhoodContainer::neighborhood hypro::NeighborhoodContainer::getNeighborhood (const Point< int > & p, bool pointself = false)
Returns the points in the neighborhood.
Parameters
p the point
pointself point is optionally an element of the returned vector
Returns
Vector filled with neighbors in all dimensions
Definition at line 13 of file NeighborhoodContainer.cpp.
References calculateNeighborhood(), hasNeighborhood(), and mNeighborhoods.
Referenced by empty().
NeighborhoodContainer::neighborhood hypro::NeighborhoodContainer::getNeighborhoodForDimension (const Point< int > & p, const carl::Variable & dimension, bool pointself = false)
Returns the points in the neighborhood, with one fixed dimension.
Parameters
p the point
dimension the fixed dimension
pointself point is optionally an element of the returned vector
Returns
Definition at line 27 of file NeighborhoodContainer.cpp.
References calculateNeighborhood(), hypro::Point< Number >::coordinate(), hasNeighborhood(), and mNeighborhoods.
Referenced by empty().
bool hypro::NeighborhoodContainer::hasNeighborhood (const Point< int > & p) const inline private
Moves all neighbors.
Parameters
p the point by which the neighbors should be moved
Definition at line 69 of file NeighborhoodContainer.h.
References calculateNeighborhood().
Referenced by getNeighborhood(), and getNeighborhoodForDimension().
NeighborhoodContainer& hypro::NeighborhoodContainer::operator= (const NeighborhoodContainer & orig) default
Referenced by NeighborhoodContainer().
NeighborhoodContainer& hypro::NeighborhoodContainer::operator= (NeighborhoodContainer && orig) default
Member Data Documentation
std::map<Point<int>, neighborhood> hypro::NeighborhoodContainer::mNeighborhoods private
Definition at line 23 of file NeighborhoodContainer.h.
Referenced by calculateNeighborhood(), getNeighborhood(), getNeighborhoodForDimension(), and NeighborhoodContainer().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/OrthogonalPolyhedron/NeighborhoodContainer.h
/home/travis/build/hypro/hypro/src/hypro/representations/OrthogonalPolyhedron/NeighborhoodContainer.cpp