HyPro: hypro::Location< Number > Class Template Reference
hypro::Location< Number > Class Template Reference
Class for location.
Public Types
using transitionVector = std::vector< std::unique_ptr< Transition< Number >>>
Public Member Functions
Location ()
Location (const std::string &name)
Location (const Location &loc)
Location (const matrix_t< Number > &mat)
Location (const matrix_t< Number > &mat, transitionVector &&trans, const Condition< Number > &inv)
~Location ()
Location< Number > & operator= (const Location< Number > &in)
std::size_t getNumberFlow () const
linearFlow< Number > getLinearFlow (std::size_t I=0) const
linearFlow< Number > & rGetLinearFlow (std::size_t I=0)
rectangularFlow< Number > getRectangularFlow (std::size_t I=0) const
rectangularFlow< Number > & rGetRectangularFlow (std::size_t I=0)
const std::vector< linearFlow< Number > > & getLinearFlows () const
const std::vector< rectangularFlow< Number > > & getRectangularFlows () const
const Condition< Number > & getInvariant () const
const transitionVector & getTransitions () const
transitionVector & rGetTransitions ()
const std::vector< carl::Interval< Number > > & getExternalInput () const
bool hasExternalInput () const
unsigned getId () const
std::string getName () const
std::size_t dimension () const
std::size_t dimension (std::size_t i) const
void setName (const std::string &name)
void setFlow (const matrix_t< Number > &f, std::size_t I=0)
void setFlow (const linearFlow< Number > &f, std::size_t I=0)
void setFlow (const rectangularFlow< Number > &f, std::size_t I=0)
void setLinearFlow (const linearFlow< Number > &f, std::size_t I=0)
void setRectangularFlow (const rectangularFlow< Number > &f, std::size_t I=0)
void setLinearFlow (const std::vector< linearFlow< Number >> &flows)
void setRectangularFlow (const std::vector< rectangularFlow< Number >> &flows)
void setInvariant (const Condition< Number > &inv)
void setTransitions (transitionVector &&trans)
void addTransition (std::unique_ptr< Transition< Number >> &&trans)
void setExtInput (const std::vector< carl::Interval< Number >> &b)
std::size_t hash () const
bool isComposedOf (const Location< Number > &rhs, const std::vector< std::string > &rhsVars, const std::vector< std::string > &thisVars) const
Determines if this composed of rhs and some potential rest.
std::string getDotRepresentation (const std::vector< std::string > &vars) const
void decompose (const Decomposition &decomposition)
bool operator< (const Location< Number > &rhs) const
bool operator== (const Location< Number > &rhs) const
bool operator!= (const Location< Number > &rhs) const
Friends
std::ostream & operator<< (std::ostream &ostr, const Location< Number > &l)
Detailed Description
template<typename Number>
class hypro::Location< Number >
Class for location.
Forward declaration of class Location *.
Template Parameters
Number The used number type.
Number
Definition at line 33 of file Location.h.
Member Typedef Documentation
template<typename Number> using hypro::Location< Number >::transitionVector = std::vector<std::unique_ptr<Transition<Number>>>
Definition at line 35 of file Location.h.
Constructor & Destructor Documentation
template<typename Number > hypro::Location< Number >::Location ()
Definition at line 6 of file Location.tpp.
Referenced by hypro::Location< Number >::Location().
template<typename Number > hypro::Location< Number >::Location (const std::string & name)
Definition at line 16 of file Location.tpp.
References hypro::Location< Number >::getExternalInput(), hypro::Location< Number >::getInvariant(), hypro::Location< Number >::getLinearFlows(), hypro::Location< Number >::getName(), hypro::Location< Number >::getRectangularFlows(), hypro::Location< Number >::getTransitions(), hypro::Location< Number >::hash(), and hypro::Location< Number >::Location().
template<typename Number> hypro::Location< Number >::Location (const Location< Number > & loc)
template<typename Number> hypro::Location< Number >::Location (const matrix_t< Number > & mat) explicit
Definition at line 51 of file Location.tpp.
References hypro::Location< Number >::Location().
template<typename Number> hypro::Location< Number >::Location (const matrix_t< Number > & mat, transitionVector && trans, const Condition< Number > & inv)
template<typename Number> hypro::Location< Number >::~Location () inline
Definition at line 54 of file Location.h.
Member Function Documentation
template<typename Number> void hypro::Location< Number >::addTransition (std::unique_ptr< Transition< Number >> && trans)
Definition at line 153 of file Location.tpp.
Referenced by hypro::Location< N >::setInvariant(), and hypro::Transformation< Number >::Transformation().
template<typename Number > void hypro::Location< Number >::decompose (const Decomposition & decomposition)
Definition at line 506 of file Location.tpp.
References hypro::rectangularFlow< Number >::setFlowIntervalForDimension().
Referenced by hypro::Location< N >::setInvariant().
template<typename Number > std::size_t hypro::Location< Number >::dimension () const
Definition at line 106 of file Location.tpp.
Referenced by hypro::Location< N >::getName(), and hypro::toFlowstarFormat().
template<typename Number > std::size_t hypro::Location< Number >::dimension (std::size_t i) const
Definition at line 115 of file Location.tpp.
template<typename Number > std::string hypro::Location< Number >::getDotRepresentation (const std::vector< std::string > & vars) const
Definition at line 197 of file Location.tpp.
References hypro::Location< Number >::getName(), and hypro::Location< Number >::hash().
Referenced by hypro::Location< N >::setInvariant().
template<typename Number> const std::vector<carl::Interval<Number> >& hypro::Location< Number >::getExternalInput () const inline
Definition at line 70 of file Location.h.
Referenced by hypro::Location< Number >::Location(), hypro::Location< Number >::operator=(), and hypro::Location< N >::operator==().
template<typename Number> unsigned hypro::Location< Number >::getId () const inline
Definition at line 72 of file Location.h.
template<typename Number> const Condition<Number>& hypro::Location< Number >::getInvariant () const inline
Definition at line 67 of file Location.h.
Referenced by hypro::Location< Number >::isComposedOf(), hypro::DecisionEntity< Number >::isRectangularSubspace(), hypro::DecisionEntity< Number >::isTimedLocation(), hypro::DecisionEntity< Number >::isTimedSubspace(), hypro::Location< Number >::Location(), std::hash< hypro::Location< Number > >::operator()(), hypro::Location< Number >::operator=(), hypro::Location< N >::operator==(), and hypro::toFlowstarFormat().
template<typename Number> linearFlow<Number> hypro::Location< Number >::getLinearFlow (std::size_t I = 0) const inline
Definition at line 59 of file Location.h.
Referenced by hypro::reachability::computeTrafoMatrix(), hypro::ltiFirstSegmentHandler< State >::computeTrafoMatrix(), hypro::Location< Number >::isComposedOf(), hypro::DecisionEntity< Number >::isDiscreteSubspace(), hypro::DecisionEntity< Number >::isRectangularSubspace(), hypro::DecisionEntity< Number >::isTimedLocation(), hypro::DecisionEntity< Number >::isTimedSubspace(), and hypro::Location< N >::operator==().
template<typename Number> const std::vector<linearFlow<Number> >& hypro::Location< Number >::getLinearFlows () const inline
Definition at line 64 of file Location.h.
Referenced by hypro::Location< Number >::Location(), std::hash< hypro::Location< Number > >::operator()(), hypro::Location< Number >::operator=(), and hypro::Location< N >::operator==().
template<typename Number> std::string hypro::Location< Number >::getName () const inline
Definition at line 73 of file Location.h.
Referenced by hypro::Location< Number >::getDotRepresentation(), hypro::Location< Number >::isComposedOf(), hypro::DecisionEntity< Number >::isRectangularLocation(), hypro::DecisionEntity< Number >::isRectangularSubspace(), hypro::DecisionEntity< Number >::isTimedLocation(), hypro::DecisionEntity< Number >::isTimedSubspace(), hypro::Location< Number >::Location(), std::hash< hypro::Location< Number > >::operator()(), hypro::Location< N >::operator<(), hypro::Location< Number >::operator=(), hypro::Location< N >::operator==(), and hypro::toFlowstarFormat().
template<typename Number> std::size_t hypro::Location< Number >::getNumberFlow () const inline
Definition at line 58 of file Location.h.
Referenced by hypro::DecisionEntity< Number >::isRectangularLocation(), and hypro::DecisionEntity< Number >::isTimedLocation().
template<typename Number> rectangularFlow<Number> hypro::Location< Number >::getRectangularFlow (std::size_t I = 0) const inline
Definition at line 61 of file Location.h.
Referenced by hypro::DecisionEntity< Number >::isDiscreteSubspace(), hypro::DecisionEntity< Number >::isRectangularSubspace(), and hypro::Location< N >::operator==().
template<typename Number> const std::vector<rectangularFlow<Number> >& hypro::Location< Number >::getRectangularFlows () const inline
Definition at line 65 of file Location.h.
Referenced by hypro::Location< Number >::Location(), std::hash< hypro::Location< Number > >::operator()(), and hypro::Location< Number >::operator=().
template<typename Number> const transitionVector& hypro::Location< Number >::getTransitions () const inline
Definition at line 68 of file Location.h.
Referenced by hypro::Location< Number >::isComposedOf(), hypro::DecisionEntity< Number >::isRectangularSubspace(), hypro::DecisionEntity< Number >::isTimedLocation(), hypro::DecisionEntity< Number >::isTimedSubspace(), hypro::Location< Number >::Location(), and hypro::Location< Number >::operator=().
template<typename Number> bool hypro::Location< Number >::hasExternalInput () const inline
Definition at line 71 of file Location.h.
template<typename Number > std::size_t hypro::Location< Number >::hash () const
Definition at line 189 of file Location.tpp.
Referenced by hypro::Location< Number >::getDotRepresentation(), hypro::HybridAutomaton< Number >::HybridAutomaton(), hypro::Location< Number >::Location(), hypro::Location< N >::operator<(), hypro::Location< Number >::operator=(), hypro::Location< N >::operator==(), and hypro::Location< N >::setInvariant().
template<typename Number> bool hypro::Location< Number >::isComposedOf (const Location< Number > & rhs, const std::vector< std::string > & rhsVars, const std::vector< std::string > & thisVars) const
Determines if this composed of rhs and some potential rest.
Checks whether this location can be the result of a parallel composition where rhs is involved as a composite.
Parameters
[in] rhs The right hand side
[in] rhsVars The right hand side variables
[in] thisVars The variables of this location
Returns
True if composed of, False otherwise.
Definition at line 229 of file Location.tpp.
References hypro::Location< Number >::getInvariant(), hypro::Location< Number >::getLinearFlow(), hypro::Location< Number >::getName(), and hypro::Location< Number >::getTransitions().
Referenced by hypro::Location< N >::setInvariant().
template<typename Number> bool hypro::Location< Number >::operator!= (const Location< Number > & rhs) const inline
Definition at line 190 of file Location.h.
template<typename Number> bool hypro::Location< Number >::operator< (const Location< Number > & rhs) const inline
Definition at line 124 of file Location.h.
template<typename Number> Location< Number > & hypro::Location< Number >::operator= (const Location< Number > & in)
Definition at line 81 of file Location.tpp.
References hypro::Location< Number >::getExternalInput(), hypro::Location< Number >::getInvariant(), hypro::Location< Number >::getLinearFlows(), hypro::Location< Number >::getName(), hypro::Location< Number >::getRectangularFlows(), hypro::Location< Number >::getTransitions(), and hypro::Location< Number >::hash().
Referenced by hypro::Location< N >::~Location().
template<typename Number> bool hypro::Location< Number >::operator== (const Location< Number > & rhs) const inline
Definition at line 135 of file Location.h.
template<typename Number> linearFlow<Number>& hypro::Location< Number >::rGetLinearFlow (std::size_t I = 0) inline
Definition at line 60 of file Location.h.
template<typename Number> rectangularFlow<Number>& hypro::Location< Number >::rGetRectangularFlow (std::size_t I = 0) inline
Definition at line 62 of file Location.h.
template<typename Number> transitionVector& hypro::Location< Number >::rGetTransitions () inline
Definition at line 69 of file Location.h.
template<typename Number> void hypro::Location< Number >::setExtInput (const std::vector< carl::Interval< Number >> & b)
Definition at line 177 of file Location.tpp.
Referenced by hypro::Location< N >::setInvariant().
template<typename Number> void hypro::Location< Number >::setFlow (const matrix_t< Number > & f, std::size_t I = 0) inline
Definition at line 81 of file Location.h.
Referenced by createComponent1(), createComponent2(), createComponent3(), createComponent4(), and main().
template<typename Number> void hypro::Location< Number >::setFlow (const linearFlow< Number > & f, std::size_t I = 0) inline
Definition at line 82 of file Location.h.
template<typename Number> void hypro::Location< Number >::setFlow (const rectangularFlow< Number > & f, std::size_t I = 0) inline
Definition at line 83 of file Location.h.
template<typename Number> void hypro::Location< Number >::setInvariant (const Condition< Number > & inv) inline
Definition at line 94 of file Location.h.
Referenced by createComponent1(), createComponent2(), createComponent3(), and createComponent4().
template<typename Number> void hypro::Location< Number >::setLinearFlow (const linearFlow< Number > & f, std::size_t I = 0)
Definition at line 121 of file Location.tpp.
Referenced by hypro::Location< N >::setFlow().
template<typename Number> void hypro::Location< Number >::setLinearFlow (const std::vector< linearFlow< Number >> & flows) inline
Definition at line 86 of file Location.h.
template<typename Number> void hypro::Location< Number >::setName (const std::string & name) inline
Definition at line 77 of file Location.h.
Referenced by createComponent1(), createComponent2(), createComponent3(), createComponent4(), hypro::CIFLocVisitor< Number >::visitLocations(), and hypro::HyproLocationVisitor< Number >::visitModes().
template<typename Number> void hypro::Location< Number >::setRectangularFlow (const rectangularFlow< Number > & f, std::size_t I = 0)
Definition at line 131 of file Location.tpp.
Referenced by main(), and hypro::Location< N >::setFlow().
template<typename Number> void hypro::Location< Number >::setRectangularFlow (const std::vector< rectangularFlow< Number >> & flows) inline
Definition at line 90 of file Location.h.
template<typename Number > void hypro::Location< Number >::setTransitions (transitionVector && trans)
Definition at line 141 of file Location.tpp.
Referenced by hypro::Location< N >::setInvariant().
Friends And Related Function Documentation
template<typename Number> std::ostream& operator<< (std::ostream & ostr, const Location< Number > & l) friend
Definition at line 192 of file Location.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/Location.h
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/Location.tpp