HyPro: hypro::BoxT< Number, Converter, Setting > Class Template Reference
hypro::BoxT< Number, Converter, Setting > Class Template Reference
State set representations
The class which represents a box.
#include <Box.h>
Public Types
typedef Setting Settings
Public Types inherited from hypro::GeometricObject< Number, BoxT< Number, Converter, Setting > >
typedef Number NumberType
Public Member Functions
BoxT ()
Creates an empty box.
BoxT (const BoxT &orig)=default
Copy constructor.
template<typename SettingRhs , carl::DisableIf< std::is_same< Setting, SettingRhs >> = carl::dummy>
BoxT (const BoxT< Number, Converter, SettingRhs > &orig)
Copy constructor. NOTE: it is not an actual copy constructor as it is templated.
BoxT (BoxT &&orig)=default
Move constructor.
BoxT (const carl::Interval< Number > &val)
Box constructor from one interval, results in a one-dimensional box.
BoxT (const std::pair< Point< Number >, Point< Number >> &limits)
Box constructor from a pair of points.
BoxT (const std::vector< carl::Interval< Number >> &_intervals)
Constructor from a vector of intervals.
BoxT (const matrix_t< Number > &_constraints, const vector_t< Number > &_constants)
Constructor from a matrix and a vector.
BoxT (const std::set< Point< Number >> &_points)
Constructor from a set of points.
BoxT (const std::vector< Point< Number >> &_points)
A constructor from a vector of points.
~BoxT ()
Destructor.
Setting getSettings () const
const std::vector< carl::Interval< Number > > & intervals () const
Getter for interval representation of the current box.
std::vector< carl::Interval< Number > > & rIntervals ()
std::pair< Point< Number >, Point< Number > > limits () const
Getter for the limiting points.
matrix_t< Number > matrix () const
vector_t< Number > vector () const
std::vector< Halfspace< Number > > constraints () const
Getter for the hyperplanar representation of the current box.
void insert (const carl::Interval< Number > &val)
Extends the dimension of the current box by the given interval.
const carl::Interval< Number > & interval (std::size_t d) const
Getter for an interval representation of one specific dimension.
carl::Interval< Number > & rInterval (std::size_t d)
carl::Interval< Number > at (std::size_t _index) const
Getter for an interval representation of one specific dimension.
bool empty () const
Determines if the current box is empty.
bool isSymmetric () const
Determines if the current box is symmetric.
Point< Number > max () const
Getter for the maximal point.
Point< Number > min () const
Getter for the minimal point.
Number supremum () const
Method returning the supremum point of the box, i.e. the maximal point.
std::vector< Point< Number > > vertices (const matrix_t< Number > &=matrix_t< Number >::Zero(0, 0)) const
Getter for a vertex-representation of the current box.
EvaluationResult< Number > evaluate (const vector_t< Number > &_direction, bool=true) const
Evaluation function (convex linear optimization).
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &_directions, bool useExact=true) const
Multi-evaluation function (convex linear optimization).
BoxT & operator= (const BoxT &rhs)=default
Assignment operator.
BoxT & operator= (BoxT &&rhs)=default
Move assignment operator.
BoxT operator* (const Number &factor) const
Scaling operator.
const carl::Interval< Number > & operator[] (unsigned i) const
Access operator (const).
carl::Interval< Number > & operator[] (unsigned i)
std::size_t dimension () const
Getter for the state space dimension.
void removeRedundancy ()
Removes redundancy (part of the general interface. Does nothing for boxes.)
std::size_t size () const
Storage size determination.
const BoxT & reduceNumberRepresentation (unsigned limit=fReach_DENOMINATOR)
Function to reduce the number representation (over-approximate).
BoxT makeSymmetric () const
Makes a symmetric box from the current box.
std::pair< CONTAINMENT, BoxT > satisfiesHalfspace (const Halfspace< Number > &rhs) const
Meta-function, which allows to compute the intersection of a box with a half-space and return the resulting box as well as the information, whether the resulting box is empty.
std::pair< CONTAINMENT, BoxT > satisfiesHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const
Method combining the intersection of the set with a set of halfspaces and a test for emptiness of the resulting set.
BoxT project (const std::vector< std::size_t > &dimensions) const
Projects the set on the ordered set of given dimensions.
BoxT assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &assignments) const
Function to set a variable to an interval. This is a meta-function which consists of projecting out the respective dimension, resulting in a lower-dimensional state set. Afterwards the state set is lifted to the original state space, i.e., unconstrained dimensions are added and finally, the interval constraints as given are added.
BoxT linearTransformation (const matrix_t< Number > &A) const
Computes the linear transformation of a box by a matrix A.
BoxT affineTransformation (const matrix_t< Number > &A, const vector_t< Number > &b) const
Computes the affine transformation of a box by a matrix A and an offset vector b.
BoxT minkowskiSum (const BoxT &rhs) const
BoxT minkowskiDecomposition (const BoxT &rhs) const
Computes the Minkowski decomposition of the current box by the given box.
BoxT intersect (const BoxT &rhs) const
Computes the intersection of two boxes.
BoxT intersectHalfspace (const Halfspace< Number > &hspace) const
Allows to compute the intersection of a box with a half-space and return the resulting box.
BoxT intersectHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const
Computes the intersection of the set with a set of halfspaces.
bool contains (const Point< Number > &point) const
Checks, whether the set contains the passed point.
bool contains (const BoxT &box) const
Containment check for a box.
BoxT unite (const BoxT &rhs) const
Computes the union of two boxes.
void reduceRepresentation ()
Reduces the box - only in case rational types are used, the number representation is optimized.
void clear ()
Makes this box equal to the empty box.
void print () const
A deprecated print method. Use the outstream operator.
Public Member Functions inherited from hypro::GeometricObject< Number, BoxT< Number, Converter, Setting > >
virtual ~GeometricObject ()
Destroys the object.
virtual BoxT< Number, Converter, Setting > minkowskiSum (const BoxT< Number, Converter, Setting > &rhs) const =0
Computes Minkowski's sum of the current set and the passed set.
virtual bool contains (const BoxT< Number, Converter, Setting > &rhs) const =0
virtual BoxT< Number, Converter, Setting > unite (const BoxT< Number, Converter, Setting > &rhs) const =0
Computes the convex hull of the union of the set and the passed set.
Static Public Member Functions
static BoxT Empty (std::size_t dimension=1)
Static method for the construction of an empty box of required dimension.
static representation_name type ()
static BoxT unite (const std::vector< BoxT > &boxes)
Computes the union of the current box with a set of boxes.
Protected Attributes
std::vector< carl::Interval< Number > > mLimits
bool mEmpty
Friends
template<class SettingRhs >
bool operator== (const BoxT &b1, const BoxT< Number, Converter, SettingRhs > &b2)
Checks if two boxes are equal.
bool operator!= (const BoxT &b1, const BoxT &b2)
Determines inequality of two boxes.
std::ostream & operator<< (std::ostream &ostr, const BoxT< Number, Converter, Setting > &b)
Outstream operator.
Detailed Description
template<typename Number, typename Converter, class Setting>
class hypro::BoxT< Number, Converter, Setting >
The class which represents a box.
A box is represented by an ordered sequence of intervals. Details can be found here.
Template Parameters
Number The used number type.
Converter The used converter.
@{
Definition at line 55 of file Box.h.
Member Typedef Documentation
template<typename Number, typename Converter, class Setting> typedef Setting hypro::BoxT< Number, Converter, Setting >::Settings
Definition at line 62 of file Box.h.
Constructor & Destructor Documentation
template<typename Number, typename Converter, class Setting> hypro::BoxT< Number, Converter, Setting >::BoxT () inline
Creates an empty box.
The empty box is represented by a zero-dimensional point pair.
Definition at line 77 of file Box.h.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::BoxT().
template<typename Number, typename Converter, class Setting> hypro::BoxT< Number, Converter, Setting >::BoxT (const BoxT< Number, Converter, Setting > & orig) default
Copy constructor.
Parameters
[in] orig The original.
template<typename Number, typename Converter, class Setting> template<typename SettingRhs , carl::DisableIf< std::is_same< Setting, SettingRhs >> = carl::dummy> hypro::BoxT< Number, Converter, Setting >::BoxT (const BoxT< Number, Converter, SettingRhs > & orig) inline
Copy constructor. NOTE: it is not an actual copy constructor as it is templated.
Parameters
[in] orig The original.
Definition at line 95 of file Box.h.
template<typename Number, typename Converter, class Setting> hypro::BoxT< Number, Converter, Setting >::BoxT (BoxT< Number, Converter, Setting > && orig) default
Move constructor.
Parameters
[in] orig The original.
template<typename Number, typename Converter, class Setting> hypro::BoxT< Number, Converter, Setting >::BoxT (const carl::Interval< Number > & val) inline explicit
Box constructor from one interval, results in a one-dimensional box.
Parameters
[in] val An interval.
Definition at line 109 of file Box.h.
template<typename Number, typename Converter, class Setting> hypro::BoxT< Number, Converter, Setting >::BoxT (const std::pair< Point< Number >, Point< Number >> & limits) inline explicit
Box constructor from a pair of points.
The given parameters are considered as the maximal and minimal point. The constructor does not check the order of points.
Parameters
limits Pair of points.
Definition at line 120 of file Box.h.
template<typename Number, typename Converter, class Setting> hypro::BoxT< Number, Converter, Setting >::BoxT (const std::vector< carl::Interval< Number >> & _intervals) inline explicit
Constructor from a vector of intervals.
The vector is required to be sorted, i.e. the first interval maps to the first dimension etc..
Parameters
_intervals A vector of intervals.
Definition at line 134 of file Box.h.
template<typename Number, typename Converter, class Setting> hypro::BoxT< Number, Converter, Setting >::BoxT (const matrix_t< Number > & _constraints, const vector_t< Number > & _constants)
Constructor from a matrix and a vector.
Constructs a box assuming each row of the matrix is the normal to a hyperplane and its corresponding entry in the given vector is the offset.
Parameters
_constraints A matrix representing the constraint normals.
_constants A vector representing the offsets of the corresponting hyperplane.
template<typename Number, typename Converter, class Setting> hypro::BoxT< Number, Converter, Setting >::BoxT (const std::set< Point< Number >> & _points) explicit
Constructor from a set of points.
The constructor does not rely on the operator < of the point class, thus each point is considered for the construction of the maximal and minimal point.
Parameters
_points A set of points.
template<typename Number, typename Converter, class Setting> hypro::BoxT< Number, Converter, Setting >::BoxT (const std::vector< Point< Number >> & _points) explicit
A constructor from a vector of points.
Creates the maximal and minimal point by collecting all coordinates from all given points.
Parameters
_points A vector of points.
template<typename Number, typename Converter, class Setting> hypro::BoxT< Number, Converter, Setting >::~BoxT () inline
Destructor.
Definition at line 173 of file Box.h.
Member Function Documentation
template<typename Number, typename Converter, class Setting> BoxT hypro::BoxT< Number, Converter, Setting >::affineTransformation (const matrix_t< Number > & A, const vector_t< Number > & b) const virtual
Computes the affine transformation of a box by a matrix A and an offset vector b.
The computation is performed via interval arithmetic using a linear transformation operation and afterwards accounting for the translation invoked by b.
Parameters
A
b
Returns
BoxT<Number,Converter,Setting>
Implements hypro::GeometricObject< Number, BoxT< Number, Converter, Setting > >.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> BoxT hypro::BoxT< Number, Converter, Setting >::assignIntervals (const std::map< std::size_t, carl::Interval< Number >> & assignments) const virtual
Function to set a variable to an interval. This is a meta-function which consists of projecting out the respective dimension, resulting in a lower-dimensional state set. Afterwards the state set is lifted to the original state space, i.e., unconstrained dimensions are added and finally, the interval constraints as given are added.
Parameters
assignments A map from dimension index to interval.
Returns
DerivedShape
Implements hypro::GeometricObject< Number, BoxT< Number, Converter, Setting > >.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> carl::Interval<Number> hypro::BoxT< Number, Converter, Setting >::at (std::size_t _index) const inline
Getter for an interval representation of one specific dimension.
Converts the d-th entries in the maximal and minimal point to an interval.
Parameters
d The queried dimension.
Returns
An interval.
Definition at line 268 of file Box.h.
template<typename Number, typename Converter, class Setting> void hypro::BoxT< Number, Converter, Setting >::clear ()
Makes this box equal to the empty box.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::reduceRepresentation().
template<typename Number, typename Converter, class Setting> std::vector<Halfspace<Number> > hypro::BoxT< Number, Converter, Setting >::constraints () const
Getter for the hyperplanar representation of the current box.
Converts the two-points representation into a hyperplanar representation, i.e. a H-polytope.
Returns
A vector of hyperplanes.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::limits().
template<typename Number, typename Converter, class Setting> bool hypro::BoxT< Number, Converter, Setting >::contains (const Point< Number > & point) const virtual
Checks, whether the set contains the passed point.
Parameters
[in] point The point.
Returns
True, if the point lies inside the set, false otherwise.
Implements hypro::GeometricObject< Number, BoxT< Number, Converter, Setting > >.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> bool hypro::BoxT< Number, Converter, Setting >::contains (const BoxT< Number, Converter, Setting > & box) const
Containment check for a box.
Parameters
[in] box The box.
Returns
True, if the given box is contained in the current box, false otherwise.
template<typename Number, typename Converter, class Setting> std::size_t hypro::BoxT< Number, Converter, Setting >::dimension () const inline virtual
Getter for the state space dimension.
Returns
The dimension of the space.
Implements hypro::GeometricObject< Number, BoxT< Number, Converter, Setting > >.
Definition at line 438 of file Box.h.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::BoxT(), hypro::BoxT< Number, hypro::Converter, Setting >::Empty(), hypro::BoxT< Number, hypro::Converter, Setting >::limits(), hypro::BoxT< Number, hypro::Converter, Setting >::max(), and hypro::BoxT< Number, hypro::Converter, Setting >::min().
template<typename Number, typename Converter, class Setting> static BoxT hypro::BoxT< Number, Converter, Setting >::Empty (std::size_t dimension = 1) inline static
Static method for the construction of an empty box of required dimension.
Parameters
dimension Required dimension.
Returns
Empty box.
Definition at line 186 of file Box.h.
template<typename Number, typename Converter, class Setting> bool hypro::BoxT< Number, Converter, Setting >::empty () const inline virtual
Determines if the current box is empty.
The method checks the dimension of the limit points and afterwards each interval for emptiness.
Returns
True, if one interval is empty. False if the dimension is 0 or no interval is empty.
Implements hypro::GeometricObject< Number, BoxT< Number, Converter, Setting > >.
Definition at line 277 of file Box.h.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::BoxT(), and hypro::operator*().
template<typename Number, typename Converter, class Setting> EvaluationResult<Number> hypro::BoxT< Number, Converter, Setting >::evaluate (const vector_t< Number > & _direction, bool = true) const
Evaluation function (convex linear optimization).
Linear optimization for boxes can be done more efficiently that for general convey polytopes as the state space dimensions are independent. Consequently it suffices to consider the coefficient of the cost function for each dimension and either use the upper, respectively lower bound depending on its sign (positive, respectively negative) to get the vertex of the box representing the optimum.
Parameters
[in] _direction The direction/cost function.
Returns
Maximum towards _direction.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::min().
template<typename Number, typename Converter, class Setting> Setting hypro::BoxT< Number, Converter, Setting >::getSettings () const inline
Definition at line 179 of file Box.h.
template<typename Number, typename Converter, class Setting> void hypro::BoxT< Number, Converter, Setting >::insert (const carl::Interval< Number > & val) inline
Extends the dimension of the current box by the given interval.
Effectively extends the dimension of the current box.
Parameters
val An interval.
Definition at line 237 of file Box.h.
template<typename Number, typename Converter, class Setting> BoxT hypro::BoxT< Number, Converter, Setting >::intersect (const BoxT< Number, Converter, Setting > & rhs) const
Computes the intersection of two boxes.
Parameters
[in] rhs The right hand side box.
Returns
The resulting box.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> BoxT hypro::BoxT< Number, Converter, Setting >::intersectHalfspace (const Halfspace< Number > & hspace) const virtual
Allows to compute the intersection of a box with a half-space and return the resulting box.
The computation is done by exploiting interval arithmetic similar to contraction operations in interval constraint propagation on linear constraints.
Parameters
hspace
Returns
BoxT<Number,Converter,Setting>
Implements hypro::GeometricObject< Number, BoxT< Number, Converter, Setting > >.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> BoxT hypro::BoxT< Number, Converter, Setting >::intersectHalfspaces (const matrix_t< Number > & _mat, const vector_t< Number > & _vec) const virtual
Computes the intersection of the set with a set of halfspaces.
The halfspaces are given as a matrix A and a vector b such that the resulting intersection of the set S with the set of halfspaces is the set R = \(\{ x | x \in S \land A\cdot x \leq b \} \).
Parameters
[in] _mat The matrix.
[in] _vec The vector.
Returns
The resulting set.
Implements hypro::GeometricObject< Number, BoxT< Number, Converter, Setting > >.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> const carl::Interval<Number>& hypro::BoxT< Number, Converter, Setting >::interval (std::size_t d) const inline
Getter for an interval representation of one specific dimension.
Converts the d-th entries in the maximal and minimal point to an interval.
Parameters
d The queried dimension.
Returns
An interval.
Definition at line 252 of file Box.h.
template<typename Number, typename Converter, class Setting> const std::vector<carl::Interval<Number> >& hypro::BoxT< Number, Converter, Setting >::intervals () const inline
Getter for interval representation of the current box.
Converts the two-points representation of the current box into a sorted vector of intervals.
Returns
A vector of intervals.
Definition at line 197 of file Box.h.
template<typename Number, typename Converter, class Setting> bool hypro::BoxT< Number, Converter, Setting >::isSymmetric () const inline
Determines if the current box is symmetric.
A box is symmetric, if its centroid is the origin in the respective space, i.e. if the center of each interval in each dimension is zero.
Returns
True if symmetric, False otherwise.
Definition at line 287 of file Box.h.
template<typename Number, typename Converter, class Setting> std::pair<Point<Number>, Point<Number> > hypro::BoxT< Number, Converter, Setting >::limits () const inline
Getter for the limiting points.
Returns
A pair of points.
Definition at line 208 of file Box.h.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::BoxT(), and hypro::convert().
template<typename Number, typename Converter, class Setting> BoxT hypro::BoxT< Number, Converter, Setting >::linearTransformation (const matrix_t< Number > & A) const virtual
Computes the linear transformation of a box by a matrix A.
We employ interval-arithmetic to compute the result instead of a naive approach in which a conversion to a V-polytope would be used.
Parameters
A Matrix used for the transformation.
Returns
BoxT<Number,Converter,Setting>
Implements hypro::GeometricObject< Number, BoxT< Number, Converter, Setting > >.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> BoxT hypro::BoxT< Number, Converter, Setting >::makeSymmetric () const
Makes a symmetric box from the current box.
The symmetry is obtained by dimension-wise extension of the boundaries. The resulting boundaries for each dimension are the maximal absolute values of the original boundaries mirrored positive and negative.
Returns
The resulting symmetric box.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> matrix_t<Number> hypro::BoxT< Number, Converter, Setting >::matrix () const
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::limits().
template<typename Number, typename Converter, class Setting> Point<Number> hypro::BoxT< Number, Converter, Setting >::max () const inline
Getter for the maximal point.
Returns
A point.
Definition at line 303 of file Box.h.
template<typename Number, typename Converter, class Setting> Point<Number> hypro::BoxT< Number, Converter, Setting >::min () const inline
Getter for the minimal point.
Returns
A point.
Definition at line 315 of file Box.h.
template<typename Number, typename Converter, class Setting> BoxT hypro::BoxT< Number, Converter, Setting >::minkowskiDecomposition (const BoxT< Number, Converter, Setting > & rhs) const
Computes the Minkowski decomposition of the current box by the given box.
This operation can be seen as the set-theoretic equivalent of subtraction. Note that this is not entirely true, as the operation is performed on sets which adds over-approximation errors (similarly to using addition and subtraction in interval-arithmetic).
Parameters
[in] rhs The right hand side box.
Returns
The resulting box.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> BoxT hypro::BoxT< Number, Converter, Setting >::minkowskiSum (const BoxT< Number, Converter, Setting > & rhs) const
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> std::vector<EvaluationResult<Number> > hypro::BoxT< Number, Converter, Setting >::multiEvaluate (const matrix_t< Number > & _directions, bool useExact = true) const
Multi-evaluation function (convex linear optimization).
Can be done similar to basic linear optimization in one direction.
Parameters
[in] _directions The directions/cost functions.
Returns
A set of maxima towards the respective directions.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::min().
template<typename Number, typename Converter, class Setting> BoxT hypro::BoxT< Number, Converter, Setting >::operator* (const Number & factor) const inline
Scaling operator.
Parameters
[in] factor The scaling factor.
Returns
The scaled box.
Definition at line 400 of file Box.h.
template<typename Number, typename Converter, class Setting> BoxT& hypro::BoxT< Number, Converter, Setting >::operator= (const BoxT< Number, Converter, Setting > & rhs) default
Assignment operator.
Parameters
rhs A box.
template<typename Number, typename Converter, class Setting> BoxT& hypro::BoxT< Number, Converter, Setting >::operator= (BoxT< Number, Converter, Setting > && rhs) default
Move assignment operator.
Parameters
rhs A box.
template<typename Number, typename Converter, class Setting> const carl::Interval<Number>& hypro::BoxT< Number, Converter, Setting >::operator[] (unsigned i) const inline
Access operator (const).
Parameters
i Dimension to access.
Returns
An interval.
Definition at line 427 of file Box.h.
template<typename Number, typename Converter, class Setting> carl::Interval<Number>& hypro::BoxT< Number, Converter, Setting >::operator[] (unsigned i) inline
Definition at line 428 of file Box.h.
template<typename Number, typename Converter, class Setting> void hypro::BoxT< Number, Converter, Setting >::print () const
A deprecated print method. Use the outstream operator.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::reduceRepresentation().
template<typename Number, typename Converter, class Setting> BoxT hypro::BoxT< Number, Converter, Setting >::project (const std::vector< std::size_t > & dimensions) const virtual
Projects the set on the ordered set of given dimensions.
Parameters
[in] dimensions The dimensions.
Returns
The resulting set.
Implements hypro::GeometricObject< Number, BoxT< Number, Converter, Setting > >.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> const BoxT& hypro::BoxT< Number, Converter, Setting >::reduceNumberRepresentation (unsigned limit = fReach_DENOMINATOR)
Function to reduce the number representation (over-approximate).
The function tries to reduce the size of each interval boundary in case it is larger than some specified limit. This is done by outward rounding. Note that this function is only relevant, if the number representation may affect running times (here: rational number implementations).
Parameters
[in] limit The limit
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::reduceRepresentation(), and hypro::BoxT< Number, hypro::Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> void hypro::BoxT< Number, Converter, Setting >::reduceRepresentation () inline virtual
Reduces the box - only in case rational types are used, the number representation is optimized.
Implements hypro::GeometricObject< Number, BoxT< Number, Converter, Setting > >.
Definition at line 553 of file Box.h.
template<typename Number, typename Converter, class Setting> void hypro::BoxT< Number, Converter, Setting >::removeRedundancy () inline
Removes redundancy (part of the general interface. Does nothing for boxes.)
Definition at line 443 of file Box.h.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::reduceRepresentation().
template<typename Number, typename Converter, class Setting> carl::Interval<Number>& hypro::BoxT< Number, Converter, Setting >::rInterval (std::size_t d) inline
Definition at line 257 of file Box.h.
template<typename Number, typename Converter, class Setting> std::vector<carl::Interval<Number> >& hypro::BoxT< Number, Converter, Setting >::rIntervals () inline
Definition at line 200 of file Box.h.
template<typename Number, typename Converter, class Setting> std::pair<CONTAINMENT, BoxT> hypro::BoxT< Number, Converter, Setting >::satisfiesHalfspace (const Halfspace< Number > & rhs) const virtual
Meta-function, which allows to compute the intersection of a box with a half-space and return the resulting box as well as the information, whether the resulting box is empty.
The computation is done by exploiting interval arithmetic similar to contraction operations in interval constraint propagation on linear constraints.
Parameters
rhs
Returns
std::pair<CONTAINMENT, BoxT>
Implements hypro::GeometricObject< Number, BoxT< Number, Converter, Setting > >.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> std::pair<CONTAINMENT, BoxT> hypro::BoxT< Number, Converter, Setting >::satisfiesHalfspaces (const matrix_t< Number > & _mat, const vector_t< Number > & _vec) const virtual
Method combining the intersection of the set with a set of halfspaces and a test for emptiness of the resulting set.
The halfspaces are given as a matrix A and a vector b such that the resulting intersection of the set S with the set of halfspaces is the set R = \(\{ x | x \in S \land A\cdot x \leq b \} \). Note that this check is at least as fast as performing the intersection and testing for emptiness, but in general we encourage to use this method instead.
Parameters
[in] _mat The matrix.
[in] _vec The vector.
Returns
A pair of a CONTAINMENT type stating whether the resulting set is empty and the resulting set.
Implements hypro::GeometricObject< Number, BoxT< Number, Converter, Setting > >.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> std::size_t hypro::BoxT< Number, Converter, Setting >::size () const
Storage size determination.
Returns
Size of the required memory.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::removeRedundancy().
template<typename Number, typename Converter, class Setting> Number hypro::BoxT< Number, Converter, Setting >::supremum () const
Method returning the supremum point of the box, i.e. the maximal point.
Returns
A point representing the supremum of the current box.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::min().
template<typename Number, typename Converter, class Setting> static representation_name hypro::BoxT< Number, Converter, Setting >::type () inline static
Definition at line 451 of file Box.h.
template<typename Number, typename Converter, class Setting> BoxT hypro::BoxT< Number, Converter, Setting >::unite (const BoxT< Number, Converter, Setting > & rhs) const
Computes the union of two boxes.
Parameters
[in] rhs The right hand side box.
Returns
The resulting box.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::type().
template<typename Number, typename Converter, class Setting> static BoxT hypro::BoxT< Number, Converter, Setting >::unite (const std::vector< BoxT< Number, Converter, Setting > > & boxes) static
Computes the union of the current box with a set of boxes.
Parameters
[in] boxes The boxes.
Returns
The resulting box.
template<typename Number, typename Converter, class Setting> vector_t<Number> hypro::BoxT< Number, Converter, Setting >::vector () const
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::limits().
template<typename Number, typename Converter, class Setting> std::vector<Point<Number> > hypro::BoxT< Number, Converter, Setting >::vertices (const matrix_t< Number > & = matrix_t< Number >::Zero(0, 0)) const virtual
Getter for a vertex-representation of the current box.
Converts the current box from its two-point representation into a vertex representation, i.e. a V-polytope. The representation is generated by creating all possible combinations of upper and lower bounds of the box.
Returns
A vector of points.
Implements hypro::GeometricObject< Number, BoxT< Number, Converter, Setting > >.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::min().
Friends And Related Function Documentation
template<typename Number, typename Converter, class Setting> bool operator!= (const BoxT< Number, Converter, Setting > & b1, const BoxT< Number, Converter, Setting > & b2) friend
Determines inequality of two boxes.
Parameters
b1 A box.
b2 A box.
Returns
False, if both boxes are equal.
Definition at line 378 of file Box.h.
template<typename Number, typename Converter, class Setting> std::ostream& operator<< (std::ostream & ostr, const BoxT< Number, Converter, Setting > & b) friend
Outstream operator.
Parameters
ostr Outstream.
b A box.
Definition at line 413 of file Box.h.
template<typename Number, typename Converter, class Setting> template<class SettingRhs > bool operator== (const BoxT< Number, Converter, Setting > & b1, const BoxT< Number, Converter, SettingRhs > & b2) friend
Checks if two boxes are equal.
Parameters
b1 Contains the first box.
b2 Contains the second box.
Returns
True, if they are equal.
Definition at line 360 of file Box.h.
Member Data Documentation
template<typename Number, typename Converter, class Setting> bool hypro::BoxT< Number, Converter, Setting >::mEmpty protected
Cache for emptiness.
Definition at line 66 of file Box.h.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::empty().
template<typename Number, typename Converter, class Setting> std::vector<carl::Interval<Number> > hypro::BoxT< Number, Converter, Setting >::mLimits protected
Box as a vector of intervals.
Definition at line 65 of file Box.h.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::intervals(), and hypro::BoxT< Number, hypro::Converter, Setting >::rIntervals().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/Box/Box.h