HyPro: hypro::IntersectOp< Number, Converter, Setting > Class Template Reference
hypro::IntersectOp< Number, Converter, Setting > Class Template Reference
#include <IntersectOp.h>
Public Member Functions
IntersectOp ()=delete
IntersectOp (const SupportFunctionNewT< Number, Converter, Setting > &lhs, const SupportFunctionNewT< Number, Converter, Setting > &rhs)
IntersectOp (const SupportFunctionNewT< Number, Converter, Setting > &lhs, const std::vector< SupportFunctionNewT< Number, Converter, Setting >> &rhs)
IntersectOp (const RGNData &)
~IntersectOp ()
SFNEW_TYPE getType () const override
unsigned getOriginCount () const override
std::size_t getDimension () const override
RGNData * getData () const override
void setDimension (const std::size_t d) override
matrix_t< Number > transform (const matrix_t< Number > &param) const override
std::vector< EvaluationResult< Number > > compute (const matrix_t< Number > &, bool) const override
std::vector< EvaluationResult< Number > > aggregate (std::vector< std::vector< EvaluationResult< Number >>> &resultStackBack, const matrix_t< Number > &) const override
bool empty (const std::vector< bool > &childrenEmpty) const override
Point< Number > supremumPoint (std::vector< Point< Number >> &points) const override
bool contains (const std::vector< bool > &v, const vector_t< Number > &) const override
std::vector< std::size_t > intersectDims (const std::vector< std::vector< std::size_t >> &dims) const override
Public Member Functions inherited from hypro::RootGrowNode< Number, Converter, Setting >
RootGrowNode ()
virtual ~RootGrowNode ()
virtual PointerVec getChildren () const
virtual PointerVec & rGetChildren ()
virtual SETSTATE isEmpty () const
virtual LeafData getLeafData () const
void addToChildren (const std::shared_ptr< RootGrowNode > &rhs)
void clearChildren ()
virtual void print (std::ostream &ostr) const
virtual bool empty () const
virtual Point< Number > supremumPoint () const
virtual vector_t< Number > reverseOp (const vector_t< Number > &point) const
virtual bool contains (const vector_t< Number > &) const
Private Attributes
SFNEW_TYPE type = SFNEW_TYPE::INTERSECTOP
unsigned originCount = 2
std::size_t mDimension = 0
std::vector< std::shared_ptr< RootGrowNode< Number, Converter, Setting > > > mChildren
Additional Inherited Members
Public Types inherited from hypro::RootGrowNode< Number, Converter, Setting >
using PointerVec = std::vector< std::shared_ptr< RootGrowNode< Number, Converter, Setting >>>
Protected Attributes inherited from hypro::RootGrowNode< Number, Converter, Setting >
SFNEW_TYPE mType = NODE
unsigned originCount = 0
PointerVec mChildren = PointerVec()
std::size_t mDimension = 0
SETSTATE mEmptyState = SETSTATE::UNKNOWN
Detailed Description
template<typename Number, typename Converter, typename Setting>
class hypro::IntersectOp< Number, Converter, Setting >
Definition at line 26 of file IntersectOp.h.
Constructor & Destructor Documentation
template<typename Number , typename Converter , typename Setting > hypro::IntersectOp< Number, Converter, Setting >::IntersectOp () delete
template<typename Number , typename Converter , typename Setting > hypro::IntersectOp< Number, Converter, Setting >::IntersectOp (const SupportFunctionNewT< Number, Converter, Setting > & lhs, const SupportFunctionNewT< Number, Converter, Setting > & rhs) inline
Definition at line 43 of file IntersectOp.h.
References hypro::SupportFunctionNewT< Number, Converter, Setting >::addOperation(), assert(), hypro::SupportFunctionNewT< Number, Converter, Setting >::dimension(), hypro::EMPTY, hypro::SupportFunctionNewT< Number, Converter, Setting >::empty(), and vector.
template<typename Number , typename Converter , typename Setting > hypro::IntersectOp< Number, Converter, Setting >::IntersectOp (const SupportFunctionNewT< Number, Converter, Setting > & lhs, const std::vector< SupportFunctionNewT< Number, Converter, Setting >> & rhs) inline
Definition at line 54 of file IntersectOp.h.
References hypro::SupportFunctionNewT< Number, Converter, Setting >::addOperation(), assert(), hypro::SupportFunctionNewT< Number, Converter, Setting >::dimension(), hypro::EMPTY, hypro::SupportFunctionNewT< Number, Converter, Setting >::empty(), and rhs.
template<typename Number , typename Converter , typename Setting > hypro::IntersectOp< Number, Converter, Setting >::IntersectOp (const RGNData &) inline
Definition at line 69 of file IntersectOp.h.
template<typename Number , typename Converter , typename Setting > hypro::IntersectOp< Number, Converter, Setting >::~IntersectOp () inline
Definition at line 71 of file IntersectOp.h.
Member Function Documentation
template<typename Number , typename Converter , typename Setting > std::vector<EvaluationResult<Number> > hypro::IntersectOp< Number, Converter, Setting >::aggregate (std::vector< std::vector< EvaluationResult< Number >>> & resultStackBack, const matrix_t< Number > &) const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 95 of file IntersectOp.h.
References assert(), hypro::EvaluationResult< Number >::errorCode, hypro::FEAS, index, hypro::INFEAS, hypro::INFTY, r, and hypro::EvaluationResult< Number >::supportValue.
template<typename Number , typename Converter , typename Setting > std::vector<EvaluationResult<Number> > hypro::IntersectOp< Number, Converter, Setting >::compute (const matrix_t< Number > & , bool) const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 89 of file IntersectOp.h.
References assert().
template<typename Number , typename Converter , typename Setting > bool hypro::IntersectOp< Number, Converter, Setting >::contains (const std::vector< bool > & v, const vector_t< Number > &) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 232 of file IntersectOp.h.
template<typename Number , typename Converter , typename Setting > bool hypro::IntersectOp< Number, Converter, Setting >::empty (const std::vector< bool > & childrenEmpty) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 173 of file IntersectOp.h.
References defaultTemplateDirectionCount, hypro::EMPTY, hypro::EvaluationResult< Number >::errorCode, hypro::SupportFunctionNewT< Number, Converter, Setting >::evaluate(), hypro::RootGrowNode< Number, Converter, Setting >::getChildren(), i, hypro::INFTY, hypro::IntersectOp< Number, Converter, Setting >::mDimension, hypro::NONEMPTY, hypro::EvaluationResult< Number >::supportValue, and hypro::UNKNOWN.
template<typename Number , typename Converter , typename Setting > RGNData* hypro::IntersectOp< Number, Converter, Setting >::getData () const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 78 of file IntersectOp.h.
template<typename Number , typename Converter , typename Setting > std::size_t hypro::IntersectOp< Number, Converter, Setting >::getDimension () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 77 of file IntersectOp.h.
References hypro::IntersectOp< Number, Converter, Setting >::mDimension.
template<typename Number , typename Converter , typename Setting > unsigned hypro::IntersectOp< Number, Converter, Setting >::getOriginCount () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 76 of file IntersectOp.h.
References hypro::IntersectOp< Number, Converter, Setting >::originCount.
template<typename Number , typename Converter , typename Setting > SFNEW_TYPE hypro::IntersectOp< Number, Converter, Setting >::getType () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 75 of file IntersectOp.h.
References hypro::IntersectOp< Number, Converter, Setting >::type.
template<typename Number , typename Converter , typename Setting > std::vector<std::size_t> hypro::IntersectOp< Number, Converter, Setting >::intersectDims (const std::vector< std::vector< std::size_t >> & dims) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 241 of file IntersectOp.h.
References dims.
template<typename Number , typename Converter , typename Setting > void hypro::IntersectOp< Number, Converter, Setting >::setDimension (const std::size_t d) inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 79 of file IntersectOp.h.
References d.
template<typename Number , typename Converter , typename Setting > Point<Number> hypro::IntersectOp< Number, Converter, Setting >::supremumPoint (std::vector< Point< Number >> & points) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 222 of file IntersectOp.h.
References hypro::Point< Number >::inftyNorm(), and points.
template<typename Number , typename Converter , typename Setting > matrix_t<Number> hypro::IntersectOp< Number, Converter, Setting >::transform (const matrix_t< Number > & param) const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 84 of file IntersectOp.h.
Member Data Documentation
template<typename Number , typename Converter , typename Setting > std::vector<std::shared_ptr<RootGrowNode<Number, Converter, Setting> > > hypro::IntersectOp< Number, Converter, Setting >::mChildren private
Definition at line 33 of file IntersectOp.h.
template<typename Number , typename Converter , typename Setting > std::size_t hypro::IntersectOp< Number, Converter, Setting >::mDimension = 0 private
Definition at line 32 of file IntersectOp.h.
Referenced by hypro::IntersectOp< Number, Converter, Setting >::empty(), and hypro::IntersectOp< Number, Converter, Setting >::getDimension().
template<typename Number , typename Converter , typename Setting > unsigned hypro::IntersectOp< Number, Converter, Setting >::originCount = 2 private
Definition at line 31 of file IntersectOp.h.
Referenced by hypro::IntersectOp< Number, Converter, Setting >::getOriginCount().
template<typename Number , typename Converter , typename Setting > SFNEW_TYPE hypro::IntersectOp< Number, Converter, Setting >::type = SFNEW_TYPE::INTERSECTOP private
Definition at line 30 of file IntersectOp.h.
Referenced by hypro::IntersectOp< Number, Converter, Setting >::getType().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunctionNew/IntersectOp.h