HyPro: hypro::ltiGuardHandler< State > Class Template Reference
hypro::ltiGuardHandler< State > Class Template Reference
#include <forwardDeclarations.h>
Public Member Functions
ltiGuardHandler ()=delete
ltiGuardHandler (std::shared_ptr< State > state, size_t index, Transition< Number > *transition)
void handle ()
const char * handlerName ()
virtual bool satisfiesGuard () override
virtual std::shared_ptr< State > getState () override
virtual void setState (std::shared_ptr< State > ptr) override
void reinitialize ()
virtual double getSortIndex () override
virtual void setSortIndex (double sortIndex) override
virtual bool getMarkedForDelete () override
virtual void setMarkedForDelete (bool toDelete) override
Public Member Functions inherited from hypro::IGuardHandler< State >
virtual ~IGuardHandler ()
Protected Attributes
bool mSatisfies = false
bool mMarkedForDelete = false
std::shared_ptr< State > mGuardSatisfyingState
Transition< Number > * mTransition
size_t mIndex
double mSortIndex
Detailed Description
template<typename State>
class hypro::ltiGuardHandler< State >
Definition at line 32 of file forwardDeclarations.h.
Constructor & Destructor Documentation
template<typename State > hypro::ltiGuardHandler< State >::ltiGuardHandler () delete
template<typename State > hypro::ltiGuardHandler< State >::ltiGuardHandler (std::shared_ptr< State > state, size_t index, Transition< Number > * transition) inline
Definition at line 21 of file ltiGuardHandler.h.
References hypro::ltiGuardHandler< State >::reinitialize().
Member Function Documentation
template<typename State > virtual bool hypro::ltiGuardHandler< State >::getMarkedForDelete () inline override virtual
Implements hypro::IGuardHandler< State >.
Definition at line 42 of file ltiGuardHandler.h.
References hypro::ltiGuardHandler< State >::mMarkedForDelete.
template<typename State > virtual double hypro::ltiGuardHandler< State >::getSortIndex () inline override virtual
Implements hypro::IGuardHandler< State >.
Reimplemented in hypro::timedGuardHandler< State >, and hypro::discreteGuardHandler< State >.
Definition at line 39 of file ltiGuardHandler.h.
References hypro::ltiGuardHandler< State >::mSortIndex.
template<typename State > virtual std::shared_ptr<State> hypro::ltiGuardHandler< State >::getState () inline override virtual
Implements hypro::IGuardHandler< State >.
Definition at line 36 of file ltiGuardHandler.h.
References hypro::ltiGuardHandler< State >::reinitialize().
template<typename State > void hypro::ltiGuardHandler< State >::handle () virtual
Implements hypro::IGuardHandler< State >.
Reimplemented in hypro::timedGuardHandler< State >.
template<typename State > const char* hypro::ltiGuardHandler< State >::handlerName () inline virtual
Implements hypro::IGuardHandler< State >.
Reimplemented in hypro::timedGuardHandler< State >.
Definition at line 33 of file ltiGuardHandler.h.
template<typename State > void hypro::ltiGuardHandler< State >::reinitialize () virtual
Implements hypro::IGuardHandler< State >.
Referenced by hypro::ltiGuardHandler< State >::getState(), hypro::ltiGuardHandler< State >::ltiGuardHandler(), and hypro::ltiGuardHandler< State >::setState().
template<typename State > virtual bool hypro::ltiGuardHandler< State >::satisfiesGuard () inline override virtual
Implements hypro::IGuardHandler< State >.
Definition at line 35 of file ltiGuardHandler.h.
References hypro::ltiGuardHandler< State >::mSatisfies.
template<typename State > virtual void hypro::ltiGuardHandler< State >::setMarkedForDelete (bool toDelete) inline override virtual
Implements hypro::IGuardHandler< State >.
Definition at line 43 of file ltiGuardHandler.h.
References hypro::ltiGuardHandler< State >::mMarkedForDelete.
template<typename State > virtual void hypro::ltiGuardHandler< State >::setSortIndex (double sortIndex) inline override virtual
Implements hypro::IGuardHandler< State >.
Reimplemented in hypro::timedGuardHandler< State >, and hypro::discreteGuardHandler< State >.
Definition at line 40 of file ltiGuardHandler.h.
References hypro::ltiGuardHandler< State >::mSortIndex.
template<typename State > virtual void hypro::ltiGuardHandler< State >::setState (std::shared_ptr< State > ptr) inline override virtual
Implements hypro::IGuardHandler< State >.
Definition at line 37 of file ltiGuardHandler.h.
References hypro::ltiGuardHandler< State >::reinitialize().
Member Data Documentation
template<typename State > std::shared_ptr<State> hypro::ltiGuardHandler< State >::mGuardSatisfyingState protected
Definition at line 13 of file ltiGuardHandler.h.
template<typename State > size_t hypro::ltiGuardHandler< State >::mIndex protected
Definition at line 16 of file ltiGuardHandler.h.
template<typename State > bool hypro::ltiGuardHandler< State >::mMarkedForDelete = false protected
Definition at line 12 of file ltiGuardHandler.h.
Referenced by hypro::ltiGuardHandler< State >::getMarkedForDelete(), and hypro::ltiGuardHandler< State >::setMarkedForDelete().
template<typename State > bool hypro::ltiGuardHandler< State >::mSatisfies = false protected
Definition at line 11 of file ltiGuardHandler.h.
Referenced by hypro::ltiGuardHandler< State >::satisfiesGuard().
template<typename State > double hypro::ltiGuardHandler< State >::mSortIndex protected
Definition at line 17 of file ltiGuardHandler.h.
Referenced by hypro::ltiGuardHandler< State >::getSortIndex(), and hypro::ltiGuardHandler< State >::setSortIndex().
template<typename State > Transition<Number>* hypro::ltiGuardHandler< State >::mTransition protected
Definition at line 14 of file ltiGuardHandler.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/forwardDeclarations.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/guardHandlers/ltiGuardHandler.h