HyPro: hypro::rectangularGuardHandler< State > Class Template Reference
hypro::rectangularGuardHandler< State > Class Template Reference
#include <forwardDeclarations.h>
Public Member Functions
rectangularGuardHandler ()=delete
rectangularGuardHandler (std::shared_ptr< State > state, size_t index, Transition< Number > *transition)
void handle ()
const char * handlerName ()
virtual bool satisfiesGuard () override
virtual std::shared_ptr< State > getState () override
virtual void setState (std::shared_ptr< State > ptr) override
void reinitialize ()
virtual double getSortIndex () override
virtual void setSortIndex (double sortIndex) override
virtual bool getMarkedForDelete () override
virtual void setMarkedForDelete (bool toDelete) override
Public Member Functions inherited from hypro::IGuardHandler< State >
virtual ~IGuardHandler ()
Protected Attributes
CONTAINMENT mContainment = CONTAINMENT::NO
bool mMarkedForDelete = false
std::shared_ptr< State > mState
Transition< Number > * mTransition
size_t mIndex
double mSortIndex
Private Types
using Number = typename State::NumberType
Detailed Description
template<typename State>
class hypro::rectangularGuardHandler< State >
Definition at line 40 of file forwardDeclarations.h.
Member Typedef Documentation
template<typename State > using hypro::rectangularGuardHandler< State >::Number = typename State::NumberType private
Definition at line 8 of file rectangularGuardHandler.h.
Constructor & Destructor Documentation
template<typename State > hypro::rectangularGuardHandler< State >::rectangularGuardHandler () delete
template<typename State > hypro::rectangularGuardHandler< State >::rectangularGuardHandler (std::shared_ptr< State > state, size_t index, Transition< Number > * transition) inline
Definition at line 21 of file rectangularGuardHandler.h.
References hypro::Decomposition::at(), hypro::SettingsProvider< State >::getSubspaceDecomposition(), and hypro::rectangularGuardHandler< State >::handle().
Member Function Documentation
template<typename State > virtual bool hypro::rectangularGuardHandler< State >::getMarkedForDelete () inline override virtual
Implements hypro::IGuardHandler< State >.
Definition at line 42 of file rectangularGuardHandler.h.
References hypro::rectangularGuardHandler< State >::mMarkedForDelete.
template<typename State > virtual double hypro::rectangularGuardHandler< State >::getSortIndex () inline override virtual
Implements hypro::IGuardHandler< State >.
Definition at line 39 of file rectangularGuardHandler.h.
References hypro::rectangularGuardHandler< State >::mSortIndex.
template<typename State > virtual std::shared_ptr<State> hypro::rectangularGuardHandler< State >::getState () inline override virtual
Implements hypro::IGuardHandler< State >.
Definition at line 36 of file rectangularGuardHandler.h.
References hypro::rectangularGuardHandler< State >::mState.
template<typename State > void hypro::rectangularGuardHandler< State >::handle () virtual
Implements hypro::IGuardHandler< State >.
Referenced by hypro::rectangularGuardHandler< State >::rectangularGuardHandler().
template<typename State > const char* hypro::rectangularGuardHandler< State >::handlerName () inline virtual
Implements hypro::IGuardHandler< State >.
Definition at line 33 of file rectangularGuardHandler.h.
template<typename State > void hypro::rectangularGuardHandler< State >::reinitialize () virtual
Implements hypro::IGuardHandler< State >.
Referenced by hypro::rectangularGuardHandler< State >::setState().
template<typename State > virtual bool hypro::rectangularGuardHandler< State >::satisfiesGuard () inline override virtual
Implements hypro::IGuardHandler< State >.
Definition at line 35 of file rectangularGuardHandler.h.
References hypro::NO.
template<typename State > virtual void hypro::rectangularGuardHandler< State >::setMarkedForDelete (bool toDelete) inline override virtual
Implements hypro::IGuardHandler< State >.
Definition at line 43 of file rectangularGuardHandler.h.
template<typename State > virtual void hypro::rectangularGuardHandler< State >::setSortIndex (double sortIndex) inline override virtual
Implements hypro::IGuardHandler< State >.
Definition at line 40 of file rectangularGuardHandler.h.
template<typename State > virtual void hypro::rectangularGuardHandler< State >::setState (std::shared_ptr< State > ptr) inline override virtual
Implements hypro::IGuardHandler< State >.
Definition at line 37 of file rectangularGuardHandler.h.
References hypro::rectangularGuardHandler< State >::reinitialize().
Member Data Documentation
template<typename State > CONTAINMENT hypro::rectangularGuardHandler< State >::mContainment = CONTAINMENT::NO protected
Definition at line 11 of file rectangularGuardHandler.h.
template<typename State > size_t hypro::rectangularGuardHandler< State >::mIndex protected
Definition at line 16 of file rectangularGuardHandler.h.
template<typename State > bool hypro::rectangularGuardHandler< State >::mMarkedForDelete = false protected
Definition at line 12 of file rectangularGuardHandler.h.
Referenced by hypro::rectangularGuardHandler< State >::getMarkedForDelete().
template<typename State > double hypro::rectangularGuardHandler< State >::mSortIndex protected
Definition at line 17 of file rectangularGuardHandler.h.
Referenced by hypro::rectangularGuardHandler< State >::getSortIndex().
template<typename State > std::shared_ptr<State> hypro::rectangularGuardHandler< State >::mState protected
Definition at line 13 of file rectangularGuardHandler.h.
Referenced by hypro::rectangularGuardHandler< State >::getState().
template<typename State > Transition<Number>* hypro::rectangularGuardHandler< State >::mTransition protected
Definition at line 14 of file rectangularGuardHandler.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/forwardDeclarations.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/guardHandlers/rectangularGuardHandler.h