HyPro: hypro::NonLinearOmega0Supportfunction< Setting > Class Template Reference
hypro::NonLinearOmega0Supportfunction< Setting > Class Template Reference
#include <NonLinearOmega0Supportfunction.h>
Public Member Functions
SupportFunctionContent * getEpsilonpsi ()
NonLinearOmega0Supportfunction (matrix_t< double > *A, SupportFunctionContent *V, SupportFunctionContent *X0, double delta, artificialDirections *aD)
~NonLinearOmega0Supportfunction ()
Public Member Functions inherited from hypro::SupportFunctionContent< Number, Setting >
virtual ~SupportFunctionContent ()
std::shared_ptr< SupportFunctionContent< Number, Setting > > & operator= (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &_orig)
EvaluationResult< Number > evaluate (const vector_t< Number > &_direction, bool useExact) const
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &_directions, bool useExact) const
std::size_t dimension () const
SF_TYPE type () const
unsigned depth () const
unsigned operationCount () const
std::shared_ptr< SupportFunctionContent< Number, Setting > > getThis () const
unsigned multiplicationsPerEvaluation () const
void forceLinTransReduction ()
Point< Number > supremumPoint () const
std::vector< std::size_t > collectProjections () const
std::vector< std::size_t > collectProjectionsIterative () const
sumContent< Number, Setting > * summands () const
scaleContent< Number, Setting > * scaleParameters () const
trafoContent< Number, Setting > * linearTrafoParameters () const
unionContent< Number, Setting > * unionParameters () const
intersectionContent< Number, Setting > * intersectionParameters () const
projectionContent< Number, Setting > * projectionParameters () const
PolytopeSupportFunction< Number, Setting > * polytope () const
BoxSupportFunction< Number, Setting > * box () const
BallSupportFunction< Number > * ball () const
EllipsoidSupportFunction< Number > * ellipsoid () const
std::shared_ptr< SupportFunctionContent< Number, Setting > > project (const std::vector< std::size_t > &dimensions) const
std::shared_ptr< SupportFunctionContent< Number, Setting > > affineTransformation (const matrix_t< Number > &A, const vector_t< Number > &b) const
std::shared_ptr< SupportFunctionContent< Number, Setting > > minkowskiSum (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &_rhs) const
std::shared_ptr< SupportFunctionContent< Number, Setting > > intersect (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &_rhs) const
bool contains (const Point< Number > &_point) const
bool contains (const vector_t< Number > &_point) const
std::shared_ptr< SupportFunctionContent< Number, Setting > > unite (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &_rhs) const
std::shared_ptr< SupportFunctionContent< Number, Setting > > scale (const Number &_factor=1) const
void reduceRepresentation ()
bool empty () const
void cleanUp () const
void print () const
bool checkTreeValidity () const
std::size_t getDotRepresentation (std::size_t startIndex, std::string &nodes, std::string &transitions) const
Protected Member Functions
evaluationResult specificEvaluation (matrix_t< double > l)
Private Member Functions
SymmetricCenteredBoxSupportFunction< BoxSupportFunctionSetting > * boxoperator (SupportFunctionContent *sf)
matrix_t< double > calcvalues (matrix_t< double > *A, unsigned int i, unsigned int j, unsigned int k, unsigned int l)
void calcepsilon ()
Static Private Member Functions
static double myfunc (unsigned n, const double *x, double *grad, void *my_func_data)
Private Attributes
unsigned int dimensions
matrix_t< double > * A
SupportFunctionContent * V
SupportFunctionContent * X0
double delta
matrix_t< double > absA
matrix_t< double > edA
matrix_t< double > phi2
SupportFunctionContent * epsilonpsi
SupportFunctionContent * edX0
matrix_t< double > e_p
matrix_t< double > e_n
std::vector< matrix_t< double > > directionsAlongDimensions
evaluationResult x0res
evaluationResult edX0res
evaluationResult Vres
evaluationResult epsilonpsires
matrix_t< double > absl
Additional Inherited Members
Static Public Member Functions inherited from hypro::SupportFunctionContent< Number, Setting >
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE _type, matrix_t< Number > _shapeMatrix)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE _type, Number _radius, unsigned dimension)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE _type, const matrix_t< Number > &_directions, const vector_t< Number > &_distances, bool overrideReduction=false)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE _type, const std::vector< carl::Interval< Number >> &inbox)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE _type, const std::vector< Halfspace< Number >> &_planes)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE _type, const std::vector< Point< Number >> &_points)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE type, const std::shared_ptr< SupportFunctionContent< Number, Setting >> &lhs, const std::shared_ptr< SupportFunctionContent< Number, Setting >> &rhs)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (SF_TYPE type, const std::vector< std::shared_ptr< SupportFunctionContent< Number, Setting >>> &rhs)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &orig, const matrix_t< Number > &constraints, const vector_t< Number > &constants)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &orig, Number factor)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &orig, const std::vector< std::size_t > &dimensions)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > create (const std::shared_ptr< SupportFunctionContent< Number, Setting >> &orig)
static std::shared_ptr< SupportFunctionContent< Number, Setting > > unite (const std::vector< std::shared_ptr< SupportFunctionContent< Number, Setting >>> &_rhs)
Detailed Description
template<class Setting>
class hypro::NonLinearOmega0Supportfunction< Setting >
Definition at line 26 of file NonLinearOmega0Supportfunction.h.
Constructor & Destructor Documentation
template<class Setting > hypro::NonLinearOmega0Supportfunction< Setting >::NonLinearOmega0Supportfunction (matrix_t< double > * A, SupportFunctionContent * V, SupportFunctionContent * X0, double delta, artificialDirections * aD) inline
Definition at line 393 of file NonLinearOmega0Supportfunction.h.
References hypro::NonLinearOmega0Supportfunction< Setting >::A, hypro::NonLinearOmega0Supportfunction< Setting >::calcepsilon(), hypro::NonLinearOmega0Supportfunction< Setting >::calcvalues(), hypro::NonLinearOmega0Supportfunction< Setting >::delta, method(), string(), temp, hypro::NonLinearOmega0Supportfunction< Setting >::V, and hypro::NonLinearOmega0Supportfunction< Setting >::X0.
template<class Setting > hypro::NonLinearOmega0Supportfunction< Setting >::~NonLinearOmega0Supportfunction () inline
Definition at line 451 of file NonLinearOmega0Supportfunction.h.
References hypro::NonLinearOmega0Supportfunction< Setting >::edX0, and hypro::NonLinearOmega0Supportfunction< Setting >::epsilonpsi.
Member Function Documentation
template<class Setting > SymmetricCenteredBoxSupportFunction<BoxSupportFunctionSetting>* hypro::NonLinearOmega0Supportfunction< Setting >::boxoperator (SupportFunctionContent * sf) inline private
Definition at line 53 of file NonLinearOmega0Supportfunction.h.
References b, hypro::NonLinearOmega0Supportfunction< Setting >::dimensions, hypro::SupportFunctionContent< Number, Setting >::evaluate(), i, l1, l2, max, method(), hypro::SupportFunctionContent< Number, Setting >::multiEvaluate(), string(), and values().
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::calcepsilon().
template<class Setting > void hypro::NonLinearOmega0Supportfunction< Setting >::calcepsilon () inline private
Definition at line 172 of file NonLinearOmega0Supportfunction.h.
References hypro::NonLinearOmega0Supportfunction< Setting >::boxoperator(), method(), string(), and temp.
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::NonLinearOmega0Supportfunction().
template<class Setting > matrix_t<double> hypro::NonLinearOmega0Supportfunction< Setting >::calcvalues (matrix_t< double > * A, unsigned int i, unsigned int j, unsigned int k, unsigned int l) inline private
Definition at line 111 of file NonLinearOmega0Supportfunction.h.
References hypro::NonLinearOmega0Supportfunction< Setting >::delta, hypro::NonLinearOmega0Supportfunction< Setting >::dimensions, method(), string(), and temp.
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::NonLinearOmega0Supportfunction().
template<class Setting > SupportFunctionContent* hypro::NonLinearOmega0Supportfunction< Setting >::getEpsilonpsi () inline
Definition at line 382 of file NonLinearOmega0Supportfunction.h.
References hypro::NonLinearOmega0Supportfunction< Setting >::epsilonpsi.
template<class Setting > static double hypro::NonLinearOmega0Supportfunction< Setting >::myfunc (unsigned n, const double * x, double * grad, void * my_func_data) inline static private
Definition at line 265 of file NonLinearOmega0Supportfunction.h.
References i, and res.
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::specificEvaluation().
template<class Setting > evaluationResult hypro::NonLinearOmega0Supportfunction< Setting >::specificEvaluation (matrix_t< double > l) inline protected
This method computes the evaluation result for a specified direction l TODO: optimization object can be declared and initialized outside the evaluate methods to improve performance (see glpk)
Definition at line 305 of file NonLinearOmega0Supportfunction.h.
References hypro::SupportFunctionContent< Number, Setting >::evaluate(), l, method(), hypro::NonLinearOmega0Supportfunction< Setting >::myfunc(), string(), and x.
Member Data Documentation
template<class Setting > matrix_t<double>* hypro::NonLinearOmega0Supportfunction< Setting >::A private
Definition at line 32 of file NonLinearOmega0Supportfunction.h.
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::NonLinearOmega0Supportfunction().
template<class Setting > matrix_t<double> hypro::NonLinearOmega0Supportfunction< Setting >::absA private
Definition at line 39 of file NonLinearOmega0Supportfunction.h.
template<class Setting > matrix_t<double> hypro::NonLinearOmega0Supportfunction< Setting >::absl private
Definition at line 261 of file NonLinearOmega0Supportfunction.h.
template<class Setting > double hypro::NonLinearOmega0Supportfunction< Setting >::delta private
Definition at line 36 of file NonLinearOmega0Supportfunction.h.
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::calcvalues(), and hypro::NonLinearOmega0Supportfunction< Setting >::NonLinearOmega0Supportfunction().
template<class Setting > unsigned int hypro::NonLinearOmega0Supportfunction< Setting >::dimensions private
Definition at line 29 of file NonLinearOmega0Supportfunction.h.
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::boxoperator(), and hypro::NonLinearOmega0Supportfunction< Setting >::calcvalues().
template<class Setting > std::vector<matrix_t<double> > hypro::NonLinearOmega0Supportfunction< Setting >::directionsAlongDimensions private
Definition at line 48 of file NonLinearOmega0Supportfunction.h.
template<class Setting > matrix_t<double> hypro::NonLinearOmega0Supportfunction< Setting >::e_n private
Definition at line 45 of file NonLinearOmega0Supportfunction.h.
template<class Setting > matrix_t<double> hypro::NonLinearOmega0Supportfunction< Setting >::e_p private
Definition at line 44 of file NonLinearOmega0Supportfunction.h.
template<class Setting > matrix_t<double> hypro::NonLinearOmega0Supportfunction< Setting >::edA private
Definition at line 40 of file NonLinearOmega0Supportfunction.h.
template<class Setting > SupportFunctionContent* hypro::NonLinearOmega0Supportfunction< Setting >::edX0 private
Definition at line 43 of file NonLinearOmega0Supportfunction.h.
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::~NonLinearOmega0Supportfunction().
template<class Setting > evaluationResult hypro::NonLinearOmega0Supportfunction< Setting >::edX0res private
Definition at line 258 of file NonLinearOmega0Supportfunction.h.
template<class Setting > SupportFunctionContent* hypro::NonLinearOmega0Supportfunction< Setting >::epsilonpsi private
Definition at line 42 of file NonLinearOmega0Supportfunction.h.
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::getEpsilonpsi(), and hypro::NonLinearOmega0Supportfunction< Setting >::~NonLinearOmega0Supportfunction().
template<class Setting > evaluationResult hypro::NonLinearOmega0Supportfunction< Setting >::epsilonpsires private
Definition at line 260 of file NonLinearOmega0Supportfunction.h.
template<class Setting > matrix_t<double> hypro::NonLinearOmega0Supportfunction< Setting >::phi2 private
Definition at line 41 of file NonLinearOmega0Supportfunction.h.
template<class Setting > SupportFunctionContent* hypro::NonLinearOmega0Supportfunction< Setting >::V private
Definition at line 33 of file NonLinearOmega0Supportfunction.h.
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::NonLinearOmega0Supportfunction().
template<class Setting > evaluationResult hypro::NonLinearOmega0Supportfunction< Setting >::Vres private
Definition at line 259 of file NonLinearOmega0Supportfunction.h.
template<class Setting > SupportFunctionContent* hypro::NonLinearOmega0Supportfunction< Setting >::X0 private
Definition at line 34 of file NonLinearOmega0Supportfunction.h.
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::NonLinearOmega0Supportfunction().
template<class Setting > evaluationResult hypro::NonLinearOmega0Supportfunction< Setting >::x0res private
Definition at line 257 of file NonLinearOmega0Supportfunction.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunction/NonLinearOmega0Supportfunction.h