HyPro: hypro::Leaf< Number, Converter, Setting, Representation > Class Template Reference
hypro::Leaf< Number, Converter, Setting, Representation > Class Template Reference
#include <Leaf.h>
Public Member Functions
Leaf ()=delete
Leaf (Representation &r)
Leaf (const std::shared_ptr< Representation > &ptr)
Leaf (const LeafData &d)
~Leaf ()
SFNEW_TYPE getType () const override
unsigned getOriginCount () const override
std::size_t getDimension () const override
Representation * getRepresentation () const
bool isRedundant () const
RGNData * getData () const override
LeafData getLeafData () const override
void setDimension (const std::size_t d) override
void print (std::ostream &ostr) const override
matrix_t< Number > transform (const matrix_t< Number > &) const override
std::vector< EvaluationResult< Number > > compute (const matrix_t< Number > &param, bool useExact) const override
std::vector< EvaluationResult< Number > > aggregate (std::vector< std::vector< EvaluationResult< Number >>> &, const matrix_t< Number > &) const override
bool empty () const override
Point< Number > supremumPoint () const override
bool contains (const vector_t< Number > &point) const override
Public Member Functions inherited from hypro::RootGrowNode< Number, Converter, Setting >
RootGrowNode ()
virtual ~RootGrowNode ()
virtual PointerVec getChildren () const
virtual PointerVec & rGetChildren ()
virtual SETSTATE isEmpty () const
void addToChildren (const std::shared_ptr< RootGrowNode > &rhs)
void clearChildren ()
virtual bool empty (const std::vector< bool > &) const
virtual Point< Number > supremumPoint (std::vector< Point< Number >> &) const
virtual vector_t< Number > reverseOp (const vector_t< Number > &point) const
virtual bool contains (const std::vector< bool > &, const vector_t< Number > &) const
virtual std::vector< std::size_t > intersectDims (const std::vector< std::vector< std::size_t >> &dims) const
Private Attributes
SFNEW_TYPE type = SFNEW_TYPE::LEAF
unsigned originCount = 0
std::size_t mDimension = 0
std::shared_ptr< Representation > rep
bool isNotRedundant = false
Additional Inherited Members
Public Types inherited from hypro::RootGrowNode< Number, Converter, Setting >
using PointerVec = std::vector< std::shared_ptr< RootGrowNode< Number, Converter, Setting >>>
Protected Attributes inherited from hypro::RootGrowNode< Number, Converter, Setting >
SFNEW_TYPE mType = NODE
unsigned originCount = 0
PointerVec mChildren = PointerVec()
std::size_t mDimension = 0
SETSTATE mEmptyState = SETSTATE::UNKNOWN
Detailed Description
template<typename Number, typename Converter, typename Setting, typename Representation>
class hypro::Leaf< Number, Converter, Setting, Representation >
Definition at line 35 of file Leaf.h.
Constructor & Destructor Documentation
template<typename Number , typename Converter , typename Setting , typename Representation > hypro::Leaf< Number, Converter, Setting, Representation >::Leaf () delete
template<typename Number , typename Converter , typename Setting , typename Representation > hypro::Leaf< Number, Converter, Setting, Representation >::Leaf (Representation & r) inline
Definition at line 57 of file Leaf.h.
template<typename Number , typename Converter , typename Setting , typename Representation > hypro::Leaf< Number, Converter, Setting, Representation >::Leaf (const std::shared_ptr< Representation > & ptr) inline
Definition at line 61 of file Leaf.h.
template<typename Number , typename Converter , typename Setting , typename Representation > hypro::Leaf< Number, Converter, Setting, Representation >::Leaf (const LeafData & d) inline
Definition at line 65 of file Leaf.h.
References hypro::LeafData::addressToRep, assert(), hypro::LeafData::isNotRedundant, type, and hypro::LeafData::typeOfRep.
template<typename Number , typename Converter , typename Setting , typename Representation > hypro::Leaf< Number, Converter, Setting, Representation >::~Leaf () inline
Definition at line 74 of file Leaf.h.
Member Function Documentation
template<typename Number , typename Converter , typename Setting , typename Representation > std::vector<EvaluationResult<Number> > hypro::Leaf< Number, Converter, Setting, Representation >::aggregate (std::vector< std::vector< EvaluationResult< Number >>> & , const matrix_t< Number > &) const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 125 of file Leaf.h.
References assert().
template<typename Number , typename Converter , typename Setting , typename Representation > std::vector<EvaluationResult<Number> > hypro::Leaf< Number, Converter, Setting, Representation >::compute (const matrix_t< Number > & param, bool useExact) const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 110 of file Leaf.h.
References assert().
template<typename Number , typename Converter , typename Setting , typename Representation > bool hypro::Leaf< Number, Converter, Setting, Representation >::contains (const vector_t< Number > & point) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 148 of file Leaf.h.
template<typename Number , typename Converter , typename Setting , typename Representation > bool hypro::Leaf< Number, Converter, Setting, Representation >::empty () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 131 of file Leaf.h.
References hypro::EMPTY, hypro::RootGrowNode< Number, Converter, Setting >::empty(), hypro::NONEMPTY, and hypro::UNKNOWN.
template<typename Number , typename Converter , typename Setting , typename Representation > RGNData* hypro::Leaf< Number, Converter, Setting, Representation >::getData () const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 83 of file Leaf.h.
template<typename Number , typename Converter , typename Setting , typename Representation > std::size_t hypro::Leaf< Number, Converter, Setting, Representation >::getDimension () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 80 of file Leaf.h.
template<typename Number , typename Converter , typename Setting , typename Representation > LeafData hypro::Leaf< Number, Converter, Setting, Representation >::getLeafData () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 84 of file Leaf.h.
References hypro::LeafData::isNotRedundant, and hypro::LeafData::LeafData().
template<typename Number , typename Converter , typename Setting , typename Representation > unsigned hypro::Leaf< Number, Converter, Setting, Representation >::getOriginCount () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 79 of file Leaf.h.
template<typename Number , typename Converter , typename Setting , typename Representation > Representation* hypro::Leaf< Number, Converter, Setting, Representation >::getRepresentation () const inline
Definition at line 81 of file Leaf.h.
template<typename Number , typename Converter , typename Setting , typename Representation > SFNEW_TYPE hypro::Leaf< Number, Converter, Setting, Representation >::getType () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 78 of file Leaf.h.
References type.
template<typename Number , typename Converter , typename Setting , typename Representation > bool hypro::Leaf< Number, Converter, Setting, Representation >::isRedundant () const inline
Definition at line 82 of file Leaf.h.
References hypro::LeafData::isNotRedundant.
template<typename Number , typename Converter , typename Setting , typename Representation > void hypro::Leaf< Number, Converter, Setting, Representation >::print (std::ostream & ostr) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 91 of file Leaf.h.
References hypro::detail::getType().
template<typename Number , typename Converter , typename Setting , typename Representation > void hypro::Leaf< Number, Converter, Setting, Representation >::setDimension (const std::size_t d) inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 87 of file Leaf.h.
References d.
template<typename Number , typename Converter , typename Setting , typename Representation > Point<Number> hypro::Leaf< Number, Converter, Setting, Representation >::supremumPoint () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 139 of file Leaf.h.
References hypro::Point< Number >::inftyNorm(), max, point, and hypro::Point< Number >::Zero().
template<typename Number , typename Converter , typename Setting , typename Representation > matrix_t<Number> hypro::Leaf< Number, Converter, Setting, Representation >::transform (const matrix_t< Number > &) const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 104 of file Leaf.h.
References assert().
Member Data Documentation
template<typename Number , typename Converter , typename Setting , typename Representation > bool hypro::Leaf< Number, Converter, Setting, Representation >::isNotRedundant = false mutable private
Definition at line 50 of file Leaf.h.
template<typename Number , typename Converter , typename Setting , typename Representation > std::size_t hypro::Leaf< Number, Converter, Setting, Representation >::mDimension = 0 private
Definition at line 41 of file Leaf.h.
template<typename Number , typename Converter , typename Setting , typename Representation > unsigned hypro::Leaf< Number, Converter, Setting, Representation >::originCount = 0 private
Definition at line 40 of file Leaf.h.
template<typename Number , typename Converter , typename Setting , typename Representation > std::shared_ptr<Representation> hypro::Leaf< Number, Converter, Setting, Representation >::rep private
Definition at line 47 of file Leaf.h.
template<typename Number , typename Converter , typename Setting , typename Representation > SFNEW_TYPE hypro::Leaf< Number, Converter, Setting, Representation >::type = SFNEW_TYPE::LEAF private
Definition at line 39 of file Leaf.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunctionNew/Leaf.h