HyPro: hypro::Optimizer< Number > Class Template Reference
hypro::Optimizer< Number > Class Template Reference
Wrapper class for linear optimization.
#include <Optimizer.h>
Public Member Functions
Optimizer (bool max=true)
Default constructor.
Optimizer (Optimizer< Number > &&orig)
Optimizer (const Optimizer< Number > &orig)
Optimizer (const matrix_t< Number > &constraints, const vector_t< Number > &constants, bool max=true)
Constructor which sets the problem.
~Optimizer ()
Destroys the object.
void cleanContexts ()
SOLUTION getLastConsistencyAnswer () const
bool getConsistencyChecked () const
const std::map< std::thread::id, glpk_context > & getGLPContexts () const
const std::map< std::thread::id, clp_context > & getCLPContexts () const
Optimizer< Number > & operator= (const Optimizer< Number > &orig)
Copy Assign operator.
const matrix_t< Number > & matrix () const
Returns the problem matrix.
const vector_t< Number > & vector () const
Returns the problem constants as a vector.
void setMatrix (const matrix_t< Number > &_matrix)
Sets the problem matrix.
void setVector (const vector_t< Number > &_vector)
Sets the problem vector.
void setRelations (const std::vector< carl::Relation > &rels)
Set the Relations for all constraints.
void setMaximize (bool max)
Set the Maximize flag to new value to switch between maximizing and minimizing.
void addConstraint (const vector_t< Number > &constraint, Number constantPart, carl::Relation rel)
Add an equality constraint.
void setRelation (carl::Relation rel, std::size_t pos)
Set the Relation for the constraint at position pos.
void clear ()
Clears the problem instance.
EvaluationResult< Number > evaluate (const vector_t< Number > &_direction, bool useExactGlpk) const
Performs linear optimization in the given direction.
bool checkConsistency () const
Checks consistency (i.e. existence of a solution) of the current problem instance.
bool checkPoint (const Point< Number > &_point) const
Checks whether the given point lies inside the satisfiable solution space of the current problem.
EvaluationResult< Number > getInternalPoint () const
Gets some point being a possible solution.
std::vector< std::size_t > redundantConstraints () const
Determines the set of redundant constraints.
Private Member Functions
bool isSane () const
void initialize () const
Calls required initialization methods.
void updateConstraints () const
Updates problem instances.
void clearCache () const
clears the cache of computed solutions.
Private Attributes
matrix_t< Number > mConstraintMatrix
vector_t< Number > mConstraintVector
bool mConsistencyChecked = false
SOLUTION mLastConsistencyAnswer = SOLUTION::UNKNOWN
bool maximize = true
std::vector< carl::Relation > mRelationSymbols
smtrat::SimplexSolver mSmtratSolver
smtrat::FormulaT mCurrentFormula
std::unordered_map< smtrat::FormulaT, std::size_t > mFormulaMapping
unsigned fileCounter
std::string filenamePrefix = "optimizer_error_out_"
std::mutex mContextLock
std::map< std::thread::id, glpk_context > mGlpkContexts
std::map< std::thread::id, clp_context > mClpContexts
Static Private Attributes
static bool warnInexact = false
Friends
void swap (Optimizer< Number > &lhs, Optimizer< Number > &rhs)
Detailed Description
template<typename Number>
class hypro::Optimizer< Number >
Wrapper class for linear optimization.
Template Parameters
Number The used number type.
Definition at line 48 of file Optimizer.h.
Constructor & Destructor Documentation
template<typename Number> hypro::Optimizer< Number >::Optimizer (bool max = true) inline explicit
Default constructor.
Definition at line 83 of file Optimizer.h.
References name, and string().
template<typename Number> hypro::Optimizer< Number >::Optimizer (Optimizer< Number > && orig)
template<typename Number> hypro::Optimizer< Number >::Optimizer (const Optimizer< Number > & orig)
template<typename Number> hypro::Optimizer< Number >::Optimizer (const matrix_t< Number > & constraints, const vector_t< Number > & constants, bool max = true) inline
Constructor which sets the problem.
Parameters
[in] constraints The constraints.
[in] constants The constants.
Definition at line 121 of file Optimizer.h.
References assert().
template<typename Number> hypro::Optimizer< Number >::~Optimizer () inline
Destroys the object.
Definition at line 139 of file Optimizer.h.
References hypro::Optimizer< Number >::cleanContexts().
Member Function Documentation
template<typename Number> void hypro::Optimizer< Number >::addConstraint (const vector_t< Number > & constraint, Number constantPart, carl::Relation rel)
Add an equality constraint.
Parameters
constraint
constantPart
template<typename Number> bool hypro::Optimizer< Number >::checkConsistency () const
Checks consistency (i.e. existence of a solution) of the current problem instance.
Returns
True, if there exists a solution, false otherwise.
template<typename Number> bool hypro::Optimizer< Number >::checkPoint (const Point< Number > & _point) const
Checks whether the given point lies inside the satisfiable solution space of the current problem.
Parameters
[in] _point The point.
Returns
True, if the point satisfies all constraints, false otherwise.
template<typename Number> void hypro::Optimizer< Number >::cleanContexts ()
Referenced by hypro::Optimizer< Number >::~Optimizer().
template<typename Number> void hypro::Optimizer< Number >::clear ()
Clears the problem instance.
template<typename Number> void hypro::Optimizer< Number >::clearCache () const private
clears the cache of computed solutions.
template<typename Number> EvaluationResult<Number> hypro::Optimizer< Number >::evaluate (const vector_t< Number > & _direction, bool useExactGlpk) const
Performs linear optimization in the given direction.
Parameters
[in] _direction The direction.
[in] useExactGlpk The use exact glpk property. If set, glpk is used in its exact mode.
Returns
A struct holding the linear optimization result.
template<typename Number> const std::map<std::thread::id, clp_context>& hypro::Optimizer< Number >::getCLPContexts () const inline
Definition at line 155 of file Optimizer.h.
References hypro::Optimizer< Number >::mClpContexts.
template<typename Number> bool hypro::Optimizer< Number >::getConsistencyChecked () const inline
Definition at line 147 of file Optimizer.h.
References hypro::Optimizer< Number >::mConsistencyChecked.
template<typename Number> const std::map<std::thread::id, glpk_context>& hypro::Optimizer< Number >::getGLPContexts () const inline
Definition at line 150 of file Optimizer.h.
References hypro::Optimizer< Number >::mGlpkContexts.
template<typename Number> EvaluationResult<Number> hypro::Optimizer< Number >::getInternalPoint () const
Gets some point being a possible solution.
Returns
The internal point.
template<typename Number> SOLUTION hypro::Optimizer< Number >::getLastConsistencyAnswer () const inline
Definition at line 146 of file Optimizer.h.
References hypro::Optimizer< Number >::mLastConsistencyAnswer.
template<typename Number> void hypro::Optimizer< Number >::initialize () const private
Calls required initialization methods.
template<typename Number> bool hypro::Optimizer< Number >::isSane () const private
template<typename Number> const matrix_t<Number>& hypro::Optimizer< Number >::matrix () const
Returns the problem matrix.
Returns
The problem matrix (row-wise constraints).
template<typename Number> Optimizer<Number>& hypro::Optimizer< Number >::operator= (const Optimizer< Number > & orig)
Copy Assign operator.
Parameters
[in] orig The right-hand-side object.
Returns
A reference to the the current object with the values of orig.
template<typename Number> std::vector<std::size_t> hypro::Optimizer< Number >::redundantConstraints () const
Determines the set of redundant constraints.
A constraint is redundant, whenever the removal of this constraint does not modify the set of possible solutions.
Returns
A vector of row-indices which represent redundant constraints.
Referenced by main().
template<typename Number> void hypro::Optimizer< Number >::setMatrix (const matrix_t< Number > & _matrix)
Sets the problem matrix.
Parameters
[in] _matrix The matrix.
Referenced by main().
template<typename Number> void hypro::Optimizer< Number >::setMaximize (bool max)
Set the Maximize flag to new value to switch between maximizing and minimizing.
Parameters
max The new flag value (true = maximize, false = minimize).
template<typename Number> void hypro::Optimizer< Number >::setRelation (carl::Relation rel, std::size_t pos)
Set the Relation for the constraint at position pos.
Parameters
pos
template<typename Number> void hypro::Optimizer< Number >::setRelations (const std::vector< carl::Relation > & rels)
Set the Relations for all constraints.
Parameters
rels
template<typename Number> void hypro::Optimizer< Number >::setVector (const vector_t< Number > & _vector)
Sets the problem vector.
Parameters
[in] _vector The vector.
Referenced by main().
template<typename Number> void hypro::Optimizer< Number >::updateConstraints () const private
Updates problem instances.
template<typename Number> const vector_t<Number>& hypro::Optimizer< Number >::vector () const
Returns the problem constants as a vector.
Returns
The vector of constants.
Friends And Related Function Documentation
template<typename Number> void swap (Optimizer< Number > & lhs, Optimizer< Number > & rhs) friend
Definition at line 160 of file Optimizer.h.
Member Data Documentation
template<typename Number> unsigned hypro::Optimizer< Number >::fileCounter mutable private
Definition at line 65 of file Optimizer.h.
template<typename Number> std::string hypro::Optimizer< Number >::filenamePrefix = "optimizer_error_out_" private
Definition at line 66 of file Optimizer.h.
template<typename Number> bool hypro::Optimizer< Number >::maximize = true private
Definition at line 56 of file Optimizer.h.
template<typename Number> std::map<std::thread::id, clp_context> hypro::Optimizer< Number >::mClpContexts mutable private
Definition at line 76 of file Optimizer.h.
Referenced by hypro::Optimizer< Number >::getCLPContexts().
template<typename Number> bool hypro::Optimizer< Number >::mConsistencyChecked = false mutable private
Definition at line 53 of file Optimizer.h.
Referenced by hypro::Optimizer< Number >::getConsistencyChecked().
template<typename Number> matrix_t<Number> hypro::Optimizer< Number >::mConstraintMatrix private
Definition at line 50 of file Optimizer.h.
template<typename Number> vector_t<Number> hypro::Optimizer< Number >::mConstraintVector private
Definition at line 51 of file Optimizer.h.
template<typename Number> std::mutex hypro::Optimizer< Number >::mContextLock mutable private
Definition at line 69 of file Optimizer.h.
template<typename Number> smtrat::FormulaT hypro::Optimizer< Number >::mCurrentFormula mutable private
Definition at line 62 of file Optimizer.h.
template<typename Number> std::unordered_map<smtrat::FormulaT, std::size_t> hypro::Optimizer< Number >::mFormulaMapping mutable private
Definition at line 63 of file Optimizer.h.
template<typename Number> std::map<std::thread::id, glpk_context> hypro::Optimizer< Number >::mGlpkContexts mutable private
Definition at line 72 of file Optimizer.h.
Referenced by hypro::Optimizer< Number >::getGLPContexts().
template<typename Number> SOLUTION hypro::Optimizer< Number >::mLastConsistencyAnswer = SOLUTION::UNKNOWN mutable private
Definition at line 54 of file Optimizer.h.
Referenced by hypro::Optimizer< Number >::getLastConsistencyAnswer().
template<typename Number> std::vector<carl::Relation> hypro::Optimizer< Number >::mRelationSymbols mutable private
Definition at line 57 of file Optimizer.h.
template<typename Number> smtrat::SimplexSolver hypro::Optimizer< Number >::mSmtratSolver mutable private
Definition at line 61 of file Optimizer.h.
template<typename Number> bool hypro::Optimizer< Number >::warnInexact = false static private
Definition at line 55 of file Optimizer.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/util/linearOptimization/Optimizer.h