HyPro: hypro::BoxT< double, Converter, Setting > Class Template Reference
hypro::BoxT< double, Converter, Setting > Class Template Reference
Class holding a specialization of the generic BoxT type with double numbers.
#include <Box_double.h>
Public Member Functions
BoxT ()
Creates an empty box.
BoxT (const BoxT &orig)=default
Copy constructor.
template<typename SettingRhs , carl::DisableIf< std::is_same< Setting, SettingRhs > > = carl::dummy>
BoxT (const BoxT< double, Converter, SettingRhs > &orig)
Copy constructor for different settings. NOTE: it is not an actual copy constructor as it is templated.
BoxT (BoxT &&orig)=default
Move constructor.
BoxT (const carl::Interval< double > &val)
Box constructor from one interval, results in a one-dimensional box.
BoxT (const std::pair< Point< double >, Point< double >> &limits)
Box constructor from a pair of points.
BoxT (const std::vector< carl::Interval< double >> &_intervals)
Constructor from a vector of intervals.
BoxT (const matrix_t< double > &_constraints, const vector_t< double > &_constants)
Constructor from a matrix and a vector.
BoxT (const std::set< Point< double >> &_points)
Constructor from a set of points.
BoxT (const std::vector< Point< double >> &_points)
A constructor from a vector of points.
~BoxT ()
Destructor.
std::vector< carl::Interval
< double > > boundaries () const
Getter for interval representation of the current box.
const std::pair< Point< double >
, Point< double > > & limits () const
Getter for the limiting points.
std::pair< Point< double >
, Point< double > > & rLimits ()
Getter for a reference to the limit points.
matrix_t< double > matrix () const
vector_t< double > vector () const
std::vector< Halfspace< double > > constraints () const
Getter for the hyperplanar representation of the current box.
void insert (const carl::Interval< double > &val)
Extends the dimension of the current box by the given interval.
carl::Interval< double > interval (std::size_t d) const
Getter for an interval representation of one specific dimension.
carl::Interval< double > at (std::size_t _index) const
Getter for an interval representation of one specific dimension.
bool empty () const
Determines if the current box is empty.
bool isSymmetric () const
Determines if the current box is symmetric.
Point< double > max () const
Getter for the maximal point.
Point< double > min () const
Getter for the maximal point.
double supremum () const
Method returning the supremum point of the box, i.e. the maximal point.
std::vector< Point< double > > vertices (const matrix_t< double > &=matrix_t< double >::Zero(0, 0)) const
Getter for a vertex-representation of the current box.
EvaluationResult< double > evaluate (const vector_t< double > &_direction, bool) const
Evaluation function (convex linear optimization).
std::vector< EvaluationResult
< double > > multiEvaluate (const matrix_t< double > &_directions, bool useExact=true) const
Multi-evaluation function (convex linear optimization).
BoxT< double, Converter,
Setting > & operator= (const BoxT< double, Converter, Setting > &rhs)=default
Assignment operator.
BoxT< double, Converter,
Setting > & operator= (BoxT< double, Converter, Setting > &&rhs)=default
Move assignment operator.
BoxT< double, Converter, Setting > operator* (const double &factor) const
Scaling operator.
carl::Interval< double > operator[] (unsigned i) const
Access operator (const).
std::size_t dimension () const
Getter for the space dimension.
void removeRedundancy ()
Removes redundancy (part of the general interface. Does nothing for boxes.)
std::size_t size () const
Storage size determination.
const BoxT< double, Converter,
Setting > & reduceNumberRepresentation (unsigned=fReach_DENOMINATOR)
Empty function for number size reduction, which is omitted when using native double numbers.
BoxT< double, Converter, Setting > makeSymmetric () const
Makes a symmetric box from the current box.
std::pair< CONTAINMENT, BoxT > satisfiesHalfspace (const Halfspace< double > &rhs) const
Checks, if the box lies inside the given halfspace.
std::pair< CONTAINMENT, BoxT > satisfiesHalfspaces (const matrix_t< double > &_mat, const vector_t< double > &_vec) const
Checks, if the box lies inside the given set of halfspaces.
BoxT< double, Converter, Setting > project (const std::vector< std::size_t > &dimensions) const
Projects the box onto the given dimensions.
BoxT< double, Converter, Setting > linearTransformation (const matrix_t< double > &A) const
Applies a linear transformation to the box.
BoxT< double, Converter, Setting > affineTransformation (const matrix_t< double > &A, const vector_t< double > &b) const
Applies an affine transformation to the box.
BoxT< double, Converter, Setting > minkowskiSum (const BoxT< double, Converter, Setting > &rhs) const
Computes the Minkowski sum of two boxes.
BoxT< double, Converter, Setting > minkowskiDecomposition (const BoxT< double, Converter, Setting > &rhs) const
Computes the Minkowski decomposition of the current box by the given box.
BoxT< double, Converter, Setting > intersect (const BoxT< double, Converter, Setting > &rhs) const
Computes the intersection of two boxes.
BoxT< double, Converter, Setting > intersectHalfspace (const Halfspace< double > &hspace) const
Computes the intersection of the current box with a given halfspace.
BoxT< double, Converter, Setting > intersectHalfspaces (const matrix_t< double > &_mat, const vector_t< double > &_vec) const
Computes the intersection of the current box with a set of halfspaces.
bool contains (const Point< double > &point) const
Containment check for a point.
bool contains (const BoxT< double, Converter, Setting > &box) const
Containment check for a box.
BoxT< double, Converter, Setting > unite (const BoxT< double, Converter, Setting > &rhs) const
Computes the union of two boxes.
void reduceRepresentation ()
Reduces the box - does nothing, as the number type cannot be optimized.
void clear ()
Makes this box the empty box.
void print () const
A deprecated print method. Use the outstream operator.
Public Member Functions inherited from hypro::GeometricObject< double, BoxT< double, Converter, Setting > >
virtual ~GeometricObject ()
Destroys the object.
virtual std::pair< CONTAINMENT,
BoxT< double, Converter,
Setting > > satisfiesHalfspace (const Halfspace< double > &rhs) const =0
Method combining the intersection of the set with a halfspace and a test for emptiness of the resulting set.
virtual BoxT< double,
Converter, Setting > minkowskiSum (const BoxT< double, Converter, Setting > &rhs) const =0
Computes Minkowski's sum of the current set and the passed set.
virtual BoxT< double,
Converter, Setting > intersectHalfspace (const Halfspace< double > &rhs) const =0
Computes the intersection of the set with the given halfspace.
virtual bool contains (const Point< double > &point) const =0
Checks, whether the set contains the passed point.
virtual bool contains (const BoxT< double, Converter, Setting > &rhs) const =0
virtual BoxT< double,
Converter, Setting > unite (const BoxT< double, Converter, Setting > &rhs) const =0
Computes the convex hull of the union of the set and the passed set.
Static Public Member Functions
static BoxT< double, Converter,
Setting > Empty (std::size_t dimension=0)
Static method for the construction of an empty box of required dimension.
static representation_name type ()
static BoxT< double, Converter,
Setting > unite (const std::vector< BoxT< double, Converter, Setting >> &boxes)
Computes the union of the current box with a set of boxes.
Protected Attributes
std::pair< Point< double >
, Point< double > > mLimits
Friends
template<class SettingRhs >
bool operator== (const BoxT< double, Converter, Setting > &b1, const BoxT< double, Converter, SettingRhs > &b2)
Checks if two boxes are equal.
bool operator!= (const BoxT< double, Converter, Setting > &b1, const BoxT< double, Converter, Setting > &b2)
Determines inequality of two boxes.
std::ostream & operator<< (std::ostream &ostr, const BoxT< double, Converter, Setting > &b)
Outstream operator.
Detailed Description
template<typename Converter, class Setting>
class hypro::BoxT< double, Converter, Setting >
Class holding a specialization of the generic BoxT type with double numbers.
Template Parameters
Converter The used converter.
Definition at line 20 of file Box_double.h.
Constructor & Destructor Documentation
template<typename Converter , class Setting > hypro::BoxT< double, Converter, Setting >::BoxT () inline
Creates an empty box.
The empty box is represented by a zero-dimensional point pair.
Definition at line 38 of file Box_double.h.
References hypro::BoxT< Number, Converter, Setting >::dimension(), and hypro::BoxT< Number, Converter, Setting >::empty().
template<typename Converter , class Setting > hypro::BoxT< double, Converter, Setting >::BoxT (const BoxT< double, Converter, Setting > & orig) default
Copy constructor.
Parameters
[in] orig The original.
template<typename Converter , class Setting > template<typename SettingRhs , carl::DisableIf< std::is_same< Setting, SettingRhs > > = carl::dummy> hypro::BoxT< double, Converter, Setting >::BoxT (const BoxT< double, Converter, SettingRhs > & orig) inline
Copy constructor for different settings. NOTE: it is not an actual copy constructor as it is templated.
Parameters
[in] orig The original.
Definition at line 51 of file Box_double.h.
template<typename Converter , class Setting > hypro::BoxT< double, Converter, Setting >::BoxT (BoxT< double, Converter, Setting > && orig) default
Move constructor.
Parameters
[in] orig The move-copyable original.
template<typename Converter , class Setting > hypro::BoxT< double, Converter, Setting >::BoxT (const carl::Interval< double > & val) inline explicit
Box constructor from one interval, results in a one-dimensional box.
Parameters
[in] val An interval.
Definition at line 66 of file Box_double.h.
References hypro::BoxT< Number, Converter, Setting >::mLimits.
template<typename Converter , class Setting > hypro::BoxT< double, Converter, Setting >::BoxT (const std::pair< Point< double >, Point< double >> & limits) inline explicit
Box constructor from a pair of points.
The given parameters are considered as the maximal and minimal point. The constructor does not check the order of points.
Parameters
limits Pair of points.
Definition at line 77 of file Box_double.h.
References hypro::BoxT< Number, Converter, Setting >::limits().
template<typename Converter , class Setting > hypro::BoxT< double, Converter, Setting >::BoxT (const std::vector< carl::Interval< double >> & _intervals) explicit
Constructor from a vector of intervals.
The vector is required to be sorted, i.e. the first interval maps to the first dimension etc..
Parameters
_intervals A vector of intervals.
template<typename Converter , class Setting > hypro::BoxT< double, Converter, Setting >::BoxT (const matrix_t< double > & _constraints, const vector_t< double > & _constants)
Constructor from a matrix and a vector.
Constructs a box assuming each row of the matrix is the normal to a hyperplane and its corresponding entry in the given vector is the offset.
Parameters
_constraints A matrix representing the constraint normals.
_constants A vector representing the offsets of the corresponting hyperplane.
template<typename Converter , class Setting > hypro::BoxT< double, Converter, Setting >::BoxT (const std::set< Point< double >> & _points) explicit
Constructor from a set of points.
The constructor does not rely on the operator < of the point class, thus each point is considered for the construction of the maximal and minimal point.
Parameters
_points A set of points.
template<typename Converter , class Setting > hypro::BoxT< double, Converter, Setting >::BoxT (const std::vector< Point< double >> & _points) explicit
A constructor from a vector of points.
Creates the maximal and minimal point by collecting all coordinates from all given points.
Parameters
_points A vector of points.
Member Function Documentation
template<typename Converter , class Setting > BoxT<double,Converter,Setting> hypro::BoxT< double, Converter, Setting >::affineTransformation (const matrix_t< double > & A, const vector_t< double > & b) const virtual
Applies an affine transformation to the box.
The transformation is done on the two limit points directly. TODO: Add more extensive description here.
Parameters
[in] A A matrix for the affine transformation.
[in] b A vector for the offset.
Returns
The resulting box.
Implements hypro::GeometricObject< double, BoxT< double, Converter, Setting > >.
template<typename Converter , class Setting > carl::Interval<double> hypro::BoxT< double, Converter, Setting >::at (std::size_t _index) const inline
Getter for an interval representation of one specific dimension.
Converts the d-th entries in the maximal and minimal point to an interval.
Parameters
d The queried dimension.
Returns
An interval.
Definition at line 182 of file Box_double.h.
References hypro::BoxT< Number, Converter, Setting >::mLimits.
template<typename Converter , class Setting > std::vector<carl::Interval<double> > hypro::BoxT< double, Converter, Setting >::boundaries () const
Getter for interval representation of the current box.
Converts the two-points representation of the current box into a sorted vector of intervals.
Returns
A vector of intervals.
template<typename Converter , class Setting > std::vector<Halfspace<double> > hypro::BoxT< double, Converter, Setting >::constraints () const
Getter for the hyperplanar representation of the current box.
Converts the two-points representation into a hyperplanar representation, i.e. a H-polytope.
Returns
A vector of hyperplanes.
template<typename Converter , class Setting > bool hypro::BoxT< double, Converter, Setting >::contains (const Point< double > & point) const
Containment check for a point.
Parameters
[in] point The point.
Returns
True, if the point is contained inside the current box, false otherwise.
template<typename Converter , class Setting > bool hypro::BoxT< double, Converter, Setting >::contains (const BoxT< double, Converter, Setting > & box) const
Containment check for a box.
Parameters
[in] box The box.
Returns
True, if the given box is contained in the current box, false otherwise.
template<typename Converter , class Setting > std::size_t hypro::BoxT< double, Converter, Setting >::dimension () const inline virtual
Getter for the space dimension.
Returns
The dimension of the space.
Implements hypro::GeometricObject< double, BoxT< double, Converter, Setting > >.
Definition at line 348 of file Box_double.h.
References hypro::BoxT< Number, Converter, Setting >::mLimits.
template<typename Converter , class Setting > static BoxT<double,Converter,Setting> hypro::BoxT< double, Converter, Setting >::Empty (std::size_t dimension = 0) inline static
Static method for the construction of an empty box of required dimension.
Parameters
dimension Required dimension.
Returns
Empty box.
Definition at line 128 of file Box_double.h.
References hypro::BoxT< Number, Converter, Setting >::dimension().
template<typename Converter , class Setting > bool hypro::BoxT< double, Converter, Setting >::empty () const inline virtual
Determines if the current box is empty.
The method checks the dimension of the limit points and afterwards each interval for emptiness.
Returns
True, if one interval is empty. False if the dimension is 0 or no interval is empty.
Implements hypro::GeometricObject< double, BoxT< double, Converter, Setting > >.
Definition at line 194 of file Box_double.h.
References hypro::BoxT< Number, Converter, Setting >::mLimits.
template<typename Converter , class Setting > EvaluationResult<double> hypro::BoxT< double, Converter, Setting >::evaluate (const vector_t< double > & _direction, bool) const
Evaluation function (convex linear optimization).
Parameters
[in] _direction The direction/cost function.
Returns
Maximum towards _direction.
template<typename Converter , class Setting > void hypro::BoxT< double, Converter, Setting >::insert (const carl::Interval< double > & val) inline
Extends the dimension of the current box by the given interval.
Effectively extends the dimension of the current box.
Parameters
val An interval.
Definition at line 166 of file Box_double.h.
References hypro::BoxT< Number, Converter, Setting >::mLimits.
template<typename Converter , class Setting > BoxT<double,Converter,Setting> hypro::BoxT< double, Converter, Setting >::intersect (const BoxT< double, Converter, Setting > & rhs) const
Computes the intersection of two boxes.
Parameters
[in] rhs The right hand side box.
Returns
The resulting box.
template<typename Converter , class Setting > BoxT<double,Converter,Setting> hypro::BoxT< double, Converter, Setting >::intersectHalfspace (const Halfspace< double > & hspace) const
Computes the intersection of the current box with a given halfspace.
Parameters
[in] hspace The halfspace.
Returns
The resulting box.
template<typename Converter , class Setting > BoxT<double,Converter,Setting> hypro::BoxT< double, Converter, Setting >::intersectHalfspaces (const matrix_t< double > & _mat, const vector_t< double > & _vec) const virtual
Computes the intersection of the current box with a set of halfspaces.
Parameters
[in] _mat The matrix representing the normal vectors.
[in] _vec The vector representing the offsets.
Returns
The resulting box.
Implements hypro::GeometricObject< double, BoxT< double, Converter, Setting > >.
template<typename Converter , class Setting > carl::Interval<double> hypro::BoxT< double, Converter, Setting >::interval (std::size_t d) const
Getter for an interval representation of one specific dimension.
Converts the d-th entries in the maximal and minimal point to an interval.
Parameters
d The queried dimension.
Returns
An interval.
template<typename Converter , class Setting > bool hypro::BoxT< double, Converter, Setting >::isSymmetric () const inline
Determines if the current box is symmetric.
A box is symmetric, if its centroid is the origin in the respective space, i.e. if the center of each interval in each dimension is zero.
Returns
True if symmetric, False otherwise.
Definition at line 213 of file Box_double.h.
References hypro::BoxT< Number, Converter, Setting >::mLimits.
template<typename Converter , class Setting > const std::pair<Point<double>, Point<double> >& hypro::BoxT< double, Converter, Setting >::limits () const inline
Getter for the limiting points.
Returns
A pair of points.
Definition at line 143 of file Box_double.h.
References hypro::BoxT< Number, Converter, Setting >::mLimits.
template<typename Converter , class Setting > BoxT<double,Converter,Setting> hypro::BoxT< double, Converter, Setting >::linearTransformation (const matrix_t< double > & A) const virtual
Applies a linear transformation to the box.
The transformation is done on the two limit points directly. TODO: Add more extensive description here.
Parameters
[in] A A matrix for the linear transformation.
Returns
The resulting box.
Implements hypro::GeometricObject< double, BoxT< double, Converter, Setting > >.
template<typename Converter , class Setting > BoxT<double,Converter,Setting> hypro::BoxT< double, Converter, Setting >::makeSymmetric () const
Makes a symmetric box from the current box.
The symmetry is obtained by dimension-wise extension of the boundaries. The resulting boundaries for each dimension are the maximal absolute values of the original boundaries mirrored positive and negative.
Returns
The resulting symmetric box.
template<typename Converter , class Setting > Point<double> hypro::BoxT< double, Converter, Setting >::max () const inline
Getter for the maximal point.
Returns
A point.
Definition at line 229 of file Box_double.h.
References hypro::BoxT< Number, Converter, Setting >::mLimits.
template<typename Converter , class Setting > Point<double> hypro::BoxT< double, Converter, Setting >::min () const inline
Getter for the maximal point.
Returns
A point.
Definition at line 237 of file Box_double.h.
References hypro::BoxT< Number, Converter, Setting >::mLimits.
template<typename Converter , class Setting > BoxT<double,Converter,Setting> hypro::BoxT< double, Converter, Setting >::minkowskiDecomposition (const BoxT< double, Converter, Setting > & rhs) const
Computes the Minkowski decomposition of the current box by the given box.
Parameters
[in] rhs The right hand side box.
Returns
The resulting box.
template<typename Converter , class Setting > BoxT<double,Converter,Setting> hypro::BoxT< double, Converter, Setting >::minkowskiSum (const BoxT< double, Converter, Setting > & rhs) const
Computes the Minkowski sum of two boxes.
Parameters
[in] rhs The right hand side box.
Returns
The resulting box.
template<typename Converter , class Setting > std::vector<EvaluationResult<double> > hypro::BoxT< double, Converter, Setting >::multiEvaluate (const matrix_t< double > & _directions, bool useExact = true) const
Multi-evaluation function (convex linear optimization).
Parameters
[in] _directions The directions/cost functions.
Returns
A set of maxima towards the respective directions.
template<typename Converter , class Setting > BoxT<double,Converter,Setting> hypro::BoxT< double, Converter, Setting >::operator* (const double & factor) const inline
Scaling operator.
Parameters
[in] factor The scaling factor.
Returns
The scaled box.
Definition at line 308 of file Box_double.h.
References hypro::BoxT< Number, Converter, Setting >::empty(), and hypro::BoxT< Number, Converter, Setting >::mLimits.
template<typename Converter , class Setting > BoxT<double,Converter,Setting>& hypro::BoxT< double, Converter, Setting >::operator= (const BoxT< double, Converter, Setting > & rhs) default
Assignment operator.
Parameters
rhs A box.
template<typename Converter , class Setting > BoxT<double,Converter,Setting>& hypro::BoxT< double, Converter, Setting >::operator= (BoxT< double, Converter, Setting > && rhs) default
Move assignment operator.
Parameters
rhs A box.
template<typename Converter , class Setting > carl::Interval<double> hypro::BoxT< double, Converter, Setting >::operator[] (unsigned i) const inline
Access operator (const).
Parameters
i Dimension to access.
Returns
An interval.
Definition at line 338 of file Box_double.h.
References hypro::BoxT< Number, Converter, Setting >::mLimits.
template<typename Converter , class Setting > BoxT<double,Converter,Setting> hypro::BoxT< double, Converter, Setting >::project (const std::vector< std::size_t > & dimensions) const virtual
Projects the box onto the given dimensions.
Parameters
[in] dimensions The dimensions.
Returns
The projected box.
Implements hypro::GeometricObject< double, BoxT< double, Converter, Setting > >.
template<typename Converter , class Setting > const BoxT<double,Converter,Setting>& hypro::BoxT< double, Converter, Setting >::reduceNumberRepresentation (unsigned = fReach_DENOMINATOR) inline
Empty function for number size reduction, which is omitted when using native double numbers.
Parameters
limit Parameter for a length estimation.
Definition at line 367 of file Box_double.h.
template<typename Converter , class Setting > std::pair<Point<double>, Point<double> >& hypro::BoxT< double, Converter, Setting >::rLimits () inline
Getter for a reference to the limit points.
Returns
A reference to the limit point pair of the object.
Definition at line 149 of file Box_double.h.
References hypro::BoxT< Number, Converter, Setting >::mLimits.
template<typename Converter , class Setting > std::pair<CONTAINMENT, BoxT> hypro::BoxT< double, Converter, Setting >::satisfiesHalfspace (const Halfspace< double > & rhs) const
Checks, if the box lies inside the given halfspace.
This function combines the intersection with a given halfspace along with the emptiness test on the result, which is often faster than the sequential execution of both commands.
Parameters
[in] rhs The halfspace.
Returns
A pair of a CONTAINMENT value and a box. The Boolean is true in case the resulting box is not empty and false otherwise.
template<typename Converter , class Setting > std::pair<CONTAINMENT, BoxT> hypro::BoxT< double, Converter, Setting >::satisfiesHalfspaces (const matrix_t< double > & _mat, const vector_t< double > & _vec) const virtual
Checks, if the box lies inside the given set of halfspaces.
This function combines the intersection with a given set of halfspaces along with the emptiness test on the result, which is often faster than the sequential execution of both commands.
Parameters
[in] _mat The normals of the halfspaces.
[in] _vec The offsets of the halfspaces.
Returns
A pair of a CONTAINMENT value and a box. The Boolean is true in case the resulting box is not empty and false otherwise.
Implements hypro::GeometricObject< double, BoxT< double, Converter, Setting > >.
template<typename Converter , class Setting > std::size_t hypro::BoxT< double, Converter, Setting >::size () const
Storage size determination.
Returns
Size of the required memory.
template<typename Converter , class Setting > double hypro::BoxT< double, Converter, Setting >::supremum () const
Method returning the supremum point of the box, i.e. the maximal point.
Returns
A point representing the supremum of the current box.
template<typename Converter , class Setting > BoxT<double,Converter,Setting> hypro::BoxT< double, Converter, Setting >::unite (const BoxT< double, Converter, Setting > & rhs) const
Computes the union of two boxes.
Parameters
[in] rhs The right hand side box.
Returns
The resulting box.
template<typename Converter , class Setting > static BoxT<double,Converter,Setting> hypro::BoxT< double, Converter, Setting >::unite (const std::vector< BoxT< double, Converter, Setting >> & boxes) static
Computes the union of the current box with a set of boxes.
Parameters
[in] boxes The boxes.
Returns
The resulting box.
template<typename Converter , class Setting > std::vector<Point<double> > hypro::BoxT< double, Converter, Setting >::vertices (const matrix_t< double > & = matrix_t< double >::Zero(0, 0)) const virtual
Getter for a vertex-representation of the current box.
Converts the current box from its two-point representation into a vertex representation, i.e. a V-polytope. The representation is generated by creating all possible combinations of upper and lower bounds of the box.
Returns
A vector of points.
Implements hypro::GeometricObject< double, BoxT< double, Converter, Setting > >.
Friends And Related Function Documentation
template<typename Converter , class Setting > bool operator!= (const BoxT< double, Converter, Setting > & b1, const BoxT< double, Converter, Setting > & b2) friend
Determines inequality of two boxes.
Parameters
b1 A box.
b2 A box.
Returns
False, if both boxes are equal.
Definition at line 289 of file Box_double.h.
template<typename Converter , class Setting > std::ostream& operator<< (std::ostream & ostr, const BoxT< double, Converter, Setting > & b) friend
Outstream operator.
Parameters
ostr Outstream.
b A box.
Definition at line 321 of file Box_double.h.
template<typename Converter , class Setting > template<class SettingRhs > bool operator== (const BoxT< double, Converter, Setting > & b1, const BoxT< double, Converter, SettingRhs > & b2) friend
Checks if two boxes are equal.
Parameters
b1 Contains the first box.
b2 Contains the second box.
Returns
True, if they are equal.
Definition at line 276 of file Box_double.h.
Member Data Documentation
template<typename Converter , class Setting > std::pair<Point<double>, Point<double> > hypro::BoxT< double, Converter, Setting >::mLimits protected
Pair of points describing the minimal and the maximal point of the box.
Definition at line 27 of file Box_double.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/Box/Box_double.h