HyPro: hypro::HybridAutomatonParser::ActivitiesContext Class Reference
hypro::HybridAutomatonParser::ActivitiesContext Class Reference
Public Member Functions
ActivitiesContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * ODE ()
antlr4::tree::TerminalNode * POLY ()
antlr4::tree::TerminalNode * LINEAR ()
antlr4::tree::TerminalNode * NONLINEAR ()
antlr4::tree::TerminalNode * NONPOLY ()
antlr4::tree::TerminalNode * LTI ()
std::vector< antlr4::tree::TerminalNode * > NUMBER ()
antlr4::tree::TerminalNode * NUMBER (size_t i)
std::vector< EquationContext * > equation ()
EquationContext * equation (size_t i)
std::vector< IntervalexprContext * > intervalexpr ()
IntervalexprContext * intervalexpr (size_t i)
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Detailed Description
Definition at line 189 of file HybridAutomatonParser.h.
Constructor & Destructor Documentation
HybridAutomatonParser::ActivitiesContext::ActivitiesContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 476 of file HybridAutomatonParser.cpp.
Member Function Documentation
antlrcpp::Any HybridAutomatonParser::ActivitiesContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
Definition at line 533 of file HybridAutomatonParser.cpp.
std::vector< HybridAutomatonParser::EquationContext * > HybridAutomatonParser::ActivitiesContext::equation ()
Definition at line 512 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::activities(), and hypro::HyproLocationVisitor< Number >::visitModes().
HybridAutomatonParser::EquationContext * HybridAutomatonParser::ActivitiesContext::equation (size_t i)
Definition at line 516 of file HybridAutomatonParser.cpp.
size_t HybridAutomatonParser::ActivitiesContext::getRuleIndex () const override virtual
Definition at line 529 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::RuleActivities.
std::vector< HybridAutomatonParser::IntervalexprContext * > HybridAutomatonParser::ActivitiesContext::intervalexpr ()
Definition at line 520 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::activities(), and hypro::HyproLocationVisitor< Number >::visitModes().
HybridAutomatonParser::IntervalexprContext * HybridAutomatonParser::ActivitiesContext::intervalexpr (size_t i)
Definition at line 524 of file HybridAutomatonParser.cpp.
tree::TerminalNode * HybridAutomatonParser::ActivitiesContext::LINEAR ()
Definition at line 488 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::LINEAR.
tree::TerminalNode * HybridAutomatonParser::ActivitiesContext::LTI ()
Definition at line 500 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::LTI.
tree::TerminalNode * HybridAutomatonParser::ActivitiesContext::NONLINEAR ()
Definition at line 492 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::NONLINEAR.
tree::TerminalNode * HybridAutomatonParser::ActivitiesContext::NONPOLY ()
Definition at line 496 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::NONPOLY.
std::vector< tree::TerminalNode * > HybridAutomatonParser::ActivitiesContext::NUMBER ()
Definition at line 504 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::NUMBER.
tree::TerminalNode * HybridAutomatonParser::ActivitiesContext::NUMBER (size_t i)
Definition at line 508 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::NUMBER.
tree::TerminalNode * HybridAutomatonParser::ActivitiesContext::ODE ()
Definition at line 480 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::ODE.
tree::TerminalNode * HybridAutomatonParser::ActivitiesContext::POLY ()
Definition at line 484 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::POLY.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HybridAutomatonParser.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HybridAutomatonParser.cpp