HyPro: hypro::Plotter< Number > Class Template Reference
hypro::Plotter< Number > Class Template Reference
Class implementing a plotter. The plotter is implemented using carl::Singleton.
#include <Plotter.h>
Public Member Functions
~Plotter ()
void setFilename (const std::string &_filename="out")
Sets the filename.
void updateSettings (const plotting::gnuplotSettings &_settings)
Overrides the current plotting settings with the passed ones.
const plotting::gnuplotSettings & settings () const
Returns the current plotting settings struct.
plotting::gnuplotSettings & rSettings ()
Provides a reference to the current plotting settings such that they can be changed in place.
void plot2d () const
Creates a gnuplot file of the currently passed objects.
void plotTex () const
Creates a LaTeX file of the currently passed objects.
void plotGen () const
Creates a .gen file of the currently passed objects, which can be used in gnuplot as well.
void plotEps () const
Creates a .eps file of the currently passed objects, which can be used in gnuplot as well.
void plotPng () const
Creates a .eps file of the currently passed objects, which can be used in gnuplot as well.
unsigned addObject (const std::vector< Point< Number >> &_points)
Adds an object represented as a vector of points. Duplicates and points inside will be removed by the plotter, which runs a 2d-convex hull algorithm (Graham's scan) one the vertices.
unsigned addObject (const std::vector< std::vector< Point< Number >>> &_points)
Adds several objects represented as a vector of vectors of points. Duplicates and points inside will be removed by the plotter, which runs a 2d-convex hull algorithm (Graham's scan) one the vertices.
unsigned addObject (const std::vector< Halfspace< Number >> &_planes)
Adds a set of halfspaces to the plotter.
unsigned addObject (const Halfspace< Number > &_plane)
Adds a halfspace to the plotter.
unsigned addPoint (const Point< Number > &_point)
Adds a point to the plotter.
unsigned addPoints (const std::vector< Point< Number >> &_points)
Adds points to the plotter.
void addVector (const vector_t< Number > &_vector)
Adds a vector to the plotter.
void setObjectColor (unsigned _id, const std::size_t _color)
Sets the object color.
void clear ()
Static Public Member Functions
static std::vector< Point< Number > > grahamScan (const std::vector< Point< Number >> &_points)
Implementation of Graham's scan.
Protected Member Functions
Plotter ()
Private Member Functions
void init (const std::string &_filename)
void writeGnuplot () const
void prepareObjects () const
Static Private Member Functions
static bool isLeftTurn (const Point< Number > &a, const Point< Number > &b, const Point< Number > &c)
Private Attributes
std::ofstream mOutfile
std::multimap< unsigned, std::vector< Point< Number > > > mObjects
std::multimap< unsigned, std::vector< Halfspace< Number > > > mPlanes
std::multimap< unsigned, Point< Number > > mPoints
std::multimap< unsigned, vector_t< Number > > mVectors
std::pair< int, int > mLastDimensions
std::pair< vector_t< Number >, vector_t< Number > > mLimits
std::map< unsigned, std::size_t > mObjectColors
plotting::gnuplotSettings mSettings = plotting::gnuplotSettings{}
unsigned mId
Detailed Description
template<typename Number>
class hypro::Plotter< Number >
Class implementing a plotter. The plotter is implemented using carl::Singleton.
Template Parameters
Number The used number type.
Definition at line 77 of file Plotter.h.
Constructor & Destructor Documentation
template<typename Number> hypro::Plotter< Number >::Plotter () inline protected
Definition at line 93 of file Plotter.h.
References b, c, settings(), string(), and vector.
template<typename Number> hypro::Plotter< Number >::~Plotter ()
Member Function Documentation
template<typename Number> unsigned hypro::Plotter< Number >::addObject (const std::vector< Point< Number >> & _points)
Adds an object represented as a vector of points. Duplicates and points inside will be removed by the plotter, which runs a 2d-convex hull algorithm (Graham's scan) one the vertices.
Parameters
[in] _points The points.
Returns
A unique id, which allows to reference the object to change its colors.
Referenced by addSegment(), main(), testAffineTransformation(), testConversionBoxToDBM(), testConversionDifferenceBoundsToDifferenceBounds(), testConversionHPolyToDBM(), testCopy(), testElapse(), testExtraLU(), testExtraLUPlus(), testExtraM(), testExtraMPlus(), testFree(), testIntersectConstraint(), testIntersectDBM(), testIntersectHalfspace(), testIntersectHalfspaces(), testLinearTransformation(), testMinkowskiSum(), testReset(), testRewind(), testSatisfiesHalfspace(), testSatisfiesHalfspaces(), testShift(), testUnion(), and testVertices().
template<typename Number> unsigned hypro::Plotter< Number >::addObject (const std::vector< std::vector< Point< Number >>> & _points)
Adds several objects represented as a vector of vectors of points. Duplicates and points inside will be removed by the plotter, which runs a 2d-convex hull algorithm (Graham's scan) one the vertices.
Parameters
[in] _points The points.
Returns
The id of the last added object, which allows to reference the object to change its colors. All other ids can be derived using the size of the passed vector (ids are assigned ascending).
template<typename Number> unsigned hypro::Plotter< Number >::addObject (const std::vector< Halfspace< Number >> & _planes)
Adds a set of halfspaces to the plotter.
Note that the plotting of planes requires that at least one proper object (a set of points) is added as well, because the plotter needs to determine the plotting dimensions.
Parameters
[in] _planes The planes.
Returns
An id referencing the last plane.
template<typename Number> unsigned hypro::Plotter< Number >::addObject (const Halfspace< Number > & _plane)
Adds a halfspace to the plotter.
Note that the plotting of planes requires that at least one proper object (a set of points) is added as well, because the plotter needs to determine the plotting dimensions.
Parameters
[in] _plane The plane.
Returns
An id referencing the plane.
template<typename Number> unsigned hypro::Plotter< Number >::addPoint (const Point< Number > & _point)
Adds a point to the plotter.
The point, in contrast to an object will be plotted as a cross.
Parameters
[in] _point The point.
Returns
An id referencing the point.
Referenced by main().
template<typename Number> unsigned hypro::Plotter< Number >::addPoints (const std::vector< Point< Number >> & _points)
Adds points to the plotter.
The points will be plotted as crosses.
Parameters
[in] _points The points.
Returns
An id referencing the last passed point.
Referenced by main().
template<typename Number> void hypro::Plotter< Number >::addVector (const vector_t< Number > & _vector)
Adds a vector to the plotter.
A vector will be plotted as an arrow starting from the origin.
Parameters
[in] _vector The vector.
template<typename Number> void hypro::Plotter< Number >::clear ()
Referenced by testAffineTransformation(), testConversionBoxToDBM(), testConversionDifferenceBoundsToDifferenceBounds(), testConversionHPolyToDBM(), testCopy(), testElapse(), testExtraLU(), testExtraLUPlus(), testExtraM(), testExtraMPlus(), testFree(), testIntersectConstraint(), testIntersectDBM(), testIntersectHalfspace(), testIntersectHalfspaces(), testLinearTransformation(), testMinkowskiSum(), testReset(), testRewind(), testSatisfiesHalfspace(), testSatisfiesHalfspaces(), testShift(), testUnion(), and testVertices().
template<typename Number> static std::vector<Point<Number> > hypro::Plotter< Number >::grahamScan (const std::vector< Point< Number >> & _points) static
Implementation of Graham's scan.
Parameters
_points A vector of 2-dimensional points.
Returns
std::vector<Point<Number>> An ordered vector of 2-dimensional points (counterclockwise).
template<typename Number> void hypro::Plotter< Number >::init (const std::string & _filename) private
template<typename Number> static bool hypro::Plotter< Number >::isLeftTurn (const Point< Number > & a, const Point< Number > & b, const Point< Number > & c) static private
template<typename Number> void hypro::Plotter< Number >::plot2d () const
Creates a gnuplot file of the currently passed objects.
The resulting *.plt file can be compiled to a pdf invoking gnuplot.
Referenced by main(), testAffineTransformation(), testConversionBoxToDBM(), testConversionDifferenceBoundsToDifferenceBounds(), testConversionHPolyToDBM(), testCopy(), testElapse(), testExtraLU(), testExtraLUPlus(), testExtraM(), testExtraMPlus(), testFree(), testIntersectConstraint(), testIntersectDBM(), testIntersectHalfspace(), testIntersectHalfspaces(), testLinearTransformation(), testMinkowskiSum(), testReset(), testRewind(), testSatisfiesHalfspace(), testSatisfiesHalfspaces(), testShift(), testUnion(), and testVertices().
template<typename Number> void hypro::Plotter< Number >::plotEps () const
Creates a .eps file of the currently passed objects, which can be used in gnuplot as well.
Referenced by main().
template<typename Number> void hypro::Plotter< Number >::plotGen () const
Creates a .gen file of the currently passed objects, which can be used in gnuplot as well.
Referenced by main().
template<typename Number> void hypro::Plotter< Number >::plotPng () const
Creates a .eps file of the currently passed objects, which can be used in gnuplot as well.
template<typename Number> void hypro::Plotter< Number >::plotTex () const
Creates a LaTeX file of the currently passed objects.
We use the gnuplot latex terminal type in standalone mode. Note that for Linux systems at least Texlive 2015 has to be installed to be able to compile the resulting *.tex file.
Referenced by main().
template<typename Number> void hypro::Plotter< Number >::prepareObjects () const private
template<typename Number> plotting::gnuplotSettings& hypro::Plotter< Number >::rSettings ()
Provides a reference to the current plotting settings such that they can be changed in place.
Returns
A reference to the current plotting settings.
template<typename Number> void hypro::Plotter< Number >::setFilename (const std::string & _filename = "out")
Sets the filename.
Parameters
[in] _filename The filename (default = "out").
Referenced by main(), testAffineTransformation(), testConversionBoxToDBM(), testConversionDifferenceBoundsToDifferenceBounds(), testConversionHPolyToDBM(), testCopy(), testElapse(), testExtraLU(), testExtraLUPlus(), testExtraM(), testExtraMPlus(), testFree(), testIntersectConstraint(), testIntersectDBM(), testIntersectHalfspace(), testIntersectHalfspaces(), testLinearTransformation(), testMinkowskiSum(), testReset(), testRewind(), testSatisfiesHalfspace(), testSatisfiesHalfspaces(), testShift(), testUnion(), and testVertices().
template<typename Number> void hypro::Plotter< Number >::setObjectColor (unsigned _id, const std::size_t _color)
Sets the object color.
Parameters
[in] _id The identifier referencing the object.
[in] _color The color.
Referenced by addSegment(), main(), testAffineTransformation(), testConversionBoxToDBM(), testConversionDifferenceBoundsToDifferenceBounds(), testConversionHPolyToDBM(), testCopy(), testElapse(), testExtraLU(), testExtraLUPlus(), testExtraM(), testExtraMPlus(), testFree(), testIntersectConstraint(), testIntersectDBM(), testIntersectHalfspace(), testIntersectHalfspaces(), testLinearTransformation(), testMinkowskiSum(), testReset(), testRewind(), testSatisfiesHalfspace(), testSatisfiesHalfspaces(), testShift(), testUnion(), and testVertices().
template<typename Number> const plotting::gnuplotSettings& hypro::Plotter< Number >::settings () const
Returns the current plotting settings struct.
Returns
The current settings.
Referenced by main().
template<typename Number> void hypro::Plotter< Number >::updateSettings (const plotting::gnuplotSettings & _settings)
Overrides the current plotting settings with the passed ones.
Parameters
[in] _settings The new settings.
Referenced by main().
template<typename Number> void hypro::Plotter< Number >::writeGnuplot () const private
Member Data Documentation
template<typename Number> unsigned hypro::Plotter< Number >::mId private
Definition at line 90 of file Plotter.h.
template<typename Number> std::pair<int, int> hypro::Plotter< Number >::mLastDimensions mutable private
Definition at line 86 of file Plotter.h.
template<typename Number> std::pair<vector_t<Number>, vector_t<Number> > hypro::Plotter< Number >::mLimits mutable private
Definition at line 87 of file Plotter.h.
template<typename Number> std::map<unsigned, std::size_t> hypro::Plotter< Number >::mObjectColors private
Definition at line 88 of file Plotter.h.
template<typename Number> std::multimap<unsigned, std::vector<Point<Number> > > hypro::Plotter< Number >::mObjects mutable private
Definition at line 82 of file Plotter.h.
template<typename Number> std::ofstream hypro::Plotter< Number >::mOutfile mutable private
Definition at line 81 of file Plotter.h.
template<typename Number> std::multimap<unsigned, std::vector<Halfspace<Number> > > hypro::Plotter< Number >::mPlanes mutable private
Definition at line 83 of file Plotter.h.
template<typename Number> std::multimap<unsigned, Point<Number> > hypro::Plotter< Number >::mPoints mutable private
Definition at line 84 of file Plotter.h.
template<typename Number> plotting::gnuplotSettings hypro::Plotter< Number >::mSettings = plotting::gnuplotSettings{} private
Definition at line 89 of file Plotter.h.
template<typename Number> std::multimap<unsigned, vector_t<Number> > hypro::Plotter< Number >::mVectors mutable private
Definition at line 85 of file Plotter.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/util/plotting/Plotter.h