HyPro: hypro::CIFLocVisitor< Number > Class Template Reference
hypro::CIFLocVisitor< Number > Class Template Reference
Public Member Functions
CIFLocVisitor (std::vector< std::string > varVec)
~CIFLocVisitor ()
antlrcpp::Any visitLocations (HybridSystemParser::LocationsContext *ctx) override
Public Member Functions inherited from hypro::HybridSystemBaseVisitor
virtual antlrcpp::Any visitSpecification (HybridSystemParser::SpecificationContext *ctx) override
virtual antlrcpp::Any visitGroupBody (HybridSystemParser::GroupBodyContext *ctx) override
virtual antlrcpp::Any visitAutomatonBody (HybridSystemParser::AutomatonBodyContext *ctx) override
virtual antlrcpp::Any visitOptGroupDecls (HybridSystemParser::OptGroupDeclsContext *ctx) override
virtual antlrcpp::Any visitGroupDecl (HybridSystemParser::GroupDeclContext *ctx) override
virtual antlrcpp::Any visitOptAutDecls (HybridSystemParser::OptAutDeclsContext *ctx) override
virtual antlrcpp::Any visitAutDecl (HybridSystemParser::AutDeclContext *ctx) override
virtual antlrcpp::Any visitDecl (HybridSystemParser::DeclContext *ctx) override
virtual antlrcpp::Any visitImports (HybridSystemParser::ImportsContext *ctx) override
virtual antlrcpp::Any visitTypeDefs (HybridSystemParser::TypeDefsContext *ctx) override
virtual antlrcpp::Any visitEnumDefs (HybridSystemParser::EnumDefsContext *ctx) override
virtual antlrcpp::Any visitConstantDefs (HybridSystemParser::ConstantDefsContext *ctx) override
virtual antlrcpp::Any visitAlgVarsDefs (HybridSystemParser::AlgVarsDefsContext *ctx) override
virtual antlrcpp::Any visitFuncParams (HybridSystemParser::FuncParamsContext *ctx) override
virtual antlrcpp::Any visitFuncParamDecls (HybridSystemParser::FuncParamDeclsContext *ctx) override
virtual antlrcpp::Any visitFuncBody (HybridSystemParser::FuncBodyContext *ctx) override
virtual antlrcpp::Any visitFuncVarDecls (HybridSystemParser::FuncVarDeclsContext *ctx) override
virtual antlrcpp::Any visitFuncVarDecl (HybridSystemParser::FuncVarDeclContext *ctx) override
virtual antlrcpp::Any visitFuncStatements (HybridSystemParser::FuncStatementsContext *ctx) override
virtual antlrcpp::Any visitFuncStatement (HybridSystemParser::FuncStatementContext *ctx) override
virtual antlrcpp::Any visitOptElifFuncStats (HybridSystemParser::OptElifFuncStatsContext *ctx) override
virtual antlrcpp::Any visitOptElseFuncStat (HybridSystemParser::OptElseFuncStatContext *ctx) override
virtual antlrcpp::Any visitEvents (HybridSystemParser::EventsContext *ctx) override
virtual antlrcpp::Any visitActualParms (HybridSystemParser::ActualParmsContext *ctx) override
virtual antlrcpp::Any visitFormalParms (HybridSystemParser::FormalParmsContext *ctx) override
virtual antlrcpp::Any visitFormalDecls (HybridSystemParser::FormalDeclsContext *ctx) override
virtual antlrcpp::Any visitFormalDeclaration (HybridSystemParser::FormalDeclarationContext *ctx) override
virtual antlrcpp::Any visitDiscDecls (HybridSystemParser::DiscDeclsContext *ctx) override
virtual antlrcpp::Any visitDiscDecl (HybridSystemParser::DiscDeclContext *ctx) override
virtual antlrcpp::Any visitContDecls (HybridSystemParser::ContDeclsContext *ctx) override
virtual antlrcpp::Any visitContDecl (HybridSystemParser::ContDeclContext *ctx) override
virtual antlrcpp::Any visitOptDerivate (HybridSystemParser::OptDerivateContext *ctx) override
virtual antlrcpp::Any visitOptControllability (HybridSystemParser::OptControllabilityContext *ctx) override
virtual antlrcpp::Any visitControllability (HybridSystemParser::ControllabilityContext *ctx) override
virtual antlrcpp::Any visitEventType (HybridSystemParser::EventTypeContext *ctx) override
virtual antlrcpp::Any visitExpressions (HybridSystemParser::ExpressionsContext *ctx) override
virtual antlrcpp::Any visitOptExpression (HybridSystemParser::OptExpressionContext *ctx) override
virtual antlrcpp::Any visitExpression (HybridSystemParser::ExpressionContext *ctx) override
virtual antlrcpp::Any visitEquations (HybridSystemParser::EquationsContext *ctx) override
virtual antlrcpp::Any visitEquationDerivate (HybridSystemParser::EquationDerivateContext *ctx) override
virtual antlrcpp::Any visitEquationNonDerivate (HybridSystemParser::EquationNonDerivateContext *ctx) override
virtual antlrcpp::Any visitOrExpression (HybridSystemParser::OrExpressionContext *ctx) override
virtual antlrcpp::Any visitAndExpression (HybridSystemParser::AndExpressionContext *ctx) override
virtual antlrcpp::Any visitCompareExpression (HybridSystemParser::CompareExpressionContext *ctx) override
virtual antlrcpp::Any visitAddExpression (HybridSystemParser::AddExpressionContext *ctx) override
virtual antlrcpp::Any visitMulExpression (HybridSystemParser::MulExpressionContext *ctx) override
virtual antlrcpp::Any visitUnaryExprFunc (HybridSystemParser::UnaryExprFuncContext *ctx) override
virtual antlrcpp::Any visitUnaryExprMinus (HybridSystemParser::UnaryExprMinusContext *ctx) override
virtual antlrcpp::Any visitUnaryExprPlus (HybridSystemParser::UnaryExprPlusContext *ctx) override
virtual antlrcpp::Any visitUnaryExpr (HybridSystemParser::UnaryExprContext *ctx) override
virtual antlrcpp::Any visitFuncExpression (HybridSystemParser::FuncExpressionContext *ctx) override
virtual antlrcpp::Any visitExprFact (HybridSystemParser::ExprFactContext *ctx) override
virtual antlrcpp::Any visitExprFactNumber (HybridSystemParser::ExprFactNumberContext *ctx) override
virtual antlrcpp::Any visitExprFactRealNumber (HybridSystemParser::ExprFactRealNumberContext *ctx) override
virtual antlrcpp::Any visitExprFactName (HybridSystemParser::ExprFactNameContext *ctx) override
virtual antlrcpp::Any visitNonEmptySetExpression (HybridSystemParser::NonEmptySetExpressionContext *ctx) override
virtual antlrcpp::Any visitDictPairs (HybridSystemParser::DictPairsContext *ctx) override
virtual antlrcpp::Any visitOptElifExprs (HybridSystemParser::OptElifExprsContext *ctx) override
virtual antlrcpp::Any visitSwitchBody (HybridSystemParser::SwitchBodyContext *ctx) override
virtual antlrcpp::Any visitSwitchCases (HybridSystemParser::SwitchCasesContext *ctx) override
virtual antlrcpp::Any visitTypes (HybridSystemParser::TypesContext *ctx) override
virtual antlrcpp::Any visitType (HybridSystemParser::TypeContext *ctx) override
virtual antlrcpp::Any visitFields (HybridSystemParser::FieldsContext *ctx) override
virtual antlrcpp::Any visitField (HybridSystemParser::FieldContext *ctx) override
virtual antlrcpp::Any visitNameSet (HybridSystemParser::NameSetContext *ctx) override
virtual antlrcpp::Any visitNames (HybridSystemParser::NamesContext *ctx) override
virtual antlrcpp::Any visitName (HybridSystemParser::NameContext *ctx) override
virtual antlrcpp::Any visitOptSupKind (HybridSystemParser::OptSupKindContext *ctx) override
virtual antlrcpp::Any visitIdentifier (HybridSystemParser::IdentifierContext *ctx) override
virtual antlrcpp::Any visitStringToken (HybridSystemParser::StringTokenContext *ctx) override
virtual antlrcpp::Any visitStdLibFunction (HybridSystemParser::StdLibFunctionContext *ctx) override
virtual antlrcpp::Any visitLoc (HybridSystemParser::LocContext *ctx) override
virtual antlrcpp::Any visitLocId (HybridSystemParser::LocIdContext *ctx) override
virtual antlrcpp::Any visitLocationElements (HybridSystemParser::LocationElementsContext *ctx) override
virtual antlrcpp::Any visitLocElemInitialFlagExpr (HybridSystemParser::LocElemInitialFlagExprContext *ctx) override
virtual antlrcpp::Any visitLocElemInv (HybridSystemParser::LocElemInvContext *ctx) override
virtual antlrcpp::Any visitLocElemMarked (HybridSystemParser::LocElemMarkedContext *ctx) override
virtual antlrcpp::Any visitLocElemMarkedExpr (HybridSystemParser::LocElemMarkedExprContext *ctx) override
virtual antlrcpp::Any visitLocElemUrgent (HybridSystemParser::LocElemUrgentContext *ctx) override
virtual antlrcpp::Any visitOptEdgeGuard (HybridSystemParser::OptEdgeGuardContext *ctx) override
virtual antlrcpp::Any visitOptEdgeUrgent (HybridSystemParser::OptEdgeUrgentContext *ctx) override
virtual antlrcpp::Any visitOptEdgeUpdate (HybridSystemParser::OptEdgeUpdateContext *ctx) override
virtual antlrcpp::Any visitEdgeEvents (HybridSystemParser::EdgeEventsContext *ctx) override
virtual antlrcpp::Any visitEdgeEvent (HybridSystemParser::EdgeEventContext *ctx) override
virtual antlrcpp::Any visitInvariantDecls (HybridSystemParser::InvariantDeclsContext *ctx) override
virtual antlrcpp::Any visitOptElifUpdates (HybridSystemParser::OptElifUpdatesContext *ctx) override
virtual antlrcpp::Any visitOptElseUpdate (HybridSystemParser::OptElseUpdateContext *ctx) override
virtual antlrcpp::Any visitAdressables (HybridSystemParser::AdressablesContext *ctx) override
virtual antlrcpp::Any visitAdressableProj (HybridSystemParser::AdressableProjContext *ctx) override
virtual antlrcpp::Any visitAdressablePair (HybridSystemParser::AdressablePairContext *ctx) override
virtual antlrcpp::Any visitProjections (HybridSystemParser::ProjectionsContext *ctx) override
virtual antlrcpp::Any visitProjection (HybridSystemParser::ProjectionContext *ctx) override
virtual antlrcpp::Any visitOptIoDecls (HybridSystemParser::OptIoDeclsContext *ctx) override
virtual antlrcpp::Any visitIoDecls (HybridSystemParser::IoDeclsContext *ctx) override
virtual antlrcpp::Any visitSvgFile (HybridSystemParser::SvgFileContext *ctx) override
virtual antlrcpp::Any visitOptSvgFile (HybridSystemParser::OptSvgFileContext *ctx) override
virtual antlrcpp::Any visitSvgCopy (HybridSystemParser::SvgCopyContext *ctx) override
virtual antlrcpp::Any visitOptSvgCopyPre (HybridSystemParser::OptSvgCopyPreContext *ctx) override
virtual antlrcpp::Any visitOptSvgCopyPost (HybridSystemParser::OptSvgCopyPostContext *ctx) override
virtual antlrcpp::Any visitSvgMove (HybridSystemParser::SvgMoveContext *ctx) override
virtual antlrcpp::Any visitSvgOut (HybridSystemParser::SvgOutContext *ctx) override
virtual antlrcpp::Any visitSvgAttr (HybridSystemParser::SvgAttrContext *ctx) override
virtual antlrcpp::Any visitSvgIn (HybridSystemParser::SvgInContext *ctx) override
virtual antlrcpp::Any visitSvgInEvent (HybridSystemParser::SvgInEventContext *ctx) override
virtual antlrcpp::Any visitOptSvgInEventElifs (HybridSystemParser::OptSvgInEventElifsContext *ctx) override
virtual antlrcpp::Any visitSvgInEventElifs (HybridSystemParser::SvgInEventElifsContext *ctx) override
virtual antlrcpp::Any visitPrintFile (HybridSystemParser::PrintFileContext *ctx) override
virtual antlrcpp::Any visitPrint (HybridSystemParser::PrintContext *ctx) override
virtual antlrcpp::Any visitPrintTxt (HybridSystemParser::PrintTxtContext *ctx) override
virtual antlrcpp::Any visitOptPrintFors (HybridSystemParser::OptPrintForsContext *ctx) override
virtual antlrcpp::Any visitPrintFors (HybridSystemParser::PrintForsContext *ctx) override
virtual antlrcpp::Any visitPrintFor (HybridSystemParser::PrintForContext *ctx) override
virtual antlrcpp::Any visitOptPrintWhen (HybridSystemParser::OptPrintWhenContext *ctx) override
virtual antlrcpp::Any visitOptPrintFile (HybridSystemParser::OptPrintFileContext *ctx) override
Detailed Description
template<typename Number>
class hypro::CIFLocVisitor< Number >
Definition at line 18 of file CIFLocVisitor.h.
Constructor & Destructor Documentation
template<typename Number > hypro::CIFLocVisitor< Number >::CIFLocVisitor (std::vector< std::string > varVec)
Definition at line 6 of file CIFLocVisitor.tpp.
template<typename Number > hypro::CIFLocVisitor< Number >::~CIFLocVisitor ()
Definition at line 11 of file CIFLocVisitor.tpp.
Member Function Documentation
template<typename Number > antlrcpp::Any hypro::CIFLocVisitor< Number >::visitLocations (HybridSystemParser::LocationsContext * ctx) override virtual
Reimplemented from hypro::HybridSystemBaseVisitor.
Definition at line 14 of file CIFLocVisitor.tpp.
References hypro::HybridSystemParser::UpdateNonIfContext::adressable(), hypro::HybridSystemParser::LocElemEdgeToContext::coreEdge(), hypro::HybridSystemParser::LocElemLoopContext::coreEdge(), hypro::HybridSystemParser::LocElemEqsContext::equations(), hypro::HybridSystemParser::InvExprContext::expression(), hypro::HybridSystemParser::UpdateNonIfContext::expression(), hypro::Transition< Number >::getSource(), hypro::HybridSystemParser::LocIdElemContext::identifier(), hypro::HybridSystemParser::LocElemEdgeToContext::identifier(), hypro::HybridSystemParser::LocElemContext::locationElements(), hypro::HybridSystemParser::LocIdElemContext::locationElements(), hypro::Location< Number >::setName(), hypro::Transition< Number >::setSource(), and hypro::Transition< Number >::setTarget().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-cif/CIFLocVisitor.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-cif/CIFLocVisitor.tpp