HyPro: hypro::EllipsoidSupportFunction< Number > Class Template Reference
hypro::EllipsoidSupportFunction< Number > Class Template Reference
#include <EllipsoidSupportFunction.h>
Public Member Functions
EllipsoidSupportFunction (const EllipsoidSupportFunction< Number > &_orig)
EllipsoidSupportFunction (matrix_t< Number > _shapeMatrix)
~EllipsoidSupportFunction ()
unsigned dimension () const
matrix_t< Number > shapeMatrix () const
SF_TYPE type () const
template<typename N = Number, carl::DisableIf< std::is_same< N, double >> = carl::dummy>
EvaluationResult< Number > evaluate (const vector_t< Number > &_l) const
template<typename N = Number, carl::EnableIf< std::is_same< N, double >> = carl::dummy>
EvaluationResult< Number > evaluate (const vector_t< Number > &_l) const
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &_A) const
Evaluates the support function in the directions given in the passed matrix.
bool contains (const Point< Number > &_point) const
Check if point is contained in the support function.
bool contains (const vector_t< Number > &_point) const
Check if point is contained in the support function.
bool empty () const
Private Attributes
unsigned mDimension
matrix_t< Number > mShapeMatrix
SF_TYPE mType
Detailed Description
template<typename Number>
class hypro::EllipsoidSupportFunction< Number >
Definition at line 25 of file EllipsoidSupportFunction.h.
Constructor & Destructor Documentation
template<typename Number> hypro::EllipsoidSupportFunction< Number >::EllipsoidSupportFunction (const EllipsoidSupportFunction< Number > & _orig)
template<typename Number> hypro::EllipsoidSupportFunction< Number >::EllipsoidSupportFunction (matrix_t< Number > _shapeMatrix)
template<typename Number> hypro::EllipsoidSupportFunction< Number >::~EllipsoidSupportFunction ()
Member Function Documentation
template<typename Number> bool hypro::EllipsoidSupportFunction< Number >::contains (const Point< Number > & _point) const
Check if point is contained in the support function.
To check if the given point is contained in the support function we evaluate it in all its directions (uses multiEvaluate).
Parameters
_point The point to check.
Returns
True, if the point is inside the support function.
Referenced by hypro::EllipsoidSupportFunction< Number >::evaluate().
template<typename Number> bool hypro::EllipsoidSupportFunction< Number >::contains (const vector_t< Number > & _point) const
Check if point is contained in the support function.
To check if the given point is contained in the support function we evaluate it in all its directions (uses multiEvaluate).
Parameters
_point The point to check.
Returns
True, if the point is inside the support function.
template<typename Number> unsigned hypro::EllipsoidSupportFunction< Number >::dimension () const
Returns the dimension of the object.
Returns
template<typename Number> bool hypro::EllipsoidSupportFunction< Number >::empty () const
Referenced by hypro::EllipsoidSupportFunction< Number >::evaluate().
template<typename Number> template<typename N = Number, carl::DisableIf< std::is_same< N, double >> = carl::dummy> EvaluationResult<Number> hypro::EllipsoidSupportFunction< Number >::evaluate (const vector_t< Number > & _l) const inline
Evaluates the support function in the given direction.
Parameters
l
Returns
Definition at line 53 of file EllipsoidSupportFunction.h.
References hypro::EvaluationResult< Number >::errorCode, hypro::FEAS, hypro::EvaluationResult< Number >::optimumValue, and hypro::EvaluationResult< Number >::supportValue.
template<typename Number> template<typename N = Number, carl::EnableIf< std::is_same< N, double >> = carl::dummy> EvaluationResult<Number> hypro::EllipsoidSupportFunction< Number >::evaluate (const vector_t< Number > & _l) const inline
Definition at line 62 of file EllipsoidSupportFunction.h.
References hypro::EllipsoidSupportFunction< Number >::contains(), hypro::EllipsoidSupportFunction< Number >::empty(), hypro::EvaluationResult< Number >::errorCode, hypro::FEAS, hypro::EllipsoidSupportFunction< Number >::multiEvaluate(), hypro::EvaluationResult< Number >::optimumValue, and hypro::EvaluationResult< Number >::supportValue.
template<typename Number> std::vector<EvaluationResult<Number> > hypro::EllipsoidSupportFunction< Number >::multiEvaluate (const matrix_t< Number > & _A) const
Evaluates the support function in the directions given in the passed matrix.
Uses the standard evaluate method for multiple directions.
Parameters
_A Matrix holding the directions in which to evaluate.
Returns
Vector of support values.
Referenced by hypro::EllipsoidSupportFunction< Number >::evaluate().
template<typename Number> matrix_t<Number> hypro::EllipsoidSupportFunction< Number >::shapeMatrix () const
template<typename Number> SF_TYPE hypro::EllipsoidSupportFunction< Number >::type () const
Member Data Documentation
template<typename Number> unsigned hypro::EllipsoidSupportFunction< Number >::mDimension private
Definition at line 27 of file EllipsoidSupportFunction.h.
template<typename Number> matrix_t<Number> hypro::EllipsoidSupportFunction< Number >::mShapeMatrix private
Definition at line 28 of file EllipsoidSupportFunction.h.
template<typename Number> SF_TYPE hypro::EllipsoidSupportFunction< Number >::mType private
Definition at line 29 of file EllipsoidSupportFunction.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunction/EllipsoidSupportFunction.h