HyPro: hypro::CarlPolytopeT< Number, Converter, Setting > Class Template Reference
hypro::CarlPolytopeT< Number, Converter, Setting > Class Template Reference
State set representations
Class for representing polytopes as CArL-formulas.
#include <carlPolytope.h>
Public Types
using Settings = Setting
using NumberType = Number
Public Member Functions
CarlPolytopeT ()
used to indicate that the space dimension has been set externally, which overrides anything else.
CarlPolytopeT (const FormulaT< tNumber > &formula, std::size_t dimension=0)
CarlPolytopeT (const matrix_t< Number > &constraints, const vector_t< Number > &constants)
CarlPolytopeT (const std::vector< carl::Interval< Number >> &intervals)
CarlPolytopeT intersect (const CarlPolytopeT &rhs) const
CarlPolytopeT project (const std::vector< std::size_t > &dimensions) const
CarlPolytopeT assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const
CarlPolytopeT linearTransformation (const matrix_t< Number > &A) const
CarlPolytopeT minkowskiSum (const CarlPolytopeT &) const
CarlPolytopeT unite (const CarlPolytopeT &) const
CarlPolytopeT affineTransformation (const matrix_t< Number > &, const vector_t< Number > &) const
std::pair< CONTAINMENT, CarlPolytopeT > satisfiesHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const
bool contains (const Point< Number > &point) const
bool contains (const CarlPolytopeT &) const
EvaluationResult< Number > evaluate (const vector_t< Number > &) const
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &, bool) const
std::size_t dimension () const
const FormulaT< tNumber > & getFormula () const
const std::vector< Halfspace< Number > > & getHalfspaces () const
std::vector< carl::Interval< Number > > getIntervals () const
void setDimension (std::size_t d)
void addConstraint (const ConstraintT< tNumber > &constraint)
void addConstraints (const std::vector< ConstraintT< tNumber >> &constraints)
void addIntervalConstraints (const carl::Interval< Number > &intv, const carl::Variable &var)
void substituteVariable (carl::Variable oldVar, carl::Variable newVar)
std::vector< carl::Variable > getVariables () const
void eliminateVariable (carl::Variable var)
void eliminateVariables (const std::vector< carl::Variable > &vars)
void eliminateVariables (const QEQuery &vars)
std::vector< Point< Number > > vertices () const
matrix_t< Number > matrix () const
vector_t< Number > vector () const
std::size_t size () const
bool empty () const
CarlPolytopeT make_rectangular () const
void removeRedundancy ()
void reduceRepresentation ()
void choseOrder (QEQuery &)
Static Public Member Functions
static CarlPolytopeT Empty ()
static representation_name type ()
Static Public Attributes
static constexpr auto type_enum = representation_name::carl_polytope
Private Member Functions
void clearCache () const
void detectDimension () const
bool dimensionWasCorrectlySet () const
Should only be used in assertions to detect inconsistency in mDimension.
Private Member Functions inherited from hypro::GeometricObjectBase
GeometricObjectBase ()=default
GeometricObjectBase (const GeometricObjectBase &in)=default
GeometricObjectBase (GeometricObjectBase &&in)=default
GeometricObjectBase & operator= (const GeometricObjectBase &in)=default
GeometricObjectBase & operator= (GeometricObjectBase &&in)=default
GeometricObjectBase (SETSTATE state)
SETSTATE getEmptyState () const
Determines, whether the set is empty.
void setEmptyState (SETSTATE state)
Set the Empty State member - only to be used if you know what you are doing.
Private Attributes
FormulaT< tNumber > mFormula
std::vector< Halfspace< Number > > mHalfspaces
The description of the polytope as a conjunction of linear constraints.
std::size_t mDimension = 0
Caches transformed half-spaces.
bool mSpaceDimensionSet = false
Stores the state space dimension the polytope resides in.
Private Attributes inherited from hypro::GeometricObjectBase
SETSTATE mEmptyState = SETSTATE::UNKNOWN
Friends
std::ostream & operator<< (std::ostream &out, const CarlPolytopeT< Number, Converter, Setting > &in)
bool operator== (const CarlPolytopeT< Number, Converter, Setting > &lhs, const CarlPolytopeT< Number, Converter, Setting > &rhs)
bool operator!= (const CarlPolytopeT< Number, Converter, Setting > &lhs, const CarlPolytopeT< Number, Converter, Setting > &rhs)
Detailed Description
template<typename Number, typename Converter, typename Setting>
class hypro::CarlPolytopeT< Number, Converter, Setting >
Class for representing polytopes as CArL-formulas.
Template Parameters
Number
Converter
Setting @{
Definition at line 27 of file carlPolytope.h.
Member Typedef Documentation
template<typename Number, typename Converter, typename Setting> using hypro::CarlPolytopeT< Number, Converter, Setting >::NumberType = Number
Definition at line 31 of file carlPolytope.h.
template<typename Number, typename Converter, typename Setting> using hypro::CarlPolytopeT< Number, Converter, Setting >::Settings = Setting
Definition at line 30 of file carlPolytope.h.
Constructor & Destructor Documentation
template<typename Number, typename Converter, typename Setting> hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT () inline
used to indicate that the space dimension has been set externally, which overrides anything else.
Definition at line 40 of file carlPolytope.h.
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::affineTransformation(), hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT(), hypro::CarlPolytopeT< Number, Converter, Setting >::minkowskiSum(), and hypro::CarlPolytopeT< Number, Converter, Setting >::unite().
template<typename Number, typename Converter, typename Setting> hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT (const FormulaT< tNumber > & formula, std::size_t dimension = 0) inline
Definition at line 44 of file carlPolytope.h.
References assert(), hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT(), constraints(), hypro::CarlPolytopeT< Number, Converter, Setting >::detectDimension(), hypro::CarlPolytopeT< Number, Converter, Setting >::dimension(), hypro::CarlPolytopeT< Number, Converter, Setting >::Empty(), hypro::CarlPolytopeT< Number, Converter, Setting >::intersect(), intervals, hypro::CarlPolytopeT< Number, Converter, Setting >::project(), rhs, and vector.
template<typename Number, typename Converter, typename Setting> hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT (const matrix_t< Number > & constraints, const vector_t< Number > & constants)
template<typename Number, typename Converter, typename Setting> hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT (const std::vector< carl::Interval< Number >> & intervals)
Member Function Documentation
template<typename Number, typename Converter, typename Setting> void hypro::CarlPolytopeT< Number, Converter, Setting >::addConstraint (const ConstraintT< tNumber > & constraint)
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::setDimension().
template<typename Number, typename Converter, typename Setting> void hypro::CarlPolytopeT< Number, Converter, Setting >::addConstraints (const std::vector< ConstraintT< tNumber >> & constraints)
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::setDimension().
template<typename Number, typename Converter, typename Setting> void hypro::CarlPolytopeT< Number, Converter, Setting >::addIntervalConstraints (const carl::Interval< Number > & intv, const carl::Variable & var)
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::setDimension().
template<typename Number, typename Converter, typename Setting> CarlPolytopeT hypro::CarlPolytopeT< Number, Converter, Setting >::affineTransformation (const matrix_t< Number > & , const vector_t< Number > &) const inline
Definition at line 82 of file carlPolytope.h.
References assert(), hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT(), hypro::CarlPolytopeT< Number, Converter, Setting >::contains(), point, and hypro::CarlPolytopeT< Number, Converter, Setting >::satisfiesHalfspaces().
template<typename Number, typename Converter, typename Setting> CarlPolytopeT hypro::CarlPolytopeT< Number, Converter, Setting >::assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const inline
Definition at line 65 of file carlPolytope.h.
References A, and hypro::CarlPolytopeT< Number, Converter, Setting >::linearTransformation().
template<typename Number, typename Converter, typename Setting> void hypro::CarlPolytopeT< Number, Converter, Setting >::choseOrder (QEQuery &) inline
Definition at line 140 of file carlPolytope.h.
template<typename Number, typename Converter, typename Setting> void hypro::CarlPolytopeT< Number, Converter, Setting >::clearCache () const private
template<typename Number, typename Converter, typename Setting> bool hypro::CarlPolytopeT< Number, Converter, Setting >::contains (const Point< Number > & point) const
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::affineTransformation().
template<typename Number, typename Converter, typename Setting> bool hypro::CarlPolytopeT< Number, Converter, Setting >::contains (const CarlPolytopeT< Number, Converter, Setting > &) const inline
Definition at line 91 of file carlPolytope.h.
References assert().
template<typename Number, typename Converter, typename Setting> void hypro::CarlPolytopeT< Number, Converter, Setting >::detectDimension () const private
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT().
template<typename Number, typename Converter, typename Setting> std::size_t hypro::CarlPolytopeT< Number, Converter, Setting >::dimension () const inline
Definition at line 106 of file carlPolytope.h.
References hypro::CarlPolytopeT< Number, Converter, Setting >::mDimension.
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT(), and hypro::genericIntervalAssignmentVisitor< T, Number >::operator()().
template<typename Number, typename Converter, typename Setting> bool hypro::CarlPolytopeT< Number, Converter, Setting >::dimensionWasCorrectlySet () const private
Should only be used in assertions to detect inconsistency in mDimension.
template<typename Number, typename Converter, typename Setting> void hypro::CarlPolytopeT< Number, Converter, Setting >::eliminateVariable (carl::Variable var)
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::setDimension().
template<typename Number, typename Converter, typename Setting> void hypro::CarlPolytopeT< Number, Converter, Setting >::eliminateVariables (const std::vector< carl::Variable > & vars)
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::setDimension().
template<typename Number, typename Converter, typename Setting> void hypro::CarlPolytopeT< Number, Converter, Setting >::eliminateVariables (const QEQuery & vars)
template<typename Number, typename Converter, typename Setting> static CarlPolytopeT hypro::CarlPolytopeT< Number, Converter, Setting >::Empty () static
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT().
template<typename Number, typename Converter, typename Setting> bool hypro::CarlPolytopeT< Number, Converter, Setting >::empty () const
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::size().
template<typename Number, typename Converter, typename Setting> EvaluationResult<Number> hypro::CarlPolytopeT< Number, Converter, Setting >::evaluate (const vector_t< Number > &) const inline
Definition at line 96 of file carlPolytope.h.
References assert().
template<typename Number, typename Converter, typename Setting> const FormulaT<tNumber>& hypro::CarlPolytopeT< Number, Converter, Setting >::getFormula () const inline
Definition at line 110 of file carlPolytope.h.
References hypro::CarlPolytopeT< Number, Converter, Setting >::getHalfspaces(), hypro::CarlPolytopeT< Number, Converter, Setting >::getIntervals(), and hypro::CarlPolytopeT< Number, Converter, Setting >::mFormula.
template<typename Number, typename Converter, typename Setting> const std::vector<Halfspace<Number> >& hypro::CarlPolytopeT< Number, Converter, Setting >::getHalfspaces () const
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::getFormula().
template<typename Number, typename Converter, typename Setting> std::vector<carl::Interval<Number> > hypro::CarlPolytopeT< Number, Converter, Setting >::getIntervals () const
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::getFormula().
template<typename Number, typename Converter, typename Setting> std::vector<carl::Variable> hypro::CarlPolytopeT< Number, Converter, Setting >::getVariables () const
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::setDimension().
template<typename Number, typename Converter, typename Setting> CarlPolytopeT hypro::CarlPolytopeT< Number, Converter, Setting >::intersect (const CarlPolytopeT< Number, Converter, Setting > & rhs) const
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT().
template<typename Number, typename Converter, typename Setting> CarlPolytopeT hypro::CarlPolytopeT< Number, Converter, Setting >::linearTransformation (const matrix_t< Number > & A) const
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::assignIntervals().
template<typename Number, typename Converter, typename Setting> CarlPolytopeT hypro::CarlPolytopeT< Number, Converter, Setting >::make_rectangular () const
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::type().
template<typename Number, typename Converter, typename Setting> matrix_t<Number> hypro::CarlPolytopeT< Number, Converter, Setting >::matrix () const
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::setDimension().
template<typename Number, typename Converter, typename Setting> CarlPolytopeT hypro::CarlPolytopeT< Number, Converter, Setting >::minkowskiSum (const CarlPolytopeT< Number, Converter, Setting > &) const inline
Definition at line 72 of file carlPolytope.h.
References assert(), and hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT().
template<typename Number, typename Converter, typename Setting> std::vector<EvaluationResult<Number> > hypro::CarlPolytopeT< Number, Converter, Setting >::multiEvaluate (const matrix_t< Number > & , bool) const inline
Definition at line 101 of file carlPolytope.h.
References assert().
template<typename Number, typename Converter, typename Setting> CarlPolytopeT hypro::CarlPolytopeT< Number, Converter, Setting >::project (const std::vector< std::size_t > & dimensions) const
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT().
template<typename Number, typename Converter, typename Setting> void hypro::CarlPolytopeT< Number, Converter, Setting >::reduceRepresentation ()
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::type().
template<typename Number, typename Converter, typename Setting> void hypro::CarlPolytopeT< Number, Converter, Setting >::removeRedundancy ()
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::type().
template<typename Number, typename Converter, typename Setting> std::pair<CONTAINMENT, CarlPolytopeT> hypro::CarlPolytopeT< Number, Converter, Setting >::satisfiesHalfspaces (const matrix_t< Number > & _mat, const vector_t< Number > & _vec) const
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::affineTransformation().
template<typename Number, typename Converter, typename Setting> void hypro::CarlPolytopeT< Number, Converter, Setting >::setDimension (std::size_t d) inline
Definition at line 114 of file carlPolytope.h.
References hypro::CarlPolytopeT< Number, Converter, Setting >::addConstraint(), hypro::CarlPolytopeT< Number, Converter, Setting >::addConstraints(), hypro::CarlPolytopeT< Number, Converter, Setting >::addIntervalConstraints(), d, hypro::CarlPolytopeT< Number, Converter, Setting >::eliminateVariable(), hypro::CarlPolytopeT< Number, Converter, Setting >::eliminateVariables(), hypro::CarlPolytopeT< Number, Converter, Setting >::getVariables(), hypro::CarlPolytopeT< Number, Converter, Setting >::matrix(), hypro::CarlPolytopeT< Number, Converter, Setting >::substituteVariable(), vector, hypro::CarlPolytopeT< Number, Converter, Setting >::vector(), and hypro::CarlPolytopeT< Number, Converter, Setting >::vertices().
template<typename Number, typename Converter, typename Setting> std::size_t hypro::CarlPolytopeT< Number, Converter, Setting >::size () const inline
Definition at line 132 of file carlPolytope.h.
References hypro::CarlPolytopeT< Number, Converter, Setting >::empty().
template<typename Number, typename Converter, typename Setting> void hypro::CarlPolytopeT< Number, Converter, Setting >::substituteVariable (carl::Variable oldVar, carl::Variable newVar)
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::setDimension().
template<typename Number, typename Converter, typename Setting> static representation_name hypro::CarlPolytopeT< Number, Converter, Setting >::type () inline static
Definition at line 134 of file carlPolytope.h.
References hypro::CarlPolytopeT< Number, Converter, Setting >::make_rectangular(), hypro::CarlPolytopeT< Number, Converter, Setting >::reduceRepresentation(), and hypro::CarlPolytopeT< Number, Converter, Setting >::removeRedundancy().
template<typename Number, typename Converter, typename Setting> CarlPolytopeT hypro::CarlPolytopeT< Number, Converter, Setting >::unite (const CarlPolytopeT< Number, Converter, Setting > &) const inline
Definition at line 77 of file carlPolytope.h.
References assert(), and hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT().
template<typename Number, typename Converter, typename Setting> vector_t<Number> hypro::CarlPolytopeT< Number, Converter, Setting >::vector () const
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::setDimension().
template<typename Number, typename Converter, typename Setting> std::vector<Point<Number> > hypro::CarlPolytopeT< Number, Converter, Setting >::vertices () const
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::setDimension().
Friends And Related Function Documentation
template<typename Number, typename Converter, typename Setting> bool operator!= (const CarlPolytopeT< Number, Converter, Setting > & lhs, const CarlPolytopeT< Number, Converter, Setting > & rhs) friend
Definition at line 152 of file carlPolytope.h.
template<typename Number, typename Converter, typename Setting> std::ostream& operator<< (std::ostream & out, const CarlPolytopeT< Number, Converter, Setting > & in) friend
Definition at line 143 of file carlPolytope.h.
template<typename Number, typename Converter, typename Setting> bool operator== (const CarlPolytopeT< Number, Converter, Setting > & lhs, const CarlPolytopeT< Number, Converter, Setting > & rhs) friend
Definition at line 148 of file carlPolytope.h.
Member Data Documentation
template<typename Number, typename Converter, typename Setting> std::size_t hypro::CarlPolytopeT< Number, Converter, Setting >::mDimension = 0 mutable private
Caches transformed half-spaces.
Definition at line 37 of file carlPolytope.h.
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::dimension().
template<typename Number, typename Converter, typename Setting> FormulaT<tNumber> hypro::CarlPolytopeT< Number, Converter, Setting >::mFormula private
Definition at line 35 of file carlPolytope.h.
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::getFormula().
template<typename Number, typename Converter, typename Setting> std::vector<Halfspace<Number> > hypro::CarlPolytopeT< Number, Converter, Setting >::mHalfspaces mutable private
The description of the polytope as a conjunction of linear constraints.
Definition at line 36 of file carlPolytope.h.
template<typename Number, typename Converter, typename Setting> bool hypro::CarlPolytopeT< Number, Converter, Setting >::mSpaceDimensionSet = false mutable private
Stores the state space dimension the polytope resides in.
Definition at line 38 of file carlPolytope.h.
template<typename Number, typename Converter, typename Setting> constexpr auto hypro::CarlPolytopeT< Number, Converter, Setting >::type_enum = representation_name::carl_polytope static
Definition at line 32 of file carlPolytope.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/Polytopes/carlPolytope/carlPolytope.h