HyPro: hypro::ProjectOp< Number, Converter, Setting > Class Template Reference
hypro::ProjectOp< Number, Converter, Setting > Class Template Reference
#include <ProjectOp.h>
Public Member Functions
ProjectOp ()=delete
ProjectOp (const SupportFunctionNewT< Number, Converter, Setting > &origin, const std::vector< std::size_t > &dims)
ProjectOp (const ProjectData &d)
~ProjectOp ()
SFNEW_TYPE getType () const override
unsigned getOriginCount () const override
std::size_t getDimension () const override
std::vector< std::size_t > getDimensions () const
RGNData * getData () const override
void setDimension (const std::size_t d) override
matrix_t< Number > transform (const matrix_t< Number > &param) const override
std::vector< EvaluationResult< Number > > compute (const matrix_t< Number > &, bool) const override
std::vector< EvaluationResult< Number > > aggregate (std::vector< std::vector< EvaluationResult< Number >>> &resultStackBack, const matrix_t< Number > &) const override
bool empty (const std::vector< bool > &childrenEmpty) const override
Point< Number > supremumPoint (std::vector< Point< Number >> &points) const override
vector_t< Number > reverseOp (const vector_t< Number > &point) const override
bool contains (const std::vector< bool > &v, const vector_t< Number > &) const override
std::vector< std::size_t > intersectDims (const std::vector< std::vector< std::size_t >> &dims) const override
Public Member Functions inherited from hypro::RootGrowNode< Number, Converter, Setting >
RootGrowNode ()
virtual ~RootGrowNode ()
virtual PointerVec getChildren () const
virtual PointerVec & rGetChildren ()
virtual SETSTATE isEmpty () const
virtual LeafData getLeafData () const
void addToChildren (const std::shared_ptr< RootGrowNode > &rhs)
void clearChildren ()
virtual void print (std::ostream &ostr) const
virtual bool empty () const
virtual Point< Number > supremumPoint () const
virtual bool contains (const vector_t< Number > &) const
Private Types
using PointerVec = typename RootGrowNode< Number, Converter, Setting >::PointerVec
Private Attributes
SFNEW_TYPE type = SFNEW_TYPE::PROJECTOP
unsigned originCount
PointerVec mChildren
std::size_t mDimension
std::vector< std::size_t > dimensions
Additional Inherited Members
Public Types inherited from hypro::RootGrowNode< Number, Converter, Setting >
using PointerVec = std::vector< std::shared_ptr< RootGrowNode< Number, Converter, Setting >>>
Protected Attributes inherited from hypro::RootGrowNode< Number, Converter, Setting >
SFNEW_TYPE mType = NODE
unsigned originCount = 0
PointerVec mChildren = PointerVec()
std::size_t mDimension = 0
SETSTATE mEmptyState = SETSTATE::UNKNOWN
Detailed Description
template<typename Number, typename Converter, typename Setting>
class hypro::ProjectOp< Number, Converter, Setting >
Definition at line 32 of file ProjectOp.h.
Member Typedef Documentation
template<typename Number , typename Converter , typename Setting > using hypro::ProjectOp< Number, Converter, Setting >::PointerVec = typename RootGrowNode<Number, Converter, Setting>::PointerVec private
Definition at line 36 of file ProjectOp.h.
Constructor & Destructor Documentation
template<typename Number , typename Converter , typename Setting > hypro::ProjectOp< Number, Converter, Setting >::ProjectOp () delete
template<typename Number , typename Converter , typename Setting > hypro::ProjectOp< Number, Converter, Setting >::ProjectOp (const SupportFunctionNewT< Number, Converter, Setting > & origin, const std::vector< std::size_t > & dims) inline
Definition at line 54 of file ProjectOp.h.
References hypro::SupportFunctionNewT< Number, Converter, Setting >::addOperation().
template<typename Number , typename Converter , typename Setting > hypro::ProjectOp< Number, Converter, Setting >::ProjectOp (const ProjectData & d) inline
Definition at line 62 of file ProjectOp.h.
References d, and hypro::ProjectData::dimensions.
template<typename Number , typename Converter , typename Setting > hypro::ProjectOp< Number, Converter, Setting >::~ProjectOp () inline
Definition at line 68 of file ProjectOp.h.
Member Function Documentation
template<typename Number , typename Converter , typename Setting > std::vector<EvaluationResult<Number> > hypro::ProjectOp< Number, Converter, Setting >::aggregate (std::vector< std::vector< EvaluationResult< Number >>> & resultStackBack, const matrix_t< Number > &) const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 103 of file ProjectOp.h.
References assert().
template<typename Number , typename Converter , typename Setting > std::vector<EvaluationResult<Number> > hypro::ProjectOp< Number, Converter, Setting >::compute (const matrix_t< Number > & , bool) const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 97 of file ProjectOp.h.
References assert().
template<typename Number , typename Converter , typename Setting > bool hypro::ProjectOp< Number, Converter, Setting >::contains (const std::vector< bool > & v, const vector_t< Number > &) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 133 of file ProjectOp.h.
References assert().
template<typename Number , typename Converter , typename Setting > bool hypro::ProjectOp< Number, Converter, Setting >::empty (const std::vector< bool > & childrenEmpty) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 109 of file ProjectOp.h.
References assert().
template<typename Number , typename Converter , typename Setting > RGNData* hypro::ProjectOp< Number, Converter, Setting >::getData () const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 76 of file ProjectOp.h.
References hypro::ProjectData::ProjectData().
template<typename Number , typename Converter , typename Setting > std::size_t hypro::ProjectOp< Number, Converter, Setting >::getDimension () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 74 of file ProjectOp.h.
template<typename Number , typename Converter , typename Setting > std::vector<std::size_t> hypro::ProjectOp< Number, Converter, Setting >::getDimensions () const inline
Definition at line 75 of file ProjectOp.h.
References hypro::ProjectData::dimensions.
template<typename Number , typename Converter , typename Setting > unsigned hypro::ProjectOp< Number, Converter, Setting >::getOriginCount () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 73 of file ProjectOp.h.
template<typename Number , typename Converter , typename Setting > SFNEW_TYPE hypro::ProjectOp< Number, Converter, Setting >::getType () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 72 of file ProjectOp.h.
References type.
template<typename Number , typename Converter , typename Setting > std::vector<std::size_t> hypro::ProjectOp< Number, Converter, Setting >::intersectDims (const std::vector< std::vector< std::size_t >> & dims) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 140 of file ProjectOp.h.
References assert(), d, dims, and res.
template<typename Number , typename Converter , typename Setting > vector_t<Number> hypro::ProjectOp< Number, Converter, Setting >::reverseOp (const vector_t< Number > & point) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 128 of file ProjectOp.h.
References point.
template<typename Number , typename Converter , typename Setting > void hypro::ProjectOp< Number, Converter, Setting >::setDimension (const std::size_t d) inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 77 of file ProjectOp.h.
References d.
template<typename Number , typename Converter , typename Setting > Point<Number> hypro::ProjectOp< Number, Converter, Setting >::supremumPoint (std::vector< Point< Number >> & points) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 116 of file ProjectOp.h.
References assert(), points, and tmp.
template<typename Number , typename Converter , typename Setting > matrix_t<Number> hypro::ProjectOp< Number, Converter, Setting >::transform (const matrix_t< Number > & param) const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 82 of file ProjectOp.h.
References assert().
Member Data Documentation
template<typename Number , typename Converter , typename Setting > std::vector<std::size_t> hypro::ProjectOp< Number, Converter, Setting >::dimensions private
Definition at line 47 of file ProjectOp.h.
template<typename Number , typename Converter , typename Setting > PointerVec hypro::ProjectOp< Number, Converter, Setting >::mChildren private
Definition at line 42 of file ProjectOp.h.
template<typename Number , typename Converter , typename Setting > std::size_t hypro::ProjectOp< Number, Converter, Setting >::mDimension private
Definition at line 43 of file ProjectOp.h.
template<typename Number , typename Converter , typename Setting > unsigned hypro::ProjectOp< Number, Converter, Setting >::originCount private
Definition at line 41 of file ProjectOp.h.
template<typename Number , typename Converter , typename Setting > SFNEW_TYPE hypro::ProjectOp< Number, Converter, Setting >::type = SFNEW_TYPE::PROJECTOP private
Definition at line 40 of file ProjectOp.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunctionNew/ProjectOp.h