HyPro: hypro::HybridAutomatonParser::TransitionContext Class Reference
hypro::HybridAutomatonParser::TransitionContext Class Reference
#include <HybridAutomatonParser.h>
Public Member Functions
TransitionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
FromtoContext * fromto ()
std::vector< UrgentContext * > urgent ()
UrgentContext * urgent (size_t i)
std::vector< GuardContext * > guard ()
GuardContext * guard (size_t i)
std::vector< LabelsContext * > labels ()
LabelsContext * labels (size_t i)
std::vector< ResetfctContext * > resetfct ()
ResetfctContext * resetfct (size_t i)
std::vector< AggregationContext * > aggregation ()
AggregationContext * aggregation (size_t i)
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Detailed Description
Definition at line 479 of file HybridAutomatonParser.h.
Constructor & Destructor Documentation
HybridAutomatonParser::TransitionContext::TransitionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 1989 of file HybridAutomatonParser.cpp.
Member Function Documentation
antlrcpp::Any HybridAutomatonParser::TransitionContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
Definition at line 2042 of file HybridAutomatonParser.cpp.
std::vector< HybridAutomatonParser::AggregationContext * > HybridAutomatonParser::TransitionContext::aggregation ()
Definition at line 2029 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::transition().
HybridAutomatonParser::AggregationContext * HybridAutomatonParser::TransitionContext::aggregation (size_t i)
Definition at line 2033 of file HybridAutomatonParser.cpp.
References i.
HybridAutomatonParser::FromtoContext * HybridAutomatonParser::TransitionContext::fromto ()
Definition at line 1993 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::transition().
size_t HybridAutomatonParser::TransitionContext::getRuleIndex () const override virtual
Definition at line 2038 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::RuleTransition.
std::vector< HybridAutomatonParser::GuardContext * > HybridAutomatonParser::TransitionContext::guard ()
Definition at line 2005 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::transition().
HybridAutomatonParser::GuardContext * HybridAutomatonParser::TransitionContext::guard (size_t i)
Definition at line 2009 of file HybridAutomatonParser.cpp.
References i.
std::vector< HybridAutomatonParser::LabelsContext * > HybridAutomatonParser::TransitionContext::labels ()
Definition at line 2013 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::transition().
HybridAutomatonParser::LabelsContext * HybridAutomatonParser::TransitionContext::labels (size_t i)
Definition at line 2017 of file HybridAutomatonParser.cpp.
References i.
std::vector< HybridAutomatonParser::ResetfctContext * > HybridAutomatonParser::TransitionContext::resetfct ()
Definition at line 2021 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::transition().
HybridAutomatonParser::ResetfctContext * HybridAutomatonParser::TransitionContext::resetfct (size_t i)
Definition at line 2025 of file HybridAutomatonParser.cpp.
References i.
std::vector< HybridAutomatonParser::UrgentContext * > HybridAutomatonParser::TransitionContext::urgent ()
Definition at line 1997 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::transition().
HybridAutomatonParser::UrgentContext * HybridAutomatonParser::TransitionContext::urgent (size_t i)
Definition at line 2001 of file HybridAutomatonParser.cpp.
References i.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HybridAutomatonParser.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HybridAutomatonParser.cpp