HyPro: hypro::HybridAutomatonParser Class Reference
hypro::HybridAutomatonParser Class Reference
Classes
class ActivitiesContext
class AdaptiveordersContext
class AggregationContext
class AllocationContext
class ConnectorContext
class ConstantdeclarationContext
class ConstantexprContext
class ConstraintContext
class ConstrsetContext
class CutoffContext
class EquationContext
class ExpressionContext
class FilenameContext
class FixedordersContext
class FixedstepsContext
class FromtoContext
class GbadstateContext
class GuardContext
class IdentityContext
class InitContext
class InitstateContext
class IntervalContext
class IntervalexprContext
class InvariantsContext
class JumpsContext
class LabelsContext
class LbadstateContext
class LocationContext
class MaxjumpsContext
class ModesContext
class PlotsettingContext
class PolynomContext
class PrecisionContext
class PrintContext
class QrprecondContext
class RemainderContext
class ReplacedexprContext
class ResetfctContext
class SettingContext
class StartContext
class TermContext
class TimeContext
class TransitionContext
class UnsafesetContext
class UrgentContext
class VardeclarationContext
Public Types
enum {
T__0 = 1, T__1 = 2, T__2 = 3, T__3 = 4,
T__4 = 5, T__5 = 6, T__6 = 7, T__7 = 8,
T__8 = 9, T__9 = 10, T__10 = 11, T__11 = 12,
T__12 = 13, T__13 = 14, T__14 = 15, T__15 = 16,
T__16 = 17, T__17 = 18, T__18 = 19, T__19 = 20,
T__20 = 21, T__21 = 22, T__22 = 23, POLY = 24,
LINEAR = 25, NONLINEAR = 26, NONPOLY = 27, LTI = 28,
ODE = 29, IN = 30, TRUE = 31, FALSE = 32,
PAR = 33, JUMPS = 34, URGENT = 35, GUARD = 36,
RESET = 37, PARALLELOTOPE = 38, BOX = 39, JUMP = 40,
DEFINE = 41, COMMENT = 42, EQUALS = 43, BOOLRELATION = 44,
PLUS = 45, MINUS = 46, TIMES = 47, DIVIDE = 48,
SBOPEN = 49, SBCLOSE = 50, CBOPEN = 51, CBCLOSE = 52,
RBOPEN = 53, RBCLOSE = 54, COMMA = 55, NUMBER = 56,
CONSTANT = 57, VARIABLE = 58, WS = 59, INTERVALAGG = 60,
EXPONENTIAL = 61
}
enum {
RuleStart = 0, RuleVardeclaration = 1, RuleConstantdeclaration = 2, RuleModes = 3,
RuleLocation = 4, RuleActivities = 5, RuleInvariants = 6, RuleReplacedexpr = 7,
RuleConstantexpr = 8, RuleConnector = 9, RuleTerm = 10, RulePolynom = 11,
RuleExpression = 12, RuleEquation = 13, RuleConstraint = 14, RuleInterval = 15,
RuleIntervalexpr = 16, RuleConstrset = 17, RuleInit = 18, RuleInitstate = 19,
RuleUnsafeset = 20, RuleLbadstate = 21, RuleGbadstate = 22, RuleJumps = 23,
RuleTransition = 24, RuleFromto = 25, RuleUrgent = 26, RuleGuard = 27,
RuleLabels = 28, RuleAllocation = 29, RuleResetfct = 30, RuleAggregation = 31,
RuleSetting = 32, RuleFixedsteps = 33, RuleTime = 34, RulePlotsetting = 35,
RuleFilename = 36, RuleMaxjumps = 37, RulePrint = 38, RuleRemainder = 39,
RuleIdentity = 40, RuleQrprecond = 41, RuleFixedorders = 42, RuleAdaptiveorders = 43,
RuleCutoff = 44, RulePrecision = 45
}
Public Member Functions
HybridAutomatonParser (antlr4::TokenStream *input)
~HybridAutomatonParser ()
virtual std::string getGrammarFileName () const override
virtual const antlr4::atn::ATN & getATN () const override
virtual const std::vector< std::string > & getTokenNames () const override
virtual const std::vector< std::string > & getRuleNames () const override
virtual antlr4::dfa::Vocabulary & getVocabulary () const override
const std::map< std::string, std::string > & getConstants () const
StartContext * start ()
VardeclarationContext * vardeclaration ()
ConstantdeclarationContext * constantdeclaration ()
ModesContext * modes ()
LocationContext * location ()
ActivitiesContext * activities ()
InvariantsContext * invariants ()
ReplacedexprContext * replacedexpr ()
ConstantexprContext * constantexpr ()
ConnectorContext * connector ()
TermContext * term ()
PolynomContext * polynom ()
ExpressionContext * expression ()
EquationContext * equation ()
ConstraintContext * constraint ()
IntervalContext * interval ()
IntervalexprContext * intervalexpr ()
ConstrsetContext * constrset ()
InitContext * init ()
InitstateContext * initstate ()
UnsafesetContext * unsafeset ()
LbadstateContext * lbadstate ()
GbadstateContext * gbadstate ()
JumpsContext * jumps ()
TransitionContext * transition ()
FromtoContext * fromto ()
UrgentContext * urgent ()
GuardContext * guard ()
LabelsContext * labels ()
AllocationContext * allocation ()
ResetfctContext * resetfct ()
AggregationContext * aggregation ()
SettingContext * setting ()
FixedstepsContext * fixedsteps ()
TimeContext * time ()
PlotsettingContext * plotsetting ()
FilenameContext * filename ()
MaxjumpsContext * maxjumps ()
PrintContext * print ()
RemainderContext * remainder ()
IdentityContext * identity ()
QrprecondContext * qrprecond ()
FixedordersContext * fixedorders ()
AdaptiveordersContext * adaptiveorders ()
CutoffContext * cutoff ()
PrecisionContext * precision ()
Detailed Description
Definition at line 17 of file HybridAutomatonParser.h.
Member Enumeration Documentation
anonymous enum
Enumerator
T__0
T__1
T__2
T__3
T__4
T__5
T__6
T__7
T__8
T__9
T__10
T__11
T__12
T__13
T__14
T__15
T__16
T__17
T__18
T__19
T__20
T__21
T__22
POLY
LINEAR
NONLINEAR
NONPOLY
LTI
ODE
IN
TRUE
FALSE
PAR
JUMPS
URGENT
GUARD
RESET
PARALLELOTOPE
BOX
JUMP
DEFINE
COMMENT
EQUALS
BOOLRELATION
PLUS
MINUS
TIMES
DIVIDE
SBOPEN
SBCLOSE
CBOPEN
CBCLOSE
RBOPEN
RBCLOSE
COMMA
NUMBER
CONSTANT
VARIABLE
WS
INTERVALAGG
EXPONENTIAL
Definition at line 19 of file HybridAutomatonParser.h.
anonymous enum
Enumerator
RuleStart
RuleVardeclaration
RuleConstantdeclaration
RuleModes
RuleLocation
RuleActivities
RuleInvariants
RuleReplacedexpr
RuleConstantexpr
RuleConnector
RuleTerm
RulePolynom
RuleExpression
RuleEquation
RuleConstraint
RuleInterval
RuleIntervalexpr
RuleConstrset
RuleInit
RuleInitstate
RuleUnsafeset
RuleLbadstate
RuleGbadstate
RuleJumps
RuleTransition
RuleFromto
RuleUrgent
RuleGuard
RuleLabels
RuleAllocation
RuleResetfct
RuleAggregation
RuleSetting
RuleFixedsteps
RuleTime
RulePlotsetting
RuleFilename
RuleMaxjumps
RulePrint
RuleRemainder
RuleIdentity
RuleQrprecond
RuleFixedorders
RuleAdaptiveorders
RuleCutoff
RulePrecision
Definition at line 32 of file HybridAutomatonParser.h.
Constructor & Destructor Documentation
HybridAutomatonParser::HybridAutomatonParser (antlr4::TokenStream * input)
Definition at line 18 of file HybridAutomatonParser.cpp.
HybridAutomatonParser::~HybridAutomatonParser ()
Definition at line 22 of file HybridAutomatonParser.cpp.
Member Function Documentation
HybridAutomatonParser::ActivitiesContext * HybridAutomatonParser::activities ()
Definition at line 540 of file HybridAutomatonParser.cpp.
References CBCLOSE, CBOPEN, hypro::HybridAutomatonParser::ActivitiesContext::equation(), hypro::HybridAutomatonParser::ActivitiesContext::intervalexpr(), LINEAR, LTI, NONLINEAR, NONPOLY, NUMBER, ODE, POLY, RuleActivities, and VARIABLE.
HybridAutomatonParser::AdaptiveordersContext * HybridAutomatonParser::adaptiveorders ()
Definition at line 3410 of file HybridAutomatonParser.cpp.
References CBCLOSE, CBOPEN, COMMA, NUMBER, RuleAdaptiveorders, T__18, T__19, and T__20.
HybridAutomatonParser::AggregationContext * HybridAutomatonParser::aggregation ()
Definition at line 2622 of file HybridAutomatonParser.cpp.
References BOX, CBCLOSE, CBOPEN, INTERVALAGG, PARALLELOTOPE, and RuleAggregation.
HybridAutomatonParser::AllocationContext * HybridAutomatonParser::allocation ()
Definition at line 2484 of file HybridAutomatonParser.cpp.
References DEFINE, hypro::HybridAutomatonParser::AllocationContext::interval(), MINUS, NUMBER, PLUS, hypro::HybridAutomatonParser::AllocationContext::polynom(), RuleAllocation, SBOPEN, and VARIABLE.
HybridAutomatonParser::ConnectorContext * HybridAutomatonParser::connector ()
Definition at line 865 of file HybridAutomatonParser.cpp.
References MINUS, PLUS, and RuleConnector.
HybridAutomatonParser::ConstantdeclarationContext * HybridAutomatonParser::constantdeclaration ()
Definition at line 281 of file HybridAutomatonParser.cpp.
References CBCLOSE, CBOPEN, CONSTANT, hypro::HybridAutomatonParser::ConstantdeclarationContext::constantexpr(), MINUS, NUMBER, PAR, hypro::HybridAutomatonParser::ConstantdeclarationContext::replacedexpr(), and RuleConstantdeclaration.
HybridAutomatonParser::ConstantexprContext * HybridAutomatonParser::constantexpr ()
Definition at line 794 of file HybridAutomatonParser.cpp.
References CONSTANT, hypro::HybridAutomatonParser::ConstantexprContext::constantToken, EQUALS, MINUS, hypro::HybridAutomatonParser::ConstantexprContext::minusToken, NUMBER, hypro::HybridAutomatonParser::ConstantexprContext::numberToken, and RuleConstantexpr.
HybridAutomatonParser::ConstraintContext * HybridAutomatonParser::constraint ()
Definition at line 1385 of file HybridAutomatonParser.cpp.
References BOOLRELATION, EQUALS, hypro::HybridAutomatonParser::ConstraintContext::expression(), and RuleConstraint.
HybridAutomatonParser::ConstrsetContext * HybridAutomatonParser::constrset ()
Definition at line 1626 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::ConstrsetContext::constraint(), FALSE, hypro::HybridAutomatonParser::ConstrsetContext::intervalexpr(), MINUS, NUMBER, PLUS, RBOPEN, RuleConstrset, TRUE, and VARIABLE.
HybridAutomatonParser::CutoffContext * HybridAutomatonParser::cutoff ()
Definition at line 3468 of file HybridAutomatonParser.cpp.
References EXPONENTIAL, RuleCutoff, and T__21.
HybridAutomatonParser::EquationContext * HybridAutomatonParser::equation ()
Definition at line 1312 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::EquationContext::connector(), EQUALS, hypro::HybridAutomatonParser::EquationContext::expression(), hypro::HybridAutomatonParser::EquationContext::interval(), MINUS, PLUS, RuleEquation, and VARIABLE.
HybridAutomatonParser::ExpressionContext * HybridAutomatonParser::expression ()
Definition at line 1184 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::ExpressionContext::connector(), DIVIDE, hypro::HybridAutomatonParser::ExpressionContext::expression(), MINUS, NUMBER, PLUS, hypro::HybridAutomatonParser::ExpressionContext::polynom(), RBCLOSE, RBOPEN, RuleExpression, hypro::HybridAutomatonParser::ExpressionContext::term(), TIMES, and VARIABLE.
HybridAutomatonParser::FilenameContext * HybridAutomatonParser::filename ()
Definition at line 3096 of file HybridAutomatonParser.cpp.
References RuleFilename, T__11, and VARIABLE.
HybridAutomatonParser::FixedordersContext * HybridAutomatonParser::fixedorders ()
Definition at line 3360 of file HybridAutomatonParser.cpp.
References NUMBER, RuleFixedorders, and T__17.
HybridAutomatonParser::FixedstepsContext * HybridAutomatonParser::fixedsteps ()
Definition at line 2935 of file HybridAutomatonParser.cpp.
References NUMBER, RuleFixedsteps, and T__8.
HybridAutomatonParser::FromtoContext * HybridAutomatonParser::fromto ()
Definition at line 2257 of file HybridAutomatonParser.cpp.
References JUMP, RuleFromto, and VARIABLE.
HybridAutomatonParser::GbadstateContext * HybridAutomatonParser::gbadstate ()
Definition at line 2004 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::GbadstateContext::constrset(), and RuleGbadstate.
virtual const antlr4::atn::ATN& hypro::HybridAutomatonParser::getATN () const inline override virtual
Definition at line 51 of file HybridAutomatonParser.h.
const std::map<std::string, std::string>& hypro::HybridAutomatonParser::getConstants () const inline
Definition at line 57 of file HybridAutomatonParser.h.
Referenced by hypro::parser::createFlowstarParseTree(), hypro::parseFlowstarFile< double >(), and hypro::parseFlowstarFile< mpq_class >().
std::string HybridAutomatonParser::getGrammarFileName () const override virtual
Definition at line 26 of file HybridAutomatonParser.cpp.
const std::vector< std::string > & HybridAutomatonParser::getRuleNames () const override virtual
Definition at line 30 of file HybridAutomatonParser.cpp.
Referenced by getTokenNames().
virtual const std::vector<std::string>& hypro::HybridAutomatonParser::getTokenNames () const inline override virtual
Definition at line 52 of file HybridAutomatonParser.h.
References getRuleNames(), and getVocabulary().
dfa::Vocabulary & HybridAutomatonParser::getVocabulary () const override virtual
Definition at line 34 of file HybridAutomatonParser.cpp.
Referenced by getTokenNames().
HybridAutomatonParser::GuardContext * HybridAutomatonParser::guard ()
Definition at line 2345 of file HybridAutomatonParser.cpp.
References CBCLOSE, CBOPEN, hypro::HybridAutomatonParser::GuardContext::constrset(), FALSE, GUARD, MINUS, NUMBER, PLUS, RBOPEN, RuleGuard, TRUE, and VARIABLE.
HybridAutomatonParser::IdentityContext * HybridAutomatonParser::identity ()
Definition at line 3276 of file HybridAutomatonParser.cpp.
References RuleIdentity, and T__15.
HybridAutomatonParser::InitContext * HybridAutomatonParser::init ()
Definition at line 1731 of file HybridAutomatonParser.cpp.
References CBCLOSE, CBOPEN, hypro::HybridAutomatonParser::InitContext::initstate(), RuleInit, T__4, and VARIABLE.
HybridAutomatonParser::InitstateContext * HybridAutomatonParser::initstate ()
Definition at line 1794 of file HybridAutomatonParser.cpp.
References CBCLOSE, CBOPEN, hypro::HybridAutomatonParser::InitstateContext::constrset(), RuleInitstate, and VARIABLE.
HybridAutomatonParser::IntervalContext * HybridAutomatonParser::interval ()
Definition at line 1463 of file HybridAutomatonParser.cpp.
References COMMA, MINUS, NUMBER, RuleInterval, SBCLOSE, SBOPEN, and VARIABLE.
HybridAutomatonParser::IntervalexprContext * HybridAutomatonParser::intervalexpr ()
Definition at line 1558 of file HybridAutomatonParser.cpp.
References IN, hypro::HybridAutomatonParser::IntervalexprContext::interval(), RuleIntervalexpr, and VARIABLE.
HybridAutomatonParser::InvariantsContext * HybridAutomatonParser::invariants ()
Definition at line 637 of file HybridAutomatonParser.cpp.
References CBCLOSE, CBOPEN, hypro::HybridAutomatonParser::InvariantsContext::constrset(), FALSE, MINUS, NUMBER, PLUS, RBOPEN, RuleInvariants, T__3, TRUE, and VARIABLE.
HybridAutomatonParser::JumpsContext * HybridAutomatonParser::jumps ()
Definition at line 2052 of file HybridAutomatonParser.cpp.
References CBCLOSE, CBOPEN, JUMPS, RuleJumps, hypro::HybridAutomatonParser::JumpsContext::transition(), and VARIABLE.
HybridAutomatonParser::LabelsContext * HybridAutomatonParser::labels ()
Definition at line 2413 of file HybridAutomatonParser.cpp.
References CBCLOSE, CBOPEN, RuleLabels, T__6, and VARIABLE.
HybridAutomatonParser::LbadstateContext * HybridAutomatonParser::lbadstate ()
Definition at line 1940 of file HybridAutomatonParser.cpp.
References CBCLOSE, CBOPEN, hypro::HybridAutomatonParser::LbadstateContext::constrset(), FALSE, MINUS, NUMBER, PLUS, RBOPEN, RuleLbadstate, TRUE, and VARIABLE.
HybridAutomatonParser::LocationContext * HybridAutomatonParser::location ()
Definition at line 435 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::LocationContext::activities(), CBCLOSE, CBOPEN, hypro::HybridAutomatonParser::LocationContext::invariants(), RuleLocation, T__3, and VARIABLE.
HybridAutomatonParser::MaxjumpsContext * HybridAutomatonParser::maxjumps ()
Definition at line 3142 of file HybridAutomatonParser.cpp.
References NUMBER, RuleMaxjumps, and T__12.
HybridAutomatonParser::ModesContext * HybridAutomatonParser::modes ()
Definition at line 364 of file HybridAutomatonParser.cpp.
References CBCLOSE, CBOPEN, hypro::HybridAutomatonParser::ModesContext::location(), RuleModes, T__2, and VARIABLE.
HybridAutomatonParser::PlotsettingContext * HybridAutomatonParser::plotsetting ()
Definition at line 3031 of file HybridAutomatonParser.cpp.
References COMMA, RulePlotsetting, T__10, and VARIABLE.
HybridAutomatonParser::PolynomContext * HybridAutomatonParser::polynom ()
Definition at line 1061 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::PolynomContext::connector(), RulePolynom, and hypro::HybridAutomatonParser::PolynomContext::term().
HybridAutomatonParser::PrecisionContext * HybridAutomatonParser::precision ()
Definition at line 3514 of file HybridAutomatonParser.cpp.
References NUMBER, RulePrecision, and T__22.
HybridAutomatonParser::PrintContext * HybridAutomatonParser::print ()
Definition at line 3188 of file HybridAutomatonParser.cpp.
References RulePrint, T__13, and VARIABLE.
HybridAutomatonParser::QrprecondContext * HybridAutomatonParser::qrprecond ()
Definition at line 3316 of file HybridAutomatonParser.cpp.
References RuleQrprecond, and T__16.
HybridAutomatonParser::RemainderContext * HybridAutomatonParser::remainder ()
Definition at line 3234 of file HybridAutomatonParser.cpp.
References EXPONENTIAL, RuleRemainder, and T__14.
HybridAutomatonParser::ReplacedexprContext * HybridAutomatonParser::replacedexpr ()
Definition at line 717 of file HybridAutomatonParser.cpp.
References EQUALS, MINUS, NUMBER, and RuleReplacedexpr.
HybridAutomatonParser::ResetfctContext * HybridAutomatonParser::resetfct ()
Definition at line 2555 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::ResetfctContext::allocation(), CBCLOSE, CBOPEN, RESET, RuleResetfct, and VARIABLE.
HybridAutomatonParser::SettingContext * HybridAutomatonParser::setting ()
Definition at line 2781 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::SettingContext::adaptiveorders(), CBCLOSE, CBOPEN, hypro::HybridAutomatonParser::SettingContext::cutoff(), hypro::HybridAutomatonParser::SettingContext::filename(), hypro::HybridAutomatonParser::SettingContext::fixedorders(), hypro::HybridAutomatonParser::SettingContext::fixedsteps(), hypro::HybridAutomatonParser::SettingContext::identity(), hypro::HybridAutomatonParser::SettingContext::maxjumps(), hypro::HybridAutomatonParser::SettingContext::plotsetting(), hypro::HybridAutomatonParser::SettingContext::precision(), hypro::HybridAutomatonParser::SettingContext::print(), hypro::HybridAutomatonParser::SettingContext::qrprecond(), hypro::HybridAutomatonParser::SettingContext::remainder(), RuleSetting, T__10, T__11, T__12, T__13, T__14, T__15, T__16, T__17, T__18, T__21, T__22, T__7, T__8, T__9, and hypro::HybridAutomatonParser::SettingContext::time().
HybridAutomatonParser::StartContext * HybridAutomatonParser::start ()
Definition at line 97 of file HybridAutomatonParser.cpp.
References CBCLOSE, CBOPEN, hypro::HybridAutomatonParser::StartContext::constantdeclaration(), hypro::HybridAutomatonParser::StartContext::init(), hypro::HybridAutomatonParser::StartContext::jumps(), hypro::HybridAutomatonParser::StartContext::modes(), PAR, RuleStart, hypro::HybridAutomatonParser::StartContext::setting(), T__0, T__4, T__5, hypro::HybridAutomatonParser::StartContext::unsafeset(), and hypro::HybridAutomatonParser::StartContext::vardeclaration().
Referenced by hypro::parser::createFlowstarParseTree(), hypro::parseFlowstarFile< double >(), and hypro::parseFlowstarFile< mpq_class >().
HybridAutomatonParser::TermContext * HybridAutomatonParser::term ()
Definition at line 951 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::TermContext::connector(), MINUS, NUMBER, PLUS, RuleTerm, TIMES, and VARIABLE.
HybridAutomatonParser::TimeContext * HybridAutomatonParser::time ()
Definition at line 2981 of file HybridAutomatonParser.cpp.
References NUMBER, RuleTime, and T__9.
HybridAutomatonParser::TransitionContext * HybridAutomatonParser::transition ()
Definition at line 2151 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::TransitionContext::aggregation(), BOX, hypro::HybridAutomatonParser::TransitionContext::fromto(), GUARD, hypro::HybridAutomatonParser::TransitionContext::guard(), INTERVALAGG, hypro::HybridAutomatonParser::TransitionContext::labels(), PARALLELOTOPE, RESET, hypro::HybridAutomatonParser::TransitionContext::resetfct(), RuleTransition, T__6, URGENT, and hypro::HybridAutomatonParser::TransitionContext::urgent().
HybridAutomatonParser::UnsafesetContext * HybridAutomatonParser::unsafeset ()
Definition at line 1856 of file HybridAutomatonParser.cpp.
References CBCLOSE, CBOPEN, FALSE, hypro::HybridAutomatonParser::UnsafesetContext::gbadstate(), hypro::HybridAutomatonParser::UnsafesetContext::lbadstate(), MINUS, NUMBER, PLUS, RBOPEN, RuleUnsafeset, T__5, TRUE, and VARIABLE.
HybridAutomatonParser::UrgentContext * HybridAutomatonParser::urgent ()
Definition at line 2301 of file HybridAutomatonParser.cpp.
References RuleUrgent, and URGENT.
HybridAutomatonParser::VardeclarationContext * HybridAutomatonParser::vardeclaration ()
Definition at line 192 of file HybridAutomatonParser.cpp.
References COMMA, RuleVardeclaration, T__1, and VARIABLE.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HybridAutomatonParser.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HybridAutomatonParser.cpp