HyPro: hypro::timedBadStateHandler< State > Class Template Reference
hypro::timedBadStateHandler< State > Class Template Reference
Public Member Functions
timedBadStateHandler ()=delete
timedBadStateHandler (State *state, size_t index)
void handle ()
const char * handlerName ()
Detailed Description
template<typename State>
class hypro::timedBadStateHandler< State >
Definition at line 7 of file timedBadStateHandler.h.
Constructor & Destructor Documentation
template<typename State > hypro::timedBadStateHandler< State >::timedBadStateHandler () delete
template<typename State > hypro::timedBadStateHandler< State >::timedBadStateHandler (State * state, size_t index) inline
Definition at line 12 of file timedBadStateHandler.h.
References hypro::timedBadStateHandler< State >::handle().
Member Function Documentation
template<typename State > void hypro::timedBadStateHandler< State >::handle ()
Definition at line 5 of file timedBadStateHandler.tpp.
References hypro::SettingsProvider< State >::getHybridAutomaton(), and hypro::NO.
Referenced by hypro::timedBadStateHandler< State >::timedBadStateHandler().
template<typename State > const char* hypro::timedBadStateHandler< State >::handlerName () inline
Definition at line 16 of file timedBadStateHandler.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/badStateHandlers/timedBadStateHandler.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/badStateHandlers/timedBadStateHandler.tpp