HyPro: hypro::Halfspace< Number > Class Template Reference
hypro::Halfspace< Number > Class Template Reference
Public Member Functions
Halfspace (const Point< Number > &_vector, const Number &_off)
Constructor from a normal vector given as a point and an offset.
Halfspace (std::initializer_list< Number > _coordinates, const Number &_off)
Constructor from an initializer list for the normal vector and an offset.
template<typename Normal , typename Offset , enable_if< convertible< Normal, vector_t< Number >> &&convertible< Offset, Number >> = 0>
Halfspace (Normal &&normal, Offset &&offset)
Constructor from a normal vector and an offset with perfect forwarding.
Halfspace (const vector_t< Number > &_vec, const std::vector< vector_t< Number >> &_vectorSet)
Constructor from an offset vector and a set of points lying in the plane.
Halfspace (const std::vector< Point< Number >> &points)
Construct a new Halfspace object from a set of points.
Halfspace (const std::vector< vector_t< Number >> &points)
Construct a new Halfspace object from a set of points given as vector_t.
double sizeOfHalfspace ()
Size function returning the estimated storage usage of this plane.
unsigned dimension () const
Returns the space dimension.
template<typename N = Number, carl::DisableIf< std::is_same< N, double >> = carl::dummy>
void makeInteger ()
template<typename N = Number, carl::EnableIf< std::is_same< N, double >> = carl::dummy>
void makeInteger ()
bool isInteger () const
Determines if the plane coefficients are integers.
const vector_t< Number > & normal () const &
Returns the plane normal.
vector_t< Number > && normal ()&&
Returns the plane normal as an rvalue if this is an rvalue.
void setNormal (const vector_t< Number > &_normal)
Sets the normal.
Halfspace< Number > & invert ()
Inverts the halfspace by negating the plane normal and the offset.
Number offset () const &
Returns the plane offset.
Number && offset ()&&
Returns the plane offset as an rvalue if this is an rvalue.
void setOffset (Number _offset)
Sets the offset.
Number signedDistance (const vector_t< Number > &_point) const
Returns the signed distance of a point to the hyperplane.
Number evaluate (const vector_t< Number > &_direction) const
Evaluates the halfspace in the given direction.
Point< Number > projectPointOnPlane (const Point< Number >) const
Projects a given point on the plane.
bool intersection (Number &_result, const vector_t< Number > &_vector) const
Computes the intersection of a vector with the plane.
bool intersection (Number &_result, const Point< Number > &_vector) const
Computes the intersection of a vector with the plane.
Halfspace< Number > projectOn (const std::vector< unsigned > &dimensions) const
Projects the halfspace on the given dimensions. Note that this corresponds to a projection of the normal vector without any re-scaling.
Halfspace< Number > linearTransformation (const matrix_t< Number > &A) const
Computes the linear transformation of the plane.
Halfspace< Number > affineTransformation (const matrix_t< Number > &A, const vector_t< Number > &b) const
Computes the affine transformation of the plane.
vector_t< Number > intersectionVector (const Halfspace< Number > &_rhs) const
Computes the vector describing the intersection of two hyperplanes.
bool contains (const vector_t< Number > _vector) const
Determines, whether the point given as a vector is contained in the halfspace.
bool contains (const Point< Number > _vector) const
Determines whether the given point is contained inside the halfspace.
bool contains (const std::vector< Point< Number >> &_points) const
Determines, whether the given set of points is contained inside the halfspace.
bool exactContains (vector_t< Number > const &point) const
Determines, whether the given point is contained inside the halfspace using exact arithmetic.
bool holds (const vector_t< Number > _vector) const
Determines, whether the point given as a vector saturates the halfspace, i.e. lies on its bounding plane.
matrix_t< Number > matrix () const
Return mNormal as a matrix.
vector_t< Number > vector () const
Return mScalar as a vector.
bool empty () const
Return whether the halfspace is empty. A halfspace itself cannot be empty, except its normal is the zero vector and the scalar is smaller than 0.
void removeRedundancy ()
Removes redundancy.
EvaluationResult< Number > evaluate (const vector_t< Number > &direction, bool) const
Return the steps needed in the given direction to reach the optimal point.
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &_directions, bool) const
Return the evaluation result for multiple directions.
std::vector< Point< Number > > vertices () const
Returns a point representation of the halfspace. which does not exist. Although this function is nonsensical, it is needed in order to use the Halfspace class as a leaf in the SupportFunctionNew.
Static Public Member Functions
static vector_t< Number > fastIntersect (const std::vector< Halfspace< Number >> &_planes)
static vector_t< Number > saveIntersect (const std::vector< Halfspace< Number >> &_planes, Number threshold=0)
static vector_t< Number > computePlaneNormal (const std::vector< vector_t< Number >> &pointSet)
Method to compute the normal of a plane based on two direction vectors simply computing the cross product does not work since the dimension is not necessarily 3.
static Number computePlaneOffset (const vector_t< Number > &normal, const Point< Number > &pointOnPlane)
Calculates the plane offset of a given normal vector for that plane and a point lying on the plane. This corresponds to the dot product of the normal vector and the negated point coordinates.
static representation_name type ()
Returns the representation type of the halfspace. Since adding an own representation name for halfspaces would greatly affect the code, it just returns constraint_set as the representation name as it is usually not used as a representation but still has defined representation name.
Friends
void swap (Halfspace< Number > &a, Halfspace< Number > &b)
The swap operator.
Detailed Description
template<typename Number>
class hypro::Halfspace< Number >
Examples:
example_box.cpp.
Definition at line 25 of file Halfspace.h.
Constructor & Destructor Documentation
template<typename Number > hypro::Halfspace< Number >::Halfspace (const Point< Number > & _vector, const Number & _off)
Constructor from a normal vector given as a point and an offset.
Parameters
[in] _vector The vector.
[in] _off The offset.
Definition at line 16 of file Halfspace.tpp.
template<typename Number > hypro::Halfspace< Number >::Halfspace (std::initializer_list< Number > _coordinates, const Number & _off)
Constructor from an initializer list for the normal vector and an offset.
Parameters
[in] _coordinates The normal vector.
[in] _off The offset.
Definition at line 21 of file Halfspace.tpp.
template<typename Number > template<typename Normal , typename Offset , enable_if< convertible< Normal, vector_t< Number >> &&convertible< Offset, Number >> > hypro::Halfspace< Number >::Halfspace (Normal && normal, Offset && offset)
Constructor from a normal vector and an offset with perfect forwarding.
Parameters
[in] _vector The vector.
[in] _off The offset.
Definition at line 34 of file Halfspace.tpp.
template<typename Number > hypro::Halfspace< Number >::Halfspace (const vector_t< Number > & _vec, const std::vector< vector_t< Number >> & _vectorSet)
Constructor from an offset vector and a set of points lying in the plane.
Parameters
[in] _vec The offset vector.
[in] _vectorSet The point-set defining the plane.
Definition at line 39 of file Halfspace.tpp.
References hypro::Halfspace< Number >::computePlaneNormal().
template<typename Number > hypro::Halfspace< Number >::Halfspace (const std::vector< Point< Number >> & points)
Construct a new Halfspace object from a set of points.
Parameters
points
Definition at line 51 of file Halfspace.tpp.
References hypro::Halfspace< Number >::computePlaneNormal(), and hypro::Halfspace< Number >::computePlaneOffset().
template<typename Number > hypro::Halfspace< Number >::Halfspace (const std::vector< vector_t< Number >> & points)
Construct a new Halfspace object from a set of points given as vector_t.
Parameters
points
Definition at line 62 of file Halfspace.tpp.
References hypro::Halfspace< Number >::computePlaneNormal(), and hypro::Halfspace< Number >::computePlaneOffset().
Member Function Documentation
template<typename Number > Halfspace< Number > hypro::Halfspace< Number >::affineTransformation (const matrix_t< Number > & A, const vector_t< Number > & b) const
Computes the affine transformation of the plane.
Parameters
[in] A The transformation matrix.
[in] b The transformation vector.
Returns
The resulting halfspace.
Definition at line 171 of file Halfspace.tpp.
Referenced by hypro::Halfspace< Number >::isInteger().
template<typename Number > vector_t< Number > hypro::Halfspace< Number >::computePlaneNormal (const std::vector< vector_t< Number >> & pointSet) static
Method to compute the normal of a plane based on two direction vectors simply computing the cross product does not work since the dimension is not necessarily 3.
Author
Chris K
Parameters
[in] The set of vectors.
Returns
A vector representing the resulting plane normal.
Definition at line 338 of file Halfspace.tpp.
References hypro::Halfspace< Number >::normal().
Referenced by hypro::Halfspace< Number >::Halfspace(), and hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT().
template<typename Number > Number hypro::Halfspace< Number >::computePlaneOffset (const vector_t< Number > & normal, const Point< Number > & pointOnPlane) static
Calculates the plane offset of a given normal vector for that plane and a point lying on the plane. This corresponds to the dot product of the normal vector and the negated point coordinates.
Parameters
[in] normal The normal.
[in] pointOnPlane The point on plane.
Returns
The plane offset.
Definition at line 438 of file Halfspace.tpp.
References hypro::Point< Number >::rawCoordinates().
Referenced by hypro::Halfspace< Number >::Halfspace(), and hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT().
template<typename Number > bool hypro::Halfspace< Number >::contains (const vector_t< Number > _vector) const
Determines, whether the point given as a vector is contained in the halfspace.
Parameters
[in] _vector The vector.
Returns
True, if it is contained, false otherwise.
Definition at line 304 of file Halfspace.tpp.
References hypro::satisfiesIneqation().
Referenced by hypro::Halfspace< Number >::contains(), hypro::ZonotopeT< Number, Converter, Setting >::intersect(), hypro::BoxT< Number, Converter, Setting >::intersectHalfspace(), and hypro::Halfspace< Number >::isInteger().
template<typename Number > bool hypro::Halfspace< Number >::contains (const Point< Number > _vector) const
Determines whether the given point is contained inside the halfspace.
Parameters
[in] _vector The point.
Returns
True, if it is contained, false otherwise.
Definition at line 309 of file Halfspace.tpp.
References hypro::Halfspace< Number >::contains(), and hypro::Point< Number >::rawCoordinates().
template<typename Number > bool hypro::Halfspace< Number >::contains (const std::vector< Point< Number >> & _points) const
Determines, whether the given set of points is contained inside the halfspace.
Parameters
[in] _points The points.
Returns
True, if all points are contained, false otherwise.
Definition at line 314 of file Halfspace.tpp.
References hypro::Halfspace< Number >::contains().
template<typename Number > unsigned hypro::Halfspace< Number >::dimension () const
Returns the space dimension.
Returns
The space dimension.
Definition at line 69 of file Halfspace.tpp.
Referenced by hypro::Plotter< Number >::addObject(), hypro::HPolytopeT< Number, Converter, Setting >::insert(), hypro::ZonotopeT< Number, Converter, Setting >::intersect(), hypro::Halfspace< Number >::multiEvaluate(), hypro::Halfspace< Number >::sizeOfHalfspace(), and hypro::ZonotopeT< Number, Converter, Setting >::vertices().
template<typename Number > Number hypro::Halfspace< Number >::evaluate (const vector_t< Number > & _direction) const
Evaluates the halfspace in the given direction.
Note that all evaluations not in direction of the normal will result in infty.
Parameters
[in] _direction The direction.
Returns
The maximal distance to the limiting plane in the given direction.
Definition at line 116 of file Halfspace.tpp.
Referenced by hypro::Halfspace< Number >::isInteger(), and hypro::Halfspace< Number >::removeRedundancy().
template<typename Number > EvaluationResult< Number > hypro::Halfspace< Number >::evaluate (const vector_t< Number > & direction, bool) const
Return the steps needed in the given direction to reach the optimal point.
Parameters
[in] direction The direction to evaluate
Returns
Whether it is feasible, and if it is, how much steps are needed.
Definition at line 466 of file Halfspace.tpp.
References hypro::linearDependent().
template<typename Number > bool hypro::Halfspace< Number >::exactContains (vector_t< Number > const & point) const
Determines, whether the given point is contained inside the halfspace using exact arithmetic.
Parameters
[in] point The point.
Returns
True iff the point is contained.
Definition at line 324 of file Halfspace.tpp.
References hypro::Halfspace< Number >::normal(), and hypro::Halfspace< Number >::offset().
Referenced by hypro::Halfspace< Number >::isInteger().
template<typename Number > bool hypro::Halfspace< Number >::holds (const vector_t< Number > _vector) const
Determines, whether the point given as a vector saturates the halfspace, i.e. lies on its bounding plane.
Parameters
[in] _vector The vector.
Returns
True, if the point lies on the plane, false otherwise.
Definition at line 333 of file Halfspace.tpp.
Referenced by hypro::Halfspace< Number >::isInteger().
template<typename Number > bool hypro::Halfspace< Number >::intersection (Number & _result, const vector_t< Number > & _vector) const
Computes the intersection of a vector with the plane.
Parameters
_result The resulting scaling factor required to determine the intersection point.
[in] _vector The vector.
Returns
True, if the vector intersects the plane, false otherwise.
Definition at line 127 of file Halfspace.tpp.
Referenced by hypro::Halfspace< Number >::intersection(), and hypro::Halfspace< Number >::isInteger().
template<typename Number > bool hypro::Halfspace< Number >::intersection (Number & _result, const Point< Number > & _vector) const
Computes the intersection of a vector with the plane.
Parameters
_result The resulting scaling factor required to determine the intersection point.
[in] _vector The vector.
Returns
True, if the vector intersects the plane, false otherwise.
Definition at line 141 of file Halfspace.tpp.
References hypro::Halfspace< Number >::intersection(), and hypro::Point< Number >::rawCoordinates().
template<typename Number > vector_t< Number > hypro::Halfspace< Number >::intersectionVector (const Halfspace< Number > & _rhs) const
Computes the vector describing the intersection of two hyperplanes.
Parameters
[in] _rhs The right hand side.
Returns
The intersection vector.
Definition at line 187 of file Halfspace.tpp.
References hypro::Halfspace< Number >::normal(), and hypro::Halfspace< Number >::offset().
Referenced by hypro::Halfspace< Number >::isInteger().
template<typename Number> bool hypro::Halfspace< Number >::isInteger () const inline
Determines if the plane coefficients are integers.
Returns
True if integer, False otherwise.
Definition at line 114 of file Halfspace.h.
References hypro::Halfspace< Number >::affineTransformation(), hypro::Halfspace< Number >::contains(), hypro::Halfspace< Number >::evaluate(), hypro::Halfspace< Number >::exactContains(), hypro::Halfspace< Number >::holds(), hypro::Halfspace< Number >::intersection(), hypro::Halfspace< Number >::intersectionVector(), hypro::Halfspace< Number >::invert(), hypro::Halfspace< Number >::linearTransformation(), hypro::Halfspace< Number >::normal(), hypro::Halfspace< Number >::offset(), hypro::Halfspace< Number >::projectOn(), hypro::Halfspace< Number >::projectPointOnPlane(), hypro::Halfspace< Number >::setNormal(), hypro::Halfspace< Number >::setOffset(), and hypro::Halfspace< Number >::signedDistance().
Referenced by hypro::Halfspace< Number >::sizeOfHalfspace().
template<typename Number > Halfspace< Number > hypro::Halfspace< Number >::linearTransformation (const matrix_t< Number > & A) const
Computes the linear transformation of the plane.
Parameters
[in] A The transformation matrix.
Returns
The resulting halfspace.
Definition at line 156 of file Halfspace.tpp.
Referenced by hypro::Halfspace< Number >::isInteger().
template<typename Number > matrix_t< Number > hypro::Halfspace< Number >::matrix () const
Return mNormal as a matrix.
Functions for SupportFunctionNew where it is seen as a representation
Definition at line 444 of file Halfspace.tpp.
Referenced by hypro::SupportFunctionNewT< Number, Converter, Setting >::SupportFunctionNewT().
template<typename Number > std::vector< EvaluationResult< Number > > hypro::Halfspace< Number >::multiEvaluate (const matrix_t< Number > & _directions, bool) const
Return the evaluation result for multiple directions.
Parameters
[in] _directions The directions to evaluate
Returns
For each direction, whether the evaluation is feasible, and if it is, how many steps are needed
Definition at line 489 of file Halfspace.tpp.
References hypro::Halfspace< Number >::dimension(), and hypro::linearDependent().
Referenced by hypro::Halfspace< Number >::removeRedundancy().
template<typename Number > const vector_t< Number > & hypro::Halfspace< Number >::normal () const
Returns the plane normal.
Returns
The normal.
Definition at line 74 of file Halfspace.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::cleanUp(), hypro::Halfspace< Number >::computePlaneNormal(), hypro::convert(), hypro::HPolytopeT< Number, Converter, Setting >::erase(), hypro::Halfspace< Number >::exactContains(), hypro::icpIntersectHalfspace(), hypro::ZonotopeT< Number, Converter, Setting >::intersect(), hypro::BoxT< Number, Converter, Setting >::intersectHalfspace(), hypro::Halfspace< Number >::intersectionVector(), hypro::Halfspace< Number >::isInteger(), hypro::operator==(), hypro::SupportFunctionNewT< Number, Converter, Setting >::satisfiesHalfspace(), hypro::BoxT< Number, Converter, Setting >::satisfiesHalfspace(), and hypro::ZonotopeT< Number, Converter, Setting >::vertices().
template<typename Number > vector_t< Number > && hypro::Halfspace< Number >::normal ()
Returns the plane normal as an rvalue if this is an rvalue.
Returns
The normal.
Definition at line 79 of file Halfspace.tpp.
template<typename Number > Number hypro::Halfspace< Number >::offset () const
Returns the plane offset.
Returns
The offset.
Definition at line 96 of file Halfspace.tpp.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::cleanUp(), hypro::convert(), hypro::HPolytopeT< Number, Converter, Setting >::erase(), hypro::Halfspace< Number >::exactContains(), hypro::icpIntersectHalfspace(), hypro::ZonotopeT< Number, Converter, Setting >::intersect(), hypro::BoxT< Number, Converter, Setting >::intersectHalfspace(), hypro::Halfspace< Number >::intersectionVector(), hypro::Halfspace< Number >::isInteger(), hypro::operator==(), hypro::SupportFunctionNewT< Number, Converter, Setting >::satisfiesHalfspace(), hypro::BoxT< Number, Converter, Setting >::satisfiesHalfspace(), and hypro::ZonotopeT< Number, Converter, Setting >::vertices().
template<typename Number > Number && hypro::Halfspace< Number >::offset ()
Returns the plane offset as an rvalue if this is an rvalue.
Returns
The offset.
Definition at line 101 of file Halfspace.tpp.
template<typename Number > Halfspace< Number > hypro::Halfspace< Number >::projectOn (const std::vector< unsigned > & dimensions) const
Projects the halfspace on the given dimensions. Note that this corresponds to a projection of the normal vector without any re-scaling.
Parameters
[in] dimensions The dimensions.
Returns
The projected halfspace.
Definition at line 146 of file Halfspace.tpp.
References hypro::projectOn().
Referenced by hypro::Halfspace< Number >::isInteger().
template<typename Number > Point< Number > hypro::Halfspace< Number >::projectPointOnPlane (const Point< Number > point) const
Projects a given point on the plane.
Parameters
[in] <unnamed> The point.
Returns
A point lying on the plane which is a projection of the input.
Definition at line 121 of file Halfspace.tpp.
References hypro::Point< Number >::rawCoordinates().
Referenced by hypro::Halfspace< Number >::isInteger().
template<typename Number > void hypro::Halfspace< Number >::setNormal (const vector_t< Number > & _normal)
Sets the normal.
Parameters
[in] _normal The normal.
Definition at line 84 of file Halfspace.tpp.
Referenced by hypro::Halfspace< Number >::isInteger().
template<typename Number > void hypro::Halfspace< Number >::setOffset (Number _offset)
Sets the offset.
Parameters
[in] _offset The offset.
Definition at line 106 of file Halfspace.tpp.
Referenced by hypro::Halfspace< Number >::isInteger().
template<typename Number > Number hypro::Halfspace< Number >::signedDistance (const vector_t< Number > & _point) const
Returns the signed distance of a point to the hyperplane.
Parameters
[in] _point The point.
Returns
The signed distance.
Definition at line 111 of file Halfspace.tpp.
Referenced by hypro::Halfspace< Number >::isInteger().
template<typename Number> double hypro::Halfspace< Number >::sizeOfHalfspace () inline
Size function returning the estimated storage usage of this plane.
Returns
An estimated storage usage.
Definition at line 79 of file Halfspace.h.
References hypro::Halfspace< Number >::dimension(), and hypro::Halfspace< Number >::isInteger().
Friends And Related Function Documentation
template<typename Number> void swap (Halfspace< Number > & a, Halfspace< Number > & b) friend
The swap operator.
Parameters
a The left-hand-side.
b The right-hand-side.
Definition at line 274 of file Halfspace.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/datastructures/Halfspace.h
/home/travis/build/hypro/hypro/src/hypro/datastructures/Halfspace.tpp