HyPro: hypro::Grid< Number > Class Template Reference
hypro::Grid< Number > Class Template Reference
Class for a grid which maps points to their assigned color.
Public Types
using gridMap = std::map< Point< std::size_t >, bool >
using gridPoints = std::map< std::size_t, std::vector< Number >>
using gridMapIterator = gridMap::iterator
using gridPointsIterator = typename gridPoints::iterator
Public Member Functions
Grid ()
Grid (const vSet< Number > &vertices)
Grid (const std::vector< Vertex< Number >> &_vertices)
Grid (const Grid< Number > &copy)
Grid< Number > & operator= (const Grid< Number > &)=default
Grid< Number > & operator= (Grid< Number > &&)=default
std::size_t size () const
std::size_t dimension () const
std::vector< carl::Variable > variables () const
std::vector< Vertex< Number > > vertices () const
std::vector< Number > inducedDimensionAt (std::size_t dimension) const
bool empty () const
bool colorAt (const Point< Number > &point) const
bool colorAtInduced (const Point< std::size_t > &inducedPoint) const
std::vector< Point< Number > > allBlack () const
void colorAll () const
Point< std::size_t > iPredecessorInduced (const Point< std::size_t > &_point, std::size_t _dimension) const
Point< Number > iPredecessor (const Point< Number > &_point, std::size_t _dimension) const
Point< std::size_t > iSuccessorInduced (const Point< std::size_t > &_point, std::size_t _dimension) const
Point< Number > iSuccessor (const Point< Number > &_point, std::size_t _dimension) const
Point< std::size_t > directPredecessorInduced (const Point< std::size_t > &_point) const
Point< Number > directPredecessor (const Point< Number > &_point) const
Point< std::size_t > directSuccessorInduced (const Point< std::size_t > &_point) const
Point< Number > directSuccessor (const Point< Number > &_point) const
std::vector< Point< std::size_t > > iSliceInduced (std::size_t i) const
std::vector< Point< Number > > iSlice (std::size_t i, Number pos) const
std::vector< Point< std::size_t > > iNeighborhoodInduced (const Point< std::size_t > &_inducedPoint, std::size_t _dimension) const
std::vector< Point< Number > > iNeighborhood (const Point< Number > &_point, std::size_t _dimension) const
std::vector< Point< std::size_t > > neighborhoodInduced (const Point< std::size_t > &_inducedPoint) const
std::vector< Point< Number > > neighborhood (const Point< Number > &_point) const
bool isVertex (const Point< Number > &_point) const
bool isOnIFacet (const Point< Number > &_point, std::size_t i) const
bool isOnFacet (const Point< Number > &_point) const
bool isOutside (const Point< Number > &_point) const
void insert (const Point< Number > &point, bool color)
void insertInduced (const Point< std::size_t > &inducedPoint, bool color)
void addCoordinate (Number value, std::size_t dimension)
void clear ()
gridMap::const_iterator find (const Point< Number > &point) const
gridMap::const_iterator findInduced (const Point< std::size_t > &inducedPoint) const
gridMap::const_iterator end () const
void induceGrid (const vSet< Number > &vertices)
std::pair< Point< std::size_t >, bool > calculateInduced (const Point< Number > &point) const
Point< Number > calculateOriginal (const Point< std::size_t > &inducedPoint) const
vSet< std::size_t > translateToInduced (const vSet< Number > &vertices) const
vSet< Number > translateToOriginal (const vSet< std::size_t > &inducedVertices) const
Static Public Member Functions
static Grid< Number > combine (const Grid< Number > &a, const Grid< Number > &b)
Friends
bool operator== (const Grid< Number > &op1, const Grid< Number > &op2)
bool operator!= (const Grid< Number > &op1, const Grid< Number > &op2)
std::ostream & operator<< (std::ostream &out, const Grid< Number > &grid)
Detailed Description
template<typename Number>
class hypro::Grid< Number >
Class for a grid which maps points to their assigned color.
Template Parameters
Number The used number type.
Definition at line 72 of file Grid.h.
Constructor & Destructor Documentation
template<typename Number > hypro::Grid< Number >::Grid ()
Constructor
Definition at line 19 of file Grid.tpp.
Member Function Documentation
template<typename Number > std::pair< Point< std::size_t >, bool > hypro::Grid< Number >::calculateInduced (const Point< Number > & point) const
Calculates the coordinates of this point on the induced grid.
Parameters
point
Returns
induced point
Definition at line 581 of file Grid.tpp.
References hypro::Point< Number >::at().
template<typename Number > Point< Number > hypro::Grid< Number >::calculateOriginal (const Point< std::size_t > & inducedPoint) const
Calculates the original coordinates of this induced point.
Parameters
inducedPoint
Returns
original point
Definition at line 607 of file Grid.tpp.
References hypro::Point< Number >::at().
template<typename Number > bool hypro::Grid< Number >::colorAt (const Point< Number > & point) const
Returns the color of the given point.
Parameters
point
Returns
the color of the point
Definition at line 90 of file Grid.tpp.
References hypro::Point< Number >::at(), and hypro::Point< Number >::dimension().
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::boundaryBox().
template<typename Number > void hypro::Grid< Number >::induceGrid (const vSet< Number > & vertices)
Clears the grid, induces it and sets up the vertices.
Parameters
vertices
Definition at line 542 of file Grid.tpp.
template<typename Number > void hypro::Grid< Number >::insert (const Point< Number > & point, bool color)
Inserts the value for the point.
Parameters
point
color
Definition at line 465 of file Grid.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::boundaryBox().
template<typename Number > std::size_t hypro::Grid< Number >::size () const
Returns the size ie. the number of points saved in this grid.
Returns
Definition at line 46 of file Grid.tpp.
References hypro::Grid< Number >::size(), and hypro::Point< Number >::Zero().
Referenced by hypro::Grid< Number >::size().
template<typename Number > vSet< std::size_t > hypro::Grid< Number >::translateToInduced (const vSet< Number > & vertices) const
Translates the points to induced points.
Parameters
vertices
Returns
induced vertices
Definition at line 623 of file Grid.tpp.
References hypro::Vertex< Number >::setColor().
template<typename Number > vSet< Number > hypro::Grid< Number >::translateToOriginal (const vSet< std::size_t > & inducedVertices) const
Translates the induced points to original points.
Parameters
inducedVertices
Returns
original vertices
Definition at line 634 of file Grid.tpp.
References hypro::Vertex< Number >::setColor().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/OrthogonalPolyhedron/Grid.h
/home/travis/build/hypro/hypro/src/hypro/representations/OrthogonalPolyhedron/Grid.tpp