HyPro: hypro::ltiJumpHandler< State > Class Template Reference
hypro::ltiJumpHandler< State > Class Template Reference
#include <forwardDeclarations.h>
Public Member Functions
ltiJumpHandler ()=delete
ltiJumpHandler (std::vector< std::tuple< Transition< Number > *, State >> *successorBuffer, std::shared_ptr< Task< State >> task, Transition< Number > *transition, StrategyParameters strategy, WorkQueue< std::shared_ptr< Task< State >>> *localQueue, WorkQueue< std::shared_ptr< Task< State >>> *localCEXQueue, const EventTimingContainer< typename State::NumberType > &timings)
void handle ()
const char * handlerName ()
std::map< Transition< Number > *, std::vector< State > > applyJump (const std::vector< std::tuple< Transition< Number > *, State >> &states, Transition< Number > *transition, const StrategyParameters &strategy)
void aggregate (std::map< Transition< Number > *, std::vector< State >> &processedStates, const std::map< Transition< Number > *, std::vector< State >> &toAggregate, const StrategyParameters &strategy) const
ReachTreeNode< State >::NodeList_t createNodesFromStates (Transition< Number > *transition, const std::vector< State > &states, std::size_t targetLevel, carl::Interval< tNumber > &coveredTimeInterval, typename ReachTreeNode< State >::Node_t parent)
Public Member Functions inherited from hypro::IJumpHandler
virtual ~IJumpHandler ()
Private Types
using Number = typename State::NumberType
Private Attributes
std::vector< std::tuple< Transition< Number > *, State > > * mSuccessorBuffer
std::shared_ptr< Task< State > > mTask
Transition< Number > * mTransition
StrategyParameters mStrategy
WorkQueue< std::shared_ptr< Task< State > > > * mLocalQueue
WorkQueue< std::shared_ptr< Task< State > > > * mLocalCEXQueue
EventTimingContainer< Number > mObtainedTimings
Detailed Description
template<typename State>
class hypro::ltiJumpHandler< State >
Definition at line 54 of file forwardDeclarations.h.
Member Typedef Documentation
template<typename State > using hypro::ltiJumpHandler< State >::Number = typename State::NumberType private
Definition at line 16 of file ltiJumpHandler.h.
Constructor & Destructor Documentation
template<typename State > hypro::ltiJumpHandler< State >::ltiJumpHandler () delete
template<typename State > hypro::ltiJumpHandler< State >::ltiJumpHandler (std::vector< std::tuple< Transition< Number > *, State >> * successorBuffer, std::shared_ptr< Task< State >> task, Transition< Number > * transition, StrategyParameters strategy, WorkQueue< std::shared_ptr< Task< State >>> * localQueue, WorkQueue< std::shared_ptr< Task< State >>> * localCEXQueue, const EventTimingContainer< typename State::NumberType > & timings) inline
Definition at line 28 of file ltiJumpHandler.h.
References hypro::ltiJumpHandler< State >::handle().
Member Function Documentation
template<typename State > void hypro::ltiJumpHandler< State >::aggregate (std::map< Transition< Number > *, std::vector< State >> & processedStates, const std::map< Transition< Number > *, std::vector< State >> & toAggregate, const StrategyParameters & strategy) const
Referenced by hypro::ltiJumpHandler< State >::handlerName().
template<typename State > std::map<Transition<Number>*, std::vector<State> > hypro::ltiJumpHandler< State >::applyJump (const std::vector< std::tuple< Transition< Number > *, State >> & states, Transition< Number > * transition, const StrategyParameters & strategy)
Referenced by hypro::ltiJumpHandler< State >::handlerName().
template<typename State > ReachTreeNode<State>::NodeList_t hypro::ltiJumpHandler< State >::createNodesFromStates (Transition< Number > * transition, const std::vector< State > & states, std::size_t targetLevel, carl::Interval< tNumber > & coveredTimeInterval, typename ReachTreeNode< State >::Node_t parent)
Referenced by hypro::ltiJumpHandler< State >::handlerName().
template<typename State > void hypro::ltiJumpHandler< State >::handle () virtual
Implements hypro::IJumpHandler.
Referenced by hypro::ltiJumpHandler< State >::ltiJumpHandler().
template<typename State > const char* hypro::ltiJumpHandler< State >::handlerName () inline virtual
Implements hypro::IJumpHandler.
Definition at line 44 of file ltiJumpHandler.h.
References hypro::ltiJumpHandler< State >::aggregate(), hypro::ltiJumpHandler< State >::applyJump(), and hypro::ltiJumpHandler< State >::createNodesFromStates().
Member Data Documentation
template<typename State > WorkQueue<std::shared_ptr<Task<State> > >* hypro::ltiJumpHandler< State >::mLocalCEXQueue private
Definition at line 23 of file ltiJumpHandler.h.
template<typename State > WorkQueue<std::shared_ptr<Task<State> > >* hypro::ltiJumpHandler< State >::mLocalQueue private
Definition at line 22 of file ltiJumpHandler.h.
template<typename State > EventTimingContainer<Number> hypro::ltiJumpHandler< State >::mObtainedTimings private
Definition at line 24 of file ltiJumpHandler.h.
template<typename State > StrategyParameters hypro::ltiJumpHandler< State >::mStrategy private
Definition at line 21 of file ltiJumpHandler.h.
template<typename State > std::vector<std::tuple<Transition<Number>*, State> >* hypro::ltiJumpHandler< State >::mSuccessorBuffer private
Definition at line 18 of file ltiJumpHandler.h.
template<typename State > std::shared_ptr<Task<State> > hypro::ltiJumpHandler< State >::mTask private
Definition at line 19 of file ltiJumpHandler.h.
template<typename State > Transition<Number>* hypro::ltiJumpHandler< State >::mTransition private
Definition at line 20 of file ltiJumpHandler.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/forwardDeclarations.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/jumpHandlers/ltiJumpHandler.h