HyPro: hypro::linearFlow< Number > Class Template Reference
hypro::linearFlow< Number > Class Template Reference
#include <linear.h>
Public Member Functions
linearFlow ()=default
linearFlow (const linearFlow &in)=default
linearFlow (const matrix_t< Number > A)
virtual ~linearFlow ()
std::size_t dimension () const
std::size_t size () const
void setFlowMatrix (const matrix_t< Number > &newA)
void addRow (const vector_t< Number > &row)
const matrix_t< Number > & getFlowMatrix () const
matrix_t< Number > & rGetFlowMatrix ()
bool isIdentity () const
bool hasNoFlow () const
bool isTimed () const
bool isDiscrete () const
Static Public Member Functions
static DynamicType type ()
Protected Attributes
matrix_t< Number > mFlowMatrix = matrix_t<Number>(0, 0)
TRIBOOL mIsIdentity = TRIBOOL::NSET
TRIBOOL mNoFlow = TRIBOOL::NSET
Friends
bool operator== (const linearFlow< Number > &lhs, const linearFlow< Number > &rhs)
bool operator!= (const linearFlow< Number > &lhs, const linearFlow< Number > &rhs)
std::ostream & operator<< (std::ostream &out, const linearFlow< Number > &in)
Detailed Description
template<typename Number>
class hypro::linearFlow< Number >
Definition at line 9 of file linear.h.
Constructor & Destructor Documentation
template<typename Number> hypro::linearFlow< Number >::linearFlow () default
template<typename Number> hypro::linearFlow< Number >::linearFlow (const linearFlow< Number > & in) default
template<typename Number> hypro::linearFlow< Number >::linearFlow (const matrix_t< Number > A) inline
Definition at line 19 of file linear.h.
template<typename Number> virtual hypro::linearFlow< Number >::~linearFlow () inline virtual
Definition at line 21 of file linear.h.
Member Function Documentation
template<typename Number> void hypro::linearFlow< Number >::addRow (const vector_t< Number > & row) inline
Definition at line 33 of file linear.h.
template<typename Number> std::size_t hypro::linearFlow< Number >::dimension () const inline
Definition at line 24 of file linear.h.
Referenced by hypro::affineFlow< Number >::dimension(), and hypro::errorBoxes().
template<typename Number> const matrix_t<Number>& hypro::linearFlow< Number >::getFlowMatrix () const inline
Definition at line 45 of file linear.h.
Referenced by hypro::errorBoxes(), and std::hash< hypro::linearFlow< Number > >::operator()().
template<typename Number> bool hypro::linearFlow< Number >::hasNoFlow () const inline
Definition at line 64 of file linear.h.
Referenced by hypro::affineFlow< Number >::isDiscrete(), hypro::linearFlow< N >::isDiscrete(), and hypro::affineFlow< Number >::isTimed().
template<typename Number> bool hypro::linearFlow< Number >::isDiscrete () const inline
Definition at line 91 of file linear.h.
template<typename Number> bool hypro::linearFlow< Number >::isIdentity () const inline
Definition at line 48 of file linear.h.
template<typename Number> bool hypro::linearFlow< Number >::isTimed () const inline
Definition at line 80 of file linear.h.
template<typename Number> matrix_t<Number>& hypro::linearFlow< Number >::rGetFlowMatrix () inline
Definition at line 46 of file linear.h.
template<typename Number> void hypro::linearFlow< Number >::setFlowMatrix (const matrix_t< Number > & newA) inline
Definition at line 27 of file linear.h.
template<typename Number> std::size_t hypro::linearFlow< Number >::size () const inline
Definition at line 25 of file linear.h.
template<typename Number> static DynamicType hypro::linearFlow< Number >::type () inline static
Definition at line 23 of file linear.h.
Friends And Related Function Documentation
template<typename Number> bool operator!= (const linearFlow< Number > & lhs, const linearFlow< Number > & rhs) friend
Definition at line 99 of file linear.h.
template<typename Number> std::ostream& operator<< (std::ostream & out, const linearFlow< Number > & in) friend
Definition at line 103 of file linear.h.
template<typename Number> bool operator== (const linearFlow< Number > & lhs, const linearFlow< Number > & rhs) friend
Definition at line 95 of file linear.h.
Member Data Documentation
template<typename Number> matrix_t<Number> hypro::linearFlow< Number >::mFlowMatrix = matrix_t<Number>(0, 0) protected
Definition at line 12 of file linear.h.
Referenced by hypro::linearFlow< N >::getFlowMatrix(), and hypro::linearFlow< N >::rGetFlowMatrix().
template<typename Number> TRIBOOL hypro::linearFlow< Number >::mIsIdentity = TRIBOOL::NSET mutable protected
Definition at line 13 of file linear.h.
template<typename Number> TRIBOOL hypro::linearFlow< Number >::mNoFlow = TRIBOOL::NSET mutable protected
Definition at line 14 of file linear.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/flow/linear.h