HyPro: hypro::HybridAutomatonParser::ExpressionContext Class Reference
hypro::HybridAutomatonParser::ExpressionContext Class Reference
#include <HybridAutomatonParser.h>
Public Member Functions
ExpressionContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
PolynomContext * polynom ()
std::vector< ExpressionContext * > expression ()
ExpressionContext * expression (size_t i)
std::vector< TermContext * > term ()
TermContext * term (size_t i)
std::vector< antlr4::tree::TerminalNode * > TIMES ()
antlr4::tree::TerminalNode * TIMES (size_t i)
std::vector< ConnectorContext * > connector ()
ConnectorContext * connector (size_t i)
antlr4::tree::TerminalNode * DIVIDE ()
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Detailed Description
Definition at line 306 of file HybridAutomatonParser.h.
Constructor & Destructor Documentation
HybridAutomatonParser::ExpressionContext::ExpressionContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Definition at line 1128 of file HybridAutomatonParser.cpp.
Member Function Documentation
antlrcpp::Any HybridAutomatonParser::ExpressionContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
Definition at line 1177 of file HybridAutomatonParser.cpp.
std::vector< HybridAutomatonParser::ConnectorContext * > HybridAutomatonParser::ExpressionContext::connector ()
Definition at line 1160 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::expression().
HybridAutomatonParser::ConnectorContext * HybridAutomatonParser::ExpressionContext::connector (size_t i)
Definition at line 1164 of file HybridAutomatonParser.cpp.
References i.
tree::TerminalNode * HybridAutomatonParser::ExpressionContext::DIVIDE ()
Definition at line 1168 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::DIVIDE.
std::vector< HybridAutomatonParser::ExpressionContext * > HybridAutomatonParser::ExpressionContext::expression ()
Definition at line 1136 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::expression().
HybridAutomatonParser::ExpressionContext * HybridAutomatonParser::ExpressionContext::expression (size_t i)
Definition at line 1140 of file HybridAutomatonParser.cpp.
References i.
size_t HybridAutomatonParser::ExpressionContext::getRuleIndex () const override virtual
Definition at line 1173 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::RuleExpression.
HybridAutomatonParser::PolynomContext * HybridAutomatonParser::ExpressionContext::polynom ()
Definition at line 1132 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::expression().
std::vector< HybridAutomatonParser::TermContext * > HybridAutomatonParser::ExpressionContext::term ()
Definition at line 1144 of file HybridAutomatonParser.cpp.
Referenced by hypro::HybridAutomatonParser::expression().
HybridAutomatonParser::TermContext * HybridAutomatonParser::ExpressionContext::term (size_t i)
Definition at line 1148 of file HybridAutomatonParser.cpp.
References i.
std::vector< tree::TerminalNode * > HybridAutomatonParser::ExpressionContext::TIMES ()
Definition at line 1152 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::TIMES.
tree::TerminalNode * HybridAutomatonParser::ExpressionContext::TIMES (size_t i)
Definition at line 1156 of file HybridAutomatonParser.cpp.
References hypro::HybridAutomatonParser::TIMES.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HybridAutomatonParser.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HybridAutomatonParser.cpp