HyPro: hypro::Facet< Number > Class Template Reference
hypro::Facet< Number > Class Template Reference
Class for a facet of a polytope.
#include <Facet.h>
Public Types
using pointVector = std::vector< Point< Number >>
using neighborsSet = std::vector< std::shared_ptr< Facet< Number >>>
Public Member Functions
Facet ()
Facet (const Facet< Number > &f)
Facet (const std::shared_ptr< Facet< Number >> &f)
Facet (std::vector< Point< Number >> r, const Point< Number > &p, const Point< Number > &insidePoint)
Facet (std::vector< Point< Number >> r, const Point< Number > &p, const std::vector< Point< Number >> &outsidePoints, const std::vector< Point< Number >> &currentOutside, const Point< Number > &insidePoint)
Facet (std::vector< Point< Number >> r, const Point< Number > &p, const std::vector< Point< Number >> &insidePoints)
Facet (std::vector< Point< Number >> r, const Point< Number > &p, const Point< Number > &insidePoint1, const Point< Number > &insidePoint2)
Facet (const std::set< vector_t< Number >> &_vertices)
~Facet ()
bool empty () const
pointVector & rVertices ()
const pointVector & vertices () const
neighborsSet & rNeighbors ()
const neighborsSet & neighbors () const
void addNeighbor (const std::shared_ptr< Facet< Number >> &facet)
const vector_t< Number > & getNormal () const
Number getScalar () const
bool removeNeighbor (const std::shared_ptr< Facet< Number >> &facet)
void setPoints (std::vector< Point< Number >> &&points, const Point< Number > &_insidePoint)
void setPoints (std::vector< Point< Number >> &&points, Point< Number > insidePoint1, Point< Number > insidePoint2)
void setPoints (std::vector< Point< Number >> &&points, const std::vector< Point< Number >> &insidePoints)
void setPoints (std::vector< Point< Number >> &&points, const std::vector< Point< Number >> &outsidePoints, const std::vector< Point< Number >> &currentOutside, Point< Number > _insidePoint)
void addPoint (Point< Number > p)
vector_t< Number > getNormalVector () const
Number getScalarVector () const
Halfspace< Number > halfspace () const
pointVector::iterator begin ()
pointVector::const_iterator begin () const
pointVector::iterator end ()
pointVector::const_iterator end () const
bool isBelow (const Point< Number > &p) const
bool isAbove (const Point< Number > &p) const
Number getDist (const Point< Number > &p) const
void addPointToOutsideSet (const Point< Number > &point)
std::vector< Point< Number > > getOutsideSet () const
void removePointFromOutsideSet (const Point< Number > &_point)
Point< Number > furthest_Point () const
bool isNeighbor (const std::shared_ptr< Facet< Number >> &facet) const
Private Attributes
pointVector mVertices
neighborsSet mNeighbors
Halfspace< Number > mHalfspace
pointVector mOutsideSet
vector_t< Number > mNormal
Number mScalar
Friends
bool operator== (const Facet< Number > &_f1, const Facet< Number > &_f2)
bool operator!= (const Facet< Number > &_f1, const Facet< Number > &_f2)
Detailed Description
template<class Number>
class hypro::Facet< Number >
Class for a facet of a polytope.
Template Parameters
Number The used number type.
Definition at line 18 of file Facet.h.
Member Typedef Documentation
template<class Number> using hypro::Facet< Number >::neighborsSet = std::vector<std::shared_ptr<Facet<Number>>>
Definition at line 24 of file Facet.h.
template<class Number> using hypro::Facet< Number >::pointVector = std::vector<Point<Number>>
Typedefs
Definition at line 23 of file Facet.h.
Constructor & Destructor Documentation
template<class Number> hypro::Facet< Number >::Facet () inline
Constructors & Destructor
Definition at line 41 of file Facet.h.
template<class Number> hypro::Facet< Number >::Facet (const Facet< Number > & f) inline
Definition at line 43 of file Facet.h.
template<class Number> hypro::Facet< Number >::Facet (const std::shared_ptr< Facet< Number >> & f) inline
Definition at line 51 of file Facet.h.
template<class Number> hypro::Facet< Number >::Facet (std::vector< Point< Number >> r, const Point< Number > & p, const Point< Number > & insidePoint) inline
Definition at line 59 of file Facet.h.
References hypro::Facet< Number >::mNormal, hypro::Facet< Number >::mScalar, r, and hypro::Facet< Number >::setPoints().
template<class Number> hypro::Facet< Number >::Facet (std::vector< Point< Number >> r, const Point< Number > & p, const std::vector< Point< Number >> & outsidePoints, const std::vector< Point< Number >> & currentOutside, const Point< Number > & insidePoint) inline
Definition at line 65 of file Facet.h.
References hypro::Facet< Number >::mNormal, hypro::Facet< Number >::mScalar, r, and hypro::Facet< Number >::setPoints().
template<class Number> hypro::Facet< Number >::Facet (std::vector< Point< Number >> r, const Point< Number > & p, const std::vector< Point< Number >> & insidePoints) inline
Definition at line 72 of file Facet.h.
References hypro::Facet< Number >::mNormal, hypro::Facet< Number >::mScalar, r, and hypro::Facet< Number >::setPoints().
template<class Number> hypro::Facet< Number >::Facet (std::vector< Point< Number >> r, const Point< Number > & p, const Point< Number > & insidePoint1, const Point< Number > & insidePoint2) inline
Definition at line 78 of file Facet.h.
References hypro::Facet< Number >::mNormal, hypro::Facet< Number >::mScalar, r, and hypro::Facet< Number >::setPoints().
template<class Number> hypro::Facet< Number >::Facet (const std::set< vector_t< Number >> & _vertices) inline
Definition at line 84 of file Facet.h.
References assert(), dimension(), and i.
template<class Number> hypro::Facet< Number >::~Facet () inline
Definition at line 109 of file Facet.h.
Member Function Documentation
template<class Number> void hypro::Facet< Number >::addNeighbor (const std::shared_ptr< Facet< Number >> & facet) inline
Definition at line 125 of file Facet.h.
References assert(), and hypro::Facet< Number >::isNeighbor().
template<class Number> void hypro::Facet< Number >::addPoint (Point< Number > p) inline
Definition at line 263 of file Facet.h.
template<class Number> void hypro::Facet< Number >::addPointToOutsideSet (const Point< Number > & point) inline
Definition at line 368 of file Facet.h.
template<class Number> pointVector::iterator hypro::Facet< Number >::begin () inline
Definition at line 330 of file Facet.h.
template<class Number> pointVector::const_iterator hypro::Facet< Number >::begin () const inline
Definition at line 332 of file Facet.h.
template<class Number> bool hypro::Facet< Number >::empty () const inline
Getters and Setters
Definition at line 115 of file Facet.h.
template<class Number> pointVector::iterator hypro::Facet< Number >::end () inline
Definition at line 334 of file Facet.h.
template<class Number> pointVector::const_iterator hypro::Facet< Number >::end () const inline
Definition at line 336 of file Facet.h.
template<class Number> Point<Number> hypro::Facet< Number >::furthest_Point () const inline
Definition at line 391 of file Facet.h.
References i, max, and temp.
template<class Number> Number hypro::Facet< Number >::getDist (const Point< Number > & p) const inline
Definition at line 363 of file Facet.h.
References hypro::Point< Number >::rawCoordinates(), and temp.
template<class Number> const vector_t<Number>& hypro::Facet< Number >::getNormal () const inline
Definition at line 134 of file Facet.h.
References hypro::Facet< Number >::mNormal.
template<class Number> vector_t<Number> hypro::Facet< Number >::getNormalVector () const inline
Definition at line 279 of file Facet.h.
References b, i, and matrix.
Referenced by hypro::Facet< Number >::setPoints().
template<class Number> std::vector<Point<Number> > hypro::Facet< Number >::getOutsideSet () const inline
Definition at line 372 of file Facet.h.
References hypro::Facet< Number >::mOutsideSet.
template<class Number> Number hypro::Facet< Number >::getScalar () const inline
Definition at line 136 of file Facet.h.
References hypro::Facet< Number >::mScalar.
template<class Number> Number hypro::Facet< Number >::getScalarVector () const inline
Definition at line 322 of file Facet.h.
Referenced by hypro::Facet< Number >::setPoints().
template<class Number> Halfspace<Number> hypro::Facet< Number >::halfspace () const inline
Definition at line 324 of file Facet.h.
References hypro::Facet< Number >::mHalfspace.
template<class Number> bool hypro::Facet< Number >::isAbove (const Point< Number > & p) const inline
Definition at line 358 of file Facet.h.
References hypro::Point< Number >::rawCoordinates(), and temp.
Referenced by hypro::Facet< Number >::setPoints().
template<class Number> bool hypro::Facet< Number >::isBelow (const Point< Number > & p) const inline
Definition at line 346 of file Facet.h.
References hypro::Point< Number >::rawCoordinates(), and temp.
template<class Number> bool hypro::Facet< Number >::isNeighbor (const std::shared_ptr< Facet< Number >> & facet) const inline
Definition at line 408 of file Facet.h.
References i.
Referenced by hypro::Facet< Number >::addNeighbor().
template<class Number> const neighborsSet& hypro::Facet< Number >::neighbors () const inline
Definition at line 123 of file Facet.h.
References hypro::Facet< Number >::mNeighbors.
template<class Number> bool hypro::Facet< Number >::removeNeighbor (const std::shared_ptr< Facet< Number >> & facet) inline
Definition at line 141 of file Facet.h.
References i.
template<class Number> void hypro::Facet< Number >::removePointFromOutsideSet (const Point< Number > & _point) inline
Definition at line 377 of file Facet.h.
References hypro::pointIt< Number >::end.
template<class Number> neighborsSet& hypro::Facet< Number >::rNeighbors () inline
Definition at line 121 of file Facet.h.
References hypro::Facet< Number >::mNeighbors.
template<class Number> pointVector& hypro::Facet< Number >::rVertices () inline
Definition at line 117 of file Facet.h.
References hypro::Facet< Number >::mVertices.
template<class Number> void hypro::Facet< Number >::setPoints (std::vector< Point< Number >> && points, const Point< Number > & _insidePoint) inline
Definition at line 151 of file Facet.h.
References hypro::Facet< Number >::getNormalVector(), hypro::Facet< Number >::getScalarVector(), hypro::Facet< Number >::mNormal, hypro::Facet< Number >::mScalar, points, and hypro::Point< Number >::rawCoordinates().
Referenced by hypro::Facet< Number >::Facet().
template<class Number> void hypro::Facet< Number >::setPoints (std::vector< Point< Number >> && points, Point< Number > insidePoint1, Point< Number > insidePoint2) inline
Definition at line 166 of file Facet.h.
References hypro::Facet< Number >::getNormalVector(), hypro::Facet< Number >::getScalarVector(), hypro::Facet< Number >::mNormal, hypro::Facet< Number >::mScalar, points, and hypro::Point< Number >::rawCoordinates().
template<class Number> void hypro::Facet< Number >::setPoints (std::vector< Point< Number >> && points, const std::vector< Point< Number >> & insidePoints) inline
Definition at line 189 of file Facet.h.
References hypro::Facet< Number >::getNormalVector(), hypro::Facet< Number >::getScalarVector(), i, hypro::Facet< Number >::isAbove(), hypro::Facet< Number >::mNormal, hypro::Facet< Number >::mScalar, and points.
template<class Number> void hypro::Facet< Number >::setPoints (std::vector< Point< Number >> && points, const std::vector< Point< Number >> & outsidePoints, const std::vector< Point< Number >> & currentOutside, Point< Number > _insidePoint) inline
Definition at line 214 of file Facet.h.
References hypro::Facet< Number >::getNormalVector(), hypro::Facet< Number >::getScalarVector(), i, hypro::Facet< Number >::isAbove(), hypro::Facet< Number >::mNormal, hypro::Facet< Number >::mScalar, points, and temp.
template<class Number> const pointVector& hypro::Facet< Number >::vertices () const inline
Definition at line 119 of file Facet.h.
References hypro::Facet< Number >::mVertices.
Friends And Related Function Documentation
template<class Number> bool operator!= (const Facet< Number > & _f1, const Facet< Number > & _f2) friend
Definition at line 440 of file Facet.h.
template<class Number> bool operator== (const Facet< Number > & _f1, const Facet< Number > & _f2) friend
Definition at line 419 of file Facet.h.
Member Data Documentation
template<class Number> Halfspace<Number> hypro::Facet< Number >::mHalfspace private
Definition at line 32 of file Facet.h.
Referenced by hypro::Facet< Number >::halfspace().
template<class Number> neighborsSet hypro::Facet< Number >::mNeighbors private
Definition at line 31 of file Facet.h.
Referenced by hypro::Facet< Number >::neighbors(), and hypro::Facet< Number >::rNeighbors().
template<class Number> vector_t<Number> hypro::Facet< Number >::mNormal private
Definition at line 34 of file Facet.h.
Referenced by hypro::Facet< Number >::Facet(), hypro::Facet< Number >::getNormal(), and hypro::Facet< Number >::setPoints().
template<class Number> pointVector hypro::Facet< Number >::mOutsideSet private
Definition at line 33 of file Facet.h.
Referenced by hypro::Facet< Number >::getOutsideSet().
template<class Number> Number hypro::Facet< Number >::mScalar private
Definition at line 35 of file Facet.h.
Referenced by hypro::Facet< Number >::Facet(), hypro::Facet< Number >::getScalar(), and hypro::Facet< Number >::setPoints().
template<class Number> pointVector hypro::Facet< Number >::mVertices private
Members
Definition at line 30 of file Facet.h.
Referenced by hypro::Facet< Number >::rVertices(), and hypro::Facet< Number >::vertices().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/Facet.h