HyPro: hypro::Label Class Reference
hypro::Label Class Reference
#include <Label.h>
Public Member Functions
Label ()=delete
Label (const Label &in)=default
Label (Label &&in)=default
Label (const std::string &name)
~Label ()
Label & operator= (const Label &in)=default
Label & operator= (Label &&in)=default
const std::string & getName () const
void setName (const std::string &name)
Private Attributes
std::string mName = ""
Friends
bool operator== (const Label &lhs, const Label &rhs)
bool operator!= (const Label &lhs, const Label &rhs)
bool operator< (const Label &lhs, const Label &rhs)
std::ostream & operator<< (std::ostream &ostr, const Label &l)
Detailed Description
Definition at line 15 of file Label.h.
Constructor & Destructor Documentation
hypro::Label::Label () delete
hypro::Label::Label (const Label & in) default
hypro::Label::Label (Label && in) default
hypro::Label::Label (const std::string & name) inline explicit
Definition at line 24 of file Label.h.
hypro::Label::~Label () inline
Definition at line 27 of file Label.h.
References operator=().
Member Function Documentation
const std::string& hypro::Label::getName () const inline
Definition at line 32 of file Label.h.
References assert(), and mName.
Label& hypro::Label::operator= (const Label & in) default
Referenced by ~Label().
Label& hypro::Label::operator= (Label && in) default
void hypro::Label::setName (const std::string & name) inline
Definition at line 37 of file Label.h.
References name.
Friends And Related Function Documentation
bool operator!= (const Label & lhs, const Label & rhs) friend
Definition at line 43 of file Label.h.
bool operator< (const Label & lhs, const Label & rhs) friend
Definition at line 47 of file Label.h.
std::ostream& operator<< (std::ostream & ostr, const Label & l) friend
Definition at line 51 of file Label.h.
bool operator== (const Label & lhs, const Label & rhs) friend
Definition at line 39 of file Label.h.
Member Data Documentation
std::string hypro::Label::mName = "" private
Definition at line 17 of file Label.h.
Referenced by getName().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/Label.h