HyPro: hypro::PolytopeSupportFunction< Number, Setting > Class Template Reference
hypro::PolytopeSupportFunction< Number, Setting > Class Template Reference
#include <PolytopeSupportFunction.h>
Public Member Functions
PolytopeSupportFunction (matrix_t< Number > constraints, vector_t< Number > constraintConstants)
PolytopeSupportFunction (const std::vector< Halfspace< Number >> &_planes)
PolytopeSupportFunction (const std::vector< Point< Number >> &_points)
PolytopeSupportFunction (const PolytopeSupportFunction< Number, Setting > &_origin)
~PolytopeSupportFunction ()
PolytopeSupportFunction< Number, Setting > & operator= (const PolytopeSupportFunction &_orig)
std::size_t dimension () const
SF_TYPE type () const
bool isTemplate () const
matrix_t< Number > constraints () const
vector_t< Number > constants () const
std::vector< Point< Number > > vertices () const
Point< Number > supremumPoint () const
EvaluationResult< Number > evaluate (const vector_t< Number > &l, bool useExact) const
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &_A, bool useExact, bool setTemplate=false) const
Evaluates the support function in the directions given in the passed matrix.
bool contains (const Point< Number > &_point) const
Check if point is contained in the support function.
bool contains (const vector_t< Number > &_point) const
Check if point is contained in the support function.
bool empty () const
void cleanUp () const
void print () const
std::string getDotRepresentation () const
std::string createCode (unsigned index=0) const
Private Member Functions
void removeRedundancy ()
matrix_t< Number > & rMatrix ()
vector_t< Number > & rVector ()
Private Attributes
friend SupportFunctionContent< Number, Setting >
matrix_t< Number > mConstraints
vector_t< Number > mConstraintConstants
Optimizer< Number > mOpt
std::size_t mDimension
std::map< vector_t< Number >, Number > mCache
Friends
template<typename N , typename C , typename S >
class SupportFunctionT
std::ostream & operator<< (std::ostream &lhs, const PolytopeSupportFunction< Number, Setting > &rhs)
Detailed Description
template<typename Number, class Setting>
class hypro::PolytopeSupportFunction< Number, Setting >
Definition at line 45 of file PolytopeSupportFunction.h.
Constructor & Destructor Documentation
template<typename Number, class Setting> hypro::PolytopeSupportFunction< Number, Setting >::PolytopeSupportFunction (matrix_t< Number > constraints, vector_t< Number > constraintConstants)
template<typename Number, class Setting> hypro::PolytopeSupportFunction< Number, Setting >::PolytopeSupportFunction (const std::vector< Halfspace< Number >> & _planes)
template<typename Number, class Setting> hypro::PolytopeSupportFunction< Number, Setting >::PolytopeSupportFunction (const std::vector< Point< Number >> & _points)
template<typename Number, class Setting> hypro::PolytopeSupportFunction< Number, Setting >::PolytopeSupportFunction (const PolytopeSupportFunction< Number, Setting > & _origin)
template<typename Number, class Setting> hypro::PolytopeSupportFunction< Number, Setting >::~PolytopeSupportFunction ()
Member Function Documentation
template<typename Number, class Setting> void hypro::PolytopeSupportFunction< Number, Setting >::cleanUp () const
Referenced by hypro::PolytopeSupportFunction< Number, Setting >::isTemplate().
template<typename Number, class Setting> vector_t<Number> hypro::PolytopeSupportFunction< Number, Setting >::constants () const
Referenced by hypro::PolytopeSupportFunction< Number, Setting >::isTemplate().
template<typename Number, class Setting> matrix_t<Number> hypro::PolytopeSupportFunction< Number, Setting >::constraints () const
Referenced by hypro::PolytopeSupportFunction< Number, Setting >::isTemplate().
template<typename Number, class Setting> bool hypro::PolytopeSupportFunction< Number, Setting >::contains (const Point< Number > & _point) const
Check if point is contained in the support function.
To check if the given point is contained in the support function we evaluate it in all its directions (uses multiEvaluate).
Parameters
_point The point to check.
Returns
True, if the point is inside the support function.
Referenced by hypro::PolytopeSupportFunction< Number, Setting >::isTemplate().
template<typename Number, class Setting> bool hypro::PolytopeSupportFunction< Number, Setting >::contains (const vector_t< Number > & _point) const
Check if point is contained in the support function.
To check if the given point is contained in the support function we evaluate it in all its directions (uses multiEvaluate).
Parameters
_point The point to check.
Returns
True, if the point is inside the support function.
template<typename Number, class Setting> std::string hypro::PolytopeSupportFunction< Number, Setting >::createCode (unsigned index = 0) const
Referenced by hypro::PolytopeSupportFunction< Number, Setting >::isTemplate().
template<typename Number, class Setting> std::size_t hypro::PolytopeSupportFunction< Number, Setting >::dimension () const
Returns the dimension of the object.
Returns
template<typename Number, class Setting> bool hypro::PolytopeSupportFunction< Number, Setting >::empty () const
Referenced by hypro::PolytopeSupportFunction< Number, Setting >::isTemplate().
template<typename Number, class Setting> EvaluationResult<Number> hypro::PolytopeSupportFunction< Number, Setting >::evaluate (const vector_t< Number > & l, bool useExact) const
Evaluates the support function in the given direction.
Parameters
l
Returns
Referenced by hypro::PolytopeSupportFunction< Number, Setting >::isTemplate().
template<typename Number, class Setting> std::string hypro::PolytopeSupportFunction< Number, Setting >::getDotRepresentation () const
Referenced by hypro::SupportFunctionContent< Number, Setting >::getDotRepresentation(), and hypro::PolytopeSupportFunction< Number, Setting >::isTemplate().
template<typename Number, class Setting> bool hypro::PolytopeSupportFunction< Number, Setting >::isTemplate () const inline
Definition at line 74 of file PolytopeSupportFunction.h.
References hypro::PolytopeSupportFunction< Number, Setting >::cleanUp(), hypro::PolytopeSupportFunction< Number, Setting >::constants(), hypro::PolytopeSupportFunction< Number, Setting >::constraints(), hypro::PolytopeSupportFunction< Number, Setting >::contains(), hypro::PolytopeSupportFunction< Number, Setting >::createCode(), hypro::PolytopeSupportFunction< Number, Setting >::empty(), hypro::PolytopeSupportFunction< Number, Setting >::evaluate(), hypro::PolytopeSupportFunction< Number, Setting >::getDotRepresentation(), index, l, hypro::PolytopeSupportFunction< Number, Setting >::multiEvaluate(), hypro::PolytopeSupportFunction< Number, Setting >::print(), string(), hypro::PolytopeSupportFunction< Number, Setting >::supremumPoint(), and hypro::PolytopeSupportFunction< Number, Setting >::vertices().
template<typename Number, class Setting> std::vector<EvaluationResult<Number> > hypro::PolytopeSupportFunction< Number, Setting >::multiEvaluate (const matrix_t< Number > & _A, bool useExact, bool setTemplate = false) const
Evaluates the support function in the directions given in the passed matrix.
Uses the standard evaluate method for multiple directions.
Parameters
_A Matrix holding the directions in which to evaluate.
Returns
Vector of support values.
Referenced by hypro::PolytopeSupportFunction< Number, Setting >::isTemplate().
template<typename Number, class Setting> PolytopeSupportFunction<Number, Setting>& hypro::PolytopeSupportFunction< Number, Setting >::operator= (const PolytopeSupportFunction< Number, Setting > & _orig)
template<typename Number, class Setting> void hypro::PolytopeSupportFunction< Number, Setting >::print () const
Referenced by hypro::PolytopeSupportFunction< Number, Setting >::isTemplate().
template<typename Number, class Setting> void hypro::PolytopeSupportFunction< Number, Setting >::removeRedundancy () private
template<typename Number, class Setting> matrix_t<Number>& hypro::PolytopeSupportFunction< Number, Setting >::rMatrix () inline private
Definition at line 147 of file PolytopeSupportFunction.h.
References hypro::PolytopeSupportFunction< Number, Setting >::mConstraints.
template<typename Number, class Setting> vector_t<Number>& hypro::PolytopeSupportFunction< Number, Setting >::rVector () inline private
Definition at line 148 of file PolytopeSupportFunction.h.
References hypro::PolytopeSupportFunction< Number, Setting >::mConstraintConstants.
template<typename Number, class Setting> Point<Number> hypro::PolytopeSupportFunction< Number, Setting >::supremumPoint () const
Referenced by hypro::PolytopeSupportFunction< Number, Setting >::isTemplate().
template<typename Number, class Setting> SF_TYPE hypro::PolytopeSupportFunction< Number, Setting >::type () const
template<typename Number, class Setting> std::vector<Point<Number> > hypro::PolytopeSupportFunction< Number, Setting >::vertices () const
Referenced by hypro::PolytopeSupportFunction< Number, Setting >::isTemplate().
Friends And Related Function Documentation
template<typename Number, class Setting> std::ostream& operator<< (std::ostream & lhs, const PolytopeSupportFunction< Number, Setting > & rhs) friend
Definition at line 128 of file PolytopeSupportFunction.h.
template<typename Number, class Setting> template<typename N , typename C , typename S > friend class SupportFunctionT friend
Definition at line 48 of file PolytopeSupportFunction.h.
Member Data Documentation
template<typename Number, class Setting> std::map<vector_t<Number>, Number> hypro::PolytopeSupportFunction< Number, Setting >::mCache private
Definition at line 55 of file PolytopeSupportFunction.h.
template<typename Number, class Setting> vector_t<Number> hypro::PolytopeSupportFunction< Number, Setting >::mConstraintConstants private
Definition at line 52 of file PolytopeSupportFunction.h.
Referenced by hypro::PolytopeSupportFunction< Number, Setting >::rVector().
template<typename Number, class Setting> matrix_t<Number> hypro::PolytopeSupportFunction< Number, Setting >::mConstraints private
Definition at line 51 of file PolytopeSupportFunction.h.
Referenced by hypro::PolytopeSupportFunction< Number, Setting >::rMatrix().
template<typename Number, class Setting> std::size_t hypro::PolytopeSupportFunction< Number, Setting >::mDimension private
Definition at line 54 of file PolytopeSupportFunction.h.
template<typename Number, class Setting> Optimizer<Number> hypro::PolytopeSupportFunction< Number, Setting >::mOpt mutable private
Definition at line 53 of file PolytopeSupportFunction.h.
template<typename Number, class Setting> friend hypro::PolytopeSupportFunction< Number, Setting >::SupportFunctionContent< Number, Setting > private
Definition at line 46 of file PolytopeSupportFunction.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunction/PolytopeSupportFunction.h