HyPro: hypro::FourierMotzkinQE< Number > Class Template Reference
hypro::FourierMotzkinQE< Number > Class Template Reference
Provides a simple implementation for Fourier Motzkin variable elimination for linear, existentially quantified constraints.
#include <FourierMotzkinQE.h>
Public Types
using FormulaPartition = std::vector< FormulasT< Number >>
Public Member Functions
FourierMotzkinQE (const FormulaT< Number > &qfree, const QEQuery &quantifiers)
FormulaT< Number > eliminateQuantifiers ()
Private Member Functions
FormulaPartition findBounds (const carl::Variable &variable)
FormulasT< Number > createNewConstraints (const FormulaPartition &bounds, carl::Variable v)
FormulasT< Number > substituteEquations (const FormulaPartition &bounds, carl::Variable v)
bool isLinearLowerBound (const ConstraintT< Number > &f, carl::Variable v)
PolyT< Number > getRemainder (const ConstraintT< Number > &c, carl::Variable v, bool isLowerBnd)
Private Attributes
QEQuery mQuery
FormulaT< Number > mFormula
Detailed Description
template<typename Number>
class hypro::FourierMotzkinQE< Number >
Provides a simple implementation for Fourier Motzkin variable elimination for linear, existentially quantified constraints.
Definition at line 12 of file FourierMotzkinQE.h.
Member Typedef Documentation
template<typename Number> using hypro::FourierMotzkinQE< Number >::FormulaPartition = std::vector<FormulasT<Number>>
Definition at line 16 of file FourierMotzkinQE.h.
Constructor & Destructor Documentation
template<typename Number> hypro::FourierMotzkinQE< Number >::FourierMotzkinQE (const FormulaT< Number > & qfree, const QEQuery & quantifiers) inline
Definition at line 23 of file FourierMotzkinQE.h.
References assert(), c, hypro::FourierMotzkinQE< Number >::createNewConstraints(), hypro::FourierMotzkinQE< Number >::eliminateQuantifiers(), hypro::FourierMotzkinQE< Number >::findBounds(), hypro::FourierMotzkinQE< Number >::getRemainder(), hypro::FourierMotzkinQE< Number >::isLinearLowerBound(), hypro::FourierMotzkinQE< Number >::substituteEquations(), and v.
Member Function Documentation
template<typename Number> FormulasT<Number> hypro::FourierMotzkinQE< Number >::createNewConstraints (const FormulaPartition & bounds, carl::Variable v) private
Referenced by hypro::FourierMotzkinQE< Number >::FourierMotzkinQE().
template<typename Number> FormulaT<Number> hypro::FourierMotzkinQE< Number >::eliminateQuantifiers ()
Referenced by hypro::eliminateQuantifiers(), and hypro::FourierMotzkinQE< Number >::FourierMotzkinQE().
template<typename Number> FormulaPartition hypro::FourierMotzkinQE< Number >::findBounds (const carl::Variable & variable) private
Referenced by hypro::FourierMotzkinQE< Number >::FourierMotzkinQE().
template<typename Number> PolyT<Number> hypro::FourierMotzkinQE< Number >::getRemainder (const ConstraintT< Number > & c, carl::Variable v, bool isLowerBnd) private
Referenced by hypro::FourierMotzkinQE< Number >::FourierMotzkinQE().
template<typename Number> bool hypro::FourierMotzkinQE< Number >::isLinearLowerBound (const ConstraintT< Number > & f, carl::Variable v) private
Referenced by hypro::FourierMotzkinQE< Number >::FourierMotzkinQE().
template<typename Number> FormulasT<Number> hypro::FourierMotzkinQE< Number >::substituteEquations (const FormulaPartition & bounds, carl::Variable v) private
Referenced by hypro::FourierMotzkinQE< Number >::FourierMotzkinQE().
Member Data Documentation
template<typename Number> FormulaT<Number> hypro::FourierMotzkinQE< Number >::mFormula private
Definition at line 20 of file FourierMotzkinQE.h.
template<typename Number> QEQuery hypro::FourierMotzkinQE< Number >::mQuery private
Definition at line 19 of file FourierMotzkinQE.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/algorithms/quantifierElimination/FourierMotzkinQE.h