HyPro: hypro::HyproBadStatesVisitor< Number > Class Template Reference
hypro::HyproBadStatesVisitor< Number > Class Template Reference
Public Member Functions
std::vector< Condition< Number > > getGlobalBadStates ()
antlrcpp::Any visitUnsafeset (HybridAutomatonParser::UnsafesetContext *ctx) override
antlrcpp::Any visitLbadstate (HybridAutomatonParser::LbadstateContext *ctx) override
antlrcpp::Any visitGbadstate (HybridAutomatonParser::GbadstateContext *ctx) override
Public Member Functions inherited from hypro::HybridAutomatonBaseVisitor
virtual antlrcpp::Any visitStart (HybridAutomatonParser::StartContext *ctx) override
virtual antlrcpp::Any visitVardeclaration (HybridAutomatonParser::VardeclarationContext *ctx) override
virtual antlrcpp::Any visitConstantdeclaration (HybridAutomatonParser::ConstantdeclarationContext *ctx) override
virtual antlrcpp::Any visitModes (HybridAutomatonParser::ModesContext *ctx) override
virtual antlrcpp::Any visitLocation (HybridAutomatonParser::LocationContext *ctx) override
virtual antlrcpp::Any visitActivities (HybridAutomatonParser::ActivitiesContext *ctx) override
virtual antlrcpp::Any visitInvariants (HybridAutomatonParser::InvariantsContext *ctx) override
virtual antlrcpp::Any visitReplacedexpr (HybridAutomatonParser::ReplacedexprContext *ctx) override
virtual antlrcpp::Any visitConstantexpr (HybridAutomatonParser::ConstantexprContext *ctx) override
virtual antlrcpp::Any visitConnector (HybridAutomatonParser::ConnectorContext *ctx) override
virtual antlrcpp::Any visitTerm (HybridAutomatonParser::TermContext *ctx) override
virtual antlrcpp::Any visitPolynom (HybridAutomatonParser::PolynomContext *ctx) override
virtual antlrcpp::Any visitExpression (HybridAutomatonParser::ExpressionContext *ctx) override
virtual antlrcpp::Any visitEquation (HybridAutomatonParser::EquationContext *ctx) override
virtual antlrcpp::Any visitConstraint (HybridAutomatonParser::ConstraintContext *ctx) override
virtual antlrcpp::Any visitInterval (HybridAutomatonParser::IntervalContext *ctx) override
virtual antlrcpp::Any visitIntervalexpr (HybridAutomatonParser::IntervalexprContext *ctx) override
virtual antlrcpp::Any visitConstrset (HybridAutomatonParser::ConstrsetContext *ctx) override
virtual antlrcpp::Any visitInit (HybridAutomatonParser::InitContext *ctx) override
virtual antlrcpp::Any visitInitstate (HybridAutomatonParser::InitstateContext *ctx) override
virtual antlrcpp::Any visitJumps (HybridAutomatonParser::JumpsContext *ctx) override
virtual antlrcpp::Any visitTransition (HybridAutomatonParser::TransitionContext *ctx) override
virtual antlrcpp::Any visitFromto (HybridAutomatonParser::FromtoContext *ctx) override
virtual antlrcpp::Any visitUrgent (HybridAutomatonParser::UrgentContext *ctx) override
virtual antlrcpp::Any visitGuard (HybridAutomatonParser::GuardContext *ctx) override
virtual antlrcpp::Any visitLabels (HybridAutomatonParser::LabelsContext *ctx) override
virtual antlrcpp::Any visitAllocation (HybridAutomatonParser::AllocationContext *ctx) override
virtual antlrcpp::Any visitResetfct (HybridAutomatonParser::ResetfctContext *ctx) override
virtual antlrcpp::Any visitAggregation (HybridAutomatonParser::AggregationContext *ctx) override
virtual antlrcpp::Any visitSetting (HybridAutomatonParser::SettingContext *ctx) override
virtual antlrcpp::Any visitFixedsteps (HybridAutomatonParser::FixedstepsContext *ctx) override
virtual antlrcpp::Any visitTime (HybridAutomatonParser::TimeContext *ctx) override
virtual antlrcpp::Any visitPlotsetting (HybridAutomatonParser::PlotsettingContext *ctx) override
virtual antlrcpp::Any visitFilename (HybridAutomatonParser::FilenameContext *ctx) override
virtual antlrcpp::Any visitMaxjumps (HybridAutomatonParser::MaxjumpsContext *ctx) override
virtual antlrcpp::Any visitPrint (HybridAutomatonParser::PrintContext *ctx) override
virtual antlrcpp::Any visitRemainder (HybridAutomatonParser::RemainderContext *ctx) override
virtual antlrcpp::Any visitIdentity (HybridAutomatonParser::IdentityContext *ctx) override
virtual antlrcpp::Any visitQrprecond (HybridAutomatonParser::QrprecondContext *ctx) override
virtual antlrcpp::Any visitFixedorders (HybridAutomatonParser::FixedordersContext *ctx) override
virtual antlrcpp::Any visitAdaptiveorders (HybridAutomatonParser::AdaptiveordersContext *ctx) override
virtual antlrcpp::Any visitCutoff (HybridAutomatonParser::CutoffContext *ctx) override
virtual antlrcpp::Any visitPrecision (HybridAutomatonParser::PrecisionContext *ctx) override
Friends
class HyproHAVisitor< Number >
Detailed Description
template<typename Number>
class hypro::HyproBadStatesVisitor< Number >
Definition at line 22 of file HyproBadStatesVisitor.h.
Member Function Documentation
template<typename Number> std::vector<Condition<Number> > hypro::HyproBadStatesVisitor< Number >::getGlobalBadStates () inline
Definition at line 44 of file HyproBadStatesVisitor.h.
References hypro::HyproBadStatesVisitor< Number >::visitGbadstate(), hypro::HyproBadStatesVisitor< Number >::visitLbadstate(), and hypro::HyproBadStatesVisitor< Number >::visitUnsafeset().
Referenced by hypro::HyproHAVisitor< Number >::visitStart().
template<typename Number > antlrcpp::Any hypro::HyproBadStatesVisitor< Number >::visitGbadstate (HybridAutomatonParser::GbadstateContext * ctx) override virtual
Reimplemented from hypro::HybridAutomatonBaseVisitor.
Definition at line 103 of file HyproBadStatesVisitor.tpp.
References hypro::HybridAutomatonParser::GbadstateContext::constrset().
Referenced by hypro::HyproBadStatesVisitor< Number >::getGlobalBadStates().
template<typename Number > antlrcpp::Any hypro::HyproBadStatesVisitor< Number >::visitLbadstate (HybridAutomatonParser::LbadstateContext * ctx) override virtual
Reimplemented from hypro::HybridAutomatonBaseVisitor.
Definition at line 73 of file HyproBadStatesVisitor.tpp.
References hypro::HybridAutomatonParser::LbadstateContext::constrset(), and hypro::HybridAutomatonParser::LbadstateContext::VARIABLE().
Referenced by hypro::HyproBadStatesVisitor< Number >::getGlobalBadStates().
template<typename Number > antlrcpp::Any hypro::HyproBadStatesVisitor< Number >::visitUnsafeset (HybridAutomatonParser::UnsafesetContext * ctx) override virtual
Reimplemented from hypro::HybridAutomatonBaseVisitor.
Definition at line 20 of file HyproBadStatesVisitor.tpp.
References hypro::HybridAutomatonParser::UnsafesetContext::gbadstate(), and hypro::HybridAutomatonParser::UnsafesetContext::lbadstate().
Referenced by hypro::HyproBadStatesVisitor< Number >::getGlobalBadStates().
Friends And Related Function Documentation
template<typename Number> friend class HyproHAVisitor< Number > friend
Definition at line 24 of file HyproBadStatesVisitor.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HyproBadStatesVisitor.h
/home/travis/build/hypro/hypro/src/hypro/parser/antlr4-flowstar/HyproBadStatesVisitor.tpp