HyPro: hypro::ZonotopeT< Number, Converter, Setting > Class Template Reference
hypro::ZonotopeT< Number, Converter, Setting > Class Template Reference
State set representations
Class for Zonotopes.
Public Types
typedef Setting Settings
typedef Number NumberType
Public Member Functions
ZonotopeT ()
ZonotopeT (std::size_t dimension)
ZonotopeT (const vector_t< Number > &center, const matrix_t< Number > &generators)
ZonotopeT (const ZonotopeT &other)=default
ZonotopeT (const ZonotopeT &other, unsigned d1, unsigned d2)
virtual ~ZonotopeT ()
matrix_t< Number > matrix () const
vector_t< Number > vector () const
std::size_t dimension () const
Number supremum () const
bool empty () const
void setCenter (const vector_t< Number > &center)
void setGenerators (const matrix_t< Number > &generators_)
bool addGenerators (const matrix_t< Number > &generators)
const vector_t< Number > & center () const
const matrix_t< Number > & generators () const
Number order () const
std::size_t size () const
void removeEmptyGenerators ()
void uniteEqualVectors ()
bool changeDimension (std::size_t new_dim)
void clear ()
void print () const
bool operator== (const ZonotopeT< Number, Converter, Setting > &rhs) const
void removeRedundancy () const
void reduceOrder (unsigned limit=Setting::ZONOTOPE_ORDERLIMIT)
void reduceNumberRepresentation ()
EvaluationResult< Number > evaluate (const vector_t< Number > &directions) const
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &directions, bool useExact=true) const
ZonotopeT minkowskiSum (const ZonotopeT &rhs) const
ZonotopeT project (const std::vector< std::size_t > &dimensions) const
ZonotopeT assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const
ZonotopeT linearTransformation (const matrix_t< Number > &A) const
ZonotopeT affineTransformation (const matrix_t< Number > &A, const vector_t< Number > &b) const
std::vector< vector_t< Number > > computeZonotopeBoundary ()
std::vector< Point< Number > > vertices (const matrix_t< Number > &=matrix_t< Number >::Zero(0, 0)) const
Compute a set of points containing the extreme points of a zonotopeT.
ZonotopeT intersectHalfspace (const Halfspace< Number > &rhs) const
ZonotopeT intersectHalfspaces (const matrix_t< Number > &mat, const vector_t< Number > &vec) const
std::pair< CONTAINMENT, ZonotopeT > satisfiesHalfspace (const Halfspace< Number > &rhs) const
std::pair< CONTAINMENT, ZonotopeT > satisfiesHalfspaces (const matrix_t< Number > &mat, const vector_t< Number > &vec) const
ZonotopeT intersect (const Parma_Polyhedra_Library::Constraint &halfspace) const
ZonotopeT intersect (const Halfspace< Number > &rhs, int method)
ZonotopeT< Number, Converter, Setting > intersect (const ZonotopeT< Number, Converter, Setting > &) const
ZonotopeT intersectHalfspaces (const matrix_t< Number > &mat, const vector_t< Number > vec, int method)
ZonotopeT intersect (const Halfspace< Number > &rhs, matrix_t< Number > &minMaxOfLine, int method)
ZonotopeT intersect (const Parma_Polyhedra_Library::C_Polyhedron &rhs) const
ZonotopeT unite (const ZonotopeT &other) const
void reduceRepresentation ()
Reduces the zonotope by reducing order, number representation and removing redundant generators.
ZonotopeT intervalHull () const
bool contains (const Point< Number > &point) const
bool contains (const ZonotopeT< Number, Converter, Setting > &) const
Static Public Member Functions
static ZonotopeT Empty (std::size_t dimension=1)
static representation_name type ()
static ZonotopeT unite (const std::vector< ZonotopeT > &sets)
Detailed Description
template<typename Number, typename Converter, typename Setting>
class hypro::ZonotopeT< Number, Converter, Setting >
Class for Zonotopes.
Template Parameters
Number The used number type.
Converter The converter. @{
Definition at line 42 of file Zonotope.h.
Member Typedef Documentation
template<typename Number, typename Converter, typename Setting> typedef Number hypro::ZonotopeT< Number, Converter, Setting >::NumberType
Definition at line 45 of file Zonotope.h.
template<typename Number, typename Converter, typename Setting> typedef Setting hypro::ZonotopeT< Number, Converter, Setting >::Settings
Definition at line 44 of file Zonotope.h.
Constructor & Destructor Documentation
template<typename Number , typename Converter , typename Setting > hypro::ZonotopeT< Number, Converter, Setting >::ZonotopeT ()
Definition at line 74 of file Zonotope.tpp.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::Empty(), and hypro::ZonotopeT< Number, Converter, Setting >::ZonotopeT().
template<typename Number , typename Converter , typename Setting > hypro::ZonotopeT< Number, Converter, Setting >::ZonotopeT (std::size_t dimension) explicit
Constructor with dimension
Parameters
dimension Dimensionality of ZonotopeT
Definition at line 80 of file Zonotope.tpp.
template<typename Number , typename Converter , typename Setting > hypro::ZonotopeT< Number, Converter, Setting >::ZonotopeT (const vector_t< Number > & center, const matrix_t< Number > & generators)
Constructs a ZonotopeT with center and generators.
Parameters
center A (nx1) vector
generators A (nxm) vector
Definition at line 88 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::center(), hypro::ZonotopeT< Number, Converter, Setting >::generators(), hypro::ZonotopeT< Number, Converter, Setting >::removeEmptyGenerators(), hypro::ZonotopeT< Number, Converter, Setting >::size(), hypro::ZonotopeT< Number, Converter, Setting >::uniteEqualVectors(), and hypro::ZonotopeT< Number, Converter, Setting >::ZonotopeT().
template<typename Number, typename Converter, typename Setting> hypro::ZonotopeT< Number, Converter, Setting >::ZonotopeT (const ZonotopeT< Number, Converter, Setting > & other) default
Copy Constructor - constructs a zonotopeT from an existing one.
Parameters
other Another ZonotopeT, from which a new zonotopeT is constructed
template<typename Number, typename Converter, typename Setting> hypro::ZonotopeT< Number, Converter, Setting >::ZonotopeT (const ZonotopeT< Number, Converter, Setting > & other, unsigned d1, unsigned d2)
Copy Constructor - constructs a 2D-zonotopeT of from an existing ND one.
Parameters
other : Another ZonotopeT, from which a new zonotopeT is constructed
d1 : 1st dimension (0 <= d1 < other.dimension)
d2 : 2nd dimension (0 <= d2 < other.dimension) d1!=d2
template<typename Number , typename Converter , typename Setting > hypro::ZonotopeT< Number, Converter, Setting >::~ZonotopeT () virtual
Definition at line 117 of file Zonotope.tpp.
Member Function Documentation
template<typename Number , typename Converter , typename Setting > bool hypro::ZonotopeT< Number, Converter, Setting >::addGenerators (const matrix_t< Number > & generators)
Add generators to ZonotopeT. Simply performs setGenerators if generators was previously not initialized.
Parameters
generators
Returns
true if able to add generators
Definition at line 198 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::generators(), hypro::ZonotopeT< Number, Converter, Setting >::removeEmptyGenerators(), hypro::ZonotopeT< Number, Converter, Setting >::setGenerators(), and hypro::ZonotopeT< Number, Converter, Setting >::uniteEqualVectors().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::intersect(), hypro::ZonotopeT< Number, Converter, Setting >::intersectHalfspace(), hypro::ZonotopeT< Number, Converter, Setting >::satisfiesHalfspace(), and hypro::ZonotopeT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > ZonotopeT< Number, Converter, Setting > hypro::ZonotopeT< Number, Converter, Setting >::affineTransformation (const matrix_t< Number > & A, const vector_t< Number > & b) const
Definition at line 428 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::setCenter().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::assignIntervals().
template<typename Number, typename Converter, typename Setting> ZonotopeT hypro::ZonotopeT< Number, Converter, Setting >::assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const inline
Definition at line 212 of file Zonotope.h.
References hypro::ZonotopeT< Number, Converter, Setting >::affineTransformation(), hypro::ZonotopeT< Number, Converter, Setting >::computeZonotopeBoundary(), hypro::ZonotopeT< Number, Converter, Setting >::intersect(), hypro::ZonotopeT< Number, Converter, Setting >::intersectHalfspace(), hypro::ZonotopeT< Number, Converter, Setting >::intersectHalfspaces(), hypro::ZonotopeT< Number, Converter, Setting >::linearTransformation(), hypro::ZonotopeT< Number, Converter, Setting >::satisfiesHalfspace(), hypro::ZonotopeT< Number, Converter, Setting >::satisfiesHalfspaces(), and hypro::ZonotopeT< Number, Converter, Setting >::vertices().
template<typename Number , typename Converter , typename Setting > const vector_t< Number > & hypro::ZonotopeT< Number, Converter, Setting >::center () const
Definition at line 155 of file Zonotope.tpp.
Referenced by hypro::intersect2d(), hypro::intersectAlamo(), hypro::intersectNDProjection(), hypro::ZonotopeT< Number, Converter, Setting >::intervalHull(), hypro::ZonotopeT< Number, Converter, Setting >::operator==(), hypro::ZonotopeT< Number, Converter, Setting >::setCenter(), hypro::ZonotopeT< Number, Converter, Setting >::type(), and hypro::ZonotopeT< Number, Converter, Setting >::ZonotopeT().
template<typename Number , typename Converter , typename Setting > bool hypro::ZonotopeT< Number, Converter, Setting >::changeDimension (std::size_t new_dim)
Changes the dimension of a ZonotopeT. if new_dim > old dim, new rows are initialized with null
Parameters
new_dim The new dimension of the ZonotopeT
Returns
True, if change in dimension was successful
Definition at line 273 of file Zonotope.tpp.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > void hypro::ZonotopeT< Number, Converter, Setting >::clear ()
Clears the generators and center of the ZonotopeT and sets dimensionality to zero
Definition at line 293 of file Zonotope.tpp.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > std::vector< vector_t< Number > > hypro::ZonotopeT< Number, Converter, Setting >::computeZonotopeBoundary ()
Compute boundaries of zonotopeT
Returns
array of points represented as vectors
Definition at line 445 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::generators(), and hypro::ZonotopeT< Number, Converter, Setting >::removeEmptyGenerators().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::assignIntervals(), and hypro::intersectZonotopeHalfspaceDSearch().
template<typename Number , typename Converter , typename Setting > bool hypro::ZonotopeT< Number, Converter, Setting >::contains (const Point< Number > & point) const
Definition at line 1245 of file Zonotope.tpp.
References hypro::Optimizer< Number >::checkConsistency(), hypro::ZonotopeT< Number, Converter, Setting >::dimension(), and hypro::Point< Number >::rawCoordinates().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number, typename Converter, typename Setting> bool hypro::ZonotopeT< Number, Converter, Setting >::contains (const ZonotopeT< Number, Converter, Setting > &) const inline
Definition at line 312 of file Zonotope.h.
template<typename Number , typename Converter , typename Setting > std::size_t hypro::ZonotopeT< Number, Converter, Setting >::dimension () const
Dimensionality of ZonotopeT
Returns
the dimension
Definition at line 127 of file Zonotope.tpp.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::contains(), hypro::intersect2d(), hypro::intersectAlamo(), hypro::intersectNDProjection(), hypro::intersectZonotopeHalfspaceDSearch(), hypro::ZonotopeT< Number, Converter, Setting >::minkowskiSum(), hypro::ZonotopeT< Number, Converter, Setting >::operator==(), hypro::ZonotopeT< Number, Converter, Setting >::project(), hypro::ZonotopeT< Number, Converter, Setting >::supremum(), hypro::Converter< Number >::toZonotope(), and hypro::ZonotopeT< Number, Converter, Setting >::vector().
template<typename Number , typename Converter , typename Setting > bool hypro::ZonotopeT< Number, Converter, Setting >::empty () const
Returns, whether the zonotopeT is empty.
Returns
Definition at line 146 of file Zonotope.tpp.
References hypro::EMPTY, hypro::GeometricObjectBase::mEmptyState, hypro::NONEMPTY, hypro::UNIVERSAL, and hypro::UNKNOWN.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::intersect(), hypro::ZonotopeT< Number, Converter, Setting >::intersectHalfspace(), hypro::ZonotopeT< Number, Converter, Setting >::intersectHalfspaces(), hypro::ZonotopeT< Number, Converter, Setting >::satisfiesHalfspace(), hypro::ZonotopeT< Number, Converter, Setting >::satisfiesHalfspaces(), and hypro::ZonotopeT< Number, Converter, Setting >::vector().
template<typename Number, typename Converter, typename Setting> static ZonotopeT hypro::ZonotopeT< Number, Converter, Setting >::Empty (std::size_t dimension = 1) inline static
Definition at line 119 of file Zonotope.h.
References hypro::EMPTY, and hypro::ZonotopeT< Number, Converter, Setting >::ZonotopeT().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::project().
template<typename Number , typename Converter , typename Setting > EvaluationResult< Number > hypro::ZonotopeT< Number, Converter, Setting >::evaluate (const vector_t< Number > & directions) const
Definition at line 358 of file Zonotope.tpp.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::removeRedundancy().
template<typename Number , typename Converter , typename Setting > const matrix_t< Number > & hypro::ZonotopeT< Number, Converter, Setting >::generators () const
Definition at line 160 of file Zonotope.tpp.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::addGenerators(), hypro::ZonotopeT< Number, Converter, Setting >::computeZonotopeBoundary(), hypro::ZonotopeT< Number, Converter, Setting >::intersect(), hypro::intersect2d(), hypro::intersectAlamo(), hypro::intersectNDProjection(), hypro::ZonotopeT< Number, Converter, Setting >::intervalHull(), hypro::ZonotopeT< Number, Converter, Setting >::minkowskiSum(), hypro::ZonotopeT< Number, Converter, Setting >::operator==(), hypro::ZonotopeT< Number, Converter, Setting >::reduceOrder(), hypro::ZonotopeT< Number, Converter, Setting >::type(), and hypro::ZonotopeT< Number, Converter, Setting >::ZonotopeT().
template<typename Number , typename Converter , typename Setting > ZonotopeT< Number, Converter, Setting > hypro::ZonotopeT< Number, Converter, Setting >::intersect (const Parma_Polyhedra_Library::Constraint & halfspace) const
Calculates zonotopeT intersect with halfspace represented as PPL constraint
Parameters
result : The resulting stateset of the intersection
halfspace : Halfspace as represented in PPL (see PPL documentation for more information)
Returns
true if intersect is found, false otherwise (result parameter is not modified if false)
Definition at line 891 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::intersectHalfspace().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::assignIntervals(), and hypro::ZonotopeT< Number, Converter, Setting >::intersect().
template<typename Number , typename Converter , typename Setting > ZonotopeT< Number, Converter, Setting > hypro::ZonotopeT< Number, Converter, Setting >::intersect (const Halfspace< Number > & rhs, int method)
Intersects the given stateset with a second one.
Parameters
result The resulting stateset of the intersection.
rhs The right-hand-side stateset. Is not modified.
Returns
True if intersect is found
Definition at line 842 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::intersect().
template<typename Number, typename Converter, typename Setting> ZonotopeT<Number, Converter, Setting> hypro::ZonotopeT< Number, Converter, Setting >::intersect (const ZonotopeT< Number, Converter, Setting > &) const inline
Definition at line 258 of file Zonotope.h.
References hypro::ZonotopeT< Number, Converter, Setting >::intersect(), hypro::ZonotopeT< Number, Converter, Setting >::intersectHalfspaces(), and hypro::ZonotopeT< Number, Converter, Setting >::unite().
template<typename Number , typename Converter , typename Setting > ZonotopeT< Number, Converter, Setting > hypro::ZonotopeT< Number, Converter, Setting >::intersect (const Halfspace< Number > & rhs, matrix_t< Number > & minMaxOfLine, int method)
Intersects the given stateset with a second one and returns min-max only when NDPROJECTION method is used
Parameters
result : The resulting stateset of the intersection as zonotopeT.
minMaxOfLine : The resulting min-max matrix.
rhs : The right-hand-side stateset. Is not modified.
Returns
True if intersect is found.
Definition at line 848 of file Zonotope.tpp.
References hypro::ZUtility::ALAMO, hypro::Halfspace< Number >::dimension(), hypro::intersectAlamo(), hypro::ZUtility::NDPROJECTION, hypro::Halfspace< Number >::normal(), and hypro::Halfspace< Number >::offset().
template<typename Number , typename Converter , typename Setting > ZonotopeT< Number, Converter, Setting > hypro::ZonotopeT< Number, Converter, Setting >::intersect (const Parma_Polyhedra_Library::C_Polyhedron & rhs) const
Calculates zonotopeT intersect with a closed polyhedron as represented in PPL.
Parameters
result : The resulting stateset of the intersection as zonotopeT.
rhs : The closed polyhedron as represented in PPL (see PPL documentation for more information).
Returns
true if intersect is found, false otherwise (result parameter is not modified if false)
Definition at line 1099 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::addGenerators(), hypro::ZonotopeT< Number, Converter, Setting >::empty(), hypro::ZonotopeT< Number, Converter, Setting >::generators(), hypro::ZonotopeT< Number, Converter, Setting >::intersect(), hypro::ZonotopeT< Number, Converter, Setting >::setCenter(), hypro::ZonotopeT< Number, Converter, Setting >::setGenerators(), hypro::ZonotopeT< Number, Converter, Setting >::size(), and hypro::ZonotopeT< Number, Converter, Setting >::unite().
template<typename Number , typename Converter , typename Setting > ZonotopeT< Number, Converter, Setting > hypro::ZonotopeT< Number, Converter, Setting >::intersectHalfspace (const Halfspace< Number > & rhs) const
Definition at line 907 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::addGenerators(), hypro::ZonotopeT< Number, Converter, Setting >::empty(), hypro::Halfspace< Number >::normal(), hypro::Halfspace< Number >::offset(), hypro::ZonotopeT< Number, Converter, Setting >::reduceOrder(), hypro::ZonotopeT< Number, Converter, Setting >::setCenter(), and hypro::ZonotopeT< Number, Converter, Setting >::setGenerators().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::assignIntervals(), and hypro::ZonotopeT< Number, Converter, Setting >::intersect().
template<typename Number , typename Converter , typename Setting > ZonotopeT< Number, Converter, Setting > hypro::ZonotopeT< Number, Converter, Setting >::intersectHalfspaces (const matrix_t< Number > & mat, const vector_t< Number > & vec) const
Definition at line 951 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::empty(), and hypro::ZUtility::NDPROJECTION.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::assignIntervals(), and hypro::ZonotopeT< Number, Converter, Setting >::intersect().
template<typename Number, typename Converter, typename Setting> ZonotopeT hypro::ZonotopeT< Number, Converter, Setting >::intersectHalfspaces (const matrix_t< Number > & mat, const vector_t< Number > vec, int method)
Intersects the given stateset with a second one.
Parameters
result The resulting stateset of the intersection.
rhs The right-hand-side stateset. Is not modified.
Returns
True if intersect is found
template<typename Number , typename Converter , typename Setting > ZonotopeT< Number, Converter, Setting > hypro::ZonotopeT< Number, Converter, Setting >::intervalHull () const
Computes the interval hull of the member zonotopeT
Parameters
result the resulting interval hull (also a zonotopeT)
Returns
true for all cases
Definition at line 1225 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::center(), hypro::ZonotopeT< Number, Converter, Setting >::generators(), hypro::ZonotopeT< Number, Converter, Setting >::setCenter(), and hypro::ZonotopeT< Number, Converter, Setting >::setGenerators().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::reduceOrder(), and hypro::ZonotopeT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , typename Setting > ZonotopeT< Number, Converter, Setting > hypro::ZonotopeT< Number, Converter, Setting >::linearTransformation (const matrix_t< Number > & A) const
Definition at line 412 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::setCenter().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::assignIntervals().
template<typename Number, typename Converter, typename Setting> matrix_t<Number> hypro::ZonotopeT< Number, Converter, Setting >::matrix () const inline
Definition at line 95 of file Zonotope.h.
template<typename Number, typename Converter, typename Setting> ZonotopeT< Number, Converter, Setting > hypro::ZonotopeT< Number, Converter, Setting >::minkowskiSum (const ZonotopeT< Number, Converter, Setting > & rhs) const
Definition at line 376 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::dimension(), hypro::ZonotopeT< Number, Converter, Setting >::generators(), hypro::ZonotopeT< Number, Converter, Setting >::setCenter(), and hypro::ZonotopeT< Number, Converter, Setting >::size().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::removeRedundancy().
template<typename Number , typename Converter , typename Setting > std::vector< EvaluationResult< Number > > hypro::ZonotopeT< Number, Converter, Setting >::multiEvaluate (const matrix_t< Number > & directions, bool useExact = true) const
Definition at line 364 of file Zonotope.tpp.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::removeRedundancy().
template<typename Number, typename Converter, typename Setting> bool hypro::ZonotopeT< Number, Converter, Setting >::operator== (const ZonotopeT< Number, Converter, Setting > & rhs) const inline
Definition at line 181 of file Zonotope.h.
References hypro::ZonotopeT< Number, Converter, Setting >::center(), hypro::ZonotopeT< Number, Converter, Setting >::dimension(), and hypro::ZonotopeT< Number, Converter, Setting >::generators().
template<typename Number , typename Converter , typename Setting > Number hypro::ZonotopeT< Number, Converter, Setting >::order () const
Definition at line 165 of file Zonotope.tpp.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::reduceOrder(), and hypro::ZonotopeT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > void hypro::ZonotopeT< Number, Converter, Setting >::print () const
Definition at line 1271 of file Zonotope.tpp.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > ZonotopeT< Number, Converter, Setting > hypro::ZonotopeT< Number, Converter, Setting >::project (const std::vector< std::size_t > & dimensions) const
Definition at line 391 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::dimension(), hypro::ZonotopeT< Number, Converter, Setting >::Empty(), hypro::project(), and hypro::ZonotopeT< Number, Converter, Setting >::reduceOrder().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::removeRedundancy().
template<typename Number , typename Converter , typename Setting > void hypro::ZonotopeT< Number, Converter, Setting >::reduceNumberRepresentation ()
Definition at line 344 of file Zonotope.tpp.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::reduceRepresentation(), and hypro::ZonotopeT< Number, Converter, Setting >::removeRedundancy().
template<typename Number , typename Converter , typename Setting > void hypro::ZonotopeT< Number, Converter, Setting >::reduceOrder (unsigned limit = Setting::ZONOTOPE_ORDERLIMIT)
Definition at line 300 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::generators(), hypro::ZonotopeT< Number, Converter, Setting >::intervalHull(), and hypro::ZonotopeT< Number, Converter, Setting >::order().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::intersectHalfspace(), hypro::ZonotopeT< Number, Converter, Setting >::project(), hypro::ZonotopeT< Number, Converter, Setting >::reduceRepresentation(), hypro::ZonotopeT< Number, Converter, Setting >::removeRedundancy(), and hypro::ZonotopeT< Number, Converter, Setting >::satisfiesHalfspace().
template<typename Number, typename Converter, typename Setting> void hypro::ZonotopeT< Number, Converter, Setting >::reduceRepresentation () inline
Reduces the zonotope by reducing order, number representation and removing redundant generators.
Definition at line 297 of file Zonotope.h.
References hypro::ZonotopeT< Number, Converter, Setting >::contains(), hypro::ZonotopeT< Number, Converter, Setting >::intervalHull(), hypro::ZonotopeT< Number, Converter, Setting >::reduceNumberRepresentation(), hypro::ZonotopeT< Number, Converter, Setting >::reduceOrder(), and hypro::ZonotopeT< Number, Converter, Setting >::removeRedundancy().
template<typename Number , typename Converter , typename Setting > void hypro::ZonotopeT< Number, Converter, Setting >::removeEmptyGenerators ()
Removes empty (null) columns in generator matrix
Definition at line 235 of file Zonotope.tpp.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::addGenerators(), hypro::ZonotopeT< Number, Converter, Setting >::computeZonotopeBoundary(), hypro::ZonotopeT< Number, Converter, Setting >::setCenter(), hypro::ZonotopeT< Number, Converter, Setting >::setGenerators(), hypro::ZonotopeT< Number, Converter, Setting >::type(), and hypro::ZonotopeT< Number, Converter, Setting >::ZonotopeT().
template<typename Number, typename Converter, typename Setting> void hypro::ZonotopeT< Number, Converter, Setting >::removeRedundancy () const inline
Definition at line 194 of file Zonotope.h.
References hypro::ZonotopeT< Number, Converter, Setting >::evaluate(), hypro::ZonotopeT< Number, Converter, Setting >::minkowskiSum(), hypro::ZonotopeT< Number, Converter, Setting >::multiEvaluate(), hypro::ZonotopeT< Number, Converter, Setting >::project(), hypro::ZonotopeT< Number, Converter, Setting >::reduceNumberRepresentation(), and hypro::ZonotopeT< Number, Converter, Setting >::reduceOrder().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::reduceRepresentation().
template<typename Number , typename Converter , typename Setting > std::pair< CONTAINMENT, ZonotopeT< Number, Converter, Setting > > hypro::ZonotopeT< Number, Converter, Setting >::satisfiesHalfspace (const Halfspace< Number > & rhs) const
Definition at line 995 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::addGenerators(), hypro::ZonotopeT< Number, Converter, Setting >::empty(), hypro::FULL, hypro::NO, hypro::Halfspace< Number >::normal(), hypro::Halfspace< Number >::offset(), hypro::PARTIAL, hypro::ZonotopeT< Number, Converter, Setting >::reduceOrder(), hypro::ZonotopeT< Number, Converter, Setting >::setCenter(), and hypro::ZonotopeT< Number, Converter, Setting >::setGenerators().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , typename Setting > std::pair< CONTAINMENT, ZonotopeT< Number, Converter, Setting > > hypro::ZonotopeT< Number, Converter, Setting >::satisfiesHalfspaces (const matrix_t< Number > & mat, const vector_t< Number > & vec) const
Definition at line 1047 of file Zonotope.tpp.
References hypro::Halfspace< Number >::contains(), hypro::ZonotopeT< Number, Converter, Setting >::empty(), hypro::FULL, hypro::NO, and hypro::PARTIAL.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::assignIntervals().
template<typename Number , typename Converter , typename Setting > void hypro::ZonotopeT< Number, Converter, Setting >::setCenter (const vector_t< Number > & center)
Replaces the current center with the parameter center
Parameters
center a nx1 matrix
Definition at line 174 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::center(), hypro::ZonotopeT< Number, Converter, Setting >::removeEmptyGenerators(), and hypro::ZonotopeT< Number, Converter, Setting >::uniteEqualVectors().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::affineTransformation(), hypro::ZonotopeT< Number, Converter, Setting >::intersect(), hypro::intersectAlamo(), hypro::ZonotopeT< Number, Converter, Setting >::intersectHalfspace(), hypro::ZonotopeT< Number, Converter, Setting >::intervalHull(), hypro::ZonotopeT< Number, Converter, Setting >::linearTransformation(), hypro::ZonotopeT< Number, Converter, Setting >::minkowskiSum(), hypro::ZonotopeT< Number, Converter, Setting >::satisfiesHalfspace(), and hypro::ZonotopeT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > void hypro::ZonotopeT< Number, Converter, Setting >::setGenerators (const matrix_t< Number > & generators_)
Replaces the current matrix of generators with the parameter generators
Parameters
new_generators a nxm matrix
Definition at line 186 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::removeEmptyGenerators(), and hypro::ZonotopeT< Number, Converter, Setting >::uniteEqualVectors().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::addGenerators(), hypro::ZonotopeT< Number, Converter, Setting >::intersect(), hypro::ZonotopeT< Number, Converter, Setting >::intersectHalfspace(), hypro::ZonotopeT< Number, Converter, Setting >::intervalHull(), hypro::ZonotopeT< Number, Converter, Setting >::satisfiesHalfspace(), and hypro::ZonotopeT< Number, Converter, Setting >::type().
template<typename Number , typename Converter , typename Setting > std::size_t hypro::ZonotopeT< Number, Converter, Setting >::size () const
Number of generators
Returns
number of generators
Definition at line 217 of file Zonotope.tpp.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::intersect(), hypro::intersect2d(), hypro::ZonotopeT< Number, Converter, Setting >::minkowskiSum(), hypro::ZonotopeT< Number, Converter, Setting >::type(), and hypro::ZonotopeT< Number, Converter, Setting >::ZonotopeT().
template<typename Number , typename Converter , typename Setting > Number hypro::ZonotopeT< Number, Converter, Setting >::supremum () const
Definition at line 132 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::dimension().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::vector().
template<typename Number, typename Converter, typename Setting> static representation_name hypro::ZonotopeT< Number, Converter, Setting >::type () inline static
Definition at line 125 of file Zonotope.h.
References hypro::ZonotopeT< Number, Converter, Setting >::addGenerators(), hypro::ZonotopeT< Number, Converter, Setting >::center(), hypro::ZonotopeT< Number, Converter, Setting >::changeDimension(), hypro::ZonotopeT< Number, Converter, Setting >::clear(), hypro::ZonotopeT< Number, Converter, Setting >::generators(), hypro::ZonotopeT< Number, Converter, Setting >::order(), hypro::ZonotopeT< Number, Converter, Setting >::print(), hypro::ZonotopeT< Number, Converter, Setting >::removeEmptyGenerators(), hypro::ZonotopeT< Number, Converter, Setting >::setCenter(), hypro::ZonotopeT< Number, Converter, Setting >::setGenerators(), hypro::ZonotopeT< Number, Converter, Setting >::size(), and hypro::ZonotopeT< Number, Converter, Setting >::uniteEqualVectors().
template<typename Number, typename Converter, typename Setting> ZonotopeT hypro::ZonotopeT< Number, Converter, Setting >::unite (const ZonotopeT< Number, Converter, Setting > & other) const
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::intersect().
template<typename Number, typename Converter, typename Setting> static ZonotopeT hypro::ZonotopeT< Number, Converter, Setting >::unite (const std::vector< ZonotopeT< Number, Converter, Setting > > & sets) static
template<typename Number , typename Converter , typename Setting > void hypro::ZonotopeT< Number, Converter, Setting >::uniteEqualVectors ()
Definition at line 252 of file Zonotope.tpp.
References hypro::linearDependent().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::addGenerators(), hypro::ZonotopeT< Number, Converter, Setting >::setCenter(), hypro::ZonotopeT< Number, Converter, Setting >::setGenerators(), hypro::ZonotopeT< Number, Converter, Setting >::type(), and hypro::ZonotopeT< Number, Converter, Setting >::ZonotopeT().
template<typename Number, typename Converter, typename Setting> vector_t<Number> hypro::ZonotopeT< Number, Converter, Setting >::vector () const inline
Definition at line 100 of file Zonotope.h.
References hypro::ZonotopeT< Number, Converter, Setting >::dimension(), hypro::ZonotopeT< Number, Converter, Setting >::empty(), and hypro::ZonotopeT< Number, Converter, Setting >::supremum().
template<typename Number , typename Converter , typename Setting > std::vector< Point< Number > > hypro::ZonotopeT< Number, Converter, Setting >::vertices (const matrix_t< Number > & = matrix_t<Number>::Zero(0, 0)) const
Compute a set of points containing the extreme points of a zonotopeT.
Compute all possible extreme points of a zonotopeT by considering all combinations of generators. This gives a set of points, which contains also the real extreme points but also some internal points.
Returns
vector of points.
Definition at line 487 of file Zonotope.tpp.
References hypro::ZUtility::getCornersRecursive().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::assignIntervals(), and hypro::intersectZonotopeHalfspaceDSearch().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/Zonotope/Zonotope.h
/home/travis/build/hypro/hypro/src/hypro/representations/Zonotope/Zonotope.tpp