HyPro: ClassHandle< T > Class Template Reference
ClassHandle< T > Class Template Reference
#include <ClassHandle.h>
Public Member Functions
ClassHandle (T *ptr)
~ClassHandle ()
bool isValid ()
T * ptr ()
Private Attributes
uint32_t signature_m
const std::string name_m
T *const ptr_m
Detailed Description
template<class T>
class ClassHandle< T >
Definition at line 16 of file ClassHandle.h.
Constructor & Destructor Documentation
template<class T> ClassHandle< T >::ClassHandle (T * ptr) inline
Definition at line 18 of file ClassHandle.h.
template<class T> ClassHandle< T >::~ClassHandle () inline
Definition at line 19 of file ClassHandle.h.
References ClassHandle< T >::ptr_m, and ClassHandle< T >::signature_m.
Member Function Documentation
template<class T> bool ClassHandle< T >::isValid () inline
Definition at line 20 of file ClassHandle.h.
References name, ClassHandle< T >::name_m, and ClassHandle< T >::signature_m.
Referenced by convertMat2HandlePtr().
template<class T> T* ClassHandle< T >::ptr () inline
Definition at line 21 of file ClassHandle.h.
References ClassHandle< T >::ptr_m.
Referenced by convertMat2HandlePtr(), and convertMat2Ptr().
Member Data Documentation
template<class T> const std::string ClassHandle< T >::name_m private
Definition at line 25 of file ClassHandle.h.
Referenced by ClassHandle< T >::isValid().
template<class T> T* const ClassHandle< T >::ptr_m private
Definition at line 26 of file ClassHandle.h.
Referenced by ClassHandle< T >::ptr(), and ClassHandle< T >::~ClassHandle().
template<class T> uint32_t ClassHandle< T >::signature_m private
Definition at line 24 of file ClassHandle.h.
Referenced by ClassHandle< T >::isValid(), and ClassHandle< T >::~ClassHandle().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/util/matlab/handles/ClassHandle.h