HyPro: hypro::WorkQueueT< Workable, Setting > Class Template Reference
hypro::WorkQueueT< Workable, Setting > Class Template Reference
#include <WorkQueue.h>
Public Types
using Workable_t = Workable
Public Member Functions
WorkQueueT ()=default
WorkQueueT (WorkQueueT< Workable, Setting > &&in)=delete
WorkQueueT (const WorkQueueT< Workable, Setting > &in)=delete
~WorkQueueT ()
void pushFront (const Workable &item)
void nonLockingPushFront (const Workable &item)
void enqueue (Workable &&item)
void nonLockingEnqueue (Workable &&item)
Workable dequeueFront ()
Workable nonLockingDequeueFront ()
Workable dequeueBack ()
Workable nonLockingDequeueBack ()
bool isEmpty () const
bool nonLockingIsEmpty () const
std::size_t size () const
std::size_t nonLockingSize () const
bool exists (const Workable &item)
bool nonLockingExists (const Workable &item)
std::mutex & getMutex ()
Protected Attributes
std::deque< Workable > mQueue
std::mutex mSpinlock
Private Member Functions
const std::deque< Workable > & getQueue () const
Friends
std::ostream & operator<< (std::ostream &out, const WorkQueueT &queue)
Detailed Description
template<class Workable, class Setting>
class hypro::WorkQueueT< Workable, Setting >
Class encapsulating a thread safe queue in order to be accessed by multiple workers.
Definition at line 23 of file WorkQueue.h.
Member Typedef Documentation
template<class Workable, class Setting> using hypro::WorkQueueT< Workable, Setting >::Workable_t = Workable
Definition at line 31 of file WorkQueue.h.
Constructor & Destructor Documentation
template<class Workable, class Setting> hypro::WorkQueueT< Workable, Setting >::WorkQueueT () default
template<class Workable, class Setting> hypro::WorkQueueT< Workable, Setting >::WorkQueueT (WorkQueueT< Workable, Setting > && in) delete
template<class Workable, class Setting> hypro::WorkQueueT< Workable, Setting >::WorkQueueT (const WorkQueueT< Workable, Setting > & in) delete
template<class Workable, class Setting> hypro::WorkQueueT< Workable, Setting >::~WorkQueueT () inline
Destructor
Definition at line 40 of file WorkQueue.h.
Member Function Documentation
template<class Workable, class Setting> Workable hypro::WorkQueueT< Workable, Setting >::dequeueBack ()
Referenced by hypro::WorkQueueT< TaskType >::~WorkQueueT().
template<class Workable, class Setting> Workable hypro::WorkQueueT< Workable, Setting >::dequeueFront ()
dequeues an item by removing it from the queue and returning it
Returns
the Workable
Referenced by hypro::WorkQueueT< TaskType >::~WorkQueueT().
template<class Workable, class Setting> void hypro::WorkQueueT< Workable, Setting >::enqueue (Workable && item)
enqueues an item
Parameters
item item to be enqueued
Referenced by hypro::WorkQueueT< TaskType >::~WorkQueueT().
template<class Workable, class Setting> bool hypro::WorkQueueT< Workable, Setting >::exists (const Workable & item)
Referenced by hypro::WorkQueueT< TaskType >::~WorkQueueT().
template<class Workable, class Setting> std::mutex& hypro::WorkQueueT< Workable, Setting >::getMutex () inline
Definition at line 82 of file WorkQueue.h.
template<class Workable, class Setting> const std::deque<Workable>& hypro::WorkQueueT< Workable, Setting >::getQueue () const inline private
Definition at line 92 of file WorkQueue.h.
template<class Workable, class Setting> bool hypro::WorkQueueT< Workable, Setting >::isEmpty () const
checks whether the queue is empty
Returns
true iff no Workable is left.
Referenced by hypro::WorkQueueT< TaskType >::~WorkQueueT().
template<class Workable, class Setting> Workable hypro::WorkQueueT< Workable, Setting >::nonLockingDequeueBack ()
Referenced by hypro::WorkQueueT< TaskType >::~WorkQueueT().
template<class Workable, class Setting> Workable hypro::WorkQueueT< Workable, Setting >::nonLockingDequeueFront ()
Referenced by hypro::WorkQueueT< TaskType >::~WorkQueueT().
template<class Workable, class Setting> void hypro::WorkQueueT< Workable, Setting >::nonLockingEnqueue (Workable && item)
Referenced by hypro::WorkQueueT< TaskType >::~WorkQueueT().
template<class Workable, class Setting> bool hypro::WorkQueueT< Workable, Setting >::nonLockingExists (const Workable & item)
Referenced by hypro::WorkQueueT< TaskType >::~WorkQueueT().
template<class Workable, class Setting> bool hypro::WorkQueueT< Workable, Setting >::nonLockingIsEmpty () const
Referenced by hypro::WorkQueueT< TaskType >::~WorkQueueT().
template<class Workable, class Setting> void hypro::WorkQueueT< Workable, Setting >::nonLockingPushFront (const Workable & item)
Referenced by hypro::WorkQueueT< TaskType >::~WorkQueueT().
template<class Workable, class Setting> std::size_t hypro::WorkQueueT< Workable, Setting >::nonLockingSize () const
Referenced by hypro::WorkQueueT< TaskType >::~WorkQueueT().
template<class Workable, class Setting> void hypro::WorkQueueT< Workable, Setting >::pushFront (const Workable & item)
Pushed an Workable to the front of the queue.
Parameters
item item to be pushed at the front
Referenced by hypro::WorkQueueT< TaskType >::~WorkQueueT().
template<class Workable, class Setting> std::size_t hypro::WorkQueueT< Workable, Setting >::size () const
Referenced by hypro::WorkQueueT< TaskType >::~WorkQueueT().
Friends And Related Function Documentation
template<class Workable, class Setting> std::ostream& operator<< (std::ostream & out, const WorkQueueT< Workable, Setting > & queue) friend
Definition at line 84 of file WorkQueue.h.
Member Data Documentation
template<class Workable, class Setting> std::deque<Workable> hypro::WorkQueueT< Workable, Setting >::mQueue protected
Definition at line 24 of file WorkQueue.h.
Referenced by hypro::WorkQueueT< TaskType >::getQueue().
template<class Workable, class Setting> std::mutex hypro::WorkQueueT< Workable, Setting >::mSpinlock mutable protected
Definition at line 28 of file WorkQueue.h.
Referenced by hypro::WorkQueueT< TaskType >::getMutex().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/workQueue/WorkQueue.h