HyPro: hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type > Class Template Reference
hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type > Class Template Reference
Class for orthogonal polyhedra.
Public Member Functions
OrthogonalPolyhedronT ()
OrthogonalPolyhedronT (const Vertex< Number > &_vertex)
OrthogonalPolyhedronT (const VertexContainer< Number > &vertices)
OrthogonalPolyhedronT (const std::set< Vertex< Number >> &points)
OrthogonalPolyhedronT (const std::vector< Vertex< Number >> &points)
OrthogonalPolyhedronT (const OrthogonalPolyhedronT< Number, Converter, Setting, Type > &copy)
OrthogonalPolyhedronT (const OrthogonalPolyhedronT< Number, Converter, Setting, Type > &&move)
template<class SettingRhs , carl::DisableIf< std::is_same< Setting, SettingRhs >> = carl::dummy>
OrthogonalPolyhedronT (const OrthogonalPolyhedronT< Number, Converter, SettingRhs, Type > &copy)
std::vector< carl::Variable > variables () const
std::vector< Vertex< Number > > vertices () const
BoxT< Number, Converter, Setting > boundaryBox () const
const Grid< Number > & grid () const
void addVertex (const Vertex< Number > &_vertex)
void addVertices (const std::vector< Vertex< Number >> &_vertices)
bool empty () const
std::size_t size () const
std::size_t dimension () const
Number supremum () const
bool isVertex (const Point< Number > &_point) const
bool isOnIEdge (const Point< Number > &_point, std::size_t i) const
bool isInternal (const Point< Number > &_point) const
bool isExternal (const Point< Number > &_point) const
bool color (const Point< Number > &_point) const
std::vector< Point< Number > > iNeighborhood (const Point< Number > &_point, std::size_t i) const
std::vector< Point< Number > > iNegNeighborhood (const Point< Number > &_point, std::size_t i) const
std::vector< Point< Number > > neighborhood (const Point< Number > &_point) const
std::vector< Point< Number > > iSlice (std::size_t i, Number pos) const
OrthogonalPolyhedronT iProjection (std::size_t i) const
OrthogonalPolyhedronT linearTransformation (const matrix_t< Number > &A, const vector_t< Number > &b) const
OrthogonalPolyhedronT minkowskiSum (const OrthogonalPolyhedronT &rhs) const
OrthogonalPolyhedronT intersect (const OrthogonalPolyhedronT &rhs) const
OrthogonalPolyhedronT hull () const
bool contains (const Point< Number > &point) const
bool contains (const OrthogonalPolyhedronT &_other) const
OrthogonalPolyhedronT unite (const OrthogonalPolyhedronT &rhs) const
std::vector< std::vector< Point< Number > > > preparePlot (std::size_t _xDim=0, std::size_t _yDim=1) const
OrthogonalPolyhedronT< Number, Converter, Setting, Type > & operator= (const OrthogonalPolyhedronT< Number, Converter, Setting, Type > &_in)=default
OrthogonalPolyhedronT< Number, Converter, Setting, Type > & operator= (OrthogonalPolyhedronT< Number, Converter, Setting, Type > &&)=default
Friends
template<typename SettingRhs >
bool operator== (const OrthogonalPolyhedronT< Number, Converter, Setting, Type > &op1, const OrthogonalPolyhedronT< Number, Converter, SettingRhs, Type > &op2)
template<typename SettingRhs >
bool operator!= (const OrthogonalPolyhedronT< Number, Converter, Setting, Type > &op1, const OrthogonalPolyhedronT< Number, Converter, Setting, Type > &op2)
std::ostream & operator<< (std::ostream &ostr, const OrthogonalPolyhedronT< Number, Converter, Setting, Type > &p)
Detailed Description
template<typename Number, typename Converter, class Setting, ORTHO_TYPE Type = ORTHO_TYPE::VERTEX>
class hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >
Class for orthogonal polyhedra.
Template Parameters
Number The used number type.
Converter The used converter.
Type The internal representation type.
Definition at line 42 of file OrthogonalPolyhedron.h.
Constructor & Destructor Documentation
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT ()
Definition at line 15 of file OrthogonalPolyhedron.tpp.
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT (const Vertex< Number > & _vertex)
Definition at line 22 of file OrthogonalPolyhedron.tpp.
References hypro::Vertex< Number >::color(), and hypro::Vertex< Number >::point().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT (const VertexContainer< Number > & vertices)
Definition at line 30 of file OrthogonalPolyhedron.tpp.
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT (const std::set< Vertex< Number >> & points)
Definition at line 37 of file OrthogonalPolyhedron.tpp.
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT (const std::vector< Vertex< Number >> & points)
Definition at line 44 of file OrthogonalPolyhedron.tpp.
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT (const OrthogonalPolyhedronT< Number, Converter, Setting, Type > & copy)
Definition at line 51 of file OrthogonalPolyhedron.tpp.
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT (const OrthogonalPolyhedronT< Number, Converter, Setting, Type > && move)
Definition at line 58 of file OrthogonalPolyhedron.tpp.
template<typename Number, typename Converter, class Setting, ORTHO_TYPE Type = ORTHO_TYPE::VERTEX> template<class SettingRhs , carl::DisableIf< std::is_same< Setting, SettingRhs >> = carl::dummy> hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT (const OrthogonalPolyhedronT< Number, Converter, SettingRhs, Type > & copy) inline
Definition at line 63 of file OrthogonalPolyhedron.h.
References hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::addVertex(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::addVertices(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::boundaryBox(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::color(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::contains(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::dimension(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::empty(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::grid(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::hull(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::iNegNeighborhood(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::iNeighborhood(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::intersect(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::iProjection(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::isExternal(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::isInternal(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::iSlice(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::isOnIEdge(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::isVertex(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::linearTransformation(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::minkowskiSum(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::neighborhood(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::operator=(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::preparePlot(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::size(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::supremum(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::unite(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::variables(), and hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::vertices().
Member Function Documentation
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> void hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::addVertex (const Vertex< Number > & _vertex)
Definition at line 98 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> void hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::addVertices (const std::vector< Vertex< Number >> & _vertices)
Definition at line 103 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> BoxT< Number, Converter, Setting > hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::boundaryBox () const
Returns and if necessary calculates the boundary box.
Definition at line 85 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> bool hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::color (const Point< Number > & _point) const
Definition at line 155 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::contains(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::intersect(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT(), and hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::unite().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> bool hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::contains (const Point< Number > & point) const
Definition at line 318 of file OrthogonalPolyhedron.tpp.
References hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::color(), and hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::vertices().
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number, typename Converter, class Setting, ORTHO_TYPE Type = ORTHO_TYPE::VERTEX> bool hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::contains (const OrthogonalPolyhedronT< Number, Converter, Setting, Type > & _other) const
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> std::size_t hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::dimension () const
Definition at line 118 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::hull(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::isVertex(), and hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> bool hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::empty () const
Definition at line 108 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> const Grid< Number > & hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::grid () const
Definition at line 93 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::intersect(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT(), and hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::unite().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> OrthogonalPolyhedronT< Number, Converter, Setting, Type > hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::hull () const
Definition at line 290 of file OrthogonalPolyhedron.tpp.
References hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::dimension(), hypro::VertexContainer< Number >::insert(), and hypro::Vertex< Number >::setColor().
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> std::vector< Point< Number > > hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::iNegNeighborhood (const Point< Number > & _point, std::size_t i) const
Definition at line 165 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> std::vector< Point< Number > > hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::iNeighborhood (const Point< Number > & _point, std::size_t i) const
Definition at line 160 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number, typename Converter, class Setting, ORTHO_TYPE Type = ORTHO_TYPE::VERTEX> OrthogonalPolyhedronT< Number, Converter, Setting, Type > hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::intersect (const OrthogonalPolyhedronT< Number, Converter, Setting, Type > & rhs) const
Definition at line 220 of file OrthogonalPolyhedron.tpp.
References hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::color(), hypro::Grid< Number >::colorAt(), hypro::Grid< Number >::combine(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::grid(), hypro::Grid< Number >::insert(), hypro::Grid< Number >::isVertex(), hypro::Grid< Number >::neighborhood(), and hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::vertices().
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> OrthogonalPolyhedronT< Number, Converter, Setting, Type > hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::iProjection (std::size_t i) const
Definition at line 181 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> bool hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::isExternal (const Point< Number > & _point) const
Definition at line 150 of file OrthogonalPolyhedron.tpp.
References hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::isInternal().
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> bool hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::isInternal (const Point< Number > & _point) const
Definition at line 145 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::isExternal(), and hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> std::vector< Point< Number > > hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::iSlice (std::size_t i, Number pos) const
Definition at line 175 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> bool hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::isOnIEdge (const Point< Number > & _point, std::size_t i) const
Definition at line 136 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::isVertex(), and hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> bool hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::isVertex (const Point< Number > & _point) const
Definition at line 128 of file OrthogonalPolyhedron.tpp.
References hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::dimension(), and hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::isOnIEdge().
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> OrthogonalPolyhedronT< Number, Converter, Setting, Type > hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::linearTransformation (const matrix_t< Number > & A, const vector_t< Number > & b) const
Definition at line 191 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number, typename Converter, class Setting, ORTHO_TYPE Type = ORTHO_TYPE::VERTEX> OrthogonalPolyhedronT< Number, Converter, Setting, Type > hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::minkowskiSum (const OrthogonalPolyhedronT< Number, Converter, Setting, Type > & rhs) const
Definition at line 207 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> std::vector< Point< Number > > hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::neighborhood (const Point< Number > & _point) const
Definition at line 170 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number, typename Converter, class Setting, ORTHO_TYPE Type = ORTHO_TYPE::VERTEX> OrthogonalPolyhedronT<Number, Converter, Setting, Type>& hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::operator= (const OrthogonalPolyhedronT< Number, Converter, Setting, Type > & _in) default
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number, typename Converter, class Setting, ORTHO_TYPE Type = ORTHO_TYPE::VERTEX> OrthogonalPolyhedronT<Number, Converter, Setting, Type>& hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::operator= (OrthogonalPolyhedronT< Number, Converter, Setting, Type > &&) default
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> std::vector< std::vector< Point< Number > > > hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::preparePlot (std::size_t _xDim = 0, std::size_t _yDim = 1) const
Definition at line 409 of file OrthogonalPolyhedron.tpp.
References hypro::detail::for_each(), hypro::Point< Number >::reduceToDimensions(), and hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::vertices().
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> std::size_t hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::size () const
Definition at line 113 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> Number hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::supremum () const
Definition at line 123 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number, typename Converter, class Setting, ORTHO_TYPE Type = ORTHO_TYPE::VERTEX> OrthogonalPolyhedronT< Number, Converter, Setting, Type > hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::unite (const OrthogonalPolyhedronT< Number, Converter, Setting, Type > & rhs) const
Definition at line 334 of file OrthogonalPolyhedron.tpp.
References hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::color(), hypro::Grid< Number >::colorAt(), hypro::Grid< Number >::combine(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::grid(), hypro::Grid< Number >::insert(), hypro::Grid< Number >::isVertex(), hypro::Grid< Number >::neighborhood(), and hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::vertices().
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> std::vector< carl::Variable > hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::variables () const
Returns the list of variables of this polyhedron
Definition at line 72 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT().
template<typename Number , typename Converter , class Setting , ORTHO_TYPE Type> std::vector< Vertex< Number > > hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::vertices () const
Definition at line 77 of file OrthogonalPolyhedron.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::contains(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::intersect(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::preparePlot(), and hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::unite().
Friends And Related Function Documentation
template<typename Number, typename Converter, class Setting, ORTHO_TYPE Type = ORTHO_TYPE::VERTEX> template<typename SettingRhs > bool operator!= (const OrthogonalPolyhedronT< Number, Converter, Setting, Type > & op1, const OrthogonalPolyhedronT< Number, Converter, Setting, Type > & op2) friend
Definition at line 127 of file OrthogonalPolyhedron.h.
template<typename Number, typename Converter, class Setting, ORTHO_TYPE Type = ORTHO_TYPE::VERTEX> std::ostream& operator<< (std::ostream & ostr, const OrthogonalPolyhedronT< Number, Converter, Setting, Type > & p) friend
Definition at line 132 of file OrthogonalPolyhedron.h.
template<typename Number, typename Converter, class Setting, ORTHO_TYPE Type = ORTHO_TYPE::VERTEX> template<typename SettingRhs > bool operator== (const OrthogonalPolyhedronT< Number, Converter, Setting, Type > & op1, const OrthogonalPolyhedronT< Number, Converter, SettingRhs, Type > & op2) friend
Definition at line 121 of file OrthogonalPolyhedron.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/OrthogonalPolyhedron/OrthogonalPolyhedron.h
/home/travis/build/hypro/hypro/src/hypro/representations/OrthogonalPolyhedron/OrthogonalPolyhedron.tpp