HyPro: hypro::SupportFunctionNewT< Number, Converter, Setting > Class Template Reference
hypro::SupportFunctionNewT< Number, Converter, Setting > Class Template Reference
State set representations
The class which represents a SupportFunctionNew.
#include <IntersectHalfspaceOp.h>
Public Types
typedef Setting Settings
typedef Number NumberType
Public Member Functions
SupportFunctionNewT (const Halfspace< Number > &hspace)
SupportFunctionNewT ()
Creates an empty SupportFunctionNew.
SupportFunctionNewT (const SupportFunctionNewT &orig)
Copy constructor.
SupportFunctionNewT (SupportFunctionNewT &&orig)
Move constructor.
template<typename SettingRhs , carl::DisableIf< std::is_same< Setting, SettingRhs >> = carl::dummy>
SupportFunctionNewT (const SupportFunctionNewT< Number, Converter, SettingRhs > &orig)
Settings conversion constructor.
template<typename Representation >
SupportFunctionNewT (const Representation &r)
Generic Leaf constructor.
SupportFunctionNewT (const matrix_t< Number > &mat, const vector_t< Number > &vec)
Matrix vector constructor.
SupportFunctionNewT (const std::vector< Halfspace< Number >> &hspaces)
Vector of halfspaces constructor.
~SupportFunctionNewT ()
Destructor.
Setting getSettings () const
Returns the Settings.
std::shared_ptr< RootGrowNode< Number, Converter, Setting > > & getRoot () const
Returns a shared pointer reference to the current root.
bool isTemplateSet () const
void traverse (std::function< void(RootGrowNode< Number, Converter, Setting > *)> &&transform, std::function< void(RootGrowNode< Number, Converter, Setting > *)> &&compute, std::function< void(RootGrowNode< Number, Converter, Setting > *)> &&aggregate) const
template<typename Result >
Result traverse (std::function< void(RootGrowNode< Number, Converter, Setting > *)> &&transform, std::function< Result(RootGrowNode< Number, Converter, Setting > *)> &&compute, std::function< Result(RootGrowNode< Number, Converter, Setting > *, std::vector< Result > &)> &&aggregate) const
template<typename... Rargs>
void traverse (std::function< Parameters< Rargs... >(RootGrowNode< Number, Converter, Setting > *, Parameters< Rargs... > &)> &&transform, std::function< void(RootGrowNode< Number, Converter, Setting > *, Parameters< Rargs... > &)> &&compute, std::function< void(RootGrowNode< Number, Converter, Setting > *, Parameters< Rargs... > &)> &&aggregate, Parameters< Rargs... > &&initParams) const
template<typename Result , typename... Rargs>
Result traverse (std::function< Parameters< Rargs... >(RootGrowNode< Number, Converter, Setting > *, Parameters< Rargs... > &)> &&transform, std::function< Result(RootGrowNode< Number, Converter, Setting > *, Parameters< Rargs... > &)> &&compute, std::function< Result(RootGrowNode< Number, Converter, Setting > *, std::vector< Result > &, Parameters< Rargs... > &)> &&aggregate, Parameters< Rargs... > &&initParams) const
bool empty () const
Determines if the current SupportFunctionNew is empty.
Number supremum () const
Method returning the supremum point of the SupportFunctionNew, i.e. the maximal point.
std::vector< Point< Number > > vertices (const matrix_t< Number > &=matrix_t< Number >::Zero(0, 0)) const
Getter for a vertex-representation of the current SupportFunctionNew.
EvaluationResult< Number > evaluate (const vector_t< Number > &_direction, bool useExact=true) const
Evaluation function (convex linear optimization).
std::vector< EvaluationResult< Number > > multiEvaluate (const matrix_t< Number > &_directions, bool useExact=true) const
Multi-evaluation function (convex linear optimization).
bool hasTrafo (std::shared_ptr< const LinTrafoParameters< Number, Setting >> &ltParam, const matrix_t< Number > &A, const vector_t< Number > &b) const
Answers whether the tree has at least one TrafoOp with the given parameters inside and updates ltParam if needed.
SupportFunctionNewT< Number, Converter, Setting > & operator= (const SupportFunctionNewT< Number, Converter, Setting > &rhs)=default
Assignment operator.
SupportFunctionNewT< Number, Converter, Setting > & operator= (SupportFunctionNewT< Number, Converter, Setting > &&rhs)=default
Move assignment operator.
std::size_t dimension () const
Getter for the space dimension.
matrix_t< Number > matrix () const
Getter for the constraint matrix.
vector_t< Number > vector () const
Getter for the offset vector.
void removeRedundancy ()
Removes redundancy.
std::size_t size () const
Storage size determination.
const SupportFunctionNewT< Number, Converter, Setting > & reduceNumberRepresentation ()
Function to reduce the number representation (over-approximate).
std::pair< CONTAINMENT, SupportFunctionNewT > satisfiesHalfspace (const Halfspace< Number > &rhs) const
Computes the region of the SupportFunction that is contained in the halfspace and how much is contained.
std::pair< CONTAINMENT, SupportFunctionNewT > satisfiesHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const
SupportFunctionNewT< Number, Converter, Setting > project (const std::vector< std::size_t > &dimensions) const
Computes the projection of the SupportFunction onto the given dimensions.
SupportFunctionNewT< Number, Converter, Setting > assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const
SupportFunctionNewT< Number, Converter, Setting > linearTransformation (const matrix_t< Number > &A) const
Computes a affine transformation of the SupportFunction.
SupportFunctionNewT< Number, Converter, Setting > affineTransformation (const matrix_t< Number > &A, const vector_t< Number > &b) const
SupportFunctionNewT< Number, Converter, Setting > minkowskiSum (const SupportFunctionNewT< Number, Converter, Setting > &rhs) const
Computes the minkowskiSum with one or more SupportFunctionNew.
SupportFunctionNewT< Number, Converter, Setting > minkowskiSum (const std::vector< SupportFunctionNewT< Number, Converter, Setting >> &rhs) const
SupportFunctionNewT< Number, Converter, Setting > scale (const Number &_factor=1) const
Scales the SupportFunctionNew by the given factor.
SupportFunctionNewT< Number, Converter, Setting > intersect (const SupportFunctionNewT< Number, Converter, Setting > &rhs) const
Computes the intersection of two SupportFunctionNewes.
SupportFunctionNewT< Number, Converter, Setting > intersect (const std::vector< SupportFunctionNewT< Number, Converter, Setting >> &rhs) const
SupportFunctionNewT< Number, Converter, Setting > intersectHalfspace (const Halfspace< Number > &hspace) const
Computes the intersection of a SupportFunctionNew with a Halfspace.
SupportFunctionNewT< Number, Converter, Setting > intersectHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const
bool contains (const vector_t< Number > &point) const
Containment check for a point.
bool contains (const Point< Number > &point) const
bool contains (const SupportFunctionNewT< Number, Converter, Setting > &rhs) const
Checks whether a given SupportFunction is fully contained in the current SupportFunctionNew.
bool contains (const SupportFunctionNewT< Number, Converter, Setting > &rhs, std::size_t directions) const
SupportFunctionNewT< Number, Converter, Setting > unite (const SupportFunctionNewT< Number, Converter, Setting > &rhs) const
Computes the union of two SupportFunctionNewes.
SupportFunctionNewT< Number, Converter, Setting > unite (const std::vector< SupportFunctionNewT< Number, Converter, Setting >> &rhs) const
Computes the union of the current SupportFunctionNew with a set of SupportFunctionNewes.
void reduceRepresentation ()
Reduces the representation of the current SupportFunctionNew.
void clear ()
Makes this SupportFunctionNew equal to the empty SupportFunctionNew.
std::vector< std::size_t > collectProjections () const
Traverses the tree and computes dimensions remaining after all projection operations considered.
void evaluateTemplate (std::size_t directionCount=defaultTemplateDirectionCount, bool force=false) const
Get the matrix vector representation of the current SupportFunctionNew.
Static Public Member Functions
static SupportFunctionNewT< Number, Converter, Setting > Empty ()
Static method for the construction of an empty SupportFunctionNew of required dimension.
static representation_name type ()
Getter for the class name.
Static Public Attributes
static constexpr auto type_enum = representation_name::SFN
Protected Attributes
std::shared_ptr< RootGrowNode< Number, Converter, Setting > > mRoot = nullptr
matrix_t< Number > mMatrix
vector_t< Number > mVector
bool mTemplateSet = false
Private Member Functions
SupportFunctionNewT (const std::shared_ptr< RootGrowNode< Number, Converter, Setting >> &root)
void addOperation (RootGrowNode< Number, Converter, Setting > *newRoot) const
Connects a given node with the current root. mRoot stays the same.
void addOperation (RootGrowNode< Number, Converter, Setting > *newRoot, const std::vector< SupportFunctionNewT< Number, Converter, Setting >> &rhs) const
Private Member Functions inherited from hypro::GeometricObjectBase
GeometricObjectBase ()=default
GeometricObjectBase (const GeometricObjectBase &in)=default
GeometricObjectBase (GeometricObjectBase &&in)=default
GeometricObjectBase & operator= (const GeometricObjectBase &in)=default
GeometricObjectBase & operator= (GeometricObjectBase &&in)=default
GeometricObjectBase (SETSTATE state)
SETSTATE getEmptyState () const
Determines, whether the set is empty.
void setEmptyState (SETSTATE state)
Set the Empty State member - only to be used if you know what you are doing.
Friends
class SumOp< Number, Converter, Setting >
class TrafoOp< Number, Converter, Setting >
class ScaleOp< Number, Converter, Setting >
class ProjectOp< Number, Converter, Setting >
class IntersectOp< Number, Converter, Setting >
class UnionOp< Number, Converter, Setting >
class IntersectHalfspaceOp< Number, Converter, Setting >
template<class SettingRhs >
bool operator== (const SupportFunctionNewT< Number, Converter, Setting > &b1, const SupportFunctionNewT< Number, Converter, SettingRhs > &b2)
Checks if two SupportFunctionNews are equal.
bool operator!= (const SupportFunctionNewT< Number, Converter, Setting > &b1, const SupportFunctionNewT< Number, Converter, Setting > &b2)
Determines inequality of two SupportFunctionNewes.
std::ostream & operator<< (std::ostream &ostr, const SupportFunctionNewT< Number, Converter, Setting > &b)
Outstream operator.
Additional Inherited Members
Private Attributes inherited from hypro::GeometricObjectBase
SETSTATE mEmptyState = SETSTATE::UNKNOWN
Detailed Description
template<typename Number, typename Converter, class Setting>
class hypro::SupportFunctionNewT< Number, Converter, Setting >
The class which represents a SupportFunctionNew.
Template Parameters
Number The used number type.
Converter The used converter.
Settings The used settings. @{
Definition at line 20 of file IntersectHalfspaceOp.h.
Member Typedef Documentation
template<typename Number, typename Converter, class Setting> typedef Number hypro::SupportFunctionNewT< Number, Converter, Setting >::NumberType
Definition at line 97 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> typedef Setting hypro::SupportFunctionNewT< Number, Converter, Setting >::Settings
Definition at line 96 of file SupportFunctionNew.h.
Constructor & Destructor Documentation
template<typename Number, typename Converter, class Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::SupportFunctionNewT (const std::shared_ptr< RootGrowNode< Number, Converter, Setting >> & root) private
template<typename Number, typename Converter, class Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::SupportFunctionNewT (const Halfspace< Number > & hspace)
template<typename Number, typename Converter, class Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::SupportFunctionNewT ()
Creates an empty SupportFunctionNew.
template<typename Number, typename Converter, class Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::SupportFunctionNewT (const SupportFunctionNewT< Number, Converter, Setting > & orig)
Copy constructor.
Parameters
[in] orig The original.
template<typename Number, typename Converter, class Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::SupportFunctionNewT (SupportFunctionNewT< Number, Converter, Setting > && orig)
Move constructor.
Parameters
[in] orig The original.
template<typename Number, typename Converter, class Setting> template<typename SettingRhs , carl::DisableIf< std::is_same< Setting, SettingRhs >> = carl::dummy> hypro::SupportFunctionNewT< Number, Converter, Setting >::SupportFunctionNewT (const SupportFunctionNewT< Number, Converter, SettingRhs > & orig)
Settings conversion constructor.
Parameters
[in] orig The original.
template<typename Number, typename Converter, class Setting> template<typename Representation > hypro::SupportFunctionNewT< Number, Converter, Setting >::SupportFunctionNewT (const Representation & r)
Generic Leaf constructor.
Parameters
[in] r A pointer to a GeometricObject, i.e. Boxes, HPolytopes, etc.
template<typename Number, typename Converter, class Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::SupportFunctionNewT (const matrix_t< Number > & mat, const vector_t< Number > & vec)
Matrix vector constructor.
Parameters
[in] mat The given matrix
[in] vec The given vector
template<typename Number, typename Converter, class Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::SupportFunctionNewT (const std::vector< Halfspace< Number >> & hspaces)
Vector of halfspaces constructor.
Parameters
[in] hspaces The vector of halfspaces
template<typename Number, typename Converter, class Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::~SupportFunctionNewT () inline
Destructor.
Definition at line 174 of file SupportFunctionNew.h.
Member Function Documentation
template<typename Number, typename Converter, class Setting> void hypro::SupportFunctionNewT< Number, Converter, Setting >::addOperation (RootGrowNode< Number, Converter, Setting > * newRoot) const private
Connects a given node with the current root. mRoot stays the same.
Parameters
[in] newRoot The node to connect the current root with.
[in] rhs Possible siblings of the current root that should also be connected to newRoot
Referenced by hypro::IntersectHalfspaceOp< Number, Converter, Setting >::IntersectHalfspaceOp(), hypro::IntersectOp< Number, Converter, Setting >::IntersectOp(), hypro::ProjectOp< Number, Converter, Setting >::ProjectOp(), hypro::ScaleOp< Number, Converter, Setting >::ScaleOp(), hypro::SumOp< Number, Converter, Setting >::SumOp(), hypro::TrafoOp< Number, Converter, Setting >::TrafoOp(), and hypro::UnionOp< Number, Converter, Setting >::UnionOp().
template<typename Number, typename Converter, class Setting> void hypro::SupportFunctionNewT< Number, Converter, Setting >::addOperation (RootGrowNode< Number, Converter, Setting > * newRoot, const std::vector< SupportFunctionNewT< Number, Converter, Setting >> & rhs) const private
template<typename Number, typename Converter, class Setting> SupportFunctionNewT<Number, Converter, Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::affineTransformation (const matrix_t< Number > & A, const vector_t< Number > & b) const
template<typename Number, typename Converter, class Setting> SupportFunctionNewT<Number, Converter, Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &) const inline
Definition at line 424 of file SupportFunctionNew.h.
References hypro::contains(), defaultTemplateDirectionCount, point, and vector.
template<typename Number, typename Converter, class Setting> void hypro::SupportFunctionNewT< Number, Converter, Setting >::clear () inline
Makes this SupportFunctionNew equal to the empty SupportFunctionNew.
template<typename Number, typename Converter, class Setting> std::vector<std::size_t> hypro::SupportFunctionNewT< Number, Converter, Setting >::collectProjections () const
Traverses the tree and computes dimensions remaining after all projection operations considered.
Returns
A vector containing the indices of the dimensions remaining
template<typename Number, typename Converter, class Setting> bool hypro::SupportFunctionNewT< Number, Converter, Setting >::contains (const vector_t< Number > & point) const
Containment check for a point.
Parameters
[in] point The point to check containment for.
Returns
True, if the given point is contained in the current SupportFunctionNew, false otherwise.
template<typename Number, typename Converter, class Setting> bool hypro::SupportFunctionNewT< Number, Converter, Setting >::contains (const Point< Number > & point) const
template<typename Number, typename Converter, class Setting> bool hypro::SupportFunctionNewT< Number, Converter, Setting >::contains (const SupportFunctionNewT< Number, Converter, Setting > & rhs) const
Checks whether a given SupportFunction is fully contained in the current SupportFunctionNew.
Parameters
[in] SupportFunctionNew The SupportFunctionNew.
Returns
True, if the given SupportFunctionNew is contained in the current SupportFunctionNew, false otherwise.
template<typename Number, typename Converter, class Setting> bool hypro::SupportFunctionNewT< Number, Converter, Setting >::contains (const SupportFunctionNewT< Number, Converter, Setting > & rhs, std::size_t directions) const
template<typename Number, typename Converter, class Setting> std::size_t hypro::SupportFunctionNewT< Number, Converter, Setting >::dimension () const
Getter for the space dimension.
Returns
The dimension of the space.
Referenced by hypro::IntersectOp< Number, Converter, Setting >::IntersectOp(), hypro::SumOp< Number, Converter, Setting >::SumOp(), and hypro::UnionOp< Number, Converter, Setting >::UnionOp().
template<typename Number, typename Converter, class Setting> static SupportFunctionNewT<Number, Converter, Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::Empty () inline static
Static method for the construction of an empty SupportFunctionNew of required dimension.
Parameters
dimension Required dimension.
Returns
Empty SupportFunctionNew.
Definition at line 200 of file SupportFunctionNew.h.
References A, b, empty, function, rhs, supremum, vector, and vertices.
template<typename Number, typename Converter, class Setting> bool hypro::SupportFunctionNewT< Number, Converter, Setting >::empty () const
Determines if the current SupportFunctionNew is empty.
Returns
True, if SupportFunctionNew is empty. False otherwise.
Referenced by hypro::IntersectOp< Number, Converter, Setting >::IntersectOp(), hypro::SumOp< Number, Converter, Setting >::SumOp(), and hypro::UnionOp< Number, Converter, Setting >::UnionOp().
template<typename Number, typename Converter, class Setting> EvaluationResult<Number> hypro::SupportFunctionNewT< Number, Converter, Setting >::evaluate (const vector_t< Number > & _direction, bool useExact = true) const
Evaluation function (convex linear optimization).
Parameters
[in] _direction The direction/cost function.
Returns
Maximum towards _direction.
Referenced by hypro::IntersectOp< Number, Converter, Setting >::empty(), hypro::IntersectHalfspaceOp< Number, Converter, Setting >::empty(), hypro::IntersectHalfspaceOp< Number, Converter, Setting >::leGuernic(), hypro::IntersectHalfspaceOp< Number, Converter, Setting >::leGuernicFast(), and hypro::IntersectHalfspaceOp< Number, Converter, Setting >::supremumPoint().
template<typename Number, typename Converter, class Setting> void hypro::SupportFunctionNewT< Number, Converter, Setting >::evaluateTemplate (std::size_t directionCount = defaultTemplateDirectionCount, bool force = false) const
Get the matrix vector representation of the current SupportFunctionNew.
Parameters
[in] directionCount Number of directions to be evaluated
[in] force Whether this should be done although a matrix vector representation is already cached
template<typename Number, typename Converter, class Setting> std::shared_ptr<RootGrowNode<Number, Converter, Setting> >& hypro::SupportFunctionNewT< Number, Converter, Setting >::getRoot () const inline
Returns a shared pointer reference to the current root.
Returns
A shared pointer reference to the root
Definition at line 191 of file SupportFunctionNew.h.
References hypro::qe::mRoot.
template<typename Number, typename Converter, class Setting> Setting hypro::SupportFunctionNewT< Number, Converter, Setting >::getSettings () const inline
Returns the Settings.
Returns
The current settings of the SupportFunctionNew.
Definition at line 185 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> bool hypro::SupportFunctionNewT< Number, Converter, Setting >::hasTrafo (std::shared_ptr< const LinTrafoParameters< Number, Setting >> & ltParam, const matrix_t< Number > & A, const vector_t< Number > & b) const
Answers whether the tree has at least one TrafoOp with the given parameters inside and updates ltParam if needed.
Parameters
[in] ltParam Actually used parameters which A and b are compared to
[in] A Matrix to compare to ltParam
[in] b Vector to compare to ltParam
Returns
True if at least one TrafoOp is found in the whole subtree, else false. ltParam gets updated to the parameters of the found TrafoOp if A and b are the parameters of the found TrafoOp.
Referenced by hypro::TrafoOp< Number, Converter, Setting >::TrafoOp().
template<typename Number, typename Converter, class Setting> SupportFunctionNewT<Number, Converter, Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::intersect (const SupportFunctionNewT< Number, Converter, Setting > & rhs) const
Computes the intersection of two SupportFunctionNewes.
Parameters
[in] rhs The right hand side SupportFunctionNew.
Returns
The resulting SupportFunctionNew.
template<typename Number, typename Converter, class Setting> SupportFunctionNewT<Number, Converter, Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::intersect (const std::vector< SupportFunctionNewT< Number, Converter, Setting >> & rhs) const
template<typename Number, typename Converter, class Setting> SupportFunctionNewT<Number, Converter, Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::intersectHalfspace (const Halfspace< Number > & hspace) const
Computes the intersection of a SupportFunctionNew with a Halfspace.
Parameters
[in] hspace The Halfspace to intersect with
Returns
The resulting SupportFunctionNew.
template<typename Number, typename Converter, class Setting> SupportFunctionNewT<Number, Converter, Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::intersectHalfspaces (const matrix_t< Number > & _mat, const vector_t< Number > & _vec) const
template<typename Number, typename Converter, class Setting> bool hypro::SupportFunctionNewT< Number, Converter, Setting >::isTemplateSet () const inline
Definition at line 193 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> SupportFunctionNewT<Number, Converter, Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::linearTransformation (const matrix_t< Number > & A) const
Computes a affine transformation of the SupportFunction.
Parameters
[in] A The transformation matrix
[in] b The transformation vector
Returns
The transformed SupportFunction
template<typename Number, typename Converter, class Setting> matrix_t<Number> hypro::SupportFunctionNewT< Number, Converter, Setting >::matrix () const
Getter for the constraint matrix.
Returns
The constraint matrix
template<typename Number, typename Converter, class Setting> SupportFunctionNewT<Number, Converter, Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::minkowskiSum (const SupportFunctionNewT< Number, Converter, Setting > & rhs) const
Computes the minkowskiSum with one or more SupportFunctionNew.
Parameters
[in] rhs The right had side SupportFunctionNew
Returns
The resulting minkowskiSum
template<typename Number, typename Converter, class Setting> SupportFunctionNewT<Number, Converter, Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::minkowskiSum (const std::vector< SupportFunctionNewT< Number, Converter, Setting >> & rhs) const
template<typename Number, typename Converter, class Setting> std::vector<EvaluationResult<Number> > hypro::SupportFunctionNewT< Number, Converter, Setting >::multiEvaluate (const matrix_t< Number > & _directions, bool useExact = true) const
Multi-evaluation function (convex linear optimization).
Parameters
[in] _directions The directions/cost functions.
Returns
A set of maxima towards the respective directions.
template<typename Number, typename Converter, class Setting> SupportFunctionNewT<Number, Converter, Setting>& hypro::SupportFunctionNewT< Number, Converter, Setting >::operator= (const SupportFunctionNewT< Number, Converter, Setting > & rhs) default
Assignment operator.
Parameters
rhs A SupportFunctionNew.
template<typename Number, typename Converter, class Setting> SupportFunctionNewT<Number, Converter, Setting>& hypro::SupportFunctionNewT< Number, Converter, Setting >::operator= (SupportFunctionNewT< Number, Converter, Setting > && rhs) default
Move assignment operator.
Parameters
rhs A SupportFunctionNew.
template<typename Number, typename Converter, class Setting> SupportFunctionNewT<Number, Converter, Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::project (const std::vector< std::size_t > & dimensions) const
Computes the projection of the SupportFunction onto the given dimensions.
Parameters
[in] dimensions The dimensions to project onto, all other dimensions will be ignored
Returns
The projected SupportFunction
template<typename Number, typename Converter, class Setting> const SupportFunctionNewT<Number, Converter, Setting>& hypro::SupportFunctionNewT< Number, Converter, Setting >::reduceNumberRepresentation () inline
Function to reduce the number representation (over-approximate).
Parameters
[in] limit The limit
Definition at line 407 of file SupportFunctionNew.h.
References hypro::project().
template<typename Number, typename Converter, class Setting> void hypro::SupportFunctionNewT< Number, Converter, Setting >::reduceRepresentation ()
Reduces the representation of the current SupportFunctionNew.
template<typename Number, typename Converter, class Setting> void hypro::SupportFunctionNewT< Number, Converter, Setting >::removeRedundancy () inline
Removes redundancy.
Definition at line 389 of file SupportFunctionNew.h.
References size.
template<typename Number, typename Converter, class Setting> std::pair<CONTAINMENT, SupportFunctionNewT> hypro::SupportFunctionNewT< Number, Converter, Setting >::satisfiesHalfspace (const Halfspace< Number > & rhs) const
Computes the region of the SupportFunction that is contained in the halfspace and how much is contained.
Parameters
[in] rhs The halfspace to intersect with
Returns
How much of the current SupportFunction is contained and the resulting SupportFunctionNew
template<typename Number, typename Converter, class Setting> std::pair<CONTAINMENT, SupportFunctionNewT> hypro::SupportFunctionNewT< Number, Converter, Setting >::satisfiesHalfspaces (const matrix_t< Number > & _mat, const vector_t< Number > & _vec) const
template<typename Number, typename Converter, class Setting> SupportFunctionNewT<Number, Converter, Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::scale (const Number & _factor = 1) const
Scales the SupportFunctionNew by the given factor.
Parameters
[in] factor The scaling factor
Returns
The scaled SupportFunction
template<typename Number, typename Converter, class Setting> std::size_t hypro::SupportFunctionNewT< Number, Converter, Setting >::size () const
Storage size determination.
Returns
Size of the required memory.
template<typename Number, typename Converter, class Setting> Number hypro::SupportFunctionNewT< Number, Converter, Setting >::supremum () const
Method returning the supremum point of the SupportFunctionNew, i.e. the maximal point.
Returns
A point representing the supremum of the current SupportFunctionNew.
template<typename Number, typename Converter, class Setting> void hypro::SupportFunctionNewT< Number, Converter, Setting >::traverse (std::function< void(RootGrowNode< Number, Converter, Setting > *)> && transform, std::function< void(RootGrowNode< Number, Converter, Setting > *)> && compute, std::function< void(RootGrowNode< Number, Converter, Setting > *)> && aggregate) const
template<typename Number, typename Converter, class Setting> template<typename Result > Result hypro::SupportFunctionNewT< Number, Converter, Setting >::traverse (std::function< void(RootGrowNode< Number, Converter, Setting > *)> && transform, std::function< Result(RootGrowNode< Number, Converter, Setting > *)> && compute, std::function< Result(RootGrowNode< Number, Converter, Setting > *, std::vector< Result > &)> && aggregate) const
template<typename Number, typename Converter, class Setting> template<typename... Rargs> void hypro::SupportFunctionNewT< Number, Converter, Setting >::traverse (std::function< Parameters< Rargs... >(RootGrowNode< Number, Converter, Setting > *, Parameters< Rargs... > &)> && transform, std::function< void(RootGrowNode< Number, Converter, Setting > *, Parameters< Rargs... > &)> && compute, std::function< void(RootGrowNode< Number, Converter, Setting > *, Parameters< Rargs... > &)> && aggregate, Parameters< Rargs... > && initParams) const
template<typename Number, typename Converter, class Setting> template<typename Result , typename... Rargs> Result hypro::SupportFunctionNewT< Number, Converter, Setting >::traverse (std::function< Parameters< Rargs... >(RootGrowNode< Number, Converter, Setting > *, Parameters< Rargs... > &)> && transform, std::function< Result(RootGrowNode< Number, Converter, Setting > *, Parameters< Rargs... > &)> && compute, std::function< Result(RootGrowNode< Number, Converter, Setting > *, std::vector< Result > &, Parameters< Rargs... > &)> && aggregate, Parameters< Rargs... > && initParams) const
template<typename Number, typename Converter, class Setting> static representation_name hypro::SupportFunctionNewT< Number, Converter, Setting >::type () inline static
Getter for the class name.
Returns
The value "SFN" of the representation_name enum
Definition at line 401 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> SupportFunctionNewT<Number, Converter, Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::unite (const SupportFunctionNewT< Number, Converter, Setting > & rhs) const
Computes the union of two SupportFunctionNewes.
Parameters
[in] rhs The right hand side SupportFunctionNew.
Returns
The resulting SupportFunctionNew.
template<typename Number, typename Converter, class Setting> SupportFunctionNewT<Number, Converter, Setting> hypro::SupportFunctionNewT< Number, Converter, Setting >::unite (const std::vector< SupportFunctionNewT< Number, Converter, Setting >> & rhs) const
Computes the union of the current SupportFunctionNew with a set of SupportFunctionNewes.
Parameters
[in] SupportFunctionNewes The SupportFunctionNewes.
Returns
The resulting SupportFunctionNew.
template<typename Number, typename Converter, class Setting> vector_t<Number> hypro::SupportFunctionNewT< Number, Converter, Setting >::vector () const
Getter for the offset vector.
Returns
The offset vector
template<typename Number, typename Converter, class Setting> std::vector<Point<Number> > hypro::SupportFunctionNewT< Number, Converter, Setting >::vertices (const matrix_t< Number > & = matrix_t< Number >::Zero(0, 0)) const
Getter for a vertex-representation of the current SupportFunctionNew.
Returns
A vector of points.
Friends And Related Function Documentation
template<typename Number, typename Converter, class Setting> friend class IntersectHalfspaceOp< Number, Converter, Setting > friend
Definition at line 92 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> friend class IntersectOp< Number, Converter, Setting > friend
Definition at line 90 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> bool operator!= (const SupportFunctionNewT< Number, Converter, Setting > & b1, const SupportFunctionNewT< Number, Converter, Setting > & b2) friend
Determines inequality of two SupportFunctionNewes.
Parameters
b1 A SupportFunctionNew.
b2 A SupportFunctionNew.
Returns
False, if both SupportFunctionNewes are equal.
Definition at line 340 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> std::ostream& operator<< (std::ostream & ostr, const SupportFunctionNewT< Number, Converter, Setting > & b) friend
Outstream operator.
Parameters
ostr Outstream.
b A SupportFunctionNew.
Definition at line 359 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> template<class SettingRhs > bool operator== (const SupportFunctionNewT< Number, Converter, Setting > & b1, const SupportFunctionNewT< Number, Converter, SettingRhs > & b2) friend
Checks if two SupportFunctionNews are equal.
Parameters
b1 Contains the first SupportFunctionNew.
b2 Contains the second SupportFunctionNew.
Returns
True, if they are equal.
Definition at line 330 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> friend class ProjectOp< Number, Converter, Setting > friend
Definition at line 89 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> friend class ScaleOp< Number, Converter, Setting > friend
Definition at line 88 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> friend class SumOp< Number, Converter, Setting > friend
Definition at line 86 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> friend class TrafoOp< Number, Converter, Setting > friend
Definition at line 87 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> friend class UnionOp< Number, Converter, Setting > friend
Definition at line 91 of file SupportFunctionNew.h.
Member Data Documentation
template<typename Number, typename Converter, class Setting> matrix_t<Number> hypro::SupportFunctionNewT< Number, Converter, Setting >::mMatrix mutable protected
Definition at line 109 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> std::shared_ptr<RootGrowNode<Number, Converter, Setting> > hypro::SupportFunctionNewT< Number, Converter, Setting >::mRoot = nullptr mutable protected
Definition at line 106 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> bool hypro::SupportFunctionNewT< Number, Converter, Setting >::mTemplateSet = false mutable protected
Definition at line 113 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> vector_t<Number> hypro::SupportFunctionNewT< Number, Converter, Setting >::mVector mutable protected
Definition at line 110 of file SupportFunctionNew.h.
template<typename Number, typename Converter, class Setting> constexpr auto hypro::SupportFunctionNewT< Number, Converter, Setting >::type_enum = representation_name::SFN static
Definition at line 98 of file SupportFunctionNew.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunctionNew/IntersectHalfspaceOp.h
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunctionNew/SupportFunctionNew.h