HyPro: hypro::WorkQueueManager< Workable > Class Template Reference
hypro::WorkQueueManager< Workable > Class Template Reference
#include <WorkQueueManager.h>
Public Member Functions
WorkQueue< Workable > * addQueue ()
WorkQueue< Workable > * getQueue (std::size_t index)
bool hasWorkable (bool lockedAcces) const
Workable getNextWorkable (bool lockedAccess, bool dequeueFront)
Protected Attributes
std::vector< std::unique_ptr< WorkQueue< Workable > > > mQueues
Detailed Description
template<typename Workable>
class hypro::WorkQueueManager< Workable >
Definition at line 8 of file WorkQueueManager.h.
Member Function Documentation
template<typename Workable> WorkQueue<Workable>* hypro::WorkQueueManager< Workable >::addQueue ()
Referenced by main().
template<typename Workable> Workable hypro::WorkQueueManager< Workable >::getNextWorkable (bool lockedAccess, bool dequeueFront)
Referenced by main().
template<typename Workable> WorkQueue<Workable>* hypro::WorkQueueManager< Workable >::getQueue (std::size_t index)
template<typename Workable> bool hypro::WorkQueueManager< Workable >::hasWorkable (bool lockedAcces) const
Referenced by main().
Member Data Documentation
template<typename Workable> std::vector<std::unique_ptr<WorkQueue<Workable> > > hypro::WorkQueueManager< Workable >::mQueues protected
Definition at line 9 of file WorkQueueManager.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/workQueue/WorkQueueManager.h