HyPro: hypro::HierarchicalIntervalVector< T, Number > Class Template Reference
hypro::HierarchicalIntervalVector< T, Number > Class Template Reference
Public Member Functions
HierarchicalIntervalVector ()=delete
HierarchicalIntervalVector (const std::vector< T > &order)
HierarchicalIntervalVector (const HierarchicalIntervalVector< T, Number > &in)
~HierarchicalIntervalVector ()
Destroy the Hierarchical Interval Vector object.
HierarchicalIntervalVector< T, Number > & operator= (const HierarchicalIntervalVector< T, Number > &orig)=default
HierarchicalIntervalVector< T, Number > & operator= (HierarchicalIntervalVector< T, Number > &&orig)=default
void initialize (const T &baseElement, Number endTime)
void insertInterval (const T &type, const carl::Interval< Number > &timespan)
void fill (const T &type, Number startingPoint)
void clear ()
Ivec::iterator begin ()
Ivec::const_iterator begin () const
Ivec::iterator end ()
Ivec::const_iterator end () const
const std::vector< T > & getTypeOrder () const
void setTypeOrder (const std::vector< T > &in)
bool hasEntry (const T &type) const
Determines if it has an entry of the passed type.
bool hasEntry (const carl::Interval< Number > &timeInterval) const
Determines if it has entry for the exact or a smaller time interval.
bool hasEntry (const carl::Interval< Number > &timeInterval, const T &type) const
Determines if it has entry where the type matches and the interval is a subset of some contained interval.
bool intersectsEntry (const carl::Interval< Number > &timeInterval, const T &type) const
Determines if it the interval intersects some contained interval where the type matches.
bool coversEntry (const carl::Interval< Number > &timeInterval, const T &type) const
Determines, if the passed entry is fully contained in the HIV.
std::vector< carl::Interval< Number > > getIntersectionIntervals (const carl::Interval< Number > &timeInterval, const T &type) const
std::vector< carl::Interval< Number > > getIntersectingIntervals (const carl::Interval< Number > &timeInterval, const T &type) const
void merge (const HierarchicalIntervalVector< T, Number > &rhs)
const endPoint< T, Number > & back () const
std::size_t size () const
bool empty () const
Number getTimeHorizon () const
const std::vector< endPoint< T, Number > > & getIntervals () const
Friends
std::ostream & operator<< (std::ostream &out, const HierarchicalIntervalVector< T, Number > &in)
bool operator== (const HierarchicalIntervalVector< T, Number > &lhs, const HierarchicalIntervalVector< T, Number > &rhs)
bool operator!= (const HierarchicalIntervalVector< T, Number > &lhs, const HierarchicalIntervalVector< T, Number > &rhs)
Detailed Description
template<typename T, typename Number>
class hypro::HierarchicalIntervalVector< T, Number >
Definition at line 34 of file HierarchicalIntervalVector.h.
Constructor & Destructor Documentation
template<typename T, typename Number> hypro::HierarchicalIntervalVector< T, Number >::HierarchicalIntervalVector () delete
template<typename T, typename Number> hypro::HierarchicalIntervalVector< T, Number >::HierarchicalIntervalVector (const std::vector< T > & order) inline explicit
Definition at line 43 of file HierarchicalIntervalVector.h.
template<typename T, typename Number> hypro::HierarchicalIntervalVector< T, Number >::HierarchicalIntervalVector (const HierarchicalIntervalVector< T, Number > & in) inline
Definition at line 45 of file HierarchicalIntervalVector.h.
template<typename T, typename Number> hypro::HierarchicalIntervalVector< T, Number >::~HierarchicalIntervalVector () inline
Destroy the Hierarchical Interval Vector object.
Definition at line 52 of file HierarchicalIntervalVector.h.
Member Function Documentation
template<typename T , typename Number > const endPoint< T, Number > & hypro::HierarchicalIntervalVector< T, Number >::back () const
Definition at line 300 of file HierarchicalIntervalVector.tpp.
template<typename T, typename Number> Ivec::iterator hypro::HierarchicalIntervalVector< T, Number >::begin () inline
Definition at line 64 of file HierarchicalIntervalVector.h.
Referenced by hypro::getEnabledTimings().
template<typename T, typename Number> Ivec::const_iterator hypro::HierarchicalIntervalVector< T, Number >::begin () const inline
Definition at line 65 of file HierarchicalIntervalVector.h.
template<typename T, typename Number> void hypro::HierarchicalIntervalVector< T, Number >::clear () inline
Definition at line 62 of file HierarchicalIntervalVector.h.
template<typename T, typename Number> bool hypro::HierarchicalIntervalVector< T, Number >::coversEntry (const carl::Interval< Number > & timeInterval, const T & type) const
Determines, if the passed entry is fully contained in the HIV.
Parameters
timeInterval
type
Returns
true
false
Definition at line 170 of file HierarchicalIntervalVector.tpp.
template<typename T , typename Number > bool hypro::HierarchicalIntervalVector< T, Number >::empty () const
Definition at line 313 of file HierarchicalIntervalVector.tpp.
template<typename T, typename Number> Ivec::iterator hypro::HierarchicalIntervalVector< T, Number >::end () inline
Definition at line 66 of file HierarchicalIntervalVector.h.
Referenced by hypro::getEnabledTimings().
template<typename T, typename Number> Ivec::const_iterator hypro::HierarchicalIntervalVector< T, Number >::end () const inline
Definition at line 67 of file HierarchicalIntervalVector.h.
template<typename T, typename Number> void hypro::HierarchicalIntervalVector< T, Number >::fill (const T & type, Number startingPoint)
Definition at line 70 of file HierarchicalIntervalVector.tpp.
template<typename T, typename Number> std::vector< carl::Interval< Number > > hypro::HierarchicalIntervalVector< T, Number >::getIntersectingIntervals (const carl::Interval< Number > & timeInterval, const T & type) const
Definition at line 247 of file HierarchicalIntervalVector.tpp.
template<typename T, typename Number> std::vector< carl::Interval< Number > > hypro::HierarchicalIntervalVector< T, Number >::getIntersectionIntervals (const carl::Interval< Number > & timeInterval, const T & type) const
Definition at line 203 of file HierarchicalIntervalVector.tpp.
template<typename T, typename Number> const std::vector<endPoint<T, Number> >& hypro::HierarchicalIntervalVector< T, Number >::getIntervals () const inline
Definition at line 142 of file HierarchicalIntervalVector.h.
Referenced by hypro::HierarchicalIntervalVector< T, Number >::merge().
template<typename T , typename Number > Number hypro::HierarchicalIntervalVector< T, Number >::getTimeHorizon () const
Definition at line 319 of file HierarchicalIntervalVector.tpp.
References hypro::HierarchicalIntervalVector< T, Number >::size().
template<typename T, typename Number> const std::vector<T>& hypro::HierarchicalIntervalVector< T, Number >::getTypeOrder () const inline
Definition at line 69 of file HierarchicalIntervalVector.h.
template<typename T, typename Number > bool hypro::HierarchicalIntervalVector< T, Number >::hasEntry (const T & type) const
Determines if it has an entry of the passed type.
Parameters
[in] type The type
Returns
True if has entry, False otherwise.
Definition at line 107 of file HierarchicalIntervalVector.tpp.
template<typename T, typename Number> bool hypro::HierarchicalIntervalVector< T, Number >::hasEntry (const carl::Interval< Number > & timeInterval) const
Determines if it has entry for the exact or a smaller time interval.
Parameters
[in] timeInterval The time interval.
Returns
True if has entry, False otherwise.
Definition at line 117 of file HierarchicalIntervalVector.tpp.
template<typename T, typename Number> bool hypro::HierarchicalIntervalVector< T, Number >::hasEntry (const carl::Interval< Number > & timeInterval, const T & type) const
Determines if it has entry where the type matches and the interval is a subset of some contained interval.
Parameters
[in] timeInterval The time interval.
[in] type The type.
Returns
True if has entry, False otherwise.
Definition at line 128 of file HierarchicalIntervalVector.tpp.
template<typename T, typename Number> void hypro::HierarchicalIntervalVector< T, Number >::initialize (const T & baseElement, Number endTime)
Definition at line 6 of file HierarchicalIntervalVector.tpp.
Referenced by hypro::EventTimingContainer< N >::EventTimingContainer(), and hypro::LTIContext< State >::LTIContext().
template<typename T, typename Number> void hypro::HierarchicalIntervalVector< T, Number >::insertInterval (const T & type, const carl::Interval< Number > & timespan)
Definition at line 15 of file HierarchicalIntervalVector.tpp.
template<typename T, typename Number> bool hypro::HierarchicalIntervalVector< T, Number >::intersectsEntry (const carl::Interval< Number > & timeInterval, const T & type) const
Determines if it the interval intersects some contained interval where the type matches.
Parameters
[in] timeInterval The time interval.
[in] type The type.
Returns
True if there exists a matching entry, False otherwise.
Definition at line 135 of file HierarchicalIntervalVector.tpp.
template<typename T, typename Number> void hypro::HierarchicalIntervalVector< T, Number >::merge (const HierarchicalIntervalVector< T, Number > & rhs)
Definition at line 291 of file HierarchicalIntervalVector.tpp.
References hypro::HierarchicalIntervalVector< T, Number >::getIntervals(), hypro::endPoint< T, Number >::timePoint, and hypro::endPoint< T, Number >::type.
Referenced by hypro::EventTimingContainer< Number >::merge().
template<typename T, typename Number> HierarchicalIntervalVector<T, Number>& hypro::HierarchicalIntervalVector< T, Number >::operator= (const HierarchicalIntervalVector< T, Number > & orig) default
template<typename T, typename Number> HierarchicalIntervalVector<T, Number>& hypro::HierarchicalIntervalVector< T, Number >::operator= (HierarchicalIntervalVector< T, Number > && orig) default
template<typename T, typename Number> void hypro::HierarchicalIntervalVector< T, Number >::setTypeOrder (const std::vector< T > & in) inline
Definition at line 70 of file HierarchicalIntervalVector.h.
Referenced by hypro::EventTimingProvider< Number >::getTimings().
template<typename T , typename Number > std::size_t hypro::HierarchicalIntervalVector< T, Number >::size () const
Definition at line 307 of file HierarchicalIntervalVector.tpp.
Referenced by hypro::HierarchicalIntervalVector< T, Number >::getTimeHorizon().
Friends And Related Function Documentation
template<typename T, typename Number> bool operator!= (const HierarchicalIntervalVector< T, Number > & lhs, const HierarchicalIntervalVector< T, Number > & rhs) friend
Definition at line 138 of file HierarchicalIntervalVector.h.
template<typename T, typename Number> std::ostream& operator<< (std::ostream & out, const HierarchicalIntervalVector< T, Number > & in) friend
Definition at line 127 of file HierarchicalIntervalVector.h.
template<typename T, typename Number> bool operator== (const HierarchicalIntervalVector< T, Number > & lhs, const HierarchicalIntervalVector< T, Number > & rhs) friend
Definition at line 134 of file HierarchicalIntervalVector.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/timing/HierarchicalIntervalVector.h
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/timing/HierarchicalIntervalVector.tpp