HyPro: hypro::GeometricObject< Number, DerivedShape > Class Template Reference
hypro::GeometricObject< Number, DerivedShape > Class Template Reference abstract
State set representations
Purely virtual class defining a common interface for geometric objects.
#include <GeometricObject.h>
Public Types
typedef Number NumberType
Public Member Functions
virtual ~GeometricObject ()
Destroys the object.
virtual std::size_t dimension () const =0
Returns the space dimension of the object.
virtual bool empty () const =0
Determines, whether the set is empty.
virtual std::vector< Point< Number > > vertices (const matrix_t< Number > &=matrix_t< Number >::Zero(0, 0)) const =0
Computes the set of extreme vertices, whose convex hull is the smallest convex set containing this set.
virtual std::pair< CONTAINMENT, DerivedShape > satisfiesHalfspace (const Halfspace< Number > &rhs) const =0
Method combining the intersection of the set with a halfspace and a test for emptiness of the resulting set.
virtual std::pair< CONTAINMENT, DerivedShape > satisfiesHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const =0
Method combining the intersection of the set with a set of halfspaces and a test for emptiness of the resulting set.
virtual DerivedShape project (const std::vector< std::size_t > &dimensions) const =0
Projects the set on the ordered set of given dimensions.
virtual DerivedShape assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &assignments) const =0
Function to set a variable to an interval. This is a meta-function which consists of projecting out the respective dimension, resulting in a lower-dimensional state set. Afterwards the state set is lifted to the original state space, i.e., unconstrained dimensions are added and finally, the interval constraints as given are added.
virtual DerivedShape linearTransformation (const matrix_t< Number > &A) const =0
Applies a linear transformation with the matrix A to the set.
virtual DerivedShape affineTransformation (const matrix_t< Number > &A, const vector_t< Number > &b) const =0
Applies an affine transformation with the matrix A and the translation vector b to the set.
virtual DerivedShape minkowskiSum (const DerivedShape &rhs) const =0
Computes Minkowski's sum of the current set and the passed set.
virtual DerivedShape intersectHalfspace (const Halfspace< Number > &rhs) const =0
Computes the intersection of the set with the given halfspace.
virtual DerivedShape intersectHalfspaces (const matrix_t< Number > &_mat, const vector_t< Number > &_vec) const =0
Computes the intersection of the set with a set of halfspaces.
virtual bool contains (const Point< Number > &point) const =0
Checks, whether the set contains the passed point.
virtual bool contains (const DerivedShape &rhs) const =0
virtual DerivedShape unite (const DerivedShape &rhs) const =0
Computes the convex hull of the union of the set and the passed set.
virtual void reduceRepresentation ()=0
Function called to reduce the representation - implementation is dependent on the actual representation and might affect number representations as well as reducing the complexity of the set at the cost of precision - the actual implementation should be settings-dependent.
Friends
std::ostream & operator<< (std::ostream &out, const GeometricObject< Number, DerivedShape > &in)
Outstream operator.
Detailed Description
template<typename Number, typename DerivedShape>
class hypro::GeometricObject< Number, DerivedShape >
Purely virtual class defining a common interface for geometric objects.
Template Parameters
Number The used number type. @{
Definition at line 35 of file GeometricObject.h.
Member Typedef Documentation
template<typename Number, typename DerivedShape> typedef Number hypro::GeometricObject< Number, DerivedShape >::NumberType
Definition at line 37 of file GeometricObject.h.
Constructor & Destructor Documentation
template<typename Number, typename DerivedShape> virtual hypro::GeometricObject< Number, DerivedShape >::~GeometricObject () inline virtual
Destroys the object.
Reimplemented in hypro::StatisticWrapper< Representation >.
Definition at line 42 of file GeometricObject.h.
Member Function Documentation
template<typename Number, typename DerivedShape> virtual DerivedShape hypro::GeometricObject< Number, DerivedShape >::affineTransformation (const matrix_t< Number > & A, const vector_t< Number > & b) const pure virtual
Applies an affine transformation with the matrix A and the translation vector b to the set.
The resulting set R is the result of the affine transformation of the set S with A and b such that \(R = \{ x | x \in A\cdot S + b \} \)
Parameters
[in] A The matrix.
[in] b The vector.
Returns
The resulting set.
Implemented in hypro::ZonotopeT< Number, Converter, Setting >, hypro::DifferenceBoundsT< Number, Converter, Setting >, and hypro::SupportFunctionT< Number, Converter, Setting >.
Referenced by hypro::GeometricObject< Number, ZonotopeT< Number, Converter, Setting > >::~GeometricObject().
template<typename Number, typename DerivedShape> virtual DerivedShape hypro::GeometricObject< Number, DerivedShape >::assignIntervals (const std::map< std::size_t, carl::Interval< Number >> & assignments) const pure virtual
Function to set a variable to an interval. This is a meta-function which consists of projecting out the respective dimension, resulting in a lower-dimensional state set. Afterwards the state set is lifted to the original state space, i.e., unconstrained dimensions are added and finally, the interval constraints as given are added.
Parameters
assignments A map from dimension index to interval.
Returns
DerivedShape
Implemented in hypro::ZonotopeT< Number, Converter, Setting >, hypro::DifferenceBoundsT< Number, Converter, Setting >, and hypro::SupportFunctionT< Number, Converter, Setting >.
Referenced by hypro::GeometricObject< Number, ZonotopeT< Number, Converter, Setting > >::~GeometricObject().
template<typename Number, typename DerivedShape> virtual bool hypro::GeometricObject< Number, DerivedShape >::contains (const Point< Number > & point) const pure virtual
Checks, whether the set contains the passed point.
Parameters
[in] point The point.
Returns
True, if the point lies inside the set, false otherwise.
Implemented in hypro::ZonotopeT< Number, Converter, Setting >, hypro::DifferenceBoundsT< Number, Converter, Setting >, and hypro::SupportFunctionT< Number, Converter, Setting >.
Referenced by hypro::GeometricObject< Number, ZonotopeT< Number, Converter, Setting > >::~GeometricObject().
template<typename Number, typename DerivedShape> virtual bool hypro::GeometricObject< Number, DerivedShape >::contains (const DerivedShape & rhs) const pure virtual
Implemented in hypro::ZonotopeT< Number, Converter, Setting >.
template<typename Number, typename DerivedShape> virtual std::size_t hypro::GeometricObject< Number, DerivedShape >::dimension () const pure virtual
Returns the space dimension of the object.
Returns
The dimension.
Implemented in hypro::DifferenceBoundsT< Number, Converter, Setting >, hypro::ZonotopeT< Number, Converter, Setting >, hypro::SupportFunctionT< Number, Converter, Setting >, and hypro::StatisticWrapper< Representation >.
Referenced by hypro::GeometricObject< Number, ZonotopeT< Number, Converter, Setting > >::~GeometricObject().
template<typename Number, typename DerivedShape> virtual bool hypro::GeometricObject< Number, DerivedShape >::empty () const pure virtual
Determines, whether the set is empty.
Returns
True, if the set is empty, false otherwise.
Implemented in hypro::DifferenceBoundsT< Number, Converter, Setting >, hypro::ZonotopeT< Number, Converter, Setting >, hypro::SupportFunctionT< Number, Converter, Setting >, and hypro::StatisticWrapper< Representation >.
Referenced by hypro::GeometricObject< Number, ZonotopeT< Number, Converter, Setting > >::~GeometricObject().
template<typename Number, typename DerivedShape> virtual DerivedShape hypro::GeometricObject< Number, DerivedShape >::intersectHalfspace (const Halfspace< Number > & rhs) const pure virtual
Computes the intersection of the set with the given halfspace.
Parameters
[in] rhs The halfspace.
Returns
The resulting set.
Implemented in hypro::ZonotopeT< Number, Converter, Setting >, hypro::DifferenceBoundsT< Number, Converter, Setting >, and hypro::SupportFunctionT< Number, Converter, Setting >.
Referenced by hypro::GeometricObject< Number, ZonotopeT< Number, Converter, Setting > >::~GeometricObject().
template<typename Number, typename DerivedShape> virtual DerivedShape hypro::GeometricObject< Number, DerivedShape >::intersectHalfspaces (const matrix_t< Number > & _mat, const vector_t< Number > & _vec) const pure virtual
Computes the intersection of the set with a set of halfspaces.
The halfspaces are given as a matrix A and a vector b such that the resulting intersection of the set S with the set of halfspaces is the set R = \(\{ x | x \in S \land A\cdot x \leq b \} \).
Parameters
[in] _mat The matrix.
[in] _vec The vector.
Returns
The resulting set.
Implemented in hypro::ZonotopeT< Number, Converter, Setting >, hypro::DifferenceBoundsT< Number, Converter, Setting >, and hypro::SupportFunctionT< Number, Converter, Setting >.
Referenced by hypro::GeometricObject< Number, ZonotopeT< Number, Converter, Setting > >::~GeometricObject().
template<typename Number, typename DerivedShape> virtual DerivedShape hypro::GeometricObject< Number, DerivedShape >::linearTransformation (const matrix_t< Number > & A) const pure virtual
Applies a linear transformation with the matrix A to the set.
The resulting set R is the result of the linear transformation of the set S with A such that \(R = \{ x | x \in A\cdot S \} \)
Parameters
[in] A The matrix.
Returns
The resulting set.
Implemented in hypro::ZonotopeT< Number, Converter, Setting >, hypro::DifferenceBoundsT< Number, Converter, Setting >, and hypro::SupportFunctionT< Number, Converter, Setting >.
Referenced by hypro::GeometricObject< Number, ZonotopeT< Number, Converter, Setting > >::~GeometricObject().
template<typename Number, typename DerivedShape> virtual DerivedShape hypro::GeometricObject< Number, DerivedShape >::minkowskiSum (const DerivedShape & rhs) const pure virtual
Computes Minkowski's sum of the current set and the passed set.
Parameters
[in] rhs The other passed set.
Returns
The resulting set.
Referenced by hypro::GeometricObject< Number, ZonotopeT< Number, Converter, Setting > >::~GeometricObject().
template<typename Number, typename DerivedShape> virtual DerivedShape hypro::GeometricObject< Number, DerivedShape >::project (const std::vector< std::size_t > & dimensions) const pure virtual
Projects the set on the ordered set of given dimensions.
Parameters
[in] dimensions The dimensions.
Returns
The resulting set.
Implemented in hypro::ZonotopeT< Number, Converter, Setting >, hypro::DifferenceBoundsT< Number, Converter, Setting >, hypro::SupportFunctionT< Number, Converter, Setting >, and hypro::StatisticWrapper< Representation >.
Referenced by hypro::GeometricObject< Number, ZonotopeT< Number, Converter, Setting > >::~GeometricObject().
template<typename Number, typename DerivedShape> virtual void hypro::GeometricObject< Number, DerivedShape >::reduceRepresentation () pure virtual
Function called to reduce the representation - implementation is dependent on the actual representation and might affect number representations as well as reducing the complexity of the set at the cost of precision - the actual implementation should be settings-dependent.
Implemented in hypro::ZonotopeT< Number, Converter, Setting >, hypro::DifferenceBoundsT< Number, Converter, Setting >, and hypro::SupportFunctionT< Number, Converter, Setting >.
Referenced by hypro::GeometricObject< Number, ZonotopeT< Number, Converter, Setting > >::~GeometricObject().
template<typename Number, typename DerivedShape> virtual std::pair<CONTAINMENT, DerivedShape> hypro::GeometricObject< Number, DerivedShape >::satisfiesHalfspace (const Halfspace< Number > & rhs) const pure virtual
Method combining the intersection of the set with a halfspace and a test for emptiness of the resulting set.
Parameters
[in] rhs The halfspace. Note that this check is at least as fast as performing the intersection and testing for emptiness, but in general we encourage to use this method instead.
Returns
A pair of a CONTAINMENT type stating whether the resulting set is empty and the resulting set.
Implemented in hypro::ZonotopeT< Number, Converter, Setting >, hypro::DifferenceBoundsT< Number, Converter, Setting >, and hypro::SupportFunctionT< Number, Converter, Setting >.
Referenced by hypro::GeometricObject< Number, ZonotopeT< Number, Converter, Setting > >::~GeometricObject().
template<typename Number, typename DerivedShape> virtual std::pair<CONTAINMENT, DerivedShape> hypro::GeometricObject< Number, DerivedShape >::satisfiesHalfspaces (const matrix_t< Number > & _mat, const vector_t< Number > & _vec) const pure virtual
Method combining the intersection of the set with a set of halfspaces and a test for emptiness of the resulting set.
The halfspaces are given as a matrix A and a vector b such that the resulting intersection of the set S with the set of halfspaces is the set R = \(\{ x | x \in S \land A\cdot x \leq b \} \). Note that this check is at least as fast as performing the intersection and testing for emptiness, but in general we encourage to use this method instead.
Parameters
[in] _mat The matrix.
[in] _vec The vector.
Returns
A pair of a CONTAINMENT type stating whether the resulting set is empty and the resulting set.
Implemented in hypro::ZonotopeT< Number, Converter, Setting >, hypro::DifferenceBoundsT< Number, Converter, Setting >, and hypro::SupportFunctionT< Number, Converter, Setting >.
Referenced by hypro::GeometricObject< Number, ZonotopeT< Number, Converter, Setting > >::~GeometricObject().
template<typename Number, typename DerivedShape> virtual DerivedShape hypro::GeometricObject< Number, DerivedShape >::unite (const DerivedShape & rhs) const pure virtual
Computes the convex hull of the union of the set and the passed set.
Parameters
[in] rhs The passed set.
Returns
The resulting set.
Referenced by hypro::GeometricObject< Number, ZonotopeT< Number, Converter, Setting > >::~GeometricObject().
template<typename Number, typename DerivedShape> virtual std::vector<Point<Number> > hypro::GeometricObject< Number, DerivedShape >::vertices (const matrix_t< Number > & = matrix_t< Number >::Zero(0, 0)) const pure virtual
Computes the set of extreme vertices, whose convex hull is the smallest convex set containing this set.
Returns
A set of extreme vertices.
Implemented in hypro::ZonotopeT< Number, Converter, Setting >, hypro::DifferenceBoundsT< Number, Converter, Setting >, and hypro::SupportFunctionT< Number, Converter, Setting >.
Referenced by hypro::GeometricObject< Number, ZonotopeT< Number, Converter, Setting > >::~GeometricObject().
Friends And Related Function Documentation
template<typename Number, typename DerivedShape> std::ostream& operator<< (std::ostream & out, const GeometricObject< Number, DerivedShape > & in) friend
Outstream operator.
Parameters
out The outstream.
[in] obj The object.
Returns
Reference to the passed outstream.
Definition at line 168 of file GeometricObject.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/GeometricObject.h