HyPro: hypro::VariablePool Class Reference
hypro::VariablePool Class Reference
#include <VariablePool.h>
Public Member Functions
~VariablePool ()
const carl::Variable & variable (const Parma_Polyhedra_Library::Variable &_var) const
const Parma_Polyhedra_Library::Variable & variable (const carl::Variable &_var) const
const Parma_Polyhedra_Library::Variable & pplVarByIndex (std::size_t _index)
const carl::Variable & carlVarByIndex (std::size_t _index)
const carl::Variable & newCarlVariable (std::string _name="")
std::size_t addCarlVariable (carl::Variable var)
const Parma_Polyhedra_Library::Variable & newPplVariable ()
bool hasDimension (const carl::Variable &_var) const
bool hasDimension (std::size_t i) const
std::size_t id (const Parma_Polyhedra_Library::Variable &_var) const
std::size_t id (const carl::Variable &_var)
std::vector< carl::Variable > carlVariables () const
std::vector< Parma_Polyhedra_Library::Variable > pplVariables () const
std::size_t size () const
void clear ()
void print () const
Protected Member Functions
VariablePool ()
Private Types
using carlPplMap = std::map< carl::Variable, Parma_Polyhedra_Library::Variable >
using pplCarlMap = std::map< Parma_Polyhedra_Library::Variable, carl::Variable, Parma_Polyhedra_Library::Variable::Compare >
Private Attributes
std::vector< carl::Variable > mCarlVariables
std::vector< Parma_Polyhedra_Library::Variable > mPplVariables
carlPplMap mCarlToPpl
pplCarlMap mPplToCarl
std::size_t mPplId
carl::VariablePool & mPool
Detailed Description
Definition at line 28 of file VariablePool.h.
Member Typedef Documentation
using hypro::VariablePool::carlPplMap = std::map<carl::Variable, Parma_Polyhedra_Library::Variable> private
Typedefs
Definition at line 34 of file VariablePool.h.
using hypro::VariablePool::pplCarlMap = std::map<Parma_Polyhedra_Library::Variable, carl::Variable, Parma_Polyhedra_Library::Variable::Compare> private
Definition at line 35 of file VariablePool.h.
Constructor & Destructor Documentation
hypro::VariablePool::VariablePool () inline protected
Default constructor and destructor
Definition at line 54 of file VariablePool.h.
hypro::VariablePool::~VariablePool () inline
Definition at line 59 of file VariablePool.h.
Member Function Documentation
std::size_t hypro::VariablePool::addCarlVariable (carl::Variable var) inline
Definition at line 149 of file VariablePool.h.
References assert(), and mPplId.
Referenced by id().
const carl::Variable& hypro::VariablePool::carlVarByIndex (std::size_t _index) inline
Definition at line 102 of file VariablePool.h.
References assert(), and mPplId.
Referenced by hypro::addPreSolution().
std::vector<carl::Variable> hypro::VariablePool::carlVariables () const inline
Definition at line 232 of file VariablePool.h.
References assert(), mCarlVariables, and mPplId.
void hypro::VariablePool::clear () inline
Definition at line 256 of file VariablePool.h.
References assert(), and mPplId.
bool hypro::VariablePool::hasDimension (const carl::Variable & _var) const inline
Definition at line 185 of file VariablePool.h.
References assert(), and mPplId.
bool hypro::VariablePool::hasDimension (std::size_t i) const inline
Definition at line 198 of file VariablePool.h.
References assert(), i, and mPplId.
std::size_t hypro::VariablePool::id (const Parma_Polyhedra_Library::Variable & _var) const inline
Definition at line 207 of file VariablePool.h.
References assert(), and mPplId.
std::size_t hypro::VariablePool::id (const carl::Variable & _var) inline
Definition at line 218 of file VariablePool.h.
References addCarlVariable(), assert(), and mPplId.
const carl::Variable& hypro::VariablePool::newCarlVariable (std::string _name = "") inline
Definition at line 126 of file VariablePool.h.
References assert(), and mPplId.
const Parma_Polyhedra_Library::Variable& hypro::VariablePool::newPplVariable () inline
Definition at line 168 of file VariablePool.h.
References assert(), and mPplId.
const Parma_Polyhedra_Library::Variable& hypro::VariablePool::pplVarByIndex (std::size_t _index) inline
Definition at line 85 of file VariablePool.h.
References assert(), and mPplId.
std::vector<Parma_Polyhedra_Library::Variable> hypro::VariablePool::pplVariables () const inline
Definition at line 241 of file VariablePool.h.
References assert(), mPplId, and mPplVariables.
void hypro::VariablePool::print () const inline
Definition at line 267 of file VariablePool.h.
References assert(), and mPplId.
std::size_t hypro::VariablePool::size () const inline
Definition at line 248 of file VariablePool.h.
References assert(), and mPplId.
const carl::Variable& hypro::VariablePool::variable (const Parma_Polyhedra_Library::Variable & _var) const inline
Definition at line 65 of file VariablePool.h.
References assert(), and mPplId.
const Parma_Polyhedra_Library::Variable& hypro::VariablePool::variable (const carl::Variable & _var) const inline
Definition at line 75 of file VariablePool.h.
References assert(), and mPplId.
Member Data Documentation
carlPplMap hypro::VariablePool::mCarlToPpl private
Definition at line 44 of file VariablePool.h.
std::vector<carl::Variable> hypro::VariablePool::mCarlVariables private
Members
Definition at line 41 of file VariablePool.h.
Referenced by carlVariables().
carl::VariablePool& hypro::VariablePool::mPool private
Definition at line 48 of file VariablePool.h.
std::size_t hypro::VariablePool::mPplId private
Definition at line 47 of file VariablePool.h.
Referenced by addCarlVariable(), carlVarByIndex(), carlVariables(), clear(), hasDimension(), id(), newCarlVariable(), newPplVariable(), pplVarByIndex(), pplVariables(), print(), size(), and variable().
pplCarlMap hypro::VariablePool::mPplToCarl private
Definition at line 45 of file VariablePool.h.
std::vector<Parma_Polyhedra_Library::Variable> hypro::VariablePool::mPplVariables private
Definition at line 43 of file VariablePool.h.
Referenced by pplVariables().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/util/VariablePool.h