HyPro: hypro::discreteGuardHandler< State > Class Template Reference
hypro::discreteGuardHandler< State > Class Template Reference
#include <forwardDeclarations.h>
Public Member Functions
discreteGuardHandler ()=delete
discreteGuardHandler (std::shared_ptr< State > state, size_t index, hypro::Transition< Number > *transition)
void handle ()
void reinitialize ()
const char * handlerName ()
virtual double getSortIndex () override
virtual void setSortIndex (double sortIndex) override
Public Member Functions inherited from hypro::ltiGuardHandler< State >
bool operator() (const State &stateSet)
const TransitionStatesMap & getGuardSatisfyingStateSets () const
Protected Attributes
bool mComputed = false
Protected Attributes inherited from hypro::ltiGuardHandler< State >
TransitionStatesMap mGuardSatisfyingStates
Private Types
using Number = typename State::NumberType
Additional Inherited Members
Public Types inherited from hypro::ltiGuardHandler< State >
using TransitionStatesMap = std::map< Transition< Number > *, std::vector< State >>
Detailed Description
template<typename State>
class hypro::discreteGuardHandler< State >
Definition at line 36 of file forwardDeclarations.h.
Member Typedef Documentation
template<typename State > using hypro::discreteGuardHandler< State >::Number = typename State::NumberType private
Definition at line 8 of file discreteGuardHandler.h.
Constructor & Destructor Documentation
template<typename State > hypro::discreteGuardHandler< State >::discreteGuardHandler () delete
template<typename State > hypro::discreteGuardHandler< State >::discreteGuardHandler (std::shared_ptr< State > state, size_t index, hypro::Transition< Number > * transition) inline
Definition at line 15 of file discreteGuardHandler.h.
References hypro::discreteGuardHandler< State >::handle(), and hypro::discreteGuardHandler< State >::reinitialize().
Member Function Documentation
template<typename State > virtual double hypro::discreteGuardHandler< State >::getSortIndex () inline override virtual
Definition at line 23 of file discreteGuardHandler.h.
template<typename State > void hypro::discreteGuardHandler< State >::handle ()
Referenced by hypro::discreteGuardHandler< State >::discreteGuardHandler().
template<typename State > const char* hypro::discreteGuardHandler< State >::handlerName () inline
Definition at line 22 of file discreteGuardHandler.h.
template<typename State > void hypro::discreteGuardHandler< State >::reinitialize ()
Referenced by hypro::discreteGuardHandler< State >::discreteGuardHandler().
template<typename State > virtual void hypro::discreteGuardHandler< State >::setSortIndex (double sortIndex) inline override virtual
Definition at line 24 of file discreteGuardHandler.h.
Member Data Documentation
template<typename State > bool hypro::discreteGuardHandler< State >::mComputed = false protected
Definition at line 11 of file discreteGuardHandler.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/forwardDeclarations.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/guardHandlers/discreteGuardHandler.h