HyPro: hypro::State< Number, Representation, Rargs > Class Template Reference
hypro::State< Number, Representation, Rargs > Class Template Reference
Class for state.
#include <State.h>
Public Types
template<std::size_t I>
using nth_representation = nth_element< I, Representation, Rargs... >
using repVariant = std::variant< Representation, Rargs... >
typedef Number NumberType
variant type for all possible state set representations.
Public Member Functions
State ()=default
Default constructor.
State (const State< Number, Representation, Rargs... > &orig)
Copy constructor.
State (State< Number, Representation, Rargs... > &&orig)
Move constructor.
State< Number, Representation, Rargs... > & operator= (const State< Number, Representation, Rargs... > &orig)
Copy assignment operator.
State< Number, Representation, Rargs... > & operator= (State< Number, Representation, Rargs... > &&orig)
Move assignment operator.
State (const Location< Number > *_loc)
Constructor from a location pointer.
State (const Location< Number > *_loc, const Representation &_rep, const Rargs...sets, const carl::Interval< tNumber > &_timestamp=carl::Interval< tNumber >::unboundedInterval())
Constructor.
State (const Representation &_rep, const carl::Interval< tNumber > &_timestamp=carl::Interval< tNumber >::unboundedInterval())
Construct a new State object with just the state set.
State (const Rargs...sets, const carl::Interval< tNumber > &_timestamp=carl::Interval< tNumber >::unboundedInterval())
Construct a new State object with just the state set.
const Location< Number > * getLocation () const
Gets the location.
Location< Number > * rGetLocation ()
Gets the location.
std::size_t getNumberSets () const
Gets the number of contained sets.
const std::variant< Representation, Rargs... > & getSet (std::size_t i=0) const
Gets the i-th set.
std::variant< Representation, Rargs... > & rGetSet (std::size_t i=0)
Gets a reference to the i-th set.
representation_name getSetType (std::size_t i=0) const
Gets the type of the i-th set.
const std::vector< repVariant > & getSets () const
Gets all contained sets.
const std::vector< representation_name > & getTypes () const
Gets all contained types.
const carl::Interval< tNumber > & getTimestamp () const
Gets the timestamp.
bool isEmpty () const
Returns empty-flag value.
const std::vector< TRIBOOL > & getEmptyStates () const
Returns empty-flag values.
std::vector< TRIBOOL > & rGetEmptyStates ()
Returns empty-flag values.
void setLocation (const Location< Number > *l)
Sets the location.
template<typename R >
void setSet (const R &s, std::size_t i=0)
Sets the set at position i.
void setSet (const repVariant &s, std::size_t i=0)
Sets the set at position i.
void setSetType (representation_name type, std::size_t I=0)
Sets the set type for the set at position i.
void setTimestamp (const carl::Interval< tNumber > &t)
Sets the timestamp.
void setSets (const std::vector< std::variant< Representation, Rargs... >> &sets)
Sets the sets.
void setSetsSave (const std::vector< std::variant< Representation, Rargs... >> &sets)
Sets the sets.
void setSetDirect (const repVariant &in, std::size_t I=0)
Sets the set.
template<typename To >
void setAndConvertType (std::size_t I=0)
void addTimeToClocks (tNumber t)
Adds time to clocks.
State< Number, Representation, Rargs... > unite (const State< Number, Representation, Rargs... > &in) const
Meta-function to aggregate two states.
std::pair< CONTAINMENT, State< Number, Representation, Rargs... > > satisfies (const Condition< Number > &in) const
Meta-function to verify a state against a condition.
std::pair< CONTAINMENT, State< Number, Representation, Rargs... > > satisfiesHalfspaces (const matrix_t< Number > &constraints, const vector_t< Number > &constants) const
std::pair< CONTAINMENT, State< Number, Representation, Rargs... > > partiallySatisfies (const Condition< Number > &in, std::size_t I) const
Meta-function to verify the i-th set of a state against the i-th component of a condition.
State< Number, Representation, Rargs... > intersectHalfspaces (const matrix_t< Number > &constraints, const vector_t< Number > &constants, std::size_t I=0) const
State< Number, Representation, Rargs... > applyTimeStep (const std::vector< std::pair< const matrix_t< Number > &, const vector_t< Number > & >> &matrixExponentials, tNumber timeStepSize) const
Meta-function which can be used to transform all contained sets at once with the passed parameters and adjust the timestamp as well.
State< Number, Representation, Rargs... > partiallyApplyTimeStep (const ConstraintSet< Number > &flow, tNumber timeStepSize, std::size_t I=0) const
Meta-function which applies a transformation by the passed parameters and increases the timestamp for the i-th set.
State< Number, Representation, Rargs... > computeAndApplyLinearTimeStep (const std::vector< const matrix_t< Number > & > &flows, tNumber timeStepSize) const
State< Number, Representation, Rargs... > partiallyComputeAndApplyLinearTimeStep (const matrix_t< Number > &flow, tNumber timeStepSize, std::size_t I=0) const
State< Number, Representation, Rargs... > computeAndApplyAffineTimeStep (const std::vector< const matrix_t< Number > & > &flows, tNumber timeStepSize) const
State< Number, Representation, Rargs... > partiallyComputeAndApplyAffineTimeStep (const matrix_t< Number > &flow, tNumber timeStepSize, std::size_t I=0) const
State< Number, Representation, Rargs... > applyTransformation (const std::vector< ConstraintSet< Number >> &trafos) const
Meta-function, which applies an affine transformation to each set contained.
State< Number, Representation, Rargs... > applyTransformation (const ConstraintSet< Number > &trafo, std::size_t I=0) const
State< Number, Representation, Rargs... > linearTransformation (const matrix_t< Number > &matrix) const
State< Number, Representation, Rargs... > affineTransformation (const matrix_t< Number > &matrix, const vector_t< Number > &vector) const
State< Number, Representation, Rargs... > partialIntervalAssignment (const std::vector< carl::Interval< Number >> &assignments, std::size_t I) const
State< Number, Representation, Rargs... > applyTransformation (const ConstraintSet< Number > &trafo) const
State< Number, Representation, Rargs... > partiallyApplyTransformation (const std::vector< ConstraintSet< Number >> &trafos, const std::vector< std::size_t > &sets) const
Meta-function, which applies an affine transformation to each set contained in the state and whose index is contained in the second parameter.
State< Number, Representation, Rargs... > partiallyApplyTransformation (const ConstraintSet< Number > &trafo, std::size_t I) const
Meta-function, which applies an affine transformation to the i-th set contained in the state.
State< Number, Representation, Rargs... > minkowskiSum (const State< Number, Representation, Rargs... > &rhs) const
State< Number, Representation, Rargs... > partiallyMinkowskiSum (const State< Number, Representation, Rargs... > &rhs, std::size_t I) const
bool contains (const State< Number, Representation, Rargs... > &rhs) const
Checks whether a state is fully contained in caller-state.
std::vector< Point< Number > > vertices (std::size_t I=0) const
State< Number, Representation, Rargs... > project (const std::vector< std::size_t > &dimensions, std::size_t I=0) const
State< Number, Representation, Rargs... > project (const std::pair< std::size_t, std::size_t > &dimensions, std::size_t I=0) const
State< Number, Representation, Rargs... > assignIntervals (const std::map< std::size_t, carl::Interval< Number >> &, std::size_t I=0) const
std::size_t getDimension (std::size_t I=0) const
std::size_t getDimensionOffset (std::size_t I) const
Number getSupremum (std::size_t I) const
void removeRedundancy ()
void partiallyRemoveRedundancy (std::size_t I)
void reduceRepresentation ()
void partiallyReduceRepresentation (std::size_t I)
void decompose (const Decomposition &decomposition)
Protected Attributes
const Location< Number > * mLoc = nullptr
std::vector< repVariant > mSets
Location of the state.
std::vector< representation_name > mTypes
The state sets wrapped in variant (repVariant).
carl::Interval< tNumber > mTimestamp = carl::Interval<tNumber>::unboundedInterval()
A vector holding the actual types corresponding to the state sets.
std::vector< TRIBOOL > mIsEmpty
A timestamp.
Private Member Functions
bool checkConsistency () const
A flag for each set which can be set to allow for a quick check for emptiness.
Friends
std::ostream & operator<< (std::ostream &out, const State< Number, Representation, Rargs... > &state)
Outstream operator.
bool operator== (const State< Number, Representation, Rargs... > &lhs, const State< Number, Representation, Rargs... > &rhs)
Comparison for equality operator.
bool operator!= (const State< Number, Representation, Rargs... > &lhs, const State< Number, Representation, Rargs... > &rhs)
Operator for unequal.
Detailed Description
template<typename Number, typename Representation, typename... Rargs>
class hypro::State< Number, Representation, Rargs >
Class for state.
A state can be used in the classical sense, i.e. as a combination of location and state set. Furthermore we allow to to hold more than one set, aiming at providing datastructures for decoupled systems where state sets inside one state can be handled independently.
Template Parameters
Number The used number type.
Representation The type of the primary state set.
Rargs The type of the additional state sets.
Definition at line 31 of file State.h.
Member Typedef Documentation
template<typename Number, typename Representation, typename... Rargs> template<std::size_t I> using hypro::State< Number, Representation, Rargs >::nth_representation = nth_element<I, Representation, Rargs...>
Definition at line 34 of file State.h.
template<typename Number, typename Representation, typename... Rargs> typedef Number hypro::State< Number, Representation, Rargs >::NumberType
variant type for all possible state set representations.
Definition at line 37 of file State.h.
template<typename Number, typename Representation, typename... Rargs> using hypro::State< Number, Representation, Rargs >::repVariant = std::variant<Representation, Rargs...>
Definition at line 36 of file State.h.
Constructor & Destructor Documentation
template<typename Number, typename Representation, typename... Rargs> hypro::State< Number, Representation, Rargs >::State () default
Default constructor.
template<typename Number, typename Representation, typename... Rargs> hypro::State< Number, Representation, Rargs >::State (const State< Number, Representation, Rargs... > & orig) inline
Copy constructor.
Parameters
[in] orig The original.
Definition at line 62 of file State.h.
References hypro::State< Number, Representation, Rargs >::checkConsistency().
template<typename Number, typename Representation, typename... Rargs> hypro::State< Number, Representation, Rargs >::State (State< Number, Representation, Rargs... > && orig) inline
Move constructor.
Parameters
orig The original.
Definition at line 75 of file State.h.
References hypro::State< Number, Representation, Rargs >::checkConsistency().
template<typename Number, typename Representation, typename... Rargs> hypro::State< Number, Representation, Rargs >::State (const Location< Number > * _loc) inline
Constructor from a location pointer.
Parameters
[in] _loc The location.
Definition at line 124 of file State.h.
References hypro::State< Number, Representation, Rargs >::checkConsistency().
template<typename Number, typename Representation, typename... Rargs> hypro::State< Number, Representation, Rargs >::State (const Location< Number > * _loc, const Representation & _rep, const Rargs... sets, const carl::Interval< tNumber > & _timestamp = carl::Interval<tNumber>::unboundedInterval()) inline
Constructor.
Parameters
[in] _loc The location.
[in] _rep The primary state set.
[in] sets The additional state sets.
[in] _timestamp The timestamp.
Definition at line 141 of file State.h.
References hypro::State< Number, Representation, Rargs >::checkConsistency(), and hypro::NSET.
template<typename Number, typename Representation, typename... Rargs> hypro::State< Number, Representation, Rargs >::State (const Representation & _rep, const carl::Interval< tNumber > & _timestamp = carl::Interval<tNumber>::unboundedInterval()) inline
Construct a new State object with just the state set.
Parameters
_rep The state set.
_timestamp
Definition at line 168 of file State.h.
References hypro::NSET.
template<typename Number, typename Representation, typename... Rargs> hypro::State< Number, Representation, Rargs >::State (const Rargs... sets, const carl::Interval< tNumber > & _timestamp = carl::Interval<tNumber>::unboundedInterval()) inline
Construct a new State object with just the state set.
Parameters
sets The state set.
_timestamp
Definition at line 183 of file State.h.
References hypro::State< Number, Representation, Rargs >::checkConsistency(), and hypro::NSET.
Member Function Documentation
template<typename Number, typename Representation, typename... Rargs> void hypro::State< Number, Representation, Rargs >::addTimeToClocks (tNumber t)
Adds time to clocks.
This is a meta-function which allows to change multiple sets. Currently it only affects the timestamp.
Parameters
[in] t The time.
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::affineTransformation (const matrix_t< Number > & matrix, const vector_t< Number > & vector) const
Referenced by hypro::errorBoxes(), and hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::applyTimeStep (const std::vector< std::pair< const matrix_t< Number > &, const vector_t< Number > & >> & matrixExponentials, tNumber timeStepSize) const
Meta-function which can be used to transform all contained sets at once with the passed parameters and adjust the timestamp as well.
Parameters
[in] matrixExponentials The solution to the differential equation system.
[in] timeStepSize The time step size.
Returns
A state where each set has been transformed by the passed parameters and the timestamp has been increased by timeStepSize.
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::applyTransformation (const std::vector< ConstraintSet< Number >> & trafos) const
Meta-function, which applies an affine transformation to each set contained.
Parameters
[in] trafos The trafos represented as a vector of ConstraintSet.
Returns
A state where each set has been transformed by the corresponding ConstraintSet.
Referenced by hypro::applyReset(), and hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::applyTransformation (const ConstraintSet< Number > & trafo, std::size_t I = 0) const
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::applyTransformation (const ConstraintSet< Number > & trafo) const
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::assignIntervals (const std::map< std::size_t, carl::Interval< Number >> & , std::size_t I = 0) const
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> bool hypro::State< Number, Representation, Rargs >::checkConsistency () const private
A flag for each set which can be set to allow for a quick check for emptiness.
Checks whether the type of all elements in mSets matches the type stored in mTypes.
Referenced by hypro::State< Number, Representation, Rargs >::getSetType(), hypro::State< Number, Representation, Rargs >::operator=(), hypro::State< Number, Representation, Rargs >::setSetDirect(), and hypro::State< Number, Representation, Rargs >::State().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::computeAndApplyAffineTimeStep (const std::vector< const matrix_t< Number > & > & flows, tNumber timeStepSize) const
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::computeAndApplyLinearTimeStep (const std::vector< const matrix_t< Number > & > & flows, tNumber timeStepSize) const
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> bool hypro::State< Number, Representation, Rargs >::contains (const State< Number, Representation, Rargs... > & rhs) const
Checks whether a state is fully contained in caller-state.
This calls "contains" for all stored state sets iteratively and returns "false" first time it can be detected.
Parameters
[in] rhs The right hand side state.
Returns
True, if every subset of rhs is fully contained in the respective subset of the caller-state.
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> void hypro::State< Number, Representation, Rargs >::decompose (const Decomposition & decomposition)
decomposes state set by projection
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> std::size_t hypro::State< Number, Representation, Rargs >::getDimension (std::size_t I = 0) const
Referenced by hypro::reachability::computeFirstSegment(), hypro::errorBoxes(), and hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> std::size_t hypro::State< Number, Representation, Rargs >::getDimensionOffset (std::size_t I) const
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> const std::vector<TRIBOOL>& hypro::State< Number, Representation, Rargs >::getEmptyStates () const inline
Returns empty-flag values.
Returns
Vector of tribools.
Definition at line 276 of file State.h.
References hypro::State< Number, Representation, Rargs >::mIsEmpty.
Referenced by hypro::State< Number, Representation, Rargs >::operator=().
template<typename Number, typename Representation, typename... Rargs> const Location<Number>* hypro::State< Number, Representation, Rargs >::getLocation () const inline
Gets the location.
Returns
The location.
Definition at line 203 of file State.h.
References hypro::State< Number, Representation, Rargs >::mLoc.
Referenced by hypro::reachability::computeFirstSegment(), main(), and hypro::State< Number, Representation, Rargs >::operator=().
template<typename Number, typename Representation, typename... Rargs> std::size_t hypro::State< Number, Representation, Rargs >::getNumberSets () const inline
Gets the number of contained sets.
Returns
The number of sets.
Definition at line 215 of file State.h.
References hypro::State< Number, Representation, Rargs >::getSet(), and hypro::State< Number, Representation, Rargs >::rGetSet().
Referenced by hypro::applyReset(), hypro::State< Number, Representation, Rargs >::operator=(), and hypro::ReachTreeNode< hypro::State >::ReachTreeNode().
template<typename Number, typename Representation, typename... Rargs> const std::variant<Representation, Rargs...>& hypro::State< Number, Representation, Rargs >::getSet (std::size_t i = 0) const
Gets the i-th set.
Parameters
[in] i Set index.
Returns
The set.
Referenced by hypro::reachability::bloatBox(), hypro::errorBoxes(), hypro::State< Number, Representation, Rargs >::getNumberSets(), main(), and hypro::detail::strategyConversionVisitor< State >::operator()().
template<typename Number, typename Representation, typename... Rargs> const std::vector<repVariant>& hypro::State< Number, Representation, Rargs >::getSets () const inline
Gets all contained sets.
Returns
The sets.
Definition at line 252 of file State.h.
References hypro::State< Number, Representation, Rargs >::mSets.
Referenced by hypro::State< Number, Representation, Rargs >::operator=().
template<typename Number, typename Representation, typename... Rargs> representation_name hypro::State< Number, Representation, Rargs >::getSetType (std::size_t i = 0) const inline
Gets the type of the i-th set.
Parameters
[in] i Set index.
Returns
The set type.
Definition at line 239 of file State.h.
References hypro::State< Number, Representation, Rargs >::checkConsistency(), and TRACE.
Referenced by hypro::detail::strategyConversionVisitor< State >::operator()().
template<typename Number, typename Representation, typename... Rargs> Number hypro::State< Number, Representation, Rargs >::getSupremum (std::size_t I) const
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> const carl::Interval<tNumber>& hypro::State< Number, Representation, Rargs >::getTimestamp () const inline
Gets the timestamp.
Returns
The timestamp.
Definition at line 264 of file State.h.
References hypro::State< Number, Representation, Rargs >::isEmpty(), and hypro::State< Number, Representation, Rargs >::mTimestamp.
Referenced by hypro::reachability::computeFirstSegment(), hypro::State< Number, Representation, Rargs >::operator=(), and hypro::ReachTreeNode< hypro::State >::ReachTreeNode().
template<typename Number, typename Representation, typename... Rargs> const std::vector<representation_name>& hypro::State< Number, Representation, Rargs >::getTypes () const inline
Gets all contained types.
Returns
The types.
Definition at line 258 of file State.h.
References hypro::State< Number, Representation, Rargs >::mTypes.
Referenced by hypro::State< Number, Representation, Rargs >::operator=().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::intersectHalfspaces (const matrix_t< Number > & constraints, const vector_t< Number > & constants, std::size_t I = 0) const
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> bool hypro::State< Number, Representation, Rargs >::isEmpty () const
Returns empty-flag value.
Returns
True if empty, False otherwise.
Referenced by hypro::errorBoxes(), and hypro::State< Number, Representation, Rargs >::getTimestamp().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::linearTransformation (const matrix_t< Number > & matrix) const
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::minkowskiSum (const State< Number, Representation, Rargs... > & rhs) const
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...>& hypro::State< Number, Representation, Rargs >::operator= (const State< Number, Representation, Rargs... > & orig) inline
Copy assignment operator.
Parameters
[in] orig The original
Returns
A copy of the original state.
Definition at line 89 of file State.h.
References hypro::State< Number, Representation, Rargs >::checkConsistency(), hypro::State< Number, Representation, Rargs >::getEmptyStates(), hypro::State< Number, Representation, Rargs >::getLocation(), hypro::State< Number, Representation, Rargs >::getNumberSets(), hypro::State< Number, Representation, Rargs >::getSets(), hypro::State< Number, Representation, Rargs >::getTimestamp(), hypro::State< Number, Representation, Rargs >::getTypes(), and TRACE.
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...>& hypro::State< Number, Representation, Rargs >::operator= (State< Number, Representation, Rargs... > && orig) inline
Move assignment operator.
Parameters
[in] orig The original.
Returns
A state corresponding to the original.
Definition at line 110 of file State.h.
References hypro::State< Number, Representation, Rargs >::checkConsistency().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::partialIntervalAssignment (const std::vector< carl::Interval< Number >> & assignments, std::size_t I) const
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::partiallyApplyTimeStep (const ConstraintSet< Number > & flow, tNumber timeStepSize, std::size_t I = 0) const
Meta-function which applies a transformation by the passed parameters and increases the timestamp for the i-th set.
Parameters
[in] flow The solution to the differential equation system (a matrix exponential).
[in] timeStepSize The time step size.
[in] I The set index.
Returns
A state where the i-th set has been transformed by the passed parameters and the timestamp has been increased by timeStepSize.
Referenced by hypro::reachability::computeFirstSegment(), and hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::partiallyApplyTransformation (const std::vector< ConstraintSet< Number >> & trafos, const std::vector< std::size_t > & sets) const
Meta-function, which applies an affine transformation to each set contained in the state and whose index is contained in the second parameter.
Parameters
[in] trafos The trafos represented as a vector of ConstraintSet.
[in] sets The indices of the sets to transform.
Returns
A state where each indexed set has been transformed by the corresponding ConstraintSet.
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::partiallyApplyTransformation (const ConstraintSet< Number > & trafo, std::size_t I) const
Meta-function, which applies an affine transformation to the i-th set contained in the state.
Parameters
[in] trafo The trafo
[in] I The set index.
Returns
A state where the i-th set has been transformed by the passed parameters.
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::partiallyComputeAndApplyAffineTimeStep (const matrix_t< Number > & flow, tNumber timeStepSize, std::size_t I = 0) const
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::partiallyComputeAndApplyLinearTimeStep (const matrix_t< Number > & flow, tNumber timeStepSize, std::size_t I = 0) const
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::partiallyMinkowskiSum (const State< Number, Representation, Rargs... > & rhs, std::size_t I) const
Referenced by hypro::bloatBox(), and hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> void hypro::State< Number, Representation, Rargs >::partiallyReduceRepresentation (std::size_t I)
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> void hypro::State< Number, Representation, Rargs >::partiallyRemoveRedundancy (std::size_t I)
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> std::pair<CONTAINMENT, State<Number, Representation, Rargs...> > hypro::State< Number, Representation, Rargs >::partiallySatisfies (const Condition< Number > & in, std::size_t I) const
Meta-function to verify the i-th set of a state against the i-th component of a condition.
Parameters
[in] in The passed condition.
[in] I The set index.
Returns
A pair of a Boolean and the resulting state. The Boolean is set to True, if the resulting state is not empty.
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::project (const std::vector< std::size_t > & dimensions, std::size_t I = 0) const
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::project (const std::pair< std::size_t, std::size_t > & dimensions, std::size_t I = 0) const
template<typename Number, typename Representation, typename... Rargs> void hypro::State< Number, Representation, Rargs >::reduceRepresentation ()
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> void hypro::State< Number, Representation, Rargs >::removeRedundancy ()
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> std::vector<TRIBOOL>& hypro::State< Number, Representation, Rargs >::rGetEmptyStates () inline
Returns empty-flag values.
Returns
Vector of tribools.
Definition at line 282 of file State.h.
References hypro::State< Number, Representation, Rargs >::mIsEmpty.
template<typename Number, typename Representation, typename... Rargs> Location<Number>* hypro::State< Number, Representation, Rargs >::rGetLocation () inline
Gets the location.
Returns
The location.
Definition at line 209 of file State.h.
References hypro::State< Number, Representation, Rargs >::mLoc.
template<typename Number, typename Representation, typename... Rargs> std::variant<Representation, Rargs...>& hypro::State< Number, Representation, Rargs >::rGetSet (std::size_t i = 0)
Gets a reference to the i-th set.
Parameters
[in] i Set index.
Returns
The set.
Referenced by hypro::State< Number, Representation, Rargs >::getNumberSets().
template<typename Number, typename Representation, typename... Rargs> std::pair<CONTAINMENT, State<Number, Representation, Rargs...> > hypro::State< Number, Representation, Rargs >::satisfies (const Condition< Number > & in) const
Meta-function to verify a state against a condition.
Each contained set is verified separately. Note that once one verification fails the whole function directly returns. This function is the equivalent to satisfiesHalfspaces in GeometricObject.
Parameters
[in] in The passed condition.
Returns
A pair of a Boolean and the resulting state. The Boolean is set to True, if the resulting state is not empty.
Referenced by hypro::reachability::computeFirstSegment(), and hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> std::pair<CONTAINMENT, State<Number, Representation, Rargs...> > hypro::State< Number, Representation, Rargs >::satisfiesHalfspaces (const matrix_t< Number > & constraints, const vector_t< Number > & constants) const
Referenced by hypro::Flowpipe< hypro::State >::selectSatisfyingStates(), and hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> template<typename To > void hypro::State< Number, Representation, Rargs >::setAndConvertType (std::size_t I = 0)
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> void hypro::State< Number, Representation, Rargs >::setLocation (const Location< Number > * l) inline
Sets the location.
Parameters
[in] l The location.
Definition at line 288 of file State.h.
References hypro::State< Number, Representation, Rargs >::setSet().
Referenced by hypro::insertAndCreateTask(), and main().
template<typename Number, typename Representation, typename... Rargs> template<typename R > void hypro::State< Number, Representation, Rargs >::setSet (const R & s, std::size_t i = 0)
Sets the set at position i.
Parameters
[in] s The set.
[in] i The position.
Template Parameters
R The type of s.
Referenced by hypro::bloatBox(), main(), hypro::detail::strategyConversionVisitor< State >::operator()(), and hypro::State< Number, Representation, Rargs >::setLocation().
template<typename Number, typename Representation, typename... Rargs> void hypro::State< Number, Representation, Rargs >::setSet (const repVariant & s, std::size_t i = 0)
Sets the set at position i.
Parameters
[in] s The set.
[in] i The position.
template<typename Number, typename Representation, typename... Rargs> void hypro::State< Number, Representation, Rargs >::setSetDirect (const repVariant & in, std::size_t I = 0) inline
Sets the set.
Does not update the type for the respective position - can be used if type does not change to avoid unpacking.
Parameters
[in] in The set as a std::variant.
[in] I The position in the sets vector.
Definition at line 353 of file State.h.
References hypro::State< Number, Representation, Rargs >::addTimeToClocks(), hypro::State< Number, Representation, Rargs >::affineTransformation(), hypro::State< Number, Representation, Rargs >::applyTimeStep(), hypro::State< Number, Representation, Rargs >::applyTransformation(), hypro::State< Number, Representation, Rargs >::assignIntervals(), hypro::State< Number, Representation, Rargs >::checkConsistency(), hypro::State< Number, Representation, Rargs >::computeAndApplyAffineTimeStep(), hypro::State< Number, Representation, Rargs >::computeAndApplyLinearTimeStep(), hypro::State< Number, Representation, Rargs >::contains(), hypro::State< Number, Representation, Rargs >::decompose(), hypro::State< Number, Representation, Rargs >::getDimension(), hypro::State< Number, Representation, Rargs >::getDimensionOffset(), hypro::State< Number, Representation, Rargs >::getSupremum(), hypro::State< Number, Representation, Rargs >::intersectHalfspaces(), hypro::State< Number, Representation, Rargs >::linearTransformation(), hypro::State< Number, Representation, Rargs >::minkowskiSum(), hypro::NSET, hypro::State< Number, Representation, Rargs >::partialIntervalAssignment(), hypro::State< Number, Representation, Rargs >::partiallyApplyTimeStep(), hypro::State< Number, Representation, Rargs >::partiallyApplyTransformation(), hypro::State< Number, Representation, Rargs >::partiallyComputeAndApplyAffineTimeStep(), hypro::State< Number, Representation, Rargs >::partiallyComputeAndApplyLinearTimeStep(), hypro::State< Number, Representation, Rargs >::partiallyMinkowskiSum(), hypro::State< Number, Representation, Rargs >::partiallyReduceRepresentation(), hypro::State< Number, Representation, Rargs >::partiallyRemoveRedundancy(), hypro::State< Number, Representation, Rargs >::partiallySatisfies(), hypro::State< Number, Representation, Rargs >::project(), hypro::State< Number, Representation, Rargs >::reduceRepresentation(), hypro::State< Number, Representation, Rargs >::removeRedundancy(), hypro::State< Number, Representation, Rargs >::satisfies(), hypro::State< Number, Representation, Rargs >::satisfiesHalfspaces(), hypro::State< Number, Representation, Rargs >::setAndConvertType(), TRACE, hypro::State< Number, Representation, Rargs >::unite(), and hypro::State< Number, Representation, Rargs >::vertices().
Referenced by hypro::reachability::bloatBox().
template<typename Number, typename Representation, typename... Rargs> void hypro::State< Number, Representation, Rargs >::setSets (const std::vector< std::variant< Representation, Rargs... >> & sets)
Sets the sets.
Note that this method directly sets the sets while ignoring the consistency of the previously stored types
Parameters
[in] sets The sets.
Referenced by hypro::State< Number, Representation, Rargs >::setTimestamp().
template<typename Number, typename Representation, typename... Rargs> void hypro::State< Number, Representation, Rargs >::setSetsSave (const std::vector< std::variant< Representation, Rargs... >> & sets)
Sets the sets.
A slower but safer version of setSets as it ensures that mTypes and mSets must be consistent in terms of length and content when being set.
Parameters
[in] sets The sets to set.
Referenced by hypro::State< Number, Representation, Rargs >::setTimestamp().
template<typename Number, typename Representation, typename... Rargs> void hypro::State< Number, Representation, Rargs >::setSetType (representation_name type, std::size_t I = 0) inline
Sets the set type for the set at position i.
Parameters
[in] type The type
[in] I The position.
Definition at line 311 of file State.h.
References hypro::NSET, and TRACE.
template<typename Number, typename Representation, typename... Rargs> void hypro::State< Number, Representation, Rargs >::setTimestamp (const carl::Interval< tNumber > & t) inline
Sets the timestamp.
Parameters
[in] t The timestamp.
Definition at line 329 of file State.h.
References hypro::State< Number, Representation, Rargs >::setSets(), and hypro::State< Number, Representation, Rargs >::setSetsSave().
Referenced by main().
template<typename Number, typename Representation, typename... Rargs> State<Number, Representation, Rargs...> hypro::State< Number, Representation, Rargs >::unite (const State< Number, Representation, Rargs... > & in) const
Meta-function to aggregate two states.
Each contained set is aggregated with its corresponding set in the passed state.
Parameters
[in] in The passed second state.
Returns
A state which represents the closure of the union of both states.
Referenced by hypro::reachability::computeFirstSegment(), and hypro::State< Number, Representation, Rargs >::setSetDirect().
template<typename Number, typename Representation, typename... Rargs> std::vector<Point<Number> > hypro::State< Number, Representation, Rargs >::vertices (std::size_t I = 0) const
Referenced by hypro::State< Number, Representation, Rargs >::setSetDirect().
Friends And Related Function Documentation
template<typename Number, typename Representation, typename... Rargs> bool operator!= (const State< Number, Representation, Rargs... > & lhs, const State< Number, Representation, Rargs... > & rhs) friend
Operator for unequal.
Parameters
[in] lhs The left hand side.
[in] rhs The right hand side.
Returns
True, if both states are not equal, false otherwise.
Definition at line 585 of file State.h.
template<typename Number, typename Representation, typename... Rargs> std::ostream& operator<< (std::ostream & out, const State< Number, Representation, Rargs... > & state) friend
Outstream operator.
Parameters
out The outstream.
[in] state The state.
Returns
A reference to the outstream.
Definition at line 506 of file State.h.
template<typename Number, typename Representation, typename... Rargs> bool operator== (const State< Number, Representation, Rargs... > & lhs, const State< Number, Representation, Rargs... > & rhs) friend
Comparison for equality operator.
Note that this operator is very expensive in case both states are equal.
Parameters
[in] lhs The left hand side.
[in] rhs The right hand side.
Returns
True, if both states are equal, false otherwise.
Definition at line 537 of file State.h.
Member Data Documentation
template<typename Number, typename Representation, typename... Rargs> std::vector<TRIBOOL> hypro::State< Number, Representation, Rargs >::mIsEmpty mutable protected
A timestamp.
Definition at line 44 of file State.h.
Referenced by hypro::State< Number, Representation, Rargs >::getEmptyStates(), and hypro::State< Number, Representation, Rargs >::rGetEmptyStates().
template<typename Number, typename Representation, typename... Rargs> const Location<Number>* hypro::State< Number, Representation, Rargs >::mLoc = nullptr protected
Definition at line 40 of file State.h.
Referenced by hypro::State< Number, Representation, Rargs >::getLocation(), and hypro::State< Number, Representation, Rargs >::rGetLocation().
template<typename Number, typename Representation, typename... Rargs> std::vector<repVariant> hypro::State< Number, Representation, Rargs >::mSets protected
Location of the state.
Definition at line 41 of file State.h.
Referenced by hypro::State< Number, Representation, Rargs >::getSets().
template<typename Number, typename Representation, typename... Rargs> carl::Interval<tNumber> hypro::State< Number, Representation, Rargs >::mTimestamp = carl::Interval<tNumber>::unboundedInterval() protected
A vector holding the actual types corresponding to the state sets.
Definition at line 43 of file State.h.
Referenced by hypro::State< Number, Representation, Rargs >::getTimestamp().
template<typename Number, typename Representation, typename... Rargs> std::vector<representation_name> hypro::State< Number, Representation, Rargs >::mTypes protected
The state sets wrapped in variant (repVariant).
Definition at line 42 of file State.h.
Referenced by hypro::State< Number, Representation, Rargs >::getTypes().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/State.h