HyPro: hypro::Point< Number > Class Template Reference
hypro::Point< Number > Class Template Reference
Class for a point.
Public Types
using pointSet = std::set< Point< Number >>
using coordinateMap = std::map< carl::Variable, Number >
Public Member Functions
Point ()
Default constructor.
Point (const Number &_value)
Constructs a one dimensional point at the given coordinate.
Point (std::initializer_list< Number > _coordinates)
Constructor from an initializer list.
Point (std::vector< Number > _coordinates)
Constructor from a std::vector.
Point (const vector_t< Number > &_vector)
Constructor from the internal vector type.
Point (vector_t< Number > &&_vector)
Move constructor from the internal vector type.
Point (const Point< Number > &_p)=default
Copy constructor.
Point (Point< Number > &&_p)=default
Move-copy constructor.
template<typename F , carl::DisableIf< std::is_same< F, Number >> = carl::dummy>
Point (const Point< F > &_p)
Copy constructor with number type conversion.
virtual ~Point ()
Destroys the object.
std::size_t hash () const
Hash function.
void extend (const Number &val)
Extends the space the point lies in by one dimension and sets its coordinate.
Point< Number > origin () const
Returns the origin of the current space.
Number coordinate (const carl::Variable &_var) const
Returns the coordinate of the dimension mapped to the given variable.
Number coordinate (std::size_t _dimension) const
Returns the coordinate at the given dimension.
coordinateMap coordinates () const
Returns a mapping from variables to coordinates for the current point.
const vector_t< Number > & rawCoordinates () const
Returns the coordinates as a vector representation.
void setCoordinate (const carl::Variable &_dim, const Number &_value)
Sets the coordinate mapped to the given variable to the given value.
void setCoordinate (std::size_t dimension, const Number &_value)
Sets the coordinate for the passed dimension.
void swap (Point< Number > &_rhs)
Swap operator.
void setCoordinates (const vector_t< Number > &vector)
Sets the coordinates.
unsigned dimension () const
Returns the space dimension.
void reduceDimension (unsigned _dimension)
Reduces the space dimension by dropping the additional coordinates.
Point< Number > reduceToDimensions (std::vector< std::size_t > _dimensions) const
Projects the point onto the given set of dimensions.
std::vector< carl::Variable > variables () const
Returns the variables (ordered), which are assigned to the space dimensions.
Point< Number > extAdd (const Point< Number > &_rhs) const
Adds the coordinated of the passed point to this point.
Number distance (const Point< Number > &_rhs) const
Returns the euclidean distance between the current and the passed point.
std::vector< Number > polarCoordinates (const Point< Number > &_origin, bool _radians=true) const
Returns the polar coordinates of the current point according to the passed origin.
Point< Number > newEmpty () const
Creates an empty origin point with the same dimensions as the current point.
Point< Number > projectOn (const std::vector< std::size_t > &dimensions) const
Projects the point on the given dimensions.
Point< Number > projectOut (const std::vector< std::size_t > &dimensions) const
Projects out the given dimensions from the point.
Point< Number > linearTransformation (const matrix_t< Number > &A) const
Applies an affine transformation on the current point.
Point< Number > affineTransformation (const matrix_t< Number > &A, const vector_t< Number > &b) const
Applies an affine transformation on the current point.
Number sum () const
Returns the sum of all coordinates.
void incrementInFixedDim (const carl::Variable &_d)
Increments the coordinate according to the passed dimension by 1.
void incrementInFixedDim (unsigned _d)
Increments the coordinate according to the passed dimension by 1.
void incrementInAllDim (const Number &_val=1)
Increments all coordinates by the passed value.
void decrementInFixedDim (const carl::Variable &_d)
Decrements the coordinate according to the passed dimension by 1.
void decrementInFixedDim (unsigned _d)
Decrements the coordinate according to the passed dimension by 1.
Point getPredecessorInDimension (const carl::Variable &_d) const
Gets the predecessor in the passed dimension.
Point getPredecessorInDimension (unsigned _d) const
Gets the predecessor in the passed dimension.
bool isInBoundary (const Point< Number > &_boundary) const
Check if the current point is coefficient-wise smaller than the given point and larger than the origin.
bool hasDimension (const carl::Variable &_i) const
Determines if the point has the passed dimension.
bool hasDimensions (const std::vector< carl::Variable > &_variables) const
Determines if the point has the passed dimensions.
bool haveEqualCoordinate (const Point< Number > &_p2) const
Determines, if the current and the passed point have at lease one shared coordinate.
bool haveSameDimensions (const Point< Number > &_p) const
Compares the space dimension for two points.
bool operator< (const Point< Number > &_p2) const
Coordinate-wise comparison of two points.
bool operator<= (const Point< Number > &_p2) const
Coordinate-wise comparison of two points.
bool operator> (const Point< Number > &_p2) const
Coordinate-wise comparison of two points.
bool operator>= (const Point< Number > &_p2) const
Coordinate-wise comparison of two points.
bool operator== (const Point< Number > &_p2) const
Coordinate-wise comparison of two points.
template<typename F , carl::DisableIf< std::is_same< F, Number >> = carl::dummy>
bool operator== (const Point< F > &_p2) const
Coordinate-wise comparison of two points.
bool operator!= (const Point< Number > &_p2) const
Coordinate-wise comparison of two points.
operator vector_t< Number > () const
Conversion operator to the internal vector type.
Point< Number > & operator+= (const Point< Number > &_rhs)
Arithmetic assignment operator.
Point< Number > & operator+= (const vector_t< Number > &_rhs)
Arithmetic assignment operator.
Point< Number > & operator-= (const Point< Number > &_rhs)
Arithmetic assignment operator.
Point< Number > & operator-= (const vector_t< Number > &_rhs)
Arithmetic assignment operator.
Point< Number > operator- () const
Arithmetic assignment operator.
Point< Number > & operator/= (unsigned _quotient)
Arithmetic assignment operator.
Point< Number > & operator*= (const Number _factor)
Arithmetic assignment operator.
Point< Number > & operator= (const Point< Number > &_in)=default
Arithmetic assignment operator.
Point< Number > & operator= (Point< Number > &&_in)=default
Arithmetic assignment operator.
Point< Number > & operator= (const vector_t< Number > &_in)
Arithmetic assignment operator.
Point< Number > & operator= (vector_t< Number > &&_in)
Arithmetic assignment operator.
Number & operator[] (const carl::Variable &_i)
Access operator to the respective dimension coefficient.
Number & operator[] (std::size_t _i)
Access operator to the respective dimension coefficient.
const Number & operator[] (const carl::Variable &_i) const
Access operator to the respective dimension coefficient.
const Number & operator[] (std::size_t _i) const
Access operator to the respective dimension coefficient.
Number & at (const carl::Variable &_i)
Access operator to the respective dimension coefficient.
Number & at (std::size_t _index)
Access operator to the respective dimension coefficient.
const Number & at (const carl::Variable &_i) const
Access operator to the respective dimension coefficient.
const Number & at (std::size_t _index) const
Access operator to the respective dimension coefficient.
Static Public Member Functions
static Point< Number > Zero (std::size_t _dim=0)
Creates the origin point of the given space dimension.
static Point< Number > coeffWiseMax (const Point< Number > &_p1, const Point< Number > &_p2)
Returns a point representing the coefficient-wise maximum of two points.
static Point< Number > coeffWiseMin (const Point< Number > &_p1, const Point< Number > &_p2)
Returns a point representing the coefficient-wise minimum of two points.
static Number inftyNorm (const Point< Number > _p)
Returns the infinity norm of the point.
static std::vector< Point< Number > > removeDuplicatePoints (const std::vector< Point< Number >> &pointVec)
Removes any duplicate points in a given set of points.
static std::vector< bool > lesserDimensionPattern (const Point< Number > &_p1, const Point< Number > &_p2)
Creates a bitvector holding a 1 at pos i, if _p1(i) < _p2(i) holds.
Friends
std::ostream & operator<< (std::ostream &_ostr, const Point< Number > &_p)
Outstream operator.
Detailed Description
template<class Number>
class hypro::Point< Number >
Class for a point.
The point class is the basis for all implementation. It consists of a vector of coordinates which forms a point in a n-dimensional space.
Template Parameters
Number The used number type.
Examples:
example_box.cpp.
Definition at line 26 of file Point.h.
Constructor & Destructor Documentation
template<typename Number> hypro::Point< Number >::Point (const Number & _value) explicit
Constructs a one dimensional point at the given coordinate.
Parameters
[in] _value The coordinate.
Definition at line 12 of file Point.tpp.
References hypro::Point< Number >::dimension().
template<typename Number> hypro::Point< Number >::Point (std::initializer_list< Number > _coordinates) explicit
Constructor from an initializer list.
Parameters
[in] _coordinates The coordinates.
Definition at line 19 of file Point.tpp.
References hypro::Point< Number >::coordinate(), and hypro::Point< Number >::dimension().
template<typename Number> hypro::Point< Number >::Point (std::vector< Number > _coordinates) explicit
Constructor from a std::vector.
Parameters
[in] _coordinates The coordinates.
Definition at line 30 of file Point.tpp.
References hypro::Point< Number >::dimension().
template<typename Number> hypro::Point< Number >::Point (const vector_t< Number > & _vector) explicit
Constructor from the internal vector type.
Parameters
[in] _vector The vector.
Definition at line 39 of file Point.tpp.
References hypro::Point< Number >::dimension().
template<typename Number> hypro::Point< Number >::Point (vector_t< Number > && _vector) explicit
Move constructor from the internal vector type.
Parameters
[in] _vector The vector.
Definition at line 45 of file Point.tpp.
References hypro::Point< Number >::dimension().
template<class Number> hypro::Point< Number >::Point (const Point< Number > & _p) default
Copy constructor.
Parameters
[in] _p The original.
template<class Number> hypro::Point< Number >::Point (Point< Number > && _p) default
Move-copy constructor.
Parameters
[in] _p The original.
Member Function Documentation
template<typename Number> Point< Number > hypro::Point< Number >::affineTransformation (const matrix_t< Number > & A, const vector_t< Number > & b) const
Applies an affine transformation on the current point.
Parameters
[in] A The transformation matrix.
[in] b The transformation vector.
Returns
The resulting point.
Definition at line 269 of file Point.tpp.
Referenced by hypro::SupportFunctionContent< Number, Setting >::multiplicationsPerEvaluation(), and hypro::Point< int >::Zero().
template<typename Number > Number & hypro::Point< Number >::at (const carl::Variable & _i)
Access operator to the respective dimension coefficient.
Parameters
[in] _i The dimension.
Returns
The coefficient.
Definition at line 462 of file Point.tpp.
Referenced by hypro::Grid< Number >::calculateInduced(), hypro::Grid< Number >::calculateOriginal(), hypro::Point< int >::coeffWiseMax(), hypro::Point< int >::coeffWiseMin(), hypro::Grid< Number >::colorAt(), hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT(), hypro::BoxT< Number, Converter, Setting >::intersectHalfspace(), hypro::Point< Number >::lesserDimensionPattern(), hypro::BoxT< Number, Converter, Setting >::linearTransformation(), hypro::SupportFunctionContent< Number, Setting >::multiplicationsPerEvaluation(), hypro::Point< int >::operator!=(), hypro::Point< Number >::operator+=(), hypro::Point< Number >::operator-=(), hypro::Point< int >::operator==(), hypro::Vertex< std::size_t >::operator[](), hypro::Point< int >::Point(), and hypro::Point< Number >::polarCoordinates().
template<typename Number > Number & hypro::Point< Number >::at (std::size_t _index)
Access operator to the respective dimension coefficient.
Parameters
[in] _i The dimension.
Returns
The coefficient.
Definition at line 470 of file Point.tpp.
template<typename Number > const Number & hypro::Point< Number >::at (const carl::Variable & _i) const
Access operator to the respective dimension coefficient.
Parameters
[in] _i The dimension.
Returns
The coefficient.
Definition at line 478 of file Point.tpp.
template<typename Number > const Number & hypro::Point< Number >::at (std::size_t _index) const
Access operator to the respective dimension coefficient.
Parameters
[in] _i The dimension.
Returns
The coefficient.
Definition at line 486 of file Point.tpp.
template<class Number> static Point<Number> hypro::Point< Number >::coeffWiseMax (const Point< Number > & _p1, const Point< Number > & _p2) inline static
Returns a point representing the coefficient-wise maximum of two points.
Parameters
[in] _p1 The first point.
[in] _p2 The second point.
Returns
The resulting point.
Definition at line 275 of file Point.h.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT().
template<class Number> static Point<Number> hypro::Point< Number >::coeffWiseMin (const Point< Number > & _p1, const Point< Number > & _p2) inline static
Returns a point representing the coefficient-wise minimum of two points.
Parameters
[in] _p1 The first point.
[in] _p2 The second point.
Returns
The resulting point.
Definition at line 290 of file Point.h.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT().
template<typename Number > Number hypro::Point< Number >::coordinate (const carl::Variable & _var) const
Returns the coordinate of the dimension mapped to the given variable.
Parameters
[in] _var The variable.
Returns
The coordinate.
Definition at line 58 of file Point.tpp.
Referenced by hypro::Vertex< std::size_t >::coordinate(), hypro::NeighborhoodContainer::getNeighborhoodForDimension(), hypro::Point< Number >::Point(), and hypro::Point< int >::Zero().
template<typename Number > Number hypro::Point< Number >::coordinate (std::size_t _dimension) const
Returns the coordinate at the given dimension.
Parameters
[in] _dimension The dimension.
Returns
The coordinate.
Definition at line 63 of file Point.tpp.
template<typename Number > Point< Number >::coordinateMap hypro::Point< Number >::coordinates () const
Returns a mapping from variables to coordinates for the current point.
Returns
The mapping.
Definition at line 69 of file Point.tpp.
Referenced by hypro::Point< int >::coeffWiseMax(), hypro::Point< int >::coeffWiseMin(), hypro::Point< Number >::origin(), hypro::Point< int >::Point(), and hypro::Point< int >::Zero().
template<typename Number > void hypro::Point< Number >::decrementInFixedDim (const carl::Variable & _d)
Decrements the coordinate according to the passed dimension by 1.
Parameters
[in] _d The dimension.
Definition at line 299 of file Point.tpp.
Referenced by hypro::Point< Number >::getPredecessorInDimension(), and hypro::Point< int >::removeDuplicatePoints().
template<typename Number > void hypro::Point< Number >::decrementInFixedDim (unsigned _d)
Decrements the coordinate according to the passed dimension by 1.
Parameters
[in] _d The dimension.
Definition at line 304 of file Point.tpp.
template<typename Number > unsigned hypro::Point< Number >::dimension () const
Returns the space dimension.
Returns
The dimension.
Definition at line 116 of file Point.tpp.
Referenced by hypro::Plotter< Number >::addPoint(), hypro::Point< int >::coeffWiseMax(), hypro::Point< int >::coeffWiseMin(), hypro::Grid< Number >::colorAt(), hypro::BoxSupportFunction< Number, Setting >::contains(), hypro::Vertex< std::size_t >::dimension(), hypro::NeighborhoodContainer::getNeighborhoodForDimension(), hypro::Plotter< Number >::grahamScan(), hypro::Point< Number >::haveEqualCoordinate(), hypro::Point< Number >::haveSameDimensions(), hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT(), hypro::Point< int >::inftyNorm(), hypro::BoxT< Number, Converter, Setting >::intersectHalfspace(), hypro::Point< Number >::lesserDimensionPattern(), hypro::SupportFunctionContent< Number, Setting >::multiplicationsPerEvaluation(), hypro::Point< Number >::newEmpty(), hypro::operator*(), hypro::operator+(), hypro::Point< Number >::operator+=(), hypro::operator-(), hypro::Point< Number >::operator-=(), hypro::operator/(), hypro::Point< int >::operator==(), hypro::Point< Number >::origin(), hypro::Point< Number >::Point(), hypro::Point< int >::Point(), hypro::Point< Number >::polarCoordinates(), hypro::Point< Number >::projectOn(), hypro::Point< Number >::projectOut(), hypro::VPolytopeT< Number, Converter, S >::setRays(), and hypro::Point< int >::Zero().
template<typename Number> Number hypro::Point< Number >::distance (const Point< Number > & _rhs) const
Returns the euclidean distance between the current and the passed point.
Parameters
[in] _rhs The right hand side.
Returns
The distance.
Definition at line 167 of file Point.tpp.
References hypro::Point< Number >::rawCoordinates().
Referenced by hypro::TimedContext< State >::computeShortestElapsedTimeIntervalForSubspace(), and hypro::Point< int >::Zero().
template<typename Number> Point< Number > hypro::Point< Number >::extAdd (const Point< Number > & _rhs) const
Adds the coordinated of the passed point to this point.
Parameters
[in] _rhs The right hand side.
Returns
The resulting point.
Definition at line 159 of file Point.tpp.
References hypro::Point< Number >::rawCoordinates().
Referenced by hypro::Point< int >::Zero().
template<class Number> void hypro::Point< Number >::extend (const Number & val) inline
Extends the space the point lies in by one dimension and sets its coordinate.
Parameters
[in] val The new coordinate.
Definition at line 110 of file Point.h.
template<typename Number > Point< Number > hypro::Point< Number >::getPredecessorInDimension (const carl::Variable & _d) const
Gets the predecessor in the passed dimension.
Parameters
[in] _d The dimension.
Returns
The predecessor in dimension.
Definition at line 309 of file Point.tpp.
References hypro::Point< Number >::decrementInFixedDim().
Referenced by hypro::Point< int >::removeDuplicatePoints().
template<typename Number > Point< Number > hypro::Point< Number >::getPredecessorInDimension (unsigned _d) const
Gets the predecessor in the passed dimension.
Parameters
[in] _d The dimension.
Returns
The predecessor in dimension.
Definition at line 316 of file Point.tpp.
References hypro::Point< Number >::decrementInFixedDim().
template<typename Number > bool hypro::Point< Number >::hasDimension (const carl::Variable & _i) const
Determines if the point has the passed dimension.
Parameters
[in] _i The dimension.
Returns
True if has the passed dimension, false otherwise.
Definition at line 328 of file Point.tpp.
Referenced by hypro::Vertex< std::size_t >::hasDimension(), hypro::Point< Number >::hasDimensions(), and hypro::Point< int >::removeDuplicatePoints().
template<typename Number > bool hypro::Point< Number >::hasDimensions (const std::vector< carl::Variable > & _variables) const
Determines if the point has the passed dimensions.
Parameters
[in] _i The vector of dimensions.
Returns
True if has all passed dimensions, false otherwise.
Definition at line 333 of file Point.tpp.
References hypro::Point< Number >::hasDimension().
Referenced by hypro::Vertex< std::size_t >::hasDimensions(), and hypro::Point< int >::removeDuplicatePoints().
template<class Number> std::size_t hypro::Point< Number >::hash () const inline
Hash function.
Returns
The hash.
Definition at line 102 of file Point.h.
Referenced by hypro::Point< int >::operator==().
template<typename Number> bool hypro::Point< Number >::haveEqualCoordinate (const Point< Number > & _p2) const
Determines, if the current and the passed point have at lease one shared coordinate.
Parameters
[in] _p2 The point.
Returns
True, if at least one coordinate is equal.
Definition at line 354 of file Point.tpp.
References hypro::Point< Number >::dimension(), and hypro::Point< Number >::rawCoordinates().
Referenced by hypro::Point< int >::removeDuplicatePoints().
template<typename Number> bool hypro::Point< Number >::haveSameDimensions (const Point< Number > & _p) const
Compares the space dimension for two points.
Parameters
[in] _p The second point.
Returns
True, if the space dimensions are equal, false otherwise.
Definition at line 366 of file Point.tpp.
References hypro::Point< Number >::dimension().
Referenced by hypro::Point< int >::removeDuplicatePoints().
template<typename Number> void hypro::Point< Number >::incrementInAllDim (const Number & _val = 1)
Increments all coordinates by the passed value.
Parameters
[in] _val The value.
Definition at line 292 of file Point.tpp.
Referenced by hypro::Point< int >::removeDuplicatePoints().
template<typename Number > void hypro::Point< Number >::incrementInFixedDim (const carl::Variable & _d)
Increments the coordinate according to the passed dimension by 1.
Parameters
[in] _d The dimension.
Definition at line 282 of file Point.tpp.
Referenced by hypro::Point< int >::removeDuplicatePoints().
template<typename Number > void hypro::Point< Number >::incrementInFixedDim (unsigned _d)
Increments the coordinate according to the passed dimension by 1.
Parameters
[in] _d The dimension.
Definition at line 287 of file Point.tpp.
template<class Number> static Number hypro::Point< Number >::inftyNorm (const Point< Number > _p) inline static
Returns the infinity norm of the point.
Parameters
[in] _p The point.
Returns
The infinity norm.
Definition at line 304 of file Point.h.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::cleanUp(), hypro::SupportFunctionContent< Number, Setting >::multiplicationsPerEvaluation(), hypro::HPolytopeT< Number, Converter, Setting >::supremum(), hypro::VPolytopeT< Number, Converter, S >::supremum(), hypro::SupportFunctionNewT< Number, Converter, Setting >::supremum(), and hypro::BoxT< Number, Converter, Setting >::supremum().
template<typename Number> bool hypro::Point< Number >::isInBoundary (const Point< Number > & _boundary) const
Check if the current point is coefficient-wise smaller than the given point and larger than the origin.
Parameters
boundary Point with coordinates that may not be exceeded in positive direction.
Returns
True, if every coordinate is within boundary[i] and the origin, false otherwise.
Definition at line 323 of file Point.tpp.
References hypro::Point< Number >::rawCoordinates().
Referenced by hypro::Point< int >::removeDuplicatePoints().
template<typename Number> std::vector< bool > hypro::Point< Number >::lesserDimensionPattern (const Point< Number > & _p1, const Point< Number > & _p2) static
Creates a bitvector holding a 1 at pos i, if _p1(i) < _p2(i) holds.
Parameters
[in] _p1 The first point.
[in] _p2 The second point.
Returns
The resulting bitvector.
Definition at line 343 of file Point.tpp.
References hypro::Point< Number >::at(), and hypro::Point< Number >::dimension().
Referenced by hypro::Point< int >::removeDuplicatePoints().
template<typename Number> Point< Number > hypro::Point< Number >::linearTransformation (const matrix_t< Number > & A) const
Applies an affine transformation on the current point.
Parameters
[in] A The transformation matrix.
[in] b The transformation vector.
Returns
The resulting point.
Definition at line 263 of file Point.tpp.
Referenced by hypro::Point< int >::Zero().
template<typename Number > Point< Number > hypro::Point< Number >::newEmpty () const
Creates an empty origin point with the same dimensions as the current point.
Returns
The empty point.
Definition at line 223 of file Point.tpp.
References hypro::Point< Number >::dimension(), and hypro::Point< Number >::origin().
Referenced by hypro::Point< int >::Zero().
template<class Number> bool hypro::Point< Number >::operator!= (const Point< Number > & _p2) const inline
Coordinate-wise comparison of two points.
Parameters
[in] _p2 The second point.
Returns
True, if for all coordinates the comparison holds.
Definition at line 486 of file Point.h.
template<typename Number> Point< Number > & hypro::Point< Number >::operator*= (const Number _factor)
Arithmetic assignment operator.
Parameters
[in] The right hand side.
Returns
The reference to the current point modified by the operation.
Definition at line 420 of file Point.tpp.
Referenced by hypro::Point< int >::operator!=().
template<typename Number> Point< Number > & hypro::Point< Number >::operator+= (const Point< Number > & _rhs)
Arithmetic assignment operator.
Parameters
[in] The right hand side.
Returns
The reference to the current point modified by the operation.
Definition at line 371 of file Point.tpp.
References hypro::Point< Number >::at(), and hypro::Point< Number >::dimension().
Referenced by hypro::Point< int >::operator!=().
template<typename Number> Point< Number > & hypro::Point< Number >::operator+= (const vector_t< Number > & _rhs)
Arithmetic assignment operator.
Parameters
[in] The right hand side.
Returns
The reference to the current point modified by the operation.
Definition at line 380 of file Point.tpp.
References hypro::Point< Number >::dimension().
template<typename Number > Point< Number > hypro::Point< Number >::operator- () const
Arithmetic assignment operator.
Parameters
[in] The right hand side.
Returns
The reference to the current point modified by the operation.
Definition at line 407 of file Point.tpp.
Referenced by hypro::Point< int >::operator!=().
template<typename Number> Point< Number > & hypro::Point< Number >::operator-= (const Point< Number > & _rhs)
Arithmetic assignment operator.
Parameters
[in] The right hand side.
Returns
The reference to the current point modified by the operation.
Definition at line 389 of file Point.tpp.
References hypro::Point< Number >::at(), and hypro::Point< Number >::dimension().
Referenced by hypro::Point< int >::operator!=().
template<typename Number> Point< Number > & hypro::Point< Number >::operator-= (const vector_t< Number > & _rhs)
Arithmetic assignment operator.
Parameters
[in] The right hand side.
Returns
The reference to the current point modified by the operation.
Definition at line 398 of file Point.tpp.
References hypro::Point< Number >::dimension().
template<typename Number > Point< Number > & hypro::Point< Number >::operator/= (unsigned _quotient)
Arithmetic assignment operator.
Parameters
[in] The right hand side.
Returns
The reference to the current point modified by the operation.
Definition at line 412 of file Point.tpp.
Referenced by hypro::Point< int >::operator!=().
template<class Number> bool hypro::Point< Number >::operator< (const Point< Number > & _p2) const inline
Coordinate-wise comparison of two points.
Parameters
[in] _p2 The second point.
Returns
True, if for all coordinates the comparison holds.
Definition at line 428 of file Point.h.
template<class Number> bool hypro::Point< Number >::operator<= (const Point< Number > & _p2) const inline
Coordinate-wise comparison of two points.
Parameters
[in] _p2 The second point.
Returns
True, if for all coordinates the comparison holds.
Definition at line 435 of file Point.h.
template<class Number> Point<Number>& hypro::Point< Number >::operator= (const Point< Number > & _in) default
Arithmetic assignment operator.
Parameters
[in] The right hand side.
Returns
The reference to the current point modified by the operation.
Referenced by hypro::Point< int >::operator!=().
template<class Number> Point<Number>& hypro::Point< Number >::operator= (Point< Number > && _in) default
Arithmetic assignment operator.
Parameters
[in] The right hand side.
Returns
The reference to the current point modified by the operation.
template<typename Number> Point< Number > & hypro::Point< Number >::operator= (const vector_t< Number > & _in)
Arithmetic assignment operator.
Parameters
[in] The right hand side.
Returns
The reference to the current point modified by the operation.
Definition at line 428 of file Point.tpp.
template<typename Number> Point< Number > & hypro::Point< Number >::operator= (vector_t< Number > && _in)
Arithmetic assignment operator.
Parameters
[in] The right hand side.
Returns
The reference to the current point modified by the operation.
Definition at line 434 of file Point.tpp.
template<class Number> bool hypro::Point< Number >::operator== (const Point< Number > & _p2) const inline
Coordinate-wise comparison of two points.
Parameters
[in] _p2 The second point.
Returns
True, if for all coordinates the comparison holds.
Definition at line 456 of file Point.h.
template<class Number> template<typename F , carl::DisableIf< std::is_same< F, Number >> = carl::dummy> bool hypro::Point< Number >::operator== (const Point< F > & _p2) const inline
Coordinate-wise comparison of two points.
Parameters
[in] _p2 The second point.
Returns
True, if for all coordinates the comparison holds.
Definition at line 471 of file Point.h.
template<class Number> bool hypro::Point< Number >::operator> (const Point< Number > & _p2) const inline
Coordinate-wise comparison of two points.
Parameters
[in] _p2 The second point.
Returns
True, if for all coordinates the comparison holds.
Definition at line 442 of file Point.h.
template<class Number> bool hypro::Point< Number >::operator>= (const Point< Number > & _p2) const inline
Coordinate-wise comparison of two points.
Parameters
[in] _p2 The second point.
Returns
True, if for all coordinates the comparison holds.
Definition at line 449 of file Point.h.
template<typename Number > Number & hypro::Point< Number >::operator[] (const carl::Variable & _i)
Access operator to the respective dimension coefficient.
Parameters
[in] _i The dimension.
Returns
The coefficient.
Definition at line 440 of file Point.tpp.
Referenced by hypro::Point< int >::operator!=().
template<typename Number > Number & hypro::Point< Number >::operator[] (std::size_t _i)
Access operator to the respective dimension coefficient.
Parameters
[in] _i The dimension.
Returns
The coefficient.
Definition at line 446 of file Point.tpp.
template<typename Number > const Number & hypro::Point< Number >::operator[] (const carl::Variable & _i) const
Access operator to the respective dimension coefficient.
Parameters
[in] _i The dimension.
Returns
The coefficient.
Definition at line 451 of file Point.tpp.
template<typename Number > const Number & hypro::Point< Number >::operator[] (std::size_t _i) const
Access operator to the respective dimension coefficient.
Parameters
[in] _i The dimension.
Returns
The coefficient.
Definition at line 457 of file Point.tpp.
template<typename Number > Point< Number > hypro::Point< Number >::origin () const
Returns the origin of the current space.
Returns
The origin.
Definition at line 51 of file Point.tpp.
References hypro::Point< Number >::coordinates(), and hypro::Point< Number >::dimension().
Referenced by hypro::SupportFunctionContent< Number, Setting >::multiplicationsPerEvaluation(), hypro::Point< Number >::newEmpty(), and hypro::Point< int >::Zero().
template<typename Number> std::vector< Number > hypro::Point< Number >::polarCoordinates (const Point< Number > & _origin, bool _radians = true) const
Returns the polar coordinates of the current point according to the passed origin.
Parameters
[in] _origin The origin.
[in] _radians If true, use radians.
Returns
A vector of polar coordinates.
Definition at line 172 of file Point.tpp.
References hypro::Point< Number >::at(), and hypro::Point< Number >::dimension().
Referenced by hypro::Point< int >::Zero().
template<typename Number > Point< Number > hypro::Point< Number >::projectOn (const std::vector< std::size_t > & dimensions) const
Projects the point on the given dimensions.
Parameters
[in] dimensions The dimensions.
Returns
The projected point.
Definition at line 229 of file Point.tpp.
References hypro::Point< Number >::dimension().
Referenced by hypro::Point< int >::Zero().
template<typename Number > Point< Number > hypro::Point< Number >::projectOut (const std::vector< std::size_t > & dimensions) const
Projects out the given dimensions from the point.
Parameters
[in] dimensions The dimensions.
Returns
The projected point.
Definition at line 245 of file Point.tpp.
References hypro::Point< Number >::dimension().
Referenced by hypro::Point< int >::Zero().
template<typename Number > const vector_t< Number > & hypro::Point< Number >::rawCoordinates () const
Returns the coordinates as a vector representation.
Returns
The coordinate vector.
Definition at line 78 of file Point.tpp.
Referenced by hypro::Plotter< Number >::addPoint(), hypro::Halfspace< Number >::computePlaneOffset(), hypro::BallSupportFunction< Number >::contains(), hypro::EllipsoidSupportFunction< Number >::contains(), hypro::PolytopeSupportFunction< Number, Setting >::contains(), hypro::Halfspace< Number >::contains(), hypro::SupportFunctionNewT< Number, Converter, Setting >::contains(), hypro::convert(), hypro::Vertex< std::size_t >::coordinate(), hypro::Point< Number >::distance(), hypro::Facet< Number >::empty(), hypro::HPolytopeT< Number, Converter, Setting >::erase(), hypro::Point< Number >::extAdd(), hypro::NeighborhoodContainer::getNeighborhoodForDimension(), hypro::Plotter< Number >::grahamScan(), hypro::Point< Number >::haveEqualCoordinate(), hypro::Point< int >::inftyNorm(), hypro::VPolytopeT< Number, Converter, S >::intersect(), hypro::BoxT< Number, Converter, Setting >::intersectHalfspace(), hypro::Halfspace< Number >::intersection(), hypro::ZonotopeT< Number, Converter, Setting >::intervalHull(), hypro::Point< Number >::isInBoundary(), hypro::SupportFunctionContent< Number, Setting >::multiplicationsPerEvaluation(), hypro::operator*(), hypro::operator+(), hypro::operator-(), hypro::operator/(), hypro::Point< int >::operator<(), hypro::Point< int >::operator<=(), hypro::Point< int >::operator==(), hypro::Halfspace< Number >::projectPointOnPlane(), and hypro::Point< int >::Zero().
template<typename Number > void hypro::Point< Number >::reduceDimension (unsigned _dimension)
Reduces the space dimension by dropping the additional coordinates.
Parameters
[in] _dimension The target dimension.
Definition at line 122 of file Point.tpp.
Referenced by hypro::Point< int >::Zero().
template<typename Number > Point< Number > hypro::Point< Number >::reduceToDimensions (std::vector< std::size_t > _dimensions) const
Projects the point onto the given set of dimensions.
Parameters
[in] _dimensions The dimensions.
Returns
The resulting point.
Definition at line 134 of file Point.tpp.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::boundaryBox(), and hypro::Point< int >::Zero().
template<class Number> static std::vector<Point<Number> > hypro::Point< Number >::removeDuplicatePoints (const std::vector< Point< Number >> & pointVec) inline static
Removes any duplicate points in a given set of points.
Author
Simon Froitzheim
Parameters
[in] PointVec the point vector which should get checked for duplicates.
Returns
A point vector that is duplicate-free.
Definition at line 320 of file Point.h.
Referenced by hypro::computeBoundaryPointsExpensive().
template<typename Number> void hypro::Point< Number >::setCoordinate (const carl::Variable & _dim, const Number & _value)
Sets the coordinate mapped to the given variable to the given value.
Parameters
[in] _dim The variable.
[in] _value The value.
Definition at line 83 of file Point.tpp.
Referenced by hypro::Point< int >::Zero().
template<typename Number> void hypro::Point< Number >::setCoordinate (std::size_t dimension, const Number & _value)
Sets the coordinate for the passed dimension.
Parameters
[in] _dim The dimension.
[in] _value The value.
Definition at line 94 of file Point.tpp.
template<typename Number> void hypro::Point< Number >::setCoordinates (const vector_t< Number > & vector)
Sets the coordinates.
Parameters
[in] vector The vector.
Definition at line 111 of file Point.tpp.
Referenced by hypro::Point< int >::Zero().
template<typename Number > Number hypro::Point< Number >::sum () const
Returns the sum of all coordinates.
Returns
The sum.
Definition at line 276 of file Point.tpp.
Referenced by hypro::Point< int >::Zero().
template<typename Number> void hypro::Point< Number >::swap (Point< Number > & _rhs)
Swap operator.
Parameters
_rhs The right hand side.
Definition at line 104 of file Point.tpp.
Referenced by hypro::Vertex< std::size_t >::invertColor(), hypro::swap(), and hypro::Point< int >::Zero().
template<typename Number > std::vector< carl::Variable > hypro::Point< Number >::variables () const
Returns the variables (ordered), which are assigned to the space dimensions.
Returns
A vector of variables.
Definition at line 150 of file Point.tpp.
Referenced by hypro::Vertex< std::size_t >::variables(), and hypro::Point< int >::Zero().
template<class Number> static Point<Number> hypro::Point< Number >::Zero (std::size_t _dim = 0) inline static
Creates the origin point of the given space dimension.
Parameters
[in] _dim The dimension.
Returns
The origin point.
Definition at line 120 of file Point.h.
Referenced by hypro::ConvexHull< Number >::conicHull(), hypro::PolytopeSupportFunction< Number, Setting >::dimension(), hypro::SupportFunctionContent< Number, Setting >::multiplicationsPerEvaluation(), and hypro::Grid< Number >::size().
Friends And Related Function Documentation
template<class Number> std::ostream& operator<< (std::ostream & _ostr, const Point< Number > & _p) friend
Outstream operator.
Parameters
_ostr The outstream
[in] _p The point.
Returns
A reference to the outstream.
Definition at line 530 of file Point.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/datastructures/Point.h
/home/travis/build/hypro/hypro/src/hypro/datastructures/Point.tpp