HyPro: hypro::VertexContainer< Number > Class Template Reference
hypro::VertexContainer< Number > Class Template Reference
Public Member Functions
VertexContainer ()
VertexContainer (const Vertex< Number > &_vertex)
VertexContainer (const vSet< Number > &vertices)
VertexContainer (const std::vector< Vertex< Number >> &_vertices)
VertexContainer (const VertexContainer &orig)
~VertexContainer ()
std::size_t dimension () const
std::vector< carl::Variable > variables () const
std::size_t size () const
bool empty () const
vSet< Number > & rVertices ()
vSet< Number > vertices () const
vList< Number > getSmallerVertices (const Point< Number > &p)
std::pair< bool, bool > isVertex (const Point< Number > &p) const
bool originIsVertex () const
VertexContainer< Number > & operator= (const VertexContainer< Number > &rhs)
vSetIt< Number > find (const Point< Number > &p, bool colour=false) const
vSetIt< Number > find (const Vertex< Number > &v) const
void move (const Point< Number > &p)
void linearTransformation (const matrix_t< Number > &A, const vector_t< Number > &b)
vSetIt< Number > begin () const
vSetIt< Number > end () const
std::pair< vSetIt< Number >, bool > insert (const Vertex< Number > &v)
template<typename ForwardIterator >
void insert (ForwardIterator begin, ForwardIterator end)
std::pair< vSetIt< Number >, bool > insert (const Point< Number > &p, const bool c=false)
template<typename BiIterator >
vSetIt< Number > insert (const Vertex< Number > &v, const BiIterator pos)
vSetIt< Number > insertAtBack (const Vertex< Number > &v)
template<typename BiIterator >
vSetIt< Number > insert (const Point< Number > &p, bool c, const BiIterator pos)
template<typename BiIterator >
void erase (BiIterator pos)
void erase (const Vertex< Number > &p)
void clear ()
bool set (const Point< Number > &p, bool c)
std::size_t getHash () const
const bool & operator[] (const Point< Number > &p) const
Friends
bool operator== (const VertexContainer< Number > &c1, const VertexContainer< Number > &c2)
bool operator!= (const VertexContainer< Number > &c1, const VertexContainer< Number > &c2)
std::ostream & operator<< (std::ostream &ostr, const VertexContainer< Number > &cont)
Detailed Description
template<typename Number>
class hypro::VertexContainer< Number >
Definition at line 19 of file VertexContainer.h.
Constructor & Destructor Documentation
template<typename Number> hypro::VertexContainer< Number >::VertexContainer () inline
Definition at line 31 of file VertexContainer.h.
template<typename Number> hypro::VertexContainer< Number >::VertexContainer (const Vertex< Number > & _vertex) inline
Definition at line 32 of file VertexContainer.h.
template<typename Number> hypro::VertexContainer< Number >::VertexContainer (const vSet< Number > & vertices) inline
Definition at line 34 of file VertexContainer.h.
template<typename Number> hypro::VertexContainer< Number >::VertexContainer (const std::vector< Vertex< Number >> & _vertices) inline
Definition at line 36 of file VertexContainer.h.
template<typename Number> hypro::VertexContainer< Number >::VertexContainer (const VertexContainer< Number > & orig) inline
Definition at line 40 of file VertexContainer.h.
template<typename Number> hypro::VertexContainer< Number >::~VertexContainer () inline
Definition at line 41 of file VertexContainer.h.
Member Function Documentation
template<typename Number> vSetIt<Number> hypro::VertexContainer< Number >::begin () const inline
Returns
Definition at line 148 of file VertexContainer.h.
Referenced by std::hash< set< hypro::Vertex< Number > > >::operator()().
template<typename Number> void hypro::VertexContainer< Number >::clear () inline
clears the underlying container.
Definition at line 241 of file VertexContainer.h.
template<typename Number> std::size_t hypro::VertexContainer< Number >::dimension () const inline
Definition at line 47 of file VertexContainer.h.
template<typename Number> bool hypro::VertexContainer< Number >::empty () const inline
Definition at line 59 of file VertexContainer.h.
template<typename Number> vSetIt<Number> hypro::VertexContainer< Number >::end () const inline
Returns
Definition at line 154 of file VertexContainer.h.
template<typename Number> template<typename BiIterator > void hypro::VertexContainer< Number >::erase (BiIterator pos) inline
Parameters
pos
Definition at line 224 of file VertexContainer.h.
template<typename Number> void hypro::VertexContainer< Number >::erase (const Vertex< Number > & p) inline
Parameters
p Vertex that is erased.
Definition at line 233 of file VertexContainer.h.
template<typename Number> vSetIt<Number> hypro::VertexContainer< Number >::find (const Point< Number > & p, bool colour = false) const inline
Definition at line 108 of file VertexContainer.h.
template<typename Number> vSetIt<Number> hypro::VertexContainer< Number >::find (const Vertex< Number > & v) const inline
Definition at line 112 of file VertexContainer.h.
References hypro::Vertex< Number >::color().
template<typename Number> std::size_t hypro::VertexContainer< Number >::getHash () const inline
Returns
Hash value
Definition at line 258 of file VertexContainer.h.
References hypro::VertexContainer< Number >::vertices().
template<typename Number> vList<Number> hypro::VertexContainer< Number >::getSmallerVertices (const Point< Number > & p) inline
Definition at line 65 of file VertexContainer.h.
template<typename Number> std::pair<vSetIt<Number>, bool> hypro::VertexContainer< Number >::insert (const Vertex< Number > & v) inline
Parameters
v
Returns
A bidirectional iterator to the inserted Vertex. Not safe.
Definition at line 162 of file VertexContainer.h.
Referenced by hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::hull(), hypro::VertexContainer< Number >::insert(), main(), and hypro::VertexContainer< Number >::set().
template<typename Number> template<typename ForwardIterator > void hypro::VertexContainer< Number >::insert (ForwardIterator begin, ForwardIterator end) inline
Parameters
begin
end
Definition at line 173 of file VertexContainer.h.
template<typename Number> std::pair<vSetIt<Number>, bool> hypro::VertexContainer< Number >::insert (const Point< Number > & p, const bool c = false) inline
Parameters
p
c
Returns
Definition at line 184 of file VertexContainer.h.
References hypro::VertexContainer< Number >::insert().
template<typename Number> template<typename BiIterator > vSetIt<Number> hypro::VertexContainer< Number >::insert (const Vertex< Number > & v, const BiIterator pos) inline
Parameters
v
pos
Returns
Definition at line 196 of file VertexContainer.h.
template<typename Number> template<typename BiIterator > vSetIt<Number> hypro::VertexContainer< Number >::insert (const Point< Number > & p, bool c, const BiIterator pos) inline
Parameters
p
c
pos
Returns
Definition at line 214 of file VertexContainer.h.
References hypro::VertexContainer< Number >::insert().
template<typename Number> vSetIt<Number> hypro::VertexContainer< Number >::insertAtBack (const Vertex< Number > & v) inline
Definition at line 201 of file VertexContainer.h.
template<typename Number> std::pair<bool, bool> hypro::VertexContainer< Number >::isVertex (const Point< Number > & p) const inline
Parameters
p
Returns
Definition at line 78 of file VertexContainer.h.
Referenced by hypro::VertexContainer< Number >::operator[]().
template<typename Number> void hypro::VertexContainer< Number >::linearTransformation (const matrix_t< Number > & A, const vector_t< Number > & b) inline
Definition at line 131 of file VertexContainer.h.
References hypro::Vertex< Number >::rPoint().
template<typename Number> void hypro::VertexContainer< Number >::move (const Point< Number > & p) inline
Definition at line 118 of file VertexContainer.h.
References hypro::Vertex< Number >::rPoint().
template<typename Number> VertexContainer<Number>& hypro::VertexContainer< Number >::operator= (const VertexContainer< Number > & rhs) inline
Definition at line 100 of file VertexContainer.h.
template<typename Number> const bool& hypro::VertexContainer< Number >::operator[] (const Point< Number > & p) const inline
Parameters
p
Returns
Definition at line 295 of file VertexContainer.h.
References hypro::VertexContainer< Number >::isVertex().
template<typename Number> bool hypro::VertexContainer< Number >::originIsVertex () const inline
Returns
Definition at line 90 of file VertexContainer.h.
template<typename Number> vSet<Number>& hypro::VertexContainer< Number >::rVertices () inline
Definition at line 61 of file VertexContainer.h.
template<typename Number> bool hypro::VertexContainer< Number >::set (const Point< Number > & p, bool c) inline
Definition at line 246 of file VertexContainer.h.
References hypro::VertexContainer< Number >::insert().
template<typename Number> std::size_t hypro::VertexContainer< Number >::size () const inline
Definition at line 57 of file VertexContainer.h.
template<typename Number> std::vector<carl::Variable> hypro::VertexContainer< Number >::variables () const inline
Definition at line 52 of file VertexContainer.h.
template<typename Number> vSet<Number> hypro::VertexContainer< Number >::vertices () const inline
Definition at line 63 of file VertexContainer.h.
Referenced by hypro::VertexContainer< Number >::getHash(), and std::hash< hypro::VertexContainer< Number > >::operator()().
Friends And Related Function Documentation
template<typename Number> bool operator!= (const VertexContainer< Number > & c1, const VertexContainer< Number > & c2) friend
Parameters
c1
c2
Returns
true, if they are not equal.
Definition at line 286 of file VertexContainer.h.
template<typename Number> std::ostream& operator<< (std::ostream & ostr, const VertexContainer< Number > & cont) friend
Definition at line 297 of file VertexContainer.h.
template<typename Number> bool operator== (const VertexContainer< Number > & c1, const VertexContainer< Number > & c2) friend
Parameters
c1
c2
Returns
true, if they are equal.
Definition at line 272 of file VertexContainer.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/VertexContainer.h