HyPro: hypro::TrafoOp< Number, Converter, Setting > Class Template Reference
hypro::TrafoOp< Number, Converter, Setting > Class Template Reference
#include <TrafoOp.h>
Public Member Functions
TrafoOp ()=delete
TrafoOp (const SupportFunctionNewT< Number, Converter, Setting > &origin, const matrix_t< Number > &A, const vector_t< Number > &b)
TrafoOp (const TrafoData< Number, Setting > &d)
~TrafoOp ()
SFNEW_TYPE getType () const override
unsigned getOriginCount () const override
std::size_t getDimension () const override
unsigned getCurrentExponent () const
std::size_t getSuccessiveTransformations () const
const std::shared_ptr< const LinTrafoParameters< Number, Setting > > & getParameters () const
RGNData * getData () const override
void setDimension (const std::size_t d) override
matrix_t< Number > transform (const matrix_t< Number > &param) const override
std::vector< EvaluationResult< Number > > compute (const matrix_t< Number > &, bool) const override
std::vector< EvaluationResult< Number > > aggregate (std::vector< std::vector< EvaluationResult< Number >>> &resultStackBack, const matrix_t< Number > &currentParam) const override
bool empty (const std::vector< bool > &childrenEmpty) const override
Point< Number > supremumPoint (std::vector< Point< Number >> &points) const override
vector_t< Number > reverseOp (const vector_t< Number > &point) const override
bool contains (const std::vector< bool > &v, const vector_t< Number > &) const override
bool hasTrafo (std::shared_ptr< const LinTrafoParameters< Number, Setting >> &ltParam, const matrix_t< Number > &A, const vector_t< Number > &b)
Public Member Functions inherited from hypro::RootGrowNode< Number, Converter, Setting >
RootGrowNode ()
virtual ~RootGrowNode ()
virtual PointerVec getChildren () const
virtual PointerVec & rGetChildren ()
virtual SETSTATE isEmpty () const
virtual LeafData getLeafData () const
void addToChildren (const std::shared_ptr< RootGrowNode > &rhs)
void clearChildren ()
virtual void print (std::ostream &ostr) const
virtual bool empty () const
virtual Point< Number > supremumPoint () const
virtual bool contains (const vector_t< Number > &) const
virtual std::vector< std::size_t > intersectDims (const std::vector< std::vector< std::size_t >> &dims) const
Private Types
using PointerVec = typename RootGrowNode< Number, Converter, Setting >::PointerVec
Private Attributes
SFNEW_TYPE type = SFNEW_TYPE::TRAFO
unsigned originCount
PointerVec mChildren
std::size_t mDimension
unsigned currentExponent
std::size_t successiveTransformations
std::shared_ptr< const LinTrafoParameters< Number, Setting > > parameters
Additional Inherited Members
Public Types inherited from hypro::RootGrowNode< Number, Converter, Setting >
using PointerVec = std::vector< std::shared_ptr< RootGrowNode< Number, Converter, Setting >>>
Protected Attributes inherited from hypro::RootGrowNode< Number, Converter, Setting >
SFNEW_TYPE mType = NODE
unsigned originCount = 0
PointerVec mChildren = PointerVec()
std::size_t mDimension = 0
SETSTATE mEmptyState = SETSTATE::UNKNOWN
Detailed Description
template<typename Number, typename Converter, typename Setting>
class hypro::TrafoOp< Number, Converter, Setting >
Definition at line 48 of file TrafoOp.h.
Member Typedef Documentation
template<typename Number , typename Converter , typename Setting > using hypro::TrafoOp< Number, Converter, Setting >::PointerVec = typename RootGrowNode<Number, Converter, Setting>::PointerVec private
Definition at line 49 of file TrafoOp.h.
Constructor & Destructor Documentation
template<typename Number , typename Converter , typename Setting > hypro::TrafoOp< Number, Converter, Setting >::TrafoOp () delete
template<typename Number , typename Converter , typename Setting > hypro::TrafoOp< Number, Converter, Setting >::TrafoOp (const SupportFunctionNewT< Number, Converter, Setting > & origin, const matrix_t< Number > & A, const vector_t< Number > & b) inline
Definition at line 74 of file TrafoOp.h.
References A, hypro::SupportFunctionNewT< Number, Converter, Setting >::addOperation(), assert(), b, hypro::TrafoData< Number, Setting >::currentExponent, hypro::TrafoOp< Number, Converter, Setting >::getSuccessiveTransformations(), hypro::detail::getType(), hypro::SupportFunctionNewT< Number, Converter, Setting >::hasTrafo(), i, size, and hypro::TRAFO.
template<typename Number , typename Converter , typename Setting > hypro::TrafoOp< Number, Converter, Setting >::TrafoOp (const TrafoData< Number, Setting > & d) inline
Definition at line 123 of file TrafoOp.h.
References hypro::TrafoData< Number, Setting >::currentExponent, d, hypro::TrafoData< Number, Setting >::parameters, and hypro::TrafoData< Number, Setting >::successiveTransformations.
template<typename Number , typename Converter , typename Setting > hypro::TrafoOp< Number, Converter, Setting >::~TrafoOp () inline
Definition at line 131 of file TrafoOp.h.
Member Function Documentation
template<typename Number , typename Converter , typename Setting > std::vector<EvaluationResult<Number> > hypro::TrafoOp< Number, Converter, Setting >::aggregate (std::vector< std::vector< EvaluationResult< Number >>> & resultStackBack, const matrix_t< Number > & currentParam) const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 159 of file TrafoOp.h.
References assert(), hypro::INFEAS, and hypro::INFTY.
template<typename Number , typename Converter , typename Setting > std::vector<EvaluationResult<Number> > hypro::TrafoOp< Number, Converter, Setting >::compute (const matrix_t< Number > & , bool) const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 152 of file TrafoOp.h.
References assert().
template<typename Number , typename Converter , typename Setting > bool hypro::TrafoOp< Number, Converter, Setting >::contains (const std::vector< bool > & v, const vector_t< Number > &) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 234 of file TrafoOp.h.
References assert().
template<typename Number , typename Converter , typename Setting > bool hypro::TrafoOp< Number, Converter, Setting >::empty (const std::vector< bool > & childrenEmpty) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 212 of file TrafoOp.h.
References assert().
template<typename Number , typename Converter , typename Setting > unsigned hypro::TrafoOp< Number, Converter, Setting >::getCurrentExponent () const inline
Definition at line 138 of file TrafoOp.h.
References hypro::TrafoData< Number, Setting >::currentExponent.
template<typename Number , typename Converter , typename Setting > RGNData* hypro::TrafoOp< Number, Converter, Setting >::getData () const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 141 of file TrafoOp.h.
References hypro::TrafoData< Number, Setting >::currentExponent, hypro::TrafoData< Number, Setting >::parameters, and hypro::TrafoData< Number, Setting >::successiveTransformations.
template<typename Number , typename Converter , typename Setting > std::size_t hypro::TrafoOp< Number, Converter, Setting >::getDimension () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 137 of file TrafoOp.h.
template<typename Number , typename Converter , typename Setting > unsigned hypro::TrafoOp< Number, Converter, Setting >::getOriginCount () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 136 of file TrafoOp.h.
template<typename Number , typename Converter , typename Setting > const std::shared_ptr<const LinTrafoParameters<Number, Setting> >& hypro::TrafoOp< Number, Converter, Setting >::getParameters () const inline
Definition at line 140 of file TrafoOp.h.
References hypro::TrafoData< Number, Setting >::parameters.
template<typename Number , typename Converter , typename Setting > std::size_t hypro::TrafoOp< Number, Converter, Setting >::getSuccessiveTransformations () const inline
Definition at line 139 of file TrafoOp.h.
References hypro::TrafoData< Number, Setting >::successiveTransformations.
Referenced by hypro::TrafoOp< Number, Converter, Setting >::TrafoOp().
template<typename Number , typename Converter , typename Setting > SFNEW_TYPE hypro::TrafoOp< Number, Converter, Setting >::getType () const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 135 of file TrafoOp.h.
References type.
template<typename Number , typename Converter , typename Setting > bool hypro::TrafoOp< Number, Converter, Setting >::hasTrafo (std::shared_ptr< const LinTrafoParameters< Number, Setting >> & ltParam, const matrix_t< Number > & A, const vector_t< Number > & b) inline
Definition at line 240 of file TrafoOp.h.
References hypro::TrafoData< Number, Setting >::parameters.
template<typename Number , typename Converter , typename Setting > vector_t<Number> hypro::TrafoOp< Number, Converter, Setting >::reverseOp (const vector_t< Number > & point) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 227 of file TrafoOp.h.
References point, and tmp.
template<typename Number , typename Converter , typename Setting > void hypro::TrafoOp< Number, Converter, Setting >::setDimension (const std::size_t d) inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 142 of file TrafoOp.h.
References d.
template<typename Number , typename Converter , typename Setting > Point<Number> hypro::TrafoOp< Number, Converter, Setting >::supremumPoint (std::vector< Point< Number >> & points) const inline override virtual
Reimplemented from hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 219 of file TrafoOp.h.
References assert(), and points.
template<typename Number , typename Converter , typename Setting > matrix_t<Number> hypro::TrafoOp< Number, Converter, Setting >::transform (const matrix_t< Number > & param) const inline override virtual
Implements hypro::RootGrowNode< Number, Converter, Setting >.
Definition at line 147 of file TrafoOp.h.
Member Data Documentation
template<typename Number , typename Converter , typename Setting > unsigned hypro::TrafoOp< Number, Converter, Setting >::currentExponent private
Definition at line 61 of file TrafoOp.h.
template<typename Number , typename Converter , typename Setting > PointerVec hypro::TrafoOp< Number, Converter, Setting >::mChildren private
Definition at line 56 of file TrafoOp.h.
template<typename Number , typename Converter , typename Setting > std::size_t hypro::TrafoOp< Number, Converter, Setting >::mDimension private
Definition at line 57 of file TrafoOp.h.
template<typename Number , typename Converter , typename Setting > unsigned hypro::TrafoOp< Number, Converter, Setting >::originCount private
Definition at line 55 of file TrafoOp.h.
template<typename Number , typename Converter , typename Setting > std::shared_ptr<const LinTrafoParameters<Number, Setting> > hypro::TrafoOp< Number, Converter, Setting >::parameters private
Definition at line 63 of file TrafoOp.h.
template<typename Number , typename Converter , typename Setting > std::size_t hypro::TrafoOp< Number, Converter, Setting >::successiveTransformations private
Definition at line 62 of file TrafoOp.h.
template<typename Number , typename Converter , typename Setting > SFNEW_TYPE hypro::TrafoOp< Number, Converter, Setting >::type = SFNEW_TYPE::TRAFO private
Definition at line 54 of file TrafoOp.h.
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunctionNew/TrafoOp.h