HyPro: hypro::RectangularContext< State > Class Template Reference
hypro::RectangularContext< State > Class Template Reference
Public Member Functions
RectangularContext ()=delete
~RectangularContext ()
RectangularContext (const TaskType &t, const Strategy< State > &strat, WorkQueue< TaskType > *localQueue, WorkQueue< TaskType > *localCEXQueue, Flowpipe< State > &localSegments, ReachabilitySettings &settings)
virtual void execOnStart () override
virtual void execBeforeFirstSegment () override
virtual void firstSegment () override
virtual void execAfterFirstSegment () override
virtual void checkInvariant () override
virtual void intersectBadStates () override
virtual void execBeforeLoop () override
virtual bool doneCondition () override
virtual void checkTransition () override
virtual void applyContinuousEvolution () override
virtual void execOnLoopItExit () override
virtual void processDiscreteBehavior () override
virtual void execOnEnd () override
void initalizeFirstSegmentHandlers ()
void initializeInvariantHandlers ()
void initializeBadStateHandlers ()
void initializeGuardHandlers ()
void applyBacktracking ()
bool omitTransition (Transition< Number > *transition)
bool omitInvariant ()
bool omitBadStateCheck ()
Public Member Functions inherited from hypro::IContext
virtual void execBeforeCheckInvariant ()
virtual void execAfterCheckInvariant ()
virtual void execBeforeIntersectBadStates ()
virtual void execAfterIntersectBadStates ()
virtual void execOnLoopItEnter ()
virtual void execBeforeCheckTransition ()
virtual void execAfterCheckTransition ()
virtual void execBeforeContinuousEvolution ()
virtual void execAfterContinuousEvolution ()
virtual void execAfterLoop ()
virtual void execBeforeProcessDiscreteBehavior ()
virtual void execAfterProcessDiscreteBehavior ()
Protected Attributes
std::shared_ptr< Task< State > > mTask
Strategy< State > mStrategy
WorkQueue< TaskType > * mLocalQueue
WorkQueue< TaskType > * mLocalCEXQueue
Flowpipe< State > & mLocalSegments
ReachabilitySettings mSettings
EventTimingContainer< Number > mLocalTimings
HierarchicalIntervalVector< CONTAINMENT, tNumber > mTransitionTimings
std::vector< std::tuple< Transition< Number > *, State > > mDiscreteSuccessorBuffer
std::map< Transition< Number > *, State > mPotentialZenoTransitions
std::vector< Transition< Number > * > mDisabledTransitions
tNumber mCurrentLocalTime
carl::Interval< tNumber > mCurrentGlobalTimeInterval
carl::Interval< tNumber > mCurrentTimeInterval
State mCurrentSegment
std::vector< IFirstSegmentHandler< State > * > mFirstSegmentHandlers
std::vector< IInvariantHandler * > mInvariantHandlers
std::vector< IBadStateHandler * > mBadStateHandlers
std::vector< ITimeEvolutionHandler * > mContinuousEvolutionHandlers
std::map< Transition< Number > *, std::vector< IGuardHandler< State > * > > mTransitionHandlerMap
Detailed Description
template<typename State>
class hypro::RectangularContext< State >
Definition at line 25 of file RectangularContext.h.
Constructor & Destructor Documentation
template<typename State > hypro::RectangularContext< State >::RectangularContext () delete
Referenced by hypro::RectangularContext< State >::~RectangularContext().
template<typename State > hypro::RectangularContext< State >::~RectangularContext () inline
Definition at line 63 of file RectangularContext.h.
References hypro::RectangularContext< State >::applyBacktracking(), hypro::RectangularContext< State >::applyContinuousEvolution(), hypro::RectangularContext< State >::checkInvariant(), hypro::RectangularContext< State >::checkTransition(), hypro::RectangularContext< State >::doneCondition(), hypro::RectangularContext< State >::execAfterFirstSegment(), hypro::RectangularContext< State >::execBeforeFirstSegment(), hypro::RectangularContext< State >::execBeforeLoop(), hypro::RectangularContext< State >::execOnEnd(), hypro::RectangularContext< State >::execOnLoopItExit(), hypro::RectangularContext< State >::execOnStart(), hypro::RectangularContext< State >::firstSegment(), hypro::RectangularContext< State >::initalizeFirstSegmentHandlers(), hypro::RectangularContext< State >::initializeBadStateHandlers(), hypro::RectangularContext< State >::initializeGuardHandlers(), hypro::RectangularContext< State >::initializeInvariantHandlers(), hypro::RectangularContext< State >::intersectBadStates(), hypro::RectangularContext< State >::omitBadStateCheck(), hypro::RectangularContext< State >::omitInvariant(), hypro::RectangularContext< State >::omitTransition(), hypro::RectangularContext< State >::processDiscreteBehavior(), and hypro::RectangularContext< State >::RectangularContext().
template<typename State > hypro::RectangularContext< State >::RectangularContext (const TaskType & t, const Strategy< State > & strat, WorkQueue< TaskType > * localQueue, WorkQueue< TaskType > * localCEXQueue, Flowpipe< State > & localSegments, ReachabilitySettings & settings)
Member Function Documentation
template<typename State > void hypro::RectangularContext< State >::applyBacktracking ()
Definition at line 81 of file RectangularContext.tpp.
References hypro::TreeNode< ReachTreeNode< State > >::getDepth(), hypro::SettingsProvider< State >::getGlobalTimeHorizon(), hypro::ReachTreeNode< State >::getMutex(), hypro::TreeNode< ReachTreeNode< State > >::getParent(), hypro::ReachTreeNode< State >::getRefinements(), hypro::ReachTreeNode< State >::getStateAtLevel(), hypro::RefinementSetting< State >::initialSet, hypro::RectangularContext< State >::mLocalCEXQueue, hypro::RectangularContext< State >::mStrategy, hypro::RectangularContext< State >::mTask, hypro::ReachTreeNode< State >::setNewRefinement(), and hypro::ReachTreeNode< State >::setTimestamp().
Referenced by hypro::RectangularContext< State >::intersectBadStates(), and hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::applyContinuousEvolution () override virtual
Implements hypro::IContext.
Definition at line 680 of file RectangularContext.tpp.
References hypro::RectangularContext< State >::mContinuousEvolutionHandlers, hypro::RectangularContext< State >::mCurrentSegment, hypro::RectangularContext< State >::mStrategy, and hypro::RectangularContext< State >::mTask.
Referenced by hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::checkInvariant () override virtual
Implements hypro::IContext.
Definition at line 369 of file RectangularContext.tpp.
References hypro::FULL, hypro::RectangularContext< State >::mCurrentSegment, hypro::RectangularContext< State >::mInvariantHandlers, hypro::RectangularContext< State >::mLocalSegments, hypro::RectangularContext< State >::mLocalTimings, hypro::RectangularContext< State >::mSettings, hypro::RectangularContext< State >::mTask, hypro::NO, hypro::RectangularContext< State >::omitInvariant(), hypro::PARTIAL, and hypro::ReachabilitySettings::useInvariantTimingInformation.
Referenced by hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::checkTransition () override virtual
Implements hypro::IContext.
Definition at line 548 of file RectangularContext.tpp.
References hypro::ReachabilitySettings::jumpDepth, hypro::RectangularContext< State >::mCurrentSegment, hypro::RectangularContext< State >::mDisabledTransitions, hypro::RectangularContext< State >::mDiscreteSuccessorBuffer, hypro::RectangularContext< State >::mLocalTimings, hypro::RectangularContext< State >::mSettings, hypro::RectangularContext< State >::mTask, hypro::RectangularContext< State >::mTransitionHandlerMap, hypro::NO, hypro::RectangularContext< State >::omitTransition(), hypro::ReachabilitySettings::useGuardTimingInformation, and hypro::YES.
Referenced by hypro::RectangularContext< State >::~RectangularContext().
template<typename State > bool hypro::RectangularContext< State >::doneCondition () override virtual
Implements hypro::IContext.
Definition at line 542 of file RectangularContext.tpp.
References hypro::RectangularContext< State >::mContinuousEvolutionHandlers, hypro::RectangularContext< State >::mCurrentLocalTime, hypro::RectangularContext< State >::mSettings, and hypro::ReachabilitySettings::timeBound.
Referenced by hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::execAfterFirstSegment () override virtual
Reimplemented from hypro::IContext.
Definition at line 350 of file RectangularContext.tpp.
References hypro::RectangularContext< State >::mCurrentGlobalTimeInterval, hypro::RectangularContext< State >::mCurrentLocalTime, hypro::RectangularContext< State >::mCurrentSegment, hypro::RectangularContext< State >::mCurrentTimeInterval, hypro::RectangularContext< State >::mStrategy, and hypro::RectangularContext< State >::mTask.
Referenced by hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::execBeforeFirstSegment () override virtual
Reimplemented from hypro::IContext.
Definition at line 238 of file RectangularContext.tpp.
References hypro::Path< Number, tNumber >::addTimeStep(), hypro::Path< Number, tNumber >::addTransition(), hypro::HandlerFactory< State >::buildGuardHandler(), hypro::IGuardHandler< State >::handlerName(), hypro::Path< Number, tNumber >::hasChatteringZeno(), hypro::ReachabilitySettings::jumpDepth, hypro::RectangularContext< State >::mCurrentSegment, hypro::RectangularContext< State >::mDiscreteSuccessorBuffer, hypro::RectangularContext< State >::mLocalTimings, hypro::RectangularContext< State >::mPotentialZenoTransitions, hypro::RectangularContext< State >::mSettings, hypro::RectangularContext< State >::mTask, and hypro::EventTimingProvider< Number >::updateTimings().
Referenced by hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::execBeforeLoop () override virtual
Reimplemented from hypro::IContext.
Definition at line 487 of file RectangularContext.tpp.
References hypro::HandlerFactory< State >::buildContinuousEvolutionHandler(), hypro::HandlerFactory< State >::buildGuardHandler(), hypro::ITimeEvolutionHandler::handlerName(), hypro::RectangularContext< State >::initializeGuardHandlers(), hypro::RectangularContext< State >::mContinuousEvolutionHandlers, hypro::RectangularContext< State >::mCurrentSegment, hypro::RectangularContext< State >::mDisabledTransitions, hypro::RectangularContext< State >::mFirstSegmentHandlers, hypro::RectangularContext< State >::mPotentialZenoTransitions, hypro::RectangularContext< State >::mSettings, hypro::RectangularContext< State >::mStrategy, hypro::RectangularContext< State >::mTask, and hypro::ReachabilitySettings::timeBound.
Referenced by hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::execOnEnd () override virtual
Reimplemented from hypro::IContext.
Definition at line 815 of file RectangularContext.tpp.
References hypro::RefinementSetting< State >::fullyComputed, hypro::RectangularContext< State >::mLocalTimings, hypro::RectangularContext< State >::mSettings, hypro::RectangularContext< State >::mTask, hypro::EventTimingProvider< Number >::rGetNode(), hypro::ReachabilitySettings::useBadStateTimingInformation, hypro::ReachabilitySettings::useGuardTimingInformation, and hypro::ReachabilitySettings::useInvariantTimingInformation.
Referenced by hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::execOnLoopItExit () override virtual
Reimplemented from hypro::IContext.
Definition at line 702 of file RectangularContext.tpp.
References hypro::RectangularContext< State >::mCurrentGlobalTimeInterval, hypro::RectangularContext< State >::mCurrentLocalTime, hypro::RectangularContext< State >::mCurrentTimeInterval, hypro::RectangularContext< State >::mStrategy, and hypro::RectangularContext< State >::mTask.
Referenced by hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::execOnStart () override virtual
Reimplemented from hypro::IContext.
Definition at line 172 of file RectangularContext.tpp.
References hypro::EventTimingProvider< Number >::getTimings(), hypro::RectangularContext< State >::initalizeFirstSegmentHandlers(), hypro::RectangularContext< State >::mLocalQueue, hypro::RectangularContext< State >::mLocalTimings, hypro::RectangularContext< State >::mSettings, hypro::RectangularContext< State >::mStrategy, hypro::RectangularContext< State >::mTask, hypro::EventTimingProvider< Number >::rGetNode(), hypro::ReachabilitySettings::useBadStateTimingInformation, hypro::ReachabilitySettings::useGuardTimingInformation, and hypro::ReachabilitySettings::useInvariantTimingInformation.
Referenced by hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::firstSegment () override virtual
Implements hypro::IContext.
Definition at line 336 of file RectangularContext.tpp.
References hypro::RectangularContext< State >::initializeBadStateHandlers(), hypro::RectangularContext< State >::initializeInvariantHandlers(), hypro::RectangularContext< State >::mCurrentSegment, and hypro::RectangularContext< State >::mFirstSegmentHandlers.
Referenced by hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::initalizeFirstSegmentHandlers ()
Definition at line 23 of file RectangularContext.tpp.
References hypro::RectangularContext< State >::mCurrentSegment, and hypro::RectangularContext< State >::mFirstSegmentHandlers.
Referenced by hypro::RectangularContext< State >::execOnStart(), and hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::initializeBadStateHandlers ()
Definition at line 44 of file RectangularContext.tpp.
References hypro::getFlowType(), hypro::RectangularContext< State >::mBadStateHandlers, hypro::RectangularContext< State >::mCurrentSegment, hypro::RectangularContext< State >::mFirstSegmentHandlers, and hypro::rectangular.
Referenced by hypro::RectangularContext< State >::firstSegment(), and hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::initializeGuardHandlers ()
Definition at line 55 of file RectangularContext.tpp.
References hypro::getFlowType(), hypro::IGuardHandler< State >::handlerName(), hypro::RectangularContext< State >::mCurrentSegment, hypro::RectangularContext< State >::mFirstSegmentHandlers, hypro::RectangularContext< State >::mTask, hypro::RectangularContext< State >::mTransitionHandlerMap, and hypro::rectangular.
Referenced by hypro::RectangularContext< State >::execBeforeLoop(), and hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::initializeInvariantHandlers ()
Definition at line 33 of file RectangularContext.tpp.
References hypro::getFlowType(), hypro::RectangularContext< State >::mCurrentSegment, hypro::RectangularContext< State >::mFirstSegmentHandlers, hypro::RectangularContext< State >::mInvariantHandlers, and hypro::rectangular.
Referenced by hypro::RectangularContext< State >::firstSegment(), and hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::intersectBadStates () override virtual
Implements hypro::IContext.
Definition at line 429 of file RectangularContext.tpp.
References hypro::RectangularContext< State >::applyBacktracking(), hypro::RectangularContext< State >::mBadStateHandlers, hypro::RectangularContext< State >::mCurrentSegment, hypro::RectangularContext< State >::mLocalTimings, hypro::RectangularContext< State >::mSettings, hypro::RectangularContext< State >::mTask, hypro::NO, hypro::RectangularContext< State >::omitBadStateCheck(), hypro::EventTimingProvider< Number >::updateTimings(), hypro::ReachabilitySettings::useBadStateTimingInformation, hypro::ReachabilitySettings::useGuardTimingInformation, hypro::ReachabilitySettings::useInvariantTimingInformation, and hypro::YES.
Referenced by hypro::RectangularContext< State >::~RectangularContext().
template<typename State > bool hypro::RectangularContext< State >::omitBadStateCheck ()
Definition at line 794 of file RectangularContext.tpp.
References hypro::RectangularContext< State >::mCurrentSegment, hypro::RectangularContext< State >::mLocalTimings, hypro::RectangularContext< State >::mSettings, hypro::NO, and hypro::ReachabilitySettings::useBadStateTimingInformation.
Referenced by hypro::RectangularContext< State >::intersectBadStates(), and hypro::RectangularContext< State >::~RectangularContext().
template<typename State > bool hypro::RectangularContext< State >::omitInvariant ()
Definition at line 773 of file RectangularContext.tpp.
References hypro::FULL, hypro::RectangularContext< State >::mCurrentSegment, hypro::RectangularContext< State >::mLocalTimings, hypro::RectangularContext< State >::mSettings, and hypro::ReachabilitySettings::useInvariantTimingInformation.
Referenced by hypro::RectangularContext< State >::checkInvariant(), and hypro::RectangularContext< State >::~RectangularContext().
template<typename State > bool hypro::RectangularContext< State >::omitTransition (Transition< Number > * transition)
Definition at line 719 of file RectangularContext.tpp.
References hypro::Transition< Number >::getSource(), hypro::Transition< Number >::getTarget(), hypro::RectangularContext< State >::mCurrentSegment, hypro::RectangularContext< State >::mLocalTimings, hypro::RectangularContext< State >::mSettings, hypro::RectangularContext< State >::mTask, and hypro::ReachabilitySettings::useGuardTimingInformation.
Referenced by hypro::RectangularContext< State >::checkTransition(), and hypro::RectangularContext< State >::~RectangularContext().
template<typename State > void hypro::RectangularContext< State >::processDiscreteBehavior () override virtual
Implements hypro::IContext.
Definition at line 709 of file RectangularContext.tpp.
References hypro::HandlerFactory< State >::buildDiscreteSuccessorHandler(), hypro::IJumpHandler::handle(), hypro::IJumpHandler::handlerName(), hypro::RectangularContext< State >::mDiscreteSuccessorBuffer, hypro::RectangularContext< State >::mLocalCEXQueue, hypro::RectangularContext< State >::mLocalQueue, hypro::RectangularContext< State >::mLocalTimings, hypro::RectangularContext< State >::mStrategy, and hypro::RectangularContext< State >::mTask.
Referenced by hypro::RectangularContext< State >::~RectangularContext().
Member Data Documentation
template<typename State > std::vector<IBadStateHandler*> hypro::RectangularContext< State >::mBadStateHandlers protected
Definition at line 56 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::initializeBadStateHandlers(), and hypro::RectangularContext< State >::intersectBadStates().
template<typename State > std::vector<ITimeEvolutionHandler*> hypro::RectangularContext< State >::mContinuousEvolutionHandlers protected
Definition at line 57 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::applyContinuousEvolution(), hypro::RectangularContext< State >::doneCondition(), and hypro::RectangularContext< State >::execBeforeLoop().
template<typename State > carl::Interval<tNumber> hypro::RectangularContext< State >::mCurrentGlobalTimeInterval protected
Definition at line 46 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::execAfterFirstSegment(), and hypro::RectangularContext< State >::execOnLoopItExit().
template<typename State > tNumber hypro::RectangularContext< State >::mCurrentLocalTime protected
Definition at line 45 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::doneCondition(), hypro::RectangularContext< State >::execAfterFirstSegment(), and hypro::RectangularContext< State >::execOnLoopItExit().
template<typename State > State hypro::RectangularContext< State >::mCurrentSegment protected
Definition at line 50 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::applyContinuousEvolution(), hypro::RectangularContext< State >::checkInvariant(), hypro::RectangularContext< State >::checkTransition(), hypro::RectangularContext< State >::execAfterFirstSegment(), hypro::RectangularContext< State >::execBeforeFirstSegment(), hypro::RectangularContext< State >::execBeforeLoop(), hypro::RectangularContext< State >::firstSegment(), hypro::RectangularContext< State >::initalizeFirstSegmentHandlers(), hypro::RectangularContext< State >::initializeBadStateHandlers(), hypro::RectangularContext< State >::initializeGuardHandlers(), hypro::RectangularContext< State >::initializeInvariantHandlers(), hypro::RectangularContext< State >::intersectBadStates(), hypro::RectangularContext< State >::omitBadStateCheck(), hypro::RectangularContext< State >::omitInvariant(), and hypro::RectangularContext< State >::omitTransition().
template<typename State > carl::Interval<tNumber> hypro::RectangularContext< State >::mCurrentTimeInterval protected
Definition at line 47 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::execAfterFirstSegment(), and hypro::RectangularContext< State >::execOnLoopItExit().
template<typename State > std::vector<Transition<Number>*> hypro::RectangularContext< State >::mDisabledTransitions protected
Definition at line 43 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::checkTransition(), and hypro::RectangularContext< State >::execBeforeLoop().
template<typename State > std::vector<std::tuple<Transition<Number>*, State> > hypro::RectangularContext< State >::mDiscreteSuccessorBuffer protected
Definition at line 40 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::checkTransition(), hypro::RectangularContext< State >::execBeforeFirstSegment(), and hypro::RectangularContext< State >::processDiscreteBehavior().
template<typename State > std::vector<IFirstSegmentHandler<State>*> hypro::RectangularContext< State >::mFirstSegmentHandlers protected
Definition at line 54 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::execBeforeLoop(), hypro::RectangularContext< State >::firstSegment(), hypro::RectangularContext< State >::initalizeFirstSegmentHandlers(), hypro::RectangularContext< State >::initializeBadStateHandlers(), hypro::RectangularContext< State >::initializeGuardHandlers(), and hypro::RectangularContext< State >::initializeInvariantHandlers().
template<typename State > std::vector<IInvariantHandler*> hypro::RectangularContext< State >::mInvariantHandlers protected
Definition at line 55 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::checkInvariant(), and hypro::RectangularContext< State >::initializeInvariantHandlers().
template<typename State > WorkQueue<TaskType>* hypro::RectangularContext< State >::mLocalCEXQueue protected
Definition at line 33 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::applyBacktracking(), and hypro::RectangularContext< State >::processDiscreteBehavior().
template<typename State > WorkQueue<TaskType>* hypro::RectangularContext< State >::mLocalQueue protected
Definition at line 32 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::execOnStart(), and hypro::RectangularContext< State >::processDiscreteBehavior().
template<typename State > Flowpipe<State>& hypro::RectangularContext< State >::mLocalSegments protected
Definition at line 34 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::checkInvariant().
template<typename State > EventTimingContainer<Number> hypro::RectangularContext< State >::mLocalTimings protected
Definition at line 37 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::checkInvariant(), hypro::RectangularContext< State >::checkTransition(), hypro::RectangularContext< State >::execBeforeFirstSegment(), hypro::RectangularContext< State >::execOnEnd(), hypro::RectangularContext< State >::execOnStart(), hypro::RectangularContext< State >::intersectBadStates(), hypro::RectangularContext< State >::omitBadStateCheck(), hypro::RectangularContext< State >::omitInvariant(), hypro::RectangularContext< State >::omitTransition(), and hypro::RectangularContext< State >::processDiscreteBehavior().
template<typename State > std::map<Transition<Number>*, State> hypro::RectangularContext< State >::mPotentialZenoTransitions protected
Definition at line 42 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::execBeforeFirstSegment(), and hypro::RectangularContext< State >::execBeforeLoop().
template<typename State > ReachabilitySettings hypro::RectangularContext< State >::mSettings protected
Definition at line 35 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::checkInvariant(), hypro::RectangularContext< State >::checkTransition(), hypro::RectangularContext< State >::doneCondition(), hypro::RectangularContext< State >::execBeforeFirstSegment(), hypro::RectangularContext< State >::execBeforeLoop(), hypro::RectangularContext< State >::execOnEnd(), hypro::RectangularContext< State >::execOnStart(), hypro::RectangularContext< State >::intersectBadStates(), hypro::RectangularContext< State >::omitBadStateCheck(), hypro::RectangularContext< State >::omitInvariant(), and hypro::RectangularContext< State >::omitTransition().
template<typename State > Strategy<State> hypro::RectangularContext< State >::mStrategy protected
Definition at line 31 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::applyBacktracking(), hypro::RectangularContext< State >::applyContinuousEvolution(), hypro::RectangularContext< State >::execAfterFirstSegment(), hypro::RectangularContext< State >::execBeforeLoop(), hypro::RectangularContext< State >::execOnLoopItExit(), hypro::RectangularContext< State >::execOnStart(), and hypro::RectangularContext< State >::processDiscreteBehavior().
template<typename State > std::shared_ptr<Task<State> > hypro::RectangularContext< State >::mTask protected
Definition at line 30 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::applyBacktracking(), hypro::RectangularContext< State >::applyContinuousEvolution(), hypro::RectangularContext< State >::checkInvariant(), hypro::RectangularContext< State >::checkTransition(), hypro::RectangularContext< State >::execAfterFirstSegment(), hypro::RectangularContext< State >::execBeforeFirstSegment(), hypro::RectangularContext< State >::execBeforeLoop(), hypro::RectangularContext< State >::execOnEnd(), hypro::RectangularContext< State >::execOnLoopItExit(), hypro::RectangularContext< State >::execOnStart(), hypro::RectangularContext< State >::initializeGuardHandlers(), hypro::RectangularContext< State >::intersectBadStates(), hypro::RectangularContext< State >::omitTransition(), and hypro::RectangularContext< State >::processDiscreteBehavior().
template<typename State > std::map<Transition<Number>*, std::vector<IGuardHandler<State>*> > hypro::RectangularContext< State >::mTransitionHandlerMap protected
Definition at line 59 of file RectangularContext.h.
Referenced by hypro::RectangularContext< State >::checkTransition(), and hypro::RectangularContext< State >::initializeGuardHandlers().
template<typename State > HierarchicalIntervalVector<CONTAINMENT, tNumber> hypro::RectangularContext< State >::mTransitionTimings protected
Definition at line 38 of file RectangularContext.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/contexts/RectangularContext.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/contexts/RectangularContext.tpp