HyPro: hypro::HybridAutomaton< Number > Class Template Reference
hypro::HybridAutomaton< Number > Class Template Reference
Class for linear hybrid automata.
Public Types
using locationVector = std::vector< std::unique_ptr< Location< Number >>>
using locationConditionMap = std::map< const Location< Number > *, Condition< Number >>
using conditionVector = std::vector< Condition< Number >>
using variableVector = std::vector< std::string >
Public Member Functions
HybridAutomaton ()
Default constructor.
HybridAutomaton (const HybridAutomaton< Number > &hybrid)
Copy constructor.
HybridAutomaton (const locationVector &locs, const locationConditionMap &initialStates)
Move constructor.
virtual ~HybridAutomaton ()
Destructor.
HybridAutomaton & operator= (const HybridAutomaton< Number > &rhs)
Copy Assignment.
HybridAutomaton & operator= (HybridAutomaton< Number > &&rhs)
Move Assignment.
void decompose (const Decomposition &decomposition)
Decomposes an automaton into the components defined by decomposition. The vector should contain sets of variables that are at least syntactically independet to each other.
void reduce ()
Reduces the automaton, i.e. removes Locations which are not connected to the automaton by transitions.
bool isComposedOf (const HybridAutomaton< Number > &rhs) const
Function which tests whether this can be the result of a parallel composition with rhs.
std::string getDotRepresentation () const
std::string getStatistics () const
template<typename T >
bool equals (const std::vector< T * > &lhs, const std::vector< T * > &rhs) const
std::vector< Location< Number > * > getLocations () const
Getter function.
Location< Number > * getLocation (const std::size_t hash) const
Getter function.
Location< Number > * getLocation (const std::string &name) const
Getter function.
std::vector< Transition< Number > * > getTransitions () const
Getter function.
const locationConditionMap & getInitialStates () const
Getter function.
const locationConditionMap & getLocalBadStates () const
Getter function.
const conditionVector & getGlobalBadStates () const
Getter function.
unsigned dimension () const
Getter function.
const variableVector & getVariables () const
Getter function.
const std::set< Label > getLabels () const
Getter function.
void setLocations (locationVector &&locs)
Setter function.
void setInitialStates (const locationConditionMap &states)
Setter function.
void setLocalBadStates (const locationConditionMap &states)
Setter function.
void setGlobalBadStates (const conditionVector &states)
Setter function.
void setVariables (const variableVector &variables)
Setter function.
const std::unique_ptr< Location< Number > > & addLocation (const Location< Number > &location)
Extension function.
const std::unique_ptr< Location< Number > > & addLocation (std::unique_ptr< Location< Number >> &&location)
Extension function.
void addTransition (std::unique_ptr< Transition< Number >> &&transition)
Extension function.
void addInitialState (const Location< Number > *loc, const Condition< Number > &state)
Extension function.
void addLocalBadState (const Location< Number > *loc, const Condition< Number > &condition)
Extension function.
void addGlobalBadState (const Condition< Number > &state)
Extension function.
Friends
bool operator== (const HybridAutomaton< Number > &lhs, const HybridAutomaton< Number > &rhs)
Comparison for equality operator.
bool operator!= (const HybridAutomaton< Number > &lhs, const HybridAutomaton< Number > &rhs)
template<typename Num >
HybridAutomaton< Num > operator|| (const HybridAutomaton< Num > &lhs, const HybridAutomaton< Num > &rhs)
Parallel Composition Operator.
HybridAutomatonComp< Number > operator+ (const HybridAutomaton< Number > &lhs, const HybridAutomaton< Number > &rhs)
Combination Operator.
Detailed Description
template<typename Number>
class hypro::HybridAutomaton< Number >
Class for linear hybrid automata.
Template Parameters
Number Number type.
The automaton owns all the locations and transitions. Newly created locations and transitions can only be added as unique pointers. If another class/object requests a location/transition, then only normal pointers are returned.
Examples:
example_bouncingBall.cpp.
Definition at line 36 of file HybridAutomaton.h.
Member Typedef Documentation
template<typename Number> using hypro::HybridAutomaton< Number >::conditionVector = std::vector<Condition<Number>>
Definition at line 40 of file HybridAutomaton.h.
template<typename Number> using hypro::HybridAutomaton< Number >::locationConditionMap = std::map<const Location<Number>*, Condition<Number>>
Definition at line 39 of file HybridAutomaton.h.
template<typename Number> using hypro::HybridAutomaton< Number >::locationVector = std::vector<std::unique_ptr<Location<Number>>>
Definition at line 38 of file HybridAutomaton.h.
template<typename Number> using hypro::HybridAutomaton< Number >::variableVector = std::vector<std::string>
Definition at line 41 of file HybridAutomaton.h.
Constructor & Destructor Documentation
template<typename Number> hypro::HybridAutomaton< Number >::HybridAutomaton () inline
Default constructor.
Definition at line 54 of file HybridAutomaton.h.
template<typename Number > hypro::HybridAutomaton< Number >::HybridAutomaton (const HybridAutomaton< Number > & hybrid)
Copy constructor.
Parameters
[in] hybrid The original hybrid automaton.
This operation is costly as it performs deep copies
Definition at line 7 of file HybridAutomaton.tpp.
References hypro::HybridAutomaton< Number >::addInitialState(), hypro::HybridAutomaton< Number >::addLocalBadState(), hypro::HybridAutomaton< Number >::getInitialStates(), hypro::HybridAutomaton< Number >::getLocalBadStates(), hypro::HybridAutomaton< Number >::getLocations(), and hypro::Location< Number >::hash().
template<typename Number> hypro::HybridAutomaton< Number >::HybridAutomaton (const locationVector & locs, const locationConditionMap & initialStates)
Move constructor.
Parameters
[in] hybrid The original hybrid automaton. Constructor from locations, transitions and initial states
[in] locs Set of locations
[in] trans Set of transitions
[in] initialStates Map of initial states
template<typename Number> virtual hypro::HybridAutomaton< Number >::~HybridAutomaton () inline virtual
Destructor.
Definition at line 84 of file HybridAutomaton.h.
References hypro::HybridAutomaton< Number >::getLocation(), hypro::HybridAutomaton< Number >::getLocations(), hypro::HybridAutomaton< Number >::getTransitions(), and hypro::HybridAutomaton< Number >::operator=().
Member Function Documentation
template<typename Number> void hypro::HybridAutomaton< Number >::addGlobalBadState (const Condition< Number > & state) inline
Extension function.
Definition at line 150 of file HybridAutomaton.h.
References hypro::HybridAutomaton< Number >::decompose(), hypro::HybridAutomaton< Number >::getDotRepresentation(), hypro::HybridAutomaton< Number >::getStatistics(), hypro::HybridAutomaton< Number >::isComposedOf(), and hypro::HybridAutomaton< Number >::reduce().
template<typename Number> void hypro::HybridAutomaton< Number >::addInitialState (const Location< Number > * loc, const Condition< Number > & state) inline
Extension function.
Definition at line 148 of file HybridAutomaton.h.
Referenced by hypro::HybridAutomaton< Number >::HybridAutomaton(), and main().
template<typename Number> void hypro::HybridAutomaton< Number >::addLocalBadState (const Location< Number > * loc, const Condition< Number > & condition) inline
Extension function.
Definition at line 149 of file HybridAutomaton.h.
Referenced by hypro::HybridAutomaton< Number >::HybridAutomaton().
template<typename Number > const std::unique_ptr< Location< Number > > & hypro::HybridAutomaton< Number >::addLocation (const Location< Number > & location)
Extension function.
Definition at line 206 of file HybridAutomaton.tpp.
Referenced by main(), hypro::operator||(), and hypro::HybridAutomaton< Number >::setVariables().
template<typename Number > const std::unique_ptr< Location< Number > > & hypro::HybridAutomaton< Number >::addLocation (std::unique_ptr< Location< Number >> && location)
Extension function.
Definition at line 211 of file HybridAutomaton.tpp.
template<typename Number > void hypro::HybridAutomaton< Number >::addTransition (std::unique_ptr< Transition< Number >> && transition)
Extension function.
Definition at line 217 of file HybridAutomaton.tpp.
Referenced by hypro::operator||(), and hypro::HybridAutomaton< Number >::setVariables().
template<typename Number > void hypro::HybridAutomaton< Number >::decompose (const Decomposition & decomposition)
Decomposes an automaton into the components defined by decomposition. The vector should contain sets of variables that are at least syntactically independet to each other.
Definition at line 280 of file HybridAutomaton.tpp.
Referenced by hypro::HybridAutomaton< Number >::addGlobalBadState(), and hypro::DecisionEntity< Number >::decomposeAutomaton().
template<typename Number > unsigned hypro::HybridAutomaton< Number >::dimension () const
Getter function.
Definition at line 188 of file HybridAutomaton.tpp.
Referenced by hypro::HybridAutomaton< Number >::getGlobalBadStates(), hypro::DecisionEntity< Number >::getSubspaceDecomposition(), and hypro::toFlowstarFormat().
template<typename Number> template<typename T > bool hypro::HybridAutomaton< Number >::equals (const std::vector< T * > & lhs, const std::vector< T * > & rhs) const inline
Definition at line 183 of file HybridAutomaton.h.
template<typename Number > std::string hypro::HybridAutomaton< Number >::getDotRepresentation () const
Definition at line 267 of file HybridAutomaton.tpp.
Referenced by hypro::HybridAutomaton< Number >::addGlobalBadState(), and main().
template<typename Number> const conditionVector& hypro::HybridAutomaton< Number >::getGlobalBadStates () const inline
Getter function.
Definition at line 116 of file HybridAutomaton.h.
References hypro::HybridAutomaton< Number >::dimension().
Referenced by hypro::Transformation< Number >::addGlobalBadStates(), hypro::DecisionEntity< Number >::getSubspaceDecomposition(), and hypro::ltiIntersectBadStates().
template<typename Number> const locationConditionMap& hypro::HybridAutomaton< Number >::getInitialStates () const inline
Getter function.
Definition at line 112 of file HybridAutomaton.h.
Referenced by hypro::DecisionEntity< Number >::checkDecomposed(), hypro::HybridAutomaton< Number >::HybridAutomaton(), hypro::EventTimingProvider< Number >::initialize(), main(), hypro::operator||(), hypro::toFlowstarFormat(), and hypro::Transformation< Number >::Transformation().
template<typename Number > const std::set< Label > hypro::HybridAutomaton< Number >::getLabels () const
Getter function.
Definition at line 195 of file HybridAutomaton.tpp.
References hypro::detail::for_each().
Referenced by hypro::HybridAutomaton< Number >::getVariables(), and hypro::operator||().
template<typename Number> const locationConditionMap& hypro::HybridAutomaton< Number >::getLocalBadStates () const inline
Getter function.
Definition at line 114 of file HybridAutomaton.h.
Referenced by hypro::DecisionEntity< Number >::getSubspaceDecomposition(), hypro::HybridAutomaton< Number >::HybridAutomaton(), hypro::ltiIntersectBadStates(), hypro::toFlowstarFormat(), and hypro::Transformation< Number >::Transformation().
template<typename Number > Location< Number > * hypro::HybridAutomaton< Number >::getLocation (const std::size_t hash) const
Getter function.
Definition at line 155 of file HybridAutomaton.tpp.
Referenced by hypro::HybridAutomaton< Number >::~HybridAutomaton().
template<typename Number > Location< Number > * hypro::HybridAutomaton< Number >::getLocation (const std::string & name) const
Getter function.
Definition at line 166 of file HybridAutomaton.tpp.
template<typename Number > std::vector< Location< Number > * > hypro::HybridAutomaton< Number >::getLocations () const
Getter function.
Definition at line 146 of file HybridAutomaton.tpp.
Referenced by hypro::Transformation< Number >::addGlobalBadStates(), hypro::SettingsProvider< State >::computeLocationSubspaceTypeMapping(), hypro::SettingsProvider< State >::computeLocationTypeMapping(), hypro::DecisionEntity< Number >::getSubspaceDecomposition(), hypro::HybridAutomaton< Number >::HybridAutomaton(), hypro::HybridAutomaton< Number >::isComposedOf(), hypro::DecisionEntity< Number >::isRectangularAutomaton(), hypro::DecisionEntity< Number >::isTimedAutomaton(), hypro::operator||(), hypro::toFlowstarFormat(), hypro::Transformation< Number >::Transformation(), and hypro::HybridAutomaton< Number >::~HybridAutomaton().
template<typename Number > std::string hypro::HybridAutomaton< Number >::getStatistics () const
Definition at line 304 of file HybridAutomaton.tpp.
Referenced by hypro::HybridAutomaton< Number >::addGlobalBadState(), and main().
template<typename Number > std::vector< Transition< Number > * > hypro::HybridAutomaton< Number >::getTransitions () const
Getter function.
Definition at line 177 of file HybridAutomaton.tpp.
Referenced by hypro::DecisionEntity< Number >::getSubspaceDecomposition(), main(), hypro::operator||(), hypro::toFlowstarFormat(), hypro::Transformation< Number >::Transformation(), and hypro::HybridAutomaton< Number >::~HybridAutomaton().
template<typename Number> const variableVector& hypro::HybridAutomaton< Number >::getVariables () const inline
Getter function.
Definition at line 120 of file HybridAutomaton.h.
References hypro::HybridAutomaton< Number >::getLabels(), and hypro::HybridAutomaton< Number >::setLocations().
Referenced by hypro::HybridAutomaton< Number >::isComposedOf(), and hypro::operator||().
template<typename Number > bool hypro::HybridAutomaton< Number >::isComposedOf (const HybridAutomaton< Number > & rhs) const
Function which tests whether this can be the result of a parallel composition with rhs.
Used to verify the result of operator|| for hybrid automata. Checks whether this automaton can be the composed of rhs and some (potentially empty) other composite.
Parameters
rhs Automaton which can be a component of this.
Returns
True, if this is composed of rhs and some (possibly empty) rest.
Definition at line 234 of file HybridAutomaton.tpp.
References hypro::HybridAutomaton< Number >::getLocations(), and hypro::HybridAutomaton< Number >::getVariables().
Referenced by hypro::HybridAutomaton< Number >::addGlobalBadState().
template<typename Number > HybridAutomaton< Number > & hypro::HybridAutomaton< Number >::operator= (const HybridAutomaton< Number > & rhs)
Copy Assignment.
Parameters
[in] rhs The original hybrid automaton
This operation is costly as it performs deep copies
Definition at line 123 of file HybridAutomaton.tpp.
Referenced by hypro::HybridAutomaton< Number >::~HybridAutomaton().
template<typename Number > HybridAutomaton< Number > & hypro::HybridAutomaton< Number >::operator= (HybridAutomaton< Number > && rhs)
Move Assignment.
Parameters
[in] rhs The original hybrid automaton
Definition at line 133 of file HybridAutomaton.tpp.
template<typename Number > void hypro::HybridAutomaton< Number >::reduce ()
Reduces the automaton, i.e. removes Locations which are not connected to the automaton by transitions.
Definition at line 228 of file HybridAutomaton.tpp.
Referenced by hypro::HybridAutomaton< Number >::addGlobalBadState(), main(), and hypro::operator||().
template<typename Number> void hypro::HybridAutomaton< Number >::setGlobalBadStates (const conditionVector & states) inline
Setter function.
Definition at line 137 of file HybridAutomaton.h.
Referenced by hypro::HyproHAVisitor< Number >::visitStart().
template<typename Number> void hypro::HybridAutomaton< Number >::setInitialStates (const locationConditionMap & states) inline
Setter function.
Definition at line 135 of file HybridAutomaton.h.
Referenced by hypro::HyproHAVisitor< Number >::visitStart().
template<typename Number> void hypro::HybridAutomaton< Number >::setLocalBadStates (const locationConditionMap & states) inline
Setter function.
Definition at line 136 of file HybridAutomaton.h.
Referenced by hypro::HyproHAVisitor< Number >::visitStart().
template<typename Number> void hypro::HybridAutomaton< Number >::setLocations (locationVector && locs) inline
Setter function.
Definition at line 129 of file HybridAutomaton.h.
Referenced by hypro::HybridAutomaton< Number >::getVariables(), hypro::Transformation< Number >::Transformation(), and hypro::HyproHAVisitor< Number >::visitStart().
template<typename Number> void hypro::HybridAutomaton< Number >::setVariables (const variableVector & variables) inline
Setter function.
Definition at line 138 of file HybridAutomaton.h.
References hypro::HybridAutomaton< Number >::addLocation(), and hypro::HybridAutomaton< Number >::addTransition().
Referenced by createComponent1(), createComponent2(), createComponent3(), createComponent4(), and hypro::operator||().
Friends And Related Function Documentation
template<typename Number> bool operator!= (const HybridAutomaton< Number > & lhs, const HybridAutomaton< Number > & rhs) friend
Definition at line 250 of file HybridAutomaton.h.
template<typename Number> HybridAutomatonComp<Number> operator+ (const HybridAutomaton< Number > & lhs, const HybridAutomaton< Number > & rhs) friend
Combination Operator.
Parameters
[in] lhs The left hand side.
[in] rhs The right hand side.
Returns
Return compositional Automata of two Automata.
Definition at line 270 of file HybridAutomaton.h.
template<typename Number> bool operator== (const HybridAutomaton< Number > & lhs, const HybridAutomaton< Number > & rhs) friend
Comparison for equality operator.
Parameters
[in] lhs The left hand side.
[in] rhs The right hand side.
Returns
True, if both automata are equal, false otherwise.
Definition at line 208 of file HybridAutomaton.h.
template<typename Number> template<typename Num > HybridAutomaton<Num> operator|| (const HybridAutomaton< Num > & lhs, const HybridAutomaton< Num > & rhs) friend
Parallel Composition Operator.
Parameters
[in] lhs The left hand side.
[in] rhs The right hand side.
Returns
Return parallel composition of two Automata.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/HybridAutomaton.h
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/HybridAutomaton.tpp