HyPro: hypro::Converter< Number > Class Template Reference
hypro::Converter< Number > Class Template Reference
Public Types
using TemplatePolyhedron = TemplatePolyhedronT< Number, Converter, TemplatePolyhedronDefault >
using Box = BoxT< Number, Converter, BoxLinearOptimizationOn >
using CarlPolytope = CarlPolytopeT< Number, Converter, CarlPolytopeSetting >
using ConstraintSet = ConstraintSetT< Number, ConstraintSetSettings >
using Ellipsoid = EllipsoidT< Number, Converter >
using HPolytope = HPolytopeT< Number, Converter, HPolytopeSetting >
using OrthogonalPolyhedron = OrthogonalPolyhedronT< Number, Converter, BoxLinearOptimizationOn >
using VPolytope = VPolytopeT< Number, Converter, VPolytopeSetting >
using DifferenceBounds = DifferenceBoundsT< Number, Converter, DifferenceBoundsSetting >
using Polytope = PolytopeT< Number, Converter, PolytopeSetting >
using SupportFunction = SupportFunctionT< Number, Converter, SupportFunctionSetting >
using Zonotope = ZonotopeT< Number, Converter, ZonotopeSetting >
using SupportFunctionNew = SupportFunctionNewT< Number, Converter, SupportFunctionNewMorePrecision >
Public Member Functions
template<typename BoxSetting , typename inSetting >
BoxT< Number, Converter< Number >, BoxSetting > toBox (const BoxT< Number, Converter< Number >, inSetting > &_source, const CONV_MODE)
template<typename CarlPolySetting , typename inSetting >
CarlPolytopeT< Number, Converter< Number >, CarlPolySetting > toCarlPolytope (const CarlPolytopeT< Number, Converter< Number >, inSetting > &_source, const CONV_MODE)
template<typename CarlPolySetting , typename inSetting >
CarlPolytopeT< Number, Converter< Number >, CarlPolySetting > toCarlPolytope (const ConstraintSetT< Number, inSetting > &_source, const CONV_MODE)
template<typename CarlPolySetting >
CarlPolytopeT< Number, Converter< Number >, CarlPolySetting > toCarlPolytope (const Ellipsoid &_source, const CONV_MODE)
template<typename CarlPolySetting , typename inSetting >
CarlPolytopeT< Number, Converter< Number >, CarlPolySetting > toCarlPolytope (const VPolytopeT< Number, Converter< Number >, inSetting > &_source, const CONV_MODE mode)
template<typename CarlPolySetting , typename inSetting >
CarlPolytopeT< Number, Converter< Number >, CarlPolySetting > toCarlPolytope (const BoxT< Number, Converter< Number >, inSetting > &_source, const CONV_MODE)
template<typename CarlPolySetting , typename inSetting >
CarlPolytopeT< Number, Converter< Number >, CarlPolySetting > toCarlPolytope (const ZonotopeT< Number, Converter< Number >, inSetting > &_source, const CONV_MODE mode)
template<typename CarlPolySetting , typename inSetting >
CarlPolytopeT< Number, Converter< Number >, CarlPolySetting > toCarlPolytope (const SupportFunctionT< Number, Converter< Number >, inSetting > &_source, const std::vector< vector_t< Number >> &additionalDirections, const CONV_MODE, std::size_t numberOfDirections)
template<typename CarlPolySetting , typename inSetting >
CarlPolytopeT< Number, Converter< Number >, CarlPolySetting > toCarlPolytope (const DifferenceBoundsT< Number, Converter< Number >, inSetting > &_source, const CONV_MODE)
template<typename CarlPolySetting , typename inSetting >
CarlPolytopeT< Number, Converter< Number >, CarlPolySetting > toCarlPolytope (const PolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE)
template<typename CarlPolySetting , typename inSetting >
CarlPolytopeT< Number, Converter< Number >, CarlPolySetting > toCarlPolytope (const HPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE)
template<typename CarlPolySetting , typename inSetting >
CarlPolytopeT< Number, Converter< Number >, CarlPolySetting > toCarlPolytope (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > &source, const CONV_MODE)
template<typename CarlPolySetting , typename inSetting >
CarlPolytopeT< Number, Converter< Number >, CarlPolySetting > toCarlPolytope (const SupportFunctionNewT< Number, Converter< Number >, inSetting > &_source, const std::vector< vector_t< Number >> &additionalDirections, const CONV_MODE, std::size_t numberOfDirections)
template<typename ConstraintSetSetting , typename inSetting >
ConstraintSetT< Number, ConstraintSetSetting > toConstraintSet (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > &source, const CONV_MODE)
template<typename DifferenceBoundsSetting , typename inSetting >
DifferenceBoundsT< Number, Converter< Number >, DifferenceBoundsSetting > toDifferenceBounds (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > &source, const CONV_MODE)
template<typename PolytopeSetting , typename inSetting >
PolytopeT< Number, Converter, PolytopeSetting > toPolytope (const SupportFunctionNewT< Number, Converter< Number >, inSetting > &source, const CONV_MODE)
Static Public Member Functions
template<typename TemplatePolyhedronSetting = typename TemplatePolyhedron::Settings, typename inSetting >
static TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > toTemplatePolyhedron (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename TemplatePolyhedronSetting = typename TemplatePolyhedron::Settings, typename inSetting >
static TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > toTemplatePolyhedron (const BoxT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename TemplatePolyhedronSetting = typename TemplatePolyhedron::Settings, typename inSetting >
static TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > toTemplatePolyhedron (const CarlPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename TemplatePolyhedronSetting = typename TemplatePolyhedron::Settings, typename inSetting >
static TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > toTemplatePolyhedron (const ConstraintSetT< Number, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename TemplatePolyhedronSetting = typename TemplatePolyhedron::Settings>
static TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > toTemplatePolyhedron (const Ellipsoid &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename TemplatePolyhedronSetting = typename TemplatePolyhedron::Settings, typename inSetting >
static TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > toTemplatePolyhedron (const HPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename TemplatePolyhedronSetting = typename TemplatePolyhedron::Settings, typename inSetting >
static TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > toTemplatePolyhedron (const VPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename TemplatePolyhedronSetting = typename TemplatePolyhedron::Settings, typename inSetting >
static TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > toTemplatePolyhedron (const DifferenceBoundsT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename TemplatePolyhedronSetting = typename TemplatePolyhedron::Settings, typename inSetting >
static TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > toTemplatePolyhedron (const PolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename TemplatePolyhedronSetting = typename TemplatePolyhedron::Settings, typename inSetting >
static TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > toTemplatePolyhedron (const SupportFunctionT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename TemplatePolyhedronSetting = typename TemplatePolyhedron::Settings, typename inSetting >
static TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > toTemplatePolyhedron (const SupportFunctionNewT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename TemplatePolyhedronSetting = typename TemplatePolyhedron::Settings, typename inSetting >
static TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > toTemplatePolyhedron (const ZonotopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename BoxSetting = typename Box::Settings, typename inSetting >
static BoxT< Number, Converter< Number >, BoxSetting > toBox (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename BoxSetting = typename Box::Settings, typename InSetting >
static BoxT< Number, Converter< Number >, BoxSetting > toBox (const BoxT< Number, Converter< Number >, InSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename BoxSetting = typename Box::Settings, typename inSetting >
static BoxT< Number, Converter< Number >, BoxSetting > toBox (const ConstraintSetT< Number, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename BoxSetting = typename Box::Settings>
static BoxT< Number, Converter< Number >, BoxSetting > toBox (const Ellipsoid &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename BoxSetting = typename Box::Settings, typename inSetting >
static BoxT< Number, Converter< Number >, BoxSetting > toBox (const HPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::ALTERNATIVE)
template<typename BoxSetting = typename Box::Settings, typename inSetting >
static BoxT< Number, Converter< Number >, BoxSetting > toBox (const VPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename BoxSetting = typename Box::Settings, typename inSetting >
static BoxT< Number, Converter< Number >, BoxSetting > toBox (const PolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename BoxSetting = typename Box::Settings, typename inSetting >
static BoxT< Number, Converter< Number >, BoxSetting > toBox (const SupportFunctionT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename BoxSetting = typename Box::Settings, typename inSetting >
static BoxT< Number, Converter< Number >, BoxSetting > toBox (const ZonotopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename BoxSetting = typename Box::Settings, typename inSetting >
static BoxT< Number, Converter< Number >, BoxSetting > toBox (const DifferenceBoundsT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename BoxSetting = typename Box::Settings, typename inSetting >
static BoxT< Number, Converter< Number >, BoxSetting > toBox (const CarlPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename BoxSetting = typename Box::Settings, typename inSetting >
static BoxT< Number, Converter< Number >, BoxSetting > toBox (const SupportFunctionNewT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting >
static CarlPolytopeT< Number, Converter< Number >, CarlPolytopeSetting > toCarlPolytope (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting >
static CarlPolytopeT< Number, Converter< Number >, CarlPolytopeSetting > toCarlPolytope (const BoxT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting >
static CarlPolytopeT< Number, Converter< Number >, CarlPolytopeSetting > toCarlPolytope (const ConstraintSetT< Number, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename CarlPolytopeSetting = typename CarlPolytope::Settings>
static CarlPolytopeT< Number, Converter< Number >, CarlPolytopeSetting > toCarlPolytope (const Ellipsoid &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting >
static CarlPolytopeT< Number, Converter< Number >, CarlPolytopeSetting > toCarlPolytope (const HPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting >
static CarlPolytopeT< Number, Converter< Number >, CarlPolytopeSetting > toCarlPolytope (const VPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting >
static CarlPolytopeT< Number, Converter< Number >, CarlPolytopeSetting > toCarlPolytope (const PolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting >
static CarlPolytopeT< Number, Converter< Number >, CarlPolytopeSetting > toCarlPolytope (const SupportFunctionT< Number, Converter< Number >, inSetting > &source, const std::vector< vector_t< Number >> &additionalDirections=std::vector< vector_t< Number >>(), const CONV_MODE=CONV_MODE::OVER, std::size_t numberOfDirections=defaultTemplateDirectionCount)
template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting >
static CarlPolytopeT< Number, Converter< Number >, CarlPolytopeSetting > toCarlPolytope (const ZonotopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting >
static CarlPolytopeT< Number, Converter< Number >, CarlPolytopeSetting > toCarlPolytope (const DifferenceBoundsT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting >
static CarlPolytopeT< Number, Converter< Number >, CarlPolytopeSetting > toCarlPolytope (const CarlPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting >
static CarlPolytopeT< Number, Converter< Number >, CarlPolytopeSetting > toCarlPolytope (const SupportFunctionNewT< Number, Converter< Number >, inSetting > &_source, const std::vector< vector_t< Number >> &additionalDirections=std::vector< vector_t< Number >>(), const CONV_MODE=CONV_MODE::OVER, std::size_t numberOfDirections=defaultTemplateDirectionCount)
template<typename CSSetting = typename ConstraintSet::Settings, typename inSetting >
static ConstraintSetT< Number, CSSetting > toConstraintSet (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename CSSetting = typename ConstraintSet::Settings, typename inSetting >
static ConstraintSetT< Number, CSSetting > toConstraintSet (const BoxT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename CSSetting = typename ConstraintSet::Settings, typename inSetting >
static ConstraintSetT< Number, CSSetting > toConstraintSet (const ConstraintSetT< Number, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename CSSetting = typename ConstraintSet::Settings>
static ConstraintSetT< Number, CSSetting > toConstraintSet (const Ellipsoid &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename CSSetting = typename ConstraintSet::Settings, typename inSetting >
static ConstraintSetT< Number, CSSetting > toConstraintSet (const HPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename CSSetting = typename ConstraintSet::Settings, typename inSetting >
static ConstraintSetT< Number, CSSetting > toConstraintSet (const VPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename CSSetting = typename ConstraintSet::Settings, typename inSetting >
static ConstraintSetT< Number, CSSetting > toConstraintSet (const PolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename CSSetting = typename ConstraintSet::Settings, typename inSetting >
static ConstraintSetT< Number, CSSetting > toConstraintSet (const SupportFunctionT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename CSSetting = typename ConstraintSet::Settings, typename inSetting >
static ConstraintSetT< Number, CSSetting > toConstraintSet (const ZonotopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename CSSetting = typename ConstraintSet::Settings, typename inSetting >
static ConstraintSetT< Number, CSSetting > toConstraintSet (const DifferenceBoundsT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename CSSetting = typename ConstraintSet::Settings, typename inSetting >
static ConstraintSetT< Number, CSSetting > toConstraintSet (const CarlPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename CSSetting = typename ConstraintSet::Settings, typename inSetting >
static ConstraintSetT< Number, CSSetting > toConstraintSet (const SupportFunctionNewT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename HPolySetting = typename HPolytope::Settings, typename inSetting >
static HPolytopeT< Number, Converter< Number >, HPolySetting > toHPolytope (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename HPolySetting = typename HPolytope::Settings, typename inSetting >
static HPolytopeT< Number, Converter< Number >, HPolySetting > toHPolytope (const BoxT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename HPolySetting = typename HPolytope::Settings, typename inSetting >
static HPolytopeT< Number, Converter< Number >, HPolySetting > toHPolytope (const ConstraintSetT< Number, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename HPolySetting = typename HPolytope::Settings>
static HPolytopeT< Number, Converter< Number >, HPolySetting > toHPolytope (const Ellipsoid &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename HPolySetting = typename HPolytope::Settings, typename inSetting >
static HPolytopeT< Number, Converter< Number >, HPolySetting > toHPolytope (const HPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename HPolySetting = typename HPolytope::Settings, typename inSetting >
static HPolytopeT< Number, Converter< Number >, HPolySetting > toHPolytope (const VPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename HPolySetting = typename HPolytope::Settings, typename inSetting >
static HPolytopeT< Number, Converter< Number >, HPolySetting > toHPolytope (const PolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename HPolySetting = typename HPolytope::Settings, typename inSetting >
static HPolytopeT< Number, Converter< Number >, HPolySetting > toHPolytope (const SupportFunctionT< Number, Converter< Number >, inSetting > &source, const std::vector< vector_t< Number >> &additionalDirections=std::vector< vector_t< Number >>(), const CONV_MODE=CONV_MODE::OVER, std::size_t numberOfDirections=defaultTemplateDirectionCount)
template<typename HPolySetting = typename HPolytope::Settings, typename inSetting >
static HPolytopeT< Number, Converter< Number >, HPolySetting > toHPolytope (const ZonotopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename HPolySetting = typename HPolytope::Settings, typename inSetting >
static HPolytopeT< Number, Converter< Number >, HPolySetting > toHPolytope (const DifferenceBoundsT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename HPolySetting = typename HPolytope::Settings, typename inSetting >
static HPolytopeT< Number, Converter< Number >, HPolySetting > toHPolytope (const CarlPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename HPolySetting = typename HPolytope::Settings, typename inSetting >
static HPolytopeT< Number, Converter< Number >, HPolySetting > toHPolytope (const SupportFunctionNewT< Number, Converter< Number >, inSetting > &source, const std::vector< vector_t< Number >> &additionalDirections=std::vector< vector_t< Number >>(), const CONV_MODE=CONV_MODE::OVER, std::size_t numberOfDirections=defaultTemplateDirectionCount)
template<typename VPolySetting = typename VPolytope::Settings, typename inSetting >
static VPolytopeT< Number, Converter< Number >, VPolySetting > toVPolytope (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename VPolySetting = typename VPolytope::Settings, typename inSetting >
static VPolytopeT< Number, Converter< Number >, VPolySetting > toVPolytope (const BoxT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename VPolySetting = typename VPolytope::Settings, typename inSetting >
static VPolytopeT< Number, Converter< Number >, VPolySetting > toVPolytope (const ConstraintSetT< Number, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename VPolySetting = typename VPolytope::Settings>
static VPolytopeT< Number, Converter< Number >, VPolySetting > toVPolytope (const Ellipsoid &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename VPolySetting = typename VPolytope::Settings, typename inSetting >
static VPolytopeT< Number, Converter< Number >, VPolySetting > toVPolytope (const HPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename VPolySetting = typename VPolytope::Settings, typename inSetting >
static VPolytopeT< Number, Converter< Number >, VPolySetting > toVPolytope (const VPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename VPolySetting = typename VPolytope::Settings, typename inSetting >
static VPolytopeT< Number, Converter< Number >, VPolySetting > toVPolytope (const PolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename VPolySetting = typename VPolytope::Settings, typename inSetting >
static VPolytopeT< Number, Converter< Number >, VPolySetting > toVPolytope (const SupportFunctionT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::UNDER, std::size_t numberOfDirections=defaultTemplateDirectionCount)
template<typename VPolySetting = typename VPolytope::Settings, typename inSetting >
static VPolytopeT< Number, Converter< Number >, VPolySetting > toVPolytope (const ZonotopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename VPolySetting = typename VPolytope::Settings, typename inSetting >
static VPolytopeT< Number, Converter< Number >, VPolySetting > toVPolytope (const DifferenceBoundsT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename VPolySetting = typename VPolytope::Settings, typename inSetting >
static VPolytopeT< Number, Converter< Number >, VPolySetting > toVPolytope (const CarlPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename VPolySetting = typename VPolytope::Settings, typename inSetting >
static VPolytopeT< Number, Converter< Number >, VPolySetting > toVPolytope (const SupportFunctionNewT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::UNDER, std::size_t numberOfDirections=defaultTemplateDirectionCount)
template<typename SFSetting = typename SupportFunction::Settings, typename inSetting >
static SupportFunctionT< Number, Converter< Number >, SFSetting > toSupportFunction (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFSetting = typename SupportFunction::Settings, typename inSetting >
static SupportFunctionT< Number, Converter< Number >, SFSetting > toSupportFunction (const BoxT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFSetting = typename SupportFunction::Settings, typename inSetting >
static SupportFunctionT< Number, Converter< Number >, SFSetting > toSupportFunction (const ConstraintSetT< Number, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFSetting = typename SupportFunction::Settings>
static SupportFunctionT< Number, Converter< Number >, SFSetting > toSupportFunction (const Ellipsoid &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFSetting = typename SupportFunction::Settings, typename inSetting >
static SupportFunctionT< Number, Converter< Number >, SFSetting > toSupportFunction (const HPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFSetting = typename SupportFunction::Settings, typename inSetting >
static SupportFunctionT< Number, Converter< Number >, SFSetting > toSupportFunction (const VPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFSetting = typename SupportFunction::Settings, typename inSetting >
static SupportFunctionT< Number, Converter< Number >, SFSetting > toSupportFunction (const PolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFSetting = typename SupportFunction::Settings, typename inSetting >
static SupportFunctionT< Number, Converter< Number >, SFSetting > toSupportFunction (const SupportFunctionT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFSetting = typename SupportFunction::Settings, typename inSetting >
static SupportFunctionT< Number, Converter< Number >, SFSetting > toSupportFunction (const ZonotopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFSetting = typename SupportFunction::Settings, typename inSetting >
static SupportFunctionT< Number, Converter< Number >, SFSetting > toSupportFunction (const DifferenceBoundsT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFSetting = typename SupportFunction::Settings, typename inSetting >
static SupportFunctionT< Number, Converter< Number >, SFSetting > toSupportFunction (const CarlPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFSetting = typename SupportFunction::Settings, typename inSetting >
static SupportFunctionT< Number, Converter< Number >, SFSetting > toSupportFunction (const SupportFunctionNewT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::UNDER)
template<typename ZonotopeSetting = typename Zonotope::Settings, typename inSetting >
static ZonotopeT< Number, Converter< Number >, ZonotopeSetting > toZonotope (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename ZonotopeSetting = typename Zonotope::Settings, typename inSetting >
static ZonotopeT< Number, Converter< Number >, ZonotopeSetting > toZonotope (const BoxT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename ZonotopeSetting = typename Zonotope::Settings, typename inSetting >
static ZonotopeT< Number, Converter< Number >, ZonotopeSetting > toZonotope (const CarlPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename ZonotopeSetting = typename Zonotope::Settings, typename inSetting >
static ZonotopeT< Number, Converter< Number >, ZonotopeSetting > toZonotope (const ConstraintSetT< Number, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename ZonotopeSetting = typename Zonotope::Settings>
static ZonotopeT< Number, Converter< Number >, ZonotopeSetting > toZonotope (const Ellipsoid &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename ZonotopeSetting = typename Zonotope::Settings, typename inSetting >
static ZonotopeT< Number, Converter< Number >, ZonotopeSetting > toZonotope (const HPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename ZonotopeSetting = typename Zonotope::Settings, typename inSetting >
static ZonotopeT< Number, Converter< Number >, ZonotopeSetting > toZonotope (const VPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename ZonotopeSetting = typename Zonotope::Settings, typename inSetting >
static ZonotopeT< Number, Converter< Number >, ZonotopeSetting > toZonotope (const PolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename ZonotopeSetting = typename Zonotope::Settings, typename inSetting >
static ZonotopeT< Number, Converter< Number >, ZonotopeSetting > toZonotope (const SupportFunctionT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER, std::size_t numberOfDirections=defaultTemplateDirectionCount)
template<typename ZonotopeSetting = typename Zonotope::Settings, typename inSetting >
static ZonotopeT< Number, Converter< Number >, ZonotopeSetting > toZonotope (const ZonotopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename ZonotopeSetting = typename Zonotope::Settings, typename inSetting >
static ZonotopeT< Number, Converter< Number >, ZonotopeSetting > toZonotope (const DifferenceBoundsT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER)
template<typename ZonotopeSetting = typename Zonotope::Settings, typename inSetting >
static ZonotopeT< Number, Converter< Number >, ZonotopeSetting > toZonotope (const SupportFunctionNewT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER, std::size_t numberOfDirections=defaultTemplateDirectionCount)
template<typename PolytopeSetting = typename Polytope::Settings, typename inSetting >
static PolytopeT< Number, Converter< Number >, PolytopeSetting > toPolytope (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename PolytopeSetting = typename Polytope::Settings, typename inSetting >
static PolytopeT< Number, Converter< Number >, PolytopeSetting > toPolytope (const PolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename PolytopeSetting = typename Polytope::Settings, typename inSetting >
static PolytopeT< Number, Converter< Number >, PolytopeSetting > toPolytope (const BoxT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename PolytopeSetting = typename Polytope::Settings, typename inSetting >
static PolytopeT< Number, Converter< Number >, PolytopeSetting > toPolytope (const ConstraintSetT< Number, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename PolytopeSetting = typename Polytope::Settings>
static PolytopeT< Number, Converter< Number >, PolytopeSetting > toPolytope (const Ellipsoid &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename PolytopeSetting = typename Polytope::Settings, typename inSetting >
static PolytopeT< Number, Converter< Number >, PolytopeSetting > toPolytope (const HPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename PolytopeSetting = typename Polytope::Settings, typename inSetting >
static PolytopeT< Number, Converter< Number >, PolytopeSetting > toPolytope (const VPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename PolytopeSetting = typename Polytope::Settings, typename inSetting >
static PolytopeT< Number, Converter< Number >, PolytopeSetting > toPolytope (const SupportFunctionT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::OVER, std::size_t numberOfDirections=defaultTemplateDirectionCount)
template<typename PolytopeSetting = typename Polytope::Settings, typename inSetting >
static PolytopeT< Number, Converter< Number >, PolytopeSetting > toPolytope (const ZonotopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename PolytopeSetting = typename Polytope::Settings, typename inSetting >
static PolytopeT< Number, Converter< Number >, PolytopeSetting > toPolytope (const DifferenceBoundsT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename PolytopeSetting = typename Polytope::Settings, typename inSetting >
static PolytopeT< Number, Converter< Number >, PolytopeSetting > toPolytope (const CarlPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename PolytopeSetting = typename Polytope::Settings, typename inSetting >
static PolytopeT< Number, Converter< Number >, PolytopeSetting > toPolytope (const SupportFunctionNewT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename DBSetting = typename DifferenceBounds::Settings, typename inSetting >
static DifferenceBoundsT< Number, Converter< Number >, DBSetting > toDifferenceBounds (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename DBSetting = typename DifferenceBounds::Settings, typename inSetting >
static DifferenceBoundsT< Number, Converter< Number >, DBSetting > toDifferenceBounds (const BoxT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename DBSetting = typename DifferenceBounds::Settings, typename inSetting >
static DifferenceBoundsT< Number, Converter< Number >, DBSetting > toDifferenceBounds (const CarlPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename DBSetting = typename DifferenceBounds::Settings, typename inSetting >
static DifferenceBoundsT< Number, Converter< Number >, DBSetting > toDifferenceBounds (const ConstraintSetT< Number, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename DBSetting = typename DifferenceBounds::Settings>
static DifferenceBoundsT< Number, Converter< Number >, DBSetting > toDifferenceBounds (const Ellipsoid &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename DBSetting = typename DifferenceBounds::Settings, typename inSetting >
static DifferenceBoundsT< Number, Converter< Number >, DBSetting > toDifferenceBounds (const HPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename DBSetting = typename DifferenceBounds::Settings, typename inSetting >
static DifferenceBoundsT< Number, Converter< Number >, DBSetting > toDifferenceBounds (const VPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename DBSetting = typename DifferenceBounds::Settings, typename inSetting >
static DifferenceBoundsT< Number, Converter< Number >, DBSetting > toDifferenceBounds (const PolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename DBSetting = typename DifferenceBounds::Settings, typename inSetting >
static DifferenceBoundsT< Number, Converter< Number >, DBSetting > toDifferenceBounds (const SupportFunctionT< Number, Converter< Number >, inSetting > &source, const std::vector< vector_t< Number >> &additionalDirections=std::vector< vector_t< Number >>(), const CONV_MODE=CONV_MODE::OVER, std::size_t numberOfDirections=defaultTemplateDirectionCount)
template<typename DBSetting = typename DifferenceBounds::Settings, typename inSetting >
static DifferenceBoundsT< Number, Converter< Number >, DBSetting > toDifferenceBounds (const ZonotopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename DBSetting = typename DifferenceBounds::Settings, typename inSetting >
static DifferenceBoundsT< Number, Converter< Number >, DBSetting > toDifferenceBounds (const DifferenceBoundsT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename DBSetting = typename DifferenceBounds::Settings, typename inSetting >
static DifferenceBoundsT< Number, Converter< Number >, DBSetting > toDifferenceBounds (const SupportFunctionNewT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFNSetting = typename SupportFunctionNew::Settings, typename inSetting >
static SupportFunctionNewT< Number, Converter< Number >, SFNSetting > toSupportFunctionNew (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFNSetting = typename SupportFunctionNew::Settings, typename inSetting >
static SupportFunctionNewT< Number, Converter< Number >, SFNSetting > toSupportFunctionNew (const BoxT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFNSetting = typename SupportFunctionNew::Settings, typename inSetting >
static SupportFunctionNewT< Number, Converter< Number >, SFNSetting > toSupportFunctionNew (const ConstraintSetT< Number, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFNSetting = typename SupportFunctionNew::Settings>
static SupportFunctionNewT< Number, Converter< Number >, SFNSetting > toSupportFunctionNew (const Ellipsoid &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFNSetting = typename SupportFunctionNew::Settings, typename inSetting >
static SupportFunctionNewT< Number, Converter< Number >, SFNSetting > toSupportFunctionNew (const HPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFNSetting = typename SupportFunctionNew::Settings, typename inSetting >
static SupportFunctionNewT< Number, Converter< Number >, SFNSetting > toSupportFunctionNew (const VPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFNSetting = typename SupportFunctionNew::Settings, typename inSetting >
static SupportFunctionNewT< Number, Converter< Number >, SFNSetting > toSupportFunctionNew (const PolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFNSetting = typename SupportFunctionNew::Settings, typename inSetting >
static SupportFunctionNewT< Number, Converter< Number >, SFNSetting > toSupportFunctionNew (const SupportFunctionT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFNSetting = typename SupportFunctionNew::Settings, typename inSetting >
static SupportFunctionNewT< Number, Converter< Number >, SFNSetting > toSupportFunctionNew (const ZonotopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFNSetting = typename SupportFunctionNew::Settings, typename inSetting >
static SupportFunctionNewT< Number, Converter< Number >, SFNSetting > toSupportFunctionNew (const DifferenceBoundsT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFNSetting = typename SupportFunctionNew::Settings, typename inSetting >
static SupportFunctionNewT< Number, Converter< Number >, SFNSetting > toSupportFunctionNew (const CarlPolytopeT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
template<typename SFNSetting = typename SupportFunctionNew::Settings, typename inSetting >
static SupportFunctionNewT< Number, Converter< Number >, SFNSetting > toSupportFunctionNew (const SupportFunctionNewT< Number, Converter< Number >, inSetting > &source, const CONV_MODE=CONV_MODE::EXACT)
Detailed Description
template<typename Number>
class hypro::Converter< Number >
Examples:
example_differenceBounds.cpp.
Definition at line 41 of file Converter.h.
Member Typedef Documentation
template<typename Number> using hypro::Converter< Number >::Box = BoxT<Number,Converter,BoxLinearOptimizationOn>
Definition at line 47 of file Converter.h.
template<typename Number> using hypro::Converter< Number >::CarlPolytope = CarlPolytopeT<Number,Converter,CarlPolytopeSetting>
Definition at line 48 of file Converter.h.
template<typename Number> using hypro::Converter< Number >::ConstraintSet = ConstraintSetT<Number,ConstraintSetSettings>
Definition at line 49 of file Converter.h.
template<typename Number> using hypro::Converter< Number >::DifferenceBounds = DifferenceBoundsT<Number,Converter,DifferenceBoundsSetting>
Definition at line 54 of file Converter.h.
template<typename Number> using hypro::Converter< Number >::Ellipsoid = EllipsoidT<Number,Converter>
Definition at line 50 of file Converter.h.
template<typename Number> using hypro::Converter< Number >::HPolytope = HPolytopeT<Number,Converter,HPolytopeSetting>
Definition at line 51 of file Converter.h.
template<typename Number> using hypro::Converter< Number >::OrthogonalPolyhedron = OrthogonalPolyhedronT<Number,Converter,BoxLinearOptimizationOn>
Definition at line 52 of file Converter.h.
template<typename Number> using hypro::Converter< Number >::Polytope = PolytopeT<Number,Converter,PolytopeSetting>
Definition at line 56 of file Converter.h.
template<typename Number> using hypro::Converter< Number >::SupportFunction = SupportFunctionT<Number,Converter,SupportFunctionSetting>
Definition at line 58 of file Converter.h.
template<typename Number> using hypro::Converter< Number >::SupportFunctionNew = SupportFunctionNewT<Number,Converter,SupportFunctionNewMorePrecision>
Definition at line 60 of file Converter.h.
template<typename Number> using hypro::Converter< Number >::TemplatePolyhedron = TemplatePolyhedronT<Number,Converter,TemplatePolyhedronDefault>
Definition at line 46 of file Converter.h.
template<typename Number> using hypro::Converter< Number >::VPolytope = VPolytopeT<Number,Converter,VPolytopeSetting>
Definition at line 53 of file Converter.h.
template<typename Number> using hypro::Converter< Number >::Zonotope = ZonotopeT<Number,Converter,ZonotopeSetting>
Definition at line 59 of file Converter.h.
Member Function Documentation
template<typename Number> template<typename BoxSetting , typename inSetting > BoxT<Number, Converter<Number>, BoxSetting> hypro::Converter< Number >::toBox (const BoxT< Number, Converter< Number >, inSetting > & _source, const CONV_MODE)
Definition at line 23 of file converterToBox.tpp.
template<typename Number > template<typename BoxSetting , typename inSetting > BoxT< Number, Converter< Number >, BoxSetting > hypro::Converter< Number >::toBox (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Examples:
example_converter.cpp.
Definition at line 375 of file converterToBox.tpp.
References hypro::isBox().
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::getCoveredTimeInterval(), hypro::timedInvariantHandler< State >::handle(), hypro::timedTickTimeEvolutionHandler< State >::handle(), hypro::timedElapseTimeEvolutionHandler< State >::handle(), hypro::timedElapseAfterTickTimeEvolutionHandler< State >::handle(), and main().
template<typename Number> template<typename BoxSetting = typename Box::Settings, typename InSetting > static BoxT<Number,Converter<Number>,BoxSetting> hypro::Converter< Number >::toBox (const BoxT< Number, Converter< Number >, InSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
template<typename Number > template<typename BoxSetting , typename inSetting > BoxT< Number, Converter< Number >, BoxSetting > hypro::Converter< Number >::toBox (const ConstraintSetT< Number, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 29 of file converterToBox.tpp.
References hypro::ConstraintSetT< Number, S >::matrix(), and hypro::ConstraintSetT< Number, S >::vector().
template<typename Number > template<typename BoxSetting > BoxT< Number, Converter< Number >, BoxSetting > hypro::Converter< Number >::toBox (const Ellipsoid & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 35 of file converterToBox.tpp.
References hypro::EllipsoidT< Number, Converter >::dimension(), and hypro::EllipsoidT< Number, Converter >::evaluate().
template<typename Number > template<typename BoxSetting , typename inSetting > BoxT< Number, Converter< Number >, BoxSetting > hypro::Converter< Number >::toBox (const HPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::ALTERNATIVE) static
Definition at line 134 of file converterToBox.tpp.
References hypro::ALTERNATIVE, hypro::BoxT< Number, Converter, Setting >::dimension(), hypro::INFTY, lowerBound(), hypro::OVER, and hypro::BoxT< Number, Converter, Setting >::vertices().
template<typename Number > template<typename BoxSetting , typename inSetting > BoxT< Number, Converter< Number >, BoxSetting > hypro::Converter< Number >::toBox (const VPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::OVER) static
Definition at line 94 of file converterToBox.tpp.
References hypro::VPolytopeT< Number, Converter, S >::empty(), and hypro::VPolytopeT< Number, Converter, S >::vertices().
template<typename Number > template<typename BoxSetting , typename inSetting > BoxT< Number, Converter< Number >, BoxSetting > hypro::Converter< Number >::toBox (const PolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::OVER) static
Definition at line 207 of file converterToBox.tpp.
template<typename Number > template<typename BoxSetting , typename inSetting > BoxT< Number, Converter< Number >, BoxSetting > hypro::Converter< Number >::toBox (const SupportFunctionT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::OVER) static
Definition at line 53 of file converterToBox.tpp.
References hypro::INFTY, and lowerBound().
template<typename Number > template<typename BoxSetting , typename inSetting > BoxT< Number, Converter< Number >, BoxSetting > hypro::Converter< Number >::toBox (const ZonotopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::OVER) static
Definition at line 216 of file converterToBox.tpp.
References hypro::ALTERNATIVE, hypro::BoxT< Number, Converter, Setting >::at(), and hypro::Point< Number >::at().
template<typename Number > template<typename BoxSetting , typename inSetting > BoxT< Number, Converter< Number >, BoxSetting > hypro::Converter< Number >::toBox (const DifferenceBoundsT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::OVER) static
Definition at line 289 of file converterToBox.tpp.
References hypro::INFTY.
template<typename Number > template<typename BoxSetting , typename inSetting > BoxT< Number, Converter< Number >, BoxSetting > hypro::Converter< Number >::toBox (const CarlPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::OVER) static
Definition at line 369 of file converterToBox.tpp.
template<typename Number > template<typename BoxSetting , typename inSetting > BoxT< Number, Converter< Number >, BoxSetting > hypro::Converter< Number >::toBox (const SupportFunctionNewT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::OVER) static
Definition at line 394 of file converterToBox.tpp.
References hypro::INFTY, and lowerBound().
template<typename Number> template<typename CarlPolySetting , typename inSetting > CarlPolytopeT<Number, Converter<Number>, CarlPolySetting> hypro::Converter< Number >::toCarlPolytope (const CarlPolytopeT< Number, Converter< Number >, inSetting > & _source, const CONV_MODE)
Definition at line 21 of file converterToCarlPolytope.tpp.
template<typename Number> template<typename CarlPolySetting , typename inSetting > CarlPolytopeT<Number, Converter<Number>, CarlPolySetting> hypro::Converter< Number >::toCarlPolytope (const ConstraintSetT< Number, inSetting > & _source, const CONV_MODE)
Definition at line 27 of file converterToCarlPolytope.tpp.
References hypro::ConstraintSetT< Number, S >::matrix(), and hypro::ConstraintSetT< Number, S >::vector().
template<typename Number> template<typename CarlPolySetting > CarlPolytopeT<Number, Converter<Number>, CarlPolySetting> hypro::Converter< Number >::toCarlPolytope (const Ellipsoid & _source, const CONV_MODE)
Definition at line 33 of file converterToCarlPolytope.tpp.
References hypro::EllipsoidT< Number, Converter >::dimension(), and hypro::EllipsoidT< Number, Converter >::evaluate().
template<typename Number> template<typename CarlPolySetting , typename inSetting > CarlPolytopeT<Number, Converter<Number>, CarlPolySetting> hypro::Converter< Number >::toCarlPolytope (const VPolytopeT< Number, Converter< Number >, inSetting > & _source, const CONV_MODE mode)
Definition at line 77 of file converterToCarlPolytope.tpp.
References hypro::CarlPolytopeT< Number, Converter, Setting >::matrix().
template<typename Number> template<typename CarlPolySetting , typename inSetting > CarlPolytopeT<Number, Converter<Number>, CarlPolySetting> hypro::Converter< Number >::toCarlPolytope (const BoxT< Number, Converter< Number >, inSetting > & _source, const CONV_MODE)
Definition at line 85 of file converterToCarlPolytope.tpp.
template<typename Number> template<typename CarlPolySetting , typename inSetting > CarlPolytopeT<Number, Converter<Number>, CarlPolySetting> hypro::Converter< Number >::toCarlPolytope (const ZonotopeT< Number, Converter< Number >, inSetting > & _source, const CONV_MODE mode)
Definition at line 92 of file converterToCarlPolytope.tpp.
template<typename Number> template<typename CarlPolySetting , typename inSetting > CarlPolytopeT<Number, Converter<Number>, CarlPolySetting> hypro::Converter< Number >::toCarlPolytope (const SupportFunctionT< Number, Converter< Number >, inSetting > & _source, const std::vector< vector_t< Number >> & additionalDirections, const CONV_MODE , std::size_t numberOfDirections)
Definition at line 106 of file converterToCarlPolytope.tpp.
References hypro::INFTY.
template<typename Number> template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting > static CarlPolytopeT<Number,Converter<Number>,CarlPolytopeSetting> hypro::Converter< Number >::toCarlPolytope (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::linearTransformation().
template<typename Number> template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting > static CarlPolytopeT<Number,Converter<Number>,CarlPolytopeSetting> hypro::Converter< Number >::toCarlPolytope (const BoxT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
template<typename Number> template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting > static CarlPolytopeT<Number,Converter<Number>,CarlPolytopeSetting> hypro::Converter< Number >::toCarlPolytope (const ConstraintSetT< Number, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
template<typename Number> template<typename CarlPolytopeSetting = typename CarlPolytope::Settings> static CarlPolytopeT<Number,Converter<Number>,CarlPolytopeSetting> hypro::Converter< Number >::toCarlPolytope (const Ellipsoid & source, const CONV_MODE = CONV_MODE::EXACT) static
template<typename Number> template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting > static CarlPolytopeT<Number,Converter<Number>,CarlPolytopeSetting> hypro::Converter< Number >::toCarlPolytope (const HPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
template<typename Number> template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting > static CarlPolytopeT<Number,Converter<Number>,CarlPolytopeSetting> hypro::Converter< Number >::toCarlPolytope (const VPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
template<typename Number> template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting > static CarlPolytopeT<Number,Converter<Number>,CarlPolytopeSetting> hypro::Converter< Number >::toCarlPolytope (const PolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
template<typename Number> template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting > static CarlPolytopeT<Number,Converter<Number>,CarlPolytopeSetting> hypro::Converter< Number >::toCarlPolytope (const SupportFunctionT< Number, Converter< Number >, inSetting > & source, const std::vector< vector_t< Number >> & additionalDirections = std::vector< vector_t< Number >>(), const CONV_MODE = CONV_MODE::OVER, std::size_t numberOfDirections = defaultTemplateDirectionCount) static
template<typename Number> template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting > static CarlPolytopeT<Number,Converter<Number>,CarlPolytopeSetting> hypro::Converter< Number >::toCarlPolytope (const ZonotopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
template<typename Number> template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting > static CarlPolytopeT<Number,Converter<Number>,CarlPolytopeSetting> hypro::Converter< Number >::toCarlPolytope (const DifferenceBoundsT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
template<typename Number> template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting > static CarlPolytopeT<Number,Converter<Number>,CarlPolytopeSetting> hypro::Converter< Number >::toCarlPolytope (const CarlPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
template<typename Number> template<typename CarlPolytopeSetting = typename CarlPolytope::Settings, typename inSetting > static CarlPolytopeT<Number,Converter<Number>,CarlPolytopeSetting> hypro::Converter< Number >::toCarlPolytope (const SupportFunctionNewT< Number, Converter< Number >, inSetting > & _source, const std::vector< vector_t< Number >> & additionalDirections = std::vector< vector_t< Number >>(), const CONV_MODE = CONV_MODE::OVER, std::size_t numberOfDirections = defaultTemplateDirectionCount) static
template<typename Number> template<typename CarlPolySetting , typename inSetting > CarlPolytopeT<Number, Converter<Number>, CarlPolySetting> hypro::Converter< Number >::toCarlPolytope (const DifferenceBoundsT< Number, Converter< Number >, inSetting > & _source, const CONV_MODE)
Definition at line 220 of file converterToCarlPolytope.tpp.
References hypro::INFTY.
template<typename Number> template<typename CarlPolySetting , typename inSetting > CarlPolytopeT<Number, Converter<Number>, CarlPolySetting> hypro::Converter< Number >::toCarlPolytope (const PolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE)
Definition at line 266 of file converterToCarlPolytope.tpp.
References hypro::EXACT.
template<typename Number> template<typename CarlPolySetting , typename inSetting > CarlPolytopeT<Number, Converter<Number>, CarlPolySetting> hypro::Converter< Number >::toCarlPolytope (const HPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE)
Definition at line 274 of file converterToCarlPolytope.tpp.
template<typename Number> template<typename CarlPolySetting , typename inSetting > CarlPolytopeT<Number,Converter<Number>,CarlPolySetting> hypro::Converter< Number >::toCarlPolytope (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > & source, const CONV_MODE)
Definition at line 280 of file converterToCarlPolytope.tpp.
template<typename Number> template<typename CarlPolySetting , typename inSetting > CarlPolytopeT<Number,Converter<Number>,CarlPolySetting> hypro::Converter< Number >::toCarlPolytope (const SupportFunctionNewT< Number, Converter< Number >, inSetting > & _source, const std::vector< vector_t< Number >> & additionalDirections, const CONV_MODE , std::size_t numberOfDirections)
Definition at line 292 of file converterToCarlPolytope.tpp.
References hypro::INFTY.
template<typename Number> template<typename ConstraintSetSetting , typename inSetting > ConstraintSetT<Number,ConstraintSetSetting> hypro::Converter< Number >::toConstraintSet (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > & source, const CONV_MODE)
Definition at line 75 of file converterToConstraintSet.tpp.
template<typename Number> template<typename CSSetting = typename ConstraintSet::Settings, typename inSetting > static ConstraintSetT<Number,CSSetting> hypro::Converter< Number >::toConstraintSet (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
template<typename Number > template<typename CSSetting , typename inSetting > ConstraintSetT< Number, CSSetting > hypro::Converter< Number >::toConstraintSet (const BoxT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 11 of file converterToConstraintSet.tpp.
template<typename Number > template<typename CSSetting , typename inSetting > ConstraintSetT< Number, CSSetting > hypro::Converter< Number >::toConstraintSet (const ConstraintSetT< Number, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 23 of file converterToConstraintSet.tpp.
template<typename Number > template<typename CSSetting > ConstraintSetT< Number, CSSetting > hypro::Converter< Number >::toConstraintSet (const Ellipsoid & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 29 of file converterToConstraintSet.tpp.
References hypro::EllipsoidT< Number, Converter >::matrix().
template<typename Number > template<typename CSSetting , typename inSetting > ConstraintSetT< Number, CSSetting > hypro::Converter< Number >::toConstraintSet (const HPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::OVER) static
Definition at line 47 of file converterToConstraintSet.tpp.
template<typename Number > template<typename CSSetting , typename inSetting > ConstraintSetT< Number, CSSetting > hypro::Converter< Number >::toConstraintSet (const VPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::OVER) static
Definition at line 40 of file converterToConstraintSet.tpp.
template<typename Number > template<typename CSSetting , typename inSetting > ConstraintSetT< Number, CSSetting > hypro::Converter< Number >::toConstraintSet (const PolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::OVER) static
Definition at line 54 of file converterToConstraintSet.tpp.
template<typename Number > template<typename CSSetting , typename inSetting > ConstraintSetT< Number, CSSetting > hypro::Converter< Number >::toConstraintSet (const SupportFunctionT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::OVER) static
Definition at line 35 of file converterToConstraintSet.tpp.
template<typename Number > template<typename CSSetting , typename inSetting > ConstraintSetT< Number, CSSetting > hypro::Converter< Number >::toConstraintSet (const ZonotopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::OVER) static
Definition at line 62 of file converterToConstraintSet.tpp.
template<typename Number > template<typename CSSetting , typename inSetting > ConstraintSetT< Number, CSSetting > hypro::Converter< Number >::toConstraintSet (const DifferenceBoundsT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::OVER) static
Definition at line 69 of file converterToConstraintSet.tpp.
template<typename Number > template<typename CSSetting , typename inSetting > ConstraintSetT< Number, CSSetting > hypro::Converter< Number >::toConstraintSet (const CarlPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::OVER) static
Definition at line 17 of file converterToConstraintSet.tpp.
template<typename Number > template<typename CSSetting , typename inSetting > ConstraintSetT< Number, CSSetting > hypro::Converter< Number >::toConstraintSet (const SupportFunctionNewT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::OVER) static
Definition at line 87 of file converterToConstraintSet.tpp.
template<typename Number> template<typename DifferenceBoundsSetting , typename inSetting > DifferenceBoundsT<Number,Converter<Number>,DifferenceBoundsSetting> hypro::Converter< Number >::toDifferenceBounds (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > & source, const CONV_MODE)
Definition at line 142 of file converterToDifferenceBounds.tpp.
template<typename Number> template<typename DBSetting = typename DifferenceBounds::Settings, typename inSetting > static DifferenceBoundsT<Number,Converter<Number>,DBSetting> hypro::Converter< Number >::toDifferenceBounds (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Examples:
example_differenceBounds.cpp.
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::affineTransformation(), hypro::DifferenceBoundsT< Number, Converter, Setting >::DifferenceBoundsT(), hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectHalfspace(), hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectHalfspaces(), hypro::DifferenceBoundsT< Number, Converter, Setting >::linearTransformation(), hypro::DifferenceBoundsT< Number, Converter, Setting >::minkowskiSum(), hypro::DifferenceBoundsT< Number, Converter, Setting >::project(), hypro::DifferenceBoundsT< Number, Converter, Setting >::satisfiesHalfspace(), hypro::DifferenceBoundsT< Number, Converter, Setting >::satisfiesHalfspaces(), testConversionBoxToDBM(), testConversionDifferenceBoundsToDifferenceBounds(), and testConversionHPolyToDBM().
template<typename Number > template<typename DBSetting , typename inSetting > DifferenceBoundsT< Number, Converter< Number >, DBSetting > hypro::Converter< Number >::toDifferenceBounds (const BoxT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 26 of file converterToDifferenceBounds.tpp.
template<typename Number > template<typename DBSetting , typename inSetting > DifferenceBoundsT< Number, Converter< Number >, DBSetting > hypro::Converter< Number >::toDifferenceBounds (const CarlPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 34 of file converterToDifferenceBounds.tpp.
template<typename Number > template<typename DBSetting , typename inSetting > DifferenceBoundsT< Number, Converter< Number >, DBSetting > hypro::Converter< Number >::toDifferenceBounds (const ConstraintSetT< Number, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 42 of file converterToDifferenceBounds.tpp.
template<typename Number > template<typename DBSetting > DifferenceBoundsT< Number, Converter< Number >, DBSetting > hypro::Converter< Number >::toDifferenceBounds (const Ellipsoid & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 50 of file converterToDifferenceBounds.tpp.
template<typename Number > template<typename DBSetting , typename inSetting > DifferenceBoundsT< Number, Converter< Number >, DBSetting > hypro::Converter< Number >::toDifferenceBounds (const HPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 58 of file converterToDifferenceBounds.tpp.
References hypro::EvaluationResult< Number >::errorCode, hypro::INFTY, hypro::DifferenceBoundsT< Number, Converter, Setting >::setDBM(), and hypro::EvaluationResult< Number >::supportValue.
template<typename Number > template<typename DBSetting , typename inSetting > DifferenceBoundsT< Number, Converter< Number >, DBSetting > hypro::Converter< Number >::toDifferenceBounds (const VPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 101 of file converterToDifferenceBounds.tpp.
template<typename Number > template<typename DBSetting , typename inSetting > DifferenceBoundsT< Number, Converter< Number >, DBSetting > hypro::Converter< Number >::toDifferenceBounds (const PolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 110 of file converterToDifferenceBounds.tpp.
template<typename Number > template<typename DBSetting , typename inSetting > DifferenceBoundsT< Number, Converter< Number >, DBSetting > hypro::Converter< Number >::toDifferenceBounds (const SupportFunctionT< Number, Converter< Number >, inSetting > & source, const std::vector< vector_t< Number >> & additionalDirections = std::vector<vector_t<Number>>(), const CONV_MODE = CONV_MODE::OVER, std::size_t numberOfDirections = defaultTemplateDirectionCount) static
Definition at line 118 of file converterToDifferenceBounds.tpp.
template<typename Number > template<typename DBSetting , typename inSetting > DifferenceBoundsT< Number, Converter< Number >, DBSetting > hypro::Converter< Number >::toDifferenceBounds (const ZonotopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 126 of file converterToDifferenceBounds.tpp.
template<typename Number > template<typename DBSetting , typename inSetting > DifferenceBoundsT< Number, Converter< Number >, DBSetting > hypro::Converter< Number >::toDifferenceBounds (const DifferenceBoundsT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 20 of file converterToDifferenceBounds.tpp.
template<typename Number > template<typename DBSetting , typename inSetting > DifferenceBoundsT< Number, Converter< Number >, DBSetting > hypro::Converter< Number >::toDifferenceBounds (const SupportFunctionNewT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 134 of file converterToDifferenceBounds.tpp.
template<typename Number > template<typename HPolySetting , typename inSetting > HPolytopeT< Number, Converter< Number >, HPolySetting > hypro::Converter< Number >::toHPolytope (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Examples:
example_differenceBounds.cpp.
Definition at line 310 of file converterToHPolytope.tpp.
Referenced by hypro::DifferenceBoundsT< Number, Converter, Setting >::affineTransformation(), hypro::HPolytopeT< Number, Converter, Setting >::affineTransformation(), hypro::VPolytopeT< Number, Converter, S >::contains(), hypro::VPolytopeT< Number, Converter, S >::intersectHalfspace(), hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectHalfspace(), hypro::VPolytopeT< Number, Converter, S >::intersectHalfspaces(), hypro::DifferenceBoundsT< Number, Converter, Setting >::intersectHalfspaces(), hypro::DifferenceBoundsT< Number, Converter, Setting >::linearTransformation(), hypro::HPolytopeT< Number, Converter, Setting >::linearTransformation(), main(), hypro::DifferenceBoundsT< Number, Converter, Setting >::minkowskiSum(), hypro::DifferenceBoundsT< Number, Converter, Setting >::project(), hypro::SupportFunctionT< Number, Converter, Setting >::satisfiesHalfspace(), hypro::VPolytopeT< Number, Converter, S >::satisfiesHalfspace(), hypro::DifferenceBoundsT< Number, Converter, Setting >::satisfiesHalfspace(), hypro::VPolytopeT< Number, Converter, S >::satisfiesHalfspaces(), hypro::DifferenceBoundsT< Number, Converter, Setting >::satisfiesHalfspaces(), testAffineTransformation(), testLinearTransformation(), testMinkowskiSum(), hypro::Converter< Number >::toPolytope(), hypro::SupportFunctionT< Number, Converter, Setting >::vertices(), hypro::CarlPolytopeT< Number, Converter, Setting >::vertices(), hypro::DifferenceBoundsT< Number, Converter, Setting >::vertices(), and hypro::SupportFunctionNewT< Number, Converter, Setting >::vertices().
template<typename Number > template<typename HPolySetting , typename inSetting > HPolytopeT< Number, Converter< Number >, HPolySetting > hypro::Converter< Number >::toHPolytope (const BoxT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 100 of file converterToHPolytope.tpp.
template<typename Number > template<typename HPolySetting , typename inSetting > HPolytopeT< Number, Converter< Number >, HPolySetting > hypro::Converter< Number >::toHPolytope (const ConstraintSetT< Number, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 27 of file converterToHPolytope.tpp.
References hypro::ConstraintSetT< Number, S >::matrix(), and hypro::ConstraintSetT< Number, S >::vector().
template<typename Number > template<typename HPolySetting > HPolytopeT< Number, Converter< Number >, HPolySetting > hypro::Converter< Number >::toHPolytope (const Ellipsoid & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 33 of file converterToHPolytope.tpp.
References hypro::EllipsoidT< Number, Converter >::dimension(), and hypro::EllipsoidT< Number, Converter >::evaluate().
template<typename Number > template<typename HPolySetting , typename inSetting > HPolytopeT< Number, Converter< Number >, HPolySetting > hypro::Converter< Number >::toHPolytope (const HPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 21 of file converterToHPolytope.tpp.
template<typename Number > template<typename HPolySetting , typename inSetting > HPolytopeT< Number, Converter< Number >, HPolySetting > hypro::Converter< Number >::toHPolytope (const VPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::EXACT) static
Definition at line 77 of file converterToHPolytope.tpp.
References hypro::PrincipalComponentAnalysis< Number >::box(), hypro::EXACT, hypro::OVER, and hypro::VPolytopeT< Number, Converter, S >::vertices().
template<typename Number > template<typename HPolySetting , typename inSetting > HPolytopeT< Number, Converter< Number >, HPolySetting > hypro::Converter< Number >::toHPolytope (const PolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::EXACT) static
Definition at line 281 of file converterToHPolytope.tpp.
References hypro::PrincipalComponentAnalysis< Number >::box(), hypro::EXACT, and hypro::OVER.
template<typename Number > template<typename HPolySetting , typename inSetting > HPolytopeT< Number, Converter< Number >, HPolySetting > hypro::Converter< Number >::toHPolytope (const SupportFunctionT< Number, Converter< Number >, inSetting > & source, const std::vector< vector_t< Number >> & additionalDirections = std::vector<vector_t<Number>>(), const CONV_MODE = CONV_MODE::OVER, std::size_t numberOfDirections = defaultTemplateDirectionCount) static
Definition at line 121 of file converterToHPolytope.tpp.
References hypro::INFTY.
template<typename Number > template<typename HPolySetting , typename inSetting > HPolytopeT< Number, Converter< Number >, HPolySetting > hypro::Converter< Number >::toHPolytope (const ZonotopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::EXACT) static
Definition at line 107 of file converterToHPolytope.tpp.
template<typename Number > template<typename HPolySetting , typename inSetting > HPolytopeT< Number, Converter< Number >, HPolySetting > hypro::Converter< Number >::toHPolytope (const DifferenceBoundsT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 235 of file converterToHPolytope.tpp.
References hypro::INFTY.
template<typename Number > template<typename HPolySetting , typename inSetting > HPolytopeT< Number, Converter< Number >, HPolySetting > hypro::Converter< Number >::toHPolytope (const CarlPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 304 of file converterToHPolytope.tpp.
template<typename Number > template<typename HPolySetting , typename inSetting > HPolytopeT< Number, Converter< Number >, HPolySetting > hypro::Converter< Number >::toHPolytope (const SupportFunctionNewT< Number, Converter< Number >, inSetting > & source, const std::vector< vector_t< Number >> & additionalDirections = std::vector<vector_t<Number>>(), const CONV_MODE = CONV_MODE::OVER, std::size_t numberOfDirections = defaultTemplateDirectionCount) static
Definition at line 322 of file converterToHPolytope.tpp.
References hypro::INFTY.
template<typename Number> template<typename PolytopeSetting , typename inSetting > PolytopeT<Number,Converter,PolytopeSetting> hypro::Converter< Number >::toPolytope (const SupportFunctionNewT< Number, Converter< Number >, inSetting > & source, const CONV_MODE)
Definition at line 104 of file converterToPolytope.tpp.
References hypro::EXACT, hypro::HPolytopeT< Number, Converter, Setting >::matrix(), hypro::Converter< Number >::toHPolytope(), and hypro::HPolytopeT< Number, Converter, Setting >::vector().
template<typename Number > template<typename PolytopeSetting , typename inSetting > PolytopeT< Number, Converter< Number >, PolytopeSetting > hypro::Converter< Number >::toPolytope (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 91 of file converterToPolytope.tpp.
template<typename Number > template<typename PolytopeSetting , typename inSetting > PolytopeT< Number, Converter< Number >, PolytopeSetting > hypro::Converter< Number >::toPolytope (const PolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 19 of file converterToPolytope.tpp.
template<typename Number > template<typename PolytopeSetting , typename inSetting > PolytopeT< Number, Converter< Number >, PolytopeSetting > hypro::Converter< Number >::toPolytope (const BoxT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 26 of file converterToPolytope.tpp.
template<typename Number > template<typename PolytopeSetting , typename inSetting > PolytopeT< Number, Converter< Number >, PolytopeSetting > hypro::Converter< Number >::toPolytope (const ConstraintSetT< Number, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 33 of file converterToPolytope.tpp.
References hypro::ConstraintSetT< Number, S >::matrix(), and hypro::ConstraintSetT< Number, S >::vector().
template<typename Number > template<typename PolytopeSetting > PolytopeT< Number, Converter< Number >, PolytopeSetting > hypro::Converter< Number >::toPolytope (const Ellipsoid & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 47 of file converterToPolytope.tpp.
References hypro::HPolytopeT< Number, Converter, Setting >::matrix(), hypro::Converter< Number >::toHPolytope(), and hypro::HPolytopeT< Number, Converter, Setting >::vector().
template<typename Number > template<typename PolytopeSetting , typename inSetting > PolytopeT< Number, Converter< Number >, PolytopeSetting > hypro::Converter< Number >::toPolytope (const HPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 55 of file converterToPolytope.tpp.
template<typename Number > template<typename PolytopeSetting , typename inSetting > PolytopeT< Number, Converter< Number >, PolytopeSetting > hypro::Converter< Number >::toPolytope (const VPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 62 of file converterToPolytope.tpp.
template<typename Number > template<typename PolytopeSetting , typename inSetting > PolytopeT< Number, Converter< Number >, PolytopeSetting > hypro::Converter< Number >::toPolytope (const SupportFunctionT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::OVER, std::size_t numberOfDirections = defaultTemplateDirectionCount) static
Definition at line 69 of file converterToPolytope.tpp.
References hypro::EXACT, hypro::HPolytopeT< Number, Converter, Setting >::matrix(), hypro::Converter< Number >::toHPolytope(), and hypro::HPolytopeT< Number, Converter, Setting >::vector().
template<typename Number > template<typename PolytopeSetting , typename inSetting > PolytopeT< Number, Converter< Number >, PolytopeSetting > hypro::Converter< Number >::toPolytope (const ZonotopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 78 of file converterToPolytope.tpp.
template<typename Number > template<typename PolytopeSetting , typename inSetting > PolytopeT< Number, Converter< Number >, PolytopeSetting > hypro::Converter< Number >::toPolytope (const DifferenceBoundsT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 40 of file converterToPolytope.tpp.
template<typename Number > template<typename PolytopeSetting , typename inSetting > PolytopeT< Number, Converter< Number >, PolytopeSetting > hypro::Converter< Number >::toPolytope (const CarlPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 85 of file converterToPolytope.tpp.
template<typename Number> template<typename PolytopeSetting = typename Polytope::Settings, typename inSetting > static PolytopeT<Number,Converter<Number>,PolytopeSetting> hypro::Converter< Number >::toPolytope (const SupportFunctionNewT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
template<typename Number > template<typename SFSetting , typename inSetting > SupportFunctionT< Number, Converter< Number >, SFSetting > hypro::Converter< Number >::toSupportFunction (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 96 of file converterToSupportFunction.tpp.
template<typename Number > template<typename SFSetting , typename inSetting > SupportFunctionT< Number, Converter< Number >, SFSetting > hypro::Converter< Number >::toSupportFunction (const BoxT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 29 of file converterToSupportFunction.tpp.
template<typename Number > template<typename SFSetting , typename inSetting > SupportFunctionT< Number, Converter< Number >, SFSetting > hypro::Converter< Number >::toSupportFunction (const ConstraintSetT< Number, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 35 of file converterToSupportFunction.tpp.
References hypro::ConstraintSetT< Number, S >::matrix(), and hypro::ConstraintSetT< Number, S >::vector().
template<typename Number > template<typename SFSetting > SupportFunctionT< Number, Converter< Number >, SFSetting > hypro::Converter< Number >::toSupportFunction (const Ellipsoid & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 41 of file converterToSupportFunction.tpp.
References hypro::EllipsoidT< Number, Converter >::matrix().
template<typename Number > template<typename SFSetting , typename inSetting > SupportFunctionT< Number, Converter< Number >, SFSetting > hypro::Converter< Number >::toSupportFunction (const HPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 56 of file converterToSupportFunction.tpp.
template<typename Number > template<typename SFSetting , typename inSetting > SupportFunctionT< Number, Converter< Number >, SFSetting > hypro::Converter< Number >::toSupportFunction (const VPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::EXACT) static
Definition at line 48 of file converterToSupportFunction.tpp.
template<typename Number > template<typename SFSetting , typename inSetting > SupportFunctionT< Number, Converter< Number >, SFSetting > hypro::Converter< Number >::toSupportFunction (const PolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 76 of file converterToSupportFunction.tpp.
template<typename Number > template<typename SFSetting , typename inSetting > SupportFunctionT< Number, Converter< Number >, SFSetting > hypro::Converter< Number >::toSupportFunction (const SupportFunctionT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 21 of file converterToSupportFunction.tpp.
template<typename Number > template<typename SFSetting , typename inSetting > SupportFunctionT< Number, Converter< Number >, SFSetting > hypro::Converter< Number >::toSupportFunction (const ZonotopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 63 of file converterToSupportFunction.tpp.
template<typename Number > template<typename SFSetting , typename inSetting > SupportFunctionT< Number, Converter< Number >, SFSetting > hypro::Converter< Number >::toSupportFunction (const DifferenceBoundsT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::EXACT) static
Definition at line 84 of file converterToSupportFunction.tpp.
template<typename Number > template<typename SFSetting , typename inSetting > SupportFunctionT< Number, Converter< Number >, SFSetting > hypro::Converter< Number >::toSupportFunction (const CarlPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 90 of file converterToSupportFunction.tpp.
template<typename Number > template<typename SFSetting , typename inSetting > SupportFunctionT< Number, Converter< Number >, SFSetting > hypro::Converter< Number >::toSupportFunction (const SupportFunctionNewT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::UNDER) static
Definition at line 109 of file converterToSupportFunction.tpp.
template<typename Number > template<typename SFNSetting , typename inSetting > SupportFunctionNewT< Number, Converter< Number >, SFNSetting > hypro::Converter< Number >::toSupportFunctionNew (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 102 of file converterToSupportFunctionNew.tpp.
template<typename Number > template<typename SFNSetting , typename inSetting > SupportFunctionNewT< Number, Converter< Number >, SFNSetting > hypro::Converter< Number >::toSupportFunctionNew (const BoxT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 19 of file converterToSupportFunctionNew.tpp.
template<typename Number > template<typename SFNSetting , typename inSetting > SupportFunctionNewT< Number, Converter< Number >, SFNSetting > hypro::Converter< Number >::toSupportFunctionNew (const ConstraintSetT< Number, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 26 of file converterToSupportFunctionNew.tpp.
References hypro::SupportFunctionNewT< Number, Converter, Setting >::getRoot(), hypro::ConstraintSetT< Number, S >::matrix(), and hypro::ConstraintSetT< Number, S >::vector().
template<typename Number > template<typename SFNSetting > SupportFunctionNewT< Number, Converter< Number >, SFNSetting > hypro::Converter< Number >::toSupportFunctionNew (const Ellipsoid & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 38 of file converterToSupportFunctionNew.tpp.
template<typename Number > template<typename SFNSetting , typename inSetting > SupportFunctionNewT< Number, Converter< Number >, SFNSetting > hypro::Converter< Number >::toSupportFunctionNew (const HPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 45 of file converterToSupportFunctionNew.tpp.
template<typename Number > template<typename SFNSetting , typename inSetting > SupportFunctionNewT< Number, Converter< Number >, SFNSetting > hypro::Converter< Number >::toSupportFunctionNew (const VPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 59 of file converterToSupportFunctionNew.tpp.
template<typename Number > template<typename SFNSetting , typename inSetting > SupportFunctionNewT< Number, Converter< Number >, SFNSetting > hypro::Converter< Number >::toSupportFunctionNew (const PolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 74 of file converterToSupportFunctionNew.tpp.
template<typename Number > template<typename SFNSetting , typename inSetting > SupportFunctionNewT< Number, Converter< Number >, SFNSetting > hypro::Converter< Number >::toSupportFunctionNew (const SupportFunctionT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 82 of file converterToSupportFunctionNew.tpp.
template<typename Number > template<typename SFNSetting , typename inSetting > SupportFunctionNewT< Number, Converter< Number >, SFNSetting > hypro::Converter< Number >::toSupportFunctionNew (const ZonotopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 89 of file converterToSupportFunctionNew.tpp.
template<typename Number > template<typename SFNSetting , typename inSetting > SupportFunctionNewT< Number, Converter< Number >, SFNSetting > hypro::Converter< Number >::toSupportFunctionNew (const DifferenceBoundsT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 66 of file converterToSupportFunctionNew.tpp.
template<typename Number > template<typename SFNSetting , typename inSetting > SupportFunctionNewT< Number, Converter< Number >, SFNSetting > hypro::Converter< Number >::toSupportFunctionNew (const CarlPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 96 of file converterToSupportFunctionNew.tpp.
template<typename Number > template<typename SFNSetting , typename inSetting > SupportFunctionNewT< Number, Converter< Number >, SFNSetting > hypro::Converter< Number >::toSupportFunctionNew (const SupportFunctionNewT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 12 of file converterToSupportFunctionNew.tpp.
template<typename Number > template<typename TemplatePolyhedronSetting , typename inSetting > TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > hypro::Converter< Number >::toTemplatePolyhedron (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 9 of file converterToTemplatePolyhedron.tpp.
template<typename Number > template<typename TemplatePolyhedronSetting , typename inSetting > TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > hypro::Converter< Number >::toTemplatePolyhedron (const BoxT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 15 of file converterToTemplatePolyhedron.tpp.
template<typename Number > template<typename TemplatePolyhedronSetting , typename inSetting > TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > hypro::Converter< Number >::toTemplatePolyhedron (const CarlPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 21 of file converterToTemplatePolyhedron.tpp.
template<typename Number > template<typename TemplatePolyhedronSetting , typename inSetting > TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > hypro::Converter< Number >::toTemplatePolyhedron (const ConstraintSetT< Number, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 27 of file converterToTemplatePolyhedron.tpp.
References hypro::ConstraintSetT< Number, S >::matrix(), and hypro::ConstraintSetT< Number, S >::vector().
template<typename Number > template<typename TemplatePolyhedronSetting > TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > hypro::Converter< Number >::toTemplatePolyhedron (const Ellipsoid & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 33 of file converterToTemplatePolyhedron.tpp.
template<typename Number > template<typename TemplatePolyhedronSetting , typename inSetting > TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > hypro::Converter< Number >::toTemplatePolyhedron (const HPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 40 of file converterToTemplatePolyhedron.tpp.
template<typename Number > template<typename TemplatePolyhedronSetting , typename inSetting > TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > hypro::Converter< Number >::toTemplatePolyhedron (const VPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 46 of file converterToTemplatePolyhedron.tpp.
template<typename Number > template<typename TemplatePolyhedronSetting , typename inSetting > TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > hypro::Converter< Number >::toTemplatePolyhedron (const DifferenceBoundsT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 53 of file converterToTemplatePolyhedron.tpp.
template<typename Number > template<typename TemplatePolyhedronSetting , typename inSetting > TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > hypro::Converter< Number >::toTemplatePolyhedron (const PolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 61 of file converterToTemplatePolyhedron.tpp.
template<typename Number > template<typename TemplatePolyhedronSetting , typename inSetting > TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > hypro::Converter< Number >::toTemplatePolyhedron (const SupportFunctionT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 69 of file converterToTemplatePolyhedron.tpp.
template<typename Number > template<typename TemplatePolyhedronSetting , typename inSetting > TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > hypro::Converter< Number >::toTemplatePolyhedron (const SupportFunctionNewT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 75 of file converterToTemplatePolyhedron.tpp.
template<typename Number > template<typename TemplatePolyhedronSetting , typename inSetting > TemplatePolyhedronT< Number, Converter< Number >, TemplatePolyhedronSetting > hypro::Converter< Number >::toTemplatePolyhedron (const ZonotopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 81 of file converterToTemplatePolyhedron.tpp.
template<typename Number > template<typename VPolySetting , typename inSetting > VPolytopeT< Number, Converter< Number >, VPolySetting > hypro::Converter< Number >::toVPolytope (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 354 of file converterToVPolytope.tpp.
Referenced by hypro::HPolytopeT< Number, Converter, Setting >::affineTransformation(), hypro::VPolytopeT< Number, Converter, S >::intersectHalfspace(), hypro::VPolytopeT< Number, Converter, S >::intersectHalfspaces(), hypro::CarlPolytopeT< Number, Converter, Setting >::linearTransformation(), hypro::HPolytopeT< Number, Converter, Setting >::linearTransformation(), hypro::VPolytopeT< Number, Converter, S >::satisfiesHalfspace(), and hypro::VPolytopeT< Number, Converter, S >::satisfiesHalfspaces().
template<typename Number > template<typename VPolySetting , typename inSetting > VPolytopeT< Number, Converter< Number >, VPolySetting > hypro::Converter< Number >::toVPolytope (const BoxT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 213 of file converterToVPolytope.tpp.
template<typename Number > template<typename VPolySetting , typename inSetting > VPolytopeT< Number, Converter< Number >, VPolySetting > hypro::Converter< Number >::toVPolytope (const ConstraintSetT< Number, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 155 of file converterToVPolytope.tpp.
References hypro::ConstraintSetT< Number, S >::matrix(), and hypro::ConstraintSetT< Number, S >::vector().
template<typename Number > template<typename VPolySetting > VPolytopeT< Number, Converter< Number >, VPolySetting > hypro::Converter< Number >::toVPolytope (const Ellipsoid & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 161 of file converterToVPolytope.tpp.
References hypro::EllipsoidT< Number, Converter >::dimension(), and hypro::EllipsoidT< Number, Converter >::evaluate().
template<typename Number > template<typename VPolySetting , typename inSetting > VPolytopeT< Number, Converter< Number >, VPolySetting > hypro::Converter< Number >::toVPolytope (const HPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 205 of file converterToVPolytope.tpp.
template<typename Number > template<typename VPolySetting , typename inSetting > VPolytopeT< Number, Converter< Number >, VPolySetting > hypro::Converter< Number >::toVPolytope (const VPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 149 of file converterToVPolytope.tpp.
template<typename Number > template<typename VPolySetting , typename inSetting > VPolytopeT< Number, Converter< Number >, VPolySetting > hypro::Converter< Number >::toVPolytope (const PolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 333 of file converterToVPolytope.tpp.
template<typename Number > template<typename VPolySetting , typename inSetting > VPolytopeT< Number, Converter< Number >, VPolySetting > hypro::Converter< Number >::toVPolytope (const SupportFunctionT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::UNDER, std::size_t numberOfDirections = defaultTemplateDirectionCount) static
Definition at line 229 of file converterToVPolytope.tpp.
References hypro::ALTERNATIVE, hypro::computeBoundaryPointsExpensive(), hypro::VPolytopeT< Number, Converter, S >::dimension(), hypro::INFTY, hypro::OVER, and hypro::UNDER.
template<typename Number > template<typename VPolySetting , typename inSetting > VPolytopeT< Number, Converter< Number >, VPolySetting > hypro::Converter< Number >::toVPolytope (const ZonotopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 220 of file converterToVPolytope.tpp.
template<typename Number > template<typename VPolySetting , typename inSetting > VPolytopeT< Number, Converter< Number >, VPolySetting > hypro::Converter< Number >::toVPolytope (const DifferenceBoundsT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::EXACT) static
Definition at line 340 of file converterToVPolytope.tpp.
template<typename Number > template<typename VPolySetting , typename inSetting > VPolytopeT< Number, Converter< Number >, VPolySetting > hypro::Converter< Number >::toVPolytope (const CarlPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 347 of file converterToVPolytope.tpp.
template<typename Number > template<typename VPolySetting , typename inSetting > VPolytopeT< Number, Converter< Number >, VPolySetting > hypro::Converter< Number >::toVPolytope (const SupportFunctionNewT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::UNDER, std::size_t numberOfDirections = defaultTemplateDirectionCount) static
Definition at line 501 of file converterToVPolytope.tpp.
References hypro::ALTERNATIVE, hypro::computeBoundaryPointsExpensive(), hypro::VPolytopeT< Number, Converter, S >::dimension(), hypro::INFTY, hypro::OVER, and hypro::UNDER.
template<typename Number > template<typename ZonotopeSetting , typename inSetting > ZonotopeT< Number, Converter< Number >, ZonotopeSetting > hypro::Converter< Number >::toZonotope (const TemplatePolyhedronT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::EXACT) static
Definition at line 645 of file converterToZonotope.tpp.
Referenced by hypro::Converter< Number >::toZonotope().
template<typename Number > template<typename ZonotopeSetting , typename inSetting > ZonotopeT< Number, Converter< Number >, ZonotopeSetting > hypro::Converter< Number >::toZonotope (const BoxT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 108 of file converterToZonotope.tpp.
template<typename Number > template<typename ZonotopeSetting , typename inSetting > ZonotopeT< Number, Converter< Number >, ZonotopeSetting > hypro::Converter< Number >::toZonotope (const CarlPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::OVER) static
Definition at line 83 of file converterToZonotope.tpp.
template<typename Number > template<typename ZonotopeSetting , typename inSetting > ZonotopeT< Number, Converter< Number >, ZonotopeSetting > hypro::Converter< Number >::toZonotope (const ConstraintSetT< Number, inSetting > & source, const CONV_MODE mode = CONV_MODE::EXACT) static
Definition at line 95 of file converterToZonotope.tpp.
template<typename Number > template<typename ZonotopeSetting > ZonotopeT< Number, Converter< Number >, ZonotopeSetting > hypro::Converter< Number >::toZonotope (const Ellipsoid & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 47 of file converterToZonotope.tpp.
template<typename Number > template<typename ZonotopeSetting , typename inSetting > ZonotopeT< Number, Converter< Number >, ZonotopeSetting > hypro::Converter< Number >::toZonotope (const HPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::OVER) static
Definition at line 71 of file converterToZonotope.tpp.
template<typename Number > template<typename ZonotopeSetting , typename inSetting > ZonotopeT< Number, Converter< Number >, ZonotopeSetting > hypro::Converter< Number >::toZonotope (const VPolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::OVER) static
Definition at line 128 of file converterToZonotope.tpp.
References hypro::PrincipalComponentAnalysis< Number >::box(), hypro::computeArithmeticMeanPoint(), fReach_DENOMINATOR, and hypro::VPolytopeT< Number, Converter, S >::vertices().
template<typename Number > template<typename ZonotopeSetting , typename inSetting > ZonotopeT< Number, Converter< Number >, ZonotopeSetting > hypro::Converter< Number >::toZonotope (const PolytopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::EXACT) static
Definition at line 429 of file converterToZonotope.tpp.
References hypro::Converter< Number >::toZonotope().
template<typename Number > template<typename ZonotopeSetting , typename inSetting > ZonotopeT< Number, Converter< Number >, ZonotopeSetting > hypro::Converter< Number >::toZonotope (const SupportFunctionT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::OVER, std::size_t numberOfDirections = defaultTemplateDirectionCount) static
Definition at line 225 of file converterToZonotope.tpp.
References hypro::ALTERNATIVE, hypro::PrincipalComponentAnalysis< Number >::box(), hypro::computeArithmeticMeanPoint(), hypro::ZonotopeT< Number, Converter, Setting >::dimension(), fReach_DENOMINATOR, hypro::INFTY, hypro::OVER, and hypro::VPolytopeT< Number, Converter, S >::vertices().
template<typename Number > template<typename ZonotopeSetting , typename inSetting > ZonotopeT< Number, Converter< Number >, ZonotopeSetting > hypro::Converter< Number >::toZonotope (const ZonotopeT< Number, Converter< Number >, inSetting > & source, const CONV_MODE = CONV_MODE::EXACT) static
Definition at line 41 of file converterToZonotope.tpp.
template<typename Number > template<typename ZonotopeSetting , typename inSetting > ZonotopeT< Number, Converter< Number >, ZonotopeSetting > hypro::Converter< Number >::toZonotope (const DifferenceBoundsT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::OVER) static
Definition at line 437 of file converterToZonotope.tpp.
template<typename Number > template<typename ZonotopeSetting , typename inSetting > ZonotopeT< Number, Converter< Number >, ZonotopeSetting > hypro::Converter< Number >::toZonotope (const SupportFunctionNewT< Number, Converter< Number >, inSetting > & source, const CONV_MODE mode = CONV_MODE::OVER, std::size_t numberOfDirections = defaultTemplateDirectionCount) static
Definition at line 443 of file converterToZonotope.tpp.
References hypro::ALTERNATIVE, hypro::PrincipalComponentAnalysis< Number >::box(), hypro::computeArithmeticMeanPoint(), hypro::ZonotopeT< Number, Converter, Setting >::dimension(), fReach_DENOMINATOR, hypro::INFTY, hypro::OVER, and hypro::VPolytopeT< Number, Converter, S >::vertices().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/representations/conversion/Converter.h
/home/travis/build/hypro/hypro/src/hypro/representations/conversion/converterToBox.tpp
/home/travis/build/hypro/hypro/src/hypro/representations/conversion/converterToCarlPolytope.tpp
/home/travis/build/hypro/hypro/src/hypro/representations/conversion/converterToConstraintSet.tpp
/home/travis/build/hypro/hypro/src/hypro/representations/conversion/converterToDifferenceBounds.tpp
/home/travis/build/hypro/hypro/src/hypro/representations/conversion/converterToHPolytope.tpp
/home/travis/build/hypro/hypro/src/hypro/representations/conversion/converterToPolytope.tpp
/home/travis/build/hypro/hypro/src/hypro/representations/conversion/converterToSupportFunction.tpp
/home/travis/build/hypro/hypro/src/hypro/representations/conversion/converterToSupportFunctionNew.tpp
/home/travis/build/hypro/hypro/src/hypro/representations/conversion/converterToTemplatePolyhedron.tpp
/home/travis/build/hypro/hypro/src/hypro/representations/conversion/converterToVPolytope.tpp
/home/travis/build/hypro/hypro/src/hypro/representations/conversion/converterToZonotope.tpp