HyPro: hypro::IHandler Class Reference
hypro::IHandler Class Reference abstract
#include <IHandler.h>
Public Member Functions
virtual void handle ()=0
virtual const char * handlerName ()=0
Detailed Description
Definition at line 7 of file IHandler.h.
Member Function Documentation
virtual void hypro::IHandler::handle () pure virtual
Implemented in hypro::IJumpHandler, hypro::IResetHandler, hypro::ITimeEvolutionHandler, hypro::IGuardHandler< State >, hypro::ltiJumpHandler< State >, hypro::IBadStateHandler, hypro::ltiGuardHandler< State >, hypro::rectangularGuardHandler< State >, hypro::rectangularTimeEvolutionHandler< State >, hypro::ltiTimeEvolutionHandler< State >, hypro::ltiFirstSegmentHandler< State >, hypro::timedElapseAfterTickTimeEvolutionHandler< State >, hypro::IInvariantHandler, hypro::ltiResetHandler< State >, hypro::ltiBadStateHandler< State >, hypro::timedElapseTimeEvolutionHandler< State >, hypro::rectangularBadStateHandler< State >, hypro::timedGuardHandler< State >, hypro::ltiInvariantHandler< State >, hypro::rectangularResetHandler< State >, hypro::rectangularInvariantHandler< State >, hypro::discreteGuardHandler< State >, hypro::rectangularFirstSegmentHandler< State >, hypro::IFirstSegmentHandler< State >, hypro::timedTickTimeEvolutionHandler< State >, hypro::timedBadStateHandler< State >, hypro::timedElapseFirstSegmentHandler< State >, hypro::timedFirstSegmentHandler< State >, hypro::timedInvariantHandler< State >, hypro::discreteResetHandler< State >, hypro::timedResetHandler< State >, hypro::discreteBadStateHandler< State >, hypro::discreteInvariantHandler< State >, and hypro::discreteTimeEvolutionHandler.
Referenced by hypro::IBadStateHandler::~IBadStateHandler(), hypro::IFirstSegmentHandler< State >::~IFirstSegmentHandler(), hypro::IGuardHandler< State >::~IGuardHandler(), hypro::IInvariantHandler::~IInvariantHandler(), hypro::IJumpHandler::~IJumpHandler(), hypro::IResetHandler::~IResetHandler(), and hypro::ITimeEvolutionHandler::~ITimeEvolutionHandler().
virtual const char* hypro::IHandler::handlerName () pure virtual
Implemented in hypro::IJumpHandler, hypro::IResetHandler, hypro::ITimeEvolutionHandler, hypro::IGuardHandler< State >, hypro::ltiJumpHandler< State >, hypro::IBadStateHandler, hypro::ltiGuardHandler< State >, hypro::rectangularGuardHandler< State >, hypro::rectangularTimeEvolutionHandler< State >, hypro::ltiTimeEvolutionHandler< State >, hypro::ltiFirstSegmentHandler< State >, hypro::timedElapseAfterTickTimeEvolutionHandler< State >, hypro::IInvariantHandler, hypro::ltiResetHandler< State >, hypro::ltiBadStateHandler< State >, hypro::timedElapseTimeEvolutionHandler< State >, hypro::rectangularBadStateHandler< State >, hypro::timedGuardHandler< State >, hypro::ltiInvariantHandler< State >, hypro::rectangularResetHandler< State >, hypro::discreteGuardHandler< State >, hypro::rectangularInvariantHandler< State >, hypro::rectangularFirstSegmentHandler< State >, hypro::IFirstSegmentHandler< State >, hypro::timedTickTimeEvolutionHandler< State >, hypro::timedBadStateHandler< State >, hypro::timedElapseFirstSegmentHandler< State >, hypro::timedFirstSegmentHandler< State >, hypro::timedInvariantHandler< State >, hypro::discreteResetHandler< State >, hypro::timedResetHandler< State >, hypro::discreteBadStateHandler< State >, hypro::discreteInvariantHandler< State >, and hypro::discreteTimeEvolutionHandler.
Referenced by hypro::IBadStateHandler::~IBadStateHandler(), hypro::IFirstSegmentHandler< State >::~IFirstSegmentHandler(), hypro::IGuardHandler< State >::~IGuardHandler(), hypro::IInvariantHandler::~IInvariantHandler(), hypro::IJumpHandler::~IJumpHandler(), hypro::IResetHandler::~IResetHandler(), and hypro::ITimeEvolutionHandler::~ITimeEvolutionHandler().
The documentation for this class was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/IHandler.h