HyPro: hypro::Dictionary< Number > Class Template Reference
hypro::Dictionary< Number > Class Template Reference
Public Member Functions
Dictionary (const Dictionary &rhs)
Dictionary (const matrix_t< Number > &rhs, std::vector< Eigen::Index > base, std::vector< Eigen::Index > cobase)
Dictionary (const matrix_t< Number > &rhs, std::vector< Eigen::Index > base, std::vector< Eigen::Index > cobase, ConstrainSet< Number > constrains)
Dictionary (const std::vector< Halfspace< Number >> &hsv)
Build a dictionary with mDictionary=rhs, mB=base and mN=cobase.
std::vector< Eigen::Index > basis () const
Build a dictionary based on the hyperplane set hsv.
std::vector< Eigen::Index > cobasis () const
ConstrainSet< Number > constrainSet () const
matrix_t< Number > tableau () const
Number get (Eigen::Index i, Eigen::Index j) const
void setValue (Eigen::Index i, Eigen::Index j, Number val)
set mDicionary(i,j) to val.
void printDictionary () const
void pivotDictionary (Eigen::Index i, Eigen::Index j)
Pivot expected ‘)’ before ‘<’ tokenthe dictionary, no modification made to mB and mN.
void pivot (Eigen::Index i, Eigen::Index j)
The whole pivot.
bool selectCrissCrossPivot (Eigen::Index &i, Eigen::Index &j)
Selects the next pivot according to CrissCross's rule.
bool fixOutOfBounds ()
Check for the satisfiability of the dictionary and finds a suitable assignment.
bool selectBlandPivot (Eigen::Index &i, Eigen::Index &j) const
Puts in i and j the pivot, returns false iff none was sutable.
bool selectDualBlandPivot (Eigen::Index &i, Eigen::Index &j, const std::vector< Eigen::Index > availableIndices)
bool isPrimalFeasible () const
bool isDualFeasible () const
bool isOptimal () const
bool reverse (const Eigen::Index i, const Eigen::Index j)
is (i,j) the pivot given by the Bland's rule for the dictionary obtained by pivoting around (i,j).
bool reverse_old (const Eigen::Index i, const Eigen::Index j)
bool reverseDual (const Eigen::Index i, const Eigen::Index j, const std::vector< Eigen::Index > &availableIndices)
bool reverseDual_old (const Eigen::Index i, const Eigen::Index j, const std::vector< Eigen::Index > availableIndices)
bool isLexMin ()
Point< Number > toPoint () const
std::vector< Eigen::Index > findZeros ()
gives the list of the degenerated constrains in the dictionary.
void setOnes (const std::vector< Eigen::Index > &indices)
put 1 in the last column for the indices provided by
void setZeros (const std::vector< Eigen::Index > &indices)
void nonSlackToBase ()
Puts the non slack variable to the basis.
void nonSlackToBase (std::vector< vector_t< Number >> &linealtySpace)
std::set< Eigen::Index > toCobase (const std::set< Eigen::Index > &saturatedIndices)
Puts the saturated variable to the cobasis.
void pushToBounds (Eigen::Index colIndex)
Tries to push the corresponding variable to its bound, if another bound is reached before, pivot around the later.
std::set< vector_t< Number > > findCones ()
Friends
bool operator== (const Dictionary< Number > &lhs, const Dictionary< Number > &rhs)
bool operator!= (const Dictionary< Number > &lhs, const Dictionary< Number > &rhs)
std::ostream & operator<< (std::ostream &_ostr, const Dictionary< Number > &d)
Detailed Description
template<typename Number>
class hypro::Dictionary< Number >
Definition at line 26 of file Dictionary.h.
Member Function Documentation
template<typename Number > bool hypro::Dictionary< Number >::fixOutOfBounds ()
Check for the satisfiability of the dictionary and finds a suitable assignment.
Checks if variables are out of bound. If yes, tries to find a suitable pivot to fix this. If there is none throws exception (empty set). If a suitable pivot is found, apply pivot step and update assignment.
Returns
True, if assignment has been updated.
Definition at line 199 of file Dictionary.tpp.
References hypro::Dictionary< Number >::pivot().
Referenced by hypro::VertexEnumeration< Number >::findFirstVertex().
template<typename Number > Number hypro::Dictionary< Number >::get (Eigen::Index i, Eigen::Index j) const
Returns
the number in the cell (i,j) of mDictionary.
Definition at line 102 of file Dictionary.tpp.
Referenced by hypro::VertexEnumeration< Number >::enumerateDictionaries().
template<typename Number > bool hypro::Dictionary< Number >::selectCrissCrossPivot (Eigen::Index & i, Eigen::Index & j)
Selects the next pivot according to CrissCross's rule.
Parameters
i The reference for the proposed row index.
j The reference for the proposed column index.
Returns
True, if there is a valid pivot.
Definition at line 310 of file Dictionary.tpp.
References hypro::Dictionary< Number >::pivot(), and hypro::Dictionary< Number >::selectBlandPivot().
template<typename Number > bool hypro::Dictionary< Number >::selectDualBlandPivot (Eigen::Index & i, Eigen::Index & j, const std::vector< Eigen::Index > availableIndices)
Parameters
available indices is the set of indices the pivot is allowed to pick in.
Definition at line 272 of file Dictionary.tpp.
Referenced by hypro::VertexEnumeration< Number >::enumerateDictionaries(), and hypro::Dictionary< Number >::reverse().
template<typename Number > void hypro::Dictionary< Number >::setOnes (const std::vector< Eigen::Index > & indices)
put 1 in the last column for the indices provided by
Parameters
indices.
Definition at line 545 of file Dictionary.tpp.
References hypro::Dictionary< Number >::nonSlackToBase(), and hypro::Dictionary< Number >::pivot().
Referenced by hypro::VertexEnumeration< Number >::enumerateDictionaries().
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/convexHull/Dictionary.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/convexHull/Dictionary.tpp