HyPro: hypro::rectangularBadStateHandler< State > Class Template Reference
hypro::rectangularBadStateHandler< State > Class Template Reference
Public Member Functions
rectangularBadStateHandler ()=delete
rectangularBadStateHandler (State &state, size_t index)
void handle ()
const char * handlerName ()
virtual bool intersectsBadState () override
virtual bool getMarkedForDelete () override
virtual void setMarkedForDelete (bool toDelete) override
Public Member Functions inherited from hypro::IBadStateHandler
virtual ~IBadStateHandler ()
Protected Attributes
State & mState
size_t mIndex
CONTAINMENT mContainment = CONTAINMENT::NO
bool mNoBadStates = false
bool mMarkedForDelete = false
Detailed Description
template<typename State>
class hypro::rectangularBadStateHandler< State >
Definition at line 6 of file rectangularBadStateHandler.h.
Constructor & Destructor Documentation
template<typename State > hypro::rectangularBadStateHandler< State >::rectangularBadStateHandler () delete
template<typename State > hypro::rectangularBadStateHandler< State >::rectangularBadStateHandler (State & state, size_t index) inline
Definition at line 18 of file rectangularBadStateHandler.h.
References hypro::rectangularBadStateHandler< State >::handle().
Member Function Documentation
template<typename State > virtual bool hypro::rectangularBadStateHandler< State >::getMarkedForDelete () inline override virtual
Implements hypro::IBadStateHandler.
Definition at line 27 of file rectangularBadStateHandler.h.
References hypro::rectangularBadStateHandler< State >::mMarkedForDelete.
template<typename State > void hypro::rectangularBadStateHandler< State >::handle () virtual
Implements hypro::IBadStateHandler.
Definition at line 5 of file rectangularBadStateHandler.tpp.
References hypro::SettingsProvider< State >::getHybridAutomaton(), hypro::NO, and hypro::YES.
Referenced by hypro::rectangularBadStateHandler< State >::rectangularBadStateHandler().
template<typename State > const char* hypro::rectangularBadStateHandler< State >::handlerName () inline virtual
Implements hypro::IBadStateHandler.
Definition at line 23 of file rectangularBadStateHandler.h.
template<typename State > virtual bool hypro::rectangularBadStateHandler< State >::intersectsBadState () inline override virtual
Implements hypro::IBadStateHandler.
Definition at line 25 of file rectangularBadStateHandler.h.
References hypro::NO.
template<typename State > virtual void hypro::rectangularBadStateHandler< State >::setMarkedForDelete (bool toDelete) inline override virtual
Implements hypro::IBadStateHandler.
Definition at line 28 of file rectangularBadStateHandler.h.
Member Data Documentation
template<typename State > CONTAINMENT hypro::rectangularBadStateHandler< State >::mContainment = CONTAINMENT::NO protected
Definition at line 12 of file rectangularBadStateHandler.h.
template<typename State > size_t hypro::rectangularBadStateHandler< State >::mIndex protected
Definition at line 11 of file rectangularBadStateHandler.h.
template<typename State > bool hypro::rectangularBadStateHandler< State >::mMarkedForDelete = false protected
Definition at line 14 of file rectangularBadStateHandler.h.
Referenced by hypro::rectangularBadStateHandler< State >::getMarkedForDelete().
template<typename State > bool hypro::rectangularBadStateHandler< State >::mNoBadStates = false protected
Definition at line 13 of file rectangularBadStateHandler.h.
template<typename State > State& hypro::rectangularBadStateHandler< State >::mState protected
Definition at line 10 of file rectangularBadStateHandler.h.
The documentation for this class was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/badStateHandlers/rectangularBadStateHandler.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/badStateHandlers/rectangularBadStateHandler.tpp