HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/CompareMHyProAndCORA/compareZonotopeFunctions.m File Reference
compareZonotopeFunctions.m File Reference
Functions
function compareZonotopeFunctions ()%This file contains the comparison of zonotope functions for mhypro and%cora.%dim1
assert (isequal(mh_c, cora_c))
assert (isequal(mh_g, cora_g))
disp ('---------------------------------------')
disp ('Minkowski sum')
disp (['MHyPro needed: ', num2str(stop_mh), 's'])
disp (' ')
disp ('center')
disp ('generators')
assert (isequal(mh_center, cora_center))
assert (isequal(mh_generators, cora_generators))
disp ('unite')
disp ('Satisfies halfspace/constraint')
disp ('Contains Point')
assert (mh_out==cora_out)
disp ('Contains Zonotope')
disp ('emptiness test')
disp ('unite equal vectors/delete aligned')
mh_z4 uniteEqualVectors ()
disp ('remove empty generators/delete zeros')
mh_z1 removeEmptyGenerators ()
disp ('vertices')
disp ('reduce order/reduce')
mh_z6 reduceOrder (2)
cora_z6 reduce ('girard', 1)
Variables
dim2 = 10
range_min = -100
range_max = 100
generators1 = randi([range_min range_max], dim1 , dim2)
center1 = randi([range_min range_max], dim1 , 1)
generators2 = [-24 74 -13 -25 -97 8 44 -45 -30 86
center2 = [ -97
mh_z1 = MHyProZonotope(center1, generators1)
cora_z1 = zonotope([center1, generators1])
mh_c = mh_z1.center()
cora_c = cora_z1.center()
mh_g = mh_z1.generators()
cora_g = cora_z1.generators()
mh_z2 = MHyProZonotope(center2, generators2)
cora_z2 = zonotope([center2, generators2])
tic
mh_ms = mh_z1 + mh_z2
stop_mh = toc
cora_ms = cora_z1 + cora_z2
stop_cora = toc
mh_center = mh_ms.center()
stop = toc
cora_center = cora_ms.center()
mh_generators = mh_ms.generators()
cora_generators = cora_ms.generators()
mh_z_united = mh_z1.unite(mh_z2)
cora_z_encl = enclose(cora_z1, cora_z2)
C = [-107 -182 814 549 -771 67 -791 120 -422 -459
d = [484
generators3 = [508 251 -562 -406 851 -88 161 328 -488 349
center3 = [-101
mh_z3 = MHyProZonotope(center3, generators3)
cora_z3 = zonotope([center3, generators3])
out = cora_z3.constrSat(C,d)
gen_point = [1 0 1 0 1
cen_point = [2
mh_point = MHyProZonotope(cen_point, gen_point)
cora_point = zonotope([cen_point, gen_point])
point = [4
mh_out = mh_point.contains(point)
cora_out = cora_point.containsPoint(point)
gen1 = [1 0 0
gen2 = [10 0 0
cen = [2
gen3 = [1 0 1 0 1
mh_z4 = MHyProZonotope(cen, gen3)
cora_z4 = zonotope([cen, gen3])
gen4 = [1 0 0
mh_v = mh_z2.vertices()
cora_v = cora_z2.vertices()
gen6 = [-10 6 -13 17 -9 -8 7 9 -6 5
cen6 = [1
mh_z6 = MHyProZonotope(cen6, gen6)
cora_z6 = zonotope([cen6, gen6])
mh_order = mh_z6.order()
cora_gen = cora_z6.generators()
cora_order = size(cora_gen,2) / 4
Function Documentation
assert (isequal(mh_c, cora_c))
Referenced by hypro::VariablePool::addCarlVariable(), hypro::TreeNode< ReachTreeNode< State > >::addChild(), hypro::ConstraintSetT< Number >::addConstraint(), hypro::Facet< Number >::addNeighbor(), hypro::linearFlow< N >::addRow(), hypro::CarlPolytopeT< Number, Converter, Setting >::affineTransformation(), hypro::SumOp< Number, Converter, Setting >::aggregate(), hypro::UnionOp< Number, Converter, Setting >::aggregate(), hypro::ScaleOp< Number, Converter, Setting >::aggregate(), hypro::IntersectHalfspaceOp< Number, Converter, Setting >::aggregate(), hypro::IntersectOp< Number, Converter, Setting >::aggregate(), hypro::ProjectOp< Number, Converter, Setting >::aggregate(), hypro::Leaf< Number, Converter, Setting, Representation >::aggregate(), hypro::TrafoOp< Number, Converter, Setting >::aggregate(), hypro::appendRow(), hypro::applyReset(), hypro::BoxT< Number, hypro::Converter, Setting >::BoxT(), hypro::NeighborhoodContainer::calculateNeighborhood(), hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT(), hypro::VariablePool::carlVarByIndex(), hypro::VariablePool::carlVariables(), hypro::SupportFunctionContent< Number, Setting >::checkTreeValidity(), CLANG_WARNING_DISABLE(), hypro::VariablePool::clear(), hypro::Point< int >::coeffWiseMax(), hypro::Point< int >::coeffWiseMin(), hypro::UnionOp< Number, Converter, Setting >::compute(), hypro::SumOp< Number, Converter, Setting >::compute(), hypro::ScaleOp< Number, Converter, Setting >::compute(), hypro::IntersectHalfspaceOp< Number, Converter, Setting >::compute(), hypro::IntersectOp< Number, Converter, Setting >::compute(), hypro::ProjectOp< Number, Converter, Setting >::compute(), hypro::Leaf< Number, Converter, Setting, Representation >::compute(), hypro::TrafoOp< Number, Converter, Setting >::compute(), hypro::reachability::computeFirstSegment(), hypro::computeHalfspaces(), hypro::constraintNormal(), hypro::CarlPolytopeT< Number, Converter, Setting >::contains(), hypro::ProjectOp< Number, Converter, Setting >::contains(), hypro::ScaleOp< Number, Converter, Setting >::contains(), hypro::RootGrowNode< Number, Converter, Setting >::contains(), hypro::TrafoOp< Number, Converter, Setting >::contains(), hypro::ConstraintSetT< Number >::contains(), hypro::ZonotopeT< Number, Converter, Setting >::contains(), hypro::IntersectHalfspaceOp< Number, Converter, Setting >::contains(), hypro::convert(), hypro::convertSettings(), hypro::SupportFunctionContent< Number, Setting >::create(), hypro::nodeUpdater< State >::createAndRaiseRefinementTask(), hypro::nodeUpdater< State >::createAndRaiseTask(), hypro::detail::createMatrix(), hypro::LinTrafoParameters< Number, Setting >::createNextReduct(), hypro::lintrafoParameters< Number >::createNextReduct(), hypro::pointIt< Number >::current(), hypro::glpk_context::deleteLPInstance(), hypro::dispatch(), hypro::Dispatcher_i< Representation >::dispatch(), hypro::VPolytopeT< Number, Converter, S >::emplace_back(), hypro::ProjectOp< Number, Converter, Setting >::empty(), hypro::ScaleOp< Number, Converter, Setting >::empty(), hypro::RootGrowNode< Number, Converter, Setting >::empty(), hypro::BoxT< Number, hypro::Converter, Setting >::Empty(), hypro::TrafoOp< Number, Converter, Setting >::empty(), hypro::IntersectHalfspaceOp< Number, Converter, Setting >::empty(), hypro::errorBoxes(), hypro::CarlPolytopeT< Number, Converter, Setting >::evaluate(), hypro::extractSolution(), hypro::Facet< Number >::Facet(), hypro::FourierMotzkinQE< Number >::FourierMotzkinQE(), hypro::Fan< Number >::get(), hypro::TreeNode< ReachTreeNode< State > >::getDepth(), hypro::getEnabledTimings(), hypro::rectangularFlow< N >::getFlowIntervalForDimension(), hypro::Task< State >::getInitialStateSet(), hypro::Label::getName(), hypro::LinTrafoParameters< Number, Setting >::getParameterSet(), hypro::lintrafoParameters< Number >::getParameterSet(), hypro::Transition< N >::getSource(), hypro::Transition< N >::getTarget(), hypro::lintrafoParameters< Number >::getTransformedDirection(), hypro::HybridAutomaton< Number >::getVariables(), hypro::glpkCheckPoint(), hypro::VariablePool::hasDimension(), hypro::SupportFunctionContent< Number, Setting >::hasTrafo(), hypro::HSVtoRGB(), hypro::icpIntersectHalfspace(), hypro::VariablePool::id(), hypro::LRUCache< hypro::Cacheable< matrix_t< Number > >, matrix_t< Number > >::insert(), hypro::VPolytopeT< Number, Converter, S >::insert(), hypro::insertAndCreateTask(), hypro::ZonotopeT< Number, Converter, Setting >::intersect(), hypro::ProjectOp< Number, Converter, Setting >::intersectDims(), hypro::IntersectOp< Number, Converter, Setting >::IntersectOp(), hypro::BoxT< Number, hypro::Converter, Setting >::interval(), hypro::Leaf< Number, Converter, Setting, Representation >::Leaf(), hypro::IntersectHalfspaceOp< Number, Converter, Setting >::leGuernic(), hypro::IntersectHalfspaceOp< Number, Converter, Setting >::leGuernicFast(), hypro::LinTrafoParameters< Number, Setting >::LinTrafoParameters(), hypro::lintrafoParameters< Number >::lintrafoParameters(), main(), hypro::Halfspace< Number >::makeInteger(), hypro::LinTrafoParameters< Number, Setting >::matrix(), hypro::ZonotopeT< Number, Converter, Setting >::matrix(), hypro::VPolytopeT< Number, Converter, S >::matrix(), hypro::lintrafoParameters< Number >::matrix(), hypro::DifferenceBoundsT< Number, Converter, Setting >::matrix(), hypro::CarlPolytopeT< Number, Converter, Setting >::minkowskiSum(), hypro::CarlPolytopeT< Number, Converter, Setting >::multiEvaluate(), hypro::VariablePool::newCarlVariable(), hypro::VariablePool::newPplVariable(), hypro::genericUniteVisitor< T >::operator()(), hypro::genericMinkowskiSumVisitor< T >::operator()(), hypro::genericIntersectVisitor< T >::operator()(), hypro::genericAffineTransformationVisitor< T, Number >::operator()(), hypro::nodeUpdater< State >::operator()(), hypro::genericSetContainsVisitor::operator()(), hypro::genericIntervalAssignmentVisitor< T, Number >::operator()(), hypro::operator+(), hypro::operator-(), hypro::HPolytopeT< Number, Converter, Setting >::operator=(), hypro::Point< int >::operator==(), hypro::Optimizer< Number >::Optimizer(), hypro::SupportFunctionContent< Number, Setting >::originCount(), hypro::Permutator::Permutator(), hypro::VariablePool::pplVarByIndex(), hypro::VariablePool::pplVariables(), hypro::VariablePool::print(), hypro::SupportFunctionContent< Number, Setting >::printLevel(), hypro::ReachTreeNode< State >::ReachTreeNode(), hypro::z3Context::real_val(), hypro::reduceIntervalsNumberRepresentation(), hypro::VPolytopeT< Number, Converter, S >::reduceNumberRepresentation(), hypro::reduceNumberRepresentation(), hypro::HPolytopeT< Number, Converter, Setting >::reduceNumberRepresentation(), hypro::RGBtoHEX(), hypro::RGBtoHSV(), hypro::BoxT< Number, hypro::Converter, Setting >::rInterval(), hypro::sample(), hypro::selectCols(), hypro::TreeNode< ReachTreeNode< State > >::setDepth(), hypro::clp_context::setMatrix(), hypro::LRUCache< hypro::Cacheable< matrix_t< Number > >, matrix_t< Number > >::size(), hypro::VariablePool::size(), hypro::SumOp< Number, Converter, Setting >::SumOp(), hypro::ProjectOp< Number, Converter, Setting >::supremumPoint(), hypro::ScaleOp< Number, Converter, Setting >::supremumPoint(), hypro::UnionOp< Number, Converter, Setting >::supremumPoint(), hypro::RootGrowNode< Number, Converter, Setting >::supremumPoint(), hypro::TrafoOp< Number, Converter, Setting >::supremumPoint(), hypro::IntersectHalfspaceOp< Number, Converter, Setting >::supremumPoint(), hypro::Task< State >::Task(), hypro::toFlowstarFormat(), hypro::stringToSetting_Impl< Enum >::toSetting(), hypro::trafoContent< Number, Setting >::trafoContent(), hypro::TrafoOp< Number, Converter, Setting >::TrafoOp(), hypro::ProjectOp< Number, Converter, Setting >::transform(), hypro::Leaf< Number, Converter, Setting, Representation >::transform(), hypro::TreeNode< ReachTreeNode< State > >::TreeNode(), hypro::unionContent< Number, Setting >::unionContent(), hypro::UnionOp< Number, Converter, Setting >::UnionOp(), hypro::CarlPolytopeT< Number, Converter, Setting >::unite(), hypro::clp_context::updateConstraints(), hypro::glpk_context::updateConstraints(), hypro::VariablePool::variable(), hypro::LinTrafoParameters< Number, Setting >::vector(), hypro::ZonotopeT< Number, Converter, Setting >::vector(), hypro::VPolytopeT< Number, Converter, S >::vector(), hypro::lintrafoParameters< Number >::vector(), hypro::DifferenceBoundsT< Number, Converter, Setting >::vector(), and hypro::z3OptimizeLinear().
assert (isequal(mh_g, cora_g))
assert (isequal(mh_center, cora_center))
assert (isequal(mh_generators, cora_generators))
assert (mh_out = =cora_out)
function compareZonotopeFunctions ()
disp ('---------------------------------------')
disp ('Minkowski sum')
disp ()
disp (' ')
disp ('center')
disp ('generators')
disp ('unite')
disp ('Satisfies halfspace/constraint')
disp ('Contains Point')
disp ('Contains Zonotope')
disp ('emptiness test')
disp ('unite equal vectors/delete aligned')
disp ('remove empty generators/delete zeros')
disp ('vertices')
disp ('reduce order/reduce')
cora_z6 reduce ('girard' , 1)
mh_z6 reduceOrder (2)
mh_z1 removeEmptyGenerators ()
mh_z4 uniteEqualVectors ()
Variable Documentation
C = [-107 -182 814 549 -771 67 -791 120 -422 -459
Definition at line 319 of file compareZonotopeFunctions.m.
Referenced by hypro::convertSettings(), and hypro::genericMinkowskiSumVisitor< T >::operator()().
cen = [2
Definition at line 587 of file compareZonotopeFunctions.m.
cen6 = [1
Definition at line 698 of file compareZonotopeFunctions.m.
cen_point = [2
Definition at line 561 of file compareZonotopeFunctions.m.
center1 = randi([range_min range_max], dim1 , 1)
Definition at line 12 of file compareZonotopeFunctions.m.
Referenced by main().
center2 = [ -97
Definition at line 226 of file compareZonotopeFunctions.m.
Referenced by main().
center3 = [-101
Definition at line 531 of file compareZonotopeFunctions.m.
Referenced by main().
cora_c = cora_z1.center()
Definition at line 236 of file compareZonotopeFunctions.m.
cora_center = cora_ms.center()
Definition at line 269 of file compareZonotopeFunctions.m.
cora_g = cora_z1.generators()
Definition at line 240 of file compareZonotopeFunctions.m.
cora_gen = cora_z6.generators()
Definition at line 714 of file compareZonotopeFunctions.m.
cora_generators = cora_ms.generators()
Definition at line 284 of file compareZonotopeFunctions.m.
cora_ms = cora_z1 + cora_z2
Definition at line 255 of file compareZonotopeFunctions.m.
cora_order = size(cora_gen,2) / 4
Definition at line 715 of file compareZonotopeFunctions.m.
cora_out = cora_point.containsPoint(point)
Definition at line 574 of file compareZonotopeFunctions.m.
cora_point = zonotope([cen_point, gen_point])
Definition at line 564 of file compareZonotopeFunctions.m.
cora_v = cora_z2.vertices()
Definition at line 685 of file compareZonotopeFunctions.m.
cora_z1 = zonotope([center1, generators1])
Definition at line 233 of file compareZonotopeFunctions.m.
cora_z2 = zonotope([center2, generators2])
Definition at line 244 of file compareZonotopeFunctions.m.
cora_z3 = zonotope([center3, generators3])
Definition at line 540 of file compareZonotopeFunctions.m.
cora_z4 = zonotope([cen, gen3])
Definition at line 633 of file compareZonotopeFunctions.m.
cora_z6 = zonotope([cen6, gen6])
Definition at line 701 of file compareZonotopeFunctions.m.
cora_z_encl = enclose(cora_z1, cora_z2)
Definition at line 302 of file compareZonotopeFunctions.m.
d = [484
Definition at line 421 of file compareZonotopeFunctions.m.
Referenced by hypro::NeighborhoodContainer::calculateNeighborhood(), CLANG_WARNING_DISABLE(), hypro::extractSolution(), hypro::ProjectOp< Number, Converter, Setting >::intersectDims(), hypro::IntersectHalfspaceOp< Number, Converter, Setting >::IntersectHalfspaceOp(), hypro::BoxT< Number, hypro::Converter, Setting >::interval(), hypro::BoxT< Number, hypro::Converter, Setting >::isSymmetric(), main(), hypro::BoxT< Number, hypro::Converter, Setting >::max(), hypro::BoxT< Number, hypro::Converter, Setting >::min(), hypro::Point< int >::operator==(), hypro::Permutator::Permutator(), hypro::ProjectOp< Number, Converter, Setting >::ProjectOp(), hypro::reduceIntervalsNumberRepresentation(), hypro::VPolytopeT< Number, Converter, S >::reduceNumberRepresentation(), hypro::BoxT< Number, hypro::Converter, Setting >::rInterval(), hypro::ScaleOp< Number, Converter, Setting >::ScaleOp(), hypro::SumOp< Number, Converter, Setting >::setDimension(), hypro::UnionOp< Number, Converter, Setting >::setDimension(), hypro::ProjectOp< Number, Converter, Setting >::setDimension(), hypro::ScaleOp< Number, Converter, Setting >::setDimension(), hypro::IntersectOp< Number, Converter, Setting >::setDimension(), hypro::IntersectHalfspaceOp< Number, Converter, Setting >::setDimension(), hypro::Leaf< Number, Converter, Setting, Representation >::setDimension(), hypro::RootGrowNode< Number, Converter, Setting >::setDimension(), hypro::CarlPolytopeT< Number, Converter, Setting >::setDimension(), hypro::TrafoOp< Number, Converter, Setting >::setDimension(), and hypro::TrafoOp< Number, Converter, Setting >::TrafoOp().
dim2 = 10
Definition at line 7 of file compareZonotopeFunctions.m.
gen1 = [1 0 0
Definition at line 585 of file compareZonotopeFunctions.m.
Referenced by main().
gen2 = [10 0 0
Definition at line 586 of file compareZonotopeFunctions.m.
Referenced by main().
gen3 = [1 0 1 0 1
Definition at line 629 of file compareZonotopeFunctions.m.
gen4 = [1 0 0
Definition at line 654 of file compareZonotopeFunctions.m.
gen6 = [-10 6 -13 17 -9 -8 7 9 -6 5
Definition at line 694 of file compareZonotopeFunctions.m.
gen_point = [1 0 1 0 1
Definition at line 560 of file compareZonotopeFunctions.m.
generators1 = randi([range_min range_max], dim1 , dim2)
Definition at line 11 of file compareZonotopeFunctions.m.
Referenced by main().
generators2 = [-24 74 -13 -25 -97 8 44 -45 -30 86
Definition at line 118 of file compareZonotopeFunctions.m.
Referenced by main().
generators3 = [508 251 -562 -406 851 -88 161 328 -488 349
Definition at line 429 of file compareZonotopeFunctions.m.
Referenced by main().
mh_c = mh_z1.center()
Definition at line 235 of file compareZonotopeFunctions.m.
mh_center = mh_ms.center()
Definition at line 264 of file compareZonotopeFunctions.m.
mh_g = mh_z1.generators()
Definition at line 239 of file compareZonotopeFunctions.m.
mh_generators = mh_ms.generators()
Definition at line 279 of file compareZonotopeFunctions.m.
mh_ms = mh_z1 + mh_z2
Definition at line 250 of file compareZonotopeFunctions.m.
mh_order = mh_z6.order()
Definition at line 703 of file compareZonotopeFunctions.m.
mh_out = mh_point.contains(point)
Definition at line 569 of file compareZonotopeFunctions.m.
mh_point = MHyProZonotope(cen_point, gen_point)
Definition at line 563 of file compareZonotopeFunctions.m.
mh_v = mh_z2.vertices()
Definition at line 680 of file compareZonotopeFunctions.m.
mh_z1 = MHyProZonotope(center1, generators1)
Definition at line 232 of file compareZonotopeFunctions.m.
mh_z2 = MHyProZonotope(center2, generators2)
Definition at line 243 of file compareZonotopeFunctions.m.
mh_z3 = MHyProZonotope(center3, generators3)
Definition at line 539 of file compareZonotopeFunctions.m.
mh_z4 = MHyProZonotope(cen, gen3)
Definition at line 632 of file compareZonotopeFunctions.m.
mh_z6 = MHyProZonotope(cen6, gen6)
Definition at line 700 of file compareZonotopeFunctions.m.
mh_z_united = mh_z1.unite(mh_z2)
Definition at line 297 of file compareZonotopeFunctions.m.
end end function out = cora_z3.constrSat(C,d)
Definition at line 551 of file compareZonotopeFunctions.m.
Referenced by configure_file(), hypro::convert(), ObjectHandle::convert2Matlab(), convertPtr2Mat(), convertSmartPtr2Mat(), hypro::genericOutstreamVisitor::operator()(), std::operator<<(), hypro::operator<<(), hypro::toFlowstarFormat(), and vector2Matlab().
point = [4
Definition at line 566 of file compareZonotopeFunctions.m.
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::affineTransformation(), hypro::VPolytopeT< Number, Converter, S >::assignIntervals(), hypro::GeneralizedStarT< Number, Converter, Setting >::assignIntervals(), hypro::SupportFunctionNewT< Number, Converter, Setting >::assignIntervals(), CLANG_WARNING_DISABLE(), hypro::extractSolution(), hypro::Halfspace< Number >::isInteger(), hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), main(), ObjectHandle::mPoint2Hypro(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT(), hypro::ZonotopeT< Number, Converter, Setting >::reduceRepresentation(), hypro::Point< int >::removeDuplicatePoints(), hypro::ProjectOp< Number, Converter, Setting >::reverseOp(), hypro::RootGrowNode< Number, Converter, Setting >::reverseOp(), hypro::TrafoOp< Number, Converter, Setting >::reverseOp(), hypro::IntersectHalfspaceOp< Number, Converter, Setting >::reverseOp(), hypro::Leaf< Number, Converter, Setting, Representation >::supremumPoint(), testContainsPoint(), hypro::ConstrainSet< Number >::toPoint(), and hypro::BoxT< Number, hypro::Converter, Setting >::type().
range_max = 100
Definition at line 9 of file compareZonotopeFunctions.m.
range_min = -100
Definition at line 8 of file compareZonotopeFunctions.m.
stop = toc
Definition at line 265 of file compareZonotopeFunctions.m.
stop_cora = toc
Definition at line 256 of file compareZonotopeFunctions.m.
stop_mh = toc
Definition at line 251 of file compareZonotopeFunctions.m.
tic
Definition at line 249 of file compareZonotopeFunctions.m.