HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/CompareMHyProAndCORA/compareVP_CORA_MHyPro.m File Reference
compareVP_CORA_MHyPro.m File Reference
Functions
disp ('CORA') HA
Zcenter (10)=0
figure ()
plot (HA,'reachableSet', options)
plot reachable set set (gca,'FontSize', 15)
plotFilled (options.R0, options.projectedDimensions,'w','EdgeColor','k')
plot (pgon,'FaceColor',[0.831, 0, 0], 'FaceAlpha', 0.5,'EdgeColor', 'none')
fill (k1, inBetweenUpper,[0.831, 0, 0], 'FaceAlpha', 0.5, 'EdgeColor','none')
dummy_reset setMatrix (eye(11))
dummy_reset setVector (zeros(11, 1))
id MHyProLocation ()
loc_qc setName ('qc')
loc_qc setFlow (Ac)
loc_qc setInvariant (inv_qc)
loc_qn setName ('qn')
loc_qn setFlow (An)
loc_qn setInvariant (inv_qn)
sink setName ('sink')
sink setFlow (zeros(11))
id MHyProTransition ()
guard1 setMatrix ([0 0 0 0 0 0 0 0 0-1 0])
guard1 setVector (-2)
temp (10, 10)=0
reset setMatrix (temp)
tran1 setAggregation (aggr)
tran1 setGuard (guard1)
tran1 setSource (qc)
tran1 setTarget (qn)
tran1 setReset (reset)
tran1 setLabels ({MHyProLabel('tran1')})
qc addTransition (tran1)
tran2 setGuard (guard2)
tran2 setSource (qn)
tran2 setTarget (qc)
tran2 setLabels ({MHyProLabel('tran2')})
qn addTransition (tran2)
id MHyProCondition ()
sink_guard setVector ([-timeHorizon;timeHorizon])
tran1s setAggregation (0)
tran1s setGuard (sink_guard)
tran1s setTarget (s)
tran1s setReset (dummy_reset)
tran1s setLabels ({MHyProLabel('tran1s')})
qn addTransition (tran1s)
tran2s setLabels ({MHyProLabel('tran2s')})
qc addTransition (tran2s)
9, 1 ones ()
* ones (9, 1)
eye (11)]
automaton addInitialState (qc, initialCond)
id timeBound ()
reacher setSettings (settings)
reacher setRepresentationType (setRepr)
reacher plotComparison (flowpipes, dim, labs)
if saveFig saveas (fig, fullfile(savePath, fname),'eps')
Variables
function compareVP_CORA_MHyPro(mhStrat, cStrat, timeHorizon, saveFig, fname, savePath, diff)%Comparison for vehicle platoon benchmark%SETTINGS settings clustering = mhStrat.clustering
aggr = mhStrat.aggr
setRepr = mhStrat.setRepr
CORA timeStepC = cStrat.timeStep
tT = cStrat.tT
zO = cStrat.zO
pO = cStrat.pO
options enclosureEnables = [3 5]
options guardIntersect = 'polytope'
Zdelta = [0.1*ones(9,1)
options Zcenter = ones(10,1)
options R0 = zonotope([Zcenter,diag(Zdelta)])
initial state for reachability analysis options x0 = center(options.R0)
initial state for simulation options intersectInvariant =1
options taylorTerms = tT
options zonotopeOrder = zO
options polytopeOrder = pO
options errorOrder =2
options reductionTechnique = 'girard'
options isHyperplaneMap = 0
options originContained = 0
set input
options uLoc {i} = 0
options uLocTrans {i} = options.uLoc{i}
options Uloc {i} = zonotope(options.uLoc{i})
end First location options startLoc = 1
initial location options finalLoc = 0
__pad9__
start time options tFinal = timeHorizon
hold on
options projectedDimensions = [1 7]
options plotType = 'b'
plot initial set if diff
x = [1.8
pgon = polyshape([x,y], 'Simplify', false)
spec1 = 0.855*k -0.05
upper = 0.6 + 0*k
k1 = [k, fliplr(k)]
inBetweenUpper = [spec1, fliplr(upper)]
end Create Automaton automaton = MHyProHAutomaton()
dummy_reset = MHyProReset()
Set flow
Set inv
Set e1prime
Set a1
Set e2
Set e2prime
Set a2
Set e3
Set e3prime
Set a3
Set t An = [0 1 0 0 0 0 0 0 0 0 0 0
qc = automaton.addLocation(loc_qc)
qn = automaton.addLocation(loc_qn)
s = automaton.addLocation(sink)
Set guard
Set reset
temp = eye(11)
tran1s = MHyProTransition()
boxMatrix = [-1*eye(11)
initialCond = MHyProCondition(boxMatrix, boxVector)
settings jumpDepth = 20
reacher = MHyProReach(automaton)
flowpipes = reacher.computeForwardReachability()
dim = [1 7]
labs = ["e1", "e3"]
Function Documentation
automaton addInitialState (qc , initialCond)
qc addTransition (tran1)
qn addTransition (tran2)
qn addTransition (tran1s)
qc addTransition (tran2s)
disp ('CORA')
eye (11)
figure ()
fill (k1 , inBetweenUpper , 'FaceAlpha' , 0. 5, 'EdgeColor' , 'none')
id MHyProCondition () virtual
id MHyProLocation () virtual
id MHyProTransition () virtual
9,1 ones () virtual
* ones (9 , 1)
plot (HA , 'reachableSet' , options)
plot (pgon , 'FaceColor' , 'FaceAlpha' , 0. 5, 'EdgeColor' , 'none')
reacher plotComparison (flowpipes , dim , labs)
plotFilled (options. R0, options. projectedDimensions, 'w' , 'EdgeColor' , 'k')
if saveFig saveas (fig , fullfile(savePath, fname) , 'eps')
plot reachable set set (gca , 'FontSize' , 15)
tran1 setAggregation (aggr)
tran1s setAggregation (0)
loc_qc setFlow (Ac)
loc_qn setFlow (An)
sink setFlow (zeros(11))
tran1 setGuard (guard1)
tran2 setGuard (guard2)
tran1s setGuard (sink_guard)
loc_qc setInvariant (inv_qc)
loc_qn setInvariant (inv_qn)
tran1 setLabels ({MHyProLabel('tran1')})
tran2 setLabels ({MHyProLabel('tran2')})
tran1s setLabels ({MHyProLabel('tran1s')})
tran2s setLabels ({MHyProLabel('tran2s')})
dummy_reset setMatrix (eye(11))
guard1 setMatrix ()
reset setMatrix (temp)
loc_qc setName ('qc')
loc_qn setName ('qn')
sink setName ('sink')
reacher setRepresentationType (setRepr)
tran1 setReset (reset)
tran1s setReset (dummy_reset)
reacher setSettings (settings)
tran1 setSource (qc)
tran2 setSource (qn)
tran1 setTarget (qn)
tran2 setTarget (qc)
tran1s setTarget (s)
dummy_reset setVector (zeros(11, 1))
guard2 setVector (- 2)
sink_guard setVector ()
temp (10 , 10) pure virtual
id timeBound () virtual
Zcenter (10) pure virtual
Variable Documentation
__pad9__
Definition at line 55 of file compareVP_CORA_MHyPro.m.
Set a1
Definition at line 140 of file compareVP_CORA_MHyPro.m.
Set a2
Definition at line 140 of file compareVP_CORA_MHyPro.m.
Set a3
Definition at line 140 of file compareVP_CORA_MHyPro.m.
aggr = mhStrat.aggr
Definition at line 10 of file compareVP_CORA_MHyPro.m.
Set t An = [0 1 0 0 0 0 0 0 0 0 0 0
Definition at line 141 of file compareVP_CORA_MHyPro.m.
end Create Automaton automaton = MHyProHAutomaton()
Definition at line 100 of file compareVP_CORA_MHyPro.m.
boxMatrix = [-1*eye(11)
Definition at line 247 of file compareVP_CORA_MHyPro.m.
function compareVP_CORA_MHyPro (mhStrat,cStrat, timeHorizon, saveFig, fname, savePath, diff) % Comparison for vehicle platoon benchmark % SETTINGS settings clustering = mhStrat.clustering
Definition at line 9 of file compareVP_CORA_MHyPro.m.
elseif diff
Initial value:
== 1
    y =
Definition at line 68 of file compareVP_CORA_MHyPro.m.
dim = [1 7]
Definition at line 267 of file compareVP_CORA_MHyPro.m.
dummy_reset = MHyProReset()
Definition at line 101 of file compareVP_CORA_MHyPro.m.
Set e1prime
Definition at line 140 of file compareVP_CORA_MHyPro.m.
Set e2
Definition at line 140 of file compareVP_CORA_MHyPro.m.
Set e2prime
Definition at line 140 of file compareVP_CORA_MHyPro.m.
Set e3
Definition at line 140 of file compareVP_CORA_MHyPro.m.
Set e3prime
Definition at line 140 of file compareVP_CORA_MHyPro.m.
options enclosureEnables = [3 5]
Definition at line 24 of file compareVP_CORA_MHyPro.m.
options errorOrder =2
Definition at line 39 of file compareVP_CORA_MHyPro.m.
initial location options finalLoc = 0
Definition at line 54 of file compareVP_CORA_MHyPro.m.
Set flow
Definition at line 114 of file compareVP_CORA_MHyPro.m.
flowpipes = reacher.computeForwardReachability()
Definition at line 264 of file compareVP_CORA_MHyPro.m.
Set guard
Definition at line 179 of file compareVP_CORA_MHyPro.m.
options guardIntersect = 'polytope'
Definition at line 25 of file compareVP_CORA_MHyPro.m.
inBetweenUpper = [spec1, fliplr(upper)]
Definition at line 89 of file compareVP_CORA_MHyPro.m.
initialCond = MHyProCondition(boxMatrix, boxVector)
Definition at line 249 of file compareVP_CORA_MHyPro.m.
set input
Definition at line 46 of file compareVP_CORA_MHyPro.m.
initial state for simulation options intersectInvariant =1
Definition at line 34 of file compareVP_CORA_MHyPro.m.
Set inv
Definition at line 130 of file compareVP_CORA_MHyPro.m.
options isHyperplaneMap = 0
Definition at line 41 of file compareVP_CORA_MHyPro.m.
settings jumpDepth = 20
Definition at line 258 of file compareVP_CORA_MHyPro.m.
k1 = [k, fliplr(k)]
Definition at line 88 of file compareVP_CORA_MHyPro.m.
labs = ["e1", "e3"]
Definition at line 268 of file compareVP_CORA_MHyPro.m.
hold on
Definition at line 61 of file compareVP_CORA_MHyPro.m.
options originContained = 0
Definition at line 42 of file compareVP_CORA_MHyPro.m.
pgon = polyshape([x,y], 'Simplify', false)
Definition at line 71 of file compareVP_CORA_MHyPro.m.
options plotType = 'b'
Definition at line 63 of file compareVP_CORA_MHyPro.m.
pO = cStrat.pO
Definition at line 17 of file compareVP_CORA_MHyPro.m.
options polytopeOrder = pO
Definition at line 38 of file compareVP_CORA_MHyPro.m.
options projectedDimensions = [1 7]
Definition at line 62 of file compareVP_CORA_MHyPro.m.
qc = automaton.addLocation(loc_qc)
Definition at line 168 of file compareVP_CORA_MHyPro.m.
qn = automaton.addLocation(loc_qn)
Definition at line 169 of file compareVP_CORA_MHyPro.m.
options R0 = zonotope([Zcenter,diag(Zdelta)])
Definition at line 31 of file compareVP_CORA_MHyPro.m.
reacher = MHyProReach(automaton)
Definition at line 260 of file compareVP_CORA_MHyPro.m.
options reductionTechnique = 'girard'
Definition at line 40 of file compareVP_CORA_MHyPro.m.
Set reset
Definition at line 183 of file compareVP_CORA_MHyPro.m.
s = automaton.addLocation(sink)
Definition at line 170 of file compareVP_CORA_MHyPro.m.
setRepr = mhStrat.setRepr
Definition at line 11 of file compareVP_CORA_MHyPro.m.
spec1 = 0.855*k -0.05
Definition at line 85 of file compareVP_CORA_MHyPro.m.
end First location options startLoc = 1
Definition at line 53 of file compareVP_CORA_MHyPro.m.
options taylorTerms = tT
Definition at line 36 of file compareVP_CORA_MHyPro.m.
temp = eye(11)
Definition at line 184 of file compareVP_CORA_MHyPro.m.
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::calcepsilon(), hypro::NonLinearOmega0Supportfunction< Setting >::calcvalues(), hypro::contains(), convertMat2Ptr(), hypro::directionList2Matrix(), hypro::Facet< Number >::furthest_Point(), hypro::Facet< Number >::getDist(), hypro::Facet< Number >::isAbove(), hypro::Facet< Number >::isBelow(), main(), ObjectHandle::mPoint2Hypro(), ObjectHandle::mVectorOfVectors2Hypro(), hypro::NonLinearOmega0Supportfunction< Setting >::NonLinearOmega0Supportfunction(), and hypro::Facet< Number >::setPoints().
start time options tFinal = timeHorizon
Definition at line 56 of file compareVP_CORA_MHyPro.m.
CORA timeStepC = cStrat.timeStep
Definition at line 14 of file compareVP_CORA_MHyPro.m.
tran1s = MHyProTransition()
Definition at line 219 of file compareVP_CORA_MHyPro.m.
tT = cStrat.tT
Definition at line 15 of file compareVP_CORA_MHyPro.m.
options uLoc {i} = 0
Definition at line 47 of file compareVP_CORA_MHyPro.m.
options Uloc {i} = zonotope(options.uLoc{i})
Definition at line 49 of file compareVP_CORA_MHyPro.m.
options uLocTrans {i} = options.uLoc{i}
Definition at line 48 of file compareVP_CORA_MHyPro.m.
upper = 0.6 + 0*k
Definition at line 86 of file compareVP_CORA_MHyPro.m.
x = [1.8
Definition at line 70 of file compareVP_CORA_MHyPro.m.
initial state for reachability analysis options x0 = center(options.R0)
Definition at line 32 of file compareVP_CORA_MHyPro.m.
options Zcenter = ones(10,1)
Definition at line 29 of file compareVP_CORA_MHyPro.m.
Zdelta = [0.1*ones(9,1)
Definition at line 26 of file compareVP_CORA_MHyPro.m.
zO = cStrat.zO
Definition at line 16 of file compareVP_CORA_MHyPro.m.
options zonotopeOrder = zO
Definition at line 37 of file compareVP_CORA_MHyPro.m.