HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/CompareMHyProAndCORA/compareFO4_CORA_MHyPro.m File Reference
compareFO4_CORA_MHyPro.m File Reference
Functions
dummy_reset setMatrix (eye(7))
dummy_reset setVector (zeros(7, 1))
id MHyProLocation ()
loc1 setName ('loc1')
loc1 setFlow (flow_loc1)
loc1 setInvariant (inv_loc1)
loc2 setName ('loc2')
loc2 setFlow (flow_loc2)
loc2 setInvariant (inv_loc2)
loc3 setName ('loc3')
loc3 setFlow (flow_loc3)
loc3 setInvariant (inv_loc3)
loc4 setName ('loc4')
loc4 setFlow (flow_loc4)
loc4 setInvariant (inv_loc4)
loc_sink setName ('sink')
loc_sink setFlow (flowMatrix)
id MHyProTransition ()
guard1 setMatrix ([1 0 0 0 0 0 0;-1 0 0 0 0 0 0;-0.714286-1 0 0 0 0 0])
guard1 setVector ([0;0;0])
tran1 setAggregation (aggr)
tran1 setGuard (guard1)
tran1 setSource (l1)
tran1 setTarget (l3)
tran1 setReset (dummy_reset)
tran1 setLabels ({MHyProLabel('tran1')})
l1 addTransition (tran1)
tran2 setGuard (guard2)
tran2 setSource (l3)
tran2 setTarget (l4)
tran2 setLabels ({MHyProLabel('tran2')})
l3 addTransition (tran2)
tran3 setGuard (guard3)
tran3 setSource (l4)
tran3 setTarget (l2)
tran3 setLabels ({MHyProLabel('tran3')})
l4 addTransition (tran3)
tran4 setGuard (guard4)
tran4 setSource (l2)
tran4 setTarget (l1)
tran4 setLabels ({MHyProLabel('tran4')})
l2 addTransition (tran4)
tran1s setAggregation (0)
tran1s setGuard (guard1s)
tran1s setTarget (s)
tran1s setLabels ({MHyProLabel('tran1s')})
l1 addTransition (tran1s)
tran2s setGuard (guard2s)
tran2s setLabels ({MHyProLabel('tran2s')})
l2 addTransition (tran2s)
tran3s setGuard (guard3s)
tran3s setLabels ({MHyProLabel('tran3s')})
l3 addTransition (tran3s)
tran4s setGuard (guard4s)
tran4s setLabels ({MHyProLabel('tran4s')})
l4 addTransition (tran4s)
id boxVector ()
7 eye ()
automaton addInitialState (l3, initialCond)
id timeHorizon ()
reacher setSettings (settings)
reacher setRepresentationType (setRepr)
reacher plotComparison (flowpipes, dim, labs)
disp ('CORA')
plot (HA,'reachableSet', options)
plot reachable set plotFilled (options.R0, options.projectedDimensions,'w','EdgeColor','k')
plot initial set set (gca,'FontSize', 15)
plot (pgon,'FaceColor',[0.831, 0, 0], 'FaceAlpha', 0.5,'EdgeColor', 'none')
fill (k1, inBetweenUpper,[0.831, 0, 0], 'FaceAlpha', 0.5, 'EdgeColor','none')
end xlabel ('x1')
ylabel ('y')
if saveFig saveas (fig, fullfile(savePath, fname),'eps')
Variables
function compareFO4_CORA_MHyPro(mhStrat, cStrat, timeHorizon, saveFig, fname, savePath, diff)%Comparison for filtered oscillator 4 benchmark%SETTINGS settings clustering = mhStrat.clustering
aggr = mhStrat.aggr
setRepr = mhStrat.setRepr
CORA timeStepC = cStrat.timeStep
tT = cStrat.tT
zO = cStrat.zO
pO = cStrat.pO
Create Automaton automaton = MHyProHAutomaton()
dummy_reset = MHyProReset()
Set flow
Set inv
flowMatrix = zeros(7)
l1 = automaton.addLocation(loc1)
l2 = automaton.addLocation(loc2)
l3 = automaton.addLocation(loc3)
l4 = automaton.addLocation(loc4)
s = automaton.addLocation(loc_sink)
Set guard
boxMatrix = [eye(7)
initialCond = MHyProCondition(boxMatrix, boxVector)
settings jumpDepth = 5
reacher = MHyProReach(automaton)
flowpipes = reacher.computeForwardReachability()
fig = figure()
dim = [3 2]
labs = ["x1", "y"]
HA = filtered_oscillator_4_ha()
options enclosureEnables = [3 5]
options guardIntersect = 'polytope'
Zdelta = [0.05
options Zcenter = [0.25
options R0 = zonotope([Zcenter,diag(Zdelta)])
initial state for reachability analysis options x0 = center(options.R0)
initial state for simulation options taylorTerms = tT
options zonotopeOrder = zO
options polytopeOrder = pO
options intersectInvariant =1
options errorOrder =2
options reductionTechnique = 'girard'
options isHyperplaneMap = 0
options originContained = 0
set input
options uLoc {i} = 0
options uLocTrans {i} = options.uLoc{i}
options Uloc {i} = zonotope(options.uLoc{i})
end First location options startLoc = 3
initial location options finalLoc = 0
__pad3__
start time options tFinal = timeHorizon
options projectedDimensions = [3 2]
options plotType = 'b'
if diff
x = [1
pgon = polyshape([x,y], 'Simplify', false)
spec1 = -0.95*k + 0.22
upper = 0.55 + 0*k
hold on
k1 = [k, fliplr(k)]
inBetweenUpper = [spec1, fliplr(upper)]
Function Documentation
automaton addInitialState (l3 , initialCond)
l1 addTransition (tran1)
l3 addTransition (tran2)
l4 addTransition (tran3)
l2 addTransition (tran4)
l1 addTransition (tran1s)
l2 addTransition (tran2s)
l3 addTransition (tran3s)
l4 addTransition (tran4s)
id boxVector () virtual
disp ('CORA')
7 eye () virtual
fill (k1 , inBetweenUpper , 'FaceAlpha' , 0. 5, 'EdgeColor' , 'none')
Referenced by hypro::HierarchicalIntervalVector< CONTAINMENT, tNumber >::~HierarchicalIntervalVector().
id MHyProLocation () virtual
id MHyProTransition () virtual
plot (HA , 'reachableSet' , options)
plot (pgon , 'FaceColor' , 'FaceAlpha' , 0. 5, 'EdgeColor' , 'none')
reacher plotComparison (flowpipes , dim , labs)
plot reachable set plotFilled (options. R0, options. projectedDimensions, 'w' , 'EdgeColor' , 'k')
if saveFig saveas (fig , fullfile(savePath, fname) , 'eps')
plot initial set set (gca , 'FontSize' , 15)
tran1 setAggregation (aggr)
tran1s setAggregation (0)
loc1 setFlow (flow_loc1)
loc2 setFlow (flow_loc2)
loc3 setFlow (flow_loc3)
loc4 setFlow (flow_loc4)
loc_sink setFlow (flowMatrix)
tran1 setGuard (guard1)
tran2 setGuard (guard2)
tran3 setGuard (guard3)
tran4 setGuard (guard4)
tran1s setGuard (guard1s)
tran2s setGuard (guard2s)
tran3s setGuard (guard3s)
tran4s setGuard (guard4s)
loc1 setInvariant (inv_loc1)
loc2 setInvariant (inv_loc2)
loc3 setInvariant (inv_loc3)
loc4 setInvariant (inv_loc4)
tran1 setLabels ({MHyProLabel('tran1')})
tran2 setLabels ({MHyProLabel('tran2')})
tran3 setLabels ({MHyProLabel('tran3')})
tran4 setLabels ({MHyProLabel('tran4')})
tran1s setLabels ({MHyProLabel('tran1s')})
tran2s setLabels ({MHyProLabel('tran2s')})
tran3s setLabels ({MHyProLabel('tran3s')})
tran4s setLabels ({MHyProLabel('tran4s')})
dummy_reset setMatrix (eye(7))
guard1 setMatrix ()
loc1 setName ('loc1')
loc2 setName ('loc2')
loc3 setName ('loc3')
loc4 setName ('loc4')
loc_sink setName ('sink')
reacher setRepresentationType (setRepr)
tran1 setReset (dummy_reset)
reacher setSettings (settings)
tran1 setSource (l1)
tran2 setSource (l3)
tran3 setSource (l4)
tran4 setSource (l2)
tran1 setTarget (l3)
tran2 setTarget (l4)
tran3 setTarget (l2)
tran4 setTarget (l1)
tran1s setTarget (s)
dummy_reset setVector (zeros(7, 1))
guard1 setVector ()
id timeHorizon () virtual
end xlabel ('x1')
ylabel ('y')
Variable Documentation
__pad3__
Definition at line 347 of file compareFO4_CORA_MHyPro.m.
aggr = mhStrat.aggr
Definition at line 10 of file compareFO4_CORA_MHyPro.m.
Create Automaton automaton = MHyProHAutomaton()
Definition at line 23 of file compareFO4_CORA_MHyPro.m.
boxMatrix = [eye(7)
Definition at line 288 of file compareFO4_CORA_MHyPro.m.
function compareFO4_CORA_MHyPro (mhStrat,cStrat, timeHorizon, saveFig, fname, savePath, diff) % Comparison for filtered oscillator 4 benchmark % SETTINGS settings clustering = mhStrat.clustering
Definition at line 9 of file compareFO4_CORA_MHyPro.m.
elseif diff
Initial value:
== 2
        y =
Definition at line 358 of file compareFO4_CORA_MHyPro.m.
dim = [3 2]
Definition at line 307 of file compareFO4_CORA_MHyPro.m.
dummy_reset = MHyProReset()
Definition at line 24 of file compareFO4_CORA_MHyPro.m.
options enclosureEnables = [3 5]
Definition at line 315 of file compareFO4_CORA_MHyPro.m.
options errorOrder =2
Definition at line 331 of file compareFO4_CORA_MHyPro.m.
fig = figure()
Definition at line 306 of file compareFO4_CORA_MHyPro.m.
initial location options finalLoc = 0
Definition at line 346 of file compareFO4_CORA_MHyPro.m.
Set flow
Definition at line 36 of file compareFO4_CORA_MHyPro.m.
flowMatrix = zeros(7)
Definition at line 122 of file compareFO4_CORA_MHyPro.m.
Referenced by hypro::reachability::computeTrafoMatrix(), and main().
flowpipes = reacher.computeForwardReachability()
Definition at line 304 of file compareFO4_CORA_MHyPro.m.
Set guard
Definition at line 137 of file compareFO4_CORA_MHyPro.m.
options guardIntersect = 'polytope'
Definition at line 316 of file compareFO4_CORA_MHyPro.m.
HA = filtered_oscillator_4_ha()
Definition at line 314 of file compareFO4_CORA_MHyPro.m.
inBetweenUpper = [spec1, fliplr(upper)]
Definition at line 379 of file compareFO4_CORA_MHyPro.m.
initialCond = MHyProCondition(boxMatrix, boxVector)
Definition at line 289 of file compareFO4_CORA_MHyPro.m.
set input
Definition at line 338 of file compareFO4_CORA_MHyPro.m.
options intersectInvariant =1
Definition at line 329 of file compareFO4_CORA_MHyPro.m.
Set inv
Definition at line 47 of file compareFO4_CORA_MHyPro.m.
options isHyperplaneMap = 0
Definition at line 333 of file compareFO4_CORA_MHyPro.m.
settings jumpDepth = 5
Definition at line 298 of file compareFO4_CORA_MHyPro.m.
k1 = [k, fliplr(k)]
Definition at line 378 of file compareFO4_CORA_MHyPro.m.
l1 = automaton.addLocation(loc1)
Definition at line 125 of file compareFO4_CORA_MHyPro.m.
l2 = automaton.addLocation(loc2)
Definition at line 126 of file compareFO4_CORA_MHyPro.m.
l3 = automaton.addLocation(loc3)
Definition at line 127 of file compareFO4_CORA_MHyPro.m.
l4 = automaton.addLocation(loc4)
Definition at line 128 of file compareFO4_CORA_MHyPro.m.
labs = ["x1", "y"]
Definition at line 308 of file compareFO4_CORA_MHyPro.m.
hold on
Definition at line 377 of file compareFO4_CORA_MHyPro.m.
options originContained = 0
Definition at line 334 of file compareFO4_CORA_MHyPro.m.
pgon = polyshape([x,y], 'Simplify', false)
Definition at line 361 of file compareFO4_CORA_MHyPro.m.
options plotType = 'b'
Definition at line 354 of file compareFO4_CORA_MHyPro.m.
pO = cStrat.pO
Definition at line 17 of file compareFO4_CORA_MHyPro.m.
options polytopeOrder = pO
Definition at line 327 of file compareFO4_CORA_MHyPro.m.
options projectedDimensions = [3 2]
Definition at line 352 of file compareFO4_CORA_MHyPro.m.
options R0 = zonotope([Zcenter,diag(Zdelta)])
Definition at line 321 of file compareFO4_CORA_MHyPro.m.
reacher = MHyProReach(automaton)
Definition at line 300 of file compareFO4_CORA_MHyPro.m.
options reductionTechnique = 'girard'
Definition at line 332 of file compareFO4_CORA_MHyPro.m.
s = automaton.addLocation(loc_sink)
Definition at line 129 of file compareFO4_CORA_MHyPro.m.
setRepr = mhStrat.setRepr
Definition at line 11 of file compareFO4_CORA_MHyPro.m.
spec1 = -0.95*k + 0.22
Definition at line 375 of file compareFO4_CORA_MHyPro.m.
end First location options startLoc = 3
Definition at line 345 of file compareFO4_CORA_MHyPro.m.
initial state for simulation options taylorTerms = tT
Definition at line 325 of file compareFO4_CORA_MHyPro.m.
start time options tFinal = timeHorizon
Definition at line 348 of file compareFO4_CORA_MHyPro.m.
CORA timeStepC = cStrat.timeStep
Definition at line 14 of file compareFO4_CORA_MHyPro.m.
tT = cStrat.tT
Definition at line 15 of file compareFO4_CORA_MHyPro.m.
options uLoc {i} = 0
Definition at line 339 of file compareFO4_CORA_MHyPro.m.
options Uloc {i} = zonotope(options.uLoc{i})
Definition at line 341 of file compareFO4_CORA_MHyPro.m.
options uLocTrans {i} = options.uLoc{i}
Definition at line 340 of file compareFO4_CORA_MHyPro.m.
upper = 0.55 + 0*k
Definition at line 376 of file compareFO4_CORA_MHyPro.m.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::isSymmetric(), hypro::IntersectHalfspaceOp< Number, Converter, Setting >::leGuernic(), hypro::IntersectHalfspaceOp< Number, Converter, Setting >::leGuernicFast(), and hypro::reduceIntervalsNumberRepresentation().
x = [1
Definition at line 360 of file compareFO4_CORA_MHyPro.m.
initial state for reachability analysis options x0 = center(options.R0)
Definition at line 322 of file compareFO4_CORA_MHyPro.m.
options Zcenter = [0.25
Definition at line 320 of file compareFO4_CORA_MHyPro.m.
Zdelta = [0.05
Definition at line 317 of file compareFO4_CORA_MHyPro.m.
zO = cStrat.zO
Definition at line 16 of file compareFO4_CORA_MHyPro.m.
options zonotopeOrder = zO
Definition at line 326 of file compareFO4_CORA_MHyPro.m.