HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/CompareMHyProAndCORA/compareBB_CORA_MHyPro.m File Reference
compareBB_CORA_MHyPro.m File Reference
Functions
id MHyProLocation ()
loc setName ('loc')
loc setFlow (flowMatrix)
loc setInvariant (inv)
id MHyProTransition ()
guard setMatrix ([-1 0 0;1 0 0;0 1 0])
guard setVector ([0;0;0])
tran setAggregation (aggr)
tran setGuard (guard)
tran setSource (l)
tran setTarget (l)
tran setReset (reset)
tran setLabels ({MHyProLabel('t1')})
l addTransition (tran)
id boxVector ()
automaton addInitialState (l, initialCond)
id timeHorizon ()
reacher setSettings (settings)
reacher setRepresentationType (setRepr)
hold on reacher plotComparison (flowpipes, dim, labs)
disp ('CORA')
plot (HA,'reachableSet', options)
plot reachable set set (gca,'FontSize', 15)
plot (x, y,'m--')
plotFilled (options.R0, options.projectedDimensions,'w','EdgeColor','k')
plot (pgon,'FaceColor',[0.831, 0, 0], 'FaceAlpha', 0.5,'EdgeColor', 'none')
end if saveFig saveas (fig, fullfile(savePath, fname),'eps')
Variables
function compareBB_CORA_MHyPro(mhStrat, cStrat, timeHorizon, saveFig, fname, savePath, diff)%Comparison for bouncing ball benchmark%SETTINGS settings clustering = mhStrat.clustering
aggr = mhStrat.aggr
setRepr = mhStrat.setRepr
CORA timeStepC = cStrat.timeStep
tT = cStrat.tT
zO = cStrat.zO
pO = cStrat.pO
Create Automaton automaton = MHyProHAutomaton()
Set flow
Set invariant x
l = automaton.addLocation(loc)
Set guard = 0
boxMatrix = [-1 0 0
initialCond = MHyProCondition(boxMatrix, boxVector)
settings jumpDepth = 2
reacher = MHyProReach(automaton)
flowpipes = reacher.computeForwardReachability()
dim = [2 1]
labs = ["v", "x"]
fig = figure()
HA = cora_bouncing_ball_ha()
Zdelta = [0.1
options Zcenter = [10.1
options R0 = zonotope([Zcenter,diag(Zdelta)])
initial state for reachability analysis options x0 = center(options.R0)
initial state for simulation First location options startLoc = 1
initial location options finalLoc = 0
__pad0__
start time options tFinal = timeHorizon
options intersectInvariant =1
options taylorTerms = tT
options zonotopeOrder = zO
options polytopeOrder = pO
options errorOrder =2
options maxProjectionError =0.1
options reductionTechnique = 'girard'
options isHyperplaneMap = 0
options enclosureEnables = [3 5]
options guardIntersect = 'polytope'
options originContained = 0
set input
options uLoc {i} = 0
options uLocTrans {i} = options.uLoc{i}
options Uloc {i} = zonotope(options.uLoc{i})
end [HA] = reach(HA,options)
options projectedDimensions = [2 1]
options plotType = 'b'
y = 0 + 0*x
plot initial set if diff
pgon = polyshape([x,y], 'Simplify', false)
Function Documentation
automaton addInitialState (l , initialCond)
Referenced by CLANG_WARNING_DISABLE().
l addTransition (tran)
Referenced by hypro::Path< Number, tNumber >::~Path().
id boxVector () virtual
disp ('CORA')
id MHyProLocation () virtual
id MHyProTransition () virtual
plot (HA , 'reachableSet' , options)
plot (x , y , 'm--')
plot (pgon , 'FaceColor' , 'FaceAlpha' , 0. 5, 'EdgeColor' , 'none')
hold on reacher plotComparison (flowpipes , dim , labs)
plot reachable set plotFilled (options. R0, options. projectedDimensions, 'w' , 'EdgeColor' , 'k')
end if saveFig saveas (fig , fullfile(savePath, fname) , 'eps')
set (gca , 'FontSize' , 15)
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::BoxT(), and main().
tran setAggregation (aggr)
loc setFlow (flowMatrix)
tran setGuard (guard)
Referenced by main().
loc setInvariant (inv)
Referenced by main().
tran setLabels ({MHyProLabel('t1')})
badState setMatrix ()
Referenced by hypro::Reset< N >::getIntervalResets().
loc setName ('loc')
reacher setRepresentationType (setRepr)
Referenced by CLANG_WARNING_DISABLE().
tran setReset (reset)
Referenced by main().
reacher setSettings (settings)
Referenced by CLANG_WARNING_DISABLE().
tran setSource (l)
Referenced by main().
tran setTarget (l)
Referenced by main().
sink_guard setVector ()
Referenced by hypro::Reset< N >::getIntervalResets().
id timeHorizon () virtual
Variable Documentation
__pad0__
Definition at line 117 of file compareBB_CORA_MHyPro.m.
aggr = mhStrat.aggr
Definition at line 10 of file compareBB_CORA_MHyPro.m.
Create Automaton automaton = MHyProHAutomaton()
Definition at line 23 of file compareBB_CORA_MHyPro.m.
boxMatrix = [-1 0 0
Definition at line 74 of file compareBB_CORA_MHyPro.m.
settings clustering = mhStrat.clustering
Definition at line 9 of file compareBB_CORA_MHyPro.m.
elseif diff
Initial value:
== 1
        x =
Definition at line 152 of file compareBB_CORA_MHyPro.m.
dim = [2 1]
Definition at line 93 of file compareBB_CORA_MHyPro.m.
Referenced by hypro::NeighborhoodContainer::calculateNeighborhood(), CLANG_WARNING_DISABLE(), hypro::computeHalfspaces(), hypro::constraintToHalfspace(), createComponent1(), createComponent2(), createComponent3(), createComponent4(), hypro::errorBoxes(), main(), Eigen::operator<(), Eigen::operator<=(), Eigen::operator==(), hypro::BallSupportFunction< Number >::setDimension(), hypro::rectangularFlow< N >::setFlowIntervalForDimension(), and MReach::settings().
options enclosureEnables = [3 5]
Definition at line 130 of file compareBB_CORA_MHyPro.m.
end[HA] = reach(HA,options)
Definition at line 142 of file compareBB_CORA_MHyPro.m.
Referenced by hypro::Path< Number, tNumber >::isEmpty(), hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), and so:().
options errorOrder =2
Definition at line 126 of file compareBB_CORA_MHyPro.m.
fig = figure()
Definition at line 96 of file compareBB_CORA_MHyPro.m.
initial location options finalLoc = 0
Definition at line 116 of file compareBB_CORA_MHyPro.m.
Set flow
Definition at line 33 of file compareBB_CORA_MHyPro.m.
Referenced by main(), and hypro::toFlowstarFormat().
flowpipes = reacher.computeForwardReachability()
Definition at line 91 of file compareBB_CORA_MHyPro.m.
Referenced by MReach::computeForwardReachability(), ObjectHandle::flowpipes2Matlab(), and main().
Set guard = 0
Definition at line 48 of file compareBB_CORA_MHyPro.m.
Referenced by main(), and hypro::Transition< N >::setGuard().
options guardIntersect = 'polytope'
Definition at line 131 of file compareBB_CORA_MHyPro.m.
HA = cora_bouncing_ball_ha()
Definition at line 105 of file compareBB_CORA_MHyPro.m.
Referenced by createComponent1(), createComponent2(), createComponent3(), and createComponent4().
initialCond = MHyProCondition(boxMatrix, boxVector)
Definition at line 75 of file compareBB_CORA_MHyPro.m.
set input
Definition at line 136 of file compareBB_CORA_MHyPro.m.
Referenced by hypro::parser::createFlowstarParseTree(), hypro::parseFlowstarFile< double >(), and hypro::parseFlowstarFile< mpq_class >().
options intersectInvariant =1
Definition at line 120 of file compareBB_CORA_MHyPro.m.
options isHyperplaneMap = 0
Definition at line 129 of file compareBB_CORA_MHyPro.m.
settings jumpDepth = 2
Definition at line 85 of file compareBB_CORA_MHyPro.m.
Referenced by MReach::setSettings(), and hypro::updateTiming().
l = automaton.addLocation(loc)
Definition at line 40 of file compareBB_CORA_MHyPro.m.
Referenced by hypro::EventTimingNode< N >::EventTimingNode(), hypro::PolytopeSupportFunction< Number, Setting >::isTemplate(), ObjectHandle::mLocsVector2Hypro(), hypro::BallSupportFunction< Number >::setDimension(), and hypro::NonLinearOmega0Supportfunction< Setting >::specificEvaluation().
labs = ["v", "x"]
Definition at line 94 of file compareBB_CORA_MHyPro.m.
options maxProjectionError =0.1
Definition at line 127 of file compareBB_CORA_MHyPro.m.
options originContained = 0
Definition at line 132 of file compareBB_CORA_MHyPro.m.
Referenced by hypro::computeWidening().
pgon = polyshape([x,y], 'Simplify', false)
Definition at line 155 of file compareBB_CORA_MHyPro.m.
options plotType = 'b'
Definition at line 145 of file compareBB_CORA_MHyPro.m.
pO = cStrat.pO
Definition at line 17 of file compareBB_CORA_MHyPro.m.
ab schwachsinn options polytopeOrder = pO
Definition at line 124 of file compareBB_CORA_MHyPro.m.
figure hold on box on options projectedDimensions = [2 1]
Definition at line 144 of file compareBB_CORA_MHyPro.m.
initial state for simulation options R0 = zonotope([Zcenter,diag(Zdelta)])
Definition at line 111 of file compareBB_CORA_MHyPro.m.
reacher = MHyProReach(automaton)
Definition at line 87 of file compareBB_CORA_MHyPro.m.
Referenced by MReach::computeForwardReachability(), main(), MReach::new_reach(), MReach::reachedBadStates(), MReach::setRepresentationType(), MReach::setSettings(), and MReach::settings().
options reductionTechnique = 'girard'
Definition at line 128 of file compareBB_CORA_MHyPro.m.
setRepr = mhStrat.setRepr
Definition at line 11 of file compareBB_CORA_MHyPro.m.
initial state for simulation First location options startLoc = 1
Definition at line 115 of file compareBB_CORA_MHyPro.m.
options taylorTerms = tT
Definition at line 122 of file compareBB_CORA_MHyPro.m.
start time options tFinal = timeHorizon
Definition at line 118 of file compareBB_CORA_MHyPro.m.
CORA timeStepC = cStrat.timeStep
Definition at line 14 of file compareBB_CORA_MHyPro.m.
tT = cStrat.tT
Definition at line 15 of file compareBB_CORA_MHyPro.m.
options uLoc {i} = 0
Definition at line 137 of file compareBB_CORA_MHyPro.m.
options Uloc {i} = zonotope(options.uLoc{i})
Definition at line 139 of file compareBB_CORA_MHyPro.m.
options uLocTrans {i} = options.uLoc{i}
Definition at line 138 of file compareBB_CORA_MHyPro.m.
Set reset x
Initial value:
= 0 t < timeHorizon
inv = MHyProCondition([-1 0 0; 0 0 1], [0;timeHorizon])
Definition at line 36 of file compareBB_CORA_MHyPro.m.
Referenced by main(), hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation(), and hypro::NonLinearOmega0Supportfunction< Setting >::specificEvaluation().
initial state for reachability analysis options x0 = center(options.R0)
Definition at line 112 of file compareBB_CORA_MHyPro.m.
Referenced by main().
y = 0 + 0*x
Definition at line 149 of file compareBB_CORA_MHyPro.m.
Referenced by main(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation().
options Zcenter = [10.1
Definition at line 110 of file compareBB_CORA_MHyPro.m.
Zdelta = [0.1
Definition at line 106 of file compareBB_CORA_MHyPro.m.
zO = cStrat.zO
Definition at line 16 of file compareBB_CORA_MHyPro.m.
options zonotopeOrder = zO
Definition at line 123 of file compareBB_CORA_MHyPro.m.