HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/CompareMHyProAndCORA/compareCC_CORA_MHyPro.m File Reference
compareCC_CORA_MHyPro.m File Reference
Functions
dummy_reset setMatrix (eye(4))
dummy_reset setVector ([0;0;0;0])
id MHyProLocation ()
loc_1 setName ('loc1')
loc_1 setFlow (flow_1)
loc_1 setInvariant (inv_1)
loc_2 setName ('loc2')
loc_2 setFlow (flow_2)
loc_2 setInvariant (inv_2)
loc_3 setName ('loc3')
loc_3 setFlow (flow_3)
loc_3 setInvariant (inv_3)
loc_4 setName ('loc4')
loc_4 setFlow (flow_4)
loc_4 setInvariant (inv_4)
loc_5 setName ('loc5')
loc_5 setFlow (flow_5)
loc_5 setInvariant (inv_5)
loc_6 setName ('loc6')
loc_6 setFlow (flow_6)
loc_6 setInvariant (inv_6)
sink setName ('sink')
sink setFlow (flow_sink)
loc_1 addLocation ()
id MHyProTransition ()
guard1 setMatrix ([0 0-1 0;0 0 1 0;0 0-1 0;0 0 1 0])
tran1 setAggregation (aggr)
tran1 setGuard (guard1)
tran1 setSource (l1)
tran1 setTarget (l2)
tran1 setReset (dummy_reset)
tran1 setLabels ({MHyProLabel('tran1')})
l1 addTransition (tran1)
tran2 setGuard (guard2)
tran2 setTarget (l4)
tran2 setReset (reset2)
tran2 setLabels ({MHyProLabel('tran2')})
l1 addTransition (tran2)
tran2s setAggregation (0)
tran2s setGuard (guard2s)
tran2s setTarget (s)
tran2s setLabels ({MHyProLabel('tran2s')})
l1 addTransition (tran2s)
tran3 setGuard (guard3)
tran3 setSource (l2)
tran3 setReset (reset3)
tran3 setLabels ({MHyProLabel('tran3')})
l2 addTransition (tran3)
tran3s setGuard (guard3s)
tran3s setLabels ({MHyProLabel('tran3s')})
l2 addTransition (tran3s)
tran4 setGuard (guard4)
tran4 setSource (l3)
tran4 setTarget (l1)
tran4 setReset (reset4)
tran4 setLabels ({MHyProLabel('tran4')})
l3 addTransition (tran4)
tran5 setTarget (l5)
tran5 setReset (reset5)
tran5 setLabels ({MHyProLabel('tran5')})
l3 addTransition (tran5)
tran5s setGuard (guard5s)
tran5s setLabels ({MHyProLabel('tran5s')})
l3 addTransition (tran5s)
tran6 setGuard (guard6)
tran6 setSource (l4)
tran6 setReset (reset6)
tran6 setLabels ({MHyProLabel('tran6')})
l4 addTransition (tran6)
tran7 setGuard (guard7)
tran7 setReset (reset7)
tran7 setLabels ({MHyProLabel('tran7')})
l4 addTransition (tran7)
tran71 setGuard (guard71)
tran71 setTarget (l3)
tran71 setLabels ({MHyProLabel('tran71')})
l4 addTransition (tran71)
tran7s setGuard (guard7s)
tran7s setLabels ({MHyProLabel('tran7s')})
l4 addTransition (tran7s)
tran8 setGuard (guard8)
tran8 setSource (l5)
tran8 setReset (reset8)
tran8 setLabels ({MHyProLabel('tran8')})
l5 addTransition (tran8)
tran9 setGuard (guard9)
tran9 setTarget (l6)
tran9 setLabels ({MHyProLabel('tran9')})
l5 addTransition (tran9)
tran9s setGuard (guard9s)
tran9s setLabels ({MHyProLabel('tran9s')})
l5 addTransition (tran9s)
tran10 setGuard (guard10)
tran10 setSource (l6)
tran10 setReset (reset10)
tran10 setLabels ({MHyProLabel('tran10')})
l6 addTransition (tran10)
tran10s setGuard (guard10s)
tran10s setLabels ({MHyProLabel('tran10s')})
l6 addTransition (tran10s)
id boxVector ()
automaton addInitialState (l1, initialCond)
id timeHorizon ()
reacher setSettings (settings)
reacher setRepresentationType (setRepr)
reacher plotComparison (flowpipes, dim, labs)
disp ('CORA')
plotFilled (options.R0, options.projectedDimensions,'w','EdgeColor','k')
plot initial set plot (HA,'reachableSet', options)
plot reachable set set (gca,'FontSize', 15)
xlabel ('t')
ylabel ('v')
plot (pgon,'FaceColor',[0.831, 0, 0], 'FaceAlpha', 0.5,'EdgeColor', 'none')
end if saveFig saveas (fig, fullfile(savePath, fname),'eps')
Variables
function compareCC_CORA_MHyPro(mhStrat, cStrat, timeHorizon, saveFig, fname, savePath, diff)%Comparison for cruise controll benchmark%SETTINGS settings clustering = mhStrat.clustering
aggr = mhStrat.aggr
setRepr = mhStrat.setRepr
CORA timeStepC = cStrat.timeStep
tT = cStrat.tT
zO = cStrat.zO
pO = cStrat.pO
Create Automaton automaton = MHyProHAutomaton()
dummy_reset = MHyProReset()
Set flow
Set inv = zonotope(c)
l2 = automaton.addLocation(loc_2)
l3 = automaton.addLocation(loc_3)
l4 = automaton.addLocation(loc_4)
l5 = automaton.addLocation(loc_5)
l6 = automaton.addLocation(loc_6)
s = automaton.addLocation(sink)
Set guard
reset2 = MHyProReset()
reset3 = MHyProReset()
reset4 = MHyProReset()
Set guard5 = MHyProCondition()
reset5 = MHyProReset()
reset6 = MHyProReset()
reset7 = MHyProReset()
reset8 = MHyProReset()
reset10 = MHyProReset()
boxMatrix = [1 0 0 0
initialCond = MHyProCondition(boxMatrix, boxVector)
settings jumpDepth = 20
reacher = MHyProReach(automaton)
flowpipes = reacher.computeForwardReachability()
fig = figure()
dim = [1 2]
labs = ["v", "x"]
Load model HA = cora_cruise_control_ha()
options enclosureEnables = [3 5]
options guardIntersect = 'polytope'
options v
options R0 = zonotope(Zcenter)
initial state for reachability analysis options x0 = center(options.R0)
initial state for simulation options taylorTerms = tT
options zonotopeOrder = zO
options polytopeOrder = pO
options errorOrder =1e-12
options reductionTechnique = 'girard'
options isHyperplaneMap = 0
options originContained = 0
set input
options uLoc {i} = [0
options uLocTrans {i} = options.uLoc{i}
options Uloc {i} = zonotope(options.uLoc{i})
end First location options startLoc = 1
initial location options finalLoc = 0
__pad1__
start time options tFinal = timeHorizon
tic
options projectedDimensions = [3 1]
options plotType = 'b'
if diff
y = [-2
pgon = polyshape([x,y], 'Simplify', false)
else x = [20
Function Documentation
automaton addInitialState (l1 , initialCond)
loc_1 addLocation () virtual
l1 addTransition (tran1)
l1 addTransition (tran2)
l1 addTransition (tran2s)
l2 addTransition (tran3)
l2 addTransition (tran3s)
l3 addTransition (tran4)
l3 addTransition (tran5)
l3 addTransition (tran5s)
l4 addTransition (tran6)
l4 addTransition (tran7)
l4 addTransition (tran71)
l4 addTransition (tran7s)
l5 addTransition (tran8)
l5 addTransition (tran9)
l5 addTransition (tran9s)
l6 addTransition (tran10)
l6 addTransition (tran10s)
id boxVector () virtual
disp ('CORA')
id MHyProLocation () virtual
id MHyProTransition () virtual
plot initial set plot (HA , 'reachableSet' , options)
plot (pgon , 'FaceColor' , 'FaceAlpha' , 0. 5, 'EdgeColor' , 'none')
reacher plotComparison (flowpipes , dim , labs)
plotFilled (options. R0, options. projectedDimensions, 'w' , 'EdgeColor' , 'k')
end if saveFig saveas (fig , fullfile(savePath, fname) , 'eps')
plot reachable set set (gca , 'FontSize' , 15)
tran1 setAggregation (aggr)
tran2s setAggregation (0)
loc_1 setFlow (flow_1)
loc_2 setFlow (flow_2)
loc_3 setFlow (flow_3)
loc_4 setFlow (flow_4)
loc_5 setFlow (flow_5)
loc_6 setFlow (flow_6)
sink setFlow (flow_sink)
tran1 setGuard (guard1)
tran2 setGuard (guard2)
tran2s setGuard (guard2s)
tran3 setGuard (guard3)
tran3s setGuard (guard3s)
tran4 setGuard (guard4)
tran5s setGuard (guard5s)
tran6 setGuard (guard6)
tran7 setGuard (guard7)
tran71 setGuard (guard71)
tran7s setGuard (guard7s)
tran8 setGuard (guard8)
tran9 setGuard (guard9)
tran9s setGuard (guard9s)
tran10 setGuard (guard10)
tran10s setGuard (guard10s)
loc_1 setInvariant (inv_1)
loc_2 setInvariant (inv_2)
loc_3 setInvariant (inv_3)
loc_4 setInvariant (inv_4)
loc_5 setInvariant (inv_5)
loc_6 setInvariant (inv_6)
tran1 setLabels ({MHyProLabel('tran1')})
tran2 setLabels ({MHyProLabel('tran2')})
tran2s setLabels ({MHyProLabel('tran2s')})
tran3 setLabels ({MHyProLabel('tran3')})
tran3s setLabels ({MHyProLabel('tran3s')})
tran4 setLabels ({MHyProLabel('tran4')})
tran5 setLabels ({MHyProLabel('tran5')})
tran5s setLabels ({MHyProLabel('tran5s')})
tran6 setLabels ({MHyProLabel('tran6')})
tran7 setLabels ({MHyProLabel('tran7')})
tran71 setLabels ({MHyProLabel('tran71')})
tran7s setLabels ({MHyProLabel('tran7s')})
tran8 setLabels ({MHyProLabel('tran8')})
tran9 setLabels ({MHyProLabel('tran9')})
tran9s setLabels ({MHyProLabel('tran9s')})
tran10 setLabels ({MHyProLabel('tran10')})
tran10s setLabels ({MHyProLabel('tran10s')})
dummy_reset setMatrix (eye(4))
guard1 setMatrix ()
loc_1 setName ('loc1')
loc_2 setName ('loc2')
loc_3 setName ('loc3')
loc_4 setName ('loc4')
loc_5 setName ('loc5')
loc_6 setName ('loc6')
sink setName ('sink')
reacher setRepresentationType (setRepr)
tran1 setReset (dummy_reset)
tran2 setReset (reset2)
tran3 setReset (reset3)
tran4 setReset (reset4)
tran5 setReset (reset5)
tran6 setReset (reset6)
tran7 setReset (reset7)
tran8 setReset (reset8)
tran10 setReset (reset10)
reacher setSettings (settings)
tran1 setSource (l1)
tran3 setSource (l2)
tran4 setSource (l3)
tran6 setSource (l4)
tran8 setSource (l5)
tran10 setSource (l6)
tran1 setTarget (l2)
tran2 setTarget (l4)
tran2s setTarget (s)
tran4 setTarget (l1)
tran5 setTarget (l5)
tran71 setTarget (l3)
tran9 setTarget (l6)
dummy_reset setVector ()
id timeHorizon () virtual
xlabel ('t')
ylabel ('v')
Variable Documentation
__pad1__
Definition at line 552 of file compareCC_CORA_MHyPro.m.
aggr = mhStrat.aggr
Definition at line 10 of file compareCC_CORA_MHyPro.m.
Create Automaton automaton = MHyProHAutomaton()
Definition at line 22 of file compareCC_CORA_MHyPro.m.
boxMatrix = [1 0 0 0
Definition at line 495 of file compareCC_CORA_MHyPro.m.
function compareCC_CORA_MHyPro (mhStrat,cStrat, timeHorizon, saveFig, fname, savePath, diff) % Comparison for cruise controll benchmark % SETTINGS settings clustering = mhStrat.clustering
Definition at line 9 of file compareCC_CORA_MHyPro.m.
elseif diff
Initial value:
== 1
        x =
Definition at line 565 of file compareCC_CORA_MHyPro.m.
dim = [1 2]
Definition at line 513 of file compareCC_CORA_MHyPro.m.
dummy_reset = MHyProReset()
Definition at line 23 of file compareCC_CORA_MHyPro.m.
options enclosureEnables = [3 5]
Definition at line 523 of file compareCC_CORA_MHyPro.m.
options errorOrder =1e-12
Definition at line 536 of file compareCC_CORA_MHyPro.m.
fig = figure()
Definition at line 512 of file compareCC_CORA_MHyPro.m.
initial location options finalLoc = 0
Definition at line 551 of file compareCC_CORA_MHyPro.m.
Set flow
Definition at line 34 of file compareCC_CORA_MHyPro.m.
flowpipes = reacher.computeForwardReachability()
Definition at line 511 of file compareCC_CORA_MHyPro.m.
Set guard
Definition at line 164 of file compareCC_CORA_MHyPro.m.
Set guard5 = MHyProCondition()
Definition at line 281 of file compareCC_CORA_MHyPro.m.
options guardIntersect = 'polytope'
Definition at line 524 of file compareCC_CORA_MHyPro.m.
Load model HA = cora_cruise_control_ha()
Definition at line 522 of file compareCC_CORA_MHyPro.m.
initialCond = MHyProCondition(boxMatrix, boxVector)
Definition at line 496 of file compareCC_CORA_MHyPro.m.
set input
Definition at line 543 of file compareCC_CORA_MHyPro.m.
Set inv = zonotope(c)
Definition at line 42 of file compareCC_CORA_MHyPro.m.
Referenced by hypro::TPolyFirstSegmentHandler< State >::handlerName(), main(), hypro::Location< N >::setInvariant(), and hypro::TPolyTimeEvolutionHandler< State >::setMarkedForDelete().
options isHyperplaneMap = 0
Definition at line 538 of file compareCC_CORA_MHyPro.m.
settings jumpDepth = 20
Definition at line 505 of file compareCC_CORA_MHyPro.m.
l2 = automaton.addLocation(loc_2)
Definition at line 152 of file compareCC_CORA_MHyPro.m.
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::boxoperator().
l3 = automaton.addLocation(loc_3)
Definition at line 153 of file compareCC_CORA_MHyPro.m.
l4 = automaton.addLocation(loc_4)
Definition at line 154 of file compareCC_CORA_MHyPro.m.
l5 = automaton.addLocation(loc_5)
Definition at line 155 of file compareCC_CORA_MHyPro.m.
l6 = automaton.addLocation(loc_6)
Definition at line 156 of file compareCC_CORA_MHyPro.m.
labs = ["v", "x"]
Definition at line 514 of file compareCC_CORA_MHyPro.m.
options originContained = 0
Definition at line 539 of file compareCC_CORA_MHyPro.m.
pgon = polyshape([x,y], 'Simplify', false)
Definition at line 568 of file compareCC_CORA_MHyPro.m.
options plotType = 'b'
Definition at line 558 of file compareCC_CORA_MHyPro.m.
pO = cStrat.pO
Definition at line 17 of file compareCC_CORA_MHyPro.m.
options polytopeOrder = pO
Definition at line 534 of file compareCC_CORA_MHyPro.m.
options projectedDimensions = [3 1]
Definition at line 557 of file compareCC_CORA_MHyPro.m.
options R0 = zonotope(Zcenter)
Definition at line 529 of file compareCC_CORA_MHyPro.m.
reacher = MHyProReach(automaton)
Definition at line 507 of file compareCC_CORA_MHyPro.m.
options reductionTechnique = 'girard'
Definition at line 537 of file compareCC_CORA_MHyPro.m.
reset10 = MHyProReset()
Definition at line 463 of file compareCC_CORA_MHyPro.m.
reset2 = MHyProReset()
Definition at line 190 of file compareCC_CORA_MHyPro.m.
reset3 = MHyProReset()
Definition at line 229 of file compareCC_CORA_MHyPro.m.
reset4 = MHyProReset()
Definition at line 268 of file compareCC_CORA_MHyPro.m.
reset5 = MHyProReset()
Definition at line 289 of file compareCC_CORA_MHyPro.m.
reset6 = MHyProReset()
Definition at line 328 of file compareCC_CORA_MHyPro.m.
reset7 = MHyProReset()
Definition at line 349 of file compareCC_CORA_MHyPro.m.
reset8 = MHyProReset()
Definition at line 406 of file compareCC_CORA_MHyPro.m.
s = automaton.addLocation(sink)
Definition at line 157 of file compareCC_CORA_MHyPro.m.
setRepr = mhStrat.setRepr
Definition at line 11 of file compareCC_CORA_MHyPro.m.
end First location options startLoc = 1
Definition at line 550 of file compareCC_CORA_MHyPro.m.
initial state for simulation options taylorTerms = tT
Definition at line 532 of file compareCC_CORA_MHyPro.m.
start time options tFinal = timeHorizon
Definition at line 553 of file compareCC_CORA_MHyPro.m.
tic
Definition at line 555 of file compareCC_CORA_MHyPro.m.
CORA timeStepC = cStrat.timeStep
Definition at line 14 of file compareCC_CORA_MHyPro.m.
tT = cStrat.tT
Definition at line 15 of file compareCC_CORA_MHyPro.m.
options uLoc {i} = [0
Definition at line 544 of file compareCC_CORA_MHyPro.m.
options Uloc {i} = zonotope(options.uLoc{i})
Definition at line 546 of file compareCC_CORA_MHyPro.m.
options uLocTrans {i} = options.uLoc{i}
Definition at line 545 of file compareCC_CORA_MHyPro.m.
options v
Initial value:
= [15, 40] x = [0, 0]  t =[0, 2.5]
Zcenter = interval([15;0;0],[40;0.1;2.5])
Definition at line 527 of file compareCC_CORA_MHyPro.m.
Referenced by addSegment(), hypro::FourierMotzkinQE< Number >::FourierMotzkinQE(), hypro::HSVtoRGB(), hypro::VertexContainer< Number >::insertAtBack(), hypro::VertexContainer< Number >::linearTransformation(), main(), hypro::VertexContainer< Number >::move(), hypro::numberOfPointsInHalfspace(), hypro::RGBtoHSV(), and hypro::vector2Array().
else x = [20
Definition at line 576 of file compareCC_CORA_MHyPro.m.
initial state for reachability analysis options x0 = center(options.R0)
Definition at line 530 of file compareCC_CORA_MHyPro.m.
y = [-2
Definition at line 567 of file compareCC_CORA_MHyPro.m.
zO = cStrat.zO
Definition at line 16 of file compareCC_CORA_MHyPro.m.
options zonotopeOrder = zO
Definition at line 533 of file compareCC_CORA_MHyPro.m.