HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/CORA_benchmarks/cora_bouncing_ball_ha.m File Reference
cora_bouncing_ball_ha.m File Reference
Variables
function HA
dynB = [0
no inputs dync = [0
dynamics = linearSys('linearSys', dynA, dynB, dync)
equation __pad11__
invb = 0
invOpt = struct('A', invA, 'b', invb)
inv = mptPolytope(invOpt)
Icenter = [7.5
Idelta = [7.5
syms a1 a2
instantiate symbolic variables s = [7.5 + 0*a1
create symbolic function c = taylm(s, interval([0,-20],[15;20]), 6)
trans = {}
equation __pad12__
resetb = [0
reset = struct('A', resetA, 'b', resetb)
equation __pad13__
guardb = [0
guardOpt = struct('A', guardA, 'b', guardb)
guard = mptPolytope(guardOpt)
loc {1} = location('S1',1, inv, trans, dynamics)
Variable Documentation
equation __pad11__
Definition at line 13 of file cora_bouncing_ball_ha.m.
equation __pad12__
Definition at line 37 of file cora_bouncing_ball_ha.m.
equation __pad13__
Definition at line 43 of file cora_bouncing_ball_ha.m.
syms a1 a2
Definition at line 23 of file cora_bouncing_ball_ha.m.
id c = taylm(s, interval([0,-20],[15;20]), 6)
Definition at line 25 of file cora_bouncing_ball_ha.m.
Referenced by CLANG_WARNING_DISABLE(), hypro::computeHalfspaces(), hypro::FourierMotzkinQE< Number >::FourierMotzkinQE(), hypro::VertexContainer< Number >::insert(), hypro::isBox(), main(), hypro::Plotter< Number >::Plotter(), hypro::RootGrowNode< Number, Converter, Setting >::print(), hypro::VertexContainer< Number >::set(), hypro::Vertex< std::size_t >::setColor(), hypro::SettingsProvider< State >::SettingsProvider(), and hypro::z3OptimizeLinear().
dynamics = linearSys('linearSys', dynA, dynB, dync)
Definition at line 9 of file cora_bouncing_ball_ha.m.
Referenced by main().
dynB = [0
Definition at line 7 of file cora_bouncing_ball_ha.m.
dync = [0
Definition at line 8 of file cora_bouncing_ball_ha.m.
guard = mptPolytope(guardOpt)
Definition at line 46 of file cora_bouncing_ball_ha.m.
equation guardb = [0
Definition at line 44 of file cora_bouncing_ball_ha.m.
guardOpt = struct('A', guardA, 'b', guardb)
Definition at line 45 of file cora_bouncing_ball_ha.m.
HA
Initial value:
= cora_bouncing_ball_ha(~)
% vars = [x v]
%% equation:
% x' = v v' = -9.81 t' = 1
dynA = [0 1 0
Definition at line 1 of file cora_bouncing_ball_ha.m.
Icenter = [7.5
Definition at line 18 of file cora_bouncing_ball_ha.m.
Idelta = [7.5
Definition at line 19 of file cora_bouncing_ball_ha.m.
Is not recognized by hybridAutomaton inv = mptPolytope(invOpt)
Definition at line 16 of file cora_bouncing_ball_ha.m.
equation invb = 0
Definition at line 14 of file cora_bouncing_ball_ha.m.
invOpt = struct('A', invA, 'b', invb)
Definition at line 15 of file cora_bouncing_ball_ha.m.
loc {1} = location('S1',1, inv, trans, dynamics)
Definition at line 51 of file cora_bouncing_ball_ha.m.
Referenced by ObjectHandle::convert2Matlab(), hypro::EventTimingNode< N >::EventTimingNode(), hypro::insertAndCreateTask(), ObjectHandle::mLocCondMap2Hypro(), and ObjectHandle::mLocsVector2Hypro().
reset = struct('A', resetA, 'b', resetb)
Definition at line 39 of file cora_bouncing_ball_ha.m.
equation resetb = [0
Definition at line 38 of file cora_bouncing_ball_ha.m.
instantiate symbolic variables s = [7.5 + 0*a1
Definition at line 24 of file cora_bouncing_ball_ha.m.
id trans = {}
Definition at line 34 of file cora_bouncing_ball_ha.m.
Referenced by hypro::EventTimingNode< N >::EventTimingNode(), main(), and hypro::Location< N >::setInvariant().