HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/CompareMHyProAndCORA/coraBoxFunctionsPrecision.m File Reference
coraBoxFunctionsPrecision.m File Reference
Functions
function coraBoxFunctionsPrecision disp ('')
disp ('---------------------------')
disp ('bspline0')
disp (['Result:[', num2str(infimum(res)), ', ', num2str(supremum(res)), ']'])
disp (['Time needed: ', num2str(stop)])
disp ('bspline1')
disp ('bspline2')
disp ('bspline3')
disp ('savitzky-golay filter')
disp ('image rejection unit')
disp ('random function')
disp ('Mitchell function')
disp ('matyas function')
disp ('three hump function')
disp ('ratscheck function')
Variables
u = interval(0,1)
tic
res = 1/6 * (1 - u)^3
stop = toc
low = -(infimum(res) - 0)/(1/6 - 0)* 100
up = (supremum(res) - 1/6)/(1/6 - 0)* 100
rl = 1/6
ru = 2/3
x1 = interval(-2,2)
x2 = interval(0,1)
x3 = interval(-2,2)
x4 = interval(-2,2)
x5 = interval(-100,100)
x6 = interval(-10,10)
x7 = interval(-100, 100)
Function Documentation
disp ('')
disp ('---------------------------')
disp ('bspline0')
disp (['Result:[', num2str(infimum(res)), ', ', num2str(supremum(res)), '] '])
disp ()
disp ('bspline1')
disp ('bspline2')
disp ('bspline3')
disp ('savitzky-golay filter')
disp ('image rejection unit')
disp ('random function')
disp ('Mitchell function')
disp ('matyas function')
disp ('three hump function')
disp ('ratscheck function')
Variable Documentation
low = -(infimum(res) - 0)/(1/6 - 0)* 100
Definition at line 14 of file coraBoxFunctionsPrecision.m.
res = 1/6 * (1 - u)^3
Definition at line 10 of file coraBoxFunctionsPrecision.m.
rl = 1/6
Definition at line 29 of file coraBoxFunctionsPrecision.m.
ru = 2/3
Definition at line 30 of file coraBoxFunctionsPrecision.m.
stop = toc
Definition at line 11 of file coraBoxFunctionsPrecision.m.
tic
Definition at line 9 of file coraBoxFunctionsPrecision.m.
u = interval(0,1)
Definition at line 8 of file coraBoxFunctionsPrecision.m.
Referenced by main().
up = (supremum(res) - 1/6)/(1/6 - 0)* 100
Definition at line 15 of file coraBoxFunctionsPrecision.m.
x1 = interval(-2,2)
Definition at line 75 of file coraBoxFunctionsPrecision.m.
x2 = interval(0,1)
Definition at line 94 of file coraBoxFunctionsPrecision.m.
x3 = interval(-2,2)
Definition at line 113 of file coraBoxFunctionsPrecision.m.
x4 = interval(-2,2)
Definition at line 133 of file coraBoxFunctionsPrecision.m.
x5 = interval(-100,100)
Definition at line 152 of file coraBoxFunctionsPrecision.m.
Referenced by main().
x6 = interval(-10,10)
Definition at line 172 of file coraBoxFunctionsPrecision.m.
Referenced by main().
x7 = interval(-100, 100)
Definition at line 191 of file coraBoxFunctionsPrecision.m.