HyPro: /home/travis/build/hypro/hypro/examples/example_parallel_composition.cpp File Reference
example_parallel_composition.cpp File Reference
Functions
template<typename Number >
HybridAutomaton< Number > createComponent1 (unsigned i)
Creates a component using a synchronization variable for the synchronizating robots benchmark.
template<typename Number >
HybridAutomaton< Number > createComponent2 (unsigned i, const std::vector< Label > &labels)
template<typename Number >
HybridAutomaton< Number > createComponent3 (unsigned i)
template<typename Number >
HybridAutomaton< Number > createComponent4 (unsigned i, const std::vector< Label > &labels)
int main (int argc, char **argv)
Function Documentation
template<typename Number > HybridAutomaton<Number> createComponent1 (unsigned i)
Creates a component using a synchronization variable for the synchronizating robots benchmark.
Parameters
[in] i Component identifier.
Template Parameters
Number Numeric type.
Returns
A hybrid automaton for one component (one robot).
Definition at line 21 of file example_parallel_composition.cpp.
References hypro::parallelotopeAgg, hypro::Location< Number >::setFlow(), hypro::Location< Number >::setInvariant(), hypro::Location< Number >::setName(), and hypro::HybridAutomaton< Number >::setVariables().
template<typename Number > HybridAutomaton<Number> createComponent2 (unsigned i, const std::vector< Label > & labels)
Definition at line 220 of file example_parallel_composition.cpp.
References hypro::parallelotopeAgg, hypro::Location< Number >::setFlow(), hypro::Location< Number >::setInvariant(), hypro::Location< Number >::setName(), and hypro::HybridAutomaton< Number >::setVariables().
template<typename Number > HybridAutomaton<Number> createComponent3 (unsigned i)
Definition at line 362 of file example_parallel_composition.cpp.
References hypro::parallelotopeAgg, hypro::Location< Number >::setFlow(), hypro::Location< Number >::setInvariant(), hypro::Location< Number >::setName(), and hypro::HybridAutomaton< Number >::setVariables().
template<typename Number > HybridAutomaton<Number> createComponent4 (unsigned i, const std::vector< Label > & labels)
Definition at line 568 of file example_parallel_composition.cpp.
References hypro::parallelotopeAgg, hypro::Location< Number >::setFlow(), hypro::Location< Number >::setInvariant(), hypro::Location< Number >::setName(), and hypro::HybridAutomaton< Number >::setVariables().
int main (int argc, char ** argv)
Definition at line 711 of file example_parallel_composition.cpp.
References hypro::LockedFileWriter::clearFile(), hypro::ReachabilitySettings::fileName, hypro::HybridAutomaton< Number >::getDotRepresentation(), hypro::HybridAutomaton< Number >::getStatistics(), hypro::HybridAutomaton< Number >::getTransitions(), hypro::ReachabilitySettings::jumpDepth, hypro::HybridAutomaton< Number >::reduce(), hypro::ReachabilitySettings::timeBound, hypro::ReachabilitySettings::timeStep, and hypro::toFlowstarFormat().