HyPro: /home/travis/build/hypro/hypro/examples/example_differenceBounds.cpp File Reference
example_differenceBounds.cpp File Reference
Typedefs
typedef double Number
Functions
void createTestDBM ()
void createTestDBM2 ()
void createTestDBM3 ()
void createTestDBMExtra ()
void createTestHPolytope ()
void testComparison ()
void testPlus ()
void testVertices ()
void testElapse ()
void testRewind ()
void testFree ()
void testReset ()
void testCopy ()
void testShift ()
void testEmpty ()
void testContains ()
void testIntersectConstraint ()
void testContainsPoint ()
void testIntersectDBM ()
void testUnion ()
void testConversionDifferenceBoundsToDifferenceBounds ()
void testConversionHPolyToDBM ()
void testConversionBoxToDBM ()
void testSatisfiesHalfspace ()
void testSatisfiesHalfspaces ()
void testIntersectHalfspace ()
void testIntersectHalfspaces ()
void testLinearTransformation ()
void testAffineTransformation ()
void testMinkowskiSum ()
void testExtraM ()
void testExtraMPlus ()
void testExtraLU ()
void testExtraLUPlus ()
void testPrint ()
int main ()
Variables
hypro::DifferenceBounds< Number > testDBM
hypro::DifferenceBounds< Number > testDBM2
hypro::DifferenceBounds< Number > testDBM3
hypro::DifferenceBounds< Number > testDBMExtra
hypro::HPolytope< Number > testHPolytope
Typedef Documentation
typedef double Number
Definition at line 11 of file example_differenceBounds.cpp.
Function Documentation
void createTestDBM ()
Definition at line 92 of file example_differenceBounds.cpp.
References mat, and testDBM.
Referenced by main().
void createTestDBM2 ()
Definition at line 118 of file example_differenceBounds.cpp.
References mat, and testDBM2.
Referenced by main().
void createTestDBM3 ()
Definition at line 144 of file example_differenceBounds.cpp.
References testDBM, and testDBM3.
Referenced by main().
void createTestDBMExtra ()
Definition at line 150 of file example_differenceBounds.cpp.
References mat, and testDBMExtra.
Referenced by main().
void createTestHPolytope ()
Definition at line 176 of file example_differenceBounds.cpp.
References testHPolytope, and vec.
Referenced by main().
int main ()
Definition at line 53 of file example_differenceBounds.cpp.
References createTestDBM(), createTestDBM2(), createTestDBM3(), createTestDBMExtra(), createTestHPolytope(), testAffineTransformation(), testComparison(), testContains(), testContainsPoint(), testConversionBoxToDBM(), testConversionDifferenceBoundsToDifferenceBounds(), testConversionHPolyToDBM(), testCopy(), testElapse(), testEmpty(), testExtraLU(), testExtraLUPlus(), testExtraM(), testExtraMPlus(), testFree(), testIntersectConstraint(), testIntersectDBM(), testIntersectHalfspace(), testIntersectHalfspaces(), testLinearTransformation(), testMinkowskiSum(), testPlus(), testReset(), testRewind(), testSatisfiesHalfspace(), testSatisfiesHalfspaces(), testShift(), testUnion(), and testVertices().
void testAffineTransformation ()
Definition at line 786 of file example_differenceBounds.cpp.
References A, hypro::Plotter< Number >::addObject(), b, hypro::plotting::blue, hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, res, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), testDBM, and hypro::Converter< Number >::toHPolytope().
Referenced by main().
void testComparison ()
Definition at line 202 of file example_differenceBounds.cpp.
Referenced by main().
void testContains ()
Definition at line 440 of file example_differenceBounds.cpp.
References contains, testDBM, and testDBM2.
Referenced by main().
void testContainsPoint ()
Definition at line 468 of file example_differenceBounds.cpp.
References contains, point, and testDBM.
Referenced by main().
void testConversionBoxToDBM ()
Definition at line 583 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), box, hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), and hypro::Converter< Number >::toDifferenceBounds().
Referenced by main().
void testConversionDifferenceBoundsToDifferenceBounds ()
Definition at line 537 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), testDBM, and hypro::Converter< Number >::toDifferenceBounds().
Referenced by main().
void testConversionHPolyToDBM ()
Definition at line 558 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), testHPolytope, and hypro::Converter< Number >::toDifferenceBounds().
Referenced by main().
void testCopy ()
Definition at line 396 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, hypro::Plotter< Number >::plot2d(), hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), and testDBM.
Referenced by main().
void testElapse ()
Definition at line 320 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, hypro::Plotter< Number >::plot2d(), hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), and testDBM.
Referenced by main().
void testEmpty ()
Definition at line 435 of file example_differenceBounds.cpp.
References isEmpty, and testDBM.
Referenced by main().
void testExtraLU ()
Definition at line 942 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::plotting::blue, hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), and testDBMExtra.
Referenced by main().
void testExtraLUPlus ()
Definition at line 985 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::plotting::blue, hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), and testDBMExtra.
Referenced by main().
void testExtraM ()
Definition at line 862 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::plotting::blue, hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), and testDBMExtra.
Referenced by main().
void testExtraMPlus ()
Definition at line 900 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::plotting::blue, hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), and testDBMExtra.
Referenced by main().
void testFree ()
Definition at line 358 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, hypro::Plotter< Number >::plot2d(), hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), and testDBM.
Referenced by main().
void testIntersectConstraint ()
Definition at line 445 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, intersection, hypro::Plotter< Number >::plot2d(), hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), and testDBM.
Referenced by main().
void testIntersectDBM ()
Definition at line 476 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::plotting::blue, hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, intersection, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), testDBM, and testDBM3.
Referenced by main().
void testIntersectHalfspace ()
Definition at line 683 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::plotting::blue, hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, res, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), testDBM, and hypro::Halfspace< Number >::vertices().
Referenced by main().
void testIntersectHalfspaces ()
Definition at line 709 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::plotting::blue, hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, mat, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, res, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), testDBM, and vec.
Referenced by main().
void testLinearTransformation ()
Definition at line 750 of file example_differenceBounds.cpp.
References A, hypro::Plotter< Number >::addObject(), hypro::plotting::blue, hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, res, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), testDBM, and hypro::Converter< Number >::toHPolytope().
Referenced by main().
void testMinkowskiSum ()
Definition at line 826 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::plotting::blue, hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, hypro::plotting::orange, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, res, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), testDBM, testDBM2, and hypro::Converter< Number >::toHPolytope().
Referenced by main().
void testPlus ()
Definition at line 249 of file example_differenceBounds.cpp.
Referenced by main().
void testPrint ()
Definition at line 1029 of file example_differenceBounds.cpp.
References testDBM.
void testReset ()
Definition at line 377 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, hypro::Plotter< Number >::plot2d(), reset, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), and testDBM.
Referenced by main().
void testRewind ()
Definition at line 339 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, hypro::Plotter< Number >::plot2d(), hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), and testDBM.
Referenced by main().
void testSatisfiesHalfspace ()
Definition at line 611 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::plotting::blue, hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, res, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), testDBM, and hypro::Halfspace< Number >::vertices().
Referenced by main().
void testSatisfiesHalfspaces ()
Definition at line 641 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::plotting::blue, hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, mat, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, res, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), testDBM, and vec.
Referenced by main().
void testShift ()
Definition at line 415 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, hypro::Plotter< Number >::plot2d(), hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), and testDBM.
Referenced by main().
void testUnion ()
Definition at line 507 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::plotting::blue, hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), testDBM, and testDBM3.
Referenced by main().
void testVertices ()
Definition at line 296 of file example_differenceBounds.cpp.
References hypro::Plotter< Number >::addObject(), hypro::Plotter< Number >::clear(), hypro::plotting::colors, hypro::plotting::green, hypro::Plotter< Number >::plot2d(), hypro::plotting::red, hypro::Plotter< Number >::setFilename(), hypro::Plotter< Number >::setObjectColor(), testDBM, and testDBM2.
Referenced by main().
Variable Documentation
hypro::DifferenceBounds<Number> testDBM
Definition at line 12 of file example_differenceBounds.cpp.
Referenced by createTestDBM(), createTestDBM3(), testAffineTransformation(), testContains(), testContainsPoint(), testConversionDifferenceBoundsToDifferenceBounds(), testCopy(), testElapse(), testEmpty(), testFree(), testIntersectConstraint(), testIntersectDBM(), testIntersectHalfspace(), testIntersectHalfspaces(), testLinearTransformation(), testMinkowskiSum(), testPrint(), testReset(), testRewind(), testSatisfiesHalfspace(), testSatisfiesHalfspaces(), testShift(), testUnion(), and testVertices().
hypro::DifferenceBounds<Number> testDBM2
Definition at line 13 of file example_differenceBounds.cpp.
Referenced by createTestDBM2(), testContains(), testMinkowskiSum(), and testVertices().
hypro::DifferenceBounds<Number> testDBM3
Definition at line 14 of file example_differenceBounds.cpp.
Referenced by createTestDBM3(), testIntersectDBM(), and testUnion().
hypro::DifferenceBounds<Number> testDBMExtra
Definition at line 15 of file example_differenceBounds.cpp.
Referenced by createTestDBMExtra(), testExtraLU(), testExtraLUPlus(), testExtraM(), and testExtraMPlus().
hypro::HPolytope<Number> testHPolytope
Definition at line 16 of file example_differenceBounds.cpp.
Referenced by createTestHPolytope(), and testConversionHPolyToDBM().