HyPro: /home/travis/build/hypro/hypro/examples/CMakeLists.txt File Reference
/home/travis/build/hypro/hypro/examples/CMakeLists.txt File Reference
Functions
file (GLOB EXAMPLES RELATIVE ${CMAKE_CURRENT_LIST_DIR}example_ *.cpp) add_custom_target(allExamples) if(STATICLIB_SWITCH) set(CMAKE_EXE_LINKER_FLAGS"-static") set(BUILD_SHARED_LIBS OFF) endif() foreach(example $
string (REPLACE".cpp"""example_name ${example}) add_executable($
Function Documentation
file (GLOB EXAMPLES RELATIVE ${CMAKE_CURRENT_LIST_DIR}example_ *. cpp)
Definition at line 1 of file CMakeLists.txt.
Referenced by configure_file(), and MReach::setSettings().
string (REPLACE".cpp"""example_name ${example})
Definition at line 11 of file CMakeLists.txt.
Referenced by hypro::HybridAutomaton< Number >::addGlobalBadState(), hypro::Transition< N >::addLabel(), hypro::ReachTreeNode< State >::addTimeStepToPath(), hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals(), hypro::NonLinearOmega0Supportfunction< Setting >::boxoperator(), hypro::NonLinearOmega0Supportfunction< Setting >::calcepsilon(), hypro::NonLinearOmega0Supportfunction< Setting >::calcvalues(), hypro::EventTimingProvider< Number >::clear(), hypro::computeDirectionMapping(), hypro::contains(), createComponent1(), createComponent2(), createComponent3(), createComponent4(), hypro::parser::createFlowstarParseTree(), hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::FacetSpace(), hypro::BoxSupportFunction< Number, Setting >::getIntervals(), hypro::Location< N >::getName(), hypro::HybridAutomatonLexer::Initializer::Initializer(), hypro::HybridSystemLexer::Initializer::Initializer(), hypro::HybridAutomatonParser::Initializer::Initializer(), hypro::HybridSystemParser::Initializer::Initializer(), hypro::PolytopeSupportFunction< Number, Setting >::isTemplate(), main(), ObjectHandle::mLocCondMap2Hypro(), ObjectHandle::mStringVector2Hypro(), hypro::NonLinearOmega0Supportfunction< Setting >::NonLinearOmega0Supportfunction(), hypro::Optimizer< Number >::Optimizer(), hypro::parseFlowstarFile< double >(), hypro::parseFlowstarFile< mpq_class >(), hypro::Plotter< Number >::Plotter(), hypro::SupportFunctionContent< Number, Setting >::printLevel(), hypro::z3Context::real_val(), hypro::Location< N >::setInvariant(), MReach::setSettings(), MReach::settings(), hypro::NonLinearOmega0Supportfunction< Setting >::specificEvaluation(), hypro::ErrorListener::syntaxError(), hypro::z3OptimizeLinear(), hypro::ErrorListener::~ErrorListener(), hypro::HybridAutomaton< Number >::~HybridAutomaton(), and hypro::ReachTree< State >::~ReachTree().