HyPro: /home/travis/build/hypro/hypro/examples/example_eigenSimpleFlow.cpp File Reference
example_eigenSimpleFlow.cpp File Reference
Classes
struct Flags
struct Input_equation
struct Invariants
struct Independent_part_funct
struct Dependent_part_funct
struct Eval_functions
struct Flowpipe_segment
Typedefs
using Number = double
using VPoly = VPolytope< Number >
typedef struct Flags Flags
typedef struct Input_equation In_eq
typedef struct Invariants Invar
typedef struct Independent_part_funct Ind_f
typedef struct Dependent_part_funct Dep_f
typedef struct Eval_functions Eval_f
typedef struct Flowpipe_segment Flow_seg
Functions
void declare_structures (const int n, In_eq &in_eq1, Invar &invar, Ind_f &ind_f, Dep_f &dep_f, Dep_f &in_traj, Eval_f &eval_f)
void mark_x0isMin (Matrix< Number > &x_tr, const int n)
void swap_x0isMax (Matrix< Number > &x_tr, const int n)
void initialize (Eval_f &eval_f, Flow_seg &safe_seg, Flow_seg &error_seg, std::size_t DIM_PLOT, bool ORIG_SYS_PLOT, const DiagonalMatrix< Number > &D, const int n, const Matrix< Number > &V, Dep_f &dep_f)
void loop (std::vector< VPoly > &flow, std::vector< VPoly > &error_flow, const Flags &flag1, const Ind_f &ind_f, const int n, const Matrix< Number > &V, Eval_f &eval_f, Dep_f &dep_f, Flow_seg &safe_seg, Flow_seg &error_seg)
void trajectory_plot (std::vector< VPoly > &exactflow, std::size_t DIM_PLOT, bool ORIG_SYS_PLOT, const Ind_f &ind_f, const int n, const Matrix< Number > &V, const std::size_t traj_scale, Dep_f &in_traj)
void plot_addTimeSegment (Flow_seg &safe_seg, std::size_t DIM_PLOT, bool ORIG_SYS_PLOT, const std::size_t traj_time, const Matrix< Number > &x_tr, const Matrix< Number > &V, const int n)
void addSegment (std::vector< VPoly > &flow, bool PLOT, Flow_seg &safe_seg, std::size_t colorUpper, std::size_t colorLower)
int main (int argc, char **argv)
Typedef Documentation
typedef struct Dependent_part_funct Dep_f
typedef struct Eval_functions Eval_f
typedef struct Flags Flags
typedef struct Flowpipe_segment Flow_seg
typedef struct Input_equation In_eq
typedef struct Independent_part_funct Ind_f
typedef struct Invariants Invar
using Number = double
Definition at line 10 of file example_eigenSimpleFlow.cpp.
using VPoly = VPolytope<Number>
Definition at line 11 of file example_eigenSimpleFlow.cpp.
Function Documentation
void addSegment (std::vector< VPoly > & flow, bool PLOT, Flow_seg & safe_seg, std::size_t colorUpper, std::size_t colorLower)
Definition at line 474 of file example_eigenSimpleFlow.cpp.
References hypro::Plotter< Number >::addObject(), Flowpipe_segment::lower, hypro::Plotter< Number >::setObjectColor(), Flowpipe_segment::upper, and v.
Referenced by loop(), and trajectory_plot().
void declare_structures (const int n, In_eq & in_eq1, Invar & invar, Ind_f & ind_f, Dep_f & dep_f, Dep_f & in_traj, Eval_f & eval_f)
Definition at line 251 of file example_eigenSimpleFlow.cpp.
References Input_equation::A, Input_equation::b, Independent_part_funct::D, Eval_functions::deriv, Eval_functions::direct, Invariants::iAV, Invariants::ib, Input_equation::x0, Input_equation::x0_2, Dependent_part_funct::x_tr, Dependent_part_funct::xhom, and Independent_part_funct::xinhom.
void initialize (Eval_f & eval_f, Flow_seg & safe_seg, Flow_seg & error_seg, std::size_t DIM_PLOT, bool ORIG_SYS_PLOT, const DiagonalMatrix< Number > & D, const int n, const Matrix< Number > & V, Dep_f & dep_f)
Definition at line 299 of file example_eigenSimpleFlow.cpp.
References Eval_functions::deriv, Eval_functions::direct, i, plot_addTimeSegment(), swap_x0isMax(), Dependent_part_funct::x_tr, and Dependent_part_funct::xhom.
Referenced by better_enums::_initialize_at_program_start< Enum >::_initialize_at_program_start(), and hypro::HierarchicalIntervalVector< CONTAINMENT, tNumber >::~HierarchicalIntervalVector().
void loop (std::vector< VPoly > & flow, std::vector< VPoly > & error_flow, const Flags & flag1, const Ind_f & ind_f, const int n, const Matrix< Number > & V, Eval_f & eval_f, Dep_f & dep_f, Flow_seg & safe_seg, Flow_seg & error_seg)
Definition at line 364 of file example_eigenSimpleFlow.cpp.
References addSegment(), hypro::plotting::blue, hypro::plotting::colors, Independent_part_funct::D, Independent_part_funct::delta, Independent_part_funct::deltalimit, Eval_functions::deriv, Flags::DIM_PLOT, Eval_functions::direct, Flags::ERROR_PLOT, Flags::HULL_PLOT, i, Flags::ORIG_SYS_PLOT, plot_addTimeSegment(), hypro::plotting::red, swap_x0isMax(), Dependent_part_funct::x_tr, Dependent_part_funct::xhom, and Independent_part_funct::xinhom.
int main (int argc, char ** argv)
Definition at line 85 of file example_eigenSimpleFlow.cpp.
References filename, hypro::Transformation< Number >::output_HybridAutomaton(), and string().
void mark_x0isMin (Matrix< Number > & x_tr, const int n)
Definition at line 271 of file example_eigenSimpleFlow.cpp.
References i.
void plot_addTimeSegment (Flow_seg & safe_seg, std::size_t DIM_PLOT, bool ORIG_SYS_PLOT, const std::size_t traj_time, const Matrix< Number > & x_tr, const Matrix< Number > & V, const int n)
Definition at line 457 of file example_eigenSimpleFlow.cpp.
References Flowpipe_segment::lower, and Flowpipe_segment::upper.
Referenced by initialize(), loop(), and trajectory_plot().
void swap_x0isMax (Matrix< Number > & x_tr, const int n)
Definition at line 279 of file example_eigenSimpleFlow.cpp.
References i, and tmp.
Referenced by initialize(), and loop().
void trajectory_plot (std::vector< VPoly > & exactflow, std::size_t DIM_PLOT, bool ORIG_SYS_PLOT, const Ind_f & ind_f, const int n, const Matrix< Number > & V, const std::size_t traj_scale, Dep_f & in_traj)
Definition at line 430 of file example_eigenSimpleFlow.cpp.
References addSegment(), hypro::plotting::colors, Independent_part_funct::D, Independent_part_funct::delta, Independent_part_funct::deltalimit, hypro::plotting::green, i, plot_addTimeSegment(), Dependent_part_funct::x_tr, Dependent_part_funct::xhom, and Independent_part_funct::xinhom.