HyPro: /home/travis/build/hypro/hypro/examples/example_sfIntersection.cpp File Reference
example_sfIntersection.cpp File Reference
Typedefs
using Number = double
using Matrix = matrix_t< Number >
using Vector = vector_t< Number >
Functions
Number sandwichValue (const SupportFunction< Number > &obj, Vector a, Number b, Vector direction, Number lambda)
Number lowerBound (const SupportFunction< Number > &obj, Vector a, Number b, Vector direction, Number lambdaI, Number lambdaJ, Number lambda)
std::pair< Number, Number > determineLowerBound (const SupportFunction< Number > &obj, Vector a, Number b, Vector direction)
int main ()
Typedef Documentation
using Matrix = matrix_t<Number>
Definition at line 6 of file example_sfIntersection.cpp.
using Number = double
Definition at line 5 of file example_sfIntersection.cpp.
using Vector = vector_t<Number>
Definition at line 7 of file example_sfIntersection.cpp.
Function Documentation
std::pair<Number, Number> determineLowerBound (const SupportFunction< Number > & obj, Vector a, Number b, Vector direction)
Definition at line 40 of file example_sfIntersection.cpp.
References sandwichValue().
Referenced by main().
Number lowerBound (const SupportFunction< Number > & obj, Vector a, Number b, Vector direction, Number lambdaI, Number lambdaJ, Number lambda)
Definition at line 16 of file example_sfIntersection.cpp.
References sandwichValue().
Referenced by hypro::TimedContext< State >::handshakeTimestamps(), hypro::sample(), and hypro::Converter< Number >::toBox().
int main ()
Definition at line 80 of file example_sfIntersection.cpp.
References hypro::Plotter< Number >::addObject(), determineLowerBound(), and hypro::Plotter< Number >::plot2d().
Number sandwichValue (const SupportFunction< Number > & obj, Vector a, Number b, Vector direction, Number lambda)
Definition at line 9 of file example_sfIntersection.cpp.
Referenced by determineLowerBound(), and lowerBound().