HyPro: /home/travis/build/hypro/hypro/examples/example_worker.cpp File Reference
example_worker.cpp File Reference
Functions
int main (int argc, char **argv)
Example file which shows how to instanciate a concrete worker out of context handlers.
Function Documentation
int main (int argc, char ** argv)
Example file which shows how to instanciate a concrete worker out of context handlers.
Definition at line 16 of file example_worker.cpp.
References hypro::WorkQueueManager< Workable >::addQueue(), hypro::AGG, assert(), filename, hypro::WorkQueueManager< Workable >::getNextWorkable(), hypro::ReachTree< State >::getRoot(), hypro::WorkQueueManager< Workable >::hasWorkable(), i, hypro::EventTimingProvider< Number >::initialize(), initialStates(), hypro::ContextBasedReachabilityWorker< State >::processTask(), hypro::Decomposition::push_back(), hypro::ReachTreeNode< State >::setTimestamp(), state, string(), hypro::TIMED, and tree.