HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/CORA_benchmarks/findSafetyProperties.m File Reference
findSafetyProperties.m File Reference
Functions
values (counter, 1)
values (counter, 2)
min (row)
max (row)
end if values (i, 2) > max(row) max(row)
Variables
function out
max = zeros(size(spec,1),1)
spec_counter = 1
for row
counter = 1
for i
vector = prepareValues(ReachableSet{i}{j}, size(spec,2))
temp = matrix * vector
value = sum(temp)
end end matrix = [-1 * spec
spec
vect = [-1 * min
Function Documentation
max (row)
min (row)
Referenced by CLANG_WARNING_DISABLE(), hypro::RGBtoHSV(), and target_include_dirs_from().
values (counter , 1)
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::boxoperator(), and main().
values (counter , 2)
end if values (i , 2)
Variable Documentation
counter = 1
Definition at line 11 of file findSafetyProperties.m.
Referenced by hypro::directionList2Matrix(), and hypro::list2Array().
for i
Initial value:
=1:length(ReachableSet)
            for j = 1:length(ReachableSet{i})
                % Check every specification for current set
                matrix = diag(spec(spec_counter,:))
Definition at line 12 of file findSafetyProperties.m.
end end matrix = [-1 * spec
Definition at line 37 of file findSafetyProperties.m.
Referenced by hypro::Facet< Number >::getNormalVector(), main(), ObjectHandle::mMatrix2Hypro(), and ObjectHandle::mVectorOfVectors2Hypro().
max = zeros(size(spec,1),1)
Definition at line 6 of file findSafetyProperties.m.
Referenced by hypro::NonLinearOmega0Supportfunction< Setting >::boxoperator(), hypro::Facet< Number >::furthest_Point(), std::max(), hypro::RGBtoHSV(), and hypro::Leaf< Number, Converter, Setting, Representation >::supremumPoint().
out
Initial value:
= findSafetyProperties(spec, ReachableSet)
% Create vector with variable values
min = zeros(size(spec,1),1)
Definition at line 1 of file findSafetyProperties.m.
for row
Initial value:
= 1:size(spec,1)
        values = zeros((length(ReachableSet) * length(ReachableSet{1})), 2)
Definition at line 9 of file findSafetyProperties.m.
Referenced by hypro::linearFlow< N >::addRow(), hypro::decomposeConstraintSet(), hypro::halfspacesToConstraints(), hypro::Halfspace< Number >::isInteger(), and main().
spec
Definition at line 37 of file findSafetyProperties.m.
end end spec_counter = 1
Definition at line 8 of file findSafetyProperties.m.
temp = matrix * vector
Definition at line 17 of file findSafetyProperties.m.
value = sum(temp)
Definition at line 18 of file findSafetyProperties.m.
Referenced by hypro::as_integer(), CLANG_WARNING_DISABLE(), hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation(), and hypro::Parameters< Rargs >::size().
vect = [-1 * min
Definition at line 38 of file findSafetyProperties.m.
end vector = prepareValues(ReachableSet{i}{j}, size(spec,2))
Definition at line 16 of file findSafetyProperties.m.
Referenced by hypro::SupportFunctionNewT< Number, Converter, Setting >::assignIntervals(), hypro::BoxT< Number, hypro::Converter, Setting >::BoxT(), hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT(), CLANG_WARNING_DISABLE(), hypro::SupportFunctionNewT< Number, Converter, Setting >::Empty(), hypro::Reset< N >::getIntervalResets(), hypro::SupportFunctionContent< Number, Setting >::getThis(), hypro::IntersectOp< Number, Converter, Setting >::IntersectOp(), hypro::Halfspace< Number >::isInteger(), hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), main(), ObjectHandle::mVector2Hypro(), ObjectHandle::mVectorOfVectors2Hypro(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT(), hypro::Plotter< Number >::Plotter(), hypro::reduceIntervalsNumberRepresentation(), hypro::SupportFunctionT< Number, Converter, Setting >::reduceNumberRepresentation(), hypro::HPolytopeT< Number, Converter, Setting >::reduceNumberRepresentation(), hypro::Reset< N >::Reset(), hypro::PrincipalComponentAnalysis< Number >::samples(), hypro::selectCols(), hypro::CarlPolytopeT< Number, Converter, Setting >::setDimension(), hypro::Location< N >::setInvariant(), hypro::SumOp< Number, Converter, Setting >::SumOp(), hypro::UnionOp< Number, Converter, Setting >::UnionOp(), and hypro::Point< int >::Zero().