var hierarchy =
[
    [ "better_enums::_eat_assign< EnumType >", "structbetter__enums_1_1__eat__assign.html", null ],
    [ "better_enums::_initialize_at_program_start< Enum >", "structbetter__enums_1_1__initialize__at__program__start.html", null ],
    [ "better_enums::_iterable< Element >", "structbetter__enums_1_1__iterable.html", null ],
    [ "hypro::AffineTransformation< Number >", "structhypro_1_1_affine_transformation.html", null ],
    [ "hypro::AffineTransformation< N >", "structhypro_1_1_affine_transformation.html", null ],
    [ "hypro::AffineTransformation< rep_number< Representation > >", "structhypro_1_1_affine_transformation.html", null ],
    [ "hypro::LTIWorker< Representation >::AggregatedGen", "structhypro_1_1_l_t_i_worker_1_1_aggregated_gen.html", null ],
    [ "hypro::AnalysisParameters", "namespacehypro.html#structhypro_1_1_analysis_parameters", null ],
    [ "hypro::AnalysisResult< Success, Failure >", "structhypro_1_1_analysis_result.html", null ],
    [ "hypro::analyzer_rep_i< Representation >", "namespacehypro.html#structhypro_1_1analyzer__rep__i", null ],
    [ "hypro::analyzer_rep_i< Analyzer< Rep, Ts... > >", "namespacehypro.html#structhypro_1_1analyzer__rep__i_3_01_analyzer_3_01_rep_00_01_ts_8_8_8_01_4_01_4", null ],
    [ "hypro::apply_i< Templ, ArgList >", "namespacehypro.html#structhypro_1_1apply__i", null ],
    [ "hypro::apply_i< Templ, TypeList< Args... > >", "namespacehypro.html#structhypro_1_1apply__i_3_01_templ_00_01_type_list_3_01_args_8_8_8_01_4_01_4", null ],
    [ "hypro::BallSupportFunction< Number >", "classhypro_1_1_ball_support_function.html", null ],
    [ "hypro::reachability::detail::bloatBoxVisitor< VariantType, Number >", "classhypro_1_1reachability_1_1detail_1_1bloat_box_visitor.html", null ],
    [ "hypro::BoxAllOff", "structhypro_1_1_box_all_off.html", null ],
    [ "hypro::BoxIntervalArithmeticOff", "structhypro_1_1_box_interval_arithmetic_off.html", null ],
    [ "hypro::BoxLinearOptimizationOff", "structhypro_1_1_box_linear_optimization_off.html", null ],
    [ "hypro::BoxSupportFunction< Number, Setting >", "classhypro_1_1_box_support_function.html", null ],
    [ "hypro::Cacheable< Content >", "structhypro_1_1_cacheable.html", null ],
    [ "hypro::Cacheable< matrix_t< Number > >", "structhypro_1_1_cacheable.html", null ],
    [ "hypro::Cacheable< vector_t< Number > >", "structhypro_1_1_cacheable.html", null ],
    [ "hypro::CEGARAnalyzer< Number, Representations >", "classhypro_1_1_c_e_g_a_r_analyzer.html", null ],
    [ "hypro::qe::CellTreeNode< Data >", "structhypro_1_1qe_1_1_cell_tree_node.html", null ],
    [ "hypro::ChildNodeGen< Representation >", "structhypro_1_1_child_node_gen.html", null ],
    [ "hypro::ChildTimingInformation< N >", "namespacehypro.html#structhypro_1_1_child_timing_information", null ],
    [ "hypro::ChildTimingInformation< Number >", "namespacehypro.html#namespacehypro", null ],
    [ "hypro::clp_context", "structhypro_1_1clp__context.html", null ],
    [ "hypro::concat_i< List, Lists >", "namespacehypro.html#structhypro_1_1concat__i", null ],
    [ "hypro::concat_i< TypeList< Ts... > >", "namespacehypro.html#structhypro_1_1concat__i_3_01_type_list_3_01_ts_8_8_8_01_4_01_4", null ],
    [ "hypro::concat_i< TypeList< Ts... >, TypeList< Us... > >", "namespacehypro.html#structhypro_1_1concat__i_3_01_type_list_3_01_ts_8_8_8_01_4_00_01_type_list_3_01_us_8_8_8_01_4_01_4", null ],
    [ "hypro::Cone< Number >", "classhypro_1_1_cone.html", null ],
    [ "hypro::ConstrainSet< Number >", "classhypro_1_1_constrain_set.html", null ],
    [ "hypro::ConstraintSetSettings", "namespacehypro.html#structhypro_1_1_constraint_set_settings", null ],
    [ "hypro::ConstraintSetT< Number, S >", "classhypro_1_1_constraint_set_t.html", null ],
    [ "hypro::ConstraintSetT< N >", "classhypro_1_1_constraint_set_t.html", null ],
    [ "hypro::ConstraintSetT< Number >", "classhypro_1_1_constraint_set_t.html", null ],
    [ "hypro::ConstraintSetT< rep_number< Representation > >", "classhypro_1_1_constraint_set_t.html", null ],
    [ "context", null, [
      [ "hypro::z3Context", "classhypro_1_1z3_context.html", null ]
    ] ],
    [ "hypro::ContinuousSystem< Number >", "classhypro_1_1_continuous_system.html", null ],
    [ "hypro::Converter< Number >", "classhypro_1_1_converter.html", null ],
    [ "hypro::ConvexHull< Number >", "classhypro_1_1_convex_hull.html", null ],
    [ "hypro::statistics::CounterRepository", "classhypro_1_1statistics_1_1_counter_repository.html", null ],
    [ "hypro::CEGARAnalyzer< Number, Representations >::CreateBaseLevel", "structhypro_1_1_c_e_g_a_r_analyzer_1_1_create_base_level.html", null ],
    [ "hypro::CEGARAnalyzer< Number, Representations >::CreateRefinementLevel", "structhypro_1_1_c_e_g_a_r_analyzer_1_1_create_refinement_level.html", null ],
    [ "hypro::DAGNode< Data >", "classhypro_1_1_d_a_g_node.html", [
      [ "hypro::EventTimingNode< N >", "classhypro_1_1_event_timing_node.html", null ]
    ] ],
    [ "hypro::DAGNode< EventTimingNode< Number > >", "classhypro_1_1_d_a_g_node.html", [
      [ "hypro::EventTimingNode< Number >", "classhypro_1_1_event_timing_node.html", null ]
    ] ],
    [ "hypro::Decomposition", "namespacehypro.html#structhypro_1_1_decomposition", null ],
    [ "hypro::Dictionary< Number >", "classhypro_1_1_dictionary.html", null ],
    [ "hypro::DifferenceBoundsSetting", "namespacehypro.html#structhypro_1_1_difference_bounds_setting", null ],
    [ "hypro::Dispatcher_i< Representation, Representations >", "structhypro_1_1_dispatcher__i.html", null ],
    [ "hypro::Dispatcher_i< Representation >", "structhypro_1_1_dispatcher__i_3_01_representation_01_4.html", null ],
    [ "hypro::Domain< Number >", "classhypro_1_1_domain.html", null ],
    [ "hypro::Dummy", "structhypro_1_1_dummy.html", null ],
    [ "element", null, [
      [ "std::tuple_element< I, boost::tuples::cons< T, U > >", "structstd_1_1tuple__element_3_01_i_00_01boost_1_1tuples_1_1cons_3_01_t_00_01_u_01_4_01_4.html", null ]
    ] ],
    [ "hypro::EllipsoidSupportFunction< Number >", "classhypro_1_1_ellipsoid_support_function.html", null ],
    [ "hypro::EllipsoidT< Number, Converter >", "classhypro_1_1_ellipsoid_t.html", null ],
    [ "hypro::LTIWorker< Representation >::EnabledSegmentsGen", "structhypro_1_1_l_t_i_worker_1_1_enabled_segments_gen.html", null ],
    [ "hypro::EnabledSets< Representation >", "namespacehypro.html#structhypro_1_1_enabled_sets", null ],
    [ "hypro::endPoint< T, Number >", "structhypro_1_1end_point.html", null ],
    [ "hypro::endPoint< CONTAINMENT, tNumber >", "structhypro_1_1end_point.html", null ],
    [ "hypro::ErrorBoxes< Number >", "namespacehypro.html#structhypro_1_1_error_boxes", null ],
    [ "hypro::EvaluationResult< Number >", "structhypro_1_1_evaluation_result.html", null ],
    [ "hypro::EventTimingContainer< Number >", "classhypro_1_1_event_timing_container.html", null ],
    [ "hypro::EventTimingContainer< N >", "classhypro_1_1_event_timing_container.html", null ],
    [ "std::exception", null, [
      [ "hypro::FinishWithDiscreteProcessingException", "classhypro_1_1_finish_with_discrete_processing_exception.html", null ],
      [ "hypro::HardTerminateException", "classhypro_1_1_hard_terminate_exception.html", null ]
    ] ],
    [ "hypro::ExactQuickhull::Facet< Number, Euclidian >", "structhypro_1_1_exact_quickhull_1_1_facet.html", null ],
    [ "hypro::Facet< Number >", "classhypro_1_1_facet.html", null ],
    [ "hypro::ExactQuickhull::FacetSpace< Number, Euclidian >", "classhypro_1_1_exact_quickhull_1_1_facet_space.html", null ],
    [ "hypro::Failure< Representation >", "namespacehypro.html#structhypro_1_1_failure", null ],
    [ "false_type", null, [
      [ "hypro::is_flow< T >", "structhypro_1_1is__flow.html", null ],
      [ "hypro::is_shared_ptr< T >", "structhypro_1_1is__shared__ptr.html", null ],
      [ "hypro::is_unique_ptr< T >", "structhypro_1_1is__unique__ptr.html", null ]
    ] ],
    [ "hypro::Fan< Number >", "classhypro_1_1_fan.html", null ],
    [ "hypro::FixedAnalysisParameters", "namespacehypro.html#structhypro_1_1_fixed_analysis_parameters", null ],
    [ "hypro::flattenRepresentations_i< Number, Converter, CombinationsList >", "namespacehypro.html#structhypro_1_1flatten_representations__i", null ],
    [ "hypro::flattenRepresentations_i< Number, Converter, TypeList< RepCombinationsList... > >", "namespacehypro.html#structhypro_1_1flatten_representations__i_3_01_number_00_01_converter_00_01_type_list_3_01_rep_c998c63914da0aac3968b8b40e6527b30", null ],
    [ "hypro::flowDimensionVisitor", "structhypro_1_1flow_dimension_visitor.html", null ],
    [ "hypro::flowDynamicsTypeVisitor", "structhypro_1_1flow_dynamics_type_visitor.html", null ],
    [ "hypro::flowHashVisitor", "structhypro_1_1flow_hash_visitor.html", null ],
    [ "hypro::flowIsDiscreteVisitor", "structhypro_1_1flow_is_discrete_visitor.html", null ],
    [ "hypro::flowIsTimedVisitor", "structhypro_1_1flow_is_timed_visitor.html", null ],
    [ "hypro::Flowpipe< Representation >", "classhypro_1_1_flowpipe.html", null ],
    [ "hypro::Flowpipe< Number >", "classhypro_1_1_flowpipe.html", null ],
    [ "hypro::Flowpipe< State >", "classhypro_1_1_flowpipe.html", null ],
    [ "hypro::FlowpipeTimingVector", "classhypro_1_1_flowpipe_timing_vector.html", null ],
    [ "hypro::flowTypeVisitor", "structhypro_1_1flow_type_visitor.html", null ],
    [ "hypro::FourierMotzkinQE< Number >", "classhypro_1_1_fourier_motzkin_q_e.html", null ],
    [ "hypro::detail::gen_seq< N, Is >", "structhypro_1_1detail_1_1gen__seq.html", null ],
    [ "hypro::genericAffineTransformationVisitor< T, Number >", "classhypro_1_1generic_affine_transformation_visitor.html", null ],
    [ "hypro::genericAssignIntervalsVisitor< T, N >", "classhypro_1_1generic_assign_intervals_visitor.html", null ],
    [ "hypro::genericCompareVisitor", "classhypro_1_1generic_compare_visitor.html", null ],
    [ "hypro::genericConversionVisitor< T, To >", "classhypro_1_1generic_conversion_visitor.html", null ],
    [ "hypro::genericConvertAndGetVisitor< OutType >", "classhypro_1_1generic_convert_and_get_visitor.html", null ],
    [ "hypro::genericDimensionVisitor", "classhypro_1_1generic_dimension_visitor.html", null ],
    [ "hypro::genericEmptyVisitor", "classhypro_1_1generic_empty_visitor.html", null ],
    [ "hypro::genericInternalConversionVisitor< T, Ext >", "classhypro_1_1generic_internal_conversion_visitor.html", null ],
    [ "hypro::genericIntersectVisitor< T >", "classhypro_1_1generic_intersect_visitor.html", null ],
    [ "hypro::genericIntervalAssignmentVisitor< T, Number >", "classhypro_1_1generic_interval_assignment_visitor.html", null ],
    [ "hypro::genericMinkowskiSumVisitor< T >", "classhypro_1_1generic_minkowski_sum_visitor.html", null ],
    [ "GenericNumTraits", null, [
      [ "Eigen::NumTraits< mpq_class >", "struct_eigen_1_1_num_traits_3_01mpq__class_01_4.html", null ]
    ] ],
    [ "hypro::genericOutstreamVisitor", "classhypro_1_1generic_outstream_visitor.html", null ],
    [ "hypro::genericProjectionVisitor< T >", "classhypro_1_1generic_projection_visitor.html", null ],
    [ "hypro::genericReductionVisitor< T, Number >", "classhypro_1_1generic_reduction_visitor.html", null ],
    [ "hypro::genericRedundancyVisitor< T, Number >", "classhypro_1_1generic_redundancy_visitor.html", null ],
    [ "hypro::genericSatisfiesHalfspacesVisitor< T, Number >", "classhypro_1_1generic_satisfies_halfspaces_visitor.html", null ],
    [ "hypro::genericSetContainsVisitor", "classhypro_1_1generic_set_contains_visitor.html", null ],
    [ "hypro::genericSupremumVisitor< T >", "classhypro_1_1generic_supremum_visitor.html", null ],
    [ "hypro::genericToStringVisitor", "classhypro_1_1generic_to_string_visitor.html", null ],
    [ "hypro::genericTypeVisitor", "classhypro_1_1generic_type_visitor.html", null ],
    [ "hypro::genericUniteVisitor< T >", "classhypro_1_1generic_unite_visitor.html", null ],
    [ "hypro::genericVerticesVisitor< Number >", "classhypro_1_1generic_vertices_visitor.html", null ],
    [ "hypro::GeometricObjectBase", "classhypro_1_1_geometric_object_base.html", [
      [ "hypro::BoxT< Number, hypro::Converter, Setting >", "classhypro_1_1_box_t.html", null ],
      [ "hypro::BoxT< Number, Converter, Setting >", "classhypro_1_1_box_t.html", null ],
      [ "hypro::CarlPolytopeT< Number, Converter, Setting >", "classhypro_1_1_carl_polytope_t.html", null ],
      [ "hypro::DifferenceBoundsT< Number, Converter, Setting >", "classhypro_1_1_difference_bounds_t.html", null ],
      [ "hypro::GeneralizedStarT< Number, Converter, Setting >", "classhypro_1_1_generalized_star_t.html", null ],
      [ "hypro::HPolytopeT< Number, Converter, Setting >", "classhypro_1_1_h_polytope_t.html", null ],
      [ "hypro::StatisticWrapper< Representation >", "classhypro_1_1_statistic_wrapper.html", null ],
      [ "hypro::SupportFunctionNewT< Number, Converter, Setting >", "classhypro_1_1_support_function_new_t.html", null ],
      [ "hypro::SupportFunctionT< Number, Converter, Setting >", "classhypro_1_1_support_function_t.html", null ],
      [ "hypro::VPolytopeT< Number, Converter, S >", "classhypro_1_1_v_polytope_t.html", null ],
      [ "hypro::ZonotopeT< Number, Converter, Setting >", "classhypro_1_1_zonotope_t.html", null ]
    ] ],
    [ "hypro::glpk_context", "structhypro_1_1glpk__context.html", null ],
    [ "hypro::plotting::gnuplotSettings", "structhypro_1_1plotting_1_1gnuplot_settings.html", null ],
    [ "hypro::Grid< Number >", "classhypro_1_1_grid.html", null ],
    [ "hypro::guardHandlerSorter", "structhypro_1_1guard_handler_sorter.html", null ],
    [ "hypro::Halfspace< Number >", "classhypro_1_1_halfspace.html", null ],
    [ "std::hash< hypro::affineFlow< Number > >", "structstd_1_1hash_3_01hypro_1_1affine_flow_3_01_number_01_4_01_4.html", null ],
    [ "std::hash< hypro::AffineTransformation< Number > >", "structstd_1_1hash_3_01hypro_1_1_affine_transformation_3_01_number_01_4_01_4.html", null ],
    [ "std::hash< hypro::Cacheable< Content > >", "structstd_1_1hash_3_01hypro_1_1_cacheable_3_01_content_01_4_01_4.html", null ],
    [ "std::hash< hypro::Halfspace< Number > >", "structstd_1_1hash_3_01hypro_1_1_halfspace_3_01_number_01_4_01_4.html", null ],
    [ "std::hash< hypro::IntervalAssignment< Number > >", "structstd_1_1hash_3_01hypro_1_1_interval_assignment_3_01_number_01_4_01_4.html", null ],
    [ "std::hash< hypro::linearFlow< Number > >", "structstd_1_1hash_3_01hypro_1_1linear_flow_3_01_number_01_4_01_4.html", null ],
    [ "std::hash< hypro::Location< Number > >", "structstd_1_1hash_3_01hypro_1_1_location_3_01_number_01_4_01_4.html", null ],
    [ "std::hash< hypro::matrix_t< Number > >", "structstd_1_1hash_3_01hypro_1_1matrix__t_3_01_number_01_4_01_4.html", null ],
    [ "std::hash< hypro::NoneAssignment >", "structstd_1_1hash_3_01hypro_1_1_none_assignment_01_4.html", null ],
    [ "std::hash< hypro::Point< Number > >", "structstd_1_1hash_3_01hypro_1_1_point_3_01_number_01_4_01_4.html", null ],
    [ "std::hash< hypro::rectangularFlow< Number > >", "structstd_1_1hash_3_01hypro_1_1rectangular_flow_3_01_number_01_4_01_4.html", null ],
    [ "std::hash< hypro::Reset< Number > >", "structstd_1_1hash_3_01hypro_1_1_reset_3_01_number_01_4_01_4.html", null ],
    [ "std::hash< hypro::Ridge< Number > >", "structstd_1_1hash_3_01hypro_1_1_ridge_3_01_number_01_4_01_4.html", null ],
    [ "std::hash< hypro::Transition< Number > >", "structstd_1_1hash_3_01hypro_1_1_transition_3_01_number_01_4_01_4.html", null ],
    [ "std::hash< hypro::vector_t< Number > >", "structstd_1_1hash_3_01hypro_1_1vector__t_3_01_number_01_4_01_4.html", null ],
    [ "std::hash< hypro::Vertex< Number > >", "structstd_1_1hash_3_01hypro_1_1_vertex_3_01_number_01_4_01_4.html", null ],
    [ "std::hash< hypro::VertexContainer< Number > >", "structstd_1_1hash_3_01hypro_1_1_vertex_container_3_01_number_01_4_01_4.html", null ],
    [ "std::hash< set< hypro::Vertex< Number > > >", "structstd_1_1hash_3_01set_3_01hypro_1_1_vertex_3_01_number_01_4_01_4_01_4.html", null ],
    [ "std::hash< std::pair< first, second > >", "structstd_1_1hash_3_01std_1_1pair_3_01first_00_01second_01_4_01_4.html", null ],
    [ "hypro::HierarchicalIntervalVector< T, Number >", "classhypro_1_1_hierarchical_interval_vector.html", null ],
    [ "hypro::HierarchicalIntervalVector< CONTAINMENT, tNumber >", "classhypro_1_1_hierarchical_interval_vector.html", null ],
    [ "hypro::HPolytopeBoundingBoxCaching", "structhypro_1_1_h_polytope_bounding_box_caching.html", null ],
    [ "hypro::HPolytopeOptimizerCaching", "structhypro_1_1_h_polytope_optimizer_caching.html", null ],
    [ "hypro::HybridAutomaton< Number >", "classhypro_1_1_hybrid_automaton.html", null ],
    [ "hypro::HybridAutomatonComp< Number >", "classhypro_1_1_hybrid_automaton_comp.html", null ],
    [ "hypro::IContext", "classhypro_1_1_i_context.html", [
      [ "hypro::LTIContext< State >", "classhypro_1_1_l_t_i_context.html", [
        [ "hypro::TemplatePolyhedronContext< State >", "classhypro_1_1_template_polyhedron_context.html", null ],
        [ "hypro::TimedContext< State >", "classhypro_1_1_timed_context.html", null ]
      ] ],
      [ "hypro::RectangularContext< State >", "classhypro_1_1_rectangular_context.html", null ]
    ] ],
    [ "hypro::IHandler", "classhypro_1_1_i_handler.html", [
      [ "hypro::IBadStateHandler", "classhypro_1_1_i_bad_state_handler.html", null ],
      [ "hypro::IFirstSegmentHandler< State >", "classhypro_1_1_i_first_segment_handler.html", [
        [ "hypro::rectangularFirstSegmentHandler< State >", "classhypro_1_1rectangular_first_segment_handler.html", null ],
        [ "hypro::TPolyFirstSegmentHandler< State >", "classhypro_1_1_t_poly_first_segment_handler.html", null ]
      ] ],
      [ "hypro::IGuardHandler< State >", "classhypro_1_1_i_guard_handler.html", null ],
      [ "hypro::IInvariantHandler", "classhypro_1_1_i_invariant_handler.html", null ],
      [ "hypro::IJumpHandler", "classhypro_1_1_i_jump_handler.html", null ],
      [ "hypro::IResetHandler", "classhypro_1_1_i_reset_handler.html", [
        [ "hypro::ltiResetHandler< State >", "classhypro_1_1lti_reset_handler.html", [
          [ "hypro::discreteResetHandler< State >", "classhypro_1_1discrete_reset_handler.html", null ],
          [ "hypro::timedResetHandler< State >", "classhypro_1_1timed_reset_handler.html", null ]
        ] ],
        [ "hypro::rectangularResetHandler< State >", "classhypro_1_1rectangular_reset_handler.html", null ]
      ] ],
      [ "hypro::ITimeEvolutionHandler", "classhypro_1_1_i_time_evolution_handler.html", [
        [ "hypro::discreteTimeEvolutionHandler", "classhypro_1_1discrete_time_evolution_handler.html", null ],
        [ "hypro::TPolyTimeEvolutionHandler< State >", "classhypro_1_1_t_poly_time_evolution_handler.html", null ]
      ] ]
    ] ],
    [ "hypro::IndexedValuationSet< Representation >", "namespacehypro.html#structhypro_1_1_indexed_valuation_set", null ],
    [ "hypro::intersectionContent< Number, Setting >", "structhypro_1_1intersection_content.html", null ],
    [ "hypro::Interval", "structhypro_1_1_interval.html", null ],
    [ "hypro::IntervalAssignment< Number >", "structhypro_1_1_interval_assignment.html", null ],
    [ "hypro::IntervalAssignment< N >", "structhypro_1_1_interval_assignment.html", null ],
    [ "hypro::IntervalAssignment< rep_number< Representation > >", "structhypro_1_1_interval_assignment.html", null ],
    [ "hypro::IWorker< Workable, State >", "classhypro_1_1_i_worker.html", null ],
    [ "hypro::IWorker< std::shared_ptr< Task< State > >, State >", "classhypro_1_1_i_worker.html", [
      [ "hypro::ContextBasedReachabilityWorker< State >", "classhypro_1_1_context_based_reachability_worker.html", null ]
    ] ],
    [ "hypro::JumpSuccessor< Representation >", "namespacehypro.html#structhypro_1_1_jump_successor", null ],
    [ "hypro::LTIWorker< Representation >::JumpSuccessorGen", "structhypro_1_1_l_t_i_worker_1_1_jump_successor_gen.html", null ],
    [ "hypro::Label", "classhypro_1_1_label.html", null ],
    [ "length", null, [
      [ "std::tuple_size< boost::tuples::cons< T, U > >", "structstd_1_1tuple__size_3_01boost_1_1tuples_1_1cons_3_01_t_00_01_u_01_4_01_4.html", null ]
    ] ],
    [ "hypro::ZUtility::Line_t< Number >", "structhypro_1_1_z_utility_1_1_line__t.html", null ],
    [ "hypro::linearFlow< Number >", "classhypro_1_1linear_flow.html", [
      [ "hypro::affineFlow< Number >", "classhypro_1_1affine_flow.html", null ]
    ] ],
    [ "hypro::lintrafoParameters< Number >", "structhypro_1_1lintrafo_parameters.html", null ],
    [ "hypro::LinTrafoParameters< Number, Setting >", "structhypro_1_1_lin_trafo_parameters.html", null ],
    [ "hypro::Location< Number >", "classhypro_1_1_location.html", null ],
    [ "hypro::Location< N >", "classhypro_1_1_location.html", null ],
    [ "hypro::Location< rep_number< Representation > >", "classhypro_1_1_location.html", null ],
    [ "hypro::LockableBase", "classhypro_1_1_lockable_base.html", [
      [ "hypro::LockedFileWriter", "classhypro_1_1_locked_file_writer.html", null ]
    ] ],
    [ "hypro::LockableObjectWrapper< Object >", "classhypro_1_1_lockable_object_wrapper.html", null ],
    [ "hypro::locPtrComp< Number >", "structhypro_1_1loc_ptr_comp.html", null ],
    [ "hypro::LRUCache< Key, Value >", "classhypro_1_1_l_r_u_cache.html", null ],
    [ "hypro::LRUCache< hypro::Cacheable< matrix_t< Number > >, matrix_t< Number > >", "classhypro_1_1_l_r_u_cache.html", null ],
    [ "hypro::LRUCache< hypro::Cacheable< vector_t< Number > >, vector_t< Number > >", "classhypro_1_1_l_r_u_cache.html", null ],
    [ "hypro::LTIAnalyzer< State >", "classhypro_1_1_l_t_i_analyzer.html", null ],
    [ "hypro::LTIAnalyzer< Representation >", "classhypro_1_1_l_t_i_analyzer.html", null ],
    [ "hypro::ltiBadStateHandler< State >", "classhypro_1_1lti_bad_state_handler.html", [
      [ "hypro::discreteBadStateHandler< State >", "classhypro_1_1discrete_bad_state_handler.html", null ],
      [ "hypro::timedBadStateHandler< State >", "classhypro_1_1timed_bad_state_handler.html", null ]
    ] ],
    [ "hypro::ltiFirstSegmentHandler< State >", "classhypro_1_1lti_first_segment_handler.html", [
      [ "hypro::timedElapseFirstSegmentHandler< State >", "classhypro_1_1timed_elapse_first_segment_handler.html", null ],
      [ "hypro::timedFirstSegmentHandler< State >", "classhypro_1_1timed_first_segment_handler.html", null ]
    ] ],
    [ "hypro::ltiGuardHandler< State >", "classhypro_1_1lti_guard_handler.html", [
      [ "hypro::discreteGuardHandler< State >", "classhypro_1_1discrete_guard_handler.html", null ],
      [ "hypro::timedGuardHandler< State >", "classhypro_1_1timed_guard_handler.html", null ]
    ] ],
    [ "hypro::ltiInvariantHandler< State >", "classhypro_1_1lti_invariant_handler.html", [
      [ "hypro::discreteInvariantHandler< State >", "classhypro_1_1discrete_invariant_handler.html", null ],
      [ "hypro::timedInvariantHandler< State >", "classhypro_1_1timed_invariant_handler.html", null ]
    ] ],
    [ "hypro::ltiJumpHandler< State >", "classhypro_1_1lti_jump_handler.html", null ],
    [ "hypro::LTISuccess", "namespacehypro.html#structhypro_1_1_l_t_i_success", null ],
    [ "hypro::ltiTimeEvolutionHandler< State >", "classhypro_1_1lti_time_evolution_handler.html", [
      [ "hypro::timedElapseAfterTickTimeEvolutionHandler< State >", "classhypro_1_1timed_elapse_after_tick_time_evolution_handler.html", null ],
      [ "hypro::timedElapseTimeEvolutionHandler< State >", "classhypro_1_1timed_elapse_time_evolution_handler.html", null ],
      [ "hypro::timedTickTimeEvolutionHandler< State >", "classhypro_1_1timed_tick_time_evolution_handler.html", null ]
    ] ],
    [ "hypro::LTIWorker< Representation >", "classhypro_1_1_l_t_i_worker.html", null ],
    [ "Manager", null, [
      [ "smtrat::SimplexSolver", "classsmtrat_1_1_simplex_solver.html", null ]
    ] ],
    [ "better_enums::map< Enum, T, Compare >", "structbetter__enums_1_1map.html", null ],
    [ "better_enums::map_compare< T >", "structbetter__enums_1_1map__compare.html", null ],
    [ "better_enums::map_compare< const char * >", "structbetter__enums_1_1map__compare_3_01const_01char_01_5_01_4.html", null ],
    [ "better_enums::map_compare< const wchar_t * >", "structbetter__enums_1_1map__compare_3_01const_01wchar__t_01_5_01_4.html", null ],
    [ "hypro::NeighborhoodContainer", "classhypro_1_1_neighborhood_container.html", null ],
    [ "hypro::NoneAssignment", "structhypro_1_1_none_assignment.html", null ],
    [ "hypro::detail::nth_element_impl< I, T, Ts >", "structhypro_1_1detail_1_1nth__element__impl.html", null ],
    [ "hypro::detail::nth_element_impl< 0, T, Ts... >", "structhypro_1_1detail_1_1nth__element__impl_3_010_00_01_t_00_01_ts_8_8_8_01_4.html", null ],
    [ "Eigen::NumTraits< carl::FLOAT_T< Number > >", "struct_eigen_1_1_num_traits_3_01carl_1_1_f_l_o_a_t___t_3_01_number_01_4_01_4.html", null ],
    [ "hypro::statistics::OperationCounter", "structhypro_1_1statistics_1_1_operation_counter.html", [
      [ "hypro::statistics::AtomicOperationCounter", "structhypro_1_1statistics_1_1_atomic_operation_counter.html", null ]
    ] ],
    [ "hypro::Optimizer< Number >", "classhypro_1_1_optimizer.html", null ],
    [ "better_enums::optional< T >", "structbetter__enums_1_1optional.html", null ],
    [ "hypro::OrthogonalPolyhedron< Number, NEIGHBORHOOD >", "classhypro_1_1_orthogonal_polyhedron.html", null ],
    [ "hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >", "classhypro_1_1_orthogonal_polyhedron_t.html", null ],
    [ "hypro::OrthoplexDefault", "namespacehypro.html#structhypro_1_1_orthoplex_default", null ],
    [ "pair", null, [
      [ "hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry", "classhypro_1_1_difference_bounds_t_1_1_d_b_m_entry.html", null ]
    ] ],
    [ "hypro::Parameters< Rargs >", "structhypro_1_1_parameters.html", null ],
    [ "hypro::Path< Number, tNumber >", "classhypro_1_1_path.html", null ],
    [ "hypro::Path< Number >", "classhypro_1_1_path.html", null ],
    [ "hypro::Permutator", "classhypro_1_1_permutator.html", null ],
    [ "hypro::PlotData< State >", "structhypro_1_1_plot_data.html", null ],
    [ "hypro::PlottingSettings", "namespacehypro.html#structhypro_1_1_plotting_settings", null ],
    [ "hypro::Point< Number >", "classhypro_1_1_point.html", null ],
    [ "hypro::Point< int >", "classhypro_1_1_point.html", null ],
    [ "hypro::Point< std::size_t >", "classhypro_1_1_point.html", null ],
    [ "hypro::pointIt< Number >", "structhypro_1_1point_it.html", null ],
    [ "hypro::PolynomialODE< Number >", "classhypro_1_1_polynomial_o_d_e.html", null ],
    [ "hypro::PolytopeSetting", "structhypro_1_1_polytope_setting.html", null ],
    [ "hypro::PolytopeSupportFunction< Number, Setting >", "classhypro_1_1_polytope_support_function.html", null ],
    [ "hypro::PreprocessingInformation", "namespacehypro.html#structhypro_1_1_preprocessing_information", null ],
    [ "hypro::PrincipalComponentAnalysis< Number >", "classhypro_1_1_principal_component_analysis.html", null ],
    [ "hypro::projectionContent< Number, Setting >", "structhypro_1_1projection_content.html", null ],
    [ "hypro::QuickhullAlgorithm< Number, Euclidian, typename >", "namespacehypro.html#classhypro_1_1_quickhull_algorithm", null ],
    [ "hypro::QuickhullAlgorithm< Number, Euclidian, EnableIfExact< Number > >", "classhypro_1_1_quickhull_algorithm_3_01_number_00_01_euclidian_00_01_enable_if_exact_3_01_number_01_4_01_4.html", null ],
    [ "hypro::Range< Number >", "classhypro_1_1_range.html", null ],
    [ "hypro::ReachabilitySettings", "structhypro_1_1_reachability_settings.html", null ],
    [ "hypro::ReachTree< State >", "classhypro_1_1_reach_tree.html", null ],
    [ "hypro::RectangularAnalyzer< State >", "classhypro_1_1_rectangular_analyzer.html", null ],
    [ "hypro::rectangularBadStateHandler< State >", "namespacehypro.html#classhypro_1_1rectangular_bad_state_handler", null ],
    [ "hypro::rectangularFlow< Number >", "classhypro_1_1rectangular_flow.html", null ],
    [ "hypro::rectangularGuardHandler< State >", "classhypro_1_1rectangular_guard_handler.html", null ],
    [ "hypro::rectangularInvariantHandler< State >", "namespacehypro.html#classhypro_1_1rectangular_invariant_handler", null ],
    [ "hypro::rectangularJumpHandler< State >", "classhypro_1_1rectangular_jump_handler.html", null ],
    [ "hypro::rectangularTimeEvolutionHandler< State >", "namespacehypro.html#classhypro_1_1rectangular_time_evolution_handler", null ],
    [ "hypro::RectangularWorker< State >", "classhypro_1_1_rectangular_worker.html", null ],
    [ "hypro::RefinementAnalyzer< Representation >", "classhypro_1_1_refinement_analyzer.html", null ],
    [ "hypro::RefinementSetting< State >", "structhypro_1_1_refinement_setting.html", null ],
    [ "hypro::RefinementSetting< Representation >", "structhypro_1_1_refinement_setting.html", null ],
    [ "hypro::RefinementSuccess< Representation >", "namespacehypro.html#structhypro_1_1_refinement_success", null ],
    [ "hypro::rep_number_i< Representation >", "namespacehypro.html#structhypro_1_1rep__number__i", null ],
    [ "hypro::rep_number_i< Rep< Number, Ts... > >", "namespacehypro.html#structhypro_1_1rep__number__i_3_01_rep_3_01_number_00_01_ts_8_8_8_01_4_01_4", null ],
    [ "hypro::RepresentationCombinations< Representation, Settings >", "namespacehypro.html#structhypro_1_1_representation_combinations", null ],
    [ "hypro::Reset< Number >", "classhypro_1_1_reset.html", null ],
    [ "hypro::Reset< N >", "classhypro_1_1_reset.html", null ],
    [ "hypro::Reset< rep_number< Representation > >", "classhypro_1_1_reset.html", null ],
    [ "hypro::detail::ResetVisitor< ReturnType, Function >", "structhypro_1_1detail_1_1_reset_visitor.html", null ],
    [ "hypro::RGNData", "structhypro_1_1_r_g_n_data.html", [
      [ "hypro::IntersectHalfspaceData< Number >", "structhypro_1_1_intersect_halfspace_data.html", null ],
      [ "hypro::LeafData", "structhypro_1_1_leaf_data.html", null ],
      [ "hypro::ProjectData", "structhypro_1_1_project_data.html", null ],
      [ "hypro::ScaleData< Number >", "structhypro_1_1_scale_data.html", null ],
      [ "hypro::TrafoData< Number, Setting >", "structhypro_1_1_trafo_data.html", null ]
    ] ],
    [ "hypro::Ridge< Number >", "classhypro_1_1_ridge.html", null ],
    [ "hypro::RootGrowNode< Number, Converter, Setting >", "classhypro_1_1_root_grow_node.html", [
      [ "hypro::IntersectHalfspaceOp< Number, Converter, Setting >", "classhypro_1_1_intersect_halfspace_op.html", null ],
      [ "hypro::IntersectOp< Number, Converter, Setting >", "classhypro_1_1_intersect_op.html", null ],
      [ "hypro::Leaf< Number, Converter, Setting, Representation >", "classhypro_1_1_leaf.html", null ],
      [ "hypro::ProjectOp< Number, Converter, Setting >", "classhypro_1_1_project_op.html", null ],
      [ "hypro::ScaleOp< Number, Converter, Setting >", "classhypro_1_1_scale_op.html", null ],
      [ "hypro::SumOp< Number, Converter, Setting >", "classhypro_1_1_sum_op.html", null ],
      [ "hypro::TrafoOp< Number, Converter, Setting >", "classhypro_1_1_trafo_op.html", null ],
      [ "hypro::UnionOp< Number, Converter, Setting >", "classhypro_1_1_union_op.html", null ]
    ] ],
    [ "hypro::RTN_Rep_i< RTN >", "namespacehypro.html#structhypro_1_1_r_t_n___rep__i", null ],
    [ "hypro::RTN_Rep_i< ReachTreeNode< Representation > >", "namespacehypro.html#structhypro_1_1_r_t_n___rep__i_3_01_reach_tree_node_3_01_representation_01_4_01_4", null ],
    [ "hypro::scaleContent< Number, Setting >", "structhypro_1_1scale_content.html", null ],
    [ "hypro::ScopedLock< Lockable >", "classhypro_1_1_scoped_lock.html", null ],
    [ "hypro::detail::seq< Is >", "structhypro_1_1detail_1_1seq.html", null ],
    [ "hypro::detail::seq< Is... >", "structhypro_1_1detail_1_1seq.html", [
      [ "hypro::detail::gen_seq< 0, Is... >", "structhypro_1_1detail_1_1gen__seq_3_010_00_01_is_8_8_8_01_4.html", null ]
    ] ],
    [ "hypro::setCreationVisitor< State >", "structhypro_1_1set_creation_visitor.html", null ],
    [ "hypro::Settings", "classhypro_1_1_settings.html", null ],
    [ "Singleton", null, [
      [ "hypro::ContextFactory< State >", "classhypro_1_1_context_factory.html", null ],
      [ "hypro::DecisionEntity< Number >", "classhypro_1_1_decision_entity.html", null ],
      [ "hypro::EventTimingProvider< Number >", "classhypro_1_1_event_timing_provider.html", null ],
      [ "hypro::HandlerFactory< State >", "classhypro_1_1_handler_factory.html", null ],
      [ "hypro::NodeManager< State >", "classhypro_1_1_node_manager.html", null ],
      [ "hypro::Plotter< Number >", "classhypro_1_1_plotter.html", null ],
      [ "hypro::SettingsProvider< State >", "classhypro_1_1_settings_provider.html", null ],
      [ "hypro::statistics::Statistician", "classhypro_1_1statistics_1_1_statistician.html", null ],
      [ "hypro::VariablePool", "classhypro_1_1_variable_pool.html", null ]
    ] ],
    [ "hypro::STallValues< Number >", "namespacehypro.html#structhypro_1_1_s_tall_values", null ],
    [ "hypro::STflowpipeSegment< Number >", "namespacehypro.html#structhypro_1_1_s_tflowpipe_segment", null ],
    [ "hypro::STindependentFunct< Number >", "namespacehypro.html#structhypro_1_1_s_tindependent_funct", null ],
    [ "hypro::Strategy", "namespacehypro.html#structhypro_1_1_strategy", null ],
    [ "hypro::Strategy< State >", "namespacehypro.html#namespacehypro", null ],
    [ "hypro::stringToSetting_Impl< Enum, Enums >", "structhypro_1_1string_to_setting___impl.html", null ],
    [ "hypro::stringToSetting_Impl< Enum >", "structhypro_1_1string_to_setting___impl_3_01_enum_01_4.html", null ],
    [ "hypro::sumContent< Number, Setting >", "structhypro_1_1sum_content.html", null ],
    [ "hypro::SupportFunctionContent< Number, Setting >", "classhypro_1_1_support_function_content.html", [
      [ "hypro::NonLinearOmega0Supportfunction< Setting >", "classhypro_1_1_non_linear_omega0_supportfunction.html", null ]
    ] ],
    [ "hypro::SupportFunctionNewLeGuernic", "structhypro_1_1_support_function_new_le_guernic.html", null ],
    [ "hypro::SupportFunctionNewMorePrecision", "structhypro_1_1_support_function_new_more_precision.html", null ],
    [ "hypro::SupportFunctionNewNoReduction", "structhypro_1_1_support_function_new_no_reduction.html", null ],
    [ "SupportFunctionSetting", null, [
      [ "hypro::NoBoxDetection", "structhypro_1_1_no_box_detection.html", null ],
      [ "hypro::NoBoxReduction", "structhypro_1_1_no_box_reduction.html", null ],
      [ "hypro::NoReduction", "structhypro_1_1_no_reduction.html", null ],
      [ "hypro::NoTrafoReduction", "structhypro_1_1_no_trafo_reduction.html", null ],
      [ "hypro::PolytopeSupportFunctionSetting", "structhypro_1_1_polytope_support_function_setting.html", null ]
    ] ],
    [ "hypro::Task< State >", "structhypro_1_1_task.html", null ],
    [ "hypro::TaylorModel< Number >", "classhypro_1_1_taylor_model.html", null ],
    [ "hypro::TaylorModelVec< Number >", "classhypro_1_1_taylor_model_vec.html", null ],
    [ "hypro::TBacktrackingInfo< Number >", "structhypro_1_1_t_backtracking_info.html", null ],
    [ "hypro::TemplatePolyhedronDefault", "structhypro_1_1_template_polyhedron_default.html", [
      [ "hypro::OctagonShape", "structhypro_1_1_octagon_shape.html", null ]
    ] ],
    [ "hypro::TimedValuationSet< Representation >", "namespacehypro.html#structhypro_1_1_timed_valuation_set", null ],
    [ "hypro::TimeTransformationCache< Number >", "classhypro_1_1_time_transformation_cache.html", null ],
    [ "hypro::TimingAggregate< Number >", "classhypro_1_1_timing_aggregate.html", null ],
    [ "hypro::TimingAggregate< N >", "classhypro_1_1_timing_aggregate.html", null ],
    [ "hypro::TPathElement< Number, tNumber >", "structhypro_1_1_t_path_element.html", null ],
    [ "hypro::TPathElement< Number, Number >", "structhypro_1_1_t_path_element.html", null ],
    [ "hypro::trafoContent< Number, Setting >", "structhypro_1_1trafo_content.html", null ],
    [ "hypro::TrafoParameters< Number >", "classhypro_1_1_trafo_parameters.html", null ],
    [ "hypro::Transformation< Number >", "classhypro_1_1_transformation.html", null ],
    [ "hypro::Transition< Number >", "classhypro_1_1_transition.html", null ],
    [ "hypro::Transition< N >", "classhypro_1_1_transition.html", null ],
    [ "hypro::Transition< rep_number< Representation > >", "classhypro_1_1_transition.html", null ],
    [ "hypro::TreeIterator< NodeType >", "classhypro_1_1_tree_iterator.html", null ],
    [ "hypro::TreeNode< Data >", "classhypro_1_1_tree_node.html", null ],
    [ "hypro::TreeNode< ReachTreeNode< Representation > >", "classhypro_1_1_tree_node.html", [
      [ "hypro::ReachTreeNode< State >", "classhypro_1_1_reach_tree_node.html", null ],
      [ "hypro::ReachTreeNode< Representation >", "classhypro_1_1_reach_tree_node.html", null ],
      [ "hypro::ReachTreeNode< Representation >", "classhypro_1_1_reach_tree_node.html", null ]
    ] ],
    [ "hypro::TreeNode< ReachTreeNode< State > >", "classhypro_1_1_tree_node.html", [
      [ "hypro::ReachTreeNode< State >", "classhypro_1_1_reach_tree_node.html", null ]
    ] ],
    [ "hypro::TreeStatistic", "namespacehypro.html#structhypro_1_1_tree_statistic", null ],
    [ "true_type", null, [
      [ "hypro::is_flow< affineFlow< N > >", "structhypro_1_1is__flow_3_01affine_flow_3_01_n_01_4_01_4.html", null ],
      [ "hypro::is_flow< linearFlow< N > >", "structhypro_1_1is__flow_3_01linear_flow_3_01_n_01_4_01_4.html", null ],
      [ "hypro::is_flow< rectangularFlow< N > >", "structhypro_1_1is__flow_3_01rectangular_flow_3_01_n_01_4_01_4.html", null ],
      [ "hypro::is_shared_ptr< std::shared_ptr< T > >", "structhypro_1_1is__shared__ptr_3_01std_1_1shared__ptr_3_01_t_01_4_01_4.html", null ],
      [ "hypro::is_unique_ptr< std::unique_ptr< T, D > >", "structhypro_1_1is__unique__ptr_3_01std_1_1unique__ptr_3_01_t_00_01_d_01_4_01_4.html", null ]
    ] ],
    [ "hypro::TypedTimingVector", "classhypro_1_1_typed_timing_vector.html", null ],
    [ "hypro::TypeList< Types >", "namespacehypro.html#structhypro_1_1_type_list", null ],
    [ "hypro::TypeMapping< Representation >", "namespacehypro.html#structhypro_1_1_type_mapping", null ],
    [ "hypro::TypeMapping< R< N, C, Setting > >", "structhypro_1_1_type_mapping_3_01_r_3_01_n_00_01_c_00_01_setting_01_4_01_4.html", null ],
    [ "hypro::typeName< T >", "structhypro_1_1type_name.html", null ],
    [ "hypro::typeName< double >", "structhypro_1_1type_name_3_01double_01_4.html", null ],
    [ "hypro::typeName< mpq_class >", "structhypro_1_1type_name_3_01mpq__class_01_4.html", null ],
    [ "hypro::unionContent< Number, Setting >", "structhypro_1_1union_content.html", null ],
    [ "hypro::UtilSetting", "structhypro_1_1_util_setting.html", null ],
    [ "hypro::Vertex< Number >", "classhypro_1_1_vertex.html", null ],
    [ "hypro::Vertex< std::size_t >", "classhypro_1_1_vertex.html", null ],
    [ "hypro::VertexContainer< Number >", "classhypro_1_1_vertex_container.html", null ],
    [ "hypro::VertexEnumeration< Number >", "classhypro_1_1_vertex_enumeration.html", null ],
    [ "hypro::VPolytopeSetting", "structhypro_1_1_v_polytope_setting.html", null ],
    [ "hypro::WorkQueueDefaultSetting", "structhypro_1_1_work_queue_default_setting.html", null ],
    [ "hypro::WorkQueueManager< Workable >", "classhypro_1_1_work_queue_manager.html", null ],
    [ "hypro::WorkQueueT< Workable, Setting >", "classhypro_1_1_work_queue_t.html", null ],
    [ "hypro::WorkQueueT< TaskType >", "classhypro_1_1_work_queue_t.html", null ],
    [ "hypro::WorkQueueT< Workable >", "classhypro_1_1_work_queue_t.html", null ],
    [ "hypro::ZonotopeSetting", "structhypro_1_1_zonotope_setting.html", null ]
];