HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/make_mHyPro.m File Reference
make_mHyPro.m File Reference
Functions
id NOTE: (id cpp)
if isfile ('matlabInput')%Load the saved paths load('matlabInput')
id c ()
mex ('-v', ipaths{:},'CC=/usr/local/opt/llvm/bin/clang','GCC=/usr/local/bin/gcc','CXX=/usr/local/opt/llvm/bin/clang++','CXXFLAGS=\$CXXFLAGS-std=c++17', srcFile)
id lib:gnu: (id linux,[gnu] id $LD_LIBRARY_PATH)
id so: (id ipaths)
mex ('-v', ipaths{:}, srcFile)
else Windows mexErrMsgTxt ('Not implemented')
Variables
ipaths = {}
else Create the file if ismac Mac matlab = dir(fullfile('/Applications','**','mex.h'))
antlr4_runtime = dir(fullfile('/Users','**','/hypro/build/resources/antlr_build/include/antlr4-runtime/antlr4-common.h'))
misc = dir(fullfile('/Users','**','/hypro/build/resources/antlr_build/include/antlr4-runtime/misc/Interval.h'))
atn = dir(fullfile('/Users','**','/hypro/build/resources/antlr_build/include/antlr4-runtime/atn/ATN.h'))
dfa = dir(fullfile('/Users','**','/hypro/build/resources/antlr_build/include/antlr4-runtime/dfa/DFA.h'))
tree = dir(fullfile('/Usershome','**','/hypro/build/resources/antlr_build/include/antlr4-runtime/tree/Trees.h'))
support = dir(fullfile('/Users','**','/hypro/build/resources/antlr_build/include/antlr4-runtime/support/Any.h'))
hypro = dir(fullfile('/Users','**','/hypro/src/hypro/types.h'))
carl = dir(fullfile('/Users','**','/carl/src/CMakeLists.txt'))
local_include = '/usr/local/include'
carl_resources = dir(fullfile('/Users','**','/carl/build/resources/include/gmp.h'))
compiler = '/usr/local/opt/llvm/include/c++/v1/'
hypro_build = dir(fullfile('/Users','**','/hypro/build/CMakeCache.txt'))
hypro_lib = dir(fullfile('/Users','**','/hypro/build/libhypro.so'))
dgtest = '-DGTEST_USE_OWN_TR1_TUPLE=1 -std=c++17 -stdlib=libc++'
llvm = '-L/usr/local/opt/llvm/lib'
hypro_lib_flag = '-hypro'
ld_flag = strcat('LDFLAGS=$LDFLAGS -Wl -rpath', hy_build.folder)
mat_str = strcat('-I', matlab.folder)
antl_str = strcat('-I', antlr4_runtime.folder)
misc_str = strcat('-I', misc.folder)
atn_str = strcat('-I', ant.folder)
dfa_str = strcat('-I', dfa.folder)
tree_str = strcat('-I', tree.folder)
supp_str = strcat('-I', support.folder)
hypro_str = strcat('-I', hypro.folder)
carl_str = strcat('-I', carl.folder)
loc_str = strcat('-I', local_include.folder)
c_res_str = strcat('-I', carl_resources.folder)
comp_str = strcat('-L', compiler.folder)
hy_bu_str = strcat('-L', hypro_build.folder)
llvm_str = '-L/usr/local/opt/llvm/lib'
hy_lib_str = '-hypro'
ld_fl_str = strcat('LDFLAGS=$LDFLAGS -Wl -rpath', hy_build.folder)
cmp_flag = 'COMPFLAGS=$COMPFLAGS -std=c++17'
cxx_flag = 'CXXFLAGS=\$CXXFLAGS -std=c++17'
glpk_lib = dir(fullfile('/usr/local/lib','**','libglpk.so'))
glpk_lib_str = strcat('-L', glpk_lib.folder, 'libglpk.so')
setenv LD_RUN_PATH home marta hypro build
setenv LD_LIBRARY_PATH usr local MATLAB R2018b bin glnxa64
Function Documentation
id c () virtual
if isfile ('matlabInput')
id lib:gnu: (id linux, [gnu] id $LD_LIBRARY_PATH) virtual
mex ('-v' , ipaths{:} , ' CC = /usr/local/opt/llvm/bin/clang','GCC=/usr/local/bin/gcc','CXX=/usr/local/opt/llvm/bin/clang++','CXXFLAGS=\$CXXFLAGS-std=c++17', srcFile)
Referenced by so:().
mex ('-v' , ipaths{:} , srcFile)
else Windows mexErrMsgTxt ('Not implemented')
Referenced by MReach::computeForwardReachability(), convertMat2HandlePtr(), MReach::del_reach(), mexFunction(), MReach::new_reach(), MReach::process(), MReach::reachedBadStates(), MReach::setRepresentationType(), MReach::setSettings(), MReach::settings(), and so:().
id NOTE: (id cpp) virtual
id so: (id ipaths) virtual
Definition at line 193 of file make_mHyPro.m.
References end, ipaths, mex(), and mexErrMsgTxt().
Variable Documentation
save matlabInput antl_str = strcat('-I', antlr4_runtime.folder)
Definition at line 54 of file make_mHyPro.m.
antlr4_runtime = dir(fullfile('/Users','**','/hypro/build/resources/antlr_build/include/antlr4-runtime/antlr4-common.h'))
Definition at line 35 of file make_mHyPro.m.
atn = dir(fullfile('/Users','**','/hypro/build/resources/antlr_build/include/antlr4-runtime/atn/ATN.h'))
Definition at line 37 of file make_mHyPro.m.
save matlabInput atn_str = strcat('-I', ant.folder)
Definition at line 56 of file make_mHyPro.m.
setenv LD_RUN_PATH home marta hypro build
Definition at line 190 of file make_mHyPro.m.
save matlabInput c_res_str = strcat('-I', carl_resources.folder)
Definition at line 63 of file make_mHyPro.m.
carl = dir(fullfile('/Users','**','/carl/src/CMakeLists.txt'))
Definition at line 42 of file make_mHyPro.m.
carl_resources = dir(fullfile('/Users','**','/carl/build/resources/include/gmp.h'))
Definition at line 44 of file make_mHyPro.m.
save matlabInput carl_str = strcat('-I', carl.folder)
Definition at line 61 of file make_mHyPro.m.
save matlabInput cmp_flag = 'COMPFLAGS=$COMPFLAGS -std=c++17'
Definition at line 69 of file make_mHyPro.m.
save matlabInput comp_str = strcat('-L', compiler.folder)
Definition at line 64 of file make_mHyPro.m.
compiler = '/usr/local/opt/llvm/include/c++/v1/'
Definition at line 45 of file make_mHyPro.m.
save matlabInput cxx_flag = 'CXXFLAGS=\$CXXFLAGS -std=c++17'
Definition at line 70 of file make_mHyPro.m.
dfa = dir(fullfile('/Users','**','/hypro/build/resources/antlr_build/include/antlr4-runtime/dfa/DFA.h'))
Definition at line 38 of file make_mHyPro.m.
save matlabInput dfa_str = strcat('-I', dfa.folder)
Definition at line 57 of file make_mHyPro.m.
dgtest = '-DGTEST_USE_OWN_TR1_TUPLE=1 -std=c++17 -stdlib=libc++'
Definition at line 48 of file make_mHyPro.m.
setenv LD_LIBRARY_PATH usr local MATLAB R2018b bin glnxa64
Definition at line 192 of file make_mHyPro.m.
glpk_lib = dir(fullfile('/usr/local/lib','**','libglpk.so'))
Definition at line 140 of file make_mHyPro.m.
save matlabInput glpk_lib_str = strcat('-L', glpk_lib.folder, 'libglpk.so')
Definition at line 156 of file make_mHyPro.m.
save matlabInput hy_bu_str = strcat('-L', hypro_build.folder)
Definition at line 65 of file make_mHyPro.m.
save matlabInput hy_lib_str = '-hypro'
Definition at line 67 of file make_mHyPro.m.
hypro = dir(fullfile('/Users','**','/hypro/src/hypro/types.h'))
Definition at line 41 of file make_mHyPro.m.
hypro_build = dir(fullfile('/Users','**','/hypro/build/CMakeCache.txt'))
Definition at line 46 of file make_mHyPro.m.
hypro_lib = dir(fullfile('/Users','**','/hypro/build/libhypro.so'))
Definition at line 47 of file make_mHyPro.m.
hypro_lib_flag = '-hypro'
Definition at line 50 of file make_mHyPro.m.
save matlabInput hypro_str = strcat('-I', hypro.folder)
Definition at line 60 of file make_mHyPro.m.
ipaths = {}
Definition at line 23 of file make_mHyPro.m.
Referenced by so:().
save matlabInput ld_fl_str = strcat('LDFLAGS=$LDFLAGS -Wl -rpath', hy_build.folder)
Definition at line 68 of file make_mHyPro.m.
ld_flag = strcat('LDFLAGS=$LDFLAGS -Wl -rpath', hy_build.folder)
Definition at line 51 of file make_mHyPro.m.
llvm = '-L/usr/local/opt/llvm/lib'
Definition at line 49 of file make_mHyPro.m.
save matlabInput llvm_str = '-L/usr/local/opt/llvm/lib'
Definition at line 66 of file make_mHyPro.m.
save matlabInput loc_str = strcat('-I', local_include.folder)
Definition at line 62 of file make_mHyPro.m.
local_include = '/usr/local/include'
Definition at line 43 of file make_mHyPro.m.
Save the found paths save matlabInput mat_str = strcat('-I', matlab.folder)
Definition at line 53 of file make_mHyPro.m.
mex reachability MHyProReach MReach cpp elseif isunix Linux matlab = dir(fullfile('/Applications','**','mex.h'))
Definition at line 34 of file make_mHyPro.m.
Referenced by configure_file().
misc = dir(fullfile('/Users','**','/hypro/build/resources/antlr_build/include/antlr4-runtime/misc/Interval.h'))
Definition at line 36 of file make_mHyPro.m.
save matlabInput misc_str = strcat('-I', misc.folder)
Definition at line 55 of file make_mHyPro.m.
save matlabInput supp_str = strcat('-I', support.folder)
Definition at line 59 of file make_mHyPro.m.
support = dir(fullfile('/Users','**','/hypro/build/resources/antlr_build/include/antlr4-runtime/support/Any.h'))
Definition at line 40 of file make_mHyPro.m.
tree = dir(fullfile('/Usershome','**','/hypro/build/resources/antlr_build/include/antlr4-runtime/tree/Trees.h'))
Definition at line 39 of file make_mHyPro.m.
Referenced by hypro::parser::createFlowstarParseTree(), main(), hypro::parseFlowstarFile< double >(), and hypro::parseFlowstarFile< mpq_class >().
save matlabInput tree_str = strcat('-I', tree.folder)
Definition at line 58 of file make_mHyPro.m.