HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/tests/MHyProLocationTest.m File Reference
MHyProLocationTest.m File Reference
Functions
end function testLocation (testCase) loc1
tran1_2 addLabel (lab1)
tran1_3 addLabel (lab2)
tran1_4 addLabel (lab3)
tran2_4 addLabel (lab4)
loc1 setName ('loc1')
loc2 setName ('loc2')
loc3 setName ('loc3')
loc4 setName ('loc4')
assert (isequal(flow_mat, [1 0 1;2 1 3;1 1 1]))
assert (num_flow==1)
assert (isequal(inv_mat,[1 2;3 4]))
assert (isequal(inv_vec, [1;2]))
assert (isequal(labs{1}.getName(), labels{i}.getName()))
assert (out==0)
loc3 setExtInput ([1 2;3 4;5 6])
assert (isequal(input, [1 2;3 4;5 6]))
assert (isequal(name, 'loc3'))
loc1 setLinearFlow (linFlow, 1)
assert (linFlow==flow)
loc1==loc3 equal ()
assert (equal==0)
assert (nequal==1)
disp (['initialCond handle: ', num2str(initialCond.ObjectHandle)])
loc1 setInvariant (initialCond)
Variables
function tests
loc2 = MHyProLocation([1 0 1; 2 1 3; 1 1 1])
loc3 = MHyProLocation([1 0; 2 1])
loc4 = MHyProLocation([1 0; 0 1])
tran1_2 = MHyProTransition(loc1, loc2)
tran1_3 = MHyProTransition(loc1, loc3)
tran1_4 = MHyProTransition(loc1, loc4)
tran2_4 = MHyProTransition(loc2, loc4)
lab1 = MHyProLabel('tran1_2')
lab2 = MHyProLabel('tran1_3')
lab3 = MHyProLabel('tran1_4')
lab4 = MHyProLabel('tran2_4')
labels = {lab1, lab2, lab3, lab4}
transitions = {tran1_2, tran1_3, tran1_4}
cond = MHyProCondition([1 2; 3 4], [1; 2])
lin_flow = loc2.getLinearFlow()
flow_mat = lin_flow.getFlowMatrix()
num_flow = loc2.getNumberFlow()
inv = loc4.getInvariant()
inv_mat = inv.getMatrix()
inv_vec = inv.getVector()
tran = loc3.getTransitions()
for i
end out = loc3.hasExternalInput()
input = loc3.getExternalInput()
hash = loc3.hash()
name = loc3.getName()
linFlow = MHyProFlow(9, [1 0 0; 0 1 0; 0 0 1])
flow = loc1.getLinearFlow()
dim = loc3.dimension_at(1)
loc5 = MHyProLocation(loc3)
equal = (loc3 == loc5)
nequal = (loc1 ~= loc3)
boxVector = [10.2
boxMatrix = [1 0
initialCond = MHyProCondition(boxMatrix, boxVector)
blub
Function Documentation
tran1_2 addLabel (lab1)
tran1_3 addLabel (lab2)
tran1_4 addLabel (lab3)
tran2_4 addLabel (lab4)
assert (isequal(flow_mat,[1 0 1;2 1 3;1 1 1]))
assert (num_flow = =1)
assert (isequal(inv_mat, [1 2;3 4]))
assert (isequal(inv_vec,[1;2]))
assert (isequal(labs{1}.getName(), labels{i}.getName()))
assert (out = =0)
assert (isequal(input,[1 2;3 4;5 6]))
assert (isequal(name, 'loc3'))
assert (linFlow = =flow)
assert (equal = =0)
assert (nequal = =1)
disp ()
loc1 == loc3 equal () virtual
loc3 setExtInput ()
loc1 setInvariant (initialCond)
loc1 setLinearFlow (linFlow , 1)
loc1 setName ('loc1')
loc2 setName ('loc2')
loc3 setName ('loc3')
loc4 setName ('loc4')
end function testLocation (testCase)
Variable Documentation
blub
Initial value:
= loc1.getInvariant()
%assert(initialCond.Handle == invariant.Handle)
Definition at line 95 of file MHyProLocationTest.m.
boxMatrix = [1 0
Definition at line 91 of file MHyProLocationTest.m.
boxVector = [10.2
Definition at line 90 of file MHyProLocationTest.m.
cond = MHyProCondition([1 2; 3 4], [1; 2])
Definition at line 29 of file MHyProLocationTest.m.
dim = loc3.dimension_at(1)
Definition at line 77 of file MHyProLocationTest.m.
equal = (loc3 == loc5)
Definition at line 82 of file MHyProLocationTest.m.
flow = loc1.getLinearFlow()
Definition at line 74 of file MHyProLocationTest.m.
flow_mat = lin_flow.getFlowMatrix()
Definition at line 39 of file MHyProLocationTest.m.
hash = loc3.hash()
Definition at line 68 of file MHyProLocationTest.m.
for i
Initial value:
= 1:length(tran)
    labs = tran{i}.getLabels()
Definition at line 52 of file MHyProLocationTest.m.
initialCond = MHyProCondition(boxMatrix, boxVector)
Definition at line 92 of file MHyProLocationTest.m.
input = loc3.getExternalInput()
Definition at line 65 of file MHyProLocationTest.m.
inv = loc4.getInvariant()
Definition at line 45 of file MHyProLocationTest.m.
inv_mat = inv.getMatrix()
Definition at line 46 of file MHyProLocationTest.m.
inv_vec = inv.getVector()
Definition at line 47 of file MHyProLocationTest.m.
lab1 = MHyProLabel('tran1_2')
Definition at line 16 of file MHyProLocationTest.m.
lab2 = MHyProLabel('tran1_3')
Definition at line 17 of file MHyProLocationTest.m.
lab3 = MHyProLabel('tran1_4')
Definition at line 18 of file MHyProLocationTest.m.
lab4 = MHyProLabel('tran2_4')
Definition at line 19 of file MHyProLocationTest.m.
labels = {lab1, lab2, lab3, lab4}
Definition at line 21 of file MHyProLocationTest.m.
Referenced by main(), and hypro::Transition< N >::setLabels().
lin_flow = loc2.getLinearFlow()
Definition at line 38 of file MHyProLocationTest.m.
linFlow = MHyProFlow(9, [1 0 0; 0 1 0; 0 0 1])
Definition at line 72 of file MHyProLocationTest.m.
loc2 = MHyProLocation([1 0 1; 2 1 3; 1 1 1])
Definition at line 7 of file MHyProLocationTest.m.
loc3 = MHyProLocation([1 0; 2 1])
Definition at line 8 of file MHyProLocationTest.m.
loc4 = MHyProLocation([1 0; 0 1])
Definition at line 9 of file MHyProLocationTest.m.
loc5 = MHyProLocation(loc3)
Definition at line 81 of file MHyProLocationTest.m.
name = loc3.getName()
Definition at line 69 of file MHyProLocationTest.m.
Referenced by hypro::statistics::CounterRepository::add(), hypro::statistics::Statistician::get(), hypro::statistics::CounterRepository::get(), hypro::HybridAutomatonLexer::Initializer::Initializer(), hypro::HybridSystemLexer::Initializer::Initializer(), hypro::HybridAutomatonParser::Initializer::Initializer(), ClassHandle< T >::isValid(), ObjectHandle::mLocCondMap2Hypro(), hypro::Optimizer< Number >::Optimizer(), hypro::EventTimingProvider< Number >::setName(), hypro::Label::setName(), hypro::Location< N >::setName(), and hypro::HybridAutomaton< Number >::~HybridAutomaton().
nequal = (loc1 ~= loc3)
Definition at line 85 of file MHyProLocationTest.m.
num_flow = loc2.getNumberFlow()
Definition at line 42 of file MHyProLocationTest.m.
out = loc3.hasExternalInput()
Definition at line 57 of file MHyProLocationTest.m.
function tests
Initial value:
= MHyProLocationTest
    tests = functiontests(localfunctions)
Definition at line 1 of file MHyProLocationTest.m.
tran = loc3.getTransitions()
Definition at line 51 of file MHyProLocationTest.m.
tran1_2 = MHyProTransition(loc1, loc2)
Definition at line 11 of file MHyProLocationTest.m.
tran1_3 = MHyProTransition(loc1, loc3)
Definition at line 12 of file MHyProLocationTest.m.
tran1_4 = MHyProTransition(loc1, loc4)
Definition at line 13 of file MHyProLocationTest.m.
tran2_4 = MHyProTransition(loc2, loc4)
Definition at line 14 of file MHyProLocationTest.m.
transitions = {tran1_2, tran1_3, tran1_4}
Definition at line 28 of file MHyProLocationTest.m.
Referenced by hypro::ReachTreeNode< State >::addTimeStepToPath().