HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/tests/MHyProZonotopeTest.m File Reference
MHyProZonotopeTest.m File Reference
Functions
end function testZonotopes (testCase) disp('z1')
disp ('z2')
disp ('z3')
disp ('z4')
disp ('z5')
assert (ans==1)
assert (isnan(s)==1)
assert (s==4)
assert (isequal(z_center,[1;1;0]))
assert (isequal(z_gen, eye(3)))
assert (ord >=0.0769)
z2 setCenter ([1 0 0 2 0 0 2 1 0 0 1 1 2])
assert (isequal([1;0;0;2;0;0;2;1;0;0;1;1;2], c))
disp ('Get generators')
z2 setGenerators (eye(13))
assert (isequal(g, eye(13)))
disp ('Add generators')
z4 addGenerators ([1 2 3;3 4 5])
assert (isequal(bound,[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))
z6 plotObj ([1 3])
Variables
function tests
z1 = MHyProZonotope()
z2 = MHyProZonotope('dimension', 13)
z3 = MHyProZonotope([1 1 0], [1 0 0; 0 1 0; 0 0 1])
z4 = MHyProZonotope(z3, 0, 2)
z5 = MHyProZonotope(z2)
ans = z1.isempty()
s = z1.supremum()
z_center = z3.center()
z_gen = z3.generators()
ord = z2.order()
c = z2.center()
g = z2.generators()
bound = z5.computeZonotopeBoundary()
Plot z6 = MHyProZonotope([1;2;1], eye(3))
Function Documentation
z4 addGenerators ()
assert (ans = =1)
assert (isnan(s) = =1)
assert (s = =4)
assert (isequal(z_center, [1;1;0]))
assert (isequal(z_gen, eye(3)))
assert (ord >=0. 0769)
assert (isequal([1;0;0;2;0;0;2;1;0;0;1;1;2], c))
assert (isequal(g, eye(13)))
assert (isequal(bound, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))
disp ('z2')
disp ('z3')
disp ('z4')
disp ('z5')
disp ('Get generators')
disp ('Add generators')
z6 plotObj ()
z2 setCenter ()
z2 setGenerators (eye(13))
end function testZonotopes (testCase)
Variable Documentation
ans = z1.isempty()
Definition at line 19 of file MHyProZonotopeTest.m.
bound = z5.computeZonotopeBoundary()
Definition at line 58 of file MHyProZonotopeTest.m.
Referenced by hypro::addPreSolution(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation().
c = z2.center()
Definition at line 43 of file MHyProZonotopeTest.m.
g = z2.generators()
Definition at line 48 of file MHyProZonotopeTest.m.
ord = z2.order()
Definition at line 39 of file MHyProZonotopeTest.m.
s = z1.supremum()
Definition at line 25 of file MHyProZonotopeTest.m.
function tests
Initial value:
= MHyProZonotopeTest
    tests = functiontests(localfunctions)
Definition at line 1 of file MHyProZonotopeTest.m.
z1 = MHyProZonotope()
Definition at line 8 of file MHyProZonotopeTest.m.
Referenced by main().
z2 = MHyProZonotope('dimension', 13)
Definition at line 10 of file MHyProZonotopeTest.m.
Referenced by main().
z3 = MHyProZonotope([1 1 0], [1 0 0; 0 1 0; 0 0 1])
Definition at line 12 of file MHyProZonotopeTest.m.
Referenced by main().
z4 = MHyProZonotope(z3, 0, 2)
Definition at line 14 of file MHyProZonotopeTest.m.
Referenced by main().
z5 = MHyProZonotope(z2)
Definition at line 16 of file MHyProZonotopeTest.m.
Referenced by main().
Plot z6 = MHyProZonotope([1;2;1], eye(3))
Definition at line 62 of file MHyProZonotopeTest.m.
Referenced by main().
z_center = z3.center()
Definition at line 34 of file MHyProZonotopeTest.m.
z_gen = z3.generators()
Definition at line 35 of file MHyProZonotopeTest.m.