HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/tests/MHyProConditionTest.m File Reference
MHyProConditionTest.m File Reference
Functions
end function testCondition (testCase) cond1
assert (s==0)
assert (empty==0)
assert (isequal(mat, [1 2;3 4]))
assert (isequal(vec, [1;2]))
assert (aligned==1)
eye(3 setMatrix ()
assert (isequal(mat, eye(3)))
cond1 setVector ([1;2;3], 1)
assert (isequal(vec, [1;2;3]))
id constraints ()
Variables
function tests
cond2 = MHyProCondition([1 2; 3 4], [1; 2])
cond3 = MHyProCondition(cond2)
s = cond1.size()
empty = cond2.isempty()
mat = cond3.getMatrix()
vec = cond2.getVector()
cond = MHyProCondition([1 0; 0 1], [1; 2])
aligned = cond.isAxisAligned()
hash = cond3.hash()
Function Documentation
assert (s = =0)
assert (empty = =0)
assert (isequal(mat,[1 2;3 4]))
assert (isequal(vec,[1;2]))
assert (aligned = =1)
assert (isequal(mat, eye(3)))
assert (isequal(vec,[1;2;3]))
id constraints () virtual
Referenced by hypro::addPreSolution(), hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT(), hypro::computeHalfspaces(), hypro::Fan< Number >::containingCone(), hypro::SupportFunctionContent< Number, Setting >::create(), hypro::halfspacesToConstraints(), hypro::isBox(), main(), hypro::DifferenceBoundsT< Number, Converter, Setting >::reduceRepresentation(), and hypro::z3OptimizeLinear().
eye(3 setMatrix () virtual
cond1 setVector (1)
end function testCondition (testCase)
Variable Documentation
aligned = cond.isAxisAligned()
Definition at line 24 of file MHyProConditionTest.m.
mappingObjectHandles(i cond = MHyProCondition([1 0; 0 1], [1; 2])
Definition at line 23 of file MHyProConditionTest.m.
Referenced by ObjectHandle::convert2Matlab(), and ObjectHandle::mLocCondMap2Hypro().
cond2 = MHyProCondition([1 2; 3 4], [1; 2])
Definition at line 8 of file MHyProConditionTest.m.
cond3 = MHyProCondition(cond2)
Definition at line 9 of file MHyProConditionTest.m.
empty = cond2.isempty()
Definition at line 14 of file MHyProConditionTest.m.
Referenced by CLANG_WARNING_DISABLE(), hypro::SupportFunctionNewT< Number, Converter, Setting >::Empty(), hypro::DAGNode< EventTimingNode< Number > >::getAvgSubtreeBranching(), hypro::TreeNode< ReachTreeNode< State > >::getAvgSubtreeBranching(), hypro::TreeNode< ReachTreeNode< State > >::getSubtreeDepth(), hypro::DAGNode< EventTimingNode< Number > >::getSubtreeSize(), hypro::TreeNode< ReachTreeNode< State > >::getSubtreeSize(), hypro::SupportFunctionContent< Number, Setting >::getThis(), and hypro::HierarchicalIntervalVector< CONTAINMENT, tNumber >::setTypeOrder().
hash = cond3.hash()
Definition at line 41 of file MHyProConditionTest.m.
Referenced by hypro::Reset< N >::getIntervalResets(), hypro::lintrafoParameters< Number >::hash(), std::hash< hypro::affineFlow< Number > >::operator()(), std::hash< hypro::rectangularFlow< Number > >::operator()(), std::hash< hypro::linearFlow< Number > >::operator()(), std::hash< hypro::Location< Number > >::operator()(), and hypro::HybridAutomaton< Number >::~HybridAutomaton().
mat = cond3.getMatrix()
Definition at line 17 of file MHyProConditionTest.m.
s = cond1.size()
Definition at line 11 of file MHyProConditionTest.m.
function tests
Initial value:
= MHyProConditionTest
    tests = functiontests(localfunctions)
Definition at line 1 of file MHyProConditionTest.m.
vec = cond2.getVector()
Definition at line 20 of file MHyProConditionTest.m.