HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/tests/MHyProHAutomatonTest.m File Reference
MHyProHAutomatonTest.m File Reference
Functions
end function testHAutomaton (testCase) automaton
loc setInvariant (inv)
loc setFlow (flowMatrix)
guard setMatrix (guardMatrix)
First set the matrix then the vector guard setVector (guardVector)
reset setMatrix (linReset)
reset setVector (constReset)
Setup transition tran setAggregation (2)
tran setGuard (guard)
tran setSource (loc)
tran setTarget (loc)
tran setReset (reset)
loc addTransition (tran)
automaton addInitialState (loc, initialCond)
initialState setMatrix ([-1 0 0 0 0 0 0 0 0 0])
First set the matrix then the vector initialState setVector (-1.7)
initialStates (1).loc = initialState
initialStates (2).loc = initialState
Variables
function tests
loc = MHyProLocation()
tran = MHyProTransition()
reset = MHyProReset()
guard = MHyProCondition()
Set invariant inv_mat = [-1 0]
inv_vec = 0
inv = MHyProCondition(inv_mat, inv_vec)
Set flow flowMatrix = [0 1 0
Set guard guardVector = [0
guardMatrix = [1 0
Set reset constReset = [0
linReset = [1 0
Create initial set boxVector = [10.2
boxMatrix = [1 0
initialCond = MHyProCondition(boxMatrix, boxVector)
l = automaton.addLocation(loc)
cpy = MHyProHAutomaton(automaton)
Copy the automaton Get initial condition of orign initCondOrig
loc2 = MHyProLocation()
locs = {loc1, loc2}
initialState = MHyProCondition()
autom1 = MHyProHAutomaton(locs, initialStates)
Function Documentation
automaton addInitialState (loc , initialCond)
loc addTransition (tran)
initialStates (1) = initialState
Referenced by CLANG_WARNING_DISABLE(), hypro::HybridAutomaton< Number >::HybridAutomaton(), and main().
initialStates (2) = initialState
Setup transition tran setAggregation (2)
loc setFlow (flowMatrix)
tran setGuard (guard)
loc setInvariant (inv)
guard setMatrix (guardMatrix)
reset setMatrix (linReset)
initialState setMatrix ()
tran setReset (reset)
tran setSource (loc)
tran setTarget (loc)
First set the matrix then the vector guard setVector (guardVector)
reset setVector (constReset)
First set the matrix then the vector initialState setVector (-1. 7)
end function testHAutomaton (testCase)
Variable Documentation
autom1 = MHyProHAutomaton(locs, initialStates)
Definition at line 76 of file MHyProHAutomatonTest.m.
boxMatrix = [1 0
Definition at line 46 of file MHyProHAutomatonTest.m.
Create initial set boxVector = [10.2
Definition at line 45 of file MHyProHAutomatonTest.m.
Set reset constReset = [0
Definition at line 31 of file MHyProHAutomatonTest.m.
cpy = MHyProHAutomaton(automaton)
Definition at line 55 of file MHyProHAutomatonTest.m.
Set flow flowMatrix = [0 1 0
Definition at line 21 of file MHyProHAutomatonTest.m.
guard = MHyProCondition()
Definition at line 12 of file MHyProHAutomatonTest.m.
guardMatrix = [1 0
Definition at line 26 of file MHyProHAutomatonTest.m.
Set guard guardVector = [0
Definition at line 25 of file MHyProHAutomatonTest.m.
Copy the automaton Get initial condition of orign initCondOrig
Initial value:
= automaton.getInitialStates()
% Creat new automaton from locations and initial set mapping
% loc1 = MHyProLocation()
Definition at line 60 of file MHyProHAutomatonTest.m.
initialCond = MHyProCondition(boxMatrix, boxVector)
Definition at line 47 of file MHyProHAutomatonTest.m.
initialState = MHyProCondition()
Definition at line 68 of file MHyProHAutomatonTest.m.
Referenced by CLANG_WARNING_DISABLE(), createComponent1(), createComponent2(), createComponent3(), and createComponent4().
inv = MHyProCondition(inv_mat, inv_vec)
Definition at line 17 of file MHyProHAutomatonTest.m.
Set invariant inv_mat = [-1 0]
Definition at line 15 of file MHyProHAutomatonTest.m.
inv_vec = 0
Definition at line 16 of file MHyProHAutomatonTest.m.
l = automaton.addLocation(loc)
Definition at line 49 of file MHyProHAutomatonTest.m.
linReset = [1 0
Definition at line 32 of file MHyProHAutomatonTest.m.
loc = MHyProLocation()
Definition at line 9 of file MHyProHAutomatonTest.m.
loc2 = MHyProLocation()
Definition at line 65 of file MHyProHAutomatonTest.m.
locs = {loc1, loc2}
Definition at line 66 of file MHyProHAutomatonTest.m.
Referenced by hypro::HybridAutomaton< Number >::HybridAutomaton(), and ObjectHandle::mLocsVector2Hypro().
reset = MHyProReset()
Definition at line 11 of file MHyProHAutomatonTest.m.
function tests
Initial value:
= MHyProHAutomatonTest
    tests = functiontests(localfunctions)
Definition at line 1 of file MHyProHAutomatonTest.m.
tran = MHyProTransition()
Definition at line 10 of file MHyProHAutomatonTest.m.