HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/reachability/@MHyProReach/MHyProReach.m File Reference
MHyProReach.m File Reference
Functions
else error ('MHyProReach-setRepresentationType:Wrong type of at least one argument.')
end end function settings (obj) MHyPro(12
end function plot (obj, flowpipes, dims, labs, save, path, name, ext) num_flowpipes
disp (['Reach-plot:number of flowpipes: ', num2str(num_flowpipes)]) for pipe
warning ('')
if isempty (msgstr) obj.plotVertices(vertices
end hold on end hold on xlabel (labs(1))
ylabel (labs(2))
saveas (fig, fullfile(path, fname), ext)
end end end function plotVertices (obj, vertices, dims)%Compute projection first
Variables
classdef MHyProReach< handleproperties(SetAccess=public, GetAccess=public) ObjectHandleendmethods(Access=private)%Destructorfunction delete(obj) MHyPro(12, 1, obj.ObjectHandle);endendmethods(Access=public)%Constructorfunction obj=MHyProReach(varargin) if nargin==1 &&isa(varargin{1}, 'MHyProHAutomaton') obj.ObjectHandle=MHyPro(12, 2, varargin{1}.ObjectHandle);elseerror('MHyProReach-Constructor:Wrong type of at least one argument.');endendfunction out=computeForwardReachability(obj) flowpipes=MHyPro(12, 3, obj.ObjectHandle);out=cell(1, length(flowpipes));for i=1:length(flowpipes) states=flowpipes(i).flowpipe;fPipe=cell(1, length(states));for j=1:length(states) if isa(states{j}, 'uint64') fPipe{j}=MHyProState(states{j});elseerror('MHyProReach-computeForwardReach:Wrong type of input argument.');endendout{i}=fPipe;endendfunction setSettings(obj, settings) if isstruct(settings) fields=fieldnames(settings);for i=1:length(fields) currentField=fields{i};if~strcmp(currentField, 'timeBound')&&~strcmp(currentField, 'jumpDepth')...&&~strcmp(currentField, 'timeStep')&&~strcmp(currentField, 'plotDimensions')...&&~strcmp(currentField, 'pplDenomimator')&&~strcmp(currentField, 'uniformBloating')...&&~strcmp(currentField, 'fileName')&&~strcmp(currentField, 'clustering') error(['MHyProReach-setSettings:Unknown field name ', currentField]);endendMHyPro(12, 4, obj.ObjectHandle, settings);elseerror('MHyProReach-setSettings:Wrong type of at least one argument.');endendfunction setRepresentationType(obj, type)%0=box, 1=carl_polytope, 2=constraint_set%3=polytope_h, 4=polytope_v%5=ppl_polytope, 6=support_function, 7=taylor_model%8=zonotope, 9=difference_bounds, if type >
end end function obj ObjectHandle
end function out
fig = figure()
num_states = length(currentFlowpipe)
for state
vertices = currentState.vertices(0)
if dims
if save fname = strcat(name,'.',ext)
second = vertices(dims(2),:)
temp = [first
Function Documentation
disp ()
else error ('MHyProReach-setRepresentationType:Wrong type of at least one argument.')
if isempty (msgstr)
end function plot (obj , flowpipes , dims , labs , save , path , name , ext)
end end end function plotVertices (obj , vertices , dims)
saveas (fig , fullfile(path, fname) , ext)
end end function settings (obj)
Referenced by CLANG_WARNING_DISABLE(), main(), hypro::Plotter< Number >::Plotter(), hypro::toFlowstarFormat(), hypro::LTIContext< State >::~LTIContext(), and hypro::RectangularContext< State >::~RectangularContext().
warning ('')
end hold on end hold on xlabel (labs(1))
ylabel (labs(2))
Variable Documentation
classdef MHyProReach< handleproperties(SetAccess=public, GetAccess=public)ObjectHandleendmethods(Access=private)%Destructorfunction delete(obj)MHyPro(12, 1, obj.ObjectHandle);endendmethods(Access=public)%Constructorfunction obj=MHyProReach(varargin)if nargin==1 &&isa(varargin{1}, 'MHyProHAutomaton')obj.ObjectHandle=MHyPro(12, 2, varargin{1}.ObjectHandle);elseerror('MHyProReach-Constructor:Wrong type of at least one argument.');endendfunction out=computeForwardReachability(obj)flowpipes=MHyPro(12, 3, obj.ObjectHandle);out=cell(1, length(flowpipes));for i=1:length(flowpipes)states=flowpipes(i).flowpipe;fPipe=cell(1, length(states));for j=1:length(states)if isa(states{j}, 'uint64')fPipe{j}=MHyProState(states{j});elseerror('MHyProReach-computeForwardReach:Wrong type of input argument.');endendout{i}=fPipe;endendfunction setSettings(obj, settings)if isstruct(settings)fields=fieldnames(settings);for i=1:length(fields)currentField=fields{i};if~strcmp(currentField, 'timeBound')&&~strcmp(currentField, 'jumpDepth')...&&~strcmp(currentField, 'timeStep')&&~strcmp(currentField, 'plotDimensions')...&&~strcmp(currentField, 'pplDenomimator')&&~strcmp(currentField, 'uniformBloating')...&&~strcmp(currentField, 'fileName')&&~strcmp(currentField, 'clustering')error(['MHyProReach-setSettings:Unknown field name ', currentField]);endendMHyPro(12, 4, obj.ObjectHandle, settings);elseerror('MHyProReach-setSettings:Wrong type of at least one argument.');endendfunction setRepresentationType(obj, type)%0=box, 1=carl_polytope, 2=constraint_set%3=polytope_h, 4=polytope_v%5=ppl_polytope, 6=support_function, 7=taylor_model%8=zonotope, 9=difference_bounds,if type >
Initial value:
= 0 && type <= 9
                MHyPro(12, 5, obj.ObjectHandle, type)
Definition at line 67 of file MHyProReach.m.
if dims
Definition at line 98 of file MHyProReach.m.
Referenced by MReach::computeForwardReachability(), ObjectHandle::convert2Matlab(), ObjectHandle::flowpipes2Matlab(), hypro::ProjectOp< Number, Converter, Setting >::intersectDims(), hypro::UnionOp< Number, Converter, Setting >::intersectDims(), hypro::SumOp< Number, Converter, Setting >::intersectDims(), hypro::RootGrowNode< Number, Converter, Setting >::intersectDims(), hypro::IntersectOp< Number, Converter, Setting >::intersectDims(), ObjectHandle::mLocCondMap2Hypro(), ObjectHandle::mPointPair2Hypro(), MReach::setSettings(), hypro::toFlowstarFormat(), and vector2Matlab().
fig = figure()
Definition at line 84 of file MHyProReach.m.
if save fname = strcat(name,'.',ext)
Definition at line 106 of file MHyProReach.m.
num_states = length(currentFlowpipe)
Definition at line 89 of file MHyProReach.m.
end end function obj ObjectHandle
Definition at line 75 of file MHyProReach.m.
end function out
Initial value:
= reachedBadStates(obj)
            out = MHyPro(12, 7, obj.ObjectHandle)
Definition at line 78 of file MHyProReach.m.
second = vertices(dims(2),:)
Definition at line 115 of file MHyProReach.m.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals(), hypro::SupportFunctionContent< Number, Setting >::checkTreeValidity(), hypro::LinTrafoParameters< Number, Setting >::createNextReduct(), hypro::lintrafoParameters< Number >::createNextReduct(), determineLowerBound(), hypro::extractSolution(), hypro::isBox(), main(), hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::operator+(), hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::operator<(), hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::operator=(), and hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::operator==().
for state
Initial value:
= 1:num_states
                    currentState = currentFlowpipe{state}
Definition at line 92 of file MHyProReach.m.
Referenced by hypro::Flowpipe< Number >::addState(), hypro::ltiResetHandler< State >::ltiResetHandler(), main(), hypro::ReachTreeNode< State >::ReachTreeNode(), and hypro::GeometricObjectBase::setEmptyState().
temp = [first
Definition at line 116 of file MHyProReach.m.
res vertices = currentState.vertices(0)
Definition at line 95 of file MHyProReach.m.
Referenced by CLANG_WARNING_DISABLE(), hypro::effectiveDimension(), hypro::SupportFunctionNewT< Number, Converter, Setting >::Empty(), main(), and hypro::sample().