HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/tests/MHyProBoxTest.m File Reference
MHyProBoxTest.m File Reference
Functions
end function testBox (testCase)%Test Basic Functionality%This script contains tests for all functions for HyPro Boxes.inter
assert (isEmpty==1)
assert (isequal(interval, [2 5]))
assert (isequal(inter, intervals))
assert (isequal(intervals, [0 2;0 1;0 0]))
assert (isequal(intervals, zeros(7, 2)))
assert (isequal(ver, [0 1 0 1 0 1 0 1;0 0 1 1 0 0 1 1;0 0 0 0 1 1 1 1]))
assert (points_box==copied_box)
assert (isequal(matrix, [1 0;-1 0;0 1;0-1]))
assert (isequal(vector, [1;-1;1;-1]))
assert (isequal(intervals, [2 4]))
intervals_box insert ([11 12])
assert (isequal([1 2;3 4;5 6;11 12], intervals))
assert (box.dimension()==50)
assert (isequal([0 2;0 1], limits))
assert (isequal(h_mat, [1 0;-1 0;0 1;0-1]))
assert (isequal(h_vec, [1;-1;3;-2]))
assert (isequal(interval, [23 179]))
assert (isequal(interval,[23 179]))
assert (out==0)
assert (isequal(maximal, [2;2]))
assert (isequal(minimal, [1;1]))
assert (supremum==1)
assert (equal==1)
assert (unequal==0)
assert (dim==1)
'interval', [1 2;1 2] MHyProBox ()
assert (symm==0)
assert (containment=="NO") = box.satisfiesHalfspaces(mat, vec)
assert (isequal(hs_normal, [0;0;-1]))
assert (isequal(hs_offset,-1))
disp ('+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++') projbox
assert (isequal(inter, [3 5;2 4]))%Perform linear transformation of a box box
assert (isequal(inter, [6 10;8 16;1 2]))
assert (isequal(inter, [8 12;9 17;3 4]))
assert (isequal(inter, [5 9;4 8]))
assert (isequal(inter, [-3-3;-2-2]))
assert (isequal(inter, [2 3;2 3]))
assert (isequal(inter, [1 2;1 3]))
assert (isequal(inter, [1 2;1 2]))
assert (contains==1)
assert (isequal(inter, [1 7;-1 9]))
assert (isequal(inter, [0 1;-1 10]))
assert (isequal(inter, [3 15;3 21]))
assert (isequal(inter, [1 5;1 7;1 2;2 3]))
Plot box1 plotObj ([3 4])
Variables
function tests
points = [0 2
Construct an empty box empty_box = MHyProBox()
isEmpty = empty_box.isempty()
Construct a box from single interval box = MHyProBox('interval', [2 5])
interval = box.intervals()
Construct a box from a list of intervals intervals_box = MHyProBox('intervals',inter)
intervals = intervals_box.intervals()
Construct box from a pair of points points_box = MHyProBox('points',points)
ver = box.vertices()
copied_box = MHyProBox(points_box)
Construct box from matrix and vector mat_vec_box = MHyProBox([1 0; -1 0; 0 1; 0 -1],[1;-1;1;-1])
matrix = mat_vec_box.matrix()
vector = mat_vec_box.vector()
Construct box from single interval interval_box = MHyProBox('interval',[2 4])
limits = box.limits()
Check if a matrix is symmetric notsymmetric_box = MHyProBox('intervals', [1 2; 1 2])
out = notsymmetric_box.isSymmetric()
symmetric_box = MHyProBox('intervals', [-1 1; -1 1])
maximal = notsymmetric_box.max()
minimal = notsymmetric_box.min()
supremum = symmetric_box.supremum()
box_copy = MHyProBox(box)
equal = (box == box_copy)
Check if points_box equals box box1 = MHyProBox('intervals', [1 2; 3 4; 5 6])
box2 = MHyProBox('intervals', [1 2; 1 2])
unequal = (box ~= box_copy)
dim = box.dimension()
symm = box.isSymmetric()
symmbox = box.makeSymmetric()
hs_normal = [0
hs_offset = -1
mat = eye(2)
vec = [3
inter = projbox.intervals()
transBox = box.linearTransformation(mat)
mSum = box1 + box2
mDec = box1.minkowskiDecomposition(box2)
intersection = box1.intersect(box2)
nor = [1
off = 2
intersected = box1.intersectHalfspace(nor,off)
contains = box1.contains([2;2])
uni = box1.unite(box2)
box3 = MHyProBox('intervals', [0 1; 9 10])
boxes = {box1,box2,box3}
united = MHyProBox.uniteMultiple(boxes)
Function Documentation
assert (isEmpty = =1)
assert (isequal(interval,[2 5]))
assert (isequal(inter, intervals))
assert (isequal(intervals,[0 2;0 1;0 0]))
assert (isequal(intervals, zeros(7, 2)))
assert (isequal(ver,[0 1 0 1 0 1 0 1;0 0 1 1 0 0 1 1;0 0 0 0 1 1 1 1]))
assert (points_box = =copied_box)
assert (isequal(matrix,[1 0;-1 0;0 1;0-1]))
assert (isequal(vector,[1;-1;1;-1]))
assert (isequal(intervals,[2 4]))
assert (isequal([1 2;3 4;5 6;11 12], intervals))
assert (box. dimension() = =50)
assert (isequal([0 2;0 1], limits))
assert (isequal(h_mat,[1 0;-1 0;0 1;0-1]))
assert (isequal(h_vec,[1;-1;3;-2]))
assert (isequal(interval,[23 179]))
assert (isequal(interval, [23 179]))
assert (out = =0)
assert (isequal(maximal,[2;2]))
assert (isequal(minimal,[1;1]))
assert (supremum = =1)
assert (equal = =1)
assert (unequal = =0)
assert (dim = =1)
assert (symm = =0)
assert (containment = ="NO") = box.satisfiesHalfspaces(mat, vec)
assert (isequal(hs_normal,[0;0;-1]))
assert (isequal(hs_offset,-1))
assert (isequal(inter,[3 5;2 4]))
assert (isequal(inter,[6 10;8 16;1 2]))
assert (isequal(inter,[8 12;9 17;3 4]))
assert (isequal(inter,[5 9;4 8]))
assert (isequal(inter,[-3-3;-2-2]))
assert (isequal(inter,[2 3;2 3]))
assert (isequal(inter,[1 2;1 3]))
assert (isequal(inter,[1 2;1 2]))
assert (contains = =1)
assert (isequal(inter,[1 7;-1 9]))
assert (isequal(inter,[0 1;-1 10]))
assert (isequal(inter,[3 15;3 21]))
assert (isequal(inter,[1 5;1 7;1 2;2 3]))
disp ('+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++')
intervals_box insert ()
'interval',[1 2; 1 2] MHyProBox () virtual
Plot box1 plotObj ()
end function testBox (testCase)
Variable Documentation
Perform affine transformation of a box box = MHyProBox('interval', [2 5])
Definition at line 18 of file MHyProBoxTest.m.
Referenced by ObjectHandle::convert2Matlab(), hypro::convertSettings(), hypro::dispatch(), hypro::SupportFunctionContent< Number, Setting >::getThis(), main(), ObjectHandle::mRepresentationName2Hypro(), MReach::setRepresentationType(), testConversionBoxToDBM(), and hypro::BoxT< Number, hypro::Converter, Setting >::type().
Reduce number of representation box1 = MHyProBox('intervals', [1 2; 3 4; 5 6])
Definition at line 122 of file MHyProBoxTest.m.
Referenced by main().
box2 = MHyProBox('intervals', [1 2; 1 2])
Definition at line 123 of file MHyProBoxTest.m.
Referenced by main().
box3 = MHyProBox('intervals', [0 1; 9 10])
Definition at line 248 of file MHyProBoxTest.m.
box_copy = MHyProBox(box)
Definition at line 117 of file MHyProBoxTest.m.
boxes = {box1,box2,box3}
Definition at line 249 of file MHyProBoxTest.m.
Referenced by hypro::BoxT< Number, hypro::Converter, Setting >::type().
Check if contains vector contains = box1.contains([2;2])
Definition at line 229 of file MHyProBoxTest.m.
Referenced by main(), testContains(), and testContainsPoint().
copied_box = MHyProBox(points_box)
Definition at line 44 of file MHyProBoxTest.m.
dim = box.dimension()
Definition at line 141 of file MHyProBoxTest.m.
Empty box in given dimension empty_box = MHyProBox()
Definition at line 13 of file MHyProBoxTest.m.
equal = (box == box_copy)
Definition at line 118 of file MHyProBoxTest.m.
Referenced by hypro::contains(), and main().
hs_normal = [0
Definition at line 154 of file MHyProBoxTest.m.
hs_offset = -1
Definition at line 155 of file MHyProBoxTest.m.
inter = projbox.intervals()
Definition at line 172 of file MHyProBoxTest.m.
intersected = box1.intersectHalfspace(nor,off)
Definition at line 215 of file MHyProBoxTest.m.
intersection = box1.intersect(box2)
Definition at line 207 of file MHyProBoxTest.m.
Referenced by main(), testIntersectConstraint(), and testIntersectDBM().
interval = box.intervals()
Definition at line 19 of file MHyProBoxTest.m.
Referenced by ObjectHandle::mInterval2Hypro().
Construct box from single interval interval_box = MHyProBox('interval',[2 4])
Definition at line 55 of file MHyProBoxTest.m.
intervals = intervals_box.intervals()
Definition at line 24 of file MHyProBoxTest.m.
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT(), hypro::Reset< N >::getIntervalResets(), hypro::icpIntersectHalfspace(), main(), ObjectHandle::mIntervals2Hypro(), hypro::reduceIntervalsNumberRepresentation(), and hypro::Reset< N >::Reset().
Insert an interval to a box intervals_box = MHyProBox('intervals',inter)
Definition at line 23 of file MHyProBoxTest.m.
isEmpty = empty_box.isempty()
Definition at line 14 of file MHyProBoxTest.m.
Referenced by hypro::icpIntersectHalfspace(), hypro::genericIntervalAssignmentVisitor< T, Number >::operator()(), and testEmpty().
limits = box.limits()
Definition at line 72 of file MHyProBoxTest.m.
id mat = eye(2)
Definition at line 163 of file MHyProBoxTest.m.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::assignIntervals(), createTestDBM(), createTestDBM2(), createTestDBMExtra(), hypro::HPolytopeT< Number, Converter, Setting >::getOptimizer(), main(), ObjectHandle::mHalfspaces2Hypro(), ObjectHandle::mPointPair2Hypro(), hypro::Reset< N >::Reset(), testIntersectHalfspaces(), and testSatisfiesHalfspaces().
Construct box from matrix and vector mat_vec_box = MHyProBox([1 0; -1 0; 0 1; 0 -1],[1;-1;1;-1])
Definition at line 48 of file MHyProBoxTest.m.
matrix = mat_vec_box.matrix()
Definition at line 49 of file MHyProBoxTest.m.
maximal = notsymmetric_box.max()
Definition at line 102 of file MHyProBoxTest.m.
mDec = box1.minkowskiDecomposition(box2)
Definition at line 200 of file MHyProBoxTest.m.
minimal = notsymmetric_box.min()
Definition at line 107 of file MHyProBoxTest.m.
mSum = box1 + box2
Definition at line 193 of file MHyProBoxTest.m.
nor = [1
Definition at line 213 of file MHyProBoxTest.m.
Get minimal point of box notsymmetric_box = MHyProBox('intervals', [1 2; 1 2])
Definition at line 93 of file MHyProBoxTest.m.
off = 2
Definition at line 214 of file MHyProBoxTest.m.
out = notsymmetric_box.isSymmetric()
Definition at line 94 of file MHyProBoxTest.m.
points = [0 2
Definition at line 10 of file MHyProBoxTest.m.
Referenced by CLANG_WARNING_DISABLE(), ObjectHandle::convert2Matlab(), main(), ObjectHandle::mPoints2Hypro(), ObjectHandle::mPointsVector2Hypro(), hypro::numberOfPointsInHalfspace(), hypro::HPolytopeT< Number, Converter, Setting >::reduceNumberRepresentation(), hypro::Facet< Number >::setPoints(), hypro::ProjectOp< Number, Converter, Setting >::supremumPoint(), hypro::ScaleOp< Number, Converter, Setting >::supremumPoint(), hypro::UnionOp< Number, Converter, Setting >::supremumPoint(), hypro::SumOp< Number, Converter, Setting >::supremumPoint(), hypro::TrafoOp< Number, Converter, Setting >::supremumPoint(), hypro::IntersectOp< Number, Converter, Setting >::supremumPoint(), and hypro::IntersectHalfspaceOp< Number, Converter, Setting >::supremumPoint().
Copy a box points_box = MHyProBox('points',points)
Definition at line 28 of file MHyProBoxTest.m.
supremum = symmetric_box.supremum()
Definition at line 112 of file MHyProBoxTest.m.
Referenced by CLANG_WARNING_DISABLE(), and hypro::SupportFunctionNewT< Number, Converter, Setting >::Empty().
symm = box.isSymmetric()
Definition at line 146 of file MHyProBoxTest.m.
symmbox = box.makeSymmetric()
Definition at line 148 of file MHyProBoxTest.m.
Get supremum of box symmetric_box = MHyProBox('intervals', [-1 1; -1 1])
Definition at line 96 of file MHyProBoxTest.m.
function tests
Initial value:
= MHyProBoxTest
    tests = functiontests(localfunctions)
Definition at line 1 of file MHyProBoxTest.m.
transBox = box.linearTransformation(mat)
Definition at line 178 of file MHyProBoxTest.m.
unequal = (box ~= box_copy)
Definition at line 130 of file MHyProBoxTest.m.
uni = box1.unite(box2)
Definition at line 241 of file MHyProBoxTest.m.
united = MHyProBox.uniteMultiple(boxes)
Definition at line 250 of file MHyProBoxTest.m.
vec = [3
Definition at line 164 of file MHyProBoxTest.m.
Referenced by hypro::VPolytopeT< Number, Converter, S >::assignIntervals(), hypro::ZonotopeT< Number, Converter, Setting >::assignIntervals(), hypro::HPolytopeT< Number, Converter, Setting >::assignIntervals(), ObjectHandle::convert2Matlab(), createTestHPolytope(), main(), ObjectHandle::mHalfspaces2Hypro(), ObjectHandle::mPoint2Hypro(), ObjectHandle::mSizeVector2Hypro(), ObjectHandle::mStringVector2Hypro(), ObjectHandle::objArray2Hypro(), hypro::Reset< N >::Reset(), testIntersectHalfspaces(), and testSatisfiesHalfspaces().
vector = mat_vec_box.vector()
Definition at line 50 of file MHyProBoxTest.m.
ver = box.vertices()
Definition at line 39 of file MHyProBoxTest.m.