HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/tests/MHyProFlowTest.m File Reference
MHyProFlowTest.m File Reference
Functions
end function testFlow (testCase)%%Test Basic Functionality linFlow
assert (flow==0)
linFlow setFlowMatrix (flowMatrix)
assert (isequal(flowMatrix, mat))
Check dimension (num.columns-1) dim
assert (dim==2)
Add new row for flow linFlow addRow ([1 2 2])
assert (isequal(mat, [1 2 0 1;3 4 1 2;1 0 1 3;1 2 1]))
9,[1 2 0;3 4 1;1 0 1] MHyProFlow ()
assert (id==0)
assert (timed==0)
assert (dis==0)
assert (equal==0)
assert (nequal==0)
assert (tran==0)
affineFlowEmpt setTranslation ([1;2]) tran
assert (isequal(tran,[1;2]))
Variables
function tests
Check if it has flow flow = linFlow.hasNoFlow()
Add flow matrix to linFlow flowMatrix = [1 2 0
mat = linFlow.getFlowMatrix()
id = linFlow1.isIdentity()
Check if is timed timed = linFlow1.isTimed()
Check if is discrete dis = linFlow1.isDiscrete()
Check if are equal equal = (linFlow == linFlow1)
linFlow = MHyProFlow(9, linFlow1)
Check if are unequal nequal = (linFlow ~= linFlow1)
affineFlowEmpt = MHyProFlow(10)
affineFlow = MHyProFlow(10, [1 2; 3 4], [1; 1])
tran = affineFlowEmpt.hasTranslation()
Function Documentation
Add new row for flow linFlow addRow ()
assert (flow = =0)
assert (isequal(flowMatrix, mat))
assert (dim = =2)
assert (isequal(mat,[1 2 0 1;3 4 1 2;1 0 1 3;1 2 1]))
assert (id = =0)
assert (timed = =0)
assert (dis = =0)
assert (equal = =0)
assert (nequal = =0)
assert (tran = =0)
assert (isequal(tran, [1;2]))
Check dimension (num.columns- 1)
Referenced by CLANG_WARNING_DISABLE(), hypro::reachability::computeFirstSegment(), hypro::SupportFunctionContent< Number, Setting >::create(), hypro::NeighborhoodContainer::empty(), hypro::extractSolution(), hypro::Facet< Number >::Facet(), hypro::isBox(), main(), hypro::sample(), and hypro::ConstrainSet< Number >::toPoint().
9, [1 2 0; 3 4 1; 1 0 1] MHyProFlow () virtual
linFlow setFlowMatrix (flowMatrix)
affineFlowEmpt setTranslation ()
end function testFlow (testCase)
Variable Documentation
affineFlow = MHyProFlow(10, [1 2; 3 4], [1; 1])
Definition at line 55 of file MHyProFlowTest.m.
affineFlowEmpt = MHyProFlow(10)
Definition at line 54 of file MHyProFlowTest.m.
Check if is discrete dis = linFlow1.isDiscrete()
Definition at line 40 of file MHyProFlowTest.m.
Referenced by hypro::sample().
equal = (linFlow == linFlow1)
Definition at line 44 of file MHyProFlowTest.m.
Check if it has flow flow = linFlow.hasNoFlow()
Definition at line 12 of file MHyProFlowTest.m.
Add flow matrix to linFlow flowMatrix = [1 2 0
Definition at line 16 of file MHyProFlowTest.m.
id = linFlow1.isIdentity()
Definition at line 32 of file MHyProFlowTest.m.
linFlow = MHyProFlow(9, linFlow1)
Definition at line 46 of file MHyProFlowTest.m.
mat = linFlow.getFlowMatrix()
Definition at line 18 of file MHyProFlowTest.m.
Check if are unequal nequal = (linFlow ~= linFlow1)
Definition at line 51 of file MHyProFlowTest.m.
function tests
Initial value:
= MHyProFlowTest
    tests = functiontests(localfunctions)
Definition at line 1 of file MHyProFlowTest.m.
Check if is timed timed = linFlow1.isTimed()
Definition at line 36 of file MHyProFlowTest.m.
Referenced by hypro::isTimed().
tran = affineFlowEmpt.hasTranslation()
Definition at line 57 of file MHyProFlowTest.m.