HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/tests/MHyProResetTest.m File Reference
MHyProResetTest.m File Reference
Functions
end function testReset (testCase) reset_empty
assert (empty==1)
assert (size==0)
reset setVector ([1;2;2])
reset setMatrix ([1 2 0;2 3 3;1 0 0])
assert (isequal(mat, [1 2 0;2 3 3;1 0 0]))
reset1 setIntervals ([1 2;3 4;5 6], 1)
assert (isequal(inter, [1 2;3 4;5 6]))
reset1 setIntervals ([1 3;3 7;10 110], 2)
assert (s==2)
assert (isequal(inter, [1 3;3 7;10 110]))
assert (isequal(intervals{1}, [1 2;3 4;5 6]))
assert (isequal(intervals{2}, [1 3;3 7;10 110]))
Variables
function tests
empty = reset_empty.isempty()
size = reset_empty.size()
reset = MHyProReset()
vec
mat = reset.getMatrix(1)
reset1 = MHyProReset()
inter = reset1.getIntervals(1)
constr = reset1.getAffineReset(1)
s = reset1.size()
intervals = reset1.getIntervalResets()
hash = reset1.hash()
Function Documentation
assert (empty = =1)
assert (size = =0)
assert (isequal(mat,[1 2 0;2 3 3;1 0 0]))
assert (isequal(inter,[1 2;3 4;5 6]))
assert (s = =2)
assert (isequal(inter,[1 3;3 7;10 110]))
assert (isequal(intervals{1},[1 2;3 4;5 6]))
assert (isequal(intervals{2},[1 3;3 7;10 110]))
reset1 setIntervals (1)
Referenced by hypro::Reset< N >::getIntervalResets().
reset1 setIntervals (2)
reset setMatrix ()
reset setVector ()
end function testReset (testCase)
Variable Documentation
constr = reset1.getAffineReset(1)
Definition at line 32 of file MHyProResetTest.m.
empty = reset_empty.isempty()
Definition at line 9 of file MHyProResetTest.m.
hash = reset1.hash()
Definition at line 49 of file MHyProResetTest.m.
inter = reset1.getIntervals(1)
Definition at line 29 of file MHyProResetTest.m.
intervals = reset1.getIntervalResets()
Definition at line 45 of file MHyProResetTest.m.
mat = reset.getMatrix(1)
Definition at line 24 of file MHyProResetTest.m.
reset = MHyProReset()
Definition at line 15 of file MHyProResetTest.m.
reset1 = MHyProReset()
Definition at line 27 of file MHyProResetTest.m.
s = reset1.size()
Definition at line 36 of file MHyProResetTest.m.
size = reset_empty.size()
Definition at line 12 of file MHyProResetTest.m.
Referenced by CLANG_WARNING_DISABLE(), hypro::DAGNode< EventTimingNode< Number > >::getSubtreeSize(), hypro::TreeNode< ReachTreeNode< State > >::getSubtreeSize(), main(), hypro::Path< Number, tNumber >::operator==(), hypro::EventTimingProvider< Number >::printSet(), hypro::SupportFunctionNewT< Number, Converter, Setting >::removeRedundancy(), MReach::settings(), hypro::HierarchicalIntervalVector< CONTAINMENT, tNumber >::setTypeOrder(), and hypro::TrafoOp< Number, Converter, Setting >::TrafoOp().
function tests
Initial value:
= MHyProResetTest
    tests = functiontests(localfunctions)
Definition at line 1 of file MHyProResetTest.m.
vec
Initial value:
= reset.getVector(1)
assert(isequal(vec, [1;2;2]))
Definition at line 20 of file MHyProResetTest.m.