HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/tests/MHyProConstraintSetTest.m File Reference
MHyProConstraintSetTest.m File Reference
Functions
end function testConstraintSet (testCase)%Test Basic Functionality set
assert (isequal(mat_vec_set.matrix(), [1 0 0 0;0 1 0 0;0 0 1 0]))
assert (isequal(mat_vec_set.vector(), [1;2;3]))
assert (isequal(mat, [1 0 0 0;0 1 0 0;0 0 1 0]))
assert (isequal(vec, [1;2;3]))
assert (aligned==1)
Add constraint mat_vec_set addConstraint ([2 3 0 1], 2)
assert (isequal(mat, [1 0 0 0;0 1 0 0;0 0 1 0;2 3 0 1]))
assert (isequal(vec, [1;2;3;2]))
assert (empty==0)
assert (equal==1)
assert (nequal==1)
assert (dim==3)
Remove redundancy set2 removeRedundancy ()
assert (isequal(containment,'NO'))
assert (emt==0)
assert (isequal(mat,[1 2 0 3;0 0 1 2;1 0 1 5;1 1 1-7]))
assert (isequal(mSum.matrix(),[1 2 3;2 2 2;1 0 0]))
assert (isequal(intersection.matrix(),[1 2 3;2 2 2;1 0 0]))
Intersect with a halfspace disp ('+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++')
id mat ()
[2;2;1] containsPoint ()
assert (contains==1)
eye(2 MHyProConstraintSet ()
[1 2] plot ()
Variables
function tests
mat_vec_set = MHyProConstraintSet([1 0 0 0; 0 1 0 0; 0 0 1 0],[1;2;3])
copied_set = MHyProConstraintSet(mat_vec_set)
Get matrix mat = mat_vec_set.matrix()
Get vector vec = mat_vec_set.vector()
Check if is axis aligned aligned = mat_vec_set.isAxisAligned()
Check if is empty empty = set.isempty()
Check for equality set1 = MHyProConstraintSet(eye(3), [1;2;3])
set2 = MHyProConstraintSet(set1)
equal = (set1 == set2)
Check for inequality nequal = (set ~= mat_vec_set)
Get dimension dim = set1.dimension()
hs_normal = [0
hs_offset = -5
emt = set.isempty()
projected = set1.project([1 3])
transSet = set1.linearTransformation(mat)
transFct = set1.affineTransformation(mat, vec)
mSum = set1 + set2
Intersect intersection = set1.intersect(set2)
nor = [1
off = 2
intersected = set1.intersectHalfspace(nor,off)
vertices = set1.vertices()
Check if contains another constraint set contains = set1.contains(set2)
Unite two sets uni = set2.unite(set1)
set3 = MHyProConstraintSet(eye(1), [2])
sets = {set2, set3}
united = set1.unite(sets)
Function Documentation
Add constraint mat_vec_set addConstraint (2)
assert (isequal(mat_vec_set.matrix(),[1 0 0 0;0 1 0 0;0 0 1 0]))
assert (isequal(mat_vec_set.vector(),[1;2;3]))
assert (isequal(mat,[1 0 0 0;0 1 0 0;0 0 1 0]))
assert (isequal(vec,[1;2;3]))
assert (aligned = =1)
assert (isequal(mat,[1 0 0 0;0 1 0 0;0 0 1 0;2 3 0 1]))
assert (isequal(vec,[1;2;3;2]))
assert (empty = =0)
assert (equal = =1)
assert (nequal = =1)
assert (dim = =3)
assert (isequal(containment,'NO'))
assert (emt = =0)
assert (isequal(mat, [1 2 0 3;0 0 1 2;1 0 1 5;1 1 1-7]))
assert (isequal(mSum.matrix(), [1 2 3;2 2 2;1 0 0]))
assert (isequal(intersection.matrix(), [1 2 3;2 2 2;1 0 0]))
assert (contains = =1)
[2;2;1] containsPoint () virtual
Intersect with a halfspace disp ('+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++')
id mat () virtual
eye(2 MHyProConstraintSet () virtual
[1 2] plot () virtual
Remove redundancy set2 removeRedundancy ()
Referenced by CLANG_WARNING_DISABLE().
end function testConstraintSet (testCase)
Variable Documentation
Check if is axis aligned aligned = mat_vec_set.isAxisAligned()
Definition at line 23 of file MHyProConstraintSetTest.m.
Check if contains another constraint set contains = set1.contains(set2)
Definition at line 126 of file MHyProConstraintSetTest.m.
copied_set = MHyProConstraintSet(mat_vec_set)
Definition at line 10 of file MHyProConstraintSetTest.m.
dim = set1.dimension()
Definition at line 52 of file MHyProConstraintSetTest.m.
Check if is empty empty = set.isempty()
Definition at line 34 of file MHyProConstraintSetTest.m.
emt = set.isempty()
Definition at line 63 of file MHyProConstraintSetTest.m.
equal = (set1 == set2)
Definition at line 40 of file MHyProConstraintSetTest.m.
hs_normal = [0
Definition at line 60 of file MHyProConstraintSetTest.m.
hs_offset = -5
Definition at line 61 of file MHyProConstraintSetTest.m.
intersected = set1.intersectHalfspace(nor,off)
Definition at line 111 of file MHyProConstraintSetTest.m.
Intersect intersection = set1.intersect(set2)
Definition at line 104 of file MHyProConstraintSetTest.m.
mat = mat_vec_set.matrix()
Definition at line 15 of file MHyProConstraintSetTest.m.
mat_vec_set = MHyProConstraintSet([1 0 0 0; 0 1 0 0; 0 0 1 0],[1;2;3])
Definition at line 9 of file MHyProConstraintSetTest.m.
mSum = set1 + set2
Definition at line 100 of file MHyProConstraintSetTest.m.
nequal = (set ~= mat_vec_set)
Definition at line 46 of file MHyProConstraintSetTest.m.
nor = [1
Definition at line 109 of file MHyProConstraintSetTest.m.
off = 2
Definition at line 110 of file MHyProConstraintSetTest.m.
projected = set1.project([1 3])
Definition at line 78 of file MHyProConstraintSetTest.m.
Referenced by main().
Add set1 = MHyProConstraintSet(eye(3), [1;2;3])
Definition at line 38 of file MHyProConstraintSetTest.m.
set2 = MHyProConstraintSet(set1)
Definition at line 39 of file MHyProConstraintSetTest.m.
set3 = MHyProConstraintSet(eye(1), [2])
Definition at line 137 of file MHyProConstraintSetTest.m.
sets = {set2, set3}
Definition at line 138 of file MHyProConstraintSetTest.m.
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::intersect(), and hypro::EventTimingProvider< Number >::printSet().
function tests
Initial value:
= MHyProConstraintTest
    tests = functiontests(localfunctions)
Definition at line 1 of file MHyProConstraintSetTest.m.
transFct = set1.affineTransformation(mat, vec)
Definition at line 93 of file MHyProConstraintSetTest.m.
transSet = set1.linearTransformation(mat)
Definition at line 83 of file MHyProConstraintSetTest.m.
Referenced by main().
Unite two sets uni = set2.unite(set1)
Definition at line 131 of file MHyProConstraintSetTest.m.
united = set1.unite(sets)
Definition at line 139 of file MHyProConstraintSetTest.m.
vec = mat_vec_set.vector()
Definition at line 19 of file MHyProConstraintSetTest.m.
vertices = set1.vertices()
Definition at line 123 of file MHyProConstraintSetTest.m.