HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/MHyPro.cpp File Reference
MHyPro.cpp File Reference
Functions
void mexFunction (int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
Function Documentation
void mexFunction (int nlhs, mxArray * plhs[], int nrhs, const mxArray * prhs[])
Definition at line 37 of file MHyPro.cpp.
References mexErrMsgTxt(), MHybridAutomaton::process(), MLocation::process(), MTransition::process(), MConstraintSet::process(), MCondition::process(), MState::process(), MAffineFlow::process(), MBox::process(), MLinearFlow::process(), MReset::process(), MZonotope::process(), MEllipsoid::process(), MLabel::process(), MSupportFunction::process(), MReach::process(), and type.