HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/tests/MHyProTransitionTest.m File Reference
MHyProTransitionTest.m File Reference
Functions
end function testTransition (testCase) tran
reset setVector ([1;2;2], 1)
assert (tloc==loc2)
assert (sloc==loc1)
assert (g==guard)
assert (isequal(r.getVector(1), reset.getVector(1)))
tran_full getTriggerTime ()
copied_tran isUrgent ()
tran_full isTimeTriggered ()
assert (out==1)
tran setTarget (loc2)
tran setSource (loc1)
tran setGuard (guard)
tran setReset (reset)
tran setUrgent (1)
assert (u==1)
tran setTriggerTime (3.1)
assert (time==3.1)
tran setLabels (labs)
assert (isequal(labels{1}.getName(),'this'))
assert (isequal(labels{2}.getName(),'is'))
assert (isequal(labels{3}.getName(),'funny'))
tran addLabel (lab4)
assert (isequal(labels{4}.getName(),'!'))
assert (equal==0)
assert (nequal==1)
Variables
function tests
copied_tran = MHyProTransition(tran)
loc1 = MHyProLocation([1 0; 2 1])
loc2 = MHyProLocation([1 0; 0 1])
tran_1_2 = MHyProTransition(loc1, loc2)
guard = MHyProCondition([1 2; 3 4], [1; 2])
reset = MHyProReset()
tran_full = MHyProTransition(loc1, loc2, guard, reset)
tloc = tran_full.getTarget()
sloc = tran_full.getSource()
g = tran_full.getGuard()
emptyCond = MHyProCondition()
r = tran_full.getReset()
out = tran.hasIdentityReset()
u = tran.isUrgent()
time = tran.getTriggerTime()
lab1 = MHyProLabel('this')
lab2 = MHyProLabel('is')
lab3 = MHyProLabel('funny')
labs = {lab1, lab2, lab3}
labels = tran.getLabels()
lab4 = MHyProLabel('!')
equal = (tran == tran_1_2)
nequal = (copied_tran ~= MHyProTransition())
Function Documentation
tran addLabel (lab4)
assert (tloc = =loc2)
assert (sloc = =loc1)
assert (g = =guard)
assert (isequal(r.getVector(1), reset.getVector(1)))
assert (out = =1)
assert (u = =1)
assert (time = =3.1)
assert (isequal(labels{1}.getName(),'this'))
assert (isequal(labels{2}.getName(),'is'))
assert (isequal(labels{3}.getName(),'funny'))
assert (isequal(labels{4}.getName(),'!'))
assert (equal = =0)
assert (nequal = =1)
tran_full getTriggerTime ()
tran_full isTimeTriggered ()
copied_tran isUrgent ()
tran setGuard (guard)
tran setLabels (labs)
tran setReset (reset)
tran setSource (loc1)
tran setTarget (loc2)
tran setTriggerTime (3. 1)
tran setUrgent (1)
reset setVector (1)
end function testTransition (testCase)
Variable Documentation
copied_tran = MHyProTransition(tran)
Definition at line 7 of file MHyProTransitionTest.m.
emptyCond = MHyProCondition()
Definition at line 29 of file MHyProTransitionTest.m.
equal = (tran == tran_1_2)
Definition at line 72 of file MHyProTransitionTest.m.
g = tran_full.getGuard()
Definition at line 25 of file MHyProTransitionTest.m.
guard = MHyProCondition([1 2; 3 4], [1; 2])
Definition at line 14 of file MHyProTransitionTest.m.
lab1 = MHyProLabel('this')
Definition at line 55 of file MHyProTransitionTest.m.
lab2 = MHyProLabel('is')
Definition at line 56 of file MHyProTransitionTest.m.
lab3 = MHyProLabel('funny')
Definition at line 57 of file MHyProTransitionTest.m.
lab4 = MHyProLabel('!')
Definition at line 66 of file MHyProTransitionTest.m.
labels = tran.getLabels()
Definition at line 61 of file MHyProTransitionTest.m.
labs = {lab1, lab2, lab3}
Definition at line 59 of file MHyProTransitionTest.m.
loc1 = MHyProLocation([1 0; 2 1])
Definition at line 9 of file MHyProTransitionTest.m.
Referenced by main().
loc2 = MHyProLocation([1 0; 0 1])
Definition at line 10 of file MHyProTransitionTest.m.
nequal = (copied_tran ~= MHyProTransition())
Definition at line 75 of file MHyProTransitionTest.m.
out = tran.hasIdentityReset()
Definition at line 41 of file MHyProTransitionTest.m.
r = tran_full.getReset()
Definition at line 32 of file MHyProTransitionTest.m.
Referenced by hypro::SumOp< Number, Converter, Setting >::aggregate(), hypro::IntersectOp< Number, Converter, Setting >::aggregate(), hypro::Facet< Number >::Facet(), hypro::Path< Number, tNumber >::getTransitionSequence(), hypro::HEXtoRGB(), hypro::HSVtoRGB(), hypro::isBox(), and hypro::selectCols().
reset = MHyProReset()
Definition at line 15 of file MHyProTransitionTest.m.
sloc = tran_full.getSource()
Definition at line 22 of file MHyProTransitionTest.m.
function tests
Initial value:
= MHyProTransitionTest
    tests = functiontests(localfunctions)
Definition at line 1 of file MHyProTransitionTest.m.
time = tran.getTriggerTime()
Definition at line 52 of file MHyProTransitionTest.m.
tloc = tran_full.getTarget()
Definition at line 19 of file MHyProTransitionTest.m.
tran_1_2 = MHyProTransition(loc1, loc2)
Definition at line 12 of file MHyProTransitionTest.m.
tran_full = MHyProTransition(loc1, loc2, guard, reset)
Definition at line 17 of file MHyProTransitionTest.m.
u = tran.isUrgent()
Definition at line 49 of file MHyProTransitionTest.m.