HyPro: run_hydra Namespace Reference
run_hydra Namespace Reference
Classes
class Model
class Results
Functions
def limit_mem (memLimit)
def read_file (fileName)
def get_cli_args ()
def main ()
Detailed Description
Run multiple benchmarks consecutively.
Required arguments (positional):
    tool: The path to the tool (hydra) executable
    settings: Path to a text file that contains the command line
        arguments for the benchmarks to run. For example, if hydra
        should be called with
        `./bin/hydra -m bball.model -r support_function --setting BoxLinearOptimizationOn`
        then the settings file should contain a line
        `-m bball.model -r support_function --setting BoxLinearOptimizationOn`
        Paths to the model (-m) should be given relative to the settings file.
        Empty lines and lines that start with '#' are ignored.
    output: Path to a file to write the output to. The output will
        be given in csv-format with the measured time, safety result and
        error messages if an error occured.
Optional arguments:
    -t <seconds> A time limit in seconds. If the execution of a benchmark
        model takes longer than the given time it will be terminated.
        This is indicated in the output.
    -m <megabyte> A memory limit in megabyte. If the execution of a benchmark
        model uses more space than allowed it will be terminated.
        This is NOT indicated in the output but will cause an error
        in the tool execution and the error message has to be interpreted.
    --verbose Verbose execution: The output of the tool will be printed.
    --benchmark Faster execution: The output is written to a file and analyzed
        after execution is complete. This lowers runtime but disables
        the timeout and verbose option as well as skipping functionality.
        (These arguments are ignored.)
Example calls:
    (1) `python3 run_hydra.py ../bin/hydra input/settings results.csv -t 1200 -m 16000 --verbose`
        Call for testing models with a timeout of 20min and memout of 16gb with verbose mode.
    (2) `python3 run_hydra.py ../bin/hydra input/settings results.csv --benchmark`
        Call for benchmarking and faster execution. Adding the timeout or verbose option
        will have no effect.
Function Documentation
def run_hydra.get_cli_args ()
Definition at line 221 of file run_hydra.py.
Referenced by main().
def run_hydra.limit_mem (memLimit)
Limit the memory-usage to memLimit (in MB).
Definition at line 50 of file run_hydra.py.
Referenced by run_hydra.Model._run_benchmark(), and run_hydra.Model._run_test().
def run_hydra.main ()
Definition at line 252 of file run_hydra.py.
References get_cli_args(), and read_file().
def run_hydra.read_file (fileName)
Return the lines of the file as a list. Lines that start with
'#' and empty lines are ignored. Multiple whitespaces are removed
from lines and lines are stripped.
Definition at line 57 of file run_hydra.py.
Referenced by main().