HyPro: hypro Namespace Reference
hypro Namespace Reference
General context interface to set up a reachability worker.
Namespaces
detail
ExactQuickhull
examples
hpolytope
parser
plotting
qe
reachability
statistics
ZUtility
Classes
class affineFlow
struct AffineTransformation
struct AnalysisParameters
struct apply_i
struct apply_i< Templ, TypeList< Args... > >
class BallSupportFunction
struct BoxAllOff
struct BoxIntervalArithmeticOff
struct BoxLinearOptimizationOff
class BoxSupportFunction
class BoxT
The class which represents a box.
struct Cacheable
class CarlPolytopeT
Class for representing polytopes as CArL-formulas.
struct ChildTimingInformation
class CIFExprVisitor
class CIFLocVisitor
struct clp_context
struct concat_i
struct concat_i< TypeList< Ts... >, TypeList< Us... > >
class Cone
class ConstrainSet
struct ConstraintSetSettings
Dummy struct for settings. *.
class ConstraintSetT
A class representing a plain constraint set. This class is intended to serve as a container.
class ContextBasedReachabilityWorker
class ContextFactory
class ContinuousSystem
class Converter
class ConvexHull
Class for convex hull computation.
class DAGNode
class DecisionEntity
struct Decomposition
class Dictionary
struct DifferenceBoundsSetting
class DifferenceBoundsT
Class wrapping the difference bounds content.
class discreteBadStateHandler
class discreteGuardHandler
class discreteInvariantHandler
class discreteResetHandler
class discreteTimeEvolutionHandler
struct Dispatcher_i
struct Dispatcher_i< Representation >
class Domain
struct Dummy
class EllipsoidSupportFunction
class EllipsoidT
Class for ellipsoids.
struct endPoint
class ErrorListener
struct EvaluationResult
Struct holding results obtained from the linear optimization engine.
class EventTimingContainer
class EventTimingNode
class EventTimingProvider
class Facet
Class for a facet of a polytope.
class Fan
Class for a polytopal fan.
class FinishWithDiscreteProcessingException
struct flattenRepresentations_i
struct flattenRepresentations_i< Number, Converter, TypeList< RepCombinationsList... > >
struct flowDimensionVisitor
struct flowHashVisitor
struct flowIsDiscreteVisitor
struct flowIsTimedVisitor
class Flowpipe
Container for a flowpipe, i.e. an ordered sequence of state sets (flowpipe segments).
struct flowTypeVisitor
class FourierMotzkinQE
Provides a simple implementation for Fourier Motzkin variable elimination for linear, existentially quantified constraints.
class GeneralizedStarT
The class which represents a GeneralizedStar.
class genericAffineTransformationVisitor
class genericAssignIntervalsVisitor
class genericCompareVisitor
class genericConversionVisitor
class genericConvertAndGetVisitor
class genericDimensionVisitor
class genericEmptyVisitor
class genericInternalConversionVisitor
class genericIntersectVisitor
class genericIntervalAssignmentVisitor
class genericMinkowskiSumVisitor
class genericOutstreamVisitor
class genericProjectionVisitor
class genericReductionVisitor
class genericRedundancyVisitor
class genericSatisfiesHalfspacesVisitor
class genericSetContainsVisitor
class genericSupremumVisitor
class genericToStringVisitor
class genericTypeVisitor
class genericUniteVisitor
class genericVerticesVisitor
class GeometricObjectBase
Purely virtual class defining a common interface for geometric objects. @{.
struct glpk_context
class Grid
Class for a grid which maps points to their assigned color.
struct guardHandlerSorter
class Halfspace
class HandlerFactory
class HardTerminateException
class HierarchicalIntervalVector
struct HPolytopeOptimizerCaching
class HPolytopeT
Class for a H-polytope.
class HybridAutomaton
Class for linear hybrid automata.
class HybridAutomatonBaseVisitor
class HybridAutomatonComp
Class for linear hybrid automata with components.
class HybridAutomatonLexer
class HybridAutomatonParser
class HybridAutomatonVisitor
class HybridCIFVisitor
class HybridSystemBaseVisitor
class HybridSystemLexer
class HybridSystemParser
class HybridSystemVisitor
class HyproBadStatesVisitor
class HyproFormulaVisitor
class HyproHAVisitor
class HyproInitialSetVisitor
class HyproLocationVisitor
class HyproSettingVisitor
class HyproTransitionVisitor
class IBadStateHandler
class IContext
class IFirstSegmentHandler
class IGuardHandler
class IHandler
class IInvariantHandler
class IJumpHandler
struct IntersectHalfspaceData
class IntersectHalfspaceOp
struct intersectionContent
class IntersectOp
struct IntervalAssignment
class IResetHandler
struct is_flow
struct is_flow< affineFlow< N > >
struct is_flow< linearFlow< N > >
struct is_flow< rectangularFlow< N > >
struct is_shared_ptr
struct is_shared_ptr< std::shared_ptr< T > >
struct is_unique_ptr
struct is_unique_ptr< std::unique_ptr< T, D > >
class ITimeEvolutionHandler
class IWorker
class Label
class Leaf
struct LeafData
class linearFlow
struct LinTrafoParameters
Struct holding linear and affine transformation parameters.
struct lintrafoParameters
Struct holding linear and affine transformation parameters.
class Location
Class for location.
class LockableBase
class LockableObjectWrapper
class LockedFileWriter
struct locPtrComp
class LRUCache
class LTIAnalyzer
class ltiBadStateHandler
class LTIContext
class ltiFirstSegmentHandler
class ltiGuardHandler
class ltiInvariantHandler
class ltiJumpHandler
class ltiResetHandler
class ltiTimeEvolutionHandler
class LTIWorker
class NeighborhoodContainer
A neighborhood container which maps points to their set of neighbor points.
struct NoBoxDetection
struct NoBoxReduction
class NodeManager
struct nodeUpdater
struct NoneAssignment
class NonLinearOmega0Supportfunction
struct NoReduction
struct NoTrafoReduction
struct OctagonShape
class Optimizer
Wrapper class for linear optimization.
class OrthogonalPolyhedron
Specialization of orthogonal polyhedra by the neighborhood representation.
class OrthogonalPolyhedronT
Class for orthogonal polyhedra.
struct OrthoplexDefault
struct Parameters
class Path
Class to define a path in some hybrid automaton.
class Permutator
Class for a permutator.
struct PlotData
Class that contains a raw segment for plotting. Note that a segment can be composed of several sub-segments, in case subspace decomposition is used.
class Plotter
Class implementing a plotter. The plotter is implemented using carl::Singleton.
class Point
Class for a point.
struct pointIt
Struct holding a point iterator allowing to iterate over a vector of points represented by their coordinates.
class PolynomialODE
struct PolytopeSetting
class PolytopeSupportFunction
struct PolytopeSupportFunctionSetting
class PrincipalComponentAnalysis
struct ProjectData
struct projectionContent
class ProjectOp
class QuickhullAlgorithm
class QuickhullAlgorithm< Number, Euclidian, EnableIfExact< Number > >
struct Range
struct ReachabilitySettings
Struct for reachability analysis algorithm settings.
class ReachTree
class ReachTreeNode
class rectangularBadStateHandler
class RectangularContext
class rectangularFirstSegmentHandler
class rectangularFlow
class rectangularGuardHandler
class rectangularInvariantHandler
class rectangularResetHandler
class rectangularTimeEvolutionHandler
struct RefinementSetting
struct RepresentationCombinations
class Reset
struct RGNData
class Ridge
class RootGrowNode
struct scaleContent
struct ScaleData
class ScaleOp
class ScopedLock
Class for scoped lock, taken from http://stackoverflow.com/questions/14276508/how-does-scope-locking-work.
struct setCreationVisitor
struct Settings
class SettingsProvider
class Spinlock
struct STallValues
STallValues as struct for all for reachability analysis relevant EVD values for constant flow of location input vertices have to be representable as points for evaluation.
class StatisticWrapper
Wrapper class which allows to create traces of operations on state set representations.
struct STflowpipeSegment
struct STindependentFunct
struct stringToSetting_Impl
struct stringToSetting_Impl< Enum >
struct sumContent
class SumOp
class SupportFunctionContent
Class for support function content.
struct SupportFunctionNewLeGuernic
struct SupportFunctionNewMorePrecision
struct SupportFunctionNewNoReduction
class SupportFunctionNewT
The class which represents a SupportFunctionNew.
class SupportFunctionT
Class wrapping the support function content.
struct Task
class TaylorModel
class TaylorModelVec
struct TBacktrackingInfo
Struct holding all currently required information for backtracking.
class TemplatePolyhedronContext
struct TemplatePolyhedronDefault
class timedBadStateHandler
class TimedContext
class timedElapseAfterTickTimeEvolutionHandler
class timedElapseFirstSegmentHandler
class timedElapseTimeEvolutionHandler
class timedFirstSegmentHandler
class timedGuardHandler
class timedInvariantHandler
class timedResetHandler
class timedTickTimeEvolutionHandler
class TimingAggregate
A class storing information about timing information. The idea is to keep track of timing nodes which are the result of a non-aggregated discete jump.
struct TPathElement
Struct holding a path element, which can be a representative for a time step or a representative for a discrete step.
class TPolyFirstSegmentHandler
class TPolyTimeEvolutionHandler
struct trafoContent
struct TrafoData
class TrafoOp
class TrafoParameters
class Transformation
Class for transformation of Hybrid Automata for Eigenvalue Decomposition(EVD) forward reachability analysis.
class Transition
Class for transition.
class TreeNode
Class for an n-ary tree.
struct TreeStatistic
struct TypeList
struct TypeMapping
struct TypeMapping< R< N, C, Setting > >
struct typeName
struct typeName< double >
struct typeName< mpq_class >
struct unionContent
class UnionOp
struct UtilSetting
class VariablePool
class Vertex
Forward declaration of class Vertex.
class VertexContainer
class VertexEnumeration
struct VPolytopeSetting
class VPolytopeT
The class implementing the vertex representation of a convex polytope.
struct WorkQueueDefaultSetting
class WorkQueueManager
class WorkQueueT
class z3Context
struct ZonotopeSetting
class ZonotopeT
Class for Zonotopes.
Typedefs
template<typename Number >
using Matrix = matrix_t< Number >
template<typename Number >
using Vector = vector_t< Number >
template<typename Number >
using DiagonalMatrix = Eigen::DiagonalMatrix< Number, Eigen::Dynamic >
using DiagonalMatrixdouble = Eigen::DiagonalMatrix< double, Eigen::Dynamic >
using BoolMatrix = matrix_t< bool >
using ExpFunctionTypeStdVector = std::vector< EXP_FUNCT_TYPE >
template<typename Number >
using Quickhull = QuickhullAlgorithm< Number, true, void >
template<typename Number >
using QuickIntersection = QuickhullAlgorithm< Number, false, void >
template<typename Number , bool Euclidian>
using ExactQuickhull = QuickhullAlgorithm< Number, Euclidian, EnableIfExact< Number >>
template<typename Number >
using PolyT = carl::MultivariatePolynomial< Number >
template<typename Number >
using ConstraintT = carl::Constraint< PolyT< Number > >
template<typename Number >
using ConstraintsT = std::vector< ConstraintT< Number > >
template<typename Number >
using FormulaT = carl::Formula< PolyT< Number > >
template<typename Number >
using FormulasT = std::vector< FormulaT< Number > >
using QEQuery = std::vector< std::pair< QuantifierType, std::vector< carl::Variable > > >
template<typename Number >
using flowVariant = std::variant< linearFlow< Number >, affineFlow< Number >, rectangularFlow< Number >>
template<typename State >
using initialData = std::tuple< const Location< typename State::NumberType > *, typename State::repVariant, typename State::NumberType, representation_name >
template<typename Number >
using TTransitionTimings = std::map< Transition< Number > *, std::vector< carl::Interval< tNumber >>>
using DynamicStrategy = std::vector< AnalysisParameters >
template<typename Workable >
using WorkQueue = WorkQueueT< Workable, WorkQueueDefaultSetting >
template<typename Number >
using vVec = typename std::vector< Vertex< Number >>
template<typename Number >
using vVecIt = typename std::vector< Vertex< Number >>::iterator
template<typename Number >
using vList = typename std::list< Vertex< Number >>
template<typename Number >
using vListIt = typename std::list< Vertex< Number >>::iterator
template<typename Number >
using vSet = typename std::set< Vertex< Number >>
template<typename Number >
using vSetIt = typename std::set< Vertex< Number >>::iterator
template<typename Number >
using Box = typename Converter< Number >::Box
template<typename Number >
using CarlPolytope = typename Converter< Number >::CarlPolytope
template<typename Number >
using ConstraintSet = typename Converter< Number >::ConstraintSet
template<typename Number >
using DifferenceBounds = typename Converter< Number >::DifferenceBounds
template<typename Number >
using Ellipsoid = typename Converter< Number >::Ellipsoid
template<typename Number >
using HPolytope = typename Converter< Number >::HPolytope
template<typename Number >
using OrthogonalPolyhedron = typename Converter< Number >::OrthogonalPolyhedron
template<typename Number >
using VPolytope = typename Converter< Number >::VPolytope
template<typename Number >
using Polytope = typename Converter< Number >::Polytope
template<typename Number >
using SupportFunction = typename Converter< Number >::SupportFunction
template<typename Number >
using SupportFunctionNew = typename Converter< Number >::SupportFunctionNew
template<typename Number >
using Zonotope = typename Converter< Number >::Zonotope
template<typename Number >
using TemplatePolyhedron = typename Converter< Number >::TemplatePolyhedron
template<typename Number >
using vectorSet = std::set< vector_t< Number >>
using tNumber = mpq_class
Number type used for timings and time intervals.
template<typename Number >
using vector_t = Eigen::Matrix< Number, Eigen::Dynamic, 1 >
template<typename Number >
using matrix_t = Eigen::Matrix< Number, Eigen::Dynamic, Eigen::Dynamic >
template<std::size_t I, typename... Ts>
using nth_element = typename detail::nth_element_impl< I, Ts... >::type
using DefaultRepresentations = TypeList< RepresentationCombinations< BoxT, BoxLinearOptimizationOn, BoxLinearOptimizationOff, BoxIntervalArithmeticOff, BoxAllOff >, RepresentationCombinations< HPolytopeT, HPolytopeSetting, HPolytopeOptimizerCaching >, RepresentationCombinations< SupportFunctionT, SupportFunctionSetting, NoBoxReduction, NoBoxDetection, NoTrafoReduction, NoReduction, PolytopeSupportFunctionSetting >, RepresentationCombinations< SupportFunctionNewT, SupportFunctionNewDefault, SupportFunctionNewMorePrecision, SupportFunctionNewNoReduction, SupportFunctionNewLeGuernic >, RepresentationCombinations< TemplatePolyhedronT, TemplatePolyhedronDefault > >
template<class Number , class Converter >
using DefaultDispatcher = Dispatcher< Number, Converter, DefaultRepresentations >
template<class Number , class Converter , class RepresentationCombinationsList >
using Dispatcher = apply< Dispatcher_i, flattenRepresentations< Number, Converter, RepresentationCombinationsList >>
template<class Number , class Converter , class CombinationsList >
using flattenRepresentations = typename flattenRepresentations_i< Number, Converter, CombinationsList >::type
template<class... Lists>
using concat = typename concat_i< Lists... >::type
template<template< class... > class Templ, class ArgList >
using apply = typename apply_i< Templ, ArgList >::type
template<bool B>
using enable_if = std::enable_if_t< B, int >
template<typename Number >
using EnableIfExact = std::enable_if_t< is_exact< Number >>
template<typename Number >
using EnableIfFloatingpoint = std::enable_if_t< std::is_floating_point_v< Number >>
Enumerations
enum EXP_FUNCT_TYPE {
CONVERGENT, DIVERGENT, LINEAR, CONSTANT,
UNDEFINED, INITIALIZED
}
enum QuantifierType { QuantifierType::EXISTS, QuantifierType::FORALL }
enum ResetType { ResetType::affine = 0, ResetType::interval, none }
enum Aggregation {
none = 0, none, boxAgg, clustering,
parallelotopeAgg
}
enum CONV_MODE { EXACT, OVER, UNDER, ALTERNATIVE }
enum for differentiating between exact conversion and over-/underapproximation (some functions support an alternative computation method).
enum ORTHO_TYPE { VERTEX, NEIGHBORHOOD, EXTREME_VERTEX }
Enum holding the type identification of the different representations of orthogonal polyhedra.
enum SF_TYPE {
SUM, INTERSECT, LINTRAFO, SCALE,
UNITE, POLY, INFTY_BALL, TWO_BALL,
ELLIPSOID, BOX, ZONOTOPE, PROJECTION,
NONE
}
enum SFNEW_TYPE {
NODE = 0, LEAF, TRAFO, SCALEOP,
PROJECTOP, SUMOP, INTERSECTOP, UNIONOP,
INTERSECTHSPACEOP
}
enum TRIBOOL { TRIBOOL::TRUE, TRIBOOL::FALSE, TRIBOOL::NSET }
Enum implementing a tribool.
enum REACHABILITY_RESULT { REACHABILITY_RESULT::SAFE, REACHABILITY_RESULT::UNKNOWN }
enum PLOTTYPE {
PLOTTYPE::pdf, PLOTTYPE::png, PLOTTYPE::eps, PLOTTYPE::gen,
PLOTTYPE::tex, PLOTTYPE::nset
}
enum SETSTATE { SETSTATE::UNKNOWN, SETSTATE::NONEMPTY, SETSTATE::EMPTY, SETSTATE::UNIVERSAL }
Enum to represent set states such as empty and universal.
enum SOLUTION { SOLUTION::FEAS = 0, SOLUTION::INFEAS, SOLUTION::INFTY, SOLUTION::UNKNOWN }
Enum of possible solution types for linear optimization.
enum CONTAINMENT {
CONTAINMENT::NO = -1, CONTAINMENT::BOT = 0, CONTAINMENT::PARTIAL = 1, CONTAINMENT::FULL = 2,
CONTAINMENT::YES = 3
}
Enum for set containment results. If known, we can make a statement about full or partial containment, otherwise fall back to YES/NO. Note: BOT is used for UNKNOWN.
enum SUBSPACETYPE { SUBSPACETYPE::LTI = 0, SUBSPACETYPE::TIMED = 1, SUBSPACETYPE::DISCRETE = 2, SUBSPACETYPE::RECTANGULAR = 3 }
classifies the type of subspace in case subspace decomposition is used.
enum LOCATIONTYPE { LOCATIONTYPE::LTILOC = 0, LOCATIONTYPE::TIMEDLOC = 1, LOCATIONTYPE::RECTANGULARLOC = 2 }
classifies the type of location, which reflects the dynamics in case we dynamically detect subspaces.
enum DynamicType {
DynamicType::linear = 0, DynamicType::affine, DynamicType::rectangular, DynamicType::timed,
DynamicType::discrete
}
classifies the type of dynamics of a flow for a location.
enum AGG_SETTING { AGG_SETTING::MODEL, AGG_SETTING::AGG, AGG_SETTING::NO_AGG }
enum OptimizerStrategy { SMTRAT, SOPLEX, SMTRAT, GLPK }
enum sampling_strategy_set { CENTER, VERTICES, RANDOM_SET_K }
enum sampling_strategy_interval { UNIFORM_K, BORDERS, RANDOM_INTV_K }
Functions
template<typename Number >
FormulaT< Number > eliminateQuantifiers (const FormulaT< Number > &qfree, const QEQuery &quantifiers)
template<typename State >
std::pair< CONTAINMENT, State > ltiIntersectBadStates (const State &stateSet, const HybridAutomaton< typename State::NumberType > &automaton)
template<typename State >
std::pair< CONTAINMENT, State > ltiIntersectBadStates (const State &stateSet, const Condition< typename State::Number > &localBadState, const std::vector< Condition< typename State::Number >> &globalBadStates)
template<typename State >
std::pair< CONTAINMENT, State > ltiIntersectBadStates (const State &stateSet, const Condition< typename State::NumberType > &localBadState, const std::vector< Condition< typename State::NumberType >> &globalBadStates)
template<typename State >
State bloatBox (const State &in, const hypro::Box< typename State::NumberType > &bloatBox, size_t index)
template<typename State >
std::pair< CONTAINMENT, State > ltiIntersectInvariant (const State &stateSet)
template<typename Number , typename State >
bool updateTiming (typename EventTimingContainer< Number >::Node_t current, carl::Interval< tNumber > entryTimestamp, Transition< Number > *transition, StrategyNode< State > currentStratNode, bool insert)
template<typename State >
bool isTreeExtension (typename ReachTreeNode< State >::Node_t node, Transition< typename State::NumberType > *transition)
template<typename State >
void collectTimespansForRefinementLevel (std::vector< carl::Interval< tNumber >> &timespans, typename ReachTreeNode< State >::NodeList_t &nodes, unsigned targetLevel)
template<typename State >
void preProcess (typename ReachTreeNode< State >::NodeList_t &toMatch, const std::vector< carl::Interval< tNumber >> &timespans)
template<typename State >
void insertAndCreateTask (typename ReachTreeNode< State >::NodeList_t &toInsert, const std::shared_ptr< Task< State >> &currentTask, WorkQueue< std::shared_ptr< Task< State >>> *localQueue, WorkQueue< std::shared_ptr< Task< State >>> *localCEXQueue, std::size_t targetLevel)
template<typename State , typename Number >
State ltiApplyTimeEvolution (const State &currentSegment, const matrix_t< Number > &transformation, const vector_t< Number > &translation, tNumber timeStepSize)
template<typename Number , typename Representation , carl::DisableIf< std::is_same< Representation, SupportFunction< Number >>> = carl::dummy>
void applyReduction (Representation &)
template<typename Representation >
void printFlowpipe (const std::vector< Representation > &_flowpipe)
template<typename Representation >
void printFlowpipeReduced (const std::vector< Representation > &_flowpipe)
template<typename Number >
Number hausdorffError (const Number &delta, const matrix_t< Number > &matrix, const Number &_supremum)
template<typename Number , typename State >
std::vector< Box< Number > > errorBoxes (const Number &delta, const linearFlow< Number > &flow, const State &initialSet, const matrix_t< Number > &trafoMatrix, const Box< Number > &externalInput)
template<typename Number >
std::ostream & operator<< (std::ostream &_ostr, const Facet< Number > &_f)
template<typename From , typename To >
Halfspace< To > convert (const Halfspace< From > &in)
Conversion operator for the number type.
template<typename Number >
std::ostream & operator<< (std::ostream &_lhs, const Halfspace< Number > &_rhs)
Outstream operator.
template<typename Number >
bool operator== (const Halfspace< Number > &lhs, const Halfspace< Number > &rhs)
Comparison operator.
template<typename Number >
bool operator< (const Halfspace< Number > &lhs, const Halfspace< Number > &rhs)
Operator less.
template<typename Number >
Halfspace< Number > operator- (const Halfspace< Number > &_in)
Operator unary minus.
template<typename Number >
Condition< Number > combine (const Condition< Number > &lhs, const Condition< Number > &rhs, const std::vector< std::string > haVar, const std::vector< std::string > lhsVar, const std::vector< std::string > rhsVar)
template<template< typename, typename > typename Rep, typename Number , typename Settings >
void decomposeConstraintSet (Rep< Number, Settings > &in, const Decomposition &decomposition, std::vector< Rep< Number, Settings >> &result)
template<typename T >
DynamicType getFlowType (const T &f)
template<typename T >
std::size_t getFlowDimension (const T &f)
template<typename T >
bool isTimed (const T &f)
template<typename T >
bool isDiscrete (const T &f)
template<typename N , typename D >
std::vector< ConstraintT< N > > createFlowConstraints (carl::Variable original, carl::Variable primed, carl::Variable t, const carl::Interval< D > &flow)
template<typename Number >
HybridAutomaton< Number > operator|| (const HybridAutomaton< Number > &lhs, const HybridAutomaton< Number > &rhs)
template<typename Number >
std::string toFlowstarFormat (const matrix_t< Number > &in, const std::map< Eigen::Index, std::string > &varNameMap, const std::string &prefix)
template<typename Number >
std::string toFlowstarFormat (const Condition< Number > &in, const std::map< Eigen::Index, std::string > &varNameMap, const std::string &prefix)
template<typename Number >
std::string toFlowstarFormat (const ConstraintSetT< Number > &in, const std::map< Eigen::Index, std::string > &varNameMap, const std::string &prefix)
template<typename Number >
std::string toFlowstarFormat (const flowVariant< Number > &f, const std::map< Eigen::Index, std::string > &varNameMap, const std::string &prefix)
template<typename Number >
std::string toFlowstarFormat (const Location< Number > *loc, const std::map< Eigen::Index, std::string > &varNameMap, const std::string &prefix)
std::string toFlowstarFormat (const ReachabilitySettings &settings, const std::map< Eigen::Index, std::string > &varNameMap, const std::string &prefix)
template<typename Number >
std::string toFlowstarFormat (const HybridAutomaton< Number > &in, const ReachabilitySettings &settings=ReachabilitySettings())
template<typename Number >
Reset< Number > combine (const Reset< Number > &lhs, const Reset< Number > &rhs, const std::vector< std::string > haVar, const std::vector< std::string > lhsVar, const std::vector< std::string > rhsVar)
template<typename Number , typename Representation , typename... Rargs>
State< Number, Representation, Rargs... > applyReset (const State< Number, Representation, Rargs... > &inState, const Reset< Number > &reset)
template<typename Number >
void swap (Point< Number > &_lhs, Point< Number > &_rhs)
Swap operator.
template<typename Number >
int effectiveDimension (const std::vector< Point< Number >> &vertices)
Determines the dimension of the affine space spanned by the given set of points.
template<typename Number >
int effectiveDimension (const std::set< Point< Number >> &vertices)
Determines the dimension of the affine space spanned by the given set of points.
template<typename From , typename To >
Point< To > convert (const Point< From > &in)
Conversion operator for the number type.
template<typename State >
std::ostream & operator<< (std::ostream &out, const ReachTreeNode< State > &reachTreeNode)
template<typename S >
bool operator< (const ReachTreeNode< S > &lhs, const ReachTreeNode< S > &rhs)
template<typename S >
bool operator== (const ReachTreeNode< S > &lhs, const ReachTreeNode< S > &rhs)
template<typename Number , typename State >
bool operator== (const std::shared_ptr< Task< State >> &lhs, const std::shared_ptr< Task< State >> &rhs)
std::vector< carl::Interval< tNumber > > getEnabledTimings (const HierarchicalIntervalVector< CONTAINMENT, tNumber > &in)
template<typename Number >
std::ostream & operator<< (std::ostream &_ostr, const Ridge< Number > &_f)
void openFile (const std::string &filename, ANTLRInputStream &input)
std::string replaceConstantsWithValues (TokenStreamRewriter &rewriter, std::map< std::string, std::string > constants)
template<>
std::pair< HybridAutomaton< mpq_class >, ReachabilitySettings > parseFlowstarFile< mpq_class > (const std::string &filename)
template<>
std::pair< HybridAutomaton< double >, ReachabilitySettings > parseFlowstarFile< double > (const std::string &filename)
template<typename Number >
std::pair< HybridAutomaton< Number >, ReachabilitySettings > parseFlowstarFile (const std::string &filename)
template<typename Number , typename Converter , class Setting >
BoxT< Number, Converter, Setting > operator* (Number factor, const BoxT< Number, Converter, Setting > &in)
Operator for scaling a box.
template<typename From , typename To , typename Converter , class Setting >
BoxT< To, Converter, Setting > convert (const BoxT< From, Converter, Setting > &in)
Conversion function for different number types.
BETTER_ENUM (boxSetting_name, int, BoxLinearOptimizationOn, BoxLinearOptimizationOff, BoxIntervalArithmeticOff, BoxAllOff) struct BoxLinearOptimizationOn
void reduceIntervalsNumberRepresentation (std::vector< carl::Interval< mpq_class >> &intervals, unsigned limit)
template<typename Number >
bool icpIntersectHalfspace (std::vector< carl::Interval< Number >> &intervals, const Halfspace< Number > &hsp)
Performs intersection of a vector of intervals with a halfspace.
template<typename Number >
void reduceIntervalsNumberRepresentation (std::vector< carl::Interval< Number >> &, unsigned)
template<typename From , typename To , typename S >
ConstraintSetT< To, S > convert (const ConstraintSetT< From, S > &in)
Conversion function for different number types.
template<typename Number , typename OutSettings , typename In >
void convert (const In &in, BoxT< Number, Converter< Number >, OutSettings > &out)
template<typename Number , typename OutSettings , typename In >
void convert (const In &in, CarlPolytopeT< Number, Converter< Number >, OutSettings > &out)
template<typename Number , typename OutSettings , typename In >
void convert (const In &in, ConstraintSetT< Number, OutSettings > &out)
template<typename Number , typename OutSettings , typename In >
void convert (const In &in, DifferenceBoundsT< Number, Converter< Number >, OutSettings > &out)
template<typename Number , typename OutSettings , typename In >
void convert (const In &in, HPolytopeT< Number, Converter< Number >, OutSettings > &out)
template<typename Number , typename OutSettings , typename In >
void convert (const In &in, SupportFunctionT< Number, Converter< Number >, OutSettings > &out)
template<typename Number , typename OutSettings , typename In >
void convert (const In &in, VPolytopeT< Number, Converter< Number >, OutSettings > &out)
template<typename Number , typename OutSettings , typename In >
void convert (const In &in, ZonotopeT< Number, Converter< Number >, OutSettings > &out)
template<typename Number , typename OutSettings , typename In >
void convert (const In &in, TemplatePolyhedronT< Number, Converter< Number >, OutSettings > &out)
template<typename Number , typename OutSettings , typename In >
void convert (const In &in, SupportFunctionNewT< Number, Converter< Number >, OutSettings > &out)
template<typename Number , typename OutSettings , typename In >
void convert (const In &in, PolytopeT< Number, Converter< Number >, OutSettings > &out)
template<typename Number , typename Converter , typename inSetting >
std::vector< Point< Number > > computeBoundaryPointsExpensive (const SupportFunctionT< Number, Converter, inSetting > &sf, const matrix_t< Number > &directions)
template<typename Number , typename Converter , typename inSetting >
Point< Number > computeBoundaryPointsExpensiveRecursive (const SupportFunctionT< Number, Converter, inSetting > &sf, const matrix_t< Number > &directions, std::size_t curDim)
template<typename Number , typename Converter , typename inSetting >
std::vector< Point< Number > > computeBoundaryPointsExpensive (const SupportFunctionNewT< Number, Converter, inSetting > &sf, const matrix_t< Number > &directions)
template<typename Number , typename Converter , typename inSetting >
Point< Number > computeBoundaryPointsExpensiveRecursive (const SupportFunctionNewT< Number, Converter, inSetting > &sf, const matrix_t< Number > &directions, std::size_t curDim)
template<typename Number >
vector_t< Number > computeArithmeticMeanPoint (const std::vector< Point< Number >> &pointVec)
template<typename Number >
std::tuple< bool, std::vector< carl::Interval< Number > > > isBox (const matrix_t< Number > &constraints, const vector_t< Number > &constants)
Determines if a constraint set represented by a matrix and a vector in fact defines a box.
template<typename Number , typename Converter , class Setting >
bool operator== (const PolytopeT< Number, Converter, Setting > &rhs, const PolytopeT< Number, Converter, Setting > &lhs)
template<typename Number , typename Converter , class Setting >
bool operator!= (const PolytopeT< Number, Converter, Setting > &rhs, const PolytopeT< Number, Converter, Setting > &lhs)
BETTER_ENUM (carlPolytopeSetting_name, int, CarlPolytopeSetting) struct CarlPolytopeSetting
template<typename N , typename D >
FormulasT< N > halfspacesToConstraints (const matrix_t< D > &constraints, const vector_t< D > &constants)
template<typename N >
FormulasT< N > constraintsToFormulas (const std::vector< ConstraintT< N >> &in)
template<typename N , typename D >
FormulasT< N > intervalToFormulas (const carl::Interval< D > &interval, const carl::Variable &var)
template<typename N , typename D >
FormulasT< N > intervalToFormulas (const carl::Interval< D > &interval, std::size_t variableIndex)
template<typename N , typename D >
vector_t< D > constraintNormal (const ConstraintT< N > &c, std::size_t dim)
template<typename N , typename D >
D normalizedOffset (const ConstraintT< N > &c)
template<typename N , typename D >
std::vector< Halfspace< D > > constraintToHalfspace (const ConstraintT< N > &constraint, std::size_t dim)
template<typename N , typename D >
std::vector< Halfspace< D > > computeHalfspaces (const FormulaT< N > &formula, std::size_t dim)
template<typename N , typename D >
D computeWidening (const ConstraintT< N > &constraint)
template<typename Number >
bool operator< (std::shared_ptr< Halfspace< Number >> _lhs, std::shared_ptr< Halfspace< Number >> _rhs)
template<typename Number >
std::ostream & operator<< (std::ostream &_out, Cone< Number > &_cone)
template<typename From , typename To , typename Converter , class Setting >
HPolytopeT< To, Converter, Setting > convert (const HPolytopeT< From, Converter, Setting > &in)
BETTER_ENUM (hPolytopeSetting_name, int, HPolytopeSetting, HPolytopeOptimizerCaching) struct HPolytopeSetting
template<typename N >
std::size_t numberOfPointsInHalfspace (const std::vector< Point< N >> &points, const Halfspace< N > &hsp)
template<typename Number , typename Converter , typename S >
std::ostream & operator<< (std::ostream &out, const hypro::VPolytopeT< Number, Converter, S > &lhs)
template<typename From , typename To , typename Converter , typename S >
VPolytopeT< To, Converter, S > convert (const VPolytopeT< From, Converter, S > &in)
template<typename Number >
bool contains (std::vector< matrix_t< Number >> list, matrix_t< Number > direction, unsigned int length)
template<typename Number >
int contains (std::vector< matrix_t< Number >> *directions, matrix_t< Number > *direction)
template<typename Number >
int contains (std::vector< matrix_t< Number >> *directions, matrix_t< Number > direction)
template<typename Number >
int * computeDirectionMapping (std::vector< matrix_t< Number >> *directions)
template<typename Number >
bool listContains (std::vector< Number > *list, Number item)
template<typename Number >
matrix_t< Number > directionList2Matrix (std::vector< matrix_t< Number >> *list)
template<typename Number >
matrix_t< Number > * list2Array (std::vector< matrix_t< Number >> *list)
template<typename Number >
Number * matrix2Array (matrix_t< Number > m)
template<typename Number >
Number * vector2Array (vector_t< Number > v)
template<typename Number >
matrix_t< Number > addZeroColumn (matrix_t< Number > m)
template<typename Number >
matrix_t< Number > addZeroRow (matrix_t< Number > m)
template<typename Number , typename Converter , typename Setting >
SupportFunctionT< Number, Converter, Setting > unite (const std::vector< SupportFunctionT< Number, Converter, Setting >> &_rhs)
BETTER_ENUM (supportFunctionSetting_name, int, SupportFunctionSetting, NoBoxReduction, NoBoxDetection, NoTrafoReduction, NoReduction, PolytopeSupportFunctionSetting) struct SupportFunctionSetting
template<typename Number , typename Converter , typename Setting , typename SettingRhs , carl::DisableIf< std::is_same< Setting, SettingRhs >> = carl::dummy>
std::shared_ptr< RootGrowNode< Number, Converter, Setting > > convertSettings (const RootGrowNode< Number, Converter, SettingRhs > *in)
BETTER_ENUM (sfnSetting_name, int, SupportFunctionNewDefault, SupportFunctionNewMorePrecision, SupportFunctionNewNoReduction, SupportFunctionNewLeGuernic) struct SupportFunctionNewDefault
template<typename Number >
void output_2D_interval_gnuplot (std::list< Flowpipe< Number >> &flowpipes, std::ofstream &os, const std::string &fileName, const carl::Variable &axis_x, const carl::Variable &axis_y)
template<typename N >
std::ostream & operator<< (std::ostream &os, const TaylorModel< N > &tm)
template<typename N >
std::ostream & operator<< (std::ostream &os, const Domain< N > &domain)
template<typename N >
std::ostream & operator<< (std::ostream &os, const PolynomialODE< N > &ode)
template<typename N >
std::ostream & operator<< (std::ostream &os, const Range< N > &range)
template<typename N >
std::ostream & operator<< (std::ostream &os, const TaylorModelVec< N > &tmv)
BETTER_ENUM (tpolySetting_name, int, TemplatePolyhedronDefault, OctagonShape) enum TEMPLATE_CONTENT
template<typename Number , typename Converter , typename Setting >
std::ostream & operator<< (std::ostream &out, const ZonotopeT< Number, Converter, Setting > &in)
template<typename Number >
bool comparePoint (Eigen::Matrix< Number, 2, 1 > &p1, Eigen::Matrix< Number, 2, 1 > &p2)
template<typename Number >
void removeGenerator (unsigned colToRemove, matrix_t< Number > &matrix)
template<typename Number >
void removeEmptyGenerators (matrix_t< Number > &generatorMatrix)
template<typename Number >
Eigen::Matrix< Number, 2, 1 > computeLineIntersection (const ZUtility::Line_t< Number > &l1, const ZUtility::Line_t< Number > &l2)
template<typename Number , typename Converter , typename Setting >
Number intersect2d (const ZonotopeT< Number, Converter, Setting > &input, const Halfspace< Number > &hp, int minOrMax)
template<typename Number , typename Converter , typename Setting >
ZonotopeT< Number, Converter, Setting > intersectZonotopeHalfspaceDSearch (const ZonotopeT< Number, Converter, Setting > &inputZonotope, const Halfspace< Number > &hp)
template<typename Number , typename Converter , typename Setting >
ZonotopeT< Number, Converter, Setting > intersectAlamo (const ZonotopeT< Number, Converter, Setting > &inputZonotope, const Halfspace< Number > &hp)
template<typename Number , typename Converter , typename Setting >
ZonotopeT< Number, Converter, Setting > intersectNDProjection (const ZonotopeT< Number, Converter, Setting > &inputZonotope, const Halfspace< Number > &hp, matrix_t< Number > &minMaxOfLine)
template<typename From , typename To >
matrix_t< To > convert (const matrix_t< From > &_mat)
template<typename From , typename To >
Eigen::DiagonalMatrix< To, Eigen::Dynamic > convert (const Eigen::DiagonalMatrix< From, Eigen::Dynamic > &_mat)
template<typename Number >
vector_t< Number > normalize (const vector_t< Number > &in)
template<typename Number >
vector_t< Number > project (const vector_t< Number > &in, const std::vector< std::size_t > &dimensions)
template<typename Number >
vector_t< Number > scalarProjection (const vector_t< Number > &source, const vector_t< Number > &target)
template<typename Number >
int effectiveDimension (const std::vector< vector_t< Number >> &vertices)
template<typename Number >
std::pair< bool, Number > linearDependent (const vector_t< Number > &lhs, const vector_t< Number > &rhs)
template<typename Number , carl::DisableIf< std::is_same< Number, double >> = carl::dummy>
vector_t< Number > reduceNumberRepresentation (const vector_t< Number > &in)
template<typename Number >
std::string createCode (const matrix_t< Number > &in, unsigned index=0)
template<typename Number >
matrix_t< Number > matrixExponential (const matrix_t< Number > &inMatrix)
Computes the matrix exponential via conversion to double and then using eigen::exp.
template<typename Number >
std::string createCode (const vector_t< Number > &in, unsigned index=0)
template<typename Number >
bool satisfiesIneqation (const vector_t< Number > &constraint, Number constant, const vector_t< Number > &point)
template<>
std::pair< bool, double > linearDependent (const vector_t< double > &lhs, const vector_t< double > &rhs)
template<>
bool satisfiesIneqation (const vector_t< double > &constraint, double constant, const vector_t< double > &point)
template<typename Number , typename IdxType >
matrix_t< Number > selectRows (const matrix_t< Number > &original, const std::vector< IdxType > &rowIndices)
template<typename Number , typename IdxType >
matrix_t< Number > removeRows (const matrix_t< Number > &original, const std::vector< IdxType > &rowIndices)
template<typename Number >
matrix_t< Number > & appendRow (matrix_t< Number > &original, const vector_t< Number > &row)
template<typename Number >
vector_t< Number > & appendRow (vector_t< Number > &original, Number entry)
template<typename Number , typename IdxType >
vector_t< Number > selectRows (const vector_t< Number > &original, const std::vector< IdxType > &rowIndices)
template<typename Number , typename IdxType >
vector_t< Number > removeRows (const vector_t< Number > &original, const std::vector< IdxType > &rowIndices)
template<typename Number , typename IdxType >
matrix_t< Number > selectCols (const matrix_t< Number > &original, const std::vector< IdxType > &colIndices)
template<typename Enumeration >
auto as_integer (Enumeration const value) -> typename std::underlying_type< Enumeration >::type
template<typename Enumeration , carl::EnableIf< std::is_enum< Enumeration >> = carl::dummy>
std::ostream & operator<< (std::ostream &out, Enumeration in)
template<typename T >
std::ostream & operator<< (std::ostream &_out, const std::set< T > &_set)
template<typename T >
std::ostream & operator<< (std::ostream &_out, const std::vector< T > &_vector)
template<typename T >
std::ostream & operator<< (std::ostream &_out, const std::pair< T, T > &_pair)
template<typename Key , typename T >
std::ostream & operator<< (std::ostream &_out, const std::map< Key, T > &_map)
template<typename From , typename To >
carl::Interval< To > convert (const carl::Interval< From > &original)
SOLUTION clpCheckConsistency (clp_context &context)
template<typename Number >
EvaluationResult< Number > clpOptimizeLinear (clp_context &context, const vector_t< Number > &_direction, const matrix_t< Number > &constraints, const vector_t< Number > &constants, bool useExact)
template<typename Number >
bool clpCheckPoint (clp_context &context, const matrix_t< Number > &constraints, const vector_t< Number > &constants, const Point< Number > &_point)
template<typename Number >
std::vector< std::size_t > clpRedundantConstraints (clp_context &context, const matrix_t< Number > &constraints, const vector_t< Number > &constants)
template<typename Number >
EvaluationResult< Number > clpGetInternalPoint (clp_context &context)
template<typename Number >
bool operator< (const EvaluationResult< Number > &lhs, const EvaluationResult< Number > &rhs)
template<typename Number >
bool operator> (const EvaluationResult< Number > &lhs, const EvaluationResult< Number > &rhs)
template<typename Number >
bool operator== (const EvaluationResult< Number > &lhs, const EvaluationResult< Number > &rhs)
void printProblem (glp_prob *glpkProblem)
template<typename Number >
vector_t< Number > refineSolution (glpk_context &context, const matrix_t< Number > &constraints, const vector_t< Number > &constants)
template<typename Number >
EvaluationResult< Number > glpkOptimizeLinear (glpk_context &context, const vector_t< Number > &_direction, const matrix_t< Number > &constraints, const vector_t< Number > &constants, bool useExact)
template<typename Number >
bool glpkCheckPoint (glpk_context &context, const matrix_t< Number > &constraints, const vector_t< Number > &, const Point< Number > &point)
template<typename Number >
std::vector< std::size_t > glpkRedundantConstraints (glpk_context &context, matrix_t< Number > constraints, vector_t< Number > constants)
template<typename Number >
EvaluationResult< Number > glpkGetInternalPoint (glpk_context &context, std::size_t dimension, bool useExact)
template<>
EvaluationResult< double > glpkOptimizeLinear (glpk_context &context, const vector_t< double > &_direction, const matrix_t< double > &constraints, const vector_t< double > &constants, bool useExact)
template<>
bool glpkCheckPoint (glpk_context &context, const matrix_t< double > &constraints, const vector_t< double > &, const Point< double > &point)
template<>
std::vector< std::size_t > glpkRedundantConstraints (glpk_context &context, matrix_t< double > constraints, vector_t< double > constants)
template<typename Number >
EvaluationResult< Number > smtratOptimizeLinear (const vector_t< Number > &_direction, const matrix_t< Number > &constraints, const vector_t< Number > &constants, const std::vector< carl::Relation > &relationSymbols, const EvaluationResult< Number > &preSolution=EvaluationResult< Number >())
template<typename Number >
bool smtratCheckConsistency (const matrix_t< Number > &constraints, const vector_t< Number > &constants, std::vector< carl::Relation > &relationSymbols)
template<typename Number >
bool smtratCheckPoint (const matrix_t< Number > &constraints, const vector_t< Number > &constants, std::vector< carl::Relation > &relationSymbols, const Point< Number > &point)
template<typename Number >
std::vector< std::size_t > smtratRedundantConstraints (const matrix_t< Number > &constraints, const vector_t< Number > &constants, std::vector< carl::Relation > &relationSymbols)
template<typename Number >
EvaluationResult< Number > smtratGetInternalPoint (const matrix_t< Number > &constraints, const vector_t< Number > &constants, std::vector< carl::Relation > &relationSymbols)
template<typename Number >
bool smtratCheckConsistency (const matrix_t< Number > &constraints, const vector_t< Number > &constants, const std::vector< carl::Relation > &relationSymbols)
template<typename Number >
bool smtratCheckPoint (const matrix_t< Number > &constraints, const vector_t< Number > &constants, const std::vector< carl::Relation > &relationSymbols, const Point< Number > &point)
template<typename Number >
std::vector< std::size_t > smtratRedundantConstraints (const matrix_t< Number > &constraints, const vector_t< Number > &constants, const std::vector< carl::Relation > &relationSymbols)
template<typename Number >
EvaluationResult< Number > smtratGetInternalPoint (const matrix_t< Number > &constraints, const vector_t< Number > &constants, const std::vector< carl::Relation > &relationSymbols)
template<typename Number >
void addPreSolution (smtrat::SimplexSolver &solver, const EvaluationResult< Number > &preSolution, const vector_t< Number > &direction, const smtrat::Poly &objective)
template<typename Number >
EvaluationResult< Number > extractSolution (smtrat::SimplexSolver &solver, const smtrat::Poly &objective, unsigned dimension)
template<typename Number >
EvaluationResult< Number > soplexOptimizeLinear (const vector_t< Number > &_direction, const matrix_t< Number > &constraints, const vector_t< Number > &constants, const EvaluationResult< Number > &preSolution=EvaluationResult< Number >())
template<typename Number >
bool soplexCheckConsistency (const matrix_t< Number > &constraints, const vector_t< Number > &constants)
template<typename Number >
bool soplexCheckPoint (const matrix_t< Number > &constraints, const vector_t< Number > &constants, const Point< Number > &point)
template<typename Number >
EvaluationResult< Number > z3OptimizeLinear (bool maximize, const vector_t< Number > &_direction, const matrix_t< Number > &constraints, const vector_t< Number > &constants, const EvaluationResult< Number > &preSolution=EvaluationResult< Number >())
template<>
EvaluationResult< double > z3OptimizeLinear (bool maximize, const vector_t< double > &_direction, const matrix_t< double > &constraints, const vector_t< double > &constants, const EvaluationResult< double > &preSolution)
template<typename Number >
bool z3CheckConsistency (const matrix_t< Number > &constraints, const vector_t< Number > &constants)
template<typename Number >
bool z3CheckPoint (const matrix_t< Number > &constraints, const vector_t< Number > &constants, const Point< Number > &point)
template<typename Number >
std::vector< std::size_t > z3RedundantConstraints (const matrix_t< Number > &constraints, const vector_t< Number > &constants)
template<typename Number >
void addPreSolution (z3::optimize &solver, z3Context &c, const EvaluationResult< Number > &preSolution, const vector_t< Number > &direction, const z3::expr &objective)
int initializeLogging (int &i)
std::vector< std::size_t > HEXtoRGB (std::size_t color)
std::size_t RGBtoHEX (std::vector< std::size_t > color)
std::vector< double > RGBtoHSV (const std::vector< std::size_t > &color)
std::vector< std::size_t > HSVtoRGB (const std::vector< double > &color)
std::vector< std::size_t > adjustSaturation (const std::vector< std::size_t > &rgbColor, double factor)
std::size_t adjustSaturation (std::size_t rgbColor, double factor)
bool file_exists (const std::string &filename)
template<typename T >
T toContainer (Range< T > &r)
template<typename T >
Range< T > selectFirstConsecutiveRange (const T &in, std::function< bool(typename T::value_type)> cmp)
template<typename SetType , typename Number , sampling_strategy_set SMPL_STRAT>
std::vector< SimulationSample< Number > > sample (const SetType &in, unsigned k=0)
template<typename tNumber , sampling_strategy_interval SMPL_STRAT>
std::vector< tNumber > sample (const carl::Interval< tNumber > guardIntersectInterval, unsigned k=0)
template<typename... Ts, typename F >
std::tuple< Ts... > for_each_in_tuple (std::tuple< Ts... > const &t, F f)
template<typename... Ts, typename F >
std::tuple< std::pair< bool, Ts... > > for_each_in_tuple_pair (std::tuple< Ts... > const &t, F f)
template<typename... Ts, typename F >
std::tuple< Ts... > for_each_in_tuple (std::tuple< Ts... > const &t1, std::tuple< Ts... > const &t2, F f)
template<typename... T>
auto make_vector (T &&...args)
template<typename Number , typename Converter , typename Callable , typename... Args>
auto dispatch (representation_name representation, int setting, Callable func, Args &&...args)
template<typename Number , typename Converter , typename Callable , typename... Args>
auto dispatch (representation_name representation, int setting, Callable func, Args...args)
Example usage: see example_dispatch.cpp
int stringToSetting (const std::string &name)
void unreachable ()
template<typename Number >
const Point< Number > operator+ (const Point< Number > &_lhs, const Point< Number > &_rhs)
Arithmetic operator returning a new point.
template<typename Number >
const Point< Number > operator+ (const Point< Number > &_lhs, const vector_t< Number > &_rhs)
Arithmetic operator returning a new point.
template<typename Number >
const Point< Number > operator- (const Point< Number > &_lhs, const Point< Number > &_rhs)
Arithmetic operator returning a new point.
template<typename Number >
const Point< Number > operator/ (const Point< Number > &_lhs, unsigned _quotient)
Arithmetic operator returning a new point.
template<typename Number >
Number operator* (const Point< Number > &_lhs, const Point< Number > &_rhs)
Arithmetic operator returning a new point.
template<typename Number >
const Point< Number > operator* (const Point< Number > &_lhs, const Number &_factor)
Arithmetic operator returning a new point.
template<typename Number >
const Point< Number > operator* (const Number &_factor, const Point< Number > &_rhs)
Arithmetic operator returning a new point.
Variables
template<typename T , typename U >
constexpr bool convertible = std::is_convertible_v<T, U>
template<typename Number >
constexpr bool is_exact = std::is_same_v<Number, mpq_class>
Detailed Description
General context interface to set up a reachability worker.
The most general namespace for the HyPro library.
TPolyFirstSegmentHandler.h
Author
Phillip Tse
Date
18.9.2019
TPolyTimeEvolutionHandler.h
Author
Phillip Tse
Date
4.10.2019
Implementation of cones.
File holding utility functions to keep the main files clean.
This file contains transformation functions for matrices and vectors.
Holds convenience functions when working with SMTRat.
Author
Stefan Schupp stefa.nosp@m.n.sc.nosp@m.hupp@.nosp@m.cs.r.nosp@m.wth-a.nosp@m.ache.nosp@m.n.de
Since
2016-03-22
Version
2016-03-22
With reference to https://stackoverflow.com/questions/16387354/template-tuple-calling-a-function-on-each-element
Class Documentation
struct hypro::AnalysisParameters
Definition at line 12 of file Settings.h.
Class Members
AGG_SETTING aggregation the used time step size
int clustering the forced aggregation settings
int representation_setting type of representation
representation_name representation_type if clustering is used: number of clusters
mpq_class timeStep
bool uniformBloating used settings for the representation
struct hypro::apply_i
template<template< class... > class Templ, class ArgList>
struct hypro::apply_i< Templ, ArgList >
Definition at line 33 of file TypeList.h.
struct hypro::apply_i< Templ, TypeList< Args... > >
template<template< class... > class Templ, class... Args>
struct hypro::apply_i< Templ, TypeList< Args... > >
Definition at line 37 of file TypeList.h.
Class Members
type
struct hypro::ChildTimingInformation
template<typename N>
struct hypro::ChildTimingInformation< N >
Definition at line 14 of file TimingAggregate.h.
Class Members
map< EventTimingNode< N > *, bool > timingInformation
struct hypro::concat_i
template<class List, class... Lists>
struct hypro::concat_i< List, Lists >
Definition at line 12 of file TypeList.h.
Class Members
type
struct hypro::concat_i< TypeList< Ts... >, TypeList< Us... > >
template<class... Ts, class... Us>
struct hypro::concat_i< TypeList< Ts... >, TypeList< Us... > >
Definition at line 19 of file TypeList.h.
Class Members
type
struct hypro::ConstraintSetSettings
Dummy struct for settings. *.
Definition at line 14 of file ConstraintSet.h.
struct hypro::DifferenceBoundsSetting
Definition at line 5 of file DifferenceBoundsSetting.h.
struct hypro::flattenRepresentations_i
template<class Number, class Converter, class CombinationsList>
struct hypro::flattenRepresentations_i< Number, Converter, CombinationsList >
Definition at line 17 of file RepresentationCombinations.h.
struct hypro::flattenRepresentations_i< Number, Converter, TypeList< RepCombinationsList... > >
template<class Number, class Converter, class... RepCombinationsList>
struct hypro::flattenRepresentations_i< Number, Converter, TypeList< RepCombinationsList... > >
Definition at line 20 of file RepresentationCombinations.h.
Class Members
type
struct hypro::OrthoplexDefault
Definition at line 5 of file OrthoplexSetting.h.
class hypro::QuickhullAlgorithm
template<typename Number, bool Euclidian = true, typename = void>
class hypro::QuickhullAlgorithm< Number, Euclidian, typename >
Definition at line 7 of file Quickhull.h.
struct hypro::RepresentationCombinations
template<template< class... > class Representation, class... Settings>
struct hypro::RepresentationCombinations< Representation, Settings >
Definition at line 8 of file RepresentationCombinations.h.
Class Members
combinations
struct hypro::Settings
Definition at line 23 of file Settings.h.
Class Members
int jumpDepth
tNumber localTimeHorizon
vector< vector< size_t > > plotDimensions
vector< string > plotFileNames
PLOTTYPE plottingFileType
unsigned long pplDenominator
vector< AnalysisParameters > strategy
struct hypro::STallValues
template<typename Number>
struct hypro::STallValues< Number >
STallValues as struct for all for reachability analysis relevant EVD values for constant flow of location input vertices have to be representable as points for evaluation.
Definition at line 52 of file Transformation.h.
Class Members
STflowpipeSegment< Number > mSTflowpipeSegment
STindependentFunct< Number > mSTindependentFunct
struct hypro::STflowpipeSegment
template<typename Number>
struct hypro::STflowpipeSegment< Number >
Definition at line 42 of file Transformation.h.
Class Members
Matrix< Number > trafoInput
Matrix< Number > V
Matrix< Number > Vinv
struct hypro::STindependentFunct
template<typename Number>
struct hypro::STindependentFunct< Number >
Definition at line 35 of file Transformation.h.
Class Members
DiagonalMatrix< Number > D
ExpFunctionTypeStdVector expFunctionType
Vector< Number > xinhom
struct hypro::TreeStatistic
Definition at line 6 of file TreeStatistic.h.
Class Members
double avgBranching
double avgLevel
size_t depth
vector< size_t > levelCnt
size_t nodeCnt
struct hypro::TypeList
template<class... Types>
struct hypro::TypeList< Types >
Definition at line 7 of file TypeList.h.
struct hypro::TypeMapping
template<class Representation>
struct hypro::TypeMapping< Representation >
Definition at line 18 of file dispatch_meta.h.
Typedef Documentation
template<template< class... > class Templ, class ArgList > using hypro::apply = typedef typename apply_i<Templ, ArgList>::type
Definition at line 43 of file TypeList.h.
using hypro::BoolMatrix = typedef matrix_t<bool>
Definition at line 31 of file Transformation.h.
template<typename Number > using hypro::Box = typedef typename Converter<Number>::Box
Definition at line 6 of file typedefs.h.
template<typename Number > using hypro::CarlPolytope = typedef typename Converter<Number>::CarlPolytope
Definition at line 9 of file typedefs.h.
template<class... Lists> using hypro::concat = typedef typename concat_i<Lists...>::type
Definition at line 25 of file TypeList.h.
template<typename Number > using hypro::ConstraintSet = typedef typename Converter<Number>::ConstraintSet
Definition at line 12 of file typedefs.h.
template<typename Number > using hypro::ConstraintsT = typedef std::vector<ConstraintT<Number> >
Definition at line 18 of file carlTypes.h.
template<typename Number > using hypro::ConstraintT = typedef carl::Constraint<PolyT<Number> >
Definition at line 15 of file carlTypes.h.
template<class Number , class Converter > using hypro::DefaultDispatcher = typedef Dispatcher<Number, Converter, DefaultRepresentations>
Definition at line 28 of file default_dispatch.h.
using hypro::DefaultRepresentations = typedef TypeList< RepresentationCombinations< BoxT, BoxLinearOptimizationOn, BoxLinearOptimizationOff, BoxIntervalArithmeticOff, BoxAllOff>, RepresentationCombinations< HPolytopeT, HPolytopeSetting, HPolytopeOptimizerCaching>, RepresentationCombinations< SupportFunctionT, SupportFunctionSetting, NoBoxReduction, NoBoxDetection, NoTrafoReduction, NoReduction, PolytopeSupportFunctionSetting>, RepresentationCombinations< SupportFunctionNewT, SupportFunctionNewDefault, SupportFunctionNewMorePrecision, SupportFunctionNewNoReduction, SupportFunctionNewLeGuernic>, RepresentationCombinations< TemplatePolyhedronT, TemplatePolyhedronDefault> >
Definition at line 25 of file default_dispatch.h.
template<typename Number > using hypro::DiagonalMatrix = typedef Eigen::DiagonalMatrix<Number, Eigen::Dynamic>
Definition at line 29 of file Transformation.h.
using hypro::DiagonalMatrixdouble = typedef Eigen::DiagonalMatrix<double, Eigen::Dynamic>
Definition at line 30 of file Transformation.h.
template<typename Number > using hypro::DifferenceBounds = typedef typename Converter<Number>::DifferenceBounds
Definition at line 15 of file typedefs.h.
template<class Number , class Converter , class RepresentationCombinationsList > using hypro::Dispatcher = typedef apply<Dispatcher_i, flattenRepresentations<Number, Converter, RepresentationCombinationsList>>
Definition at line 52 of file dispatch_meta.h.
using hypro::DynamicStrategy = typedef std::vector<AnalysisParameters>
Definition at line 21 of file Settings.h.
template<typename Number > using hypro::Ellipsoid = typedef typename Converter<Number>::Ellipsoid
Definition at line 18 of file typedefs.h.
template<bool B> using hypro::enable_if = typedef std::enable_if_t<B, int>
Definition at line 21 of file typetraits.h.
template<typename Number > using hypro::EnableIfExact = typedef std::enable_if_t<is_exact<Number>>
Definition at line 31 of file typetraits.h.
template<typename Number > using hypro::EnableIfFloatingpoint = typedef std::enable_if_t<std::is_floating_point_v<Number>>
Definition at line 34 of file typetraits.h.
template<typename Number , bool Euclidian> using hypro::ExactQuickhull = typedef QuickhullAlgorithm<Number, Euclidian, EnableIfExact<Number>>
Definition at line 12 of file Quickhull.h.
using hypro::ExpFunctionTypeStdVector = typedef std::vector<EXP_FUNCT_TYPE>
Definition at line 32 of file Transformation.h.
template<class Number , class Converter , class CombinationsList > using hypro::flattenRepresentations = typedef typename flattenRepresentations_i<Number, Converter, CombinationsList>::type
Definition at line 27 of file RepresentationCombinations.h.
template<typename Number > using hypro::flowVariant = typedef std::variant<linearFlow<Number>, affineFlow<Number>, rectangularFlow<Number>>
Definition at line 26 of file Location.h.
template<typename Number > using hypro::FormulasT = typedef std::vector<FormulaT<Number> >
Definition at line 24 of file carlTypes.h.
template<typename Number > using hypro::FormulaT = typedef carl::Formula<PolyT<Number> >
Definition at line 21 of file carlTypes.h.
template<typename Number > using hypro::HPolytope = typedef typename Converter<Number>::HPolytope
Definition at line 21 of file typedefs.h.
template<typename State > using hypro::initialData = typedef std::tuple<const Location<typename State::NumberType>*, typename State::repVariant, typename State::NumberType, representation_name>
Definition at line 22 of file NodeManager.h.
template<typename Number > using hypro::Matrix = typedef matrix_t<Number>
Definition at line 25 of file Transformation.h.
template<typename Number > using hypro::matrix_t = typedef Eigen::Matrix<Number, Eigen::Dynamic, Eigen::Dynamic>
typedef wrapping an Eigen::Matrix type.
Definition at line 28 of file types.h.
template<std::size_t I, typename... Ts> using hypro::nth_element = typedef typename detail::nth_element_impl<I, Ts...>::type
Definition at line 19 of file nth_element.h.
template<typename Number > using hypro::OrthogonalPolyhedron = typedef typename Converter<Number>::OrthogonalPolyhedron
Definition at line 24 of file typedefs.h.
template<typename Number > using hypro::PolyT = typedef carl::MultivariatePolynomial<Number>
Definition at line 12 of file carlTypes.h.
template<typename Number > using hypro::Polytope = typedef typename Converter<Number>::Polytope
Definition at line 31 of file typedefs.h.
using hypro::QEQuery = typedef std::vector<std::pair<QuantifierType, std::vector<carl::Variable> > >
Definition at line 26 of file carlTypes.h.
template<typename Number > using hypro::Quickhull = typedef QuickhullAlgorithm<Number, true, void>
Definition at line 10 of file Quickhull.h.
template<typename Number > using hypro::QuickIntersection = typedef QuickhullAlgorithm<Number, false, void>
Definition at line 13 of file Quickhull.h.
template<typename Number > using hypro::SupportFunction = typedef typename Converter<Number>::SupportFunction
Definition at line 35 of file typedefs.h.
template<typename Number > using hypro::SupportFunctionNew = typedef typename Converter<Number>::SupportFunctionNew
Definition at line 38 of file typedefs.h.
template<typename Number > using hypro::TemplatePolyhedron = typedef typename Converter<Number>::TemplatePolyhedron
Definition at line 47 of file typedefs.h.
using hypro::tNumber = typedef mpq_class
Number type used for timings and time intervals.
Definition at line 16 of file types.h.
template<typename Number > using hypro::TTransitionTimings = typedef std::map<Transition<Number>*, std::vector<carl::Interval<tNumber>>>
Maps a transition to its time intervals where the guard was satisfied. Should be updated during computation.
Definition at line 27 of file ReachTreeNode.h.
template<typename Number > using hypro::Vector = typedef vector_t<Number>
Definition at line 27 of file Transformation.h.
template<typename Number > using hypro::vector_t = typedef Eigen::Matrix<Number, Eigen::Dynamic, 1>
typedef wrapping an Eigen::Matrix type with only one column.
Definition at line 22 of file types.h.
template<typename Number > using hypro::vectorSet = typedef std::set<vector_t<Number>>
Definition at line 14 of file Cone.h.
template<typename Number > using hypro::vList = typedef typename std::list<Vertex<Number>>
Definition at line 28 of file Vertex.h.
template<typename Number > using hypro::vListIt = typedef typename std::list<Vertex<Number>>::iterator
Definition at line 30 of file Vertex.h.
template<typename Number > using hypro::VPolytope = typedef typename Converter<Number>::VPolytope
Definition at line 27 of file typedefs.h.
template<typename Number > using hypro::vSet = typedef typename std::set<Vertex<Number>>
Definition at line 32 of file Vertex.h.
template<typename Number > using hypro::vSetIt = typedef typename std::set<Vertex<Number>>::iterator
Definition at line 34 of file Vertex.h.
template<typename Number > using hypro::vVec = typedef typename std::vector<Vertex<Number>>
Definition at line 24 of file Vertex.h.
template<typename Number > using hypro::vVecIt = typedef typename std::vector<Vertex<Number>>::iterator
Definition at line 26 of file Vertex.h.
template<typename Workable > using hypro::WorkQueue = typedef WorkQueueT<Workable, WorkQueueDefaultSetting>
Definition at line 114 of file WorkQueue.h.
template<typename Number > using hypro::Zonotope = typedef typename Converter<Number>::Zonotope
Definition at line 41 of file typedefs.h.
Enumeration Type Documentation
enum hypro::AGG_SETTING strong
Enumerator
MODEL
AGG
NO_AGG
Definition at line 102 of file types.h.
enum hypro::Aggregation
Enumerator
none
none
boxAgg
clustering
parallelotopeAgg
Definition at line 21 of file Transition.h.
enum hypro::CONTAINMENT strong
Enum for set containment results. If known, we can make a statement about full or partial containment, otherwise fall back to YES/NO. Note: BOT is used for UNKNOWN.
Enumerator
NO
BOT
PARTIAL
FULL
YES
Definition at line 72 of file types.h.
enum hypro::CONV_MODE
enum for differentiating between exact conversion and over-/underapproximation (some functions support an alternative computation method).
Enumerator
EXACT
OVER
UNDER
ALTERNATIVE
Definition at line 33 of file Converter.h.
enum hypro::DynamicType strong
classifies the type of dynamics of a flow for a location.
Enumerator
linear
affine
rectangular
timed
discrete
Definition at line 96 of file types.h.
enum hypro::EXP_FUNCT_TYPE
Enumerator
CONVERGENT
DIVERGENT
LINEAR
CONSTANT
UNDEFINED
INITIALIZED
Definition at line 17 of file Transformation.h.
enum hypro::LOCATIONTYPE strong
classifies the type of location, which reflects the dynamics in case we dynamically detect subspaces.
Enumerator
LTILOC
TIMEDLOC
RECTANGULARLOC
Definition at line 89 of file types.h.
enum hypro::OptimizerStrategy
Enumerator
SMTRAT
SOPLEX
SMTRAT
GLPK
Definition at line 5 of file Strategy.h.
enum hypro::ORTHO_TYPE
Enum holding the type identification of the different representations of orthogonal polyhedra.
Enumerator
VERTEX
NEIGHBORHOOD
EXTREME_VERTEX
Definition at line 30 of file OrthogonalPolyhedron.h.
enum hypro::PLOTTYPE strong
Enumerator
pdf
png
eps
gen
tex
nset
Definition at line 45 of file types.h.
enum hypro::QuantifierType strong
Enumerator
EXISTS
FORALL
Definition at line 8 of file carlTypes.h.
enum hypro::REACHABILITY_RESULT strong
Enumerator
SAFE
UNKNOWN
Definition at line 40 of file types.h.
enum hypro::ResetType strong
Enumerator
affine
interval
none
Definition at line 9 of file ResetTypes.h.
enum hypro::sampling_strategy_interval
Enumerator
UNIFORM_K
BORDERS
RANDOM_INTV_K
Definition at line 18 of file sampling.h.
enum hypro::sampling_strategy_set
Enumerator
CENTER
VERTICES
RANDOM_SET_K
Definition at line 15 of file sampling.h.
enum hypro::SETSTATE strong
Enum to represent set states such as empty and universal.
Enumerator
UNKNOWN
NONEMPTY
EMPTY
UNIVERSAL
Definition at line 55 of file types.h.
enum hypro::SF_TYPE
This enum represents the support function type and is used to identify support function instances without instanceof operations.
Enumerator
SUM
INTERSECT
LINTRAFO
SCALE
UNITE
POLY
INFTY_BALL
TWO_BALL
ELLIPSOID
BOX
ZONOTOPE
PROJECTION
NONE
Definition at line 20 of file util.h.
enum hypro::SFNEW_TYPE
Enumerator
NODE
LEAF
TRAFO
SCALEOP
PROJECTOP
SUMOP
INTERSECTOP
UNIONOP
INTERSECTHSPACEOP
Definition at line 34 of file RootGrowNode.h.
enum hypro::SOLUTION strong
Enum of possible solution types for linear optimization.
Enumerator
FEAS
INFEAS
INFTY
UNKNOWN
Definition at line 63 of file types.h.
enum hypro::SUBSPACETYPE strong
classifies the type of subspace in case subspace decomposition is used.
Enumerator
LTI
TIMED
DISCRETE
RECTANGULAR
Definition at line 81 of file types.h.
enum hypro::TRIBOOL strong
Enum implementing a tribool.
Enumerator
TRUE
FALSE
NSET
Definition at line 36 of file types.h.
Function Documentation
template<typename Number > void hypro::addPreSolution (smtrat::SimplexSolver & solver, const EvaluationResult< Number > & preSolution, const vector_t< Number > & direction, const smtrat::Poly & objective)
Definition at line 3 of file helper_methods.h.
References hypro::VariablePool::carlVarByIndex(), hypro::EvaluationResult< Number >::optimumValue, and hypro::EvaluationResult< Number >::supportValue.
Referenced by smtratOptimizeLinear(), and z3OptimizeLinear().
template<typename Number > void hypro::addPreSolution (z3::optimize & solver, z3Context & c, const EvaluationResult< Number > & preSolution, const vector_t< Number > & direction, const z3::expr & objective)
Definition at line 7 of file helper_methods.h.
References hypro::EvaluationResult< Number >::optimumValue, hypro::z3Context::real_val(), hypro::EvaluationResult< Number >::supportValue, and hypro::plotting::to_string().
template<typename Number > matrix_t<Number> hypro::addZeroColumn (matrix_t< Number > m)
Definition at line 217 of file helperMethods.h.
template<typename Number > matrix_t<Number> hypro::addZeroRow (matrix_t< Number > m)
Definition at line 252 of file helperMethods.h.
std::vector< std::size_t > hypro::adjustSaturation (const std::vector< std::size_t > & rgbColor, double factor)
Definition at line 134 of file PlotterUtil.cpp.
References HSVtoRGB(), and RGBtoHSV().
Referenced by adjustSaturation().
std::size_t hypro::adjustSaturation (std::size_t rgbColor, double factor)
Definition at line 140 of file PlotterUtil.cpp.
References adjustSaturation(), HEXtoRGB(), and RGBtoHEX().
template<typename Number > matrix_t<Number>& hypro::appendRow (matrix_t< Number > & original, const vector_t< Number > & row)
Definition at line 31 of file transformation.h.
Referenced by hypro::SupportFunctionT< Number, Converter, Setting >::satisfiesHalfspaces().
template<typename Number > vector_t<Number>& hypro::appendRow (vector_t< Number > & original, Number entry)
Definition at line 39 of file transformation.h.
template<typename Number , typename Representation , carl::DisableIf< std::is_same< Representation, SupportFunction< Number >>> = carl::dummy> void hypro::applyReduction (Representation & _in)
Definition at line 12 of file util.h.
Referenced by hypro::ltiJumpHandler< State >::applyJump().
template<typename Number , typename Representation , typename... Rargs> State<Number, Representation, Rargs...> hypro::applyReset (const State< Number, Representation, Rargs... > & inState, const Reset< Number > & reset)
Definition at line 6 of file StateUtil.h.
References hypro::Reset< Number >::empty(), hypro::Reset< Number >::getAffineReset(), hypro::Reset< Number >::getIntervalReset(), and hypro::Reset< Number >::size().
Referenced by hypro::ltiJumpHandler< State >::applyJump().
template<typename Enumeration > auto hypro::as_integer (Enumeration const value) -> typename std::underlying_type<Enumeration>::type
Definition at line 31 of file convenienceOperators.h.
Referenced by operator<<().
hypro::BETTER_ENUM (boxSetting_name , int , BoxLinearOptimizationOn , BoxLinearOptimizationOff , BoxIntervalArithmeticOff , BoxAllOff)
Definition at line 7 of file BoxSetting.h.
hypro::BETTER_ENUM (supportFunctionSetting_name , int , SupportFunctionSetting , NoBoxReduction , NoBoxDetection , NoTrafoReduction , NoReduction , PolytopeSupportFunctionSetting)
Definition at line 7 of file SupportFunctionSetting.h.
hypro::BETTER_ENUM (carlPolytopeSetting_name , int , CarlPolytopeSetting)
Definition at line 7 of file carlPolytopeSetting.h.
hypro::BETTER_ENUM (hPolytopeSetting_name , int , HPolytopeSetting , HPolytopeOptimizerCaching)
Definition at line 7 of file HPolytopeSetting.h.
hypro::BETTER_ENUM (sfnSetting_name , int , SupportFunctionNewDefault , SupportFunctionNewMorePrecision , SupportFunctionNewNoReduction , SupportFunctionNewLeGuernic)
Definition at line 8 of file SupportFunctionNewSetting.h.
hypro::BETTER_ENUM (tpolySetting_name , int , TemplatePolyhedronDefault , OctagonShape)
Definition at line 8 of file TemplatePolyhedronSetting.h.
template<typename State > State hypro::bloatBox (const State & in, const hypro::Box< typename State::NumberType > & bloatBox, size_t index)
Definition at line 7 of file utility.h.
Referenced by hypro::ltiFirstSegmentHandler< State >::operator()().
SOLUTION hypro::clpCheckConsistency (clp_context & context)
Definition at line 9 of file adaptions_clp.cpp.
Referenced by hypro::Optimizer< Number >::checkConsistency().
template<typename Number > bool hypro::clpCheckPoint (clp_context & context, const matrix_t< Number > & constraints, const vector_t< Number > & constants, const Point< Number > & _point)
Definition at line 37 of file adaptions_clp.tpp.
Referenced by hypro::Optimizer< Number >::checkPoint().
template<typename Number > EvaluationResult< Number > hypro::clpGetInternalPoint (clp_context & context)
Definition at line 45 of file adaptions_clp.tpp.
template<typename Number > EvaluationResult< Number > hypro::clpOptimizeLinear (clp_context & context, const vector_t< Number > & _direction, const matrix_t< Number > & constraints, const vector_t< Number > & constants, bool useExact)
Definition at line 10 of file adaptions_clp.tpp.
References INFEAS, hypro::clp_context::lp, hypro::clp_context::matrix, hypro::clp_context::mLowerBounds, hypro::clp_context::mUpperBounds, and hypro::EvaluationResult< Number >::optimumValue.
Referenced by hypro::Optimizer< Number >::evaluate().
template<typename Number > std::vector< std::size_t > hypro::clpRedundantConstraints (clp_context & context, const matrix_t< Number > & constraints, const vector_t< Number > & constants)
Definition at line 41 of file adaptions_clp.tpp.
Referenced by hypro::Optimizer< Number >::redundantConstraints().
template<typename State > void hypro::collectTimespansForRefinementLevel (std::vector< carl::Interval< tNumber >> & timespans, typename ReachTreeNode< State >::NodeList_t & nodes, unsigned targetLevel) inline
Definition at line 25 of file util.h.
template<typename Number > Condition<Number> hypro::combine (const Condition< Number > & lhs, const Condition< Number > & rhs, const std::vector< std::string > haVar, const std::vector< std::string > lhsVar, const std::vector< std::string > rhsVar)
Definition at line 86 of file Condition.tpp.
References FALSE, hypro::ConstraintSetT< Number, S >::matrix(), NSET, selectCols(), selectRows(), hypro::Decomposition::size(), hypro::ConstraintSetT< Number, S >::size(), TRUE, and hypro::ConstraintSetT< Number, S >::vector().
Referenced by combine(), and selectCols().
template<typename Number > Reset< Number > hypro::combine (const Reset< Number > & lhs, const Reset< Number > & rhs, const std::vector< std::string > haVar, const std::vector< std::string > lhsVar, const std::vector< std::string > rhsVar)
Definition at line 100 of file Reset.tpp.
References combine(), hypro::Reset< Number >::getMatrix(), hypro::Reset< Number >::getVector(), hypro::Reset< Number >::setMatrix(), hypro::Reset< Number >::setVector(), and hypro::Reset< Number >::size().
template<typename Number > bool hypro::comparePoint (Eigen::Matrix< Number, 2, 1 > & p1, Eigen::Matrix< Number, 2, 1 > & p2)
Definition at line 12 of file Zonotope.tpp.
Referenced by intersectZonotopeHalfspaceDSearch().
template<typename Number > vector_t<Number> hypro::computeArithmeticMeanPoint (const std::vector< Point< Number >> & pointVec)
Definition at line 22 of file converterToZonotope.tpp.
Referenced by computeBoundaryPointsExpensiveRecursive(), and hypro::Converter< Number >::toZonotope().
template<typename Number , typename Converter , typename inSetting > std::vector<Point<Number> > hypro::computeBoundaryPointsExpensive (const SupportFunctionT< Number, Converter, inSetting > & sf, const matrix_t< Number > & directions)
Is the caller function for the recursive method that computes exactly one boundary point for each direction that it gets (via support function)
Definition at line 21 of file converterToVPolytope.tpp.
References computeBoundaryPointsExpensiveRecursive(), hypro::SupportFunctionT< Number, Converter, Setting >::contains(), hypro::SupportFunctionT< Number, Converter, Setting >::dimension(), hypro::EvaluationResult< Number >::errorCode, hypro::SupportFunctionT< Number, Converter, Setting >::evaluate(), INFEAS, INFTY, hypro::SupportFunctionT< Number, Converter, Setting >::intersect(), hypro::EvaluationResult< Number >::optimumValue, hypro::SupportFunctionT< Number, Converter, Setting >::print(), hypro::Point< Number >::removeDuplicatePoints(), hypro::EvaluationResult< Number >::supportValue, and UNKNOWN.
Referenced by hypro::Converter< Number >::toVPolytope().
template<typename Number , typename Converter , typename inSetting > std::vector<Point<Number> > hypro::computeBoundaryPointsExpensive (const SupportFunctionNewT< Number, Converter, inSetting > & sf, const matrix_t< Number > & directions)
Is the caller function for the recursive method that computes exactly one boundary point for each direction that it gets (via support function) Note that the next three functions are all copies of the functions above, but for SupportFunctionNews instead of SupportFunctions.
Definition at line 370 of file converterToVPolytope.tpp.
References computeBoundaryPointsExpensiveRecursive(), hypro::SupportFunctionNewT< Number, Converter, Setting >::contains(), hypro::SupportFunctionNewT< Number, Converter, Setting >::dimension(), hypro::EvaluationResult< Number >::errorCode, hypro::SupportFunctionNewT< Number, Converter, Setting >::evaluate(), INFEAS, INFTY, hypro::SupportFunctionNewT< Number, Converter, Setting >::intersect(), hypro::EvaluationResult< Number >::optimumValue, hypro::Point< Number >::removeDuplicatePoints(), hypro::EvaluationResult< Number >::supportValue, and UNKNOWN.
template<typename Number , typename Converter , typename inSetting > Point<Number> hypro::computeBoundaryPointsExpensiveRecursive (const SupportFunctionT< Number, Converter, inSetting > & sf, const matrix_t< Number > & directions, std::size_t curDim)
Definition at line 83 of file converterToVPolytope.tpp.
References computeArithmeticMeanPoint(), hypro::SupportFunctionT< Number, Converter, Setting >::contains(), hypro::SupportFunctionT< Number, Converter, Setting >::dimension(), hypro::EvaluationResult< Number >::errorCode, hypro::SupportFunctionT< Number, Converter, Setting >::evaluate(), INFEAS, INFTY, hypro::SupportFunctionT< Number, Converter, Setting >::intersect(), hypro::EvaluationResult< Number >::optimumValue, hypro::SupportFunctionT< Number, Converter, Setting >::print(), hypro::Point< Number >::removeDuplicatePoints(), hypro::EvaluationResult< Number >::supportValue, and UNKNOWN.
Referenced by computeBoundaryPointsExpensive(), and computeBoundaryPointsExpensiveRecursive().
template<typename Number , typename Converter , typename inSetting > Point<Number> hypro::computeBoundaryPointsExpensiveRecursive (const SupportFunctionNewT< Number, Converter, inSetting > & sf, const matrix_t< Number > & directions, std::size_t curDim)
Definition at line 433 of file converterToVPolytope.tpp.
References computeArithmeticMeanPoint(), computeBoundaryPointsExpensiveRecursive(), hypro::SupportFunctionNewT< Number, Converter, Setting >::contains(), hypro::SupportFunctionNewT< Number, Converter, Setting >::dimension(), hypro::EvaluationResult< Number >::errorCode, hypro::SupportFunctionNewT< Number, Converter, Setting >::evaluate(), INFEAS, INFTY, hypro::SupportFunctionNewT< Number, Converter, Setting >::intersect(), hypro::EvaluationResult< Number >::optimumValue, hypro::Point< Number >::removeDuplicatePoints(), hypro::EvaluationResult< Number >::supportValue, and UNKNOWN.
template<typename Number > int* hypro::computeDirectionMapping (std::vector< matrix_t< Number >> * directions)
Definition at line 98 of file helperMethods.h.
References contains().
template<typename N , typename D > std::vector<Halfspace<D> > hypro::computeHalfspaces (const FormulaT< N > & formula, std::size_t dim)
Definition at line 102 of file util.h.
template<typename Number > Eigen::Matrix<Number, 2, 1> hypro::computeLineIntersection (const ZUtility::Line_t< Number > & l1, const ZUtility::Line_t< Number > & l2)
Definition at line 56 of file Zonotope.tpp.
References hypro::ZUtility::Line_t< Number >::direction, and hypro::ZUtility::Line_t< Number >::point.
Referenced by intersectZonotopeHalfspaceDSearch().
template<typename N , typename D > D hypro::computeWidening (const ConstraintT< N > & constraint)
Definition at line 118 of file util.h.
template<typename N , typename D > vector_t<D> hypro::constraintNormal (const ConstraintT< N > & c, std::size_t dim)
Definition at line 49 of file util.h.
template<typename N > FormulasT<N> hypro::constraintsToFormulas (const std::vector< ConstraintT< N >> & in) inline
Definition at line 25 of file util.h.
References hypro::detail::for_each().
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::addConstraint(), hypro::CarlPolytopeT< Number, Converter, Setting >::addConstraints(), hypro::CarlPolytopeT< Number, Converter, Setting >::intersect(), and hypro::CarlPolytopeT< Number, Converter, Setting >::removeRedundancy().
template<typename N , typename D > std::vector<Halfspace<D> > hypro::constraintToHalfspace (const ConstraintT< N > & constraint, std::size_t dim)
Definition at line 82 of file util.h.
template<typename Number > bool hypro::contains (std::vector< matrix_t< Number >> list, matrix_t< Number > direction, unsigned int length)
Examples:
example_differenceBounds.cpp.
Definition at line 19 of file helperMethods.h.
Referenced by hypro::SupportFunctionNewT< Number, Converter, Setting >::assignIntervals(), CLANG_WARNING_DISABLE(), computeDirectionMapping(), contains(), hypro::BoxT< Number, Converter, Setting >::contains(), hypro::SupportFunctionContent< Number, Setting >::getThis(), main(), testContains(), and testContainsPoint().
template<typename Number > int hypro::contains (std::vector< matrix_t< Number >> * directions, matrix_t< Number > * direction)
Definition at line 54 of file helperMethods.h.
template<typename Number > int hypro::contains (std::vector< matrix_t< Number >> * directions, matrix_t< Number > direction)
Definition at line 90 of file helperMethods.h.
References contains().
template<typename Number , typename OutSettings , typename In > void hypro::convert (const In & in, BoxT< Number, Converter< Number >, OutSettings > & out)
Definition at line 6 of file conversionHelper.h.
template<typename From , typename To > carl::Interval<To> hypro::convert (const carl::Interval< From > & original)
Definition at line 6 of file conversion.h.
template<typename Number , typename OutSettings , typename In > void hypro::convert (const In & in, CarlPolytopeT< Number, Converter< Number >, OutSettings > & out)
Definition at line 11 of file conversionHelper.h.
template<typename Number , typename OutSettings , typename In > void hypro::convert (const In & in, ConstraintSetT< Number, OutSettings > & out)
Definition at line 16 of file conversionHelper.h.
template<typename Number , typename OutSettings , typename In > void hypro::convert (const In & in, DifferenceBoundsT< Number, Converter< Number >, OutSettings > & out)
Definition at line 21 of file conversionHelper.h.
template<typename Number , typename OutSettings , typename In > void hypro::convert (const In & in, HPolytopeT< Number, Converter< Number >, OutSettings > & out)
Definition at line 26 of file conversionHelper.h.
template<typename Number , typename OutSettings , typename In > void hypro::convert (const In & in, SupportFunctionT< Number, Converter< Number >, OutSettings > & out)
Definition at line 31 of file conversionHelper.h.
template<typename Number , typename OutSettings , typename In > void hypro::convert (const In & in, VPolytopeT< Number, Converter< Number >, OutSettings > & out)
Definition at line 36 of file conversionHelper.h.
template<typename Number , typename OutSettings , typename In > void hypro::convert (const In & in, ZonotopeT< Number, Converter< Number >, OutSettings > & out)
Definition at line 41 of file conversionHelper.h.
template<typename Number , typename OutSettings , typename In > void hypro::convert (const In & in, TemplatePolyhedronT< Number, Converter< Number >, OutSettings > & out)
Definition at line 46 of file conversionHelper.h.
template<typename Number , typename OutSettings , typename In > void hypro::convert (const In & in, SupportFunctionNewT< Number, Converter< Number >, OutSettings > & out)
Definition at line 56 of file conversionHelper.h.
template<typename Number , typename OutSettings , typename In > void hypro::convert (const In & in, PolytopeT< Number, Converter< Number >, OutSettings > & out)
Definition at line 62 of file conversionHelper.h.
template<typename From , typename To > matrix_t<To> hypro::convert (const matrix_t< From > & _mat)
conversion of a matrix_t
Definition at line 225 of file adaptions_eigen.h.
template<typename From , typename To > Eigen::DiagonalMatrix<To, Eigen::Dynamic> hypro::convert (const Eigen::DiagonalMatrix< From, Eigen::Dynamic > & _mat)
Definition at line 238 of file adaptions_eigen.h.
template<typename From , typename To , typename S > ConstraintSetT<To, S> hypro::convert (const ConstraintSetT< From, S > & in)
Conversion function for different number types.
Parameters
[in] in The input constraintSet.
Template Parameters
From The current number type.
To The number type the constraintSet is to be converted to.
Converter The passed representation converter.
Returns
The resulting constraintSet.
Definition at line 291 of file ConstraintSet.h.
References hypro::ConstraintSetT< Number, S >::matrix(), and hypro::ConstraintSetT< Number, S >::vector().
template<typename From , typename To > Halfspace<To> hypro::convert (const Halfspace< From > & in)
Conversion operator for the number type.
Parameters
[in] in The plane to convert
Template Parameters
From The original number type.
To The target number type.
Returns
A halfspace in the desired number type.
Definition at line 360 of file Halfspace.h.
References hypro::Halfspace< Number >::normal(), and hypro::Halfspace< Number >::offset().
Referenced by hypro::reachability::detail::bloatBoxVisitor< VariantType, Number >::operator()().
template<typename From , typename To , typename Converter , typename S > VPolytopeT<To, Converter, S> hypro::convert (const VPolytopeT< From, Converter, S > & in)
Definition at line 401 of file VPolytope.h.
References hypro::VPolytopeT< Number, Converter, S >::vertices().
template<typename From , typename To , typename Converter , class Setting > HPolytopeT<To, Converter, Setting> hypro::convert (const HPolytopeT< From, Converter, Setting > & in)
Definition at line 451 of file HPolytope.h.
References hypro::HPolytopeT< Number, Converter, Setting >::matrix(), and hypro::HPolytopeT< Number, Converter, Setting >::vector().
template<typename From , typename To , typename Converter , class Setting > BoxT<To, Converter, Setting> hypro::convert (const BoxT< From, Converter, Setting > & in)
Conversion function for different number types.
Parameters
[in] in The input box.
Template Parameters
From The current number type.
To The number type the box is to be converted to.
Converter The passed representation converter.
Returns
The resulting box.
Definition at line 607 of file Box.h.
References hypro::BoxT< Number, Converter, Setting >::limits().
template<typename From , typename To > Point<To> hypro::convert (const Point< From > & in)
Conversion operator for the number type.
Parameters
[in] in The point.
Template Parameters
From The original number type.
To The target number type.
Returns
A point in the targeted number type.
Definition at line 672 of file Point.h.
References hypro::Point< Number >::rawCoordinates().
template<typename Number , typename Converter , typename Setting , typename SettingRhs , carl::DisableIf< std::is_same< Setting, SettingRhs >> = carl::dummy> std::shared_ptr<RootGrowNode<Number, Converter, Setting> > hypro::convertSettings (const RootGrowNode< Number, Converter, SettingRhs > * in)
Definition at line 191 of file RootGrowNode.h.
References hypro::RootGrowNode< Number, Converter, Setting >::getData(), hypro::RootGrowNode< Number, Converter, Setting >::getLeafData(), hypro::RootGrowNode< Number, Converter, Setting >::getType(), INTERSECTHSPACEOP, INTERSECTOP, LEAF, NODE, project(), PROJECTOP, SCALEOP, SUMOP, TRAFO, hypro::LeafData::typeOfRep, and UNIONOP.
template<typename Number > std::string hypro::createCode (const matrix_t< Number > & in, unsigned index = 0)
Definition at line 347 of file adaptions_eigen.h.
template<typename Number > std::string hypro::createCode (const vector_t< Number > & in, unsigned index = 0)
Definition at line 381 of file adaptions_eigen.h.
template<typename N , typename D > std::vector<ConstraintT<N> > hypro::createFlowConstraints (carl::Variable original, carl::Variable primed, carl::Variable t, const carl::Interval< D > & flow)
Definition at line 8 of file rectangularOperations.h.
template<template< typename, typename > typename Rep, typename Number , typename Settings > void hypro::decomposeConstraintSet (Rep< Number, Settings > & in, const Decomposition & decomposition, std::vector< Rep< Number, Settings >> & result)
Definition at line 8 of file decomposeConstraintSet.h.
template<typename Number > matrix_t<Number> hypro::directionList2Matrix (std::vector< matrix_t< Number >> * list)
Converts a list of directions into a matrix containing directions
Definition at line 139 of file helperMethods.h.
template<typename Number , typename Converter , typename Callable , typename... Args> auto hypro::dispatch (representation_name representation, int setting, Callable func, Args &&... args)
Definition at line 7 of file dispatch.h.
template<typename Number , typename Converter , typename Callable , typename... Args> auto hypro::dispatch (representation_name representation, int setting, Callable func, Args... args)
Example usage: see example_dispatch.cpp
Definition at line 16 of file dispatch_manual.h.
template<typename Number > int hypro::effectiveDimension (const std::vector< vector_t< Number >> & vertices)
Definition at line 276 of file adaptions_eigen.h.
template<typename Number > int hypro::effectiveDimension (const std::vector< Point< Number >> & vertices)
Determines the dimension of the affine space spanned by the given set of points.
Parameters
[in] vertices The set of points.
Template Parameters
Number The number type.
Returns
The spanned dimension.
Definition at line 623 of file Point.h.
Referenced by hypro::VPolytopeT< Number, Converter, S >::contains(), hypro::HPolytopeT< Number, Converter, Setting >::HPolytopeT(), hypro::PolytopeSupportFunction< Number, Setting >::PolytopeSupportFunction(), and hypro::VPolytopeT< Number, Converter, S >::unite().
template<typename Number > int hypro::effectiveDimension (const std::set< Point< Number >> & vertices)
Determines the dimension of the affine space spanned by the given set of points.
Parameters
[in] vertices The set of points.
Template Parameters
Number The number type.
Returns
The spanned dimension.
Definition at line 647 of file Point.h.
template<typename Number > FormulaT<Number> hypro::eliminateQuantifiers (const FormulaT< Number > & qfree, const QEQuery & quantifiers)
Definition at line 9 of file qe.h.
References hypro::FourierMotzkinQE< Number >::eliminateQuantifiers().
Referenced by hypro::CarlPolytopeT< Number, Converter, Setting >::eliminateVariable(), and hypro::CarlPolytopeT< Number, Converter, Setting >::eliminateVariables().
template<typename Number , typename State > std::vector<Box<Number> > hypro::errorBoxes (const Number & delta, const linearFlow< Number > & flow, const State & initialSet, const matrix_t< Number > & trafoMatrix, const Box< Number > & externalInput)
Definition at line 75 of file util.h.
References hypro::linearFlow< Number >::dimension(), and hypro::linearFlow< Number >::getFlowMatrix().
Referenced by hypro::reachability::computeFirstSegment(), and hypro::ltiFirstSegmentHandler< State >::operator()().
template<typename Number > EvaluationResult<Number> hypro::extractSolution (smtrat::SimplexSolver & solver, const smtrat::Poly & objective, unsigned dimension)
Definition at line 32 of file helper_methods.h.
References FEAS, and INFTY.
bool hypro::file_exists (const std::string & filename) inline
Definition at line 21 of file PlotterUtil.h.
Referenced by hypro::Plotter< Number >::plot2d().
template<typename... Ts, typename F > std::tuple<Ts...> hypro::for_each_in_tuple (std::tuple< Ts... > const & t, F f)
Definition at line 37 of file for_each.h.
References hypro::detail::for_each().
template<typename... Ts, typename F > std::tuple<Ts...> hypro::for_each_in_tuple (std::tuple< Ts... > const & t1, std::tuple< Ts... > const & t2, F f)
Definition at line 48 of file for_each.h.
References hypro::detail::for_each().
template<typename... Ts, typename F > std::tuple<std::pair<bool, Ts...> > hypro::for_each_in_tuple_pair (std::tuple< Ts... > const & t, F f)
Definition at line 42 of file for_each.h.
References hypro::detail::for_each().
std::vector< carl::Interval< tNumber > > hypro::getEnabledTimings (const HierarchicalIntervalVector< CONTAINMENT, tNumber > & in)
Definition at line 5 of file ETC_util.cpp.
References hypro::HierarchicalIntervalVector< T, Number >::begin(), and hypro::HierarchicalIntervalVector< T, Number >::end().
template<typename T > std::size_t hypro::getFlowDimension (const T & f)
Definition at line 17 of file operations.h.
template<typename T > DynamicType hypro::getFlowType (const T & f)
Definition at line 12 of file operations.h.
Referenced by hypro::LTIContext< State >::initializeBadStateHandlers(), hypro::RectangularContext< State >::initializeBadStateHandlers(), hypro::RectangularContext< State >::initializeGuardHandlers(), hypro::LTIContext< State >::initializeGuardHandlers(), hypro::RectangularContext< State >::initializeInvariantHandlers(), hypro::LTIContext< State >::initializeInvariantHandlers(), and toFlowstarFormat().
template<typename Number > bool hypro::glpkCheckPoint (glpk_context & context, const matrix_t< Number > & constraints, const vector_t< Number > & , const Point< Number > & point)
Definition at line 111 of file adaptions_glpk.tpp.
References hypro::glpk_context::lp, hypro::glpk_context::parm, and hypro::Point< Number >::rawCoordinates().
Referenced by hypro::Optimizer< Number >::checkPoint().
template<> bool hypro::glpkCheckPoint (glpk_context & context, const matrix_t< double > & constraints, const vector_t< double > & , const Point< double > & point)
Definition at line 53 of file adaptions_glpk_double.cpp.
References hypro::glpk_context::lp, hypro::glpk_context::parm, and hypro::Point< Number >::rawCoordinates().
template<typename Number > EvaluationResult< Number > hypro::glpkGetInternalPoint (glpk_context & context, std::size_t dimension, bool useExact)
Definition at line 174 of file adaptions_glpk.tpp.
References FEAS, INFEAS, INFTY, hypro::glpk_context::lp, and hypro::glpk_context::parm.
template<typename Number > EvaluationResult< Number > hypro::glpkOptimizeLinear (glpk_context & context, const vector_t< Number > & _direction, const matrix_t< Number > & constraints, const vector_t< Number > & constants, bool useExact)
Definition at line 69 of file adaptions_glpk.tpp.
References FEAS, INFEAS, INFTY, hypro::glpk_context::lp, hypro::glpk_context::parm, and refineSolution().
Referenced by hypro::Optimizer< Number >::evaluate(), and glpkRedundantConstraints().
template<> EvaluationResult< double > hypro::glpkOptimizeLinear (glpk_context & context, const vector_t< double > & _direction, const matrix_t< double > & constraints, const vector_t< double > & constants, bool useExact)
Definition at line 6 of file adaptions_glpk_double.cpp.
References FEAS, INFEAS, INFTY, hypro::glpk_context::lp, and hypro::glpk_context::parm.
template<typename Number > std::vector< std::size_t > hypro::glpkRedundantConstraints (glpk_context & context, matrix_t< Number > constraints, vector_t< Number > constants)
Definition at line 124 of file adaptions_glpk.tpp.
References hypro::EvaluationResult< Number >::errorCode, glpkOptimizeLinear(), hypro::glpk_context::lp, hypro::glpk_context::parm, and hypro::EvaluationResult< Number >::supportValue.
Referenced by hypro::Optimizer< Number >::redundantConstraints().
template<> std::vector< std::size_t > hypro::glpkRedundantConstraints (glpk_context & context, matrix_t< double > constraints, vector_t< double > constants)
Definition at line 65 of file adaptions_glpk_double.cpp.
References hypro::EvaluationResult< Number >::errorCode, glpkOptimizeLinear(), hypro::glpk_context::lp, hypro::glpk_context::parm, and hypro::EvaluationResult< Number >::supportValue.
template<typename N , typename D > FormulasT<N> hypro::halfspacesToConstraints (const matrix_t< D > & constraints, const vector_t< D > & constants) inline
Definition at line 9 of file util.h.
template<typename Number > Number hypro::hausdorffError (const Number & delta, const matrix_t< Number > & matrix, const Number & _supremum)
Definition at line 57 of file util.h.
std::vector< std::size_t > hypro::HEXtoRGB (std::size_t color)
Definition at line 5 of file PlotterUtil.cpp.
Referenced by adjustSaturation().
std::vector< std::size_t > hypro::HSVtoRGB (const std::vector< double > & color)
Definition at line 68 of file PlotterUtil.cpp.
Referenced by adjustSaturation().
template<typename Number > bool hypro::icpIntersectHalfspace (std::vector< carl::Interval< Number >> & intervals, const Halfspace< Number > & hsp)
Performs intersection of a vector of intervals with a halfspace.
The idea is to use ICP-style contractions to obtain the resulting box. As we know the constraint (the halfspace) is linear, we only need to perform one contraction per dimension and the order does not matter.
Parameters
intervals The intervals as a vector (call by reference).
[in] hsp The halfspace
Template Parameters
Number The used number type.
Returns
True, if one of the resulting intervals is empty, False otherwise.
Definition at line 22 of file intervalMethods.h.
References hypro::Halfspace< Number >::normal(), and hypro::Halfspace< Number >::offset().
Referenced by hypro::BoxT< Number, Converter, Setting >::intersectHalfspace(), hypro::BoxT< Number, Converter, Setting >::intersectHalfspaces(), and main().
int hypro::initializeLogging (int & i)
Definition at line 6 of file Logger.cpp.
template<typename State > void hypro::insertAndCreateTask (typename ReachTreeNode< State >::NodeList_t & toInsert, const std::shared_ptr< Task< State >> & currentTask, WorkQueue< std::shared_ptr< Task< State >>> * localQueue, WorkQueue< std::shared_ptr< Task< State >>> * localCEXQueue, std::size_t targetLevel) inline
Definition at line 211 of file util.h.
References hypro::TreeNode< ReachTreeNode< State > >::addChild(), and hypro::SettingsProvider< State >::getStrategy().
template<typename Number , typename Converter , typename Setting > Number hypro::intersect2d (const ZonotopeT< Number, Converter, Setting > & input, const Halfspace< Number > & hp, int minOrMax)
Definition at line 507 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::center(), hypro::Halfspace< Number >::dimension(), hypro::ZonotopeT< Number, Converter, Setting >::dimension(), hypro::ZonotopeT< Number, Converter, Setting >::generators(), hypro::Halfspace< Number >::offset(), and hypro::ZonotopeT< Number, Converter, Setting >::size().
template<typename Number , typename Converter , typename Setting > ZonotopeT<Number, Converter, Setting> hypro::intersectAlamo (const ZonotopeT< Number, Converter, Setting > & inputZonotope, const Halfspace< Number > & hp)
Definition at line 748 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::center(), hypro::Halfspace< Number >::dimension(), hypro::ZonotopeT< Number, Converter, Setting >::dimension(), hypro::ZonotopeT< Number, Converter, Setting >::generators(), hypro::Halfspace< Number >::normal(), hypro::Halfspace< Number >::offset(), and hypro::ZonotopeT< Number, Converter, Setting >::setCenter().
Referenced by hypro::ZonotopeT< Number, Converter, Setting >::intersect().
template<typename Number , typename Converter , typename Setting > ZonotopeT<Number, Converter, Setting> hypro::intersectNDProjection (const ZonotopeT< Number, Converter, Setting > & inputZonotope, const Halfspace< Number > & hp, matrix_t< Number > & minMaxOfLine)
Definition at line 774 of file Zonotope.tpp.
References hypro::ZonotopeT< Number, Converter, Setting >::center(), hypro::Halfspace< Number >::dimension(), hypro::ZonotopeT< Number, Converter, Setting >::dimension(), hypro::ZonotopeT< Number, Converter, Setting >::generators(), intersectZonotopeHalfspaceDSearch(), hypro::Halfspace< Number >::normal(), and hypro::Halfspace< Number >::offset().
template<typename Number , typename Converter , typename Setting > ZonotopeT<Number, Converter, Setting> hypro::intersectZonotopeHalfspaceDSearch (const ZonotopeT< Number, Converter, Setting > & inputZonotope, const Halfspace< Number > & hp)
Definition at line 621 of file Zonotope.tpp.
References comparePoint(), computeLineIntersection(), hypro::ZonotopeT< Number, Converter, Setting >::computeZonotopeBoundary(), hypro::Halfspace< Number >::dimension(), hypro::ZonotopeT< Number, Converter, Setting >::dimension(), hypro::ZUtility::Line_t< Number >::direction, hypro::Halfspace< Number >::normal(), hypro::Halfspace< Number >::offset(), hypro::ZUtility::Line_t< Number >::point, and hypro::ZonotopeT< Number, Converter, Setting >::vertices().
Referenced by intersectNDProjection().
template<typename N , typename D > FormulasT<N> hypro::intervalToFormulas (const carl::Interval< D > & interval, const carl::Variable & var)
Definition at line 32 of file util.h.
template<typename N , typename D > FormulasT<N> hypro::intervalToFormulas (const carl::Interval< D > & interval, std::size_t variableIndex)
Definition at line 43 of file util.h.
template<typename Number > std::tuple<bool, std::vector<carl::Interval<Number> > > hypro::isBox (const matrix_t< Number > & constraints, const vector_t< Number > & constants)
Determines if a constraint set represented by a matrix and a vector in fact defines a box.
Uses simple checks to syntactically detect a box-description via half-spaces. This can be used, to use a box-representation instead of a H-Polytope representation, if desired.
Parameters
[in] constraints The constraints.
[in] constants The constants.
Template Parameters
Number The used number type.
Returns
True if box, False otherwise.
Definition at line 18 of file isBox.h.
Referenced by hypro::ltiJumpHandler< State >::applyReduction(), hypro::BoxT< Number, Converter, Setting >::BoxT(), hypro::ConstraintSetT< Number >::isAxisAligned(), hypro::SupportFunctionNewT< Number, Converter, Setting >::SupportFunctionNewT(), and hypro::Converter< Number >::toBox().
template<typename T > bool hypro::isDiscrete (const T & f)
Definition at line 33 of file operations.h.
References discrete.
Referenced by hypro::LTIContext< State >::initializeBadStateHandlers(), hypro::LTIContext< State >::initializeGuardHandlers(), and hypro::LTIContext< State >::initializeInvariantHandlers().
template<typename T > bool hypro::isTimed (const T & f)
Definition at line 22 of file operations.h.
References timed.
Referenced by hypro::DecisionEntity< Number >::getRepresentationForAutomaton(), hypro::DecisionEntity< Number >::getRepresentationForLocation(), hypro::DecisionEntity< Number >::getRepresentationForSubspace(), and hypro::DecisionEntity< Number >::isTimedSubspace().
template<typename State > bool hypro::isTreeExtension (typename ReachTreeNode< State >::Node_t node, Transition< typename State::NumberType > * transition)
Definition at line 8 of file util.h.
References hypro::TreeNode< ReachTreeNode< State > >::getChildren(), and hypro::ReachTreeNode< State >::getChildrenForTransition().
template<> std::pair<bool, double> hypro::linearDependent (const vector_t< double > & lhs, const vector_t< double > & rhs) inline
Definition at line 94 of file adaptions_eigen_double.cpp.
template<typename Number > std::pair<bool, Number> hypro::linearDependent (const vector_t< Number > & lhs, const vector_t< Number > & rhs) inline
Definition at line 294 of file adaptions_eigen.h.
Referenced by hypro::Optimizer< Number >::evaluate(), hypro::Halfspace< Number >::evaluate(), hypro::PolytopeSupportFunction< Number, Setting >::multiEvaluate(), hypro::Halfspace< Number >::multiEvaluate(), and hypro::ZonotopeT< Number, Converter, Setting >::uniteEqualVectors().
template<typename Number > matrix_t<Number>* hypro::list2Array (std::vector< matrix_t< Number >> * list)
Definition at line 174 of file helperMethods.h.
template<typename Number > bool hypro::listContains (std::vector< Number > * list, Number item)
Definition at line 126 of file helperMethods.h.
template<typename State , typename Number > State hypro::ltiApplyTimeEvolution (const State & currentSegment, const matrix_t< Number > & transformation, const vector_t< Number > & translation, tNumber timeStepSize)
Definition at line 5 of file ltiTimeEvolutionHandler.tpp.
Referenced by hypro::LTIWorker< State >::computeTimeSuccessors().
template<typename State > std::pair< CONTAINMENT, State > hypro::ltiIntersectBadStates (const State & stateSet, const HybridAutomaton< typename State::NumberType > & automaton)
Definition at line 6 of file ltiBadStateHandler.tpp.
References hypro::HybridAutomaton< Number >::getGlobalBadStates(), hypro::HybridAutomaton< Number >::getLocalBadStates(), and NO.
Referenced by hypro::LTIWorker< State >::computeTimeSuccessors().
template<typename State > std::pair<CONTAINMENT, State> hypro::ltiIntersectBadStates (const State & stateSet, const Condition< typename State::Number > & localBadState, const std::vector< Condition< typename State::Number >> & globalBadStates)
template<typename State > std::pair<CONTAINMENT, State> hypro::ltiIntersectBadStates (const State & stateSet, const Condition< typename State::NumberType > & localBadState, const std::vector< Condition< typename State::NumberType >> & globalBadStates)
Definition at line 30 of file ltiBadStateHandler.tpp.
References NO.
template<typename State > std::pair< CONTAINMENT, State > hypro::ltiIntersectInvariant (const State & stateSet)
Definition at line 5 of file ltiInvariantHandler.tpp.
Referenced by hypro::ltiJumpHandler< State >::applyJump(), and hypro::LTIWorker< State >::computeTimeSuccessors().
template<typename... T> auto hypro::make_vector (T &&... args)
Definition at line 7 of file make_vector.h.
template<typename Number > Number* hypro::matrix2Array (matrix_t< Number > m)
Definition at line 189 of file helperMethods.h.
template<typename Number > matrix_t<Number> hypro::matrixExponential (const matrix_t< Number > & inMatrix)
Computes the matrix exponential via conversion to double and then using eigen::exp.
Template Parameters
Number The used number representation.
Parameters
inMatrix Matrix describing the system of linear ODEs.
Returns
matrix_t<Number> Matrix exponential of inMatrix.
Definition at line 372 of file adaptions_eigen.h.
Referenced by hypro::reachability::computeTrafoMatrix().
template<typename Number > vector_t<Number> hypro::normalize (const vector_t< Number > & in)
Definition at line 249 of file adaptions_eigen.h.
Referenced by hypro::BallSupportFunction< Number >::evaluate(), and hypro::BallSupportFunction< Number >::multiEvaluate().
template<typename N , typename D > D hypro::normalizedOffset (const ConstraintT< N > & c)
Definition at line 72 of file util.h.
template<typename N > std::size_t hypro::numberOfPointsInHalfspace (const std::vector< Point< N >> & points, const Halfspace< N > & hsp)
Definition at line 8 of file util.h.
References hypro::Halfspace< Number >::contains().
Referenced by hypro::VPolytopeT< Number, Converter, S >::satisfiesHalfspace(), and hypro::VPolytopeT< Number, Converter, S >::satisfiesHalfspaces().
void hypro::openFile (const std::string & filename, ANTLRInputStream & input)
Definition at line 19 of file ParserWrapper.cpp.
Referenced by parseFlowstarFile< double >(), and parseFlowstarFile< mpq_class >().
template<typename Number , typename Converter , class Setting > bool hypro::operator!= (const PolytopeT< Number, Converter, Setting > & rhs, const PolytopeT< Number, Converter, Setting > & lhs)
Definition at line 767 of file Polytope.tpp.
References hypro::Point< Number >::coordinates(), hypro::Point< Number >::dimension(), EPSILON, hypro::Point< Number >::extAdd(), hypro::Halfspace< Number >::normal(), and hypro::Halfspace< Number >::offset().
template<typename Number , typename Converter , class Setting > BoxT<Number, Converter, Setting> hypro::operator* (Number factor, const BoxT< Number, Converter, Setting > & in)
Operator for scaling a box.
Parameters
[in] factor The scaling factor.
[in] in The box which is to be scaled.
Template Parameters
Number The number type.
Converter The passed representation converter.
Returns
The resulting box.
Definition at line 591 of file Box.h.
References hypro::BoxT< Number, Converter, Setting >::empty().
template<typename Number > Number hypro::operator* (const Point< Number > & _lhs, const Point< Number > & _rhs)
Arithmetic operator returning a new point.
Parameters
[in] _lhs The left hand side.
[in] _rhs The right hand side.
Template Parameters
Number The number type.
Returns
The resulting point.
Definition at line 596 of file Point.h.
References hypro::Point< Number >::rawCoordinates().
template<typename Number > const Point<Number> hypro::operator* (const Point< Number > & _lhs, const Number & _factor)
Arithmetic operator returning a new point.
Parameters
[in] _lhs The left hand side.
[in] _rhs The right hand side.
Template Parameters
Number The number type.
Returns
The resulting point.
Definition at line 603 of file Point.h.
References hypro::Point< Number >::dimension(), and hypro::Point< Number >::rawCoordinates().
template<typename Number > const Point<Number> hypro::operator* (const Number & _factor, const Point< Number > & _rhs)
Arithmetic operator returning a new point.
Parameters
[in] _lhs The left hand side.
[in] _rhs The right hand side.
Template Parameters
Number The number type.
Returns
The resulting point.
Definition at line 611 of file Point.h.
template<typename Number > const Point<Number> hypro::operator+ (const Point< Number > & _lhs, const Point< Number > & _rhs)
Arithmetic operator returning a new point.
Parameters
[in] _lhs The left hand side.
[in] _rhs The right hand side.
Template Parameters
Number The number type.
Returns
The resulting point.
Definition at line 559 of file Point.h.
References hypro::Point< Number >::dimension(), and hypro::Point< Number >::rawCoordinates().
template<typename Number > const Point<Number> hypro::operator+ (const Point< Number > & _lhs, const vector_t< Number > & _rhs)
Arithmetic operator returning a new point.
Parameters
[in] _lhs The left hand side.
[in] _rhs The right hand side.
Template Parameters
Number The number type.
Returns
The resulting point.
Definition at line 569 of file Point.h.
References hypro::Point< Number >::dimension(), and hypro::Point< Number >::rawCoordinates().
template<typename Number > Halfspace<Number> hypro::operator- (const Halfspace< Number > & _in)
Operator unary minus.
Used to invert the halfspace.
Parameters
[in] _in The halfspace.
Template Parameters
Number The number type.
Returns
The inverted halfspace.
Definition at line 411 of file Halfspace.h.
References hypro::Halfspace< Number >::invert().
template<typename Number > const Point<Number> hypro::operator- (const Point< Number > & _lhs, const Point< Number > & _rhs)
Arithmetic operator returning a new point.
Parameters
[in] _lhs The left hand side.
[in] _rhs The right hand side.
Template Parameters
Number The number type.
Returns
The resulting point.
Definition at line 578 of file Point.h.
References hypro::Point< Number >::dimension(), and hypro::Point< Number >::rawCoordinates().
template<typename Number > const Point<Number> hypro::operator/ (const Point< Number > & _lhs, unsigned _quotient)
Arithmetic operator returning a new point.
Parameters
[in] _lhs The left hand side.
[in] _rhs The right hand side.
Template Parameters
Number The number type.
Returns
The resulting point.
Definition at line 588 of file Point.h.
References hypro::Point< Number >::dimension(), and hypro::Point< Number >::rawCoordinates().
template<typename Number > bool hypro::operator< (std::shared_ptr< Halfspace< Number >> _lhs, std::shared_ptr< Halfspace< Number >> _rhs)
Definition at line 17 of file Cone.h.
template<typename Number > bool hypro::operator< (const EvaluationResult< Number > & lhs, const EvaluationResult< Number > & rhs)
Definition at line 52 of file EvaluationResult.h.
References INFEAS, INFTY, and hypro::EvaluationResult< Number >::supportValue.
template<typename S > bool hypro::operator< (const ReachTreeNode< S > & lhs, const ReachTreeNode< S > & rhs)
Definition at line 381 of file ReachTreeNode.tpp.
template<typename Number > bool hypro::operator< (const Halfspace< Number > & lhs, const Halfspace< Number > & rhs)
Operator less.
Note that this operator uses SOME comparison (dimension wise) without any meaning. Only used for STL containers.
Parameters
[in] lhs The left hand side.
[in] rhs The right hand side.
Template Parameters
Number The number type.
Returns
True, if lhs < rhs according to the normal vector and the scalar, false otherwise.
Definition at line 399 of file Halfspace.h.
template<typename Enumeration , carl::EnableIf< std::is_enum< Enumeration >> = carl::dummy> std::ostream& hypro::operator<< (std::ostream & out, Enumeration in)
Definition at line 37 of file convenienceOperators.h.
References as_integer().
template<typename T > std::ostream& hypro::operator<< (std::ostream & _out, const std::set< T > & _set)
Definition at line 43 of file convenienceOperators.h.
template<typename T > std::ostream& hypro::operator<< (std::ostream & _out, const std::vector< T > & _vector)
Definition at line 55 of file convenienceOperators.h.
template<typename Number > std::ostream& hypro::operator<< (std::ostream & _out, Cone< Number > & _cone)
Definition at line 61 of file Cone.h.
template<typename T > std::ostream& hypro::operator<< (std::ostream & _out, const std::pair< T, T > & _pair)
Definition at line 67 of file convenienceOperators.h.
template<typename Key , typename T > std::ostream& hypro::operator<< (std::ostream & _out, const std::map< Key, T > & _map)
Definition at line 74 of file convenienceOperators.h.
template<typename Number > std::ostream& hypro::operator<< (std::ostream & _ostr, const Ridge< Number > & _f)
Definition at line 83 of file Ridge.h.
template<typename Number , typename Converter , typename Setting > std::ostream& hypro::operator<< (std::ostream & out, const ZonotopeT< Number, Converter, Setting > & in)
Definition at line 321 of file Zonotope.h.
template<typename State > std::ostream& hypro::operator<< (std::ostream & out, const ReachTreeNode< State > & reachTreeNode)
Definition at line 372 of file ReachTreeNode.tpp.
template<typename Number > std::ostream& hypro::operator<< (std::ostream & _lhs, const Halfspace< Number > & _rhs)
Outstream operator.
Parameters
_lhs The outstream.
[in] _rhs The halfspace.
Template Parameters
Number The number type of the halfspace.
Returns
A reference to the outstream.
Definition at line 372 of file Halfspace.h.
template<typename Number , typename Converter , typename S > std::ostream& hypro::operator<< (std::ostream & out, const hypro::VPolytopeT< Number, Converter, S > & lhs)
Definition at line 391 of file VPolytope.h.
References hypro::VPolytopeT< Number, Converter, S >::vector().
template<typename Number > std::ostream& hypro::operator<< (std::ostream & _ostr, const Facet< Number > & _f)
Definition at line 444 of file Facet.h.
template<typename N > std::ostream& hypro::operator<< (std::ostream & os, const TaylorModel< N > & tm)
Definition at line 757 of file TaylorModel.tpp.
template<typename N > std::ostream& hypro::operator<< (std::ostream & os, const Domain< N > & domain)
Definition at line 820 of file TaylorModel.tpp.
template<typename N > std::ostream& hypro::operator<< (std::ostream & os, const PolynomialODE< N > & ode)
Definition at line 881 of file TaylorModel.tpp.
template<typename N > std::ostream& hypro::operator<< (std::ostream & os, const Range< N > & range)
Definition at line 950 of file TaylorModel.tpp.
template<typename N > std::ostream& hypro::operator<< (std::ostream & os, const TaylorModelVec< N > & tmv)
Definition at line 1334 of file TaylorModel.tpp.
template<typename Number > bool hypro::operator== (const EvaluationResult< Number > & lhs, const EvaluationResult< Number > & rhs)
Definition at line 76 of file EvaluationResult.h.
References hypro::EvaluationResult< Number >::errorCode, hypro::EvaluationResult< Number >::optimumValue, and hypro::EvaluationResult< Number >::supportValue.
template<typename Number , typename State > bool hypro::operator== (const std::shared_ptr< Task< State >> & lhs, const std::shared_ptr< Task< State >> & rhs)
Definition at line 113 of file Task.h.
template<typename Number > bool hypro::operator== (const Halfspace< Number > & lhs, const Halfspace< Number > & rhs)
Comparison operator.
Parameters
[in] lhs The left hand side.
[in] rhs The right hand side.
Template Parameters
Number The number type.
Returns
True, if both halfspaces are equal in terms of coefficients, false otherwise.
Definition at line 385 of file Halfspace.h.
References hypro::Halfspace< Number >::normal(), and hypro::Halfspace< Number >::offset().
template<typename S > bool hypro::operator== (const ReachTreeNode< S > & lhs, const ReachTreeNode< S > & rhs)
Definition at line 386 of file ReachTreeNode.tpp.
References hypro::TreeNode< ReachTreeNode< State > >::mChildren, hypro::TreeNode< ReachTreeNode< State > >::mDepth, hypro::TreeNode< ReachTreeNode< State > >::mParent, hypro::ReachTreeNode< State >::mPath, and hypro::ReachTreeNode< State >::mRefinements.
template<typename Number , typename Converter , class Setting > bool hypro::operator== (const PolytopeT< Number, Converter, Setting > & rhs, const PolytopeT< Number, Converter, Setting > & lhs)
Definition at line 763 of file Polytope.tpp.
template<typename Number > bool hypro::operator> (const EvaluationResult< Number > & lhs, const EvaluationResult< Number > & rhs)
Definition at line 71 of file EvaluationResult.h.
Referenced by hypro::Path< Number, tNumber >::getTransitionSequence().
template<typename Number > HybridAutomaton<Number> hypro::operator|| (const HybridAutomaton< Number > & lhs, const HybridAutomaton< Number > & rhs)
Definition at line 312 of file HybridAutomaton.tpp.
References hypro::HybridAutomaton< Number >::addLocation(), hypro::HybridAutomaton< Number >::addTransition(), hypro::HybridAutomaton< Number >::getInitialStates(), hypro::HybridAutomaton< Number >::getLabels(), hypro::HybridAutomaton< Number >::getLocations(), hypro::HybridAutomaton< Number >::getTransitions(), hypro::HybridAutomaton< Number >::getVariables(), hypro::HybridAutomaton< Number >::reduce(), hypro::Reset< Number >::rGetMatrix(), hypro::Reset< Number >::rGetVector(), and hypro::HybridAutomaton< Number >::setVariables().
template<typename Number > void hypro::output_2D_interval_gnuplot (std::list< Flowpipe< Number >> & flowpipes, std::ofstream & os, const std::string & fileName, const carl::Variable & axis_x, const carl::Variable & axis_y)
Definition at line 339 of file continuous.tpp.
References hypro::Range< Number >::find_assignment().
template<typename Number > std::pair<HybridAutomaton<Number>, ReachabilitySettings> hypro::parseFlowstarFile (const std::string & filename)
template<> std::pair<HybridAutomaton<double>, ReachabilitySettings> hypro::parseFlowstarFile< double > (const std::string & filename)
Definition at line 210 of file ParserWrapper.cpp.
References hypro::HybridAutomatonParser::getConstants(), hypro::HyproHAVisitor< Number >::getSettings(), openFile(), replaceConstantsWithValues(), and hypro::HybridAutomatonParser::start().
template<> std::pair<HybridAutomaton<mpq_class>, ReachabilitySettings> hypro::parseFlowstarFile< mpq_class > (const std::string & filename)
Definition at line 130 of file ParserWrapper.cpp.
References hypro::HybridAutomatonParser::getConstants(), hypro::HyproHAVisitor< Number >::getSettings(), openFile(), replaceConstantsWithValues(), and hypro::HybridAutomatonParser::start().
template<typename State > void hypro::preProcess (typename ReachTreeNode< State >::NodeList_t & toMatch, const std::vector< carl::Interval< tNumber >> & timespans) inline
Definition at line 45 of file util.h.
template<typename Representation > void hypro::printFlowpipe (const std::vector< Representation > & _flowpipe)
Definition at line 43 of file util.h.
template<typename Representation > void hypro::printFlowpipeReduced (const std::vector< Representation > & _flowpipe)
Definition at line 50 of file util.h.
void hypro::printProblem (glp_prob * glpkProblem) inline
Definition at line 8 of file adaptions_glpk.tpp.
template<typename Number > vector_t<Number> hypro::project (const vector_t< Number > & in, const std::vector< std::size_t > & dimensions)
Definition at line 254 of file adaptions_eigen.h.
Referenced by CLANG_WARNING_DISABLE(), convertSettings(), hypro::SupportFunctionContent< Number, Setting >::getThis(), hypro::Halfspace< Number >::project(), hypro::ZonotopeT< Number, Converter, Setting >::project(), and hypro::SupportFunctionNewT< Number, Converter, Setting >::reduceNumberRepresentation().
void hypro::reduceIntervalsNumberRepresentation (std::vector< carl::Interval< mpq_class >> & intervals, unsigned limit)
Definition at line 5 of file intervalMethods.cpp.
Referenced by reduceIntervalsNumberRepresentation(), and hypro::BoxT< Number, Converter, Setting >::reduceNumberRepresentation().
template<typename Number > void hypro::reduceIntervalsNumberRepresentation (std::vector< carl::Interval< Number >> & , unsigned)
Definition at line 47 of file intervalMethods.h.
References reduceIntervalsNumberRepresentation().
template<typename Number , carl::DisableIf< std::is_same< Number, double >> = carl::dummy> vector_t< Number > hypro::reduceNumberRepresentation (const vector_t< Number > & in)
Definition at line 319 of file adaptions_eigen.h.
Referenced by hypro::BoxT< Number, Converter, Setting >::BoxT().
template<typename Number > vector_t< Number > hypro::refineSolution (glpk_context & context, const matrix_t< Number > & constraints, const vector_t< Number > & constants)
Definition at line 40 of file adaptions_glpk.tpp.
References hypro::glpk_context::lp.
Referenced by glpkOptimizeLinear().
template<typename Number > void hypro::removeEmptyGenerators (matrix_t< Number > & generatorMatrix)
Definition at line 37 of file Zonotope.tpp.
template<typename Number > void hypro::removeGenerator (unsigned colToRemove, matrix_t< Number > & matrix)
Definition at line 20 of file Zonotope.tpp.
template<typename Number , typename IdxType > matrix_t<Number> hypro::removeRows (const matrix_t< Number > & original, const std::vector< IdxType > & rowIndices)
Definition at line 19 of file transformation.h.
References selectRows().
Referenced by removeRows(), and hypro::VPolytopeT< Number, Converter, S >::satisfiesHalfspaces().
template<typename Number , typename IdxType > vector_t<Number> hypro::removeRows (const vector_t< Number > & original, const std::vector< IdxType > & rowIndices)
Definition at line 55 of file transformation.h.
References removeRows().
std::string hypro::replaceConstantsWithValues (TokenStreamRewriter & rewriter, std::map< std::string, std::string > constants)
Definition at line 43 of file ParserWrapper.cpp.
Referenced by parseFlowstarFile< double >(), and parseFlowstarFile< mpq_class >().
std::size_t hypro::RGBtoHEX (std::vector< std::size_t > color)
Definition at line 13 of file PlotterUtil.cpp.
Referenced by adjustSaturation().
std::vector< double > hypro::RGBtoHSV (const std::vector< std::size_t > & color)
Definition at line 26 of file PlotterUtil.cpp.
Referenced by adjustSaturation().
template<typename SetType , typename Number , sampling_strategy_set SMPL_STRAT> std::vector<SimulationSample<Number> > hypro::sample (const SetType & in, unsigned k = 0)
Definition at line 24 of file sampling.h.
References CENTER, hypro::Point< Number >::dimension(), and VERTICES.
template<typename tNumber , sampling_strategy_interval SMPL_STRAT> std::vector<tNumber> hypro::sample (const carl::Interval< tNumber > guardIntersectInterval, unsigned k = 0)
Definition at line 87 of file sampling.h.
References BORDERS, gen, lowerBound(), RANDOM_INTV_K, and UNIFORM_K.
template<> bool hypro::satisfiesIneqation (const vector_t< double > & constraint, double constant, const vector_t< double > & point)
Definition at line 117 of file adaptions_eigen_double.cpp.
template<typename Number > bool hypro::satisfiesIneqation (const vector_t< Number > & constraint, Number constant, const vector_t< Number > & point)
Definition at line 397 of file adaptions_eigen.h.
Referenced by hypro::Halfspace< Number >::contains().
template<typename Number > vector_t<Number> hypro::scalarProjection (const vector_t< Number > & source, const vector_t< Number > & target)
Definition at line 269 of file adaptions_eigen.h.
template<typename Number , typename IdxType > matrix_t<Number> hypro::selectCols (const matrix_t< Number > & original, const std::vector< IdxType > & colIndices)
Definition at line 60 of file transformation.h.
References combine().
Referenced by combine(), and hypro::Reset< Number >::decompose().
template<typename T > Range<T> hypro::selectFirstConsecutiveRange (const T & in, std::function< bool(typename T::value_type)> cmp)
Definition at line 28 of file Range.h.
Referenced by hypro::Flowpipe< Number >::selectSatisfyingStates(), and hypro::Flowpipe< Number >::selectTimestamps().
template<typename Number , typename IdxType > matrix_t<Number> hypro::selectRows (const matrix_t< Number > & original, const std::vector< IdxType > & rowIndices)
Definition at line 10 of file transformation.h.
Referenced by combine(), hypro::Reset< Number >::decompose(), and removeRows().
template<typename Number , typename IdxType > vector_t<Number> hypro::selectRows (const vector_t< Number > & original, const std::vector< IdxType > & rowIndices)
Definition at line 46 of file transformation.h.
template<typename Number > bool hypro::smtratCheckConsistency (const matrix_t< Number > & constraints, const vector_t< Number > & constants, std::vector< carl::Relation > & relationSymbols)
Referenced by hypro::Optimizer< Number >::checkConsistency().
template<typename Number > bool hypro::smtratCheckConsistency (const matrix_t< Number > & constraints, const vector_t< Number > & constants, const std::vector< carl::Relation > & relationSymbols)
Definition at line 88 of file adaptions_smtrat.tpp.
template<typename Number > bool hypro::smtratCheckPoint (const matrix_t< Number > & constraints, const vector_t< Number > & constants, std::vector< carl::Relation > & relationSymbols, const Point< Number > & point)
Referenced by hypro::Optimizer< Number >::checkPoint(), smtratGetInternalPoint(), and smtratOptimizeLinear().
template<typename Number > bool hypro::smtratCheckPoint (const matrix_t< Number > & constraints, const vector_t< Number > & constants, const std::vector< carl::Relation > & relationSymbols, const Point< Number > & point)
Definition at line 128 of file adaptions_smtrat.tpp.
template<typename Number > EvaluationResult<Number> hypro::smtratGetInternalPoint (const matrix_t< Number > & constraints, const vector_t< Number > & constants, std::vector< carl::Relation > & relationSymbols)
Referenced by hypro::Optimizer< Number >::getInternalPoint().
template<typename Number > EvaluationResult<Number> hypro::smtratGetInternalPoint (const matrix_t< Number > & constraints, const vector_t< Number > & constants, const std::vector< carl::Relation > & relationSymbols)
Definition at line 323 of file adaptions_smtrat.tpp.
References hypro::EvaluationResult< Number >::errorCode, FEAS, INFEAS, hypro::EvaluationResult< Number >::optimumValue, and smtratCheckPoint().
template<typename Number > EvaluationResult< Number > hypro::smtratOptimizeLinear (const vector_t< Number > & _direction, const matrix_t< Number > & constraints, const vector_t< Number > & constants, const std::vector< carl::Relation > & relationSymbols, const EvaluationResult< Number > & preSolution = EvaluationResult<Number>())
Definition at line 7 of file adaptions_smtrat.tpp.
References addPreSolution(), hypro::EvaluationResult< Number >::errorCode, FEAS, INFEAS, hypro::EvaluationResult< Number >::optimumValue, and smtratCheckPoint().
Referenced by hypro::Optimizer< Number >::evaluate().
template<typename Number > std::vector<std::size_t> hypro::smtratRedundantConstraints (const matrix_t< Number > & constraints, const vector_t< Number > & constants, std::vector< carl::Relation > & relationSymbols)
Referenced by hypro::Optimizer< Number >::redundantConstraints().
template<typename Number > std::vector<std::size_t> hypro::smtratRedundantConstraints (const matrix_t< Number > & constraints, const vector_t< Number > & constants, const std::vector< carl::Relation > & relationSymbols)
Definition at line 164 of file adaptions_smtrat.tpp.
template<typename Number > bool hypro::soplexCheckConsistency (const matrix_t< Number > & constraints, const vector_t< Number > & constants)
Definition at line 83 of file adaptions_soplex.tpp.
Referenced by hypro::Optimizer< Number >::checkConsistency().
template<typename Number > bool hypro::soplexCheckPoint (const matrix_t< Number > & constraints, const vector_t< Number > & constants, const Point< Number > & point)
Definition at line 129 of file adaptions_soplex.tpp.
References hypro::Point< Number >::at().
Referenced by hypro::Optimizer< Number >::checkPoint().
template<typename Number > EvaluationResult< Number > hypro::soplexOptimizeLinear (const vector_t< Number > & _direction, const matrix_t< Number > & constraints, const vector_t< Number > & constants, const EvaluationResult< Number > & preSolution = EvaluationResult<Number>())
Definition at line 8 of file adaptions_soplex.tpp.
References FEAS, INFEAS, and INFTY.
Referenced by hypro::Optimizer< Number >::evaluate().
int hypro::stringToSetting (const std::string & name)
Definition at line 25 of file settings_enums.cpp.
References hypro::stringToSetting_Impl< Enum, Enums >::toSetting().
Referenced by main().
template<typename Number > void hypro::swap (Point< Number > & _lhs, Point< Number > & _rhs)
Swap operator.
Parameters
_lhs The left hand side.
_rhs The right hand side.
Template Parameters
Number The number type.
Definition at line 546 of file Point.h.
References hypro::Point< Number >::swap().
Referenced by hypro::SupportFunctionContent< Number, Setting >::collectProjections(), and hypro::Vertex< std::size_t >::swap().
template<typename T > T hypro::toContainer (Range< T > & r)
Definition at line 23 of file Range.h.
template<typename Number > std::string hypro::toFlowstarFormat (const matrix_t< Number > & in, const std::map< Eigen::Index, std::string > & varNameMap, const std::string & prefix)
Definition at line 11 of file Flowstar.h.
Referenced by main(), and toFlowstarFormat().
template<typename Number > std::string hypro::toFlowstarFormat (const Condition< Number > & in, const std::map< Eigen::Index, std::string > & varNameMap, const std::string & prefix)
Definition at line 53 of file Flowstar.h.
template<typename Number > std::string hypro::toFlowstarFormat (const ConstraintSetT< Number > & in, const std::map< Eigen::Index, std::string > & varNameMap, const std::string & prefix)
Definition at line 85 of file Flowstar.h.
References hypro::ConstraintSetT< Number, S >::matrix(), toFlowstarFormat(), and hypro::ConstraintSetT< Number, S >::vector().
template<typename Number > std::string hypro::toFlowstarFormat (const flowVariant< Number > & f, const std::map< Eigen::Index, std::string > & varNameMap, const std::string & prefix)
Definition at line 92 of file Flowstar.h.
References affine, discrete, getFlowType(), linear, rectangular, timed, and toFlowstarFormat().
template<typename Number > std::string hypro::toFlowstarFormat (const Location< Number > * loc, const std::map< Eigen::Index, std::string > & varNameMap, const std::string & prefix)
Definition at line 131 of file Flowstar.h.
References hypro::Location< Number >::dimension(), hypro::Location< Number >::getInvariant(), hypro::Location< Number >::getName(), and toFlowstarFormat().
std::string hypro::toFlowstarFormat (const ReachabilitySettings & settings, const std::map< Eigen::Index, std::string > & varNameMap, const std::string & prefix)
Definition at line 157 of file Flowstar.h.
References hypro::ReachabilitySettings::fileName, hypro::ReachabilitySettings::jumpDepth, hypro::ReachabilitySettings::plotDimensions, hypro::ReachabilitySettings::timeBound, and hypro::ReachabilitySettings::timeStep.
template<typename Number > std::string hypro::toFlowstarFormat (const HybridAutomaton< Number > & in, const ReachabilitySettings & settings = ReachabilitySettings())
Definition at line 181 of file Flowstar.h.
References hypro::HybridAutomaton< Number >::dimension(), hypro::HybridAutomaton< Number >::getInitialStates(), hypro::HybridAutomaton< Number >::getLocalBadStates(), hypro::HybridAutomaton< Number >::getLocations(), hypro::HybridAutomaton< Number >::getTransitions(), and toFlowstarFormat().
template<typename Number , typename Converter , typename Setting > SupportFunctionT<Number, Converter, Setting> hypro::unite (const std::vector< SupportFunctionT< Number, Converter, Setting >> & _rhs)
Definition at line 438 of file SupportFunction.tpp.
References hypro::SupportFunctionContent< Number, Setting >::unite().
Referenced by hypro::SupportFunctionNewT< Number, Converter, Setting >::assignIntervals(), hypro::SupportFunctionContent< Number, Setting >::getThis(), hypro::EventTimingProvider< Number >::getTimings(), and main().
void hypro::unreachable () inline
Definition at line 6 of file unreachable.h.
Referenced by hypro::Dispatcher_i< Representation >::dispatch(), and hypro::ExactQuickhull::Facet< Number, Euclidian >::findNeighborIndex().
template<typename Number , typename State > bool hypro::updateTiming (typename EventTimingContainer< Number >::Node_t current, carl::Interval< tNumber > entryTimestamp, Transition< Number > * transition, StrategyNode< State > currentStratNode, bool insert) inline
Definition at line 8 of file timingUtil.h.
References hypro::EventTimingProvider< Number >::addChildToNode(), hypro::Transition< Number >::getAggregation(), hypro::Transition< Number >::getTarget(), MODEL, NO_AGG, and none.
template<typename Number > Number* hypro::vector2Array (vector_t< Number > v)
Definition at line 203 of file helperMethods.h.
template<typename Number > bool hypro::z3CheckConsistency (const matrix_t< Number > & constraints, const vector_t< Number > & constants)
Definition at line 135 of file adaptions_z3.tpp.
Referenced by hypro::Optimizer< Number >::checkConsistency().
template<typename Number > bool hypro::z3CheckPoint (const matrix_t< Number > & constraints, const vector_t< Number > & constants, const Point< Number > & point)
Definition at line 153 of file adaptions_z3.tpp.
Referenced by hypro::Optimizer< Number >::checkPoint().
template<typename Number > EvaluationResult< Number > hypro::z3OptimizeLinear (bool maximize, const vector_t< Number > & _direction, const matrix_t< Number > & constraints, const vector_t< Number > & constants, const EvaluationResult< Number > & preSolution = EvaluationResult<Number>())
Definition at line 8 of file adaptions_z3.tpp.
References addPreSolution(), hypro::EvaluationResult< Number >::errorCode, FEAS, INFEAS, INFTY, hypro::EvaluationResult< Number >::optimumValue, and hypro::EvaluationResult< Number >::supportValue.
Referenced by hypro::Optimizer< Number >::evaluate().
template<> EvaluationResult< double > hypro::z3OptimizeLinear (bool maximize, const vector_t< double > & _direction, const matrix_t< double > & constraints, const vector_t< double > & constants, const EvaluationResult< double > & preSolution)
Definition at line 11 of file adaptions_z3_double.cpp.
References addPreSolution(), hypro::EvaluationResult< Number >::errorCode, FEAS, INFEAS, INFTY, hypro::EvaluationResult< Number >::optimumValue, and hypro::EvaluationResult< Number >::supportValue.
template<typename Number > std::vector< std::size_t > hypro::z3RedundantConstraints (const matrix_t< Number > & constraints, const vector_t< Number > & constants)
Definition at line 168 of file adaptions_z3.tpp.
Referenced by hypro::Optimizer< Number >::redundantConstraints().
Variable Documentation
template<typename T , typename U > constexpr bool hypro::convertible = std::is_convertible_v<T, U>
Definition at line 24 of file typetraits.h.
template<typename Number > constexpr bool hypro::is_exact = std::is_same_v<Number, mpq_class> inline
Definition at line 28 of file typetraits.h.