var namespacehypro =
[
    [ "detail", null, [
      [ "seq", "structhypro_1_1detail_1_1seq.html", null ],
      [ "gen_seq", "structhypro_1_1detail_1_1gen__seq.html", null ],
      [ "gen_seq< 0, Is...>", "structhypro_1_1detail_1_1gen__seq_3_010_00_01Is_8_8_8_4.html", null ]
    ] ],
    [ "Eigen", null, [
      [ "NumTraits< carl::FLOAT_T< Number > >", "structhypro_1_1Eigen_1_1NumTraits_3_01carl_1_1FLOAT__T_3_01Number_01_4_01_4.html", "structhypro_1_1Eigen_1_1NumTraits_3_01carl_1_1FLOAT__T_3_01Number_01_4_01_4" ],
      [ "NumTraits< mpq_class >", "structhypro_1_1Eigen_1_1NumTraits_3_01mpq__class_01_4.html", "structhypro_1_1Eigen_1_1NumTraits_3_01mpq__class_01_4" ],
      [ "NumTraits< carl::Interval< Number > >", "structhypro_1_1Eigen_1_1NumTraits_3_01carl_1_1Interval_3_01Number_01_4_01_4.html", "structhypro_1_1Eigen_1_1NumTraits_3_01carl_1_1Interval_3_01Number_01_4_01_4" ]
    ] ],
    [ "hypro", "namespacehypro_1_1hypro.html", "namespacehypro_1_1hypro" ],
    [ "parser", null, [
      [ "fsSkipper", "structhypro_1_1parser_1_1fsSkipper.html", "structhypro_1_1parser_1_1fsSkipper" ],
      [ "ErrorHandler", "structhypro_1_1parser_1_1ErrorHandler.html", "structhypro_1_1parser_1_1ErrorHandler" ],
      [ "transitionParser", "structhypro_1_1parser_1_1transitionParser.html", "structhypro_1_1parser_1_1transitionParser" ],
      [ "modeParser", "structhypro_1_1parser_1_1modeParser.html", "structhypro_1_1parser_1_1modeParser" ],
      [ "settingsParser", "structhypro_1_1parser_1_1settingsParser.html", "structhypro_1_1parser_1_1settingsParser" ],
      [ "flowstarParser", "structhypro_1_1parser_1_1flowstarParser.html", "structhypro_1_1parser_1_1flowstarParser" ],
      [ "variableParser", "structhypro_1_1parser_1_1variableParser.html", "structhypro_1_1parser_1_1variableParser" ],
      [ "monomialParser", "structhypro_1_1parser_1_1monomialParser.html", "structhypro_1_1parser_1_1monomialParser" ],
      [ "polynomialParser", "structhypro_1_1parser_1_1polynomialParser.html", "structhypro_1_1parser_1_1polynomialParser" ],
      [ "odeParser", "structhypro_1_1parser_1_1odeParser.html", "structhypro_1_1parser_1_1odeParser" ],
      [ "resetParser", "structhypro_1_1parser_1_1resetParser.html", "structhypro_1_1parser_1_1resetParser" ],
      [ "singleVariableConstraintParser", "structhypro_1_1parser_1_1singleVariableConstraintParser.html", "structhypro_1_1parser_1_1singleVariableConstraintParser" ],
      [ "constraintParser", "structhypro_1_1parser_1_1constraintParser.html", "structhypro_1_1parser_1_1constraintParser" ],
      [ "discreteConstraintParser", "structhypro_1_1parser_1_1discreteConstraintParser.html", "structhypro_1_1parser_1_1discreteConstraintParser" ],
      [ "aggregation_", "structhypro_1_1parser_1_1aggregation__.html", "structhypro_1_1parser_1_1aggregation__" ]
    ] ],
    [ "plotting", null, [
      [ "gnuplotSettings", "structhypro_1_1plotting_1_1gnuplotSettings.html", "structhypro_1_1plotting_1_1gnuplotSettings" ]
    ] ],
    [ "reachability", null, [
      [ "Reach", "classhypro_1_1reachability_1_1Reach.html", "classhypro_1_1reachability_1_1Reach" ],
      [ "Reach< Number, SupportFunction< Number > >", "classhypro_1_1reachability_1_1Reach_3_01Number_00_01SupportFunction_3_01Number_01_4_01_4.html", "classhypro_1_1reachability_1_1Reach_3_01Number_00_01SupportFunction_3_01Number_01_4_01_4" ]
    ] ],
    [ "statistics", null, [
      [ "CounterRepository", "classhypro_1_1statistics_1_1CounterRepository.html", "classhypro_1_1statistics_1_1CounterRepository" ]
    ] ],
    [ "std", null, [
      [ "hash< hypro::vector_t< Number > >", "structhypro_1_1std_1_1hash_3_01hypro_1_1vector__t_3_01Number_01_4_01_4.html", "structhypro_1_1std_1_1hash_3_01hypro_1_1vector__t_3_01Number_01_4_01_4" ],
      [ "hash< hypro::matrix_t< Number > >", "structhypro_1_1std_1_1hash_3_01hypro_1_1matrix__t_3_01Number_01_4_01_4.html", "structhypro_1_1std_1_1hash_3_01hypro_1_1matrix__t_3_01Number_01_4_01_4" ]
    ] ],
    [ "ConstrainSet", "classhypro_1_1ConstrainSet.html", "classhypro_1_1ConstrainSet" ],
    [ "ConvexHull", "classhypro_1_1ConvexHull.html", "classhypro_1_1ConvexHull" ],
    [ "Dictionary", "classhypro_1_1Dictionary.html", "classhypro_1_1Dictionary" ],
    [ "VertexEnumeration", "classhypro_1_1VertexEnumeration.html", "classhypro_1_1VertexEnumeration" ],
    [ "TrafoParameters", "classhypro_1_1TrafoParameters.html", "classhypro_1_1TrafoParameters" ],
    [ "Facet", "classhypro_1_1Facet.html", "classhypro_1_1Facet" ],
    [ "Halfspace", "classhypro_1_1Halfspace.html", "classhypro_1_1Halfspace" ],
    [ "Condition", "classhypro_1_1Condition.html", "classhypro_1_1Condition" ],
    [ "union_functor", "structhypro_1_1union__functor.html", "structhypro_1_1union__functor" ],
    [ "affineTransformation_functor", "structhypro_1_1affineTransformation__functor.html", "structhypro_1_1affineTransformation__functor" ],
    [ "satisfiesHalfspaces_functor", "structhypro_1_1satisfiesHalfspaces__functor.html", "structhypro_1_1satisfiesHalfspaces__functor" ],
    [ "HybridAutomaton", "classhypro_1_1HybridAutomaton.html", "classhypro_1_1HybridAutomaton" ],
    [ "Transition", "classhypro_1_1Transition.html", "classhypro_1_1Transition" ],
    [ "LocationManager", "classhypro_1_1LocationManager.html", "classhypro_1_1LocationManager" ],
    [ "Location", "classhypro_1_1Location.html", "classhypro_1_1Location" ],
    [ "locPtrComp", "structhypro_1_1locPtrComp.html", "structhypro_1_1locPtrComp" ],
    [ "TPathElement", "structhypro_1_1TPathElement.html", "structhypro_1_1TPathElement" ],
    [ "Path", "classhypro_1_1Path.html", "classhypro_1_1Path" ],
    [ "Reset", "classhypro_1_1Reset.html", "classhypro_1_1Reset" ],
    [ "ReachabilitySettings", "structhypro_1_1ReachabilitySettings.html", "structhypro_1_1ReachabilitySettings" ],
    [ "State", "classhypro_1_1State.html", "classhypro_1_1State" ],
    [ "genericUniteVisitor", "classhypro_1_1genericUniteVisitor.html", "classhypro_1_1genericUniteVisitor" ],
    [ "genericIntersectVisitor", "classhypro_1_1genericIntersectVisitor.html", "classhypro_1_1genericIntersectVisitor" ],
    [ "genericAffineTransformationVisitor", "classhypro_1_1genericAffineTransformationVisitor.html", "classhypro_1_1genericAffineTransformationVisitor" ],
    [ "genericConversionVisitor", "classhypro_1_1genericConversionVisitor.html", "classhypro_1_1genericConversionVisitor" ],
    [ "genericReductionVisitor", "classhypro_1_1genericReductionVisitor.html", "classhypro_1_1genericReductionVisitor" ],
    [ "genericSatisfiesHalfspacesVisitor", "classhypro_1_1genericSatisfiesHalfspacesVisitor.html", "classhypro_1_1genericSatisfiesHalfspacesVisitor" ],
    [ "genericCompareVisitor", "classhypro_1_1genericCompareVisitor.html", "classhypro_1_1genericCompareVisitor" ],
    [ "genericOutstreamVisitor", "classhypro_1_1genericOutstreamVisitor.html", "classhypro_1_1genericOutstreamVisitor" ],
    [ "LRUCache", "classhypro_1_1LRUCache.html", "classhypro_1_1LRUCache" ],
    [ "Point", "classhypro_1_1Point.html", "classhypro_1_1Point" ],
    [ "ReachTree", "classhypro_1_1ReachTree.html", "classhypro_1_1ReachTree" ],
    [ "ReachTreeNode", "classhypro_1_1ReachTreeNode.html", "classhypro_1_1ReachTreeNode" ],
    [ "ReachTreeNodeSimple", "classhypro_1_1ReachTreeNodeSimple.html", "classhypro_1_1ReachTreeNodeSimple" ],
    [ "Ridge", "classhypro_1_1Ridge.html", "classhypro_1_1Ridge" ],
    [ "Vertex", "classhypro_1_1Vertex.html", "classhypro_1_1Vertex" ],
    [ "VertexContainer", "classhypro_1_1VertexContainer.html", "classhypro_1_1VertexContainer" ],
    [ "BoxT", "classhypro_1_1BoxT.html", "classhypro_1_1BoxT" ],
    [ "BoxT< double, Converter >", "classhypro_1_1BoxT_3_01double_00_01Converter_01_4.html", "classhypro_1_1BoxT_3_01double_00_01Converter_01_4" ],
    [ "ConstraintSetT", "classhypro_1_1ConstraintSetT.html", "classhypro_1_1ConstraintSetT" ],
    [ "Converter", "classhypro_1_1Converter.html", "classhypro_1_1Converter" ],
    [ "EllipsoidT", "classhypro_1_1EllipsoidT.html", "classhypro_1_1EllipsoidT" ],
    [ "GeometricObject", "classhypro_1_1GeometricObject.html", "classhypro_1_1GeometricObject" ],
    [ "pointIt", "structhypro_1_1pointIt.html", "structhypro_1_1pointIt" ],
    [ "Grid", "classhypro_1_1Grid.html", "classhypro_1_1Grid" ],
    [ "NeighborhoodContainer", "classhypro_1_1NeighborhoodContainer.html", "classhypro_1_1NeighborhoodContainer" ],
    [ "OrthogonalPolyhedronT", "classhypro_1_1OrthogonalPolyhedronT.html", "classhypro_1_1OrthogonalPolyhedronT" ],
    [ "OrthogonalPolyhedron", "classhypro_1_1OrthogonalPolyhedron.html", "classhypro_1_1OrthogonalPolyhedron" ],
    [ "Cone", "classhypro_1_1Cone.html", "classhypro_1_1Cone" ],
    [ "Fan", "classhypro_1_1Fan.html", "classhypro_1_1Fan" ],
    [ "HPolytopeT", "classhypro_1_1HPolytopeT.html", "classhypro_1_1HPolytopeT" ],
    [ "VPolytopeT", "classhypro_1_1VPolytopeT.html", "classhypro_1_1VPolytopeT" ],
    [ "BallSupportFunction", "classhypro_1_1BallSupportFunction.html", "classhypro_1_1BallSupportFunction" ],
    [ "SymmetricCenteredBoxSupportFunction", "classhypro_1_1SymmetricCenteredBoxSupportFunction.html", "classhypro_1_1SymmetricCenteredBoxSupportFunction" ],
    [ "EllipsoidSupportFunction", "classhypro_1_1EllipsoidSupportFunction.html", "classhypro_1_1EllipsoidSupportFunction" ],
    [ "NonLinearOmega0Supportfunction", "classhypro_1_1NonLinearOmega0Supportfunction.html", "classhypro_1_1NonLinearOmega0Supportfunction" ],
    [ "PolytopeSupportFunction", "classhypro_1_1PolytopeSupportFunction.html", "classhypro_1_1PolytopeSupportFunction" ],
    [ "SupportFunctionT", "classhypro_1_1SupportFunctionT.html", "classhypro_1_1SupportFunctionT" ],
    [ "SupportFunctionContent", "classhypro_1_1SupportFunctionContent.html", "classhypro_1_1SupportFunctionContent" ],
    [ "sumContent", "structhypro_1_1sumContent.html", "structhypro_1_1sumContent" ],
    [ "trafoContent", "structhypro_1_1trafoContent.html", "structhypro_1_1trafoContent" ],
    [ "scaleContent", "structhypro_1_1scaleContent.html", "structhypro_1_1scaleContent" ],
    [ "unionContent", "structhypro_1_1unionContent.html", "structhypro_1_1unionContent" ],
    [ "intersectionContent", "structhypro_1_1intersectionContent.html", "structhypro_1_1intersectionContent" ],
    [ "projectionContent", "structhypro_1_1projectionContent.html", "structhypro_1_1projectionContent" ],
    [ "Cacheable", "structhypro_1_1Cacheable.html", "structhypro_1_1Cacheable" ],
    [ "lintrafoParameters", "structhypro_1_1lintrafoParameters.html", "structhypro_1_1lintrafoParameters" ],
    [ "Flowpipe", "classhypro_1_1Flowpipe.html", "classhypro_1_1Flowpipe" ],
    [ "ContinuousSystem", "classhypro_1_1ContinuousSystem.html", "classhypro_1_1ContinuousSystem" ],
    [ "Domain", "classhypro_1_1Domain.html", "classhypro_1_1Domain" ],
    [ "TaylorModelVec", "classhypro_1_1TaylorModelVec.html", "classhypro_1_1TaylorModelVec" ],
    [ "PolynomialODE", "classhypro_1_1PolynomialODE.html", "classhypro_1_1PolynomialODE" ],
    [ "TaylorModel", "classhypro_1_1TaylorModel.html", "classhypro_1_1TaylorModel" ],
    [ "Range", "classhypro_1_1Range.html", "classhypro_1_1Range" ],
    [ "ZonotopeT", "classhypro_1_1ZonotopeT.html", "classhypro_1_1ZonotopeT" ],
    [ "typeName", "structhypro_1_1typeName.html", "structhypro_1_1typeName" ],
    [ "typeName< double >", "structhypro_1_1typeName_3_01double_01_4.html", "structhypro_1_1typeName_3_01double_01_4" ],
    [ "typeName< mpq_class >", "structhypro_1_1typeName_3_01mpq__class_01_4.html", "structhypro_1_1typeName_3_01mpq__class_01_4" ],
    [ "EvaluationResult", "structhypro_1_1EvaluationResult.html", "structhypro_1_1EvaluationResult" ],
    [ "Optimizer", "classhypro_1_1Optimizer.html", "classhypro_1_1Optimizer" ],
    [ "PrincipalComponentAnalysis", "classhypro_1_1PrincipalComponentAnalysis.html", "classhypro_1_1PrincipalComponentAnalysis" ],
    [ "Permutator", "classhypro_1_1Permutator.html", "classhypro_1_1Permutator" ],
    [ "Plotter", "classhypro_1_1Plotter.html", "classhypro_1_1Plotter" ],
    [ "VariablePool", "classhypro_1_1VariablePool.html", "classhypro_1_1VariablePool" ]
];