var namespacehypro =
[
    [ "detail", null, [
      [ "seq", "structhypro_1_1detail_1_1seq.html", null ],
      [ "gen_seq", "structhypro_1_1detail_1_1gen__seq.html", null ],
      [ "gen_seq< 0, Is...>", "structhypro_1_1detail_1_1gen__seq_3_010_00_01Is_8_8_8_4.html", null ]
    ] ],
    [ "Eigen", null, [
      [ "NumTraits< carl::FLOAT_T< Number > >", "structhypro_1_1Eigen_1_1NumTraits_3_01carl_1_1FLOAT__T_3_01Number_01_4_01_4.html", "structhypro_1_1Eigen_1_1NumTraits_3_01carl_1_1FLOAT__T_3_01Number_01_4_01_4" ],
      [ "NumTraits< mpq_class >", "structhypro_1_1Eigen_1_1NumTraits_3_01mpq__class_01_4.html", "structhypro_1_1Eigen_1_1NumTraits_3_01mpq__class_01_4" ],
      [ "NumTraits< carl::Interval< Number > >", "structhypro_1_1Eigen_1_1NumTraits_3_01carl_1_1Interval_3_01Number_01_4_01_4.html", "structhypro_1_1Eigen_1_1NumTraits_3_01carl_1_1Interval_3_01Number_01_4_01_4" ]
    ] ],
    [ "hypro", "namespacehypro_1_1hypro.html", "namespacehypro_1_1hypro" ],
    [ "parser", null, [
      [ "fsSkipper", "structhypro_1_1parser_1_1fsSkipper.html", "structhypro_1_1parser_1_1fsSkipper" ],
      [ "ErrorHandler", "structhypro_1_1parser_1_1ErrorHandler.html", "structhypro_1_1parser_1_1ErrorHandler" ],
      [ "transitionParser", "structhypro_1_1parser_1_1transitionParser.html", "structhypro_1_1parser_1_1transitionParser" ],
      [ "modeParser", "structhypro_1_1parser_1_1modeParser.html", "structhypro_1_1parser_1_1modeParser" ],
      [ "settingsParser", "structhypro_1_1parser_1_1settingsParser.html", "structhypro_1_1parser_1_1settingsParser" ],
      [ "flowstarParser", "structhypro_1_1parser_1_1flowstarParser.html", "structhypro_1_1parser_1_1flowstarParser" ],
      [ "variableParser", "structhypro_1_1parser_1_1variableParser.html", "structhypro_1_1parser_1_1variableParser" ],
      [ "monomialParser", "structhypro_1_1parser_1_1monomialParser.html", "structhypro_1_1parser_1_1monomialParser" ],
      [ "polynomialParser", "structhypro_1_1parser_1_1polynomialParser.html", "structhypro_1_1parser_1_1polynomialParser" ],
      [ "odeParser", "structhypro_1_1parser_1_1odeParser.html", "structhypro_1_1parser_1_1odeParser" ],
      [ "resetParser", "structhypro_1_1parser_1_1resetParser.html", "structhypro_1_1parser_1_1resetParser" ],
      [ "singleVariableConstraintParser", "structhypro_1_1parser_1_1singleVariableConstraintParser.html", "structhypro_1_1parser_1_1singleVariableConstraintParser" ],
      [ "constraintParser", "structhypro_1_1parser_1_1constraintParser.html", "structhypro_1_1parser_1_1constraintParser" ],
      [ "discreteConstraintParser", "structhypro_1_1parser_1_1discreteConstraintParser.html", "structhypro_1_1parser_1_1discreteConstraintParser" ],
      [ "aggregation_", "structhypro_1_1parser_1_1aggregation__.html", "structhypro_1_1parser_1_1aggregation__" ]
    ] ],
    [ "plotting", null, [
      [ "gnuplotSettings", "structhypro_1_1plotting_1_1gnuplotSettings.html", "structhypro_1_1plotting_1_1gnuplotSettings" ]
    ] ],
    [ "reachability", null, [
      [ "Eigen", "namespacehypro_1_1reachability_1_1Eigen.html", "namespacehypro_1_1reachability_1_1Eigen" ],
      [ "hypro", "namespacehypro_1_1reachability_1_1hypro.html", "namespacehypro_1_1reachability_1_1hypro" ],
      [ "std", null, [
        [ "hash< hypro::vector_t< Number > >", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1vector__t_3_01Number_01_4_01_4.html", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1vector__t_3_01Number_01_4_01_4" ],
        [ "hash< hypro::matrix_t< Number > >", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1matrix__t_3_01Number_01_4_01_4.html", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1matrix__t_3_01Number_01_4_01_4" ],
        [ "hash< hypro::Cacheable< Content > >", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1Cacheable_3_01Content_01_4_01_4.html", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1Cacheable_3_01Content_01_4_01_4" ],
        [ "hash< hypro::Point< Number > >", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1Point_3_01Number_01_4_01_4.html", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1Point_3_01Number_01_4_01_4" ],
        [ "hash< hypro::Halfspace< Number > >", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1Halfspace_3_01Number_01_4_01_4.html", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1Halfspace_3_01Number_01_4_01_4" ],
        [ "hash< hypro::Vertex< Number > >", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1Vertex_3_01Number_01_4_01_4.html", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1Vertex_3_01Number_01_4_01_4" ],
        [ "hash< hypro::VertexContainer< Number > >", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1VertexContainer_3_01Number_01_4_01_4.html", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1VertexContainer_3_01Number_01_4_01_4" ],
        [ "hash< set< hypro::Vertex< Number > > >", "structhypro_1_1reachability_1_1std_1_1hash_3_01set_3_01hypro_1_1Vertex_3_01Number_01_4_01_4_01_4.html", "structhypro_1_1reachability_1_1std_1_1hash_3_01set_3_01hypro_1_1Vertex_3_01Number_01_4_01_4_01_4" ],
        [ "hash< hypro::Ridge< Number > >", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1Ridge_3_01Number_01_4_01_4.html", "structhypro_1_1reachability_1_1std_1_1hash_3_01hypro_1_1Ridge_3_01Number_01_4_01_4" ]
      ] ],
      [ "ZUtility", "namespacehypro_1_1reachability_1_1ZUtility.html", "namespacehypro_1_1reachability_1_1ZUtility" ],
      [ "Reach", "classhypro_1_1reachability_1_1Reach.html", "classhypro_1_1reachability_1_1Reach" ]
    ] ],
    [ "statistics", null, [
      [ "CounterRepository", "classhypro_1_1statistics_1_1CounterRepository.html", "classhypro_1_1statistics_1_1CounterRepository" ]
    ] ],
    [ "std", null, [
      [ "hash< hypro::vector_t< Number > >", "structhypro_1_1std_1_1hash_3_01hypro_1_1vector__t_3_01Number_01_4_01_4.html", "structhypro_1_1std_1_1hash_3_01hypro_1_1vector__t_3_01Number_01_4_01_4" ],
      [ "hash< hypro::matrix_t< Number > >", "structhypro_1_1std_1_1hash_3_01hypro_1_1matrix__t_3_01Number_01_4_01_4.html", "structhypro_1_1std_1_1hash_3_01hypro_1_1matrix__t_3_01Number_01_4_01_4" ]
    ] ],
    [ "ConstrainSet", "classhypro_1_1ConstrainSet.html", "classhypro_1_1ConstrainSet" ],
    [ "ConvexHull", "classhypro_1_1ConvexHull.html", "classhypro_1_1ConvexHull" ],
    [ "Dictionary", "classhypro_1_1Dictionary.html", "classhypro_1_1Dictionary" ],
    [ "VertexEnumeration", "classhypro_1_1VertexEnumeration.html", "classhypro_1_1VertexEnumeration" ],
    [ "STindependentFunct", "structhypro_1_1STindependentFunct.html", "structhypro_1_1STindependentFunct" ],
    [ "STflowpipeSegment", "structhypro_1_1STflowpipeSegment.html", "structhypro_1_1STflowpipeSegment" ],
    [ "STallValues", "structhypro_1_1STallValues.html", "structhypro_1_1STallValues" ],
    [ "Transformation", "classhypro_1_1Transformation.html", "classhypro_1_1Transformation" ],
    [ "TrafoParameters", "classhypro_1_1TrafoParameters.html", "classhypro_1_1TrafoParameters" ],
    [ "Facet", "classhypro_1_1Facet.html", "classhypro_1_1Facet" ],
    [ "Halfspace", "classhypro_1_1Halfspace.html", "classhypro_1_1Halfspace" ],
    [ "Condition", "classhypro_1_1Condition.html", "classhypro_1_1Condition" ],
    [ "HybridAutomaton", "classhypro_1_1HybridAutomaton.html", "classhypro_1_1HybridAutomaton" ],
    [ "HybridAutomatonComp", "classhypro_1_1HybridAutomatonComp.html", "classhypro_1_1HybridAutomatonComp" ],
    [ "Label", "classhypro_1_1Label.html", "classhypro_1_1Label" ],
    [ "Transition", "classhypro_1_1Transition.html", "classhypro_1_1Transition" ],
    [ "LocationManager", "classhypro_1_1LocationManager.html", "classhypro_1_1LocationManager" ],
    [ "Location", "classhypro_1_1Location.html", "classhypro_1_1Location" ],
    [ "locPtrComp", "structhypro_1_1locPtrComp.html", "structhypro_1_1locPtrComp" ],
    [ "TPathElement", "structhypro_1_1TPathElement.html", "structhypro_1_1TPathElement" ],
    [ "Path", "classhypro_1_1Path.html", "classhypro_1_1Path" ],
    [ "Reset", "classhypro_1_1Reset.html", "classhypro_1_1Reset" ],
    [ "ReachabilitySettings", "structhypro_1_1ReachabilitySettings.html", "structhypro_1_1ReachabilitySettings" ],
    [ "State", "classhypro_1_1State.html", "classhypro_1_1State" ],
    [ "genericUniteVisitor", "classhypro_1_1genericUniteVisitor.html", "classhypro_1_1genericUniteVisitor" ],
    [ "genericMinkowskiSumVisitor", "classhypro_1_1genericMinkowskiSumVisitor.html", "classhypro_1_1genericMinkowskiSumVisitor" ],
    [ "genericIntersectVisitor", "classhypro_1_1genericIntersectVisitor.html", "classhypro_1_1genericIntersectVisitor" ],
    [ "genericAffineTransformationVisitor", "classhypro_1_1genericAffineTransformationVisitor.html", "classhypro_1_1genericAffineTransformationVisitor" ],
    [ "genericConversionVisitor", "classhypro_1_1genericConversionVisitor.html", "classhypro_1_1genericConversionVisitor" ],
    [ "genericReductionVisitor", "classhypro_1_1genericReductionVisitor.html", "classhypro_1_1genericReductionVisitor" ],
    [ "genericSatisfiesHalfspacesVisitor", "classhypro_1_1genericSatisfiesHalfspacesVisitor.html", "classhypro_1_1genericSatisfiesHalfspacesVisitor" ],
    [ "genericCompareVisitor", "classhypro_1_1genericCompareVisitor.html", "classhypro_1_1genericCompareVisitor" ],
    [ "genericOutstreamVisitor", "classhypro_1_1genericOutstreamVisitor.html", "classhypro_1_1genericOutstreamVisitor" ],
    [ "genericDimensionVisitor", "classhypro_1_1genericDimensionVisitor.html", "classhypro_1_1genericDimensionVisitor" ],
    [ "genericSupremumVisitor", "classhypro_1_1genericSupremumVisitor.html", "classhypro_1_1genericSupremumVisitor" ],
    [ "genericTypeVisitor", "classhypro_1_1genericTypeVisitor.html", "classhypro_1_1genericTypeVisitor" ],
    [ "genericVerticesVisitor", "classhypro_1_1genericVerticesVisitor.html", "classhypro_1_1genericVerticesVisitor" ],
    [ "genericProjectionVisitor", "classhypro_1_1genericProjectionVisitor.html", "classhypro_1_1genericProjectionVisitor" ],
    [ "genericSetContainsVisitor", "classhypro_1_1genericSetContainsVisitor.html", "classhypro_1_1genericSetContainsVisitor" ],
    [ "LRUCache", "classhypro_1_1LRUCache.html", "classhypro_1_1LRUCache" ],
    [ "Point", "classhypro_1_1Point.html", "classhypro_1_1Point" ],
    [ "Ridge", "classhypro_1_1Ridge.html", "classhypro_1_1Ridge" ],
    [ "Vertex", "classhypro_1_1Vertex.html", "classhypro_1_1Vertex" ],
    [ "VertexContainer", "classhypro_1_1VertexContainer.html", "classhypro_1_1VertexContainer" ],
    [ "CIFExprVisitor", "classhypro_1_1CIFExprVisitor.html", "classhypro_1_1CIFExprVisitor" ],
    [ "CIFLocVisitor", "classhypro_1_1CIFLocVisitor.html", "classhypro_1_1CIFLocVisitor" ],
    [ "HybridCIFVisitor", "classhypro_1_1HybridCIFVisitor.html", "classhypro_1_1HybridCIFVisitor" ],
    [ "ErrorListener", "classhypro_1_1ErrorListener.html", "classhypro_1_1ErrorListener" ],
    [ "HyproHAVisitor", "classhypro_1_1HyproHAVisitor.html", "classhypro_1_1HyproHAVisitor" ],
    [ "HyproBadStatesVisitor", "classhypro_1_1HyproBadStatesVisitor.html", "classhypro_1_1HyproBadStatesVisitor" ],
    [ "HyproLocationVisitor", "classhypro_1_1HyproLocationVisitor.html", "classhypro_1_1HyproLocationVisitor" ],
    [ "HyproTransitionVisitor", "classhypro_1_1HyproTransitionVisitor.html", "classhypro_1_1HyproTransitionVisitor" ],
    [ "HyproInitialSetVisitor", "classhypro_1_1HyproInitialSetVisitor.html", "classhypro_1_1HyproInitialSetVisitor" ],
    [ "HyproSettingVisitor", "classhypro_1_1HyproSettingVisitor.html", "classhypro_1_1HyproSettingVisitor" ],
    [ "HyproFormulaVisitor", "classhypro_1_1HyproFormulaVisitor.html", "classhypro_1_1HyproFormulaVisitor" ],
    [ "BoxT", "classhypro_1_1BoxT.html", "classhypro_1_1BoxT" ],
    [ "BoxT< double, Converter, Setting >", "classhypro_1_1BoxT_3_01double_00_01Converter_00_01Setting_01_4.html", "classhypro_1_1BoxT_3_01double_00_01Converter_00_01Setting_01_4" ],
    [ "BoxLinearOptimizationOn", "structhypro_1_1BoxLinearOptimizationOn.html", null ],
    [ "BoxLinearOptimizationOff", "structhypro_1_1BoxLinearOptimizationOff.html", null ],
    [ "ConstraintSetT", "classhypro_1_1ConstraintSetT.html", "classhypro_1_1ConstraintSetT" ],
    [ "Converter", "classhypro_1_1Converter.html", "classhypro_1_1Converter" ],
    [ "EllipsoidT", "classhypro_1_1EllipsoidT.html", "classhypro_1_1EllipsoidT" ],
    [ "GeometricObject", "classhypro_1_1GeometricObject.html", "classhypro_1_1GeometricObject" ],
    [ "pointIt", "structhypro_1_1pointIt.html", "structhypro_1_1pointIt" ],
    [ "Grid", "classhypro_1_1Grid.html", "classhypro_1_1Grid" ],
    [ "NeighborhoodContainer", "classhypro_1_1NeighborhoodContainer.html", "classhypro_1_1NeighborhoodContainer" ],
    [ "OrthogonalPolyhedronT", "classhypro_1_1OrthogonalPolyhedronT.html", "classhypro_1_1OrthogonalPolyhedronT" ],
    [ "OrthogonalPolyhedron", "classhypro_1_1OrthogonalPolyhedron.html", "classhypro_1_1OrthogonalPolyhedron" ],
    [ "PolytopeSetting", "structhypro_1_1PolytopeSetting.html", null ],
    [ "Cone", "classhypro_1_1Cone.html", "classhypro_1_1Cone" ],
    [ "Fan", "classhypro_1_1Fan.html", "classhypro_1_1Fan" ],
    [ "HPolytopeT", "classhypro_1_1HPolytopeT.html", "classhypro_1_1HPolytopeT" ],
    [ "HPolytopeSetting", "structhypro_1_1HPolytopeSetting.html", null ],
    [ "VPolytopeT", "classhypro_1_1VPolytopeT.html", "classhypro_1_1VPolytopeT" ],
    [ "BallSupportFunction", "classhypro_1_1BallSupportFunction.html", "classhypro_1_1BallSupportFunction" ],
    [ "SymmetricCenteredBoxSupportFunction", "classhypro_1_1SymmetricCenteredBoxSupportFunction.html", "classhypro_1_1SymmetricCenteredBoxSupportFunction" ],
    [ "EllipsoidSupportFunction", "classhypro_1_1EllipsoidSupportFunction.html", "classhypro_1_1EllipsoidSupportFunction" ],
    [ "NonLinearOmega0Supportfunction", "classhypro_1_1NonLinearOmega0Supportfunction.html", "classhypro_1_1NonLinearOmega0Supportfunction" ],
    [ "PolytopeSupportFunction", "classhypro_1_1PolytopeSupportFunction.html", "classhypro_1_1PolytopeSupportFunction" ],
    [ "SupportFunctionT", "classhypro_1_1SupportFunctionT.html", "classhypro_1_1SupportFunctionT" ],
    [ "SupportFunctionContent", "classhypro_1_1SupportFunctionContent.html", "classhypro_1_1SupportFunctionContent" ],
    [ "sumContent", "structhypro_1_1sumContent.html", "structhypro_1_1sumContent" ],
    [ "trafoContent", "structhypro_1_1trafoContent.html", "structhypro_1_1trafoContent" ],
    [ "scaleContent", "structhypro_1_1scaleContent.html", "structhypro_1_1scaleContent" ],
    [ "unionContent", "structhypro_1_1unionContent.html", "structhypro_1_1unionContent" ],
    [ "intersectionContent", "structhypro_1_1intersectionContent.html", "structhypro_1_1intersectionContent" ],
    [ "projectionContent", "structhypro_1_1projectionContent.html", "structhypro_1_1projectionContent" ],
    [ "SupportFunctionSetting", "structhypro_1_1SupportFunctionSetting.html", null ],
    [ "SupportFunctionContentSetting", "structhypro_1_1SupportFunctionContentSetting.html", null ],
    [ "BoxSupportFunctionSetting", "structhypro_1_1BoxSupportFunctionSetting.html", null ],
    [ "NonLineaerOmegaOSupportFunctionSetting", "structhypro_1_1NonLineaerOmegaOSupportFunctionSetting.html", null ],
    [ "PolytopeSupportFunctionSetting", "structhypro_1_1PolytopeSupportFunctionSetting.html", null ],
    [ "Cacheable", "structhypro_1_1Cacheable.html", "structhypro_1_1Cacheable" ],
    [ "lintrafoParameters", "structhypro_1_1lintrafoParameters.html", "structhypro_1_1lintrafoParameters" ],
    [ "Flowpipe", "classhypro_1_1Flowpipe.html", "classhypro_1_1Flowpipe" ],
    [ "ContinuousSystem", "classhypro_1_1ContinuousSystem.html", "classhypro_1_1ContinuousSystem" ],
    [ "UtilSetting", "structhypro_1_1UtilSetting.html", null ],
    [ "Domain", "classhypro_1_1Domain.html", "classhypro_1_1Domain" ],
    [ "TaylorModelVec", "classhypro_1_1TaylorModelVec.html", "classhypro_1_1TaylorModelVec" ],
    [ "PolynomialODE", "classhypro_1_1PolynomialODE.html", "classhypro_1_1PolynomialODE" ],
    [ "TaylorModel", "classhypro_1_1TaylorModel.html", "classhypro_1_1TaylorModel" ],
    [ "Range", "classhypro_1_1Range.html", "classhypro_1_1Range" ],
    [ "ZonotopeT", "classhypro_1_1ZonotopeT.html", "classhypro_1_1ZonotopeT" ],
    [ "ZonotopeSetting", "structhypro_1_1ZonotopeSetting.html", null ],
    [ "typeName", "structhypro_1_1typeName.html", "structhypro_1_1typeName" ],
    [ "typeName< double >", "structhypro_1_1typeName_3_01double_01_4.html", "structhypro_1_1typeName_3_01double_01_4" ],
    [ "typeName< mpq_class >", "structhypro_1_1typeName_3_01mpq__class_01_4.html", "structhypro_1_1typeName_3_01mpq__class_01_4" ],
    [ "EvaluationResult", "structhypro_1_1EvaluationResult.html", "structhypro_1_1EvaluationResult" ],
    [ "glpk_context", "structhypro_1_1glpk__context.html", "structhypro_1_1glpk__context" ],
    [ "Optimizer", "classhypro_1_1Optimizer.html", "classhypro_1_1Optimizer" ],
    [ "LockedFileWriter", "classhypro_1_1LockedFileWriter.html", "classhypro_1_1LockedFileWriter" ],
    [ "LockableBase", "classhypro_1_1LockableBase.html", "classhypro_1_1LockableBase" ],
    [ "LockableObjectWrapper", "classhypro_1_1LockableObjectWrapper.html", "classhypro_1_1LockableObjectWrapper" ],
    [ "PrincipalComponentAnalysis", "classhypro_1_1PrincipalComponentAnalysis.html", "classhypro_1_1PrincipalComponentAnalysis" ],
    [ "Permutator", "classhypro_1_1Permutator.html", "classhypro_1_1Permutator" ],
    [ "Plotter", "classhypro_1_1Plotter.html", "classhypro_1_1Plotter" ],
    [ "VariablePool", "classhypro_1_1VariablePool.html", "classhypro_1_1VariablePool" ]
];