HyPro: hypro::reachability Namespace Reference
hypro::reachability Namespace Reference
Namespaces
detail
Functions
template<typename Number >
matrix_t< Number > computeTrafoMatrix (const Location< Number > *_loc, Number timeStep)
template<typename Number , typename State >
void bloatBox (State &in, const Box< Number > &bloatBox)
template<typename Number , typename State >
std::tuple< CONTAINMENT, State, matrix_t< Number >, vector_t< Number >, Box< Number > > computeFirstSegment (const State &_state, tNumber timeStep)
Function Documentation
template<typename Number , typename State > void hypro::reachability::bloatBox (State & in, const Box< Number > & bloatBox)
Definition at line 50 of file FirstSegment.h.
template<typename Number , typename State > std::tuple<CONTAINMENT, State, matrix_t<Number>, vector_t<Number>, Box<Number> > hypro::reachability::computeFirstSegment (const State & _state, tNumber timeStep)
Definition at line 56 of file FirstSegment.h.
References assert(), cols, computeTrafoMatrix(), dimension(), hypro::errorBoxes(), hypro::NO, and timeStep.
template<typename Number > matrix_t<Number> hypro::reachability::computeTrafoMatrix (const Location< Number > * _loc, Number timeStep)
Definition at line 14 of file FirstSegment.h.
References flowMatrix, hypro::Location< Number >::getLinearFlow(), hypro::matrixExponential(), and timeStep.
Referenced by CLANG_WARNING_DISABLE(), and computeFirstSegment().