HyPro: hypro::parser Namespace Reference
hypro::parser Namespace Reference
Functions
void openFile (const std::string &filename, ANTLRInputStream &input)
std::string replaceConstantsWithValues (TokenStreamRewriter &rewriter, std::map< std::string, std::string > constants)
tree::ParseTree * createFlowstarParseTree (const std::string &filename)
Function Documentation
tree::ParseTree * hypro::parser::createFlowstarParseTree (const std::string & filename)
Definition at line 39 of file FlowstarParser.cpp.
References hypro::HybridAutomatonParser::getConstants(), input, openFile(), replaceConstantsWithValues(), hypro::HybridAutomatonParser::start(), string(), and tree.
void hypro::parser::openFile (const std::string & filename, ANTLRInputStream & input)
Definition at line 6 of file FlowstarParser.cpp.
Referenced by createFlowstarParseTree().
std::string hypro::parser::replaceConstantsWithValues (TokenStreamRewriter & rewriter, std::map< std::string, std::string > constants)
Definition at line 28 of file FlowstarParser.cpp.
References i.
Referenced by createFlowstarParseTree().