HyPro: Eigen Namespace Reference
Eigen Namespace Reference
Classes
struct NumTraits< carl::FLOAT_T< Number > >
struct NumTraits< mpq_class >
Functions
template<typename Number >
bool operator< (const hypro::vector_t< Number > &lhs, const hypro::vector_t< Number > &rhs)
template<typename Number >
bool operator<= (const hypro::vector_t< Number > &lhs, const hypro::vector_t< Number > &rhs)
template<typename Number >
bool operator> (const hypro::vector_t< Number > &lhs, const hypro::vector_t< Number > &rhs)
template<typename Number >
bool operator>= (const hypro::vector_t< Number > &lhs, const hypro::vector_t< Number > &rhs)
template<typename Number >
std::size_t VectorHashValue (const hypro::vector_t< Number > &pVector)
template<typename Number >
std::size_t MatrixHashValue (const hypro::matrix_t< Number > &pMatrix)
template<typename Number >
bool operator== (const hypro::vector_t< Number > &lhs, const hypro::vector_t< Number > &rhs)
template<typename Number >
bool operator!= (const hypro::vector_t< Number > &lhs, const hypro::vector_t< Number > &rhs)
template<typename Number >
bool operator== (const hypro::matrix_t< Number > &lhs, const hypro::matrix_t< Number > &rhs)
template<typename Number >
bool operator!= (const hypro::matrix_t< Number > &lhs, const hypro::matrix_t< Number > &rhs)
template<typename Number >
std::ostream & operator<< (std::ostream &_out, const hypro::vector_t< Number > &in)
template<typename Number >
std::ostream & operator<< (std::ostream &_out, const hypro::matrix_t< Number > &in)
template<typename Number >
Number norm (const hypro::vector_t< Number > &in, bool roundUp=true)
template<>
double norm (const hypro::vector_t< double > &in, bool roundUp)
template<typename Number >
Number inftyNorm (const hypro::matrix_t< Number > &in)
template<typename Number >
hypro::matrix_t< Number > abs (const hypro::matrix_t< Number > &in)
template<>
bool operator< (const hypro::vector_t< double > &lhs, const hypro::vector_t< double > &rhs)
template<>
bool operator<= (const hypro::vector_t< double > &lhs, const hypro::vector_t< double > &rhs)
template<>
bool operator> (const hypro::vector_t< double > &lhs, const hypro::vector_t< double > &rhs)
template<>
bool operator>= (const hypro::vector_t< double > &lhs, const hypro::vector_t< double > &rhs)
template<>
bool operator== (const hypro::vector_t< double > &lhs, const hypro::vector_t< double > &rhs)
template<>
bool operator!= (const hypro::vector_t< double > &lhs, const hypro::vector_t< double > &rhs)
template<>
bool operator== (const hypro::matrix_t< double > &lhs, const hypro::matrix_t< double > &rhs)
template<>
bool operator!= (const hypro::matrix_t< double > &lhs, const hypro::matrix_t< double > &rhs)
Function Documentation
template<typename Number > hypro::matrix_t<Number> Eigen::abs (const hypro::matrix_t< Number > & in)
Definition at line 210 of file adaptions_eigen.h.
Referenced by hypro::errorBoxes(), hypro::reduceIntervalsNumberRepresentation(), hypro::VPolytopeT< Number, Converter, S >::reduceNumberRepresentation(), and hypro::HPolytopeT< Number, Converter, Setting >::reduceNumberRepresentation().
template<typename Number > Number Eigen::inftyNorm (const hypro::matrix_t< Number > & in)
Definition at line 200 of file adaptions_eigen.h.
References norm().
Referenced by hypro::hausdorffError().
template<typename Number > std::size_t Eigen::MatrixHashValue (const hypro::matrix_t< Number > & pMatrix)
computes a hash chain over a matrix using carl::hash_add
Parameters
pMatrix input matrix
Returns
size_t
Definition at line 97 of file adaptions_eigen.h.
Referenced by std::hash< hypro::matrix_t< Number > >::operator()(), and operator==().
template<typename Number > Number Eigen::norm (const hypro::vector_t< Number > & in, bool roundUp = true)
Definition at line 173 of file adaptions_eigen.h.
Referenced by hypro::hausdorffError(), inftyNorm(), hypro::normalize(), and hypro::scalarProjection().
template<> double Eigen::norm (const hypro::vector_t< double > & in, bool roundUp) inline
Definition at line 192 of file adaptions_eigen.h.
template<> bool Eigen::operator!= (const hypro::vector_t< double > & lhs, const hypro::vector_t< double > & rhs) inline
Definition at line 64 of file adaptions_eigen_double.cpp.
template<> bool Eigen::operator!= (const hypro::matrix_t< double > & lhs, const hypro::matrix_t< double > & rhs) inline
Definition at line 86 of file adaptions_eigen_double.cpp.
template<typename Number > bool Eigen::operator!= (const hypro::vector_t< Number > & lhs, const hypro::vector_t< Number > & rhs) inline
Definition at line 125 of file adaptions_eigen.h.
template<typename Number > bool Eigen::operator!= (const hypro::matrix_t< Number > & lhs, const hypro::matrix_t< Number > & rhs) inline
Definition at line 149 of file adaptions_eigen.h.
template<> bool Eigen::operator< (const hypro::vector_t< double > & lhs, const hypro::vector_t< double > & rhs) inline
Definition at line 7 of file adaptions_eigen_double.cpp.
template<typename Number > bool Eigen::operator< (const hypro::vector_t< Number > & lhs, const hypro::vector_t< Number > & rhs) inline
Definition at line 30 of file adaptions_eigen.h.
template<typename Number > std::ostream& Eigen::operator<< (std::ostream & _out, const hypro::vector_t< Number > & in) inline
Definition at line 154 of file adaptions_eigen.h.
template<typename Number > std::ostream& Eigen::operator<< (std::ostream & _out, const hypro::matrix_t< Number > & in) inline
Definition at line 162 of file adaptions_eigen.h.
template<> bool Eigen::operator<= (const hypro::vector_t< double > & lhs, const hypro::vector_t< double > & rhs) inline
Definition at line 23 of file adaptions_eigen_double.cpp.
template<typename Number > bool Eigen::operator<= (const hypro::vector_t< Number > & lhs, const hypro::vector_t< Number > & rhs) inline
Definition at line 47 of file adaptions_eigen.h.
template<> bool Eigen::operator== (const hypro::vector_t< double > & lhs, const hypro::vector_t< double > & rhs) inline
Definition at line 49 of file adaptions_eigen_double.cpp.
References default_double_comparison_ulps.
template<> bool Eigen::operator== (const hypro::matrix_t< double > & lhs, const hypro::matrix_t< double > & rhs) inline
Definition at line 69 of file adaptions_eigen_double.cpp.
References default_double_comparison_ulps.
template<typename Number > bool Eigen::operator== (const hypro::vector_t< Number > & lhs, const hypro::vector_t< Number > & rhs) inline
Definition at line 108 of file adaptions_eigen.h.
References VectorHashValue().
template<typename Number > bool Eigen::operator== (const hypro::matrix_t< Number > & lhs, const hypro::matrix_t< Number > & rhs) inline
Definition at line 130 of file adaptions_eigen.h.
References MatrixHashValue().
template<> bool Eigen::operator> (const hypro::vector_t< double > & lhs, const hypro::vector_t< double > & rhs) inline
Definition at line 39 of file adaptions_eigen_double.cpp.
template<typename Number > bool Eigen::operator> (const hypro::vector_t< Number > & lhs, const hypro::vector_t< Number > & rhs) inline
Definition at line 64 of file adaptions_eigen.h.
template<> bool Eigen::operator>= (const hypro::vector_t< double > & lhs, const hypro::vector_t< double > & rhs) inline
Definition at line 44 of file adaptions_eigen_double.cpp.
template<typename Number > bool Eigen::operator>= (const hypro::vector_t< Number > & lhs, const hypro::vector_t< Number > & rhs) inline
Definition at line 69 of file adaptions_eigen.h.
template<typename Number > std::size_t Eigen::VectorHashValue (const hypro::vector_t< Number > & pVector)
computes a hash chain over a vector nx1 using carl::hash_add and returns it
Parameters
pVector input vector
Returns
size_t hash seed
Definition at line 79 of file adaptions_eigen.h.
Referenced by std::hash< hypro::vector_t< Number > >::operator()(), and operator==().