HyPro: better_enums Namespace Reference
better_enums Namespace Reference
Classes
struct _eat_assign
struct _initialize_at_program_start
struct _iterable
struct map
struct map_compare
struct map_compare< const char * >
struct map_compare< const wchar_t * >
struct optional
Functions
template<typename T >
BETTER_ENUMS_CONSTEXPR_ T _default ()
template<>
BETTER_ENUMS_CONSTEXPR_ const char * _default< const char * > ()
template<>
BETTER_ENUMS_CONSTEXPR_ std::size_t _default< std::size_t > ()
BETTER_ENUMS_IF_EXCEPTIONS (template< typename T > BETTER_ENUMS_CONSTEXPR_ static T _or_throw(optional< T > maybe, const char *message){BETTER_ENUMS_OR_THROW}) template< typename T > BETTER_ENUMS_CONSTEXPR_ static T *_or_null(optional< T * > maybe)
template<typename T , typename U >
BETTER_ENUMS_CONSTEXPR_ U continue_with (T, U value)
BETTER_ENUMS_CONSTEXPR_ bool _ends_name (char c, std::size_t index=0)
BETTER_ENUMS_CONSTEXPR_ bool _has_initializer (const char *s, std::size_t index=0)
BETTER_ENUMS_CONSTEXPR_ std::size_t _constant_length (const char *s, std::size_t index=0)
BETTER_ENUMS_CONSTEXPR_ char _select (const char *from, std::size_t from_length, std::size_t index)
BETTER_ENUMS_CONSTEXPR_ char _to_lower_ascii (char c)
BETTER_ENUMS_CONSTEXPR_ bool _names_match (const char *stringizedName, const char *referenceName, std::size_t index=0)
BETTER_ENUMS_CONSTEXPR_ bool _names_match_nocase (const char *stringizedName, const char *referenceName, std::size_t index=0)
void _trim_names (const char *const *raw_names, const char **trimmed_names, char *storage, std::size_t count)
template<typename Enum , typename T >
BETTER_ENUMS_CONSTEXPR_ map< Enum, T > make_map (T(*f)(Enum))
Function Documentation
BETTER_ENUMS_CONSTEXPR_ std::size_t better_enums::_constant_length (const char * s, std::size_t index = 0) inline
Definition at line 408 of file enum.h.
References _ends_name().
template<typename T > BETTER_ENUMS_CONSTEXPR_ T better_enums::_default () inline
Definition at line 273 of file enum.h.
template<> BETTER_ENUMS_CONSTEXPR_ const char* better_enums::_default< const char * > () inline
Definition at line 278 of file enum.h.
template<> BETTER_ENUMS_CONSTEXPR_ std::size_t better_enums::_default< std::size_t > () inline
Definition at line 283 of file enum.h.
BETTER_ENUMS_CONSTEXPR_ bool better_enums::_ends_name (char c, std::size_t index = 0) inline
Definition at line 398 of file enum.h.
Referenced by _constant_length(), _names_match(), and _names_match_nocase().
BETTER_ENUMS_CONSTEXPR_ bool better_enums::_has_initializer (const char * s, std::size_t index = 0) inline
Definition at line 402 of file enum.h.
BETTER_ENUMS_CONSTEXPR_ bool better_enums::_names_match (const char * stringizedName, const char * referenceName, std::size_t index = 0) inline
Definition at line 421 of file enum.h.
References _ends_name().
BETTER_ENUMS_CONSTEXPR_ bool better_enums::_names_match_nocase (const char * stringizedName, const char * referenceName, std::size_t index = 0) inline
Definition at line 428 of file enum.h.
References _ends_name(), and _to_lower_ascii().
BETTER_ENUMS_CONSTEXPR_ char better_enums::_select (const char * from, std::size_t from_length, std::size_t index) inline
Definition at line 413 of file enum.h.
BETTER_ENUMS_CONSTEXPR_ char better_enums::_to_lower_ascii (char c) inline
Definition at line 417 of file enum.h.
Referenced by _names_match_nocase().
void better_enums::_trim_names (const char *const * raw_names, const char ** trimmed_names, char * storage, std::size_t count) inline
Definition at line 433 of file enum.h.
better_enums::BETTER_ENUMS_IF_EXCEPTIONS (template< typename T > BETTER_ENUMS_CONSTEXPR_ static T _or_throw(optional< T > maybe, const char *message){BETTER_ENUMS_OR_THROW})
Definition at line 330 of file enum.h.
template<typename T , typename U > BETTER_ENUMS_CONSTEXPR_ U better_enums::continue_with (T , U value)
Definition at line 353 of file enum.h.
References better_enums::optional< T >::value().
template<typename Enum , typename T > BETTER_ENUMS_CONSTEXPR_ map<Enum, T> better_enums::make_map (T(*)(Enum) f)
Definition at line 1086 of file enum.h.