HyPro: hypro::detail Namespace Reference
hypro::detail Namespace Reference
Classes
struct Dependent_part_funct
struct Eval_functions
struct Flags
struct Flowpipe_segment
struct gen_seq
struct gen_seq< 0, Is... >
struct Independent_part_funct
struct Input_equation
struct Invariants
struct nth_element_impl
struct nth_element_impl< 0, T, Ts... >
struct ResetVisitor
struct seq
Typedefs
typedef struct hypro::detail::Flags Flags
typedef struct hypro::detail::Input_equation In_eq
typedef struct hypro::detail::Invariants Invar
typedef struct hypro::detail::Independent_part_funct Ind_f
typedef struct hypro::detail::Dependent_part_funct Dep_f
typedef struct hypro::detail::Eval_functions Eval_f
typedef struct hypro::detail::Flowpipe_segment Flow_seg
Functions
template<class Result , class Func >
ResetVisitor< Result, std::decay_t< Func > > make_reset_visitor (Func &&func)
template<typename T >
auto getType (const T &)
template<typename Number >
CoinPackedMatrix createMatrix (const matrix_t< Number > &in)
Create a CoinPackedMatrix from a matrix_t-type. CoinPacketMatrices are implemented as sparse matrices, however we utilize dense matrices here.
template<typename T , typename F , int... Is>
auto for_each (T &&t, F f, seq< Is... >)
template<typename T , typename F , int... Is>
auto for_each (T &&t1, T &&t2, F f, seq< Is... >)
template<typename T , typename P , typename F , int... Is>
auto for_each (T &&t, P &&p, F f, seq< Is... >)
void declare_structures (const int n, In_eq &in_eq1, Invar &invar, Ind_f &ind_f, Dep_f &dep_f, Dep_f &in_traj, Eval_f &eval_f)
void mark_x0isMin (Matrix< Number > &x_tr, const int n)
void swap_x0isMax (Matrix< Number > &x_tr, const int n)
void initialize (Eval_f &eval_f, Flow_seg &safe_seg, Flow_seg &error_seg, std::size_t DIM_PLOT, bool ORIG_SYS_PLOT, const DiagonalMatrix< Number > &D, const int n, const Matrix< Number > &V, Dep_f &dep_f)
void loop (std::vector< VPoly > &flow, std::vector< VPoly > &error_flow, const Flags &flag1, const Ind_f &ind_f, const int n, const Matrix< Number > &V, Eval_f &eval_f, Dep_f &dep_f, Flow_seg &safe_seg, Flow_seg &error_seg)
Class Documentation
struct hypro::detail::Dependent_part_funct
Definition at line 48 of file example_eigenSimpleFlow.cpp.
Class Members
Matrix< Number > x_tr
Matrix< Number > xhom
struct hypro::detail::Eval_functions
Definition at line 55 of file example_eigenSimpleFlow.cpp.
Class Members
Matrix< Number > deriv
BoolMatrix direct
struct hypro::detail::Flags
Definition at line 16 of file example_eigenSimpleFlow.cpp.
Class Members
size_t DIM_PLOT
bool ERROR_PLOT
bool HULL_PLOT
bool HULLCONSTR
bool ORIG_SYS_PLOT
bool TRAJECTORY_PLOT
struct hypro::detail::Flowpipe_segment
Definition at line 59 of file example_eigenSimpleFlow.cpp.
Class Members
vector< Vector< Number > > lower
vector< Vector< Number > > upper
struct hypro::detail::gen_seq
template<int N, int... Is>
struct hypro::detail::gen_seq< N, Is >
Definition at line 14 of file for_each.h.
struct hypro::detail::Independent_part_funct
Definition at line 42 of file example_eigenSimpleFlow.cpp.
Class Members
DiagonalMatrix< Number > D
Number delta
size_t deltalimit
Matrix< Number > xinhom
struct hypro::detail::Input_equation
Definition at line 26 of file example_eigenSimpleFlow.cpp.
Class Members
Matrix< Number > A
Vector< Number > b
Vector< Number > x0
Vector< Number > x0_2
struct hypro::detail::Invariants
Definition at line 32 of file example_eigenSimpleFlow.cpp.
Class Members
Matrix< Number > iAV
Vector< Number > ib
struct hypro::detail::nth_element_impl
template<std::size_t I, typename T, typename... Ts>
struct hypro::detail::nth_element_impl< I, T, Ts >
Definition at line 7 of file nth_element.h.
Class Members
type
struct hypro::detail::nth_element_impl< 0, T, Ts... >
template<typename T, typename... Ts>
struct hypro::detail::nth_element_impl< 0, T, Ts... >
Definition at line 12 of file nth_element.h.
Class Members
typedef T type
struct hypro::detail::seq
template<int... Is>
struct hypro::detail::seq< Is >
Definition at line 11 of file for_each.h.
Typedef Documentation
typedef struct hypro::detail::Dependent_part_funct hypro::detail::Dep_f
typedef struct hypro::detail::Eval_functions hypro::detail::Eval_f
typedef struct hypro::detail::Flags hypro::detail::Flags
typedef struct hypro::detail::Flowpipe_segment hypro::detail::Flow_seg
typedef struct hypro::detail::Input_equation hypro::detail::In_eq
typedef struct hypro::detail::Independent_part_funct hypro::detail::Ind_f
typedef struct hypro::detail::Invariants hypro::detail::Invar
Function Documentation
template<typename Number > CoinPackedMatrix hypro::detail::createMatrix (const matrix_t< Number > & in)
Create a CoinPackedMatrix from a matrix_t-type. CoinPacketMatrices are implemented as sparse matrices, however we utilize dense matrices here.
Template Parameters
Number
Parameters
in
Returns
CoinPackedMatrix
Definition at line 17 of file helperFunctions.h.
Referenced by hypro::clp_context::setMatrix().
void hypro::detail::declare_structures (const int n, In_eq & in_eq1, Invar & invar, Ind_f & ind_f, Dep_f & dep_f, Dep_f & in_traj, Eval_f & eval_f)
Definition at line 132 of file example_eigenSimpleFlow.cpp.
References hypro::detail::Input_equation::A, hypro::detail::Input_equation::b, hypro::detail::Independent_part_funct::D, hypro::detail::Eval_functions::deriv, hypro::detail::Eval_functions::direct, hypro::detail::Invariants::iAV, hypro::detail::Invariants::ib, hypro::detail::Input_equation::x0, hypro::detail::Input_equation::x0_2, hypro::detail::Dependent_part_funct::x_tr, hypro::detail::Dependent_part_funct::xhom, and hypro::detail::Independent_part_funct::xinhom.
Referenced by hypro::Transformation< Number >::Transformation().
template<typename T , typename F , int... Is> auto hypro::detail::for_each (T && t, F f, seq< Is... >)
Definition at line 20 of file for_each.h.
Referenced by hypro::constraintsToFormulas(), hypro::for_each_in_tuple(), hypro::for_each_in_tuple_pair(), hypro::CarlPolytopeT< Number, Converter, Setting >::getIntervals(), hypro::HybridAutomaton< Number >::getLabels(), hypro::TimingAggregate< N >::getOpenSuccessorCount(), hypro::Path< Number, tNumber >::Path(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::preparePlot(), and hypro::CarlPolytopeT< Number, Converter, Setting >::reduceRepresentation().
template<typename T , typename F , int... Is> auto hypro::detail::for_each (T && t1, T && t2, F f, seq< Is... >)
Definition at line 25 of file for_each.h.
template<typename T , typename P , typename F , int... Is> auto hypro::detail::for_each (T && t, P && p, F f, seq< Is... >)
Definition at line 30 of file for_each.h.
template<typename T > auto hypro::detail::getType (const T &)
Definition at line 116 of file ResetTypes.h.
Referenced by hypro::FourierMotzkinQE< Number >::eliminateQuantifiers(), hypro::Leaf< Number, Converter, Setting, Representation >::print(), hypro::RootGrowNode< Number, Converter, Setting >::print(), and hypro::TrafoOp< Number, Converter, Setting >::TrafoOp().
void hypro::detail::initialize (Eval_f & eval_f, Flow_seg & safe_seg, Flow_seg & error_seg, std::size_t DIM_PLOT, bool ORIG_SYS_PLOT, const DiagonalMatrix< Number > & D, const int n, const Matrix< Number > & V, Dep_f & dep_f)
Definition at line 180 of file example_eigenSimpleFlow.cpp.
References hypro::detail::Eval_functions::deriv, hypro::detail::Eval_functions::direct, swap_x0isMax(), hypro::detail::Dependent_part_funct::x_tr, and hypro::detail::Dependent_part_funct::xhom.
Referenced by better_enums::_initialize_at_program_start< Enum >::_initialize_at_program_start(), and hypro::HierarchicalIntervalVector< CONTAINMENT, tNumber >::~HierarchicalIntervalVector().
void hypro::detail::loop (std::vector< VPoly > & flow, std::vector< VPoly > & error_flow, const Flags & flag1, const Ind_f & ind_f, const int n, const Matrix< Number > & V, Eval_f & eval_f, Dep_f & dep_f, Flow_seg & safe_seg, Flow_seg & error_seg)
Definition at line 245 of file example_eigenSimpleFlow.cpp.
References hypro::plotting::blue, hypro::plotting::colors, hypro::detail::Independent_part_funct::D, hypro::detail::Independent_part_funct::delta, hypro::detail::Independent_part_funct::deltalimit, hypro::detail::Eval_functions::deriv, hypro::detail::Flags::DIM_PLOT, hypro::detail::Eval_functions::direct, hypro::detail::Flags::ERROR_PLOT, hypro::detail::Flags::HULL_PLOT, hypro::detail::Flags::ORIG_SYS_PLOT, hypro::plotting::red, swap_x0isMax(), hypro::detail::Dependent_part_funct::x_tr, hypro::detail::Dependent_part_funct::xhom, and hypro::detail::Independent_part_funct::xinhom.
template<class Result , class Func > ResetVisitor<Result, std::decay_t<Func> > hypro::detail::make_reset_visitor (Func && func)
Definition at line 28 of file Reset.h.
void hypro::detail::mark_x0isMin (Matrix< Number > & x_tr, const int n)
Definition at line 152 of file example_eigenSimpleFlow.cpp.
void hypro::detail::swap_x0isMax (Matrix< Number > & x_tr, const int n)
Definition at line 160 of file example_eigenSimpleFlow.cpp.
Referenced by initialize(), and loop().