HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/handles/ObjectHandle.h File Reference
ObjectHandle.h File Reference
Classes
class ObjectHandle
Functions
template<typename T >
void vector2Matlab (const std::vector< T > &vec, mxArray *m_out)
template<typename T >
void vector2Matlab (const std::vector< T > &vec, mxArray *m_out_1, mxArray *m_out_2)
template<typename T >
void pair2Matlab (const std::pair< T, T > p, mxArray *m_out, const int rows, const int cols)
template<typename T >
void objArray2Matlab (const std::vector< T > &vec, mxArray *m_array, const int len)
Function Documentation
template<typename T > void objArray2Matlab (const std::vector< T > & vec, mxArray * m_array, const int len)
Definition at line 158 of file ObjectHandle.h.
References i.
template<typename T > void pair2Matlab (const std::pair< T, T > p, mxArray * m_out, const int rows, const int cols)
Definition at line 129 of file ObjectHandle.h.
References ObjectHandle::convert2Matlab().
template<typename T > void vector2Matlab (const std::vector< T > & vec, mxArray * m_out)
Definition at line 94 of file ObjectHandle.h.
References cols, ObjectHandle::convert2Matlab(), dims, i, and out.
template<typename T > void vector2Matlab (const std::vector< T > & vec, mxArray * m_out_1, mxArray * m_out_2)
Definition at line 112 of file ObjectHandle.h.
References cols, ObjectHandle::convert2Matlab(), dims, and i.