HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/CORA_benchmarks/runCORABenchmarks.m File Reference
runCORABenchmarks.m File Reference
Variables
function runCORABenchmarks(benchmark, diff, strategy)%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%With this file all benchmarks for cora can be run.%Input If this flag is set then the plots will be saved saveFig = 0
Path to the folder where the plots will be saved savePath = '/home/'
logs = {}
log_counter = 1
names
if benchmark
else filename = strcat(names{10},'_',num2str(diff))
Variable Documentation
elseif benchmark
Initial value:
== 1
        filename = strcat(names{1},'_',num2str(diff))
Definition at line 43 of file runCORABenchmarks.m.
else filename = strcat(names{10},'_',num2str(diff))
Definition at line 80 of file runCORABenchmarks.m.
Referenced by main(), hypro::parseFlowstarFile< double >(), and hypro::parseFlowstarFile< mpq_class >().
log_counter = 1
Definition at line 35 of file runCORABenchmarks.m.
logs = {}
Definition at line 34 of file runCORABenchmarks.m.
names
Initial value:
= {'cora_bouncing_ball','cora_cruise_control',...
    'cora_oscillator_4','cora_oscillator_8','cora_oscillator_16',...
    'cora_switching_system','cora_rendezvous', 'cora_rod_reactor' ,'cora_two_tanks',...
    'cora_vehicle_platoon'}
Definition at line 36 of file runCORABenchmarks.m.
function runCORABenchmarks (benchmark, diff, strategy) %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% % With this file all benchmarks for cora can be run. % Input If this flag is set then the plots will be saved saveFig = 0
Definition at line 29 of file runCORABenchmarks.m.
Path to the folder where the plots will be saved savePath = '/home/'
Definition at line 32 of file runCORABenchmarks.m.