HyPro: /home/travis/build/hypro/hypro/src/hypro/CMakeLists.txt File Reference
/home/travis/build/hypro/hypro/src/hypro/CMakeLists.txt File Reference
Functions
configure_file (${CMAKE_CURRENT_SOURCE_DIR}/flags.h.in ${CMAKE_CURRENT_SOURCE_DIR}/flags.h @ONLY) file(GLOB_RECURSE sources RELATIVE $
*cpp message (STATUS"sources before filtering: ${sources}") list(FILTER sources EXCLUDE REGEX MHyPro.cpp|MReach.cpp|CompareMHyProAndCORA/example_box.cpp|CompareMHyProAndCORA/example_zonotope.cpp) message(STATUS"sources after filtering
add_library (${PROJECT_NAME}-objects OBJECT ${sources}) add_dependencies($
objects resources target_include_dirs_from (${PROJECT_NAME}-objects SYSTEM PUBLIC EIGEN3 COCOA_SHARED Boost_SHARED Boost_program_options_SHARED carl-shared GMP_SHARED GMPXX_SHARED GLPK_STATIC ANTLR4_SHARED clp_STATIC coinUtils_STATIC) target_include_directories($
Function Documentation
add_library (${PROJECT_NAME}-objects OBJECT ${sources})
Definition at line 13 of file CMakeLists.txt.
configure_file (${CMAKE_CURRENT_SOURCE_DIR}/flags.h.in ${CMAKE_CURRENT_SOURCE_DIR}/flags.h @)
Definition at line 3 of file CMakeLists.txt.
References file(), matlab, and out.
* cpp message (STATUS"sources before filtering: ${sources}")
Definition at line 9 of file CMakeLists.txt.
Referenced by hypro::ErrorListener::syntaxError().
objects resources target_include_dirs_from (${PROJECT_NAME}-objects SYSTEM PUBLIC EIGEN3 COCOA_SHARED Boost_SHARED Boost_program_options_SHARED carl-shared GMP_SHARED GMPXX_SHARED GLPK_STATIC ANTLR4_SHARED clp_STATIC)
Definition at line 15 of file CMakeLists.txt.
References min().