HyPro: hypro::clp_context Struct Reference
hypro::clp_context Struct Reference
#include <clp_context.h>
Public Member Functions
bool operator== (const clp_context &rhs)
void createArrays (unsigned)
void deleteArrays ()
void createLPInstance ()
void deleteLPInstance ()
~clp_context ()
template<typename Number >
void setMatrix (const matrix_t< Number > &constraints, const vector_t< Number > &constants, const std::vector< carl::Relation > &relations)
template<typename Number >
void updateConstraints (const matrix_t< Number > &constraints, const vector_t< Number > &constants, const std::vector< carl::Relation > &relations, bool maximize)
Public Attributes
ClpSimplex lp
CoinPackedMatrix matrix
double * mUpperBounds
double * mLowerBounds
bool arraysCreated = false
bool mInitialized = false
bool mConstraintsSet = false
Detailed Description
Definition at line 12 of file clp_context.h.
Constructor & Destructor Documentation
hypro::clp_context::~clp_context () inline
Definition at line 37 of file clp_context.h.
Member Function Documentation
void hypro::clp_context::createArrays (unsigned) inline
Definition at line 25 of file clp_context.h.
void hypro::clp_context::createLPInstance () inline
Definition at line 31 of file clp_context.h.
void hypro::clp_context::deleteArrays () inline
Definition at line 28 of file clp_context.h.
void hypro::clp_context::deleteLPInstance () inline
Definition at line 34 of file clp_context.h.
bool hypro::clp_context::operator== (const clp_context & rhs) inline
Definition at line 21 of file clp_context.h.
template<typename Number > void hypro::clp_context::setMatrix (const matrix_t< Number > & constraints, const vector_t< Number > & constants, const std::vector< carl::Relation > & relations) inline
Definition at line 41 of file clp_context.h.
References assert(), hypro::detail::createMatrix(), and i.
Referenced by updateConstraints().
template<typename Number > void hypro::clp_context::updateConstraints (const matrix_t< Number > & constraints, const vector_t< Number > & constants, const std::vector< carl::Relation > & relations, bool maximize) inline
Definition at line 72 of file clp_context.h.
References assert(), and setMatrix().
Member Data Documentation
bool hypro::clp_context::arraysCreated = false
Definition at line 17 of file clp_context.h.
ClpSimplex hypro::clp_context::lp
Definition at line 13 of file clp_context.h.
CoinPackedMatrix hypro::clp_context::matrix
Definition at line 14 of file clp_context.h.
bool hypro::clp_context::mConstraintsSet = false mutable
Definition at line 19 of file clp_context.h.
bool hypro::clp_context::mInitialized = false mutable
Definition at line 18 of file clp_context.h.
double* hypro::clp_context::mLowerBounds
Definition at line 16 of file clp_context.h.
double* hypro::clp_context::mUpperBounds
Definition at line 15 of file clp_context.h.
The documentation for this struct was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/util/linearOptimization/clp/clp_context.h