HyPro: hypro::nodeUpdater< State > Struct Template Reference
hypro::nodeUpdater< State > Struct Template Reference
#include <util.h>
Public Member Functions
nodeUpdater (const std::shared_ptr< Task< State >> &currentTask, WorkQueue< std::shared_ptr< Task< State >>> *localQueue, WorkQueue< std::shared_ptr< Task< State >>> *localCEXQueue, std::size_t targetLevel)
void createAndRaiseRefinementTask (typename ReachTreeNode< State >::Node_t node, typename ReachTreeNode< State >::Node_t update)
void createAndRaiseTask (typename ReachTreeNode< State >::Node_t node, typename ReachTreeNode< State >::Node_t update)
void operator() (typename ReachTreeNode< State >::NodeList_t &toMatch, typename ReachTreeNode< State >::NodeList_t &reference, Transition< typename State::NumberType > *transition)
Private Attributes
const std::shared_ptr< Task< State > > & mTask
WorkQueue< std::shared_ptr< Task< State > > > * mLocalQueue
WorkQueue< std::shared_ptr< Task< State > > > * mLocalCEXQueue
std::size_t mTargetLevel
Detailed Description
template<typename State>
struct hypro::nodeUpdater< State >
Definition at line 65 of file util.h.
Constructor & Destructor Documentation
template<typename State > hypro::nodeUpdater< State >::nodeUpdater (const std::shared_ptr< Task< State >> & currentTask, WorkQueue< std::shared_ptr< Task< State >>> * localQueue, WorkQueue< std::shared_ptr< Task< State >>> * localCEXQueue, std::size_t targetLevel) inline
Definition at line 66 of file util.h.
Member Function Documentation
template<typename State > void hypro::nodeUpdater< State >::createAndRaiseRefinementTask (typename ReachTreeNode< State >::Node_t node, typename ReachTreeNode< State >::Node_t update) inline
Definition at line 72 of file util.h.
References assert(), hypro::ReachTreeNode< State >::getRefinements(), hypro::SettingsProvider< State >::getStrategy(), i, hypro::nodeUpdater< State >::mLocalCEXQueue, hypro::nodeUpdater< State >::mTargetLevel, hypro::nodeUpdater< State >::mTask, hypro::ReachTreeNode< State >::rGetRefinements(), hypro::ReachTreeNode< State >::setNewRefinement(), and hypro::ReachTreeNode< State >::updateContent().
Referenced by hypro::nodeUpdater< State >::operator()().
template<typename State > void hypro::nodeUpdater< State >::createAndRaiseTask (typename ReachTreeNode< State >::Node_t node, typename ReachTreeNode< State >::Node_t update) inline
Definition at line 109 of file util.h.
References assert(), hypro::ReachTreeNode< State >::getRefinements(), hypro::SettingsProvider< State >::getStrategy(), i, hypro::nodeUpdater< State >::mLocalQueue, hypro::nodeUpdater< State >::mTargetLevel, hypro::ReachTreeNode< State >::rGetRefinements(), hypro::ReachTreeNode< State >::setNewRefinement(), and hypro::SettingsProvider< State >::useLocalTiming().
Referenced by hypro::nodeUpdater< State >::operator()().
template<typename State > void hypro::nodeUpdater< State >::operator() (typename ReachTreeNode< State >::NodeList_t & toMatch, typename ReachTreeNode< State >::NodeList_t & reference, Transition< typename State::NumberType > * transition) inline
Definition at line 151 of file util.h.
References assert(), hypro::nodeUpdater< State >::createAndRaiseRefinementTask(), hypro::nodeUpdater< State >::createAndRaiseTask(), and hypro::nodeUpdater< State >::mTask.
Member Data Documentation
template<typename State > WorkQueue<std::shared_ptr<Task<State> > >* hypro::nodeUpdater< State >::mLocalCEXQueue private
Definition at line 206 of file util.h.
Referenced by hypro::nodeUpdater< State >::createAndRaiseRefinementTask().
template<typename State > WorkQueue<std::shared_ptr<Task<State> > >* hypro::nodeUpdater< State >::mLocalQueue private
Definition at line 205 of file util.h.
Referenced by hypro::nodeUpdater< State >::createAndRaiseTask().
template<typename State > std::size_t hypro::nodeUpdater< State >::mTargetLevel private
Definition at line 207 of file util.h.
Referenced by hypro::nodeUpdater< State >::createAndRaiseRefinementTask(), and hypro::nodeUpdater< State >::createAndRaiseTask().
template<typename State > const std::shared_ptr<Task<State> >& hypro::nodeUpdater< State >::mTask private
Definition at line 204 of file util.h.
Referenced by hypro::nodeUpdater< State >::createAndRaiseRefinementTask(), and hypro::nodeUpdater< State >::operator()().
The documentation for this struct was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/algorithms/reachability/handlers/jumpHandlers/util.h