HyPro: hypro::RefinementSetting< State > Struct Template Reference
hypro::RefinementSetting< State > Struct Template Reference
#include <ReachTreeNode.h>
Public Types
using Number = typename State::NumberType
Public Member Functions
RefinementSetting ()=default
RefinementSetting (const RefinementSetting< State > &orig)=default
RefinementSetting (RefinementSetting< State > &&orig)=default
RefinementSetting (const Location< Number > *loc)
RefinementSetting (const State &state)
RefinementSetting (const State &set, const Location< Number > *)
RefinementSetting & operator= (const RefinementSetting &original)=default
Public Attributes
State initialSet
EventTimingContainer< Number > mTimings
carl::Interval< tNumber > entryTimestamp = carl::Interval<tNumber>::emptyInterval()
bool fullyComputed = false
bool isDummy = true
bool isEmpty = false
bool hitBadStates = false
Friends
std::ostream & operator<< (std::ostream &out, const RefinementSetting &in)
bool operator== (const RefinementSetting &lhs, const RefinementSetting &rhs)
bool operator!= (const RefinementSetting &lhs, const RefinementSetting &rhs)
Detailed Description
template<typename State>
struct hypro::RefinementSetting< State >
Definition at line 30 of file ReachTreeNode.h.
Member Typedef Documentation
template<typename State> using hypro::RefinementSetting< State >::Number = typename State::NumberType
Definition at line 31 of file ReachTreeNode.h.
Constructor & Destructor Documentation
template<typename State> hypro::RefinementSetting< State >::RefinementSetting () default
denotes that this setup lead to an intersection with the bad states. Currently only used for tree plotting.
template<typename State> hypro::RefinementSetting< State >::RefinementSetting (const RefinementSetting< State > & orig) default
template<typename State> hypro::RefinementSetting< State >::RefinementSetting (RefinementSetting< State > && orig) default
template<typename State> hypro::RefinementSetting< State >::RefinementSetting (const Location< Number > * loc) inline explicit
Definition at line 48 of file ReachTreeNode.h.
template<typename State> hypro::RefinementSetting< State >::RefinementSetting (const State & state) inline explicit
Definition at line 55 of file ReachTreeNode.h.
template<typename State> hypro::RefinementSetting< State >::RefinementSetting (const State & set, const Location< Number > *) inline
Definition at line 62 of file ReachTreeNode.h.
References hypro::RefinementSetting< State >::operator=().
Member Function Documentation
template<typename State> RefinementSetting& hypro::RefinementSetting< State >::operator= (const RefinementSetting< State > & original) default
Referenced by hypro::RefinementSetting< State >::RefinementSetting().
Friends And Related Function Documentation
template<typename State> bool operator!= (const RefinementSetting< State > & lhs, const RefinementSetting< State > & rhs) friend
Definition at line 105 of file ReachTreeNode.h.
template<typename State> std::ostream& operator<< (std::ostream & out, const RefinementSetting< State > & in) friend
Definition at line 83 of file ReachTreeNode.h.
template<typename State> bool operator== (const RefinementSetting< State > & lhs, const RefinementSetting< State > & rhs) friend
Definition at line 92 of file ReachTreeNode.h.
Referenced by hypro::ReachTreeNode< State >::addTimeStepToPath().
Member Data Documentation
template<typename State> carl::Interval<tNumber> hypro::RefinementSetting< State >::entryTimestamp = carl::Interval<tNumber>::emptyInterval()
Definition at line 36 of file ReachTreeNode.h.
template<typename State> bool hypro::RefinementSetting< State >::fullyComputed = false
Definition at line 37 of file ReachTreeNode.h.
template<typename State> bool hypro::RefinementSetting< State >::hitBadStates = false
Definition at line 41 of file ReachTreeNode.h.
template<typename State> State hypro::RefinementSetting< State >::initialSet
Definition at line 33 of file ReachTreeNode.h.
template<typename State> bool hypro::RefinementSetting< State >::isDummy = true
Definition at line 38 of file ReachTreeNode.h.
template<typename State> bool hypro::RefinementSetting< State >::isEmpty = false
Definition at line 40 of file ReachTreeNode.h.
template<typename State> EventTimingContainer<Number> hypro::RefinementSetting< State >::mTimings
Definition at line 35 of file ReachTreeNode.h.
The documentation for this struct was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/ReachTreeNode.h