HyPro: hypro::glpk_context Struct Reference
hypro::glpk_context Struct Reference
Public Member Functions
glpk_context ()
glpk_context (const glpk_context &orig)
glpk_context (glpk_context &&orig)=delete
glpk_context & operator= (const glpk_context &orig)
glpk_context & operator= (glpk_context &&orig)=delete
bool operator== (const glpk_context &rhs)
void createArrays (unsigned size)
void deleteArrays ()
void createLPInstance ()
void deleteLPInstance ()
template<typename Number >
void updateConstraints (const matrix_t< Number > &constraints, const vector_t< Number > &constants, const std::vector< carl::Relation > &relations, bool maximize)
~glpk_context ()
Public Attributes
glp_prob * lp = nullptr
glp_smcp parm
int * ia = nullptr
int * ja = nullptr
double * ar = nullptr
bool arraysCreated = false
bool mInitialized = false
bool mConstraintsSet = false
Detailed Description
Definition at line 8 of file glpk_context.h.
Constructor & Destructor Documentation
hypro::glpk_context::glpk_context () inline
Definition at line 18 of file glpk_context.h.
Referenced by glpk_context().
hypro::glpk_context::glpk_context (const glpk_context & orig) inline
Definition at line 30 of file glpk_context.h.
References glpk_context(), lp, mInitialized, and parm.
hypro::glpk_context::glpk_context (glpk_context && orig) delete
hypro::glpk_context::~glpk_context () inline
Definition at line 199 of file glpk_context.h.
References deleteArrays().
Member Function Documentation
void hypro::glpk_context::createArrays (unsigned size) inline
Definition at line 73 of file glpk_context.h.
References deleteArrays().
Referenced by updateConstraints().
void hypro::glpk_context::createLPInstance () inline
Definition at line 97 of file glpk_context.h.
Referenced by updateConstraints().
void hypro::glpk_context::deleteArrays () inline
Definition at line 84 of file glpk_context.h.
References ar, ia, and ja.
Referenced by createArrays(), operator=(), updateConstraints(), and ~glpk_context().
void hypro::glpk_context::deleteLPInstance () inline
Definition at line 110 of file glpk_context.h.
Referenced by operator=(), and updateConstraints().
glpk_context& hypro::glpk_context::operator= (const glpk_context & orig) inline
Definition at line 46 of file glpk_context.h.
References deleteArrays(), deleteLPInstance(), lp, mInitialized, and parm.
glpk_context& hypro::glpk_context::operator= (glpk_context && orig) delete
bool hypro::glpk_context::operator== (const glpk_context & rhs) inline
Definition at line 69 of file glpk_context.h.
References lp.
template<typename Number > void hypro::glpk_context::updateConstraints (const matrix_t< Number > & constraints, const vector_t< Number > & constants, const std::vector< carl::Relation > & relations, bool maximize) inline
Definition at line 125 of file glpk_context.h.
References createArrays(), createLPInstance(), deleteArrays(), and deleteLPInstance().
Member Data Documentation
double* hypro::glpk_context::ar = nullptr
Definition at line 13 of file glpk_context.h.
Referenced by deleteArrays().
bool hypro::glpk_context::arraysCreated = false
Definition at line 14 of file glpk_context.h.
int* hypro::glpk_context::ia = nullptr
Definition at line 11 of file glpk_context.h.
Referenced by deleteArrays().
int* hypro::glpk_context::ja = nullptr
Definition at line 12 of file glpk_context.h.
Referenced by deleteArrays().
glp_prob* hypro::glpk_context::lp = nullptr
Definition at line 9 of file glpk_context.h.
Referenced by glpk_context(), hypro::glpkCheckPoint(), hypro::glpkGetInternalPoint(), hypro::glpkOptimizeLinear(), hypro::glpkRedundantConstraints(), operator=(), operator==(), and hypro::refineSolution().
bool hypro::glpk_context::mConstraintsSet = false mutable
Definition at line 16 of file glpk_context.h.
bool hypro::glpk_context::mInitialized = false mutable
Definition at line 15 of file glpk_context.h.
Referenced by glpk_context(), and operator=().
glp_smcp hypro::glpk_context::parm
Definition at line 10 of file glpk_context.h.
Referenced by glpk_context(), hypro::glpkCheckPoint(), hypro::glpkGetInternalPoint(), hypro::glpkOptimizeLinear(), hypro::glpkRedundantConstraints(), and operator=().
The documentation for this struct was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/util/linearOptimization/glpk_context.h