HyPro: hypro::ExactQuickhull::Facet< Number, Euclidian > Struct Template Reference
hypro::ExactQuickhull::Facet< Number, Euclidian > Struct Template Reference
Public Member Functions
Facet ()=default
void invert ()
void setOrientation (point_t const &containedPoint, Facet const &adjacentFacet)
Number distance (point_t const &point) const
bool visible (point_t const &vertex) const
size_t findNeighborIndex (facet_ind_t facet_i)
Public Attributes
std::vector< point_ind_t > mVertices
std::vector< facet_ind_t > mNeighbors
std::vector< point_ind_t > mOutsideSet
point_t mNormal
point_ind_t furthestPoint
Number furthestPointDistance = Number(0)
Number mOffset = Number(1000)
Detailed Description
template<typename Number, bool Euclidian>
struct hypro::ExactQuickhull::Facet< Number, Euclidian >
Definition at line 7 of file Facet.h.
Constructor & Destructor Documentation
template<typename Number , bool Euclidian> hypro::ExactQuickhull::Facet< Number, Euclidian >::Facet () default
Member Function Documentation
template<typename Number , bool Euclidian> Number hypro::ExactQuickhull::Facet< Number, Euclidian >::distance (point_t const & point) const
Definition at line 30 of file Facet.tpp.
Referenced by hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::tryAddToOutsideSet().
template<typename Number , bool Euclidian> size_t hypro::ExactQuickhull::Facet< Number, Euclidian >::findNeighborIndex (facet_ind_t facet_i)
Definition at line 46 of file Facet.tpp.
References hypro::unreachable().
template<typename Number , bool Euclidian> void hypro::ExactQuickhull::Facet< Number, Euclidian >::invert ()
Definition at line 10 of file Facet.tpp.
Referenced by hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::containsAllPoints().
template<typename Number , bool Euclidian> void hypro::ExactQuickhull::Facet< Number, Euclidian >::setOrientation (point_t const & containedPoint, Facet< Number, Euclidian > const & adjacentFacet)
Definition at line 16 of file Facet.tpp.
References hypro::ExactQuickhull::Facet< Number, Euclidian >::mNormal, and hypro::ExactQuickhull::Facet< Number, Euclidian >::mOffset.
Referenced by hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::validateFacet().
template<typename Number , bool Euclidian> bool hypro::ExactQuickhull::Facet< Number, Euclidian >::visible (point_t const & vertex) const
Definition at line 41 of file Facet.tpp.
Referenced by hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::containsAllPoints(), and hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::containsVertices().
Member Data Documentation
template<typename Number , bool Euclidian> point_ind_t hypro::ExactQuickhull::Facet< Number, Euclidian >::furthestPoint
Definition at line 24 of file Facet.h.
Referenced by hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::tryAddToOutsideSet().
template<typename Number , bool Euclidian> Number hypro::ExactQuickhull::Facet< Number, Euclidian >::furthestPointDistance = Number(0)
Definition at line 25 of file Facet.h.
Referenced by hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::tryAddToOutsideSet().
template<typename Number , bool Euclidian> std::vector<facet_ind_t> hypro::ExactQuickhull::Facet< Number, Euclidian >::mNeighbors
Definition at line 21 of file Facet.h.
Referenced by hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::containsVertices(), and hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::establishNeighborhood().
template<typename Number , bool Euclidian> point_t hypro::ExactQuickhull::Facet< Number, Euclidian >::mNormal
Definition at line 23 of file Facet.h.
Referenced by hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::computeNormal(), hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::insertReduced(), hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::printFacet(), hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::removeCoplanarFacets(), and hypro::ExactQuickhull::Facet< Number, Euclidian >::setOrientation().
template<typename Number , bool Euclidian> Number hypro::ExactQuickhull::Facet< Number, Euclidian >::mOffset = Number(1000)
Definition at line 26 of file Facet.h.
Referenced by hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::computeNormal(), hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::insertReduced(), hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::printFacet(), hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::removeCoplanarFacets(), and hypro::ExactQuickhull::Facet< Number, Euclidian >::setOrientation().
template<typename Number , bool Euclidian> std::vector<point_ind_t> hypro::ExactQuickhull::Facet< Number, Euclidian >::mOutsideSet
Definition at line 22 of file Facet.h.
Referenced by hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::containsAllPoints(), and hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::tryAddToOutsideSet().
template<typename Number , bool Euclidian> std::vector<point_ind_t> hypro::ExactQuickhull::Facet< Number, Euclidian >::mVertices
Definition at line 20 of file Facet.h.
Referenced by hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::computeNormal(), hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::containsVertices(), hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::establishNeighborhood(), and hypro::ExactQuickhull::FacetSpace< Number, Euclidian >::insertReduced().
The documentation for this struct was generated from the following files:
/home/travis/build/hypro/hypro/src/hypro/algorithms/quickhull/quickhull_exact/Facet.h
/home/travis/build/hypro/hypro/src/hypro/algorithms/quickhull/quickhull_exact/Facet.tpp