HyPro: hypro::Decomposition Struct Reference
hypro::Decomposition Struct Reference
Public Member Functions
std::size_t size () const
void push_back (const std::vector< std::size_t > &decomp)
const std::vector< std::size_t > & at (std::size_t pos) const
std::vector< std::vector< std::size_t > >::iterator begin ()
std::vector< std::vector< std::size_t > >::const_iterator begin () const
std::vector< std::vector< std::size_t > >::iterator end ()
std::vector< std::vector< std::size_t > >::const_iterator end () const
Public Attributes
std::vector< std::vector< std::size_t > > mDecomposition
Detailed Description
Definition at line 6 of file Decomposition.h.
Member Function Documentation
const std::vector<std::size_t>& hypro::Decomposition::at (std::size_t pos) const inline
Definition at line 12 of file Decomposition.h.
Referenced by hypro::rectangularGuardHandler< State >::rectangularGuardHandler(), and hypro::timedGuardHandler< State >::timedGuardHandler().
std::vector<std::vector<std::size_t> >::iterator hypro::Decomposition::begin () inline
Definition at line 14 of file Decomposition.h.
std::vector<std::vector<std::size_t> >::const_iterator hypro::Decomposition::begin () const inline
Definition at line 15 of file Decomposition.h.
std::vector<std::vector<std::size_t> >::iterator hypro::Decomposition::end () inline
Definition at line 16 of file Decomposition.h.
std::vector<std::vector<std::size_t> >::const_iterator hypro::Decomposition::end () const inline
Definition at line 17 of file Decomposition.h.
void hypro::Decomposition::push_back (const std::vector< std::size_t > & decomp) inline
Definition at line 11 of file Decomposition.h.
Referenced by hypro::SettingsProvider< State >::computeLocationSubspaceTypeMapping().
std::size_t hypro::Decomposition::size () const inline
Definition at line 9 of file Decomposition.h.
Referenced by hypro::combine(), hypro::SettingsProvider< State >::computeLocationSubspaceTypeMapping(), and hypro::DecisionEntity< Number >::decomposeAutomaton().
Member Data Documentation
std::vector<std::vector<std::size_t> > hypro::Decomposition::mDecomposition
Definition at line 7 of file Decomposition.h.
Referenced by hypro::DecisionEntity< Number >::getSubspaceDecomposition().
The documentation for this struct was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/HybridAutomaton/decomposition/Decomposition.h