HyPro: hypro::LinTrafoParameters< Number, Setting > Struct Template Reference
hypro::LinTrafoParameters< Number, Setting > Struct Template Reference
Struct holding linear and affine transformation parameters.
Public Member Functions
LinTrafoParameters ()=delete
LinTrafoParameters (const matrix_t< Number > &_A, const vector_t< Number > &_b, unsigned _power=Setting::LIN_TRANS_REDUCTION_GROUP_SIZE)
~LinTrafoParameters ()
matrix_t< Number > matrix () const
vector_t< Number > vector () const
const std::pair< matrix_t< Number >, vector_t< Number > > & getParameterSet (unsigned exponent) const
vector_t< Number > getTransformedDirection (const vector_t< Number > &inDirection, unsigned exponent) const
matrix_t< Number > getTransformedDirections (const matrix_t< Number > &inDirections, unsigned exponent) const
void createNextReduct () const
bool operator== (const LinTrafoParameters< Number, Setting > &rhs) const
Public Attributes
std::map< unsigned, std::pair< matrix_t< Number >, vector_t< Number > > > parameters
unsigned power = Setting::LIN_TRANS_REDUCTION_GROUP_SIZE
Detailed Description
template<typename Number, typename Setting>
struct hypro::LinTrafoParameters< Number, Setting >
Struct holding linear and affine transformation parameters.
Template Parameters
Number The used number type.
Setting A SupportFunctionNew setting, given by the calling TrafoOp obj. Holds a map associating exponents n with the nth-timestep flow matrix A^n and vector b^n
Definition at line 14 of file LinTrafoParameters.h.
Constructor & Destructor Documentation
template<typename Number, typename Setting> hypro::LinTrafoParameters< Number, Setting >::LinTrafoParameters () delete
template<typename Number, typename Setting> hypro::LinTrafoParameters< Number, Setting >::LinTrafoParameters (const matrix_t< Number > & _A, const vector_t< Number > & _b, unsigned _power = Setting::LIN_TRANS_REDUCTION_GROUP_SIZE) inline
Definition at line 26 of file LinTrafoParameters.h.
template<typename Number, typename Setting> hypro::LinTrafoParameters< Number, Setting >::~LinTrafoParameters () inline
Definition at line 33 of file LinTrafoParameters.h.
Member Function Documentation
template<typename Number, typename Setting> void hypro::LinTrafoParameters< Number, Setting >::createNextReduct () const inline
Definition at line 70 of file LinTrafoParameters.h.
References hypro::LinTrafoParameters< Number, Setting >::power.
Referenced by hypro::LinTrafoParameters< Number, Setting >::getParameterSet().
template<typename Number, typename Setting> const std::pair<matrix_t<Number>, vector_t<Number> >& hypro::LinTrafoParameters< Number, Setting >::getParameterSet (unsigned exponent) const inline
Definition at line 49 of file LinTrafoParameters.h.
References hypro::LinTrafoParameters< Number, Setting >::createNextReduct().
Referenced by hypro::LinTrafoParameters< Number, Setting >::getTransformedDirection(), and hypro::LinTrafoParameters< Number, Setting >::getTransformedDirections().
template<typename Number, typename Setting> vector_t<Number> hypro::LinTrafoParameters< Number, Setting >::getTransformedDirection (const vector_t< Number > & inDirection, unsigned exponent) const inline
Definition at line 61 of file LinTrafoParameters.h.
References hypro::LinTrafoParameters< Number, Setting >::getParameterSet().
template<typename Number, typename Setting> matrix_t<Number> hypro::LinTrafoParameters< Number, Setting >::getTransformedDirections (const matrix_t< Number > & inDirections, unsigned exponent) const inline
Definition at line 66 of file LinTrafoParameters.h.
References hypro::LinTrafoParameters< Number, Setting >::getParameterSet().
template<typename Number, typename Setting> matrix_t<Number> hypro::LinTrafoParameters< Number, Setting >::matrix () const inline
Definition at line 39 of file LinTrafoParameters.h.
template<typename Number, typename Setting> bool hypro::LinTrafoParameters< Number, Setting >::operator== (const LinTrafoParameters< Number, Setting > & rhs) const inline
Definition at line 92 of file LinTrafoParameters.h.
References hypro::LinTrafoParameters< Number, Setting >::parameters.
template<typename Number, typename Setting> vector_t<Number> hypro::LinTrafoParameters< Number, Setting >::vector () const inline
Definition at line 44 of file LinTrafoParameters.h.
Member Data Documentation
template<typename Number, typename Setting> std::map<unsigned, std::pair<matrix_t<Number>, vector_t<Number> > > hypro::LinTrafoParameters< Number, Setting >::parameters mutable
Definition at line 17 of file LinTrafoParameters.h.
Referenced by hypro::LinTrafoParameters< Number, Setting >::operator==().
template<typename Number, typename Setting> unsigned hypro::LinTrafoParameters< Number, Setting >::power = Setting::LIN_TRANS_REDUCTION_GROUP_SIZE
Definition at line 18 of file LinTrafoParameters.h.
Referenced by hypro::LinTrafoParameters< Number, Setting >::createNextReduct().
The documentation for this struct was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/representations/SupportFunctionNew/LinTrafoParameters.h