HyPro: hypro::detail::strategyConversionVisitor< State > Struct Template Reference
hypro::detail::strategyConversionVisitor< State > Struct Template Reference
#include <StrategyNode.h>
Public Member Functions
strategyConversionVisitor ()=delete
strategyConversionVisitor (State &s, std::size_t subset=0)
template<typename Node >
void operator() (Node &) const
Public Attributes
State & mState
std::size_t mSubsetIndex
Detailed Description
template<typename State>
struct hypro::detail::strategyConversionVisitor< State >
Definition at line 30 of file StrategyNode.h.
Constructor & Destructor Documentation
template<typename State > hypro::detail::strategyConversionVisitor< State >::strategyConversionVisitor () delete
template<typename State > hypro::detail::strategyConversionVisitor< State >::strategyConversionVisitor (State & s, std::size_t subset = 0) inline
Definition at line 35 of file StrategyNode.h.
Member Function Documentation
template<typename State > template<typename Node > void hypro::detail::strategyConversionVisitor< State >::operator() (Node &) const inline
Definition at line 40 of file StrategyNode.h.
References hypro::State< Number, Representation, Rargs >::getSet(), hypro::State< Number, Representation, Rargs >::getSetType(), hypro::State< Number, Representation, Rargs >::setSet(), and TRACE.
Member Data Documentation
template<typename State > State& hypro::detail::strategyConversionVisitor< State >::mState
Definition at line 31 of file StrategyNode.h.
template<typename State > std::size_t hypro::detail::strategyConversionVisitor< State >::mSubsetIndex
Definition at line 32 of file StrategyNode.h.
The documentation for this struct was generated from the following file:
/home/travis/build/hypro/hypro/src/hypro/datastructures/reachability/StrategyNode.h