HyPro: /home/travis/build/hypro/hypro/src/hypro/util/matlab/CORA_benchmarks/verifySafetyPropertiesCORA.m File Reference
verifySafetyPropertiesCORA.m File Reference
Functions
parfor (row=1:size(spec, 1), M) for row
disp (['Checking:['num2str(spec(row,:)) ']<= 'num2str(rhs) '...'])
Check for validity if supremum (value) > rhs%Specification was violated
Check for validity if exit disp (['NOT SAFE-spec.no. 'num2str(row) 'violated following specification:['num2str(spec(row,:)) ']<= 'num2str(rhs)])
Variables
function out
spec = spec_matrix(:, 1:(s_mat_cols -1))
rhSides = spec_matrix(:, s_mat_cols)
tmp = true
tic
for i
rhs = rhSides(row)
vector = prepareValues(ReachableSet{i}{j}, s_mat_cols-1)
temp = matrix * vector
value = sum(temp)
results {row} = false
Function Documentation
disp (['Checking:['num2str(spec(row,:)) '] <= 'num2str(rhs) '...'])
Check for validity if exit disp (['NOT SAFE-spec.no. 'num2str(row) 'violated following specification:['num2str(spec(row,:)) '] <= 'num2str(rhs)])
parfor (row = 1:size(spec, 1), M)
Check for validity if supremum (value)
Variable Documentation
for i
Initial value:
=1:length(ReachableSet)
    for j = 1:length(ReachableSet{i})
        % Check every specification for current set
        % sliced var to store the result of parfor
        results = cell(size(spec,1),1)
Definition at line 30 of file verifySafetyPropertiesCORA.m.
function out
Initial value:
= verifySafetyProperties(spec_matrix, ReachableSet)
%--------------------------------------------------------------------------
% spec_matrix:  The rows of the matrix contain coefficients of a single
%               safety specification
%
% ReachableSet: Contains the reachable set computed by CORA (OT)
%
% example:      safety specification: x1 + 3 * x2 + 2 * x3 <= 5
%               spec_matrix: [1 3 2 5]
%
%               The last column of spec_matrix always contains the rhs.
%               Moreover, it is always assumed that the operator <= is used
%               for specifying safety properties. For multiple safety prop.
%               just add new row to the matrix
%
% notice:       Do not forget the variable order! -> For the following
%               variable order: x1, x2, x3 and the safety property
%               x3 + 3 * x1 <= 5 the spec_matrix has to have the form:
%               [3 0 1 5]
%--------------------------------------------------------------------------
[~, s_mat_cols] = size(spec_matrix)
Definition at line 1 of file verifySafetyPropertiesCORA.m.
results {row} = false
Definition at line 48 of file verifySafetyPropertiesCORA.m.
Referenced by main().
rhs = rhSides(row)
Definition at line 39 of file verifySafetyPropertiesCORA.m.
Referenced by hypro::Transition< N >::addLabel(), hypro::ReachTreeNode< State >::addTimeStepToPath(), hypro::SupportFunctionT< Number, Converter, Setting >::assignIntervals(), hypro::VPolytopeT< Number, Converter, S >::assignIntervals(), hypro::CarlPolytopeT< Number, Converter, Setting >::CarlPolytopeT(), CLANG_WARNING_DISABLE(), hypro::SupportFunctionNewT< Number, Converter, Setting >::Empty(), hypro::IntersectOp< Number, Converter, Setting >::IntersectOp(), hypro::IntervalAssignment< N >::IntervalAssignment(), hypro::HPolytopeT< Number, Converter, Setting >::isNonRedundant(), hypro::linearDependent(), hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::min(), Eigen::operator!=(), hypro::Path< Number, tNumber >::operator!=(), hypro::Location< N >::operator!=(), hypro::locPtrComp< Number >::operator()(), Eigen::operator<(), hypro::operator<(), Eigen::operator<=(), hypro::DifferenceBoundsT< Number, Converter, Setting >::DBMEntry::operator<=(), Eigen::operator==(), hypro::operator==(), hypro::OrthogonalPolyhedronT< Number, Converter, Setting, Type >::OrthogonalPolyhedronT(), hypro::ZonotopeT< Number, Converter, Setting >::removeRedundancy(), hypro::selectCols(), hypro::Location< N >::setInvariant(), hypro::HierarchicalIntervalVector< CONTAINMENT, tNumber >::setTypeOrder(), hypro::SumOp< Number, Converter, Setting >::SumOp(), hypro::DifferenceBoundsT< Number, Converter, Setting >::type(), hypro::UnionOp< Number, Converter, Setting >::UnionOp(), hypro::HybridAutomaton< Number >::~HybridAutomaton(), and hypro::Path< Number, tNumber >::~Path().
rhSides = spec_matrix(:, s_mat_cols)
Definition at line 26 of file verifySafetyPropertiesCORA.m.
spec = spec_matrix(:, 1:(s_mat_cols -1))
Definition at line 25 of file verifySafetyPropertiesCORA.m.
temp = matrix * vector
Definition at line 42 of file verifySafetyPropertiesCORA.m.
tic
Definition at line 29 of file verifySafetyPropertiesCORA.m.
tmp = true
Definition at line 27 of file verifySafetyPropertiesCORA.m.
Referenced by CLANG_WARNING_DISABLE(), hypro::SupportFunctionContent< Number, Setting >::collectLevelEntries(), hypro::computeHalfspaces(), hypro::BoxT< Number, hypro::Converter, Setting >::Empty(), hypro::errorBoxes(), hypro::DAGNode< EventTimingNode< Number > >::getAvgSubtreeBranching(), hypro::TreeNode< ReachTreeNode< State > >::getAvgSubtreeBranching(), hypro::TreeNode< ReachTreeNode< State > >::getSubtreeDepth(), hypro::LinTrafoParameters< Number, Setting >::getTransformedDirection(), hypro::lintrafoParameters< Number >::getTransformedDirection(), hypro::SupportFunctionContent< Number, Setting >::hasTrafo(), hypro::hausdorffError(), hypro::insertAndCreateTask(), hypro::VertexContainer< Number >::linearTransformation(), main(), hypro::VertexContainer< Number >::move(), hypro::Permutator::operator()(), hypro::genericMinkowskiSumVisitor< T >::operator()(), hypro::reachability::detail::bloatBoxVisitor< VariantType, Number >::operator()(), hypro::genericConversionVisitor< T, To >::operator()(), hypro::genericInternalConversionVisitor< T, Ext >::operator()(), hypro::genericConvertAndGetVisitor< OutType >::operator()(), hypro::operator-(), hypro::ReachTreeNode< State >::ReachTreeNode(), hypro::HPolytopeT< Number, Converter, Setting >::reduceNumberRepresentation(), hypro::TrafoOp< Number, Converter, Setting >::reverseOp(), hypro::sample(), sandwichValue(), hypro::Flowpipe< Number >::selectSatisfyingStates(), MReach::setSettings(), hypro::ProjectOp< Number, Converter, Setting >::supremumPoint(), swap_x0isMax(), hypro::toFlowstarFormat(), and hypro::z3OptimizeLinear().
value = sum(temp)
Definition at line 43 of file verifySafetyPropertiesCORA.m.
vector = prepareValues(ReachableSet{i}{j}, s_mat_cols-1)
Definition at line 41 of file verifySafetyPropertiesCORA.m.