
if(STATICLIB_SWITCH)
	export_target(DEPENDENT_TARGETS carl_STATIC)
	export_target(DEPENDENT_TARGETS GLPK_STATIC)
	if (HYPRO_USE_Z3)
		export_target(DEPENDENT_TARGETS z3_STATIC)
	endif ()
	if(HYPRO_USE_SMTRAT)
	    export_target(DEPENDENT_TARGETS smtrat_STATIC)
	endif()
else()
	export_target(DEPENDENT_TARGETS carl_SHARED)
	#export_target(DEPENDENT_TARGETS GLPK_SHARED)
	if (HYPRO_USE_Z3)
		export_target(DEPENDENT_TARGETS z3_SHARED)
	endif ()
	if(HYPRO_USE_SMTRAT)
	    export_target(DEPENDENT_TARGETS smtrat_SHARED)
	endif()
endif()
export_target(DEPENDENT_TARGETS EIGEN3)
#export_target(DEPENDENT_TARGETS GMP_SHARED)
#export_target(DEPENDENT_TARGETS GMP_STATIC)
#export_target(DEPENDENT_TARGETS GMPXX_SHARED)
#export_target(DEPENDENT_TARGETS GMPXX_STATIC GMP_STATIC)
